// Chip definitions block 17
// Chips: 74x242-74x264

export const CHIPS_BLOCK_17 = {

  // ── 74242: Quad Bus Transceiver, Inverting ──────────────────────────────
  /* Primary source: Texas Instruments, SN74LS242 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls242.pdf
     Wikipedia: https://en.wikipedia.org/wiki/Three-state_logic
     Wikipedia: https://en.wikipedia.org/wiki/Bus_transceiver */
  '74242': {
    name: '74x242',
    simpleName: '4 bit Inv Transceiver',
    description: 'Quad inverting tri-state bus transceiver (14-pin)',
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls242.pdf',
    tags: ['transceiver', 'bus', 'inverting', '4 bit', 'tri-state'],
    guideOverview: 'The 74x242 is a quad (4-channel) inverting bus transceiver. Each channel passes data in one of two directions while inverting the logic level. GABn (active LOW) enables the A-to-B direction; GBAn (active LOW) enables the B-to-A direction. Enabling both simultaneously causes bus contention and should be avoided. Inverting transceivers are useful when interfacing signals of opposite polarity or when the downstream bus requires active LOW signals.',
    guidePinDescriptions: {
      'A1':   'Bus A channel 1. Output when GBAn active; input when GABn active.',
      'B1':   'Bus B channel 1. Output when GABn active; input when GBAn active.',
      'GABn': 'Enable A→B direction (active LOW). When LOW, A inputs are inverted and driven onto B outputs.',
      'A2':   'Bus A channel 2.',
      'B2':   'Bus B channel 2.',
      'A3':   'Bus A channel 3.',
      'GND':  'Ground reference (pin 7).',
      'B3':   'Bus B channel 3.',
      'A4':   'Bus A channel 4.',
      'B4':   'Bus B channel 4.',
      'GBAn': 'Enable B→A direction (active LOW). When LOW, B inputs are inverted and driven onto A outputs.',
      'NC1':  'Not connected.',
      'NC2':  'Not connected.',
      'VCC':  'Positive supply (+5 V, pin 14).',
    },
    pinout: [
      { pin:  1, name: 'A1',   type: 'output' },
      { pin:  2, name: 'B1',   type: 'output' },
      { pin:  3, name: 'GABn', type: 'input' },
      { pin:  4, name: 'A2',   type: 'output' },
      { pin:  5, name: 'B2',   type: 'output' },
      { pin:  6, name: 'A3',   type: 'output' },
      { pin:  7, name: 'GND',  type: 'power' },
      { pin:  8, name: 'B3',   type: 'output' },
      { pin:  9, name: 'A4',   type: 'output' },
      { pin: 10, name: 'B4',   type: 'output' },
      { pin: 11, name: 'GBAn', type: 'input' },
      { pin: 12, name: 'NC1',  type: 'nc' },
      { pin: 13, name: 'NC2',  type: 'nc' },
      { pin: 14, name: 'VCC',  type: 'power' },
    ],
    gates: [
      {
        type: 'TRANSCEIVER_4BIT_INV',
        inputs: ['A1','B1','A2','B2','A3','B3','A4','B4','GABn','GBAn'],
        outputs: ['A1','B1','A2','B2','A3','B3','A4','B4'],
      },
    ],
    sequential: false,
    guideSections: [
      {
        title: 'Inverting Transceiver Use',
        paragraphs: [
          'An inverting transceiver is used when the two buses use opposite polarity conventions. For example, one side may use positive logic and the other active LOW (inverted) signals. The inversion is transparent once the direction is established.',
        ],
        note: 'Never enable both GABn and GBAn LOW at the same time both sides would be driven simultaneously, causing contention.',
      },
    ],
  },

  // ── 74243: Quad Bus Transceiver, Non-Inverting ──────────────────────────
  /* Primary source: Texas Instruments, SN74LS243 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls243.pdf
     Wikipedia: https://en.wikipedia.org/wiki/Three-state_logic
     Wikipedia: https://en.wikipedia.org/wiki/Bus_transceiver */
  '74243': {
    name: '74x243',
    simpleName: '4 bit Transceiver',
    description: 'Quad non-inverting tri-state bus transceiver (14-pin)',
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls243.pdf',
    tags: ['transceiver', 'bus', 'non-inverting', '4 bit', 'tri-state'],
    guideOverview: 'The 74x243 is a quad (4-channel) non-inverting bus transceiver the non-inverting complement to the 74x242. GABn (active LOW) enables A-to-B data flow; GBAn (active LOW) enables B-to-A. Signals pass through without polarity change. Bus transceivers provide isolation between two bus sections, allowing one side to be driven while the other remains high-impedance.',
    guidePinDescriptions: {
      'A1':   'Bus A channel 1.',
      'B1':   'Bus B channel 1.',
      'GABn': 'Enable A→B direction (active LOW). When LOW, A inputs are driven non-inverted onto B.',
      'A2':   'Bus A channel 2.',
      'B2':   'Bus B channel 2.',
      'A3':   'Bus A channel 3.',
      'GND':  'Ground reference (pin 7).',
      'B3':   'Bus B channel 3.',
      'A4':   'Bus A channel 4.',
      'B4':   'Bus B channel 4.',
      'GBAn': 'Enable B→A direction (active LOW). When LOW, B inputs are driven non-inverted onto A.',
      'NC1':  'Not connected.',
      'NC2':  'Not connected.',
      'VCC':  'Positive supply (+5 V, pin 14).',
    },
    pinout: [
      { pin:  1, name: 'A1',   type: 'output' },
      { pin:  2, name: 'B1',   type: 'output' },
      { pin:  3, name: 'GABn', type: 'input' },
      { pin:  4, name: 'A2',   type: 'output' },
      { pin:  5, name: 'B2',   type: 'output' },
      { pin:  6, name: 'A3',   type: 'output' },
      { pin:  7, name: 'GND',  type: 'power' },
      { pin:  8, name: 'B3',   type: 'output' },
      { pin:  9, name: 'A4',   type: 'output' },
      { pin: 10, name: 'B4',   type: 'output' },
      { pin: 11, name: 'GBAn', type: 'input' },
      { pin: 12, name: 'NC1',  type: 'nc' },
      { pin: 13, name: 'NC2',  type: 'nc' },
      { pin: 14, name: 'VCC',  type: 'power' },
    ],
    gates: [
      {
        type: 'TRANSCEIVER_4BIT',
        inputs: ['A1','B1','A2','B2','A3','B3','A4','B4','GABn','GBAn'],
        outputs: ['A1','B1','A2','B2','A3','B3','A4','B4'],
      },
    ],
    sequential: false,
    guideSections: [
      {
        title: 'Bidirectional Bus Isolation',
        paragraphs: [
          'Bus transceivers like the 74x243 isolate two bus segments so that capacitive loading from one side does not affect the other. They also allow a slow-driving device on one side to be isolated while a fast device takes over the bus.',
          'Control logic should ensure only one direction is enabled at a time. A common approach uses a single direction signal: DIR=HIGH enables A→B (GABn=LOW, GBAn=HIGH); DIR=LOW enables B→A.',
        ],
      },
    ],
  },

  // ── 74246: BCD to 7-Segment Decoder/Driver (OC 30V) ────────────────────
  /* Primary source: Texas Instruments, SN74246 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74246.pdf
     Wikipedia: https://en.wikipedia.org/wiki/Multiplexer
     Wikipedia: https://en.wikipedia.org/wiki/Open_collector */
  '74246': {
    name: '74x246',
    simpleName: 'BCD to 7-Seg (OC)',
    description: 'BCD to 7-segment decoder/driver with open-collector outputs (30V) (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    openCollector: true,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74246.pdf',
    tags: ['7-segment', '7 seg', 'decoder', 'bcd', 'display', 'open-collector'],
    guideOverview: 'The 74x246 is a BCD-to-7-segment decoder/driver with open-collector outputs rated for up to 30 V. It accepts a 4 bit BCD input (A D) and drives seven output lines (a g) LOW for the segments that should illuminate on a common-anode display. Open-collector outputs allow direct interface with LED arrays or vacuum fluorescent displays running at elevated supply voltages. LT (Lamp Test) forces all segments ON; RBI (Ripple Blanking Input) suppresses leading/trailing zeros; BI/RBO is the blanking input/output.',
    guidePinDescriptions: {
      'B':      'BCD input bit B (weight 2).',
      'C':      'BCD input bit C (weight 4).',
      'LT':     'Lamp Test (active LOW). Pull LOW to force all seven segments ON regardless of input.',
      'BI/RBO': 'Blanking Input / Ripple Blanking Output. Pull LOW to blank display; goes LOW when RBI suppresses a zero.',
      'RBI':    'Ripple Blanking Input (active LOW). Pull LOW when input is 0000 to suppress (blank) the zero digit.',
      'D':      'BCD input bit D (weight 8, MSB).',
      'A':      'BCD input bit A (weight 1, LSB).',
      'GND':    'Ground reference (pin 8).',
      'e':      'Segment e output (open-collector, active LOW).',
      'd':      'Segment d output.',
      'c':      'Segment c output.',
      'b':      'Segment b output.',
      'a':      'Segment a output.',
      'g':      'Segment g output.',
      'f':      'Segment f output.',
      'VCC':    'Positive supply (+5 V, pin 16).',
    },
    pinout: [
      { pin:  1, name: 'B',      type: 'input' },
      { pin:  2, name: 'C',      type: 'input' },
      { pin:  3, name: 'LT',     type: 'input' },
      { pin:  4, name: 'BI/RBO', type: 'input' },
      { pin:  5, name: 'RBI',    type: 'input' },
      { pin:  6, name: 'D',      type: 'input' },
      { pin:  7, name: 'A',      type: 'input' },
      { pin:  8, name: 'GND',    type: 'power' },
      { pin:  9, name: 'e',      type: 'output' },
      { pin: 10, name: 'd',      type: 'output' },
      { pin: 11, name: 'c',      type: 'output' },
      { pin: 12, name: 'b',      type: 'output' },
      { pin: 13, name: 'a',      type: 'output' },
      { pin: 14, name: 'g',      type: 'output' },
      { pin: 15, name: 'f',      type: 'output' },
      { pin: 16, name: 'VCC',    type: 'power' },
    ],
    gates: [
      { type: 'BCD_7SEG', inputs: ['A','B','C','D'], outputs: ['a','b','c','d','e','f','g'] },
    ],
    guideSections: [
      {
        title: '7-Segment Display Encoding',
        paragraphs: [
          'A 7-segment display uses seven LED segments (a g) arranged to show digits 0 9. The decoder maps each 4 bit BCD code to the correct combination of active LOW segment drivers. For example, digit ‘0’ illuminates segments a,b,c,d,e,f (g is off).',
          'The 74x246 drives common-anode displays where each segment anode is connected to VCC and the cathode is driven LOW by the decoder. The 30 V open-collector rating allows higher-voltage display drivers.',
        ],
        formulas: [
          'BCD 0000 → segments a,b,c,d,e,f ON (g off)',
          'BCD 0001 → segments b,c ON (a,d,e,f,g off)',
          'BCD 0111 → segments a,b,c ON',
        ],
      },
    ],
  },

  // ── 74247: BCD to 7-Segment Decoder/Driver (OC 15V) ────────────────────
  /* Primary source: Texas Instruments, SN74LS247 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls247.pdf
     Wikipedia: https://en.wikipedia.org/wiki/Multiplexer
     Wikipedia: https://en.wikipedia.org/wiki/Open_collector */
  '74247': {
    name: '74x247',
    simpleName: 'BCD to 7-Seg (OC)',
    description: 'BCD to 7-segment decoder/driver with open-collector outputs (15V) (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    openCollector: true,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls247.pdf',
    tags: ['7-segment', '7 seg', 'decoder', 'bcd', 'display', 'open-collector'],
    guideOverview: 'The 74x247 is a BCD-to-7-segment decoder/driver identical to the 74x246 except the open-collector outputs are rated for 15 V (vs 30 V). It drives common-anode 7-segment displays with active LOW segment outputs. LT, BI/RBO, and RBI control lamp test and zero blanking.',
    guidePinDescriptions: {
      'B':      'BCD input bit B (weight 2).',
      'C':      'BCD input bit C (weight 4).',
      'LT':     'Lamp Test (active LOW). Pull LOW to light all segments.',
      'BI/RBO': 'Blanking Input / Ripple Blanking Output.',
      'RBI':    'Ripple Blanking Input. Pull LOW with 0000 input to blank leading/trailing zeros.',
      'D':      'BCD input bit D (weight 8, MSB).',
      'A':      'BCD input bit A (weight 1, LSB).',
      'GND':    'Ground reference (pin 8).',
      'e':      'Segment e output (open-collector, active LOW, 15 V max).',
      'd':      'Segment d output.',
      'c':      'Segment c output.',
      'b':      'Segment b output.',
      'a':      'Segment a output.',
      'g':      'Segment g output.',
      'f':      'Segment f output.',
      'VCC':    'Positive supply (+5 V, pin 16).',
    },
    pinout: [
      { pin:  1, name: 'B',      type: 'input' },
      { pin:  2, name: 'C',      type: 'input' },
      { pin:  3, name: 'LT',     type: 'input' },
      { pin:  4, name: 'BI/RBO', type: 'input' },
      { pin:  5, name: 'RBI',    type: 'input' },
      { pin:  6, name: 'D',      type: 'input' },
      { pin:  7, name: 'A',      type: 'input' },
      { pin:  8, name: 'GND',    type: 'power' },
      { pin:  9, name: 'e',      type: 'output' },
      { pin: 10, name: 'd',      type: 'output' },
      { pin: 11, name: 'c',      type: 'output' },
      { pin: 12, name: 'b',      type: 'output' },
      { pin: 13, name: 'a',      type: 'output' },
      { pin: 14, name: 'g',      type: 'output' },
      { pin: 15, name: 'f',      type: 'output' },
      { pin: 16, name: 'VCC',    type: 'power' },
    ],
    gates: [
      { type: 'BCD_7SEG', inputs: ['A','B','C','D'], outputs: ['a','b','c','d','e','f','g'] },
    ],
    guideSections: [
      {
        title: 'Equivalent to 74246 at 15 V',
        paragraphs: [
          'The 74x247 is functionally identical to the 74x246. The only difference is the maximum open-collector output voltage: 15 V for the 74x247 vs 30 V for the 74x246. Use the 74x247 for standard 5 V or 12 V LED displays and the 74x246 for higher-voltage vacuum fluorescent or gas discharge displays.',
        ],
      },
    ],
  },

  // ── 74248: BCD to 7-Segment Decoder/Driver (OC with internal pull up) ──
  /* Primary source: Texas Instruments, SN74LS248 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls248.pdf
     Wikipedia: https://en.wikipedia.org/wiki/Multiplexer */
  '74248': {
    name: '74x248',
    simpleName: 'BCD to 7-Seg (CC)',
    description: 'BCD to 7-segment decoder/driver with 2k internal pull up resistors (common cathode) (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls248.pdf',
    tags: ['7-segment', '7 seg', 'decoder', 'bcd', 'display', 'common-cathode'],
    guideOverview: 'The 74x248 is a BCD-to-7-segment decoder/driver for common-cathode displays. It includes internal 2 kΩ pull up resistors, making its active HIGH outputs capable of driving common-cathode LED segments directly without additional components. LAMP_TEST (equivalent to LT on 74x246/247) forces all segments ON; BI/RBO controls blanking.',
    guidePinDescriptions: {
      'B':         'BCD input bit B (weight 2).',
      'C':         'BCD input bit C (weight 4).',
      'LAMP_TEST': 'Lamp Test (active LOW). Pull LOW to force all segments HIGH (all ON).',
      'BI/RBO':    'Blanking Input / Ripple Blanking Output. Active LOW blanking.',
      'RBI':       'Ripple Blanking Input (active LOW). Suppresses zero display on 0000 input.',
      'D':         'BCD input bit D (weight 8, MSB).',
      'A':         'BCD input bit A (weight 1, LSB).',
      'GND':       'Ground reference (pin 8).',
      'e':         'Segment e output (active HIGH, with 2kΩ pull up).',
      'd':         'Segment d output.',
      'c':         'Segment c output.',
      'b':         'Segment b output.',
      'a':         'Segment a output.',
      'g':         'Segment g output.',
      'f':         'Segment f output.',
      'VCC':       'Positive supply (+5 V, pin 16).',
    },
    pinout: [
      { pin:  1, name: 'B',         type: 'input' },
      { pin:  2, name: 'C',         type: 'input' },
      { pin:  3, name: 'LAMP_TEST', type: 'input' },
      { pin:  4, name: 'BI/RBO',    type: 'input' },
      { pin:  5, name: 'RBI',       type: 'input' },
      { pin:  6, name: 'D',         type: 'input' },
      { pin:  7, name: 'A',         type: 'input' },
      { pin:  8, name: 'GND',       type: 'power' },
      { pin:  9, name: 'e',         type: 'output' },
      { pin: 10, name: 'd',         type: 'output' },
      { pin: 11, name: 'c',         type: 'output' },
      { pin: 12, name: 'b',         type: 'output' },
      { pin: 13, name: 'a',         type: 'output' },
      { pin: 14, name: 'g',         type: 'output' },
      { pin: 15, name: 'f',         type: 'output' },
      { pin: 16, name: 'VCC',       type: 'power' },
    ],
    gates: [
      { type: 'BCD_7SEG_CC', inputs: ['A','B','C','D'], outputs: ['a','b','c','d','e','f','g'] },
    ],
    guideSections: [
      {
        title: 'Common-Cathode vs Common-Anode',
        paragraphs: [
          'The 74x248 produces active HIGH outputs: a segment lights when the output is HIGH. Connect each output directly to the anode of the corresponding segment; the cathodes of all segments share a common ground (common-cathode configuration).',
          'The internal 2 kΩ pull ups limit segment current. For brighter displays, use external series resistors in place of relying on the internal pull ups, or choose a driver IC with lower output resistance.',
        ],
      },
    ],
  },

  // ── 74249: BCD to 7-Segment Decoder/Driver (OC, active HIGH) ───────────
  /* Primary source: Texas Instruments, SN74249 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74249.pdf
     Wikipedia: https://en.wikipedia.org/wiki/Multiplexer
     Wikipedia: https://en.wikipedia.org/wiki/Open_collector */
  '74249': {
    name: '74x249',
    simpleName: 'BCD to 7-Seg (OC CC)',
    description: 'BCD to 7-segment decoder/driver with open-collector active HIGH outputs (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    openCollector: true,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74249.pdf',
    tags: ['7-segment', '7 seg', 'decoder', 'bcd', 'display', 'open-collector', 'common-cathode'],
    guideOverview: 'The 74x249 is a BCD-to-7-segment decoder/driver with open-collector, active HIGH outputs for common-cathode displays. Unlike the 74x246/247 (which drive common-anode with active LOW outputs), the 74x249 outputs go HIGH to turn segments ON. External pull up resistors to VCC (or a higher display supply) are needed since the outputs are open-collector.',
    guidePinDescriptions: {
      'B':      'BCD input bit B (weight 2).',
      'C':      'BCD input bit C (weight 4).',
      'LT':     'Lamp Test (active LOW). Pull LOW to force all segments HIGH (all ON).',
      'BI/RBO': 'Blanking Input / Ripple Blanking Output.',
      'RBI':    'Ripple Blanking Input (active LOW). Suppresses zero display.',
      'D':      'BCD input bit D (weight 8, MSB).',
      'A':      'BCD input bit A (weight 1, LSB).',
      'GND':    'Ground reference (pin 8).',
      'e':      'Segment e (open-collector, active HIGH). Pulls HIGH via external pull up when segment is ON.',
      'd':      'Segment d output.',
      'c':      'Segment c output.',
      'b':      'Segment b output.',
      'a':      'Segment a output.',
      'g':      'Segment g output.',
      'f':      'Segment f output.',
      'VCC':    'Positive supply (+5 V, pin 16).',
    },
    pinout: [
      { pin:  1, name: 'B',      type: 'input' },
      { pin:  2, name: 'C',      type: 'input' },
      { pin:  3, name: 'LT',     type: 'input' },
      { pin:  4, name: 'BI/RBO', type: 'input' },
      { pin:  5, name: 'RBI',    type: 'input' },
      { pin:  6, name: 'D',      type: 'input' },
      { pin:  7, name: 'A',      type: 'input' },
      { pin:  8, name: 'GND',    type: 'power' },
      { pin:  9, name: 'e',      type: 'output' },
      { pin: 10, name: 'd',      type: 'output' },
      { pin: 11, name: 'c',      type: 'output' },
      { pin: 12, name: 'b',      type: 'output' },
      { pin: 13, name: 'a',      type: 'output' },
      { pin: 14, name: 'g',      type: 'output' },
      { pin: 15, name: 'f',      type: 'output' },
      { pin: 16, name: 'VCC',    type: 'power' },
    ],
    gates: [
      { type: 'BCD_7SEG_CC', inputs: ['A','B','C','D'], outputs: ['a','b','c','d','e','f','g'] },
    ],
    guideSections: [
      {
        title: 'Open Collector for Common-Cathode',
        paragraphs: [
          'The 74x249 combines the open-collector output style with active HIGH polarity. Connect each output through a pull up resistor to the display’s supply voltage; the display’s cathodes share a common ground. This arrangement is useful when the display supply differs from the logic supply.',
        ],
      },
    ],
  },

  // ── 74250: 1-of-16 Data Selector/Multiplexer (Tri-state) ───────────────
  /* Primary source: Texas Instruments, SN74AS250 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74as250.pdf
     Wikipedia: https://en.wikipedia.org/wiki/Multiplexer
     Wikipedia: https://en.wikipedia.org/wiki/Three-state_logic */
  '74250': {
    name: '74x250',
    simpleName: '16-to-1 MUX (3-state)',
    description: '1-of-16 data selector/multiplexer with 3-state output (24-pin)',
    pins: 24,
    vcc: 24,
    gnd: 12,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74as250.pdf',
    tags: ['multiplexer', 'mux', '16-to-1', 'tri-state', 'selector'],
    guideOverview: 'The 74x250 is a 16-to-1 data selector (multiplexer) with a 3-state output. A 4 bit select address (A, B, C, D) picks one of 16 data inputs (E1 E16) and routes it to the single output W. OE (active LOW) enables the output; when OE is HIGH, W is tri-stated. The 24-pin DIP accommodates all 16 data inputs while leaving room for the address, enable, and power pins.',
    guidePinDescriptions: {
      'E8':  'Data input 8.',
      'E7':  'Data input 7.',
      'E6':  'Data input 6.',
      'E5':  'Data input 5.',
      'E4':  'Data input 4.',
      'E3':  'Data input 3.',
      'E2':  'Data input 2.',
      'E1':  'Data input 1.',
      'A':   'Select bit A (LSB of 4 bit address).',
      'B':   'Select bit B.',
      'OE':  'Output Enable (active LOW). When asserted (LOW), drives W output; when HIGH, tri-states it.',
      'GND': 'Ground reference (pin 12).',
      'W':   'Selected data output (3-state). Reflects the E input addressed by A D when OE=LOW.',
      'C':   'Select bit C.',
      'D':   'Select bit D (MSB).',
      'E9':  'Data input 9.',
      'E10': 'Data input 10.',
      'E11': 'Data input 11.',
      'E12': 'Data input 12.',
      'E13': 'Data input 13.',
      'E14': 'Data input 14.',
      'E15': 'Data input 15.',
      'E16': 'Data input 16.',
      'VCC': 'Positive supply (+5 V, pin 24).',
    },
    pinout: [
      { pin:  1, name: 'E8',  type: 'input' },
      { pin:  2, name: 'E7',  type: 'input' },
      { pin:  3, name: 'E6',  type: 'input' },
      { pin:  4, name: 'E5',  type: 'input' },
      { pin:  5, name: 'E4',  type: 'input' },
      { pin:  6, name: 'E3',  type: 'input' },
      { pin:  7, name: 'E2',  type: 'input' },
      { pin:  8, name: 'E1',  type: 'input' },
      { pin:  9, name: 'A',   type: 'input' },
      { pin: 10, name: 'B',   type: 'input' },
      { pin: 11, name: 'OE',  type: 'input' },
      { pin: 12, name: 'GND', type: 'power' },
      { pin: 13, name: 'W',   type: 'output' },
      { pin: 14, name: 'C',   type: 'input' },
      { pin: 15, name: 'D',   type: 'input' },
      { pin: 16, name: 'E9',  type: 'input' },
      { pin: 17, name: 'E10', type: 'input' },
      { pin: 18, name: 'E11', type: 'input' },
      { pin: 19, name: 'E12', type: 'input' },
      { pin: 20, name: 'E13', type: 'input' },
      { pin: 21, name: 'E14', type: 'input' },
      { pin: 22, name: 'E15', type: 'input' },
      { pin: 23, name: 'E16', type: 'input' },
      { pin: 24, name: 'VCC', type: 'power' },
    ],
    gates: [
      {
        type: 'MUX_16TO1_TRI',
        inputs: ['E1','E2','E3','E4','E5','E6','E7','E8','E9','E10','E11','E12','E13','E14','E15','E16','A','B','C','D','OE'],
        outputs: ['W'],
      },
    ],
    guideSections: [
      {
        title: '16-to-1 Multiplexer',
        paragraphs: [
          'With a 4 bit address you can select any one of 2⁴ = 16 inputs. Counting from E1 to E16, the select encoding is: A is the LSB and D is the MSB. E1 is selected when DCBA = 0000, E16 when DCBA = 1111.',
          'The 3-state output allows multiple 74x250s to share a common bus: only the one with OE=LOW drives the bus at any time.',
        ],
      },
    ],
  },

  // ── 74251: 8-Line to 1-Line Data Selector/Multiplexer (Complementary 3-state) ──
  /* Primary source: Texas Instruments, SN74LS251 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls251.pdf
     Wikipedia: https://en.wikipedia.org/wiki/Multiplexer
     Wikipedia: https://en.wikipedia.org/wiki/Three-state_logic */
  '74251': {
    name: '74x251',
    simpleName: '8-to-1 MUX (3-state, comp)',
    description: '8-line to 1-line data selector/multiplexer with complementary 3-state outputs (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls251.pdf',
    tags: ['multiplexer', 'mux', '8-to-1', 'tri-state', 'complementary'],
    guideOverview: 'The 74x251 is an 8-to-1 data selector (MUX) with complementary 3-state outputs. Three select lines (A, B, C) address one of eight data inputs (D0 D7). Unlike the 74x151 which has a single output, the 74x251 provides both Y (true, non-inverted) and W (complement, inverted) outputs simultaneously, both tri-stated. Gn (active LOW) enables both outputs; when Gn is HIGH, both Y and W are tri-stated.',
    guidePinDescriptions: {
      'D3':  'Data input 3.',
      'D2':  'Data input 2.',
      'D1':  'Data input 1.',
      'D0':  'Data input 0.',
      'Y':   'True (non-inverted) output (3-state). Reflects the selected data input when Gn=LOW.',
      'W':   'Complement (inverted) output (3-state). Reflects the inverse of the selected data input when Gn=LOW.',
      'Gn':  'Enable (active LOW). When asserted (LOW), drives Y and W outputs; when HIGH, tri-states them.',
      'GND': 'Ground reference (pin 8).',
      'C':   'Select bit C (MSB).',
      'B':   'Select bit B.',
      'A':   'Select bit A (LSB). CBA=000 selects D0; CBA=111 selects D7.',
      'D7':  'Data input 7.',
      'D6':  'Data input 6.',
      'D5':  'Data input 5.',
      'D4':  'Data input 4.',
      'VCC': 'Positive supply (+5 V, pin 16).',
    },
    pinout: [
      { pin:  1, name: 'D3', type: 'input' },
      { pin:  2, name: 'D2', type: 'input' },
      { pin:  3, name: 'D1', type: 'input' },
      { pin:  4, name: 'D0', type: 'input' },
      { pin:  5, name: 'Y',  type: 'output' },
      { pin:  6, name: 'W',  type: 'output' },
      { pin:  7, name: 'Gn', type: 'input' },
      { pin:  8, name: 'GND', type: 'power' },
      { pin:  9, name: 'C',  type: 'input' },
      { pin: 10, name: 'B',  type: 'input' },
      { pin: 11, name: 'A',  type: 'input' },
      { pin: 12, name: 'D7', type: 'input' },
      { pin: 13, name: 'D6', type: 'input' },
      { pin: 14, name: 'D5', type: 'input' },
      { pin: 15, name: 'D4', type: 'input' },
      { pin: 16, name: 'VCC', type: 'power' },
    ],
    gates: [
      {
        type: 'MUX_8TO1_TRI',
        inputs: ['D0','D1','D2','D3','D4','D5','D6','D7','A','B','C','Gn'],
        outputs: ['Y','W'],
      },
    ],
    guideSections: [
      {
        title: 'Complementary Outputs',
        paragraphs: [
          'The dual outputs Y and W allow the MUX to feed both a positive-logic and negative-logic input simultaneously without an external inverter. This is useful in comparators, priority encoders, and any circuit that benefits from having both the selected value and its complement available.',
        ],
      },
    ],
  },

  // ── 74253: Dual 4-Line to 1-Line Data Selector/Multiplexer (Tri-state) ─
  /* Primary source: Texas Instruments, SN74LS253 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls253.pdf
     Wikipedia: https://en.wikipedia.org/wiki/Multiplexer
     Wikipedia: https://en.wikipedia.org/wiki/Three-state_logic */
  '74253': {
    name: '74x253',
    simpleName: 'Dual 4-to-1 MUX (3-state)',
    description: 'Dual 4-line to 1-line data selector/multiplexer with 3-state outputs (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls253.pdf',
    tags: ['multiplexer', 'mux', '4-to-1', 'dual', 'tri-state'],
    guideOverview: 'The 74x253 is the 3-state output version of the 74x153 dual 4-to-1 multiplexer. It contains two independent 4 input MUX sections sharing select lines S0 and S1. Each section has an independent active LOW enable (1Gn, 2Gn): when asserted LOW, the selected input is routed to the output; when HIGH, the output is tri-stated. The 3-state outputs allow multiple 74x253s to share a common data bus.',
    guidePinDescriptions: {
      'S0':  'Select bit 0 (LSB), shared by both sections. S1S0=00 selects C0; =11 selects C3.',
      '1Gn': 'Enable for section 1 (active LOW). LOW = output 1Y reflects selected input; HIGH = 1Y tri-stated.',
      '1C3': 'Section 1 data input 3 (selected when S1=1, S0=1).',
      '1C2': 'Section 1 data input 2 (selected when S1=1, S0=0).',
      '1C1': 'Section 1 data input 1 (selected when S1=0, S0=1).',
      '1C0': 'Section 1 data input 0 (selected when S1=0, S0=0).',
      '1Y':  'Section 1 output (3-state). Tri-stated when 1Gn=HIGH.',
      'GND': 'Ground reference (pin 8).',
      '2Y':  'Section 2 output (3-state).',
      '2C0': 'Section 2 data input 0.',
      '2C1': 'Section 2 data input 1.',
      '2C2': 'Section 2 data input 2.',
      '2C3': 'Section 2 data input 3.',
      '2Gn': 'Enable for section 2 (active LOW).',
      'S1':  'Select bit 1 (MSB), shared by both sections.',
      'VCC': 'Positive supply (+5 V, pin 16).',
    },
    pinout: [
      { pin:  1, name: 'S0',  type: 'input' },
      { pin:  2, name: '1Gn', type: 'input' },
      { pin:  3, name: '1C3', type: 'input' },
      { pin:  4, name: '1C2', type: 'input' },
      { pin:  5, name: '1C1', type: 'input' },
      { pin:  6, name: '1C0', type: 'input' },
      { pin:  7, name: '1Y',  type: 'output' },
      { pin:  8, name: 'GND', type: 'power' },
      { pin:  9, name: '2Y',  type: 'output' },
      { pin: 10, name: '2C0', type: 'input' },
      { pin: 11, name: '2C1', type: 'input' },
      { pin: 12, name: '2C2', type: 'input' },
      { pin: 13, name: '2C3', type: 'input' },
      { pin: 14, name: '2Gn', type: 'input' },
      { pin: 15, name: 'S1',  type: 'input' },
      { pin: 16, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'MUX_4TO1_TRI', inputs: ['1C0','1C1','1C2','1C3','S0','S1','1Gn'], output: '1Y' },
      { type: 'MUX_4TO1_TRI', inputs: ['2C0','2C1','2C2','2C3','S0','S1','2Gn'], output: '2Y' },
    ],
    guideSections: [
      {
        title: '3-State Dual MUX',
        paragraphs: [
          'The 3-state outputs make the 74x253 ideal for bus-structured designs. Multiple 74x253 chips can be connected with their outputs tied together; only the enabled chip drives the bus. Use Gn as the chip-select: assert one chip’s Gn LOW while keeping all others HIGH.',
        ],
      },
    ],
  },

  // ── 74255: Dual 2-to-4 Line Decoder/Demultiplexer (Inverting, Tri-state) ─
  /* Primary source: Texas Instruments, 74LS255 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/74ls255.pdf
     Wikipedia: https://en.wikipedia.org/wiki/Multiplexer
     Wikipedia: https://en.wikipedia.org/wiki/Three-state_logic */
  '74255': {
    name: '74x255',
    simpleName: 'Dual 2-to-4 Decoder (inv, 3-state)',
    description: 'Dual 2-to-4 line decoder/demultiplexer with inverting outputs and 3-state enable (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/74ls255.pdf',
    tags: ['decoder', 'demultiplexer', '2-to-4', 'dual', 'tri-state', 'inverting'],
    guideOverview: 'The 74x255 is a dual 2-to-4 line decoder/demultiplexer with inverting, 3-state outputs. Two shared select lines (S0, S1) address one of four output lines per section. In demultiplex mode, a data input (1C or 2C) is routed to the selected output; the other three outputs remain HIGH (inactive-inverted). When the enable pin Gn is HIGH, all outputs are tri-stated, enabling bus sharing.',
    guidePinDescriptions: {
      'S0':   'Select bit 0 (LSB), shared. S1S0=00 routes to Y0; =11 routes to Y3.',
      '1Gn':  'Enable for section 1 (active LOW). HIGH = section 1 outputs tri-stated.',
      '1Y3n': 'Section 1 output 3 (inverting, 3-state). LOW when selected with data=HIGH.',
      '1Y2n': 'Section 1 output 2.',
      '1Y1n': 'Section 1 output 1.',
      '1Y0n': 'Section 1 output 0.',
      '1C':   'Section 1 data input (demultiplex mode). This signal is routed (inverted) to the selected output.',
      'GND':  'Ground reference (pin 8).',
      '2C':   'Section 2 data input (demultiplex mode).',
      '2Y0n': 'Section 2 output 0.',
      '2Y1n': 'Section 2 output 1.',
      '2Y2n': 'Section 2 output 2.',
      '2Y3n': 'Section 2 output 3.',
      '2Gn':  'Enable for section 2 (active LOW).',
      'S1':   'Select bit 1 (MSB), shared.',
      'VCC':  'Positive supply (+5 V, pin 16).',
    },
    pinout: [
      { pin:  1, name: 'S0',   type: 'input' },
      { pin:  2, name: '1Gn',  type: 'input' },
      { pin:  3, name: '1Y3n', type: 'output' },
      { pin:  4, name: '1Y2n', type: 'output' },
      { pin:  5, name: '1Y1n', type: 'output' },
      { pin:  6, name: '1Y0n', type: 'output' },
      { pin:  7, name: '1C',   type: 'input' },
      { pin:  8, name: 'GND',  type: 'power' },
      { pin:  9, name: '2C',   type: 'input' },
      { pin: 10, name: '2Y0n', type: 'output' },
      { pin: 11, name: '2Y1n', type: 'output' },
      { pin: 12, name: '2Y2n', type: 'output' },
      { pin: 13, name: '2Y3n', type: 'output' },
      { pin: 14, name: '2Gn',  type: 'input' },
      { pin: 15, name: 'S1',   type: 'input' },
      { pin: 16, name: 'VCC',  type: 'power' },
    ],
    gates: [
      { type: 'DEMUX_2TO4_TRI', inputs: ['S0','S1','1Gn','1C'], outputs: ['1Y0n','1Y1n','1Y2n','1Y3n'] },
      { type: 'DEMUX_2TO4_TRI', inputs: ['S0','S1','2Gn','2C'], outputs: ['2Y0n','2Y1n','2Y2n','2Y3n'] },
    ],
    guideSections: [
      {
        title: 'Decoder vs Demultiplexer Mode',
        paragraphs: [
          'In decoder mode: tie 1C/2C HIGH and use Gn as the enable. The selected output goes LOW; all others stay HIGH (active LOW encoding).',
          'In demultiplexer mode: drive 1C/2C with your data signal. The data is routed (inverted) to the selected output the chip acts as a 1-to-4 data router.',
        ],
      },
    ],
  },

  // ── 74256: Dual 4 bit Addressable Latch ─────────────────────────────────
  /* Primary source: Texas Instruments, MC74F256 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/mc74f256.pdf
     Wikipedia: https://en.wikipedia.org/wiki/Flip-flop_(electronics) */
  '74256': {
    name: '74x256',
    simpleName: 'Dual 4 bit Addr Latch',
    description: 'Dual 4 bit addressable latch (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/mc74f256.pdf',
    tags: ['latch', 'addressable', 'dual', '4 bit', 'register'],
    guideOverview: 'The 74x256 is a dual 4 bit addressable latch, similar to two 74x259 sections in one package. Two address bits (A0, A1) select which of four latch bits receives input D during a GS (Gate Strobe) pulse. Each 4 bit section has its own active LOW CLR pin. A0/A1/D/GS are shared between both sections; CLR1 clears section 1 and CLR2 clears section 2.',
    guidePinDescriptions: {
      'A0':   'Address bit 0 (LSB). Together with A1, selects which bit (Q0 Q3) receives D.',
      'A1':   'Address bit 1 (MSB). A1A0=00 addresses Q0; =11 addresses Q3.',
      'D':    'Data input. Written to the addressed bit when GS is asserted.',
      'GS':   'Gate Strobe. When HIGH (active HIGH), the addressed bit is written with D.',
      'CLR1': 'Clear for section 1 (active LOW). Forces 1Q0 1Q3 all LOW.',
      '1Q0':  'Section 1 latch bit 0 output.',
      '1Q1':  'Section 1 latch bit 1 output.',
      'GND':  'Ground reference (pin 8).',
      '1Q2':  'Section 1 latch bit 2 output.',
      '1Q3':  'Section 1 latch bit 3 output.',
      'CLR2': 'Clear for section 2 (active LOW). Forces 2Q0 2Q3 all LOW.',
      '2Q0':  'Section 2 latch bit 0 output.',
      '2Q1':  'Section 2 latch bit 1 output.',
      '2Q2':  'Section 2 latch bit 2 output.',
      '2Q3':  'Section 2 latch bit 3 output.',
      'VCC':  'Positive supply (+5 V, pin 16).',
    },
    pinout: [
      { pin:  1, name: 'A0',   type: 'input' },
      { pin:  2, name: 'A1',   type: 'input' },
      { pin:  3, name: 'D',    type: 'input' },
      { pin:  4, name: 'GS',   type: 'input' },
      { pin:  5, name: 'CLR1', type: 'input' },
      { pin:  6, name: '1Q0',  type: 'output' },
      { pin:  7, name: '1Q1',  type: 'output' },
      { pin:  8, name: 'GND',  type: 'power' },
      { pin:  9, name: '1Q2',  type: 'output' },
      { pin: 10, name: '1Q3',  type: 'output' },
      { pin: 11, name: 'CLR2', type: 'input' },
      { pin: 12, name: '2Q0',  type: 'output' },
      { pin: 13, name: '2Q1',  type: 'output' },
      { pin: 14, name: '2Q2',  type: 'output' },
      { pin: 15, name: '2Q3',  type: 'output' },
      { pin: 16, name: 'VCC',  type: 'power' },
    ],
    gates: [
      {
        type: 'DUAL_ADDR_LATCH_4BIT',
        inputs: ['A0','A1','D','GS','CLR1','CLR2'],
        outputs: ['1Q0','1Q1','1Q2','1Q3','2Q0','2Q1','2Q2','2Q3'],
      },
    ],
    sequential: true,
    guideSections: [
      {
        title: 'Addressable Latch Operation',
        paragraphs: [
          'An addressable latch functions like a small RAM: you select a bit by address and write D into just that bit when GS is asserted. The other bits retain their previous state. This makes it efficient for setting or clearing individual bits in a register without affecting the others.',
          'Typical use: attach A0/A1 to the two LSBs of an address bus, D to the data bus, and GS to a decoded write strobe. Eight consecutive writes (or fewer) can independently set each output HIGH or LOW.',
        ],
      },
    ],
  },

  // ── 74258: Quad 2-to-1 MUX, Inverting, Tri-state ────────────────────────
  /* Primary source: Texas Instruments, SN74LS258B datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls258b.pdf
     Wikipedia: https://en.wikipedia.org/wiki/Multiplexer
     Wikipedia: https://en.wikipedia.org/wiki/Three-state_logic */
  '74258': {
    name: '74x258',
    simpleName: 'Quad 2-to-1 MUX (inv, 3-state)',
    description: 'Quad 2-line to 1-line data selector/multiplexer with inverting 3-state outputs (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls258b.pdf',
    tags: ['multiplexer', 'mux', '2-to-1', 'quad', 'tri-state', 'inverting'],
    guideOverview: 'The 74x258 is a quad 2-to-1 inverting multiplexer with 3-state outputs the inverting, 3-state complement to the 74x157. A single select pin S chooses between the A or B input of all four sections simultaneously; when S=LOW, A is selected; when S=HIGH, B is selected. Output Enable (active LOW): when asserted (LOW), drives outputs; when HIGH, tri-states them.',
    guidePinDescriptions: {
      'S':   'Select input. LOW = route A inputs; HIGH = route B inputs (applies to all four sections).',
      '1A':  'Section 1 input A.',
      '1B':  'Section 1 input B.',
      '1Y':  'Section 1 output (inverted, 3-state). LOW when selected input is HIGH and OEn=LOW.',
      '2A':  'Section 2 input A.',
      '2B':  'Section 2 input B.',
      '2Y':  'Section 2 output.',
      'GND': 'Ground reference (pin 8).',
      'OEn': 'Output Enable (active LOW). When asserted (LOW), drives Y outputs; when HIGH, tri-states them.',
      '3Y':  'Section 3 output.',
      '3A':  'Section 3 input A.',
      '3B':  'Section 3 input B.',
      '4Y':  'Section 4 output.',
      '4A':  'Section 4 input A.',
      '4B':  'Section 4 input B.',
      'VCC': 'Positive supply (+5 V, pin 16).',
    },
    pinout: [
      { pin:  1, name: 'S',   type: 'input' },
      { pin:  2, name: '1A',  type: 'input' },
      { pin:  3, name: '1B',  type: 'input' },
      { pin:  4, name: '1Y',  type: 'output' },
      { pin:  5, name: '2A',  type: 'input' },
      { pin:  6, name: '2B',  type: 'input' },
      { pin:  7, name: '2Y',  type: 'output' },
      { pin:  8, name: 'GND', type: 'power' },
      { pin:  9, name: 'OEn', type: 'input' },
      { pin: 10, name: '3Y',  type: 'output' },
      { pin: 11, name: '3A',  type: 'input' },
      { pin: 12, name: '3B',  type: 'input' },
      { pin: 13, name: '4Y',  type: 'output' },
      { pin: 14, name: '4A',  type: 'input' },
      { pin: 15, name: '4B',  type: 'input' },
      { pin: 16, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'MUX_2TO1_INV_TRI', inputs: ['1A','1B','S','OEn'], output: '1Y' },
      { type: 'MUX_2TO1_INV_TRI', inputs: ['2A','2B','S','OEn'], output: '2Y' },
      { type: 'MUX_2TO1_INV_TRI', inputs: ['3A','3B','S','OEn'], output: '3Y' },
      { type: 'MUX_2TO1_INV_TRI', inputs: ['4A','4B','S','OEn'], output: '4Y' },
    ],
    guideSections: [
      {
        title: 'Inverting 2-to-1 MUX',
        paragraphs: [
          'Each section selects between two inputs and inverts the result. Y = NOT(selected input). The 3-state output allows this chip to drive a shared bus enable with OEn=LOW only when driving.',
          'Use case: select between two active LOW signals and output to an active LOW bus, achieving double inversion (positive logic) while multiplexing.',
        ],
      },
    ],
  },

  // ── 74260: Dual 5 Input NOR Gate ─────────────────────────────────────────
  /* Primary source: Texas Instruments, SN74LS260 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls260.pdf */
  '74260': {
    name: '74x260',
    simpleName: 'Dual 5 Input NOR',
    description: 'Dual 5 input NOR gate (14-pin)',
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls260.pdf',
    tags: ['nor', 'gate', 'dual', '5 input', 'logic'],
    guideOverview: 'The 74x260 contains two independent 5 input NOR gates. A NOR gate output is HIGH only when ALL inputs are LOW; if any input is HIGH, the output is LOW. With five inputs per gate, the 74x260 can replace combinations of 2- and 3 input NOR gates when a single-chip solution for a 5 input NOR function is desired.',
    guidePinDescriptions: {
      '1Y':  'Gate 1 output. HIGH only when 1A, 1B, 1C, 1D, and 1E are all LOW.',
      '1A':  'Gate 1 input A.',
      '1B':  'Gate 1 input B.',
      '1C':  'Gate 1 input C.',
      '1D':  'Gate 1 input D.',
      '1E':  'Gate 1 input E.',
      'GND': 'Ground reference (pin 7).',
      '2A':  'Gate 2 input A.',
      '2B':  'Gate 2 input B.',
      '2C':  'Gate 2 input C.',
      '2D':  'Gate 2 input D.',
      '2E':  'Gate 2 input E.',
      '2Y':  'Gate 2 output.',
      'VCC': 'Positive supply (+5 V, pin 14).',
    },
    pinout: [
      { pin:  1, name: '1Y',  type: 'output' },
      { pin:  2, name: '1A',  type: 'input' },
      { pin:  3, name: '1B',  type: 'input' },
      { pin:  4, name: '1C',  type: 'input' },
      { pin:  5, name: '1D',  type: 'input' },
      { pin:  6, name: '1E',  type: 'input' },
      { pin:  7, name: 'GND', type: 'power' },
      { pin:  8, name: '2A',  type: 'input' },
      { pin:  9, name: '2B',  type: 'input' },
      { pin: 10, name: '2C',  type: 'input' },
      { pin: 11, name: '2D',  type: 'input' },
      { pin: 12, name: '2E',  type: 'input' },
      { pin: 13, name: '2Y',  type: 'output' },
      { pin: 14, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'NOR', inputs: ['1A','1B','1C','1D','1E'], output: '1Y' },
      { type: 'NOR', inputs: ['2A','2B','2C','2D','2E'], output: '2Y' },
    ],
    guideSections: [
      {
        title: '5 Input NOR Truth Table',
        paragraphs: [
          'Y is HIGH only when all five inputs are LOW. Any single HIGH input forces Y LOW. Use it to detect a "all idle" condition (all five lines LOW), or implement a wide OR function by noting that Y’s complement is a 5 input OR.',
        ],
        formulas: [
          'Y = NOT(A OR B OR C OR D OR E)',
          'Y = 1 only when A=B=C=D=E=0',
        ],
      },
    ],
  },

  // ── 74261: 2 bit by 4 bit Parallel Binary Multiplier ─────────────────────
  /* Primary source: Texas Instruments, SN74LS261 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls261.pdf */
  '74261': {
    name: '74x261',
    simpleName: '2x4 bit Multiplier',
    description: '2 bit by 4 bit parallel binary multiplier (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls261.pdf',
    tags: ['multiplier', 'binary', '2 bit', '4 bit', 'arithmetic'],
    guideOverview: 'The 74x261 is a 2×4 bit parallel binary multiplier. It multiplies a 2 bit multiplicand (B1 B2) by a 4 bit multiplier (A1 A2 plus partial products Y1 Y4 for cascading) to produce a 6 bit product (P1 P6). Unlike serial multiply-accumulate approaches, the entire product appears combinationally within one propagation delay. Useful for small DSP building blocks and hardware scaling operations.',
    guidePinDescriptions: {
      'B1':  'Multiplicand bit 1 (LSB of the 2 bit value).',
      'B2':  'Multiplicand bit 2 (MSB of the 2 bit value).',
      'Y1':  'Partial product / carry-in bit 1 (used when cascading multiple 74x261s).',
      'Y2':  'Partial product / carry-in bit 2.',
      'Y3':  'Partial product / carry-in bit 3.',
      'Y4':  'Partial product / carry-in bit 4.',
      'A1':  'Multiplier bit 1 (LSB of the 4 bit value).',
      'GND': 'Ground reference (pin 8).',
      'A2':  'Multiplier bit 2.',
      'P2':  'Product output bit 2.',
      'P3':  'Product output bit 3.',
      'P4':  'Product output bit 4.',
      'P5':  'Product output bit 5.',
      'P6':  'Product output bit 6 (MSB).',
      'P1':  'Product output bit 1 (LSB).',
      'VCC': 'Positive supply (+5 V, pin 16).',
    },
    pinout: [
      { pin:  1, name: 'B1',  type: 'input' },
      { pin:  2, name: 'B2',  type: 'input' },
      { pin:  3, name: 'Y1',  type: 'input' },
      { pin:  4, name: 'Y2',  type: 'input' },
      { pin:  5, name: 'Y3',  type: 'input' },
      { pin:  6, name: 'Y4',  type: 'input' },
      { pin:  7, name: 'A1',  type: 'input' },
      { pin:  8, name: 'GND', type: 'power' },
      { pin:  9, name: 'A2',  type: 'input' },
      { pin: 10, name: 'P2',  type: 'output' },
      { pin: 11, name: 'P3',  type: 'output' },
      { pin: 12, name: 'P4',  type: 'output' },
      { pin: 13, name: 'P5',  type: 'output' },
      { pin: 14, name: 'P6',  type: 'output' },
      { pin: 15, name: 'P1',  type: 'output' },
      { pin: 16, name: 'VCC', type: 'power' },
    ],
    gates: [
      {
        type: 'MULT_2X4BIT',
        inputs: ['B1','B2','A1','A2','Y1','Y2','Y3','Y4'],
        outputs: ['P1','P2','P3','P4','P5','P6'],
      },
    ],
    guideSections: [
      {
        title: 'Parallel Binary Multiplication',
        paragraphs: [
          'Multiplying an N-bit number by an M-bit number produces an (N+M)-bit result. A 2×4 multiplier produces a 6 bit result. The 74x261 computes all partial products simultaneously using AND gates and carry-save adder trees, yielding the full product combinationally.',
          'For a 4×4 unsigned multiply (16 bit result), cascade two 74x261s: feed the upper 2 bits of the 4 bit number to the B inputs of one chip and the lower 2 bits to the other, then sum the partial products.',
        ],
        formulas: [
          'Product (6 bit) = B[2:1] × A[4:1] (unsigned)',
          'Max result: 3 × 15 = 45 (fits in 6 bits)',
        ],
      },
    ],
  },

  // ── 74264: Look-Ahead Carry Generator ────────────────────────────────────
  /* Primary source: Texas Instruments, SN74AS264 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74as264.pdf
     Wikipedia: https://en.wikipedia.org/wiki/Adder_(electronics)
     Wikipedia: https://en.wikipedia.org/wiki/Arithmetic_logic_unit */
  '74264': {
    name: '74x264',
    simpleName: 'Look-Ahead Carry Gen',
    description: 'High-speed carry look-ahead generator (same function as 74182) (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74as264.pdf',
    tags: ['carry', 'look-ahead', 'alu', 'arithmetic', 'carry generator'],
    guideOverview: 'The 74x264 is a high-speed carry look-ahead generator equivalent in function to the 74x182. It accepts group Propagate (P0 P3) and Generate (G0 G3) signals from four 4 bit ALU slices (e.g., 74x181), plus a carry-in Cn, and produces intermediate carry outputs (Cn_x, Cn_y, Cn_z) for bits 4, 8, and 12, along with a group Generate (G) and group Propagate (P) for chaining another level of look-ahead. This eliminates carry ripple delay in 16 bit and wider adders.',
    guidePinDescriptions: {
      'P0':   'Propagate input from ALU slice 0 (bits 0 3). HIGH when a carry will propagate through this slice.',
      'G0':   'Generate input from ALU slice 0. HIGH when this slice generates a carry regardless of carry-in.',
      'P1':   'Propagate input from ALU slice 1 (bits 4 7).',
      'G1':   'Generate input from ALU slice 1.',
      'Cn_y': 'Carry output into bit 8 (between slice 1 and slice 2).',
      'P2':   'Propagate input from ALU slice 2 (bits 8 11).',
      'G2':   'Generate input from ALU slice 2.',
      'GND':  'Ground reference (pin 8).',
      'Cn_x': 'Carry output into bit 4 (between slice 0 and slice 1).',
      'Cn':   'Carry input from the previous 74x264 (or tied LOW for the least-significant group).',
      'G':    'Group Generate output. HIGH if this group of four slices generates a carry out of bit 15.',
      'P':    'Group Propagate output. HIGH if a carry-in to bit 0 would propagate through all 16 bits.',
      'Cn_z': 'Carry output into bit 12 (between slice 2 and slice 3).',
      'P3':   'Propagate input from ALU slice 3 (bits 12 15).',
      'G3':   'Generate input from ALU slice 3.',
      'VCC':  'Positive supply (+5 V, pin 16).',
    },
    pinout: [
      { pin:  1, name: 'P0',   type: 'input' },
      { pin:  2, name: 'G0',   type: 'input' },
      { pin:  3, name: 'P1',   type: 'input' },
      { pin:  4, name: 'G1',   type: 'input' },
      { pin:  5, name: 'Cn_y', type: 'output' },
      { pin:  6, name: 'P2',   type: 'input' },
      { pin:  7, name: 'G2',   type: 'input' },
      { pin:  8, name: 'GND',  type: 'power' },
      { pin:  9, name: 'Cn_x', type: 'output' },
      { pin: 10, name: 'Cn',   type: 'input' },
      { pin: 11, name: 'G',    type: 'output' },
      { pin: 12, name: 'P',    type: 'output' },
      { pin: 13, name: 'Cn_z', type: 'output' },
      { pin: 14, name: 'P3',   type: 'input' },
      { pin: 15, name: 'G3',   type: 'input' },
      { pin: 16, name: 'VCC',  type: 'power' },
    ],
    gates: [
      {
        type: 'CARRY_LOOKAHEAD',
        inputs: ['P0','G0','P1','G1','P2','G2','P3','G3','Cn'],
        outputs: ['Cn_x','Cn_y','Cn_z','P','G'],
      },
    ],
    guideSections: [
      {
        title: 'Carry Look-Ahead Concept',
        paragraphs: [
          'A ripple-carry adder computes each bit’s carry sequentially, causing delay proportional to word width. Look-ahead carry solves this by pre-computing all carries in parallel using Generate (G) and Propagate (P) signals from each slice.',
          'G=1 means the slice generates a carry regardless of carry-in. P=1 means the slice passes any carry-in to its carry-out. The 74x264 combines four slices’ P and G signals to produce carry outputs Cn_x, Cn_y, Cn_z simultaneously reducing a 16 bit carry chain to a single gate level delay.',
        ],
        formulas: [
          'Cn_x = G0 + P0·Cn',
          'Cn_y = G1 + P1·G0 + P1·P0·Cn',
          'Cn_z = G2 + P2·G1 + P2·P1·G0 + P2·P1·P0·Cn',
        ],
      },
    ],
  },

};
