// Chip definitions block 2
// Auto-generated from chips.js

export const CHIPS_BLOCK_2 = {
  // ── 7415: Triple 3 input AND (open collector) ──────────────────────────
  /* Primary source: Texas Instruments, SN74LS15 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls15.pdf
     Open-collector output technology: https://en.wikipedia.org/wiki/Open_collector */
  '7415': {
    name: '74x15',
    simpleName: 'Triple 3-in AND (OC)',
    description: 'Three independent 3 input AND gates with open-collector outputs. (14-pin)',
    guideOverview: 'The 74x15 provides three independent 3 input AND gates with open-collector outputs. Like the 74x11 (which has totem-pole outputs), the output goes HIGH only when all three inputs are HIGH. The open-collector output requires an external pull up resistor and supports wire-ANDing and high-voltage load driving.',
    guidePinDescriptions: {
      '1A': 'Input A of AND gate 1.',
      '1B': 'Input B of AND gate 1.',
      '2A': 'Input A of AND gate 2.',
      '2B': 'Input B of AND gate 2.',
      '2C': 'Input C of AND gate 2.',
      '2Y': 'Open-collector output of gate 2. Conducts (sinks to LOW) when 2A, 2B, and 2C are all HIGH.',
      'GND': 'Ground reference (pin 7).',
      '3Y': 'Open-collector output of gate 3. Conducts when 3A, 3B, and 3C are all HIGH.',
      '3A': 'Input A of AND gate 3.',
      '3B': 'Input B of AND gate 3.',
      '3C': 'Input C of AND gate 3.',
      '1Y': 'Open-collector output of gate 1. Conducts when 1A, 1B, and 1C are all HIGH.',
      '1C': 'Input C of AND gate 1.',
      'VCC': 'Positive supply (+5 V) at pin 14.',
    },
    pins: 14,
    vcc: 14,
    gnd: 7,
    openCollector: true,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls15.pdf',
    tags: ['and', 'gate', 'logic', 'triple', '3 input', 'open collector'],
    guideSections: [
      {
        title: 'Open Collector 3-Input AND',
        paragraphs: [
          'Logic function is identical to the 74x11: Y = A AND B AND C. The open-collector output requires a pull up resistor to produce the HIGH level and supports wire-ANDing multiple outputs on a shared bus.',
        ],
        formulas: ['Y = A AND B AND C'],
        note: 'Tie unused inputs to VCC and add a pull up resistor to each used output.',
      },
    ],
    pinout: [
      { pin: 1, name: '1A', type: 'input', description: 'Gate 1 input A' },
      { pin: 2, name: '1B', type: 'input', description: 'Gate 1 input B' },
      { pin: 3, name: '2A', type: 'input', description: 'Gate 2 input A' },
      { pin: 4, name: '2B', type: 'input', description: 'Gate 2 input B' },
      { pin: 5, name: '2C', type: 'input', description: 'Gate 2 input C' },
      { pin: 6, name: '2Y', type: 'output', description: 'Gate 2 open-collector AND output' },
      { pin: 7, name: 'GND', type: 'power', description: 'Ground (0V)' },
      { pin: 8, name: '3Y', type: 'output', description: 'Gate 3 open-collector AND output' },
      { pin: 9, name: '3A', type: 'input', description: 'Gate 3 input A' },
      { pin: 10, name: '3B', type: 'input', description: 'Gate 3 input B' },
      { pin: 11, name: '3C', type: 'input', description: 'Gate 3 input C' },
      { pin: 12, name: '1Y', type: 'output', description: 'Gate 1 open-collector AND output' },
      { pin: 13, name: '1C', type: 'input', description: 'Gate 1 input C' },
      { pin: 14, name: 'VCC', type: 'power', description: 'Positive supply (+5V)' },
    ],
    gates: [
      { type: 'AND', inputs: ['1A', '1B', '1C'], output: '1Y' },
      { type: 'AND', inputs: ['2A', '2B', '2C'], output: '2Y' },
      { type: 'AND', inputs: ['3A', '3B', '3C'], output: '3Y' },
    ],
  },

  // ── 7416: Hex Inverter (open collector, high voltage) ───────────────────
  /* Primary source: Texas Instruments, SN7416 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn7416.pdf
     Open-collector output technology: https://en.wikipedia.org/wiki/Open_collector */
  '7416': {
    name: '74x16',
    simpleName: 'Hex NOT (OC, 15V)',
    description: 'Six open-collector inverting buffers/drivers with up to 15V output voltage. (14-pin)',
    guideOverview: 'The 74x16 provides six open-collector inverting drivers rated for outputs up to 15 V. It fills the gap between standard 5V TTL inverters (74x04/05) and the higher-voltage 74x06 (30V). Use it when the load voltage is between 5V and 15V, such as driving 12V indicator LEDs or interfacing to CMOS logic at an intermediate supply.',
    guidePinDescriptions: {
      '1A': 'Input of inverter 1.',
      '1Y': 'Open-collector output of inverter 1. Inverts 1A; rated to 15 V.',
      '2A': 'Input of inverter 2.',
      '2Y': 'Open-collector output of inverter 2. Inverts 2A.',
      '3A': 'Input of inverter 3.',
      '3Y': 'Open-collector output of inverter 3. Inverts 3A.',
      'GND': 'Ground reference (pin 7). Common ground for TTL supply and load.',
      '4Y': 'Open-collector output of inverter 4. Inverts 4A.',
      '4A': 'Input of inverter 4.',
      '5Y': 'Open-collector output of inverter 5. Inverts 5A.',
      '5A': 'Input of inverter 5.',
      '6Y': 'Open-collector output of inverter 6. Inverts 6A.',
      '6A': 'Input of inverter 6.',
      'VCC': 'TTL supply (+5 V) at pin 14.',
    },
    pins: 14,
    vcc: 14,
    gnd: 7,
    openCollector: true,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn7416.pdf',
    tags: ['not', 'inverter', 'buffer', 'driver', 'gate', 'logic', 'hex', 'open collector', 'high voltage'],
    guideSections: [
      {
        title: 'Inverting 15V Driver',
        paragraphs: [
          'The output inverts the input and can withstand up to 15 V at the output pin. Connect the pull up to the load supply (up to 15 V). The TTL input logic thresholds remain standard 5V.',
        ],
        note: 'Do not exceed 15 V on any output pin. For loads up to 30 V use the 74x06 instead.',
      },
    ],
    pinout: [
      { pin: 1, name: '1A', type: 'input', description: 'Inverter 1 input' },
      { pin: 2, name: '1Y', type: 'output', description: 'Inverter 1 open-collector output (NOT 1A)' },
      { pin: 3, name: '2A', type: 'input', description: 'Inverter 2 input' },
      { pin: 4, name: '2Y', type: 'output', description: 'Inverter 2 open-collector output (NOT 2A)' },
      { pin: 5, name: '3A', type: 'input', description: 'Inverter 3 input' },
      { pin: 6, name: '3Y', type: 'output', description: 'Inverter 3 open-collector output (NOT 3A)' },
      { pin: 7, name: 'GND', type: 'power', description: 'Ground (0V)' },
      { pin: 8, name: '4Y', type: 'output', description: 'Inverter 4 open-collector output (NOT 4A)' },
      { pin: 9, name: '4A', type: 'input', description: 'Inverter 4 input' },
      { pin: 10, name: '5Y', type: 'output', description: 'Inverter 5 open-collector output (NOT 5A)' },
      { pin: 11, name: '5A', type: 'input', description: 'Inverter 5 input' },
      { pin: 12, name: '6Y', type: 'output', description: 'Inverter 6 open-collector output (NOT 6A)' },
      { pin: 13, name: '6A', type: 'input', description: 'Inverter 6 input' },
      { pin: 14, name: 'VCC', type: 'power', description: 'Positive supply (+5V)' },
    ],
    gates: [
      { type: 'NOT', inputs: ['1A'], output: '1Y' },
      { type: 'NOT', inputs: ['2A'], output: '2Y' },
      { type: 'NOT', inputs: ['3A'], output: '3Y' },
      { type: 'NOT', inputs: ['4A'], output: '4Y' },
      { type: 'NOT', inputs: ['5A'], output: '5Y' },
      { type: 'NOT', inputs: ['6A'], output: '6Y' },
    ],
  },

  // ── 7417: Hex Buffer (open collector, high voltage) ─────────────────────
  /* Primary source: Texas Instruments, SN7417 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn7417.pdf
     Open-collector output technology: https://en.wikipedia.org/wiki/Open_collector */
  '7417': {
    name: '74x17',
    simpleName: 'Hex Buffer (OC, 15V)',
    description: 'Six non-inverting open-collector buffers/drivers with up to 15V output voltage. (14-pin)',
    guideOverview: 'The 74x17 provides six non-inverting open-collector buffers rated to 15 V. It is the non-inverting counterpart to the 74x16. A HIGH input causes the output transistor to conduct, sinking current from the load. Useful for driving active LOW loads at up to 15V while keeping control logic at 5V.',
    guidePinDescriptions: {
      '1A': 'Input of buffer 1.',
      '1Y': 'Open-collector output of buffer 1. Conducts when 1A is HIGH.',
      '2A': 'Input of buffer 2.',
      '2Y': 'Open-collector output of buffer 2. Conducts when 2A is HIGH.',
      '3A': 'Input of buffer 3.',
      '3Y': 'Open-collector output of buffer 3. Conducts when 3A is HIGH.',
      'GND': 'Ground reference (pin 7). Common ground for TTL supply and load.',
      '4Y': 'Open-collector output of buffer 4. Conducts when 4A is HIGH.',
      '4A': 'Input of buffer 4.',
      '5Y': 'Open-collector output of buffer 5. Conducts when 5A is HIGH.',
      '5A': 'Input of buffer 5.',
      '6Y': 'Open-collector output of buffer 6. Conducts when 6A is HIGH.',
      '6A': 'Input of buffer 6.',
      'VCC': 'TTL supply (+5 V) at pin 14.',
    },
    pins: 14,
    vcc: 14,
    gnd: 7,
    openCollector: true,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn7417.pdf',
    tags: ['buffer', 'driver', 'gate', 'logic', 'hex', 'open collector', 'high voltage', 'non-inverting'],
    guideSections: [
      {
        title: 'Non-Inverting 15V Buffer',
        paragraphs: [
          'Each output passes the input logic state through without inversion, but using an open-collector stage capable of sinking current at up to 15 V. A pull up to the load rail is required.',
        ],
        note: 'Do not exceed 15 V on any output pin. For loads up to 30 V use the 74x07 instead.',
      },
    ],
    pinout: [
      { pin: 1, name: '1A', type: 'input', description: 'Buffer 1 input' },
      { pin: 2, name: '1Y', type: 'output', description: 'Buffer 1 open-collector output (= 1A)' },
      { pin: 3, name: '2A', type: 'input', description: 'Buffer 2 input' },
      { pin: 4, name: '2Y', type: 'output', description: 'Buffer 2 open-collector output (= 2A)' },
      { pin: 5, name: '3A', type: 'input', description: 'Buffer 3 input' },
      { pin: 6, name: '3Y', type: 'output', description: 'Buffer 3 open-collector output (= 3A)' },
      { pin: 7, name: 'GND', type: 'power', description: 'Ground (0V)' },
      { pin: 8, name: '4Y', type: 'output', description: 'Buffer 4 open-collector output (= 4A)' },
      { pin: 9, name: '4A', type: 'input', description: 'Buffer 4 input' },
      { pin: 10, name: '5Y', type: 'output', description: 'Buffer 5 open-collector output (= 5A)' },
      { pin: 11, name: '5A', type: 'input', description: 'Buffer 5 input' },
      { pin: 12, name: '6Y', type: 'output', description: 'Buffer 6 open-collector output (= 6A)' },
      { pin: 13, name: '6A', type: 'input', description: 'Buffer 6 input' },
      { pin: 14, name: 'VCC', type: 'power', description: 'Positive supply (+5V)' },
    ],
    gates: [
      { type: 'BUFFER', inputs: ['1A'], output: '1Y' },
      { type: 'BUFFER', inputs: ['2A'], output: '2Y' },
      { type: 'BUFFER', inputs: ['3A'], output: '3Y' },
      { type: 'BUFFER', inputs: ['4A'], output: '4Y' },
      { type: 'BUFFER', inputs: ['5A'], output: '5Y' },
      { type: 'BUFFER', inputs: ['6A'], output: '6Y' },
    ],
  },

  // ── 7421: Dual 4 input AND ──────────────────────────────────────────────
  /* Primary source: Texas Instruments, SN74LS21 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls21.pdf */
  '7421': {
    name: '74x21',
    simpleName: 'Dual 4-in AND',
    description: 'Two independent 4 input AND gates. (14-pin)',
    guideOverview: 'The 74x21 contains two independent 4 input AND gates. The output is HIGH only when all four inputs are simultaneously HIGH useful for detecting a specific 4 bit pattern or gating a signal behind three simultaneous enable conditions. Pins 3 and 11 are NC (not connected).',
    guidePinDescriptions: {
      '1A': 'Input A of AND gate 1.',
      '1B': 'Input B of AND gate 1.',
      'NC': 'Not connected leave unconnected.',
      '1C': 'Input C of AND gate 1.',
      '1D': 'Input D of AND gate 1.',
      '1Y': 'Output of gate 1. HIGH only when 1A, 1B, 1C, and 1D are all HIGH.',
      'GND': 'Ground reference (pin 7).',
      '2Y': 'Output of gate 2. HIGH only when 2A, 2B, 2C, and 2D are all HIGH.',
      '2A': 'Input A of AND gate 2.',
      '2B': 'Input B of AND gate 2.',
      '2C': 'Input C of AND gate 2.',
      '2D': 'Input D of AND gate 2.',
      'VCC': 'Positive supply (+5 V) at pin 14.',
    },
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls21.pdf',
    tags: ['and', 'gate', 'logic', 'dual', '4 input'],
    guideSections: [
      {
        title: '4 Input AND Logic',
        paragraphs: ['All four inputs must be HIGH for the output to go HIGH. Any LOW input forces the output LOW. Tie unused inputs to VCC.'],
        formulas: ['Y = A AND B AND C AND D'],
      },
    ],
    pinout: [
      { pin: 1, name: '1A', type: 'input', description: 'Gate 1 input A' },
      { pin: 2, name: '1B', type: 'input', description: 'Gate 1 input B' },
      { pin: 3, name: 'NC', type: 'nc', description: 'Not connected' },
      { pin: 4, name: '1C', type: 'input', description: 'Gate 1 input C' },
      { pin: 5, name: '1D', type: 'input', description: 'Gate 1 input D' },
      { pin: 6, name: '1Y', type: 'output', description: 'Gate 1 AND output' },
      { pin: 7, name: 'GND', type: 'power', description: 'Ground (0V)' },
      { pin: 8, name: '2Y', type: 'output', description: 'Gate 2 AND output' },
      { pin: 9, name: '2A', type: 'input', description: 'Gate 2 input A' },
      { pin: 10, name: '2B', type: 'input', description: 'Gate 2 input B' },
      { pin: 11, name: 'NC', type: 'nc', description: 'Not connected' },
      { pin: 12, name: '2C', type: 'input', description: 'Gate 2 input C' },
      { pin: 13, name: '2D', type: 'input', description: 'Gate 2 input D' },
      { pin: 14, name: 'VCC', type: 'power', description: 'Positive supply (+5V)' },
    ],
    gates: [
      { type: 'AND', inputs: ['1A', '1B', '1C', '1D'], output: '1Y' },
      { type: 'AND', inputs: ['2A', '2B', '2C', '2D'], output: '2Y' },
    ],
  },

  // ── 7422: Dual 4 input NAND (open collector) ───────────────────────────
  /* Primary source: Texas Instruments, SN74LS22 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls22.pdf
     Open-collector output technology: https://en.wikipedia.org/wiki/Open_collector */
  '7422': {
    name: '74x22',
    simpleName: 'Dual 4-in NAND (OC)',
    description: 'Two independent 4 input NAND gates with open-collector outputs. (14-pin)',
    guideOverview: 'The 74x22 provides two 4 input NAND gates with open-collector outputs. The output pulls LOW only when all four inputs are HIGH. External pull up resistors are required. Allows wire-ANDing and interfacing to higher voltage loads.',
    guidePinDescriptions: {
      '1A': 'Input A of NAND gate 1.',
      '1B': 'Input B of NAND gate 1.',
      'NC': 'Not connected leave unconnected.',
      '1C': 'Input C of NAND gate 1.',
      '1D': 'Input D of NAND gate 1.',
      '1Y':  'Open-collector output of gate 1 (active LOW, open collector). Pulls LOW only when all four inputs are HIGH.',
      'GND': 'Ground reference (pin 7).',
      '2Y':  'Open-collector output of gate 2 (active LOW, open collector). Pulls LOW only when all four inputs are HIGH.',
      '2A': 'Input A of NAND gate 2.',
      '2B': 'Input B of NAND gate 2.',
      '2C': 'Input C of NAND gate 2.',
      '2D': 'Input D of NAND gate 2.',
      'VCC': 'Positive supply (+5 V) at pin 14.',
    },
    pins: 14,
    vcc: 14,
    gnd: 7,
    openCollector: true,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls22.pdf',
    tags: ['nand', 'gate', 'logic', 'dual', '4 input', 'open collector'],
    guideSections: [
      {
        title: 'Open Collector 4 Input NAND',
        paragraphs: ['Y = NOT(A AND B AND C AND D). Output pulls LOW only when all four inputs are HIGH. Requires external pull up resistor.'],
        note: 'Tie unused inputs to VCC to prevent spurious LOW outputs.',
      },
    ],
    pinout: [
      { pin: 1, name: '1A', type: 'input', description: 'Gate 1 input A' },
      { pin: 2, name: '1B', type: 'input', description: 'Gate 1 input B' },
      { pin: 3, name: 'NC', type: 'nc', description: 'Not connected' },
      { pin: 4, name: '1C', type: 'input', description: 'Gate 1 input C' },
      { pin: 5, name: '1D', type: 'input', description: 'Gate 1 input D' },
      { pin: 6, name: '1Y', type: 'output', description: 'Gate 1 open-collector NAND output' },
      { pin: 7, name: 'GND', type: 'power', description: 'Ground (0V)' },
      { pin: 8, name: '2Y', type: 'output', description: 'Gate 2 open-collector NAND output' },
      { pin: 9, name: '2A', type: 'input', description: 'Gate 2 input A' },
      { pin: 10, name: '2B', type: 'input', description: 'Gate 2 input B' },
      { pin: 11, name: 'NC', type: 'nc', description: 'Not connected' },
      { pin: 12, name: '2C', type: 'input', description: 'Gate 2 input C' },
      { pin: 13, name: '2D', type: 'input', description: 'Gate 2 input D' },
      { pin: 14, name: 'VCC', type: 'power', description: 'Positive supply (+5V)' },
    ],
    gates: [
      { type: 'NAND', inputs: ['1A', '1B', '1C', '1D'], output: '1Y' },
      { type: 'NAND', inputs: ['2A', '2B', '2C', '2D'], output: '2Y' },
    ],
  },

  // ── 7425: Dual 4 input NOR with strobe ─────────────────────────────────
  /* Primary source: Texas Instruments, SN74LS25 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls25.pdf */
  '7425': {
    name: '74x25',
    simpleName: 'Dual 4-in NOR (strobe)',
    description: 'Two independent 4 input NOR gates, each with an active HIGH strobe (enable) input. (14-pin)',
    guideOverview: 'The 74x25 contains two 4 input NOR gates, each with an additional active HIGH strobe (enable) input. When the strobe (1G or 2G) is LOW, the gate functions as a normal NOR: output is HIGH only when all four data inputs are LOW. When the strobe is HIGH, the output is forced LOW regardless of the data inputs. This allows controlled disabling of each NOR section independently.',
    guidePinDescriptions: {
      '1A':  'Input A of NOR gate 1.',
      '1B':  'Input B of NOR gate 1.',
      '1G':  'Strobe (enable) for gate 1 (active HIGH). HIGH forces 1Y LOW. LOW allows normal NOR operation.',
      '1C':  'Input C of NOR gate 1.',
      '1D':  'Input D of NOR gate 1.',
      '1Y':  'NOR output of gate 1. HIGH only when 1G=LOW and all four data inputs are LOW.',
      'GND': 'Ground reference (pin 7).',
      '2Y':  'NOR output of gate 2. HIGH only when 2G=LOW and all four data inputs are LOW.',
      '2A':  'Input A of NOR gate 2.',
      '2B':  'Input B of NOR gate 2.',
      '2G':  'Strobe (enable) for gate 2 (active HIGH). HIGH forces 2Y LOW.',
      '2C':  'Input C of NOR gate 2.',
      '2D':  'Input D of NOR gate 2.',
      'VCC': 'Positive supply (+5 V) at pin 14.',
    },
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls25.pdf',
    tags: ['nor', 'gate', 'logic', 'dual', '4 input', 'strobe', 'enable'],
    guideSections: [
      {
        title: 'NOR with Strobe Logic',
        paragraphs: [
          'The strobe pin adds an extra active HIGH input to the NOR gate. Effectively the gate computes: Y = NOR(G, A, B, C, D). Setting G HIGH is equivalent to asserting a HIGH on any input the NOR output goes LOW.',
          'The strobe is useful for selectively activating one of several NOR sections sharing a bus, or for generating controlled pulses by briefly asserting the strobe.',
        ],
        note: 'This chip is simulated as a standard 5 input NOR gate with 1G/2G treated as a regular data input.',
      },
    ],
    pinout: [
      { pin: 1, name: '1A', type: 'input', description: 'Gate 1 data input A' },
      { pin: 2, name: '1B', type: 'input', description: 'Gate 1 data input B' },
      { pin: 3, name: '1G', type: 'input', description: 'Gate 1 strobe (active HIGH disables gate, forces output LOW)' },
      { pin: 4, name: '1C', type: 'input', description: 'Gate 1 data input C' },
      { pin: 5, name: '1D', type: 'input', description: 'Gate 1 data input D' },
      { pin: 6, name: '1Y', type: 'output', description: 'Gate 1 NOR output' },
      { pin: 7, name: 'GND', type: 'power', description: 'Ground (0V)' },
      { pin: 8, name: '2Y', type: 'output', description: 'Gate 2 NOR output' },
      { pin: 9, name: '2A', type: 'input', description: 'Gate 2 data input A' },
      { pin: 10, name: '2B', type: 'input', description: 'Gate 2 data input B' },
      { pin: 11, name: '2G', type: 'input', description: 'Gate 2 strobe (active HIGH disables gate, forces output LOW)' },
      { pin: 12, name: '2C', type: 'input', description: 'Gate 2 data input C' },
      { pin: 13, name: '2D', type: 'input', description: 'Gate 2 data input D' },
      { pin: 14, name: 'VCC', type: 'power', description: 'Positive supply (+5V)' },
    ],
    gates: [
      { type: 'NOR', inputs: ['1A', '1B', '1C', '1D', '1G'], output: '1Y' },
      { type: 'NOR', inputs: ['2A', '2B', '2C', '2D', '2G'], output: '2Y' },
    ],
  },

  // ── 7427: Triple 3 input NOR ────────────────────────────────────────────
  /* Primary source: Texas Instruments, SN74LS27 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls27.pdf */
  '7427': {
    name: '74x27',
    simpleName: 'Triple 3 input NOR',
    description: 'Three independent 3 input NOR gates. (14-pin)',
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls27.pdf',
    tags: ['nor', 'gate', 'logic', 'triple', '3 input'],
    guideOverview: 'The 74x27 gives you three 3 input NOR gates in one 14-pin package. A NOR gate outputs HIGH only when every input is LOW even a single HIGH input drives the output LOW.',
    guidePinDescriptions: {
      '1A':  'Input A of NOR gate 1.',
      '1B':  'Input B of NOR gate 1.',
      '2A':  'Input A of NOR gate 2.',
      '2B':  'Input B of NOR gate 2.',
      '2C':  'Input C of NOR gate 2.',
      '2Y':  'Output of gate 2. HIGH only when 2A, 2B, and 2C are all LOW.',
      'GND': 'Ground reference (pin 7).',
      '3Y':  'Output of gate 3. HIGH only when 3A, 3B, and 3C are all LOW.',
      '3A':  'Input A of NOR gate 3.',
      '3B':  'Input B of NOR gate 3.',
      '3C':  'Input C of NOR gate 3.',
      '1Y':  'Output of gate 1. HIGH only when 1A, 1B, and 1C are all LOW.',
      '1C':  'Input C of NOR gate 1.',
      'VCC': 'Positive supply (+5 V) at pin 14.',
    },
    guideSections: [
      {
        title: 'NOR Logic Function',
        paragraphs: ['A NOR gate is the complement of OR: output is HIGH only when all inputs are LOW. One or more HIGH inputs forces the output LOW.'],
        formulas: ['Y = NOT(A OR B OR C)'],
        list: ['Tie two inputs together for a 2 input NOR.', 'Two cascaded NOR gates form a NOT-NOR = OR gate.'],
      },
    ],
    pinout: [
      { pin: 1, name: '1A', type: 'input', description: 'Gate 1 input A' },
      { pin: 2, name: '1B', type: 'input', description: 'Gate 1 input B' },
      { pin: 3, name: '2A', type: 'input', description: 'Gate 2 input A' },
      { pin: 4, name: '2B', type: 'input', description: 'Gate 2 input B' },
      { pin: 5, name: '2C', type: 'input', description: 'Gate 2 input C' },
      { pin: 6, name: '2Y', type: 'output', description: 'Gate 2 output: HIGH only when 2A, 2B, and 2C are all LOW' },
      { pin: 7, name: 'GND', type: 'power', description: 'Ground (0 V)' },
      { pin: 8, name: '3Y', type: 'output', description: 'Gate 3 output: HIGH only when 3A, 3B, and 3C are all LOW' },
      { pin: 9, name: '3A', type: 'input', description: 'Gate 3 input A' },
      { pin: 10, name: '3B', type: 'input', description: 'Gate 3 input B' },
      { pin: 11, name: '3C', type: 'input', description: 'Gate 3 input C' },
      { pin: 12, name: '1Y', type: 'output', description: 'Gate 1 output: HIGH only when 1A, 1B, and 1C are all LOW' },
      { pin: 13, name: '1C', type: 'input', description: 'Gate 1 input C' },
      { pin: 14, name: 'VCC', type: 'power', description: 'Positive supply (+5 V)' },
    ],
    gates: [
      { type: 'NOR', inputs: ['1A', '1B', '1C'], output: '1Y' },
      { type: 'NOR', inputs: ['2A', '2B', '2C'], output: '2Y' },
      { type: 'NOR', inputs: ['3A', '3B', '3C'], output: '3Y' },
    ],
  },

  // ── 7430: 8-input NAND ─────────────────────────────────────────────────
  /* Primary source: Texas Instruments, SN74LS30 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls30.pdf */
  '7430': {
    name: '74x30',
    simpleName: '8-input NAND',
    description: '8-input NAND gate (14-pin)',
    guideOverview: 'The 74x30 is a single 8-input NAND gate. The output is LOW only when all eight inputs (A H) are simultaneously HIGH. It is commonly used to detect an 8 bit all-ones condition or as a wired AND enable. Pins 9, 10, and 13 are NC (not connected).',
    guidePinDescriptions: {
      'A': 'Input A (pin 1).',
      'B': 'Input B (pin 2).',
      'C': 'Input C (pin 3).',
      'D': 'Input D (pin 4).',
      'E': 'Input E (pin 5).',
      'F': 'Input F (pin 6).',
      'GND': 'Ground reference (pin 7).',
      'Y': 'NAND output (pin 8). LOW only when all inputs A H are HIGH.',
      'NC1': 'Not connected (pin 9).',
      'NC2': 'Not connected (pin 10).',
      'G': 'Input G (pin 11).',
      'H': 'Input H (pin 12).',
      'NC3': 'Not connected (pin 13).',
      'VCC': 'Positive supply (+5 V) at pin 14.',
    },
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls30.pdf',
    tags: ['nand', 'gate', 'logic', '8-input'],
    guideSections: [
      {
        title: '8-Input NAND',
        paragraphs: ['The single gate produces LOW only when all eight inputs are HIGH simultaneously. Any LOW input holds the output HIGH.'],
        formulas: ['Y = NOT(A AND B AND C AND D AND E AND F AND G AND H)'],
        note: 'Tie unused inputs to VCC so they do not affect the output.',
      },
    ],
    pinout: [
      { pin: 1, name: 'A', type: 'input' },
      { pin: 2, name: 'B', type: 'input' },
      { pin: 3, name: 'C', type: 'input' },
      { pin: 4, name: 'D', type: 'input' },
      { pin: 5, name: 'E', type: 'input' },
      { pin: 6, name: 'F', type: 'input' },
      { pin: 7, name: 'GND', type: 'power' },
      { pin: 8, name: 'Y', type: 'output' },
      { pin: 9, name: 'NC1', type: 'nc' },
      { pin: 10, name: 'NC2', type: 'nc' },
      { pin: 11, name: 'G', type: 'input' },
      { pin: 12, name: 'H', type: 'input' },
      { pin: 13, name: 'NC3', type: 'nc' },
      { pin: 14, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'NAND', inputs: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'], output: 'Y' },
    ],
  },

  // ── 7437: Quad 2 input NAND (buffer) ────────────────────────────────────
  /* Primary source: Texas Instruments, SN74LS37 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls37.pdf */
  '7437': {
    name: '74x37',
    simpleName: 'Quad 2 Input NAND Buffer',
    description: 'Quad 2 input NAND gate with buffered outputs. (14-pin)',
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls37.pdf',
    tags: ['nand', 'gate', 'logic', 'quad', 'buffer', 'TTL'],
    guideOverview: 'The 7437 contains four independent 2 input NAND gates with buffered outputs. The buffered outputs allow it to sink more current than the standard 7400 the 74x37 can sink up to 8 mA and the 7437 (original) up to 48 mA per output making it suitable for driving larger loads or multiple inputs without risking output voltage sag.',
    guidePinDescriptions: {
      '1A':  'Input A of gate 1.',
      '1B':  'Input B of gate 1.',
      '1Y':  'Buffered NAND output of gate 1. LOW only when 1A and 1B are both HIGH.',
      '2A':  'Input A of gate 2.',
      '2B':  'Input B of gate 2.',
      '2Y':  'Buffered NAND output of gate 2.',
      GND:   'Ground reference. Connect to 0 V.',
      '3Y':  'Buffered NAND output of gate 3.',
      '3A':  'Input A of gate 3.',
      '3B':  'Input B of gate 3.',
      '4Y':  'Buffered NAND output of gate 4.',
      '4A':  'Input A of gate 4.',
      '4B':  'Input B of gate 4.',
      VCC:   'Positive supply (+5 V TTL).',
    },
    pinout: [
      { pin:  1, name: '1A',  type: 'input',  description: 'Gate 1 input A' },
      { pin:  2, name: '1B',  type: 'input',  description: 'Gate 1 input B' },
      { pin:  3, name: '1Y',  type: 'output', description: 'Gate 1 buffered NAND output: LOW only when 1A and 1B are both HIGH' },
      { pin:  4, name: '2A',  type: 'input',  description: 'Gate 2 input A' },
      { pin:  5, name: '2B',  type: 'input',  description: 'Gate 2 input B' },
      { pin:  6, name: '2Y',  type: 'output', description: 'Gate 2 buffered NAND output' },
      { pin:  7, name: 'GND', type: 'power',  description: 'Ground (0 V)' },
      { pin:  8, name: '3Y',  type: 'output', description: 'Gate 3 buffered NAND output' },
      { pin:  9, name: '3A',  type: 'input',  description: 'Gate 3 input A' },
      { pin: 10, name: '3B',  type: 'input',  description: 'Gate 3 input B' },
      { pin: 11, name: '4Y',  type: 'output', description: 'Gate 4 buffered NAND output' },
      { pin: 12, name: '4A',  type: 'input',  description: 'Gate 4 input A' },
      { pin: 13, name: '4B',  type: 'input',  description: 'Gate 4 input B' },
      { pin: 14, name: 'VCC', type: 'power',  description: 'Positive supply (+5 V)' },
    ],
    gates: [
      { type: 'NAND', inputs: ['1A', '1B'], output: '1Y' },
      { type: 'NAND', inputs: ['2A', '2B'], output: '2Y' },
      { type: 'NAND', inputs: ['3A', '3B'], output: '3Y' },
      { type: 'NAND', inputs: ['4A', '4B'], output: '4Y' },
    ],
    guideSections: [
      {
        title: 'NAND Logic with Buffered Output',
        paragraphs: [
          'A NAND gate outputs LOW only when all inputs are simultaneously HIGH; any LOW input forces the output HIGH.',
          'The 7437 is pin-compatible with the 7400 but provides higher output current. Use it when driving heavy loads or many gate inputs from a single output. The 74x37 sinks up to 8 mA; the original 7437 sinks up to 48 mA.',
        ],
        list: [
          'Tie both inputs together to use a gate as an inverter.',
          'Tie one input HIGH to route the other input through as an inverter.',
          'Chain outputs to wire-OR logic using the open-collector 7438 instead.',
        ],
        note: 'The 7437 is a drop-in replacement for the 7400 in most circuits. Upgrade to it when output loading causes logic-level problems.',
      },
    ],
  },

  // ── 7438: Quad 2 input NAND (open collector, buffered) ─────────────────
  /* Primary source: Texas Instruments, SN74LS38 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls38.pdf
     Open-collector output technology: https://en.wikipedia.org/wiki/Open_collector */
  '7438': {
    name: '74x38',
    simpleName: 'Quad 2 Input NAND (Open Collector)',
    description: 'Quad 2 input NAND gate with buffered open-collector outputs. (14-pin)',
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls38.pdf',
    tags: ['nand', 'gate', 'logic', 'quad', 'open collector', 'TTL'],
    guideOverview: 'The 7438 contains four 2 input NAND gates with open-collector buffered outputs. Open-collector outputs can only sink current they pull the output LOW when active but rely on an external pull up resistor to reach a HIGH level. This allows multiple outputs to be wire-AND connected to a single bus and enables interfacing to circuits with different supply voltages. The 74x38 can sink up to 48 mA per output.',
    guidePinDescriptions: {
      '1A':  'Input A of gate 1.',
      '1B':  'Input B of gate 1.',
      '1Y':  'Open-collector NAND output of gate 1. Pulled LOW when 1A and 1B are both HIGH; open otherwise. Requires external pull up resistor.',
      '2A':  'Input A of gate 2.',
      '2B':  'Input B of gate 2.',
      '2Y':  'Open-collector NAND output of gate 2.',
      GND:   'Ground reference. Connect to 0 V.',
      '3Y':  'Open-collector NAND output of gate 3.',
      '3A':  'Input A of gate 3.',
      '3B':  'Input B of gate 3.',
      '4Y':  'Open-collector NAND output of gate 4.',
      '4A':  'Input A of gate 4.',
      '4B':  'Input B of gate 4.',
      VCC:   'Positive supply (+5 V TTL).',
    },
    pinout: [
      { pin:  1, name: '1A',  type: 'input',  description: 'Gate 1 input A' },
      { pin:  2, name: '1B',  type: 'input',  description: 'Gate 1 input B' },
      { pin:  3, name: '1Y',  type: 'output', description: 'Gate 1 open-collector NAND output. LOW when 1A and 1B are both HIGH; open otherwise' },
      { pin:  4, name: '2A',  type: 'input',  description: 'Gate 2 input A' },
      { pin:  5, name: '2B',  type: 'input',  description: 'Gate 2 input B' },
      { pin:  6, name: '2Y',  type: 'output', description: 'Gate 2 open-collector NAND output' },
      { pin:  7, name: 'GND', type: 'power',  description: 'Ground (0 V)' },
      { pin:  8, name: '3Y',  type: 'output', description: 'Gate 3 open-collector NAND output' },
      { pin:  9, name: '3A',  type: 'input',  description: 'Gate 3 input A' },
      { pin: 10, name: '3B',  type: 'input',  description: 'Gate 3 input B' },
      { pin: 11, name: '4Y',  type: 'output', description: 'Gate 4 open-collector NAND output' },
      { pin: 12, name: '4A',  type: 'input',  description: 'Gate 4 input A' },
      { pin: 13, name: '4B',  type: 'input',  description: 'Gate 4 input B' },
      { pin: 14, name: 'VCC', type: 'power',  description: 'Positive supply (+5 V)' },
    ],
    gates: [
      { type: 'NAND', inputs: ['1A', '1B'], output: '1Y' },
      { type: 'NAND', inputs: ['2A', '2B'], output: '2Y' },
      { type: 'NAND', inputs: ['3A', '3B'], output: '3Y' },
      { type: 'NAND', inputs: ['4A', '4B'], output: '4Y' },
    ],
    guideSections: [
      {
        title: 'Open Collector NAND Output',
        paragraphs: [
          'Open-collector outputs cannot source current they can only pull the line LOW. An external pull up resistor (typically 1 10 kΩ to VCC) is required for each output to achieve a logic HIGH level.',
          'Because the output only actively drives LOW, multiple open-collector outputs can be connected to the same wire (wire-AND). If any one output is LOW, the shared line goes LOW. This is useful for interrupt buses and I²C-style communication.',
          'The open-collector structure also lets you interface to a bus at a different voltage than VCC by pulling up to that higher rail through the resistor, as long as the transistor breakdown voltage is not exceeded.',
        ],
        list: [
          'Always add a pull up resistor outputs will float HIGH without one.',
          'Wire-AND: connect multiple 7438 outputs together with a single shared pull up to create logical AND across the outputs.',
          'Pin-compatible with 7400 and 7437; use when wire-AND or level-shifting is needed.',
        ],
        note: '74Sim models open-collector outputs as standard NAND logic. The Hi-Z open state and pull up resistor behavior are not simulated.',
      },
    ],
  },

  // ── 7440: Dual 4 input NAND (buffer) ───────────────────────────────────
  /* Primary source: Texas Instruments, SN74LS40 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls40.pdf */
  '7440': {
    name: '74x40',
    simpleName: 'Dual 4 input NAND Buffer',
    description: 'Two 4 input NAND gates with buffered outputs. (14-pin)',
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls40.pdf',
    tags: ['nand', 'gate', 'logic', 'dual', '4 input', 'buffer'],
    guideOverview: 'The 74x40 contains two 4 input NAND gates with buffered (high-current) outputs. It is functionally identical to the 74x20 but delivers more drive current, making it suitable for directly driving larger loads. Pins 3 and 11 are not connected (NC) and serve no logic function.',
    guidePinDescriptions: {
      '1A':  'Input A of NAND gate 1.',
      '1B':  'Input B of NAND gate 1.',
      'NC1': 'Not connected (pin 3). Leave unconnected.',
      '1C':  'Input C of NAND gate 1.',
      '1D':  'Input D of NAND gate 1.',
      '1Y':  'Buffered NAND output of gate 1. LOW only when all four inputs are HIGH.',
      'GND': 'Ground reference (pin 7).',
      '2Y':  'Buffered NAND output of gate 2.',
      '2A':  'Input A of NAND gate 2.',
      '2B':  'Input B of NAND gate 2.',
      'NC2': 'Not connected (pin 11). Leave unconnected.',
      '2C':  'Input C of NAND gate 2.',
      '2D':  'Input D of NAND gate 2.',
      'VCC': 'Positive supply (+5 V) at pin 14.',
    },
    guideSections: [
      {
        title: 'Buffered 4 Input NAND',
        paragraphs: ['The 74x40 is pin-compatible with the 74x20 but uses a buffered output stage for higher sink/source current. Use it when the NAND output must drive many TTL inputs or heavier loads without voltage-level degradation.'],
        formulas: ['Y = NOT(A AND B AND C AND D)'],
        note: 'Tie unused inputs to VCC to keep them from affecting the output.',
      },
    ],
    pinout: [
      { pin: 1,  name: '1A',  type: 'input',  description: 'Gate 1 input A' },
      { pin: 2,  name: '1B',  type: 'input',  description: 'Gate 1 input B' },
      { pin: 3,  name: 'NC1', type: 'nc',     description: 'Not connected leave unconnected' },
      { pin: 4,  name: '1C',  type: 'input',  description: 'Gate 1 input C' },
      { pin: 5,  name: '1D',  type: 'input',  description: 'Gate 1 input D' },
      { pin: 6,  name: '1Y',  type: 'output', description: 'Gate 1 output (buffered): LOW only when 1A, 1B, 1C, and 1D are all HIGH' },
      { pin: 7,  name: 'GND', type: 'power',  description: 'Ground (0 V)' },
      { pin: 8,  name: '2Y',  type: 'output', description: 'Gate 2 output (buffered): LOW only when 2A, 2B, 2C, and 2D are all HIGH' },
      { pin: 9,  name: '2A',  type: 'input',  description: 'Gate 2 input A' },
      { pin: 10, name: '2B',  type: 'input',  description: 'Gate 2 input B' },
      { pin: 11, name: 'NC2', type: 'nc',     description: 'Not connected leave unconnected' },
      { pin: 12, name: '2C',  type: 'input',  description: 'Gate 2 input C' },
      { pin: 13, name: '2D',  type: 'input',  description: 'Gate 2 input D' },
      { pin: 14, name: 'VCC', type: 'power',  description: 'Positive supply (+5 V)' },
    ],
    gates: [
      { type: 'NAND', inputs: ['1A', '1B', '1C', '1D'], output: '1Y' },
      { type: 'NAND', inputs: ['2A', '2B', '2C', '2D'], output: '2Y' },
    ],
  },

  // ── 7442: BCD to Decimal Decoder ────────────────────────────────────────
  /* Primary source: Texas Instruments, SN74LS42 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls42.pdf
     Decoder/demultiplexer concept: https://en.wikipedia.org/wiki/Multiplexer */
  '7442': {
    name: '74x42',
    simpleName: 'BCD-to-Decimal Decoder',
    description: 'BCD to decimal 1-of-10 decoder. (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls42.pdf',
    tags: ['decoder', 'bcd', 'decimal', '1-of-10', '1 of 10', 'demultiplexer', 'active low'],
    guideOverview: 'The 74x42 decodes a 4 bit BCD code into one of ten mutually exclusive active LOW outputs. Only the output matching the BCD value (0 9) goes LOW; all others remain HIGH. Invalid codes (10 15) leave every output HIGH. Commonly used to select one of up to ten devices from a BCD counter output.',
    guidePinDescriptions: {
      'Y0':  'Active LOW decoded output for decimal 0. LOW when DCBA = 0000.',
      'Y1':  'Active LOW decoded output for decimal 1. LOW when DCBA = 0001.',
      'Y2':  'Active LOW decoded output for decimal 2. LOW when DCBA = 0010.',
      'Y3':  'Active LOW decoded output for decimal 3. LOW when DCBA = 0011.',
      'Y4':  'Active LOW decoded output for decimal 4. LOW when DCBA = 0100.',
      'Y5':  'Active LOW decoded output for decimal 5. LOW when DCBA = 0101.',
      'Y6':  'Active LOW decoded output for decimal 6. LOW when DCBA = 0110.',
      'GND': 'Ground reference (pin 8).',
      'Y7':  'Active LOW decoded output for decimal 7. LOW when DCBA = 0111.',
      'Y8':  'Active LOW decoded output for decimal 8. LOW when DCBA = 1000.',
      'Y9':  'Active LOW decoded output for decimal 9. LOW when DCBA = 1001.',
      'D':   'BCD input bit 3 (MSB). When D=1 and C=1, all outputs go HIGH (invalid codes 10 15).',
      'C':   'BCD input bit 2.',
      'B':   'BCD input bit 1.',
      'A':   'BCD input bit 0 (LSB).',
      'VCC': 'Positive supply (+5 V) at pin 16.',
    },
    guideSections: [
      {
        title: 'BCD to Decimal Decoding',
        paragraphs: [
          'BCD (Binary-Coded Decimal) represents decimal digits 0 9 as 4 bit binary codes. The 74x42 takes a 4 bit BCD word (A=LSB, D=MSB) and activates exactly one of ten active LOW outputs corresponding to the decimal value.',
          'Input codes 10 15 (which are not valid BCD digits) produce no active output all outputs remain HIGH. This provides built in protection against undefined decoder states.',
        ],
        list: [
          'Use with a BCD counter (e.g., 74x90) to cycle through ten devices.',
          'Connect D to a common enable: when D=1 all outputs are disabled (all HIGH).',
          'Wire multiple 74x42s to decode larger address spaces.',
        ],
      },
    ],
    pinout: [
      { pin: 1,  name: 'Y0',  type: 'output', description: 'Active LOW decoded output for decimal 0 goes LOW when BCD input = 0000' },
      { pin: 2,  name: 'Y1',  type: 'output', description: 'Active LOW decoded output for decimal 1 goes LOW when BCD input = 0001' },
      { pin: 3,  name: 'Y2',  type: 'output', description: 'Active LOW decoded output for decimal 2 goes LOW when BCD input = 0010' },
      { pin: 4,  name: 'Y3',  type: 'output', description: 'Active LOW decoded output for decimal 3 goes LOW when BCD input = 0011' },
      { pin: 5,  name: 'Y4',  type: 'output', description: 'Active LOW decoded output for decimal 4 goes LOW when BCD input = 0100' },
      { pin: 6,  name: 'Y5',  type: 'output', description: 'Active LOW decoded output for decimal 5 goes LOW when BCD input = 0101' },
      { pin: 7,  name: 'Y6',  type: 'output', description: 'Active LOW decoded output for decimal 6 goes LOW when BCD input = 0110' },
      { pin: 8,  name: 'GND', type: 'power',  description: 'Ground (0 V)' },
      { pin: 9,  name: 'Y7',  type: 'output', description: 'Active LOW decoded output for decimal 7 goes LOW when BCD input = 0111' },
      { pin: 10, name: 'Y8',  type: 'output', description: 'Active LOW decoded output for decimal 8 goes LOW when BCD input = 1000' },
      { pin: 11, name: 'Y9',  type: 'output', description: 'Active LOW decoded output for decimal 9 goes LOW when BCD input = 1001' },
      { pin: 12, name: 'D',   type: 'input',  description: 'BCD input bit 3 (MSB). D=1 forces all outputs HIGH (no valid decode) also acts as active HIGH disable for 1-of-8 use.' },
      { pin: 13, name: 'C',   type: 'input',  description: 'BCD input bit 2' },
      { pin: 14, name: 'B',   type: 'input',  description: 'BCD input bit 1' },
      { pin: 15, name: 'A',   type: 'input',  description: 'BCD input bit 0 (LSB)' },
      { pin: 16, name: 'VCC', type: 'power',  description: 'Positive supply (+5 V)' },
    ],
    gates: [
      {
        type: 'BCD_DECIMAL',
        inputs: ['A', 'B', 'C', 'D'],
        outputs: ['Y0', 'Y1', 'Y2', 'Y3', 'Y4', 'Y5', 'Y6', 'Y7', 'Y8', 'Y9'],
      },
    ],
  },

  // ── 7445: BCD to Decimal Decoder/Driver (open collector) ───────────────
  /* Primary source: Texas Instruments, SN7445A datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn7445a.pdf
     Open-collector output technology: https://en.wikipedia.org/wiki/Open_collector
     Decoder/demultiplexer concept: https://en.wikipedia.org/wiki/Multiplexer */
  '7445': {
    name: '74x45',
    simpleName: 'BCD to Decimal (OC)',
    description: 'BCD to decimal decoder/driver (open collector) (16-pin)',
    guideOverview: 'The 74x45 is the open-collector version of the 74x42 BCD-to-decimal decoder. It decodes a 4 bit BCD input into one of ten active LOW outputs, but uses open-collector transistor outputs capable of sinking up to 80 mA at up to 30 V. This makes it suitable for directly driving indicator lamps, relays, high-current LEDs, or other loads that exceed standard TTL output capabilities.',
    guidePinDescriptions: {
      'Y0':  'Active LOW open-collector output for decimal 0. Conducts when DCBA = 0000.',
      'Y1':  'Active LOW open-collector output for decimal 1. Conducts when DCBA = 0001.',
      'Y2':  'Active LOW open-collector output for decimal 2.',
      'Y3':  'Active LOW open-collector output for decimal 3.',
      'Y4':  'Active LOW open-collector output for decimal 4.',
      'Y5':  'Active LOW open-collector output for decimal 5.',
      'Y6':  'Active LOW open-collector output for decimal 6.',
      'GND': 'Ground reference (pin 8). Common ground for TTL supply and output load.',
      'Y7':  'Active LOW open-collector output for decimal 7.',
      'Y8':  'Active LOW open-collector output for decimal 8.',
      'Y9':  'Active LOW open-collector output for decimal 9. Conducts when DCBA = 1001.',
      'D':   'BCD input bit 3 (MSB).',
      'C':   'BCD input bit 2.',
      'B':   'BCD input bit 1.',
      'A':   'BCD input bit 0 (LSB).',
      'VCC': 'TTL supply (+5 V) at pin 16.',
    },
    guideSections: [
      {
        title: 'High-Current BCD Decoder',
        paragraphs: [
          'Identical decoding logic to the 74x42 one of ten active LOW outputs goes LOW for each valid BCD input code 0 9. Invalid codes (10 15) leave all outputs off.',
          'The open-collector outputs can sink up to 80 mA and withstand up to 30 V, so they can directly drive lamps, relays, and LEDs without additional driver transistors.',
        ],
        note: 'Add a pull up resistor to VCC (or load voltage) for each output used. Do not exceed 30 V or 80 mA per output.',
      },
    ],
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn7445a.pdf',
    tags: ['decoder', 'bcd', 'decimal', '1-of-10', 'driver', 'open collector'],
    pinout: [
      { pin: 1, name: 'Y0', type: 'output' },
      { pin: 2, name: 'Y1', type: 'output' },
      { pin: 3, name: 'Y2', type: 'output' },
      { pin: 4, name: 'Y3', type: 'output' },
      { pin: 5, name: 'Y4', type: 'output' },
      { pin: 6, name: 'Y5', type: 'output' },
      { pin: 7, name: 'Y6', type: 'output' },
      { pin: 8, name: 'GND', type: 'power' },
      { pin: 9, name: 'Y7', type: 'output' },
      { pin: 10, name: 'Y8', type: 'output' },
      { pin: 11, name: 'Y9', type: 'output' },
      { pin: 12, name: 'D', type: 'input' },
      { pin: 13, name: 'C', type: 'input' },
      { pin: 14, name: 'B', type: 'input' },
      { pin: 15, name: 'A', type: 'input' },
      { pin: 16, name: 'VCC', type: 'power' },
    ],
    gates: [
      {
        type: 'BCD_DECIMAL',
        inputs: ['A', 'B', 'C', 'D'],
        outputs: ['Y0', 'Y1', 'Y2', 'Y3', 'Y4', 'Y5', 'Y6', 'Y7', 'Y8', 'Y9'],
      },
    ],
  },
};
