// Chip definitions block 37
// Chips: 74694 74699, 74700 74702, 74707, 74710 74712, 74715, 74716, 74718

export const CHIPS_BLOCK_37 = {

  // ── 74694: 4 bit decade counter/latch/mux, sync+async CLR, TRI (20-pin) ──
  /* Primary source: Texas Instruments, 74694 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74als694.pdf
     https://en.wikipedia.org/wiki/Counter_(digital) */
  '74694': {
    name: '74x694',
    simpleName: '4 bit BCD Counter/Latch/Mux (S+A CLR)',
    description: '4 bit decade counter/latch/multiplexer with synchronous and asynchronous clears, tri-state output (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74als694.pdf',
    tags: ['counter', 'bcd', 'decade', 'latch', 'multiplexer', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x694 is a 4 bit BCD (decade) counter with output latch, 2:1 MUX, and both asynchronous (ACLR, active LOW) and synchronous (SCLR, active LOW) clear inputs. ACLR instantly resets; SCLR clears on the next clock edge. Having both allows flexible reset strategies in the same circuit without extra gates.',
    guidePinDescriptions: {
      'CLK':  'Clock input (rising edge).',
      'ACLR': 'Asynchronous Clear (active LOW). Instantly resets counter.',
      'SCLR': 'Synchronous Clear (active LOW). Clears on next clock edge.',
      'D0':   'Parallel load input bit 0.',
      'D1':   'Parallel load input bit 1.',
      'D2':   'Parallel load input bit 2.',
      'D3':   'Parallel load input bit 3.',
      'LE':   'Latch Enable.',
      'S':    'Output Select: LOW = latch; HIGH = counter.',
      'GND':  'Ground reference (pin 10).',
      'OEn':  'Output Enable (active LOW).',
      'Q0':   'Output bit 0.',
      'Q1':   'Output bit 1.',
      'Q2':   'Output bit 2.',
      'Q3':   'Output bit 3.',
      'RCO':  'Ripple Carry Output.',
      'ENT':  'Count Enable T (active LOW).',
      'ENP':  'Count Enable P (active LOW).',
      'LOAD': 'Parallel Load (active LOW).',
      'VCC':  'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'Dual Clear Inputs',
        paragraphs: [
          'ACLR resets the counter immediately regardless of clock; SCLR waits for the next rising edge. This lets designers choose between fast deterministic reset and clean clocked reset from the same IC.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'CLK',  type: 'input'  },
      { pin:  2, name: 'ACLR', type: 'input'  },
      { pin:  3, name: 'SCLR', type: 'input'  },
      { pin:  4, name: 'D0',   type: 'input'  },
      { pin:  5, name: 'D1',   type: 'input'  },
      { pin:  6, name: 'D2',   type: 'input'  },
      { pin:  7, name: 'D3',   type: 'input'  },
      { pin:  8, name: 'LE',   type: 'input'  },
      { pin:  9, name: 'S',    type: 'input'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'OEn',  type: 'input'  },
      { pin: 12, name: 'Q0',   type: 'output' },
      { pin: 13, name: 'Q1',   type: 'output' },
      { pin: 14, name: 'Q2',   type: 'output' },
      { pin: 15, name: 'Q3',   type: 'output' },
      { pin: 16, name: 'RCO',  type: 'output' },
      { pin: 17, name: 'ENT',  type: 'input'  },
      { pin: 18, name: 'ENP',  type: 'input'  },
      { pin: 19, name: 'LOAD', type: 'input'  },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'COUNTER_LATCH_MUX_STUB', inputs: ['CLK','ACLR','SCLR','D0','D1','D2','D3','LE','S','OEn','ENT','ENP','LOAD'], outputs: ['Q0','Q1','Q2','Q3','RCO'] },
    ],
  },

  // ── 74695: 4 bit binary counter/latch/mux, sync+async CLR, TRI (20-pin) ──
  /* Primary source: Texas Instruments, 74695 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74als695.pdf
     https://en.wikipedia.org/wiki/Counter_(digital) */
  '74695': {
    name: '74x695',
    simpleName: '4 bit Binary Counter/Latch/Mux (S+A CLR)',
    description: '4 bit binary counter/latch/multiplexer with synchronous and asynchronous clears, tri-state output (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74als695.pdf',
    tags: ['counter', 'binary', '4 bit', 'latch', 'multiplexer', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x695 is the binary (0-15) version of the 74x694: same dual ACLR (active LOW) / SCLR (active LOW) inputs, output latch, 2:1 MUX, and tri-state outputs. Where 74x694 counts BCD (0-9), 74x695 counts full 4 bit binary (0-15).',
    guidePinDescriptions: {
      'CLK':  'Clock input (rising edge).',
      'ACLR': 'Asynchronous Clear (active LOW).',
      'SCLR': 'Synchronous Clear (active LOW).',
      'D0':   'Parallel load input bit 0.',
      'D1':   'Parallel load input bit 1.',
      'D2':   'Parallel load input bit 2.',
      'D3':   'Parallel load input bit 3.',
      'LE':   'Latch Enable.',
      'S':    'Output Select.',
      'GND':  'Ground reference (pin 10).',
      'OEn':  'Output Enable (active LOW).',
      'Q0':   'Output bit 0.',
      'Q1':   'Output bit 1.',
      'Q2':   'Output bit 2.',
      'Q3':   'Output bit 3.',
      'RCO':  'Ripple Carry Output.',
      'ENT':  'Count Enable T (active LOW).',
      'ENP':  'Count Enable P (active LOW).',
      'LOAD': 'Parallel Load (active LOW).',
      'VCC':  'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: '74x694 vs 74x695',
        paragraphs: [
          'Pin-for-pin compatible; only the counting sequence differs. 74x694 = BCD (decade); 74x695 = binary.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'CLK',  type: 'input'  },
      { pin:  2, name: 'ACLR', type: 'input'  },
      { pin:  3, name: 'SCLR', type: 'input'  },
      { pin:  4, name: 'D0',   type: 'input'  },
      { pin:  5, name: 'D1',   type: 'input'  },
      { pin:  6, name: 'D2',   type: 'input'  },
      { pin:  7, name: 'D3',   type: 'input'  },
      { pin:  8, name: 'LE',   type: 'input'  },
      { pin:  9, name: 'S',    type: 'input'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'OEn',  type: 'input'  },
      { pin: 12, name: 'Q0',   type: 'output' },
      { pin: 13, name: 'Q1',   type: 'output' },
      { pin: 14, name: 'Q2',   type: 'output' },
      { pin: 15, name: 'Q3',   type: 'output' },
      { pin: 16, name: 'RCO',  type: 'output' },
      { pin: 17, name: 'ENT',  type: 'input'  },
      { pin: 18, name: 'ENP',  type: 'input'  },
      { pin: 19, name: 'LOAD', type: 'input'  },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'COUNTER_LATCH_MUX_STUB', inputs: ['CLK','ACLR','SCLR','D0','D1','D2','D3','LE','S','OEn','ENT','ENP','LOAD'], outputs: ['Q0','Q1','Q2','Q3','RCO'] },
    ],
  },

  // ── 74696: 4 bit decade counter/reg/mux, async CLR, TRI (20-pin) ─────────
  /* Primary source: Texas Instruments, 74696 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls696.pdf
     https://en.wikipedia.org/wiki/Counter_(digital) */
  '74696': {
    name: '74x696',
    simpleName: '4 bit BCD Counter/Reg/Mux (Async CLR)',
    description: '4 bit decade counter/register/multiplexer with asynchronous clear, tri-state output (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls696.pdf',
    tags: ['counter', 'bcd', 'decade', 'register', 'multiplexer', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x696 is a 4 bit BCD up/down counter with an output storage register (clocked, not a latch), 2:1 MUX, asynchronous CLR, and tri-state outputs. UD selects count direction. The registered output ensures glitch-free transitions; the MUX selects between counter and register output.',
    guidePinDescriptions: {
      'CLK':  'Clock input (rising edge).',
      'CLR':  'Asynchronous Clear (active LOW).',
      'D0':   'Parallel load input bit 0.',
      'D1':   'Parallel load input bit 1.',
      'D2':   'Parallel load input bit 2.',
      'D3':   'Parallel load input bit 3.',
      'LE':   'Register Load Enable.',
      'S':    'Output Select: LOW = register; HIGH = counter.',
      'OEn':  'Output Enable (active LOW).',
      'GND':  'Ground reference (pin 10).',
      'Q0':   'Output bit 0.',
      'Q1':   'Output bit 1.',
      'Q2':   'Output bit 2.',
      'Q3':   'Output bit 3.',
      'RCO':  'Ripple Carry Output.',
      'ENT':  'Count Enable T (active LOW).',
      'ENP':  'Count Enable P (active LOW).',
      'LOAD': 'Parallel Load (active LOW).',
      'UD':   'Up/Down count direction. HIGH = up; LOW = down.',
      'VCC':  'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'Latch vs Register Output',
        paragraphs: [
          'The 74x690/74x691 group uses a transparent latch for output storage; the 74x696/74x697 group uses a clocked register. A register only updates on a clock edge, eliminating the transparency window that can cause glitches during metastability.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'CLK',  type: 'input'  },
      { pin:  2, name: 'CLR',  type: 'input'  },
      { pin:  3, name: 'D0',   type: 'input'  },
      { pin:  4, name: 'D1',   type: 'input'  },
      { pin:  5, name: 'D2',   type: 'input'  },
      { pin:  6, name: 'D3',   type: 'input'  },
      { pin:  7, name: 'LE',   type: 'input'  },
      { pin:  8, name: 'S',    type: 'input'  },
      { pin:  9, name: 'OEn',  type: 'input'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'Q0',   type: 'output' },
      { pin: 12, name: 'Q1',   type: 'output' },
      { pin: 13, name: 'Q2',   type: 'output' },
      { pin: 14, name: 'Q3',   type: 'output' },
      { pin: 15, name: 'RCO',  type: 'output' },
      { pin: 16, name: 'ENT',  type: 'input'  },
      { pin: 17, name: 'ENP',  type: 'input'  },
      { pin: 18, name: 'LOAD', type: 'input'  },
      { pin: 19, name: 'UD',   type: 'input'  },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'COUNTER_LATCH_MUX_STUB', inputs: ['CLK','CLR','D0','D1','D2','D3','LE','S','OEn','ENT','ENP','LOAD','UD'], outputs: ['Q0','Q1','Q2','Q3','RCO'] },
    ],
  },

  // ── 74697: 4 bit binary counter/reg/mux, async CLR, TRI (20-pin) ─────────
  /* Primary source: Texas Instruments, 74697 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls697.pdf
     https://en.wikipedia.org/wiki/Counter_(digital) */
  '74697': {
    name: '74x697',
    simpleName: '4 bit Binary Counter/Reg/Mux (Async CLR)',
    description: '4 bit binary counter/register/multiplexer with asynchronous clear, tri-state output (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls697.pdf',
    tags: ['counter', 'binary', '4 bit', 'register', 'multiplexer', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x697 is the binary (0-15) up/down version of the 74x696: clocked register output, 2:1 MUX, asynchronous CLR. Identical pinout; counts 0-15 rather than BCD 0-9.',
    guidePinDescriptions: {
      'CLK':  'Clock input (rising edge).',
      'CLR':  'Asynchronous Clear (active LOW).',
      'D0':   'Parallel load input bit 0.',
      'D1':   'Parallel load input bit 1.',
      'D2':   'Parallel load input bit 2.',
      'D3':   'Parallel load input bit 3.',
      'LE':   'Register Load Enable.',
      'S':    'Output Select: LOW = register; HIGH = counter.',
      'OEn':  'Output Enable (active LOW).',
      'GND':  'Ground reference (pin 10).',
      'Q0':   'Output bit 0.',
      'Q1':   'Output bit 1.',
      'Q2':   'Output bit 2.',
      'Q3':   'Output bit 3.',
      'RCO':  'Ripple Carry Output.',
      'ENT':  'Count Enable T (active LOW).',
      'ENP':  'Count Enable P (active LOW).',
      'LOAD': 'Parallel Load (active LOW).',
      'UD':   'Up/Down count direction.',
      'VCC':  'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: '74x696/74x697/74x698/74x699 Family',
        list: [
          '74x696: BCD, async CLR, register output',
          '74x697: Binary, async CLR, register output',
          '74x698: BCD, sync CLR, register output',
          '74x699: Binary, sync CLR, register output',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'CLK',  type: 'input'  },
      { pin:  2, name: 'CLR',  type: 'input'  },
      { pin:  3, name: 'D0',   type: 'input'  },
      { pin:  4, name: 'D1',   type: 'input'  },
      { pin:  5, name: 'D2',   type: 'input'  },
      { pin:  6, name: 'D3',   type: 'input'  },
      { pin:  7, name: 'LE',   type: 'input'  },
      { pin:  8, name: 'S',    type: 'input'  },
      { pin:  9, name: 'OEn',  type: 'input'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'Q0',   type: 'output' },
      { pin: 12, name: 'Q1',   type: 'output' },
      { pin: 13, name: 'Q2',   type: 'output' },
      { pin: 14, name: 'Q3',   type: 'output' },
      { pin: 15, name: 'RCO',  type: 'output' },
      { pin: 16, name: 'ENT',  type: 'input'  },
      { pin: 17, name: 'ENP',  type: 'input'  },
      { pin: 18, name: 'LOAD', type: 'input'  },
      { pin: 19, name: 'UD',   type: 'input'  },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'COUNTER_LATCH_MUX_STUB', inputs: ['CLK','CLR','D0','D1','D2','D3','LE','S','OEn','ENT','ENP','LOAD','UD'], outputs: ['Q0','Q1','Q2','Q3','RCO'] },
    ],
  },

  // ── 74698: 4 bit decade counter/reg/mux, sync CLR, TRI (20-pin) ──────────
  /* Primary source: Texas Instruments, 74698 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls698.pdf
     https://en.wikipedia.org/wiki/Counter_(digital) */
  '74698': {
    name: '74x698',
    simpleName: '4 bit BCD Counter/Reg/Mux (Sync CLR)',
    description: '4 bit decade counter/register/multiplexer with synchronous clear, tri-state output (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls698.pdf',
    tags: ['counter', 'bcd', 'decade', 'register', 'multiplexer', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x698 is the synchronous-CLR version of the 74x696: 4 bit BCD up/down counter with clocked register output, 2:1 MUX, synchronous CLR, and tri-state outputs. CLR only clears on the next clock edge.',
    guidePinDescriptions: {
      'CLK':  'Clock input (rising edge).',
      'CLR':  'Synchronous Clear (active LOW). Clears on next clock edge.',
      'D0':   'Parallel load input bit 0.',
      'D1':   'Parallel load input bit 1.',
      'D2':   'Parallel load input bit 2.',
      'D3':   'Parallel load input bit 3.',
      'LE':   'Register Load Enable.',
      'S':    'Output Select.',
      'OEn':  'Output Enable (active LOW).',
      'GND':  'Ground reference (pin 10).',
      'Q0':   'Output bit 0.',
      'Q1':   'Output bit 1.',
      'Q2':   'Output bit 2.',
      'Q3':   'Output bit 3.',
      'RCO':  'Ripple Carry Output.',
      'ENT':  'Count Enable T (active LOW).',
      'ENP':  'Count Enable P (active LOW).',
      'LOAD': 'Parallel Load (active LOW).',
      'UD':   'Up/Down count direction.',
      'VCC':  'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'Synchronous Clear',
        paragraphs: [
          'Synchronous CLR avoids asynchronous glitches: the clear takes effect at the next clock edge, maintaining a clean synchronous design boundary.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'CLK',  type: 'input'  },
      { pin:  2, name: 'CLR',  type: 'input'  },
      { pin:  3, name: 'D0',   type: 'input'  },
      { pin:  4, name: 'D1',   type: 'input'  },
      { pin:  5, name: 'D2',   type: 'input'  },
      { pin:  6, name: 'D3',   type: 'input'  },
      { pin:  7, name: 'LE',   type: 'input'  },
      { pin:  8, name: 'S',    type: 'input'  },
      { pin:  9, name: 'OEn',  type: 'input'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'Q0',   type: 'output' },
      { pin: 12, name: 'Q1',   type: 'output' },
      { pin: 13, name: 'Q2',   type: 'output' },
      { pin: 14, name: 'Q3',   type: 'output' },
      { pin: 15, name: 'RCO',  type: 'output' },
      { pin: 16, name: 'ENT',  type: 'input'  },
      { pin: 17, name: 'ENP',  type: 'input'  },
      { pin: 18, name: 'LOAD', type: 'input'  },
      { pin: 19, name: 'UD',   type: 'input'  },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'COUNTER_LATCH_MUX_STUB', inputs: ['CLK','CLR','D0','D1','D2','D3','LE','S','OEn','ENT','ENP','LOAD','UD'], outputs: ['Q0','Q1','Q2','Q3','RCO'] },
    ],
  },

  // ── 74699: 4 bit binary counter/reg/mux, sync CLR, TRI (20-pin) ──────────
  /* Primary source: Texas Instruments, 74699 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls699.pdf
     https://en.wikipedia.org/wiki/Counter_(digital) */
  '74699': {
    name: '74x699',
    simpleName: '4 bit Binary Counter/Reg/Mux (Sync CLR)',
    description: '4 bit binary counter/register/multiplexer with synchronous clear, tri-state output (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls699.pdf',
    tags: ['counter', 'binary', '4 bit', 'register', 'multiplexer', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x699 is the synchronous-CLR binary version of the 74x698: 4 bit binary up/down counter with clocked register output, 2:1 MUX, synchronous CLR, and tri-state outputs.',
    guidePinDescriptions: {
      'CLK':  'Clock input (rising edge).',
      'CLR':  'Synchronous Clear (active LOW).',
      'D0':   'Parallel load input bit 0.',
      'D1':   'Parallel load input bit 1.',
      'D2':   'Parallel load input bit 2.',
      'D3':   'Parallel load input bit 3.',
      'LE':   'Register Load Enable.',
      'S':    'Output Select.',
      'OEn':  'Output Enable (active LOW).',
      'GND':  'Ground reference (pin 10).',
      'Q0':   'Output bit 0.',
      'Q1':   'Output bit 1.',
      'Q2':   'Output bit 2.',
      'Q3':   'Output bit 3.',
      'RCO':  'Ripple Carry Output.',
      'ENT':  'Count Enable T (active LOW).',
      'ENP':  'Count Enable P (active LOW).',
      'LOAD': 'Parallel Load (active LOW).',
      'UD':   'Up/Down count direction.',
      'VCC':  'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: '74x698 vs 74x699',
        paragraphs: [
          'Pin-for-pin compatible. 74x698 = BCD (decade); 74x699 = binary (0-15).',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'CLK',  type: 'input'  },
      { pin:  2, name: 'CLR',  type: 'input'  },
      { pin:  3, name: 'D0',   type: 'input'  },
      { pin:  4, name: 'D1',   type: 'input'  },
      { pin:  5, name: 'D2',   type: 'input'  },
      { pin:  6, name: 'D3',   type: 'input'  },
      { pin:  7, name: 'LE',   type: 'input'  },
      { pin:  8, name: 'S',    type: 'input'  },
      { pin:  9, name: 'OEn',  type: 'input'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'Q0',   type: 'output' },
      { pin: 12, name: 'Q1',   type: 'output' },
      { pin: 13, name: 'Q2',   type: 'output' },
      { pin: 14, name: 'Q3',   type: 'output' },
      { pin: 15, name: 'RCO',  type: 'output' },
      { pin: 16, name: 'ENT',  type: 'input'  },
      { pin: 17, name: 'ENP',  type: 'input'  },
      { pin: 18, name: 'LOAD', type: 'input'  },
      { pin: 19, name: 'UD',   type: 'input'  },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'COUNTER_LATCH_MUX_STUB', inputs: ['CLK','CLR','D0','D1','D2','D3','LE','S','OEn','ENT','ENP','LOAD','UD'], outputs: ['Q0','Q1','Q2','Q3','RCO'] },
    ],
  },

  // ── 74700: Octal DRAM driver, inverting, TRI (20-pin) ────────────────────
  /* Primary source: Texas Instruments, 74700 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74s700.pdf
     https://en.wikipedia.org/wiki/Random-access_memory */
  '74700': {
    name: '74x700',
    simpleName: 'Octal DRAM Driver (Inv)',
    description: 'Octal DRAM address driver with inverting tri-state outputs (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74s700.pdf',
    tags: ['buffer', 'driver', 'DRAM', 'octal', 'inverting', 'tri-state', 'stub'],
    guideOverview: 'The 74x700 is an octal DRAM address driver with inverting tri-state outputs. It buffers and inverts 8 address lines (A0-A7) to the active LOW DRAM address format (Y0-Y7). OEn enables all outputs simultaneously. Used in DRAM controller circuits to multiplex row and column address signals.',
    guidePinDescriptions: {
      'OEn':  'Output Enable (active LOW). All 8 outputs go tri-state when HIGH.',
      'A0':   'Address input bit 0.',
      'A1':   'Address input bit 1.',
      'A2':   'Address input bit 2.',
      'A3':   'Address input bit 3.',
      'A4':   'Address input bit 4.',
      'A5':   'Address input bit 5.',
      'A6':   'Address input bit 6.',
      'A7':   'Address input bit 7.',
      'GND':  'Ground reference (pin 10).',
      'Y7':   'Inverted output for A7.',
      'Y6':   'Inverted output for A6.',
      'Y5':   'Inverted output for A5.',
      'Y4':   'Inverted output for A4.',
      'Y3':   'Inverted output for A3.',
      'Y2':   'Inverted output for A2.',
      'Y1':   'Inverted output for A1.',
      'Y0':   'Inverted output for A0.',
      'NC':   'No connect.',
      'VCC':  'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'DRAM Address Multiplexing',
        paragraphs: [
          'DRAM chips use multiplexed row/column addresses on the same pins. The 74x700 buffers one set of address lines during RAS or CAS strobe. The inversion handles the active LOW address convention on some DRAM families.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'OEn',  type: 'input'  },
      { pin:  2, name: 'A0',   type: 'input'  },
      { pin:  3, name: 'A1',   type: 'input'  },
      { pin:  4, name: 'A2',   type: 'input'  },
      { pin:  5, name: 'A3',   type: 'input'  },
      { pin:  6, name: 'A4',   type: 'input'  },
      { pin:  7, name: 'A5',   type: 'input'  },
      { pin:  8, name: 'A6',   type: 'input'  },
      { pin:  9, name: 'A7',   type: 'input'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'Y7',   type: 'output' },
      { pin: 12, name: 'Y6',   type: 'output' },
      { pin: 13, name: 'Y5',   type: 'output' },
      { pin: 14, name: 'Y4',   type: 'output' },
      { pin: 15, name: 'Y3',   type: 'output' },
      { pin: 16, name: 'Y2',   type: 'output' },
      { pin: 17, name: 'Y1',   type: 'output' },
      { pin: 18, name: 'Y0',   type: 'output' },
      { pin: 19, name: 'NC',   type: 'nc'     },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['A0','A1','A2','A3','A4','A5','A6','A7','OEn'], outputs: ['Y0','Y1','Y2','Y3','Y4','Y5','Y6','Y7'] },
    ],
  },

  // ── 74701: 8 bit register/counter/comparator, TRI (24-pin) ───────────────
  /* Primary source: Texas Instruments, 74701 datasheet. [Online]. Available: https://www.datasheetz.com/datasheet/74F701
     https://en.wikipedia.org/wiki/Digital_comparator */
  '74701': {
    name: '74x701',
    simpleName: '8 bit Register/Counter/Comparator',
    description: '8 bit register/counter/comparator with tri-state outputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: 'https://www.datasheetz.com/datasheet/74F701',
    tags: ['register', 'counter', 'comparator', '8 bit', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x701 integrates an 8 bit loadable register, a counter, and a magnitude comparator in one 24-pin package. CLK clocks the register; CLR resets it. Q0-Q7 are tri-state parallel outputs; EQout signals when the internal count matches a compare value. Used in timers and event counting applications.',
    guidePinDescriptions: {
      'CLK':   'Clock input (rising edge).',
      'CLR':   'Clear (active LOW).',
      'D0':    'Data input bit 0.',
      'D1':    'Data input bit 1.',
      'D2':    'Data input bit 2.',
      'D3':    'Data input bit 3.',
      'D4':    'Data input bit 4.',
      'D5':    'Data input bit 5.',
      'D6':    'Data input bit 6.',
      'D7':    'Data input bit 7.',
      'NC1':   'No connect.',
      'GND':   'Ground reference (pin 12).',
      'Q0':    'Output bit 0.',
      'Q1':    'Output bit 1.',
      'Q2':    'Output bit 2.',
      'Q3':    'Output bit 3.',
      'Q4':    'Output bit 4.',
      'Q5':    'Output bit 5.',
      'Q6':    'Output bit 6.',
      'Q7':    'Output bit 7.',
      'OEn':   'Output Enable (active LOW).',
      'EQout': 'Equal output. Asserts when count equals compare value.',
      'NC2':   'No connect.',
      'VCC':   'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: 'Register/Counter/Comparator',
        paragraphs: [
          'Combines register storage, counting, and magnitude comparison. Useful for match-and-trigger circuits: count events and fire when a target count is reached, without external comparator chips.',
        ],
        note: 'Full ALU and comparison logic is stubbed in the simulator.',
      },
    ],
    pinout: [
      { pin:  1, name: 'CLK',  type: 'input'  },
      { pin:  2, name: 'CLR',  type: 'input'  },
      { pin:  3, name: 'D0',   type: 'input'  },
      { pin:  4, name: 'D1',   type: 'input'  },
      { pin:  5, name: 'D2',   type: 'input'  },
      { pin:  6, name: 'D3',   type: 'input'  },
      { pin:  7, name: 'D4',   type: 'input'  },
      { pin:  8, name: 'D5',   type: 'input'  },
      { pin:  9, name: 'D6',   type: 'input'  },
      { pin: 10, name: 'D7',   type: 'input'  },
      { pin: 11, name: 'NC1',  type: 'nc'     },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'Q0',   type: 'output' },
      { pin: 14, name: 'Q1',   type: 'output' },
      { pin: 15, name: 'Q2',   type: 'output' },
      { pin: 16, name: 'Q3',   type: 'output' },
      { pin: 17, name: 'Q4',   type: 'output' },
      { pin: 18, name: 'Q5',   type: 'output' },
      { pin: 19, name: 'Q6',   type: 'output' },
      { pin: 20, name: 'Q7',   type: 'output' },
      { pin: 21, name: 'OEn',  type: 'input'  },
      { pin: 22, name: 'EQout',type: 'output' },
      { pin: 23, name: 'NC2',  type: 'nc'     },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['CLK','CLR','D0','D1','D2','D3','D4','D5','D6','D7','OEn'], outputs: ['Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7','EQout'] },
    ],
  },

  // ── 74702: 8 bit registered read-back transceiver, TRI (24-pin) ──────────
  /* Primary source: Texas Instruments, 74702 datasheet. [Online]. Available: https://www.datasheetz.com/datasheet/74F702
     https://en.wikipedia.org/wiki/Bus_transceiver */
  '74702': {
    name: '74x702',
    simpleName: '8 bit Reg Read-back Transceiver',
    description: '8 bit registered read-back transceiver with tri-state outputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: 'https://www.datasheetz.com/datasheet/74F702',
    tags: ['transceiver', 'register', '8 bit', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x702 is an 8 bit registered transceiver with read-back capability. CLK registers data; DIR controls transfer direction; OEABn and OEBAn enable A-to-B and B-to-A paths independently. The read-back feature allows the CPU to verify what was written to the bus without additional logic.',
    guidePinDescriptions: {
      'CLK':   'Clock input. Registers data on rising edge.',
      'OEABn': 'Output Enable A-to-B (active LOW).',
      'OEBAn': 'Output Enable B-to-A (active LOW).',
      'DIR':   'Direction select. HIGH = A to B; LOW = B to A.',
      'A0':    'Bidirectional port A, bit 0.',
      'A1':    'Bidirectional port A, bit 1.',
      'A2':    'Bidirectional port A, bit 2.',
      'A3':    'Bidirectional port A, bit 3.',
      'A4':    'Bidirectional port A, bit 4.',
      'A5':    'Bidirectional port A, bit 5.',
      'A6':    'Bidirectional port A, bit 6.',
      'GND':   'Ground reference (pin 12).',
      'A7':    'Bidirectional port A, bit 7.',
      'B7':    'Bidirectional port B, bit 7.',
      'B6':    'Bidirectional port B, bit 6.',
      'B5':    'Bidirectional port B, bit 5.',
      'B4':    'Bidirectional port B, bit 4.',
      'B3':    'Bidirectional port B, bit 3.',
      'B2':    'Bidirectional port B, bit 2.',
      'B1':    'Bidirectional port B, bit 1.',
      'B0':    'Bidirectional port B, bit 0.',
      'NC1':   'No connect.',
      'NC2':   'No connect.',
      'VCC':   'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: 'Registered Transceiver',
        paragraphs: [
          'Registered transceivers capture incoming data on the clock edge before driving it onto the destination bus. This prevents bus contention glitches and synchronizes data crossing between asynchronous bus segments.',
        ],
        note: 'Stub in simulator.',
      },
    ],
    pinout: [
      { pin:  1, name: 'CLK',  type: 'input'  },
      { pin:  2, name: 'OEABn',type: 'input'  },
      { pin:  3, name: 'OEBAn',type: 'input'  },
      { pin:  4, name: 'DIR',  type: 'input'  },
      { pin:  5, name: 'A0',   type: 'bidir'  },
      { pin:  6, name: 'A1',   type: 'bidir'  },
      { pin:  7, name: 'A2',   type: 'bidir'  },
      { pin:  8, name: 'A3',   type: 'bidir'  },
      { pin:  9, name: 'A4',   type: 'bidir'  },
      { pin: 10, name: 'A5',   type: 'bidir'  },
      { pin: 11, name: 'A6',   type: 'bidir'  },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'A7',   type: 'bidir'  },
      { pin: 14, name: 'B7',   type: 'bidir'  },
      { pin: 15, name: 'B6',   type: 'bidir'  },
      { pin: 16, name: 'B5',   type: 'bidir'  },
      { pin: 17, name: 'B4',   type: 'bidir'  },
      { pin: 18, name: 'B3',   type: 'bidir'  },
      { pin: 19, name: 'B2',   type: 'bidir'  },
      { pin: 20, name: 'B1',   type: 'bidir'  },
      { pin: 21, name: 'B0',   type: 'bidir'  },
      { pin: 22, name: 'NC1',  type: 'nc'     },
      { pin: 23, name: 'NC2',  type: 'nc'     },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['CLK','OEABn','OEBAn','DIR','A0','A1','A2','A3','A4','A5','A6','A7'], outputs: ['B0','B1','B2','B3','B4','B5','B6','B7'] },
    ],
  },

  // ── 74707: 8 bit TTL-ECL shift register (20-pin) ─────────────────────────
  /* Primary source: Texas Instruments, 74707 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74f707.pdf
     https://en.wikipedia.org/wiki/Shift_register */
  '74707': {
    name: '74x707',
    simpleName: '8 bit TTL-ECL Shift Register',
    description: '8 bit TTL-to-ECL shift register (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74f707.pdf',
    tags: ['shift register', 'ECL', 'TTL', '8 bit', 'stub'],
    sequential: true,
    guideOverview: 'The 74x707 is an 8 bit SIPO shift register that converts TTL input levels to ECL output levels, enabling interfacing between TTL logic and high-speed ECL circuits. SI is the TTL serial input; CLK/CLKn provide differential clock. Q0-Q7 are ECL-level outputs.',
    guidePinDescriptions: {
      'SI':   'Serial Input (TTL level).',
      'CLK':  'Clock input (positive phase of differential clock).',
      'CLKn': 'Complementary clock input.',
      'Q0':   'ECL output bit 0 (first shifted).',
      'Q1':   'ECL output bit 1.',
      'Q2':   'ECL output bit 2.',
      'Q3':   'ECL output bit 3.',
      'Q4':   'ECL output bit 4.',
      'Q5':   'ECL output bit 5.',
      'GND':  'Ground reference (pin 10).',
      'Q6':   'ECL output bit 6.',
      'Q7':   'ECL output bit 7.',
      'NC1':  'No connect.',
      'NC2':  'No connect.',
      'NC3':  'No connect.',
      'NC4':  'No connect.',
      'NC5':  'No connect.',
      'NC6':  'No connect.',
      'NC7':  'No connect.',
      'VCC':  'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'TTL-to-ECL Level Translation',
        paragraphs: [
          'ECL (Emitter-Coupled Logic) operates at very high speeds but at different voltage levels than TTL. The 74x707 provides the level-shifting function while capturing serial TTL data into an 8 bit parallel ECL word.',
        ],
        note: 'Stub in simulator. ECL output levels not fully modeled.',
      },
    ],
    pinout: [
      { pin:  1, name: 'SI',   type: 'input'  },
      { pin:  2, name: 'CLK',  type: 'input'  },
      { pin:  3, name: 'CLKn', type: 'input'  },
      { pin:  4, name: 'Q0',   type: 'output' },
      { pin:  5, name: 'Q1',   type: 'output' },
      { pin:  6, name: 'Q2',   type: 'output' },
      { pin:  7, name: 'Q3',   type: 'output' },
      { pin:  8, name: 'Q4',   type: 'output' },
      { pin:  9, name: 'Q5',   type: 'output' },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'Q6',   type: 'output' },
      { pin: 12, name: 'Q7',   type: 'output' },
      { pin: 13, name: 'NC1',  type: 'nc'     },
      { pin: 14, name: 'NC2',  type: 'nc'     },
      { pin: 15, name: 'NC3',  type: 'nc'     },
      { pin: 16, name: 'NC4',  type: 'nc'     },
      { pin: 17, name: 'NC5',  type: 'nc'     },
      { pin: 18, name: 'NC6',  type: 'nc'     },
      { pin: 19, name: 'NC7',  type: 'nc'     },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['SI','CLK','CLKn'], outputs: ['Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7'] },
    ],
  },

  // ── 74710: 8 bit single-supply TTL-ECL shift register (20-pin) ───────────
  /* Primary source: Texas Instruments, 74710 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74f710.pdf
     https://en.wikipedia.org/wiki/Shift_register */
  '74710': {
    name: '74x710',
    simpleName: '8 bit TTL-ECL Shift Register (Single Supply)',
    description: '8 bit single-supply TTL-to-ECL shift register (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74f710.pdf',
    tags: ['shift register', 'ECL', 'TTL', '8 bit', 'stub'],
    sequential: true,
    guideOverview: 'The 74x710 is a single-supply version of the 74x707: 8 bit TTL-to-ECL shift register that operates from a single +5 V supply instead of dual ±5 V. The single-supply design simplifies power distribution in mixed TTL/ECL boards.',
    guidePinDescriptions: {
      'SI':   'Serial Input (TTL level).',
      'CLK':  'Clock input (positive phase).',
      'CLKn': 'Complementary clock.',
      'Q0':   'ECL output bit 0.',
      'Q1':   'ECL output bit 1.',
      'Q2':   'ECL output bit 2.',
      'Q3':   'ECL output bit 3.',
      'Q4':   'ECL output bit 4.',
      'Q5':   'ECL output bit 5.',
      'GND':  'Ground reference (pin 10).',
      'Q6':   'ECL output bit 6.',
      'Q7':   'ECL output bit 7.',
      'NC1':  'No connect.',
      'NC2':  'No connect.',
      'NC3':  'No connect.',
      'NC4':  'No connect.',
      'NC5':  'No connect.',
      'NC6':  'No connect.',
      'NC7':  'No connect.',
      'VCC':  'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: '74x707 vs 74x710',
        paragraphs: [
          '74x707 requires dual supply (+5 V / -5.2 V); 74x710 works from a single +5 V supply. Otherwise functionally identical.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'SI',   type: 'input'  },
      { pin:  2, name: 'CLK',  type: 'input'  },
      { pin:  3, name: 'CLKn', type: 'input'  },
      { pin:  4, name: 'Q0',   type: 'output' },
      { pin:  5, name: 'Q1',   type: 'output' },
      { pin:  6, name: 'Q2',   type: 'output' },
      { pin:  7, name: 'Q3',   type: 'output' },
      { pin:  8, name: 'Q4',   type: 'output' },
      { pin:  9, name: 'Q5',   type: 'output' },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'Q6',   type: 'output' },
      { pin: 12, name: 'Q7',   type: 'output' },
      { pin: 13, name: 'NC1',  type: 'nc'     },
      { pin: 14, name: 'NC2',  type: 'nc'     },
      { pin: 15, name: 'NC3',  type: 'nc'     },
      { pin: 16, name: 'NC4',  type: 'nc'     },
      { pin: 17, name: 'NC5',  type: 'nc'     },
      { pin: 18, name: 'NC6',  type: 'nc'     },
      { pin: 19, name: 'NC7',  type: 'nc'     },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['SI','CLK','CLKn'], outputs: ['Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7'] },
    ],
  },

  // ── 74711: Quint 2-to-1 multiplexer, TRI (20-pin) ─────────────────────────
  /* Primary source: Texas Instruments, 74711 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74f711.pdf
     https://en.wikipedia.org/wiki/Multiplexer */
  '74711': {
    name: '74x711',
    simpleName: 'Quint 2-to-1 Mux',
    description: 'Five 2-to-1 multiplexers with tri-state outputs and common select (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74f711.pdf',
    tags: ['multiplexer', '2-to-1', 'quint', 'tri-state'],
    guideOverview: 'The 74x711 contains five independent 2-to-1 multiplexers sharing a single SEL line and OEn enable. SEL=0 routes A0-A4 to Y0-Y4; SEL=1 routes B0-B4. OEn forces all outputs tri-state. This bus-width approach (five MUXes in one package) is useful for routing 5 bit data paths or arbitrary 5 bit control signals.',
    guidePinDescriptions: {
      'OEn':  'Output Enable (active LOW). All outputs go tri-state when HIGH.',
      'SEL':  'Select. LOW = A inputs; HIGH = B inputs.',
      'A0':   'Input A of channel 0.',
      'B0':   'Input B of channel 0.',
      'A1':   'Input A of channel 1.',
      'B1':   'Input B of channel 1.',
      'A2':   'Input A of channel 2.',
      'B2':   'Input B of channel 2.',
      'A3':   'Input A of channel 3.',
      'GND':  'Ground reference (pin 10).',
      'B3':   'Input B of channel 3.',
      'A4':   'Input A of channel 4.',
      'B4':   'Input B of channel 4.',
      'Y4':   'Output of channel 4.',
      'Y3':   'Output of channel 3.',
      'Y2':   'Output of channel 2.',
      'Y1':   'Output of channel 1.',
      'Y0':   'Output of channel 0.',
      'NC':   'No connect.',
      'VCC':  'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'Quint 2-to-1 Multiplexer',
        paragraphs: [
          'Five separate 2-to-1 channels share one select line, allowing a 5 bit word to be routed from one of two 5 bit sources with a single control signal. Suitable for bus arbitration or path switching in datapath circuits.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'OEn',  type: 'input'  },
      { pin:  2, name: 'SEL',  type: 'input'  },
      { pin:  3, name: 'A0',   type: 'input'  },
      { pin:  4, name: 'B0',   type: 'input'  },
      { pin:  5, name: 'A1',   type: 'input'  },
      { pin:  6, name: 'B1',   type: 'input'  },
      { pin:  7, name: 'A2',   type: 'input'  },
      { pin:  8, name: 'B2',   type: 'input'  },
      { pin:  9, name: 'A3',   type: 'input'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'B3',   type: 'input'  },
      { pin: 12, name: 'A4',   type: 'input'  },
      { pin: 13, name: 'B4',   type: 'input'  },
      { pin: 14, name: 'Y4',   type: 'output' },
      { pin: 15, name: 'Y3',   type: 'output' },
      { pin: 16, name: 'Y2',   type: 'output' },
      { pin: 17, name: 'Y1',   type: 'output' },
      { pin: 18, name: 'Y0',   type: 'output' },
      { pin: 19, name: 'NC',   type: 'nc'     },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'MUX_QUINT_2TO1', inputs: ['A0','B0','A1','B1','A2','B2','A3','B3','A4','B4','SEL','OEn'], outputs: ['Y0','Y1','Y2','Y3','Y4'] },
    ],
  },

  // ── 74712: Quint 3-to-1 multiplexer (24-pin) ──────────────────────────────
  /* Primary source: Texas Instruments, 74712 datasheet. [Online]. Available: https://www.datasheetz.com/datasheet/74F712
     https://en.wikipedia.org/wiki/Multiplexer */
  '74712': {
    name: '74x712',
    simpleName: 'Quint 3-to-1 Mux',
    description: 'Five 3-to-1 multiplexers (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: 'https://www.datasheetz.com/datasheet/74F712',
    tags: ['multiplexer', '3-to-1', 'quint', 'stub'],
    guideOverview: 'The 74x712 contains five independent 3-to-1 multiplexers. S0 and S1 address three data inputs (A, B, C) per channel; each channel produces one output. All five channels share the same S0/S1 select lines. Used for 5 bit triple-source bus arbitration.',
    guidePinDescriptions: {
      'S0':   'Select bit 0 (LSB).',
      'S1':   'Select bit 1 (MSB).',
      'A0':   'Input A of channel 0.',
      'B0':   'Input B of channel 0.',
      'C0':   'Input C of channel 0.',
      'A1':   'Input A of channel 1.',
      'B1':   'Input B of channel 1.',
      'C1':   'Input C of channel 1.',
      'A2':   'Input A of channel 2.',
      'B2':   'Input B of channel 2.',
      'C2':   'Input C of channel 2.',
      'GND':  'Ground reference (pin 12).',
      'Y2':   'Output of channel 2.',
      'A3':   'Input A of channel 3.',
      'B3':   'Input B of channel 3.',
      'C3':   'Input C of channel 3.',
      'Y3':   'Output of channel 3.',
      'A4':   'Input A of channel 4.',
      'B4':   'Input B of channel 4.',
      'C4':   'Input C of channel 4.',
      'Y4':   'Output of channel 4.',
      'Y0':   'Output of channel 0.',
      'Y1':   'Output of channel 1.',
      'VCC':  'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: '3-to-1 Select Encoding',
        formulas: [
          'S1=0, S0=0 → selects A inputs',
          'S1=0, S0=1 → selects B inputs',
          'S1=1, S0=0 → selects C inputs',
          'S1=1, S0=1 → unused state',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'S0',   type: 'input'  },
      { pin:  2, name: 'S1',   type: 'input'  },
      { pin:  3, name: 'A0',   type: 'input'  },
      { pin:  4, name: 'B0',   type: 'input'  },
      { pin:  5, name: 'C0',   type: 'input'  },
      { pin:  6, name: 'A1',   type: 'input'  },
      { pin:  7, name: 'B1',   type: 'input'  },
      { pin:  8, name: 'C1',   type: 'input'  },
      { pin:  9, name: 'A2',   type: 'input'  },
      { pin: 10, name: 'B2',   type: 'input'  },
      { pin: 11, name: 'C2',   type: 'input'  },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'Y2',   type: 'output' },
      { pin: 14, name: 'A3',   type: 'input'  },
      { pin: 15, name: 'B3',   type: 'input'  },
      { pin: 16, name: 'C3',   type: 'input'  },
      { pin: 17, name: 'Y3',   type: 'output' },
      { pin: 18, name: 'A4',   type: 'input'  },
      { pin: 19, name: 'B4',   type: 'input'  },
      { pin: 20, name: 'C4',   type: 'input'  },
      { pin: 21, name: 'Y4',   type: 'output' },
      { pin: 22, name: 'Y0',   type: 'output' },
      { pin: 23, name: 'Y1',   type: 'output' },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['S0','S1','A0','B0','C0','A1','B1','C1','A2','B2','C2','A3','B3','C3','A4','B4','C4'], outputs: ['Y0','Y1','Y2','Y3','Y4'] },
    ],
  },


  // ── 74715: Video sync generator (20-pin) ──────────────────────────────────
  /* Primary source: 74715 datasheet   URL not yet verified. */
  '74715': {
    name: '74x715',
    simpleName: 'Video Sync Generator',
    description: 'Video sync generator with HSYNC, VSYNC, BLANK, and composite sync outputs (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: null,
    tags: ['video', 'sync', 'generator', 'stub'],
    guideOverview: 'The 74x715 is a video sync generator that produces standard horizontal sync (HSYNC), vertical sync (VSYNC), blanking (BLANK), and composite sync (CSYNC) signals from a master clock input. Timing configuration inputs allow selection of horizontal and vertical resolution parameters. Used in video display controller designs to provide precise timing signals to CRTs and video DACs.',
    guidePinDescriptions: {
      'CLK':   'Master clock input. Divides down to generate line and frame timing.',
      'RESETn':'Asynchronous reset (active LOW). Resets all internal timing counters.',
      'OEn':   'Output enable (active LOW). Tri-states all sync outputs when HIGH.',
      'H0':    'Horizontal timing configuration bit 0.',
      'H1':    'Horizontal timing configuration bit 1.',
      'H2':    'Horizontal timing configuration bit 2.',
      'V0':    'Vertical timing configuration bit 0.',
      'V1':    'Vertical timing configuration bit 1.',
      'V2':    'Vertical timing configuration bit 2.',
      'GND':   'Ground reference (pin 10).',
      'HSYNC': 'Horizontal sync output. Pulses at end of each scan line.',
      'VSYNC': 'Vertical sync output. Pulses at end of each field/frame.',
      'BLANK': 'Blanking output. HIGH during horizontal and vertical retrace intervals.',
      'CSYNC': 'Composite sync output. OR of HSYNC and VSYNC on a single line.',
      'ODDEVEN':'Odd/Even field indicator output for interlaced display modes.',
      'NC1':   'No connect.',
      'NC2':   'No connect.',
      'NC3':   'No connect.',
      'NC4':   'No connect.',
      'VCC':   'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'Video Sync Timing',
        paragraphs: [
          'A video sync generator divides a master pixel clock into the horizontal and vertical timing signals required by a CRT monitor or composite video system. HSYNC fires at the end of each horizontal scan line; VSYNC fires at the end of each frame. The BLANK signal masks the display during retrace intervals to prevent visible scan lines on screen.',
        ],
      },
      {
        title: 'Configuration Inputs',
        paragraphs: [
          'H0-H2 and V0-V2 select among preset horizontal and vertical timing parameters, allowing the same chip to generate sync for multiple standard resolutions without external timing components.',
        ],
        note: 'Full sync generation logic is represented as a generic stub in simulation.',
      },
    ],
    pinout: [
      { pin:  1, name: 'CLK',    type: 'input'  },
      { pin:  2, name: 'RESETn', type: 'input'  },
      { pin:  3, name: 'OEn',    type: 'input'  },
      { pin:  4, name: 'H0',     type: 'input'  },
      { pin:  5, name: 'H1',     type: 'input'  },
      { pin:  6, name: 'H2',     type: 'input'  },
      { pin:  7, name: 'V0',     type: 'input'  },
      { pin:  8, name: 'V1',     type: 'input'  },
      { pin:  9, name: 'V2',     type: 'input'  },
      { pin: 10, name: 'GND',    type: 'power'  },
      { pin: 11, name: 'HSYNC',  type: 'output' },
      { pin: 12, name: 'VSYNC',  type: 'output' },
      { pin: 13, name: 'BLANK',  type: 'output' },
      { pin: 14, name: 'CSYNC',  type: 'output' },
      { pin: 15, name: 'ODDEVEN',type: 'output' },
      { pin: 16, name: 'NC1',    type: 'nc'     },
      { pin: 17, name: 'NC2',    type: 'nc'     },
      { pin: 18, name: 'NC3',    type: 'nc'     },
      { pin: 19, name: 'NC4',    type: 'nc'     },
      { pin: 20, name: 'VCC',    type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['CLK','RESETn','OEn','H0','H1','H2','V0','V1','V2'], outputs: ['HSYNC','VSYNC','BLANK','CSYNC','ODDEVEN'] },
    ],
  },

  // ── 74716: Programmable decade counter (16-pin) ───────────────────────────
  /* Primary source: Texas Instruments, 74716 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls716.pdf
     https://en.wikipedia.org/wiki/Counter_(digital) */
  '74716': {
    name: '74x716',
    simpleName: 'Programmable Decade Counter',
    description: 'Programmable decade counter (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls716.pdf',
    tags: ['counter', 'decade', 'programmable', 'stub'],
    sequential: true,
    guideOverview: 'The 74x716 is a programmable decade counter with a preset terminal count capability. D0-D3 load a start value; LOAD latches it on command. The counter increments from the loaded value to terminal count, then asserts RCO for cascading. ENP enables counting.',
    guidePinDescriptions: {
      'CLK':  'Clock input (rising edge).',
      'CLRn': 'Clear (active LOW).',
      'D0':   'Parallel load input bit 0.',
      'D1':   'Parallel load input bit 1.',
      'D2':   'Parallel load input bit 2.',
      'D3':   'Parallel load input bit 3.',
      'LOAD': 'Parallel Load (active LOW).',
      'GND':  'Ground reference (pin 8).',
      'ENP':  'Count Enable P (active LOW).',
      'QA':   'Output bit A.',
      'QB':   'Output bit B.',
      'QC':   'Output bit C.',
      'QD':   'Output bit D.',
      'RCO':  'Ripple Carry Output for cascading.',
      'NC':   'No connect.',
      'VCC':  'Positive supply (+5 V, pin 16).',
    },
    guideSections: [
      {
        title: 'Programmable Counter',
        paragraphs: [
          'A programmable counter starts counting from a loaded preset value rather than always from zero. This allows arbitrary count lengths: for example, loading 7 into a decade counter makes it count from 7 to 9 (3 steps) before rolling over.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'CLK',  type: 'input'  },
      { pin:  2, name: 'CLRn', type: 'input'  },
      { pin:  3, name: 'D0',   type: 'input'  },
      { pin:  4, name: 'D1',   type: 'input'  },
      { pin:  5, name: 'D2',   type: 'input'  },
      { pin:  6, name: 'D3',   type: 'input'  },
      { pin:  7, name: 'LOAD', type: 'input'  },
      { pin:  8, name: 'GND',  type: 'power'  },
      { pin:  9, name: 'ENP',  type: 'input'  },
      { pin: 10, name: 'QA',   type: 'output' },
      { pin: 11, name: 'QB',   type: 'output' },
      { pin: 12, name: 'QC',   type: 'output' },
      { pin: 13, name: 'QD',   type: 'output' },
      { pin: 14, name: 'RCO',  type: 'output' },
      { pin: 15, name: 'NC',   type: 'nc'     },
      { pin: 16, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['CLK','CLRn','D0','D1','D2','D3','LOAD','ENP'], outputs: ['QA','QB','QC','QD','RCO'] },
    ],
  },

  // ── 74718: Programmable binary counter (16-pin) ───────────────────────────
  /* Primary source: Texas Instruments, 74718 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls718.pdf
     https://en.wikipedia.org/wiki/Counter_(digital) */
  '74718': {
    name: '74x718',
    simpleName: 'Programmable Binary Counter',
    description: 'Programmable binary counter (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls718.pdf',
    tags: ['counter', 'binary', '4 bit', 'programmable', 'stub'],
    sequential: true,
    guideOverview: 'The 74x718 is the binary version of the 74x716: a programmable 4 bit binary counter (0-15) with preset load, CLR, and RCO. Same pinout and operation as 74x716 but without BCD limitation, counting the full 4 bit range.',
    guidePinDescriptions: {
      'CLK':  'Clock input (rising edge).',
      'CLRn': 'Clear (active LOW).',
      'D0':   'Parallel load input bit 0.',
      'D1':   'Parallel load input bit 1.',
      'D2':   'Parallel load input bit 2.',
      'D3':   'Parallel load input bit 3.',
      'LOAD': 'Parallel Load (active LOW).',
      'GND':  'Ground reference (pin 8).',
      'ENP':  'Count Enable P (active LOW).',
      'QA':   'Output bit A.',
      'QB':   'Output bit B.',
      'QC':   'Output bit C.',
      'QD':   'Output bit D.',
      'RCO':  'Ripple Carry Output.',
      'NC':   'No connect.',
      'VCC':  'Positive supply (+5 V, pin 16).',
    },
    guideSections: [
      {
        title: '74x716 vs 74x718',
        paragraphs: [
          '74x716 counts in BCD (decade, 0-9); 74x718 counts in 4 bit binary (0-15). Otherwise pin-compatible and functionally identical.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'CLK',  type: 'input'  },
      { pin:  2, name: 'CLRn', type: 'input'  },
      { pin:  3, name: 'D0',   type: 'input'  },
      { pin:  4, name: 'D1',   type: 'input'  },
      { pin:  5, name: 'D2',   type: 'input'  },
      { pin:  6, name: 'D3',   type: 'input'  },
      { pin:  7, name: 'LOAD', type: 'input'  },
      { pin:  8, name: 'GND',  type: 'power'  },
      { pin:  9, name: 'ENP',  type: 'input'  },
      { pin: 10, name: 'QA',   type: 'output' },
      { pin: 11, name: 'QB',   type: 'output' },
      { pin: 12, name: 'QC',   type: 'output' },
      { pin: 13, name: 'QD',   type: 'output' },
      { pin: 14, name: 'RCO',  type: 'output' },
      { pin: 15, name: 'NC',   type: 'nc'     },
      { pin: 16, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['CLK','CLRn','D0','D1','D2','D3','LOAD','ENP'], outputs: ['QA','QB','QC','QD','RCO'] },
    ],
  },
};