// Chip definitions block 45
// Chips: 74929, 74930, 74932, 74933, 74936-74938, 74940-74943, 74952, 74x956, 74962-74964

export const CHIPS_BLOCK_45 = {

  // 74929: 1024 bit RAM (1024x1), single chip select, three-state (16-pin)
  '74929': {
    name: '74x929',
    simpleName: '1024 bit RAM 1024x1 (TRI)',
    description: '1024 bit RAM organized as 1024 words x 1 bit with three-state output and single chip select (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    datasheet: '',
    tags: ['ram', 'memory', '1024 bit', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x929 is a 1024 bit static RAM organized as 1024 words by 1 bit with a single chip select. Ten address inputs A0–A9 select one of 1024 locations. WEn (active LOW) writes the value on DIN into the selected location; CSn (chip select, active LOW) enables the device; DOUT is the 3-state output. Build wider memories by paralleling multiple chips — each chip holds one bit plane of the data word.',
    pinout: [
      { pin:  1, name: 'A0',  type: 'input'  },
      { pin:  2, name: 'A1',  type: 'input'  },
      { pin:  3, name: 'A2',  type: 'input'  },
      { pin:  4, name: 'A3',  type: 'input'  },
      { pin:  5, name: 'A4',  type: 'input'  },
      { pin:  6, name: 'A5',  type: 'input'  },
      { pin:  7, name: 'A6',  type: 'input'  },
      { pin:  8, name: 'GND', type: 'power'  },
      { pin:  9, name: 'A7',  type: 'input'  },
      { pin: 10, name: 'A8',  type: 'input'  },
      { pin: 11, name: 'A9',  type: 'input'  },
      { pin: 12, name: 'WEn', type: 'input'  },
      { pin: 13, name: 'CSn', type: 'input'  },
      { pin: 14, name: 'DIN', type: 'input'  },
      { pin: 15, name: 'DOUT',type: 'output' },
      { pin: 16, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['A0','A1','A2','A3','A4','A5','A6','A7','A8','A9','WEn','CSn','DIN'], outputs: ['DOUT'] },
    ],
  },

  // 74930: 1024 bit RAM (1024x1), three chip selects, three-state (18-pin)
  '74930': {
    name: '74x930',
    simpleName: '1024 bit RAM 1024x1 (TRI, 3 CS)',
    description: '1024 bit RAM organized as 1024 words x 1 bit with three-state output and three chip selects (18-pin)',
    pins: 18, vcc: 18, gnd: 9,
    datasheet: '',
    tags: ['ram', 'memory', '1024 bit', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x930 is a 1024 bit static RAM organized as 1024 words by 1 bit with three chip selects for flexible address decoding. Ten address inputs A0–A9 select one of 1024 locations. The device is active only when CS1n (active LOW), CS2n (active LOW), and CS3 (active HIGH) are all satisfied simultaneously, enabling memory map control without external gates. WEn writes DIN; DOUT is the 3-state output. Like the 74x929 but with three chip selects.',
    pinout: [
      { pin: 10, name: 'A8',  type: 'input'  },
      { pin: 11, name: 'A9',  type: 'input'  },
      { pin: 12, name: 'WEn', type: 'input'  },
      { pin: 13, name: 'CS1n',type: 'input'  },
      { pin: 14, name: 'CS2n',type: 'input'  },
      { pin: 15, name: 'CS3', type: 'input'  },
      { pin: 16, name: 'DIN', type: 'input'  },
      { pin: 17, name: 'DOUT',type: 'output' },
      { pin: 18, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['A0','A1','A2','A3','A4','A5','A6','A7','A8','A9','WEn','CS1n','CS2n','CS3','DIN'], outputs: ['DOUT'] },
    ],
  },

  // 74932: Phase comparator (8-pin)
  '74932': {
    name: '74x932',
    simpleName: 'Phase Comparator',
    description: 'Phase comparator (8-pin)',
    pins: 8, vcc: 8, gnd: 4,
    datasheet: '',
    tags: ['phase comparator', 'analog', 'stub'],
    guideOverview: 'The 74x932 is a phase comparator. It compares the phase of two digital signals: a signal input (SIG) and a reference (REF). The UP output goes HIGH when SIG is lagging REF (the signal is slow relative to the reference); the DN output goes HIGH when SIG is leading REF (the signal is fast). Together UP and DN drive the charge pump or VCO control in a phase-locked loop (PLL) system.',
    pinout: [
      { pin: 1, name: 'SIG',  type: 'input'  },
      { pin: 2, name: 'REF',  type: 'input'  },
      { pin: 3, name: 'UP',   type: 'output' },
      { pin: 4, name: 'GND',  type: 'power'  },
      { pin: 5, name: 'DN',   type: 'output' },
      { pin: 6, name: 'NC',   type: 'nc'     },
      { pin: 7, name: 'NC2',  type: 'nc'     },
      { pin: 8, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['SIG','REF'], outputs: ['UP','DN'] },
    ],
  },

  // 74933: 7 bit address bus comparator (20-pin)
  '74933': {
    name: '74x933',
    simpleName: '7 bit Address Bus Comparator',
    description: '7 bit address bus comparator (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: '',
    tags: ['comparator', 'bus', '7 bit', 'stub'],
    guideOverview: 'The 74x933 is a 7 bit address bus comparator. It compares two 7 bit words A0–A6 and B0–B6 bit by bit, and asserts the EQ output HIGH when all seven bit pairs match. Use for address decoding where matching the seven least-significant bits of an address to a fixed base value is sufficient, or where comparing a 7 bit tag or index between two buses is needed.',
    pinout: [
      { pin:  1, name: 'A0',   type: 'input'  },
      { pin:  2, name: 'B0',   type: 'input'  },
      { pin:  3, name: 'A1',   type: 'input'  },
      { pin:  4, name: 'B1',   type: 'input'  },
      { pin:  5, name: 'A2',   type: 'input'  },
      { pin:  6, name: 'B2',   type: 'input'  },
      { pin:  7, name: 'A3',   type: 'input'  },
      { pin:  8, name: 'B3',   type: 'input'  },
      { pin:  9, name: 'A4',   type: 'input'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'B4',   type: 'input'  },
      { pin: 12, name: 'A5',   type: 'input'  },
      { pin: 13, name: 'B5',   type: 'input'  },
      { pin: 14, name: 'A6',   type: 'input'  },
      { pin: 15, name: 'B6',   type: 'input'  },
      { pin: 16, name: 'EQ',   type: 'output' },
      { pin: 17, name: 'NC',   type: 'nc'     },
      { pin: 18, name: 'NC2',  type: 'nc'     },
      { pin: 19, name: 'NC3',  type: 'nc'     },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['A0','B0','A1','B1','A2','B2','A3','B3','A4','B4','A5','B5','A6','B6'], outputs: ['EQ'] },
    ],
  },

  // 74936: ADC for 3.75-digit digital voltmeter with multiplexed 7-segment display outputs (28-pin)
  '74936': {
    name: '74x936',
    simpleName: 'ADC 3.75-Digit DVM (7-Seg)',
    description: 'ADC for 3.75-digit digital voltmeters with multiplexed 7-segment display outputs (28-pin)',
    pins: 28, vcc: 28, gnd: 14,
    datasheet: '',
    tags: ['adc', 'analog', 'voltmeter', '7-segment', 'stub'],
    guideOverview: 'The 74x936 is an ADC designed for 3.75-digit digital voltmeter (DVM) applications with multiplexed 7-segment display outputs. An internal dual-slope integrator converts the differential analog input (IN+ minus IN−) referenced to REF+/REF−. The chip drives 7-segment outputs a–g and digit select lines D1–D4 directly. POL indicates measurement polarity; HV signals over-range. C1/C2 are integrator capacitor pins; OSC sets conversion timing; TEST initiates a self-test; STB synchronizes the display latch.',
    pinout: [
      { pin:  1, name: 'IN+',  type: 'input'  },
      { pin:  2, name: 'IN-',  type: 'input'  },
      { pin:  3, name: 'REF+', type: 'input'  },
      { pin:  4, name: 'REF-', type: 'input'  },
      { pin:  5, name: 'C1',   type: 'input'  },
      { pin:  6, name: 'C2',   type: 'input'  },
      { pin:  7, name: 'OSC',  type: 'input'  },
      { pin:  8, name: 'TEST', type: 'input'  },
      { pin:  9, name: 'STB',  type: 'output' },
      { pin: 10, name: 'a',    type: 'output' },
      { pin: 11, name: 'b',    type: 'output' },
      { pin: 12, name: 'c',    type: 'output' },
      { pin: 13, name: 'd',    type: 'output' },
      { pin: 14, name: 'GND',  type: 'power'  },
      { pin: 15, name: 'e',    type: 'output' },
      { pin: 16, name: 'f',    type: 'output' },
      { pin: 17, name: 'g',    type: 'output' },
      { pin: 18, name: 'POL',  type: 'output' },
      { pin: 19, name: 'D1',   type: 'output' },
      { pin: 20, name: 'D2',   type: 'output' },
      { pin: 21, name: 'D3',   type: 'output' },
      { pin: 22, name: 'D4',   type: 'output' },
      { pin: 23, name: 'HV',   type: 'output' },
      { pin: 24, name: 'NC',   type: 'nc'     },
      { pin: 25, name: 'NC2',  type: 'nc'     },
      { pin: 26, name: 'NC3',  type: 'nc'     },
      { pin: 27, name: 'NC4',  type: 'nc'     },
      { pin: 28, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['IN+','IN-','REF+','REF-','C1','C2','OSC','TEST'], outputs: ['STB','a','b','c','d','e','f','g','POL','D1','D2','D3','D4','HV'] },
    ],
  },

  // 74937: ADC for 3.5-digit digital voltmeter with multiplexed BCD outputs (24-pin)
  '74937': {
    name: '74x937',
    simpleName: 'ADC 3.5-Digit DVM (BCD)',
    description: 'ADC for 3.5-digit digital voltmeters with multiplexed BCD outputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['adc', 'analog', 'voltmeter', 'bcd', 'stub'],
    guideOverview: 'The 74x937 is an ADC for 3.5-digit digital voltmeter applications with multiplexed BCD outputs. Like the 74x936 it uses a dual-slope integrator for conversion, but outputs the digit values as 4 bit BCD codes (Q0–Q3) instead of 7-segment patterns. Digit select lines D1–D4 cycle through up to four digit positions; POL indicates polarity; HV indicates over-range. An external BCD-to-7-segment decoder then drives the display. Maximum reading is 1999 (3.5 digits).',
    pinout: [
      { pin:  1, name: 'IN+',  type: 'input'  },
      { pin:  2, name: 'IN-',  type: 'input'  },
      { pin:  3, name: 'REF+', type: 'input'  },
      { pin:  4, name: 'REF-', type: 'input'  },
      { pin:  5, name: 'C1',   type: 'input'  },
      { pin:  6, name: 'C2',   type: 'input'  },
      { pin:  7, name: 'OSC',  type: 'input'  },
      { pin:  8, name: 'TEST', type: 'input'  },
      { pin:  9, name: 'STB',  type: 'output' },
      { pin: 10, name: 'Q0',   type: 'output' },
      { pin: 11, name: 'Q1',   type: 'output' },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'Q2',   type: 'output' },
      { pin: 14, name: 'Q3',   type: 'output' },
      { pin: 15, name: 'POL',  type: 'output' },
      { pin: 16, name: 'D1',   type: 'output' },
      { pin: 17, name: 'D2',   type: 'output' },
      { pin: 18, name: 'D3',   type: 'output' },
      { pin: 19, name: 'D4',   type: 'output' },
      { pin: 20, name: 'HV',   type: 'output' },
      { pin: 21, name: 'NC',   type: 'nc'     },
      { pin: 22, name: 'NC2',  type: 'nc'     },
      { pin: 23, name: 'NC3',  type: 'nc'     },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['IN+','IN-','REF+','REF-','C1','C2','OSC','TEST'], outputs: ['STB','Q0','Q1','Q2','Q3','POL','D1','D2','D3','D4','HV'] },
    ],
  },

  // 74938: ADC for 3.75-digit digital voltmeter with multiplexed BCD outputs (24-pin)
  '74938': {
    name: '74x938',
    simpleName: 'ADC 3.75-Digit DVM (BCD)',
    description: 'ADC for 3.75-digit digital voltmeters with multiplexed BCD outputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['adc', 'analog', 'voltmeter', 'bcd', 'stub'],
    guideOverview: 'The 74x938 is an ADC for 3.75-digit digital voltmeter applications with multiplexed BCD outputs. Like the 74x937 it outputs BCD digit data (Q0–Q3) and uses dual-slope integration, but provides 3.75-digit resolution (maximum reading 3999) rather than 3.5 digits. Digit select lines D1–D4, polarity (POL), and over-range (HV) operate identically to the 74x937. Use when a higher full-scale range is required while keeping BCD data outputs for external decoding.',
    pinout: [
      { pin:  1, name: 'IN+',  type: 'input'  },
      { pin:  2, name: 'IN-',  type: 'input'  },
      { pin:  3, name: 'REF+', type: 'input'  },
      { pin:  4, name: 'REF-', type: 'input'  },
      { pin:  5, name: 'C1',   type: 'input'  },
      { pin:  6, name: 'C2',   type: 'input'  },
      { pin:  7, name: 'OSC',  type: 'input'  },
      { pin:  8, name: 'TEST', type: 'input'  },
      { pin:  9, name: 'STB',  type: 'output' },
      { pin: 10, name: 'Q0',   type: 'output' },
      { pin: 11, name: 'Q1',   type: 'output' },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'Q2',   type: 'output' },
      { pin: 14, name: 'Q3',   type: 'output' },
      { pin: 15, name: 'POL',  type: 'output' },
      { pin: 16, name: 'D1',   type: 'output' },
      { pin: 17, name: 'D2',   type: 'output' },
      { pin: 18, name: 'D3',   type: 'output' },
      { pin: 19, name: 'D4',   type: 'output' },
      { pin: 20, name: 'HV',   type: 'output' },
      { pin: 21, name: 'NC',   type: 'nc'     },
      { pin: 22, name: 'NC2',  type: 'nc'     },
      { pin: 23, name: 'NC3',  type: 'nc'     },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['IN+','IN-','REF+','REF-','C1','C2','OSC','TEST'], outputs: ['STB','Q0','Q1','Q2','Q3','POL','D1','D2','D3','D4','HV'] },
    ],
  },

  // 74940: Octal bus/line driver/receiver, Schmitt trigger, three-state (20-pin)
  '74940': {
    name: '74x940',
    simpleName: 'Octal Bus/Line Driver (TRI)',
    description: 'Octal bus/line drivers/line receivers with Schmitt trigger inputs and three-state outputs (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: '',
    tags: ['bus driver', 'line receiver', 'octal', 'schmitt-trigger', 'tri-state', 'stub'],
    guideOverview: 'The 74x940 is an octal non-inverting bus/line driver with Schmitt trigger inputs and 3-state outputs. Eight channels buffer their nA inputs to the nY outputs with hysteresis on each input to reject noise and slow-slewing signals. OEn (active LOW) places all eight 3-state outputs into high impedance for bus sharing. Use when driving a noisy or long bus line and clean digital transitions are required on the output.',
    pinout: [
      { pin:  1, name: 'OEn',  type: 'input'  },
      { pin:  2, name: '1A',   type: 'input'  },
      { pin:  3, name: '2A',   type: 'input'  },
      { pin:  4, name: '3A',   type: 'input'  },
      { pin:  5, name: '4A',   type: 'input'  },
      { pin:  6, name: '5A',   type: 'input'  },
      { pin:  7, name: '6A',   type: 'input'  },
      { pin:  8, name: '7A',   type: 'input'  },
      { pin:  9, name: '8A',   type: 'input'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: '8Y',   type: 'output' },
      { pin: 12, name: '7Y',   type: 'output' },
      { pin: 13, name: '6Y',   type: 'output' },
      { pin: 14, name: '5Y',   type: 'output' },
      { pin: 15, name: '4Y',   type: 'output' },
      { pin: 16, name: '3Y',   type: 'output' },
      { pin: 17, name: '2Y',   type: 'output' },
      { pin: 18, name: '1Y',   type: 'output' },
      { pin: 19, name: 'NC',   type: 'nc'     },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','1A','2A','3A','4A','5A','6A','7A','8A'], outputs: ['1Y','2Y','3Y','4Y','5Y','6Y','7Y','8Y'] },
    ],
  },

  // 74941: Octal bus/line driver/receiver, Schmitt trigger, three-state (20-pin)
  '74941': {
    name: '74x941',
    simpleName: 'Octal Bus/Line Driver (TRI, Inv)',
    description: 'Octal bus/line drivers/line receivers with Schmitt trigger inputs and inverting three-state outputs (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: '',
    tags: ['bus driver', 'line receiver', 'octal', 'schmitt-trigger', 'tri-state', 'stub'],
    guideOverview: 'The 74x941 is the inverting version of the 74x940 — an octal bus/line driver with Schmitt trigger inputs and inverting 3-state outputs. Each of the eight channels produces a logic-inverted output relative to its nA input, with hysteresis on the input threshold for noise rejection. OEn (active LOW) enables the 3-state outputs. Use when the receiving bus requires inverted polarity and input noise immunity is needed.',
    pinout: [
      { pin:  1, name: 'OEn',  type: 'input'  },
      { pin:  2, name: '1A',   type: 'input'  },
      { pin:  3, name: '2A',   type: 'input'  },
      { pin:  4, name: '3A',   type: 'input'  },
      { pin:  5, name: '4A',   type: 'input'  },
      { pin:  6, name: '5A',   type: 'input'  },
      { pin:  7, name: '6A',   type: 'input'  },
      { pin:  8, name: '7A',   type: 'input'  },
      { pin:  9, name: '8A',   type: 'input'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: '8Y',   type: 'output' },
      { pin: 12, name: '7Y',   type: 'output' },
      { pin: 13, name: '6Y',   type: 'output' },
      { pin: 14, name: '5Y',   type: 'output' },
      { pin: 15, name: '4Y',   type: 'output' },
      { pin: 16, name: '3Y',   type: 'output' },
      { pin: 17, name: '2Y',   type: 'output' },
      { pin: 18, name: '1Y',   type: 'output' },
      { pin: 19, name: 'NC',   type: 'nc'     },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','1A','2A','3A','4A','5A','6A','7A','8A'], outputs: ['1Y','2Y','3Y','4Y','5Y','6Y','7Y','8Y'] },
    ],
  },

  // 74952: Dual rank 8 bit shift register, synchronous clear, three-state (18-pin)
  '74952': {
    name: '74x952',
    simpleName: 'Dual Rank 8 bit Shift Register (Sync CLR, TRI)',
    description: 'Dual rank 8 bit shift register with synchronous clear and three-state outputs (18-pin)',
    pins: 18, vcc: 18, gnd: 9,
    datasheet: '',
    tags: ['shift register', '8 bit', 'dual rank', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x952 is a dual-rank 8 bit serial shift register with synchronous clear and 3-state outputs. Serial data enters on SER and advances one position on each rising CLK edge. CLRn (active LOW) synchronously clears all eight stages to zero on the next clock edge. OEn (active LOW) enables the 3-state outputs Q0–Q7. The dual-rank design separates the shift and output stages so the output byte remains stable while a new byte is being shifted in.',
    pinout: [
      { pin: 14, name: 'NC',   type: 'nc'     },
      { pin: 15, name: 'NC2',  type: 'nc'     },
      { pin: 16, name: 'NC3',  type: 'nc'     },
      { pin: 17, name: 'NC4',  type: 'nc'     },
      { pin: 18, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['CLK','SER','CLRn','OEn'], outputs: ['Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7'] },
    ],
  },

  // 74x956: Octal bus transceiver and latch, three-state (24-pin)
  '74x956': {
    name: '74x956',
    simpleName: 'Octal Bus Transceiver and Latch (TRI)',
    description: 'Octal bus transceiver and latch with three-state outputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['transceiver', 'latch', 'octal', 'bus', 'tri-state', 'stub'],
    guideOverview: 'The 74x956 is an octal bus transceiver with an integrated latch and 3-state outputs. It buffers eight bidirectional data bits between the A and B bus sides. DIR selects the transfer direction; OEAn and OEBn (both active LOW) independently enable each side. LE (latch enable) when LOW freezes the output register so the last data values are held stable while the bus changes. Use in bus interfaces that need address or data latching alongside bidirectional transceiver buffering.',
    pinout: [
      { pin:  1, name: 'OEAn', type: 'input'  },
      { pin:  2, name: 'A0',   type: 'bidir'  },
      { pin:  3, name: 'A1',   type: 'bidir'  },
      { pin:  4, name: 'A2',   type: 'bidir'  },
      { pin:  5, name: 'A3',   type: 'bidir'  },
      { pin:  6, name: 'A4',   type: 'bidir'  },
      { pin:  7, name: 'A5',   type: 'bidir'  },
      { pin:  8, name: 'A6',   type: 'bidir'  },
      { pin:  9, name: 'A7',   type: 'bidir'  },
      { pin: 10, name: 'LE',   type: 'input'  },
      { pin: 11, name: 'DIR',  type: 'input'  },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'OEBn', type: 'input'  },
      { pin: 14, name: 'B7',   type: 'bidir'  },
      { pin: 15, name: 'B6',   type: 'bidir'  },
      { pin: 16, name: 'B5',   type: 'bidir'  },
      { pin: 17, name: 'B4',   type: 'bidir'  },
      { pin: 18, name: 'B3',   type: 'bidir'  },
      { pin: 19, name: 'B2',   type: 'bidir'  },
      { pin: 20, name: 'B1',   type: 'bidir'  },
      { pin: 21, name: 'B0',   type: 'bidir'  },
      { pin: 22, name: 'NC',   type: 'nc'     },
      { pin: 23, name: 'NC2',  type: 'nc'     },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEAn','LE','DIR','OEBn'], outputs: [] },
    ],
  },

  // 74962: Dual rank 8 bit shift register with register exchange mode, three-state (18-pin)
  '74962': {
    name: '74x962',
    simpleName: 'Dual Rank 8 bit Shift Register (Exchange, TRI)',
    description: 'Dual rank 8 bit shift register with register exchange mode and three-state outputs (18-pin)',
    pins: 18, vcc: 18, gnd: 9,
    datasheet: '',
    tags: ['shift register', '8 bit', 'dual rank', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x962 is a dual-rank 8 bit shift register with a register exchange mode and 3-state outputs. Serial data shifts in via SER on rising CLK edges. When XCHG is asserted, the contents of the internal shift stage and the output stage are swapped simultaneously, enabling atomic exchange of two 8 bit values without data loss. OEn (active LOW) enables the 3-state outputs Q0–Q7. Use in buffered serial communications or double-buffered pipelines.',
    pinout: [
      { pin:  1, name: 'CLK',  type: 'input'  },
      { pin:  2, name: 'SER',  type: 'input'  },
      { pin:  3, name: 'XCHG', type: 'input'  },
      { pin:  4, name: 'OEn',  type: 'input'  },
      { pin:  5, name: 'Q0',   type: 'output' },
      { pin:  6, name: 'Q1',   type: 'output' },
      { pin:  7, name: 'Q2',   type: 'output' },
      { pin:  8, name: 'Q3',   type: 'output' },
      { pin:  9, name: 'GND',  type: 'power'  },
      { pin: 10, name: 'Q4',   type: 'output' },
      { pin: 11, name: 'Q5',   type: 'output' },
      { pin: 12, name: 'Q6',   type: 'output' },
      { pin: 13, name: 'Q7',   type: 'output' },
      { pin: 14, name: 'NC',   type: 'nc'     },
      { pin: 15, name: 'NC2',  type: 'nc'     },
      { pin: 16, name: 'NC3',  type: 'nc'     },
      { pin: 17, name: 'NC4',  type: 'nc'     },
      { pin: 18, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['CLK','SER','XCHG','OEn'], outputs: ['Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7'] },
    ],
  },

  // 74963: Dual rank 8 bit shift register, synchronous clear, three-state (20-pin)
  '74963': {
    name: '74x963',
    simpleName: 'Dual Rank 8 bit Shift Register (Sync CLR, TRI, 20-pin)',
    description: 'Dual rank 8 bit shift register with synchronous clear and three-state outputs (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: '',
    tags: ['shift register', '8 bit', 'dual rank', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x963 is a dual-rank 8 bit shift register with synchronous clear and two independent 3-state output enables in a 20-pin package. Serial data enters on SER and shifts on rising CLK edges. CLRn synchronously clears both ranks. OEAn and OEBn independently enable the two output groups (Q0–Q7 and QA0–QA3), allowing one output rank to be gated to high impedance while the other drives the bus.',
    pinout: [
      { pin:  1, name: 'CLK',  type: 'input'  },
      { pin:  2, name: 'SER',  type: 'input'  },
      { pin:  3, name: 'CLRn', type: 'input'  },
      { pin:  4, name: 'OEAn', type: 'input'  },
      { pin:  5, name: 'OEBn', type: 'input'  },
      { pin:  6, name: 'Q0',   type: 'output' },
      { pin:  7, name: 'Q1',   type: 'output' },
      { pin:  8, name: 'Q2',   type: 'output' },
      { pin:  9, name: 'Q3',   type: 'output' },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'Q4',   type: 'output' },
      { pin: 12, name: 'Q5',   type: 'output' },
      { pin: 13, name: 'Q6',   type: 'output' },
      { pin: 14, name: 'Q7',   type: 'output' },
      { pin: 15, name: 'QA0',  type: 'output' },
      { pin: 16, name: 'QA1',  type: 'output' },
      { pin: 17, name: 'QA2',  type: 'output' },
      { pin: 18, name: 'QA3',  type: 'output' },
      { pin: 19, name: 'NC',   type: 'nc'     },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['CLK','SER','CLRn','OEAn','OEBn'], outputs: ['Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7','QA0','QA1','QA2','QA3'] },
    ],
  },

  // 74964: Dual rank 8 bit shift register, synchronous and asynchronous clear, three-state (20-pin)
  '74964': {
    name: '74x964',
    simpleName: 'Dual Rank 8 bit Shift Register (Sync+Async CLR, TRI)',
    description: 'Dual rank 8 bit shift register with synchronous and asynchronous clear and three-state outputs (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: '',
    tags: ['shift register', '8 bit', 'dual rank', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x964 is a dual-rank 8 bit shift register with both synchronous (CLRn) and asynchronous (ACLRn) clear, plus two independent 3-state enables. ACLRn (active LOW) immediately clears all stages to zero regardless of the clock state; CLRn clears synchronously on the next rising CLK edge. Serial data shifts in on SER each clock. OEAn and OEBn independently enable the Q0–Q7 and QA0–QA3 output groups.',
    pinout: [
      { pin:  5, name: 'OEAn', type: 'input'  },
      { pin:  6, name: 'OEBn', type: 'input'  },
      { pin:  7, name: 'Q0',   type: 'output' },
      { pin:  8, name: 'Q1',   type: 'output' },
      { pin:  9, name: 'Q2',   type: 'output' },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'Q3',   type: 'output' },
      { pin: 12, name: 'Q4',   type: 'output' },
      { pin: 13, name: 'Q5',   type: 'output' },
      { pin: 14, name: 'Q6',   type: 'output' },
      { pin: 15, name: 'Q7',   type: 'output' },
      { pin: 16, name: 'QA0',  type: 'output' },
      { pin: 17, name: 'QA1',  type: 'output' },
      { pin: 18, name: 'QA2',  type: 'output' },
      { pin: 19, name: 'QA3',  type: 'output' },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['CLK','SER','CLRn','ACLRn','OEAn','OEBn'], outputs: ['Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7','QA0','QA1','QA2','QA3'] },
    ],
  },
};