// Chip definitions block 18
// Chips: 74x265-74x285

export const CHIPS_BLOCK_18 = {

  // ── 74265: Quad Complementary Output Elements ─────────────────────────────
  /* Primary source: Texas Instruments, SN74265 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74265.pdf */
  '74x265': {
    name: '74x265',
    simpleName: 'Quad Compl. Buffer',
    description: 'Quad complementary elements, each with Q and /Q outputs (14-pin)',
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74265.pdf',
    tags: ['buffer', 'complementary', 'inverter', 'logic', 'quad'],
    guideOverview: 'The 74x265 contains four complementary output elements. Each section has one input (A) and two outputs: Y (non inverting, same polarity as A) and Yn (inverting, opposite polarity). This eliminates the need for a separate inverter when both the true and complemented versions of a signal are required a common need in clock trees, differential signaling stubs, and control logic.',
    guidePinDescriptions: {
      '1A':  'Section 1 input.',
      '1Y':  'Section 1 non inverting output. Follows 1A.',
      '1Yn': 'Section 1 inverting output. Complement of 1A.',
      '2A':  'Section 2 input.',
      '2Y':  'Section 2 non inverting output.',
      '2Yn': 'Section 2 inverting output.',
      'GND': 'Ground reference (pin 7).',
      '3Yn': 'Section 3 inverting output.',
      '3Y':  'Section 3 non inverting output.',
      '3A':  'Section 3 input.',
      '4Yn': 'Section 4 inverting output.',
      '4Y':  'Section 4 non inverting output.',
      '4A':  'Section 4 input.',
      'VCC': 'Positive supply (+5 V, pin 14).',
    },
    pinout: [
      { pin:  1, name: '1A',  type: 'input' },
      { pin:  2, name: '1Y',  type: 'output' },
      { pin:  3, name: '1Yn', type: 'output' },
      { pin:  4, name: '2A',  type: 'input' },
      { pin:  5, name: '2Y',  type: 'output' },
      { pin:  6, name: '2Yn', type: 'output' },
      { pin:  7, name: 'GND', type: 'power' },
      { pin:  8, name: '3Yn', type: 'output' },
      { pin:  9, name: '3Y',  type: 'output' },
      { pin: 10, name: '3A',  type: 'input' },
      { pin: 11, name: '4Yn', type: 'output' },
      { pin: 12, name: '4Y',  type: 'output' },
      { pin: 13, name: '4A',  type: 'input' },
      { pin: 14, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'BUFFER_COMP', inputs: ['1A'], outputs: ['1Y', '1Yn'] },
      { type: 'BUFFER_COMP', inputs: ['2A'], outputs: ['2Y', '2Yn'] },
      { type: 'BUFFER_COMP', inputs: ['3A'], outputs: ['3Y', '3Yn'] },
      { type: 'BUFFER_COMP', inputs: ['4A'], outputs: ['4Y', '4Yn'] },
    ],
    guideSections: [
      {
        title: 'Complementary Outputs',
        paragraphs: [
          'Having both Q and /Q available on the same chip simplifies layouts: you route one wire and get both phases without adding a NOT gate. This is particularly useful in registered clock trees where both rising edge and falling edge flip flops are present, or when driving push pull stages that need complementary drive signals.',
        ],
      },
    ],
  },

  // ── 74268: Hex D Type Latches, Tri state ─────────────────────────────────
  /* Primary source: Texas Instruments, SN74268 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74268.pdf
     Wikipedia: https://en.wikipedia.org/wiki/Flip-flop_(electronics)
     Wikipedia: https://en.wikipedia.org/wiki/Three-state_logic */
  '74x268': {
    name: '74x268',
    simpleName: 'Hex D Latches (3-state)',
    description: 'Hex D-type latch, shared gate enable, 3-state output control (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74268.pdf',
    tags: ['latch', 'd type', 'hex', 'tri state', 'sequential'],
    sequential: true,
    guideOverview: 'The 74x268 is a hex (6 bit) D type latch with 3-state outputs. A shared Gate pin G controls transparency for all six bits simultaneously: when G is HIGH, each Q output follows its D input (transparent); when G goes LOW, all six bits are latched (stored). A separate Output Enable pin OEn (active LOW) controls whether the Q outputs are driven or tri stated, allowing the chip to connect to a shared bus.',
    guidePinDescriptions: {
      'G':   'Latch gate enable. HIGH = transparent (Q tracks D); LOW = latch (Q holds last value).',
      '1D':  'Data input for bit 1.',
      '2D':  'Data input for bit 2.',
      '3D':  'Data input for bit 3.',
      '4D':  'Data input for bit 4.',
      '5D':  'Data input for bit 5.',
      '6D':  'Data input for bit 6.',
      'GND': 'Ground reference (pin 8).',
      'OEn': 'Output Enable (active LOW). When asserted (LOW), drives Q outputs; when HIGH, tri states them.',
      '6Q':  'Latched output for bit 6.',
      '5Q':  'Latched output for bit 5.',
      '4Q':  'Latched output for bit 4.',
      '3Q':  'Latched output for bit 3.',
      '2Q':  'Latched output for bit 2.',
      '1Q':  'Latched output for bit 1.',
      'VCC': 'Positive supply (+5 V, pin 16).',
    },
    pinout: [
      { pin:  1, name: 'G',   type: 'input' },
      { pin:  2, name: '1D',  type: 'input' },
      { pin:  3, name: '2D',  type: 'input' },
      { pin:  4, name: '3D',  type: 'input' },
      { pin:  5, name: '4D',  type: 'input' },
      { pin:  6, name: '5D',  type: 'input' },
      { pin:  7, name: '6D',  type: 'input' },
      { pin:  8, name: 'GND', type: 'power' },
      { pin:  9, name: 'OEn', type: 'input' },
      { pin: 10, name: '6Q',  type: 'output' },
      { pin: 11, name: '5Q',  type: 'output' },
      { pin: 12, name: '4Q',  type: 'output' },
      { pin: 13, name: '3Q',  type: 'output' },
      { pin: 14, name: '2Q',  type: 'output' },
      { pin: 15, name: '1Q',  type: 'output' },
      { pin: 16, name: 'VCC', type: 'power' },
    ],
    gates: [
      {
        type: 'D_LATCH_HEX_TRI',
        inputs: ['1D','2D','3D','4D','5D','6D','G','OEn'],
        outputs: ['1Q','2Q','3Q','4Q','5Q','6Q'],
      },
    ],
    guideSections: [
      {
        title: 'Transparent Latch with Bus Output',
        paragraphs: [
          'The 74x268 combines two common functions: transparent latching (like the 74x373 octal latch) and 3-state bus driving. Use G to capture data at a specific moment, then use OEn to drive the stored value onto a shared bus without releasing the latch. With G=LOW and OEn=LOW, the chip acts as a 6 bit register driving the bus.',
        ],
      },
    ],
  },

  // ── 74269: 8 bit Bidirectional Binary Counter ──────────────────────────────
  /* Primary source: Texas Instruments, MC74F269 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/mc74f269.pdf
     Wikipedia: https://en.wikipedia.org/wiki/Counter_(digital) */
  '74x269': {
    name: '74x269',
    simpleName: '8 bit Bidir Counter',
    description: '8-bit sync up/down binary counter, sync load and clear (24-pin)',
    pins: 24,
    vcc: 24,
    gnd: 12,
    datasheet: 'https://www.ti.com/lit/ds/symlink/mc74f269.pdf',
    tags: ['counter', '8 bit', 'bidirectional', 'synchronous', 'presettable', 'sequential'],
    sequential: true,
    guideOverview: 'The 74x269 is an 8 bit synchronous up/down binary counter a wider version of the 74x169 (4 bit). It counts on the rising edge of CLK, with ENP and ENT controlling counting enable and TC (Terminal Count) cascade output. U_Dn (HIGH=up, LOW=down) selects the counting direction. LOAD (active LOW synchronous) loads A0 A7 into the counter on the next clock edge. Eight bits span 0 255.',
    guidePinDescriptions: {
      'CLK':  'Clock input. Counter updates on rising edge.',
      'ENT':  'Enable (terminal count) input. Both ENT and ENP must be HIGH to count; ENT also enables TC output.',
      'ENP':  'Enable (parallel) input. Both ENP and ENT must be HIGH to count.',
      'U_Dn': 'Up/Down select. HIGH = count up; LOW = count down.',
      'LOAD': 'Synchronous load (active LOW). On next rising CLK edge, loads A0 A7 into counter.',
      'A0':   'Parallel data input bit 0 (LSB).',
      'A1':   'Parallel data input bit 1.',
      'A2':   'Parallel data input bit 2.',
      'A3':   'Parallel data input bit 3.',
      'A4':   'Parallel data input bit 4.',
      'A5':   'Parallel data input bit 5.',
      'GND':  'Ground reference (pin 12).',
      'A6':   'Parallel data input bit 6.',
      'A7':   'Parallel data input bit 7 (MSB).',
      'Q7':   'Counter output bit 7 (MSB).',
      'Q6':   'Counter output bit 6.',
      'Q5':   'Counter output bit 5.',
      'Q4':   'Counter output bit 4.',
      'Q3':   'Counter output bit 3.',
      'Q2':   'Counter output bit 2.',
      'Q1':   'Counter output bit 1.',
      'Q0':   'Counter output bit 0 (LSB).',
      'TC':   'Terminal Count output. HIGH when counter reaches max (up) or 0 (down) and ENT=HIGH. Used for cascading.',
      'VCC':  'Positive supply (+5 V, pin 24).',
    },
    pinout: [
      { pin:  1, name: 'CLK',  type: 'input' },
      { pin:  2, name: 'ENT',  type: 'input' },
      { pin:  3, name: 'ENP',  type: 'input' },
      { pin:  4, name: 'U_Dn', type: 'input' },
      { pin:  5, name: 'LOAD', type: 'input' },
      { pin:  6, name: 'A0',   type: 'input' },
      { pin:  7, name: 'A1',   type: 'input' },
      { pin:  8, name: 'A2',   type: 'input' },
      { pin:  9, name: 'A3',   type: 'input' },
      { pin: 10, name: 'A4',   type: 'input' },
      { pin: 11, name: 'A5',   type: 'input' },
      { pin: 12, name: 'GND',  type: 'power' },
      { pin: 13, name: 'A6',   type: 'input' },
      { pin: 14, name: 'A7',   type: 'input' },
      { pin: 15, name: 'Q7',   type: 'output' },
      { pin: 16, name: 'Q6',   type: 'output' },
      { pin: 17, name: 'Q5',   type: 'output' },
      { pin: 18, name: 'Q4',   type: 'output' },
      { pin: 19, name: 'Q3',   type: 'output' },
      { pin: 20, name: 'Q2',   type: 'output' },
      { pin: 21, name: 'Q1',   type: 'output' },
      { pin: 22, name: 'Q0',   type: 'output' },
      { pin: 23, name: 'TC',   type: 'output' },
      { pin: 24, name: 'VCC',  type: 'power' },
    ],
    gates: [
      {
        type: 'COUNTER_8BIT_BIDIR',
        inputs: ['CLK','ENT','ENP','U_Dn','LOAD','A0','A1','A2','A3','A4','A5','A6','A7'],
        outputs: ['Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7','TC'],
      },
    ],
    guideSections: [
      {
        title: 'Synchronous Up/Down Counting',
        paragraphs: [
          'Synchronous counters update all bits simultaneously on the clock edge, avoiding the glitches of ripple counters. Both ENP and ENT must be HIGH to count; hold either LOW to pause counting while keeping the count value intact.',
          'TC goes HIGH when the counter reaches 255 (counting up) or 0 (counting down) and ENT is HIGH. Tie the TC of the lower chip to the ENT of the next chip to cascade two 74x269s into a 16 bit counter.',
        ],
      },
    ],
  },

  // ── 74274: 4 bit by 4 bit Binary Multiplier, Tri state ───────────────────
  /* Primary source: Texas Instruments, SN74S274 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74s274.pdf
     Wikipedia: https://en.wikipedia.org/wiki/Three-state_logic */
  '74x274': {
    name: '74x274',
    simpleName: '4×4 Multiplier (3-state)',
    description: '4 bit by 4 bit parallel binary multiplier with 3-state output (20-pin)',
    pins: 20,
    vcc: 20,
    gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74s274.pdf',
    tags: ['multiplier', 'binary', '4 bit', 'tri state', 'arithmetic'],
    guideOverview: 'The 74x274 is a 4×4 bit parallel binary multiplier with 3-state outputs. It multiplies two unsigned 4 bit numbers (X0 X3 and Y0 Y3) and produces an 8 bit product (P0 P7) combinationally. Output Enable (active LOW): when asserted (LOW), drives product outputs; when HIGH, tri states them, allowing multiple multipliers to share a product bus.',
    guidePinDescriptions: {
      'X0':  'Multiplicand bit 0 (LSB).',
      'X1':  'Multiplicand bit 1.',
      'X2':  'Multiplicand bit 2.',
      'X3':  'Multiplicand bit 3 (MSB).',
      'Y0':  'Multiplier bit 0 (LSB).',
      'Y1':  'Multiplier bit 1.',
      'Y2':  'Multiplier bit 2.',
      'Y3':  'Multiplier bit 3 (MSB).',
      'OEn': 'Output Enable (active LOW). When asserted (LOW), drives P outputs; when HIGH, tri states them.',
      'GND': 'Ground reference (pin 10).',
      'P0':  'Product bit 0 (LSB).',
      'P1':  'Product bit 1.',
      'P2':  'Product bit 2.',
      'P3':  'Product bit 3.',
      'P4':  'Product bit 4.',
      'P5':  'Product bit 5.',
      'P6':  'Product bit 6.',
      'P7':  'Product bit 7 (MSB).',
      'NC1': 'Not connected.',
      'VCC': 'Positive supply (+5 V, pin 20).',
    },
    pinout: [
      { pin:  1, name: 'X0',  type: 'input' },
      { pin:  2, name: 'X1',  type: 'input' },
      { pin:  3, name: 'X2',  type: 'input' },
      { pin:  4, name: 'X3',  type: 'input' },
      { pin:  5, name: 'Y0',  type: 'input' },
      { pin:  6, name: 'Y1',  type: 'input' },
      { pin:  7, name: 'Y2',  type: 'input' },
      { pin:  8, name: 'Y3',  type: 'input' },
      { pin:  9, name: 'OEn', type: 'input' },
      { pin: 10, name: 'GND', type: 'power' },
      { pin: 11, name: 'P0',  type: 'output' },
      { pin: 12, name: 'P1',  type: 'output' },
      { pin: 13, name: 'P2',  type: 'output' },
      { pin: 14, name: 'P3',  type: 'output' },
      { pin: 15, name: 'P4',  type: 'output' },
      { pin: 16, name: 'P5',  type: 'output' },
      { pin: 17, name: 'P6',  type: 'output' },
      { pin: 18, name: 'P7',  type: 'output' },
      { pin: 19, name: 'NC1', type: 'nc' },
      { pin: 20, name: 'VCC', type: 'power' },
    ],
    gates: [
      {
        type: 'MULT_4X4BIT_TRI',
        inputs: ['X0','X1','X2','X3','Y0','Y1','Y2','Y3','OEn'],
        outputs: ['P0','P1','P2','P3','P4','P5','P6','P7'],
      },
    ],
    guideSections: [
      {
        title: '4×4 bit Unsigned Multiplication',
        paragraphs: [
          'The product of two 4 bit values (0 15) requires 8 bits (0 225). The 74x274 computes all partial products in parallel, so the result appears at the outputs after just one propagation delay. Unlike the 74x284/285 pair, the 74x274 integrates the full 8 bit product in a single chip.',
        ],
        formulas: [
          'P[7:0] = X[3:0] × Y[3:0] (unsigned)',
          'Max: 15 × 15 = 225 (0xE1)',
        ],
      },
    ],
  },

  // ── 74275: 7 bit Slice Wallace Tree ──────────────────────────────────────
  /* Primary source: Texas Instruments, SN74S275 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74s275.pdf */
  '74x275': {
    name: '74x275',
    simpleName: '7 bit Wallace Tree Slice',
    description: '7-bit slice Wallace tree multiplier element (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74s275.pdf',
    tags: ['multiplier', 'wallace tree', 'arithmetic', 'carry save'],
    guideOverview: 'The 74x275 is a 7 bit slice Wallace tree element used to build fast parallel multipliers. A Wallace tree reduces multiple partial product bits at the same column weight to a two number sum (sum + carry) using a network of full adders, enabling multiplication in O(log N) gate stages. The 74x275 processes 7 input bits per bit position and produces partial sum and carry outputs for the next stage.',
    guidePinDescriptions: {
      'W0':  'Input partial product bit 0.',
      'W1':  'Input partial product bit 1.',
      'W2':  'Input partial product bit 2.',
      'W3':  'Input partial product bit 3.',
      'X0':  'Input partial product bit 4.',
      'X1':  'Input partial product bit 5.',
      'Y0':  'Input partial product bit 6.',
      'GND': 'Ground reference (pin 8).',
      'Y1':  'Carry output to the next bit position.',
      'S0':  'Carry save sum output bit 0.',
      'S1':  'Carry save sum output bit 1.',
      'S2':  'Carry save sum output bit 2.',
      'S3':  'Carry save sum output bit 3.',
      'C2':  'Carry output from adder level 2.',
      'C3':  'Carry output from adder level 3.',
      'VCC': 'Positive supply (+5 V, pin 16).',
    },
    pinout: [
      { pin:  1, name: 'W0',  type: 'input' },
      { pin:  2, name: 'W1',  type: 'input' },
      { pin:  3, name: 'W2',  type: 'input' },
      { pin:  4, name: 'W3',  type: 'input' },
      { pin:  5, name: 'X0',  type: 'input' },
      { pin:  6, name: 'X1',  type: 'input' },
      { pin:  7, name: 'Y0',  type: 'input' },
      { pin:  8, name: 'GND', type: 'power' },
      { pin:  9, name: 'Y1',  type: 'output' },
      { pin: 10, name: 'S0',  type: 'output' },
      { pin: 11, name: 'S1',  type: 'output' },
      { pin: 12, name: 'S2',  type: 'output' },
      { pin: 13, name: 'S3',  type: 'output' },
      { pin: 14, name: 'C2',  type: 'output' },
      { pin: 15, name: 'C3',  type: 'output' },
      { pin: 16, name: 'VCC', type: 'power' },
    ],
    gates: [
      {
        type: 'WALLACE_TREE_7BIT',
        inputs: ['W0','W1','W2','W3','X0','X1','Y0'],
        outputs: ['S0','S1','S2','S3','C2','C3','Y1'],
      },
    ],
    guideSections: [
      {
        title: 'Wallace Tree Multiplication',
        paragraphs: [
          'In Wallace tree multiplication, partial products from all pairs of multiplier and multiplicand bits are organized by column (bit weight) and reduced using carry save adders (CSA). Each CSA takes three inputs and produces a sum and a carry out, reducing 3 bits to 2 at each stage. After log₂N stages, only two rows remain, and a single fast adder produces the final product.',
          'The 74x275 is one slice: it handles 7 bits at one bit position. Multiple slices are cascaded horizontally and vertically to build large multipliers (e.g., 8×8 or 16×16).',
        ],
      },
    ],
  },

  // ── 74276: Quad JK FFs, Separate Clocks, Shared PRE/CLR ─────────────────
  /* Primary source: Texas Instruments, SN74276 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74276.pdf
     Wikipedia: https://en.wikipedia.org/wiki/Flip-flop_(electronics) */
  '74x276': {
    name: '74x276',
    simpleName: 'Quad JK FF (sep. CLK)',
    description: 'Quad JK flip-flops, separate clocks, shared preset and clear (20-pin)',
    pins: 20,
    vcc: 20,
    gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74276.pdf',
    tags: ['flip flop', 'jk', 'quad', 'sequential', 'controller device'],
    sequential: true,
    guideOverview: 'The 74x276 contains four JK flip flops sharing a common clock (CLK, active LOW) and a combined preset/clear pin (PRE/CLR, active LOW). Each flip flop has independent J and K inputs and both Q and Q (inverted) outputs. JK logic: J=0,K=0 → hold; J=1,K=0 → set; J=0,K=1 → reset; J=1,K=1 → toggle on clock edge. The chip is intended for controller to device interface applications where a toggle or set/reset pattern drives peripheral control lines.',
    guidePinDescriptions: {
      'CLKn':    'Clock input (active LOW edge). All four flip flops clock on falling edge.',
      '1J':      'J input for flip flop 1.',
      '1K':      'K input for flip flop 1.',
      '1Q':      'Q output for flip flop 1.',
      '1Qn':     'Complement Q output for flip flop 1.',
      '2J':      'J input for flip flop 2.',
      '2K':      'K input for flip flop 2.',
      '2Q':      'Q output for flip flop 2.',
      '2Qn':     'Complement Q output for flip flop 2.',
      'GND':     'Ground reference (pin 10).',
      '3Q':      'Q output for flip flop 3.',
      '3Qn':     'Complement Q output for flip flop 3.',
      '3K':      'K input for flip flop 3.',
      '3J':      'J input for flip flop 3.',
      '4Q':      'Q output for flip flop 4.',
      '4Qn':     'Complement Q output for flip flop 4.',
      '4K':      'K input for flip flop 4.',
      '4J':      'J input for flip flop 4.',
      'PRE_CLRn': 'Combined Preset/Clear (active LOW). Asynchronously presets or clears all flip flops.',
      'VCC':     'Positive supply (+5 V, pin 20).',
    },
    pinout: [
      { pin:  1, name: 'CLKn',   type: 'input' },
      { pin:  2, name: '1J',     type: 'input' },
      { pin:  3, name: '1K',     type: 'input' },
      { pin:  4, name: '1Q',     type: 'output' },
      { pin:  5, name: '1Qn',    type: 'output' },
      { pin:  6, name: '2J',     type: 'input' },
      { pin:  7, name: '2K',     type: 'input' },
      { pin:  8, name: '2Q',     type: 'output' },
      { pin:  9, name: '2Qn',    type: 'output' },
      { pin: 10, name: 'GND',    type: 'power' },
      { pin: 11, name: '3Q',     type: 'output' },
      { pin: 12, name: '3Qn',    type: 'output' },
      { pin: 13, name: '3K',     type: 'input' },
      { pin: 14, name: '3J',     type: 'input' },
      { pin: 15, name: '4Q',     type: 'output' },
      { pin: 16, name: '4Qn',    type: 'output' },
      { pin: 17, name: '4K',     type: 'input' },
      { pin: 18, name: '4J',     type: 'input' },
      { pin: 19, name: 'PRE_CLRn', type: 'input' },
      { pin: 20, name: 'VCC',    type: 'power' },
    ],
    gates: [
      {
        type: 'JK_FF_QUAD_SEP_CLK',
        inputs: ['CLKn','1J','1K','2J','2K','3J','3K','4J','4K','PRE_CLRn'],
        outputs: ['1Q','1Qn','2Q','2Qn','3Q','3Qn','4Q','4Qn'],
      },
    ],
    guideSections: [
      {
        title: 'JK Flip Flop Modes',
        paragraphs: [
          'The JK flip flop is the most versatile storage element because J=1,K=1 causes a toggle on every clock edge. This allows it to function as: a D flip flop (tie K = NOT J), an SR flip flop (J=S, K=R), a T flip flop (J=K=1), or a divide by-2 counter.',
        ],
        formulas: [
          'J=0, K=0 → Q unchanged (hold)',
          'J=1, K=0 → Q=1 (set)',
          'J=0, K=1 → Q=0 (reset)',
          'J=1, K=1 → Q=NOT(Q) (toggle)',
        ],
      },
    ],
  },

  // ── 74278: 4 bit Cascadeable Priority Register with Latched Inputs ─────────
  /* Primary source: Texas Instruments, SN74278 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74278.pdf
     Wikipedia: https://en.wikipedia.org/wiki/Flip-flop_(electronics) */
  '74x278': {
    name: '74x278',
    simpleName: '4 bit Priority Reg',
    description: '4 bit cascadeable priority registers with latched data inputs (14-pin)',
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74278.pdf',
    tags: ['priority', 'register', '4 bit', 'cascadeable', 'sequential'],
    sequential: true,
    guideOverview: 'The 74x278 is a 4 bit cascadeable priority register. It latches four data inputs (D0-D3) on the CLK edge and presents the address of the highest priority active input on Q0-Q2 (encoded). GS (Group Select) goes HIGH when any input is active. EO (Enable Output) goes LOW when all inputs are LOW, allowing cascading of multiple chips. EI (Enable Input) disables all outputs when LOW, enabling priority daisy chains.',
    guidePinDescriptions: {
      'D3':   'Data input 3 (highest priority). When HIGH, encodes to Q=11.',
      'D2':   'Data input 2.',
      'D1':   'Data input 1.',
      'D0':   'Data input 0 (lowest priority).',
      'EI':   'Enable Input. When LOW, disables all outputs and forces EO LOW (for cascading; tie HIGH on first chip).',
      'Q2':   'Priority encoded output bit 2 (MSB of 2 bit code).',
      'GND':  'Ground reference (pin 7).',
      'Q1':   'Priority encoded output bit 1.',
      'Q0':   'Priority encoded output bit 0 (LSB).',
      'GS':   'Group Select output. HIGH when any input is active and EI=HIGH.',
      'EO':   'Enable Output. Goes LOW when no inputs are active; connects to EI of next chip in cascade.',
      'CLK':  'Clock input. Latches current priority on rising edge.',
      'CLRn': 'Clear (active LOW). Asynchronously clears Q0-Q2 and GS.',
      'VCC':  'Positive supply (+5 V, pin 14).',
    },
    pinout: [
      { pin:  1, name: 'D3',  type: 'input' },
      { pin:  2, name: 'D2',  type: 'input' },
      { pin:  3, name: 'D1',  type: 'input' },
      { pin:  4, name: 'D0',  type: 'input' },
      { pin:  5, name: 'EI',  type: 'input' },
      { pin:  6, name: 'Q2',  type: 'output' },
      { pin:  7, name: 'GND', type: 'power' },
      { pin:  8, name: 'Q1',  type: 'output' },
      { pin:  9, name: 'Q0',  type: 'output' },
      { pin: 10, name: 'GS',  type: 'output' },
      { pin: 11, name: 'EO',  type: 'output' },
      { pin: 12, name: 'CLK', type: 'input' },
      { pin: 13, name: 'CLRn',type: 'input' },
      { pin: 14, name: 'VCC', type: 'power' },
    ],
    gates: [
      {
        type: 'PRIORITY_REG_4BIT',
        inputs: ['D0','D1','D2','D3','EI','CLK','CLRn'],
        outputs: ['Q0','Q1','Q2','GS','EO'],
      },
    ],
    guideSections: [
      {
        title: 'Priority Encoding',
        paragraphs: [
          'A priority encoder resolves conflicts when multiple inputs are active simultaneously by assigning fixed priority levels. The highest priority active input wins; lower priority inputs are ignored. Here D3 has highest priority.',
          'Cascading: connect EO of the lower priority chip to EI of the higher priority chip. GS on each chip signals whether that group contains the winning input.',
        ],
      },
    ],
  },

  // ── 74279: Quad Set Reset Latch ───────────────────────────────────────────
  /* Primary source: Texas Instruments, SN74LS279A datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls279a.pdf
     Wikipedia: https://en.wikipedia.org/wiki/Flip-flop_(electronics) */
  '74x279': {
    name: '74x279',
    simpleName: 'Quad SR Latch',
    description: 'Quad set reset latch (active LOW S and R inputs) (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls279a.pdf',
    tags: ['latch', 'sr', 'quad', 'sequential'],
    sequential: true,
    guideOverview: 'The 74x279 contains four SR latches with active LOW Set and Reset inputs. Sections 1 and 4 have two Set inputs (e.g., 1S1n and 1S2n) that are internally NANDed, allowing either input to set the latch. Sections 2 and 3 have single S inputs. All inputs are active LOW: pulling Sn LOW sets Q HIGH; pulling Rn LOW resets Q LOW. Do not assert both S and R simultaneously.',
    guidePinDescriptions: {
      '1Rn':  'Reset for section 1 (active LOW). Pulling LOW forces 1Q LOW.',
      '1S1n': 'Set input 1 for section 1 (active LOW). Either 1S1n or 1S2n LOW will set 1Q HIGH.',
      '1S2n': 'Set input 2 for section 1 (active LOW). NANDed with 1S1n internally.',
      '1Q':   'Output for section 1.',
      '2Rn':  'Reset for section 2 (active LOW).',
      '2Sn':  'Set for section 2 (active LOW).',
      '2Q':   'Output for section 2.',
      'GND':  'Ground reference (pin 8).',
      '3Q':   'Output for section 3.',
      '3Rn':  'Reset for section 3 (active LOW).',
      '3Sn':  'Set for section 3 (active LOW).',
      '4Q':   'Output for section 4.',
      '4Rn':  'Reset for section 4 (active LOW).',
      '4S1n': 'Set input 1 for section 4 (active LOW).',
      '4S2n': 'Set input 2 for section 4 (active LOW).',
      'VCC':  'Positive supply (+5 V, pin 16).',
    },
    pinout: [
      { pin:  1, name: '1Rn',  type: 'input' },
      { pin:  2, name: '1S1n', type: 'input' },
      { pin:  3, name: '1S2n', type: 'input' },
      { pin:  4, name: '1Q',   type: 'output' },
      { pin:  5, name: '2Rn',  type: 'input' },
      { pin:  6, name: '2Sn',  type: 'input' },
      { pin:  7, name: '2Q',   type: 'output' },
      { pin:  8, name: 'GND',  type: 'power' },
      { pin:  9, name: '3Q',   type: 'output' },
      { pin: 10, name: '3Rn',  type: 'input' },
      { pin: 11, name: '3Sn',  type: 'input' },
      { pin: 12, name: '4Q',   type: 'output' },
      { pin: 13, name: '4Rn',  type: 'input' },
      { pin: 14, name: '4S1n', type: 'input' },
      { pin: 15, name: '4S2n', type: 'input' },
      { pin: 16, name: 'VCC',  type: 'power' },
    ],
    gates: [
      { type: 'SR_LATCH_NOR_NAND', inputs: ['1S1n','1S2n','1Rn'], output: '1Q' },
      { type: 'SR_LATCH_NOR_NAND', inputs: ['2Sn','2Sn','2Rn'],  output: '2Q' },
      { type: 'SR_LATCH_NOR_NAND', inputs: ['3Sn','3Sn','3Rn'],  output: '3Q' },
      { type: 'SR_LATCH_NOR_NAND', inputs: ['4S1n','4S2n','4Rn'], output: '4Q' },
    ],
    guideSections: [
      {
        title: 'SR Latch Basics',
        paragraphs: [
          'An SR latch is the simplest sequential element. Set (S) forces Q HIGH; Reset (R) forces Q LOW. When both are deasserted, Q retains its last state. The forbidden state (S=R=0 for active LOW) should be avoided it causes both Q outputs to be HIGH simultaneously and results in a race condition when released.',
          'Typical use: debouncing a mechanical switch. Connect the two poles of the switch to S and R; the latch produces a clean output without contact bounce.',
        ],
        note: 'Never assert both Sn and Rn simultaneously (both LOW) this is the forbidden state.',
      },
    ],
  },

  // ── 74280: 9 bit Odd/Even Parity Generator/Checker ───────────────────────
  /* Primary source: Texas Instruments, SN74LS280 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls280.pdf
     Wikipedia: https://en.wikipedia.org/wiki/Parity_bit */
  '74x280': {
    name: '74x280',
    simpleName: '9 bit Parity Gen/Chk',
    description: '9 bit odd/even parity generator/checker (14-pin)',
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls280.pdf',
    tags: ['parity', '9 bit', 'logic', 'checker', 'generator'],
    guideOverview: 'The 74x280 is a 9 bit odd/even parity generator and checker. It XORs all nine inputs (A I) together and drives two complementary outputs: EVEN goes HIGH when an even number of inputs are HIGH; ODD goes HIGH when an odd number are HIGH. Used in data transmission to detect single bit errors: add a parity bit to make the total count odd (or even), then check at the receiver.',
    guidePinDescriptions: {
      'A':    'Parity input bit A.',
      'B':    'Parity input bit B.',
      'C':    'Parity input bit C.',
      'D':    'Parity input bit D.',
      'E':    'Parity input bit E.',
      'F':    'Parity input bit F.',
      'GND':  'Ground reference (pin 7).',
      'H':    'Parity input bit H.',
      'EVEN': 'Even parity output. HIGH when an even number of inputs are HIGH.',
      'ODD':  'Odd parity output. HIGH when an odd number of inputs are HIGH. EVEN and ODD are always complements.',
      'I':    'Parity input bit I.',
      'G':    'Parity input bit G.',
      'NC1':  'Not connected.',
      'VCC':  'Positive supply (+5 V, pin 14).',
    },
    pinout: [
      { pin:  1, name: 'A',      type: 'input' },
      { pin:  2, name: 'B',      type: 'input' },
      { pin:  3, name: 'C',      type: 'input' },
      { pin:  4, name: 'D',      type: 'input' },
      { pin:  5, name: 'E',      type: 'input' },
      { pin:  6, name: 'F',      type: 'input' },
      { pin:  7, name: 'GND',    type: 'power' },
      { pin:  8, name: 'H',      type: 'input' },
      { pin:  9, name: 'EVEN',   type: 'output' },
      { pin: 10, name: 'ODD',    type: 'output' },
      { pin: 11, name: 'I',      type: 'input' },
      { pin: 12, name: 'G',      type: 'input' },
      { pin: 13, name: 'NC1',    type: 'nc' },
      { pin: 14, name: 'VCC',    type: 'power' },
    ],
    gates: [
      { type: 'PARITY_9BIT_SIMPLE', inputs: ['A','B','C','D','E','F','G','H','I'], outputs: ['EVEN','ODD'] },
    ],
    guideSections: [
      {
        title: 'Parity Generation and Checking',
        paragraphs: [
          'For generation: send 8 data bits through A H, and tie I to 0. Connect the ODD output as the parity bit appended to the 8 bit word (odd parity convention).',
          'For checking: send all 9 bits (8 data + 1 parity) through A I. If ODD=HIGH, parity is correct (odd count maintained). If ODD=LOW, a single bit error was detected.',
        ],
        formulas: [
          'EVEN = NOT(A XOR B XOR C XOR D XOR E XOR F XOR G XOR H XOR I)',
          'ODD  = A XOR B XOR C XOR D XOR E XOR F XOR G XOR H XOR I',
        ],
      },
    ],
  },

  // ── 74281: 4 bit Parallel Binary Accumulator ─────────────────────────────
  /* Primary source: Texas Instruments, SN74S281 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74s281.pdf
     Wikipedia: https://en.wikipedia.org/wiki/Adder_(electronics)
     Wikipedia: https://en.wikipedia.org/wiki/Arithmetic_logic_unit */
  '74x281': {
    name: '74x281',
    simpleName: '4 bit Accumulator',
    description: '4 bit parallel binary accumulator with synchronous load and carry (24-pin)',
    pins: 24,
    vcc: 24,
    gnd: 12,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74s281.pdf',
    tags: ['accumulator', '4 bit', 'arithmetic', 'sequential', 'adder'],
    sequential: true,
    guideOverview: 'The 74x281 is a 4 bit parallel binary accumulator that combines an ALU like function unit with a clocked 4 bit register. B0 B3 are the external data inputs; M0 M3 and S0 S3 select the arithmetic or logic function. On each rising CLK edge, the result of the selected operation is stored in the internal register. CLRn asynchronously clears the register. This chip is used to iteratively accumulate sums, products, or logic operations.',
    guidePinDescriptions: {
      'B0':   'External operand input bit 0 (LSB).',
      'B1':   'External operand input bit 1.',
      'B2':   'External operand input bit 2.',
      'B3':   'External operand input bit 3 (MSB).',
      'CLK':  'Clock input. On rising edge, stores the result into the internal register.',
      'M0':   'Mode/mask control bit 0.',
      'M1':   'Mode/mask control bit 1.',
      'M2':   'Mode/mask control bit 2.',
      'M3':   'Mode/mask control bit 3.',
      'S0':   'Function select bit 0.',
      'S1':   'Function select bit 1.',
      'GND':  'Ground reference (pin 12).',
      'S2':   'Function select bit 2.',
      'S3':   'Function select bit 3.',
      'Cn':   'Carry input for arithmetic operations.',
      'CLRn': 'Clear (active LOW). Asynchronously resets the internal register to 0.',
      'F0':   'Result output bit 0.',
      'F1':   'Result output bit 1.',
      'F2':   'Result output bit 2.',
      'F3':   'Result output bit 3.',
      'Cn4':  'Carry output from the MSB position.',
      'OVR':  'Overflow output. HIGH when signed arithmetic overflow occurs.',
      'NC1':  'Not connected.',
      'VCC':  'Positive supply (+5 V, pin 24).',
    },
    pinout: [
      { pin:  1, name: 'B0',   type: 'input' },
      { pin:  2, name: 'B1',   type: 'input' },
      { pin:  3, name: 'B2',   type: 'input' },
      { pin:  4, name: 'B3',   type: 'input' },
      { pin:  5, name: 'CLK',  type: 'input' },
      { pin:  6, name: 'M0',   type: 'input' },
      { pin:  7, name: 'M1',   type: 'input' },
      { pin:  8, name: 'M2',   type: 'input' },
      { pin:  9, name: 'M3',   type: 'input' },
      { pin: 10, name: 'S0',   type: 'input' },
      { pin: 11, name: 'S1',   type: 'input' },
      { pin: 12, name: 'GND',  type: 'power' },
      { pin: 13, name: 'S2',   type: 'input' },
      { pin: 14, name: 'S3',   type: 'input' },
      { pin: 15, name: 'Cn',   type: 'input' },
      { pin: 16, name: 'CLRn', type: 'input' },
      { pin: 17, name: 'F0',   type: 'output' },
      { pin: 18, name: 'F1',   type: 'output' },
      { pin: 19, name: 'F2',   type: 'output' },
      { pin: 20, name: 'F3',   type: 'output' },
      { pin: 21, name: 'Cn4',  type: 'output' },
      { pin: 22, name: 'OVR',  type: 'output' },
      { pin: 23, name: 'NC1',  type: 'nc' },
      { pin: 24, name: 'VCC',  type: 'power' },
    ],
    gates: [
      {
        type: 'ACCUMULATOR_4BIT',
        inputs: ['B0','B1','B2','B3','M0','M1','M2','M3','S0','S1','S2','S3','Cn','CLRn','CLK'],
        outputs: ['F0','F1','F2','F3','Cn4','OVR'],
      },
    ],
    guideSections: [
      {
        title: 'Accumulation Principle',
        paragraphs: [
          'An accumulator repeatedly applies an operation (addition, subtraction, AND, OR, etc.) between an incoming value and the current stored value, replacing the stored value with the result each clock cycle. This is the fundamental operation of a CPU’s arithmetic logic unit.',
          'Example: to sum a series of values B0, B1, B2..., configure the function select for ADD, start with CLRn=LOW then HIGH (clear to 0), then clock in each value in turn. After N clocks, the register contains the running total.',
        ],
      },
    ],
  },

  // ── 74282: Look Ahead Carry Generator (Selectable) ───────────────────────
  /* Primary source: Texas Instruments, SN74AS282 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74as282.pdf
     Wikipedia: https://en.wikipedia.org/wiki/Adder_(electronics)
     Wikipedia: https://en.wikipedia.org/wiki/Arithmetic_logic_unit */
  '74x282': {
    name: '74x282',
    simpleName: 'Look Ahead Carry (sel)',
    description: 'High speed look ahead carry generator with selectable carry inputs (20-pin)',
    pins: 20,
    vcc: 20,
    gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74as282.pdf',
    tags: ['carry', 'look ahead', 'alu', 'arithmetic', 'carry generator'],
    guideOverview: 'The 74x282 is a look ahead carry generator with selectable carry inputs. Like the 74x264/74x182, it takes Propagate (P0 P3) and Generate (G0 G3) signals from four ALU slices and generates carry outputs Cn4, Cn8, Cn12 for 4 bit groups. The SEL input, along with P_in and G_in, selects between the locally computed carry or an external carry source, enabling flexible multi level lookahead in wider adders.',
    guidePinDescriptions: {
      'P0':   'Propagate from ALU slice 0.',
      'G0':   'Generate from ALU slice 0.',
      'P1':   'Propagate from ALU slice 1.',
      'G1':   'Generate from ALU slice 1.',
      'P2':   'Propagate from ALU slice 2.',
      'G2':   'Generate from ALU slice 2.',
      'P3':   'Propagate from ALU slice 3.',
      'G3':   'Generate from ALU slice 3.',
      'Cn':   'Carry input (to bit 0 of group).',
      'GND':  'Ground reference (pin 10).',
      'Cn4':  'Carry into bit 4.',
      'Cn8':  'Carry into bit 8.',
      'Cn12': 'Carry into bit 12.',
      'G':    'Group Generate output.',
      'P':    'Group Propagate output.',
      'SEL':  'Select input. Controls whether the internal or external P/G is used for higher level lookahead.',
      'P_in': 'External Propagate input (selected by SEL).',
      'G_in': 'External Generate input (selected by SEL).',
      'NC1':  'Not connected.',
      'VCC':  'Positive supply (+5 V, pin 20).',
    },
    pinout: [
      { pin:  1, name: 'P0',   type: 'input' },
      { pin:  2, name: 'G0',   type: 'input' },
      { pin:  3, name: 'P1',   type: 'input' },
      { pin:  4, name: 'G1',   type: 'input' },
      { pin:  5, name: 'P2',   type: 'input' },
      { pin:  6, name: 'G2',   type: 'input' },
      { pin:  7, name: 'P3',   type: 'input' },
      { pin:  8, name: 'G3',   type: 'input' },
      { pin:  9, name: 'Cn',   type: 'input' },
      { pin: 10, name: 'GND',  type: 'power' },
      { pin: 11, name: 'Cn4',  type: 'output' },
      { pin: 12, name: 'Cn8',  type: 'output' },
      { pin: 13, name: 'Cn12', type: 'output' },
      { pin: 14, name: 'G',    type: 'output' },
      { pin: 15, name: 'P',    type: 'output' },
      { pin: 16, name: 'SEL',  type: 'input' },
      { pin: 17, name: 'P_in', type: 'input' },
      { pin: 18, name: 'G_in', type: 'input' },
      { pin: 19, name: 'NC1',  type: 'nc' },
      { pin: 20, name: 'VCC',  type: 'power' },
    ],
    gates: [
      {
        type: 'CARRY_LOOKAHEAD_SEL',
        inputs: ['P0','G0','P1','G1','P2','G2','P3','G3','Cn','SEL','P_in','G_in'],
        outputs: ['Cn4','Cn8','Cn12','P','G'],
      },
    ],
    guideSections: [
      {
        title: 'Selectable Carry Source',
        paragraphs: [
          'The SEL input allows the 74x282 to work in two modes. When SEL=LOW, the chip behaves like a standard 74x182 / 74x264. When SEL=HIGH, the P_in and G_in values (from an external carry source) are substituted into the lookahead equations, enabling multi tier lookahead schemes where the 74x282 receives partial group P/G from another unit.',
        ],
      },
    ],
  },

  // ── 74283: 4 bit Binary Full Adder ────────────────────────────────────────
  /* Sources:
     [1] Texas Instruments, "SN54283, SN54LS283, SN54S283, SN74283, SN74LS283,
         SN74S283 4-Bit Binary Full Adders With Fast Carry", SDLS095A, Oct. 1976
         (rev. Mar. 1988). [Online]. Available:
         https://www.ti.com/lit/ds/symlink/sn74ls283.pdf. Verified: terminal
         assignment (D/N package, top view), function table, and logic diagram,
         pages 1-2, read as rendered PDF page images (issues.md C4). Confirms
         pin 9 = C4 (carry out), C0 (carry in) on pin 7, power on the corner pins
         (VCC=16, GND=8), and that the 283 is functionally identical to the older
         83 with only the terminal arrangement changed.
     [2] Wikipedia contributors, "Adder (electronics)."
         https://en.wikipedia.org/wiki/Adder_(electronics). Used only for the
         general full-adder and carry-look-ahead background. */
  '74x283': {
    name: '74x283',
    simpleName: '4 bit Full Adder',
    description: '4 bit binary full adder with fast (look-ahead) carry. (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls283.pdf',
    tags: ['adder', '4 bit', 'binary', 'full adder', 'arithmetic', 'carry'],
    guideOverview: 'The 74x283 adds two 4 bit binary numbers plus a carry in, producing a 4 bit sum (S1 to S4) and a carry out (C4). It is one of the most common 74 series arithmetic chips, and it is purely combinational: with no clock, the outputs settle as soon as the inputs are stable. What sets it apart from a hand-built adder is fast carry. A plain adder lets the carry ripple up one bit at a time, so the top sum bit is the slowest to appear; the 74x283 computes all four carries in parallel with a look-ahead network, so the whole sum is ready sooner. Two things surprise beginners: the power pins sit on the corners (VCC=16, GND=8) instead of the usual places, and the operand and sum pins are interleaved down the package rather than grouped by name, so check the pinout before wiring. To add wider numbers, chain chips by wiring C4 of one stage to C0 of the next.',
    guidePinDescriptions: {
      'S2':  'Bit 2 of the sum output.',
      'B2':  'Bit 2 of input number B.',
      'A2':  'Bit 2 of input number A.',
      'S1':  'Bit 1 (LSB) of the sum output.',
      'A1':  'Bit 1 (LSB) of input number A.',
      'B1':  'Bit 1 (LSB) of input number B.',
      'C0':  'Carry in. Tie to GND for a standalone adder or the lowest stage; drive it from C4 of the stage below when cascading.',
      'GND': 'Ground reference (pin 8, on the corner).',
      'C4':  'Carry out of the top bit. Wire to C0 of the next stage when cascading. It is effectively the fifth, most significant bit of the sum.',
      'S4':  'Bit 4 (MSB) of the sum output.',
      'B4':  'Bit 4 (MSB) of input number B.',
      'A4':  'Bit 4 (MSB) of input number A.',
      'S3':  'Bit 3 of the sum output.',
      'A3':  'Bit 3 of input number A.',
      'B3':  'Bit 3 of input number B.',
      'VCC': 'Positive supply, +5 V (pin 16, on the corner).',
    },
    // Pinout verified against TI SDLS095A, D/N package top view (read as PDF page
    // images, issues.md C4): operand, sum and carry pins are interleaved down the
    // package (NOT grouped by name), and power sits on the corners (VCC=16, GND=8).
    // Pin 9 is the carry out C4 (this entry previously mis-named it 'S5'; the
    // physical assignment was correct, only the label was wrong — see issues.md).
    pinout: [
      { pin:  1, name: 'S2',   type: 'output' },
      { pin:  2, name: 'B2',   type: 'input' },
      { pin:  3, name: 'A2',   type: 'input' },
      { pin:  4, name: 'S1',   type: 'output' },
      { pin:  5, name: 'A1',   type: 'input' },
      { pin:  6, name: 'B1',   type: 'input' },
      { pin:  7, name: 'C0',   type: 'input' },
      { pin:  8, name: 'GND',  type: 'power' },
      { pin:  9, name: 'C4',   type: 'output' },
      { pin: 10, name: 'S4',   type: 'output' },
      { pin: 11, name: 'B4',   type: 'input' },
      { pin: 12, name: 'A4',   type: 'input' },
      { pin: 13, name: 'S3',   type: 'output' },
      { pin: 14, name: 'A3',   type: 'input' },
      { pin: 15, name: 'B3',   type: 'input' },
      { pin: 16, name: 'VCC',  type: 'power' },
    ],
    gates: [
      { type: 'ADDER_4BIT', inputs: ['A1','A2','A3','A4','B1','B2','B3','B4','C0'], outputs: ['S1','S2','S3','S4','C4'] },
    ],
    guideSections: [
      {
        title: 'How a full adder works',
        paragraphs: [
          'Binary addition works column by column, exactly like decimal: add the two bits in a column, and if the result is too big for one bit, carry a 1 into the next column. A full adder is the circuit for one column. It takes two bits plus a carry in, and produces a sum bit and a carry out.',
          'The 74x283 stacks four of these, one per bit, and drives the carry chain with a look-ahead network so the carries do not have to ripple through in sequence. Because it is combinational you do not clock it: present A, B, and C0, wait for the propagation delay (on the order of 10 to 25 ns for LS parts, depending on logic family, temperature, and load; this is a simplification), then read the answer.',
        ],
        formulas: [
          'One bit:  Sum = A XOR B XOR Cin;   Cout = 1 when two or more of A, B, Cin are 1',
          'A B Cin -> Sum Cout:  000 -> 0 0 | 001 -> 1 0 | 010 -> 1 0 | 011 -> 0 1 | 100 -> 1 0 | 101 -> 0 1 | 110 -> 0 1 | 111 -> 1 1',
        ],
      },
      {
        title: 'A worked example',
        paragraphs: [
          'Put A = 1001 (9) on A4 A3 A2 A1, and B = 0111 (7) on B4 B3 B2 B1, with C0 = 0. The chip adds 9 + 7 = 16, which does not fit in four bits: the sum pins read S4 S3 S2 S1 = 0000 and C4 = 1, giving the full 5 bit answer 10000 (16). That extra bit is why C4 is best read as the top bit of the sum, not a separate signal.',
        ],
        formulas: [
          '(C4, S4, S3, S2, S1) = A + B + C0     — a 5 bit result from two 4 bit inputs plus C0',
        ],
      },
      {
        title: 'Cascading and gotchas',
        paragraphs: [
          'To add numbers wider than four bits, chain chips: wire C4 of the low stage into C0 of the next stage, and so on. Two 74x283s make an 8 bit adder, and the C4 of the top chip is the final carry out. Because the carry logic is non-inverting (the datasheet calls it "true form"), you can cascade directly with no inverters between stages.',
        ],
        list: [
          'Tie C0 of the lowest stage to GND, not floating. A floating carry in gives wrong sums.',
          'Power is on the corner pins (VCC=16, GND=8), unlike most 16-pin logic. Double-check before powering up.',
          'The pins are interleaved (S2, B2, A2, S1, A1, B1 down one side), not grouped by signal. Read the pinout, do not guess.',
          'It is the same logic as the 74x83, but not a drop-in replacement: the 74x83 has a different pinout, with power at pins 5 and 12.',
        ],
        note: 'The 283 and LS283 are functionally identical to the older 83A/LS83A; TI rearranged only the terminals to put power and ground on the corner pins.',
      },
    ],
  },

  // ── 74284: 4×4 bit Binary Multiplier (High Order Product Bits) ────────────
  /* Primary source: Texas Instruments, SN74284 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74284.pdf */
  '74x284': {
    name: '74x284',
    simpleName: '4×4 Multiplier (High)',
    description: '4x4-bit parallel binary multiplier: high 4 bits of product (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74284.pdf',
    tags: ['multiplier', 'binary', '4 bit', 'arithmetic', 'high-order'],
    guideOverview: 'The 74x284 produces the high order four bits (P4 P7) of an 8 bit product from a 4×4 bit unsigned multiplication. It is always used in combination with the 74x285 (which produces P0 P3). Together the pair creates a complete 4×4 bit multiplier. A0 A3 is the multiplier and B0 B3 is the multiplicand.',
    guidePinDescriptions: {
      'B0':  'Multiplicand bit 0 (LSB).',
      'B1':  'Multiplicand bit 1.',
      'B2':  'Multiplicand bit 2.',
      'B3':  'Multiplicand bit 3 (MSB).',
      'A0':  'Multiplier bit 0 (LSB).',
      'A1':  'Multiplier bit 1.',
      'A2':  'Multiplier bit 2.',
      'GND': 'Ground reference (pin 8).',
      'A3':  'Multiplier bit 3 (MSB).',
      'P4':  'Product bit 4 (high order half LSB).',
      'P5':  'Product bit 5.',
      'P6':  'Product bit 6.',
      'P7':  'Product bit 7 (MSB).',
      'NC1': 'Not connected.',
      'NC2': 'Not connected.',
      'VCC': 'Positive supply (+5 V, pin 16).',
    },
    pinout: [
      { pin:  1, name: 'B0',  type: 'input' },
      { pin:  2, name: 'B1',  type: 'input' },
      { pin:  3, name: 'B2',  type: 'input' },
      { pin:  4, name: 'B3',  type: 'input' },
      { pin:  5, name: 'A0',  type: 'input' },
      { pin:  6, name: 'A1',  type: 'input' },
      { pin:  7, name: 'A2',  type: 'input' },
      { pin:  8, name: 'GND', type: 'power' },
      { pin:  9, name: 'A3',  type: 'input' },
      { pin: 10, name: 'P4',  type: 'output' },
      { pin: 11, name: 'P5',  type: 'output' },
      { pin: 12, name: 'P6',  type: 'output' },
      { pin: 13, name: 'P7',  type: 'output' },
      { pin: 14, name: 'NC1', type: 'nc' },
      { pin: 15, name: 'NC2', type: 'nc' },
      { pin: 16, name: 'VCC', type: 'power' },
    ],
    gates: [
      {
        type: 'MULT_4X4BIT_HI',
        inputs: ['A0','A1','A2','A3','B0','B1','B2','B3'],
        outputs: ['P4','P5','P6','P7'],
      },
    ],
    guideSections: [
      {
        title: '74x284 + 74x285 = 4×4 Multiplier',
        paragraphs: [
          'These two chips form a matched pair: connect the same A and B inputs to both. The 74x285 output provides P0 P3 (low order nibble) and 74x284 provides P4 P7 (high order nibble). Together they produce the full 8 bit product of two 4 bit unsigned values.',
        ],
      },
    ],
  },

  // ── 74285: 4×4 bit Binary Multiplier (Low Order Product Bits) ─────────────
  /* Primary source: Texas Instruments, SN74285 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74285.pdf */
  '74x285': {
    name: '74x285',
    simpleName: '4×4 Multiplier (Low)',
    description: '4x4-bit parallel binary multiplier: low 4 bits of product (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74285.pdf',
    tags: ['multiplier', 'binary', '4 bit', 'arithmetic', 'low-order'],
    guideOverview: 'The 74x285 produces the low order four bits (P0 P3) of an 8 bit product from a 4×4 bit unsigned multiplication. It is always paired with the 74x284 (which produces P4 P7). Both chips receive the same A0 A3 (multiplier) and B0 B3 (multiplicand) inputs; their outputs P0 P7 together form the full 8 bit result.',
    guidePinDescriptions: {
      'B0':  'Multiplicand bit 0 (LSB).',
      'B1':  'Multiplicand bit 1.',
      'B2':  'Multiplicand bit 2.',
      'B3':  'Multiplicand bit 3 (MSB).',
      'A0':  'Multiplier bit 0 (LSB).',
      'A1':  'Multiplier bit 1.',
      'A2':  'Multiplier bit 2.',
      'GND': 'Ground reference (pin 8).',
      'A3':  'Multiplier bit 3 (MSB).',
      'P0':  'Product bit 0 (LSB).',
      'P1':  'Product bit 1.',
      'P2':  'Product bit 2.',
      'P3':  'Product bit 3 (low order half MSB).',
      'NC1': 'Not connected.',
      'NC2': 'Not connected.',
      'VCC': 'Positive supply (+5 V, pin 16).',
    },
    pinout: [
      { pin:  1, name: 'B0',  type: 'input' },
      { pin:  2, name: 'B1',  type: 'input' },
      { pin:  3, name: 'B2',  type: 'input' },
      { pin:  4, name: 'B3',  type: 'input' },
      { pin:  5, name: 'A0',  type: 'input' },
      { pin:  6, name: 'A1',  type: 'input' },
      { pin:  7, name: 'A2',  type: 'input' },
      { pin:  8, name: 'GND', type: 'power' },
      { pin:  9, name: 'A3',  type: 'input' },
      { pin: 10, name: 'P0',  type: 'output' },
      { pin: 11, name: 'P1',  type: 'output' },
      { pin: 12, name: 'P2',  type: 'output' },
      { pin: 13, name: 'P3',  type: 'output' },
      { pin: 14, name: 'NC1', type: 'nc' },
      { pin: 15, name: 'NC2', type: 'nc' },
      { pin: 16, name: 'VCC', type: 'power' },
    ],
    gates: [
      {
        type: 'MULT_4X4BIT_LO',
        inputs: ['A0','A1','A2','A3','B0','B1','B2','B3'],
        outputs: ['P0','P1','P2','P3'],
      },
    ],
    guideSections: [
      {
        title: 'Low Order Product Bits',
        paragraphs: [
          'P0 is always the AND of A0 and B0 (partial product of the two LSBs). P1 P3 involve XOR and carry logic from the partial product columns. The 74x285 computes these lower bits using a carry save adder tree, ensuring they are available at the same time as P4 P7 from the companion 74x284.',
        ],
      },
    ],
  },

};
