// Chip definitions block 46
// Chips: 74978, 74989-74996, 74x1000/1002-1005/1008, 74ALS1010

export const CHIPS_BLOCK_46 = {

  // 74978: Octal flip-flop with serial scanner (24-pin)
  '74978': {
    name: '74x978',
    simpleName: 'Octal FF with Serial Scanner',
    description: 'Octal flip-flop with serial scanner (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['flip-flop', 'octal', 'scanner', 'stub'],
    sequential: true,
    guideOverview: 'The 74x978 is an octal D-type flip-flop that adds a serial scanner output, useful in board-level testing. Eight data inputs load into eight flip-flops on a clock edge. When the scan enable (SEN) is asserted, the stored bits can be read out through the serial output (SO) without disturbing the parallel outputs. On a breadboard it is most useful for applications that need both normal parallel storage and a way to inspect the stored byte bit by bit. The simulator currently represents this as a generic stub.',
    pinout: [
      { pin:  1, name: 'CLK',  type: 'input'  },
      { pin:  2, name: 'D0',   type: 'input'  },
      { pin:  3, name: 'D1',   type: 'input'  },
      { pin:  4, name: 'D2',   type: 'input'  },
      { pin:  5, name: 'D3',   type: 'input'  },
      { pin:  6, name: 'D4',   type: 'input'  },
      { pin:  7, name: 'D5',   type: 'input'  },
      { pin:  8, name: 'D6',   type: 'input'  },
      { pin:  9, name: 'D7',   type: 'input'  },
      { pin: 10, name: 'OEn',  type: 'input'  },
      { pin: 11, name: 'SO',   type: 'output' },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'SEN',  type: 'input'  },
      { pin: 14, name: 'Q0',   type: 'output' },
      { pin: 15, name: 'Q1',   type: 'output' },
      { pin: 16, name: 'Q2',   type: 'output' },
      { pin: 17, name: 'Q3',   type: 'output' },
      { pin: 18, name: 'Q4',   type: 'output' },
      { pin: 19, name: 'Q5',   type: 'output' },
      { pin: 20, name: 'Q6',   type: 'output' },
      { pin: 21, name: 'Q7',   type: 'output' },
      { pin: 22, name: 'NC',   type: 'nc'     },
      { pin: 23, name: 'NC2',  type: 'nc'     },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['CLK','D0','D1','D2','D3','D4','D5','D6','D7','OEn','SEN'], outputs: ['SO','Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7'] },
    ],
  },

  // 74989: 64 bit RAM (16x4), inverting output, three-state (16-pin)
  '74989': {
    name: '74x989',
    simpleName: '64 bit RAM 16x4 Inv (TRI)',
    description: '64 bit RAM organized as 16 words x 4 bits with inverting three-state outputs (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    datasheet: '',
    tags: ['ram', 'memory', '64 bit', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x989 is a 64 bit static RAM organized as 16 words of 4 bits each, with inverting three-state outputs. Writing stores a 4 bit nibble at the selected address, and reading retrieves the complement of the stored value. On a breadboard it is useful as a small look-up table or as temporary storage for 4 bit values in a data path. The simulator currently represents this as a generic stub.',
    pinout: [
      { pin:  1, name: 'A0',   type: 'input'  },
      { pin:  2, name: 'A1',   type: 'input'  },
      { pin:  3, name: 'A2',   type: 'input'  },
      { pin:  4, name: 'A3',   type: 'input'  },
      { pin:  5, name: 'WEn',  type: 'input'  },
      { pin:  6, name: 'OEn',  type: 'input'  },
      { pin:  7, name: 'CSn',  type: 'input'  },
      { pin:  8, name: 'GND',  type: 'power'  },
      { pin:  9, name: 'D0',   type: 'bidir'  },
      { pin: 10, name: 'D1',   type: 'bidir'  },
      { pin: 11, name: 'D2',   type: 'bidir'  },
      { pin: 12, name: 'D3',   type: 'bidir'  },
      { pin: 13, name: 'NC',   type: 'nc'     },
      { pin: 14, name: 'NC2',  type: 'nc'     },
      { pin: 15, name: 'NC3',  type: 'nc'     },
      { pin: 16, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['A0','A1','A2','A3','WEn','OEn','CSn'], outputs: [] },
    ],
  },

  // 74990: 8 bit D-type transparent read-back latch, non-inverting, TRI (20-pin)
  '74990': {
    name: '74x990',
    simpleName: '8 bit Transparent Latch Read-Back (TRI)',
    description: '8 bit D-type transparent read-back latch, non-inverting, with three-state outputs (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74als990.pdf',
    tags: ['latch', '8 bit', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x990 is an octal transparent D-type latch with 3-state outputs and read-back behavior. A transparent latch can either pass input data straight through or hold the last value, making it useful as a byte-wide holding register between logic stages. On a breadboard it is a good choice when you want to capture a bus value, hold it, and then optionally present that stored byte back onto a shared bus.',
    guidePinDescriptions: {
      'OEn': 'Active LOW output enable. Pull LOW to let Q0-Q7 drive the bus, or HIGH to place the outputs in high impedance.',
      'D0': 'Data input bit 0.',
      'D1': 'Data input bit 1.',
      'D2': 'Data input bit 2.',
      'D3': 'Data input bit 3.',
      'D4': 'Data input bit 4.',
      'D5': 'Data input bit 5.',
      'D6': 'Data input bit 6.',
      'D7': 'Data input bit 7.',
      'GND': 'Ground reference for the device at pin 10.',
      'LE': 'Latch-enable control. It determines whether the latch is transparent or whether it holds the previously stored byte.',
      'Q7': 'Stored output bit 7.',
      'Q6': 'Stored output bit 6.',
      'Q5': 'Stored output bit 5.',
      'Q4': 'Stored output bit 4.',
      'Q3': 'Stored output bit 3.',
      'Q2': 'Stored output bit 2.',
      'Q1': 'Stored output bit 1.',
      'Q0': 'Stored output bit 0.',
      'VCC': 'Positive 5 V supply at pin 20.',
    },
    guideSections: [
      {
        title: 'Transparent Read-Back Latching',
        paragraphs: [
          'When the latch-enable control is active, the output follows the input. When the control is inactive, the most recent input word is stored and can be read later.',
          'That makes the 74x990 useful for temporarily holding a byte without needing a full edge-triggered register stage.',
        ],
      },
      {
        title: 'Why Read-Back Matters',
        paragraphs: [
          'Read-back latches are designed so stored information can be observed or placed on a bus when needed. Combined with a 3-state output enable, the part can stay electrically quiet until the rest of the system asks for that byte.',
        ],
        list: [
          'Capture a byte from a peripheral bus.',
          'Hold a state value for later inspection.',
          'Drive a shared backplane only when output enable (OE, active LOW) is asserted.',
        ],
        note: 'The simulator currently models this part as a generic stub rather than a full transparent-latch implementation.',
      },
    ],
    pinout: [
      { pin:  1, name: 'OEn',  type: 'input'  },
      { pin:  2, name: 'D0',   type: 'input'  },
      { pin:  3, name: 'D1',   type: 'input'  },
      { pin:  4, name: 'D2',   type: 'input'  },
      { pin:  5, name: 'D3',   type: 'input'  },
      { pin:  6, name: 'D4',   type: 'input'  },
      { pin:  7, name: 'D5',   type: 'input'  },
      { pin:  8, name: 'D6',   type: 'input'  },
      { pin:  9, name: 'D7',   type: 'input'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'LE',   type: 'input'  },
      { pin: 12, name: 'Q7',   type: 'output' },
      { pin: 13, name: 'Q6',   type: 'output' },
      { pin: 14, name: 'Q5',   type: 'output' },
      { pin: 15, name: 'Q4',   type: 'output' },
      { pin: 16, name: 'Q3',   type: 'output' },
      { pin: 17, name: 'Q2',   type: 'output' },
      { pin: 18, name: 'Q1',   type: 'output' },
      { pin: 19, name: 'Q0',   type: 'output' },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','D0','D1','D2','D3','D4','D5','D6','D7','LE'], outputs: ['Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7'] },
    ],
  },

  // 74991: 8 bit D-type transparent read-back latch, inverting, TRI (20-pin)
  '74991': {
    name: '74x991',
    simpleName: '8 bit Transparent Latch Read-Back Inv (TRI)',
    description: '8 bit D-type transparent read-back latch, inverting, with three-state outputs (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: '',
    tags: ['latch', '8 bit', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x991 is an octal transparent D-type latch with inverting 3-state outputs. Like the 74990, it can either pass data transparently or hold the last byte, but all eight outputs present the logical complement of the stored value. That inversion is useful when downstream logic needs an active LOW byte or when one extra complement stage would otherwise waste another gate package. The simulator currently represents this as a generic stub.',
    pinout: [
      { pin:  1, name: 'OEn',  type: 'input'  },
      { pin:  2, name: 'D0',   type: 'input'  },
      { pin:  3, name: 'D1',   type: 'input'  },
      { pin:  4, name: 'D2',   type: 'input'  },
      { pin:  5, name: 'D3',   type: 'input'  },
      { pin:  6, name: 'D4',   type: 'input'  },
      { pin:  7, name: 'D5',   type: 'input'  },
      { pin:  8, name: 'D6',   type: 'input'  },
      { pin:  9, name: 'D7',   type: 'input'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'LE',   type: 'input'  },
      { pin: 12, name: 'Q7n',  type: 'output' },
      { pin: 13, name: 'Q6n',  type: 'output' },
      { pin: 14, name: 'Q5n',  type: 'output' },
      { pin: 15, name: 'Q4n',  type: 'output' },
      { pin: 16, name: 'Q3n',  type: 'output' },
      { pin: 17, name: 'Q2n',  type: 'output' },
      { pin: 18, name: 'Q1n',  type: 'output' },
      { pin: 19, name: 'Q0n',  type: 'output' },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','D0','D1','D2','D3','D4','D5','D6','D7','LE'], outputs: ['Q0n','Q1n','Q2n','Q3n','Q4n','Q5n','Q6n','Q7n'] },
    ],
  },

  // 74992: 9 bit D-type transparent read-back latch, non-inverting, TRI (24-pin)
  '74992': {
    name: '74x992',
    simpleName: '9 bit Transparent Latch Read-Back (TRI)',
    description: '9 bit D-type transparent read-back latch, non-inverting, with three-state outputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74als992.pdf',
    tags: ['latch', '9 bit', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x992 extends the read-back latch idea to nine bits, which is useful for eight data bits plus a parity or status bit. It behaves like a transparent latch while enabled, then holds the captured word and can present it through 3-state outputs when the bus is ready. On a breadboard this makes it a natural fit for parity-protected buses or byte-plus-flag interfaces.',
    guidePinDescriptions: {
      'OEn': 'Active LOW output enable. Pull LOW to drive Q0-Q8, or HIGH to disconnect the outputs from the bus.',
      'D0': 'Data input bit 0.',
      'D1': 'Data input bit 1.',
      'D2': 'Data input bit 2.',
      'D3': 'Data input bit 3.',
      'D4': 'Data input bit 4.',
      'D5': 'Data input bit 5.',
      'D6': 'Data input bit 6.',
      'D7': 'Data input bit 7.',
      'D8': 'Data input bit 8, often used as a parity or status bit.',
      'LE': 'Latch-enable control for the 9 bit register.',
      'GND': 'Ground reference for the device at pin 12.',
      'Q8': 'Stored output bit 8.',
      'Q7': 'Stored output bit 7.',
      'Q6': 'Stored output bit 6.',
      'Q5': 'Stored output bit 5.',
      'Q4': 'Stored output bit 4.',
      'Q3': 'Stored output bit 3.',
      'Q2': 'Stored output bit 2.',
      'Q1': 'Stored output bit 1.',
      'Q0': 'Stored output bit 0.',
      'NC': 'No internal connection. Leave this pin unconnected.',
      'NC2': 'No internal connection. Leave this pin unconnected.',
      'VCC': 'Positive 5 V supply at pin 24.',
    },
    guideSections: [
      {
        title: 'Nine-Bit Bus Storage',
        paragraphs: [
          'A ninth stored bit is commonly used for parity, framing, or an extra control flag. The 74x992 keeps that extra bit synchronized with the rest of the byte instead of forcing you to add a separate single-bit latch.',
        ],
      },
      {
        title: 'Bus Isolation',
        paragraphs: [
          'Because the outputs are 3-state, the latch can hold data internally without always driving the bus. That is important on shared backplanes where only one device should talk at a time.',
        ],
        note: 'The simulator currently represents this device with a generic stub rather than a full 9 bit latch model.',
      },
    ],
    pinout: [
      { pin:  1, name: 'OEn',  type: 'input'  },
      { pin:  2, name: 'D0',   type: 'input'  },
      { pin:  3, name: 'D1',   type: 'input'  },
      { pin:  4, name: 'D2',   type: 'input'  },
      { pin:  5, name: 'D3',   type: 'input'  },
      { pin:  6, name: 'D4',   type: 'input'  },
      { pin:  7, name: 'D5',   type: 'input'  },
      { pin:  8, name: 'D6',   type: 'input'  },
      { pin:  9, name: 'D7',   type: 'input'  },
      { pin: 10, name: 'D8',   type: 'input'  },
      { pin: 11, name: 'LE',   type: 'input'  },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'Q8',   type: 'output' },
      { pin: 14, name: 'Q7',   type: 'output' },
      { pin: 15, name: 'Q6',   type: 'output' },
      { pin: 16, name: 'Q5',   type: 'output' },
      { pin: 17, name: 'Q4',   type: 'output' },
      { pin: 18, name: 'Q3',   type: 'output' },
      { pin: 19, name: 'Q2',   type: 'output' },
      { pin: 20, name: 'Q1',   type: 'output' },
      { pin: 21, name: 'Q0',   type: 'output' },
      { pin: 22, name: 'NC',   type: 'nc'     },
      { pin: 23, name: 'NC2',  type: 'nc'     },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','D0','D1','D2','D3','D4','D5','D6','D7','D8','LE'], outputs: ['Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7','Q8'] },
    ],
  },

  // 74993: 9 bit D-type transparent read-back latch, inverting, TRI (24-pin)
  '74993': {
    name: '74x993',
    simpleName: '9 bit Transparent Latch Read-Back Inv (TRI)',
    description: '9 bit D-type transparent read-back latch, inverting, with three-state outputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['latch', '9 bit', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x993 is a nine-bit transparent latch with inverting 3-state outputs, matching the 74992 but presenting complemented values at the outputs. The ninth bit can carry parity or a status flag. On a breadboard it is a good choice when downstream logic expects an active LOW wide word or when you need to hold a parity-protected byte and drive it in complemented form onto a shared bus. The simulator currently represents this as a generic stub.',
    pinout: [
      { pin:  1, name: 'OEn',  type: 'input'  },
      { pin:  2, name: 'D0',   type: 'input'  },
      { pin:  3, name: 'D1',   type: 'input'  },
      { pin:  4, name: 'D2',   type: 'input'  },
      { pin:  5, name: 'D3',   type: 'input'  },
      { pin:  6, name: 'D4',   type: 'input'  },
      { pin:  7, name: 'D5',   type: 'input'  },
      { pin:  8, name: 'D6',   type: 'input'  },
      { pin:  9, name: 'D7',   type: 'input'  },
      { pin: 10, name: 'D8',   type: 'input'  },
      { pin: 11, name: 'LE',   type: 'input'  },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'Q8n',  type: 'output' },
      { pin: 14, name: 'Q7n',  type: 'output' },
      { pin: 15, name: 'Q6n',  type: 'output' },
      { pin: 16, name: 'Q5n',  type: 'output' },
      { pin: 17, name: 'Q4n',  type: 'output' },
      { pin: 18, name: 'Q3n',  type: 'output' },
      { pin: 19, name: 'Q2n',  type: 'output' },
      { pin: 20, name: 'Q1n',  type: 'output' },
      { pin: 21, name: 'Q0n',  type: 'output' },
      { pin: 22, name: 'NC',   type: 'nc'     },
      { pin: 23, name: 'NC2',  type: 'nc'     },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','D0','D1','D2','D3','D4','D5','D6','D7','D8','LE'], outputs: ['Q0n','Q1n','Q2n','Q3n','Q4n','Q5n','Q6n','Q7n','Q8n'] },
    ],
  },

  // 74994: 10 bit D-type transparent read-back latch, non-inverting, TRI (24-pin)
  '74994': {
    name: '74x994',
    simpleName: '10 bit Transparent Latch Read-Back (TRI)',
    description: '10 bit D-type transparent read-back latch, non-inverting, with three-state outputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['latch', '10 bit', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x994 extends the transparent read-back latch to ten bits, enough to hold a full byte plus two extra control or parity bits in one package. Data is captured while the latch is enabled, then held and can be driven onto a bus through 3-state outputs. On a breadboard it fits naturally into designs that need a ten-bit wide holding register alongside a bus that must be shared with other drivers. The simulator currently represents this as a generic stub.',
    pinout: [
      { pin:  1, name: 'OEn',  type: 'input'  },
      { pin:  2, name: 'D0',   type: 'input'  },
      { pin:  3, name: 'D1',   type: 'input'  },
      { pin:  4, name: 'D2',   type: 'input'  },
      { pin:  5, name: 'D3',   type: 'input'  },
      { pin:  6, name: 'D4',   type: 'input'  },
      { pin:  7, name: 'D5',   type: 'input'  },
      { pin:  8, name: 'D6',   type: 'input'  },
      { pin:  9, name: 'D7',   type: 'input'  },
      { pin: 10, name: 'D8',   type: 'input'  },
      { pin: 11, name: 'D9',   type: 'input'  },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'LE',   type: 'input'  },
      { pin: 14, name: 'Q9',   type: 'output' },
      { pin: 15, name: 'Q8',   type: 'output' },
      { pin: 16, name: 'Q7',   type: 'output' },
      { pin: 17, name: 'Q6',   type: 'output' },
      { pin: 18, name: 'Q5',   type: 'output' },
      { pin: 19, name: 'Q4',   type: 'output' },
      { pin: 20, name: 'Q3',   type: 'output' },
      { pin: 21, name: 'Q2',   type: 'output' },
      { pin: 22, name: 'Q1',   type: 'output' },
      { pin: 23, name: 'Q0',   type: 'output' },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','D0','D1','D2','D3','D4','D5','D6','D7','D8','D9','LE'], outputs: ['Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7','Q8','Q9'] },
    ],
  },

  // 74995: 10 bit D-type transparent read-back latch, inverting, TRI (24-pin)
  '74995': {
    name: '74x995',
    simpleName: '10 bit Transparent Latch Read-Back Inv (TRI)',
    description: '10 bit D-type transparent read-back latch, inverting, with three-state outputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['latch', '10 bit', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x995 is the inverting complement of the 74994. It holds ten bits in a transparent latch and presents complemented values through 3-state outputs. On a breadboard this is useful when downstream logic expects active LOW bit patterns across a ten-bit word, avoiding separate inverter packages. The simulator currently represents this as a generic stub.',
    pinout: [
      { pin:  1, name: 'OEn',  type: 'input'  },
      { pin:  2, name: 'D0',   type: 'input'  },
      { pin:  3, name: 'D1',   type: 'input'  },
      { pin:  4, name: 'D2',   type: 'input'  },
      { pin:  5, name: 'D3',   type: 'input'  },
      { pin:  6, name: 'D4',   type: 'input'  },
      { pin:  7, name: 'D5',   type: 'input'  },
      { pin:  8, name: 'D6',   type: 'input'  },
      { pin:  9, name: 'D7',   type: 'input'  },
      { pin: 10, name: 'D8',   type: 'input'  },
      { pin: 11, name: 'D9',   type: 'input'  },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'LE',   type: 'input'  },
      { pin: 14, name: 'Q9n',  type: 'output' },
      { pin: 15, name: 'Q8n',  type: 'output' },
      { pin: 16, name: 'Q7n',  type: 'output' },
      { pin: 17, name: 'Q6n',  type: 'output' },
      { pin: 18, name: 'Q5n',  type: 'output' },
      { pin: 19, name: 'Q4n',  type: 'output' },
      { pin: 20, name: 'Q3n',  type: 'output' },
      { pin: 21, name: 'Q2n',  type: 'output' },
      { pin: 22, name: 'Q1n',  type: 'output' },
      { pin: 23, name: 'Q0n',  type: 'output' },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','D0','D1','D2','D3','D4','D5','D6','D7','D8','D9','LE'], outputs: ['Q0n','Q1n','Q2n','Q3n','Q4n','Q5n','Q6n','Q7n','Q8n','Q9n'] },
    ],
  },

  // 74996: 8 bit D-type edge-triggered read-back latch, TRI (24-pin)
  '74996': {
    name: '74x996',
    simpleName: '8 bit Edge-Triggered Latch Read-Back (TRI)',
    description: '8 bit D-type edge-triggered read-back latch with three-state outputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74als996.pdf',
    tags: ['latch', 'flip-flop', '8 bit', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x996 is an octal edge-triggered read-back latch with 3-state outputs. Unlike a transparent latch, it captures data only on a clock event and then holds that byte until the next clock or a clear operation. On a breadboard it is useful when you want registered byte storage that can still be disconnected from a shared bus until readout is needed.',
    guidePinDescriptions: {
      'OEn': 'Active LOW output enable. Pull LOW to let Q0-Q7 drive the bus, or HIGH to release the outputs.',
      'D0': 'Data input bit 0.',
      'D1': 'Data input bit 1.',
      'D2': 'Data input bit 2.',
      'D3': 'Data input bit 3.',
      'D4': 'Data input bit 4.',
      'D5': 'Data input bit 5.',
      'D6': 'Data input bit 6.',
      'D7': 'Data input bit 7.',
      'CLK': 'Clock input. A clock event captures the eight input bits into the register.',
      'CLRn': 'Active LOW clear. Pull LOW to reset the stored byte; tie HIGH when clear is not being used.',
      'GND': 'Ground reference for the device at pin 12.',
      'Q7': 'Registered output bit 7.',
      'Q6': 'Registered output bit 6.',
      'Q5': 'Registered output bit 5.',
      'Q4': 'Registered output bit 4.',
      'Q3': 'Registered output bit 3.',
      'Q2': 'Registered output bit 2.',
      'Q1': 'Registered output bit 1.',
      'Q0': 'Registered output bit 0.',
      'NC': 'No internal connection. Leave this pin unconnected.',
      'NC2': 'No internal connection. Leave this pin unconnected.',
      'NC3': 'No internal connection. Leave this pin unconnected.',
      'VCC': 'Positive 5 V supply at pin 24.',
    },
    guideSections: [
      {
        title: 'Edge-Triggered Read-Back Storage',
        paragraphs: [
          'Edge-triggered storage is useful in synchronous designs because the stored value changes only at a clock boundary. That makes the circuit easier to time than a transparent latch in systems where data is moving between clocked stages.',
          'The read-back feature means the register can hold a captured byte internally and then present it later when the bus is enabled.',
        ],
      },
      {
        title: 'Clear and Bus Control',
        paragraphs: [
          'The active LOW clear input gives you a way to force a known startup state, while the 3-state output enable keeps the register from loading a shared bus unless it is supposed to drive.',
        ],
        note: 'The simulator currently models this device as a generic stub rather than a full edge-triggered storage element.',
      },
    ],
    pinout: [
      { pin:  1, name: 'OEn',  type: 'input'  },
      { pin:  2, name: 'D0',   type: 'input'  },
      { pin:  3, name: 'D1',   type: 'input'  },
      { pin:  4, name: 'D2',   type: 'input'  },
      { pin:  5, name: 'D3',   type: 'input'  },
      { pin:  6, name: 'D4',   type: 'input'  },
      { pin:  7, name: 'D5',   type: 'input'  },
      { pin:  8, name: 'D6',   type: 'input'  },
      { pin:  9, name: 'D7',   type: 'input'  },
      { pin: 10, name: 'CLK',  type: 'input'  },
      { pin: 11, name: 'CLRn', type: 'input'  },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'Q7',   type: 'output' },
      { pin: 14, name: 'Q6',   type: 'output' },
      { pin: 15, name: 'Q5',   type: 'output' },
      { pin: 16, name: 'Q4',   type: 'output' },
      { pin: 17, name: 'Q3',   type: 'output' },
      { pin: 18, name: 'Q2',   type: 'output' },
      { pin: 19, name: 'Q1',   type: 'output' },
      { pin: 20, name: 'Q0',   type: 'output' },
      { pin: 21, name: 'NC',   type: 'nc'     },
      { pin: 22, name: 'NC2',  type: 'nc'     },
      { pin: 23, name: 'NC3',  type: 'nc'     },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','D0','D1','D2','D3','D4','D5','D6','D7','CLK','CLRn'], outputs: ['Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7'] },
    ],
  },

  // 74x1000: Quad 2 input NAND gate driver (14-pin)
  '74x1000': {
    name: '74x1000',
    simpleName: 'Quad 2 Input NAND Gate Driver',
    description: 'Quad 2 input NAND gate with high-drive outputs (14-pin)',
    pins: 14, vcc: 14, gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74as1000a.pdf',
    tags: ['nand', 'gate', 'quad', 'driver'],
    guideOverview: 'The 74x1000 contains four independent 2 input NAND buffer/driver stages in one package. A NAND gate outputs LOW only when both inputs are HIGH, which makes it one of the most flexible building blocks in digital logic because many other functions can be assembled from NANDs. On a breadboard it is useful when you need ordinary logic plus stronger output drive than a small-signal gate can provide.',
    guidePinDescriptions: {
      '1A': 'Input A of gate 1.',
      '1B': 'Input B of gate 1.',
      '1Y': 'Output of gate 1. It goes LOW only when both 1A and 1B are HIGH.',
      '2A': 'Input A of gate 2.',
      '2B': 'Input B of gate 2.',
      '2Y': 'Output of gate 2.',
      'GND': 'Ground reference for the device at pin 7.',
      '3Y': 'Output of gate 3.',
      '3A': 'Input A of gate 3.',
      '3B': 'Input B of gate 3.',
      '4Y': 'Output of gate 4.',
      '4A': 'Input A of gate 4.',
      '4B': 'Input B of gate 4.',
      'VCC': 'Positive 5 V supply at pin 14.',
    },
    guideSections: [
      {
        title: 'Logic Function',
        paragraphs: [
          'A 2 input NAND performs the function Y = !(A · B). Only the input combination HIGH-HIGH produces a LOW output; every other combination gives a HIGH output.',
        ],
        formulas: [
          'A=0, B=0 -> Y=1',
          'A=0, B=1 -> Y=1',
          'A=1, B=0 -> Y=1',
          'A=1, B=1 -> Y=0',
        ],
      },
      {
        title: 'Why Drivers Matter',
        paragraphs: [
          'A buffer/driver version of a logic gate is intended to source or sink more current than a minimal logic stage. That makes it a better choice when one gate output must feed several TTL inputs or a slightly heavier load.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: '1A',  type: 'input'  },
      { pin:  2, name: '1B',  type: 'input'  },
      { pin:  3, name: '1Y',  type: 'output' },
      { pin:  4, name: '2A',  type: 'input'  },
      { pin:  5, name: '2B',  type: 'input'  },
      { pin:  6, name: '2Y',  type: 'output' },
      { pin:  7, name: 'GND', type: 'power'  },
      { pin:  8, name: '3Y',  type: 'output' },
      { pin:  9, name: '3A',  type: 'input'  },
      { pin: 10, name: '3B',  type: 'input'  },
      { pin: 11, name: '4Y',  type: 'output' },
      { pin: 12, name: '4A',  type: 'input'  },
      { pin: 13, name: '4B',  type: 'input'  },
      { pin: 14, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'NAND', inputs: ['1A','1B'], output: '1Y' },
      { type: 'NAND', inputs: ['2A','2B'], output: '2Y' },
      { type: 'NAND', inputs: ['3A','3B'], output: '3Y' },
      { type: 'NAND', inputs: ['4A','4B'], output: '4Y' },
    ],
  },

  // 74x1002: Quad 2 input NOR gate driver (14-pin)
  '74x1002': {
    name: '74x1002',
    simpleName: 'Quad 2 Input NOR Gate Driver',
    description: 'Quad 2 input NOR gate with high-drive outputs (14-pin)',
    pins: 14, vcc: 14, gnd: 7,
    datasheet: '',
    tags: ['nor', 'gate', 'quad', 'driver'],
    guideOverview: 'The 74x1002 contains four independent 2 input NOR buffer/driver stages. A NOR gate outputs HIGH only when both inputs are LOW, making it the complement of OR and a useful universal building block alongside NAND gates. The driver outputs supply stronger current than a minimal logic gate, which helps when one gate must feed several TTL inputs on a breadboard.',
    pinout: [
      { pin:  1, name: '1A',  type: 'input'  },
      { pin:  2, name: '1B',  type: 'input'  },
      { pin:  3, name: '1Y',  type: 'output' },
      { pin:  4, name: '2A',  type: 'input'  },
      { pin:  5, name: '2B',  type: 'input'  },
      { pin:  6, name: '2Y',  type: 'output' },
      { pin:  7, name: 'GND', type: 'power'  },
      { pin:  8, name: '3Y',  type: 'output' },
      { pin:  9, name: '3A',  type: 'input'  },
      { pin: 10, name: '3B',  type: 'input'  },
      { pin: 11, name: '4Y',  type: 'output' },
      { pin: 12, name: '4A',  type: 'input'  },
      { pin: 13, name: '4B',  type: 'input'  },
      { pin: 14, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'NOR', inputs: ['1A','1B'], output: '1Y' },
      { type: 'NOR', inputs: ['2A','2B'], output: '2Y' },
      { type: 'NOR', inputs: ['3A','3B'], output: '3Y' },
      { type: 'NOR', inputs: ['4A','4B'], output: '4Y' },
    ],
  },

  // 74x1003: Quad 2 input NAND gate, open-collector driver (14-pin)
  '74x1003': {
    name: '74x1003',
    simpleName: 'Quad 2 Input NAND Gate OC Driver',
    description: 'Quad 2 input NAND gate with open-collector high-drive outputs (14-pin)',
    pins: 14, vcc: 14, gnd: 7,
    openCollector: true,
    datasheet: '',
    tags: ['nand', 'gate', 'quad', 'driver', 'open collector'],
    guideOverview: 'The 74x1003 provides four 2 input NAND stages with open-collector outputs. Internally each gate computes the NAND function, but the output transistor can only pull the line LOW. An external pull up resistor is required to create a HIGH level. On a breadboard this makes it possible to wire several open-collector NAND outputs together on one shared line for wired AND behavior, or to drive loads at a voltage different from the supply rail.',
    pinout: [
      { pin:  1, name: '1A',  type: 'input'  },
      { pin:  2, name: '1B',  type: 'input'  },
      { pin:  3, name: '1Y',  type: 'output' },
      { pin:  4, name: '2A',  type: 'input'  },
      { pin:  5, name: '2B',  type: 'input'  },
      { pin:  6, name: '2Y',  type: 'output' },
      { pin:  7, name: 'GND', type: 'power'  },
      { pin:  8, name: '3Y',  type: 'output' },
      { pin:  9, name: '3A',  type: 'input'  },
      { pin: 10, name: '3B',  type: 'input'  },
      { pin: 11, name: '4Y',  type: 'output' },
      { pin: 12, name: '4A',  type: 'input'  },
      { pin: 13, name: '4B',  type: 'input'  },
      { pin: 14, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'NAND', inputs: ['1A','1B'], output: '1Y' },
      { type: 'NAND', inputs: ['2A','2B'], output: '2Y' },
      { type: 'NAND', inputs: ['3A','3B'], output: '3Y' },
      { type: 'NAND', inputs: ['4A','4B'], output: '4Y' },
    ],
  },

  // 74x1004: Hex inverting buffer driver (14-pin)
  '74x1004': {
    name: '74x1004',
    simpleName: 'Hex Inverting Buffer Driver',
    description: 'Hex inverting buffer with high-drive outputs (14-pin)',
    pins: 14, vcc: 14, gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74als1004.pdf',
    tags: ['inverter', 'hex', 'driver'],
    guideOverview: 'The 74x1004 is a hex inverting buffer/driver. Each of the six channels performs a simple logical inversion, but the driver family is intended to supply stronger output current than a tiny logic gate. On a breadboard it is useful for polarity cleanup, fanout, and turning one control signal into several stronger inverted copies.',
    guidePinDescriptions: {
      '1A': 'Input of inverter 1.',
      '1Y': 'Output of inverter 1. It is the logical inverse of 1A.',
      '2A': 'Input of inverter 2.',
      '2Y': 'Output of inverter 2.',
      '3A': 'Input of inverter 3.',
      '3Y': 'Output of inverter 3.',
      'GND': 'Ground reference for the device at pin 7.',
      '4Y': 'Output of inverter 4.',
      '4A': 'Input of inverter 4.',
      '5Y': 'Output of inverter 5.',
      '5A': 'Input of inverter 5.',
      '6Y': 'Output of inverter 6.',
      '6A': 'Input of inverter 6.',
      'VCC': 'Positive 5 V supply at pin 14.',
    },
    guideSections: [
      {
        title: 'Inversion',
        paragraphs: [
          'An inverter implements Y = !A. A HIGH input becomes a LOW output, and a LOW input becomes a HIGH output.',
        ],
        formulas: [
          'A=0 -> Y=1',
          'A=1 -> Y=0',
        ],
      },
      {
        title: 'Common Uses',
        list: [
          'Generate active LOW control signals from active HIGH logic.',
          'Strengthen a weak logic source before driving multiple loads.',
          'Add a deliberate inversion stage in timing or control paths.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: '1A',  type: 'input'  },
      { pin:  2, name: '1Y',  type: 'output' },
      { pin:  3, name: '2A',  type: 'input'  },
      { pin:  4, name: '2Y',  type: 'output' },
      { pin:  5, name: '3A',  type: 'input'  },
      { pin:  6, name: '3Y',  type: 'output' },
      { pin:  7, name: 'GND', type: 'power'  },
      { pin:  8, name: '4Y',  type: 'output' },
      { pin:  9, name: '4A',  type: 'input'  },
      { pin: 10, name: '5Y',  type: 'output' },
      { pin: 11, name: '5A',  type: 'input'  },
      { pin: 12, name: '6Y',  type: 'output' },
      { pin: 13, name: '6A',  type: 'input'  },
      { pin: 14, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'NOT', inputs: ['1A'], output: '1Y' },
      { type: 'NOT', inputs: ['2A'], output: '2Y' },
      { type: 'NOT', inputs: ['3A'], output: '3Y' },
      { type: 'NOT', inputs: ['4A'], output: '4Y' },
      { type: 'NOT', inputs: ['5A'], output: '5Y' },
      { type: 'NOT', inputs: ['6A'], output: '6Y' },
    ],
  },

  // 74x1005: Hex inverting buffer, open-collector driver (14-pin)
  '74x1005': {
    name: '74x1005',
    simpleName: 'Hex Inverting Buffer OC Driver',
    description: 'Hex inverting buffer with open-collector high-drive outputs (14-pin)',
    pins: 14, vcc: 14, gnd: 7,
    openCollector: true,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74als1005.pdf',
    tags: ['inverter', 'hex', 'driver', 'open collector'],
    guideOverview: 'The 74x1005 is a hex inverting driver with open-collector outputs. Internally each channel still behaves like an inverter, but the output transistor can only pull the line LOW, so an external pull up is needed to create a HIGH level. On a breadboard this makes the part useful for wired-logic connections, level-shifting tricks, and driving loads that should share a pull up rail.',
    guidePinDescriptions: {
      '1A': 'Input of inverter 1.',
      '1Y': 'Open-collector output of inverter 1. It pulls LOW when active and otherwise releases the line, so use a pull up resistor.',
      '2A': 'Input of inverter 2.',
      '2Y': 'Open-collector output of inverter 2.',
      '3A': 'Input of inverter 3.',
      '3Y': 'Open-collector output of inverter 3.',
      'GND': 'Ground reference for the device at pin 7.',
      '4Y': 'Open-collector output of inverter 4.',
      '4A': 'Input of inverter 4.',
      '5Y': 'Open-collector output of inverter 5.',
      '5A': 'Input of inverter 5.',
      '6Y': 'Open-collector output of inverter 6.',
      '6A': 'Input of inverter 6.',
      'VCC': 'Positive 5 V supply at pin 14.',
    },
    guideSections: [
      {
        title: 'Open Collector Behavior',
        paragraphs: [
          'An open-collector output can actively pull the line LOW but cannot drive it HIGH by itself. Instead, a resistor or another pull up network brings the line HIGH when the transistor is off.',
        ],
        list: [
          'Add a pull up resistor whenever you use the output.',
          'Multiple open-collector outputs can share one line for wired-logic behavior.',
          'Use it when the load voltage or pull up arrangement needs flexibility.',
        ],
      },
      {
        title: 'Logic Function',
        paragraphs: [
          'Each channel still performs inversion: a HIGH input turns on the pull down transistor, while a LOW input releases the output node.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: '1A',  type: 'input'  },
      { pin:  2, name: '1Y',  type: 'output' },
      { pin:  3, name: '2A',  type: 'input'  },
      { pin:  4, name: '2Y',  type: 'output' },
      { pin:  5, name: '3A',  type: 'input'  },
      { pin:  6, name: '3Y',  type: 'output' },
      { pin:  7, name: 'GND', type: 'power'  },
      { pin:  8, name: '4Y',  type: 'output' },
      { pin:  9, name: '4A',  type: 'input'  },
      { pin: 10, name: '5Y',  type: 'output' },
      { pin: 11, name: '5A',  type: 'input'  },
      { pin: 12, name: '6Y',  type: 'output' },
      { pin: 13, name: '6A',  type: 'input'  },
      { pin: 14, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'NOT', inputs: ['1A'], output: '1Y' },
      { type: 'NOT', inputs: ['2A'], output: '2Y' },
      { type: 'NOT', inputs: ['3A'], output: '3Y' },
      { type: 'NOT', inputs: ['4A'], output: '4Y' },
      { type: 'NOT', inputs: ['5A'], output: '5Y' },
      { type: 'NOT', inputs: ['6A'], output: '6Y' },
    ],
  },

  // 74x1008: Quad 2 input AND gate driver (14-pin)
  '74x1008': {
    name: '74x1008',
    simpleName: 'Quad 2 Input AND Gate Driver',
    description: 'Quad 2 input AND gate with high-drive outputs (14-pin)',
    pins: 14, vcc: 14, gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74as1008a.pdf',
    tags: ['and', 'gate', 'quad', 'driver'],
    guideOverview: 'The 74x1008 provides four independent 2 input AND buffer/driver stages. An AND gate outputs HIGH only when both inputs are HIGH, which makes it a convenient way to combine two enable conditions or require two simultaneous logic truths before driving a load. The driver family gives the outputs enough strength to be useful in real TTL fanout situations on a breadboard.',
    guidePinDescriptions: {
      '1A': 'Input A of gate 1.',
      '1B': 'Input B of gate 1.',
      '1Y': 'Output of gate 1. It is HIGH only when both 1A and 1B are HIGH.',
      '2A': 'Input A of gate 2.',
      '2B': 'Input B of gate 2.',
      '2Y': 'Output of gate 2.',
      'GND': 'Ground reference for the device at pin 7.',
      '3Y': 'Output of gate 3.',
      '3A': 'Input A of gate 3.',
      '3B': 'Input B of gate 3.',
      '4Y': 'Output of gate 4.',
      '4A': 'Input A of gate 4.',
      '4B': 'Input B of gate 4.',
      'VCC': 'Positive 5 V supply at pin 14.',
    },
    guideSections: [
      {
        title: 'Logic Function',
        paragraphs: [
          'A 2 input AND performs Y = A · B. The output goes HIGH only when both inputs are HIGH.',
        ],
        formulas: [
          'A=0, B=0 -> Y=0',
          'A=0, B=1 -> Y=0',
          'A=1, B=0 -> Y=0',
          'A=1, B=1 -> Y=1',
        ],
      },
      {
        title: 'Common Uses',
        list: [
          'Gate one control signal with another enable signal.',
          'Require two independent conditions before turning something on.',
          'Drive a slightly heavier TTL load than a minimal logic gate can handle.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: '1A',  type: 'input'  },
      { pin:  2, name: '1B',  type: 'input'  },
      { pin:  3, name: '1Y',  type: 'output' },
      { pin:  4, name: '2A',  type: 'input'  },
      { pin:  5, name: '2B',  type: 'input'  },
      { pin:  6, name: '2Y',  type: 'output' },
      { pin:  7, name: 'GND', type: 'power'  },
      { pin:  8, name: '3Y',  type: 'output' },
      { pin:  9, name: '3A',  type: 'input'  },
      { pin: 10, name: '3B',  type: 'input'  },
      { pin: 11, name: '4Y',  type: 'output' },
      { pin: 12, name: '4A',  type: 'input'  },
      { pin: 13, name: '4B',  type: 'input'  },
      { pin: 14, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'AND', inputs: ['1A','1B'], output: '1Y' },
      { type: 'AND', inputs: ['2A','2B'], output: '2Y' },
      { type: 'AND', inputs: ['3A','3B'], output: '3Y' },
      { type: 'AND', inputs: ['4A','4B'], output: '4Y' },
    ],
  },

  // 74x1010: Triple 3-input NAND gate driver (14-pin)
  '74x1010': {
    name: '74x1010',
    simpleName: 'Triple 3-Input NAND Gate Driver',
    description: 'Triple 3-input NAND gate with high-drive outputs (14-pin)',
    pins: 14, vcc: 14, gnd: 7,
    datasheet: '',
    tags: ['nand', 'gate', 'triple', 'driver'],
    guideOverview: 'The 74x1010 contains three independent 3 input NAND buffer/driver stages. A three-input NAND outputs LOW only when all three inputs are simultaneously HIGH, making it useful for gate functions that need a third control or enable signal before an action is blocked. The driver outputs supply stronger current than a minimal logic gate, which helps when one gate must feed multiple TTL loads on a breadboard.',
    pinout: [
      { pin:  1, name: '1A',  type: 'input'  },
      { pin:  2, name: '1B',  type: 'input'  },
      { pin:  3, name: '1C',  type: 'input'  },
      { pin:  4, name: '1Y',  type: 'output' },
      { pin:  5, name: '2A',  type: 'input'  },
      { pin:  6, name: '2B',  type: 'input'  },
      { pin:  7, name: 'GND', type: 'power'  },
      { pin:  8, name: '2C',  type: 'input'  },
      { pin:  9, name: '2Y',  type: 'output' },
      { pin: 10, name: '3A',  type: 'input'  },
      { pin: 11, name: '3B',  type: 'input'  },
      { pin: 12, name: '3C',  type: 'input'  },
      { pin: 13, name: '3Y',  type: 'output' },
      { pin: 14, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'NAND', inputs: ['1A','1B','1C'], output: '1Y' },
      { type: 'NAND', inputs: ['2A','2B','2C'], output: '2Y' },
      { type: 'NAND', inputs: ['3A','3B','3C'], output: '3Y' },
    ],
  },
};