// Chip definitions block 54
// Chips: 74x2825, 74x2827, 74x2828, 74x2833, 74x2841, 74x2843, 74x2845, 74x2853,
//        74x2861, 74x2862, 74x2863, 74x2864, 74x2952, 74x2953, 74x2961, 74x2962

export const CHIPS_BLOCK_54 = {

  // 74x2825: 8 bit D type flip flop with clear and clock enable, TRI+25Ω (24-pin)
  '74x2825': {
    name: '74x2825',
    simpleName: '8 bit D-Flip Flop with Clear and Clock Enable (25Ω)',
    description: '8-bit D flip-flop, async clear+clock enable, 3-state 25Ω series (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['flip flop', '8 bit', 'D type', 'clear', 'clock-enable', 'tri state', 'stub'],
    pinout: [
      { pin:  1, name: 'OEn',  type: 'input'  },
      { pin:  2, name: 'CLK',  type: 'input'  },
      { pin:  3, name: 'CLRn', type: 'input'  },
      { pin:  4, name: 'CEn',  type: 'input'  },
      { pin:  5, name: 'D0',   type: 'input'  },
      { pin:  6, name: 'D1',   type: 'input'  },
      { pin:  7, name: 'D2',   type: 'input'  },
      { pin:  8, name: 'D3',   type: 'input'  },
      { pin:  9, name: 'D4',   type: 'input'  },
      { pin: 10, name: 'D5',   type: 'input'  },
      { pin: 11, name: 'D6',   type: 'input'  },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'D7',   type: 'input'  },
      { pin: 14, name: 'Q7',   type: 'output' },
      { pin: 15, name: 'Q6',   type: 'output' },
      { pin: 16, name: 'Q5',   type: 'output' },
      { pin: 17, name: 'Q4',   type: 'output' },
      { pin: 18, name: 'Q3',   type: 'output' },
      { pin: 19, name: 'Q2',   type: 'output' },
      { pin: 20, name: 'Q1',   type: 'output' },
      { pin: 21, name: 'Q0',   type: 'output' },
      { pin: 22, name: 'NC',   type: 'nc'     },
      { pin: 23, name: 'NC2',  type: 'nc'     },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','CLK','CLRn','CEn','D0','D1','D2','D3','D4','D5','D6','D7'], outputs: [] },
    ],
  },

  // 74x2827: 10 bit buffer, non inverting, TRI+25Ω (24-pin)
  '74x2827': {
    name: '74x2827',
    simpleName: '10 bit Non Inverting Buffer (25Ω)',
    description: '10 bit non inverting buffer, TRI STATE with 25 Ω series resistor (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['buffer', '10 bit', 'non inverting', 'tri state', 'stub'],
    pinout: [
      { pin:  1, name: 'OE1n', type: 'input'  },
      { pin:  2, name: 'A0',   type: 'input'  },
      { pin:  3, name: 'A1',   type: 'input'  },
      { pin:  4, name: 'A2',   type: 'input'  },
      { pin:  5, name: 'A3',   type: 'input'  },
      { pin:  6, name: 'A4',   type: 'input'  },
      { pin:  7, name: 'A5',   type: 'input'  },
      { pin:  8, name: 'A6',   type: 'input'  },
      { pin:  9, name: 'A7',   type: 'input'  },
      { pin: 10, name: 'A8',   type: 'input'  },
      { pin: 11, name: 'A9',   type: 'input'  },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'OE2n', type: 'input'  },
      { pin: 14, name: 'Y9',   type: 'output' },
      { pin: 15, name: 'Y8',   type: 'output' },
      { pin: 16, name: 'Y7',   type: 'output' },
      { pin: 17, name: 'Y6',   type: 'output' },
      { pin: 18, name: 'Y5',   type: 'output' },
      { pin: 19, name: 'Y4',   type: 'output' },
      { pin: 20, name: 'Y3',   type: 'output' },
      { pin: 21, name: 'Y2',   type: 'output' },
      { pin: 22, name: 'Y1',   type: 'output' },
      { pin: 23, name: 'Y0',   type: 'output' },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OE1n','OE2n','A0','A1','A2','A3','A4','A5','A6','A7','A8','A9'], outputs: [] },
    ],
  },

  // 74x2828: 10 bit buffer, inverting, TRI+25Ω (24-pin)
  '74x2828': {
    name: '74x2828',
    simpleName: '10 bit Inverting Buffer (25Ω)',
    description: '10 bit inverting buffer, TRI STATE with 25 Ω series resistor (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['buffer', '10 bit', 'inverting', 'tri state', 'stub'],
    pinout: [
      { pin:  1, name: 'OE1n', type: 'input'  },
      { pin:  2, name: 'A0',   type: 'input'  },
      { pin:  3, name: 'A1',   type: 'input'  },
      { pin:  4, name: 'A2',   type: 'input'  },
      { pin:  5, name: 'A3',   type: 'input'  },
      { pin:  6, name: 'A4',   type: 'input'  },
      { pin:  7, name: 'A5',   type: 'input'  },
      { pin:  8, name: 'A6',   type: 'input'  },
      { pin:  9, name: 'A7',   type: 'input'  },
      { pin: 10, name: 'A8',   type: 'input'  },
      { pin: 11, name: 'A9',   type: 'input'  },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'OE2n', type: 'input'  },
      { pin: 14, name: 'Y9',   type: 'output' },
      { pin: 15, name: 'Y8',   type: 'output' },
      { pin: 16, name: 'Y7',   type: 'output' },
      { pin: 17, name: 'Y6',   type: 'output' },
      { pin: 18, name: 'Y5',   type: 'output' },
      { pin: 19, name: 'Y4',   type: 'output' },
      { pin: 20, name: 'Y3',   type: 'output' },
      { pin: 21, name: 'Y2',   type: 'output' },
      { pin: 22, name: 'Y1',   type: 'output' },
      { pin: 23, name: 'Y0',   type: 'output' },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OE1n','OE2n','A0','A1','A2','A3','A4','A5','A6','A7','A8','A9'], outputs: [] },
    ],
  },

  // 74x2833: 8 bit bus transceiver with parity error flip flop, TRI+25Ω (24-pin)
  '74x2833': {
    name: '74x2833',
    simpleName: '8 bit Bus Transceiver with Parity Error Flip Flop (25Ω)',
    description: '8-bit bus transceiver, parity error flip-flop, 3-state 25Ω series (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['transceiver', '8 bit', 'parity', 'bidir', 'stub'],
    pinout: [
      { pin:  1, name: 'OEABn', type: 'input'  },
      { pin:  2, name: 'OEBAn', type: 'input'  },
      { pin:  3, name: 'A1',    type: 'bidir'  },
      { pin:  4, name: 'A2',    type: 'bidir'  },
      { pin:  5, name: 'A3',    type: 'bidir'  },
      { pin:  6, name: 'A4',    type: 'bidir'  },
      { pin:  7, name: 'A5',    type: 'bidir'  },
      { pin:  8, name: 'A6',    type: 'bidir'  },
      { pin:  9, name: 'A7',    type: 'bidir'  },
      { pin: 10, name: 'A8',    type: 'bidir'  },
      { pin: 11, name: 'CLK',   type: 'input'  },
      { pin: 12, name: 'GND',   type: 'power'  },
      { pin: 13, name: 'PEn',   type: 'output' },
      { pin: 14, name: 'B8',    type: 'bidir'  },
      { pin: 15, name: 'B7',    type: 'bidir'  },
      { pin: 16, name: 'B6',    type: 'bidir'  },
      { pin: 17, name: 'B5',    type: 'bidir'  },
      { pin: 18, name: 'B4',    type: 'bidir'  },
      { pin: 19, name: 'B3',    type: 'bidir'  },
      { pin: 20, name: 'B2',    type: 'bidir'  },
      { pin: 21, name: 'B1',    type: 'bidir'  },
      { pin: 22, name: 'PEVEN', type: 'input'  },
      { pin: 23, name: 'NC',    type: 'nc'     },
      { pin: 24, name: 'VCC',   type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEABn','OEBAn','CLK','PEVEN'], outputs: [] },
    ],
  },

  // 74x2841: 10 bit transparent latch, TRI+25Ω (24-pin)
  '74x2841': {
    name: '74x2841',
    simpleName: '10 bit Transparent Latch (25Ω)',
    description: '10 bit transparent latch, TRI STATE with 25 Ω series resistor (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['latch', '10 bit', 'transparent', 'tri state', 'stub'],
    pinout: [
      { pin:  1, name: 'OEn',  type: 'input'  },
      { pin:  2, name: 'LE',   type: 'input'  },
      { pin:  3, name: 'D0',   type: 'input'  },
      { pin:  4, name: 'D1',   type: 'input'  },
      { pin:  5, name: 'D2',   type: 'input'  },
      { pin:  6, name: 'D3',   type: 'input'  },
      { pin:  7, name: 'D4',   type: 'input'  },
      { pin:  8, name: 'D5',   type: 'input'  },
      { pin:  9, name: 'D6',   type: 'input'  },
      { pin: 10, name: 'D7',   type: 'input'  },
      { pin: 11, name: 'D8',   type: 'input'  },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'D9',   type: 'input'  },
      { pin: 14, name: 'Q9',   type: 'output' },
      { pin: 15, name: 'Q8',   type: 'output' },
      { pin: 16, name: 'Q7',   type: 'output' },
      { pin: 17, name: 'Q6',   type: 'output' },
      { pin: 18, name: 'Q5',   type: 'output' },
      { pin: 19, name: 'Q4',   type: 'output' },
      { pin: 20, name: 'Q3',   type: 'output' },
      { pin: 21, name: 'Q2',   type: 'output' },
      { pin: 22, name: 'Q1',   type: 'output' },
      { pin: 23, name: 'Q0',   type: 'output' },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','LE','D0','D1','D2','D3','D4','D5','D6','D7','D8','D9'], outputs: [] },
    ],
  },

  // 74x2843: 9 bit transparent latch with asynchronous reset, TRI+25Ω (24-pin)
  '74x2843': {
    name: '74x2843',
    simpleName: '9 bit Transparent Latch with Async Reset (25Ω)',
    description: '9-bit transparent latch, async reset, 3-state 25Ω series (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['latch', '9 bit', 'transparent', 'reset', 'tri state', 'stub'],
    pinout: [
      { pin:  1, name: 'OEn',  type: 'input'  },
      { pin:  2, name: 'LE',   type: 'input'  },
      { pin:  3, name: 'CLRn', type: 'input'  },
      { pin:  4, name: 'D0',   type: 'input'  },
      { pin:  5, name: 'D1',   type: 'input'  },
      { pin:  6, name: 'D2',   type: 'input'  },
      { pin:  7, name: 'D3',   type: 'input'  },
      { pin:  8, name: 'D4',   type: 'input'  },
      { pin:  9, name: 'D5',   type: 'input'  },
      { pin: 10, name: 'D6',   type: 'input'  },
      { pin: 11, name: 'D7',   type: 'input'  },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'D8',   type: 'input'  },
      { pin: 14, name: 'Q8',   type: 'output' },
      { pin: 15, name: 'Q7',   type: 'output' },
      { pin: 16, name: 'Q6',   type: 'output' },
      { pin: 17, name: 'Q5',   type: 'output' },
      { pin: 18, name: 'Q4',   type: 'output' },
      { pin: 19, name: 'Q3',   type: 'output' },
      { pin: 20, name: 'Q2',   type: 'output' },
      { pin: 21, name: 'Q1',   type: 'output' },
      { pin: 22, name: 'Q0',   type: 'output' },
      { pin: 23, name: 'NC',   type: 'nc'     },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','LE','CLRn','D0','D1','D2','D3','D4','D5','D6','D7','D8'], outputs: [] },
    ],
  },

  // 74x2845: 8 bit transparent latch with async reset and multiple OE, TRI+25Ω (24-pin)
  '74x2845': {
    name: '74x2845',
    simpleName: '8 bit Transparent Latch with Async Reset and Multi-OE (25Ω)',
    description: '8-bit transparent latch, async reset, multi OE, 3-state 25Ω (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['latch', '8 bit', 'transparent', 'reset', 'tri state', 'stub'],
    pinout: [
      { pin:  1, name: 'OE1n', type: 'input'  },
      { pin:  2, name: 'OE2n', type: 'input'  },
      { pin:  3, name: 'LE',   type: 'input'  },
      { pin:  4, name: 'CLRn', type: 'input'  },
      { pin:  5, name: 'D0',   type: 'input'  },
      { pin:  6, name: 'D1',   type: 'input'  },
      { pin:  7, name: 'D2',   type: 'input'  },
      { pin:  8, name: 'D3',   type: 'input'  },
      { pin:  9, name: 'D4',   type: 'input'  },
      { pin: 10, name: 'D5',   type: 'input'  },
      { pin: 11, name: 'D6',   type: 'input'  },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'D7',   type: 'input'  },
      { pin: 14, name: 'Q7',   type: 'output' },
      { pin: 15, name: 'Q6',   type: 'output' },
      { pin: 16, name: 'Q5',   type: 'output' },
      { pin: 17, name: 'Q4',   type: 'output' },
      { pin: 18, name: 'Q3',   type: 'output' },
      { pin: 19, name: 'Q2',   type: 'output' },
      { pin: 20, name: 'Q1',   type: 'output' },
      { pin: 21, name: 'Q0',   type: 'output' },
      { pin: 22, name: 'NC',   type: 'nc'     },
      { pin: 23, name: 'NC2',  type: 'nc'     },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OE1n','OE2n','LE','CLRn','D0','D1','D2','D3','D4','D5','D6','D7'], outputs: [] },
    ],
  },

  // 74x2853: 8 bit bus transceiver with parity error latch, TRI+25Ω (24-pin)
  '74x2853': {
    name: '74x2853',
    simpleName: '8 bit Bus Transceiver with Parity Error Latch (25Ω)',
    description: '8-bit bus transceiver, parity error latch, 3-state 25Ω series (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['transceiver', '8 bit', 'parity', 'bidir', 'stub'],
    pinout: [
      { pin:  1, name: 'OEABn', type: 'input'  },
      { pin:  2, name: 'OEBAn', type: 'input'  },
      { pin:  3, name: 'A1',    type: 'bidir'  },
      { pin:  4, name: 'A2',    type: 'bidir'  },
      { pin:  5, name: 'A3',    type: 'bidir'  },
      { pin:  6, name: 'A4',    type: 'bidir'  },
      { pin:  7, name: 'A5',    type: 'bidir'  },
      { pin:  8, name: 'A6',    type: 'bidir'  },
      { pin:  9, name: 'A7',    type: 'bidir'  },
      { pin: 10, name: 'A8',    type: 'bidir'  },
      { pin: 11, name: 'LE',    type: 'input'  },
      { pin: 12, name: 'GND',   type: 'power'  },
      { pin: 13, name: 'PEn',   type: 'output' },
      { pin: 14, name: 'B8',    type: 'bidir'  },
      { pin: 15, name: 'B7',    type: 'bidir'  },
      { pin: 16, name: 'B6',    type: 'bidir'  },
      { pin: 17, name: 'B5',    type: 'bidir'  },
      { pin: 18, name: 'B4',    type: 'bidir'  },
      { pin: 19, name: 'B3',    type: 'bidir'  },
      { pin: 20, name: 'B2',    type: 'bidir'  },
      { pin: 21, name: 'B1',    type: 'bidir'  },
      { pin: 22, name: 'PEVEN', type: 'input'  },
      { pin: 23, name: 'NC',    type: 'nc'     },
      { pin: 24, name: 'VCC',   type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEABn','OEBAn','LE','PEVEN'], outputs: [] },
    ],
  },

  // 74x2861: 10 bit non inverting bus transceiver, TRI+25Ω (24-pin)
  '74x2861': {
    name: '74x2861',
    simpleName: '10 bit Non Inverting Bus Transceiver (25Ω)',
    description: '10-bit non-inverting bus transceiver, 3-state 25Ω series (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['transceiver', '10 bit', 'non inverting', 'bidir', 'stub'],
    pinout: [
      { pin:  1, name: 'OEABn', type: 'input'  },
      { pin:  2, name: 'OEBAn', type: 'input'  },
      { pin:  3, name: 'A1',    type: 'bidir'  },
      { pin:  4, name: 'A2',    type: 'bidir'  },
      { pin:  5, name: 'A3',    type: 'bidir'  },
      { pin:  6, name: 'A4',    type: 'bidir'  },
      { pin:  7, name: 'A5',    type: 'bidir'  },
      { pin:  8, name: 'A6',    type: 'bidir'  },
      { pin:  9, name: 'A7',    type: 'bidir'  },
      { pin: 10, name: 'A8',    type: 'bidir'  },
      { pin: 11, name: 'A9',    type: 'bidir'  },
      { pin: 12, name: 'GND',   type: 'power'  },
      { pin: 13, name: 'A10',   type: 'bidir'  },
      { pin: 14, name: 'B10',   type: 'bidir'  },
      { pin: 15, name: 'B9',    type: 'bidir'  },
      { pin: 16, name: 'B8',    type: 'bidir'  },
      { pin: 17, name: 'B7',    type: 'bidir'  },
      { pin: 18, name: 'B6',    type: 'bidir'  },
      { pin: 19, name: 'B5',    type: 'bidir'  },
      { pin: 20, name: 'B4',    type: 'bidir'  },
      { pin: 21, name: 'B3',    type: 'bidir'  },
      { pin: 22, name: 'B2',    type: 'bidir'  },
      { pin: 23, name: 'B1',    type: 'bidir'  },
      { pin: 24, name: 'VCC',   type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEABn','OEBAn'], outputs: [] },
    ],
  },

  // 74x2862: 10 bit inverting bus transceiver, TRI+25Ω (24-pin)
  '74x2862': {
    name: '74x2862',
    simpleName: '10 bit Inverting Bus Transceiver (25Ω)',
    description: '10-bit inverting bus transceiver, 3-state 25Ω series (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['transceiver', '10 bit', 'inverting', 'bidir', 'stub'],
    pinout: [
      { pin:  1, name: 'OEABn', type: 'input'  },
      { pin:  2, name: 'OEBAn', type: 'input'  },
      { pin:  3, name: 'A1',    type: 'bidir'  },
      { pin:  4, name: 'A2',    type: 'bidir'  },
      { pin:  5, name: 'A3',    type: 'bidir'  },
      { pin:  6, name: 'A4',    type: 'bidir'  },
      { pin:  7, name: 'A5',    type: 'bidir'  },
      { pin:  8, name: 'A6',    type: 'bidir'  },
      { pin:  9, name: 'A7',    type: 'bidir'  },
      { pin: 10, name: 'A8',    type: 'bidir'  },
      { pin: 11, name: 'A9',    type: 'bidir'  },
      { pin: 12, name: 'GND',   type: 'power'  },
      { pin: 13, name: 'A10',   type: 'bidir'  },
      { pin: 14, name: 'B10',   type: 'bidir'  },
      { pin: 15, name: 'B9',    type: 'bidir'  },
      { pin: 16, name: 'B8',    type: 'bidir'  },
      { pin: 17, name: 'B7',    type: 'bidir'  },
      { pin: 18, name: 'B6',    type: 'bidir'  },
      { pin: 19, name: 'B5',    type: 'bidir'  },
      { pin: 20, name: 'B4',    type: 'bidir'  },
      { pin: 21, name: 'B3',    type: 'bidir'  },
      { pin: 22, name: 'B2',    type: 'bidir'  },
      { pin: 23, name: 'B1',    type: 'bidir'  },
      { pin: 24, name: 'VCC',   type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEABn','OEBAn'], outputs: [] },
    ],
  },

  // 74x2863: 9 bit non inverting bus transceiver with dual output enable, TRI+25Ω (24-pin)
  '74x2863': {
    name: '74x2863',
    simpleName: '9 bit Non Inverting Bus Transceiver with Dual OE (25Ω)',
    description: '9-bit non-inverting bus transceiver, dual OE, 3-state 25Ω series (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['transceiver', '9 bit', 'non inverting', 'bidir', 'stub'],
    pinout: [
      { pin:  1, name: 'OEABn', type: 'input'  },
      { pin:  2, name: 'OEBAn', type: 'input'  },
      { pin:  3, name: 'A1',    type: 'bidir'  },
      { pin:  4, name: 'A2',    type: 'bidir'  },
      { pin:  5, name: 'A3',    type: 'bidir'  },
      { pin:  6, name: 'A4',    type: 'bidir'  },
      { pin:  7, name: 'A5',    type: 'bidir'  },
      { pin:  8, name: 'A6',    type: 'bidir'  },
      { pin:  9, name: 'A7',    type: 'bidir'  },
      { pin: 10, name: 'A8',    type: 'bidir'  },
      { pin: 11, name: 'A9',    type: 'bidir'  },
      { pin: 12, name: 'GND',   type: 'power'  },
      { pin: 13, name: 'NC',    type: 'nc'     },
      { pin: 14, name: 'B9',    type: 'bidir'  },
      { pin: 15, name: 'B8',    type: 'bidir'  },
      { pin: 16, name: 'B7',    type: 'bidir'  },
      { pin: 17, name: 'B6',    type: 'bidir'  },
      { pin: 18, name: 'B5',    type: 'bidir'  },
      { pin: 19, name: 'B4',    type: 'bidir'  },
      { pin: 20, name: 'B3',    type: 'bidir'  },
      { pin: 21, name: 'B2',    type: 'bidir'  },
      { pin: 22, name: 'B1',    type: 'bidir'  },
      { pin: 23, name: 'NC2',   type: 'nc'     },
      { pin: 24, name: 'VCC',   type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEABn','OEBAn'], outputs: [] },
    ],
  },

  // 74x2864: 9 bit inverting bus transceiver with dual output enable, TRI+25Ω (24-pin)
  '74x2864': {
    name: '74x2864',
    simpleName: '9 bit Inverting Bus Transceiver with Dual OE (25Ω)',
    description: '9-bit inverting bus transceiver, dual OE, 3-state 25Ω series (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['transceiver', '9 bit', 'inverting', 'bidir', 'stub'],
    pinout: [
      { pin:  1, name: 'OEABn', type: 'input'  },
      { pin:  2, name: 'OEBAn', type: 'input'  },
      { pin:  3, name: 'A1',    type: 'bidir'  },
      { pin:  4, name: 'A2',    type: 'bidir'  },
      { pin:  5, name: 'A3',    type: 'bidir'  },
      { pin:  6, name: 'A4',    type: 'bidir'  },
      { pin:  7, name: 'A5',    type: 'bidir'  },
      { pin:  8, name: 'A6',    type: 'bidir'  },
      { pin:  9, name: 'A7',    type: 'bidir'  },
      { pin: 10, name: 'A8',    type: 'bidir'  },
      { pin: 11, name: 'A9',    type: 'bidir'  },
      { pin: 12, name: 'GND',   type: 'power'  },
      { pin: 13, name: 'NC',    type: 'nc'     },
      { pin: 14, name: 'B9',    type: 'bidir'  },
      { pin: 15, name: 'B8',    type: 'bidir'  },
      { pin: 16, name: 'B7',    type: 'bidir'  },
      { pin: 17, name: 'B6',    type: 'bidir'  },
      { pin: 18, name: 'B5',    type: 'bidir'  },
      { pin: 19, name: 'B4',    type: 'bidir'  },
      { pin: 20, name: 'B3',    type: 'bidir'  },
      { pin: 21, name: 'B2',    type: 'bidir'  },
      { pin: 22, name: 'B1',    type: 'bidir'  },
      { pin: 23, name: 'NC2',   type: 'nc'     },
      { pin: 24, name: 'VCC',   type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEABn','OEBAn'], outputs: [] },
    ],
  },

  // 74x2952: Octal bus transceiver and register, non inverting, TRI (24-pin)
  '74x2952': {
    name: '74x2952',
    simpleName: 'Octal Bus Transceiver and Register Non Inverting',
    description: 'Octal bus transceiver and register, non inverting, TRI STATE (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74lvc2952a.pdf',
    tags: ['transceiver', 'octal', 'registered', 'non inverting', 'bidir'],
    guideOverview: 'The 74x2952 combines two common bus functions in one package: bidirectional transceiving and clocked data registration. It can move data between two 8 bit buses under direction control, while the clocked internal staging makes it useful when bus transfers need to line up cleanly with a system clock rather than pass straight through combinationally. This is the kind of device used in higher speed bus interfaces where timing control matters as much as simple buffering.',
    guidePinDescriptions: {
      'OEABn': 'Enable control (active LOW) for the A-to B path. Use it to decide when that direction is allowed to drive the bus.',
      'CLK': 'Clock input for the internal register stage. Data transfer timing is referenced to this clock.',
      'A1': 'Bit 1 of the A-side bus. It participates in the registered transceiver path.',
      'A2': 'Bit 2 of the A-side bus.',
      'A3': 'Bit 3 of the A-side bus.',
      'A4': 'Bit 4 of the A-side bus.',
      'A5': 'Bit 5 of the A-side bus.',
      'A6': 'Bit 6 of the A-side bus.',
      'A7': 'Bit 7 of the A-side bus.',
      'A8': 'Bit 8 of the A-side bus.',
      'OEBAn': 'Enable control (active LOW) for the B-to A path.',
      'GND': 'Ground reference for the device.',
      'DIR': 'Direction control input. It selects which side of the bus is treated as the source in the current cycle.',
      'B8': 'Bit 8 of the B-side bus. It is the B-side mate for A8.',
      'B7': 'Bit 7 of the B-side bus.',
      'B6': 'Bit 6 of the B-side bus.',
      'B5': 'Bit 5 of the B-side bus.',
      'B4': 'Bit 4 of the B-side bus.',
      'B3': 'Bit 3 of the B-side bus.',
      'B2': 'Bit 2 of the B-side bus.',
      'B1': 'Bit 1 of the B-side bus.',
      'NC': 'No internal connection. Leave this pin unconnected.',
      'NC2': 'No internal connection. Leave this pin unconnected.',
      'VCC': 'Positive supply for the transceiver and register circuitry.',
    },
    guideSections: [
      {
        title: 'Why Combine a Register and a Transceiver',
        paragraphs: [
          'A plain bus transceiver simply passes data across when enabled. A registered transceiver adds a clocked storage stage so data can be captured and then presented in a more controlled, synchronous way.',
          'That is helpful on faster buses because it gives the designer a clean timing boundary. Instead of letting propagation delays vary with whatever is upstream, the device can align transfers to the system clock.',
        ],
      },
      {
        title: 'Direction and Enable Control',
        paragraphs: [
          'DIR chooses the active flow of information, while the two active LOW enable controls decide which path is allowed to drive. Together they prevent contention and let one package support complex bus ownership schemes.',
        ],
        note: 'Modeled in the simulator as an 8-bit registered transceiver: rising CLK edges latch the source-side data, OEABn/OEBAn gate the destination drivers, and DIR selects the active direction. The simulator collapses the real chip\'s separate CLKAB/CLKBA inputs into a single CLK.',
      },
    ],
    pinout: [
      { pin:  1, name: 'OEABn', type: 'input'  },
      { pin:  2, name: 'CLK',   type: 'input'  },
      { pin:  3, name: 'A1',    type: 'bidir'  },
      { pin:  4, name: 'A2',    type: 'bidir'  },
      { pin:  5, name: 'A3',    type: 'bidir'  },
      { pin:  6, name: 'A4',    type: 'bidir'  },
      { pin:  7, name: 'A5',    type: 'bidir'  },
      { pin:  8, name: 'A6',    type: 'bidir'  },
      { pin:  9, name: 'A7',    type: 'bidir'  },
      { pin: 10, name: 'A8',    type: 'bidir'  },
      { pin: 11, name: 'OEBAn', type: 'input'  },
      { pin: 12, name: 'GND',   type: 'power'  },
      { pin: 13, name: 'DIR',   type: 'input'  },
      { pin: 14, name: 'B8',    type: 'bidir'  },
      { pin: 15, name: 'B7',    type: 'bidir'  },
      { pin: 16, name: 'B6',    type: 'bidir'  },
      { pin: 17, name: 'B5',    type: 'bidir'  },
      { pin: 18, name: 'B4',    type: 'bidir'  },
      { pin: 19, name: 'B3',    type: 'bidir'  },
      { pin: 20, name: 'B2',    type: 'bidir'  },
      { pin: 21, name: 'B1',    type: 'bidir'  },
      { pin: 22, name: 'NC',    type: 'nc'     },
      { pin: 23, name: 'NC2',   type: 'nc'     },
      { pin: 24, name: 'VCC',   type: 'power'  },
    ],
    gates: [
      { type: 'TRANSCEIVER_OCTAL_REG',
        inputs:  ['OEABn','OEBAn','NC','NC2','CLK','DIR',
                  'A1','A2','A3','A4','A5','A6','A7','A8',
                  'B1','B2','B3','B4','B5','B6','B7','B8'],
        outputs: ['A1','A2','A3','A4','A5','A6','A7','A8',
                  'B1','B2','B3','B4','B5','B6','B7','B8'] },
    ],
    sequential: true,
  },

  // 74x2953: Octal bus transceiver and register, inverting, TRI (24-pin)
  '74x2953': {
    name: '74x2953',
    simpleName: 'Octal Bus Transceiver and Register Inverting',
    description: 'Octal bus transceiver and register, inverting, TRI STATE (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['transceiver', 'octal', 'registered', 'inverting', 'bidir'],
    pinout: [
      { pin:  1, name: 'OEABn', type: 'input'  },
      { pin:  2, name: 'CLK',   type: 'input'  },
      { pin:  3, name: 'A1',    type: 'bidir'  },
      { pin:  4, name: 'A2',    type: 'bidir'  },
      { pin:  5, name: 'A3',    type: 'bidir'  },
      { pin:  6, name: 'A4',    type: 'bidir'  },
      { pin:  7, name: 'A5',    type: 'bidir'  },
      { pin:  8, name: 'A6',    type: 'bidir'  },
      { pin:  9, name: 'A7',    type: 'bidir'  },
      { pin: 10, name: 'A8',    type: 'bidir'  },
      { pin: 11, name: 'OEBAn', type: 'input'  },
      { pin: 12, name: 'GND',   type: 'power'  },
      { pin: 13, name: 'DIR',   type: 'input'  },
      { pin: 14, name: 'B8',    type: 'bidir'  },
      { pin: 15, name: 'B7',    type: 'bidir'  },
      { pin: 16, name: 'B6',    type: 'bidir'  },
      { pin: 17, name: 'B5',    type: 'bidir'  },
      { pin: 18, name: 'B4',    type: 'bidir'  },
      { pin: 19, name: 'B3',    type: 'bidir'  },
      { pin: 20, name: 'B2',    type: 'bidir'  },
      { pin: 21, name: 'B1',    type: 'bidir'  },
      { pin: 22, name: 'NC',    type: 'nc'     },
      { pin: 23, name: 'NC2',   type: 'nc'     },
      { pin: 24, name: 'VCC',   type: 'power'  },
    ],
    gates: [
      { type: 'TRANSCEIVER_OCTAL_REG_INV',
        inputs:  ['OEABn','OEBAn','NC','NC2','CLK','DIR',
                  'A1','A2','A3','A4','A5','A6','A7','A8',
                  'B1','B2','B3','B4','B5','B6','B7','B8'],
        outputs: ['A1','A2','A3','A4','A5','A6','A7','A8',
                  'B1','B2','B3','B4','B5','B6','B7','B8'] },
    ],
    sequential: true,
  },

  // 74x2961: 4 bit EDAC bus buffer, inverting (Am2961 equivalent), TRI (24-pin)
  '74x2961': {
    name: '74x2961',
    simpleName: '4 bit EDAC Bus Buffer, Inverting (Am2961 Equivalent)',
    description: '4 bit EDAC bus buffer, inverting, equivalent to Am2961, TRI STATE (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['buffer', 'EDAC', '4 bit', 'inverting', 'tri state', 'stub'],
    pinout: [
      { pin:  1, name: 'OEn',  type: 'input'  },
      { pin:  2, name: 'A0',   type: 'input'  },
      { pin:  3, name: 'A1',   type: 'input'  },
      { pin:  4, name: 'A2',   type: 'input'  },
      { pin:  5, name: 'A3',   type: 'input'  },
      { pin:  6, name: 'P0',   type: 'input'  },
      { pin:  7, name: 'P1',   type: 'input'  },
      { pin:  8, name: 'P2',   type: 'input'  },
      { pin:  9, name: 'P3',   type: 'input'  },
      { pin: 10, name: 'P4',   type: 'input'  },
      { pin: 11, name: 'P5',   type: 'input'  },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'P6',   type: 'input'  },
      { pin: 14, name: 'YP6',  type: 'output' },
      { pin: 15, name: 'YP5',  type: 'output' },
      { pin: 16, name: 'YP4',  type: 'output' },
      { pin: 17, name: 'YP3',  type: 'output' },
      { pin: 18, name: 'YP2',  type: 'output' },
      { pin: 19, name: 'YP1',  type: 'output' },
      { pin: 20, name: 'YP0',  type: 'output' },
      { pin: 21, name: 'YA3',  type: 'output' },
      { pin: 22, name: 'YA2',  type: 'output' },
      { pin: 23, name: 'YA1',  type: 'output' },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','A0','A1','A2','A3','P0','P1','P2','P3','P4','P5','P6'], outputs: [] },
    ],
  },

  // 74x2962: 4 bit EDAC bus buffer, non inverting (Am2962 equivalent), TRI (24-pin)
  '74x2962': {
    name: '74x2962',
    simpleName: '4 bit EDAC Bus Buffer, Non Inverting (Am2962 Equivalent)',
    description: '4-bit EDAC bus buffer, non-inverting, Am2962 equivalent, 3-state (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['buffer', 'EDAC', '4 bit', 'non inverting', 'tri state', 'stub'],
    pinout: [
      { pin:  1, name: 'OEn',  type: 'input'  },
      { pin:  2, name: 'A0',   type: 'input'  },
      { pin:  3, name: 'A1',   type: 'input'  },
      { pin:  4, name: 'A2',   type: 'input'  },
      { pin:  5, name: 'A3',   type: 'input'  },
      { pin:  6, name: 'P0',   type: 'input'  },
      { pin:  7, name: 'P1',   type: 'input'  },
      { pin:  8, name: 'P2',   type: 'input'  },
      { pin:  9, name: 'P3',   type: 'input'  },
      { pin: 10, name: 'P4',   type: 'input'  },
      { pin: 11, name: 'P5',   type: 'input'  },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'P6',   type: 'input'  },
      { pin: 14, name: 'YP6',  type: 'output' },
      { pin: 15, name: 'YP5',  type: 'output' },
      { pin: 16, name: 'YP4',  type: 'output' },
      { pin: 17, name: 'YP3',  type: 'output' },
      { pin: 18, name: 'YP2',  type: 'output' },
      { pin: 19, name: 'YP1',  type: 'output' },
      { pin: 20, name: 'YP0',  type: 'output' },
      { pin: 21, name: 'YA3',  type: 'output' },
      { pin: 22, name: 'YA2',  type: 'output' },
      { pin: 23, name: 'YA1',  type: 'output' },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','A0','A1','A2','A3','P0','P1','P2','P3','P4','P5','P6'], outputs: [] },
    ],
  },
};
