// Chip definitions block 53
// Chips: 74x2543, 74x2544, 74x2573, 74x2574, 74x2620, 74x2623, 74x2640, 74x2643,
//        74x2645, 74x2646, 74x2648, 74x2651, 74x2652, 74x2821, 74x2823

export const CHIPS_BLOCK_53 = {

  // 74x2543: 8 bit latched transceiver, non inverting, TRI+25Ω (24-pin)
  '74x2543': {
    name: '74x2543',
    simpleName: '8 bit Latched Transceiver Non Inverting (25Ω)',
    description: '8 bit latched transceiver, non inverting, 3-state, 25 Ω series R (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['transceiver', 'latch', '8 bit', 'tri state', 'bidir', 'stub'],
    pinout: [
      { pin:  1, name: 'LEAB', type: 'input'  },
      { pin:  2, name: 'OEAN', type: 'input'  },
      { pin:  3, name: 'A1',   type: 'bidir'  },
      { pin:  4, name: 'A2',   type: 'bidir'  },
      { pin:  5, name: 'A3',   type: 'bidir'  },
      { pin:  6, name: 'A4',   type: 'bidir'  },
      { pin:  7, name: 'A5',   type: 'bidir'  },
      { pin:  8, name: 'A6',   type: 'bidir'  },
      { pin:  9, name: 'A7',   type: 'bidir'  },
      { pin: 10, name: 'A8',   type: 'bidir'  },
      { pin: 11, name: 'OEBN', type: 'input'  },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'LEBA', type: 'input'  },
      { pin: 14, name: 'B8',   type: 'bidir'  },
      { pin: 15, name: 'B7',   type: 'bidir'  },
      { pin: 16, name: 'B6',   type: 'bidir'  },
      { pin: 17, name: 'B5',   type: 'bidir'  },
      { pin: 18, name: 'B4',   type: 'bidir'  },
      { pin: 19, name: 'B3',   type: 'bidir'  },
      { pin: 20, name: 'B2',   type: 'bidir'  },
      { pin: 21, name: 'B1',   type: 'bidir'  },
      { pin: 22, name: 'NC',   type: 'nc'     },
      { pin: 23, name: 'NC2',  type: 'nc'     },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['LEAB','OEAN','OEBN','LEBA'], outputs: [] },
    ],
  },

  // 74x2544: 8 bit latched transceiver, inverting, TRI+25Ω (24-pin)
  '74x2544': {
    name: '74x2544',
    simpleName: '8 bit Latched Transceiver Inverting (25Ω)',
    description: '8 bit latched transceiver, inverting, 3-state, 25 Ω series R (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['transceiver', 'latch', '8 bit', 'inverting', 'tri state', 'bidir', 'stub'],
    pinout: [
      { pin:  1, name: 'LEAB', type: 'input'  },
      { pin:  2, name: 'OEAN', type: 'input'  },
      { pin:  3, name: 'A1',   type: 'bidir'  },
      { pin:  4, name: 'A2',   type: 'bidir'  },
      { pin:  5, name: 'A3',   type: 'bidir'  },
      { pin:  6, name: 'A4',   type: 'bidir'  },
      { pin:  7, name: 'A5',   type: 'bidir'  },
      { pin:  8, name: 'A6',   type: 'bidir'  },
      { pin:  9, name: 'A7',   type: 'bidir'  },
      { pin: 10, name: 'A8',   type: 'bidir'  },
      { pin: 11, name: 'OEBN', type: 'input'  },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'LEBA', type: 'input'  },
      { pin: 14, name: 'B8',   type: 'bidir'  },
      { pin: 15, name: 'B7',   type: 'bidir'  },
      { pin: 16, name: 'B6',   type: 'bidir'  },
      { pin: 17, name: 'B5',   type: 'bidir'  },
      { pin: 18, name: 'B4',   type: 'bidir'  },
      { pin: 19, name: 'B3',   type: 'bidir'  },
      { pin: 20, name: 'B2',   type: 'bidir'  },
      { pin: 21, name: 'B1',   type: 'bidir'  },
      { pin: 22, name: 'NC',   type: 'nc'     },
      { pin: 23, name: 'NC2',  type: 'nc'     },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['LEAB','OEAN','OEBN','LEBA'], outputs: [] },
    ],
  },

  // 74x2573: 8 bit transparent latch, TRI+25Ω (20-pin)
  '74x2573': {
    name: '74x2573',
    simpleName: '8 bit Transparent Latch (25Ω, Bus Oriented)',
    description: '8 bit transparent latch, TRI STATE with 25 Ω series resistor (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: '',
    tags: ['latch', '8 bit', 'transparent', 'tri state', 'stub'],
    pinout: [
      { pin:  1, name: 'OEn',  type: 'input'  },
      { pin:  2, name: 'D1',   type: 'input'  },
      { pin:  3, name: 'D2',   type: 'input'  },
      { pin:  4, name: 'D3',   type: 'input'  },
      { pin:  5, name: 'D4',   type: 'input'  },
      { pin:  6, name: 'D5',   type: 'input'  },
      { pin:  7, name: 'D6',   type: 'input'  },
      { pin:  8, name: 'D7',   type: 'input'  },
      { pin:  9, name: 'D8',   type: 'input'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'LE',   type: 'input'  },
      { pin: 12, name: 'Q8',   type: 'output' },
      { pin: 13, name: 'Q7',   type: 'output' },
      { pin: 14, name: 'Q6',   type: 'output' },
      { pin: 15, name: 'Q5',   type: 'output' },
      { pin: 16, name: 'Q4',   type: 'output' },
      { pin: 17, name: 'Q3',   type: 'output' },
      { pin: 18, name: 'Q2',   type: 'output' },
      { pin: 19, name: 'Q1',   type: 'output' },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','LE','D1','D2','D3','D4','D5','D6','D7','D8'], outputs: [] },
    ],
  },

  // 74x2574: Octal D type flip flop, shared clock, TRI+25Ω (20-pin, bus oriented pinout)
  '74x2574': {
    name: '74x2574',
    simpleName: 'Octal D Type Flip Flop Shared CLK (25Ω, Bus Oriented)',
    description: 'Octal D flip-flop, shared clock, 3-state, 25 Ω series R (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: '',
    tags: ['flip flop', 'octal', 'D type', 'tri state', 'stub'],
    pinout: [
      { pin:  1, name: 'OEn',  type: 'input'  },
      { pin:  2, name: 'D1',   type: 'input'  },
      { pin:  3, name: 'D2',   type: 'input'  },
      { pin:  4, name: 'D3',   type: 'input'  },
      { pin:  5, name: 'D4',   type: 'input'  },
      { pin:  6, name: 'D5',   type: 'input'  },
      { pin:  7, name: 'D6',   type: 'input'  },
      { pin:  8, name: 'D7',   type: 'input'  },
      { pin:  9, name: 'D8',   type: 'input'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'CLK',  type: 'input'  },
      { pin: 12, name: 'Q8',   type: 'output' },
      { pin: 13, name: 'Q7',   type: 'output' },
      { pin: 14, name: 'Q6',   type: 'output' },
      { pin: 15, name: 'Q5',   type: 'output' },
      { pin: 16, name: 'Q4',   type: 'output' },
      { pin: 17, name: 'Q3',   type: 'output' },
      { pin: 18, name: 'Q2',   type: 'output' },
      { pin: 19, name: 'Q1',   type: 'output' },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','CLK','D1','D2','D3','D4','D5','D6','D7','D8'], outputs: [] },
    ],
  },

  // 74x2620: Octal bus transceiver / MOS driver, inverting, TRI+25Ω (20-pin)
  '74x2620': {
    name: '74x2620',
    simpleName: 'Octal Bus Transceiver / MOS Driver Inverting (25Ω)',
    description: 'Octal bus transceiver/MOS driver, inverting, 3-state, 25 Ω R (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: '',
    tags: ['transceiver', 'octal', 'MOS', 'inverting', 'bidir', 'stub'],
    pinout: [
      { pin:  1, name: 'GABn', type: 'input'  },
      { pin:  2, name: 'GBAn', type: 'input'  },
      { pin:  3, name: 'A1',   type: 'bidir'  },
      { pin:  4, name: 'A2',   type: 'bidir'  },
      { pin:  5, name: 'A3',   type: 'bidir'  },
      { pin:  6, name: 'A4',   type: 'bidir'  },
      { pin:  7, name: 'A5',   type: 'bidir'  },
      { pin:  8, name: 'A6',   type: 'bidir'  },
      { pin:  9, name: 'A7',   type: 'bidir'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'A8',   type: 'bidir'  },
      { pin: 12, name: 'B8',   type: 'bidir'  },
      { pin: 13, name: 'B7',   type: 'bidir'  },
      { pin: 14, name: 'B6',   type: 'bidir'  },
      { pin: 15, name: 'B5',   type: 'bidir'  },
      { pin: 16, name: 'B4',   type: 'bidir'  },
      { pin: 17, name: 'B3',   type: 'bidir'  },
      { pin: 18, name: 'B2',   type: 'bidir'  },
      { pin: 19, name: 'B1',   type: 'bidir'  },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['GABn','GBAn'], outputs: [] },
    ],
  },

  // 74x2623: Octal bus transceiver / MOS driver, non inverting, TRI+25Ω (20-pin)
  '74x2623': {
    name: '74x2623',
    simpleName: 'Octal Bus Transceiver / MOS Driver Non Inverting (25Ω)',
    description: 'Octal bus transceiver/MOS driver, non inverting, 3-state, 25 Ω R (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: '',
    tags: ['transceiver', 'octal', 'MOS', 'non inverting', 'bidir', 'stub'],
    pinout: [
      { pin:  1, name: 'GABn', type: 'input'  },
      { pin:  2, name: 'GBAn', type: 'input'  },
      { pin:  3, name: 'A1',   type: 'bidir'  },
      { pin:  4, name: 'A2',   type: 'bidir'  },
      { pin:  5, name: 'A3',   type: 'bidir'  },
      { pin:  6, name: 'A4',   type: 'bidir'  },
      { pin:  7, name: 'A5',   type: 'bidir'  },
      { pin:  8, name: 'A6',   type: 'bidir'  },
      { pin:  9, name: 'A7',   type: 'bidir'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'A8',   type: 'bidir'  },
      { pin: 12, name: 'B8',   type: 'bidir'  },
      { pin: 13, name: 'B7',   type: 'bidir'  },
      { pin: 14, name: 'B6',   type: 'bidir'  },
      { pin: 15, name: 'B5',   type: 'bidir'  },
      { pin: 16, name: 'B4',   type: 'bidir'  },
      { pin: 17, name: 'B3',   type: 'bidir'  },
      { pin: 18, name: 'B2',   type: 'bidir'  },
      { pin: 19, name: 'B1',   type: 'bidir'  },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['GABn','GBAn'], outputs: [] },
    ],
  },

  // 74x2640: Octal bus transceiver / MOS driver, inverting, TRI+25Ω (20-pin, alt OE control)
  '74x2640': {
    name: '74x2640',
    simpleName: 'Octal Bus Transceiver / MOS Driver Inverting (25Ω, Alt)',
    description: 'Octal bus transceiver/MOS driver, inverting, 3-state, 25 Ω R (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: '',
    tags: ['transceiver', 'octal', 'MOS', 'inverting', 'bidir', 'stub'],
    pinout: [
      { pin:  1, name: 'DIR',  type: 'input'  },
      { pin:  2, name: 'OEn',  type: 'input'  },
      { pin:  3, name: 'A1',   type: 'bidir'  },
      { pin:  4, name: 'A2',   type: 'bidir'  },
      { pin:  5, name: 'A3',   type: 'bidir'  },
      { pin:  6, name: 'A4',   type: 'bidir'  },
      { pin:  7, name: 'A5',   type: 'bidir'  },
      { pin:  8, name: 'A6',   type: 'bidir'  },
      { pin:  9, name: 'A7',   type: 'bidir'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'A8',   type: 'bidir'  },
      { pin: 12, name: 'B8',   type: 'bidir'  },
      { pin: 13, name: 'B7',   type: 'bidir'  },
      { pin: 14, name: 'B6',   type: 'bidir'  },
      { pin: 15, name: 'B5',   type: 'bidir'  },
      { pin: 16, name: 'B4',   type: 'bidir'  },
      { pin: 17, name: 'B3',   type: 'bidir'  },
      { pin: 18, name: 'B2',   type: 'bidir'  },
      { pin: 19, name: 'B1',   type: 'bidir'  },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['DIR','OEn'], outputs: [] },
    ],
  },

  // 74x2643: Octal bus transceiver, mix inv/non inv outputs, TRI+25Ω (20-pin)
  '74x2643': {
    name: '74x2643',
    simpleName: 'Octal Bus Transceiver Mix Inv/Non Inv (25Ω)',
    description: 'Octal bus transceiver, mix inv/non inv outputs, 3-state, 25 Ω R (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: '',
    tags: ['transceiver', 'octal', 'bidir', 'stub'],
    pinout: [
      { pin:  1, name: 'GABn', type: 'input'  },
      { pin:  2, name: 'GBAn', type: 'input'  },
      { pin:  3, name: 'A1',   type: 'bidir'  },
      { pin:  4, name: 'A2',   type: 'bidir'  },
      { pin:  5, name: 'A3',   type: 'bidir'  },
      { pin:  6, name: 'A4',   type: 'bidir'  },
      { pin:  7, name: 'A5',   type: 'bidir'  },
      { pin:  8, name: 'A6',   type: 'bidir'  },
      { pin:  9, name: 'A7',   type: 'bidir'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'A8',   type: 'bidir'  },
      { pin: 12, name: 'B8',   type: 'bidir'  },
      { pin: 13, name: 'B7',   type: 'bidir'  },
      { pin: 14, name: 'B6',   type: 'bidir'  },
      { pin: 15, name: 'B5',   type: 'bidir'  },
      { pin: 16, name: 'B4',   type: 'bidir'  },
      { pin: 17, name: 'B3',   type: 'bidir'  },
      { pin: 18, name: 'B2',   type: 'bidir'  },
      { pin: 19, name: 'B1',   type: 'bidir'  },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['GABn','GBAn'], outputs: [] },
    ],
  },

  // 74x2645: Octal bus transceiver / MOS driver, non inverting, TRI+25Ω (20-pin)
  '74x2645': {
    name: '74x2645',
    simpleName: 'Octal Bus Transceiver / MOS Driver Non Inverting (25Ω, Alt)',
    description: 'Octal bus transceiver/MOS driver, non inverting, 3-state, 25 Ω R (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: '',
    tags: ['transceiver', 'octal', 'MOS', 'non inverting', 'bidir', 'stub'],
    pinout: [
      { pin:  1, name: 'DIR',  type: 'input'  },
      { pin:  2, name: 'OEn',  type: 'input'  },
      { pin:  3, name: 'A1',   type: 'bidir'  },
      { pin:  4, name: 'A2',   type: 'bidir'  },
      { pin:  5, name: 'A3',   type: 'bidir'  },
      { pin:  6, name: 'A4',   type: 'bidir'  },
      { pin:  7, name: 'A5',   type: 'bidir'  },
      { pin:  8, name: 'A6',   type: 'bidir'  },
      { pin:  9, name: 'A7',   type: 'bidir'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'A8',   type: 'bidir'  },
      { pin: 12, name: 'B8',   type: 'bidir'  },
      { pin: 13, name: 'B7',   type: 'bidir'  },
      { pin: 14, name: 'B6',   type: 'bidir'  },
      { pin: 15, name: 'B5',   type: 'bidir'  },
      { pin: 16, name: 'B4',   type: 'bidir'  },
      { pin: 17, name: 'B3',   type: 'bidir'  },
      { pin: 18, name: 'B2',   type: 'bidir'  },
      { pin: 19, name: 'B1',   type: 'bidir'  },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['DIR','OEn'], outputs: [] },
    ],
  },

  // 74x2646: Octal registered transceiver, non inverting, TRI+25Ω (24-pin)
  '74x2646': {
    name: '74x2646',
    simpleName: 'Octal Registered Transceiver Non Inverting (25Ω)',
    description: 'Octal registered transceiver, non inverting, 3-state, 25 Ω R (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['transceiver', 'octal', 'registered', 'bidir', 'stub'],
    pinout: [
      { pin:  1, name: 'CLKAB', type: 'input'  },
      { pin:  2, name: 'OEAN',  type: 'input'  },
      { pin:  3, name: 'A1',    type: 'bidir'  },
      { pin:  4, name: 'A2',    type: 'bidir'  },
      { pin:  5, name: 'A3',    type: 'bidir'  },
      { pin:  6, name: 'A4',    type: 'bidir'  },
      { pin:  7, name: 'A5',    type: 'bidir'  },
      { pin:  8, name: 'A6',    type: 'bidir'  },
      { pin:  9, name: 'A7',    type: 'bidir'  },
      { pin: 10, name: 'A8',    type: 'bidir'  },
      { pin: 11, name: 'OEBN',  type: 'input'  },
      { pin: 12, name: 'GND',   type: 'power'  },
      { pin: 13, name: 'CLKBA', type: 'input'  },
      { pin: 14, name: 'B8',    type: 'bidir'  },
      { pin: 15, name: 'B7',    type: 'bidir'  },
      { pin: 16, name: 'B6',    type: 'bidir'  },
      { pin: 17, name: 'B5',    type: 'bidir'  },
      { pin: 18, name: 'B4',    type: 'bidir'  },
      { pin: 19, name: 'B3',    type: 'bidir'  },
      { pin: 20, name: 'B2',    type: 'bidir'  },
      { pin: 21, name: 'B1',    type: 'bidir'  },
      { pin: 22, name: 'NC',    type: 'nc'     },
      { pin: 23, name: 'NC2',   type: 'nc'     },
      { pin: 24, name: 'VCC',   type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['CLKAB','OEAN','OEBN','CLKBA'], outputs: [] },
    ],
  },

  // 74x2648: Octal registered transceiver, inverting, TRI+25Ω (24-pin)
  '74x2648': {
    name: '74x2648',
    simpleName: 'Octal Registered Transceiver Inverting (25Ω)',
    description: 'Octal registered transceiver, inverting, 3-state, 25 Ω R (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['transceiver', 'octal', 'registered', 'inverting', 'bidir', 'stub'],
    pinout: [
      { pin:  1, name: 'CLKAB', type: 'input'  },
      { pin:  2, name: 'OEAN',  type: 'input'  },
      { pin:  3, name: 'A1',    type: 'bidir'  },
      { pin:  4, name: 'A2',    type: 'bidir'  },
      { pin:  5, name: 'A3',    type: 'bidir'  },
      { pin:  6, name: 'A4',    type: 'bidir'  },
      { pin:  7, name: 'A5',    type: 'bidir'  },
      { pin:  8, name: 'A6',    type: 'bidir'  },
      { pin:  9, name: 'A7',    type: 'bidir'  },
      { pin: 10, name: 'A8',    type: 'bidir'  },
      { pin: 11, name: 'OEBN',  type: 'input'  },
      { pin: 12, name: 'GND',   type: 'power'  },
      { pin: 13, name: 'CLKBA', type: 'input'  },
      { pin: 14, name: 'B8',    type: 'bidir'  },
      { pin: 15, name: 'B7',    type: 'bidir'  },
      { pin: 16, name: 'B6',    type: 'bidir'  },
      { pin: 17, name: 'B5',    type: 'bidir'  },
      { pin: 18, name: 'B4',    type: 'bidir'  },
      { pin: 19, name: 'B3',    type: 'bidir'  },
      { pin: 20, name: 'B2',    type: 'bidir'  },
      { pin: 21, name: 'B1',    type: 'bidir'  },
      { pin: 22, name: 'NC',    type: 'nc'     },
      { pin: 23, name: 'NC2',   type: 'nc'     },
      { pin: 24, name: 'VCC',   type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['CLKAB','OEAN','OEBN','CLKBA'], outputs: [] },
    ],
  },

  // 74x2651: Octal registered transceiver, inverting, TRI+25Ω (24-pin, alt pinout)
  '74x2651': {
    name: '74x2651',
    simpleName: 'Octal Registered Transceiver Inverting (25Ω, Alt)',
    description: 'Octal registered transceiver, inverting, 3-state, 25 Ω R (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['transceiver', 'octal', 'registered', 'inverting', 'bidir', 'stub'],
    pinout: [
      { pin:  1, name: 'CLKAB', type: 'input'  },
      { pin:  2, name: 'OEAN',  type: 'input'  },
      { pin:  3, name: 'A1',    type: 'bidir'  },
      { pin:  4, name: 'A2',    type: 'bidir'  },
      { pin:  5, name: 'A3',    type: 'bidir'  },
      { pin:  6, name: 'A4',    type: 'bidir'  },
      { pin:  7, name: 'A5',    type: 'bidir'  },
      { pin:  8, name: 'A6',    type: 'bidir'  },
      { pin:  9, name: 'A7',    type: 'bidir'  },
      { pin: 10, name: 'A8',    type: 'bidir'  },
      { pin: 11, name: 'OEBN',  type: 'input'  },
      { pin: 12, name: 'GND',   type: 'power'  },
      { pin: 13, name: 'CLKBA', type: 'input'  },
      { pin: 14, name: 'B8',    type: 'bidir'  },
      { pin: 15, name: 'B7',    type: 'bidir'  },
      { pin: 16, name: 'B6',    type: 'bidir'  },
      { pin: 17, name: 'B5',    type: 'bidir'  },
      { pin: 18, name: 'B4',    type: 'bidir'  },
      { pin: 19, name: 'B3',    type: 'bidir'  },
      { pin: 20, name: 'B2',    type: 'bidir'  },
      { pin: 21, name: 'B1',    type: 'bidir'  },
      { pin: 22, name: 'NC',    type: 'nc'     },
      { pin: 23, name: 'NC2',   type: 'nc'     },
      { pin: 24, name: 'VCC',   type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['CLKAB','OEAN','OEBN','CLKBA'], outputs: [] },
    ],
  },

  // 74x2652: Octal registered transceiver, non inverting, TRI+25Ω (24-pin, alt pinout)
  '74x2652': {
    name: '74x2652',
    simpleName: 'Octal Registered Transceiver Non Inverting (25Ω, Alt)',
    description: 'Octal registered transceiver, non inverting, 3-state, 25 Ω R (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['transceiver', 'octal', 'registered', 'non inverting', 'bidir', 'stub'],
    pinout: [
      { pin:  1, name: 'CLKAB', type: 'input'  },
      { pin:  2, name: 'OEAN',  type: 'input'  },
      { pin:  3, name: 'A1',    type: 'bidir'  },
      { pin:  4, name: 'A2',    type: 'bidir'  },
      { pin:  5, name: 'A3',    type: 'bidir'  },
      { pin:  6, name: 'A4',    type: 'bidir'  },
      { pin:  7, name: 'A5',    type: 'bidir'  },
      { pin:  8, name: 'A6',    type: 'bidir'  },
      { pin:  9, name: 'A7',    type: 'bidir'  },
      { pin: 10, name: 'A8',    type: 'bidir'  },
      { pin: 11, name: 'OEBN',  type: 'input'  },
      { pin: 12, name: 'GND',   type: 'power'  },
      { pin: 13, name: 'CLKBA', type: 'input'  },
      { pin: 14, name: 'B8',    type: 'bidir'  },
      { pin: 15, name: 'B7',    type: 'bidir'  },
      { pin: 16, name: 'B6',    type: 'bidir'  },
      { pin: 17, name: 'B5',    type: 'bidir'  },
      { pin: 18, name: 'B4',    type: 'bidir'  },
      { pin: 19, name: 'B3',    type: 'bidir'  },
      { pin: 20, name: 'B2',    type: 'bidir'  },
      { pin: 21, name: 'B1',    type: 'bidir'  },
      { pin: 22, name: 'NC',    type: 'nc'     },
      { pin: 23, name: 'NC2',   type: 'nc'     },
      { pin: 24, name: 'VCC',   type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['CLKAB','OEAN','OEBN','CLKBA'], outputs: [] },
    ],
  },

  // 74x2821: 10 bit D type flip flop, TRI+25Ω (24-pin)
  '74x2821': {
    name: '74x2821',
    simpleName: '10 bit D Type Flip Flop (25Ω)',
    description: '10 bit D type flip flop, TRI STATE with 25 Ω series resistor (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['flip flop', '10 bit', 'D type', 'tri state', 'stub'],
    pinout: [
      { pin:  1, name: 'OEn',  type: 'input'  },
      { pin:  2, name: 'CLK',  type: 'input'  },
      { pin:  3, name: 'D0',   type: 'input'  },
      { pin:  4, name: 'D1',   type: 'input'  },
      { pin:  5, name: 'D2',   type: 'input'  },
      { pin:  6, name: 'D3',   type: 'input'  },
      { pin:  7, name: 'D4',   type: 'input'  },
      { pin:  8, name: 'D5',   type: 'input'  },
      { pin:  9, name: 'D6',   type: 'input'  },
      { pin: 10, name: 'D7',   type: 'input'  },
      { pin: 11, name: 'D8',   type: 'input'  },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'D9',   type: 'input'  },
      { pin: 14, name: 'Q9',   type: 'output' },
      { pin: 15, name: 'Q8',   type: 'output' },
      { pin: 16, name: 'Q7',   type: 'output' },
      { pin: 17, name: 'Q6',   type: 'output' },
      { pin: 18, name: 'Q5',   type: 'output' },
      { pin: 19, name: 'Q4',   type: 'output' },
      { pin: 20, name: 'Q3',   type: 'output' },
      { pin: 21, name: 'Q2',   type: 'output' },
      { pin: 22, name: 'Q1',   type: 'output' },
      { pin: 23, name: 'Q0',   type: 'output' },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','CLK','D0','D1','D2','D3','D4','D5','D6','D7','D8','D9'], outputs: [] },
    ],
  },

  // 74x2823: 9 bit D type flip flop with clear, TRI+25Ω (24-pin)
  '74x2823': {
    name: '74x2823',
    simpleName: '9 bit D Type Flip Flop with Clear (25Ω)',
    description: '9 bit D flip-flop with clear, 3-state, 25 Ω series R (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['flip flop', '9 bit', 'D type', 'clear', 'tri state', 'stub'],
    pinout: [
      { pin:  1, name: 'OEn',  type: 'input'  },
      { pin:  2, name: 'CLK',  type: 'input'  },
      { pin:  3, name: 'CLRn', type: 'input'  },
      { pin:  4, name: 'D0',   type: 'input'  },
      { pin:  5, name: 'D1',   type: 'input'  },
      { pin:  6, name: 'D2',   type: 'input'  },
      { pin:  7, name: 'D3',   type: 'input'  },
      { pin:  8, name: 'D4',   type: 'input'  },
      { pin:  9, name: 'D5',   type: 'input'  },
      { pin: 10, name: 'D6',   type: 'input'  },
      { pin: 11, name: 'D7',   type: 'input'  },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'D8',   type: 'input'  },
      { pin: 14, name: 'Q8',   type: 'output' },
      { pin: 15, name: 'Q7',   type: 'output' },
      { pin: 16, name: 'Q6',   type: 'output' },
      { pin: 17, name: 'Q5',   type: 'output' },
      { pin: 18, name: 'Q4',   type: 'output' },
      { pin: 19, name: 'Q3',   type: 'output' },
      { pin: 20, name: 'Q2',   type: 'output' },
      { pin: 21, name: 'Q1',   type: 'output' },
      { pin: 22, name: 'Q0',   type: 'output' },
      { pin: 23, name: 'NC',   type: 'nc'     },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','CLK','CLRn','D0','D1','D2','D3','D4','D5','D6','D7','D8'], outputs: [] },
    ],
  },
};
