export const CHIPS_BLOCK_70 = {
  '28C16': {
    name: '28C16',
    simpleName: '2K × 8 EEPROM',
    description: '2048 × 8 electrically erasable PROM with byte-wide I/O (24-pin)',
    pins: 24,
    vcc: 24,
    gnd: 12,
    datasheet: 'https://ww1.microchip.com/downloads/en/DeviceDoc/doc0000.pdf',
    tags: ['eeprom', 'memory', 'rom', 'programmable', 'non-volatile', '2k', '8-bit', 'storage'],
    sequential: true,
    guideOverview: 'The 28C16 (AT28C16) is a 2048-word by 8-bit EEPROM in a 24-pin DIP package. Despite the "28" in its name (which identifies the EEPROM product family), it is a 24-pin device. Three control signals manage all access modes: CE# (Chip Enable, active LOW), OE# (Output Enable, active LOW), and WE# (Write Enable, active LOW). During standby (CE# HIGH) all I/O pins float to high-impedance. During a read cycle (CE# LOW, OE# LOW, WE# HIGH) the stored byte at the 11-bit address drives IO0–IO7. During a byte write (CE# LOW, OE# HIGH, WE# LOW) data present on IO0–IO7 is captured and written to memory; IO pins go high-impedance.',
    guidePinDescriptions: {
      'A0':  'Address bit 0 (LSB).',
      'A1':  'Address bit 1.',
      'A2':  'Address bit 2.',
      'A3':  'Address bit 3.',
      'A4':  'Address bit 4.',
      'A5':  'Address bit 5.',
      'A6':  'Address bit 6.',
      'A7':  'Address bit 7.',
      'A8':  'Address bit 8.',
      'A9':  'Address bit 9.',
      'A10': 'Address bit 10 (MSB). Combined with A0–A9, selects one of 2048 byte locations.',
      'IO0': 'Data I/O bit 0 (LSB). Bidirectional: inputs write data when WE# is active; outputs stored data when OE# is active.',
      'IO1': 'Data I/O bit 1.',
      'IO2': 'Data I/O bit 2.',
      'IO3': 'Data I/O bit 3.',
      'IO4': 'Data I/O bit 4.',
      'IO5': 'Data I/O bit 5.',
      'IO6': 'Data I/O bit 6.',
      'IO7': 'Data I/O bit 7 (MSB).',
      'CE':  'Chip Enable, active LOW. Pull HIGH to deselect the chip and force all I/O to Hi-Z.',
      'OE':  'Output Enable, active LOW. Pull LOW (with CE# LOW, WE# HIGH) to drive read data onto IO0–IO7.',
      'WE':  'Write Enable, active LOW. Pull LOW (with CE# LOW, OE# HIGH) to write IO0–IO7 into memory.',
      'GND': 'Ground reference (pin 12).',
      'VCC': 'Supply voltage +5 V (pin 24).',
    },
    guideSections: [
      {
        title: 'Operating Modes',
        paragraphs: [
          'Standby: CE# HIGH. All IO pins are high-impedance regardless of OE# and WE#.',
          'Read: CE# LOW, OE# LOW, WE# HIGH. The byte stored at address A0–A10 drives IO0–IO7.',
          'Write: CE# LOW, OE# HIGH, WE# LOW. Data on IO0–IO7 is written to the addressed location. IO pins are high-impedance during the write cycle.',
          'Output Disable: CE# LOW, OE# HIGH, WE# HIGH. IO pins are high-impedance; no write occurs.',
        ],
      },
      {
        title: 'Addressing and Memory',
        paragraphs: [
          'Eleven address bits (A0–A10) select one of 2048 byte locations. Note that A10 is on pin 19, A9 on pin 21, and A8 on pin 22 — not in sequence with A0–A7.',
          'In the simulator all 2048 locations start at 0x00. Contents persist for the session but reset when the chip is removed from the board.',
        ],
        note: 'The "28" in 28C16 is the EEPROM family designation, not the pin count. This chip has 24 pins.',
      },
    ],
    pinout: [
      { pin:  1, name: 'A7',  type: 'input',  description: 'Address bit 7' },
      { pin:  2, name: 'A6',  type: 'input',  description: 'Address bit 6' },
      { pin:  3, name: 'A5',  type: 'input',  description: 'Address bit 5' },
      { pin:  4, name: 'A4',  type: 'input',  description: 'Address bit 4' },
      { pin:  5, name: 'A3',  type: 'input',  description: 'Address bit 3' },
      { pin:  6, name: 'A2',  type: 'input',  description: 'Address bit 2' },
      { pin:  7, name: 'A1',  type: 'input',  description: 'Address bit 1' },
      { pin:  8, name: 'A0',  type: 'input',  description: 'Address bit 0 (LSB)' },
      { pin:  9, name: 'IO0', type: 'output', description: 'Data I/O bit 0 (bidirectional)' },
      { pin: 10, name: 'IO1', type: 'output', description: 'Data I/O bit 1 (bidirectional)' },
      { pin: 11, name: 'IO2', type: 'output', description: 'Data I/O bit 2 (bidirectional)' },
      { pin: 12, name: 'GND', type: 'power',  description: 'Ground (0 V)' },
      { pin: 13, name: 'IO3', type: 'output', description: 'Data I/O bit 3 (bidirectional)' },
      { pin: 14, name: 'IO4', type: 'output', description: 'Data I/O bit 4 (bidirectional)' },
      { pin: 15, name: 'IO5', type: 'output', description: 'Data I/O bit 5 (bidirectional)' },
      { pin: 16, name: 'IO6', type: 'output', description: 'Data I/O bit 6 (bidirectional)' },
      { pin: 17, name: 'IO7', type: 'output', description: 'Data I/O bit 7 (MSB, bidirectional)' },
      { pin: 18, name: 'CE',  type: 'input',  description: 'Chip Enable, active LOW' },
      { pin: 19, name: 'A10', type: 'input',  description: 'Address bit 10 (MSB)' },
      { pin: 20, name: 'OE',  type: 'input',  description: 'Output Enable, active LOW' },
      { pin: 21, name: 'A9',  type: 'input',  description: 'Address bit 9' },
      { pin: 22, name: 'A8',  type: 'input',  description: 'Address bit 8' },
      { pin: 23, name: 'WE',  type: 'input',  description: 'Write Enable, active LOW' },
      { pin: 24, name: 'VCC', type: 'power',  description: 'Supply voltage (+5 V)' },
    ],
    gates: [
      {
        type: 'EEPROM_2KX8',
        inputs: [
          'A0','A1','A2','A3','A4','A5','A6','A7','A8','A9','A10',
          'IO0','IO1','IO2','IO3','IO4','IO5','IO6','IO7',
          'CE','OE','WE',
        ],
        outputs: ['IO0','IO1','IO2','IO3','IO4','IO5','IO6','IO7'],
      },
    ],
  },
};
