// Chip definitions block 41
// Chips: 74826 74828, 74832 74835, 74839 74840, 74841 74846, 74848

export const CHIPS_BLOCK_41 = {

  // ── 74826: 8 bit D-FF, CLRn+CEN, inverting inputs, TRI (24-pin) ──────────
  /* Primary source: Texas Instruments, 74826 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74as826.pdf
     https://en.wikipedia.org/wiki/Flip-flop_(electronics) */
  '74826': {
    name: '74x826',
    simpleName: '8 bit D-FF w/ CLRn+CEN, Inv In (TRI)',
    description: '8 bit D-type flip-flop with clear and clock enable inputs, inverting inputs, three-state outputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74as826.pdf',
    tags: ['flip-flop', 'D-type', '8 bit', 'inverting', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x826 is an 8 bit D-type bus flip-flop with asynchronous clear, clock enable, and tri-state outputs. It is the inverted-input/polarity variant used when surrounding logic is active LOW. This helps reduce external inverter count in high-speed bus interfaces.',
    guidePinDescriptions: {
      'OEn':  'Output enable (active LOW).',
      'CLRn': 'Asynchronous clear input (active LOW).',
      'CEN':  'Clock enable input.',
      'D0':   'Data input bit 0.',
      'D1':   'Data input bit 1.',
      'D2':   'Data input bit 2.',
      'D3':   'Data input bit 3.',
      'D4':   'Data input bit 4.',
      'D5':   'Data input bit 5.',
      'D6':   'Data input bit 6.',
      'D7':   'Data input bit 7.',
      'GND':  'Ground reference (pin 12).',
      'CLK':  'Clock input.',
      'NC':   'No connect.',
      'Q7':   'Registered output bit 7.',
      'Q6':   'Registered output bit 6.',
      'Q5':   'Registered output bit 5.',
      'Q4':   'Registered output bit 4.',
      'Q3':   'Registered output bit 3.',
      'Q2':   'Registered output bit 2.',
      'Q1':   'Registered output bit 1.',
      'Q0':   'Registered output bit 0.',
      'VCC':  'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: 'Bus Register Control Pins',
        paragraphs: [
          'CLRn provides immediate reset, CEN allows state hold without stopping the clock, and OEn controls bus driving. This trio is common in high-speed synchronous bus pipelines.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'OEn', type: 'input'  },
      { pin:  2, name: 'CLRn',type: 'input'  },
      { pin:  3, name: 'CEN', type: 'input'  },
      { pin:  4, name: 'D0',  type: 'input'  },
      { pin:  5, name: 'D1',  type: 'input'  },
      { pin:  6, name: 'D2',  type: 'input'  },
      { pin:  7, name: 'D3',  type: 'input'  },
      { pin:  8, name: 'D4',  type: 'input'  },
      { pin:  9, name: 'D5',  type: 'input'  },
      { pin: 10, name: 'D6',  type: 'input'  },
      { pin: 11, name: 'D7',  type: 'input'  },
      { pin: 12, name: 'GND', type: 'power'  },
      { pin: 13, name: 'CLK', type: 'input'  },
      { pin: 14, name: 'NC',  type: 'nc'     },
      { pin: 15, name: 'Q7',  type: 'output' },
      { pin: 16, name: 'Q6',  type: 'output' },
      { pin: 17, name: 'Q5',  type: 'output' },
      { pin: 18, name: 'Q4',  type: 'output' },
      { pin: 19, name: 'Q3',  type: 'output' },
      { pin: 20, name: 'Q2',  type: 'output' },
      { pin: 21, name: 'Q1',  type: 'output' },
      { pin: 22, name: 'Q0',  type: 'output' },
      { pin: 23, name: 'NC',  type: 'nc'     },
      { pin: 24, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','CLRn','CEN','CLK','D0','D1','D2','D3','D4','D5','D6','D7'], outputs: ['Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7'] },
    ],
  },

  // ── 74827: 10 bit buffer, non-inverting, TRI (24-pin) ────────────────────
  /* Primary source: Texas Instruments, 74827 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/mc74f827.pdf
     https://en.wikipedia.org/wiki/Three-state_logic */
  '74827': {
    name: '74x827',
    simpleName: '10 bit Buffer (Non-Inv, TRI)',
    description: '10 bit buffer with non-inverting three-state outputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: 'https://www.ti.com/lit/ds/symlink/mc74f827.pdf',
    tags: ['buffer', '10 bit', 'non-inverting', 'tri-state', 'stub'],
    guideOverview: 'The 74x827 is a 10 bit non-inverting tri-state buffer for wide bus interfaces. It is commonly used to isolate processor, memory, and peripheral buses while preserving logic polarity.',
    guidePinDescriptions: {
      'OEn': 'Output enable (active LOW).',
      'A0':  'Input bit 0.',
      'A1':  'Input bit 1.',
      'A2':  'Input bit 2.',
      'A3':  'Input bit 3.',
      'A4':  'Input bit 4.',
      'A5':  'Input bit 5.',
      'A6':  'Input bit 6.',
      'A7':  'Input bit 7.',
      'A8':  'Input bit 8.',
      'A9':  'Input bit 9.',
      'GND': 'Ground reference (pin 12).',
      'Y9':  'Buffered output bit 9.',
      'Y8':  'Buffered output bit 8.',
      'Y7':  'Buffered output bit 7.',
      'Y6':  'Buffered output bit 6.',
      'Y5':  'Buffered output bit 5.',
      'Y4':  'Buffered output bit 4.',
      'Y3':  'Buffered output bit 3.',
      'Y2':  'Buffered output bit 2.',
      'Y1':  'Buffered output bit 1.',
      'Y0':  'Buffered output bit 0.',
      'NC':  'No connect.',
      'VCC': 'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: '10 bit Bus Width',
        paragraphs: [
          'Ten-bit paths are useful for 8 bit data plus parity/status lines, or for segmented control/address bundles. One package can buffer the whole group with one enable.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'OEn', type: 'input'  },
      { pin:  2, name: 'A0',  type: 'input'  },
      { pin:  3, name: 'A1',  type: 'input'  },
      { pin:  4, name: 'A2',  type: 'input'  },
      { pin:  5, name: 'A3',  type: 'input'  },
      { pin:  6, name: 'A4',  type: 'input'  },
      { pin:  7, name: 'A5',  type: 'input'  },
      { pin:  8, name: 'A6',  type: 'input'  },
      { pin:  9, name: 'A7',  type: 'input'  },
      { pin: 10, name: 'A8',  type: 'input'  },
      { pin: 11, name: 'A9',  type: 'input'  },
      { pin: 12, name: 'GND', type: 'power'  },
      { pin: 13, name: 'Y9',  type: 'output' },
      { pin: 14, name: 'Y8',  type: 'output' },
      { pin: 15, name: 'Y7',  type: 'output' },
      { pin: 16, name: 'Y6',  type: 'output' },
      { pin: 17, name: 'Y5',  type: 'output' },
      { pin: 18, name: 'Y4',  type: 'output' },
      { pin: 19, name: 'Y3',  type: 'output' },
      { pin: 20, name: 'Y2',  type: 'output' },
      { pin: 21, name: 'Y1',  type: 'output' },
      { pin: 22, name: 'Y0',  type: 'output' },
      { pin: 23, name: 'NC',  type: 'nc'     },
      { pin: 24, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','A0','A1','A2','A3','A4','A5','A6','A7','A8','A9'], outputs: ['Y0','Y1','Y2','Y3','Y4','Y5','Y6','Y7','Y8','Y9'] },
    ],
  },

  // ── 74828: 10 bit buffer, inverting, TRI (24-pin) ────────────────────────
  /* Primary source: Texas Instruments, 74828 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/mc74f828.pdf
     https://en.wikipedia.org/wiki/Three-state_logic */
  '74828': {
    name: '74x828',
    simpleName: '10 bit Buffer (Inv, TRI)',
    description: '10 bit buffer with inverting three-state outputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: 'https://www.ti.com/lit/ds/symlink/mc74f828.pdf',
    tags: ['buffer', '10 bit', 'inverting', 'tri-state', 'stub'],
    guideOverview: 'The 74x828 is the inverting counterpart to the 74x827. It provides the same 10 bit tri-state bus isolation while flipping polarity, useful for active LOW bus conventions.',
    guidePinDescriptions: {
      'OEn': 'Output enable (active LOW).',
      'A0':  'Input bit 0.',
      'A1':  'Input bit 1.',
      'A2':  'Input bit 2.',
      'A3':  'Input bit 3.',
      'A4':  'Input bit 4.',
      'A5':  'Input bit 5.',
      'A6':  'Input bit 6.',
      'A7':  'Input bit 7.',
      'A8':  'Input bit 8.',
      'A9':  'Input bit 9.',
      'GND': 'Ground reference (pin 12).',
      'Y9':  'Inverted output bit 9.',
      'Y8':  'Inverted output bit 8.',
      'Y7':  'Inverted output bit 7.',
      'Y6':  'Inverted output bit 6.',
      'Y5':  'Inverted output bit 5.',
      'Y4':  'Inverted output bit 4.',
      'Y3':  'Inverted output bit 3.',
      'Y2':  'Inverted output bit 2.',
      'Y1':  'Inverted output bit 1.',
      'Y0':  'Inverted output bit 0.',
      'NC':  'No connect.',
      'VCC': 'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: '74x827 vs 74x828',
        paragraphs: [
          'Both are 10 bit tri-state buffers. 74x827 is non-inverting; 74x828 is inverting.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'OEn', type: 'input'  },
      { pin:  2, name: 'A0',  type: 'input'  },
      { pin:  3, name: 'A1',  type: 'input'  },
      { pin:  4, name: 'A2',  type: 'input'  },
      { pin:  5, name: 'A3',  type: 'input'  },
      { pin:  6, name: 'A4',  type: 'input'  },
      { pin:  7, name: 'A5',  type: 'input'  },
      { pin:  8, name: 'A6',  type: 'input'  },
      { pin:  9, name: 'A7',  type: 'input'  },
      { pin: 10, name: 'A8',  type: 'input'  },
      { pin: 11, name: 'A9',  type: 'input'  },
      { pin: 12, name: 'GND', type: 'power'  },
      { pin: 13, name: 'Y9',  type: 'output' },
      { pin: 14, name: 'Y8',  type: 'output' },
      { pin: 15, name: 'Y7',  type: 'output' },
      { pin: 16, name: 'Y6',  type: 'output' },
      { pin: 17, name: 'Y5',  type: 'output' },
      { pin: 18, name: 'Y4',  type: 'output' },
      { pin: 19, name: 'Y3',  type: 'output' },
      { pin: 20, name: 'Y2',  type: 'output' },
      { pin: 21, name: 'Y1',  type: 'output' },
      { pin: 22, name: 'Y0',  type: 'output' },
      { pin: 23, name: 'NC',  type: 'nc'     },
      { pin: 24, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','A0','A1','A2','A3','A4','A5','A6','A7','A8','A9'], outputs: ['Y0','Y1','Y2','Y3','Y4','Y5','Y6','Y7','Y8','Y9'] },
    ],
  },

  // ── 74832: Hex 2 input OR drivers (20-pin) ───────────────────────────────
  /* Primary source: Texas Instruments, 74832 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74als832a.pdf */
  '74832': {
    name: '74x832',
    simpleName: 'Hex 2 Input OR Driver',
    description: 'Hex 2 input OR drivers (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74als832a.pdf',
    tags: ['OR', 'gate', 'driver', 'hex', 'stub'],
    guideOverview: 'The 74x832 contains six independent 2 input OR driver gates. It is a general-purpose glue-logic part for combining enables, status conditions, and control strobes.',
    guidePinDescriptions: {
      'A0':  'Input A for gate 0.',
      'B0':  'Input B for gate 0.',
      'Y0':  'OR output for gate 0.',
      'A1':  'Input A for gate 1.',
      'B1':  'Input B for gate 1.',
      'Y1':  'OR output for gate 1.',
      'A2':  'Input A for gate 2.',
      'B2':  'Input B for gate 2.',
      'Y2':  'OR output for gate 2.',
      'GND': 'Ground reference (pin 10).',
      'Y3':  'OR output for gate 3.',
      'B3':  'Input B for gate 3.',
      'A3':  'Input A for gate 3.',
      'Y4':  'OR output for gate 4.',
      'B4':  'Input B for gate 4.',
      'A4':  'Input A for gate 4.',
      'Y5':  'OR output for gate 5.',
      'B5':  'Input B for gate 5.',
      'A5':  'Input A for gate 5.',
      'VCC': 'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'Hex OR Logic',
        formulas: [
          'Y = A + B',
        ],
        paragraphs: [
          'OR gates are widely used to merge multiple request or enable conditions into a single control signal.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'A0',  type: 'input'  },
      { pin:  2, name: 'B0',  type: 'input'  },
      { pin:  3, name: 'Y0',  type: 'output' },
      { pin:  4, name: 'A1',  type: 'input'  },
      { pin:  5, name: 'B1',  type: 'input'  },
      { pin:  6, name: 'Y1',  type: 'output' },
      { pin:  7, name: 'A2',  type: 'input'  },
      { pin:  8, name: 'B2',  type: 'input'  },
      { pin:  9, name: 'Y2',  type: 'output' },
      { pin: 10, name: 'GND', type: 'power'  },
      { pin: 11, name: 'Y3',  type: 'output' },
      { pin: 12, name: 'B3',  type: 'input'  },
      { pin: 13, name: 'A3',  type: 'input'  },
      { pin: 14, name: 'Y4',  type: 'output' },
      { pin: 15, name: 'B4',  type: 'input'  },
      { pin: 16, name: 'A4',  type: 'input'  },
      { pin: 17, name: 'Y5',  type: 'output' },
      { pin: 18, name: 'B5',  type: 'input'  },
      { pin: 19, name: 'A5',  type: 'input'  },
      { pin: 20, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['A0','B0','A1','B1','A2','B2','A3','B3','A4','B4','A5','B5'], outputs: ['Y0','Y1','Y2','Y3','Y4','Y5'] },
    ],
  },

  // ── 74833: 8-to-9 bit bus transceiver w/ parity register, non-inv, TRI (24-pin)
  /* Primary source: Texas Instruments, 74833 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74abt833.pdf
     https://en.wikipedia.org/wiki/Parity_bit */
  '74833': {
    name: '74x833',
    simpleName: '8-to-9 bit Transceiver w/ Parity (TRI)',
    description: '8 bit to 9 bit bus transceiver with parity register, non-inverting, three-state outputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74abt833.pdf',
    tags: ['transceiver', 'parity', '8 bit', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x833 is an 8 bit bidirectional transceiver with an extra parity bit path and parity register support. It moves byte-wide data between A and B buses while handling AP/BP parity lines under shared control. OEBAn and OEABn (both active LOW) enable the two directions independently.',
    guidePinDescriptions: {
      'OEn': 'Output enable (active LOW).',
      'DIR': 'Direction control for A-to-B or B-to-A transfer.',
      'A0':  'Bus A bit 0.',
      'A1':  'Bus A bit 1.',
      'A2':  'Bus A bit 2.',
      'A3':  'Bus A bit 3.',
      'A4':  'Bus A bit 4.',
      'A5':  'Bus A bit 5.',
      'A6':  'Bus A bit 6.',
      'A7':  'Bus A bit 7.',
      'AP':  'Bus A parity bit.',
      'GND': 'Ground reference (pin 12).',
      'BP':  'Bus B parity bit.',
      'B7':  'Bus B bit 7.',
      'B6':  'Bus B bit 6.',
      'B5':  'Bus B bit 5.',
      'B4':  'Bus B bit 4.',
      'B3':  'Bus B bit 3.',
      'B2':  'Bus B bit 2.',
      'B1':  'Bus B bit 1.',
      'B0':  'Bus B bit 0.',
      'CLK': 'Clock input for parity/register timing.',
      'LE':  'Latch enable/control input.',
      'VCC': 'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: 'Parity Bus Interfaces',
        paragraphs: [
          'Parity adds simple error detection to byte transfers. A 9 bit transceiver keeps data and parity aligned so system firmware can verify bus integrity.',
        ],
        note: 'This part is currently represented by a generic stub model.',
      },
    ],
    pinout: [
      { pin:  1, name: 'OEn', type: 'input'  },
      { pin:  2, name: 'DIR', type: 'input'  },
      { pin:  3, name: 'A0',  type: 'bidir'  },
      { pin:  4, name: 'A1',  type: 'bidir'  },
      { pin:  5, name: 'A2',  type: 'bidir'  },
      { pin:  6, name: 'A3',  type: 'bidir'  },
      { pin:  7, name: 'A4',  type: 'bidir'  },
      { pin:  8, name: 'A5',  type: 'bidir'  },
      { pin:  9, name: 'A6',  type: 'bidir'  },
      { pin: 10, name: 'A7',  type: 'bidir'  },
      { pin: 11, name: 'AP',  type: 'bidir'  },
      { pin: 12, name: 'GND', type: 'power'  },
      { pin: 13, name: 'BP',  type: 'bidir'  },
      { pin: 14, name: 'B7',  type: 'bidir'  },
      { pin: 15, name: 'B6',  type: 'bidir'  },
      { pin: 16, name: 'B5',  type: 'bidir'  },
      { pin: 17, name: 'B4',  type: 'bidir'  },
      { pin: 18, name: 'B3',  type: 'bidir'  },
      { pin: 19, name: 'B2',  type: 'bidir'  },
      { pin: 20, name: 'B1',  type: 'bidir'  },
      { pin: 21, name: 'B0',  type: 'bidir'  },
      { pin: 22, name: 'CLK', type: 'input'  },
      { pin: 23, name: 'LE',  type: 'input'  },
      { pin: 24, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','DIR','CLK','LE'], outputs: [] },
    ],
  },

  // ── 74834: 8-to-9 bit bus transceiver w/ parity register, inv, TRI (24-pin)
  /* Primary source: Texas Instruments, 74834 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/idt74fct834.pdf
     https://en.wikipedia.org/wiki/Parity_bit */
  '74834': {
    name: '74x834',
    simpleName: '8-to-9 bit Transceiver w/ Parity, Inv (TRI)',
    description: '8 bit to 9 bit bus transceiver with parity register, inverting, three-state outputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: 'https://www.ti.com/lit/ds/symlink/idt74fct834.pdf',
    tags: ['transceiver', 'parity', '8 bit', 'inverting', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x834 is the inverting/polarity variant of the 74x833 parity transceiver. It supports the same 8+1 bit transfer concept with inversion. Choose 74x834 when active LOW conventions or inversion-aware bus logic are required.',
    guidePinDescriptions: {
      'OEn': 'Output enable (active LOW).',
      'DIR': 'Direction control for transfer path.',
      'A0':  'Bus A bit 0.',
      'A1':  'Bus A bit 1.',
      'A2':  'Bus A bit 2.',
      'A3':  'Bus A bit 3.',
      'A4':  'Bus A bit 4.',
      'A5':  'Bus A bit 5.',
      'A6':  'Bus A bit 6.',
      'A7':  'Bus A bit 7.',
      'AP':  'Bus A parity channel.',
      'GND': 'Ground reference (pin 12).',
      'BP':  'Bus B parity channel.',
      'B7':  'Bus B bit 7.',
      'B6':  'Bus B bit 6.',
      'B5':  'Bus B bit 5.',
      'B4':  'Bus B bit 4.',
      'B3':  'Bus B bit 3.',
      'B2':  'Bus B bit 2.',
      'B1':  'Bus B bit 1.',
      'B0':  'Bus B bit 0.',
      'CLK': 'Clock input.',
      'LE':  'Latch/enable timing input.',
      'VCC': 'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: 'Parity Transceiver Pairing',
        paragraphs: [
          '74x833 and 74x834 are often paired by polarity needs across a design. Functionally they target the same error-aware byte transfer role.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'OEn', type: 'input'  },
      { pin:  2, name: 'DIR', type: 'input'  },
      { pin:  3, name: 'A0',  type: 'bidir'  },
      { pin:  4, name: 'A1',  type: 'bidir'  },
      { pin:  5, name: 'A2',  type: 'bidir'  },
      { pin:  6, name: 'A3',  type: 'bidir'  },
      { pin:  7, name: 'A4',  type: 'bidir'  },
      { pin:  8, name: 'A5',  type: 'bidir'  },
      { pin:  9, name: 'A6',  type: 'bidir'  },
      { pin: 10, name: 'A7',  type: 'bidir'  },
      { pin: 11, name: 'AP',  type: 'bidir'  },
      { pin: 12, name: 'GND', type: 'power'  },
      { pin: 13, name: 'BP',  type: 'bidir'  },
      { pin: 14, name: 'B7',  type: 'bidir'  },
      { pin: 15, name: 'B6',  type: 'bidir'  },
      { pin: 16, name: 'B5',  type: 'bidir'  },
      { pin: 17, name: 'B4',  type: 'bidir'  },
      { pin: 18, name: 'B3',  type: 'bidir'  },
      { pin: 19, name: 'B2',  type: 'bidir'  },
      { pin: 20, name: 'B1',  type: 'bidir'  },
      { pin: 21, name: 'B0',  type: 'bidir'  },
      { pin: 22, name: 'CLK', type: 'input'  },
      { pin: 23, name: 'LE',  type: 'input'  },
      { pin: 24, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','DIR','CLK','LE'], outputs: [] },
    ],
  },

  // ── 74835: 8 bit shift register w/ 2:1 MUX, latched input, serial out (24-pin)
  /* Primary source: Texas Instruments, 74835 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74f835.pdf
     https://en.wikipedia.org/wiki/Shift_register */
  '74835': {
    name: '74x835',
    simpleName: '8 bit Shift Reg w/ 2:1 MUX',
    description: '8 bit shift register with 2:1 input multiplexers, one input latched, serial output (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74f835.pdf',
    tags: ['shift register', 'mux', '8 bit', 'sequential', 'stub'],
    sequential: true,
    guideOverview: 'The 74x835 is an 8 bit shift register with 2:1 input multiplexing per stage and serial output. SEL chooses between A and B input banks, while SER supports serial chaining and QSER provides serial-out. LE and CLK coordinate staged loading and shifting.',
    guidePinDescriptions: {
      'SER':  'Serial input for shift-chain operation.',
      'CLK':  'Clock input for shift/register updates.',
      'LE':   'Latch/enable control for loading behavior.',
      'SEL':  'Selects A-input bank or B-input bank.',
      'A0':   'Parallel input A bit 0.',
      'B0':   'Parallel input B bit 0.',
      'A1':   'Parallel input A bit 1.',
      'B1':   'Parallel input B bit 1.',
      'A2':   'Parallel input A bit 2.',
      'B2':   'Parallel input B bit 2.',
      'A3':   'Parallel input A bit 3.',
      'GND':  'Ground reference (pin 12).',
      'B3':   'Parallel input B bit 3.',
      'A4':   'Parallel input A bit 4.',
      'B4':   'Parallel input B bit 4.',
      'A5':   'Parallel input A bit 5.',
      'B5':   'Parallel input B bit 5.',
      'A6':   'Parallel input A bit 6.',
      'B6':   'Parallel input B bit 6.',
      'A7':   'Parallel input A bit 7.',
      'B7':   'Parallel input B bit 7.',
      'QSER': 'Serial output for cascading to next shift stage.',
      'NC':   'No connect.',
      'VCC':  'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: 'Muxed Shift Register Concept',
        paragraphs: [
          'Combining input multiplexers with shift storage lets one part switch between two parallel sources while retaining serial-chain capability. This is useful in scan paths and selectable data staging.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'SER',  type: 'input'  },
      { pin:  2, name: 'CLK',  type: 'input'  },
      { pin:  3, name: 'LE',   type: 'input'  },
      { pin:  4, name: 'SEL',  type: 'input'  },
      { pin:  5, name: 'A0',   type: 'input'  },
      { pin:  6, name: 'B0',   type: 'input'  },
      { pin:  7, name: 'A1',   type: 'input'  },
      { pin:  8, name: 'B1',   type: 'input'  },
      { pin:  9, name: 'A2',   type: 'input'  },
      { pin: 10, name: 'B2',   type: 'input'  },
      { pin: 11, name: 'A3',   type: 'input'  },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'B3',   type: 'input'  },
      { pin: 14, name: 'A4',   type: 'input'  },
      { pin: 15, name: 'B4',   type: 'input'  },
      { pin: 16, name: 'A5',   type: 'input'  },
      { pin: 17, name: 'B5',   type: 'input'  },
      { pin: 18, name: 'A6',   type: 'input'  },
      { pin: 19, name: 'B6',   type: 'input'  },
      { pin: 20, name: 'A7',   type: 'input'  },
      { pin: 21, name: 'B7',   type: 'input'  },
      { pin: 22, name: 'QSER', type: 'output' },
      { pin: 23, name: 'NC',   type: 'nc'     },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['SER','CLK','LE','SEL','A0','B0','A1','B1','A2','B2','A3','B3','A4','B4','A5','B5','A6','B6','A7','B7'], outputs: ['QSER'] },
    ],
  },

  // ── 74839: Field-programmable logic array 14×32×6, TRI (24-pin) ──────────
  /* Primary source: Texas Instruments, 74839 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74pl839.pdf */
  '74839': {
    name: '74x839',
    simpleName: 'Prog. Logic Array 14×32×6 (TRI)',
    description: 'Field-programmable logic array 14×32×6 with three-state outputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74pl839.pdf',
    tags: ['PLA', 'programmable', 'tri-state', 'stub'],
    guideOverview: 'The 74x839 is a field-programmable logic array (PLA) with 14 inputs and 6 tri-state outputs. It implements custom sum-of-products logic in one package, historically used for board-level state decoding and control equations.',
    guidePinDescriptions: {
      'OEn': 'Output enable control (active LOW) for tri-state outputs.',
      'I0':  'Programmable logic input 0.',
      'I1':  'Programmable logic input 1.',
      'I2':  'Programmable logic input 2.',
      'I3':  'Programmable logic input 3.',
      'I4':  'Programmable logic input 4.',
      'I5':  'Programmable logic input 5.',
      'I6':  'Programmable logic input 6.',
      'I7':  'Programmable logic input 7.',
      'I8':  'Programmable logic input 8.',
      'I9':  'Programmable logic input 9.',
      'GND': 'Ground reference (pin 12).',
      'I10': 'Programmable logic input 10.',
      'I11': 'Programmable logic input 11.',
      'I12': 'Programmable logic input 12.',
      'I13': 'Programmable logic input 13.',
      'O5':  'Programmable output 5.',
      'O4':  'Programmable output 4.',
      'O3':  'Programmable output 3.',
      'O2':  'Programmable output 2.',
      'O1':  'Programmable output 1.',
      'O0':  'Programmable output 0.',
      'NC':  'No connect.',
      'VCC': 'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: 'PLA Fundamentals',
        paragraphs: [
          'PLAs implement logic as programmable AND terms feeding OR outputs. Before CPLDs/FPGAs became common, PLAs were a compact way to replace many small glue-logic chips.',
        ],
        note: 'Internal fuse-map behavior is not modeled; represented as a stub.',
      },
    ],
    pinout: [
      { pin:  1, name: 'OEn', type: 'input'  },
      { pin:  2, name: 'I0',  type: 'input'  },
      { pin:  3, name: 'I1',  type: 'input'  },
      { pin:  4, name: 'I2',  type: 'input'  },
      { pin:  5, name: 'I3',  type: 'input'  },
      { pin:  6, name: 'I4',  type: 'input'  },
      { pin:  7, name: 'I5',  type: 'input'  },
      { pin:  8, name: 'I6',  type: 'input'  },
      { pin:  9, name: 'I7',  type: 'input'  },
      { pin: 10, name: 'I8',  type: 'input'  },
      { pin: 11, name: 'I9',  type: 'input'  },
      { pin: 12, name: 'GND', type: 'power'  },
      { pin: 13, name: 'I10', type: 'input'  },
      { pin: 14, name: 'I11', type: 'input'  },
      { pin: 15, name: 'I12', type: 'input'  },
      { pin: 16, name: 'I13', type: 'input'  },
      { pin: 17, name: 'O5',  type: 'output' },
      { pin: 18, name: 'O4',  type: 'output' },
      { pin: 19, name: 'O3',  type: 'output' },
      { pin: 20, name: 'O2',  type: 'output' },
      { pin: 21, name: 'O1',  type: 'output' },
      { pin: 22, name: 'O0',  type: 'output' },
      { pin: 23, name: 'NC',  type: 'nc'     },
      { pin: 24, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','I0','I1','I2','I3','I4','I5','I6','I7','I8','I9','I10','I11','I12','I13'], outputs: ['O0','O1','O2','O3','O4','O5'] },
    ],
  },

  // ── 74840: Field-programmable logic array 14×32×6, OC (24-pin) ───────────
  /* Primary source: Texas Instruments, 74840 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74pl840.pdf */
  '74840': {
    name: '74x840',
    simpleName: 'Prog. Logic Array 14×32×6 (OC)',
    description: 'Field-programmable logic array 14×32×6 with open-collector outputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    openCollector: true,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74pl840.pdf',
    tags: ['PLA', 'programmable', 'open-collector', 'stub'],
    guideOverview: 'The 74x840 is the open-collector output variant of the 14x32x6 PLA family. It supports programmable logic equations while allowing wired OR style output interconnection through pull up resistors.',
    guidePinDescriptions: {
      'NC':  'No connect.',
      'I0':  'Programmable logic input 0.',
      'I1':  'Programmable logic input 1.',
      'I2':  'Programmable logic input 2.',
      'I3':  'Programmable logic input 3.',
      'I4':  'Programmable logic input 4.',
      'I5':  'Programmable logic input 5.',
      'I6':  'Programmable logic input 6.',
      'I7':  'Programmable logic input 7.',
      'I8':  'Programmable logic input 8.',
      'I9':  'Programmable logic input 9.',
      'GND': 'Ground reference (pin 12).',
      'I10': 'Programmable logic input 10.',
      'I11': 'Programmable logic input 11.',
      'I12': 'Programmable logic input 12.',
      'I13': 'Programmable logic input 13.',
      'O5':  'Open-collector programmable output 5.',
      'O4':  'Open-collector programmable output 4.',
      'O3':  'Open-collector programmable output 3.',
      'O2':  'Open-collector programmable output 2.',
      'O1':  'Open-collector programmable output 1.',
      'O0':  'Open-collector programmable output 0.',
      'VCC': 'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: 'OC PLA Outputs',
        paragraphs: [
          'Open-collector outputs let multiple logic sources share a line with pull ups, which is useful for fault flags and priority-encoded control lines.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'NC',  type: 'nc'     },
      { pin:  2, name: 'I0',  type: 'input'  },
      { pin:  3, name: 'I1',  type: 'input'  },
      { pin:  4, name: 'I2',  type: 'input'  },
      { pin:  5, name: 'I3',  type: 'input'  },
      { pin:  6, name: 'I4',  type: 'input'  },
      { pin:  7, name: 'I5',  type: 'input'  },
      { pin:  8, name: 'I6',  type: 'input'  },
      { pin:  9, name: 'I7',  type: 'input'  },
      { pin: 10, name: 'I8',  type: 'input'  },
      { pin: 11, name: 'I9',  type: 'input'  },
      { pin: 12, name: 'GND', type: 'power'  },
      { pin: 13, name: 'I10', type: 'input'  },
      { pin: 14, name: 'I11', type: 'input'  },
      { pin: 15, name: 'I12', type: 'input'  },
      { pin: 16, name: 'I13', type: 'input'  },
      { pin: 17, name: 'O5',  type: 'output' },
      { pin: 18, name: 'O4',  type: 'output' },
      { pin: 19, name: 'O3',  type: 'output' },
      { pin: 20, name: 'O2',  type: 'output' },
      { pin: 21, name: 'O1',  type: 'output' },
      { pin: 22, name: 'O0',  type: 'output' },
      { pin: 23, name: 'NC',  type: 'nc'     },
      { pin: 24, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['I0','I1','I2','I3','I4','I5','I6','I7','I8','I9','I10','I11','I12','I13'], outputs: ['O0','O1','O2','O3','O4','O5'] },
    ],
  },

  // ── 74841: 10 bit D-type flip-flop, TRI (24-pin) ─────────────────────────
  /* Primary source: Texas Instruments, 74841 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74als841.pdf
     https://en.wikipedia.org/wiki/Flip-flop_(electronics) */
  '74841': {
    name: '74x841',
    simpleName: '10 bit D-FF (TRI)',
    description: '10 bit D-type flip-flop with three-state outputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74als841.pdf',
    tags: ['flip-flop', 'D-type', '10 bit', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x841 is a 10 bit edge-triggered D flip-flop bank with tri-state outputs. It captures ten input bits on clock edges and drives them onto a shared bus when enabled.',
    guidePinDescriptions: {
      'OEn': 'Output enable (active LOW).',
      'D0':  'Data input bit 0.',
      'D1':  'Data input bit 1.',
      'D2':  'Data input bit 2.',
      'D3':  'Data input bit 3.',
      'D4':  'Data input bit 4.',
      'D5':  'Data input bit 5.',
      'D6':  'Data input bit 6.',
      'D7':  'Data input bit 7.',
      'D8':  'Data input bit 8.',
      'D9':  'Data input bit 9.',
      'GND': 'Ground reference (pin 12).',
      'CLK': 'Clock input.',
      'Q9':  'Registered output bit 9.',
      'Q8':  'Registered output bit 8.',
      'Q7':  'Registered output bit 7.',
      'Q6':  'Registered output bit 6.',
      'Q5':  'Registered output bit 5.',
      'Q4':  'Registered output bit 4.',
      'Q3':  'Registered output bit 3.',
      'Q2':  'Registered output bit 2.',
      'Q1':  'Registered output bit 1.',
      'Q0':  'Registered output bit 0.',
      'VCC': 'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: '10 bit Registered Bus Paths',
        paragraphs: [
          'A 10 bit register is commonly used for byte+parity or mixed control/data bundles where an extra two bits are needed beyond 8 bit byte width.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'OEn', type: 'input'  },
      { pin:  2, name: 'D0',  type: 'input'  },
      { pin:  3, name: 'D1',  type: 'input'  },
      { pin:  4, name: 'D2',  type: 'input'  },
      { pin:  5, name: 'D3',  type: 'input'  },
      { pin:  6, name: 'D4',  type: 'input'  },
      { pin:  7, name: 'D5',  type: 'input'  },
      { pin:  8, name: 'D6',  type: 'input'  },
      { pin:  9, name: 'D7',  type: 'input'  },
      { pin: 10, name: 'D8',  type: 'input'  },
      { pin: 11, name: 'D9',  type: 'input'  },
      { pin: 12, name: 'GND', type: 'power'  },
      { pin: 13, name: 'CLK', type: 'input'  },
      { pin: 14, name: 'Q9',  type: 'output' },
      { pin: 15, name: 'Q8',  type: 'output' },
      { pin: 16, name: 'Q7',  type: 'output' },
      { pin: 17, name: 'Q6',  type: 'output' },
      { pin: 18, name: 'Q5',  type: 'output' },
      { pin: 19, name: 'Q4',  type: 'output' },
      { pin: 20, name: 'Q3',  type: 'output' },
      { pin: 21, name: 'Q2',  type: 'output' },
      { pin: 22, name: 'Q1',  type: 'output' },
      { pin: 23, name: 'Q0',  type: 'output' },
      { pin: 24, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','CLK','D0','D1','D2','D3','D4','D5','D6','D7','D8','D9'], outputs: ['Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7','Q8','Q9'] },
    ],
  },

  // ── 74842: 10 bit D-type flip-flop, inverting inputs, TRI (24-pin) ───────
  /* Primary source: Texas Instruments, 74842 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74als842.pdf
     https://en.wikipedia.org/wiki/Flip-flop_(electronics) */
  '74842': {
    name: '74x842',
    simpleName: '10 bit D-FF, Inv In (TRI)',
    description: '10 bit D-type flip-flop with inverting inputs and three-state outputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74als842.pdf',
    tags: ['flip-flop', 'D-type', '10 bit', 'inverting', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x842 is the inverting/polarity variant of the 74x841 10 bit D-FF. It offers the same bus-register function while matching active LOW logic conventions in surrounding circuitry.',
    guidePinDescriptions: {
      'OEn': 'Output enable (active LOW).',
      'D0':  'Data input bit 0.',
      'D1':  'Data input bit 1.',
      'D2':  'Data input bit 2.',
      'D3':  'Data input bit 3.',
      'D4':  'Data input bit 4.',
      'D5':  'Data input bit 5.',
      'D6':  'Data input bit 6.',
      'D7':  'Data input bit 7.',
      'D8':  'Data input bit 8.',
      'D9':  'Data input bit 9.',
      'GND': 'Ground reference (pin 12).',
      'CLK': 'Clock input.',
      'Q9':  'Registered output bit 9.',
      'Q8':  'Registered output bit 8.',
      'Q7':  'Registered output bit 7.',
      'Q6':  'Registered output bit 6.',
      'Q5':  'Registered output bit 5.',
      'Q4':  'Registered output bit 4.',
      'Q3':  'Registered output bit 3.',
      'Q2':  'Registered output bit 2.',
      'Q1':  'Registered output bit 1.',
      'Q0':  'Registered output bit 0.',
      'VCC': 'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: 'Polarity-Matched Register Variants',
        paragraphs: [
          'Choosing an inverting variant can eliminate separate inverter chips and reduce skew on control-critical paths.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'OEn', type: 'input'  },
      { pin:  2, name: 'D0',  type: 'input'  },
      { pin:  3, name: 'D1',  type: 'input'  },
      { pin:  4, name: 'D2',  type: 'input'  },
      { pin:  5, name: 'D3',  type: 'input'  },
      { pin:  6, name: 'D4',  type: 'input'  },
      { pin:  7, name: 'D5',  type: 'input'  },
      { pin:  8, name: 'D6',  type: 'input'  },
      { pin:  9, name: 'D7',  type: 'input'  },
      { pin: 10, name: 'D8',  type: 'input'  },
      { pin: 11, name: 'D9',  type: 'input'  },
      { pin: 12, name: 'GND', type: 'power'  },
      { pin: 13, name: 'CLK', type: 'input'  },
      { pin: 14, name: 'Q9',  type: 'output' },
      { pin: 15, name: 'Q8',  type: 'output' },
      { pin: 16, name: 'Q7',  type: 'output' },
      { pin: 17, name: 'Q6',  type: 'output' },
      { pin: 18, name: 'Q5',  type: 'output' },
      { pin: 19, name: 'Q4',  type: 'output' },
      { pin: 20, name: 'Q3',  type: 'output' },
      { pin: 21, name: 'Q2',  type: 'output' },
      { pin: 22, name: 'Q1',  type: 'output' },
      { pin: 23, name: 'Q0',  type: 'output' },
      { pin: 24, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','CLK','D0','D1','D2','D3','D4','D5','D6','D7','D8','D9'], outputs: ['Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7','Q8','Q9'] },
    ],
  },

  // ── 74843: 9 bit D flip-flops, CLRn+SET, TRI (24-pin) ───────────────────
  /* Primary source: Texas Instruments, 74843 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74als843.pdf
     https://en.wikipedia.org/wiki/Flip-flop_(electronics) */
  '74843': {
    name: '74x843',
    simpleName: '9 bit D-FF w/ CLRn+SET (TRI)',
    description: '9 bit D flip-flops with clear and set inputs, three-state outputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74als843.pdf',
    tags: ['flip-flop', 'D-type', '9 bit', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x843 is a 9 bit D-FF bank with asynchronous clear and set controls plus tri-state outputs. It supports fast initialization and forced states, making it useful in state machines and bus control blocks.',
    guidePinDescriptions: {
      'OEn':  'Output enable (active LOW).',
      'CLRn': 'Asynchronous clear input (active LOW).',
      'SET':  'Asynchronous set input.',
      'D0':   'Data input bit 0.',
      'D1':   'Data input bit 1.',
      'D2':   'Data input bit 2.',
      'D3':   'Data input bit 3.',
      'D4':   'Data input bit 4.',
      'D5':   'Data input bit 5.',
      'D6':   'Data input bit 6.',
      'D7':   'Data input bit 7.',
      'GND':  'Ground reference (pin 12).',
      'CLK':  'Clock input.',
      'D8':   'Data input bit 8.',
      'Q8':   'Registered output bit 8.',
      'Q7':   'Registered output bit 7.',
      'Q6':   'Registered output bit 6.',
      'Q5':   'Registered output bit 5.',
      'Q4':   'Registered output bit 4.',
      'Q3':   'Registered output bit 3.',
      'Q2':   'Registered output bit 2.',
      'Q1':   'Registered output bit 1.',
      'Q0':   'Registered output bit 0.',
      'VCC':  'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: 'Asynchronous Set/Clear Controls',
        paragraphs: [
          'SET and CLRn allow immediate forcing of known states independent of clock timing. This is valuable for startup initialization and fault recovery.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'OEn', type: 'input'  },
      { pin:  2, name: 'CLRn',type: 'input'  },
      { pin:  3, name: 'SET', type: 'input'  },
      { pin:  4, name: 'D0',  type: 'input'  },
      { pin:  5, name: 'D1',  type: 'input'  },
      { pin:  6, name: 'D2',  type: 'input'  },
      { pin:  7, name: 'D3',  type: 'input'  },
      { pin:  8, name: 'D4',  type: 'input'  },
      { pin:  9, name: 'D5',  type: 'input'  },
      { pin: 10, name: 'D6',  type: 'input'  },
      { pin: 11, name: 'D7',  type: 'input'  },
      { pin: 12, name: 'GND', type: 'power'  },
      { pin: 13, name: 'CLK', type: 'input'  },
      { pin: 14, name: 'D8',  type: 'input'  },
      { pin: 15, name: 'Q8',  type: 'output' },
      { pin: 16, name: 'Q7',  type: 'output' },
      { pin: 17, name: 'Q6',  type: 'output' },
      { pin: 18, name: 'Q5',  type: 'output' },
      { pin: 19, name: 'Q4',  type: 'output' },
      { pin: 20, name: 'Q3',  type: 'output' },
      { pin: 21, name: 'Q2',  type: 'output' },
      { pin: 22, name: 'Q1',  type: 'output' },
      { pin: 23, name: 'Q0',  type: 'output' },
      { pin: 24, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','CLRn','SET','CLK','D0','D1','D2','D3','D4','D5','D6','D7','D8'], outputs: ['Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7','Q8'] },
    ],
  },

  // ── 74844: 9 bit D flip-flops, CLRn+SET, inv inputs, TRI (24-pin) ────────
  /* Primary source: Texas Instruments, 74844 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74als844.pdf
     https://en.wikipedia.org/wiki/Flip-flop_(electronics) */
  '74844': {
    name: '74x844',
    simpleName: '9 bit D-FF w/ CLRn+SET, Inv In (TRI)',
    description: '9 bit D flip-flops with clear and set inputs, inverting inputs, three-state outputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74als844.pdf',
    tags: ['flip-flop', 'D-type', '9 bit', 'inverting', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x844 is the inverting-input variant of the 9 bit SET/CLR bus D-FF family. It retains tri-state bus functionality while fitting inverted signal conventions.',
    guidePinDescriptions: {
      'OEn':  'Output enable (active LOW).',
      'CLRn': 'Asynchronous clear input (active LOW).',
      'SET':  'Asynchronous set input.',
      'D0':   'Data input bit 0.',
      'D1':   'Data input bit 1.',
      'D2':   'Data input bit 2.',
      'D3':   'Data input bit 3.',
      'D4':   'Data input bit 4.',
      'D5':   'Data input bit 5.',
      'D6':   'Data input bit 6.',
      'D7':   'Data input bit 7.',
      'GND':  'Ground reference (pin 12).',
      'CLK':  'Clock input.',
      'D8':   'Data input bit 8.',
      'Q8':   'Registered output bit 8.',
      'Q7':   'Registered output bit 7.',
      'Q6':   'Registered output bit 6.',
      'Q5':   'Registered output bit 5.',
      'Q4':   'Registered output bit 4.',
      'Q3':   'Registered output bit 3.',
      'Q2':   'Registered output bit 2.',
      'Q1':   'Registered output bit 1.',
      'Q0':   'Registered output bit 0.',
      'VCC':  'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: '74x843 vs 74x844',
        paragraphs: [
          'Functionally the same control model, but different polarity conventions. Designers choose based on whether surrounding logic is active HIGH or active LOW.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'OEn', type: 'input'  },
      { pin:  2, name: 'CLRn',type: 'input'  },
      { pin:  3, name: 'SET', type: 'input'  },
      { pin:  4, name: 'D0',  type: 'input'  },
      { pin:  5, name: 'D1',  type: 'input'  },
      { pin:  6, name: 'D2',  type: 'input'  },
      { pin:  7, name: 'D3',  type: 'input'  },
      { pin:  8, name: 'D4',  type: 'input'  },
      { pin:  9, name: 'D5',  type: 'input'  },
      { pin: 10, name: 'D6',  type: 'input'  },
      { pin: 11, name: 'D7',  type: 'input'  },
      { pin: 12, name: 'GND', type: 'power'  },
      { pin: 13, name: 'CLK', type: 'input'  },
      { pin: 14, name: 'D8',  type: 'input'  },
      { pin: 15, name: 'Q8',  type: 'output' },
      { pin: 16, name: 'Q7',  type: 'output' },
      { pin: 17, name: 'Q6',  type: 'output' },
      { pin: 18, name: 'Q5',  type: 'output' },
      { pin: 19, name: 'Q4',  type: 'output' },
      { pin: 20, name: 'Q3',  type: 'output' },
      { pin: 21, name: 'Q2',  type: 'output' },
      { pin: 22, name: 'Q1',  type: 'output' },
      { pin: 23, name: 'Q0',  type: 'output' },
      { pin: 24, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','CLRn','SET','CLK','D0','D1','D2','D3','D4','D5','D6','D7','D8'], outputs: ['Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7','Q8'] },
    ],
  },

  // ── 74845: 8 bit D flip-flops, CLRn+SET, TRI (24-pin) ───────────────────
  /* Primary source: Texas Instruments, 74845 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74als845.pdf
     https://en.wikipedia.org/wiki/Flip-flop_(electronics) */
  '74845': {
    name: '74x845',
    simpleName: '8 bit D-FF w/ CLRn+SET (TRI)',
    description: '8 bit D flip-flops with clear and set inputs, three-state outputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74als845.pdf',
    tags: ['flip-flop', 'D-type', '8 bit', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x845 is an 8 bit D-FF bank with asynchronous clear and set controls and tri-state outputs. It is a byte-wide variant for bus registers, command latches, and state staging.',
    guidePinDescriptions: {
      'OEn':  'Output enable (active LOW).',
      'CLRn': 'Asynchronous clear input (active LOW).',
      'SET':  'Asynchronous set input.',
      'D0':   'Data input bit 0.',
      'D1':   'Data input bit 1.',
      'D2':   'Data input bit 2.',
      'D3':   'Data input bit 3.',
      'D4':   'Data input bit 4.',
      'D5':   'Data input bit 5.',
      'D6':   'Data input bit 6.',
      'D7':   'Data input bit 7.',
      'GND':  'Ground reference (pin 12).',
      'CLK':  'Clock input.',
      'NC':   'No connect.',
      'Q7':   'Registered output bit 7.',
      'Q6':   'Registered output bit 6.',
      'Q5':   'Registered output bit 5.',
      'Q4':   'Registered output bit 4.',
      'Q3':   'Registered output bit 3.',
      'Q2':   'Registered output bit 2.',
      'Q1':   'Registered output bit 1.',
      'Q0':   'Registered output bit 0.',
      'VCC':  'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: 'Byte-Wide Set/Clear Registers',
        paragraphs: [
          'Combining byte width with asynchronous set/clear gives quick deterministic startup behavior and flexible bus-state control.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'OEn', type: 'input'  },
      { pin:  2, name: 'CLRn',type: 'input'  },
      { pin:  3, name: 'SET', type: 'input'  },
      { pin:  4, name: 'D0',  type: 'input'  },
      { pin:  5, name: 'D1',  type: 'input'  },
      { pin:  6, name: 'D2',  type: 'input'  },
      { pin:  7, name: 'D3',  type: 'input'  },
      { pin:  8, name: 'D4',  type: 'input'  },
      { pin:  9, name: 'D5',  type: 'input'  },
      { pin: 10, name: 'D6',  type: 'input'  },
      { pin: 11, name: 'D7',  type: 'input'  },
      { pin: 12, name: 'GND', type: 'power'  },
      { pin: 13, name: 'CLK', type: 'input'  },
      { pin: 14, name: 'NC',  type: 'nc'     },
      { pin: 15, name: 'Q7',  type: 'output' },
      { pin: 16, name: 'Q6',  type: 'output' },
      { pin: 17, name: 'Q5',  type: 'output' },
      { pin: 18, name: 'Q4',  type: 'output' },
      { pin: 19, name: 'Q3',  type: 'output' },
      { pin: 20, name: 'Q2',  type: 'output' },
      { pin: 21, name: 'Q1',  type: 'output' },
      { pin: 22, name: 'Q0',  type: 'output' },
      { pin: 23, name: 'NC',  type: 'nc'     },
      { pin: 24, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','CLRn','SET','CLK','D0','D1','D2','D3','D4','D5','D6','D7'], outputs: ['Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7'] },
    ],
  },

  // ── 74846: 8 bit D flip-flops, CLRn+SET, inv inputs, TRI (24-pin) ────────
  /* Primary source: Texas Instruments, 74846 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74als846.pdf
     https://en.wikipedia.org/wiki/Flip-flop_(electronics) */
  '74846': {
    name: '74x846',
    simpleName: '8 bit D-FF w/ CLRn+SET, Inv In (TRI)',
    description: '8 bit D flip-flops with clear and set inputs, inverting inputs, three-state outputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74als846.pdf',
    tags: ['flip-flop', 'D-type', '8 bit', 'inverting', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x846 is the inverting variant of the 74x845 byte-wide SET/CLR D-FF. It is selected when inverted data conventions make routing and decode simpler.',
    guidePinDescriptions: {
      'OEn':  'Output enable (active LOW).',
      'CLRn': 'Asynchronous clear input (active LOW).',
      'SET':  'Asynchronous set input.',
      'D0':   'Data input bit 0.',
      'D1':   'Data input bit 1.',
      'D2':   'Data input bit 2.',
      'D3':   'Data input bit 3.',
      'D4':   'Data input bit 4.',
      'D5':   'Data input bit 5.',
      'D6':   'Data input bit 6.',
      'D7':   'Data input bit 7.',
      'GND':  'Ground reference (pin 12).',
      'CLK':  'Clock input.',
      'NC':   'No connect.',
      'Q7':   'Registered output bit 7.',
      'Q6':   'Registered output bit 6.',
      'Q5':   'Registered output bit 5.',
      'Q4':   'Registered output bit 4.',
      'Q3':   'Registered output bit 3.',
      'Q2':   'Registered output bit 2.',
      'Q1':   'Registered output bit 1.',
      'Q0':   'Registered output bit 0.',
      'VCC':  'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: 'Inverting Byte Register Variant',
        paragraphs: [
          'Inverting variants reduce glue logic in active LOW buses and can help maintain matched propagation paths where inversion is otherwise required.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'OEn', type: 'input'  },
      { pin:  2, name: 'CLRn',type: 'input'  },
      { pin:  3, name: 'SET', type: 'input'  },
      { pin:  4, name: 'D0',  type: 'input'  },
      { pin:  5, name: 'D1',  type: 'input'  },
      { pin:  6, name: 'D2',  type: 'input'  },
      { pin:  7, name: 'D3',  type: 'input'  },
      { pin:  8, name: 'D4',  type: 'input'  },
      { pin:  9, name: 'D5',  type: 'input'  },
      { pin: 10, name: 'D6',  type: 'input'  },
      { pin: 11, name: 'D7',  type: 'input'  },
      { pin: 12, name: 'GND', type: 'power'  },
      { pin: 13, name: 'CLK', type: 'input'  },
      { pin: 14, name: 'NC',  type: 'nc'     },
      { pin: 15, name: 'Q7',  type: 'output' },
      { pin: 16, name: 'Q6',  type: 'output' },
      { pin: 17, name: 'Q5',  type: 'output' },
      { pin: 18, name: 'Q4',  type: 'output' },
      { pin: 19, name: 'Q3',  type: 'output' },
      { pin: 20, name: 'Q2',  type: 'output' },
      { pin: 21, name: 'Q1',  type: 'output' },
      { pin: 22, name: 'Q0',  type: 'output' },
      { pin: 23, name: 'NC',  type: 'nc'     },
      { pin: 24, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','CLRn','SET','CLK','D0','D1','D2','D3','D4','D5','D6','D7'], outputs: ['Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7'] },
    ],
  },

  // ── 74848: 8-to-3 priority encoder (glitch-less), TRI (16-pin) ───────────
  /* Primary source: Texas Instruments, 74848 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls848.pdf
     https://en.wikipedia.org/wiki/Priority_encoder */
  // Same pinout and behavior as 74348 reuses PRIORITY_ENC_8TO3_TRI gate type.
  '74848': {
    name: '74x848',
    simpleName: '8-to-3 Priority Encoder (Glitch-Less, TRI)',
    description: '8-to-3 line priority encoder (glitch-less) with three-state outputs (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls848.pdf',
    tags: ['encoder', 'priority', '8-to-3', 'tri-state'],
    guideOverview: 'The 74x848 is an 8-to-3 priority encoder with active LOW encoded outputs and cascade pins. It chooses the highest-priority active input and reports its binary index on A2n, A1n, and A0n. GS and EO support expansion to wider request sets.',
    guidePinDescriptions: {
      'I4':  'Priority input 4.',
      'I5':  'Priority input 5.',
      'I6':  'Priority input 6.',
      'I7':  'Priority input 7 (highest priority).',
      'EIn': 'Enable input (active LOW).',
      'A2n': 'Encoded output bit 2 (active LOW).',
      'A1n': 'Encoded output bit 1 (active LOW).',
      'GND': 'Ground reference (pin 8).',
      'A0n': 'Encoded output bit 0 (active LOW).',
      'GS':  'Group-select status output.',
      'EO':  'Enable-output for cascading priority stages.',
      'I3':  'Priority input 3.',
      'I2':  'Priority input 2.',
      'I1':  'Priority input 1.',
      'I0':  'Priority input 0 (lowest priority).',
      'VCC': 'Positive supply (+5 V, pin 16).',
    },
    guideSections: [
      {
        title: 'Priority Encoding and Cascading',
        paragraphs: [
          'Priority encoders resolve simultaneous requests by rank, not by first-arrival timing. Cascading outputs allow multiple chips to build larger arbitration trees.',
        ],
      },
      {
        title: 'Common Uses',
        list: [
          'Interrupt request ranking',
          'Bus arbitration request compression',
          'Keyboard and event matrix encoding',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'I4',  type: 'input'  },
      { pin:  2, name: 'I5',  type: 'input'  },
      { pin:  3, name: 'I6',  type: 'input'  },
      { pin:  4, name: 'I7',  type: 'input'  },
      { pin:  5, name: 'EIn', type: 'input'  },
      { pin:  6, name: 'A2n', type: 'output' },
      { pin:  7, name: 'A1n', type: 'output' },
      { pin:  8, name: 'GND', type: 'power'  },
      { pin:  9, name: 'A0n', type: 'output' },
      { pin: 10, name: 'GS',  type: 'output' },
      { pin: 11, name: 'EO',  type: 'output' },
      { pin: 12, name: 'I3',  type: 'input'  },
      { pin: 13, name: 'I2',  type: 'input'  },
      { pin: 14, name: 'I1',  type: 'input'  },
      { pin: 15, name: 'I0',  type: 'input'  },
      { pin: 16, name: 'VCC', type: 'power'  },
    ],
    gates: [{
      type: 'PRIORITY_ENC_8TO3_TRI',
      inputs:  ['I0','I1','I2','I3','I4','I5','I6','I7','EIn'],
      outputs: ['A0n','A1n','A2n','GS','EO'],
    }],
  },

};