// Chip definitions block 20
// Chips: 74x304-74x321

export const CHIPS_BLOCK_20 = {

  // ── 74304: Octal ÷2 Clock Driver ──────────────────────────────────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Flip-flop_(electronics) */
  '74304': {
    name: '74x304',
    simpleName: 'Octal ÷2 Clock Driver',
    description: 'Octal divide-by-2 clock driver (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    sequential: true,
    tags: ['clock', 'divider', 'driver', 'octal'],
    guideOverview: 'The 74x304 is an octal divide-by-2 clock driver with 8 independent toggle flip-flop channels. All outputs (Q3-Q8) are non-inverting, unlike the 74x303 where Q7n is inverted. Used for distributing a half-rate clock to up to 8 loads with high drive capability.',
    guidePinDescriptions: {
      'CLK1': 'Clock input for channel 1.',
      'CLK2': 'Clock input for channel 2.',
      'CLK3': 'Clock input for channel 3.',
      'CLK4': 'Clock input for channel 4.',
      'CLK5': 'Clock input for channel 5.',
      'CLK6': 'Clock input for channel 6.',
      'CLK7': 'Clock input for channel 7.',
      'GND':  'Ground reference (pin 8).',
      'CLK8': 'Clock input for channel 8.',
      'Q8':   'Divide-by-2 output for channel 8 (non-inverting).',
      'Q7':   'Divide-by-2 output for channel 7.',
      'Q6':   'Divide-by-2 output for channel 6.',
      'Q5':   'Divide-by-2 output for channel 5.',
      'Q4':   'Divide-by-2 output for channel 4.',
      'Q3':   'Divide-by-2 output for channel 3.',
      'VCC':  'Positive supply (+5 V, pin 16).',
    },
    pinout: [
      { pin:  1, name: 'CLK1', type: 'input' },
      { pin:  2, name: 'CLK2', type: 'input' },
      { pin:  3, name: 'CLK3', type: 'input' },
      { pin:  4, name: 'CLK4', type: 'input' },
      { pin:  5, name: 'CLK5', type: 'input' },
      { pin:  6, name: 'CLK6', type: 'input' },
      { pin:  7, name: 'CLK7', type: 'input' },
      { pin:  8, name: 'GND',  type: 'power' },
      { pin:  9, name: 'CLK8', type: 'input' },
      { pin: 10, name: 'Q8',   type: 'output' },
      { pin: 11, name: 'Q7',   type: 'output' },
      { pin: 12, name: 'Q6',   type: 'output' },
      { pin: 13, name: 'Q5',   type: 'output' },
      { pin: 14, name: 'Q4',   type: 'output' },
      { pin: 15, name: 'Q3',   type: 'output' },
      { pin: 16, name: 'VCC',  type: 'power' },
    ],
    gates: [
      { type: 'CLK_DIV2_OCT', inputs: ['CLK1','CLK2','CLK3','CLK4','CLK5','CLK6','CLK7','CLK8'], outputs: ['Q3','Q4','Q5','Q6','Q7','Q8'] },
    ],
    guideSections: [
      {
        title: 'Octal Half-Rate Clock Driver',
        paragraphs: [
          'Each of the 8 channels divides its clock by 2, delivering a 50% duty-cycle output. All outputs are in phase with each other if driven by the same source. Choose the 74x304 over the 74x303 when consistent polarity across all 8 outputs is required.',
        ],
      },
    ],
  },

  // -- 74305 ─────────────────────
  // ── 74305: Octal ÷2 Clock (4 inv), 16-pin ──────────────────────────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits */
  '74305': {
    name: '74x305',
    simpleName: 'Octal ÷2 Clock (4 inv)',
    description: 'Octal divide-by-2 clock driver with 4 inverted outputs (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    sequential: true,
    tags: ['clock', 'divider', 'driver', 'octal', 'inverting'],
    guideOverview: 'The 74x305 is an octal divide-by-2 clock driver where channels 5-8 produce inverted outputs (Q5n-Q8n) and channels 3-4 produce non-inverted outputs. This mixed polarity is useful when a circuit needs complementary clock phases at different loads from a single chip.',
    guidePinDescriptions: {
      'CLK1': 'Clock input for channel 1.',
      'CLK2': 'Clock input for channel 2.',
      'CLK3': 'Clock input for channel 3.',
      'CLK4': 'Clock input for channel 4.',
      'CLK5': 'Clock input for channel 5.',
      'CLK6': 'Clock input for channel 6.',
      'CLK7': 'Clock input for channel 7.',
      'GND':  'Ground reference (pin 8).',
      'CLK8': 'Clock input for channel 8.',
      'Q8n':  'Divide-by-2 output for channel 8 (inverted).',
      'Q7n':  'Divide-by-2 output for channel 7 (inverted).',
      'Q6n':  'Divide-by-2 output for channel 6 (inverted).',
      'Q5n':  'Divide-by-2 output for channel 5 (inverted).',
      'Q4':   'Divide-by-2 output for channel 4 (non-inverting).',
      'Q3':   'Divide-by-2 output for channel 3 (non-inverting).',
      'VCC':  'Positive supply (+5 V, pin 16).',
    },
    pinout: [
      { pin:  1, name: 'CLK1', type: 'input' },
      { pin:  2, name: 'CLK2', type: 'input' },
      { pin:  3, name: 'CLK3', type: 'input' },
      { pin:  4, name: 'CLK4', type: 'input' },
      { pin:  5, name: 'CLK5', type: 'input' },
      { pin:  6, name: 'CLK6', type: 'input' },
      { pin:  7, name: 'CLK7', type: 'input' },
      { pin:  8, name: 'GND',  type: 'power' },
      { pin:  9, name: 'CLK8', type: 'input' },
      { pin: 10, name: 'Q8n',  type: 'output' },
      { pin: 11, name: 'Q7n',  type: 'output' },
      { pin: 12, name: 'Q6n',  type: 'output' },
      { pin: 13, name: 'Q5n',  type: 'output' },
      { pin: 14, name: 'Q4',   type: 'output' },
      { pin: 15, name: 'Q3',   type: 'output' },
      { pin: 16, name: 'VCC',  type: 'power' },
    ],
    gates: [
      { type: 'CLK_DIV2_OCT_4INV', inputs: ['CLK1','CLK2','CLK3','CLK4','CLK5','CLK6','CLK7','CLK8'], outputs: ['Q3','Q4','Q5n','Q6n','Q7n','Q8n'] },
    ],
    guideSections: [
      {
        title: 'Mixed Polarity Clock Distribution',
        paragraphs: [
          'Channels 3-4 output non-inverted half-rate clocks; channels 5-8 output inverted half-rate clocks. Feed all channels from the same source to get complementary phase clock pairs without external inverters.',
        ],
      },
    ],
  },

  // -- 74306 ────────────────────────
  // ── 74306: 8 bit Bus Xcvr GTL+, 24-pin ─────────────────────────────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Three-state_logic
     Wikipedia: https://en.wikipedia.org/wiki/Open_collector
     Wikipedia: https://en.wikipedia.org/wiki/Bus_transceiver */
  '74306': {
    name: '74x306',
    simpleName: '8 bit Bus Xcvr GTL+',
    description: '8 bit LV-TTL to GTL+ bus transceiver with tri-state and OC outputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    tags: ['transceiver', 'bus', 'GTL+', '8 bit', 'tri-state', 'open-collector'],
    guideOverview: 'The 74x306 is an 8 bit bidirectional bus transceiver that translates between LV-TTL logic levels and GTL+ (Gunning Transceiver Logic Plus) bus levels. DIR controls direction; OEn (active LOW) enables the chip. Used to interface a TTL processor bus with a GTL+ backplane.',
    guidePinDescriptions: {
      'OEn':  'Output Enable (active LOW). When asserted (LOW), drives outputs; when HIGH, disables (tri-states) them.',
      'DIR':  'Direction control. HIGH = A-to-B; LOW = B-to-A.',
      'A1':   'Port A bit 1.',
      'B1':   'Port B bit 1 (GTL+ side).',
      'A2':   'Port A bit 2.',
      'B2':   'Port B bit 2.',
      'A3':   'Port A bit 3.',
      'B3':   'Port B bit 3.',
      'A4':   'Port A bit 4.',
      'B4':   'Port B bit 4.',
      'A5':   'Port A bit 5.',
      'GND':  'Ground reference (pin 12).',
      'B5':   'Port B bit 5.',
      'A6':   'Port A bit 6.',
      'B6':   'Port B bit 6.',
      'A7':   'Port A bit 7.',
      'B7':   'Port B bit 7.',
      'A8':   'Port A bit 8.',
      'B8':   'Port B bit 8.',
      'NC1':  'Not connected.',
      'NC2':  'Not connected.',
      'NC3':  'Not connected.',
      'NC4':  'Not connected.',
      'VCC':  'Positive supply (+5 V, pin 24).',
    },
    pinout: [
      { pin:  1, name: 'OEn',  type: 'input' },
      { pin:  2, name: 'DIR',  type: 'input' },
      { pin:  3, name: 'A1',   type: 'input' },
      { pin:  4, name: 'B1',   type: 'output' },
      { pin:  5, name: 'A2',   type: 'input' },
      { pin:  6, name: 'B2',   type: 'output' },
      { pin:  7, name: 'A3',   type: 'input' },
      { pin:  8, name: 'B3',   type: 'output' },
      { pin:  9, name: 'A4',   type: 'input' },
      { pin: 10, name: 'B4',   type: 'output' },
      { pin: 11, name: 'A5',   type: 'input' },
      { pin: 12, name: 'GND',  type: 'power' },
      { pin: 13, name: 'B5',   type: 'output' },
      { pin: 14, name: 'A6',   type: 'input' },
      { pin: 15, name: 'B6',   type: 'output' },
      { pin: 16, name: 'A7',   type: 'input' },
      { pin: 17, name: 'B7',   type: 'output' },
      { pin: 18, name: 'A8',   type: 'input' },
      { pin: 19, name: 'B8',   type: 'output' },
      { pin: 20, name: 'NC1',  type: 'nc' },
      { pin: 21, name: 'NC2',  type: 'nc' },
      { pin: 22, name: 'NC3',  type: 'nc' },
      { pin: 23, name: 'NC4',  type: 'nc' },
      { pin: 24, name: 'VCC',  type: 'power' },
    ],
    gates: [
      { type: 'BUS_XCVR_8BIT_GTL', inputs: ['OEn','DIR','A1','A2','A3','A4','A5','A6','A7','A8'], outputs: ['B1','B2','B3','B4','B5','B6','B7','B8'] },
    ],
    guideSections: [
      {
        title: 'GTL+ Level Translation',
        paragraphs: [
          'GTL+ is a low-voltage differential-like bus standard used in servers and workstations. Logic HIGH on a GTL+ bus is achieved by a pull up resistor; logic LOW is driven by an open-collector output. The 74x306 bridges 5V TTL logic to this bus, handling level shifting in both directions.',
        ],
      },
    ],
  },

  // -- 74309 ───────────────────────────────────── 
  // ── 74309: RAM 1024×1 (OC), 16-pin ─────────────────────────────────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Open_collector
     Wikipedia: https://en.wikipedia.org/wiki/Random-access_memory */
  '74309': {
    name: '74x309',
    simpleName: 'RAM 1024×1 (OC)',
    description: '1024 bit static RAM organized as 1024 words × 1 bit, open-collector (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    openCollector: true, sequential: true,
    tags: ['ram', 'memory', '1024x1', 'open-collector', 'static'],
    guideOverview: 'The 74x309 is a 1024x1 bit static RAM with a 10 bit address (A0-A9) selecting one of 1024 single-bit cells. CSn and WEn (both active LOW) control access. The open-collector DO output requires a pull up resistor. Twice the depth of the 74x300.',
    guidePinDescriptions: {
      'A0':  'Address bit 0 (LSB).',
      'A1':  'Address bit 1.',
      'A2':  'Address bit 2.',
      'A3':  'Address bit 3.',
      'A4':  'Address bit 4.',
      'A5':  'Address bit 5.',
      'A6':  'Address bit 6.',
      'GND': 'Ground reference (pin 8).',
      'A7':  'Address bit 7.',
      'A8':  'Address bit 8.',
      'A9':  'Address bit 9 (MSB). A0-A9 select 1 of 1024 cells.',
      'WEn': 'Write Enable (active LOW).',
      'CSn': 'Chip Select (active LOW).',
      'DI':  'Data input.',
      'DO':  'Data output (open-collector). Add pull up to VCC.',
      'VCC': 'Positive supply (+5 V, pin 16).',
    },
    pinout: [
      { pin:  1, name: 'A0',  type: 'input' },
      { pin:  2, name: 'A1',  type: 'input' },
      { pin:  3, name: 'A2',  type: 'input' },
      { pin:  4, name: 'A3',  type: 'input' },
      { pin:  5, name: 'A4',  type: 'input' },
      { pin:  6, name: 'A5',  type: 'input' },
      { pin:  7, name: 'A6',  type: 'input' },
      { pin:  8, name: 'GND', type: 'power' },
      { pin:  9, name: 'A7',  type: 'input' },
      { pin: 10, name: 'A8',  type: 'input' },
      { pin: 11, name: 'A9',  type: 'input' },
      { pin: 12, name: 'WEn', type: 'input' },
      { pin: 13, name: 'CSn', type: 'input' },
      { pin: 14, name: 'DI',  type: 'input' },
      { pin: 15, name: 'DO',  type: 'output' },
      { pin: 16, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'RAM_1024X1_OC', inputs: ['A0','A1','A2','A3','A4','A5','A6','A7','A8','A9','WEn','CSn','DI'], outputs: ['DO'] },
    ],
    guideSections: [
      {
        title: '1024x1 Static RAM',
        paragraphs: [
          'Eight 74x309 chips in parallel give 1024 bytes of byte-wide RAM. Chip select lines are tied together or decoded individually for expansion.',
        ],
      },
    ],
  },

  // -- 74310 ────────────
  // ── 74310: Octal Buffer/Inv (ST, 3-state), 20-pin ──────────────────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Three-state_logic */
  '74310': {
    name: '74x310',
    simpleName: 'Octal Buffer/Inv (ST, 3-state)',
    description: 'Octal inverting buffer with Schmitt trigger inputs and tri-state outputs (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    tags: ['buffer', 'inverter', 'schmitt trigger', 'tri-state', 'octal'],
    guideOverview: 'The 74x310 is an octal inverting buffer with Schmitt-trigger inputs and 3-state outputs. Schmitt triggers provide hysteresis, cleaning up noisy or slowly-slewing signals before inversion. Two independent output-enable pins (OE1n, OE2n) control the two groups of four buffers.',
    guidePinDescriptions: {
      'OE1n': 'Output Enable 1 (active LOW) for Y1-Y4.',
      'A1':   'Input 1.',
      'A2':   'Input 2.',
      'A3':   'Input 3.',
      'A4':   'Input 4.',
      'Y4':   'Inverted output for A4.',
      'Y3':   'Inverted output for A3.',
      'Y2':   'Inverted output for A2.',
      'Y1':   'Inverted output for A1.',
      'GND':  'Ground reference (pin 10).',
      'Y5':   'Inverted output for A5.',
      'Y6':   'Inverted output for A6.',
      'Y7':   'Inverted output for A7.',
      'Y8':   'Inverted output for A8.',
      'A5':   'Input 5.',
      'A6':   'Input 6.',
      'A7':   'Input 7.',
      'A8':   'Input 8.',
      'OE2n': 'Output Enable 2 (active LOW) for Y5-Y8.',
      'VCC':  'Positive supply (+5 V, pin 20).',
    },
    pinout: [
      { pin:  1, name: 'OE1n', type: 'input' },
      { pin:  2, name: 'A1',   type: 'input' },
      { pin:  3, name: 'A2',   type: 'input' },
      { pin:  4, name: 'A3',   type: 'input' },
      { pin:  5, name: 'A4',   type: 'input' },
      { pin:  6, name: 'Y4',   type: 'output' },
      { pin:  7, name: 'Y3',   type: 'output' },
      { pin:  8, name: 'Y2',   type: 'output' },
      { pin:  9, name: 'Y1',   type: 'output' },
      { pin: 10, name: 'GND',  type: 'power' },
      { pin: 11, name: 'Y5',   type: 'output' },
      { pin: 12, name: 'Y6',   type: 'output' },
      { pin: 13, name: 'Y7',   type: 'output' },
      { pin: 14, name: 'Y8',   type: 'output' },
      { pin: 15, name: 'A5',   type: 'input' },
      { pin: 16, name: 'A6',   type: 'input' },
      { pin: 17, name: 'A7',   type: 'input' },
      { pin: 18, name: 'A8',   type: 'input' },
      { pin: 19, name: 'OE2n', type: 'input' },
      { pin: 20, name: 'VCC',  type: 'power' },
    ],
    gates: [
      { type: 'BUFFER_OCT_INV_ST_TRI', inputs: ['A1','A2','A3','A4','A5','A6','A7','A8','OE1n','OE2n'], outputs: ['Y1','Y2','Y3','Y4','Y5','Y6','Y7','Y8'] },
    ],
    guideSections: [
      {
        title: 'Schmitt-Trigger Inputs',
        paragraphs: [
          'Schmitt-trigger inputs add hysteresis: the input threshold for switching HIGH is higher than for switching LOW. This prevents oscillation on slowly-changing inputs and rejects glitches. Useful at bus interfaces, long cable receivers, or after RC filter stages.',
        ],
      },
    ],
  },

  // -- 74311 ──────────────────────
  // ── 74311: RAM 16×9 Latch (OC), 20-pin ─────────────────────────────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Flip-flop_(electronics)
     Wikipedia: https://en.wikipedia.org/wiki/Open_collector
     Wikipedia: https://en.wikipedia.org/wiki/Random-access_memory */
  '74311': {
    name: '74x311',
    simpleName: 'RAM 16×9 Latch (OC)',
    description: '144 bit static RAM (16 words × 9 bits) with output latch, open-collector (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    openCollector: true, sequential: true,
    tags: ['ram', 'memory', '16x9', 'latch', 'open-collector'],
    guideOverview: 'The 74x311 is a 144 bit static RAM (16 words x 9 bits) with an output latch and open-collector output. The LE (Latch Enable) pin holds the Q output stable during address changes, preventing glitches during reads. OEn (active LOW) enables the output.',
    guidePinDescriptions: {
      'A0':  'Address bit 0 (LSB).',
      'A1':  'Address bit 1.',
      'A2':  'Address bit 2.',
      'A3':  'Address bit 3 (MSB). Selects 1 of 16 words.',
      'WEn': 'Write Enable (active LOW). With CSn=LOW writes D0-D8.',
      'CSn': 'Chip Select (active LOW).',
      'OEn': 'Output Enable (active LOW). When HIGH, Q is tri-stated.',
      'LE':  'Latch Enable. When HIGH, output Q tracks the RAM read; when LOW, Q is latched.',
      'D0':  'Data input bit 0.',
      'GND': 'Ground reference (pin 10).',
      'D1':  'Data input bit 1.',
      'D2':  'Data input bit 2.',
      'D3':  'Data input bit 3.',
      'D4':  'Data input bit 4.',
      'D5':  'Data input bit 5.',
      'D6':  'Data input bit 6.',
      'D7':  'Data input bit 7.',
      'D8':  'Data input bit 8.',
      'Q':   'Data output (open-collector, latched).',
      'VCC': 'Positive supply (+5 V, pin 20).',
    },
    pinout: [
      { pin:  1, name: 'A0',   type: 'input' },
      { pin:  2, name: 'A1',   type: 'input' },
      { pin:  3, name: 'A2',   type: 'input' },
      { pin:  4, name: 'A3',   type: 'input' },
      { pin:  5, name: 'WEn',  type: 'input' },
      { pin:  6, name: 'CSn',  type: 'input' },
      { pin:  7, name: 'OEn',  type: 'input' },
      { pin:  8, name: 'LE',   type: 'input' },
      { pin:  9, name: 'D0',   type: 'input' },
      { pin: 10, name: 'GND',  type: 'power' },
      { pin: 11, name: 'D1',   type: 'input' },
      { pin: 12, name: 'D2',   type: 'input' },
      { pin: 13, name: 'D3',   type: 'input' },
      { pin: 14, name: 'D4',   type: 'input' },
      { pin: 15, name: 'D5',   type: 'input' },
      { pin: 16, name: 'D6',   type: 'input' },
      { pin: 17, name: 'D7',   type: 'input' },
      { pin: 18, name: 'D8',   type: 'input' },
      { pin: 19, name: 'Q',    type: 'output' },
      { pin: 20, name: 'VCC',  type: 'power' },
    ],
    gates: [
      { type: 'RAM_16X9_LATCH_OC', inputs: ['A0','A1','A2','A3','WEn','CSn','OEn','LE','D0','D1','D2','D3','D4','D5','D6','D7','D8'], outputs: ['Q'] },
    ],
    guideSections: [
      {
        title: 'Output Latch',
        paragraphs: [
          'The output latch (LE) decouples the output from the RAM read cycle. Assert LE=HIGH to read, then pull LE=LOW to hold Q stable. This allows changing the address without disturbing the bus during a slow read cycle.',
        ],
      },
    ],
  },

  // -- 74312 ────────────────────────────────────────
  // ── 74312: RAM 16×9 (OC), 20-pin ───────────────────────────────────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Flip-flop_(electronics)
     Wikipedia: https://en.wikipedia.org/wiki/Open_collector
     Wikipedia: https://en.wikipedia.org/wiki/Random-access_memory */
  '74312': {
    name: '74x312',
    simpleName: 'RAM 16×9 (OC)',
    description: '144 bit static RAM organized as 16 words × 9 bits, open-collector (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    openCollector: true, sequential: true,
    tags: ['ram', 'memory', '16x9', 'open-collector'],
    guideOverview: 'The 74x312 is a 144 bit static RAM organized as 16 words x 9 bits with an open-collector output. Unlike the 74x311 it has no output latch. A0-A3 address 16 nine-bit words. OEn (active LOW) enables the Q output.',
    guidePinDescriptions: {
      'A0':  'Address bit 0 (LSB).',
      'A1':  'Address bit 1.',
      'A2':  'Address bit 2.',
      'A3':  'Address bit 3 (MSB).',
      'WEn': 'Write Enable (active LOW).',
      'CSn': 'Chip Select (active LOW).',
      'OEn': 'Output Enable (active LOW). When HIGH, Q is tri-stated.',
      'D0':  'Data input bit 0.',
      'D1':  'Data input bit 1.',
      'GND': 'Ground reference (pin 10).',
      'D2':  'Data input bit 2.',
      'D3':  'Data input bit 3.',
      'D4':  'Data input bit 4.',
      'D5':  'Data input bit 5.',
      'D6':  'Data input bit 6.',
      'D7':  'Data input bit 7.',
      'D8':  'Data input bit 8.',
      'Q':   'Data output (open-collector).',
      'NC1': 'Not connected.',
      'VCC': 'Positive supply (+5 V, pin 20).',
    },
    pinout: [
      { pin:  1, name: 'A0',  type: 'input' },
      { pin:  2, name: 'A1',  type: 'input' },
      { pin:  3, name: 'A2',  type: 'input' },
      { pin:  4, name: 'A3',  type: 'input' },
      { pin:  5, name: 'WEn', type: 'input' },
      { pin:  6, name: 'CSn', type: 'input' },
      { pin:  7, name: 'OEn', type: 'input' },
      { pin:  8, name: 'D0',  type: 'input' },
      { pin:  9, name: 'D1',  type: 'input' },
      { pin: 10, name: 'GND', type: 'power' },
      { pin: 11, name: 'D2',  type: 'input' },
      { pin: 12, name: 'D3',  type: 'input' },
      { pin: 13, name: 'D4',  type: 'input' },
      { pin: 14, name: 'D5',  type: 'input' },
      { pin: 15, name: 'D6',  type: 'input' },
      { pin: 16, name: 'D7',  type: 'input' },
      { pin: 17, name: 'D8',  type: 'input' },
      { pin: 18, name: 'Q',   type: 'output' },
      { pin: 19, name: 'NC1', type: 'nc' },
      { pin: 20, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'RAM_16X9_OC', inputs: ['A0','A1','A2','A3','WEn','CSn','OEn','D0','D1','D2','D3','D4','D5','D6','D7','D8'], outputs: ['Q'] },
    ],
    guideSections: [
      {
        title: '16x9 RAM',
        paragraphs: [
          'Sixteen 9 bit words; useful for storing 8 bit data plus a parity bit per word. Pair with the 74x311 if you need a latched output for bus driving.',
        ],
      },
    ],
  },

  // -- 74313 ───────────────────────────────────────
  // ── 74313: RAM 16×12 (OC), 20-pin ──────────────────────────────────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Open_collector
     Wikipedia: https://en.wikipedia.org/wiki/Random-access_memory */
  '74313': {
    name: '74x313',
    simpleName: 'RAM 16×12 (OC)',
    description: '192 bit static RAM organized as 16 words × 12 bits, open-collector (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    openCollector: true, sequential: true,
    tags: ['ram', 'memory', '16x12', 'open-collector'],
    guideOverview: 'The 74x313 is a 192 bit static RAM organized as 16 words x 12 bits with open-collector outputs. A0-A3 address 16 words of 12 bits each. CSn and WEn control access; OEn enables outputs. Suitable for wider lookup tables or microcode stores in TTL-only designs.',
    guidePinDescriptions: {
      'A0':  'Address bit 0.',
      'A1':  'Address bit 1.',
      'A2':  'Address bit 2.',
      'A3':  'Address bit 3.',
      'WEn': 'Write Enable (active LOW).',
      'CSn': 'Chip Select (active LOW).',
      'OEn': 'Output Enable (active LOW).',
      'D0':  'Data input bit 0.',
      'D1':  'Data input bit 1.',
      'GND': 'Ground reference (pin 10).',
      'D2':  'Data input bit 2.',
      'D3':  'Data input bit 3.',
      'D4':  'Data input bit 4.',
      'D5':  'Data input bit 5.',
      'D6':  'Data input bit 6.',
      'D7':  'Data input bit 7.',
      'D8':  'Data input bit 8.',
      'D9':  'Data input bit 9.',
      'D10': 'Data input bit 10.',
      'VCC': 'Positive supply (+5 V, pin 20).',
    },
    pinout: [
      { pin:  1, name: 'A0',   type: 'input' },
      { pin:  2, name: 'A1',   type: 'input' },
      { pin:  3, name: 'A2',   type: 'input' },
      { pin:  4, name: 'A3',   type: 'input' },
      { pin:  5, name: 'WEn',  type: 'input' },
      { pin:  6, name: 'CSn',  type: 'input' },
      { pin:  7, name: 'OEn',  type: 'input' },
      { pin:  8, name: 'D0',   type: 'input' },
      { pin:  9, name: 'D1',   type: 'input' },
      { pin: 10, name: 'GND',  type: 'power' },
      { pin: 11, name: 'D2',   type: 'input' },
      { pin: 12, name: 'D3',   type: 'input' },
      { pin: 13, name: 'D4',   type: 'input' },
      { pin: 14, name: 'D5',   type: 'input' },
      { pin: 15, name: 'D6',   type: 'input' },
      { pin: 16, name: 'D7',   type: 'input' },
      { pin: 17, name: 'D8',   type: 'input' },
      { pin: 18, name: 'D9',   type: 'input' },
      { pin: 19, name: 'D10',  type: 'input' },
      { pin: 20, name: 'VCC',  type: 'power' },
    ],
    gates: [
      { type: 'RAM_16X12_OC', inputs: ['A0','A1','A2','A3','WEn','CSn','OEn','D0','D1','D2','D3','D4','D5','D6','D7','D8','D9','D10'], outputs: [] },
    ],
    guideSections: [
      {
        title: '16x12 RAM',
        paragraphs: [
          'Twelve data bits per address allow storing 12 bit values (e.g., 12 bit microinstruction words) at each of 16 locations. Output is open-collector requiring pull up resistors.',
        ],
      },
    ],
  },

  // -- 74314 ─────────────────────────────────────
  // ── 74314: RAM 1024×1 (OC) v2, 16-pin ──────────────────────────────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Open_collector
     Wikipedia: https://en.wikipedia.org/wiki/Random-access_memory */
  '74314': {
    name: '74x314',
    simpleName: 'RAM 1024×1 (OC) v2',
    description: '1024 bit static RAM organized as 1024 words × 1 bit, open-collector (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    openCollector: true, sequential: true,
    tags: ['ram', 'memory', '1024x1', 'open-collector'],
    guideOverview: 'The 74x314 is a variant of the 74x309: 1024x1 bit static RAM with open-collector output. Functionally identical (A0-A9 address, WEn/CSn control, DI/DO data pins); the variant number reflects a different process or manufacturer.',
    guidePinDescriptions: {
      'A0':  'Address bit 0.',
      'A1':  'Address bit 1.',
      'A2':  'Address bit 2.',
      'A3':  'Address bit 3.',
      'A4':  'Address bit 4.',
      'A5':  'Address bit 5.',
      'A6':  'Address bit 6.',
      'GND': 'Ground reference (pin 8).',
      'A7':  'Address bit 7.',
      'A8':  'Address bit 8.',
      'A9':  'Address bit 9.',
      'WEn': 'Write Enable (active LOW).',
      'CSn': 'Chip Select (active LOW).',
      'DI':  'Data input.',
      'DO':  'Data output (open-collector).',
      'VCC': 'Positive supply (+5 V, pin 16).',
    },
    pinout: [
      { pin:  1, name: 'A0',  type: 'input' },
      { pin:  2, name: 'A1',  type: 'input' },
      { pin:  3, name: 'A2',  type: 'input' },
      { pin:  4, name: 'A3',  type: 'input' },
      { pin:  5, name: 'A4',  type: 'input' },
      { pin:  6, name: 'A5',  type: 'input' },
      { pin:  7, name: 'A6',  type: 'input' },
      { pin:  8, name: 'GND', type: 'power' },
      { pin:  9, name: 'A7',  type: 'input' },
      { pin: 10, name: 'A8',  type: 'input' },
      { pin: 11, name: 'A9',  type: 'input' },
      { pin: 12, name: 'WEn', type: 'input' },
      { pin: 13, name: 'CSn', type: 'input' },
      { pin: 14, name: 'DI',  type: 'input' },
      { pin: 15, name: 'DO',  type: 'output' },
      { pin: 16, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'RAM_1024X1_OC', inputs: ['A0','A1','A2','A3','A4','A5','A6','A7','A8','A9','WEn','CSn','DI'], outputs: ['DO'] },
    ],
    guideSections: [
      {
        title: 'Variant Notes',
        paragraphs: [
          'Same operation as 74x309. Use when your PCB or sourcing requires this part number.',
        ],
      },
    ],
  },

  // -- 74315 ─────────────────────
  // ── 74315: RAM 1024×1 PD (OC), 16-pin ──────────────────────────────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Open_collector
     Wikipedia: https://en.wikipedia.org/wiki/Random-access_memory */
  '74315': {
    name: '74x315',
    simpleName: 'RAM 1024×1 PD (OC)',
    description: '1024 bit static RAM with power-down mode, open-collector (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    openCollector: true, sequential: true,
    tags: ['ram', 'memory', '1024x1', 'open-collector', 'power-down'],
    guideOverview: 'The 74x315 is a 1024x1 bit static RAM with a power-down mode for reduced standby current. When CSn is deasserted (HIGH) the chip enters low power standby. Otherwise identical to the 74x309 in pinout and operation.',
    guidePinDescriptions: {
      'A0':  'Address bit 0.',
      'A1':  'Address bit 1.',
      'A2':  'Address bit 2.',
      'A3':  'Address bit 3.',
      'A4':  'Address bit 4.',
      'A5':  'Address bit 5.',
      'A6':  'Address bit 6.',
      'GND': 'Ground reference (pin 8).',
      'A7':  'Address bit 7.',
      'A8':  'Address bit 8.',
      'A9':  'Address bit 9.',
      'WEn': 'Write Enable (active LOW).',
      'CSn': 'Chip Select (active LOW). When HIGH, chip enters power-down standby.',
      'DI':  'Data input.',
      'DO':  'Data output (open-collector).',
      'VCC': 'Positive supply (+5 V, pin 16).',
    },
    pinout: [
      { pin:  1, name: 'A0',  type: 'input' },
      { pin:  2, name: 'A1',  type: 'input' },
      { pin:  3, name: 'A2',  type: 'input' },
      { pin:  4, name: 'A3',  type: 'input' },
      { pin:  5, name: 'A4',  type: 'input' },
      { pin:  6, name: 'A5',  type: 'input' },
      { pin:  7, name: 'A6',  type: 'input' },
      { pin:  8, name: 'GND', type: 'power' },
      { pin:  9, name: 'A7',  type: 'input' },
      { pin: 10, name: 'A8',  type: 'input' },
      { pin: 11, name: 'A9',  type: 'input' },
      { pin: 12, name: 'WEn', type: 'input' },
      { pin: 13, name: 'CSn', type: 'input' },
      { pin: 14, name: 'DI',  type: 'input' },
      { pin: 15, name: 'DO',  type: 'output' },
      { pin: 16, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'RAM_1024X1_OC', inputs: ['A0','A1','A2','A3','A4','A5','A6','A7','A8','A9','WEn','CSn','DI'], outputs: ['DO'] },
    ],
    guideSections: [
      {
        title: 'Power-Down Mode',
        paragraphs: [
          'When CSn is HIGH the chip reduces its supply current significantly while retaining stored data. Useful in battery-backed designs or multiplexed memory banks where most chips are idle most of the time.',
        ],
      },
    ],
  },

  // -- 74316 ────────────────────────────
  // ── 74316: RAM 64×4 (OC, common I/O), 16-pin ───────────────────────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Open_collector
     Wikipedia: https://en.wikipedia.org/wiki/Random-access_memory */
  '74316': {
    name: '74x316',
    simpleName: 'RAM 64×4 (OC, common I/O)',
    description: '256 bit static RAM (64 words × 4 bits), common I/O, open-collector (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    openCollector: true, sequential: true,
    tags: ['ram', 'memory', '64x4', 'open-collector', 'common I/O'],
    guideOverview: 'The 74x316 is a 256 bit static RAM organized as 64 words x 4 bits with common I/O (bidirectional data pins IO0-IO3) and open-collector outputs. A 6 bit address (A0-A5) selects one of 64 four-bit words. WEn low writes D0-D1 and reads back the updated cell on IO0-IO3.',
    guidePinDescriptions: {
      'A0':  'Address bit 0.',
      'A1':  'Address bit 1.',
      'A2':  'Address bit 2.',
      'A3':  'Address bit 3.',
      'A4':  'Address bit 4.',
      'A5':  'Address bit 5 (MSB). Selects 1 of 64 words.',
      'WEn': 'Write Enable (active LOW).',
      'GND': 'Ground reference (pin 8).',
      'CSn': 'Chip Select (active LOW).',
      'IO0': 'Bidirectional data bit 0 (open-collector).',
      'IO1': 'Bidirectional data bit 1.',
      'IO2': 'Bidirectional data bit 2.',
      'IO3': 'Bidirectional data bit 3.',
      'D0':  'Data input bit 0 (write-only).',
      'D1':  'Data input bit 1.',
      'VCC': 'Positive supply (+5 V, pin 16).',
    },
    pinout: [
      { pin:  1, name: 'A0',  type: 'input' },
      { pin:  2, name: 'A1',  type: 'input' },
      { pin:  3, name: 'A2',  type: 'input' },
      { pin:  4, name: 'A3',  type: 'input' },
      { pin:  5, name: 'A4',  type: 'input' },
      { pin:  6, name: 'A5',  type: 'input' },
      { pin:  7, name: 'WEn', type: 'input' },
      { pin:  8, name: 'GND', type: 'power' },
      { pin:  9, name: 'CSn', type: 'input' },
      { pin: 10, name: 'IO0', type: 'output' },
      { pin: 11, name: 'IO1', type: 'output' },
      { pin: 12, name: 'IO2', type: 'output' },
      { pin: 13, name: 'IO3', type: 'output' },
      { pin: 14, name: 'D0',  type: 'input' },
      { pin: 15, name: 'D1',  type: 'input' },
      { pin: 16, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'RAM_64X4_CMN_OC', inputs: ['A0','A1','A2','A3','A4','A5','WEn','CSn','D0','D1','IO0','IO1','IO2','IO3'], outputs: ['IO0','IO1','IO2','IO3'] },
    ],
    guideSections: [
      {
        title: '64x4 Common I/O RAM',
        paragraphs: [
          'Common I/O (also called shared I/O) means the same pins serve as both data input and output, reducing pin count. Add pull up resistors on IO0-IO3 since these are open-collector. Keep D0/D1 stable only during writes.',
        ],
      },
    ],
  },

  // -- 74317 ────────────────────────────────────────
  // ── 74317: RAM 64×4 (OC), 20-pin ───────────────────────────────────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Open_collector
     Wikipedia: https://en.wikipedia.org/wiki/Random-access_memory */
  '74317': {
    name: '74x317',
    simpleName: 'RAM 64×4 (OC)',
    description: '256 bit static RAM organized as 64 words × 4 bits, open-collector (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    openCollector: true, sequential: true,
    tags: ['ram', 'memory', '64x4', 'open-collector'],
    guideOverview: 'The 74x317 is a 256 bit static RAM organized as 64 words x 4 bits with separate data-in (D0-D3) and data-out (Q0-Q3) ports, plus open-collector outputs. A 6 bit address (A0-A5) selects one of 64 nibbles. WEn and CSn control write/read.',
    guidePinDescriptions: {
      'A0':  'Address bit 0.',
      'A1':  'Address bit 1.',
      'A2':  'Address bit 2.',
      'A3':  'Address bit 3.',
      'A4':  'Address bit 4.',
      'A5':  'Address bit 5 (MSB).',
      'WEn': 'Write Enable (active LOW).',
      'CSn': 'Chip Select (active LOW).',
      'D0':  'Data input bit 0.',
      'GND': 'Ground reference (pin 10).',
      'D1':  'Data input bit 1.',
      'D2':  'Data input bit 2.',
      'D3':  'Data input bit 3.',
      'Q3':  'Data output bit 3 (open-collector).',
      'Q2':  'Data output bit 2.',
      'Q1':  'Data output bit 1.',
      'Q0':  'Data output bit 0.',
      'NC1': 'Not connected.',
      'NC2': 'Not connected.',
      'VCC': 'Positive supply (+5 V, pin 20).',
    },
    pinout: [
      { pin:  1, name: 'A0',  type: 'input' },
      { pin:  2, name: 'A1',  type: 'input' },
      { pin:  3, name: 'A2',  type: 'input' },
      { pin:  4, name: 'A3',  type: 'input' },
      { pin:  5, name: 'A4',  type: 'input' },
      { pin:  6, name: 'A5',  type: 'input' },
      { pin:  7, name: 'WEn', type: 'input' },
      { pin:  8, name: 'CSn', type: 'input' },
      { pin:  9, name: 'D0',  type: 'input' },
      { pin: 10, name: 'GND', type: 'power' },
      { pin: 11, name: 'D1',  type: 'input' },
      { pin: 12, name: 'D2',  type: 'input' },
      { pin: 13, name: 'D3',  type: 'input' },
      { pin: 14, name: 'Q3',  type: 'output' },
      { pin: 15, name: 'Q2',  type: 'output' },
      { pin: 16, name: 'Q1',  type: 'output' },
      { pin: 17, name: 'Q0',  type: 'output' },
      { pin: 18, name: 'NC1', type: 'nc' },
      { pin: 19, name: 'NC2', type: 'nc' },
      { pin: 20, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'RAM_64X4_OC', inputs: ['A0','A1','A2','A3','A4','A5','WEn','CSn','D0','D1','D2','D3'], outputs: ['Q0','Q1','Q2','Q3'] },
    ],
    guideSections: [
      {
        title: '64x4 Separate I/O RAM',
        paragraphs: [
          'Separate data-in and data-out simplifies board layout compared to common-I/O variants. Eight 74x317s in parallel give 512 bytes of byte-wide storage. Add pull up resistors on Q outputs.',
        ],
      },
    ],
  },

  // -- 74318 ────────────────────────────────────────
  // ── 74318: RAM 32×8 (OC), 20-pin ───────────────────────────────────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Open_collector
     Wikipedia: https://en.wikipedia.org/wiki/Random-access_memory */
  '74318': {
    name: '74x318',
    simpleName: 'RAM 32×8 (OC)',
    description: '256 bit static RAM organized as 32 words × 8 bits, open-collector (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    openCollector: true, sequential: true,
    tags: ['ram', 'memory', '32x8', 'open-collector'],
    guideOverview: 'The 74x318 is a 256 bit static RAM organized as 32 words x 8 bits with open-collector outputs. A 5 bit address (A0-A4) selects one of 32 byte-wide locations. WEn and CSn control write/read. D0-D7 are inputs; Q5-Q7 are part of the output (note: full 8 bit output wiring may require additional pins).',
    guidePinDescriptions: {
      'A0':  'Address bit 0.',
      'A1':  'Address bit 1.',
      'A2':  'Address bit 2.',
      'A3':  'Address bit 3.',
      'A4':  'Address bit 4 (MSB). Selects 1 of 32 byte locations.',
      'WEn': 'Write Enable (active LOW).',
      'CSn': 'Chip Select (active LOW).',
      'D0':  'Data input bit 0.',
      'D1':  'Data input bit 1.',
      'GND': 'Ground reference (pin 10).',
      'D2':  'Data input bit 2.',
      'D3':  'Data input bit 3.',
      'D4':  'Data input bit 4.',
      'D5':  'Data input bit 5.',
      'D6':  'Data input bit 6.',
      'D7':  'Data input bit 7.',
      'Q7':  'Data output bit 7 (open-collector).',
      'Q6':  'Data output bit 6.',
      'Q5':  'Data output bit 5.',
      'VCC': 'Positive supply (+5 V, pin 20).',
    },
    pinout: [
      { pin:  1, name: 'A0',  type: 'input' },
      { pin:  2, name: 'A1',  type: 'input' },
      { pin:  3, name: 'A2',  type: 'input' },
      { pin:  4, name: 'A3',  type: 'input' },
      { pin:  5, name: 'A4',  type: 'input' },
      { pin:  6, name: 'WEn', type: 'input' },
      { pin:  7, name: 'CSn', type: 'input' },
      { pin:  8, name: 'D0',  type: 'input' },
      { pin:  9, name: 'D1',  type: 'input' },
      { pin: 10, name: 'GND', type: 'power' },
      { pin: 11, name: 'D2',  type: 'input' },
      { pin: 12, name: 'D3',  type: 'input' },
      { pin: 13, name: 'D4',  type: 'input' },
      { pin: 14, name: 'D5',  type: 'input' },
      { pin: 15, name: 'D6',  type: 'input' },
      { pin: 16, name: 'D7',  type: 'input' },
      { pin: 17, name: 'Q7',  type: 'output' },
      { pin: 18, name: 'Q6',  type: 'output' },
      { pin: 19, name: 'Q5',  type: 'output' },
      { pin: 20, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'RAM_32X8_OC', inputs: ['A0','A1','A2','A3','A4','WEn','CSn','D0','D1','D2','D3','D4','D5','D6','D7'], outputs: ['Q5','Q6','Q7'] },
    ],
    guideSections: [
      {
        title: '32x8 Byte-Wide RAM',
        paragraphs: [
          'Thirty-two byte-wide words; a useful scratchpad for small microcontroller-like applications in TTL. Chain multiple chips on the same address bus with separate CSn lines for larger memories.',
        ],
      },
    ],
  },

  // -- 74319 ─────────────────────────────────────────
  // ── 74319: RAM 16×4 (OC), 16-pin ───────────────────────────────────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Open_collector
     Wikipedia: https://en.wikipedia.org/wiki/Random-access_memory */
  '74319': {
    name: '74x319',
    simpleName: 'RAM 16×4 (OC)',
    description: '64 bit static RAM organized as 16 words × 4 bits, open-collector (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    openCollector: true, sequential: true,
    tags: ['ram', 'memory', '16x4', 'open-collector'],
    guideOverview: 'The 74x319 is a 64 bit static RAM organized as 16 words x 4 bits with open-collector outputs. A0-A3 address 16 nibble locations. CSn and WEn control access. D0-D3 write; Q0-Q3 read back (open-collector, add pull ups).',
    guidePinDescriptions: {
      'A0':  'Address bit 0.',
      'A1':  'Address bit 1.',
      'A2':  'Address bit 2.',
      'A3':  'Address bit 3 (MSB).',
      'CSn': 'Chip Select (active LOW).',
      'WEn': 'Write Enable (active LOW).',
      'D0':  'Data input bit 0.',
      'GND': 'Ground reference (pin 8).',
      'D1':  'Data input bit 1.',
      'D2':  'Data input bit 2.',
      'D3':  'Data input bit 3.',
      'Q3':  'Data output bit 3 (open-collector).',
      'Q2':  'Data output bit 2.',
      'Q1':  'Data output bit 1.',
      'Q0':  'Data output bit 0.',
      'VCC': 'Positive supply (+5 V, pin 16).',
    },
    pinout: [
      { pin:  1, name: 'A0',  type: 'input' },
      { pin:  2, name: 'A1',  type: 'input' },
      { pin:  3, name: 'A2',  type: 'input' },
      { pin:  4, name: 'A3',  type: 'input' },
      { pin:  5, name: 'CSn', type: 'input' },
      { pin:  6, name: 'WEn', type: 'input' },
      { pin:  7, name: 'D0',  type: 'input' },
      { pin:  8, name: 'GND', type: 'power' },
      { pin:  9, name: 'D1',  type: 'input' },
      { pin: 10, name: 'D2',  type: 'input' },
      { pin: 11, name: 'D3',  type: 'input' },
      { pin: 12, name: 'Q3',  type: 'output' },
      { pin: 13, name: 'Q2',  type: 'output' },
      { pin: 14, name: 'Q1',  type: 'output' },
      { pin: 15, name: 'Q0',  type: 'output' },
      { pin: 16, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'RAM_16X4_OC', inputs: ['A0','A1','A2','A3','CSn','WEn','D0','D1','D2','D3'], outputs: ['Q0','Q1','Q2','Q3'] },
    ],
    guideSections: [
      {
        title: '16x4 Static RAM',
        paragraphs: [
          'Compact 64 bit RAM useful for state tables, character LUTs, or small register files in TTL-only designs. Add pull up resistors to each Q pin.',
        ],
      },
    ],
  },

  // -- 74320 ──────────────────────────────────
  // ── 74320: Crystal Osc, 16-pin ─────────────────────────────────────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits */
  '74320': {
    name: '74x320',
    simpleName: 'Crystal Osc',
    description: 'Crystal-controlled oscillator (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    sequential: true,
    tags: ['oscillator', 'crystal', 'clock'],
    guideOverview: 'The 74x320 is a crystal-controlled oscillator that generates a stable clock signal from an external quartz crystal connected to XTAL1/XTAL2. The output frequency is set by the crystal and is highly stable over temperature and time. Used to provide a master clock reference in a digital system.',
    guidePinDescriptions: {
      'XTAL1': 'Crystal input 1 (connect one terminal of the quartz crystal).',
      'XTAL2': 'Crystal input 2 (connect other terminal; may also feed a feedback capacitor to GND).',
      'NC1':   'Not connected.',
      'NC2':   'Not connected.',
      'NC3':   'Not connected.',
      'NC4':   'Not connected.',
      'NC5':   'Not connected.',
      'GND':   'Ground reference (pin 8).',
      'NC6':   'Not connected.',
      'NC7':   'Not connected.',
      'NC8':   'Not connected.',
      'NC9':   'Not connected.',
      'NC10':  'Not connected.',
      'NC11':  'Not connected.',
      'OUT':   'Oscillator output clock at crystal frequency.',
      'VCC':   'Positive supply (+5 V, pin 16).',
    },
    pinout: [
      { pin:  1, name: 'XTAL1', type: 'input' },
      { pin:  2, name: 'XTAL2', type: 'input' },
      { pin:  3, name: 'NC1',   type: 'nc' },
      { pin:  4, name: 'NC2',   type: 'nc' },
      { pin:  5, name: 'NC3',   type: 'nc' },
      { pin:  6, name: 'NC4',   type: 'nc' },
      { pin:  7, name: 'NC5',   type: 'nc' },
      { pin:  8, name: 'GND',   type: 'power' },
      { pin:  9, name: 'NC6',   type: 'nc' },
      { pin: 10, name: 'NC7',   type: 'nc' },
      { pin: 11, name: 'NC8',   type: 'nc' },
      { pin: 12, name: 'NC9',   type: 'nc' },
      { pin: 13, name: 'NC10',  type: 'nc' },
      { pin: 14, name: 'NC11',  type: 'nc' },
      { pin: 15, name: 'OUT',   type: 'output' },
      { pin: 16, name: 'VCC',   type: 'power' },
    ],
    gates: [
      { type: 'CRYSTAL_OSC', inputs: ['XTAL1'], outputs: ['OUT'] },
    ],
    guideSections: [
      {
        title: 'Crystal Oscillator Basics',
        paragraphs: [
          'A quartz crystal has a precise resonant frequency determined by its physical dimensions. The oscillator circuit amplifies the crystal feedback to sustain oscillation, producing a stable square wave at OUT. Stability is typically in the ppm (parts per million) range.',
        ],
        note: 'Add small load capacitors (typically 12-22 pF) from each crystal pin to GND for correct frequency.',
      },
    ],
  },

  // -- 74321 ──────────
  // ── 74321: Crystal Osc (F/2, F/4), 16-pin ──────────────────────────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits */
  '74321': {
    name: '74x321',
    simpleName: 'Crystal Osc (F/2, F/4)',
    description: 'Crystal-controlled oscillator with F/2 and F/4 count-down outputs (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    sequential: true,
    tags: ['oscillator', 'crystal', 'clock', 'divider'],
    guideOverview: 'The 74x321 is a crystal-controlled oscillator with three outputs: the fundamental frequency (OUT), a divided-by-2 output (F2), and a divided-by-4 output (F4). These provide three synchronous clock rates from a single crystal, useful for systems requiring multiple clock domains.',
    guidePinDescriptions: {
      'XTAL1': 'Crystal input 1.',
      'XTAL2': 'Crystal input 2.',
      'NC1':   'Not connected.',
      'NC2':   'Not connected.',
      'NC3':   'Not connected.',
      'NC4':   'Not connected.',
      'NC5':   'Not connected.',
      'GND':   'Ground reference (pin 8).',
      'NC6':   'Not connected.',
      'NC7':   'Not connected.',
      'NC8':   'Not connected.',
      'NC9':   'Not connected.',
      'F4':    'Oscillator frequency divided by 4 output.',
      'F2':    'Oscillator frequency divided by 2 output.',
      'OUT':   'Fundamental oscillator output at crystal frequency.',
      'VCC':   'Positive supply (+5 V, pin 16).',
    },
    pinout: [
      { pin:  1, name: 'XTAL1', type: 'input' },
      { pin:  2, name: 'XTAL2', type: 'input' },
      { pin:  3, name: 'NC1',   type: 'nc' },
      { pin:  4, name: 'NC2',   type: 'nc' },
      { pin:  5, name: 'NC3',   type: 'nc' },
      { pin:  6, name: 'NC4',   type: 'nc' },
      { pin:  7, name: 'NC5',   type: 'nc' },
      { pin:  8, name: 'GND',   type: 'power' },
      { pin:  9, name: 'NC6',   type: 'nc' },
      { pin: 10, name: 'NC7',   type: 'nc' },
      { pin: 11, name: 'NC8',   type: 'nc' },
      { pin: 12, name: 'NC9',   type: 'nc' },
      { pin: 13, name: 'F4',    type: 'output' },
      { pin: 14, name: 'F2',    type: 'output' },
      { pin: 15, name: 'OUT',   type: 'output' },
      { pin: 16, name: 'VCC',   type: 'power' },
    ],
    gates: [
      { type: 'CRYSTAL_OSC_DIV', inputs: ['XTAL1'], outputs: ['OUT','F2','F4'] },
    ],
    guideSections: [
      {
        title: 'Multi-Rate Clock Generation',
        paragraphs: [
          'F2 = OUT / 2 and F4 = OUT / 4, generated by internal toggle flip-flops. All three outputs are synchronous (phase-related). Use OUT for the fastest logic, F2 for a slower pipeline stage, and F4 for timers or slow peripherals.',
        ],
        formulas: [
          'F2 = f_crystal / 2',
          'F4 = f_crystal / 4',
        ],
      },
    ],
  },

};
