// Chip definitions block 39
// Chips: 74758 74759, 74760, 74762 74763, 74777, 74779, 74784, 74786,
//        74793 74798 (skipping 74∅), 74800

export const CHIPS_BLOCK_39 = {

  // ── 74758: Quadruple bus transceivers, inverting, OC (14-pin) ────────────
  /* Primary source: Texas Instruments, 74758 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74as758.pdf
     https://en.wikipedia.org/wiki/Bus_transceiver */
  // 2× bidirectional paths (A↔B) with separate enables. Modeled as stub.
  '74758': {
    name: '74x758',
    simpleName: 'Quad Bus Transceiver (Inv, OC)',
    description: 'Quadruple bus transceivers with inverting open-collector outputs (14-pin)',
    pins: 14, vcc: 14, gnd: 7,
    openCollector: true,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74as758.pdf',
    tags: ['transceiver', 'bus', 'quad', 'inverting', 'open-collector', 'stub'],
    guideOverview: 'The 74x758 is a 4 bit bus transceiver with open-collector, inverting behavior intended for shared bus lines. GAB and GBA control which direction is active, while OC outputs allow wire-OR style connection with pull up resistors. It is useful in glue logic where multiple devices may need to pull a bus LOW safely.',
    guidePinDescriptions: {
      'GAB': 'Enable/control for A-to-B transfer path.',
      'A0':  'Bus A bit 0, bidirectional transceiver node.',
      'A1':  'Bus A bit 1, bidirectional transceiver node.',
      'A2':  'Bus A bit 2, bidirectional transceiver node.',
      'A3':  'Bus A bit 3, bidirectional transceiver node.',
      'GBA': 'Enable/control for B-to-A transfer path.',
      'GND': 'Ground reference (pin 7).',
      'B3':  'Bus B bit 3 output/transceiver node.',
      'B2':  'Bus B bit 2 output/transceiver node.',
      'B1':  'Bus B bit 1 output/transceiver node.',
      'B0':  'Bus B bit 0 output/transceiver node.',
      'NC':  'No connect.',
      'VCC': 'Positive supply (+5 V, pin 14).',
    },
    guideSections: [
      {
        title: 'Open Collector Bus Sharing',
        paragraphs: [
          'Open-collector transceivers can only pull lines LOW and require pull up resistors to return HIGH. This makes contention-safe shared buses possible, because multiple devices can connect to the same line without one forcing HIGH against another forcing LOW.',
        ],
        note: 'Modeled as a generic stub in the simulator.',
      },
    ],
    pinout: [
      { pin:  1, name: 'GAB', type: 'input'  },
      { pin:  2, name: 'A0',  type: 'bidir'  },
      { pin:  3, name: 'A1',  type: 'bidir'  },
      { pin:  4, name: 'A2',  type: 'bidir'  },
      { pin:  5, name: 'A3',  type: 'bidir'  },
      { pin:  6, name: 'GBA', type: 'input'  },
      { pin:  7, name: 'GND', type: 'power'  },
      { pin:  8, name: 'B3',  type: 'output' },
      { pin:  9, name: 'B2',  type: 'output' },
      { pin: 10, name: 'B1',  type: 'output' },
      { pin: 11, name: 'B0',  type: 'output' },
      { pin: 12, name: 'NC',  type: 'nc'     },
      { pin: 13, name: 'NC',  type: 'nc'     },
      { pin: 14, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['GAB','GBA','A0','A1','A2','A3'], outputs: ['B0','B1','B2','B3'] },
    ],
  },

  // ── 74759: Quadruple bus transceivers, non-inverting, OC (14-pin) ─────────
  /* Primary source: Texas Instruments, 74759 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74as759.pdf
     https://en.wikipedia.org/wiki/Bus_transceiver */
  '74759': {
    name: '74x759',
    simpleName: 'Quad Bus Transceiver (Non-Inv, OC)',
    description: 'Quadruple bus transceivers with non-inverting open-collector outputs (14-pin)',
    pins: 14, vcc: 14, gnd: 7,
    openCollector: true,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74as759.pdf',
    tags: ['transceiver', 'bus', 'quad', 'non-inverting', 'open-collector', 'stub'],
    guideOverview: 'The 74x759 is the non-inverting companion to the 74x758. It provides 4 bit bus transceiver functionality with open-collector outputs for wired bus systems, but preserves signal polarity. Use it when shared-bus compatibility is needed without inversion.',
    guidePinDescriptions: {
      'GAB': 'Enable/control for A-to-B transfer path.',
      'A0':  'Bus A bit 0, bidirectional transceiver node.',
      'A1':  'Bus A bit 1, bidirectional transceiver node.',
      'A2':  'Bus A bit 2, bidirectional transceiver node.',
      'A3':  'Bus A bit 3, bidirectional transceiver node.',
      'GBA': 'Enable/control for B-to-A transfer path.',
      'GND': 'Ground reference (pin 7).',
      'B3':  'Bus B bit 3 output/transceiver node.',
      'B2':  'Bus B bit 2 output/transceiver node.',
      'B1':  'Bus B bit 1 output/transceiver node.',
      'B0':  'Bus B bit 0 output/transceiver node.',
      'NC':  'No connect.',
      'VCC': 'Positive supply (+5 V, pin 14).',
    },
    guideSections: [
      {
        title: '74x758 vs 74x759',
        paragraphs: [
          'Both are quad open-collector bus transceivers. The 74x758 inverts data polarity; the 74x759 is non-inverting.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'GAB', type: 'input'  },
      { pin:  2, name: 'A0',  type: 'bidir'  },
      { pin:  3, name: 'A1',  type: 'bidir'  },
      { pin:  4, name: 'A2',  type: 'bidir'  },
      { pin:  5, name: 'A3',  type: 'bidir'  },
      { pin:  6, name: 'GBA', type: 'input'  },
      { pin:  7, name: 'GND', type: 'power'  },
      { pin:  8, name: 'B3',  type: 'output' },
      { pin:  9, name: 'B2',  type: 'output' },
      { pin: 10, name: 'B1',  type: 'output' },
      { pin: 11, name: 'B0',  type: 'output' },
      { pin: 12, name: 'NC',  type: 'nc'     },
      { pin: 13, name: 'NC',  type: 'nc'     },
      { pin: 14, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['GAB','GBA','A0','A1','A2','A3'], outputs: ['B0','B1','B2','B3'] },
    ],
  },

  // ── 74760: Octal buffer/line driver, non-inverting, OC (20-pin) ──────────
  /* Primary source: Texas Instruments, 74760 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74als760.pdf
     https://en.wikipedia.org/wiki/Three-state_logic */
  '74760': {
    name: '74x760',
    simpleName: 'Octal Buffer (Non-Inv, OC)',
    description: 'Octal buffer/line driver with non-inverting open-collector outputs (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    openCollector: true,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74als760.pdf',
    tags: ['buffer', 'driver', 'octal', 'non-inverting', 'open-collector', 'stub'],
    guideOverview: 'The 74x760 is an octal non-inverting buffer/line driver with open-collector outputs. It buffers eight lines and can sink current strongly while relying on pull up resistors for HIGH level. This is commonly used for wired OR buses, level translation, and distributed control lines.',
    guidePinDescriptions: {
      'OEn': 'Output enable control. Disable output stage when not driving the bus.',
      'A0':  'Input bit 0.',
      'A1':  'Input bit 1.',
      'A2':  'Input bit 2.',
      'A3':  'Input bit 3.',
      'A4':  'Input bit 4.',
      'A5':  'Input bit 5.',
      'A6':  'Input bit 6.',
      'A7':  'Input bit 7.',
      'GND': 'Ground reference (pin 10).',
      'Y7':  'Open-collector non-inverting output bit 7.',
      'Y6':  'Open-collector non-inverting output bit 6.',
      'Y5':  'Open-collector non-inverting output bit 5.',
      'Y4':  'Open-collector non-inverting output bit 4.',
      'Y3':  'Open-collector non-inverting output bit 3.',
      'Y2':  'Open-collector non-inverting output bit 2.',
      'Y1':  'Open-collector non-inverting output bit 1.',
      'Y0':  'Open-collector non-inverting output bit 0.',
      'NC':  'No connect.',
      'VCC': 'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'Open Collector Driver Use Cases',
        list: [
          'Wired OR interrupt lines',
          'Mixed-voltage pull up buses',
          'Long backplane control lines',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'OEn', type: 'input'  },
      { pin:  2, name: 'A0',  type: 'input'  },
      { pin:  3, name: 'A1',  type: 'input'  },
      { pin:  4, name: 'A2',  type: 'input'  },
      { pin:  5, name: 'A3',  type: 'input'  },
      { pin:  6, name: 'A4',  type: 'input'  },
      { pin:  7, name: 'A5',  type: 'input'  },
      { pin:  8, name: 'A6',  type: 'input'  },
      { pin:  9, name: 'A7',  type: 'input'  },
      { pin: 10, name: 'GND', type: 'power'  },
      { pin: 11, name: 'Y7',  type: 'output' },
      { pin: 12, name: 'Y6',  type: 'output' },
      { pin: 13, name: 'Y5',  type: 'output' },
      { pin: 14, name: 'Y4',  type: 'output' },
      { pin: 15, name: 'Y3',  type: 'output' },
      { pin: 16, name: 'Y2',  type: 'output' },
      { pin: 17, name: 'Y1',  type: 'output' },
      { pin: 18, name: 'Y0',  type: 'output' },
      { pin: 19, name: 'NC',  type: 'nc'     },
      { pin: 20, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','A0','A1','A2','A3','A4','A5','A6','A7'], outputs: ['Y0','Y1','Y2','Y3','Y4','Y5','Y6','Y7'] },
    ],
  },

  // ── 74762: Octal buffer/line driver, inverting+non-inverting, OC (20-pin) ─
  /* Primary source: Texas Instruments, 74762 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74als762.pdf
     https://en.wikipedia.org/wiki/Three-state_logic */
  '74762': {
    name: '74x762',
    simpleName: 'Octal Buffer (Inv+Non-Inv, OC)',
    description: 'Octal buffer/line driver with inverting and non-inverting open-collector outputs (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    openCollector: true,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74als762.pdf',
    tags: ['buffer', 'driver', 'octal', 'inverting', 'non-inverting', 'open-collector', 'stub'],
    guideOverview: 'The 74x762 provides both true and inverted open-collector outputs from buffered inputs. Having Y and Yn pairs in one package simplifies designs that need both polarities for bus control, decoding, or handshake lines.',
    guidePinDescriptions: {
      'OEn': 'Output enable control for all output channels.',
      'A0':  'Input bit 0.',
      'A1':  'Input bit 1.',
      'A2':  'Input bit 2.',
      'A3':  'Input bit 3.',
      'A4':  'Input bit 4.',
      'A5':  'Input bit 5.',
      'A6':  'Input bit 6.',
      'A7':  'Input bit 7.',
      'GND': 'Ground reference (pin 10).',
      'Y7n': 'Open-collector inverted output for channel 7.',
      'Y7':  'Open-collector non-inverted output for channel 7.',
      'Y6n': 'Open-collector inverted output for channel 6.',
      'Y6':  'Open-collector non-inverted output for channel 6.',
      'Y5n': 'Open-collector inverted output for channel 5.',
      'Y5':  'Open-collector non-inverted output for channel 5.',
      'Y4n': 'Open-collector inverted output for channel 4.',
      'Y4':  'Open-collector non-inverted output for channel 4.',
      'NC':  'No connect.',
      'VCC': 'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'Dual-Polarity Outputs',
        paragraphs: [
          'Generating both Y and Yn in one IC reduces extra inverter stages and timing skew between complementary control lines. This can simplify state machines and bus arbitration glue logic.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'OEn', type: 'input'  },
      { pin:  2, name: 'A0',  type: 'input'  },
      { pin:  3, name: 'A1',  type: 'input'  },
      { pin:  4, name: 'A2',  type: 'input'  },
      { pin:  5, name: 'A3',  type: 'input'  },
      { pin:  6, name: 'A4',  type: 'input'  },
      { pin:  7, name: 'A5',  type: 'input'  },
      { pin:  8, name: 'A6',  type: 'input'  },
      { pin:  9, name: 'A7',  type: 'input'  },
      { pin: 10, name: 'GND', type: 'power'  },
      { pin: 11, name: 'Y7n', type: 'output' },
      { pin: 12, name: 'Y7',  type: 'output' },
      { pin: 13, name: 'Y6n', type: 'output' },
      { pin: 14, name: 'Y6',  type: 'output' },
      { pin: 15, name: 'Y5n', type: 'output' },
      { pin: 16, name: 'Y5',  type: 'output' },
      { pin: 17, name: 'Y4n', type: 'output' },
      { pin: 18, name: 'Y4',  type: 'output' },
      { pin: 19, name: 'NC',  type: 'nc'     },
      { pin: 20, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','A0','A1','A2','A3','A4','A5','A6','A7'], outputs: ['Y4','Y4n','Y5','Y5n','Y6','Y6n','Y7','Y7n'] },
    ],
  },

  // ── 74763: Octal buffer/line driver, inverting, comp. enables, OC (20-pin) ─
  /* Primary source: Texas Instruments, 74763 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74als763.pdf
     https://en.wikipedia.org/wiki/Three-state_logic */
  '74763': {
    name: '74x763',
    simpleName: 'Octal Buffer (Inv, Comp. En, OC)',
    description: 'Octal buffer/line driver with inverting outputs and complementary enable inputs, open-collector (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    openCollector: true,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74als763.pdf',
    tags: ['buffer', 'driver', 'octal', 'inverting', 'open-collector', 'stub'],
    guideOverview: 'The 74x763 is an octal inverting open-collector line driver with complementary-style enables (OE and OEn). It is intended for robust bus and interface drive where one logic path may need active HIGH gating and another active LOW gating.',
    guidePinDescriptions: {
      'OE':  'Primary output-enable control input.',
      'OEn': 'Complementary output-enable control input (active LOW naming).',
      'A0':  'Input bit 0.',
      'A1':  'Input bit 1.',
      'A2':  'Input bit 2.',
      'A3':  'Input bit 3.',
      'A4':  'Input bit 4.',
      'A5':  'Input bit 5.',
      'A6':  'Input bit 6.',
      'GND': 'Ground reference (pin 10).',
      'A7':  'Input bit 7.',
      'Y7':  'Open-collector inverting output bit 7.',
      'Y6':  'Open-collector inverting output bit 6.',
      'Y5':  'Open-collector inverting output bit 5.',
      'Y4':  'Open-collector inverting output bit 4.',
      'Y3':  'Open-collector inverting output bit 3.',
      'Y2':  'Open-collector inverting output bit 2.',
      'Y1':  'Open-collector inverting output bit 1.',
      'Y0':  'Open-collector inverting output bit 0.',
      'VCC': 'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'Enable Polarity Notes',
        paragraphs: [
          'Parts with both OE and OEn often appear in board-level glue logic where control signals already exist in opposite polarities. This avoids extra inverter gates and preserves timing margin.',
        ],
        note: 'Driver behavior is represented as a generic stub in simulation.',
      },
    ],
    pinout: [
      { pin:  1, name: 'OE',  type: 'input'  },
      { pin:  2, name: 'OEn', type: 'input'  },
      { pin:  3, name: 'A0',  type: 'input'  },
      { pin:  4, name: 'A1',  type: 'input'  },
      { pin:  5, name: 'A2',  type: 'input'  },
      { pin:  6, name: 'A3',  type: 'input'  },
      { pin:  7, name: 'A4',  type: 'input'  },
      { pin:  8, name: 'A5',  type: 'input'  },
      { pin:  9, name: 'A6',  type: 'input'  },
      { pin: 10, name: 'GND', type: 'power'  },
      { pin: 11, name: 'A7',  type: 'input'  },
      { pin: 12, name: 'Y7',  type: 'output' },
      { pin: 13, name: 'Y6',  type: 'output' },
      { pin: 14, name: 'Y5',  type: 'output' },
      { pin: 15, name: 'Y4',  type: 'output' },
      { pin: 16, name: 'Y3',  type: 'output' },
      { pin: 17, name: 'Y2',  type: 'output' },
      { pin: 18, name: 'Y1',  type: 'output' },
      { pin: 19, name: 'Y0',  type: 'output' },
      { pin: 20, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OE','OEn','A0','A1','A2','A3','A4','A5','A6','A7'], outputs: ['Y0','Y1','Y2','Y3','Y4','Y5','Y6','Y7'] },
    ],
  },

  // ── 74777: Triple latched transceiver, TRI+OC (20-pin) ───────────────────
  /* Primary source: Texas Instruments, 74777 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74f777.pdf
     https://en.wikipedia.org/wiki/Flip-flop_(electronics) */
  '74777': {
    name: '74x777',
    simpleName: 'Triple Latched Transceiver (TRI+OC)',
    description: 'Triple latched transceiver with three-state and open-collector outputs (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74f777.pdf',
    tags: ['transceiver', 'latch', 'triple', 'tri-state', 'open-collector', 'stub'],
    sequential: true,
    guideOverview: 'The 74x777 is a triple latched transceiver combining direction control, latching, and mixed output style support. It can capture data with CLK/LATCH and then transfer between A and B sides under GAB/GBA control. This is useful when narrow control buses need staged transfer and contention-safe sharing.',
    guidePinDescriptions: {
      'CLK':   'Clock input for registered/latch timing functions.',
      'LATCH': 'Latch control input for holding captured bus state.',
      'GBA':   'Enable/direction control for B-to-A path.',
      'A0':  'A-side transceiver channel 0; bidirectional.',
      'A1':  'A-side transceiver channel 1; bidirectional.',
      'A2':  'A-side transceiver channel 2; bidirectional.',
      'B2':  'B-side transceiver channel 2; bidirectional.',
      'B1':  'B-side transceiver channel 1; bidirectional.',
      'B0':  'B-side transceiver channel 0; bidirectional.',
      'GND':   'Ground reference (pin 10)',
      'GAB':   'Enable/direction control for A-to-B path.',
      'NC':    'No connect.',
      'VCC':   'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'Latched Transceiver Concept',
        paragraphs: [
          'A latched transceiver can decouple bus timing domains: data is sampled at one moment and driven later, avoiding race conditions. This is especially helpful in asynchronous or multi-master bus glue logic.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'CLK',  type: 'input'  },
      { pin:  2, name: 'LATCH',type: 'input'  },
      { pin:  3, name: 'GBA',  type: 'input'  },
      { pin:  4, name: 'A2',   type: 'bidir'  },
      { pin:  5, name: 'B2',   type: 'bidir'  },
      { pin:  6, name: 'A1',   type: 'bidir'  },
      { pin:  7, name: 'B1',   type: 'bidir'  },
      { pin:  8, name: 'A0',   type: 'bidir'  },
      { pin:  9, name: 'B0',   type: 'bidir'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'GAB',  type: 'input'  },
      { pin: 12, name: 'NC',   type: 'nc'     },
      { pin: 13, name: 'NC',   type: 'nc'     },
      { pin: 14, name: 'NC',   type: 'nc'     },
      { pin: 15, name: 'NC',   type: 'nc'     },
      { pin: 16, name: 'NC',   type: 'nc'     },
      { pin: 17, name: 'NC',   type: 'nc'     },
      { pin: 18, name: 'NC',   type: 'nc'     },
      { pin: 19, name: 'NC',   type: 'nc'     },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['CLK','LATCH','GAB','GBA','A0','A1','A2'], outputs: ['B0','B1','B2'] },
    ],
  },

  // ── 74779: 8 bit bidirectional binary counter, TRI (16-pin) ──────────────
  /* Primary source: Texas Instruments, 74779 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/mc74f779.pdf
     https://en.wikipedia.org/wiki/Counter_(digital) */
  '74779': {
    name: '74x779',
    simpleName: '8 bit Bidirectional Counter (TRI)',
    description: '8 bit bidirectional binary counter with three-state outputs (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/mc74f779.pdf',
    tags: ['counter', 'binary', '8 bit', 'bidirectional', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x779 is an 8 bit bidirectional binary counter with tri-state I/O style data pins and terminal-count output. U_Dn sets up/down direction, CEn enables counting, and TC flags terminal count for cascading. It is aimed at programmable counting and shared-bus counter readback designs.',
    guidePinDescriptions: {
      'CLK':  'Clock input; counter updates on active clock edge.',
      'Cn':   'Carry/cascade control input for chaining counters.',
      'D0':   'Counter data bit 0 I/O node.',
      'D1':   'Counter data bit 1 I/O node.',
      'D2':   'Counter data bit 2 I/O node.',
      'D3':   'Counter data bit 3 I/O node.',
      'OEn':  'Output enable (active LOW). Disables bus drive when HIGH.',
      'GND':  'Ground reference (pin 8).',
      'D7':   'Counter data bit 7 I/O node.',
      'D6':   'Counter data bit 6 I/O node.',
      'D5':   'Counter data bit 5 I/O node.',
      'D4':   'Counter data bit 4 I/O node.',
      'TC':   'Terminal count output for cascade and end-of-range detection.',
      'U_Dn': 'Up/Down direction control input.',
      'CEn':  'Count enable control input.',
      'VCC':  'Positive supply (+5 V, pin 16).',
    },
    guideSections: [
      {
        title: 'Bidirectional Counting',
        paragraphs: [
          'Up/down counters are used in position tracking, reversible timers, and queue-depth tracking. A terminal-count output lets multiple counters be chained into wider counters or bounded count windows.',
        ],
        note: 'This device is represented as a stub in the simulator.',
      },
    ],
    pinout: [
      { pin:  1, name: 'CLK',  type: 'input'  },
      { pin:  2, name: 'Cn',   type: 'input'  },
      { pin:  3, name: 'D0',   type: 'bidir'  },
      { pin:  4, name: 'D1',   type: 'bidir'  },
      { pin:  5, name: 'D2',   type: 'bidir'  },
      { pin:  6, name: 'D3',   type: 'bidir'  },
      { pin:  7, name: 'OEn',  type: 'input'  },
      { pin:  8, name: 'GND',  type: 'power'  },
      { pin:  9, name: 'D7',   type: 'bidir'  },
      { pin: 10, name: 'D6',   type: 'bidir'  },
      { pin: 11, name: 'D5',   type: 'bidir'  },
      { pin: 12, name: 'D4',   type: 'bidir'  },
      { pin: 13, name: 'TC',   type: 'output' },
      { pin: 14, name: 'U_Dn', type: 'input'  },
      { pin: 15, name: 'CEn',  type: 'input'  },
      { pin: 16, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['CLK','Cn','OEn','U_Dn','CEn'], outputs: ['D0','D1','D2','D3','D4','D5','D6','D7','TC'] },
    ],
  },

  // ── 74784: 8 bit serial/parallel multiplier w/ adder/subtractor (20-pin) ──
  /* Primary source: Texas Instruments, 74784 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74f784.pdf
     https://en.wikipedia.org/wiki/Adder_(electronics) */
  '74784': {
    name: '74x784',
    simpleName: '8 bit Multiplier/Adder',
    description: '8 bit serial/parallel multiplier with adder/subtractor (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74f784.pdf',
    tags: ['multiplier', 'arithmetic', 'adder', 'subtractor', '8 bit', 'stub'],
    sequential: true,
    guideOverview: 'The 74x784 is a specialized arithmetic device for serial/parallel multiply-style operations with adder/subtractor support. A_Bn selects arithmetic mode while clocked operation produces S0-S7 and overflow status. It is intended for high-speed arithmetic datapaths where discrete gate implementations would be too large.',
    guidePinDescriptions: {
      'CLK':  'Clock input for arithmetic pipeline/register timing.',
      'A_Bn': 'Arithmetic mode control (add/subtract or related function selection).',
      'OVF':  'Overflow output flag.',
      'S7':   'Result output bit 7.',
      'S6':   'Result output bit 6.',
      'S5':   'Result output bit 5.',
      'S4':   'Result output bit 4.',
      'S3':   'Result output bit 3.',
      'S2':   'Result output bit 2.',
      'GND':  'Ground reference (pin 10).',
      'S1':   'Result output bit 1.',
      'S0':   'Result output bit 0.',
      'B7':   'Operand input bit 7.',
      'B6':   'Operand input bit 6.',
      'B5':   'Operand input bit 5.',
      'B4':   'Operand input bit 4.',
      'B3':   'Operand input bit 3.',
      'B2':   'Operand input bit 2.',
      'B1':   'Operand input bit 1.',
      'VCC':  'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'Arithmetic Datapath Role',
        paragraphs: [
          'Before compact microcontrollers were common, arithmetic MSI devices handled multiply/accumulate and add/subtract tasks in controllers and signal-processing boards. Clocked arithmetic blocks made high-speed deterministic pipelines practical in TTL logic.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'CLK',  type: 'input'  },
      { pin:  2, name: 'A_Bn', type: 'input'  },
      { pin:  3, name: 'OVF',  type: 'output' },
      { pin:  4, name: 'S7',   type: 'output' },
      { pin:  5, name: 'S6',   type: 'output' },
      { pin:  6, name: 'S5',   type: 'output' },
      { pin:  7, name: 'S4',   type: 'output' },
      { pin:  8, name: 'S3',   type: 'output' },
      { pin:  9, name: 'S2',   type: 'output' },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'S1',   type: 'output' },
      { pin: 12, name: 'S0',   type: 'output' },
      { pin: 13, name: 'B7',   type: 'input'  },
      { pin: 14, name: 'B6',   type: 'input'  },
      { pin: 15, name: 'B5',   type: 'input'  },
      { pin: 16, name: 'B4',   type: 'input'  },
      { pin: 17, name: 'B3',   type: 'input'  },
      { pin: 18, name: 'B2',   type: 'input'  },
      { pin: 19, name: 'B1',   type: 'input'  },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['CLK','A_Bn','B1','B2','B3','B4','B5','B6','B7'], outputs: ['S0','S1','S2','S3','S4','S5','S6','S7','OVF'] },
    ],
  },

  // ── 74786: 4 input asynchronous bus arbiter (16-pin) ─────────────────────
  /* Primary source: Texas Instruments, 74786 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74f786.pdf */
  '74786': {
    name: '74x786',
    simpleName: '4 Input Bus Arbiter',
    description: '4 input asynchronous bus arbiter (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74f786.pdf',
    tags: ['arbiter', 'bus', '4 input', 'stub'],
    guideOverview: 'The 74x786 is a 4-request asynchronous bus arbiter. It accepts four request inputs and asserts one corresponding active LOW grant output according to internal arbitration rules. RESET initializes arbitration state. This device prevents multiple bus masters from driving a shared bus at once.',
    guidePinDescriptions: {
      'REQ0':  'Request input channel 0.',
      'GNT0n': 'Grant output for channel 0 (active LOW).',
      'REQ1':  'Request input channel 1.',
      'GNT1n': 'Grant output for channel 1 (active LOW).',
      'REQ2':  'Request input channel 2.',
      'GNT2n': 'Grant output for channel 2 (active LOW).',
      'REQ3':  'Request input channel 3.',
      'GND':   'Ground reference (pin 8).',
      'GNT3n': 'Grant output for channel 3 (active LOW).',
      'RESET': 'Reset input for arbiter state machine.',
      'NC':    'No connect.',
      'VCC':   'Positive supply (+5 V, pin 16).',
    },
    guideSections: [
      {
        title: 'Bus Arbitration Basics',
        paragraphs: [
          'An arbiter decides which requester can own a shared bus. Without arbitration, two masters may drive conflicting values and cause contention current or corrupted transfers.',
        ],
      },
      {
        title: 'Common Uses',
        list: [
          'DMA vs CPU bus sharing',
          'Multi-processor peripheral access',
          'Shared memory bus mastering',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'REQ0',  type: 'input'  },
      { pin:  2, name: 'GNT0n', type: 'output' },
      { pin:  3, name: 'REQ1',  type: 'input'  },
      { pin:  4, name: 'GNT1n', type: 'output' },
      { pin:  5, name: 'REQ2',  type: 'input'  },
      { pin:  6, name: 'GNT2n', type: 'output' },
      { pin:  7, name: 'REQ3',  type: 'input'  },
      { pin:  8, name: 'GND',   type: 'power'  },
      { pin:  9, name: 'GNT3n', type: 'output' },
      { pin: 10, name: 'RESET', type: 'input'  },
      { pin: 11, name: 'NC',    type: 'nc'     },
      { pin: 12, name: 'NC',    type: 'nc'     },
      { pin: 13, name: 'NC',    type: 'nc'     },
      { pin: 14, name: 'NC',    type: 'nc'     },
      { pin: 15, name: 'NC',    type: 'nc'     },
      { pin: 16, name: 'VCC',   type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['REQ0','REQ1','REQ2','REQ3','RESET'], outputs: ['GNT0n','GNT1n','GNT2n','GNT3n'] },
    ],
  },

  // ── 74793: 8 bit latch w/ readback (20-pin) ───────────────────────────────
  /* Primary source: Texas Instruments, 74793 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls793.pdf
     https://en.wikipedia.org/wiki/Flip-flop_(electronics) */
  '74793': {
    name: '74x793',
    simpleName: '8 bit Latch w/ Readback',
    description: '8 bit latch with readback capability (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls793.pdf',
    tags: ['latch', '8 bit', 'readback', 'stub'],
    sequential: true,
    guideOverview: 'The 74x793 is an 8 bit transparent latch with readback-oriented bus behavior. LE controls when input data is captured, and OEn controls output driving onto a shared bus. It is useful for holding peripheral state or control words while still allowing the host to read the latched value back.',
    guidePinDescriptions: {
      'OEn': 'Output enable (active LOW). High places outputs in high-impedance state.',
      'LE':  'Latch enable. Active state allows D inputs to update the latched outputs.',
      'D0':  'Data input bit 0.',
      'D1':  'Data input bit 1.',
      'D2':  'Data input bit 2.',
      'D3':  'Data input bit 3.',
      'D4':  'Data input bit 4.',
      'D5':  'Data input bit 5.',
      'D6':  'Data input bit 6.',
      'GND': 'Ground reference (pin 10).',
      'D7':  'Data input bit 7.',
      'Q7':  'Latched output bit 7.',
      'Q6':  'Latched output bit 6.',
      'Q5':  'Latched output bit 5.',
      'Q4':  'Latched output bit 4.',
      'Q3':  'Latched output bit 3.',
      'Q2':  'Latched output bit 2.',
      'Q1':  'Latched output bit 1.',
      'Q0':  'Latched output bit 0.',
      'VCC': 'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'Latch vs Register',
        paragraphs: [
          'A latch is level-sensitive: while LE is active, output tracks input. A register is edge-triggered: output only changes on a clock edge. Latches are often used in simple I/O decode paths where a dedicated clock is not available.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'OEn',  type: 'input'  },
      { pin:  2, name: 'LE',   type: 'input'  },
      { pin:  3, name: 'D0',   type: 'input'  },
      { pin:  4, name: 'D1',   type: 'input'  },
      { pin:  5, name: 'D2',   type: 'input'  },
      { pin:  6, name: 'D3',   type: 'input'  },
      { pin:  7, name: 'D4',   type: 'input'  },
      { pin:  8, name: 'D5',   type: 'input'  },
      { pin:  9, name: 'D6',   type: 'input'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'D7',   type: 'input'  },
      { pin: 12, name: 'Q7',   type: 'output' },
      { pin: 13, name: 'Q6',   type: 'output' },
      { pin: 14, name: 'Q5',   type: 'output' },
      { pin: 15, name: 'Q4',   type: 'output' },
      { pin: 16, name: 'Q3',   type: 'output' },
      { pin: 17, name: 'Q2',   type: 'output' },
      { pin: 18, name: 'Q1',   type: 'output' },
      { pin: 19, name: 'Q0',   type: 'output' },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','LE','D0','D1','D2','D3','D4','D5','D6','D7'], outputs: ['Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7'] },
    ],
  },

  // ── 74794: 8 bit register w/ readback (20-pin) ────────────────────────────
  /* Primary source: Texas Instruments, 74794 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls794.pdf */
  '74794': {
    name: '74x794',
    simpleName: '8 bit Register w/ Readback',
    description: '8 bit register with readback capability (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls794.pdf',
    tags: ['register', '8 bit', 'readback', 'stub'],
    sequential: true,
    guideOverview: 'The 74x794 is an 8 bit edge-triggered register with readback capability. On each active clock edge, D0-D7 are captured and presented on Q0-Q7. OEn controls tri-state output drive so the register can share a common bus.',
    guidePinDescriptions: {
      'OEn': 'Output enable (active LOW).',
      'CLK': 'Clock input; captures D inputs on active edge.',
      'D0':  'Data input bit 0.',
      'D1':  'Data input bit 1.',
      'D2':  'Data input bit 2.',
      'D3':  'Data input bit 3.',
      'D4':  'Data input bit 4.',
      'D5':  'Data input bit 5.',
      'D6':  'Data input bit 6.',
      'GND': 'Ground reference (pin 10).',
      'D7':  'Data input bit 7.',
      'Q7':  'Registered output bit 7.',
      'Q6':  'Registered output bit 6.',
      'Q5':  'Registered output bit 5.',
      'Q4':  'Registered output bit 4.',
      'Q3':  'Registered output bit 3.',
      'Q2':  'Registered output bit 2.',
      'Q1':  'Registered output bit 1.',
      'Q0':  'Registered output bit 0.',
      'VCC': 'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'Readback Register Use',
        paragraphs: [
          'Readback lets firmware verify that a write reached external hardware correctly. This was common in bus-peripheral interfaces where software needed confidence about programmed control values.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'OEn',  type: 'input'  },
      { pin:  2, name: 'CLK',  type: 'input'  },
      { pin:  3, name: 'D0',   type: 'input'  },
      { pin:  4, name: 'D1',   type: 'input'  },
      { pin:  5, name: 'D2',   type: 'input'  },
      { pin:  6, name: 'D3',   type: 'input'  },
      { pin:  7, name: 'D4',   type: 'input'  },
      { pin:  8, name: 'D5',   type: 'input'  },
      { pin:  9, name: 'D6',   type: 'input'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'D7',   type: 'input'  },
      { pin: 12, name: 'Q7',   type: 'output' },
      { pin: 13, name: 'Q6',   type: 'output' },
      { pin: 14, name: 'Q5',   type: 'output' },
      { pin: 15, name: 'Q4',   type: 'output' },
      { pin: 16, name: 'Q3',   type: 'output' },
      { pin: 17, name: 'Q2',   type: 'output' },
      { pin: 18, name: 'Q1',   type: 'output' },
      { pin: 19, name: 'Q0',   type: 'output' },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','CLK','D0','D1','D2','D3','D4','D5','D6','D7'], outputs: ['Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7'] },
    ],
  },

  // ── 74795: Octal buffer, non-inverting, shared enable, TRI (20-pin) ───────
  /* Primary source: Texas Instruments, 74795 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls795.pdf
     https://en.wikipedia.org/wiki/Three-state_logic */
  '74795': {
    name: '74x795',
    simpleName: 'Octal Buffer (Non-Inv, Shared En, TRI)',
    description: 'Octal buffer with non-inverting outputs and shared enable, three-state (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls795.pdf',
    tags: ['buffer', 'octal', 'non-inverting', 'tri-state', 'stub'],
    guideOverview: 'The 74x795 is an octal non-inverting tri-state buffer with one shared enable input. It is a straightforward bus interface part: present A0-A7 at Y0-Y7 when enabled, otherwise float outputs.',
    guidePinDescriptions: {
      'OEn': 'Shared output enable (active LOW).',
      'A0':  'Input bit 0.',
      'A1':  'Input bit 1.',
      'A2':  'Input bit 2.',
      'A3':  'Input bit 3.',
      'A4':  'Input bit 4.',
      'A5':  'Input bit 5.',
      'A6':  'Input bit 6.',
      'A7':  'Input bit 7.',
      'GND': 'Ground reference (pin 10).',
      'Y7':  'Buffered output bit 7.',
      'Y6':  'Buffered output bit 6.',
      'Y5':  'Buffered output bit 5.',
      'Y4':  'Buffered output bit 4.',
      'Y3':  'Buffered output bit 3.',
      'Y2':  'Buffered output bit 2.',
      'Y1':  'Buffered output bit 1.',
      'Y0':  'Buffered output bit 0.',
      'NC':  'No connect.',
      'VCC': 'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'Shared Enable Buffers',
        paragraphs: [
          'A single enable line is ideal when an entire 8 bit bus must be connected or disconnected as one unit. This keeps control logic simple in memory and peripheral bus decode.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'OEn', type: 'input'  },
      { pin:  2, name: 'A0',  type: 'input'  },
      { pin:  3, name: 'A1',  type: 'input'  },
      { pin:  4, name: 'A2',  type: 'input'  },
      { pin:  5, name: 'A3',  type: 'input'  },
      { pin:  6, name: 'A4',  type: 'input'  },
      { pin:  7, name: 'A5',  type: 'input'  },
      { pin:  8, name: 'A6',  type: 'input'  },
      { pin:  9, name: 'A7',  type: 'input'  },
      { pin: 10, name: 'GND', type: 'power'  },
      { pin: 11, name: 'Y7',  type: 'output' },
      { pin: 12, name: 'Y6',  type: 'output' },
      { pin: 13, name: 'Y5',  type: 'output' },
      { pin: 14, name: 'Y4',  type: 'output' },
      { pin: 15, name: 'Y3',  type: 'output' },
      { pin: 16, name: 'Y2',  type: 'output' },
      { pin: 17, name: 'Y1',  type: 'output' },
      { pin: 18, name: 'Y0',  type: 'output' },
      { pin: 19, name: 'NC',  type: 'nc'     },
      { pin: 20, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','A0','A1','A2','A3','A4','A5','A6','A7'], outputs: ['Y0','Y1','Y2','Y3','Y4','Y5','Y6','Y7'] },
    ],
  },

  // ── 74796: Octal buffer, inverting, shared enable, TRI (20-pin) ──────────
  /* Primary source: Texas Instruments, 74796 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls796.pdf
     https://en.wikipedia.org/wiki/Three-state_logic */
  '74796': {
    name: '74x796',
    simpleName: 'Octal Buffer (Inv, Shared En, TRI)',
    description: 'Octal buffer with inverting outputs and shared enable, three-state (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls796.pdf',
    tags: ['buffer', 'octal', 'inverting', 'tri-state', 'stub'],
    guideOverview: 'The 74x796 is the inverting counterpart to the 74x795. It buffers eight lines, inverts each channel, and provides a shared tri-state enable. This is useful where active LOW bus conventions are preferred.',
    guidePinDescriptions: {
      'OEn': 'Shared output enable (active LOW).',
      'A0':  'Input bit 0.',
      'A1':  'Input bit 1.',
      'A2':  'Input bit 2.',
      'A3':  'Input bit 3.',
      'A4':  'Input bit 4.',
      'A5':  'Input bit 5.',
      'A6':  'Input bit 6.',
      'A7':  'Input bit 7.',
      'GND': 'Ground reference (pin 10).',
      'Y7':  'Inverted output bit 7.',
      'Y6':  'Inverted output bit 6.',
      'Y5':  'Inverted output bit 5.',
      'Y4':  'Inverted output bit 4.',
      'Y3':  'Inverted output bit 3.',
      'Y2':  'Inverted output bit 2.',
      'Y1':  'Inverted output bit 1.',
      'Y0':  'Inverted output bit 0.',
      'NC':  'No connect.',
      'VCC': 'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: '74x795 vs 74x796',
        paragraphs: [
          'Both are shared-enable octal tri-state buffers. 74x795 is non-inverting, while 74x796 inverts every channel.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'OEn', type: 'input'  },
      { pin:  2, name: 'A0',  type: 'input'  },
      { pin:  3, name: 'A1',  type: 'input'  },
      { pin:  4, name: 'A2',  type: 'input'  },
      { pin:  5, name: 'A3',  type: 'input'  },
      { pin:  6, name: 'A4',  type: 'input'  },
      { pin:  7, name: 'A5',  type: 'input'  },
      { pin:  8, name: 'A6',  type: 'input'  },
      { pin:  9, name: 'A7',  type: 'input'  },
      { pin: 10, name: 'GND', type: 'power'  },
      { pin: 11, name: 'Y7',  type: 'output' },
      { pin: 12, name: 'Y6',  type: 'output' },
      { pin: 13, name: 'Y5',  type: 'output' },
      { pin: 14, name: 'Y4',  type: 'output' },
      { pin: 15, name: 'Y3',  type: 'output' },
      { pin: 16, name: 'Y2',  type: 'output' },
      { pin: 17, name: 'Y1',  type: 'output' },
      { pin: 18, name: 'Y0',  type: 'output' },
      { pin: 19, name: 'NC',  type: 'nc'     },
      { pin: 20, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','A0','A1','A2','A3','A4','A5','A6','A7'], outputs: ['Y0','Y1','Y2','Y3','Y4','Y5','Y6','Y7'] },
    ],
  },

  // ── 74797: Octal buffer, non-inverting, enable for 4 each, TRI (20-pin) ──
  /* Primary source: Texas Instruments, 74797 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls797.pdf
     https://en.wikipedia.org/wiki/Three-state_logic */
  '74797': {
    name: '74x797',
    simpleName: 'Octal Buffer (Non-Inv, Split En, TRI)',
    description: 'Octal buffer with non-inverting outputs and separate enables for each group of 4, three-state (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls797.pdf',
    tags: ['buffer', 'octal', 'non-inverting', 'tri-state', 'stub'],
    guideOverview: 'The 74x797 is an octal non-inverting tri-state buffer with split enables, letting two 4 bit groups be controlled independently. This is useful when upper and lower nibbles belong to different bus phases or devices.',
    guidePinDescriptions: {
      'OE1n': 'Enable for one 4 bit output group (active LOW).',
      'A0':   'Input bit 0.',
      'A1':   'Input bit 1.',
      'A2':   'Input bit 2.',
      'A3':   'Input bit 3.',
      'A4':   'Input bit 4.',
      'A5':   'Input bit 5.',
      'A6':   'Input bit 6.',
      'OE2n': 'Enable for the other 4 bit output group (active LOW).',
      'GND':  'Ground reference (pin 10).',
      'A7':   'Input bit 7.',
      'Y7':   'Buffered output bit 7.',
      'Y6':   'Buffered output bit 6.',
      'Y5':   'Buffered output bit 5.',
      'Y4':   'Buffered output bit 4.',
      'Y3':   'Buffered output bit 3.',
      'Y2':   'Buffered output bit 2.',
      'Y1':   'Buffered output bit 1.',
      'Y0':   'Buffered output bit 0.',
      'VCC':  'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'Split-Nibble Bus Control',
        paragraphs: [
          'Independent nibble enables are handy in BCD systems, half-byte peripherals, and multiplexed bus designs where only four bits should drive at a given time.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'OE1n',type: 'input'  },
      { pin:  2, name: 'A0',  type: 'input'  },
      { pin:  3, name: 'A1',  type: 'input'  },
      { pin:  4, name: 'A2',  type: 'input'  },
      { pin:  5, name: 'A3',  type: 'input'  },
      { pin:  6, name: 'A4',  type: 'input'  },
      { pin:  7, name: 'A5',  type: 'input'  },
      { pin:  8, name: 'A6',  type: 'input'  },
      { pin:  9, name: 'OE2n',type: 'input'  },
      { pin: 10, name: 'GND', type: 'power'  },
      { pin: 11, name: 'A7',  type: 'input'  },
      { pin: 12, name: 'Y7',  type: 'output' },
      { pin: 13, name: 'Y6',  type: 'output' },
      { pin: 14, name: 'Y5',  type: 'output' },
      { pin: 15, name: 'Y4',  type: 'output' },
      { pin: 16, name: 'Y3',  type: 'output' },
      { pin: 17, name: 'Y2',  type: 'output' },
      { pin: 18, name: 'Y1',  type: 'output' },
      { pin: 19, name: 'Y0',  type: 'output' },
      { pin: 20, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OE1n','OE2n','A0','A1','A2','A3','A4','A5','A6','A7'], outputs: ['Y0','Y1','Y2','Y3','Y4','Y5','Y6','Y7'] },
    ],
  },

  // ── 74798: Octal buffer, inverting, enable for 4 each, TRI (20-pin) ──────
  /* Primary source: Texas Instruments, 74798 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls798.pdf
     https://en.wikipedia.org/wiki/Three-state_logic */
  '74798': {
    name: '74x798',
    simpleName: 'Octal Buffer (Inv, Split En, TRI)',
    description: 'Octal buffer with inverting outputs and separate enables for each group of 4, three-state (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls798.pdf',
    tags: ['buffer', 'octal', 'inverting', 'tri-state', 'stub'],
    guideOverview: 'The 74x798 is the inverting split-enable version of the 74x797. It provides two independently enabled 4 bit output groups and inverts data polarity on each channel.',
    guidePinDescriptions: {
      'OE1n': 'Enable for one 4 bit output group (active LOW).',
      'A0':   'Input bit 0.',
      'A1':   'Input bit 1.',
      'A2':   'Input bit 2.',
      'A3':   'Input bit 3.',
      'A4':   'Input bit 4.',
      'A5':   'Input bit 5.',
      'A6':   'Input bit 6.',
      'OE2n': 'Enable for the second 4 bit output group (active LOW).',
      'GND':  'Ground reference (pin 10).',
      'A7':   'Input bit 7.',
      'Y7':   'Inverted output bit 7.',
      'Y6':   'Inverted output bit 6.',
      'Y5':   'Inverted output bit 5.',
      'Y4':   'Inverted output bit 4.',
      'Y3':   'Inverted output bit 3.',
      'Y2':   'Inverted output bit 2.',
      'Y1':   'Inverted output bit 1.',
      'Y0':   'Inverted output bit 0.',
      'VCC':  'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'When to Use Inverting Split Enables',
        paragraphs: [
          'This combination is helpful when two nibble lanes need separate gating and active LOW signal conventions. It avoids adding external inverters and extra decode chips.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'OE1n',type: 'input'  },
      { pin:  2, name: 'A0',  type: 'input'  },
      { pin:  3, name: 'A1',  type: 'input'  },
      { pin:  4, name: 'A2',  type: 'input'  },
      { pin:  5, name: 'A3',  type: 'input'  },
      { pin:  6, name: 'A4',  type: 'input'  },
      { pin:  7, name: 'A5',  type: 'input'  },
      { pin:  8, name: 'A6',  type: 'input'  },
      { pin:  9, name: 'OE2n',type: 'input'  },
      { pin: 10, name: 'GND', type: 'power'  },
      { pin: 11, name: 'A7',  type: 'input'  },
      { pin: 12, name: 'Y7',  type: 'output' },
      { pin: 13, name: 'Y6',  type: 'output' },
      { pin: 14, name: 'Y5',  type: 'output' },
      { pin: 15, name: 'Y4',  type: 'output' },
      { pin: 16, name: 'Y3',  type: 'output' },
      { pin: 17, name: 'Y2',  type: 'output' },
      { pin: 18, name: 'Y1',  type: 'output' },
      { pin: 19, name: 'Y0',  type: 'output' },
      { pin: 20, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OE1n','OE2n','A0','A1','A2','A3','A4','A5','A6','A7'], outputs: ['Y0','Y1','Y2','Y3','Y4','Y5','Y6','Y7'] },
    ],
  },

  // ── 74800: Triple 4 input AND/NAND drivers (20-pin) ──────────────────────
  /* Primary source: Texas Instruments, 74800 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74as800.pdf */
  '74800': {
    name: '74x800',
    simpleName: 'Triple 4 Input AND/NAND Driver',
    description: 'Triple 4 input AND/NAND drivers (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74as800.pdf',
    tags: ['AND', 'NAND', 'gate', 'driver', 'quad-input', 'stub'],
    guideOverview: 'The 74x800 includes three 4 input logic driver sections that provide both true AND outputs and inverted NAND outputs for each channel. Having Y and Yn together is convenient for control logic where both polarities are needed without extra gates.',
    guidePinDescriptions: {
      'A0':  'Input A of channel 0.',
      'B0':  'Input B of channel 0.',
      'C0':  'Input C of channel 0.',
      'D0':  'Input D of channel 0.',
      'Y0n': 'NAND output of channel 0 (inverted).',
      'Y0':  'AND output of channel 0 (true polarity).',
      'A1':  'Input A of channel 1.',
      'B1':  'Input B of channel 1.',
      'C1':  'Input C of channel 1.',
      'GND': 'Ground reference (pin 10).',
      'D1':  'Input D of channel 1.',
      'Y1n': 'NAND output of channel 1 (inverted).',
      'Y1':  'AND output of channel 1 (true polarity).',
      'A2':  'Input A of channel 2.',
      'B2':  'Input B of channel 2.',
      'C2':  'Input C of channel 2.',
      'D2':  'Input D of channel 2.',
      'Y2n': 'NAND output of channel 2 (inverted).',
      'Y2':  'AND output of channel 2 (true polarity).',
      'VCC': 'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'AND and NAND Together',
        paragraphs: [
          'Because NAND is the complement of AND, providing both outputs from one section reduces part count in complex combinational networks. Designers can route whichever polarity they need directly.',
        ],
      },
      {
        title: 'Logic Formula',
        formulas: [
          'Y = A * B * C * D',
          'Yn = (A * B * C * D)',
        ],
        note: 'Functional behavior is currently represented as a generic stub in simulation.',
      },
    ],
    pinout: [
      { pin:  1, name: 'A0',   type: 'input'  },
      { pin:  2, name: 'B0',   type: 'input'  },
      { pin:  3, name: 'C0',   type: 'input'  },
      { pin:  4, name: 'D0',   type: 'input'  },
      { pin:  5, name: 'Y0n',  type: 'output' },
      { pin:  6, name: 'Y0',   type: 'output' },
      { pin:  7, name: 'A1',   type: 'input'  },
      { pin:  8, name: 'B1',   type: 'input'  },
      { pin:  9, name: 'C1',   type: 'input'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'D1',   type: 'input'  },
      { pin: 12, name: 'Y1n',  type: 'output' },
      { pin: 13, name: 'Y1',   type: 'output' },
      { pin: 14, name: 'A2',   type: 'input'  },
      { pin: 15, name: 'B2',   type: 'input'  },
      { pin: 16, name: 'C2',   type: 'input'  },
      { pin: 17, name: 'D2',   type: 'input'  },
      { pin: 18, name: 'Y2n',  type: 'output' },
      { pin: 19, name: 'Y2',   type: 'output' },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['A0','B0','C0','D0','A1','B1','C1','D1','A2','B2','C2','D2'], outputs: ['Y0','Y0n','Y1','Y1n','Y2','Y2n'] },
    ],
  },

};