// Chip definitions block 32
// 74x589   74x614

export const CHIPS_BLOCK_32 = {

  // ── 74589: 8 bit shift register with input latch, tri state ─────────────
  /* Primary source: Texas Instruments, 74589 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls589.pdf
     https://en.wikipedia.org/wiki/Shift_register */
  // 8 bit input latch (transparent on RCK high) feeds shift register.
  // Rising SRCK shifts serial data; QH* is the serial output (last SR stage).
  // OE=0 enables QH* output; CKEN gates shift clock.
  '74x589': {
    name: '74x589',
    simpleName: '8 bit Shift Reg+Latch (TRI)',
    description: '8-bit SIPO shift register, input latch, 3-state output (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls589.pdf',
    tags: ['shift register', 'latch', 'serial', '8 bit', 'sequential', 'sipo', 'tri state'],
    guideOverview: 'The 74x589 is an 8 bit serial in/parallel out shift register with a parallel input latch. D0-D7 are first captured into a transparent latch when RCK is HIGH. On each rising SRCK edge (gated by CKEN), data is shifted into the shift register from SER. QH is the serial output (last stage). OE (active LOW) enables QH. Useful for converting a parallel bus byte into a serial stream.',
    guidePinDescriptions: {
      'QH':   'Serial output (MSB of shift register). Enabled by OE.',
      'SER':  'Serial data input. Enters the first stage on each SRCK edge.',
      'OE':   'Output Enable for QH (active LOW).',
      'D7':   'Parallel input bit 7 (MSB) to input latch.',
      'D6':   'Parallel input bit 6.',
      'D5':   'Parallel input bit 5.',
      'D4':   'Parallel input bit 4.',
      'GND':  'Ground reference (pin 8).',
      'D3':   'Parallel input bit 3.',
      'D2':   'Parallel input bit 2.',
      'D1':   'Parallel input bit 1.',
      'D0':   'Parallel input bit 0.',
      'SRCK': 'Shift register clock (rising edge).',
      'RCK':  'Register Clock. HIGH = transparent, captures D0-D7 into latch.',
      'CKEN': 'Clock Enable for SRCK (active LOW). Tie LOW to enable shifting.',
      'VCC':  'Positive supply (+5 V, pin 16).',
    },
    guideSections: [
      {
        title: 'Parallel In Serial Out via Input Latch',
        paragraphs: [
          'The input latch decouples the D0-D7 bus from the shift register. First, assert RCK HIGH to capture the parallel byte; then shift out 8 bits serially via SRCK. The latch holds the value stable during shifting even if the D bus changes.',
        ],
      },
    ],
    pinout: [
      { pin: 1,  name: 'QH',   type: 'output' },
      { pin: 2,  name: 'SER',  type: 'input' },
      { pin: 3,  name: 'OE',   type: 'input' },
      { pin: 4,  name: 'D7',   type: 'input' },
      { pin: 5,  name: 'D6',   type: 'input' },
      { pin: 6,  name: 'D5',   type: 'input' },
      { pin: 7,  name: 'D4',   type: 'input' },
      { pin: 8,  name: 'GND',  type: 'power' },
      { pin: 9,  name: 'D3',   type: 'input' },
      { pin: 10, name: 'D2',   type: 'input' },
      { pin: 11, name: 'D1',   type: 'input' },
      { pin: 12, name: 'D0',   type: 'input' },
      { pin: 13, name: 'SRCK', type: 'input' },
      { pin: 14, name: 'RCK',  type: 'input' },
      { pin: 15, name: 'CKEN', type: 'input' },
      { pin: 16, name: 'VCC',  type: 'power' },
    ],
    gates: [
      { type: 'SHIFT_REG_8BIT_LATCH_TRI',
        inputs:  ['SER', 'SRCK', 'RCK', 'CKEN', 'OE', 'D0', 'D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7'],
        outputs: ['QH'] },
    ],
    sequential: true,
  },

  // ── 74590: 8 bit binary counter with output registers, tri state ─────────
  /* Primary source: Texas Instruments, 74590 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls590.pdf
     https://en.wikipedia.org/wiki/Counter_(digital) */
  // Separate counter clock (CCLKn, active LOW) and register clock (RClk).
  // CCLR=0: async clear counter. RCLR=0: async clear output register.
  // RClk rising edge: latch counter→output register. OEn=0: drive Q0-Q7.
  // RC output = carry (RCO) from counter.
  '74x590': {
    name: '74x590',
    simpleName: '8 bit Counter+OutReg (TRI)',
    description: '8 bit binary counter with output registers and tri state outputs (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls590.pdf',
    tags: ['counter', 'register', '8 bit', 'binary', 'sequential', 'tri state'],
    guideOverview: 'The 74x590 is an 8 bit binary counter (0-255) with a separate 8 bit output register and tri state outputs. CCLKn (active LOW falling edge) increments the counter; RCLK rising edge latches the counter value into the output register. OEn (active LOW) enables the register outputs. Separate CCLR and RCLR clear the counter and register independently.',
    guidePinDescriptions: {
      'Q1':    'Output register bit 1.',
      'Q2':    'Output register bit 2.',
      'Q3':    'Output register bit 3.',
      'Q4':    'Output register bit 4.',
      'Q5':    'Output register bit 5.',
      'Q6':    'Output register bit 6.',
      'Q7':    'Output register bit 7.',
      'GND':   'Ground reference (pin 8).',
      'RC':    'Ripple Carry out (HIGH when counter = 255).',
      'CCLKn': 'Counter Clock (active LOW, falling edge).',
      'CCLR':  'Async Counter Clear (active HIGH). Clears counter immediately.',
      'RCLK':  'Register Clock (rising edge). Latches counter to output register.',
      'RCLR':  'Async Register Clear (active LOW).',
      'OEn':   'Output Enable (active LOW).',
      'Q0':    'Output register bit 0 (LSB).',
      'VCC':   'Positive supply (+5 V, pin 16).',
    },
    guideSections: [
      {
        title: 'Counter with Output Register',
        paragraphs: [
          'The separate output register lets you freeze a snapshot of the count while the counter continues running. Pulse RCLK to capture the current count; the bus shows that value until the next RCLK.',
        ],
      },
    ],
    pinout: [
      { pin: 1,  name: 'Q1',   type: 'output' },
      { pin: 2,  name: 'Q2',   type: 'output' },
      { pin: 3,  name: 'Q3',   type: 'output' },
      { pin: 4,  name: 'Q4',   type: 'output' },
      { pin: 5,  name: 'Q5',   type: 'output' },
      { pin: 6,  name: 'Q6',   type: 'output' },
      { pin: 7,  name: 'Q7',   type: 'output' },
      { pin: 8,  name: 'GND',  type: 'power' },
      { pin: 9,  name: 'RC',   type: 'output' },
      { pin: 10, name: 'CCLKn',type: 'input' },
      { pin: 11, name: 'CCLR', type: 'input' },
      { pin: 12, name: 'RCLK', type: 'input' },
      { pin: 13, name: 'RCLR', type: 'input' },
      { pin: 14, name: 'OEn',  type: 'input' },
      { pin: 15, name: 'Q0',   type: 'output' },
      { pin: 16, name: 'VCC',  type: 'power' },
    ],
    gates: [
      { type: 'COUNTER_8BIT_REG_OUT_TRI',
        inputs:  ['CCLKn', 'CCLR', 'RCLK', 'RCLR', 'OEn'],
        outputs: ['Q0', 'Q1', 'Q2', 'Q3', 'Q4', 'Q5', 'Q6', 'Q7', 'RC'] },
    ],
    sequential: true,
  },

  // ── 74591: 8 bit binary counter with output registers, open collector ────
  /* Primary source: Texas Instruments, 74591 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls591.pdf
     https://en.wikipedia.org/wiki/Counter_(digital) */
  '74x591': {
    name: '74x591',
    simpleName: '8 bit Counter+OutReg (OC)',
    description: '8-bit binary counter, output registers, open-collector out (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    openCollector: true,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls591.pdf',
    tags: ['counter', 'register', '8 bit', 'binary', 'sequential', 'open collector'],
    guideOverview: 'The 74x591 is functionally identical to the 74x590 but with open collector outputs instead of tri state. The OEn pin still exists; with OC outputs, external pull up resistors are required. This allows wire OR combinations on shared bus lines.',
    guidePinDescriptions: {
      'Q1':    'Open collector output bit 1.',
      'Q2':    'Open collector output bit 2.',
      'Q3':    'Open collector output bit 3.',
      'Q4':    'Open collector output bit 4.',
      'Q5':    'Open collector output bit 5.',
      'Q6':    'Open collector output bit 6.',
      'Q7':    'Open collector output bit 7.',
      'GND':   'Ground reference (pin 8).',
      'RC':    'Ripple Carry out.',
      'CCLKn': 'Counter Clock (active LOW).',
      'CCLR':  'Async Counter Clear.',
      'RCLK':  'Register Clock (rising edge).',
      'RCLR':  'Async Register Clear.',
      'OEn':   'Output Enable (active LOW).',
      'Q0':    'Open collector output bit 0.',
      'VCC':   'Positive supply (+5 V, pin 16).',
    },
    guideSections: [
      {
        title: '74x590 vs 74x591',
        paragraphs: [
          '74x590 has tri state outputs; 74x591 has open collector. Use 74x591 with pull ups when multiple counters share a bus via wire OR, or when driving optocouplers or relay drivers directly.',
        ],
        note: 'External pull up resistors (typically 1-4.7 kΩ) are required on all Q outputs for proper HIGH levels.',
      },
    ],
    pinout: [
      { pin: 1,  name: 'Q1',   type: 'output' },
      { pin: 2,  name: 'Q2',   type: 'output' },
      { pin: 3,  name: 'Q3',   type: 'output' },
      { pin: 4,  name: 'Q4',   type: 'output' },
      { pin: 5,  name: 'Q5',   type: 'output' },
      { pin: 6,  name: 'Q6',   type: 'output' },
      { pin: 7,  name: 'Q7',   type: 'output' },
      { pin: 8,  name: 'GND',  type: 'power' },
      { pin: 9,  name: 'RC',   type: 'output' },
      { pin: 10, name: 'CCLKn',type: 'input' },
      { pin: 11, name: 'CCLR', type: 'input' },
      { pin: 12, name: 'RCLK', type: 'input' },
      { pin: 13, name: 'RCLR', type: 'input' },
      { pin: 14, name: 'OEn',  type: 'input' },
      { pin: 15, name: 'Q0',   type: 'output' },
      { pin: 16, name: 'VCC',  type: 'power' },
    ],
    gates: [
      { type: 'COUNTER_8BIT_REG_OUT_OC',
        inputs:  ['CCLKn', 'CCLR', 'RCLK', 'RCLR', 'OEn'],
        outputs: ['Q0', 'Q1', 'Q2', 'Q3', 'Q4', 'Q5', 'Q6', 'Q7', 'RC'] },
    ],
    sequential: true,
  },

  // ── 74592: 8 bit binary counter with input registers ─────────────────────
  /* Primary source: Texas Instruments, 74592 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls592.pdf
     https://en.wikipedia.org/wiki/Counter_(digital) */
  // Input register captures D0-D7 on rising RCK. Counter loads from input
  // register on rising CCK when CCLR=1 and CKEN=0. Counter increments on
  // rising CCK when CKEN=1. CCLR=0: async clear counter.
  // RC output = ripple carry (counter==255).
  '74x592': {
    name: '74x592',
    simpleName: '8 bit Counter+InReg',
    description: '8 bit binary counter with input registers for parallel loading (16-pin)',
    pins: 16,
    vcc: 15,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls592.pdf',
    tags: ['counter', 'register', '8 bit', 'binary', 'sequential', 'load'],
    guideOverview: 'The 74x592 is an 8 bit binary counter with an input register for parallel loading. D0-D7 are captured by the input register on rising RCK. When CKEN=0, the next rising CCK loads the input register value into the counter; when CKEN=1, CCK increments the counter. RC indicates counter = 255. No parallel output pins (counter drives internal logic only).',
    guidePinDescriptions: {
      'D1':   'Parallel input bit 1.',
      'D2':   'Parallel input bit 2.',
      'D3':   'Parallel input bit 3.',
      'D4':   'Parallel input bit 4.',
      'D5':   'Parallel input bit 5.',
      'D6':   'Parallel input bit 6.',
      'D7':   'Parallel input bit 7.',
      'GND':  'Ground reference (pin 8).',
      'RC':   'Ripple Carry (counter = 255).',
      'CCK':  'Counter Clock (rising edge).',
      'CCLR': 'Async Counter Clear (active LOW).',
      'RCK':  'Register Clock. Rising edge captures D0-D7.',
      'CKEN': 'Count Enable. HIGH = count; LOW = load on next CCK.',
      'D0':   'Parallel input bit 0.',
      'VCC':  'Positive supply (pin 15).',
      'GND2': 'Additional ground pin (pin 16).',
    },
    guideSections: [
      {
        title: 'Counter with Input Register',
        paragraphs: [
          'The input register separates the data bus from the counter. Load a preset value: first capture it with RCK, then load it with CKEN=0 on the next CCK. After loading, set CKEN=1 to resume counting from the loaded value.',
        ],
      },
    ],
    pinout: [
      { pin: 1,  name: 'D1',   type: 'input' },
      { pin: 2,  name: 'D2',   type: 'input' },
      { pin: 3,  name: 'D3',   type: 'input' },
      { pin: 4,  name: 'D4',   type: 'input' },
      { pin: 5,  name: 'D5',   type: 'input' },
      { pin: 6,  name: 'D6',   type: 'input' },
      { pin: 7,  name: 'D7',   type: 'input' },
      { pin: 8,  name: 'GND',  type: 'power' },
      { pin: 9,  name: 'RC',   type: 'output' },
      { pin: 10, name: 'CCK',  type: 'input' },
      { pin: 11, name: 'CCLR', type: 'input' },
      { pin: 12, name: 'RCK',  type: 'input' },
      { pin: 13, name: 'CKEN', type: 'input' },
      { pin: 14, name: 'D0',   type: 'input' },
      { pin: 15, name: 'VCC',  type: 'power' },
      { pin: 16, name: 'GND2', type: 'power' },
    ],
    gates: [
      { type: 'COUNTER_8BIT_REG_IN',
        inputs:  ['CCK', 'CCLR', 'RCK', 'CKEN', 'D0', 'D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7'],
        outputs: ['RC'] },
    ],
    sequential: true,
  },

  // ── 74593: 8 bit binary counter with input registers, tri state ──────────
  /* Primary source: Texas Instruments, 74593 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls593.pdf
     https://en.wikipedia.org/wiki/Counter_(digital) */
  '74x593': {
    name: '74x593',
    simpleName: '8 bit Counter+InReg (TRI)',
    description: '8 bit binary counter with input registers and tri state outputs (20-pin)',
    pins: 20,
    vcc: 20,
    gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls593.pdf',
    tags: ['counter', 'register', '8 bit', 'binary', 'sequential', 'tri state', 'load'],
    guideOverview: 'The 74x593 is the tri state output version of the 74x592. D0-D7 are bidirectional: used as inputs for parallel load (via RCK) and as outputs (Q0-D7) when OEn is LOW. Q4-Q7 are dedicated output pins. RC is the ripple carry. CKEN selects load vs count on each CCK edge.',
    guidePinDescriptions: {
      'OEn':  'Output Enable (active LOW).',
      'D0':   'Bidirectional data/output bit 0.',
      'D1':   'Bidirectional data/output bit 1.',
      'D2':   'Bidirectional data/output bit 2.',
      'D3':   'Bidirectional data/output bit 3.',
      'D4':   'Bidirectional data/output bit 4.',
      'D5':   'Bidirectional data/output bit 5.',
      'D6':   'Bidirectional data/output bit 6.',
      'D7':   'Bidirectional data/output bit 7.',
      'GND':  'Ground reference (pin 10).',
      'RCK':  'Register Clock. Rising edge captures D0-D7.',
      'CCK':  'Counter Clock (rising edge).',
      'CCLR': 'Async Counter Clear (active LOW).',
      'CKEN': 'Count Enable. HIGH = count; LOW = load on next CCK.',
      'RC':   'Ripple Carry output.',
      'Q7':   'Counter output bit 7.',
      'Q6':   'Counter output bit 6.',
      'Q5':   'Counter output bit 5.',
      'Q4':   'Counter output bit 4.',
      'VCC':  'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: '74x592 vs 74x593',
        paragraphs: [
          '74x592 has no output pins; 74x593 adds tri state outputs on D0-D7 and dedicated Q4-Q7 outputs. Use 74x593 when counter contents must be read back over a shared bus.',
        ],
      },
    ],
    pinout: [
      { pin: 1,  name: 'OEn',  type: 'input' },
      { pin: 2,  name: 'D0',   type: 'io' },
      { pin: 3,  name: 'D1',   type: 'io' },
      { pin: 4,  name: 'D2',   type: 'io' },
      { pin: 5,  name: 'D3',   type: 'io' },
      { pin: 6,  name: 'D4',   type: 'io' },
      { pin: 7,  name: 'D5',   type: 'io' },
      { pin: 8,  name: 'D6',   type: 'io' },
      { pin: 9,  name: 'D7',   type: 'io' },
      { pin: 10, name: 'GND',  type: 'power' },
      { pin: 11, name: 'RCK',  type: 'input' },
      { pin: 12, name: 'CCK',  type: 'input' },
      { pin: 13, name: 'CCLR', type: 'input' },
      { pin: 14, name: 'CKEN', type: 'input' },
      { pin: 15, name: 'RC',   type: 'output' },
      { pin: 16, name: 'Q7',   type: 'output' },
      { pin: 17, name: 'Q6',   type: 'output' },
      { pin: 18, name: 'Q5',   type: 'output' },
      { pin: 19, name: 'Q4',   type: 'output' },
      { pin: 20, name: 'VCC',  type: 'power' },
    ],
    gates: [
      { type: 'COUNTER_8BIT_REG_IN_TRI',
        inputs:  ['CCK', 'CCLR', 'RCK', 'CKEN', 'OEn', 'D0', 'D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7'],
        outputs: ['D0', 'D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'RC'] },
    ],
    sequential: true,
  },

  // ── 74594: 8 bit SIPO shift register with output latch, buffered ─────────
  /* Primary source: Texas Instruments, 74594 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls594.pdf
     https://en.wikipedia.org/wiki/Shift_register */
  // Like 74595 but WITHOUT tri state OE outputs always driven.
  // SRCLR=0: async clear shift register. No OE pin.
  '74x594': {
    name: '74x594',
    simpleName: '8 bit Shift Reg+Latch (Buf)',
    description: '8-bit SIPO shift register, buffered output latch (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls594.pdf',
    tags: ['shift register', 'latch', 'serial', '8 bit', 'sequential', 'sipo'],
    guideOverview: 'The 74x594 is an 8 bit serial in/parallel out shift register with a separate 8 bit output latch. SER data is shifted on rising SRCLK edges; the current shift register state is latched to outputs QA-QH on rising RCLK. Unlike the 74x595, there is no OEn tri state outputs are always actively driven. SRCLR clears the shift register; RCLR clears the output latch.',
    guidePinDescriptions: {
      'QB':    'Output latch bit B.',
      'QC':    'Output latch bit C.',
      'QD':    'Output latch bit D.',
      'QE':    'Output latch bit E.',
      'QF':    'Output latch bit F.',
      'QG':    'Output latch bit G.',
      'QH':    'Output latch bit H (MSB of shift register).',
      'GND':   'Ground reference (pin 8).',
      'QHs':   'Serial output (cascade to next chip SER input).',
      'SRCLR': 'Shift Register Clear (active LOW, asynchronous).',
      'SRCLK': 'Shift Register Clock (rising edge).',
      'RCLK':  'Register Clock (rising edge). Transfers shift reg to output latch.',
      'RCLR':  'Output Register Clear (active LOW, asynchronous).',
      'SER':   'Serial data input.',
      'QA':    'Output latch bit A (LSB).',
      'VCC':   'Positive supply (+5 V, pin 16).',
    },
    guideSections: [
      {
        title: 'Two Stage Shift Register',
        paragraphs: [
          'The two stage design (shift register → output latch) prevents glitches on the outputs during shifting. All outputs update simultaneously on RCLK, not one bit at a time as the shift register loads.',
        ],
      },
    ],
    pinout: [
      { pin: 1,  name: 'QB',    type: 'output' },
      { pin: 2,  name: 'QC',    type: 'output' },
      { pin: 3,  name: 'QD',    type: 'output' },
      { pin: 4,  name: 'QE',    type: 'output' },
      { pin: 5,  name: 'QF',    type: 'output' },
      { pin: 6,  name: 'QG',    type: 'output' },
      { pin: 7,  name: 'QH',    type: 'output' },
      { pin: 8,  name: 'GND',   type: 'power' },
      { pin: 9,  name: 'QHs',   type: 'output' },
      { pin: 10, name: 'SRCLR', type: 'input' },
      { pin: 11, name: 'SRCLK', type: 'input' },
      { pin: 12, name: 'RCLK',  type: 'input' },
      { pin: 13, name: 'RCLR',  type: 'input' },
      { pin: 14, name: 'SER',   type: 'input' },
      { pin: 15, name: 'QA',    type: 'output' },
      { pin: 16, name: 'VCC',   type: 'power' },
    ],
    gates: [
      { type: 'SHIFT_REG_8BIT_LATCH_BUF',
        inputs:  ['SER', 'SRCLK', 'RCLK', 'SRCLR', 'RCLR'],
        outputs: ['QA', 'QB', 'QC', 'QD', 'QE', 'QF', 'QG', 'QH', 'QHs'] },
    ],
    sequential: true,
  },

  // ── 74596: 8 bit SIPO shift register with output latch, OC ──────────────
  /* Primary source: Texas Instruments, 74596 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls596.pdf
     https://en.wikipedia.org/wiki/Shift_register */
  // Like 74595 but OC outputs with OEn pin. OEn=0: drive outputs; else HiZ.
  '74x596': {
    name: '74x596',
    simpleName: '8 bit Shift Reg+Latch (OC)',
    description: '8-bit SIPO shift register, output latch, open-collector (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls596.pdf',
    tags: ['shift register', 'latch', 'serial', '8 bit', 'sequential', 'sipo', 'open collector'],
    guideOverview: 'The 74x596 is an 8 bit SIPO shift register with a two stage output latch and open collector outputs. Same SRCLK/RCLK/SRCLR shift then latch operation as the 74x595, but outputs are open collector requiring external pull ups. OEn (active LOW) enables the outputs.',
    guidePinDescriptions: {
      'QB':    'OC output bit B.',
      'QC':    'OC output bit C.',
      'QD':    'OC output bit D.',
      'QE':    'OC output bit E.',
      'QF':    'OC output bit F.',
      'QG':    'OC output bit G.',
      'QH':    'OC output bit H.',
      'GND':   'Ground reference (pin 8).',
      'QHs':   'Serial cascade output.',
      'SRCLR': 'Shift Register Clear (active LOW).',
      'SRCLK': 'Shift Register Clock.',
      'RCLK':  'Output Register Clock.',
      'OEn':   'Output Enable (active LOW).',
      'SER':   'Serial input.',
      'QA':    'OC output bit A.',
      'VCC':   'Positive supply (+5 V, pin 16).',
    },
    guideSections: [
      {
        title: 'Open Collector SIPO Register',
        paragraphs: [
          'OC outputs allow wire OR of multiple shift registers on a common bus and direct driving of high voltage or high current loads. External pull ups (1-4.7 kΩ) are required.',
        ],
      },
    ],
    pinout: [
      { pin: 1,  name: 'QB',    type: 'output' },
      { pin: 2,  name: 'QC',    type: 'output' },
      { pin: 3,  name: 'QD',    type: 'output' },
      { pin: 4,  name: 'QE',    type: 'output' },
      { pin: 5,  name: 'QF',    type: 'output' },
      { pin: 6,  name: 'QG',    type: 'output' },
      { pin: 7,  name: 'QH',    type: 'output' },
      { pin: 8,  name: 'GND',   type: 'power' },
      { pin: 9,  name: 'QHs',   type: 'output' },
      { pin: 10, name: 'SRCLR', type: 'input' },
      { pin: 11, name: 'SRCLK', type: 'input' },
      { pin: 12, name: 'RCLK',  type: 'input' },
      { pin: 13, name: 'OEn',   type: 'input' },
      { pin: 14, name: 'SER',   type: 'input' },
      { pin: 15, name: 'QA',    type: 'output' },
      { pin: 16, name: 'VCC',   type: 'power' },
    ],
    gates: [
      { type: 'SHIFT_REG_LATCH',
        inputs:  ['SER', 'SRCLK', 'RCLK', 'SRCLR', 'OEn'],
        outputs: ['QA', 'QB', 'QC', 'QD', 'QE', 'QF', 'QG', 'QH', 'QHs'] },
    ],
    sequential: true,
  },

  // ── 74597: 8-bit PISO shift register with input storage latch ────────────
  /* Primary source: Texas Instruments, "SN54LS597, SN54LS598, SN74LS597, SN74LS598
       8-Bit Shift Registers With Input Latches," SDLS007 (Jan. 1981, rev. Mar. 1988).
       [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls597.pdf.
       Verified: 'LS597 terminal assignment (N-package top view), logic diagram, and
       recommended operating conditions — pages 1, 3 and 5 — read as PDF page images.
     Family/behavior corroboration: Wikipedia contributors, "Shift register,"
       https://en.wikipedia.org/wiki/Shift_register. */
  // Corrected pinout (16-pin DIP), from the verified terminal diagram:
  //   1-7 = B,C,D,E,F,G,H (parallel data inputs), 8 = GND, 9 = QH' (serial out),
  //   10 = SRCLR (async clear, active low), 11 = SRCK (shift clock),
  //   12 = RCK (storage-latch clock), 13 = SRLOAD (async load, active low),
  //   14 = SER (serial in), 15 = A (parallel input), 16 = VCC.
  // Behavior: rising RCK latches A-H into the storage latch; SRLOAD low copies the
  //   storage latch into the shift register (async); SRCLR low clears it (async,
  //   dominates); rising SRCK shifts SER->A..H->QH'. QH' (shown here as QHs) is the
  //   only serial output. The old hand-entered pinout was wrong (see issues.md).
  '74x597': {
    name: '74x597',
    simpleName: '8-bit PISO + Input Latch',
    description: '8-bit PISO shift register, 8-bit input storage latch (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls597.pdf',
    tags: ['shift register', 'latch', 'serial', 'parallel', '8 bit', 'sequential', 'piso'],
    guideOverview: 'The 74x597 reads 8 bits in parallel and streams them out one at a time on a single serial pin — the input-side mirror of the 74x595, which does the reverse. It has two stages inside: a storage latch that grabs pins A–H on a rising edge of RCK, and a shift register the latched byte is loaded into and clocked out of. Pull SRLOAD low to copy the latch into the shift register, then clock SRCK to shift the byte out on QHs, the H bit first. SER feeds bits in from another chip, so several 597s chain into a wider input. It is the classic way to read a bank of switches or sensors into a microcontroller over just a few wires. Two things trip people up: there are two separate clocks (RCK loads the latch, SRCK shifts), and SRLOAD and SRCLR are both active-low and asynchronous — they act the instant they go low, no clock needed.',
    guidePinDescriptions: {
      'B':      'Parallel data input B (pin 1).',
      'C':      'Parallel data input C (pin 2).',
      'D':      'Parallel data input D (pin 3).',
      'E':      'Parallel data input E (pin 4).',
      'F':      'Parallel data input F (pin 5).',
      'G':      'Parallel data input G (pin 6).',
      'H':      'Parallel data input H — the last shift stage, read out first on QHs (pin 7).',
      'GND':    'Ground reference (pin 8).',
      'QHs':    'Serial output — the H (last) stage of the shift register. The datasheet labels it QH′; wire it to SER of the next chip to cascade (pin 9).',
      'SRCLR':  'Shift Register Clear. A LOW clears the shift register to all zeros at once, no clock needed (asynchronous, active LOW, pin 10).',
      'SRCK':   'Shift Register Clock. A rising edge shifts the register one place, but only while SRLOAD and SRCLR are HIGH (pin 11).',
      'RCK':    'Register Clock. A rising edge captures inputs A–H into the storage latch (pin 12).',
      'SRLOAD': 'Shift Register Load. A LOW copies the storage latch into the shift register at once, no clock needed (asynchronous, active LOW, pin 13).',
      'SER':    'Serial data input. New bits enter here at stage A during a shift; used to cascade chips (pin 14).',
      'A':      'Parallel data input A — the first shift stage, next to SER (pin 15).',
      'VCC':    'Positive supply (+5 V, pin 16).',
    },
    guideSections: [
      {
        title: 'Two stages: latch, then shift register',
        paragraphs: [
          'The 597 is really two 8-bit registers back to back. The first is a storage latch: on each rising edge of RCK it takes a snapshot of the eight parallel inputs A–H and holds it. Nothing shifts yet — this just freezes the inputs so they can not change under you while you read them out.',
          'The second is the shift register, the part that produces the serial output. Pulling SRLOAD low copies the latched snapshot into it in one step — no clock edge, the load is asynchronous. After that, every rising edge of SRCK moves the whole register one place toward QHs. The bit that falls off the end appears on QHs; the bit that enters the other end comes from SER.',
          'Splitting the capture (RCK) from the shift-out (SRCK) lets you grab a fresh snapshot at a precise moment and then read the previous one out at your own pace on a separate clock.',
        ],
      },
      {
        title: 'Control inputs',
        paragraphs: [
          'RCK and SRCK are edge-triggered (they act on a rising edge). SRLOAD and SRCLR are level-sensitive and asynchronous: they take effect the moment they go low and stay in effect the whole time they are held low. SRCLR wins over SRLOAD — hold both low and you get zeros, not the latched byte.',
        ],
        formulas: [
          'SRCLR=0                      → shift register cleared to 0 (async, overrides all)',
          'SRCLR=1, SRLOAD=0            → load storage latch into shift register (async)',
          'SRCLR=1, SRLOAD=1, SRCK↑     → shift one place toward QHs (SER enters at A)',
          'RCK↑                         → latch A–H into storage (works at any time)',
        ],
      },
      {
        title: 'Reading a byte out',
        list: [
          'Put the 8 bits on A–H and pulse RCK high to latch them.',
          'Pulse SRLOAD low (then back high) to copy the latched byte into the shift register.',
          'QHs now shows bit H. Each SRCK rising edge then brings the next bit to QHs, in the order H, G, F, … A.',
          'RCK can re-latch a fresh A–H at any time without disturbing a shift already in progress.',
        ],
      },
      {
        title: 'Common uses',
        list: [
          'Reading a bank of 8 switches, jumpers, or sensor outputs into a microcontroller over ~4 wires instead of 8.',
          'Chaining several 597s (QHs → SER of the next) to read 16, 24, or more inputs on the same few wires.',
          'Snapshotting a fast parallel bus at one instant with RCK, then clocking it into a slower processor at leisure with SRCK.',
          'Pairing with a 74x595 (serial-out) to build a serial input/output port from two shift registers.',
        ],
      },
      {
        title: 'Gotchas',
        list: [
          'Two clocks, two jobs: RCK loads the input latch, SRCK shifts. Pulsing the wrong one does nothing useful.',
          'SRLOAD and SRCLR are active LOW and asynchronous — no clock edge, and they hold as long as the pin is low. Tie them high when not in use.',
          'SRCLR beats SRLOAD: hold both low and the register clears to zero instead of loading the latch.',
          'H comes out first, A last. If your bytes read back bit-reversed, that ordering is why.',
          'The datasheet names the parallel inputs A–H and the serial output QH′; this simulator shows QH′ as QHs.',
        ],
      },
    ],
    pinout: [
      { pin: 1,  name: 'B',      type: 'input'  },
      { pin: 2,  name: 'C',      type: 'input'  },
      { pin: 3,  name: 'D',      type: 'input'  },
      { pin: 4,  name: 'E',      type: 'input'  },
      { pin: 5,  name: 'F',      type: 'input'  },
      { pin: 6,  name: 'G',      type: 'input'  },
      { pin: 7,  name: 'H',      type: 'input'  },
      { pin: 8,  name: 'GND',    type: 'power'  },
      { pin: 9,  name: 'QHs',    type: 'output' },
      { pin: 10, name: 'SRCLR',  type: 'input'  },
      { pin: 11, name: 'SRCK',   type: 'input'  },
      { pin: 12, name: 'RCK',    type: 'input'  },
      { pin: 13, name: 'SRLOAD', type: 'input'  },
      { pin: 14, name: 'SER',    type: 'input'  },
      { pin: 15, name: 'A',      type: 'input'  },
      { pin: 16, name: 'VCC',    type: 'power'  },
    ],
    gates: [
      { type: 'SHIFT_REG_8BIT_PISO_LATCH',
        inputs:  ['SER', 'SRCK', 'RCK', 'SRLOAD', 'SRCLR',
                  'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'],
        outputs: ['QHs'] },
    ],
    sequential: true,
  },

  // ── 74598: 8 bit shift register, selectable PI/PO + input latches, TRI ───
  /* Primary source: Texas Instruments, 74598 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls598.pdf
     https://en.wikipedia.org/wiki/Shift_register */
  // Complex: S1/S0 mode select. D0-D7 latched on RCK.
  // Mode 00: hold. Mode 01: shift right. Mode 10: parallel load. Mode 11: parallel out.
  '74x598': {
    name: '74x598',
    simpleName: '8 bit Shift Reg Sel (TRI)',
    description: '8-bit shift register, selectable parallel I/O, latches, 3-state (20-pin)',
    pins: 20,
    vcc: 20,
    gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls598.pdf',
    tags: ['shift register', 'latch', 'serial', 'parallel', '8 bit', 'sequential', 'tri state'],
    guideOverview: 'The 74x598 is an 8 bit shift register with selectable modes. S1/S0 control the operation: hold, shift right, parallel load from the input latch (captured on RCK), or parallel output onto the D bus. OEn enables the D bus output. Provides the most flexible shift register operation of the 74x59x family.',
    guidePinDescriptions: {
      'SER':  'Serial input for shift right mode.',
      'D0':   'Bidirectional data bus bit 0.',
      'D1':   'Bidirectional data bus bit 1.',
      'D2':   'Bidirectional data bus bit 2.',
      'D3':   'Bidirectional data bus bit 3.',
      'D4':   'Bidirectional data bus bit 4.',
      'D5':   'Bidirectional data bus bit 5.',
      'D6':   'Bidirectional data bus bit 6.',
      'D7':   'Bidirectional data bus bit 7.',
      'GND':  'Ground reference (pin 10).',
      'OEn':  'Output Enable for D0-D7 bus (active LOW).',
      'CLK':  'Shift register clock (rising edge).',
      'S0':   'Mode select bit 0.',
      'S1':   'Mode select bit 1.',
      'RCK':  'Register Clock for input latch.',
      'QH':   'Serial output bit H.',
      'QG':   'Serial output bit G.',
      'QF':   'Serial output bit F.',
      'QE':   'Serial output bit E.',
      'VCC':  'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'Mode Select',
        paragraphs: [
          'S1=0, S0=0: Hold. S1=0, S0=1: Shift right. S1=1, S0=0: Parallel load from latch. S1=1, S0=1: Parallel output to D bus.',
        ],
      },
    ],
    pinout: [
      { pin: 1,  name: 'SER',   type: 'input' },
      { pin: 2,  name: 'D0',    type: 'io' },
      { pin: 3,  name: 'D1',    type: 'io' },
      { pin: 4,  name: 'D2',    type: 'io' },
      { pin: 5,  name: 'D3',    type: 'io' },
      { pin: 6,  name: 'D4',    type: 'io' },
      { pin: 7,  name: 'D5',    type: 'io' },
      { pin: 8,  name: 'D6',    type: 'io' },
      { pin: 9,  name: 'D7',    type: 'io' },
      { pin: 10, name: 'GND',   type: 'power' },
      { pin: 11, name: 'OEn',   type: 'input' },
      { pin: 12, name: 'CLK',   type: 'input' },
      { pin: 13, name: 'S0',    type: 'input' },
      { pin: 14, name: 'S1',    type: 'input' },
      { pin: 15, name: 'RCK',   type: 'input' },
      { pin: 16, name: 'QH',    type: 'output' },
      { pin: 17, name: 'QG',    type: 'output' },
      { pin: 18, name: 'QF',    type: 'output' },
      { pin: 19, name: 'QE',    type: 'output' },
      { pin: 20, name: 'VCC',   type: 'power' },
    ],
    gates: [
      { type: 'SHIFT_REG_8BIT_SEL_TRI',
        inputs:  ['SER', 'CLK', 'RCK', 'S0', 'S1', 'OEn', 'D0', 'D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7'],
        outputs: ['D0', 'D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'QH'] },
    ],
    sequential: true,
  },

  // ── 74599: 8 bit SIPO shift register with output latches, OC ────────────
  /* Primary source: Texas Instruments, 74599 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls599.pdf
     https://en.wikipedia.org/wiki/Shift_register */
  // Like 74595 but OC outputs (no OEn tri state always drives low or HiZ by OC).
  // SRCLR=0: async clear SR. RCLR=0: async clear output reg.
  '74x599': {
    name: '74x599',
    simpleName: '8 bit Shift Reg+Latch (OC2)',
    description: '8-bit SIPO shift register, output latches, open-collector (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls599.pdf',
    tags: ['shift register', 'latch', 'serial', '8 bit', 'sequential', 'sipo', 'open collector'],
    guideOverview: 'The 74x599 is an 8 bit SIPO shift register with two stage output latch and open collector outputs. Similar to the 74x596 but replaces OEn with RCLR (output register clear, active LOW). Outputs are always enabled (OC style). SRCLR clears the shift register.',
    guidePinDescriptions: {
      'QB':    'OC output bit B.',
      'QC':    'OC output bit C.',
      'QD':    'OC output bit D.',
      'QE':    'OC output bit E.',
      'QF':    'OC output bit F.',
      'QG':    'OC output bit G.',
      'QH':    'OC output bit H.',
      'GND':   'Ground reference (pin 8).',
      'QHs':   'Serial cascade output.',
      'SRCLR': 'Shift Register Clear (active LOW).',
      'SRCLK': 'Shift Register Clock.',
      'RCLK':  'Output Register Clock.',
      'RCLR':  'Output Register Clear (active LOW). Clears output latch.',
      'SER':   'Serial input.',
      'QA':    'OC output bit A.',
      'VCC':   'Positive supply (+5 V, pin 16).',
    },
    guideSections: [
      {
        title: '74x596 vs 74x599',
        paragraphs: [
          'Both are OC SIPO registers. 74x596 has OEn (disable all outputs); 74x599 has RCLR (clear output latch asynchronously). Choose 74x599 when you need hardware reset of the output latch rather than high impedance.',
        ],
      },
    ],
    pinout: [
      { pin: 1,  name: 'QB',    type: 'output' },
      { pin: 2,  name: 'QC',    type: 'output' },
      { pin: 3,  name: 'QD',    type: 'output' },
      { pin: 4,  name: 'QE',    type: 'output' },
      { pin: 5,  name: 'QF',    type: 'output' },
      { pin: 6,  name: 'QG',    type: 'output' },
      { pin: 7,  name: 'QH',    type: 'output' },
      { pin: 8,  name: 'GND',   type: 'power' },
      { pin: 9,  name: 'QHs',   type: 'output' },
      { pin: 10, name: 'SRCLR', type: 'input' },
      { pin: 11, name: 'SRCLK', type: 'input' },
      { pin: 12, name: 'RCLK',  type: 'input' },
      { pin: 13, name: 'RCLR',  type: 'input' },
      { pin: 14, name: 'SER',   type: 'input' },
      { pin: 15, name: 'QA',    type: 'output' },
      { pin: 16, name: 'VCC',   type: 'power' },
    ],
    gates: [
      { type: 'SHIFT_REG_8BIT_LATCH_BUF',
        inputs:  ['SER', 'SRCLK', 'RCLK', 'SRCLR', 'RCLR'],
        outputs: ['QA', 'QB', 'QC', 'QD', 'QE', 'QF', 'QG', 'QH', 'QHs'] },
    ],
    sequential: true,
  },

  // ── 74600: DRAM refresh controller, 4K/16K, transparent+burst, TRI ───────
  /* Primary source: Texas Instruments, 74600 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls600.pdf
     https://en.wikipedia.org/wiki/Random-access_memory */
  '74x600': {
    name: '74x600',
    simpleName: 'DRAM Refresh 4K/16K (TRI)',
    description: '4K/16K DRAM refresh controller, transparent/burst modes (20-pin)',
    pins: 20,
    vcc: 20,
    gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls600.pdf',
    tags: ['dram', 'refresh', 'controller', 'memory'],
    guideOverview: 'The 74x600 is a DRAM refresh controller for 4K and 16K DRAM devices. It generates periodic RAS (Row Address Strobe) and CAS (Column Address Strobe) refresh cycles based on an input oscillator (OSC). BURST mode performs a run of refreshes back to back; transparent mode steals a single cycle. TC indicates terminal count of the refresh address counter.',
    guidePinDescriptions: {
      'OSC':   'Oscillator input. Controls refresh timing.',
      'IN0':   'Address input bit 0 for multiplexed address output.',
      'IN1':   'Address input bit 1.',
      'IN2':   'Address input bit 2.',
      'IN3':   'Address input bit 3.',
      'IN4':   'Address input bit 4.',
      'IN5':   'Address input bit 5.',
      'IN6':   'Address input bit 6.',
      'TC':    'Terminal Count output. HIGH when refresh counter wraps.',
      'GND':   'Ground reference (pin 10).',
      'RAS':   'Row Address Strobe output for DRAM.',
      'CAS':   'Column Address Strobe output for DRAM.',
      'RFSH':  'Refresh indicator output.',
      'BURST': 'Burst mode select. HIGH = run all refresh cycles consecutively.',
      'MR':    'Master Reset (active LOW).',
      'OUT4':  'Multiplexed address output bit 4.',
      'OUT5':  'Multiplexed address output bit 5.',
      'OUT6':  'Multiplexed address output bit 6.',
      'OEn':   'Output Enable (active LOW).',
      'VCC':   'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'DRAM Refresh',
        paragraphs: [
          'DRAM cells lose their charge if not periodically refreshed. The 74x600 automates this: it cycles through all row addresses, issuing RAS strobes. Burst mode does all refreshes in one block; transparent mode interleaves refreshes with normal memory access.',
        ],
      },
    ],
    pinout: [
      { pin: 1,  name: 'OSC',   type: 'input' },
      { pin: 2,  name: 'IN0',   type: 'input' },
      { pin: 3,  name: 'IN1',   type: 'input' },
      { pin: 4,  name: 'IN2',   type: 'input' },
      { pin: 5,  name: 'IN3',   type: 'input' },
      { pin: 6,  name: 'IN4',   type: 'input' },
      { pin: 7,  name: 'IN5',   type: 'input' },
      { pin: 8,  name: 'IN6',   type: 'input' },
      { pin: 9,  name: 'TC',    type: 'output' },
      { pin: 10, name: 'GND',   type: 'power' },
      { pin: 11, name: 'RAS',   type: 'output' },
      { pin: 12, name: 'CAS',   type: 'output' },
      { pin: 13, name: 'RFSH',  type: 'output' },
      { pin: 14, name: 'BURST', type: 'input' },
      { pin: 15, name: 'MR',    type: 'input' },
      { pin: 16, name: 'OUT4',  type: 'output' },
      { pin: 17, name: 'OUT5',  type: 'output' },
      { pin: 18, name: 'OUT6',  type: 'output' },
      { pin: 19, name: 'OEn',   type: 'input' },
      { pin: 20, name: 'VCC',   type: 'power' },
    ],
    gates: [
      { type: 'DRAM_REFRESH_STUB',
        inputs:  ['OSC', 'BURST', 'MR', 'OEn'],
        outputs: ['TC', 'RAS', 'CAS', 'RFSH'] },
    ],
    sequential: true,
  },

  // ── 74601: DRAM refresh controller, 64K, transparent+burst, TRI ──────────
  /* Primary source: Texas Instruments, 74601 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls601.pdf
     https://en.wikipedia.org/wiki/Random-access_memory */
  '74x601': {
    name: '74x601',
    simpleName: 'DRAM Refresh 64K (TRI)',
    description: '64K DRAM refresh controller, transparent/burst modes (20-pin)',
    pins: 20,
    vcc: 20,
    gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls601.pdf',
    tags: ['dram', 'refresh', 'controller', 'memory', '64k'],
    guideOverview: 'The 74x601 is a DRAM refresh controller for 64K DRAM devices. It requires a 7 bit row address counter (vs the 6 bit used for 4K/16K in the 74x600). All other features (BURST mode, transparent mode, RAS/CAS generation) are identical to the 74x600.',
    guidePinDescriptions: {
      'OSC':   'Oscillator input.',
      'IN0':   'Address input bit 0.',
      'IN1':   'Address input bit 1.',
      'IN2':   'Address input bit 2.',
      'IN3':   'Address input bit 3.',
      'IN4':   'Address input bit 4.',
      'IN5':   'Address input bit 5.',
      'IN6':   'Address input bit 6.',
      'TC':    'Terminal Count.',
      'GND':   'Ground reference (pin 10).',
      'RAS':   'Row Address Strobe.',
      'CAS':   'Column Address Strobe.',
      'RFSH':  'Refresh indicator.',
      'BURST': 'Burst mode select.',
      'MR':    'Master Reset.',
      'OUT4':  'Address output bit 4.',
      'OUT5':  'Address output bit 5.',
      'OUT6':  'Address output bit 6.',
      'OEn':   'Output Enable.',
      'VCC':   'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: '74x600 vs 74x601',
        paragraphs: [
          '74x600 handles 4K/16K DRAM (64 or 128 rows); 74x601 handles 64K DRAM (256 rows), requiring a 7 bit refresh counter. Choose based on the DRAM capacity in the system.',
        ],
      },
    ],
    pinout: [
      { pin: 1,  name: 'OSC',   type: 'input' },
      { pin: 2,  name: 'IN0',   type: 'input' },
      { pin: 3,  name: 'IN1',   type: 'input' },
      { pin: 4,  name: 'IN2',   type: 'input' },
      { pin: 5,  name: 'IN3',   type: 'input' },
      { pin: 6,  name: 'IN4',   type: 'input' },
      { pin: 7,  name: 'IN5',   type: 'input' },
      { pin: 8,  name: 'IN6',   type: 'input' },
      { pin: 9,  name: 'TC',    type: 'output' },
      { pin: 10, name: 'GND',   type: 'power' },
      { pin: 11, name: 'RAS',   type: 'output' },
      { pin: 12, name: 'CAS',   type: 'output' },
      { pin: 13, name: 'RFSH',  type: 'output' },
      { pin: 14, name: 'BURST', type: 'input' },
      { pin: 15, name: 'MR',    type: 'input' },
      { pin: 16, name: 'OUT4',  type: 'output' },
      { pin: 17, name: 'OUT5',  type: 'output' },
      { pin: 18, name: 'OUT6',  type: 'output' },
      { pin: 19, name: 'OEn',   type: 'input' },
      { pin: 20, name: 'VCC',   type: 'power' },
    ],
    gates: [
      { type: 'DRAM_REFRESH_STUB',
        inputs:  ['OSC', 'BURST', 'MR', 'OEn'],
        outputs: ['TC', 'RAS', 'CAS', 'RFSH'] },
    ],
    sequential: true,
  },

  // ── 74602: DRAM refresh controller, 4K/16K, cycle steal + burst, TRI ─────
  /* Primary source: Texas Instruments, 74602 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls602.pdf
     https://en.wikipedia.org/wiki/Random-access_memory */
  '74x602': {
    name: '74x602',
    simpleName: 'DRAM Refresh 4K/16K CS (TRI)',
    description: '4K/16K DRAM refresh controller, cycle-steal/burst modes (20-pin)',
    pins: 20,
    vcc: 20,
    gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls602.pdf',
    tags: ['dram', 'refresh', 'controller', 'memory', 'cycle-steal'],
    guideOverview: 'The 74x602 is a DRAM refresh controller for 4K/16K DRAM using cycle steal mode. Unlike transparent mode, cycle steal actively halts the CPU bus to perform a refresh cycle. BURST mode runs consecutive refreshes. Pin compatible with 74x600 but with different internal refresh arbitration logic.',
    guidePinDescriptions: {
      'OSC':   'Oscillator input.',
      'IN0':   'Address input bit 0.',
      'IN1':   'Address input bit 1.',
      'IN2':   'Address input bit 2.',
      'IN3':   'Address input bit 3.',
      'IN4':   'Address input bit 4.',
      'IN5':   'Address input bit 5.',
      'IN6':   'Address input bit 6.',
      'TC':    'Terminal Count.',
      'GND':   'Ground reference (pin 10).',
      'RAS':   'Row Address Strobe.',
      'CAS':   'Column Address Strobe.',
      'RFSH':  'Refresh indicator.',
      'BURST': 'Burst mode select.',
      'MR':    'Master Reset.',
      'OUT4':  'Address output bit 4.',
      'OUT5':  'Address output bit 5.',
      'OUT6':  'Address output bit 6.',
      'OEn':   'Output Enable.',
      'VCC':   'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'Cycle Steal vs Transparent Refresh',
        paragraphs: [
          'Cycle steal refresh asserts a HOLD/WAIT signal to the CPU, pausing the bus for one cycle to perform a refresh. Transparent mode attempts to sneak a refresh into unused bus cycles without stalling the CPU.',
        ],
      },
    ],
    pinout: [
      { pin: 1,  name: 'OSC',   type: 'input' },
      { pin: 2,  name: 'IN0',   type: 'input' },
      { pin: 3,  name: 'IN1',   type: 'input' },
      { pin: 4,  name: 'IN2',   type: 'input' },
      { pin: 5,  name: 'IN3',   type: 'input' },
      { pin: 6,  name: 'IN4',   type: 'input' },
      { pin: 7,  name: 'IN5',   type: 'input' },
      { pin: 8,  name: 'IN6',   type: 'input' },
      { pin: 9,  name: 'TC',    type: 'output' },
      { pin: 10, name: 'GND',   type: 'power' },
      { pin: 11, name: 'RAS',   type: 'output' },
      { pin: 12, name: 'CAS',   type: 'output' },
      { pin: 13, name: 'RFSH',  type: 'output' },
      { pin: 14, name: 'BURST', type: 'input' },
      { pin: 15, name: 'MR',    type: 'input' },
      { pin: 16, name: 'OUT4',  type: 'output' },
      { pin: 17, name: 'OUT5',  type: 'output' },
      { pin: 18, name: 'OUT6',  type: 'output' },
      { pin: 19, name: 'OEn',   type: 'input' },
      { pin: 20, name: 'VCC',   type: 'power' },
    ],
    gates: [
      { type: 'DRAM_REFRESH_STUB',
        inputs:  ['OSC', 'BURST', 'MR', 'OEn'],
        outputs: ['TC', 'RAS', 'CAS', 'RFSH'] },
    ],
    sequential: true,
  },

  // ── 74603: DRAM refresh controller, 64K, cycle steal + burst, TRI ────────
  /* Primary source: Texas Instruments, 74603 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls603.pdf
     https://en.wikipedia.org/wiki/Random-access_memory */
  '74x603': {
    name: '74x603',
    simpleName: 'DRAM Refresh 64K CS (TRI)',
    description: '64K DRAM refresh controller, cycle-steal/burst modes (20-pin)',
    pins: 20,
    vcc: 20,
    gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls603.pdf',
    tags: ['dram', 'refresh', 'controller', 'memory', '64k', 'cycle-steal'],
    guideOverview: 'The 74x603 is the 64K DRAM version of the cycle steal refresh controller (74x602). It handles 256 row refresh cycles for 64K DRAM. Cycle steal mode halts the CPU for each refresh; BURST performs all refreshes consecutively.',
    guidePinDescriptions: {
      'OSC':   'Oscillator input.',
      'IN0':   'Address input bit 0.',
      'IN1':   'Address input bit 1.',
      'IN2':   'Address input bit 2.',
      'IN3':   'Address input bit 3.',
      'IN4':   'Address input bit 4.',
      'IN5':   'Address input bit 5.',
      'IN6':   'Address input bit 6.',
      'TC':    'Terminal Count.',
      'GND':   'Ground reference (pin 10).',
      'RAS':   'Row Address Strobe.',
      'CAS':   'Column Address Strobe.',
      'RFSH':  'Refresh indicator.',
      'BURST': 'Burst mode.',
      'MR':    'Master Reset.',
      'OUT4':  'Address output bit 4.',
      'OUT5':  'Address output bit 5.',
      'OUT6':  'Address output bit 6.',
      'OEn':   'Output Enable.',
      'VCC':   'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'DRAM Refresh Family',
        list: [
          '74x600: 4K/16K, transparent mode',
          '74x601: 64K, transparent mode',
          '74x602: 4K/16K, cycle steal mode',
          '74x603: 64K, cycle steal mode',
        ],
      },
    ],
    pinout: [
      { pin: 1,  name: 'OSC',   type: 'input' },
      { pin: 2,  name: 'IN0',   type: 'input' },
      { pin: 3,  name: 'IN1',   type: 'input' },
      { pin: 4,  name: 'IN2',   type: 'input' },
      { pin: 5,  name: 'IN3',   type: 'input' },
      { pin: 6,  name: 'IN4',   type: 'input' },
      { pin: 7,  name: 'IN5',   type: 'input' },
      { pin: 8,  name: 'IN6',   type: 'input' },
      { pin: 9,  name: 'TC',    type: 'output' },
      { pin: 10, name: 'GND',   type: 'power' },
      { pin: 11, name: 'RAS',   type: 'output' },
      { pin: 12, name: 'CAS',   type: 'output' },
      { pin: 13, name: 'RFSH',  type: 'output' },
      { pin: 14, name: 'BURST', type: 'input' },
      { pin: 15, name: 'MR',    type: 'input' },
      { pin: 16, name: 'OUT4',  type: 'output' },
      { pin: 17, name: 'OUT5',  type: 'output' },
      { pin: 18, name: 'OUT6',  type: 'output' },
      { pin: 19, name: 'OEn',   type: 'input' },
      { pin: 20, name: 'VCC',   type: 'power' },
    ],
    gates: [
      { type: 'DRAM_REFRESH_STUB',
        inputs:  ['OSC', 'BURST', 'MR', 'OEn'],
        outputs: ['TC', 'RAS', 'CAS', 'RFSH'] },
    ],
    sequential: true,
  },

  // ── 74608: Memory cycle controller ───────────────────────────────────────
  /* Primary source: Texas Instruments, 74608 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls608.pdf
     https://en.wikipedia.org/wiki/Random-access_memory */
  '74x608': {
    name: '74x608',
    simpleName: 'Memory Cycle Ctrl',
    description: 'Memory cycle controller (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls608.pdf',
    tags: ['memory', 'controller', 'cycle'],
    guideOverview: 'The 74x608 is a memory cycle controller that generates control signals (CS, OE, WE, WAIT) from CPU address and RD/WR signals. EN1 and EN2 enable the decode; CLK synchronizes cycle generation; MR resets the state machine. Useful for glue logic between a CPU and SRAM or EPROM in a breadboard microcomputer.',
    guidePinDescriptions: {
      'A0':   'Address input bit 0.',
      'A1':   'Address input bit 1.',
      'A2':   'Address input bit 2.',
      'A3':   'Address input bit 3.',
      'EN1':  'Enable 1 (active HIGH).',
      'EN2':  'Enable 2 (active LOW).',
      'RD':   'Read strobe from CPU.',
      'GND':  'Ground reference (pin 8).',
      'WR':   'Write strobe from CPU.',
      'CS':   'Chip Select output for memory device.',
      'OE':   'Output Enable output for memory device.',
      'WE':   'Write Enable output for memory device.',
      'CLK':  'Clock for cycle synchronization.',
      'MR':   'Master Reset.',
      'WAIT': 'Wait output to CPU (extends bus cycle).',
      'VCC':  'Positive supply (+5 V, pin 16).',
    },
    guideSections: [
      {
        title: 'Memory Bus Glue Logic',
        paragraphs: [
          'The 74x608 reduces the discrete logic needed to interface a CPU to memory by integrating address decode, read/write qualification, and wait state generation into one chip.',
        ],
        note: 'Simplification: 74Sim models only the combinational enable path — CS goes active (LOW) when EN1=EN2=LOW and MR=HIGH; OE follows CS AND RD; WE follows CS AND WR. The address inputs A0..A3, the CLK-synchronised cycle state machine, and wait-state generation are not modelled — WAIT is always held inactive (HIGH).',
      },
    ],
    pinout: [
      { pin: 1,  name: 'A0',  type: 'input' },
      { pin: 2,  name: 'A1',  type: 'input' },
      { pin: 3,  name: 'A2',  type: 'input' },
      { pin: 4,  name: 'A3',  type: 'input' },
      { pin: 5,  name: 'EN1', type: 'input' },
      { pin: 6,  name: 'EN2', type: 'input' },
      { pin: 7,  name: 'RD',  type: 'input' },
      { pin: 8,  name: 'GND', type: 'power' },
      { pin: 9,  name: 'WR',  type: 'input' },
      { pin: 10, name: 'CS',  type: 'output' },
      { pin: 11, name: 'OE',  type: 'output' },
      { pin: 12, name: 'WE',  type: 'output' },
      { pin: 13, name: 'CLK', type: 'input' },
      { pin: 14, name: 'MR',  type: 'input' },
      { pin: 15, name: 'WAIT',type: 'output' },
      { pin: 16, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'MEM_CYCLE_CTRL',
        inputs:  ['A0', 'A1', 'A2', 'A3', 'EN1', 'EN2', 'RD', 'WR', 'CLK', 'MR'],
        outputs: ['CS', 'OE', 'WE', 'WAIT'] },
    ],
    sequential: true,
  },

  // ── 74614: Octal bus transceiver and register, inverting, OC ─────────────
  /* Primary source: Texas Instruments, 74614 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74als614.pdf
     https://en.wikipedia.org/wiki/Bus_transceiver */
  // Like 74566 (TRANSCEIVER_OCTAL_REG_INV) but with open collector outputs.
  // DIR=1: A→B direction; DIR=0: B→A direction.
  // CLK: register clock. OEABn=0: enables A→B path; OEBAn=0: enables B→A.
  '74x614': {
    name: '74x614',
    simpleName: 'Octal Reg Xcvr Inv (OC)',
    description: 'Octal bus transceiver/register, inverting open-collector out (24-pin)',
    pins: 24,
    vcc: 24,
    gnd: 12,
    openCollector: true,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74als614.pdf',
    tags: ['transceiver', 'registered', 'bidirectional', 'inverting', 'octal', 'open collector'],
    guideOverview: 'The 74x614 is an octal registered bidirectional transceiver with inverting open collector outputs. It has the same OEABn/OEBAn/LEAB/LEBA/CLK/DIR control structure as the 74x566 (tri state), but outputs are open collector. External pull up resistors are required. Useful for wired AND bus designs.',
    guidePinDescriptions: {
      'OEABn': 'A-to B Output Enable (active LOW).',
      'OEBAn': 'B-to A Output Enable (active LOW).',
      'LEAB':  'Latch Enable A-to B.',
      'LEBA':  'Latch Enable B-to A.',
      'CLK':   'Register clock.',
      'DIR':   'Direction select.',
      'A0':    'Port A bit 0.',
      'A1':    'Port A bit 1.',
      'A2':    'Port A bit 2.',
      'A3':    'Port A bit 3.',
      'A4':    'Port A bit 4.',
      'GND':   'Ground reference (pin 12).',
      'A5':    'Port A bit 5.',
      'A6':    'Port A bit 6.',
      'A7':    'Port A bit 7.',
      'B0':    'Port B bit 0.',
      'B1':    'Port B bit 1.',
      'B2':    'Port B bit 2.',
      'B3':    'Port B bit 3.',
      'B4':    'Port B bit 4.',
      'B5':    'Port B bit 5.',
      'B6':    'Port B bit 6.',
      'B7':    'Port B bit 7.',
      'VCC':   'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: '74x566 vs 74x614',
        paragraphs: [
          '74x566 has tri state outputs; 74x614 has open collector. Both invert data and use the same LEAB/LEBA/CLK/DIR control scheme. Use 74x614 for wired AND multi master bus architectures.',
        ],
        note: 'External pull up resistors required on all bidirectional A/B pins.',
      },
    ],
    pinout: [
      { pin: 1,  name: 'OEABn', type: 'input' },
      { pin: 2,  name: 'OEBAn', type: 'input' },
      { pin: 3,  name: 'LEAB',  type: 'input' },
      { pin: 4,  name: 'LEBA',  type: 'input' },
      { pin: 5,  name: 'CLK',   type: 'input' },
      { pin: 6,  name: 'DIR',   type: 'input' },
      { pin: 7,  name: 'A0',    type: 'io' },
      { pin: 8,  name: 'A1',    type: 'io' },
      { pin: 9,  name: 'A2',    type: 'io' },
      { pin: 10, name: 'A3',    type: 'io' },
      { pin: 11, name: 'A4',    type: 'io' },
      { pin: 12, name: 'GND',   type: 'power' },
      { pin: 13, name: 'A5',    type: 'io' },
      { pin: 14, name: 'A6',    type: 'io' },
      { pin: 15, name: 'A7',    type: 'io' },
      { pin: 16, name: 'B0',    type: 'io' },
      { pin: 17, name: 'B1',    type: 'io' },
      { pin: 18, name: 'B2',    type: 'io' },
      { pin: 19, name: 'B3',    type: 'io' },
      { pin: 20, name: 'B4',    type: 'io' },
      { pin: 21, name: 'B5',    type: 'io' },
      { pin: 22, name: 'B6',    type: 'io' },
      { pin: 23, name: 'B7',    type: 'io' },
      { pin: 24, name: 'VCC',   type: 'power' },
    ],
    gates: [
      { type: 'TRANSCEIVER_OCTAL_REG_INV',
        inputs:  ['OEABn', 'OEBAn', 'LEAB', 'LEBA', 'CLK', 'DIR',
                  'A0', 'A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7',
                  'B0', 'B1', 'B2', 'B3', 'B4', 'B5', 'B6', 'B7'],
        outputs: ['A0', 'A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7',
                  'B0', 'B1', 'B2', 'B3', 'B4', 'B5', 'B6', 'B7'] },
    ],
    sequential: true,
  },

};
