// Chip definitions block 31
// 74x564   74x588

export const CHIPS_BLOCK_31 = {

  // ── 74564: Octal D type edge triggered flip flop, inverting outputs ──────
  /* Primary source: Texas Instruments, 74564 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74als564b.pdf
     https://en.wikipedia.org/wiki/Flip-flop_(electronics) */
  '74x564': {
    name: '74x564',
    simpleName: 'Octal FF Inv (TRI)',
    description: 'Octal D-type edge-triggered flip-flop, inverting, 3-state (20-pin)',
    pins: 20,
    vcc: 20,
    gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74als564b.pdf',
    tags: ['flip flop', 'octal', 'register', 'inverting', 'tri state'],
    guideOverview: 'The 74x564 is an octal D type edge triggered flip flop with inverting outputs and tri state output control. On each rising edge of CLK, each output Qn is set to the complement of the corresponding D input. OE (active LOW) enables all outputs; negating it (HIGH) tri states them. It is the inverting complement of the 74x574.',
    guidePinDescriptions: {
      'OEn': 'Output Enable (active LOW). Tri states all Qn outputs when negated (HIGH).',
      'D0':  'Data input 0.',
      'D1':  'Data input 1.',
      'D2':  'Data input 2.',
      'D3':  'Data input 3.',
      'D4':  'Data input 4.',
      'D5':  'Data input 5.',
      'D6':  'Data input 6.',
      'D7':  'Data input 7.',
      'GND': 'Ground reference (pin 10).',
      'CLK': 'Clock (rising edge). Captures all D inputs simultaneously.',
      'Qn0': 'Inverted register output 0.',
      'Qn1': 'Inverted register output 1.',
      'Qn2': 'Inverted register output 2.',
      'Qn3': 'Inverted register output 3.',
      'Qn4': 'Inverted register output 4.',
      'Qn5': 'Inverted register output 5.',
      'Qn6': 'Inverted register output 6.',
      'Qn7': 'Inverted register output 7.',
      'VCC': 'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'Inverting Octal Register',
        paragraphs: [
          'The inverting output makes the 74x564 useful when the downstream logic requires active LOW signals, saving an inverter stage on the bus. It is otherwise pin compatible with the 74x574.',
        ],
      },
    ],
    pinout: [
      { pin: 1,  name: 'OEn', type: 'input' },
      { pin: 2,  name: 'D0',  type: 'input' },
      { pin: 3,  name: 'D1',  type: 'input' },
      { pin: 4,  name: 'D2',  type: 'input' },
      { pin: 5,  name: 'D3',  type: 'input' },
      { pin: 6,  name: 'D4',  type: 'input' },
      { pin: 7,  name: 'D5',  type: 'input' },
      { pin: 8,  name: 'D6',  type: 'input' },
      { pin: 9,  name: 'D7',  type: 'input' },
      { pin: 10, name: 'GND', type: 'power' },
      { pin: 11, name: 'CLK', type: 'input' },
      { pin: 12, name: 'Qn0', type: 'output' },
      { pin: 13, name: 'Qn1', type: 'output' },
      { pin: 14, name: 'Qn2', type: 'output' },
      { pin: 15, name: 'Qn3', type: 'output' },
      { pin: 16, name: 'Qn4', type: 'output' },
      { pin: 17, name: 'Qn5', type: 'output' },
      { pin: 18, name: 'Qn6', type: 'output' },
      { pin: 19, name: 'Qn7', type: 'output' },
      { pin: 20, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'REG_OCTAL_INV_TRI',
        inputs:  ['OEn','CLK','D0','D1','D2','D3','D4','D5','D6','D7'],
        outputs: ['Qn0','Qn1','Qn2','Qn3','Qn4','Qn5','Qn6','Qn7'] },
    ],
  },

  // ── 74566: 8 bit bidirectional registered transceiver, inverting ─────────
  /* Primary source: Texas Instruments, 74566 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls566.pdf
     https://en.wikipedia.org/wiki/Bus_transceiver */
  '74x566': {
    name: '74x566',
    simpleName: 'Octal Reg Xcvr Inv (TRI)',
    description: '8-bit bidirectional registered transceiver, inverting 3-state (24-pin)',
    pins: 24,
    vcc: 24,
    gnd: 12,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls566.pdf',
    tags: ['transceiver', 'registered', 'bidirectional', 'inverting', 'octal', 'tri state'],
    guideOverview: 'The 74x566 is an 8 bit bidirectional registered transceiver with inverting outputs. It is the inverting output version of the 74x546. LEAB and LEBA are latch enables for the two directions; CLK registers the latch output; DIR and OEABn/OEBAn control direction and bus drives. Data is inverted through the register path.',
    guidePinDescriptions: {
      'OEABn': 'A-to B Output Enable (active LOW).',
      'OEBAn': 'B-to A Output Enable (active LOW).',
      'LEAB':  'Latch Enable A-to B.',
      'LEBA':  'Latch Enable B-to A.',
      'CLK':   'Clock for register capture.',
      'DIR':   'Direction select.',
      'A0':    'Port A bit 0.',
      'A1':    'Port A bit 1.',
      'A2':    'Port A bit 2.',
      'A3':    'Port A bit 3.',
      'A4':    'Port A bit 4.',
      'GND':   'Ground reference (pin 12).',
      'A5':    'Port A bit 5.',
      'A6':    'Port A bit 6.',
      'A7':    'Port A bit 7.',
      'B0':    'Port B bit 0.',
      'B1':    'Port B bit 1.',
      'B2':    'Port B bit 2.',
      'B3':    'Port B bit 3.',
      'B4':    'Port B bit 4.',
      'B5':    'Port B bit 5.',
      'B6':    'Port B bit 6.',
      'B7':    'Port B bit 7.',
      'VCC':   'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: 'Inverting vs Non Inverting Registered Transceiver',
        paragraphs: [
          '74x546 passes data unchanged; 74x566 inverts it. Use 74x566 when the receiving bus uses complemented logic or to avoid external inverter stages.',
        ],
      },
    ],
    pinout: [
      { pin: 1,  name: 'OEABn', type: 'input' },
      { pin: 2,  name: 'OEBAn', type: 'input' },
      { pin: 3,  name: 'LEAB',  type: 'input' },
      { pin: 4,  name: 'LEBA',  type: 'input' },
      { pin: 5,  name: 'CLK',   type: 'input' },
      { pin: 6,  name: 'DIR',   type: 'input' },
      { pin: 7,  name: 'A0',    type: 'io' },
      { pin: 8,  name: 'A1',    type: 'io' },
      { pin: 9,  name: 'A2',    type: 'io' },
      { pin: 10, name: 'A3',    type: 'io' },
      { pin: 11, name: 'A4',    type: 'io' },
      { pin: 12, name: 'GND',   type: 'power' },
      { pin: 13, name: 'A5',    type: 'io' },
      { pin: 14, name: 'A6',    type: 'io' },
      { pin: 15, name: 'A7',    type: 'io' },
      { pin: 16, name: 'B0',    type: 'io' },
      { pin: 17, name: 'B1',    type: 'io' },
      { pin: 18, name: 'B2',    type: 'io' },
      { pin: 19, name: 'B3',    type: 'io' },
      { pin: 20, name: 'B4',    type: 'io' },
      { pin: 21, name: 'B5',    type: 'io' },
      { pin: 22, name: 'B6',    type: 'io' },
      { pin: 23, name: 'B7',    type: 'io' },
      { pin: 24, name: 'VCC',   type: 'power' },
    ],
    gates: [
      { type: 'TRANSCEIVER_OCTAL_REG_INV',
        inputs:  ['OEABn','OEBAn','LEAB','LEBA','CLK','DIR',
                  'A0','A1','A2','A3','A4','A5','A6','A7',
                  'B0','B1','B2','B3','B4','B5','B6','B7'],
        outputs: ['A0','A1','A2','A3','A4','A5','A6','A7',
                  'B0','B1','B2','B3','B4','B5','B6','B7'] },
    ],
  },

  // ── 74567: 8 bit bidirectional latched transceiver, inverting ───────────
  /* Primary source: Texas Instruments, 74567 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls567.pdf
     https://en.wikipedia.org/wiki/Flip-flop_(electronics) */
  '74x567': {
    name: '74x567',
    simpleName: 'Octal Latch Xcvr Inv (TRI)',
    description: '8-bit bidirectional latched transceiver, inverting 3-state (24-pin)',
    pins: 24,
    vcc: 24,
    gnd: 12,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls567.pdf',
    tags: ['transceiver', 'latch', 'bidirectional', 'inverting', 'octal', 'tri state'],
    guideOverview: 'The 74x567 is an 8 bit bidirectional latched transceiver with inverting outputs. It is the inverting version of the 74x547. LEAB/LEBA are level triggered (transparent when HIGH); there is no separate CLK. All data paths invert through the latch.',
    guidePinDescriptions: {
      'OEABn': 'A-to B Output Enable (active LOW).',
      'OEBAn': 'B-to A Output Enable (active LOW).',
      'LEAB':  'Latch Enable A-to B. HIGH = transparent.',
      'LEBA':  'Latch Enable B-to A.',
      'DIR':   'Direction select.',
      'A0':    'Port A bit 0.',
      'A1':    'Port A bit 1.',
      'A2':    'Port A bit 2.',
      'A3':    'Port A bit 3.',
      'A4':    'Port A bit 4.',
      'A5':    'Port A bit 5.',
      'GND':   'Ground reference (pin 12).',
      'A6':    'Port A bit 6.',
      'A7':    'Port A bit 7.',
      'B0':    'Port B bit 0.',
      'B1':    'Port B bit 1.',
      'B2':    'Port B bit 2.',
      'B3':    'Port B bit 3.',
      'B4':    'Port B bit 4.',
      'B5':    'Port B bit 5.',
      'B6':    'Port B bit 6.',
      'B7':    'Port B bit 7.',
      'NC':    'No connect (pin 23).',
      'VCC':   'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: 'Latched vs Registered Inverting Transceiver',
        paragraphs: [
          '74x567 (latch) is transparent when LEAB/LEBA are HIGH; 74x566 (registered) requires a CLK edge. Use 74x567 when asynchronous transparent operation is needed.',
        ],
      },
    ],
    pinout: [
      { pin: 1,  name: 'OEABn', type: 'input' },
      { pin: 2,  name: 'OEBAn', type: 'input' },
      { pin: 3,  name: 'LEAB',  type: 'input' },
      { pin: 4,  name: 'LEBA',  type: 'input' },
      { pin: 5,  name: 'DIR',   type: 'input' },
      { pin: 6,  name: 'A0',    type: 'io' },
      { pin: 7,  name: 'A1',    type: 'io' },
      { pin: 8,  name: 'A2',    type: 'io' },
      { pin: 9,  name: 'A3',    type: 'io' },
      { pin: 10, name: 'A4',    type: 'io' },
      { pin: 11, name: 'A5',    type: 'io' },
      { pin: 12, name: 'GND',   type: 'power' },
      { pin: 13, name: 'A6',    type: 'io' },
      { pin: 14, name: 'A7',    type: 'io' },
      { pin: 15, name: 'B0',    type: 'io' },
      { pin: 16, name: 'B1',    type: 'io' },
      { pin: 17, name: 'B2',    type: 'io' },
      { pin: 18, name: 'B3',    type: 'io' },
      { pin: 19, name: 'B4',    type: 'io' },
      { pin: 20, name: 'B5',    type: 'io' },
      { pin: 21, name: 'B6',    type: 'io' },
      { pin: 22, name: 'B7',    type: 'io' },
      { pin: 23, name: 'NC',    type: 'nc' },
      { pin: 24, name: 'VCC',   type: 'power' },
    ],
    gates: [
      { type: 'TRANSCEIVER_OCTAL_LATCH_INV',
        inputs:  ['OEABn','OEBAn','LEAB','LEBA','DIR',
                  'A0','A1','A2','A3','A4','A5','A6','A7',
                  'B0','B1','B2','B3','B4','B5','B6','B7'],
        outputs: ['A0','A1','A2','A3','A4','A5','A6','A7',
                  'B0','B1','B2','B3','B4','B5','B6','B7'] },
    ],
  },

  // ── 74568: Decade up/down counter, tri state ────────────────────────────
  /* Primary source: Texas Instruments, 74568 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74als568a.pdf
     https://en.wikipedia.org/wiki/Counter_(digital) */
  '74x568': {
    name: '74x568',
    simpleName: 'Decade Up/Down Ctr (TRI)',
    description: 'Synchronous 4 bit decade up/down counter with tri state outputs (20-pin)',
    pins: 20,
    vcc: 20,
    gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74als568a.pdf',
    tags: ['counter', 'decade', 'up-down', 'synchronous', 'tri state'],
    guideOverview: 'The 74x568 is a synchronous 4 bit BCD (decade) up/down counter with tri state outputs. U_Dn HIGH = count up, LOW = count down. ENP and ENT both HIGH enable counting; LOAD loads the parallel A-D inputs; CLRn (active LOW) synchronously clears on the next CLK edge. RCO carries for multi digit cascading.',
    guidePinDescriptions: {
      'CLRn':  'Synchronous Clear (active LOW). Clears counter on next CLK edge.',
      'CLK':   'Clock (rising edge).',
      'U_Dn':  'Up/Down select. HIGH = count up; LOW = count down.',
      'ENP':   'Count Enable Parallel. Both ENP and ENT must be HIGH to count.',
      'A':     'Parallel load input A (LSB).',
      'B':     'Parallel load input B.',
      'C':     'Parallel load input C.',
      'D':     'Parallel load input D (MSB).',
      'ENT':   'Count Enable Trickle. Also gates RCO.',
      'GND':   'Ground reference (pin 10).',
      'LOAD':  'Parallel Load (active LOW). Loads A-D on next CLK.',
      'OEn':   'Output Enable (active LOW).',
      'RCO':   'Ripple Carry Output for cascade.',
      'QD':    'Counter output D.',
      'QC':    'Counter output C.',
      'QB':    'Counter output B.',
      'QA':    'Counter output A.',
      'NC':    'No connect.',
      'NC2':   'No connect.',
      'VCC':   'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'Up/Down BCD Counter',
        paragraphs: [
          'The up/down capability enables presettable timer and event counting circuits. For a down counter, preload the starting value via LOAD; the counter decrements to 0 and then rolls over to 9.',
        ],
      },
    ],
    pinout: [
      { pin: 1,  name: 'CLRn',  type: 'input' },
      { pin: 2,  name: 'CLK',   type: 'input' },
      { pin: 3,  name: 'U_Dn',  type: 'input' },
      { pin: 4,  name: 'ENP',   type: 'input' },
      { pin: 5,  name: 'A',     type: 'input' },
      { pin: 6,  name: 'B',     type: 'input' },
      { pin: 7,  name: 'C',     type: 'input' },
      { pin: 8,  name: 'D',     type: 'input' },
      { pin: 9,  name: 'ENT',   type: 'input' },
      { pin: 10, name: 'GND',   type: 'power' },
      { pin: 11, name: 'LOAD',  type: 'input' },
      { pin: 12, name: 'OEn',   type: 'input' },
      { pin: 13, name: 'RCO',   type: 'output' },
      { pin: 14, name: 'QD',    type: 'output' },
      { pin: 15, name: 'QC',    type: 'output' },
      { pin: 16, name: 'QB',    type: 'output' },
      { pin: 17, name: 'QA',    type: 'output' },
      { pin: 18, name: 'NC',    type: 'nc' },
      { pin: 19, name: 'NC2',   type: 'nc' },
      { pin: 20, name: 'VCC',   type: 'power' },
    ],
    gates: [
      { type: 'COUNTER_SYNC_DECADE_UPDOWN_TRI',
        inputs:  ['CLRn','CLK','U_Dn','ENP','A','B','C','D','ENT','LOAD','OEn'],
        outputs: ['QA','QB','QC','QD','RCO'] },
    ],
  },

  // ── 74569: Binary up/down counter, tri state ────────────────────────────
  /* Primary source: Texas Instruments, 74569 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74als569a.pdf
     https://en.wikipedia.org/wiki/Counter_(digital) */
  '74x569': {
    name: '74x569',
    simpleName: 'Binary Up/Down Ctr (TRI)',
    description: 'Synchronous 4 bit binary up/down counter with tri state outputs (20-pin)',
    pins: 20,
    vcc: 20,
    gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74als569a.pdf',
    tags: ['counter', 'binary', 'up-down', 'synchronous', 'tri state'],
    guideOverview: 'The 74x569 is the binary version of the 74x568, counting 0-15 (modulo-16) rather than 0-9. Same synchronous up/down control, ENP/ENT enables, parallel load, synchronous clear (CLRn active LOW), and tri state outputs. RCO cascades for wider counters.',
    guidePinDescriptions: {
      'CLRn':  'Synchronous Clear (active LOW).',
      'CLK':   'Clock (rising edge).',
      'U_Dn':  'Up/Down select.',
      'ENP':   'Count Enable Parallel.',
      'A':     'Parallel load input A.',
      'B':     'Parallel load input B.',
      'C':     'Parallel load input C.',
      'D':     'Parallel load input D.',
      'ENT':   'Count Enable Trickle.',
      'GND':   'Ground reference (pin 10).',
      'LOAD':  'Parallel Load (active LOW).',
      'OEn':   'Output Enable (active LOW).',
      'RCO':   'Ripple Carry Output.',
      'QD':    'Counter output D (MSB).',
      'QC':    'Counter output C.',
      'QB':    'Counter output B.',
      'QA':    'Counter output A (LSB).',
      'NC':    'No connect.',
      'NC2':   'No connect.',
      'VCC':   'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: '74x568 vs 74x569',
        paragraphs: [
          '74x568 is decade (BCD, 0-9); 74x569 is binary (0-15). Choose 74x568 for decimal display applications; 74x569 for general purpose power of-2 counting.',
        ],
      },
    ],
    pinout: [
      { pin: 1,  name: 'CLRn',  type: 'input' },
      { pin: 2,  name: 'CLK',   type: 'input' },
      { pin: 3,  name: 'U_Dn',  type: 'input' },
      { pin: 4,  name: 'ENP',   type: 'input' },
      { pin: 5,  name: 'A',     type: 'input' },
      { pin: 6,  name: 'B',     type: 'input' },
      { pin: 7,  name: 'C',     type: 'input' },
      { pin: 8,  name: 'D',     type: 'input' },
      { pin: 9,  name: 'ENT',   type: 'input' },
      { pin: 10, name: 'GND',   type: 'power' },
      { pin: 11, name: 'LOAD',  type: 'input' },
      { pin: 12, name: 'OEn',   type: 'input' },
      { pin: 13, name: 'RCO',   type: 'output' },
      { pin: 14, name: 'QD',    type: 'output' },
      { pin: 15, name: 'QC',    type: 'output' },
      { pin: 16, name: 'QB',    type: 'output' },
      { pin: 17, name: 'QA',    type: 'output' },
      { pin: 18, name: 'NC',    type: 'nc' },
      { pin: 19, name: 'NC2',   type: 'nc' },
      { pin: 20, name: 'VCC',   type: 'power' },
    ],
    gates: [
      { type: 'COUNTER_SYNC_BIN_UPDOWN_TRI',
        inputs:  ['CLRn','CLK','U_Dn','ENP','A','B','C','D','ENT','LOAD','OEn'],
        outputs: ['QA','QB','QC','QD','RCO'] },
    ],
  },

  // ── 74575: Octal D type FF, synchronous clear, tri state ────────────────
  /* Primary source: Texas Instruments, 74575 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74als575a.pdf
     https://en.wikipedia.org/wiki/Flip-flop_(electronics) */
  '74x575': {
    name: '74x575',
    simpleName: 'Octal FF Sync CLR (TRI)',
    description: 'Octal D-type edge-triggered flip-flop, sync clear, 3-state (24-pin)',
    pins: 24,
    vcc: 24,
    gnd: 12,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74als575a.pdf',
    tags: ['flip flop', 'octal', 'register', 'synchronous-clear', 'tri state'],
    guideOverview: 'The 74x575 is an octal D type edge triggered flip flop with synchronous clear and tri state outputs. CLRn (active LOW) on the rising CLK edge resets all outputs to 0. OE (active LOW) enables the Q outputs. The 24-pin package provides 3 NC pins for mechanical compatibility.',
    guidePinDescriptions: {
      'OEn':  'Output Enable (active LOW).',
      'CLRn': 'Synchronous Clear (active LOW). Clears to 0 on rising CLK edge.',
      'D0':   'Data input 0.',
      'D1':   'Data input 1.',
      'D2':   'Data input 2.',
      'D3':   'Data input 3.',
      'D4':   'Data input 4.',
      'D5':   'Data input 5.',
      'D6':   'Data input 6.',
      'D7':   'Data input 7.',
      'CLK':  'Clock (rising edge).',
      'GND':  'Ground reference (pin 12).',
      'Q0':   'Register output 0.',
      'Q1':   'Register output 1.',
      'Q2':   'Register output 2.',
      'Q3':   'Register output 3.',
      'Q4':   'Register output 4.',
      'Q5':   'Register output 5.',
      'Q6':   'Register output 6.',
      'Q7':   'Register output 7.',
      'NC':   'No connect.',
      'NC2':  'No connect.',
      'NC3':  'No connect.',
      'VCC':  'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: 'Synchronous Clear',
        paragraphs: [
          'Synchronous clear (vs asynchronous) ensures the register only resets on the active clock edge. This avoids glitches from metastable clear signals in synchronous systems.',
        ],
      },
    ],
    pinout: [
      { pin: 1,  name: 'OEn',  type: 'input' },
      { pin: 2,  name: 'CLRn', type: 'input' },
      { pin: 3,  name: 'D0',   type: 'input' },
      { pin: 4,  name: 'D1',   type: 'input' },
      { pin: 5,  name: 'D2',   type: 'input' },
      { pin: 6,  name: 'D3',   type: 'input' },
      { pin: 7,  name: 'D4',   type: 'input' },
      { pin: 8,  name: 'D5',   type: 'input' },
      { pin: 9,  name: 'D6',   type: 'input' },
      { pin: 10, name: 'D7',   type: 'input' },
      { pin: 11, name: 'CLK',  type: 'input' },
      { pin: 12, name: 'GND',  type: 'power' },
      { pin: 13, name: 'Q0',   type: 'output' },
      { pin: 14, name: 'Q1',   type: 'output' },
      { pin: 15, name: 'Q2',   type: 'output' },
      { pin: 16, name: 'Q3',   type: 'output' },
      { pin: 17, name: 'Q4',   type: 'output' },
      { pin: 18, name: 'Q5',   type: 'output' },
      { pin: 19, name: 'Q6',   type: 'output' },
      { pin: 20, name: 'Q7',   type: 'output' },
      { pin: 21, name: 'NC',   type: 'nc' },
      { pin: 22, name: 'NC2',  type: 'nc' },
      { pin: 23, name: 'NC3',  type: 'nc' },
      { pin: 24, name: 'VCC',  type: 'power' },
    ],
    gates: [
      { type: 'REG_OCTAL_SYNCLR_TRI',
        inputs:  ['OEn','CLRn','CLK','D0','D1','D2','D3','D4','D5','D6','D7'],
        outputs: ['Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7'] },
    ],
  },

  // ── 74576: Octal D type edge triggered FF, inverting, tri state ──────────
  /* Primary source: Texas Instruments, 74576 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74als576b.pdf
     https://en.wikipedia.org/wiki/Flip-flop_(electronics) */
  '74x576': {
    name: '74x576',
    simpleName: 'Octal FF Inv (TRI)',
    description: 'Octal D-type edge-triggered flip-flop, inverting, 3-state (20-pin)',
    pins: 20,
    vcc: 20,
    gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74als576b.pdf',
    tags: ['flip flop', 'octal', 'register', 'inverting', 'tri state'],
    guideOverview: 'The 74x576 is an octal D type edge triggered flip flop with inverting outputs and tri state, identical in function to the 74x564. Both capture the complement of D inputs on the rising CLK edge. The part number difference reflects a process or package revision within the ALS/FAST family.',
    guidePinDescriptions: {
      'OEn': 'Output Enable (active LOW).',
      'D0':  'Data input 0.',
      'D1':  'Data input 1.',
      'D2':  'Data input 2.',
      'D3':  'Data input 3.',
      'D4':  'Data input 4.',
      'D5':  'Data input 5.',
      'D6':  'Data input 6.',
      'D7':  'Data input 7.',
      'GND': 'Ground reference (pin 10).',
      'CLK': 'Clock (rising edge).',
      'Qn0': 'Inverted register output 0.',
      'Qn1': 'Inverted register output 1.',
      'Qn2': 'Inverted register output 2.',
      'Qn3': 'Inverted register output 3.',
      'Qn4': 'Inverted register output 4.',
      'Qn5': 'Inverted register output 5.',
      'Qn6': 'Inverted register output 6.',
      'Qn7': 'Inverted register output 7.',
      'VCC': 'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: '74x564 vs 74x576',
        paragraphs: [
          'Both chips are octal inverting registers. The 74x576 is the ALS family update of the 74x564. They are functionally interchangeable in most designs.',
        ],
      },
    ],
    pinout: [
      { pin: 1,  name: 'OEn', type: 'input' },
      { pin: 2,  name: 'D0',  type: 'input' },
      { pin: 3,  name: 'D1',  type: 'input' },
      { pin: 4,  name: 'D2',  type: 'input' },
      { pin: 5,  name: 'D3',  type: 'input' },
      { pin: 6,  name: 'D4',  type: 'input' },
      { pin: 7,  name: 'D5',  type: 'input' },
      { pin: 8,  name: 'D6',  type: 'input' },
      { pin: 9,  name: 'D7',  type: 'input' },
      { pin: 10, name: 'GND', type: 'power' },
      { pin: 11, name: 'CLK', type: 'input' },
      { pin: 12, name: 'Qn0', type: 'output' },
      { pin: 13, name: 'Qn1', type: 'output' },
      { pin: 14, name: 'Qn2', type: 'output' },
      { pin: 15, name: 'Qn3', type: 'output' },
      { pin: 16, name: 'Qn4', type: 'output' },
      { pin: 17, name: 'Qn5', type: 'output' },
      { pin: 18, name: 'Qn6', type: 'output' },
      { pin: 19, name: 'Qn7', type: 'output' },
      { pin: 20, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'REG_OCTAL_INV_TRI',
        inputs:  ['OEn','CLK','D0','D1','D2','D3','D4','D5','D6','D7'],
        outputs: ['Qn0','Qn1','Qn2','Qn3','Qn4','Qn5','Qn6','Qn7'] },
    ],
  },

  // ── 74577: Octal D type FF, synchronous clear, inverting, tri state ──────
  /* Primary source: Texas Instruments, 74577 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74als577a.pdf
     https://en.wikipedia.org/wiki/Flip-flop_(electronics) */
  '74x577': {
    name: '74x577',
    simpleName: 'Octal FF SynCLR Inv (TRI)',
    description: 'Octal D-type flip-flop, sync clear, inverting, 3-state (24-pin)',
    pins: 24,
    vcc: 24,
    gnd: 12,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74als577a.pdf',
    tags: ['flip flop', 'octal', 'register', 'synchronous-clear', 'inverting', 'tri state'],
    guideOverview: 'The 74x577 adds synchronous clear to the inverting output octal D-FF. CLRn LOW on a rising CLK edge forces all Qn HIGH (since outputs are inverted). OEn tri states all outputs. The 24-pin package is pin compatible with 74x575 but with inverted outputs.',
    guidePinDescriptions: {
      'OEn':  'Output Enable (active LOW).',
      'CLRn': 'Synchronous Clear (active LOW). Forces Qn HIGH on rising CLK.',
      'D0':   'Data input 0.',
      'D1':   'Data input 1.',
      'D2':   'Data input 2.',
      'D3':   'Data input 3.',
      'D4':   'Data input 4.',
      'D5':   'Data input 5.',
      'D6':   'Data input 6.',
      'D7':   'Data input 7.',
      'CLK':  'Clock (rising edge).',
      'GND':  'Ground reference (pin 12).',
      'Qn0':  'Inverted register output 0.',
      'Qn1':  'Inverted register output 1.',
      'Qn2':  'Inverted register output 2.',
      'Qn3':  'Inverted register output 3.',
      'Qn4':  'Inverted register output 4.',
      'Qn5':  'Inverted register output 5.',
      'Qn6':  'Inverted register output 6.',
      'Qn7':  'Inverted register output 7.',
      'NC':   'No connect.',
      'NC2':  'No connect.',
      'NC3':  'No connect.',
      'VCC':  'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: 'Synchronous Clear with Inverted Outputs',
        paragraphs: [
          'Because outputs are inverted, CLRn LOW clears D=0 into the flip flop, which appears as Qn=HIGH after the CLK edge. For active LOW downstream logic, this acts as a forced HIGH reset.',
        ],
      },
    ],
    pinout: [
      { pin: 1,  name: 'OEn',  type: 'input' },
      { pin: 2,  name: 'CLRn', type: 'input' },
      { pin: 3,  name: 'D0',   type: 'input' },
      { pin: 4,  name: 'D1',   type: 'input' },
      { pin: 5,  name: 'D2',   type: 'input' },
      { pin: 6,  name: 'D3',   type: 'input' },
      { pin: 7,  name: 'D4',   type: 'input' },
      { pin: 8,  name: 'D5',   type: 'input' },
      { pin: 9,  name: 'D6',   type: 'input' },
      { pin: 10, name: 'D7',   type: 'input' },
      { pin: 11, name: 'CLK',  type: 'input' },
      { pin: 12, name: 'GND',  type: 'power' },
      { pin: 13, name: 'Qn0',  type: 'output' },
      { pin: 14, name: 'Qn1',  type: 'output' },
      { pin: 15, name: 'Qn2',  type: 'output' },
      { pin: 16, name: 'Qn3',  type: 'output' },
      { pin: 17, name: 'Qn4',  type: 'output' },
      { pin: 18, name: 'Qn5',  type: 'output' },
      { pin: 19, name: 'Qn6',  type: 'output' },
      { pin: 20, name: 'Qn7',  type: 'output' },
      { pin: 21, name: 'NC',   type: 'nc' },
      { pin: 22, name: 'NC2',  type: 'nc' },
      { pin: 23, name: 'NC3',  type: 'nc' },
      { pin: 24, name: 'VCC',  type: 'power' },
    ],
    gates: [
      { type: 'REG_OCTAL_SYNCLR_INV_TRI',
        inputs:  ['OEn','CLRn','CLK','D0','D1','D2','D3','D4','D5','D6','D7'],
        outputs: ['Qn0','Qn1','Qn2','Qn3','Qn4','Qn5','Qn6','Qn7'] },
    ],
  },

  // ── 74579: 8 bit bidirectional binary counter, tri state ─────────────────
  /* Primary source: Texas Instruments, 74579 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/mc74f579.pdf
     https://en.wikipedia.org/wiki/Counter_(digital) */
  '74x579': {
    name: '74x579',
    simpleName: '8 bit Bidir Ctr (TRI)',
    description: '8-bit bidirectional sync binary counter, 3-state (20-pin)',
    pins: 20,
    vcc: 20,
    gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/mc74f579.pdf',
    tags: ['counter', 'binary', 'up-down', '8 bit', 'synchronous', 'tri state'],
    guideOverview: 'The 74x579 is an 8 bit synchronous binary up/down counter with a bidirectional tri state bus (A0-A7 are shared data/output pins). ENP, ENT, U_Dn, LOAD, and OEn provide full count control. TC (terminal count) goes HIGH at the maximum (count up) or minimum (count down) to cascade multiple chips.',
    guidePinDescriptions: {
      'CLK':  'Clock (rising edge).',
      'ENT':  'Count Enable Trickle (also gates TC).',
      'ENP':  'Count Enable Parallel.',
      'U_Dn': 'Up/Down select. HIGH = up; LOW = down.',
      'LOAD': 'Parallel Load (active LOW).',
      'OEn':  'Output Enable (active LOW).',
      'A0':   'Bidirectional data/output bit 0.',
      'A1':   'Bidirectional data/output bit 1.',
      'A2':   'Bidirectional data/output bit 2.',
      'GND':  'Ground reference (pin 10).',
      'A3':   'Bidirectional data/output bit 3.',
      'A4':   'Bidirectional data/output bit 4.',
      'A5':   'Bidirectional data/output bit 5.',
      'A6':   'Bidirectional data/output bit 6.',
      'A7':   'Bidirectional data/output bit 7.',
      'TC':   'Terminal Count output for cascade.',
      'NC':   'No connect.',
      'NC2':  'No connect.',
      'NC3':  'No connect.',
      'VCC':  'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: '8 bit Up/Down Counter',
        paragraphs: [
          'At 8 bits, the 74x579 counts 0-255. Cascade using TC → ENT of the next chip for a 16 bit or wider counter. The shared A bus allows parallel load directly from the bus.',
        ],
      },
    ],
    pinout: [
      { pin: 1,  name: 'CLK',  type: 'input' },
      { pin: 2,  name: 'ENT',  type: 'input' },
      { pin: 3,  name: 'ENP',  type: 'input' },
      { pin: 4,  name: 'U_Dn', type: 'input' },
      { pin: 5,  name: 'LOAD', type: 'input' },
      { pin: 6,  name: 'OEn',  type: 'input' },
      { pin: 7,  name: 'A0',   type: 'io' },
      { pin: 8,  name: 'A1',   type: 'io' },
      { pin: 9,  name: 'A2',   type: 'io' },
      { pin: 10, name: 'GND',  type: 'power' },
      { pin: 11, name: 'A3',   type: 'io' },
      { pin: 12, name: 'A4',   type: 'io' },
      { pin: 13, name: 'A5',   type: 'io' },
      { pin: 14, name: 'A6',   type: 'io' },
      { pin: 15, name: 'A7',   type: 'io' },
      { pin: 16, name: 'TC',   type: 'output' },
      { pin: 17, name: 'NC',   type: 'nc' },
      { pin: 18, name: 'NC2',  type: 'nc' },
      { pin: 19, name: 'NC3',  type: 'nc' },
      { pin: 20, name: 'VCC',  type: 'power' },
    ],
    gates: [
      { type: 'COUNTER_8BIT_BIDIR_TRI',
        inputs:  ['CLK','ENT','ENP','U_Dn','LOAD','OEn','A0','A1','A2','A3','A4','A5','A6','A7'],
        outputs: ['A0','A1','A2','A3','A4','A5','A6','A7','TC'] },
    ],
  },

  // ── 74580: Octal D type transparent latch, inverting, tri state ──────────
  /* Primary source: Texas Instruments, 74580 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74als580b.pdf
     https://en.wikipedia.org/wiki/Flip-flop_(electronics) */
  '74x580': {
    name: '74x580',
    simpleName: 'Octal Latch Inv (TRI)',
    description: 'Octal D-type transparent latch, inverting, 3-state (20-pin)',
    pins: 20,
    vcc: 20,
    gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74als580b.pdf',
    tags: ['latch', 'octal', 'inverting', 'tri state'],
    guideOverview: 'The 74x580 is an octal D type transparent latch with inverting outputs and tri state. LE HIGH makes outputs follow the inverted D inputs; LE LOW holds the latched value. OEn enables outputs. Functionally equivalent to the 74x533/74x563 family.',
    guidePinDescriptions: {
      'OEn': 'Output Enable (active LOW).',
      'D0':  'Data input 0.',
      'D1':  'Data input 1.',
      'D2':  'Data input 2.',
      'D3':  'Data input 3.',
      'D4':  'Data input 4.',
      'D5':  'Data input 5.',
      'D6':  'Data input 6.',
      'D7':  'Data input 7.',
      'GND': 'Ground reference (pin 10).',
      'LE':  'Latch Enable. HIGH = transparent; LOW = hold.',
      'Qn0': 'Inverted latch output 0.',
      'Qn1': 'Inverted latch output 1.',
      'Qn2': 'Inverted latch output 2.',
      'Qn3': 'Inverted latch output 3.',
      'Qn4': 'Inverted latch output 4.',
      'Qn5': 'Inverted latch output 5.',
      'Qn6': 'Inverted latch output 6.',
      'Qn7': 'Inverted latch output 7.',
      'VCC': 'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'Octal Inverting Transparent Latch',
        paragraphs: [
          'Interchangeable with 74x533 and 74x563. The inverting output saves an external inversion stage when driving active LOW bus signals.',
        ],
      },
    ],
    pinout: [
      { pin: 1,  name: 'OEn', type: 'input' },
      { pin: 2,  name: 'D0',  type: 'input' },
      { pin: 3,  name: 'D1',  type: 'input' },
      { pin: 4,  name: 'D2',  type: 'input' },
      { pin: 5,  name: 'D3',  type: 'input' },
      { pin: 6,  name: 'D4',  type: 'input' },
      { pin: 7,  name: 'D5',  type: 'input' },
      { pin: 8,  name: 'D6',  type: 'input' },
      { pin: 9,  name: 'D7',  type: 'input' },
      { pin: 10, name: 'GND', type: 'power' },
      { pin: 11, name: 'LE',  type: 'input' },
      { pin: 12, name: 'Qn0', type: 'output' },
      { pin: 13, name: 'Qn1', type: 'output' },
      { pin: 14, name: 'Qn2', type: 'output' },
      { pin: 15, name: 'Qn3', type: 'output' },
      { pin: 16, name: 'Qn4', type: 'output' },
      { pin: 17, name: 'Qn5', type: 'output' },
      { pin: 18, name: 'Qn6', type: 'output' },
      { pin: 19, name: 'Qn7', type: 'output' },
      { pin: 20, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'LATCH_OCTAL_INV_TRI',
        inputs:  ['OEn','LE','D0','D1','D2','D3','D4','D5','D6','D7'],
        outputs: ['Qn0','Qn1','Qn2','Qn3','Qn4','Qn5','Qn6','Qn7'] },
    ],
  },

  // ── 74582: 4 bit BCD arithmetic logic unit ───────────────────────────────
  /* Primary source: Texas Instruments, 74582 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/74f582.pdf
     https://en.wikipedia.org/wiki/Arithmetic_logic_unit */
  '74x582': {
    name: '74x582',
    simpleName: '4 bit BCD ALU',
    description: '4 bit binary coded decimal arithmetic logic unit (24-pin)',
    pins: 24,
    vcc: 24,
    gnd: 12,
    datasheet: 'https://www.ti.com/lit/ds/symlink/74f582.pdf',
    tags: ['alu', 'bcd', 'arithmetic'],
    guideOverview: 'The 74x582 is a 4 bit BCD (binary coded decimal) arithmetic logic unit. It performs 16 operations on BCD operands selected by S3-S0, with mode M (arithmetic vs logic). Cn is carry in; F0-F3 are the result; Cn4 is carry out; OVR indicates decimal overflow; P and G are carry propagate and generate outputs for fast lookahead chaining.',
    guidePinDescriptions: {
      'B0':  'BCD operand B bit 0.',
      'A0':  'BCD operand A bit 0.',
      'B1':  'BCD operand B bit 1.',
      'A1':  'BCD operand A bit 1.',
      'B2':  'BCD operand B bit 2.',
      'A2':  'BCD operand A bit 2.',
      'B3':  'BCD operand B bit 3.',
      'A3':  'BCD operand A bit 3.',
      'Cn':  'Carry input.',
      'M':   'Mode select. HIGH = logic; LOW = arithmetic.',
      'S0':  'Function select bit 0.',
      'GND': 'Ground reference (pin 12).',
      'S1':  'Function select bit 1.',
      'S2':  'Function select bit 2.',
      'S3':  'Function select bit 3.',
      'F0':  'ALU result bit 0.',
      'F1':  'ALU result bit 1.',
      'F2':  'ALU result bit 2.',
      'F3':  'ALU result bit 3.',
      'Cn4': 'Carry output.',
      'OVR': 'BCD overflow output.',
      'P':   'Carry propagate output for lookahead.',
      'G':   'Carry generate output for lookahead.',
      'VCC': 'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: 'BCD ALU vs Binary ALU',
        paragraphs: [
          'The 74x582 performs the same 16 operations as the 74x181 but corrects the BCD carry internally. This avoids the BCD correction step required when doing decimal arithmetic with binary ALUs.',
        ],
        note: 'Simplification: only the BCD-add operation is modelled in 74Sim (mode M=LOW with S3..S0 = 1001), which produces F = A + B + Cn with decimal carry on Cn4. Every other select/mode combination simply passes A through to F, and the OVR, P and G outputs are always held LOW. Treat this part as a decimal adder in-sim, not a full 16-function ALU.',
      },
    ],
    pinout: [
      { pin: 1,  name: 'B0',  type: 'input' },
      { pin: 2,  name: 'A0',  type: 'input' },
      { pin: 3,  name: 'B1',  type: 'input' },
      { pin: 4,  name: 'A1',  type: 'input' },
      { pin: 5,  name: 'B2',  type: 'input' },
      { pin: 6,  name: 'A2',  type: 'input' },
      { pin: 7,  name: 'B3',  type: 'input' },
      { pin: 8,  name: 'A3',  type: 'input' },
      { pin: 9,  name: 'Cn',  type: 'input' },
      { pin: 10, name: 'M',   type: 'input' },
      { pin: 11, name: 'S0',  type: 'input' },
      { pin: 12, name: 'GND', type: 'power' },
      { pin: 13, name: 'S1',  type: 'input' },
      { pin: 14, name: 'S2',  type: 'input' },
      { pin: 15, name: 'S3',  type: 'input' },
      { pin: 16, name: 'F0',  type: 'output' },
      { pin: 17, name: 'F1',  type: 'output' },
      { pin: 18, name: 'F2',  type: 'output' },
      { pin: 19, name: 'F3',  type: 'output' },
      { pin: 20, name: 'Cn4', type: 'output' },
      { pin: 21, name: 'OVR', type: 'output' },
      { pin: 22, name: 'P',   type: 'output' },
      { pin: 23, name: 'G',   type: 'output' },
      { pin: 24, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'ALU_BCD_4BIT',
        inputs:  ['A0','A1','A2','A3','B0','B1','B2','B3','Cn','M','S0','S1','S2','S3'],
        outputs: ['F0','F1','F2','F3','Cn4','OVR','P','G'] },
    ],
  },

  // ── 74583: 4 bit BCD adder ───────────────────────────────────────────────
  /* Primary source: Texas Instruments, 74583 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/74f583.pdf
     https://en.wikipedia.org/wiki/Adder_(electronics) */
  '74x583': {
    name: '74x583',
    simpleName: '4 bit BCD Adder',
    description: '4 bit binary coded decimal adder (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/74f583.pdf',
    tags: ['adder', 'bcd', 'arithmetic'],
    guideOverview: 'The 74x583 is a 4 bit BCD adder that sums two BCD digits and a carry in to produce a 4 bit BCD sum and a carry out. It is simpler than the 74x582 (addition only, no function select). Cascade by connecting Cout to Cin of the next chip for multi digit decimal addition.',
    guidePinDescriptions: {
      'B0':  'BCD addend B bit 0.',
      'A0':  'BCD addend A bit 0.',
      'B1':  'BCD addend B bit 1.',
      'A1':  'BCD addend A bit 1.',
      'B2':  'BCD addend B bit 2.',
      'A2':  'BCD addend A bit 2.',
      'B3':  'BCD addend B bit 3.',
      'GND': 'Ground reference (pin 8).',
      'A3':  'BCD addend A bit 3.',
      'Cin': 'Carry input.',
      'Cout':'Carry output.',
      'S3':  'BCD sum bit 3.',
      'S2':  'BCD sum bit 2.',
      'S1':  'BCD sum bit 1.',
      'S0':  'BCD sum bit 0.',
      'VCC': 'Positive supply (+5 V, pin 16).',
    },
    guideSections: [
      {
        title: 'BCD Addition',
        paragraphs: [
          'Adds two BCD digits (0-9 each) and produce a BCD result plus carry. The chip automatically handles the 6-correction needed to keep the result valid BCD, unlike a plain binary adder.',
        ],
      },
    ],
    pinout: [
      { pin: 1,  name: 'B0',  type: 'input' },
      { pin: 2,  name: 'A0',  type: 'input' },
      { pin: 3,  name: 'B1',  type: 'input' },
      { pin: 4,  name: 'A1',  type: 'input' },
      { pin: 5,  name: 'B2',  type: 'input' },
      { pin: 6,  name: 'A2',  type: 'input' },
      { pin: 7,  name: 'B3',  type: 'input' },
      { pin: 8,  name: 'GND', type: 'power' },
      { pin: 9,  name: 'A3',  type: 'input' },
      { pin: 10, name: 'Cin', type: 'input' },
      { pin: 11, name: 'Cout',type: 'output' },
      { pin: 12, name: 'S3',  type: 'output' },
      { pin: 13, name: 'S2',  type: 'output' },
      { pin: 14, name: 'S1',  type: 'output' },
      { pin: 15, name: 'S0',  type: 'output' },
      { pin: 16, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'ADDER_BCD_4BIT',
        inputs:  ['A0','A1','A2','A3','B0','B1','B2','B3','Cin'],
        outputs: ['S0','S1','S2','S3','Cout'] },
    ],
  },

  // ── 74588: Octal bidirectional transceiver, IEEE-488 termination ─────────
  /* Primary source: Texas Instruments, 74588 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/74f588.pdf
     https://en.wikipedia.org/wiki/Bus_transceiver */
  '74x588': {
    name: '74x588',
    simpleName: 'Octal Xcvr IEEE-488',
    description: 'Octal bidirectional transceiver, IEEE-488 termination (20-pin)',
    pins: 20,
    vcc: 20,
    gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/74f588.pdf',
    tags: ['transceiver', 'bidirectional', 'octal', 'ieee-488', 'gpib'],
    guideOverview: 'The 74x588 is an 8 bit bidirectional bus transceiver designed for IEEE-488 (GPIB) bus interfaces. It integrates bus termination resistors matched to GPIB cable impedance requirements. DIR and OEn control direction and output enable, identical to a 74x245, but internal termination simplifies GPIB board design.',
    guidePinDescriptions: {
      'OEn': 'Output Enable (active LOW).',
      'DIR': 'Direction. HIGH = A drives B; LOW = B drives A.',
      'A0':  'Port A bit 0.',
      'A1':  'Port A bit 1.',
      'A2':  'Port A bit 2.',
      'A3':  'Port A bit 3.',
      'A4':  'Port A bit 4.',
      'A5':  'Port A bit 5.',
      'A6':  'Port A bit 6.',
      'GND': 'Ground reference (pin 10).',
      'A7':  'Port A bit 7.',
      'B0':  'Port B bit 0.',
      'B1':  'Port B bit 1.',
      'B2':  'Port B bit 2.',
      'B3':  'Port B bit 3.',
      'B4':  'Port B bit 4.',
      'B5':  'Port B bit 5.',
      'B6':  'Port B bit 6.',
      'B7':  'Port B bit 7.',
      'VCC': 'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'IEEE-488 / GPIB Bus',
        paragraphs: [
          'IEEE-488 (also called GPIB or HP IB) is an 8 bit parallel instrumentation bus. The bus uses passive termination resistors to defined impedance. The 74x588 combines the driver/receiver function of a 74x245 with the required termination, reducing external component count.',
        ],
      },
    ],
    pinout: [
      { pin: 1,  name: 'OEn', type: 'input' },
      { pin: 2,  name: 'DIR', type: 'input' },
      { pin: 3,  name: 'A0',  type: 'io' },
      { pin: 4,  name: 'A1',  type: 'io' },
      { pin: 5,  name: 'A2',  type: 'io' },
      { pin: 6,  name: 'A3',  type: 'io' },
      { pin: 7,  name: 'A4',  type: 'io' },
      { pin: 8,  name: 'A5',  type: 'io' },
      { pin: 9,  name: 'A6',  type: 'io' },
      { pin: 10, name: 'GND', type: 'power' },
      { pin: 11, name: 'A7',  type: 'io' },
      { pin: 12, name: 'B0',  type: 'io' },
      { pin: 13, name: 'B1',  type: 'io' },
      { pin: 14, name: 'B2',  type: 'io' },
      { pin: 15, name: 'B3',  type: 'io' },
      { pin: 16, name: 'B4',  type: 'io' },
      { pin: 17, name: 'B5',  type: 'io' },
      { pin: 18, name: 'B6',  type: 'io' },
      { pin: 19, name: 'B7',  type: 'io' },
      { pin: 20, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'TRANSCEIVER_8BIT',
        inputs:  ['OEn','DIR','A0','A1','A2','A3','A4','A5','A6','A7',
                  'B0','B1','B2','B3','B4','B5','B6','B7'],
        outputs: ['A0','A1','A2','A3','A4','A5','A6','A7',
                  'B0','B1','B2','B3','B4','B5','B6','B7'] },
    ],
  },

};
