// Chip definitions block 43
// Chips: 74877-74882, 74885, 74900-74906

export const CHIPS_BLOCK_43 = {

  // 74877: 8 bit universal transceiver port controller (24-pin)
  '74877': {
    name: '74x877',
    simpleName: '8 bit Universal Transceiver Port Controller',
    description: '8 bit universal transceiver port controller (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['transceiver', '8 bit', 'tri-state', 'stub'],
    guideOverview: 'The 74x877 is an 8 bit universal transceiver port controller with 3-state outputs. Mode select inputs S0 and S1 choose among pass-through, registered, and hold modes for transferring data between the bidirectional A and B buses. OEn (active LOW) enables the output drivers. CLK clocks the internal pipeline register and CLRn (active LOW) asynchronously clears it. This chip is a later enhanced-process variant in the 74x852/856/877 family and is used in high-speed bus interfaces requiring configurable data-flow direction.',
    pinout: [
      { pin:  1, name: 'S0',   type: 'input'  },
      { pin:  2, name: 'S1',   type: 'input'  },
      { pin:  3, name: 'OEn',  type: 'input'  },
      { pin:  4, name: 'A0',   type: 'bidir'  },
      { pin:  5, name: 'A1',   type: 'bidir'  },
      { pin:  6, name: 'A2',   type: 'bidir'  },
      { pin:  7, name: 'A3',   type: 'bidir'  },
      { pin:  8, name: 'A4',   type: 'bidir'  },
      { pin:  9, name: 'A5',   type: 'bidir'  },
      { pin: 10, name: 'A6',   type: 'bidir'  },
      { pin: 11, name: 'A7',   type: 'bidir'  },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'B7',   type: 'bidir'  },
      { pin: 14, name: 'B6',   type: 'bidir'  },
      { pin: 15, name: 'B5',   type: 'bidir'  },
      { pin: 16, name: 'B4',   type: 'bidir'  },
      { pin: 17, name: 'B3',   type: 'bidir'  },
      { pin: 18, name: 'B2',   type: 'bidir'  },
      { pin: 19, name: 'B1',   type: 'bidir'  },
      { pin: 20, name: 'B0',   type: 'bidir'  },
      { pin: 21, name: 'CLK',  type: 'input'  },
      { pin: 22, name: 'CLRn', type: 'input'  },
      { pin: 23, name: 'NC',   type: 'nc'     },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['S0','S1','OEn','CLK','CLRn'], outputs: [] },
    ],
  },

  // 74878: Dual 4 bit D-FF, synchronous clear, non-inverting outputs, TRI (24-pin)
  '74878': {
    name: '74x878',
    simpleName: 'Dual 4 bit D-FF (Sync CLR, Non-Inv, TRI)',
    description: 'Dual 4 bit D-type flip-flop with synchronous clear and non-inverting three-state outputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['flip-flop', 'D-type', 'dual', '4 bit', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x878 contains two independent 4 bit banks of positive-edge-triggered D flip-flops with synchronous clear and non-inverting 3-state outputs. Each bank captures its four D inputs on the rising CLK edge and drives the Q outputs non-inverted when OEn (active LOW) is asserted. CLRn (active LOW) clears the register synchronously on the next rising clock edge, preventing glitches. The synchronous clear makes this chip preferable to the 74x873/874 in high-speed pipelined designs.',
    pinout: [
      { pin:  1, name: 'OE1n', type: 'input'  },
      { pin:  2, name: 'CLR1n',type: 'input'  },
      { pin:  3, name: 'CLK1', type: 'input'  },
      { pin:  4, name: 'D10',  type: 'input'  },
      { pin:  5, name: 'D11',  type: 'input'  },
      { pin:  6, name: 'D12',  type: 'input'  },
      { pin:  7, name: 'D13',  type: 'input'  },
      { pin:  8, name: 'Q10',  type: 'output' },
      { pin:  9, name: 'Q11',  type: 'output' },
      { pin: 10, name: 'Q12',  type: 'output' },
      { pin: 11, name: 'Q13',  type: 'output' },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'Q23',  type: 'output' },
      { pin: 14, name: 'Q22',  type: 'output' },
      { pin: 15, name: 'Q21',  type: 'output' },
      { pin: 16, name: 'Q20',  type: 'output' },
      { pin: 17, name: 'D23',  type: 'input'  },
      { pin: 18, name: 'D22',  type: 'input'  },
      { pin: 19, name: 'D21',  type: 'input'  },
      { pin: 20, name: 'D20',  type: 'input'  },
      { pin: 21, name: 'CLK2', type: 'input'  },
      { pin: 22, name: 'CLR2n',type: 'input'  },
      { pin: 23, name: 'OE2n', type: 'input'  },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OE1n','CLR1n','CLK1','D10','D11','D12','D13','OE2n','CLR2n','CLK2','D20','D21','D22','D23'], outputs: ['Q10','Q11','Q12','Q13','Q20','Q21','Q22','Q23'] },
    ],
  },

  // 74879: Dual 4 bit D-FF, synchronous clear, inverting outputs, TRI (24-pin)
  '74879': {
    name: '74x879',
    simpleName: 'Dual 4 bit D-FF (Sync CLR, Inv, TRI)',
    description: 'Dual 4 bit D-type flip-flop with synchronous clear and inverting three-state outputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['flip-flop', 'D-type', 'dual', '4 bit', 'inverting', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x879 is identical to the 74x878 but provides inverting 3-state outputs. Data captured on the rising CLK edge appears inverted at the Q̄ outputs when OEn (active LOW) is asserted. CLRn (active LOW) clears the internal registers synchronously on the next rising clock edge. Use when the system bus requires active LOW data levels with registered driving and synchronous clear.',
    pinout: [
      { pin:  1, name: 'OE1n', type: 'input'  },
      { pin:  2, name: 'CLR1n',type: 'input'  },
      { pin:  3, name: 'CLK1', type: 'input'  },
      { pin:  4, name: 'D10',  type: 'input'  },
      { pin:  5, name: 'D11',  type: 'input'  },
      { pin:  6, name: 'D12',  type: 'input'  },
      { pin:  7, name: 'D13',  type: 'input'  },
      { pin:  8, name: 'Q10n', type: 'output' },
      { pin:  9, name: 'Q11n', type: 'output' },
      { pin: 10, name: 'Q12n', type: 'output' },
      { pin: 11, name: 'Q13n', type: 'output' },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'Q23n', type: 'output' },
      { pin: 14, name: 'Q22n', type: 'output' },
      { pin: 15, name: 'Q21n', type: 'output' },
      { pin: 16, name: 'Q20n', type: 'output' },
      { pin: 17, name: 'D23',  type: 'input'  },
      { pin: 18, name: 'D22',  type: 'input'  },
      { pin: 19, name: 'D21',  type: 'input'  },
      { pin: 20, name: 'D20',  type: 'input'  },
      { pin: 21, name: 'CLK2', type: 'input'  },
      { pin: 22, name: 'CLR2n',type: 'input'  },
      { pin: 23, name: 'OE2n', type: 'input'  },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OE1n','CLR1n','CLK1','D10','D11','D12','D13','OE2n','CLR2n','CLK2','D20','D21','D22','D23'], outputs: ['Q10n','Q11n','Q12n','Q13n','Q20n','Q21n','Q22n','Q23n'] },
    ],
  },

  // 74880: Dual 4 bit transparent latch with clear, inverting outputs, TRI (24-pin)
  '74880': {
    name: '74x880',
    simpleName: 'Dual 4 bit Transparent Latch w/ Clear (Inv, TRI)',
    description: 'Dual 4 bit transparent latch with clear and inverting three-state outputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['latch', 'dual', '4 bit', 'transparent', 'inverting', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x880 contains two independent 4 bit transparent latches with active LOW clear and inverting 3-state outputs. When the latch enable LE is HIGH, the D inputs pass through to the inverted Q̄ outputs in real time (transparent mode). When LE goes LOW the last state is captured and held. CLRn (active LOW) asynchronously forces all Q̄ outputs LOW (Q=1) regardless of LE. OEn (active LOW) enables the 3-state output drivers. Use in address or data latching circuits where inverted bus levels are required.',
    pinout: [
      { pin:  1, name: 'OE1n', type: 'input'  },
      { pin:  2, name: 'CLR1n',type: 'input'  },
      { pin:  3, name: 'LE1',  type: 'input'  },
      { pin:  4, name: 'D10',  type: 'input'  },
      { pin:  5, name: 'D11',  type: 'input'  },
      { pin:  6, name: 'D12',  type: 'input'  },
      { pin:  7, name: 'D13',  type: 'input'  },
      { pin:  8, name: 'Q10n', type: 'output' },
      { pin:  9, name: 'Q11n', type: 'output' },
      { pin: 10, name: 'Q12n', type: 'output' },
      { pin: 11, name: 'Q13n', type: 'output' },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'Q23n', type: 'output' },
      { pin: 14, name: 'Q22n', type: 'output' },
      { pin: 15, name: 'Q21n', type: 'output' },
      { pin: 16, name: 'Q20n', type: 'output' },
      { pin: 17, name: 'D23',  type: 'input'  },
      { pin: 18, name: 'D22',  type: 'input'  },
      { pin: 19, name: 'D21',  type: 'input'  },
      { pin: 20, name: 'D20',  type: 'input'  },
      { pin: 21, name: 'LE2',  type: 'input'  },
      { pin: 22, name: 'CLR2n',type: 'input'  },
      { pin: 23, name: 'OE2n', type: 'input'  },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OE1n','CLR1n','LE1','D10','D11','D12','D13','OE2n','CLR2n','LE2','D20','D21','D22','D23'], outputs: ['Q10n','Q11n','Q12n','Q13n','Q20n','Q21n','Q22n','Q23n'] },
    ],
  },

  // 74881: 4 bit arithmetic logic unit (24-pin)
  '74881': {
    name: '74x881',
    simpleName: '4 bit ALU',
    description: '4 bit arithmetic logic unit (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['alu', 'arithmetic', 'logic', '4 bit', 'combinational'],
    guideOverview: 'The 74x881 is a 4 bit arithmetic logic unit (ALU). Four function-select inputs S0–S3 and the mode pin M choose from 16 arithmetic operations (M=LOW, with carry Cn) or 16 logic operations (M=HIGH) on the two 4 bit input words A and B. Results appear on F0–F3; Cn4 is the carry out; P (propagate) and G (generate) feed a lookahead carry unit for cascading into wider adders; AeqB indicates equality. This is the 24-pin package equivalent of the 74x181 and is used wherever a full-function ALU is needed in a standard DIP form factor.',
    pinout: [
      { pin:  1, name: 'B0',   type: 'input'  },
      { pin:  2, name: 'A0',   type: 'input'  },
      { pin:  3, name: 'S3',   type: 'input'  },
      { pin:  4, name: 'S2',   type: 'input'  },
      { pin:  5, name: 'S1',   type: 'input'  },
      { pin:  6, name: 'S0',   type: 'input'  },
      { pin:  7, name: 'Cn',   type: 'input'  },
      { pin:  8, name: 'M',    type: 'input'  },
      { pin:  9, name: 'F0',   type: 'output' },
      { pin: 10, name: 'F1',   type: 'output' },
      { pin: 11, name: 'F2',   type: 'output' },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'F3',   type: 'output' },
      { pin: 14, name: 'AeqB', type: 'output' },
      { pin: 15, name: 'P',    type: 'output' },
      { pin: 16, name: 'Cn4',  type: 'output' },
      { pin: 17, name: 'G',    type: 'output' },
      { pin: 18, name: 'B3',   type: 'input'  },
      { pin: 19, name: 'A3',   type: 'input'  },
      { pin: 20, name: 'B2',   type: 'input'  },
      { pin: 21, name: 'A2',   type: 'input'  },
      { pin: 22, name: 'B1',   type: 'input'  },
      { pin: 23, name: 'A1',   type: 'input'  },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'ALU_4BIT', inputs: ['A0','A1','A2','A3','B0','B1','B2','B3','S0','S1','S2','S3','M','Cn'], outputs: ['F0','F1','F2','F3','Cn4','P','G','AeqB'] },
    ],
  },

  // 74882: 32 bit lookahead carry generator (24-pin)
  '74882': {
    name: '74x882',
    simpleName: '32 bit Lookahead Carry Generator',
    description: '32 bit lookahead carry generator (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['carry', 'lookahead', 'arithmetic', 'stub'],
    guideOverview: 'The 74x882 is a 32 bit lookahead carry generator. It accepts generate (G0–G7) and propagate (P0–P7) signals from up to eight 4 bit ALU or adder stages and computes inter-group carry outputs at 8 bit boundaries: Cn8, Cn16, Cn24, and Cn32. The group generate output GG indicates when the entire 32 bit block will generate a carry regardless of carry-in. Using a 74x882 with eight 74x181 or 74x881 ALUs enables full 32 bit parallel addition with near-constant carry propagation delay instead of a slow ripple-carry chain.',
    pinout: [
      { pin:  1, name: 'G0',   type: 'input'  },
      { pin:  2, name: 'P0',   type: 'input'  },
      { pin:  3, name: 'G1',   type: 'input'  },
      { pin:  4, name: 'P1',   type: 'input'  },
      { pin:  5, name: 'G2',   type: 'input'  },
      { pin:  6, name: 'P2',   type: 'input'  },
      { pin:  7, name: 'G3',   type: 'input'  },
      { pin:  8, name: 'P3',   type: 'input'  },
      { pin:  9, name: 'G4',   type: 'input'  },
      { pin: 10, name: 'P4',   type: 'input'  },
      { pin: 11, name: 'G5',   type: 'input'  },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'P5',   type: 'input'  },
      { pin: 14, name: 'G6',   type: 'input'  },
      { pin: 15, name: 'P6',   type: 'input'  },
      { pin: 16, name: 'G7',   type: 'input'  },
      { pin: 17, name: 'P7',   type: 'input'  },
      { pin: 18, name: 'Cn',   type: 'input'  },
      { pin: 19, name: 'Cn8',  type: 'output' },
      { pin: 20, name: 'Cn16', type: 'output' },
      { pin: 21, name: 'Cn24', type: 'output' },
      { pin: 22, name: 'Cn32', type: 'output' },
      { pin: 23, name: 'GG',   type: 'output' },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['G0','P0','G1','P1','G2','P2','G3','P3','G4','P4','G5','P5','G6','P6','G7','P7','Cn'], outputs: ['Cn8','Cn16','Cn24','Cn32','GG'] },
    ],
  },

  // 74885: 8 bit magnitude comparator (24-pin)
  '74885': {
    name: '74x885',
    simpleName: '8 bit Magnitude Comparator',
    description: '8 bit magnitude comparator (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74as885.pdf',
    tags: ['comparator', '8 bit', 'stub'],
    guideOverview: 'The 74x885 is an 8 bit magnitude comparator. A magnitude comparator tells you whether one binary number is greater than, equal to, or less than another by checking the most significant differing bit first. On a breadboard it is useful for address decoding, threshold decisions, and for building wider comparators by cascading several packages together.',
    guidePinDescriptions: {
      'A0': 'Least-significant bit of the A input word.',
      'B0': 'Least-significant bit of the B input word.',
      'A1': 'A input bit 1.',
      'B1': 'B input bit 1.',
      'A2': 'A input bit 2.',
      'B2': 'B input bit 2.',
      'A3': 'A input bit 3.',
      'B3': 'B input bit 3.',
      'AGEB': 'Output that indicates A is greater than or equal to B.',
      'ALTB': 'Output that indicates A is less than B.',
      'AEQB': 'Output that indicates A equals B.',
      'GND': 'Ground reference for the device at pin 12.',
      'AGTB': 'Output that indicates A is greater than B.',
      'A7': 'Most-significant bit of the A input word.',
      'B7': 'Most-significant bit of the B input word.',
      'A6': 'A input bit 6.',
      'B6': 'B input bit 6.',
      'A5': 'A input bit 5.',
      'B5': 'B input bit 5.',
      'A4': 'A input bit 4.',
      'B4': 'B input bit 4.',
      'ALTBI': 'Cascade input used when chaining comparators so a lower-order stage can report that A is already less than B. When the chip is used alone, set cascade inputs to the standalone state described in the datasheet.',
      'AEQBI': 'Cascade input used when chaining comparators so lower-order equality information can feed into this stage. Set it to the standalone default when no lower-order stage is present.',
      'VCC': 'Positive 5 V supply at pin 24.',
    },
    guideSections: [
      {
        title: 'How Magnitude Comparison Works',
        paragraphs: [
          'Binary magnitude comparison starts at the most significant bit. If the top bits differ, the larger bit wins immediately; only when the higher bits match does the circuit continue downward to the next bit.',
          'That is why comparators are useful in digital control logic: they turn two multi-bit words into simple decision outputs such as greater-than, equal, or less-than.',
        ],
      },
      {
        title: 'Cascading Wider Comparators',
        paragraphs: [
          'Two or more comparator packages can be chained together to compare 16 bit or wider values. Lower-order comparison results feed the cascade inputs, while the upper-order device produces the final decision outputs.',
        ],
        list: [
          'Compare addresses against a range boundary.',
          'Decide whether one binary counter has passed another value.',
          'Chain multiple packages for larger word widths.',
        ],
        note: 'The simulator currently treats this comparator as a generic stub rather than a full cascaded compare model.',
      },
    ],
    pinout: [
      { pin:  1, name: 'A0',   type: 'input'  },
      { pin:  2, name: 'B0',   type: 'input'  },
      { pin:  3, name: 'A1',   type: 'input'  },
      { pin:  4, name: 'B1',   type: 'input'  },
      { pin:  5, name: 'A2',   type: 'input'  },
      { pin:  6, name: 'B2',   type: 'input'  },
      { pin:  7, name: 'A3',   type: 'input'  },
      { pin:  8, name: 'B3',   type: 'input'  },
      { pin:  9, name: 'AGEB', type: 'output' },
      { pin: 10, name: 'ALTB', type: 'output' },
      { pin: 11, name: 'AEQB', type: 'output' },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'AGTB', type: 'output' },
      { pin: 14, name: 'A7',   type: 'input'  },
      { pin: 15, name: 'B7',   type: 'input'  },
      { pin: 16, name: 'A6',   type: 'input'  },
      { pin: 17, name: 'B6',   type: 'input'  },
      { pin: 18, name: 'A5',   type: 'input'  },
      { pin: 19, name: 'B5',   type: 'input'  },
      { pin: 20, name: 'A4',   type: 'input'  },
      { pin: 21, name: 'B4',   type: 'input'  },
      { pin: 22, name: 'ALTBI',type: 'input'  },
      { pin: 23, name: 'AEQBI',type: 'input'  },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['A0','B0','A1','B1','A2','B2','A3','B3','A4','B4','A5','B5','A6','B6','A7','B7','ALTBI','AEQBI'], outputs: ['AGEB','ALTB','AEQB','AGTB'] },
    ],
  },

  // 74900: Quad 2 input NAND driver (14-pin)
  '74900': {
    name: '74x900',
    simpleName: 'Quad 2 Input NAND Driver',
    description: 'Quad 2 input NAND gate (driver) (14-pin)',
    pins: 14, vcc: 14, gnd: 7,
    datasheet: '',
    tags: ['nand', 'gate', 'logic', 'quad', 'driver'],
    guideOverview: 'The 74x900 is a quad 2-input NAND gate with high-current output drivers. Four independent NAND gates each produce a LOW output only when both inputs are HIGH; otherwise the output is HIGH. The driver-grade outputs can sink and source more current than standard-logic NAND gates, making this chip suitable for driving bus lines, long PCB traces, or multiple downstream inputs.',
    pinout: [
      { pin:  1, name: '1A',  type: 'input'  },
      { pin:  2, name: '1B',  type: 'input'  },
      { pin:  3, name: '1Y',  type: 'output' },
      { pin:  4, name: '2A',  type: 'input'  },
      { pin:  5, name: '2B',  type: 'input'  },
      { pin:  6, name: '2Y',  type: 'output' },
      { pin:  7, name: 'GND', type: 'power'  },
      { pin:  8, name: '3Y',  type: 'output' },
      { pin:  9, name: '3A',  type: 'input'  },
      { pin: 10, name: '3B',  type: 'input'  },
      { pin: 11, name: '4Y',  type: 'output' },
      { pin: 12, name: '4A',  type: 'input'  },
      { pin: 13, name: '4B',  type: 'input'  },
      { pin: 14, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'NAND', inputs: ['1A','1B'], output: '1Y' },
      { type: 'NAND', inputs: ['2A','2B'], output: '2Y' },
      { type: 'NAND', inputs: ['3A','3B'], output: '3Y' },
      { type: 'NAND', inputs: ['4A','4B'], output: '4Y' },
    ],
  },

  // 74901: Hex inverting TTL buffer (14-pin)
  '74901': {
    name: '74x901',
    simpleName: 'Hex Inverting TTL Buffer',
    description: 'Hex inverting TTL buffer (14-pin)',
    pins: 14, vcc: 14, gnd: 7,
    datasheet: '',
    tags: ['buffer', 'inverter', 'hex', 'ttl'],
    guideOverview: 'The 74x901 is a hex inverting TTL buffer. Six independent NOT gates each drive a TTL-compatible output that is the logical complement of the input, with higher current capability than standard logic inverters. Use it as a signal driver, line driver, or inverting buffer to fan out a signal to many destinations or to restore degraded logic levels.',
    pinout: [
      { pin:  1, name: '1A',  type: 'input'  },
      { pin:  2, name: '1Y',  type: 'output' },
      { pin:  3, name: '2A',  type: 'input'  },
      { pin:  4, name: '2Y',  type: 'output' },
      { pin:  5, name: '3A',  type: 'input'  },
      { pin:  6, name: '3Y',  type: 'output' },
      { pin:  7, name: 'GND', type: 'power'  },
      { pin:  8, name: '4Y',  type: 'output' },
      { pin:  9, name: '4A',  type: 'input'  },
      { pin: 10, name: '5Y',  type: 'output' },
      { pin: 11, name: '5A',  type: 'input'  },
      { pin: 12, name: '6Y',  type: 'output' },
      { pin: 13, name: '6A',  type: 'input'  },
      { pin: 14, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'NOT', inputs: ['1A'], output: '1Y' },
      { type: 'NOT', inputs: ['2A'], output: '2Y' },
      { type: 'NOT', inputs: ['3A'], output: '3Y' },
      { type: 'NOT', inputs: ['4A'], output: '4Y' },
      { type: 'NOT', inputs: ['5A'], output: '5Y' },
      { type: 'NOT', inputs: ['6A'], output: '6Y' },
    ],
  },

  // 74C902: Hex non-inverting TTL buffer (14-pin)
  '74C902': {
    name: '74x902',
    simpleName: 'Hex Non-Inverting TTL Buffer',
    description: 'Hex non-inverting TTL buffer (14-pin)',
    pins: 14, vcc: 14, gnd: 7,
    datasheet: '',
    tags: ['buffer', 'hex', 'ttl'],
    guideOverview: 'The 74C902 is a hex non-inverting TTL buffer. Six independent BUFFER channels each pass their input directly to the output without inversion, providing higher current drive than standard CMOS logic. Use as a bus driver or level restorer when six signals need to be buffered simultaneously without changing their logic polarity.',
    pinout: [
      { pin:  1, name: '1A',  type: 'input'  },
      { pin:  2, name: '1Y',  type: 'output' },
      { pin:  3, name: '2A',  type: 'input'  },
      { pin:  4, name: '2Y',  type: 'output' },
      { pin:  5, name: '3A',  type: 'input'  },
      { pin:  6, name: '3Y',  type: 'output' },
      { pin:  7, name: 'GND', type: 'power'  },
      { pin:  8, name: '4Y',  type: 'output' },
      { pin:  9, name: '4A',  type: 'input'  },
      { pin: 10, name: '5Y',  type: 'output' },
      { pin: 11, name: '5A',  type: 'input'  },
      { pin: 12, name: '6Y',  type: 'output' },
      { pin: 13, name: '6A',  type: 'input'  },
      { pin: 14, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'BUFFER', inputs: ['1A'], output: '1Y' },
      { type: 'BUFFER', inputs: ['2A'], output: '2Y' },
      { type: 'BUFFER', inputs: ['3A'], output: '3Y' },
      { type: 'BUFFER', inputs: ['4A'], output: '4Y' },
      { type: 'BUFFER', inputs: ['5A'], output: '5Y' },
      { type: 'BUFFER', inputs: ['6A'], output: '6Y' },
    ],
  },

  // 74x902: Quad 2 input NOR driver (14-pin)
  '74x902': {
    name: '74x902',
    simpleName: 'Quad 2 Input NOR Driver',
    description: 'Quad 2 input NOR gate (driver) (14-pin)',
    pins: 14, vcc: 14, gnd: 7,
    datasheet: '',
    tags: ['nor', 'gate', 'logic', 'quad', 'driver'],
    guideOverview: 'The 74x902 is a quad 2-input NOR gate with high-current output drivers. Four independent NOR gates each produce a HIGH output only when both inputs are LOW; if either input is HIGH the output is LOW. The driver-grade outputs can sink and source more current than standard-logic NOR gates, making this chip suitable for driving bus lines, long PCB traces, or multiple downstream inputs directly.',
    pinout: [
      { pin:  1, name: '1Y',  type: 'output' },
      { pin:  2, name: '1A',  type: 'input'  },
      { pin:  3, name: '1B',  type: 'input'  },
      { pin:  4, name: '2Y',  type: 'output' },
      { pin:  5, name: '2A',  type: 'input'  },
      { pin:  6, name: '2B',  type: 'input'  },
      { pin:  7, name: 'GND', type: 'power'  },
      { pin:  8, name: '3A',  type: 'input'  },
      { pin:  9, name: '3B',  type: 'input'  },
      { pin: 10, name: '3Y',  type: 'output' },
      { pin: 11, name: '4A',  type: 'input'  },
      { pin: 12, name: '4B',  type: 'input'  },
      { pin: 13, name: '4Y',  type: 'output' },
      { pin: 14, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'NOR', inputs: ['1A','1B'], output: '1Y' },
      { type: 'NOR', inputs: ['2A','2B'], output: '2Y' },
      { type: 'NOR', inputs: ['3A','3B'], output: '3Y' },
      { type: 'NOR', inputs: ['4A','4B'], output: '4Y' },
    ],
  },

  // 74C903: Hex inverting PMOS buffer (14-pin)
  '74C903': {
    name: '74x903',
    simpleName: 'Hex Inverting PMOS Buffer',
    description: 'Hex inverting PMOS buffer (14-pin)',
    pins: 14, vcc: 14, gnd: 7,
    datasheet: 'https://www.fairchildsemi.com/datasheets/MM/MM74C903.pdf',
    tags: ['buffer', 'inverter', 'hex', 'pmos'],
    guideOverview: 'The 74C903 is a hex inverting PMOS buffer. Six independent NOT gates each drive a PMOS-compatible output that is the logical complement of the input with higher current capability than standard logic inverters. Use when interfacing TTL or CMOS logic to PMOS circuits that require inverted signal polarity, or as a general-purpose hex inverting driver.',
    pinout: [
      { pin:  1, name: '1A',  type: 'input'  },
      { pin:  2, name: '1Y',  type: 'output' },
      { pin:  3, name: '2A',  type: 'input'  },
      { pin:  4, name: '2Y',  type: 'output' },
      { pin:  5, name: '3A',  type: 'input'  },
      { pin:  6, name: '3Y',  type: 'output' },
      { pin:  7, name: 'GND', type: 'power'  },
      { pin:  8, name: '4Y',  type: 'output' },
      { pin:  9, name: '4A',  type: 'input'  },
      { pin: 10, name: '5Y',  type: 'output' },
      { pin: 11, name: '5A',  type: 'input'  },
      { pin: 12, name: '6Y',  type: 'output' },
      { pin: 13, name: '6A',  type: 'input'  },
      { pin: 14, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'NOT', inputs: ['1A'], output: '1Y' },
      { type: 'NOT', inputs: ['2A'], output: '2Y' },
      { type: 'NOT', inputs: ['3A'], output: '3Y' },
      { type: 'NOT', inputs: ['4A'], output: '4Y' },
      { type: 'NOT', inputs: ['5A'], output: '5Y' },
      { type: 'NOT', inputs: ['6A'], output: '6Y' },
    ],
  },

  // 74x903: Quad 2 input NAND, open-collector driver (14-pin)
  '74x903': {
    name: '74x903',
    simpleName: 'Quad 2 Input NAND Driver (OC)',
    description: 'Quad 2 input NAND gate (open-collector driver) (14-pin)',
    pins: 14, vcc: 14, gnd: 7,
    openCollector: true,
    datasheet: '',
    tags: ['nand', 'gate', 'logic', 'quad', 'driver', 'open collector'],
    guideOverview: 'The 74x903 is a quad 2-input NAND gate with open-collector outputs for driving large loads. Four independent NAND gates each produce a LOW output only when both inputs are HIGH; otherwise the output is open-collector (requires an external pull up resistor to pull it HIGH). Multiple open-collector outputs can share a wired AND bus line where any gate asserting LOW pulls the shared line LOW.',
    pinout: [
      { pin:  1, name: '1A',  type: 'input'  },
      { pin:  2, name: '1B',  type: 'input'  },
      { pin:  3, name: '1Y',  type: 'output' },
      { pin:  4, name: '2A',  type: 'input'  },
      { pin:  5, name: '2B',  type: 'input'  },
      { pin:  6, name: '2Y',  type: 'output' },
      { pin:  7, name: 'GND', type: 'power'  },
      { pin:  8, name: '3Y',  type: 'output' },
      { pin:  9, name: '3A',  type: 'input'  },
      { pin: 10, name: '3B',  type: 'input'  },
      { pin: 11, name: '4Y',  type: 'output' },
      { pin: 12, name: '4A',  type: 'input'  },
      { pin: 13, name: '4B',  type: 'input'  },
      { pin: 14, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'NAND', inputs: ['1A','1B'], output: '1Y' },
      { type: 'NAND', inputs: ['2A','2B'], output: '2Y' },
      { type: 'NAND', inputs: ['3A','3B'], output: '3Y' },
      { type: 'NAND', inputs: ['4A','4B'], output: '4Y' },
    ],
  },

  // 74x904: Hex non-inverting PMOS buffer (14-pin)
  '74904': {
    name: '74x904',
    simpleName: 'Hex Non-Inverting PMOS Buffer',
    description: 'Hex non-inverting PMOS buffer (14-pin)',
    pins: 14, vcc: 14, gnd: 7,
    datasheet: '',
    tags: ['buffer', 'hex', 'pmos'],
    guideOverview: 'The 74x904 is a hex non-inverting PMOS buffer. Six independent BUFFER channels each pass their input directly to the output without inversion, providing PMOS-compatible drive levels. Use to interface TTL logic to PMOS circuits or to increase the current drive capacity for six independent signals simultaneously.',
    pinout: [
      { pin:  1, name: '1A',  type: 'input'  },
      { pin:  2, name: '1Y',  type: 'output' },
      { pin:  3, name: '2A',  type: 'input'  },
      { pin:  4, name: '2Y',  type: 'output' },
      { pin:  5, name: '3A',  type: 'input'  },
      { pin:  6, name: '3Y',  type: 'output' },
      { pin:  7, name: 'GND', type: 'power'  },
      { pin:  8, name: '4Y',  type: 'output' },
      { pin:  9, name: '4A',  type: 'input'  },
      { pin: 10, name: '5Y',  type: 'output' },
      { pin: 11, name: '5A',  type: 'input'  },
      { pin: 12, name: '6Y',  type: 'output' },
      { pin: 13, name: '6A',  type: 'input'  },
      { pin: 14, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'BUFFER', inputs: ['1A'], output: '1Y' },
      { type: 'BUFFER', inputs: ['2A'], output: '2Y' },
      { type: 'BUFFER', inputs: ['3A'], output: '3Y' },
      { type: 'BUFFER', inputs: ['4A'], output: '4Y' },
      { type: 'BUFFER', inputs: ['5A'], output: '5Y' },
      { type: 'BUFFER', inputs: ['6A'], output: '6Y' },
    ],
  },

  // 74x905: 12 bit successive approximation register (24-pin)
  '74905': {
    name: '74x905',
    simpleName: '12 bit Successive Approximation Register',
    description: '12 bit successive approximation register (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['register', '12 bit', 'adc', 'sar', 'stub'],
    sequential: true,
    guideOverview: 'The 74x905 is a 12 bit successive approximation register (SAR) used to control analog-to-digital conversion. Asserting SOC starts conversion. Over 12 clock cycles the SAR asserts each output bit D0–D11 one at a time from MSB to LSB; the external comparator result fed back via the MSB pin tells the SAR whether to keep or clear each bit. EOC goes HIGH when conversion is complete and the full 12 bit result is stable. The SC pin coordinates the external DAC and comparator; OE enables the output drivers. The simulator represents this device as a generic stub.',
    pinout: [
      { pin:  1, name: 'SOC',  type: 'input'  },
      { pin:  2, name: 'CLK',  type: 'input'  },
      { pin:  3, name: 'SC',   type: 'output' },
      { pin:  4, name: 'MSB',  type: 'input'  },
      { pin:  5, name: 'D0',   type: 'output' },
      { pin:  6, name: 'D1',   type: 'output' },
      { pin:  7, name: 'D2',   type: 'output' },
      { pin:  8, name: 'D3',   type: 'output' },
      { pin:  9, name: 'D4',   type: 'output' },
      { pin: 10, name: 'D5',   type: 'output' },
      { pin: 11, name: 'D6',   type: 'output' },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'D7',   type: 'output' },
      { pin: 14, name: 'D8',   type: 'output' },
      { pin: 15, name: 'D9',   type: 'output' },
      { pin: 16, name: 'D10',  type: 'output' },
      { pin: 17, name: 'D11',  type: 'output' },
      { pin: 18, name: 'EOC',  type: 'output' },
      { pin: 19, name: 'SER',  type: 'input'  },
      { pin: 20, name: 'OE',   type: 'input'  },
      { pin: 21, name: 'NC',   type: 'nc'     },
      { pin: 22, name: 'NC',   type: 'nc'     },
      { pin: 23, name: 'NC',   type: 'nc'     },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['SOC','CLK','MSB','SER','OE'], outputs: ['SC','D0','D1','D2','D3','D4','D5','D6','D7','D8','D9','D10','D11','EOC'] },
    ],
  },

  // 74x906: Hex open drain n-channel buffers (14-pin)
  '74906': {
    name: '74x906',
    simpleName: 'Hex Open Drain N-Channel Buffer',
    description: 'Hex open drain n-channel buffers (14-pin)',
    pins: 14, vcc: 14, gnd: 7,
    openCollector: true,
    datasheet: '',
    tags: ['buffer', 'hex', 'open drain', 'open collector'],
    guideOverview: 'The 74x906 is a hex open-drain n-channel buffer. Six BUFFER channels pass their input without inversion, but each output is an open-drain transistor — it can only pull the output LOW, not drive it HIGH. An external pull up resistor is required to bring the output HIGH when the input is LOW. Open-drain outputs allow multiple devices to share a wired OR bus line: any device asserting LOW pulls the shared line LOW regardless of what the others output.',
    pinout: [
      { pin:  1, name: '1A',  type: 'input'  },
      { pin:  2, name: '1Y',  type: 'output' },
      { pin:  3, name: '2A',  type: 'input'  },
      { pin:  4, name: '2Y',  type: 'output' },
      { pin:  5, name: '3A',  type: 'input'  },
      { pin:  6, name: '3Y',  type: 'output' },
      { pin:  7, name: 'GND', type: 'power'  },
      { pin:  8, name: '4Y',  type: 'output' },
      { pin:  9, name: '4A',  type: 'input'  },
      { pin: 10, name: '5Y',  type: 'output' },
      { pin: 11, name: '5A',  type: 'input'  },
      { pin: 12, name: '6Y',  type: 'output' },
      { pin: 13, name: '6A',  type: 'input'  },
      { pin: 14, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'BUFFER', inputs: ['1A'], output: '1Y' },
      { type: 'BUFFER', inputs: ['2A'], output: '2Y' },
      { type: 'BUFFER', inputs: ['3A'], output: '3Y' },
      { type: 'BUFFER', inputs: ['4A'], output: '4Y' },
      { type: 'BUFFER', inputs: ['5A'], output: '5Y' },
      { type: 'BUFFER', inputs: ['6A'], output: '6Y' },
    ],
  },
};