// Chip definitions block 12
// Chips: 74x137, 74x140, 74x141, 74x142, 74x143, 74x144, 74x145, 74x146,
//        74x147, 74x149, 74x152, 74x155, 74x156, 74x158, 74x159, 74x162

export const CHIPS_BLOCK_12 = {

  // ── 74x137: 3-to-8 decoder/demux with address latch, 16-pin ──────────────
  /* Primary source: Texas Instruments, SN74LS137 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls137.pdf
     Wikipedia: https://en.wikipedia.org/wiki/Multiplexer
     Wikipedia: https://en.wikipedia.org/wiki/Flip-flop_(electronics) */
  '74137': {
    name: '74x137',
    simpleName: '3-to-8 Decoder with Latch',
    description: '3-to-8 line decoder/demultiplexer with built in address latch. (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls137.pdf',
    tags: ['decoder', 'demultiplexer', '3-to-8', 'latch', 'inverting'],
    guideOverview: 'The 74137 is a 3-to-8 line decoder/demultiplexer with a built in address latch. Address inputs A, B, and C are latched when LE goes LOW, holding the selected output stable even if the address lines change afterward. When both enable inputs are asserted (G1n=0 and G2=1) exactly one of the eight active LOW outputs Y0 Y7 goes LOW based on the latched address.',
    guidePinDescriptions: {
      A:   'Address input bit 0 (LSB); combined with B and C to select one of eight outputs.',
      B:   'Address input bit 1; middle weight of the 3 bit address.',
      C:   'Address input bit 2 (MSB); combined with A and B to select one of eight outputs.',
      LE:  'Latch Enable; HIGH = transparent (address inputs update the decoder in real time); LOW = latch freezes the last address.',
      G1n: 'Enable input 1 (active LOW). Must be LOW to activate any output.',
      G2:  'Enable input 2 (active HIGH). Must be HIGH to activate any output.',
      Y7:  'Decoder output 7 (active LOW); goes LOW when address = 111 and chip is enabled.',
      GND: 'Ground (0 V) supply.',
      Y6:  'Decoder output 6 (active LOW); goes LOW when address = 110 and chip is enabled.',
      Y5:  'Decoder output 5 (active LOW); goes LOW when address = 101 and chip is enabled.',
      Y4:  'Decoder output 4 (active LOW); goes LOW when address = 100 and chip is enabled.',
      Y3:  'Decoder output 3 (active LOW); goes LOW when address = 011 and chip is enabled.',
      Y2:  'Decoder output 2 (active LOW); goes LOW when address = 010 and chip is enabled.',
      Y1:  'Decoder output 1 (active LOW); goes LOW when address = 001 and chip is enabled.',
      Y0:  'Decoder output 0 (active LOW); goes LOW when address = 000 and chip is enabled.',
      VCC: 'Positive supply (+5 V).',
    },
    guideSections: [
      {
        title: 'Address Latch Operation',
        paragraphs: [
          'While LE is HIGH the latch is transparent: the address on A/B/C passes directly to the decoder. When LE goes LOW the last address is captured and held regardless of subsequent address changes, keeping the selected output stable.',
        ],
        note: 'This latching feature is useful in multiplexed address-bus environments where address lines may change before decoding is complete.',
      },
      {
        title: 'Enable Control and Output Decoding',
        paragraphs: [
          'Both enable inputs must be asserted (G1n=0 AND G2=1) for any output to go LOW. If either enable is de-asserted all outputs go HIGH. The binary value CBA selects output Yi: Y0 for 000 through Y7 for 111.',
        ],
        list: [
          'CBA=000 → Y0 LOW',
          'CBA=001 → Y1 LOW',
          'CBA=010 → Y2 LOW',
          'CBA=011 → Y3 LOW',
          'CBA=100 → Y4 LOW',
          'CBA=101 → Y5 LOW',
          'CBA=110 → Y6 LOW',
          'CBA=111 → Y7 LOW',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'A',   type: 'input',  description: 'Address input bit 0 (LSB)' },
      { pin:  2, name: 'B',   type: 'input',  description: 'Address input bit 1' },
      { pin:  3, name: 'C',   type: 'input',  description: 'Address input bit 2 (MSB)' },
      { pin:  4, name: 'LE',  type: 'input',  description: 'Latch Enable HIGH: transparent (address updates); LOW: address is held/latched' },
      { pin:  5, name: 'G1n', type: 'input',  description: 'Enable input 1 (active LOW); must be LOW to enable outputs' },
      { pin:  6, name: 'G2',  type: 'input',  description: 'Enable input 2 (active HIGH); must be HIGH to enable outputs' },
      { pin:  7, name: 'Y7',  type: 'output', description: 'Decoder output 7 (active LOW)' },
      { pin:  8, name: 'GND', type: 'power',  description: 'Ground (0V)' },
      { pin:  9, name: 'Y6',  type: 'output', description: 'Decoder output 6 (active LOW)' },
      { pin: 10, name: 'Y5',  type: 'output', description: 'Decoder output 5 (active LOW)' },
      { pin: 11, name: 'Y4',  type: 'output', description: 'Decoder output 4 (active LOW)' },
      { pin: 12, name: 'Y3',  type: 'output', description: 'Decoder output 3 (active LOW)' },
      { pin: 13, name: 'Y2',  type: 'output', description: 'Decoder output 2 (active LOW)' },
      { pin: 14, name: 'Y1',  type: 'output', description: 'Decoder output 1 (active LOW)' },
      { pin: 15, name: 'Y0',  type: 'output', description: 'Decoder output 0 (active LOW)' },
      { pin: 16, name: 'VCC', type: 'power',  description: 'Positive supply (+5V)' },
    ],
    gates: [
      { type: 'DEC_3TO8_LATCH', inputs: ['A', 'B', 'C', 'G1n', 'G2', 'LE'], outputs: ['Y0', 'Y1', 'Y2', 'Y3', 'Y4', 'Y5', 'Y6', 'Y7'] },
    ],
    sequential: true,
  },

  // ── 74x140: dual 4 input NAND gate, 50Ω line driver, 14-pin ──────────────
  /* Primary source: Texas Instruments, SN74S140 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74s140.pdf */
  '74140': {
    name: '74x140',
    simpleName: 'Dual 4 input NAND (50Ω)',
    description: 'Dual 4 input NAND gate with 50 ohm line driver outputs (14-pin)',
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74s140.pdf',
    tags: ['logic gate', 'nand', 'combinational', '4 input', 'driver'],
    guideOverview: 'The 74140 contains two independent 4 input NAND gates optimised for driving 50-ohm transmission lines. Each gate asserts its output LOW only when all four inputs are HIGH; any LOW input forces the output HIGH. The enhanced output drive current allows direct connection to coaxial cables without external matching resistors.',
    guidePinDescriptions: {
      '1A':  'Gate 1 input A; one of four inputs to NAND gate 1.',
      '1B':  'Gate 1 input B; one of four inputs to NAND gate 1.',
      NC1:   'No connection; this pin is internally unconnected.',
      '1C':  'Gate 1 input C; one of four inputs to NAND gate 1.',
      '1D':  'Gate 1 input D; one of four inputs to NAND gate 1.',
      '1Y':  'Gate 1 output; LOW when all four inputs (1A 1D) are HIGH, HIGH otherwise.',
      GND:   'Ground (0 V) supply.',
      '2Y':  'Gate 2 output; LOW when all four inputs (2A 2D) are HIGH, HIGH otherwise.',
      '2A':  'Gate 2 input A; one of four inputs to NAND gate 2.',
      '2B':  'Gate 2 input B; one of four inputs to NAND gate 2.',
      NC2:   'No connection; this pin is internally unconnected.',
      '2C':  'Gate 2 input C; one of four inputs to NAND gate 2.',
      '2D':  'Gate 2 input D; one of four inputs to NAND gate 2.',
      VCC:   'Positive supply (+5 V).',
    },
    guideSections: [
      {
        title: '4 Input NAND Function',
        paragraphs: [
          'Each gate computes Y = NOT(A AND B AND C AND D). The output is LOW only when all four inputs are simultaneously HIGH. If any single input is LOW the output is HIGH regardless of the other inputs.',
        ],
        list: [
          'All inputs HIGH → Y = LOW',
          'Any input LOW → Y = HIGH',
        ],
      },
      {
        title: '50-Ohm Line Driver',
        paragraphs: [
          'The 74140 output stage is designed to drive 50-ohm transmission lines directly. The increased sink/source current capability reduces reflections compared to standard TTL gates when used in wired-backplane or cable-interconnect environments.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: '1A',  type: 'input' },
      { pin:  2, name: '1B',  type: 'input' },
      { pin:  3, name: 'NC1', type: 'nc' },
      { pin:  4, name: '1C',  type: 'input' },
      { pin:  5, name: '1D',  type: 'input' },
      { pin:  6, name: '1Y',  type: 'output' },
      { pin:  7, name: 'GND', type: 'power' },
      { pin:  8, name: '2Y',  type: 'output' },
      { pin:  9, name: '2A',  type: 'input' },
      { pin: 10, name: '2B',  type: 'input' },
      { pin: 11, name: 'NC2', type: 'nc' },
      { pin: 12, name: '2C',  type: 'input' },
      { pin: 13, name: '2D',  type: 'input' },
      { pin: 14, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'NAND', inputs: ['1A', '1B', '1C', '1D'], output: '1Y' },
      { type: 'NAND', inputs: ['2A', '2B', '2C', '2D'], output: '2Y' },
    ],
  },



  // ── 74x143: decade counter/latch/7-seg decoder/driver, 15mA CC, 24-pin ───
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Counter_(digital)
     Wikipedia: https://en.wikipedia.org/wiki/Multiplexer
     Wikipedia: https://en.wikipedia.org/wiki/Flip-flop_(electronics) */
  '74143': {
    name: '74x143',
    simpleName: 'Decade Counter/7-Seg Driver (CC)',
    description: 'Decade counter / latch / 7-segment decoder / constant-current driver (15 mA) (24-pin)',
    pins: 24,
    vcc: 24,
    gnd: 12,
    datasheet: 'https://en.wikipedia.org/wiki/7400-series_integrated_circuits',
    tags: ['counter', 'decoder', '7-segment', 'bcd', 'latch', 'sequential'],
    guideOverview: 'The 74143 is a fully integrated BCD decade counter with an internal output latch, BCD-to-7-segment decoder, and constant-current (15 mA) segment drivers. The counter advances on each rising CLK edge when ENP and ENT are both HIGH. Asserting STROBE HIGH captures the current count in the latch, holding the 7-segment outputs stable while counting continues.',
    guidePinDescriptions: {
      CLK:    'Clock input; the counter increments on the rising edge when ENP and ENT are HIGH.',
      CLR:    'Synchronous clear; when HIGH at the rising CLK edge the counter resets to 0000.',
      STROBE: 'Latch strobe; when HIGH the current BCD count is latched and segment outputs are frozen.',
      ENP:    'Count enable P; both ENP and ENT must be HIGH for the counter to advance.',
      ENT:    'Count enable T; also gates the RCO output RCO is HIGH only when ENT=1 and count=9.',
      A:      'Parallel load input A (LSB); loaded into QA when LOAD is asserted (if implemented).',
      B:      'Parallel load input B.',
      C:      'Parallel load input C.',
      D:      'Parallel load input D (MSB).',
      RCO:    'Ripple Carry Output; goes HIGH when the count reaches 9 and ENT is HIGH, enabling cascaded counters.',
      QA:     'BCD counter output bit 0 (LSB, weight 1).',
      GND:    'Ground (0 V) supply.',
      QB:     'BCD counter output bit 1 (weight 2).',
      QC:     'BCD counter output bit 2 (weight 4).',
      QD:     'BCD counter output bit 3 (MSB, weight 8).',
      a:      '7-segment driver output a (top horizontal segment).',
      b:      '7-segment driver output b (upper-right vertical segment).',
      c:      '7-segment driver output c (lower-right vertical segment).',
      d:      '7-segment driver output d (bottom horizontal segment).',
      e:      '7-segment driver output e (lower-left vertical segment).',
      f:      '7-segment driver output f (upper-left vertical segment).',
      g:      '7-segment driver output g (middle horizontal segment).',
      NC1:    'No connection; internally unconnected.',
      VCC:    'Positive supply (+5 V).',
    },
    guideSections: [
      {
        title: 'Counter and Latch Operation',
        paragraphs: [
          'The internal decade counter counts 0 9 and resets on the next clock after 9, producing a carry on RCO. When STROBE goes HIGH the current count is transferred to the latch; the 7-segment outputs then display the latched digit while the counter may continue running behind it.',
        ],
        note: 'CLR is synchronous it resets the counter only on the next rising CLK edge, not immediately.',
      },
      {
        title: 'Segment Driver Interface',
        paragraphs: [
          'Outputs a g are constant-current drivers suitable for direct connection to common-cathode LED displays. The 74143 provides approximately 15 mA per segment, eliminating the need for external current-limiting resistors in many designs.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'CLK',    type: 'input' },
      { pin:  2, name: 'CLR',    type: 'input' },
      { pin:  3, name: 'STROBE', type: 'input' },
      { pin:  4, name: 'ENP',    type: 'input' },
      { pin:  5, name: 'ENT',    type: 'input' },
      { pin:  6, name: 'A',      type: 'input' },
      { pin:  7, name: 'B',      type: 'input' },
      { pin:  8, name: 'C',      type: 'input' },
      { pin:  9, name: 'D',      type: 'input' },
      { pin: 10, name: 'RCO',    type: 'output' },
      { pin: 11, name: 'QA',     type: 'output' },
      { pin: 12, name: 'GND',    type: 'power' },
      { pin: 13, name: 'QB',     type: 'output' },
      { pin: 14, name: 'QC',     type: 'output' },
      { pin: 15, name: 'QD',     type: 'output' },
      { pin: 16, name: 'a',      type: 'output' },
      { pin: 17, name: 'b',      type: 'output' },
      { pin: 18, name: 'c',      type: 'output' },
      { pin: 19, name: 'd',      type: 'output' },
      { pin: 20, name: 'e',      type: 'output' },
      { pin: 21, name: 'f',      type: 'output' },
      { pin: 22, name: 'g',      type: 'output' },
      { pin: 23, name: 'NC1',    type: 'nc' },
      { pin: 24, name: 'VCC',    type: 'power' },
    ],
    gates: [
      { type: 'COUNTER_7SEG', inputs: ['CLK', 'CLR', 'STROBE', 'ENP', 'ENT'], outputs: ['QA', 'QB', 'QC', 'QD', 'RCO', 'a', 'b', 'c', 'd', 'e', 'f', 'g'] },
    ],
    sequential: true,
  },

  // ── 74x144: decade counter/latch/7-seg driver, OC 15V/25mA, 24-pin ───────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Counter_(digital)
     Wikipedia: https://en.wikipedia.org/wiki/Multiplexer
     Wikipedia: https://en.wikipedia.org/wiki/Flip-flop_(electronics)
     Wikipedia: https://en.wikipedia.org/wiki/Open_collector */
  '74144': {
    name: '74x144',
    simpleName: 'Decade Counter/7-Seg Driver (OC)',
    description: 'Decade counter / latch / 7-segment decoder / open-collector driver (15V, 25mA) (24-pin)',
    pins: 24,
    vcc: 24,
    gnd: 12,
    openCollector: true,
    datasheet: 'https://en.wikipedia.org/wiki/7400-series_integrated_circuits',
    tags: ['counter', 'decoder', '7-segment', 'bcd', 'latch', 'open-collector', 'sequential'],
    guideOverview: 'The 74144 is functionally identical to the 74143 but its segment drivers use open-collector outputs rated at 15V and 25mA per segment. This makes it suitable for driving gas-discharge, incandescent, or other high-voltage displays that require an external supply voltage above 5V. An external pull up resistor is required on each segment output.',
    guidePinDescriptions: {
      CLK:    'Clock input; the counter increments on the rising edge when ENP and ENT are HIGH.',
      CLR:    'Synchronous clear; when HIGH at the rising CLK edge the counter resets to 0000.',
      STROBE: 'Latch strobe; when HIGH the current BCD count is latched and segment outputs are frozen.',
      ENP:    'Count enable P; both ENP and ENT must be HIGH for the counter to advance.',
      ENT:    'Count enable T; also gates the RCO output RCO is HIGH only when ENT=1 and count=9.',
      A:      'Parallel load input A (LSB).',
      B:      'Parallel load input B.',
      C:      'Parallel load input C.',
      D:      'Parallel load input D (MSB).',
      RCO:    'Ripple Carry Output; HIGH when count=9 and ENT=1, used to cascade multiple counters.',
      QA:     'BCD counter output bit 0 (LSB, weight 1).',
      GND:    'Ground (0 V) supply.',
      QB:     'BCD counter output bit 1 (weight 2).',
      QC:     'BCD counter output bit 2 (weight 4).',
      QD:     'BCD counter output bit 3 (MSB, weight 8).',
      a:      'Open-collector segment driver output a; connect via pull up to the display supply.',
      b:      'Open-collector segment driver output b.',
      c:      'Open-collector segment driver output c.',
      d:      'Open-collector segment driver output d.',
      e:      'Open-collector segment driver output e.',
      f:      'Open-collector segment driver output f.',
      g:      'Open-collector segment driver output g.',
      NC1:    'No connection; internally unconnected.',
      VCC:    'Positive supply (+5 V).',
    },
    guideSections: [
      {
        title: 'Counter and Latch Operation',
        paragraphs: [
          'Identical to the 74143: the decade counter advances on CLK rising edges when ENP and ENT are HIGH, STROBE latches the count for stable display, and CLR synchronously resets on the next clock edge.',
        ],
      },
      {
        title: 'Open Collector High-Voltage Driver',
        paragraphs: [
          'Unlike the 74143, segment outputs are open-collector and can switch up to 15V. Connect an external pull up resistor from each segment output to the display supply voltage. The outputs can sink 25 mA, allowing direct drive of higher-power segment types.',
        ],
        note: 'Do not connect the segment supply directly to VCC (+5V) if using a higher-voltage display; the open-collector structure isolates the display voltage from the logic supply.',
      },
    ],
    pinout: [
      { pin:  1, name: 'CLK',    type: 'input' },
      { pin:  2, name: 'CLR',    type: 'input' },
      { pin:  3, name: 'STROBE', type: 'input' },
      { pin:  4, name: 'ENP',    type: 'input' },
      { pin:  5, name: 'ENT',    type: 'input' },
      { pin:  6, name: 'A',      type: 'input' },
      { pin:  7, name: 'B',      type: 'input' },
      { pin:  8, name: 'C',      type: 'input' },
      { pin:  9, name: 'D',      type: 'input' },
      { pin: 10, name: 'RCO',    type: 'output' },
      { pin: 11, name: 'QA',     type: 'output' },
      { pin: 12, name: 'GND',    type: 'power' },
      { pin: 13, name: 'QB',     type: 'output' },
      { pin: 14, name: 'QC',     type: 'output' },
      { pin: 15, name: 'QD',     type: 'output' },
      { pin: 16, name: 'a',      type: 'output' },
      { pin: 17, name: 'b',      type: 'output' },
      { pin: 18, name: 'c',      type: 'output' },
      { pin: 19, name: 'd',      type: 'output' },
      { pin: 20, name: 'e',      type: 'output' },
      { pin: 21, name: 'f',      type: 'output' },
      { pin: 22, name: 'g',      type: 'output' },
      { pin: 23, name: 'NC1',    type: 'nc' },
      { pin: 24, name: 'VCC',    type: 'power' },
    ],
    gates: [
      { type: 'COUNTER_7SEG', inputs: ['CLK', 'CLR', 'STROBE', 'ENP', 'ENT'], outputs: ['QA', 'QB', 'QC', 'QD', 'RCO', 'a', 'b', 'c', 'd', 'e', 'f', 'g'] },
    ],
    sequential: true,
  },

  // ── 74x145: BCD to decimal decoder/driver, OC 15V/80mA, 16-pin ──────────
  /* Primary source: Texas Instruments, SN74LS145 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls145.pdf
     Wikipedia: https://en.wikipedia.org/wiki/Multiplexer
     Wikipedia: https://en.wikipedia.org/wiki/Open_collector */
  '74145': {
    name: '74x145',
    simpleName: 'BCD to Decimal Decoder (OC)',
    description: 'BCD-to-decimal (1-of-10) decoder with open-collector outputs. (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    openCollector: true,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls145.pdf',
    tags: ['decoder', 'bcd', 'decimal', 'driver', 'open-collector', '10-line', '1-of-10'],
    guideOverview: 'The 74145 decodes a 4 bit BCD input (A=LSB, D=MSB) into one of ten active LOW open-collector outputs Y0 Y9. For invalid BCD codes (10 15) all outputs remain HIGH. The open-collector outputs can sink up to 80 mA at up to 15V, making them suitable for driving relays, indicator lamps, and high-current digit-selection lines.',
    guidePinDescriptions: {
      Y0:  'Decimal output 0 (open-collector, active LOW); pulled LOW when BCD input = 0000.',
      Y1:  'Decimal output 1 (open-collector, active LOW); pulled LOW when BCD input = 0001.',
      Y2:  'Decimal output 2 (open-collector, active LOW); pulled LOW when BCD input = 0010.',
      Y3:  'Decimal output 3 (open-collector, active LOW); pulled LOW when BCD input = 0011.',
      Y4:  'Decimal output 4 (open-collector, active LOW); pulled LOW when BCD input = 0100.',
      Y5:  'Decimal output 5 (open-collector, active LOW); pulled LOW when BCD input = 0101.',
      Y6:  'Decimal output 6 (open-collector, active LOW); pulled LOW when BCD input = 0110.',
      GND: 'Ground (0 V) supply.',
      Y7:  'Decimal output 7 (open-collector, active LOW); pulled LOW when BCD input = 0111.',
      Y8:  'Decimal output 8 (open-collector, active LOW); pulled LOW when BCD input = 1000.',
      Y9:  'Decimal output 9 (open-collector, active LOW); pulled LOW when BCD input = 1001.',
      D:   'BCD input bit 3 (MSB, weight 8); combined with A, B, C to form the BCD digit.',
      C:   'BCD input bit 2 (weight 4).',
      B:   'BCD input bit 1 (weight 2).',
      A:   'BCD input bit 0 (LSB, weight 1).',
      VCC: 'Positive supply (+5 V).',
    },
    guideSections: [
      {
        title: 'BCD-to-Decimal Decoding',
        paragraphs: [
          'The 4 bit input DCBA is interpreted as a BCD digit 0 9. The corresponding output Yi is pulled LOW while all others remain HIGH (open, requiring pull up resistors). BCD codes 1010 1111 are invalid; all outputs stay HIGH for these inputs.',
        ],
        list: [
          'DCBA = 0000 → Y0 LOW (digit 0)',
          'DCBA = 0001 → Y1 LOW (digit 1)',
          '... and so on through ...',
          'DCBA = 1001 → Y9 LOW (digit 9)',
          'DCBA = 1010 1111 → all outputs HIGH (invalid)',
        ],
      },
      {
        title: 'Open Collector Outputs',
        paragraphs: [
          'Each output is an open-collector NPN transistor capable of sinking 80 mA and blocking up to 15V. Connect an external pull up resistor from each output to the load supply. This allows driving loads such as neon indicator lamps or relay coils directly.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'Y0',  type: 'output', description: 'Decimal output 0 (open-collector, active LOW)' },
      { pin:  2, name: 'Y1',  type: 'output', description: 'Decimal output 1 (open-collector, active LOW)' },
      { pin:  3, name: 'Y2',  type: 'output', description: 'Decimal output 2 (open-collector, active LOW)' },
      { pin:  4, name: 'Y3',  type: 'output', description: 'Decimal output 3 (open-collector, active LOW)' },
      { pin:  5, name: 'Y4',  type: 'output', description: 'Decimal output 4 (open-collector, active LOW)' },
      { pin:  6, name: 'Y5',  type: 'output', description: 'Decimal output 5 (open-collector, active LOW)' },
      { pin:  7, name: 'Y6',  type: 'output', description: 'Decimal output 6 (open-collector, active LOW)' },
      { pin:  8, name: 'GND', type: 'power',  description: 'Ground (0V)' },
      { pin:  9, name: 'Y7',  type: 'output', description: 'Decimal output 7 (open-collector, active LOW)' },
      { pin: 10, name: 'Y8',  type: 'output', description: 'Decimal output 8 (open-collector, active LOW)' },
      { pin: 11, name: 'Y9',  type: 'output', description: 'Decimal output 9 (open-collector, active LOW)' },
      { pin: 12, name: 'D',   type: 'input',  description: 'BCD input bit 3 (MSB, weight 8)' },
      { pin: 13, name: 'C',   type: 'input',  description: 'BCD input bit 2 (weight 4)' },
      { pin: 14, name: 'B',   type: 'input',  description: 'BCD input bit 1 (weight 2)' },
      { pin: 15, name: 'A',   type: 'input',  description: 'BCD input bit 0 (LSB, weight 1)' },
      { pin: 16, name: 'VCC', type: 'power',  description: 'Positive supply (+5V)' },
    ],
    gates: [
      { type: 'BCD_DECIMAL', inputs: ['A', 'B', 'C', 'D'], outputs: ['Y0', 'Y1', 'Y2', 'Y3', 'Y4', 'Y5', 'Y6', 'Y7', 'Y8', 'Y9'] },
    ],
  },

  // ── 74x146: 3-to-8 line decoder (H-family), 16-pin ───────────────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Multiplexer */
  '74146': {
    name: '74x146',
    simpleName: '3-to-8 Decoder',
    description: '3-to-8 line decoder/demultiplexer (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://en.wikipedia.org/wiki/7400-series_integrated_circuits',
    tags: ['decoder', 'demultiplexer', '3-to-8', 'inverting'],
    guideOverview: 'The 74146 is a 3-to-8 line decoder/demultiplexer similar to the 74138. The three address inputs A, B, and C select one of eight active LOW outputs Y0 Y7. All outputs are forced HIGH when enable input G1 is LOW or when either G2A or G2B is HIGH.',
    guidePinDescriptions: {
      A:   'Address input bit 0 (LSB); determines which output is selected.',
      B:   'Address input bit 1; middle weight address bit.',
      C:   'Address input bit 2 (MSB); determines which output is selected.',
      G2A: 'Active LOW enable input A; must be LOW to enable outputs.',
      G2B: 'Active LOW enable input B; must be LOW to enable outputs.',
      G1:  'Active HIGH enable input; must be HIGH to enable outputs.',
      Y7:  'Decoder output 7 (active LOW); LOW when CBA=111 and chip is enabled.',
      GND: 'Ground (0 V) supply.',
      Y6:  'Decoder output 6 (active LOW); LOW when CBA=110 and chip is enabled.',
      Y5:  'Decoder output 5 (active LOW); LOW when CBA=101 and chip is enabled.',
      Y4:  'Decoder output 4 (active LOW); LOW when CBA=100 and chip is enabled.',
      Y3:  'Decoder output 3 (active LOW); LOW when CBA=011 and chip is enabled.',
      Y2:  'Decoder output 2 (active LOW); LOW when CBA=010 and chip is enabled.',
      Y1:  'Decoder output 1 (active LOW); LOW when CBA=001 and chip is enabled.',
      Y0:  'Decoder output 0 (active LOW); LOW when CBA=000 and chip is enabled.',
      VCC: 'Positive supply (+5 V).',
    },
    guideSections: [
      {
        title: 'Decoding and Enable Logic',
        paragraphs: [
          'The chip is enabled when G1=1 AND G2A=0 AND G2B=0. Once enabled, the binary value CBA selects one output: Yi goes LOW while all others remain HIGH. If any enable condition fails, all outputs are HIGH (inactive).',
        ],
        list: [
          'CBA=000 → Y0 LOW',
          'CBA=001 → Y1 LOW',
          'CBA=010 → Y2 LOW',
          'CBA=011 → Y3 LOW',
          'CBA=100 → Y4 LOW',
          'CBA=101 → Y5 LOW',
          'CBA=110 → Y6 LOW',
          'CBA=111 → Y7 LOW',
        ],
      },
      {
        title: 'Demultiplexer Use',
        paragraphs: [
          'When used as a demultiplexer, one of the enable inputs (e.g. G2A) serves as the data input. The data signal is steered to the output selected by CBA; the signal appears inverted at the selected output due to the active LOW output convention.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'A',   type: 'input' },
      { pin:  2, name: 'B',   type: 'input' },
      { pin:  3, name: 'C',   type: 'input' },
      { pin:  4, name: 'G2A', type: 'input' },
      { pin:  5, name: 'G2B', type: 'input' },
      { pin:  6, name: 'G1',  type: 'input' },
      { pin:  7, name: 'Y7',  type: 'output' },
      { pin:  8, name: 'GND', type: 'power' },
      { pin:  9, name: 'Y6',  type: 'output' },
      { pin: 10, name: 'Y5',  type: 'output' },
      { pin: 11, name: 'Y4',  type: 'output' },
      { pin: 12, name: 'Y3',  type: 'output' },
      { pin: 13, name: 'Y2',  type: 'output' },
      { pin: 14, name: 'Y1',  type: 'output' },
      { pin: 15, name: 'Y0',  type: 'output' },
      { pin: 16, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'DECODER_3TO8', inputs: ['A', 'B', 'C', 'G1', 'G2A', 'G2B'], outputs: ['Y0', 'Y1', 'Y2', 'Y3', 'Y4', 'Y5', 'Y6', 'Y7'] },
    ],
  },

  // ── 74x147: 10-to-4-line BCD priority encoder, 16-pin ────────────────────
  /* Primary source: Texas Instruments, SN74LS147 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls147.pdf
     Wikipedia: https://en.wikipedia.org/wiki/Priority_encoder */
  '74147': {
    name: '74x147',
    simpleName: '10-to-4 Priority Encoder (BCD)',
    description: '10-line to 4-line (decimal to BCD) priority encoder. (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls147.pdf',
    tags: ['encoder', 'priority', 'bcd', '10-to-4', 'active low', 'decimal'],
    guideOverview: 'The 74147 is a 9-line (I1 I9) to 4-line priority encoder that produces the active LOW BCD code of the highest-priority asserted input. Input I9 has the highest priority and I1 the lowest. Input I0 (representing decimal 0) is implicit when no input is asserted the outputs represent 0 (all HIGH in active LOW form).',
    guidePinDescriptions: {
      I4:  'Active LOW input 4 (decimal digit 4); assert LOW to encode value 4.',
      I5:  'Active LOW input 5 (decimal digit 5); assert LOW to encode value 5.',
      I6:  'Active LOW input 6 (decimal digit 6); assert LOW to encode value 6.',
      I7:  'Active LOW input 7 (decimal digit 7); assert LOW to encode value 7.',
      I8:  'Active LOW input 8 (decimal digit 8); assert LOW to encode value 8.',
      A2n: 'BCD output bit 2 (active LOW, weight 4); complement of DCBA bit 2.',
      A1n: 'BCD output bit 1 (active LOW, weight 2); complement of DCBA bit 1.',
      GND: 'Ground (0 V) supply.',
      A0n: 'BCD output bit 0 (active LOW, LSB, weight 1); complement of DCBA bit 0.',
      I9:  'Active LOW input 9 (decimal digit 9, highest priority); assert LOW to encode value 9.',
      I1:  'Active LOW input 1 (decimal digit 1, lowest priority); assert LOW to encode value 1.',
      I2:  'Active LOW input 2 (decimal digit 2); assert LOW to encode value 2.',
      I3:  'Active LOW input 3 (decimal digit 3); assert LOW to encode value 3.',
      A3n: 'BCD output bit 3 (active LOW, MSB, weight 8); complement of DCBA bit 3.',
      NC:  'No connection; internally unconnected.',
      VCC: 'Positive supply (+5 V).',
    },
    guideSections: [
      {
        title: 'Priority Encoding',
        paragraphs: [
          'All inputs are active LOW. When multiple inputs are asserted simultaneously, the highest-numbered asserted input takes priority. The 4 bit active LOW BCD output (A3n, A2n, A1n, A0n) reflects the encoded decimal value invert all four bits to obtain standard positive-logic BCD.',
        ],
        list: [
          'I9=0 (any others) → A3n A2n A1n A0n = 0110 (BCD 9)',
          'I8=0, I9=1 → output = 0111 (BCD 8)',
          'No inputs asserted → output = 1111 (BCD 0)',
        ],
        note: 'The chip has no enable input. Cascading requires external logic.',
      },
      {
        title: 'Active LOW Output Convention',
        paragraphs: [
          'Outputs A3n A0n are the complement of the standard BCD value. To obtain positive-logic BCD connect these outputs to inverters or to a device that accepts active LOW BCD inputs (such as the 74145 decoder).',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'I4',  type: 'input',  description: 'Active LOW input 4 (decimal digit 4)' },
      { pin:  2, name: 'I5',  type: 'input',  description: 'Active LOW input 5 (decimal digit 5)' },
      { pin:  3, name: 'I6',  type: 'input',  description: 'Active LOW input 6 (decimal digit 6)' },
      { pin:  4, name: 'I7',  type: 'input',  description: 'Active LOW input 7 (decimal digit 7)' },
      { pin:  5, name: 'I8',  type: 'input',  description: 'Active LOW input 8 (decimal digit 8)' },
      { pin:  6, name: 'A2n', type: 'output', description: 'BCD output bit 2 (active LOW, weight 4)' },
      { pin:  7, name: 'A1n', type: 'output', description: 'BCD output bit 1 (active LOW, weight 2)' },
      { pin:  8, name: 'GND', type: 'power',  description: 'Ground (0V)' },
      { pin:  9, name: 'A0n', type: 'output', description: 'BCD output bit 0, LSB (active LOW, weight 1)' },
      { pin: 10, name: 'I9',  type: 'input',  description: 'Active LOW input 9 (decimal digit 9, highest priority)' },
      { pin: 11, name: 'I1',  type: 'input',  description: 'Active LOW input 1 (decimal digit 1)' },
      { pin: 12, name: 'I2',  type: 'input',  description: 'Active LOW input 2 (decimal digit 2)' },
      { pin: 13, name: 'I3',  type: 'input',  description: 'Active LOW input 3 (decimal digit 3)' },
      { pin: 14, name: 'A3n', type: 'output', description: 'BCD output bit 3, MSB (active LOW, weight 8)' },
      { pin: 15, name: 'NC',  type: 'nc',     description: 'No connection' },
      { pin: 16, name: 'VCC', type: 'power',  description: 'Positive supply (+5V)' },
    ],
    gates: [
      { type: 'PRIORITY_ENC_10TO4', inputs: ['I1', 'I2', 'I3', 'I4', 'I5', 'I6', 'I7', 'I8', 'I9'], outputs: ['A0n', 'A1n', 'A2n', 'A3n'] },
    ],
  },

  // ── 74x149: 8-line cascadable 1-of-8 priority encoder, 20-pin ────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Priority_encoder */
  '74149': {
    name: '74x149',
    simpleName: '8-line Priority Encoder',
    description: '8-line to 8-line cascadable priority encoder; each output LOW for highest-priority active input (20-pin)',
    pins: 20,
    vcc: 20,
    gnd: 10,
    datasheet: 'https://en.wikipedia.org/wiki/7400-series_integrated_circuits',
    tags: ['encoder', 'priority', '8-line', 'cascadable'],
    guideOverview: 'The 74149 is a cascadable 8-line priority encoder. When Enable Input EI is LOW the chip examines inputs X0 X7 and drives the output Yi LOW that corresponds to the highest-priority asserted input. Enable Output EO goes LOW when EI is LOW and no input is asserted, allowing multiple 74149s to be daisy-chained for wider priority encoders.',
    guidePinDescriptions: {
      X0:  'Priority input 0 (active LOW, lowest priority); assert LOW to select output Y0.',
      X1:  'Priority input 1 (active LOW); assert LOW to select output Y1.',
      X2:  'Priority input 2 (active LOW); assert LOW to select output Y2.',
      X3:  'Priority input 3 (active LOW); assert LOW to select output Y3.',
      X4:  'Priority input 4 (active LOW); assert LOW to select output Y4.',
      X5:  'Priority input 5 (active LOW); assert LOW to select output Y5.',
      X6:  'Priority input 6 (active LOW); assert LOW to select output Y6.',
      X7:  'Priority input 7 (active LOW, highest priority); assert LOW to select output Y7.',
      EI:  'Enable Input (active LOW); chip is active when EI=0. When EI=1 all outputs are HIGH.',
      GND: 'Ground (0 V) supply.',
      Y7:  'Priority output 7 (active LOW); LOW when X7=0 and chip is enabled.',
      Y6:  'Priority output 6 (active LOW); LOW when X6=0 is highest priority.',
      Y5:  'Priority output 5 (active LOW); LOW when X5=0 is highest priority.',
      Y4:  'Priority output 4 (active LOW); LOW when X4=0 is highest priority.',
      Y3:  'Priority output 3 (active LOW); LOW when X3=0 is highest priority.',
      Y2:  'Priority output 2 (active LOW); LOW when X2=0 is highest priority.',
      Y1:  'Priority output 1 (active LOW); LOW when X1=0 is highest priority.',
      Y0:  'Priority output 0 (active LOW); LOW when X0=0 is highest priority.',
      EO:  'Enable Output (active LOW); goes LOW when EI=0 and no input is asserted, enabling the next cascaded device.',
      VCC: 'Positive supply (+5 V).',
    },
    guideSections: [
      {
        title: 'Priority and Enable Operation',
        paragraphs: [
          'When EI is LOW the chip scans X0 X7. The output Yi corresponding to the highest-priority asserted input goes LOW; all other outputs remain HIGH. X7 has the highest priority. When no input is asserted and EI=0, EO goes LOW.',
        ],
        note: 'Unlike the 74148, this encoder drives one output LOW per input rather than producing a binary code. Connect EO of a lower-priority device to EI of the next to cascade.',
      },
      {
        title: 'Cascading Multiple Devices',
        paragraphs: [
          'To expand beyond 8 inputs, chain EO of the lower-priority 74149 to EI of the higher-priority 74149. The lower-priority device only activates (EO goes LOW) when no input on the higher-priority device is asserted.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'X0',  type: 'input' },
      { pin:  2, name: 'X1',  type: 'input' },
      { pin:  3, name: 'X2',  type: 'input' },
      { pin:  4, name: 'X3',  type: 'input' },
      { pin:  5, name: 'X4',  type: 'input' },
      { pin:  6, name: 'X5',  type: 'input' },
      { pin:  7, name: 'X6',  type: 'input' },
      { pin:  8, name: 'X7',  type: 'input' },
      { pin:  9, name: 'EI',  type: 'input' },
      { pin: 10, name: 'GND', type: 'power' },
      { pin: 11, name: 'Y7',  type: 'output' },
      { pin: 12, name: 'Y6',  type: 'output' },
      { pin: 13, name: 'Y5',  type: 'output' },
      { pin: 14, name: 'Y4',  type: 'output' },
      { pin: 15, name: 'Y3',  type: 'output' },
      { pin: 16, name: 'Y2',  type: 'output' },
      { pin: 17, name: 'Y1',  type: 'output' },
      { pin: 18, name: 'Y0',  type: 'output' },
      { pin: 19, name: 'EO',  type: 'output' },
      { pin: 20, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'PRIORITY_ENC_8LINE', inputs: ['X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'EI'], outputs: ['Y0', 'Y1', 'Y2', 'Y3', 'Y4', 'Y5', 'Y6', 'Y7', 'EO'] },
    ],
  },

  // ── 74x152: 8-to-1 data selector/mux, complemented output, 14-pin ────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Multiplexer */
  '74152': {
    name: '74x152',
    simpleName: '8-to-1 MUX (inverted output)',
    description: '8-line to 1-line data selector/multiplexer with inverted (complemented) output (14-pin)',
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://en.wikipedia.org/wiki/7400-series_integrated_circuits',
    tags: ['multiplexer', 'mux', '8-to-1', 'selector', 'inverting'],
    guideOverview: 'The 74152 is an 8-line to 1-line data selector/multiplexer. Three select inputs C (MSB), B, and A (LSB) choose one of eight data inputs D0 D7, and the selected data value appears inverted at output W. Unlike the 74151 there is no non-inverting output and no enable (strobe) input.',
    guidePinDescriptions: {
      D3:  'Data input 3; selected when CBA=011.',
      D2:  'Data input 2; selected when CBA=010.',
      D1:  'Data input 1; selected when CBA=001.',
      D0:  'Data input 0; selected when CBA=000.',
      A:   'Select input bit 0 (LSB); least-significant address bit.',
      B:   'Select input bit 1; middle address bit.',
      GND: 'Ground (0 V) supply.',
      C:   'Select input bit 2 (MSB); most-significant address bit.',
      W:   'Multiplexer output (inverted); W = NOT(D[CBA]).',
      D4:  'Data input 4; selected when CBA=100.',
      D5:  'Data input 5; selected when CBA=101.',
      D6:  'Data input 6; selected when CBA=110.',
      D7:  'Data input 7; selected when CBA=111.',
      VCC: 'Positive supply (+5 V).',
    },
    guideSections: [
      {
        title: '8-to-1 Selection',
        paragraphs: [
          'The binary value CBA (C=MSB, A=LSB) addresses one of eight data inputs. The selected input value is inverted and presented at W. There is no enable input, so the output always reflects the selected data.',
        ],
        list: [
          'CBA=000 → W = NOT D0',
          'CBA=001 → W = NOT D1',
          'CBA=010 → W = NOT D2',
          'CBA=011 → W = NOT D3',
          'CBA=100 → W = NOT D4',
          'CBA=101 → W = NOT D5',
          'CBA=110 → W = NOT D6',
          'CBA=111 → W = NOT D7',
        ],
        note: 'Use a NOT gate after W or invert all data inputs to obtain a non-inverting output.',
      },
    ],
    pinout: [
      { pin:  1, name: 'D3',  type: 'input' },
      { pin:  2, name: 'D2',  type: 'input' },
      { pin:  3, name: 'D1',  type: 'input' },
      { pin:  4, name: 'D0',  type: 'input' },
      { pin:  5, name: 'A',   type: 'input' },
      { pin:  6, name: 'B',   type: 'input' },
      { pin:  7, name: 'GND', type: 'power' },
      { pin:  8, name: 'C',   type: 'input' },
      { pin:  9, name: 'W',   type: 'output' },
      { pin: 10, name: 'D4',  type: 'input' },
      { pin: 11, name: 'D5',  type: 'input' },
      { pin: 12, name: 'D6',  type: 'input' },
      { pin: 13, name: 'D7',  type: 'input' },
      { pin: 14, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'MUX_8TO1_INV', inputs: ['D0', 'D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'A', 'B', 'C'], outputs: ['W'] },
    ],
  },

  // ── 74x155: dual 2-to-4 decoder/demux, 16-pin ────────────────────────────
  /* Primary source: Texas Instruments, SN74LS155A datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls155a.pdf
     Wikipedia: https://en.wikipedia.org/wiki/Multiplexer */
  '74155': {
    name: '74x155',
    simpleName: 'Dual 2-to-4 Decoder/Demux',
    description: 'Dual 2-to-4 line decoder/demultiplexer. (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls155a.pdf',
    tags: ['decoder', 'demultiplexer', '2-to-4', 'dual', 'inverting'],
    guideOverview: 'The 74155 contains two independent 2-to-4 line decoder/demultiplexer sections sharing the address inputs A and B. Section 1 is enabled when 1G=0 AND 1C=0 (both active LOW); Section 2 is enabled when 2G=0 AND 2Cn=1 (2Cn is active HIGH). The selected output in each section goes LOW; unselected outputs remain HIGH.',
    guidePinDescriptions: {
      '1C':  'Section 1 data/strobe (active LOW); must be LOW with 1G=LOW to enable Section 1.',
      '1G':  'Section 1 enable/gate (active LOW); must be LOW to enable Section 1 outputs.',
      B:     'Address bit 1, shared by both sections; selects row in the 2×2 decode matrix.',
      '1Y3': 'Section 1 output 3 (active LOW); LOW when A=1, B=1 and Section 1 is enabled.',
      '1Y2': 'Section 1 output 2 (active LOW); LOW when A=0, B=1 and Section 1 is enabled.',
      '1Y1': 'Section 1 output 1 (active LOW); LOW when A=1, B=0 and Section 1 is enabled.',
      '1Y0': 'Section 1 output 0 (active LOW); LOW when A=0, B=0 and Section 1 is enabled.',
      GND:   'Ground (0 V) supply.',
      '2Y0': 'Section 2 output 0 (active LOW); LOW when A=0, B=0 and Section 2 is enabled.',
      '2Y1': 'Section 2 output 1 (active LOW); LOW when A=1, B=0 and Section 2 is enabled.',
      '2Y2': 'Section 2 output 2 (active LOW); LOW when A=0, B=1 and Section 2 is enabled.',
      '2Y3': 'Section 2 output 3 (active LOW); LOW when A=1, B=1 and Section 2 is enabled.',
      A:     'Address bit 0, shared by both sections; selects column in the 2×2 decode matrix.',
      '2G':  'Section 2 enable/gate (active LOW); must be LOW to enable Section 2 outputs.',
      '2Cn': 'Section 2 data/strobe (active HIGH); must be HIGH with 2G=LOW to enable Section 2.',
      VCC:   'Positive supply (+5 V).',
    },
    guideSections: [
      {
        title: 'Dual Section Enable Logic',
        paragraphs: [
          'Section 1 requires 1G=0 AND 1C=0. Section 2 requires 2G=0 AND 2Cn=1. The different enable polarities (both active LOW vs. active LOW + active HIGH) allow a single data line to be demultiplexed to two separate 4-output buses by connecting it as the strobe while the common address selects the target output.',
        ],
        note: 'Both sections share address lines A and B, so they always decode the same address but may be independently enabled.',
      },
      {
        title: 'Output Decode Truth Table',
        paragraphs: [
          'When a section is enabled the selected output goes LOW and all others stay HIGH.',
        ],
        list: [
          'BA=00 → Y0 LOW',
          'BA=01 → Y1 LOW',
          'BA=10 → Y2 LOW',
          'BA=11 → Y3 LOW',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: '1C',  type: 'input',  description: 'Section 1 data/strobe input (active LOW; must be LOW with 1G=LOW to enable)' },
      { pin:  2, name: '1G',  type: 'input',  description: 'Section 1 enable/strobe (active LOW gate)' },
      { pin:  3, name: 'B',   type: 'input',  description: 'Address bit 1 (shared by both sections)' },
      { pin:  4, name: '1Y3', type: 'output', description: 'Section 1 output 3 (active LOW; selected when A=1, B=1)' },
      { pin:  5, name: '1Y2', type: 'output', description: 'Section 1 output 2 (active LOW; selected when A=0, B=1)' },
      { pin:  6, name: '1Y1', type: 'output', description: 'Section 1 output 1 (active LOW; selected when A=1, B=0)' },
      { pin:  7, name: '1Y0', type: 'output', description: 'Section 1 output 0 (active LOW; selected when A=0, B=0)' },
      { pin:  8, name: 'GND', type: 'power',  description: 'Ground (0V)' },
      { pin:  9, name: '2Y0', type: 'output', description: 'Section 2 output 0 (active LOW; selected when A=0, B=0)' },
      { pin: 10, name: '2Y1', type: 'output', description: 'Section 2 output 1 (active LOW; selected when A=1, B=0)' },
      { pin: 11, name: '2Y2', type: 'output', description: 'Section 2 output 2 (active LOW; selected when A=0, B=1)' },
      { pin: 12, name: '2Y3', type: 'output', description: 'Section 2 output 3 (active LOW; selected when A=1, B=1)' },
      { pin: 13, name: 'A',   type: 'input',  description: 'Address bit 0 (shared by both sections)' },
      { pin: 14, name: '2G',  type: 'input',  description: 'Section 2 enable/strobe (active LOW gate)' },
      { pin: 15, name: '2Cn', type: 'input',  description: 'Section 2 data/strobe input (active HIGH; must be HIGH with 2G=LOW to enable)' },
      { pin: 16, name: 'VCC', type: 'power',  description: 'Positive supply (+5V)' },
    ],
    // Section 1: enabled when 1G=0 AND 1C=0 (NAND strobe, both active LOW)
    // Section 2: enabled when 2G=0 AND 2Cn=1 (AND strobe; '2Cn' suffix triggers internal inversion)
    gates: [
      { type: 'DEMUX_2TO4', inputs: ['A', 'B', '1G', '1C'],  outputs: ['1Y0', '1Y1', '1Y2', '1Y3'] },
      { type: 'DEMUX_2TO4', inputs: ['A', 'B', '2G', '2Cn'], outputs: ['2Y0', '2Y1', '2Y2', '2Y3'] },
    ],
  },

  // ── 74x156: dual 2-to-4 decoder/demux, OC, 16-pin ────────────────────────
  /* Primary source: Texas Instruments, SN74LS156 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls156.pdf
     Wikipedia: https://en.wikipedia.org/wiki/Multiplexer
     Wikipedia: https://en.wikipedia.org/wiki/Open_collector */
  '74156': {
    name: '74x156',
    simpleName: 'Dual 2-to-4 Decoder (OC)',
    description: 'Dual 2-to-4 line decoder/demultiplexer with open-collector outputs; shared address inputs (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    openCollector: true,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls156.pdf',
    tags: ['decoder', 'demultiplexer', '2-to-4', 'dual', 'inverting', 'open-collector'],
    guideOverview: 'The 74156 is functionally identical to the 74155 but replaces the totem-pole output drivers with open-collector outputs. This allows multiple outputs to be wired AND (dot-AND) together or connected to loads operating at voltages higher than VCC. An external pull up resistor is required on each output.',
    guidePinDescriptions: {
      '1G':  'Section 1 enable/gate (active LOW); must be LOW to enable Section 1 outputs.',
      '1C':  'Section 1 data/strobe (active LOW); must be LOW with 1G=LOW to enable Section 1.',
      A:     'Address bit 0, shared by both sections.',
      B:     'Address bit 1, shared by both sections.',
      '1Y3': 'Section 1 open-collector output 3 (active LOW); sinks current when A=1, B=1 and Section 1 enabled.',
      '1Y2': 'Section 1 open-collector output 2 (active LOW); sinks current when A=0, B=1 and Section 1 enabled.',
      '1Y1': 'Section 1 open-collector output 1 (active LOW); sinks current when A=1, B=0 and Section 1 enabled.',
      GND:   'Ground (0 V) supply.',
      '1Y0': 'Section 1 open-collector output 0 (active LOW); sinks current when A=0, B=0 and Section 1 enabled.',
      '2Y0': 'Section 2 open-collector output 0 (active LOW); sinks current when A=0, B=0 and Section 2 enabled.',
      '2Y1': 'Section 2 open-collector output 1 (active LOW); sinks current when A=1, B=0 and Section 2 enabled.',
      '2Y2': 'Section 2 open-collector output 2 (active LOW); sinks current when A=0, B=1 and Section 2 enabled.',
      '2Y3': 'Section 2 open-collector output 3 (active LOW); sinks current when A=1, B=1 and Section 2 enabled.',
      '2Cn': 'Section 2 data/strobe (active HIGH); must be HIGH with 2G=LOW to enable Section 2.',
      '2G':  'Section 2 enable/gate (active LOW); must be LOW to enable Section 2 outputs.',
      VCC:   'Positive supply (+5 V).',
    },
    guideSections: [
      {
        title: 'Open Collector Output Operation',
        paragraphs: [
          'Each output is an open-collector NPN transistor. When selected and enabled the transistor turns on, sinking current to GND (output LOW). When not selected or disabled the transistor is off and the output is floating a pull up resistor to the load supply is required to obtain a HIGH output voltage.',
        ],
        note: 'Outputs from multiple 74156 devices can be wired together to the same pull up, creating a wired AND bus.',
      },
      {
        title: 'Enable and Address Decoding',
        paragraphs: [
          'Section 1 is enabled when 1G=0 AND 1C=0. Section 2 is enabled when 2G=0 AND 2Cn=1. Address BA selects which output of the active section sinks current (BA=00→Y0, BA=01→Y1, BA=10→Y2, BA=11→Y3).',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: '1G',  type: 'input' },
      { pin:  2, name: '1C',  type: 'input' },
      { pin:  3, name: 'A',   type: 'input' },
      { pin:  4, name: 'B',   type: 'input' },
      { pin:  5, name: '1Y3', type: 'output' },
      { pin:  6, name: '1Y2', type: 'output' },
      { pin:  7, name: '1Y1', type: 'output' },
      { pin:  8, name: 'GND', type: 'power' },
      { pin:  9, name: '1Y0', type: 'output' },
      { pin: 10, name: '2Y0', type: 'output' },
      { pin: 11, name: '2Y1', type: 'output' },
      { pin: 12, name: '2Y2', type: 'output' },
      { pin: 13, name: '2Y3', type: 'output' },
      { pin: 14, name: '2Cn', type: 'input' },
      { pin: 15, name: '2G',  type: 'input' },
      { pin: 16, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'DEMUX_2TO4', inputs: ['A', 'B', '1G', '1C'],  outputs: ['1Y0', '1Y1', '1Y2', '1Y3'] },
      { type: 'DEMUX_2TO4', inputs: ['A', 'B', '2G', '2Cn'], outputs: ['2Y0', '2Y1', '2Y2', '2Y3'] },
    ],
  },

  // ── 74x158: quad 2-to-1 data selector/mux, inverting output, 16-pin ──────
  /* Primary source: Texas Instruments, SN74LS158 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls158.pdf
     Wikipedia: https://en.wikipedia.org/wiki/Multiplexer */
  '74158': {
    name: '74x158',
    simpleName: 'Quad 2-to-1 MUX (inverting)',
    description: 'Quad 2-line to 1-line data selector/multiplexer with inverting outputs (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls158.pdf',
    tags: ['multiplexer', 'mux', '2-to-1', 'quad', 'inverting'],
    guideOverview: 'The 74158 contains four 2-to-1 multiplexers with a common select input SEL and a common active LOW output enable G. When G is LOW, each output Yn is the complement of the data input selected by SEL: SEL=0 selects the A input and SEL=1 selects the B input. When G is HIGH all outputs are forced HIGH.',
    guidePinDescriptions: {
      SEL: 'Common select input; LOW selects all A inputs, HIGH selects all B inputs.',
      '1A': 'Data input A of MUX 1; routed to 1Y (inverted) when SEL=0 and G=0.',
      '1B': 'Data input B of MUX 1; routed to 1Y (inverted) when SEL=1 and G=0.',
      '1Y': 'Output of MUX 1 (inverted); = NOT(SEL ? 1B : 1A) when G=0.',
      '2A': 'Data input A of MUX 2; routed to 2Y (inverted) when SEL=0 and G=0.',
      '2B': 'Data input B of MUX 2; routed to 2Y (inverted) when SEL=1 and G=0.',
      '2Y': 'Output of MUX 2 (inverted); = NOT(SEL ? 2B : 2A) when G=0.',
      GND: 'Ground (0 V) supply.',
      '3Y': 'Output of MUX 3 (inverted); = NOT(SEL ? 3B : 3A) when G=0.',
      '3B': 'Data input B of MUX 3.',
      '3A': 'Data input A of MUX 3.',
      '4Y': 'Output of MUX 4 (inverted); = NOT(SEL ? 4B : 4A) when G=0.',
      '4B': 'Data input B of MUX 4.',
      '4A': 'Data input A of MUX 4.',
      G:   'Active LOW output enable; when HIGH all outputs are forced HIGH regardless of data inputs.',
      VCC: 'Positive supply (+5 V).',
    },
    guideSections: [
      {
        title: 'Selection and Inversion',
        paragraphs: [
          'All four multiplexers are controlled by a single SEL line. When G=0 and SEL=0 each output Yn = NOT(An). When G=0 and SEL=1 each output Yn = NOT(Bn). This inverted output is useful in complemented-bus applications or when a subsequent inverter is implied by the system design.',
        ],
        list: [
          'G=0, SEL=0 → Yn = NOT An (all four channels)',
          'G=0, SEL=1 → Yn = NOT Bn (all four channels)',
          'G=1 → all outputs HIGH regardless of inputs',
        ],
      },
      {
        title: 'Bus Steering',
        paragraphs: [
          'The 74158 is commonly used to steer one of two 4 bit data buses onto a single output bus while providing output-enable control. Pair it with inverters or use it with downstream logic designed to accept inverted inputs.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'SEL', type: 'input' },
      { pin:  2, name: '1A',  type: 'input' },
      { pin:  3, name: '1B',  type: 'input' },
      { pin:  4, name: '1Y',  type: 'output' },
      { pin:  5, name: '2A',  type: 'input' },
      { pin:  6, name: '2B',  type: 'input' },
      { pin:  7, name: '2Y',  type: 'output' },
      { pin:  8, name: 'GND', type: 'power' },
      { pin:  9, name: '3Y',  type: 'output' },
      { pin: 10, name: '3B',  type: 'input' },
      { pin: 11, name: '3A',  type: 'input' },
      { pin: 12, name: '4Y',  type: 'output' },
      { pin: 13, name: '4B',  type: 'input' },
      { pin: 14, name: '4A',  type: 'input' },
      { pin: 15, name: 'G',   type: 'input' },
      { pin: 16, name: 'VCC', type: 'power' },
    ],
    // Each gate: inputs [A, B, SEL, G], output Y = NOT(SEL ? B : A) when G=0
    gates: [
      { type: 'MUX_2TO1_INV', inputs: ['1A', '1B', 'SEL', 'G'], output: '1Y' },
      { type: 'MUX_2TO1_INV', inputs: ['2A', '2B', 'SEL', 'G'], output: '2Y' },
      { type: 'MUX_2TO1_INV', inputs: ['3A', '3B', 'SEL', 'G'], output: '3Y' },
      { type: 'MUX_2TO1_INV', inputs: ['4A', '4B', 'SEL', 'G'], output: '4Y' },
    ],
  },

  // ── 74x159: 4-to-16 line decoder/demux, OC, 24-pin ───────────────────────
  /* Primary source: Texas Instruments, SN74159 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74159.pdf
     Wikipedia: https://en.wikipedia.org/wiki/Multiplexer
     Wikipedia: https://en.wikipedia.org/wiki/Open_collector */
  '74159': {
    name: '74x159',
    simpleName: '4-to-16 Decoder (OC)',
    description: '4-to-16 line decoder/demultiplexer with open-collector outputs (24-pin)',
    pins: 24,
    vcc: 24,
    gnd: 12,
    openCollector: true,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74159.pdf',
    tags: ['decoder', 'demultiplexer', '4-to-16', 'open-collector', 'inverting'],
    guideOverview: 'The 74159 is a 4-to-16 line decoder/demultiplexer with open-collector outputs. Address inputs A0 A3 select one of sixteen active LOW outputs Y0 Y15. The chip is enabled when both active LOW enables G1n and G2n are LOW; if either enable is HIGH all outputs float HIGH (off). Open-collector outputs allow wired AND connections and higher-voltage load driving.',
    guidePinDescriptions: {
      A0:  'Address input bit 0 (LSB); least-significant address bit.',
      A1:  'Address input bit 1.',
      A2:  'Address input bit 2.',
      A3:  'Address input bit 3 (MSB); most-significant address bit.',
      G1n: 'Active LOW enable 1; must be LOW to enable any output.',
      G2n: 'Active LOW enable 2; must be LOW to enable any output.',
      Y0:  'Open-collector output 0 (active LOW); sinks current when A3..A0=0000 and enabled.',
      Y1:  'Open-collector output 1 (active LOW); sinks current when A3..A0=0001 and enabled.',
      Y2:  'Open-collector output 2 (active LOW); sinks current when A3..A0=0010 and enabled.',
      Y3:  'Open-collector output 3 (active LOW); sinks current when A3..A0=0011 and enabled.',
      Y4:  'Open-collector output 4 (active LOW); sinks current when A3..A0=0100 and enabled.',
      GND: 'Ground (0 V) supply.',
      Y5:  'Open-collector output 5 (active LOW); sinks current when A3..A0=0101 and enabled.',
      Y6:  'Open-collector output 6 (active LOW); sinks current when A3..A0=0110 and enabled.',
      Y7:  'Open-collector output 7 (active LOW); sinks current when A3..A0=0111 and enabled.',
      Y8:  'Open-collector output 8 (active LOW); sinks current when A3..A0=1000 and enabled.',
      Y9:  'Open-collector output 9 (active LOW); sinks current when A3..A0=1001 and enabled.',
      Y10: 'Open-collector output 10 (active LOW); sinks current when A3..A0=1010 and enabled.',
      Y11: 'Open-collector output 11 (active LOW); sinks current when A3..A0=1011 and enabled.',
      Y12: 'Open-collector output 12 (active LOW); sinks current when A3..A0=1100 and enabled.',
      Y13: 'Open-collector output 13 (active LOW); sinks current when A3..A0=1101 and enabled.',
      Y14: 'Open-collector output 14 (active LOW); sinks current when A3..A0=1110 and enabled.',
      Y15: 'Open-collector output 15 (active LOW); sinks current when A3..A0=1111 and enabled.',
      VCC: 'Positive supply (+5 V).',
    },
    guideSections: [
      {
        title: 'Decoding and Enable',
        paragraphs: [
          'Both G1n and G2n must be LOW to enable the decoder. The 4 bit address A3..A0 (A3=MSB, A0=LSB) selects one output Yi which sinks current (LOW). All other outputs are off (floating HIGH via pull up). When either enable is HIGH all outputs are off.',
        ],
        note: 'External pull up resistors are required on all 16 outputs to provide a defined HIGH voltage when outputs are off.',
      },
      {
        title: 'Open Collector Wired AND',
        paragraphs: [
          'Because outputs are open-collector, multiple 74159 outputs can be connected together to the same pull up resistor to form a wired AND bus. This is commonly used in memory chip-select and priority interrupt schemes.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'A0',  type: 'input' },
      { pin:  2, name: 'A1',  type: 'input' },
      { pin:  3, name: 'A2',  type: 'input' },
      { pin:  4, name: 'A3',  type: 'input' },
      { pin:  5, name: 'G1n', type: 'input' },
      { pin:  6, name: 'G2n', type: 'input' },
      { pin:  7, name: 'Y0',  type: 'output' },
      { pin:  8, name: 'Y1',  type: 'output' },
      { pin:  9, name: 'Y2',  type: 'output' },
      { pin: 10, name: 'Y3',  type: 'output' },
      { pin: 11, name: 'Y4',  type: 'output' },
      { pin: 12, name: 'GND', type: 'power' },
      { pin: 13, name: 'Y5',  type: 'output' },
      { pin: 14, name: 'Y6',  type: 'output' },
      { pin: 15, name: 'Y7',  type: 'output' },
      { pin: 16, name: 'Y8',  type: 'output' },
      { pin: 17, name: 'Y9',  type: 'output' },
      { pin: 18, name: 'Y10', type: 'output' },
      { pin: 19, name: 'Y11', type: 'output' },
      { pin: 20, name: 'Y12', type: 'output' },
      { pin: 21, name: 'Y13', type: 'output' },
      { pin: 22, name: 'Y14', type: 'output' },
      { pin: 23, name: 'Y15', type: 'output' },
      { pin: 24, name: 'VCC', type: 'power' },
    ],
    // Uses DECODER_4TO16: enabled when G1=0 AND G2=0 (both active LOW)
    gates: [
      { type: 'DECODER_4TO16', inputs: ['A0', 'A1', 'A2', 'A3', 'G1n', 'G2n'], outputs: ['Y0', 'Y1', 'Y2', 'Y3', 'Y4', 'Y5', 'Y6', 'Y7', 'Y8', 'Y9', 'Y10', 'Y11', 'Y12', 'Y13', 'Y14', 'Y15'] },
    ],
  },

  // ── 74x162: sync 4 bit decade counter, synchronous clear, 16-pin ──────────
  /* Primary source: Texas Instruments, SN74LS162A datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls162a.pdf
     Wikipedia: https://en.wikipedia.org/wiki/Counter_(digital) */
  '74162': {
    name: '74x162',
    simpleName: 'Sync BCD Counter (sync CLR)',
    description: 'Synchronous presettable 4 bit decade counter with synchronous clear (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls162a.pdf',
    tags: ['counter', 'bcd', 'decade', 'synchronous', 'preset', 'sequential'],
    guideOverview: 'The 74162 is a synchronous presettable 4 bit decade (BCD) counter that differs from the 74160 by having a synchronous clear: the CLR input takes effect on the next rising CLK edge rather than asynchronously. It counts 0 9 and rolls over, with RCO going HIGH when the count reaches 9 and ENT is HIGH, enabling ripple-carry cascading.',
    guidePinDescriptions: {
      CLR:  'Synchronous clear (active LOW); resets the counter to 0000 on the next rising CLK edge when LOW.',
      CLK:  'Clock input; all synchronous operations occur on the rising edge.',
      A:    'Parallel load data input A (LSB); loaded into QA when LOAD is asserted LOW.',
      B:    'Parallel load data input B; loaded into QB when LOAD is asserted LOW.',
      C:    'Parallel load data input C; loaded into QC when LOAD is asserted LOW.',
      D:    'Parallel load data input D (MSB); loaded into QD when LOAD is asserted LOW.',
      ENP:  'Count Enable P; both ENP and ENT must be HIGH for the counter to advance.',
      GND:  'Ground (0 V) supply.',
      RCO:  'Ripple Carry Output; HIGH when count=9 (BCD 1001) and ENT=1, used to clock the next cascaded counter.',
      QD:   'Counter output bit 3 (MSB, weight 8).',
      QC:   'Counter output bit 2 (weight 4).',
      QB:   'Counter output bit 1 (weight 2).',
      QA:   'Counter output bit 0 (LSB, weight 1).',
      ENT:  'Count Enable T; also controls the RCO output RCO is only HIGH when ENT=1.',
      LOAD: 'Synchronous parallel load (active LOW); loads A D into QA QD on the next rising CLK edge.',
      VCC:  'Positive supply (+5 V).',
    },
    guideSections: [
      {
        title: 'Synchronous Clear vs. Asynchronous Clear',
        paragraphs: [
          'The key distinction of the 74162 versus the 74160 is that CLR is synchronous: asserting CLR LOW does not immediately reset the counter the reset takes effect only on the next rising CLK edge. This keeps the entire counter change synchronous with the system clock and avoids glitches.',
        ],
        note: 'The 74163 is the binary (0 15) version; the 74162 counts only 0 9 (BCD). The 74160 is the asynchronous-clear BCD variant.',
      },
      {
        title: 'Count Enable and Cascading',
        paragraphs: [
          'Both ENP and ENT must be HIGH for the counter to advance. ENT additionally gates the RCO output: RCO is HIGH only when the count is 9 AND ENT=1. Connect RCO of the units digit counter to ENP and ENT of the tens digit counter to cascade BCD decades.',
        ],
        list: [
          'ENP=1, ENT=1 → counter advances',
          'ENP=0 or ENT=0 → counter holds',
          'LOAD=0 → parallel load on next CLK',
          'CLR=0 → reset to 0000 on next CLK',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'CLR',  type: 'input' },
      { pin:  2, name: 'CLK',  type: 'input' },
      { pin:  3, name: 'A',    type: 'input' },
      { pin:  4, name: 'B',    type: 'input' },
      { pin:  5, name: 'C',    type: 'input' },
      { pin:  6, name: 'D',    type: 'input' },
      { pin:  7, name: 'ENP',  type: 'input' },
      { pin:  8, name: 'GND',  type: 'power' },
      { pin:  9, name: 'RCO',  type: 'output' },
      { pin: 10, name: 'QD',   type: 'output' },
      { pin: 11, name: 'QC',   type: 'output' },
      { pin: 12, name: 'QB',   type: 'output' },
      { pin: 13, name: 'QA',   type: 'output' },
      { pin: 14, name: 'ENT',  type: 'input' },
      { pin: 15, name: 'LOAD', type: 'input' },
      { pin: 16, name: 'VCC',  type: 'power' },
    ],
    gates: [
      { type: 'COUNTER_SYNC_DECADE_SC', inputs: ['CLK', 'CLR', 'LOAD', 'ENP', 'ENT', 'A', 'B', 'C', 'D'], outputs: ['QA', 'QB', 'QC', 'QD', 'RCO'] },
    ],
    sequential: true,
  },
};
