// Chip definitions block 36
// Chips: 74678 74693

export const CHIPS_BLOCK_36 = {

  // ── 74678: 16 bit address comparator with latch (24-pin) ──────────────────
  /* Primary source: Texas Instruments, 74678 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74als678.pdf
     https://en.wikipedia.org/wiki/Digital_comparator */
  '74678': {
    name: '74x678',
    simpleName: '16 bit Addr Comparator/Latch',
    description: '16 bit address comparator with latch (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74als678.pdf',
    tags: ['comparator', 'address', '16 bit', 'latch', 'stub'],
    sequential: true,
    guideOverview: 'The 74x678 is a 16 bit address comparator with an internal reference latch. LE loads the 16 bit address (A0-A15) into the internal latch; OE (active LOW) enables the comparison outputs. Once latched, the chip continuously compares any 16 bit input against the stored reference without needing external storage. Used for memory address decoding.',
    guidePinDescriptions: {
      'A0':    'Address input bit 0.',
      'A1':    'Address input bit 1.',
      'A2':    'Address input bit 2.',
      'A3':    'Address input bit 3.',
      'A4':    'Address input bit 4.',
      'A5':    'Address input bit 5.',
      'A6':    'Address input bit 6.',
      'A7':    'Address input bit 7.',
      'A8':    'Address input bit 8.',
      'A9':    'Address input bit 9.',
      'A10':   'Address input bit 10.',
      'GND':   'Ground reference (pin 12).',
      'A11':   'Address input bit 11.',
      'A12':   'Address input bit 12.',
      'A13':   'Address input bit 13.',
      'A14':   'Address input bit 14.',
      'A15':   'Address input bit 15.',
      'LE':    'Latch Enable. Stores the current A0-A15 value as the reference.',
      'OEn':   'Output Enable for GEn and EQout (active LOW).',
      'NC1':   'No connect.',
      'GEn':   'Greater-or-Equal output (active LOW).',
      'EQout': 'Equal output.',
      'NC2':   'No connect.',
      'VCC':   'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: 'Address Comparator with Latch',
        paragraphs: [
          'The internal latch stores a programmable base address. Once loaded via LE, the chip asserts EQout whenever the 16 bit address bus exactly matches the stored value. This saves external latch chips in address decoding circuits.',
        ],
        note: 'Full comparison logic is stubbed in the simulator.',
      },
    ],
    pinout: [
      { pin:  1, name: 'A0',   type: 'input'  },
      { pin:  2, name: 'A1',   type: 'input'  },
      { pin:  3, name: 'A2',   type: 'input'  },
      { pin:  4, name: 'A3',   type: 'input'  },
      { pin:  5, name: 'A4',   type: 'input'  },
      { pin:  6, name: 'A5',   type: 'input'  },
      { pin:  7, name: 'A6',   type: 'input'  },
      { pin:  8, name: 'A7',   type: 'input'  },
      { pin:  9, name: 'A8',   type: 'input'  },
      { pin: 10, name: 'A9',   type: 'input'  },
      { pin: 11, name: 'A10',  type: 'input'  },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'A11',  type: 'input'  },
      { pin: 14, name: 'A12',  type: 'input'  },
      { pin: 15, name: 'A13',  type: 'input'  },
      { pin: 16, name: 'A14',  type: 'input'  },
      { pin: 17, name: 'A15',  type: 'input'  },
      { pin: 18, name: 'LE',   type: 'input'  },
      { pin: 19, name: 'OEn',  type: 'input'  },
      { pin: 20, name: 'NC1',  type: 'nc'     },
      { pin: 21, name: 'GEn',  type: 'output' },
      { pin: 22, name: 'EQout',type: 'output' },
      { pin: 23, name: 'NC2',  type: 'nc'     },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'ADDR_COMP_16BIT_STUB', inputs: ['A0','A1','A2','A3','A4','A5','A6','A7','A8','A9','A10','A11','A12','A13','A14','A15','LE','OEn'], outputs: ['GEn','EQout'] },
    ],
  },

  // ── 74679: 12 bit address comparator with latch (20-pin) ─────────────────
  /* Primary source: Texas Instruments, 74679 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74als679.pdf
     https://en.wikipedia.org/wiki/Digital_comparator */
  '74679': {
    name: '74x679',
    simpleName: '12 bit Addr Comparator/Latch',
    description: '12 bit address comparator with latch (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74als679.pdf',
    tags: ['comparator', 'address', '12 bit', 'latch', 'stub'],
    sequential: true,
    guideOverview: 'The 74x679 is a 12 bit address comparator with an internal reference latch, in a 20-pin package. Functionally similar to the 74x678 but with 12 address bits (A0-A11). LE stores the reference address; OE (active LOW) enables outputs. Used in systems with 12 bit address spaces or as the lower half of a 16 bit comparison.',
    guidePinDescriptions: {
      'A0':    'Address input bit 0.',
      'A1':    'Address input bit 1.',
      'A2':    'Address input bit 2.',
      'A3':    'Address input bit 3.',
      'A4':    'Address input bit 4.',
      'A5':    'Address input bit 5.',
      'A6':    'Address input bit 6.',
      'A7':    'Address input bit 7.',
      'A8':    'Address input bit 8.',
      'GND':   'Ground reference (pin 10).',
      'A9':    'Address input bit 9.',
      'A10':   'Address input bit 10.',
      'A11':   'Address input bit 11.',
      'LE':    'Latch Enable. Stores A0-A11 as reference.',
      'OEn':   'Output Enable (active LOW).',
      'NC1':   'No connect.',
      'NC2':   'No connect.',
      'GEn':   'Greater-or-Equal output (active LOW).',
      'EQout': 'Equal output.',
      'VCC':   'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: '74x678 vs 74x679',
        paragraphs: [
          '74x678 compares 16 bits (24-pin); 74x679 compares 12 bits (20-pin). For a full 16 bit comparison in a 20-pin package, cascade 74x679 with a 74x677 for the remaining 4 bits.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'A0',   type: 'input'  },
      { pin:  2, name: 'A1',   type: 'input'  },
      { pin:  3, name: 'A2',   type: 'input'  },
      { pin:  4, name: 'A3',   type: 'input'  },
      { pin:  5, name: 'A4',   type: 'input'  },
      { pin:  6, name: 'A5',   type: 'input'  },
      { pin:  7, name: 'A6',   type: 'input'  },
      { pin:  8, name: 'A7',   type: 'input'  },
      { pin:  9, name: 'A8',   type: 'input'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'A9',   type: 'input'  },
      { pin: 12, name: 'A10',  type: 'input'  },
      { pin: 13, name: 'A11',  type: 'input'  },
      { pin: 14, name: 'LE',   type: 'input'  },
      { pin: 15, name: 'OEn',  type: 'input'  },
      { pin: 16, name: 'NC1',  type: 'nc'     },
      { pin: 17, name: 'NC2',  type: 'nc'     },
      { pin: 18, name: 'GEn',  type: 'output' },
      { pin: 19, name: 'EQout',type: 'output' },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'ADDR_COMP_16BIT_STUB', inputs: ['A0','A1','A2','A3','A4','A5','A6','A7','A8','A9','A10','A11','LE','OEn'], outputs: ['GEn','EQout'] },
    ],
  },

  // ── 74680: 12 bit address comparator with enable (20-pin) ────────────────
  /* Primary source: Texas Instruments, 74680 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74als680.pdf
     https://en.wikipedia.org/wiki/Digital_comparator */
  '74680': {
    name: '74x680',
    simpleName: '12 bit Addr Comparator/Enable',
    description: '12 bit address comparator with enable (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74als680.pdf',
    tags: ['comparator', 'address', '12 bit', 'enable', 'stub'],
    sequential: true,
    guideOverview: 'The 74x680 is a 12 bit address comparator with a global enable pin instead of a latch. When G (active LOW) is asserted, the comparison outputs are enabled; when G is deasserted, outputs are disabled. Use when a fixed (wired) reference address is sufficient.',
    guidePinDescriptions: {
      'A0':    'Address input bit 0.',
      'A1':    'Address input bit 1.',
      'A2':    'Address input bit 2.',
      'A3':    'Address input bit 3.',
      'A4':    'Address input bit 4.',
      'A5':    'Address input bit 5.',
      'A6':    'Address input bit 6.',
      'A7':    'Address input bit 7.',
      'A8':    'Address input bit 8.',
      'GND':   'Ground reference (pin 10).',
      'A9':    'Address input bit 9.',
      'A10':   'Address input bit 10.',
      'A11':   'Address input bit 11.',
      'G':     'Global Enable (active LOW). When LOW, enables the comparison outputs.',
      'NC1':   'No connect.',
      'NC2':   'No connect.',
      'NC3':   'No connect.',
      'GEn':   'Greater-or-Equal output (active LOW).',
      'EQout': 'Equal output.',
      'VCC':   'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: '74x679 vs 74x680',
        paragraphs: [
          '74x679 has an internal LE latch (programmable reference); 74x680 uses a fixed wire-programmed reference and a G enable. Use 74x680 for hard-wired address decoding where the base address is set at board assembly time.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'A0',   type: 'input'  },
      { pin:  2, name: 'A1',   type: 'input'  },
      { pin:  3, name: 'A2',   type: 'input'  },
      { pin:  4, name: 'A3',   type: 'input'  },
      { pin:  5, name: 'A4',   type: 'input'  },
      { pin:  6, name: 'A5',   type: 'input'  },
      { pin:  7, name: 'A6',   type: 'input'  },
      { pin:  8, name: 'A7',   type: 'input'  },
      { pin:  9, name: 'A8',   type: 'input'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'A9',   type: 'input'  },
      { pin: 12, name: 'A10',  type: 'input'  },
      { pin: 13, name: 'A11',  type: 'input'  },
      { pin: 14, name: 'G',    type: 'input'  },
      { pin: 15, name: 'NC1',  type: 'nc'     },
      { pin: 16, name: 'NC2',  type: 'nc'     },
      { pin: 17, name: 'NC3',  type: 'nc'     },
      { pin: 18, name: 'GEn',  type: 'output' },
      { pin: 19, name: 'EQout',type: 'output' },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'ADDR_COMP_16BIT_STUB', inputs: ['A0','A1','A2','A3','A4','A5','A6','A7','A8','A9','A10','A11','G'], outputs: ['GEn','EQout'] },
    ],
  },

  // ── 74681: 4 bit parallel binary accumulator TRI (20-pin) ────────────────
  /* Primary source: Texas Instruments, 74681 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls681.pdf
     https://en.wikipedia.org/wiki/Adder_(electronics) */
  '74681': {
    name: '74x681',
    simpleName: '4 bit Binary Accumulator',
    description: '4 bit parallel binary accumulator with tri-state outputs (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls681.pdf',
    tags: ['accumulator', '4 bit', 'ALU', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x681 is a 4 bit parallel binary accumulator. It performs ALU-style operations selected by S0-S3 (16 possible functions) on inputs A0-A3 and accumulates the result each clock cycle. M selects arithmetic or logic mode; CIN is carry-in; COUT is carry-out. Complex circuit stub in simulation.',
    guidePinDescriptions: {
      'S0':   'Function select bit 0.',
      'S1':   'Function select bit 1.',
      'S2':   'Function select bit 2.',
      'S3':   'Function select bit 3.',
      'A0':   'Data input bit 0.',
      'A1':   'Data input bit 1.',
      'A2':   'Data input bit 2.',
      'A3':   'Data input bit 3.',
      'OEn':  'Output Enable (active LOW).',
      'GND':  'Ground reference (pin 10).',
      'CLK':  'Clock input. Accumulates result on rising edge.',
      'F0':   'Accumulator output bit 0.',
      'F1':   'Accumulator output bit 1.',
      'F2':   'Accumulator output bit 2.',
      'F3':   'Accumulator output bit 3.',
      'COUT': 'Carry out.',
      'CIN':  'Carry in.',
      'M':    'Mode select. HIGH = logic functions; LOW = arithmetic functions.',
      'NC':   'No connect.',
      'VCC':  'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: '4 bit Accumulator',
        paragraphs: [
          'An accumulator combines an ALU with a register: the output is fed back as one of the operands on the next cycle, allowing repeated operations without external storage. The 74x681 is the clocked accumulator companion to the 74x181 ALU.',
        ],
        note: 'Stub in simulator ALU and accumulate logic not fully implemented.',
      },
    ],
    pinout: [
      { pin:  1, name: 'S0',   type: 'input'  },
      { pin:  2, name: 'S1',   type: 'input'  },
      { pin:  3, name: 'S2',   type: 'input'  },
      { pin:  4, name: 'S3',   type: 'input'  },
      { pin:  5, name: 'A0',   type: 'input'  },
      { pin:  6, name: 'A1',   type: 'input'  },
      { pin:  7, name: 'A2',   type: 'input'  },
      { pin:  8, name: 'A3',   type: 'input'  },
      { pin:  9, name: 'OEn',  type: 'input'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'CLK',  type: 'input'  },
      { pin: 12, name: 'F0',   type: 'output' },
      { pin: 13, name: 'F1',   type: 'output' },
      { pin: 14, name: 'F2',   type: 'output' },
      { pin: 15, name: 'F3',   type: 'output' },
      { pin: 16, name: 'COUT', type: 'output' },
      { pin: 17, name: 'CIN',  type: 'input'  },
      { pin: 18, name: 'M',    type: 'input'  },
      { pin: 19, name: 'NC',   type: 'nc'     },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'ACC_4BIT_STUB', inputs: ['S0','S1','S2','S3','A0','A1','A2','A3','OEn','CLK','CIN','M'], outputs: ['F0','F1','F2','F3','COUT'] },
    ],
  },

  // ── 74682: 8 bit magnitude comparator P>Q, pull up (20-pin) ──────────────
  /* Primary source: Texas Instruments, 74682 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls682.pdf
     https://en.wikipedia.org/wiki/Digital_comparator */
  '74682': {
    name: '74x682',
    simpleName: '8 bit Magnitude Comparator (P>Q)',
    description: '8 bit magnitude comparator with P>Q output and 20kΩ pull up inputs (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls682.pdf',
    tags: ['comparator', '8 bit', 'magnitude', 'P>Q'],
    guideOverview: 'The 74x682 is an 8 bit magnitude comparator that compares word P (P0-P7) against word Q (Q0-Q7) and asserts PGQ (active LOW) when P > Q. G is a global enable. The Q inputs have internal 20 kΩ pull up resistors, making them compatible with open-collector bus lines or DIP switches.',
    guidePinDescriptions: {
      'G':    'Global Enable (active LOW). Disables PGQ and PEQQ outputs when HIGH.',
      'P0':   'P word input bit 0.',
      'P1':   'P word input bit 1.',
      'P2':   'P word input bit 2.',
      'P3':   'P word input bit 3.',
      'P4':   'P word input bit 4.',
      'P5':   'P word input bit 5.',
      'P6':   'P word input bit 6.',
      'P7':   'P word input bit 7.',
      'GND':  'Ground reference (pin 10).',
      'Q7':   'Q word input bit 7 (has 20 kΩ pull up).',
      'Q6':   'Q word input bit 6.',
      'Q5':   'Q word input bit 5.',
      'Q4':   'Q word input bit 4.',
      'Q3':   'Q word input bit 3.',
      'Q2':   'Q word input bit 2.',
      'Q1':   'Q word input bit 1.',
      'Q0':   'Q word input bit 0 (has 20 kΩ pull up).',
      'PGQ':  'P Greater Than Q output (active LOW).',
      'VCC':  'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: '8 bit Magnitude Comparator',
        paragraphs: [
          'A magnitude comparator determines the numeric relationship between two binary words. The 74x682 outputs P>Q; use with 74x688 (P=Q) to implement full greater/less/equal comparison.',
        ],
      },
      {
        title: '74x682 vs 74x684',
        paragraphs: [
          '74x682 has 20 kΩ pull up resistors on the Q inputs for compatibility with open-collector or DIP-switch buses. 74x684 has no pull ups and is for direct TTL inputs only.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'G',    type: 'input'  },
      { pin:  2, name: 'P0',   type: 'input'  },
      { pin:  3, name: 'P1',   type: 'input'  },
      { pin:  4, name: 'P2',   type: 'input'  },
      { pin:  5, name: 'P3',   type: 'input'  },
      { pin:  6, name: 'P4',   type: 'input'  },
      { pin:  7, name: 'P5',   type: 'input'  },
      { pin:  8, name: 'P6',   type: 'input'  },
      { pin:  9, name: 'P7',   type: 'input'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'Q7',   type: 'input'  },
      { pin: 12, name: 'Q6',   type: 'input'  },
      { pin: 13, name: 'Q5',   type: 'input'  },
      { pin: 14, name: 'Q4',   type: 'input'  },
      { pin: 15, name: 'Q3',   type: 'input'  },
      { pin: 16, name: 'Q2',   type: 'input'  },
      { pin: 17, name: 'Q1',   type: 'input'  },
      { pin: 18, name: 'Q0',   type: 'input'  },
      { pin: 19, name: 'PGQ',  type: 'output' },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'COMPARATOR_8BIT_PQ', inputs: ['P0','P1','P2','P3','P4','P5','P6','P7','Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7','G'], outputs: ['PGQ'] },
    ],
  },

  // ── 74683: 8 bit magnitude comparator P>Q, OC (20-pin) ───────────────────
  /* Primary source: Texas Instruments, 74683 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls683.pdf
     https://en.wikipedia.org/wiki/Digital_comparator */
  '74683': {
    name: '74x683',
    simpleName: '8 bit Magnitude Comparator (P>Q, OC)',
    description: '8 bit magnitude comparator with P>Q open-collector output and 20kΩ pull up inputs (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    openCollector: true,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls683.pdf',
    tags: ['comparator', '8 bit', 'magnitude', 'P>Q', 'open-collector'],
    guideOverview: 'The 74x683 is the open-collector version of the 74x682. Same P>Q comparison with 20 kΩ Q-input pull ups and G enable, but PGQ output is open-collector, allowing wire-AND of multiple comparison chips. External pull up required on PGQ.',
    guidePinDescriptions: {
      'G':    'Global Enable (active LOW).',
      'P0':   'P word input bit 0.',
      'P1':   'P word input bit 1.',
      'P2':   'P word input bit 2.',
      'P3':   'P word input bit 3.',
      'P4':   'P word input bit 4.',
      'P5':   'P word input bit 5.',
      'P6':   'P word input bit 6.',
      'P7':   'P word input bit 7.',
      'GND':  'Ground reference (pin 10).',
      'Q7':   'Q word input bit 7 (pull up).',
      'Q6':   'Q word input bit 6.',
      'Q5':   'Q word input bit 5.',
      'Q4':   'Q word input bit 4.',
      'Q3':   'Q word input bit 3.',
      'Q2':   'Q word input bit 2.',
      'Q1':   'Q word input bit 1.',
      'Q0':   'Q word input bit 0 (pull up).',
      'PGQ':  'P Greater Than Q output (active LOW, open-collector).',
      'VCC':  'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'Wire-AND Comparison',
        paragraphs: [
          'OC output enables wire-AND: connect PGQ from multiple comparators together with a pull up; the combined output is LOW only when all comparators assert P>Q simultaneously. Useful for multi-stage address range checks.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'G',    type: 'input'  },
      { pin:  2, name: 'P0',   type: 'input'  },
      { pin:  3, name: 'P1',   type: 'input'  },
      { pin:  4, name: 'P2',   type: 'input'  },
      { pin:  5, name: 'P3',   type: 'input'  },
      { pin:  6, name: 'P4',   type: 'input'  },
      { pin:  7, name: 'P5',   type: 'input'  },
      { pin:  8, name: 'P6',   type: 'input'  },
      { pin:  9, name: 'P7',   type: 'input'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'Q7',   type: 'input'  },
      { pin: 12, name: 'Q6',   type: 'input'  },
      { pin: 13, name: 'Q5',   type: 'input'  },
      { pin: 14, name: 'Q4',   type: 'input'  },
      { pin: 15, name: 'Q3',   type: 'input'  },
      { pin: 16, name: 'Q2',   type: 'input'  },
      { pin: 17, name: 'Q1',   type: 'input'  },
      { pin: 18, name: 'Q0',   type: 'input'  },
      { pin: 19, name: 'PGQ',  type: 'output' },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'COMPARATOR_8BIT_PQ', inputs: ['P0','P1','P2','P3','P4','P5','P6','P7','Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7','G'], outputs: ['PGQ'] },
    ],
  },

  // ── 74684: 8 bit magnitude comparator P>Q (20-pin) ───────────────────────
  /* Primary source: Texas Instruments, 74684 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls684.pdf
     https://en.wikipedia.org/wiki/Digital_comparator */
  '74684': {
    name: '74x684',
    simpleName: '8 bit Magnitude Comparator (P>Q)',
    description: '8 bit magnitude comparator with P>Q output (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls684.pdf',
    tags: ['comparator', '8 bit', 'magnitude', 'P>Q'],
    guideOverview: 'The 74x684 is an 8 bit P>Q magnitude comparator without pull up resistors on the Q inputs (unlike 74x682). Direct TTL/CMOS drive required on Q0-Q7. Same G enable and PGQ output. The more common choice when Q inputs are driven directly from logic outputs.',
    guidePinDescriptions: {
      'G':    'Global Enable (active LOW).',
      'P0':   'P word input bit 0.',
      'P1':   'P word input bit 1.',
      'P2':   'P word input bit 2.',
      'P3':   'P word input bit 3.',
      'P4':   'P word input bit 4.',
      'P5':   'P word input bit 5.',
      'P6':   'P word input bit 6.',
      'P7':   'P word input bit 7.',
      'GND':  'Ground reference (pin 10).',
      'Q7':   'Q word input bit 7.',
      'Q6':   'Q word input bit 6.',
      'Q5':   'Q word input bit 5.',
      'Q4':   'Q word input bit 4.',
      'Q3':   'Q word input bit 3.',
      'Q2':   'Q word input bit 2.',
      'Q1':   'Q word input bit 1.',
      'Q0':   'Q word input bit 0.',
      'PGQ':  'P Greater Than Q output (active LOW).',
      'VCC':  'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'Direct-Drive Magnitude Comparator',
        paragraphs: [
          'Use 74x684 when both P and Q words are driven by totem-pole logic outputs. The lack of pull ups reduces input current draw compared to 74x682.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'G',    type: 'input'  },
      { pin:  2, name: 'P0',   type: 'input'  },
      { pin:  3, name: 'P1',   type: 'input'  },
      { pin:  4, name: 'P2',   type: 'input'  },
      { pin:  5, name: 'P3',   type: 'input'  },
      { pin:  6, name: 'P4',   type: 'input'  },
      { pin:  7, name: 'P5',   type: 'input'  },
      { pin:  8, name: 'P6',   type: 'input'  },
      { pin:  9, name: 'P7',   type: 'input'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'Q7',   type: 'input'  },
      { pin: 12, name: 'Q6',   type: 'input'  },
      { pin: 13, name: 'Q5',   type: 'input'  },
      { pin: 14, name: 'Q4',   type: 'input'  },
      { pin: 15, name: 'Q3',   type: 'input'  },
      { pin: 16, name: 'Q2',   type: 'input'  },
      { pin: 17, name: 'Q1',   type: 'input'  },
      { pin: 18, name: 'Q0',   type: 'input'  },
      { pin: 19, name: 'PGQ',  type: 'output' },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'COMPARATOR_8BIT_PQ', inputs: ['P0','P1','P2','P3','P4','P5','P6','P7','Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7','G'], outputs: ['PGQ'] },
    ],
  },

  // ── 74685: 8 bit magnitude comparator P>Q, OC (20-pin) ───────────────────
  /* Primary source: Texas Instruments, 74685 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls685.pdf
     https://en.wikipedia.org/wiki/Digital_comparator */
  '74685': {
    name: '74x685',
    simpleName: '8 bit Magnitude Comparator (P>Q, OC)',
    description: '8 bit magnitude comparator with P>Q open-collector output (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    openCollector: true,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls685.pdf',
    tags: ['comparator', '8 bit', 'magnitude', 'P>Q', 'open-collector'],
    guideOverview: 'The 74x685 is the open-collector version of the 74x684. P>Q comparison without Q-input pull ups and with OC PGQ output. External pull up required on PGQ. The no-pull up OC variant for direct-drive systems.',
    guidePinDescriptions: {
      'G':    'Global Enable (active LOW).',
      'P0':   'P word input bit 0.',
      'P1':   'P word input bit 1.',
      'P2':   'P word input bit 2.',
      'P3':   'P word input bit 3.',
      'P4':   'P word input bit 4.',
      'P5':   'P word input bit 5.',
      'P6':   'P word input bit 6.',
      'P7':   'P word input bit 7.',
      'GND':  'Ground reference (pin 10).',
      'Q7':   'Q word input bit 7.',
      'Q6':   'Q word input bit 6.',
      'Q5':   'Q word input bit 5.',
      'Q4':   'Q word input bit 4.',
      'Q3':   'Q word input bit 3.',
      'Q2':   'Q word input bit 2.',
      'Q1':   'Q word input bit 1.',
      'Q0':   'Q word input bit 0.',
      'PGQ':  'P Greater Than Q output (active LOW, open-collector).',
      'VCC':  'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: '74x682 74x685 Family Summary',
        list: [
          '74x682: TRI, 20kΩ Q pull ups',
          '74x683: OC, 20kΩ Q pull ups',
          '74x684: TRI, no pull ups',
          '74x685: OC, no pull ups',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'G',    type: 'input'  },
      { pin:  2, name: 'P0',   type: 'input'  },
      { pin:  3, name: 'P1',   type: 'input'  },
      { pin:  4, name: 'P2',   type: 'input'  },
      { pin:  5, name: 'P3',   type: 'input'  },
      { pin:  6, name: 'P4',   type: 'input'  },
      { pin:  7, name: 'P5',   type: 'input'  },
      { pin:  8, name: 'P6',   type: 'input'  },
      { pin:  9, name: 'P7',   type: 'input'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'Q7',   type: 'input'  },
      { pin: 12, name: 'Q6',   type: 'input'  },
      { pin: 13, name: 'Q5',   type: 'input'  },
      { pin: 14, name: 'Q4',   type: 'input'  },
      { pin: 15, name: 'Q3',   type: 'input'  },
      { pin: 16, name: 'Q2',   type: 'input'  },
      { pin: 17, name: 'Q1',   type: 'input'  },
      { pin: 18, name: 'Q0',   type: 'input'  },
      { pin: 19, name: 'PGQ',  type: 'output' },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'COMPARATOR_8BIT_PQ', inputs: ['P0','P1','P2','P3','P4','P5','P6','P7','Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7','G'], outputs: ['PGQ'] },
    ],
  },

  // ── 74686: 8 bit magnitude comparator P>Q with enable, TRI (24-pin) ──────
  /* Primary source: Texas Instruments, 74686 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls686.pdf
     https://en.wikipedia.org/wiki/Digital_comparator */
  '74686': {
    name: '74x686',
    simpleName: '8 bit Magnitude Comparator (P>Q, Enable)',
    description: '8 bit magnitude comparator with P>Q output and enable (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls686.pdf',
    tags: ['comparator', '8 bit', 'magnitude', 'P>Q', 'enable', 'tri-state'],
    guideOverview: 'The 74x686 is a 24-pin 8 bit comparator providing both P>Q (PGQ) and P=Q (PEQQ) outputs with dual enable pins G1 and G2. Useful when both magnitude and equality decisions are needed simultaneously for example, address decoding with range checking.',
    guidePinDescriptions: {
      'G1':   'Enable input 1 (active LOW).',
      'G2':   'Enable input 2 (active LOW).',
      'P0':   'P word input bit 0.',
      'P1':   'P word input bit 1.',
      'P2':   'P word input bit 2.',
      'P3':   'P word input bit 3.',
      'P4':   'P word input bit 4.',
      'P5':   'P word input bit 5.',
      'P6':   'P word input bit 6.',
      'P7':   'P word input bit 7.',
      'NC1':  'No connect.',
      'GND':  'Ground reference (pin 12).',
      'Q7':   'Q word input bit 7.',
      'Q6':   'Q word input bit 6.',
      'Q5':   'Q word input bit 5.',
      'Q4':   'Q word input bit 4.',
      'Q3':   'Q word input bit 3.',
      'Q2':   'Q word input bit 2.',
      'Q1':   'Q word input bit 1.',
      'Q0':   'Q word input bit 0.',
      'NC2':  'No connect.',
      'PGQ':  'P Greater Than Q output (active LOW).',
      'PEQQ': 'P Equal Q output (active LOW).',
      'VCC':  'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: 'Dual Output Comparator',
        paragraphs: [
          'By providing both PGQ and PEQQ, the 74x686 covers greater-than, equal, and (by deduction) less-than without external logic. Dual enables allow use in shared-bus and cascaded configurations.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'G1',   type: 'input'  },
      { pin:  2, name: 'G2',   type: 'input'  },
      { pin:  3, name: 'P0',   type: 'input'  },
      { pin:  4, name: 'P1',   type: 'input'  },
      { pin:  5, name: 'P2',   type: 'input'  },
      { pin:  6, name: 'P3',   type: 'input'  },
      { pin:  7, name: 'P4',   type: 'input'  },
      { pin:  8, name: 'P5',   type: 'input'  },
      { pin:  9, name: 'P6',   type: 'input'  },
      { pin: 10, name: 'P7',   type: 'input'  },
      { pin: 11, name: 'NC1',  type: 'nc'     },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'Q7',   type: 'input'  },
      { pin: 14, name: 'Q6',   type: 'input'  },
      { pin: 15, name: 'Q5',   type: 'input'  },
      { pin: 16, name: 'Q4',   type: 'input'  },
      { pin: 17, name: 'Q3',   type: 'input'  },
      { pin: 18, name: 'Q2',   type: 'input'  },
      { pin: 19, name: 'Q1',   type: 'input'  },
      { pin: 20, name: 'Q0',   type: 'input'  },
      { pin: 21, name: 'NC2',  type: 'nc'     },
      { pin: 22, name: 'PGQ',  type: 'output' },
      { pin: 23, name: 'PEQQ', type: 'output' },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'COMPARATOR_8BIT_PQ_EN', inputs: ['P0','P1','P2','P3','P4','P5','P6','P7','Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7','G1','G2'], outputs: ['PGQ','PEQQ'] },
    ],
  },

  // ── 74687: 8 bit magnitude comparator P>Q with enable, OC (24-pin) ───────
  /* Primary source: Texas Instruments, 74687 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls687.pdf
     https://en.wikipedia.org/wiki/Digital_comparator */
  '74687': {
    name: '74x687',
    simpleName: '8 bit Magnitude Comparator (P>Q, Enable, OC)',
    description: '8 bit magnitude comparator with P>Q output, enable, and open-collector outputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    openCollector: true,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls687.pdf',
    tags: ['comparator', '8 bit', 'magnitude', 'P>Q', 'enable', 'open-collector'],
    guideOverview: 'The 74x687 is the open-collector version of the 74x686: 8 bit magnitude comparator with PGQ and PEQQ outputs and G1/G2 enables. Both outputs are OC, allowing wire-AND when multiple chips share the same output lines.',
    guidePinDescriptions: {
      'G1':   'Enable input 1 (active LOW).',
      'G2':   'Enable input 2 (active LOW).',
      'P0':   'P word input bit 0.',
      'P1':   'P word input bit 1.',
      'P2':   'P word input bit 2.',
      'P3':   'P word input bit 3.',
      'P4':   'P word input bit 4.',
      'P5':   'P word input bit 5.',
      'P6':   'P word input bit 6.',
      'P7':   'P word input bit 7.',
      'NC1':  'No connect.',
      'GND':  'Ground reference (pin 12).',
      'Q7':   'Q word input bit 7.',
      'Q6':   'Q word input bit 6.',
      'Q5':   'Q word input bit 5.',
      'Q4':   'Q word input bit 4.',
      'Q3':   'Q word input bit 3.',
      'Q2':   'Q word input bit 2.',
      'Q1':   'Q word input bit 1.',
      'Q0':   'Q word input bit 0.',
      'NC2':  'No connect.',
      'PGQ':  'P Greater Than Q output (active LOW, open-collector).',
      'PEQQ': 'P Equal Q output (active LOW, open-collector).',
      'VCC':  'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: 'OC Dual Output',
        paragraphs: [
          'Wire-AND both PGQ and PEQQ across multiple chips for multi-chip comparison: all connected comparators must agree before the shared output asserts.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'G1',   type: 'input'  },
      { pin:  2, name: 'G2',   type: 'input'  },
      { pin:  3, name: 'P0',   type: 'input'  },
      { pin:  4, name: 'P1',   type: 'input'  },
      { pin:  5, name: 'P2',   type: 'input'  },
      { pin:  6, name: 'P3',   type: 'input'  },
      { pin:  7, name: 'P4',   type: 'input'  },
      { pin:  8, name: 'P5',   type: 'input'  },
      { pin:  9, name: 'P6',   type: 'input'  },
      { pin: 10, name: 'P7',   type: 'input'  },
      { pin: 11, name: 'NC1',  type: 'nc'     },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'Q7',   type: 'input'  },
      { pin: 14, name: 'Q6',   type: 'input'  },
      { pin: 15, name: 'Q5',   type: 'input'  },
      { pin: 16, name: 'Q4',   type: 'input'  },
      { pin: 17, name: 'Q3',   type: 'input'  },
      { pin: 18, name: 'Q2',   type: 'input'  },
      { pin: 19, name: 'Q1',   type: 'input'  },
      { pin: 20, name: 'Q0',   type: 'input'  },
      { pin: 21, name: 'NC2',  type: 'nc'     },
      { pin: 22, name: 'PGQ',  type: 'output' },
      { pin: 23, name: 'PEQQ', type: 'output' },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'COMPARATOR_8BIT_PQ_EN', inputs: ['P0','P1','P2','P3','P4','P5','P6','P7','Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7','G1','G2'], outputs: ['PGQ','PEQQ'] },
    ],
  },

  // ── 74688: 8 bit magnitude comparator P==Q with enable (20-pin) ──────────
  /* Primary source: Texas Instruments, 74688 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls688.pdf
     https://en.wikipedia.org/wiki/Digital_comparator */
  '74688': {
    name: '74x688',
    simpleName: '8 bit Identity Comparator',
    description: '8 bit magnitude comparator with equality (P==Q) output and enable (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls688.pdf',
    tags: ['comparator', '8 bit', 'equality', 'identity'],
    guideOverview: 'The 74x688 is an 8 bit identity comparator that asserts PEQQ (active LOW) when P0-P7 exactly equals Q0-Q7. G is a global enable. It is the most widely used chip in this family for address decoding: tie Q to a fixed address pattern and PEQQ asserts the chip-select when the address bus matches.',
    guidePinDescriptions: {
      'G':    'Global Enable (active LOW). Must be LOW for PEQQ to respond.',
      'P0':   'P word input bit 0.',
      'P1':   'P word input bit 1.',
      'P2':   'P word input bit 2.',
      'P3':   'P word input bit 3.',
      'P4':   'P word input bit 4.',
      'P5':   'P word input bit 5.',
      'P6':   'P word input bit 6.',
      'P7':   'P word input bit 7.',
      'GND':  'Ground reference (pin 10).',
      'Q7':   'Q reference input bit 7.',
      'Q6':   'Q reference input bit 6.',
      'Q5':   'Q reference input bit 5.',
      'Q4':   'Q reference input bit 4.',
      'Q3':   'Q reference input bit 3.',
      'Q2':   'Q reference input bit 2.',
      'Q1':   'Q reference input bit 1.',
      'Q0':   'Q reference input bit 0.',
      'PEQQ': 'P Equal Q output (active LOW).',
      'VCC':  'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'Address Decoding with 74x688',
        paragraphs: [
          'Connect the CPU address bus to P0-P7. Set Q0-Q7 to the desired chip-select address using DIP switches or pull up/pull down resistors. Drive G from higher address bits decoded elsewhere. When all 8 bits match and G is LOW, PEQQ goes LOW to assert CS.',
        ],
      },
      {
        title: 'Common Uses',
        list: [
          'Chip-select generation in microprocessor systems',
          'DIP switch address comparison',
          'Equality testing of two data busses',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'G',    type: 'input'  },
      { pin:  2, name: 'P0',   type: 'input'  },
      { pin:  3, name: 'P1',   type: 'input'  },
      { pin:  4, name: 'P2',   type: 'input'  },
      { pin:  5, name: 'P3',   type: 'input'  },
      { pin:  6, name: 'P4',   type: 'input'  },
      { pin:  7, name: 'P5',   type: 'input'  },
      { pin:  8, name: 'P6',   type: 'input'  },
      { pin:  9, name: 'P7',   type: 'input'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'Q7',   type: 'input'  },
      { pin: 12, name: 'Q6',   type: 'input'  },
      { pin: 13, name: 'Q5',   type: 'input'  },
      { pin: 14, name: 'Q4',   type: 'input'  },
      { pin: 15, name: 'Q3',   type: 'input'  },
      { pin: 16, name: 'Q2',   type: 'input'  },
      { pin: 17, name: 'Q1',   type: 'input'  },
      { pin: 18, name: 'Q0',   type: 'input'  },
      { pin: 19, name: 'PEQQ',type: 'output' },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'COMPARATOR_8BIT_EQ', inputs: ['P0','P1','P2','P3','P4','P5','P6','P7','Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7','G'], outputs: ['PEQQ'] },
    ],
  },

  // ── 74689: 8 bit magnitude comparator P==Q with enable, OC (20-pin) ──────
  /* Primary source: Texas Instruments, 74689 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls689.pdf
     https://en.wikipedia.org/wiki/Digital_comparator */
  '74689': {
    name: '74x689',
    simpleName: '8 bit Identity Comparator (OC)',
    description: '8 bit magnitude comparator with equality (P==Q) open-collector output and enable (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    openCollector: true,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls689.pdf',
    tags: ['comparator', '8 bit', 'equality', 'identity', 'open-collector'],
    guideOverview: 'The 74x689 is the open-collector version of the 74x688. Same 8 bit equality comparison with G enable and active LOW PEQQ output. The OC output allows wire-AND: connect multiple 74x689s sharing PEQQ to implement an N×8 bit comparison where all sections must agree.',
    guidePinDescriptions: {
      'G':    'Global Enable (active LOW).',
      'P0':   'P word input bit 0.',
      'P1':   'P word input bit 1.',
      'P2':   'P word input bit 2.',
      'P3':   'P word input bit 3.',
      'P4':   'P word input bit 4.',
      'P5':   'P word input bit 5.',
      'P6':   'P word input bit 6.',
      'P7':   'P word input bit 7.',
      'GND':  'Ground reference (pin 10).',
      'Q7':   'Q reference input bit 7.',
      'Q6':   'Q reference input bit 6.',
      'Q5':   'Q reference input bit 5.',
      'Q4':   'Q reference input bit 4.',
      'Q3':   'Q reference input bit 3.',
      'Q2':   'Q reference input bit 2.',
      'Q1':   'Q reference input bit 1.',
      'Q0':   'Q reference input bit 0.',
      'PEQQ': 'P Equal Q output (active LOW, open-collector).',
      'VCC':  'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: '16 bit Equality from Two 74x689s',
        paragraphs: [
          'Wire the PEQQ pins of two 74x689s together with a pull up resistor. The result is LOW only when both byte comparisons match implementing a 16 bit address compare without a cascading input pin.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'G',    type: 'input'  },
      { pin:  2, name: 'P0',   type: 'input'  },
      { pin:  3, name: 'P1',   type: 'input'  },
      { pin:  4, name: 'P2',   type: 'input'  },
      { pin:  5, name: 'P3',   type: 'input'  },
      { pin:  6, name: 'P4',   type: 'input'  },
      { pin:  7, name: 'P5',   type: 'input'  },
      { pin:  8, name: 'P6',   type: 'input'  },
      { pin:  9, name: 'P7',   type: 'input'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'Q7',   type: 'input'  },
      { pin: 12, name: 'Q6',   type: 'input'  },
      { pin: 13, name: 'Q5',   type: 'input'  },
      { pin: 14, name: 'Q4',   type: 'input'  },
      { pin: 15, name: 'Q3',   type: 'input'  },
      { pin: 16, name: 'Q2',   type: 'input'  },
      { pin: 17, name: 'Q1',   type: 'input'  },
      { pin: 18, name: 'Q0',   type: 'input'  },
      { pin: 19, name: 'PEQQ',type: 'output' },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'COMPARATOR_8BIT_EQ', inputs: ['P0','P1','P2','P3','P4','P5','P6','P7','Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7','G'], outputs: ['PEQQ'] },
    ],
  },

  // ── 74690: 4 bit decade counter/latch/mux async CLR TRI (20-pin) ─────────
  /* Primary source: Texas Instruments, 74690 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls690.pdf
     https://en.wikipedia.org/wiki/Counter_(digital) */
  '74690': {
    name: '74x690',
    simpleName: '4 bit BCD Counter/Latch/Mux (Async CLR)',
    description: '4 bit decade counter/latch/multiplexer with asynchronous clear and tri-state output (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls690.pdf',
    tags: ['counter', 'bcd', 'decade', 'latch', 'multiplexer', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x690 is a 4 bit BCD (decade) counter combined with an output latch and 2:1 multiplexer, with asynchronous CLR and tri-state outputs. The counter counts BCD (0-9). S selects whether Q outputs reflect the live counter value or the latched value. LE loads the latch. Complex multi-function chip stub in simulator.',
    guidePinDescriptions: {
      'CLK':  'Clock input (rising edge increments counter).',
      'CLR':  'Asynchronous Clear (active LOW). Immediately resets counter to 0.',
      'D0':   'Parallel load data bit 0.',
      'D1':   'Parallel load data bit 1.',
      'D2':   'Parallel load data bit 2.',
      'D3':   'Parallel load data bit 3.',
      'LE':   'Latch Enable. Loads Q0-Q3 into internal latch.',
      'S':    'Select. LOW = Q outputs show latch; HIGH = Q outputs show counter.',
      'OEn':  'Output Enable (active LOW).',
      'GND':  'Ground reference (pin 10).',
      'Q0':   'Output bit 0.',
      'Q1':   'Output bit 1.',
      'Q2':   'Output bit 2.',
      'Q3':   'Output bit 3.',
      'RCO':  'Ripple Carry Output for cascading.',
      'ENT':  'Count Enable T (active LOW). Used for cascading.',
      'ENP':  'Count Enable P (active LOW).',
      'LOAD': 'Parallel Load (active LOW). Loads D0-D3 into counter.',
      'UD':   'Up/Down count direction. HIGH = up; LOW = down.',
      'VCC':  'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'Counter/Latch/Multiplexer',
        paragraphs: [
          'This chip integrates three functions: a presettable BCD counter, an output latch, and a 2:1 MUX to choose between counter and latch outputs. The latch freezes the display while the counter continues, useful for glitch-free 7-segment displays.',
        ],
        note: 'Simulation is stubbed; full counter/latch/mux behavior not implemented.',
      },
    ],
    pinout: [
      { pin:  1, name: 'CLK', type: 'input'  },
      { pin:  2, name: 'CLR', type: 'input'  },
      { pin:  3, name: 'D0',  type: 'input'  },
      { pin:  4, name: 'D1',  type: 'input'  },
      { pin:  5, name: 'D2',  type: 'input'  },
      { pin:  6, name: 'D3',  type: 'input'  },
      { pin:  7, name: 'LE',  type: 'input'  },
      { pin:  8, name: 'S',   type: 'input'  },
      { pin:  9, name: 'OEn', type: 'input'  },
      { pin: 10, name: 'GND', type: 'power'  },
      { pin: 11, name: 'Q0',  type: 'output' },
      { pin: 12, name: 'Q1',  type: 'output' },
      { pin: 13, name: 'Q2',  type: 'output' },
      { pin: 14, name: 'Q3',  type: 'output' },
      { pin: 15, name: 'RCO', type: 'output' },
      { pin: 16, name: 'ENT', type: 'input'  },
      { pin: 17, name: 'ENP', type: 'input'  },
      { pin: 18, name: 'LOAD',type: 'input'  },
      { pin: 19, name: 'UD',  type: 'input'  },
      { pin: 20, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'COUNTER_LATCH_MUX_STUB', inputs: ['CLK','CLR','D0','D1','D2','D3','LE','S','OEn','ENT','ENP','LOAD','UD'], outputs: ['Q0','Q1','Q2','Q3','RCO'] },
    ],
  },

  // ── 74691: 4 bit binary counter/latch/mux async CLR TRI (20-pin) ─────────
  /* Primary source: Texas Instruments, 74691 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls691.pdf
     https://en.wikipedia.org/wiki/Counter_(digital) */
  '74691': {
    name: '74x691',
    simpleName: '4 bit Binary Counter/Latch/Mux (Async CLR)',
    description: '4 bit binary counter/latch/multiplexer with asynchronous clear and tri-state output (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls691.pdf',
    tags: ['counter', 'binary', '4 bit', 'latch', 'multiplexer', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x691 is the binary version of the 74x690: a 4 bit binary counter (counts 0-15) with output latch, 2:1 MUX, asynchronous CLR, and tri-state outputs. S selects counter vs latch output; LE latches. Same pin layout as 74x690 with binary (not BCD) counting mode.',
    guidePinDescriptions: {
      'CLK':  'Clock input (rising edge).',
      'CLR':  'Asynchronous Clear (active LOW).',
      'D0':   'Parallel load input bit 0.',
      'D1':   'Parallel load input bit 1.',
      'D2':   'Parallel load input bit 2.',
      'D3':   'Parallel load input bit 3.',
      'LE':   'Latch Enable.',
      'S':    'Output Select: LOW = latch; HIGH = counter.',
      'OEn':  'Output Enable (active LOW).',
      'GND':  'Ground reference (pin 10).',
      'Q0':   'Output bit 0.',
      'Q1':   'Output bit 1.',
      'Q2':   'Output bit 2.',
      'Q3':   'Output bit 3.',
      'RCO':  'Ripple Carry Output.',
      'ENT':  'Count Enable T (active LOW).',
      'ENP':  'Count Enable P (active LOW).',
      'LOAD': 'Parallel Load (active LOW).',
      'UD':   'Up/Down select.',
      'VCC':  'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: '74x690 vs 74x691',
        paragraphs: [
          '74x690 counts BCD (0-9, rolls over at 10); 74x691 counts in 4 bit binary (0-15). Both combine counter, latch, and MUX in the same pinout.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'CLK', type: 'input'  },
      { pin:  2, name: 'CLR', type: 'input'  },
      { pin:  3, name: 'D0',  type: 'input'  },
      { pin:  4, name: 'D1',  type: 'input'  },
      { pin:  5, name: 'D2',  type: 'input'  },
      { pin:  6, name: 'D3',  type: 'input'  },
      { pin:  7, name: 'LE',  type: 'input'  },
      { pin:  8, name: 'S',   type: 'input'  },
      { pin:  9, name: 'OEn', type: 'input'  },
      { pin: 10, name: 'GND', type: 'power'  },
      { pin: 11, name: 'Q0',  type: 'output' },
      { pin: 12, name: 'Q1',  type: 'output' },
      { pin: 13, name: 'Q2',  type: 'output' },
      { pin: 14, name: 'Q3',  type: 'output' },
      { pin: 15, name: 'RCO', type: 'output' },
      { pin: 16, name: 'ENT', type: 'input'  },
      { pin: 17, name: 'ENP', type: 'input'  },
      { pin: 18, name: 'LOAD',type: 'input'  },
      { pin: 19, name: 'UD',  type: 'input'  },
      { pin: 20, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'COUNTER_LATCH_MUX_STUB', inputs: ['CLK','CLR','D0','D1','D2','D3','LE','S','OEn','ENT','ENP','LOAD','UD'], outputs: ['Q0','Q1','Q2','Q3','RCO'] },
    ],
  },

  // ── 74692: 4 bit decade counter/latch/mux sync CLR TRI (20-pin) ──────────
  /* Primary source: Texas Instruments, 74692 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls692.pdf
     https://en.wikipedia.org/wiki/Counter_(digital) */
  '74692': {
    name: '74x692',
    simpleName: '4 bit BCD Counter/Latch/Mux (Sync CLR)',
    description: '4 bit decade counter/latch/multiplexer with synchronous clear and tri-state output (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls692.pdf',
    tags: ['counter', 'bcd', 'decade', 'latch', 'multiplexer', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x692 is identical to the 74x690 except CLR is synchronous: the counter clears on the next rising clock edge rather than immediately. Synchronous clear prevents spurious transitions in noise-sensitive systems.',
    guidePinDescriptions: {
      'CLK':  'Clock input (rising edge).',
      'CLR':  'Synchronous Clear (active LOW). Clears on the next clock edge.',
      'D0':   'Parallel load input bit 0.',
      'D1':   'Parallel load input bit 1.',
      'D2':   'Parallel load input bit 2.',
      'D3':   'Parallel load input bit 3.',
      'LE':   'Latch Enable.',
      'S':    'Output Select: LOW = latch; HIGH = counter.',
      'OEn':  'Output Enable (active LOW).',
      'GND':  'Ground reference (pin 10).',
      'Q0':   'Output bit 0.',
      'Q1':   'Output bit 1.',
      'Q2':   'Output bit 2.',
      'Q3':   'Output bit 3.',
      'RCO':  'Ripple Carry Output.',
      'ENT':  'Count Enable T (active LOW).',
      'ENP':  'Count Enable P (active LOW).',
      'LOAD': 'Parallel Load (active LOW).',
      'UD':   'Up/Down select.',
      'VCC':  'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'Synchronous vs Asynchronous Clear',
        paragraphs: [
          '74x690 CLR is async (instant); 74x692 CLR is synchronous (waits for clock edge). Use 74x692 in clocked systems where deterministic timing is required.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'CLK', type: 'input'  },
      { pin:  2, name: 'CLR', type: 'input'  },
      { pin:  3, name: 'D0',  type: 'input'  },
      { pin:  4, name: 'D1',  type: 'input'  },
      { pin:  5, name: 'D2',  type: 'input'  },
      { pin:  6, name: 'D3',  type: 'input'  },
      { pin:  7, name: 'LE',  type: 'input'  },
      { pin:  8, name: 'S',   type: 'input'  },
      { pin:  9, name: 'OEn', type: 'input'  },
      { pin: 10, name: 'GND', type: 'power'  },
      { pin: 11, name: 'Q0',  type: 'output' },
      { pin: 12, name: 'Q1',  type: 'output' },
      { pin: 13, name: 'Q2',  type: 'output' },
      { pin: 14, name: 'Q3',  type: 'output' },
      { pin: 15, name: 'RCO', type: 'output' },
      { pin: 16, name: 'ENT', type: 'input'  },
      { pin: 17, name: 'ENP', type: 'input'  },
      { pin: 18, name: 'LOAD',type: 'input'  },
      { pin: 19, name: 'UD',  type: 'input'  },
      { pin: 20, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'COUNTER_LATCH_MUX_STUB', inputs: ['CLK','CLR','D0','D1','D2','D3','LE','S','OEn','ENT','ENP','LOAD','UD'], outputs: ['Q0','Q1','Q2','Q3','RCO'] },
    ],
  },

  // ── 74693: 4 bit binary counter/latch/mux sync CLR TRI (20-pin) ──────────
  /* Primary source: Texas Instruments, 74693 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls693.pdf
     https://en.wikipedia.org/wiki/Counter_(digital) */
  '74693': {
    name: '74x693',
    simpleName: '4 bit Binary Counter/Latch/Mux (Sync CLR)',
    description: '4 bit binary counter/latch/multiplexer with synchronous clear and tri-state output (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls693.pdf',
    tags: ['counter', 'binary', '4 bit', 'latch', 'multiplexer', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x693 is the binary version of the 74x692: a 4 bit binary counter with synchronous CLR, output latch, 2:1 MUX, and tri-state outputs. Counts 0-15 in binary. Synchronous clear ensures glitch-free reset aligned to the clock edge.',
    guidePinDescriptions: {
      'CLK':  'Clock input (rising edge).',
      'CLR':  'Synchronous Clear (active LOW).',
      'D0':   'Parallel load input bit 0.',
      'D1':   'Parallel load input bit 1.',
      'D2':   'Parallel load input bit 2.',
      'D3':   'Parallel load input bit 3.',
      'LE':   'Latch Enable.',
      'S':    'Output Select: LOW = latch; HIGH = counter.',
      'OEn':  'Output Enable (active LOW).',
      'GND':  'Ground reference (pin 10).',
      'Q0':   'Output bit 0.',
      'Q1':   'Output bit 1.',
      'Q2':   'Output bit 2.',
      'Q3':   'Output bit 3.',
      'RCO':  'Ripple Carry Output.',
      'ENT':  'Count Enable T (active LOW).',
      'ENP':  'Count Enable P (active LOW).',
      'LOAD': 'Parallel Load (active LOW).',
      'UD':   'Up/Down select.',
      'VCC':  'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: '74x690-74x693 Family Summary',
        list: [
          '74x690: BCD, async CLR',
          '74x691: Binary, async CLR',
          '74x692: BCD, sync CLR',
          '74x693: Binary, sync CLR',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'CLK', type: 'input'  },
      { pin:  2, name: 'CLR', type: 'input'  },
      { pin:  3, name: 'D0',  type: 'input'  },
      { pin:  4, name: 'D1',  type: 'input'  },
      { pin:  5, name: 'D2',  type: 'input'  },
      { pin:  6, name: 'D3',  type: 'input'  },
      { pin:  7, name: 'LE',  type: 'input'  },
      { pin:  8, name: 'S',   type: 'input'  },
      { pin:  9, name: 'OEn', type: 'input'  },
      { pin: 10, name: 'GND', type: 'power'  },
      { pin: 11, name: 'Q0',  type: 'output' },
      { pin: 12, name: 'Q1',  type: 'output' },
      { pin: 13, name: 'Q2',  type: 'output' },
      { pin: 14, name: 'Q3',  type: 'output' },
      { pin: 15, name: 'RCO', type: 'output' },
      { pin: 16, name: 'ENT', type: 'input'  },
      { pin: 17, name: 'ENP', type: 'input'  },
      { pin: 18, name: 'LOAD',type: 'input'  },
      { pin: 19, name: 'UD',  type: 'input'  },
      { pin: 20, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'COUNTER_LATCH_MUX_STUB', inputs: ['CLK','CLR','D0','D1','D2','D3','LE','S','OEn','ENT','ENP','LOAD','UD'], outputs: ['Q0','Q1','Q2','Q3','RCO'] },
    ],
  },
};