// chips28.js - Chips Block 28: 74479-74516
export const CHIPS_BLOCK_28 = {

  // ── 74480: Burst Error Recovery (stub), 24-pin ─────────────────────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits */
  '74480': {
    name: '74x480', simpleName: 'Burst Error Recovery (stub)',
    description: 'Single burst error recovery circuit; specialized error-correction (logic stub) (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    tags: ['error-recovery', 'stub'],
    guideOverview: 'The 74x480 is a single burst error recovery circuit used in data storage and communications to correct single burst errors in serial data streams. It implements a specialized polynomial-based correction algorithm. Due to its analog and complex digital nature, it is represented as a logic stub in the simulator.',
    guidePinDescriptions: {
      'D0':    'Data input bit 0.',
      'D1':    'Data input bit 1.',
      'D2':    'Data input bit 2.',
      'D3':    'Data input bit 3.',
      'D4':    'Data input bit 4.',
      'D5':    'Data input bit 5.',
      'D6':    'Data input bit 6.',
      'D7':    'Data input bit 7.',
      'CLK':   'Clock.',
      'LOADn': 'Load (active LOW).',
      'OEn':   'Output Enable (active LOW).',
      'GND':   'Ground reference (pin 12).',
      'ERR':   'Error flag output.',
      'Q0':    'Corrected data output bit 0.',
      'Q1':    'Corrected data output bit 1.',
      'Q2':    'Corrected data output bit 2.',
      'Q3':    'Corrected data output bit 3.',
      'Q4':    'Corrected data output bit 4.',
      'Q5':    'Corrected data output bit 5.',
      'Q6':    'Corrected data output bit 6.',
      'Q7':    'Corrected data output bit 7.',
      'NC1':   'No connect.',
      'NC2':   'No connect.',
      'VCC':   'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: 'Burst Error Correction',
        paragraphs: [
          'A burst error is a sequence of consecutive corrupted bits in a data stream. Unlike random errors, burst errors typically arise from physical media defects, impulse noise, or synchronization loss. This chip applies a hardware polynomial algorithm to detect and correct such bursts.',
        ],
        note: 'This device is simulated as a stub. Real burst error correction requires analog signal integrity analysis beyond the scope of logic simulation.',
      },
    ],
    pinout: [
      { pin:  1, name: 'D0',    type: 'input' },  { pin:  2, name: 'D1',    type: 'input' },
      { pin:  3, name: 'D2',    type: 'input' },  { pin:  4, name: 'D3',    type: 'input' },
      { pin:  5, name: 'D4',    type: 'input' },  { pin:  6, name: 'D5',    type: 'input' },
      { pin:  7, name: 'D6',    type: 'input' },  { pin:  8, name: 'D7',    type: 'input' },
      { pin:  9, name: 'CLK',   type: 'input' },  { pin: 10, name: 'LOADn', type: 'input' },
      { pin: 11, name: 'OEn',   type: 'input' },  { pin: 12, name: 'GND',   type: 'power' },
      { pin: 13, name: 'ERR',   type: 'output' }, { pin: 14, name: 'Q0',    type: 'output' },
      { pin: 15, name: 'Q1',    type: 'output' }, { pin: 16, name: 'Q2',    type: 'output' },
      { pin: 17, name: 'Q3',    type: 'output' }, { pin: 18, name: 'Q4',    type: 'output' },
      { pin: 19, name: 'Q5',    type: 'output' }, { pin: 20, name: 'Q6',    type: 'output' },
      { pin: 21, name: 'Q7',    type: 'output' }, { pin: 22, name: 'NC1',   type: 'nc' },
      { pin: 23, name: 'NC2',   type: 'nc' },  { pin: 24, name: 'VCC',   type: 'power' },
    ],
    gates: [{ type: 'BURST_ERR_RECOVERY',
      inputs: ['D0','D1','D2','D3','D4','D5','D6','D7','CLK','LOADn','OEn'],
      outputs: ['Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7','ERR'] }],
  },

  // ── 74482: 4 bit Control Slice (stub), 20-pin ──────────────────────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits */
  '74482': {
    name: '74x482', simpleName: '4 bit Control Slice (stub)',
    description: '4 bit slice expandable pipeline control element (logic stub) (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    tags: ['control', 'slice', 'pipeline', 'stub'],
    guideOverview: 'The 74x482 is a 4 bit expandable pipeline control element used to build microcode sequencers and microprogrammed controllers. Multiple slices cascade to control wider instruction pipelines. Represented as a logic stub in the simulator due to its complex internal state machine.',
    guidePinDescriptions: {
      'I0': 'Instruction/control input bit 0.',
      'I1': 'Instruction/control input bit 1.',
      'I2': 'Instruction/control input bit 2.',
      'I3': 'Instruction/control input bit 3.',
      'I4': 'Instruction/control input bit 4.',
      'I5': 'Instruction/control input bit 5.',
      'I6': 'Instruction/control input bit 6.',
      'I7': 'Instruction/control input bit 7.',
      'I8': 'Instruction/control input bit 8.',
      'GND': 'Ground reference (pin 10).',
      'Y0': 'Control output bit 0.',
      'Y1': 'Control output bit 1.',
      'Y2': 'Control output bit 2.',
      'Y3': 'Control output bit 3.',
      'Y4': 'Control output bit 4.',
      'Y5': 'Control output bit 5.',
      'Y6': 'Control output bit 6.',
      'Y7': 'Control output bit 7.',
      'Y8': 'Control output bit 8.',
      'VCC': 'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'Pipeline Control Slice',
        paragraphs: [
          'Microprogrammed control units use ROM lookup tables (microcode) to decode instruction opcodes into sequences of control signals. A control slice handles a portion of those control bits, with multiple slices cascaded for wider control words.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'I0',  type: 'input' },  { pin:  2, name: 'I1',  type: 'input' },
      { pin:  3, name: 'I2',  type: 'input' },  { pin:  4, name: 'I3',  type: 'input' },
      { pin:  5, name: 'I4',  type: 'input' },  { pin:  6, name: 'I5',  type: 'input' },
      { pin:  7, name: 'I6',  type: 'input' },  { pin:  8, name: 'I7',  type: 'input' },
      { pin:  9, name: 'I8',  type: 'input' },  { pin: 10, name: 'GND', type: 'power' },
      { pin: 11, name: 'Y0',  type: 'output' }, { pin: 12, name: 'Y1',  type: 'output' },
      { pin: 13, name: 'Y2',  type: 'output' }, { pin: 14, name: 'Y3',  type: 'output' },
      { pin: 15, name: 'Y4',  type: 'output' }, { pin: 16, name: 'Y5',  type: 'output' },
      { pin: 17, name: 'Y6',  type: 'output' }, { pin: 18, name: 'Y7',  type: 'output' },
      { pin: 19, name: 'Y8',  type: 'output' }, { pin: 20, name: 'VCC', type: 'power' },
    ],
    gates: [{ type: 'CONTROL_SLICE_4BIT',
      inputs: ['I0','I1','I2','I3','I4','I5','I6','I7','I8'],
      outputs: ['Y0','Y1','Y2','Y3','Y4','Y5','Y6','Y7','Y8'] }],
  },

  // ── 74484: BCD-to-Binary Converter, 20-pin ─────────────────────────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Three-state_logic */
  '74484': {
    name: '74x484', simpleName: 'BCD-to-Binary Converter',
    description: '7 bit BCD-to-binary converter with tri-state outputs (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    tags: ['converter', 'bcd', 'binary', 'tri-state'],
    guideOverview: 'The 74x484 converts a 2-digit BCD number (up to 99 decimal) to a 7 bit pure binary output. Two BCD digits (units D1 and tens D2, each A-D) are presented in parallel; the chip combinationally converts the BCD-encoded value to its binary equivalent on Y0-Y6. OEn tri-states the outputs.',
    guidePinDescriptions: {
      'C1':  'BCD units digit input bit C (weight 4).',
      'B1':  'BCD units digit input bit B (weight 2).',
      'A1':  'BCD units digit input bit A (weight 1, LSB).',
      'D1':  'BCD units digit input bit D (weight 8, MSB).',
      'C2':  'BCD tens digit input bit C.',
      'B2':  'BCD tens digit input bit B.',
      'A2':  'BCD tens digit input bit A.',
      'OEn': 'Output Enable (active LOW).',
      'D2':  'BCD tens digit input bit D.',
      'GND': 'Ground reference (pin 10).',
      'Y0':  'Binary output bit 0 (LSB).',
      'Y1':  'Binary output bit 1.',
      'Y2':  'Binary output bit 2.',
      'Y3':  'Binary output bit 3.',
      'Y4':  'Binary output bit 4.',
      'Y5':  'Binary output bit 5.',
      'Y6':  'Binary output bit 6 (MSB, range 0-99 = 0-64h).',
      'NC1': 'No connect.',
      'NC2': 'No connect.',
      'VCC': 'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'BCD to Binary Conversion',
        paragraphs: [
          'BCD represents each decimal digit separately as 4 bits. Pure binary encodes the entire value in a single binary word. For example, decimal 47 is 0100 0111 in BCD but 0101111 (47) in binary.',
          'The 74x484 handles values 0-99, producing a 7 bit binary result (0-127 range, but only 0-99 are valid BCD inputs).',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'C1',  type: 'input' },  { pin:  2, name: 'B1',  type: 'input' },
      { pin:  3, name: 'A1',  type: 'input' },  { pin:  4, name: 'D1',  type: 'input' },
      { pin:  5, name: 'C2',  type: 'input' },  { pin:  6, name: 'B2',  type: 'input' },
      { pin:  7, name: 'A2',  type: 'input' },  { pin:  8, name: 'OEn', type: 'input' },
      { pin:  9, name: 'D2',  type: 'input' },  { pin: 10, name: 'GND', type: 'power' },
      { pin: 11, name: 'Y0',  type: 'output' }, { pin: 12, name: 'Y1',  type: 'output' },
      { pin: 13, name: 'Y2',  type: 'output' }, { pin: 14, name: 'Y3',  type: 'output' },
      { pin: 15, name: 'Y4',  type: 'output' }, { pin: 16, name: 'Y5',  type: 'output' },
      { pin: 17, name: 'Y6',  type: 'output' }, { pin: 18, name: 'NC1', type: 'nc' },
      { pin: 19, name: 'NC2', type: 'nc' },  { pin: 20, name: 'VCC', type: 'power' },
    ],
    gates: [{ type: 'BCD_TO_BIN',
      inputs: ['A1','B1','C1','D1','A2','B2','C2','D2','OEn'],
      outputs: ['Y0','Y1','Y2','Y3','Y4','Y5','Y6'] }],
  },

  // ── 74485: Binary-to-BCD Converter, 20-pin ─────────────────────────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Three-state_logic */
  '74485': {
    name: '74x485', simpleName: 'Binary-to-BCD Converter',
    description: '7 bit binary-to-BCD converter with tri-state outputs (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    tags: ['converter', 'binary', 'bcd', 'tri-state'],
    guideOverview: 'The 74x485 is the inverse of the 74x484: it converts a 7 bit binary number to a 2-digit BCD output. Given a binary value 0-99 on I0-I6, it outputs the tens digit on D2/C2/B2/A2 and the units digit on D1/C1/B1/A1. OEn tri-states all outputs.',
    guidePinDescriptions: {
      'I0':  'Binary input bit 0 (LSB).',
      'I1':  'Binary input bit 1.',
      'I2':  'Binary input bit 2.',
      'I3':  'Binary input bit 3.',
      'I4':  'Binary input bit 4.',
      'I5':  'Binary input bit 5.',
      'I6':  'Binary input bit 6 (MSB).',
      'OEn': 'Output Enable (active LOW).',
      'NC1': 'No connect.',
      'GND': 'Ground reference (pin 10).',
      'A1':  'Units digit output bit A (weight 1).',
      'B1':  'Units digit output bit B (weight 2).',
      'C1':  'Units digit output bit C (weight 4).',
      'D1':  'Units digit output bit D (weight 8).',
      'A2':  'Tens digit output bit A.',
      'B2':  'Tens digit output bit B.',
      'C2':  'Tens digit output bit C.',
      'D2':  'Tens digit output bit D.',
      'NC2': 'No connect.',
      'VCC': 'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'Binary to BCD Conversion',
        paragraphs: [
          'Connecting 74x485 output to a BCD 7-segment decoder (like 74x447) allows direct display of a binary counter value in decimal digits. The chain is: binary counter → 74x485 → two 74x447s → two 7-segment displays.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'I0',  type: 'input' },  { pin:  2, name: 'I1',  type: 'input' },
      { pin:  3, name: 'I2',  type: 'input' },  { pin:  4, name: 'I3',  type: 'input' },
      { pin:  5, name: 'I4',  type: 'input' },  { pin:  6, name: 'I5',  type: 'input' },
      { pin:  7, name: 'I6',  type: 'input' },  { pin:  8, name: 'OEn', type: 'input' },
      { pin:  9, name: 'NC1', type: 'nc' },  { pin: 10, name: 'GND', type: 'power' },
      { pin: 11, name: 'A1',  type: 'output' }, { pin: 12, name: 'B1',  type: 'output' },
      { pin: 13, name: 'C1',  type: 'output' }, { pin: 14, name: 'D1',  type: 'output' },
      { pin: 15, name: 'A2',  type: 'output' }, { pin: 16, name: 'B2',  type: 'output' },
      { pin: 17, name: 'C2',  type: 'output' }, { pin: 18, name: 'D2',  type: 'output' },
      { pin: 19, name: 'NC2', type: 'nc' },  { pin: 20, name: 'VCC', type: 'power' },
    ],
    gates: [{ type: 'BIN_TO_BCD',
      inputs: ['I0','I1','I2','I3','I4','I5','I6','OEn'],
      outputs: ['A1','B1','C1','D1','A2','B2','C2','D2'] }],
  },

  // ── 74490: Dual Decade Counter, 16-pin ─────────────────────────────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Counter_(digital) */
  '74490': {
    name: '74x490', simpleName: 'Dual Decade Counter',
    description: 'Dual decade counter, two independent sections each with async clear (16-pin)',
    pins: 16, vcc: 16, gnd: 8, sequential: true,
    tags: ['counter', 'decade', 'dual', 'asynchronous'],
    guideOverview: 'The 74x490 contains two independent BCD decade counters with asynchronous (active HIGH) clear. Each counter has a divide-by-2 clock (CKA) and a divide-by-5 clock (CKB). Connect CKB to QA for a 0-9 BCD counter. This is functionally equivalent to the 74x390 with slight pin ordering differences.',
    guidePinDescriptions: {
      'CKA1': 'Clock A (÷2 stage) for counter 1. Falls on negative edge.',
      'CLR1': 'Clear for counter 1 (active HIGH). Asynchronously resets to 0.',
      'CKB1': 'Clock B (÷5 stage) for counter 1. Connect to QA1 for BCD.',
      'QA1':  'Output A (bit 0) of counter 1.',
      'QB1':  'Output B of counter 1.',
      'QC1':  'Output C of counter 1.',
      'QD1':  'Output D (MSB) of counter 1.',
      'GND':  'Ground reference (pin 8).',
      'QD2':  'Output D of counter 2.',
      'QC2':  'Output C of counter 2.',
      'QB2':  'Output B of counter 2.',
      'QA2':  'Output A of counter 2.',
      'CKB2': 'Clock B for counter 2.',
      'CLR2': 'Clear for counter 2 (active HIGH).',
      'CKA2': 'Clock A for counter 2.',
      'VCC':  'Positive supply (+5 V, pin 16).',
    },
    guideSections: [
      {
        title: 'BCD Decade Counter',
        paragraphs: [
          'Connect CKB to QA to form a full BCD 0-9 counter. The ÷2 stage clocks on CKA; the ÷5 stage clocks from QA. When the count reaches 9 the next CKA pulse wraps back to 0.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'CKA1', type: 'input' },  { pin:  2, name: 'CLR1', type: 'input' },
      { pin:  3, name: 'CKB1', type: 'input' },  { pin:  4, name: 'QA1',  type: 'output' },
      { pin:  5, name: 'QB1',  type: 'output' }, { pin:  6, name: 'QC1',  type: 'output' },
      { pin:  7, name: 'QD1',  type: 'output' }, { pin:  8, name: 'GND',  type: 'power' },
      { pin:  9, name: 'QD2',  type: 'output' }, { pin: 10, name: 'QC2',  type: 'output' },
      { pin: 11, name: 'QB2',  type: 'output' }, { pin: 12, name: 'QA2',  type: 'output' },
      { pin: 13, name: 'CKB2', type: 'input' },  { pin: 14, name: 'CLR2', type: 'input' },
      { pin: 15, name: 'CKA2', type: 'input' },  { pin: 16, name: 'VCC',  type: 'power' },
    ],
    gates: [{ type: 'COUNTER_DECADE_DUAL',
      inputs: ['CKA1','CLR1','CKB1','CKA2','CLR2','CKB2'],
      outputs: ['QA1','QB1','QC1','QD1','QA2','QB2','QC2','QD2'] }],
  },

  // ── 74491: 10 bit Up/Down Counter, 24-pin ──────────────────────────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Counter_(digital)
     Wikipedia: https://en.wikipedia.org/wiki/Three-state_logic */
  '74491': {
    name: '74x491', simpleName: '10 bit Up/Down Counter',
    description: '10 bit synchronous binary up/down counter with limited preset and tri-state outputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12, sequential: true,
    tags: ['counter', '10 bit', 'up-down', 'synchronous', 'tri-state'],
    guideOverview: 'The 74x491 is a 10 bit synchronous binary up/down counter with parallel preset (P0-P9), direction select (U_Dn), enable (ENn), clear (CLRn), parallel load (LOADn), and tri-state outputs (OEn). Its 10 bit width (count 0-1023) makes it useful for address generation in 1K memory systems.',
    guidePinDescriptions: {
      'CLK':   'Clock (rising edge).',
      'U_Dn':  'Direction. HIGH = up; LOW = down.',
      'ENn':   'Count Enable (active LOW). When HIGH, counter holds.',
      'CLRn':  'Asynchronous Clear (active LOW).',
      'LOADn': 'Parallel Load (active LOW). Loads P0-P9 on next CLK.',
      'P0':    'Preset bit 0.',
      'P1':    'Preset bit 1.',
      'P2':    'Preset bit 2.',
      'P3':    'Preset bit 3.',
      'P4':    'Preset bit 4.',
      'P5':    'Preset bit 5.',
      'GND':   'Ground reference (pin 12).',
      'P6':    'Preset bit 6.',
      'P7':    'Preset bit 7.',
      'P8':    'Preset bit 8.',
      'P9':    'Preset bit 9.',
      'OEn':   'Output Enable (active LOW).',
      'Q0':    'Counter output bit 0.',
      'Q1':    'Counter output bit 1.',
      'Q2':    'Counter output bit 2.',
      'Q3':    'Counter output bit 3.',
      'Q4':    'Counter output bit 4.',
      'Q5':    'Counter output bit 5.',
      'VCC':   'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: '10 bit Address Counter',
        paragraphs: [
          'A 10 bit counter can directly address 1024 (1K) memory locations (0x000-0x3FF). Load an arbitrary start address via P0-P9 for non-zero starting DMA or memory scan operations.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'CLK',   type: 'input' },  { pin:  2, name: 'U_Dn',  type: 'input' },
      { pin:  3, name: 'ENn',   type: 'input' },  { pin:  4, name: 'CLRn',  type: 'input' },
      { pin:  5, name: 'LOADn', type: 'input' },  { pin:  6, name: 'P0',    type: 'input' },
      { pin:  7, name: 'P1',    type: 'input' },  { pin:  8, name: 'P2',    type: 'input' },
      { pin:  9, name: 'P3',    type: 'input' },  { pin: 10, name: 'P4',    type: 'input' },
      { pin: 11, name: 'P5',    type: 'input' },  { pin: 12, name: 'GND',   type: 'power' },
      { pin: 13, name: 'P6',    type: 'input' },  { pin: 14, name: 'P7',    type: 'input' },
      { pin: 15, name: 'P8',    type: 'input' },  { pin: 16, name: 'P9',    type: 'input' },
      { pin: 17, name: 'OEn',   type: 'input' },  { pin: 18, name: 'Q0',    type: 'output' },
      { pin: 19, name: 'Q1',    type: 'output' }, { pin: 20, name: 'Q2',    type: 'output' },
      { pin: 21, name: 'Q3',    type: 'output' }, { pin: 22, name: 'Q4',    type: 'output' },
      { pin: 23, name: 'Q5',    type: 'output' }, { pin: 24, name: 'VCC',   type: 'power' },
    ],
    gates: [{ type: 'COUNTER_10BIT_UPDOWN',
      inputs: ['CLK','U_Dn','ENn','CLRn','LOADn','P0','P1','P2','P3','P4','P5','P6','P7','P8','P9','OEn'],
      outputs: ['Q0','Q1','Q2','Q3','Q4','Q5'] }],
  },

  // ── 74498: 8 bit Bidirectional Shift Register, 24-pin ──────────────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Shift_register
     Wikipedia: https://en.wikipedia.org/wiki/Three-state_logic */
  '74498': {
    name: '74x498', simpleName: '8 bit Bidirectional Shift Register',
    description: '8 bit bidirectional shift register with parallel inputs and tri-state outputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12, sequential: true,
    tags: ['shift-register', '8 bit', 'bidirectional', 'parallel-load', 'tri-state'],
    guideOverview: 'The 74x498 is an 8 bit bidirectional shift register with parallel load, tri-state outputs, and independent left/right serial inputs (SRL, SRR). Two mode-select bits (S0, S1) choose from: hold (00), shift right (01), shift left (10), or parallel load (11). OEn tri-states Q0-Q7.',
    guidePinDescriptions: {
      'S0':  'Mode select bit 0. See mode table.',
      'S1':  'Mode select bit 1.',
      'CLK': 'Clock (rising edge).',
      'OEn': 'Output Enable (active LOW).',
      'SRL': 'Serial input for shift-left mode. Data enters at Q7.',
      'SRR': 'Serial input for shift-right mode. Data enters at Q0.',
      'P0':  'Parallel data input bit 0.',
      'P1':  'Parallel data input bit 1.',
      'P2':  'Parallel data input bit 2.',
      'P3':  'Parallel data input bit 3.',
      'P4':  'Parallel data input bit 4.',
      'GND': 'Ground reference (pin 12).',
      'P5':  'Parallel data input bit 5.',
      'P6':  'Parallel data input bit 6.',
      'P7':  'Parallel data input bit 7.',
      'Q0':  'Output bit 0.',
      'Q1':  'Output bit 1.',
      'Q2':  'Output bit 2.',
      'Q3':  'Output bit 3.',
      'Q4':  'Output bit 4.',
      'Q5':  'Output bit 5.',
      'Q6':  'Output bit 6.',
      'Q7':  'Output bit 7.',
      'VCC': 'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: 'Mode Select Table',
        paragraphs: [
          'S1=0, S0=0: Hold (no change). S1=0, S0=1: Shift right (SRR enters at Q0). S1=1, S0=0: Shift left (SRL enters at Q7). S1=1, S0=1: Parallel load P0-P7.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'S0',  type: 'input' },  { pin:  2, name: 'S1',  type: 'input' },
      { pin:  3, name: 'CLK', type: 'input' },  { pin:  4, name: 'OEn', type: 'input' },
      { pin:  5, name: 'SRL', type: 'input' },  { pin:  6, name: 'SRR', type: 'input' },
      { pin:  7, name: 'P0',  type: 'input' },  { pin:  8, name: 'P1',  type: 'input' },
      { pin:  9, name: 'P2',  type: 'input' },  { pin: 10, name: 'P3',  type: 'input' },
      { pin: 11, name: 'P4',  type: 'input' },  { pin: 12, name: 'GND', type: 'power' },
      { pin: 13, name: 'P5',  type: 'input' },  { pin: 14, name: 'P6',  type: 'input' },
      { pin: 15, name: 'P7',  type: 'input' },  { pin: 16, name: 'Q0',  type: 'output' },
      { pin: 17, name: 'Q1',  type: 'output' }, { pin: 18, name: 'Q2',  type: 'output' },
      { pin: 19, name: 'Q3',  type: 'output' }, { pin: 20, name: 'Q4',  type: 'output' },
      { pin: 21, name: 'Q5',  type: 'output' }, { pin: 22, name: 'Q6',  type: 'output' },
      { pin: 23, name: 'Q7',  type: 'output' }, { pin: 24, name: 'VCC', type: 'power' },
    ],
    gates: [{ type: 'SHIFT_REG_8BIT_BIDI',
      inputs: ['CLK','S0','S1','SRL','SRR','P0','P1','P2','P3','P4','P5','P6','P7','OEn'],
      outputs: ['Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7'] }],
  },

  // ── 74500: 6 bit Flash ADC (stub), 24-pin ──────────────────────────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Digital_comparator */
  '74500': {
    name: '74x500', simpleName: '6 bit Flash ADC (stub)',
    description: '6 bit flash analog-to-digital converter; analog device (logic stub) (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    tags: ['adc', 'analog', 'flash', 'stub'],
    guideOverview: 'The 74x500 is a 6 bit flash (parallel) analog-to-digital converter. Flash ADCs compare the input voltage against 2^N reference voltages simultaneously using a resistor ladder and comparator array, making them the fastest ADC topology. Simulated as a logic stub due to analog content.',
    guidePinDescriptions: {
      'VIN':  'Analog voltage input.',
      'VREF': 'Reference voltage input. Defines full-scale range.',
      'OEn':  'Output Enable (active LOW).',
      'CLK':  'Conversion clock.',
      'NC1':  'No connect.',
      'NC2':  'No connect.',
      'NC3':  'No connect.',
      'NC4':  'No connect.',
      'NC5':  'No connect.',
      'NC6':  'No connect.',
      'NC7':  'No connect.',
      'GND':  'Ground reference (pin 12).',
      'D0':   'Digital output bit 0 (LSB).',
      'D1':   'Digital output bit 1.',
      'D2':   'Digital output bit 2.',
      'D3':   'Digital output bit 3.',
      'D4':   'Digital output bit 4.',
      'D5':   'Digital output bit 5 (MSB).',
      'CC':   'Conversion Complete flag.',
      'NC8':  'No connect.',
      'NC9':  'No connect.',
      'NC10': 'No connect.',
      'NC11': 'No connect.',
      'VCC':  'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: 'Flash ADC Architecture',
        paragraphs: [
          'A flash ADC uses 2^N-1 comparators in parallel to convert an analog input in a single clock cycle. The 6 bit version requires 63 comparators. This makes it extremely fast but power-hungry and expensive compared to SAR or delta-sigma ADCs.',
        ],
        note: 'Logic stub analog conversion is not simulated.',
      },
    ],
    pinout: [
      { pin:  1, name: 'VIN',  type: 'input' },  { pin:  2, name: 'VREF', type: 'input' },
      { pin:  3, name: 'OEn',  type: 'input' },  { pin:  4, name: 'CLK',  type: 'input' },
      { pin:  5, name: 'NC1',  type: 'nc' },  { pin:  6, name: 'NC2',  type: 'nc' },
      { pin:  7, name: 'NC3',  type: 'nc' },  { pin:  8, name: 'NC4',  type: 'nc' },
      { pin:  9, name: 'NC5',  type: 'nc' },  { pin: 10, name: 'NC6',  type: 'nc' },
      { pin: 11, name: 'NC7',  type: 'nc' },  { pin: 12, name: 'GND',  type: 'power' },
      { pin: 13, name: 'D0',   type: 'output' }, { pin: 14, name: 'D1',   type: 'output' },
      { pin: 15, name: 'D2',   type: 'output' }, { pin: 16, name: 'D3',   type: 'output' },
      { pin: 17, name: 'D4',   type: 'output' }, { pin: 18, name: 'D5',   type: 'output' },
      { pin: 19, name: 'CC',   type: 'output' }, { pin: 20, name: 'NC8',  type: 'nc' },
      { pin: 21, name: 'NC9',  type: 'nc' },  { pin: 22, name: 'NC10', type: 'nc' },
      { pin: 23, name: 'NC11', type: 'nc' },  { pin: 24, name: 'VCC',  type: 'power' },
    ],
    gates: [{ type: 'ADC_6BIT_FLASH',
      inputs: ['VIN','VREF','OEn','CLK'],
      outputs: ['D0','D1','D2','D3','D4','D5','CC'] }],
  },

  // ── 74502: 8 bit Successive Approx Register, 16-pin ────────────────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits */
  '74502': {
    name: '74x502', simpleName: '8 bit Successive Approx Register',
    description: '8 bit successive approximation register (SAR) for ADC use (16-pin)',
    pins: 16, vcc: 16, gnd: 8, sequential: true,
    tags: ['sar', 'successive-approximation', '8 bit', 'adc'],
    guideOverview: 'The 74x502 is an 8 bit successive approximation register (SAR) the digital control core of a SAR ADC. A SAR performs binary search: it starts from the MSB, tentatively sets each bit, compares the resulting DAC output against the analog input via COMP, and keeps or clears the bit based on the result. The process repeats for 8 clock cycles producing the 8 bit result.',
    guidePinDescriptions: {
      'CLK':    'Clock input. Each rising edge performs one bit trial.',
      'EOCn':   'End-Of-Conversion reset (active LOW). Hold LOW during conversion; release to start next cycle.',
      'STARTn': 'Start conversion (active LOW pulse).',
      'COMP':   'Comparator input. HIGH = DAC output > VIN (clear bit); LOW = keep bit.',
      'Q0':     'SAR output bit 0.',
      'Q1':     'SAR output bit 1.',
      'Q2':     'SAR output bit 2.',
      'GND':    'Ground reference (pin 8).',
      'Q3':     'SAR output bit 3.',
      'Q4':     'SAR output bit 4.',
      'Q5':     'SAR output bit 5.',
      'Q6':     'SAR output bit 6.',
      'Q7':     'SAR output bit 7 (MSB).',
      'EOC':    'End-Of-Conversion output. Pulses HIGH when 8 bit result is ready.',
      'SC':     'Start-of-Conversion output.',
      'VCC':    'Positive supply (+5 V, pin 16).',
    },
    guideSections: [
      {
        title: 'Successive Approximation Algorithm',
        paragraphs: [
          'The SAR tests each bit from MSB to LSB. On each clock: set the trial bit, output Q[7:0] to a DAC, compare DAC output vs VIN. If DAC > VIN, clear the bit; else keep it. After 8 clocks, Q[7:0] holds the converted result.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'CLK',    type: 'input' },  { pin:  2, name: 'EOCn',   type: 'input' },
      { pin:  3, name: 'STARTn', type: 'input' },  { pin:  4, name: 'COMP',   type: 'input' },
      { pin:  5, name: 'Q0',     type: 'output' }, { pin:  6, name: 'Q1',     type: 'output' },
      { pin:  7, name: 'Q2',     type: 'output' }, { pin:  8, name: 'GND',    type: 'power' },
      { pin:  9, name: 'Q3',     type: 'output' }, { pin: 10, name: 'Q4',     type: 'output' },
      { pin: 11, name: 'Q5',     type: 'output' }, { pin: 12, name: 'Q6',     type: 'output' },
      { pin: 13, name: 'Q7',     type: 'output' }, { pin: 14, name: 'EOC',    type: 'output' },
      { pin: 15, name: 'SC',     type: 'output' }, { pin: 16, name: 'VCC',    type: 'power' },
    ],
    gates: [{ type: 'SAR_8BIT',
      inputs: ['CLK','STARTn','COMP','EOCn'],
      outputs: ['Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7','EOC','SC'] }],
  },

  // ── 74503: 8 bit SAR (with expansion), 16-pin ──────────────────────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits */
  '74503': {
    name: '74x503', simpleName: '8 bit SAR (with expansion)',
    description: '8 bit successive approximation register with expansion control for ADC use (16-pin)',
    pins: 16, vcc: 16, gnd: 8, sequential: true,
    tags: ['sar', 'successive-approximation', '8 bit', 'adc', 'expansion'],
    guideOverview: 'The 74x503 is an 8 bit SAR with an expansion output (EXP) that allows cascading two devices for higher resolution. EXP feeds the cascade input of a second SAR to extend the conversion to 16 bits using a two-stage SAR + DAC chain.',
    guidePinDescriptions: {
      'CLK':    'Clock (rising edge, one bit trial per cycle).',
      'EOCn':   'End-Of-Conversion reset (active LOW).',
      'STARTn': 'Start conversion (active LOW pulse).',
      'COMP':   'Comparator result input.',
      'Q0':     'SAR bit 0.',
      'Q1':     'SAR bit 1.',
      'Q2':     'SAR bit 2.',
      'GND':    'Ground reference (pin 8).',
      'Q3':     'SAR bit 3.',
      'Q4':     'SAR bit 4.',
      'Q5':     'SAR bit 5.',
      'Q6':     'SAR bit 6.',
      'Q7':     'SAR bit 7 (MSB).',
      'EOC':    'End-Of-Conversion output.',
      'EXP':    'Expansion output. Triggers a second-stage SAR for higher-resolution cascading.',
      'VCC':    'Positive supply (+5 V, pin 16).',
    },
    guideSections: [
      {
        title: 'Cascading for Higher Resolution',
        paragraphs: [
          'Connect EXP of the first 74x503 to STARTn of a second 74x503. The first handles the high byte, the second the low byte, together producing a 16 bit result in two successive 8-cycle conversions.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'CLK',    type: 'input' },  { pin:  2, name: 'EOCn',   type: 'input' },
      { pin:  3, name: 'STARTn', type: 'input' },  { pin:  4, name: 'COMP',   type: 'input' },
      { pin:  5, name: 'Q0',     type: 'output' }, { pin:  6, name: 'Q1',     type: 'output' },
      { pin:  7, name: 'Q2',     type: 'output' }, { pin:  8, name: 'GND',    type: 'power' },
      { pin:  9, name: 'Q3',     type: 'output' }, { pin: 10, name: 'Q4',     type: 'output' },
      { pin: 11, name: 'Q5',     type: 'output' }, { pin: 12, name: 'Q6',     type: 'output' },
      { pin: 13, name: 'Q7',     type: 'output' }, { pin: 14, name: 'EOC',    type: 'output' },
      { pin: 15, name: 'EXP',    type: 'output' }, { pin: 16, name: 'VCC',    type: 'power' },
    ],
    gates: [{ type: 'SAR_8BIT_EXP',
      inputs: ['CLK','STARTn','COMP','EOCn'],
      outputs: ['Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7','EOC','EXP'] }],
  },

  // ── 74504: 12 bit SAR (with expansion), 24-pin ─────────────────────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits */
  '74504': {
    name: '74x504', simpleName: '12 bit SAR (with expansion)',
    description: '12 bit successive approximation register with expansion control for ADC use (24-pin)',
    pins: 24, vcc: 24, gnd: 12, sequential: true,
    tags: ['sar', 'successive-approximation', '12 bit', 'adc', 'expansion'],
    guideOverview: 'The 74x504 is a 12 bit SAR register that performs a 12-cycle successive approximation conversion, producing Q0-Q11. Like the 74x503 it includes an EXP cascade output for multi-chip high-resolution systems.',
    guidePinDescriptions: {
      'CLK':    'Clock (one bit trial per rising edge).',
      'EOCn':   'End-Of-Conversion reset (active LOW).',
      'STARTn': 'Start conversion (active LOW pulse).',
      'COMP':   'Comparator result.',
      'Q0':     'SAR output bit 0 (LSB).',
      'Q1':     'SAR output bit 1.',
      'Q2':     'SAR output bit 2.',
      'Q3':     'SAR output bit 3.',
      'Q4':     'SAR output bit 4.',
      'Q5':     'SAR output bit 5.',
      'Q6':     'SAR output bit 6.',
      'GND':    'Ground reference (pin 12).',
      'Q7':     'SAR output bit 7.',
      'Q8':     'SAR output bit 8.',
      'Q9':     'SAR output bit 9.',
      'Q10':    'SAR output bit 10.',
      'Q11':    'SAR output bit 11 (MSB).',
      'EOC':    'End-Of-Conversion output.',
      'EXP':    'Expansion cascade output.',
      'NC1':    'No connect.',
      'NC2':    'No connect.',
      'NC3':    'No connect.',
      'NC4':    'No connect.',
      'VCC':    'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: '12 bit SAR',
        paragraphs: [
          'A 12 bit SAR provides 4096 steps of resolution (0-4095), adequate for most precision measurement applications. Conversion takes 12 clock cycles.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'CLK',    type: 'input' },  { pin:  2, name: 'EOCn',   type: 'input' },
      { pin:  3, name: 'STARTn', type: 'input' },  { pin:  4, name: 'COMP',   type: 'input' },
      { pin:  5, name: 'Q0',     type: 'output' }, { pin:  6, name: 'Q1',     type: 'output' },
      { pin:  7, name: 'Q2',     type: 'output' }, { pin:  8, name: 'Q3',     type: 'output' },
      { pin:  9, name: 'Q4',     type: 'output' }, { pin: 10, name: 'Q5',     type: 'output' },
      { pin: 11, name: 'Q6',     type: 'output' }, { pin: 12, name: 'GND',    type: 'power' },
      { pin: 13, name: 'Q7',     type: 'output' }, { pin: 14, name: 'Q8',     type: 'output' },
      { pin: 15, name: 'Q9',     type: 'output' }, { pin: 16, name: 'Q10',    type: 'output' },
      { pin: 17, name: 'Q11',    type: 'output' }, { pin: 18, name: 'EOC',    type: 'output' },
      { pin: 19, name: 'EXP',    type: 'output' }, { pin: 20, name: 'NC1',    type: 'nc' },
      { pin: 21, name: 'NC2',    type: 'nc' },  { pin: 22, name: 'NC3',    type: 'nc' },
      { pin: 23, name: 'NC4',    type: 'nc' },  { pin: 24, name: 'VCC',    type: 'power' },
    ],
    gates: [{ type: 'SAR_12BIT_EXP',
      inputs: ['CLK','STARTn','COMP','EOCn'],
      outputs: ['Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7','Q8','Q9','Q10','Q11','EOC','EXP'] }],
  },

  // ── 74505: 8 bit SAR ADC (stub), 24-pin ────────────────────────────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Digital_comparator */
  '74505': {
    name: '74x505', simpleName: '8 bit SAR ADC (stub)',
    description: '8 bit successive approximation ADC; analog device (logic stub) (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    tags: ['adc', 'analog', 'successive-approximation', 'stub'],
    guideOverview: 'The 74x505 is a complete 8 bit successive approximation ADC integrating analog comparator, internal DAC, and SAR logic into one package. Unlike the 74x502/503 which are SAR-only chips requiring an external DAC and comparator, the 74x505 is a self-contained converter. Simulated as a logic stub due to analog content.',
    guidePinDescriptions: {
      'VIN':    'Analog voltage input.',
      'VREF':   'Reference voltage.',
      'OEn':    'Output Enable (active LOW).',
      'CLK':    'Conversion clock.',
      'STARTn': 'Start conversion (active LOW).',
      'NC1':    'No connect.',
      'NC2':    'No connect.',
      'NC3':    'No connect.',
      'NC4':    'No connect.',
      'NC5':    'No connect.',
      'NC6':    'No connect.',
      'GND':    'Ground reference (pin 12).',
      'D0':     'Digital output bit 0 (LSB).',
      'D1':     'Digital output bit 1.',
      'D2':     'Digital output bit 2.',
      'D3':     'Digital output bit 3.',
      'D4':     'Digital output bit 4.',
      'D5':     'Digital output bit 5.',
      'D6':     'Digital output bit 6.',
      'D7':     'Digital output bit 7 (MSB).',
      'EOC':    'End-Of-Conversion output.',
      'NC7':    'No connect.',
      'NC8':    'No connect.',
      'VCC':    'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: 'Integrated SAR ADC',
        paragraphs: [
          'The 74x505 packages the entire SAR ADC signal chain on a single chip. Apply VIN, assert STARTn, clock 8 cycles, and read D0-D7 when EOC asserts.',
        ],
        note: 'Logic stub analog conversion not simulated.',
      },
    ],
    pinout: [
      { pin:  1, name: 'VIN',    type: 'input' },  { pin:  2, name: 'VREF',   type: 'input' },
      { pin:  3, name: 'OEn',    type: 'input' },  { pin:  4, name: 'CLK',    type: 'input' },
      { pin:  5, name: 'STARTn', type: 'input' },  { pin:  6, name: 'NC1',    type: 'nc' },
      { pin:  7, name: 'NC2',    type: 'nc' },  { pin:  8, name: 'NC3',    type: 'nc' },
      { pin:  9, name: 'NC4',    type: 'nc' },  { pin: 10, name: 'NC5',    type: 'nc' },
      { pin: 11, name: 'NC6',    type: 'nc' },  { pin: 12, name: 'GND',    type: 'power' },
      { pin: 13, name: 'D0',     type: 'output' }, { pin: 14, name: 'D1',     type: 'output' },
      { pin: 15, name: 'D2',     type: 'output' }, { pin: 16, name: 'D3',     type: 'output' },
      { pin: 17, name: 'D4',     type: 'output' }, { pin: 18, name: 'D5',     type: 'output' },
      { pin: 19, name: 'D6',     type: 'output' }, { pin: 20, name: 'D7',     type: 'output' },
      { pin: 21, name: 'EOC',    type: 'output' }, { pin: 22, name: 'NC7',    type: 'nc' },
      { pin: 23, name: 'NC8',    type: 'nc' },  { pin: 24, name: 'VCC',    type: 'power' },
    ],
    gates: [{ type: 'ADC_8BIT_SAR',
      inputs: ['VIN','VREF','OEn','CLK','STARTn'],
      outputs: ['D0','D1','D2','D3','D4','D5','D6','D7','EOC'] }],
  },

  // ── 74508: 8 bit Multiplier, 24-pin ────────────────────────────────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits */
  '74508': {
    name: '74x508', simpleName: '8 bit Multiplier',
    description: "8 bit two's complement parallel multiplier (8x8) (24-pin)",
    pins: 24, vcc: 24, gnd: 12,
    tags: ['multiplier', '8 bit', 'arithmetic'],
    guideOverview: "The 74x508 is an 8x8 bit two's complement parallel multiplier. It multiplies signed 8 bit operands A and B combinationally, producing the lower 6 bits of the 16 bit product on P0-P5. Additional product bits require cascading. Parallel multipliers use arrays of partial product adders for maximum speed.",
    guidePinDescriptions: {
      'A0':  'Multiplicand bit 0 (LSB).',
      'A1':  'Multiplicand bit 1.',
      'A2':  'Multiplicand bit 2.',
      'A3':  'Multiplicand bit 3.',
      'A4':  'Multiplicand bit 4.',
      'A5':  'Multiplicand bit 5.',
      'A6':  'Multiplicand bit 6.',
      'A7':  'Multiplicand bit 7 (MSB / sign bit in 2s complement).',
      'B0':  'Multiplier bit 0.',
      'B1':  'Multiplier bit 1.',
      'B2':  'Multiplier bit 2.',
      'GND': 'Ground reference (pin 12).',
      'B3':  'Multiplier bit 3.',
      'B4':  'Multiplier bit 4.',
      'B5':  'Multiplier bit 5.',
      'B6':  'Multiplier bit 6.',
      'B7':  'Multiplier bit 7 (sign bit).',
      'P0':  'Product bit 0 (LSB).',
      'P1':  'Product bit 1.',
      'P2':  'Product bit 2.',
      'P3':  'Product bit 3.',
      'P4':  'Product bit 4.',
      'P5':  'Product bit 5 (MSB available on-chip).',
      'VCC': 'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: 'Parallel Multiplication',
        paragraphs: [
          "Multiplying two N-bit numbers produces a 2N-bit product. Two's complement encoding handles signed operands. The chip internally forms all partial products and sums them in a single combinational pass much faster than shift-and-add approaches.",
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'A0',  type: 'input' },  { pin:  2, name: 'A1',  type: 'input' },
      { pin:  3, name: 'A2',  type: 'input' },  { pin:  4, name: 'A3',  type: 'input' },
      { pin:  5, name: 'A4',  type: 'input' },  { pin:  6, name: 'A5',  type: 'input' },
      { pin:  7, name: 'A6',  type: 'input' },  { pin:  8, name: 'A7',  type: 'input' },
      { pin:  9, name: 'B0',  type: 'input' },  { pin: 10, name: 'B1',  type: 'input' },
      { pin: 11, name: 'B2',  type: 'input' },  { pin: 12, name: 'GND', type: 'power' },
      { pin: 13, name: 'B3',  type: 'input' },  { pin: 14, name: 'B4',  type: 'input' },
      { pin: 15, name: 'B5',  type: 'input' },  { pin: 16, name: 'B6',  type: 'input' },
      { pin: 17, name: 'B7',  type: 'input' },  { pin: 18, name: 'P0',  type: 'output' },
      { pin: 19, name: 'P1',  type: 'output' }, { pin: 20, name: 'P2',  type: 'output' },
      { pin: 21, name: 'P3',  type: 'output' }, { pin: 22, name: 'P4',  type: 'output' },
      { pin: 23, name: 'P5',  type: 'output' }, { pin: 24, name: 'VCC', type: 'power' },
    ],
    gates: [{ type: 'MULTIPLIER_8BIT',
      inputs: ['A0','A1','A2','A3','A4','A5','A6','A7','B0','B1','B2','B3','B4','B5','B6','B7'],
      outputs: ['P0','P1','P2','P3','P4','P5'] }],
  },

  // ── 74515: Programmable Mapping Decoder, 20-pin ────────────────────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Multiplexer */
  '74515': {
    name: '74x515', simpleName: 'Programmable Mapping Decoder',
    description: '2-to-4 line decoder with 9 programmable enable inputs for memory mapping (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    tags: ['decoder', 'programmable', 'address-decoder'],
    guideOverview: 'The 74x515 is a 2-to-4 decoder with nine programmable enable inputs (E0-E8), intended for memory address decoding. The nine enables allow very specific address patterns to be decoded without external glue logic. A0/A1 select one of four active LOW outputs; all nine enables must be satisfied simultaneously.',
    guidePinDescriptions: {
      'A0':  'Address input bit 0 (LSB).',
      'A1':  'Address input bit 1.',
      'E0':  'Enable input 0 (logic level determines active state).',
      'E1':  'Enable input 1.',
      'E2':  'Enable input 2.',
      'E3':  'Enable input 3.',
      'E4':  'Enable input 4.',
      'E5':  'Enable input 5.',
      'E6':  'Enable input 6.',
      'GND': 'Ground reference (pin 10).',
      'E7':  'Enable input 7.',
      'E8':  'Enable input 8.',
      'Y0n': 'Decoded output 0 (active LOW).',
      'Y1n': 'Decoded output 1 (active LOW).',
      'Y2n': 'Decoded output 2 (active LOW).',
      'Y3n': 'Decoded output 3 (active LOW).',
      'NC1': 'No connect.',
      'NC2': 'No connect.',
      'NC3': 'No connect.',
      'VCC': 'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'Programmable Address Decoder',
        paragraphs: [
          'With 9 enable inputs the 74x515 can decode from a wide address bus. Connect high address lines to E0-E8 to select a specific 4-location window in the memory map. Each Y output selects a specific chip-select region.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'A0',  type: 'input' },  { pin:  2, name: 'A1',  type: 'input' },
      { pin:  3, name: 'E0',  type: 'input' },  { pin:  4, name: 'E1',  type: 'input' },
      { pin:  5, name: 'E2',  type: 'input' },  { pin:  6, name: 'E3',  type: 'input' },
      { pin:  7, name: 'E4',  type: 'input' },  { pin:  8, name: 'E5',  type: 'input' },
      { pin:  9, name: 'E6',  type: 'input' },  { pin: 10, name: 'GND', type: 'power' },
      { pin: 11, name: 'E7',  type: 'input' },  { pin: 12, name: 'E8',  type: 'input' },
      { pin: 13, name: 'Y0n', type: 'output' }, { pin: 14, name: 'Y1n', type: 'output' },
      { pin: 15, name: 'Y2n', type: 'output' }, { pin: 16, name: 'Y3n', type: 'output' },
      { pin: 17, name: 'NC1', type: 'nc' },  { pin: 18, name: 'NC2', type: 'nc' },
      { pin: 19, name: 'NC3', type: 'nc' },  { pin: 20, name: 'VCC', type: 'power' },
    ],
    gates: [{ type: 'DECODER_PROG_2TO4',
      inputs: ['A0','A1','E0','E1','E2','E3','E4','E5','E6','E7','E8'],
      outputs: ['Y0n','Y1n','Y2n','Y3n'] }],
  },

  // ── 74516: 4x4 bit Multiplier, 24-pin ──────────────────────────────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits */
  '74516': {
    name: '74x516', simpleName: '4x4 bit Multiplier',
    description: "4x4 bit two's complement parallel multiplier (24-pin)",
    pins: 24, vcc: 24, gnd: 12,
    tags: ['multiplier', '4 bit', 'arithmetic'],
    guideOverview: "The 74x516 is a 4x4 bit two's complement parallel multiplier that produces a full 8 bit product (P0-P7). Both signed operands A (4 bit) and B (4 bit) are multiplied combinationally. The full product is available without cascading, making this chip simpler to use than wider multipliers.",
    guidePinDescriptions: {
      'A0':  'Multiplicand bit 0 (LSB).',
      'A1':  'Multiplicand bit 1.',
      'A2':  'Multiplicand bit 2.',
      'A3':  'Multiplicand bit 3 (MSB/sign).',
      'B0':  'Multiplier bit 0.',
      'B1':  'Multiplier bit 1.',
      'B2':  'Multiplier bit 2.',
      'B3':  'Multiplier bit 3 (MSB/sign).',
      'P0':  'Product bit 0 (LSB).',
      'P1':  'Product bit 1.',
      'P2':  'Product bit 2.',
      'GND': 'Ground reference (pin 12).',
      'P3':  'Product bit 3.',
      'P4':  'Product bit 4.',
      'P5':  'Product bit 5.',
      'P6':  'Product bit 6.',
      'P7':  'Product bit 7 (MSB).',
      'NC1': 'No connect.',
      'NC2': 'No connect.',
      'NC3': 'No connect.',
      'NC4': 'No connect.',
      'NC5': 'No connect.',
      'NC6': 'No connect.',
      'VCC': 'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: '4x4 Parallel Multiplier',
        paragraphs: [
          'A 4x4 multiply produces an 8 bit result. Range: -8 to +7 signed (-128 to +49 product). The chip completes the operation in a single propagation delay, no clock required.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'A0',  type: 'input' },  { pin:  2, name: 'A1',  type: 'input' },
      { pin:  3, name: 'A2',  type: 'input' },  { pin:  4, name: 'A3',  type: 'input' },
      { pin:  5, name: 'B0',  type: 'input' },  { pin:  6, name: 'B1',  type: 'input' },
      { pin:  7, name: 'B2',  type: 'input' },  { pin:  8, name: 'B3',  type: 'input' },
      { pin:  9, name: 'P0',  type: 'output' }, { pin: 10, name: 'P1',  type: 'output' },
      { pin: 11, name: 'P2',  type: 'output' }, { pin: 12, name: 'GND', type: 'power' },
      { pin: 13, name: 'P3',  type: 'output' }, { pin: 14, name: 'P4',  type: 'output' },
      { pin: 15, name: 'P5',  type: 'output' }, { pin: 16, name: 'P6',  type: 'output' },
      { pin: 17, name: 'P7',  type: 'output' }, { pin: 18, name: 'NC1', type: 'nc' },
      { pin: 19, name: 'NC2', type: 'nc' },  { pin: 20, name: 'NC3', type: 'nc' },
      { pin: 21, name: 'NC4', type: 'nc' },  { pin: 22, name: 'NC5', type: 'nc' },
      { pin: 23, name: 'NC6', type: 'nc' },  { pin: 24, name: 'VCC', type: 'power' },
    ],
    gates: [{ type: 'MULTIPLIER_16BIT',
      inputs: ['A0','A1','A2','A3','B0','B1','B2','B3'],
      outputs: ['P0','P1','P2','P3','P4','P5','P6','P7'] }],
  },

};
// end of CHIPS_BLOCK_28
