// chips69.js Block 69: CMOS 4000-series logic ICs
// Chips: CD4011, CD4012, CD4069, CD4082, CD4543
export const CHIPS_BLOCK_69 = {

  // ── CD4011: Quad 2 input NAND (14-pin) ─────────────────────────────────
  /* Primary source: Texas Instruments, CD4011 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/cd4011b.pdf */
  'CD4011': {
    name: 'CD4011',
    simpleName: 'Quad 2 Input NAND',
    description: 'Quad 2 input NAND gate CMOS 4000 series. (14-pin)',
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/cd4011b.pdf',
    tags: ['cmos', '4000 series', 'logic gate', 'NAND', 'quad'],
    guideOverview: 'The CD4011 contains four independent 2 input NAND gates. Output is LOW only when both inputs are simultaneously HIGH; if either input is LOW the output is HIGH. It is the CMOS equivalent of the 74x00 and is the universal building block of digital logic. Two cross-connected NAND gates form an SR latch; one gate with both inputs tied together works as an inverter. Supply voltage 3 15 V (some versions to 18 V).',
    guidePinDescriptions: {
      A1:  'Input A of gate 1.',
      B1:  'Input B of gate 1.',
      Q1:  'NAND output of gate 1. LOW only when A1 and B1 are both HIGH.',
      Q2:  'NAND output of gate 2. LOW only when A2 and B2 are both HIGH.',
      A2:  'Input A of gate 2.',
      B2:  'Input B of gate 2.',
      GND: 'Ground reference (VSS). Connect to 0 V.',
      A3:  'Input A of gate 3.',
      B3:  'Input B of gate 3.',
      Q3:  'NAND output of gate 3.',
      Q4:  'NAND output of gate 4.',
      A4:  'Input A of gate 4.',
      B4:  'Input B of gate 4.',
      VDD: 'Positive supply. Accepts 3 V to 15 V (some versions to 18 V).',
    },
    pinout: [
      { pin:  1, name: 'A1',  type: 'input',  description: 'Gate 1 input A' },
      { pin:  2, name: 'B1',  type: 'input',  description: 'Gate 1 input B' },
      { pin:  3, name: 'Q1',  type: 'output', description: 'Gate 1 NAND output: LOW only when A1 and B1 are both HIGH' },
      { pin:  4, name: 'Q2',  type: 'output', description: 'Gate 2 NAND output: LOW only when A2 and B2 are both HIGH' },
      { pin:  5, name: 'A2',  type: 'input',  description: 'Gate 2 input A' },
      { pin:  6, name: 'B2',  type: 'input',  description: 'Gate 2 input B' },
      { pin:  7, name: 'GND', type: 'power',  description: 'Ground (0 V)' },
      { pin:  8, name: 'A3',  type: 'input',  description: 'Gate 3 input A' },
      { pin:  9, name: 'B3',  type: 'input',  description: 'Gate 3 input B' },
      { pin: 10, name: 'Q3',  type: 'output', description: 'Gate 3 NAND output' },
      { pin: 11, name: 'Q4',  type: 'output', description: 'Gate 4 NAND output' },
      { pin: 12, name: 'A4',  type: 'input',  description: 'Gate 4 input A' },
      { pin: 13, name: 'B4',  type: 'input',  description: 'Gate 4 input B' },
      { pin: 14, name: 'VDD', type: 'power',  description: 'Positive supply (3 15 V)' },
    ],
    gates: [
      { type: 'NAND', inputs: ['A1','B1'], output: 'Q1' },
      { type: 'NAND', inputs: ['A2','B2'], output: 'Q2' },
      { type: 'NAND', inputs: ['A3','B3'], output: 'Q3' },
      { type: 'NAND', inputs: ['A4','B4'], output: 'Q4' },
    ],
    guideSections: [
      {
        title: 'NAND Logic and Universal Gate',
        paragraphs: [
          'A NAND gate outputs LOW only when all inputs are HIGH simultaneously. One LOW input is enough to force the output HIGH, making NAND the complement of AND.',
          'NAND is a universal gate: any logic function can be built from NAND gates alone. Tie both inputs of one gate together to get an inverter; cross-connect two NAND gates (Q1→B2, Q2→B1) to form an SR latch.',
          'CMOS inputs draw essentially no static current but unused inputs must be tied HIGH or LOW, never left floating.',
        ],
        list: [
          'SR latch: connect Q1 back to B2 and Q2 back to B1 for bistable memory.',
          'Inverter: tie both inputs of any gate together.',
          'Enable gate: one input as enable (LOW disables), other as data.',
        ],
        note: 'The CD4093 is a pin-compatible version with Schmitt-trigger inputs for use with noisy or slowly changing signals.',
      },
    ],
  },

  // ── CD4012: Dual 4 input NAND (14-pin) ─────────────────────────────────
  /* Primary source: Texas Instruments, CD4012 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/cd4012b.pdf */
  'CD4012': {
    name: 'CD4012',
    simpleName: 'Dual 4 Input NAND',
    description: 'Dual 4 input NAND gate CMOS 4000 series. (14-pin)',
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/cd4012b.pdf',
    tags: ['cmos', '4000 series', 'logic gate', 'NAND', 'dual', '4 input'],
    guideOverview: 'The CD4012 contains two independent 4 input NAND gates. Output is LOW only when all four inputs are simultaneously HIGH; any single LOW input forces the output HIGH. Pins 6 and 8 are no-connect. The chip provides the function of four cascaded AND gates in a single package. Supply voltage 3 15 V.',
    guidePinDescriptions: {
      '1Y':  'Output of gate 1. LOW only when 1A, 1B, 1C, and 1D are all HIGH.',
      '1A':  'Input A of gate 1.',
      '1B':  'Input B of gate 1.',
      '1C':  'Input C of gate 1.',
      '1D':  'Input D of gate 1.',
      'NC':  'No internal connection. Leave unconnected.',
      'GND': 'Ground reference (VSS). Connect to 0 V.',
      'NC2': 'No internal connection. Leave unconnected.',
      '2D':  'Input D of gate 2.',
      '2C':  'Input C of gate 2.',
      '2B':  'Input B of gate 2.',
      '2A':  'Input A of gate 2.',
      '2Y':  'Output of gate 2. LOW only when 2A, 2B, 2C, and 2D are all HIGH.',
      'VDD': 'Positive supply. Accepts 3 V to 15 V.',
    },
    pinout: [
      { pin:  1, name: '1Y',  type: 'output', description: 'Gate 1 NAND output: LOW when all inputs HIGH' },
      { pin:  2, name: '1A',  type: 'input',  description: 'Gate 1 input A' },
      { pin:  3, name: '1B',  type: 'input',  description: 'Gate 1 input B' },
      { pin:  4, name: '1C',  type: 'input',  description: 'Gate 1 input C' },
      { pin:  5, name: '1D',  type: 'input',  description: 'Gate 1 input D' },
      { pin:  6, name: 'NC',  type: 'nc',     description: 'No connection' },
      { pin:  7, name: 'GND', type: 'power',  description: 'Ground (0 V)' },
      { pin:  8, name: 'NC2', type: 'nc',     description: 'No connection' },
      { pin:  9, name: '2D',  type: 'input',  description: 'Gate 2 input D' },
      { pin: 10, name: '2C',  type: 'input',  description: 'Gate 2 input C' },
      { pin: 11, name: '2B',  type: 'input',  description: 'Gate 2 input B' },
      { pin: 12, name: '2A',  type: 'input',  description: 'Gate 2 input A' },
      { pin: 13, name: '2Y',  type: 'output', description: 'Gate 2 NAND output: LOW when all inputs HIGH' },
      { pin: 14, name: 'VDD', type: 'power',  description: 'Positive supply (3 15 V)' },
    ],
    gates: [
      { type: 'NAND', inputs: ['1A','1B','1C','1D'], output: '1Y' },
      { type: 'NAND', inputs: ['2A','2B','2C','2D'], output: '2Y' },
    ],
    guideSections: [
      {
        title: 'Logic Function',
        paragraphs: [
          'NAND logic: output is LOW only when every input is simultaneously HIGH. One LOW input is sufficient to hold the output HIGH.',
          'The 4 input version allows combining more conditions in a single gate, reducing chip count compared to cascading 2 input NAND gates.',
        ],
        formulas: [
          'Y = NOT(A · B · C · D)',
        ],
      },
      {
        title: 'Typical Uses',
        list: [
          'Detect when all four conditions are true (all inputs HIGH)   output goes LOW as an active LOW flag.',
          'Enable control: any one of four inputs can block the output (keep it HIGH) by going LOW.',
          'Reduce gate count versus cascading two 2-input NAND gates for a 4-input function.',
        ],
        note: 'Pins 6 and 8 are no-connect; do not route signals through them.',
      },
    ],
  },

  // ── CD4069: Hex inverter (14-pin) ──────────────────────────────────────
  /* Primary source: Texas Instruments, CD4069 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/cd4069ub.pdf */
  'CD4069': {
    name: 'CD4069',
    simpleName: 'Hex Inverter',
    description: 'Six unbuffered CMOS inverters. (14-pin)',
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/cd4069ub.pdf',
    tags: ['cmos', '4000 series', 'logic gate', 'NOT', 'inverter', 'hex inverter'],
    guideOverview: 'The CD4069 contains six independent unbuffered CMOS inverter gates. Each gate outputs the complement of its input: HIGH when input is LOW, LOW when input is HIGH. Unlike the CD4049 or CD40106, the CD4069UB is unbuffered, meaning its output is a single CMOS inverting stage. This gives a more linear voltage transfer characteristic, making it useful as a linear amplifier in oscillator and analog signal-conditioning circuits. Supply voltage 3 15 V.',
    guidePinDescriptions: {
      A:   'Input of inverter 1.',
      YA:  'Output of inverter 1. HIGH when A is LOW.',
      B:   'Input of inverter 2.',
      YB:  'Output of inverter 2. HIGH when B is LOW.',
      C:   'Input of inverter 3.',
      YC:  'Output of inverter 3. HIGH when C is LOW.',
      GND: 'Ground reference (VSS). Connect to 0 V.',
      YD:  'Output of inverter 4. HIGH when D is LOW.',
      D:   'Input of inverter 4.',
      YE:  'Output of inverter 5. HIGH when E is LOW.',
      E:   'Input of inverter 5.',
      YF:  'Output of inverter 6. HIGH when F is LOW.',
      F:   'Input of inverter 6.',
      VDD: 'Positive supply. Accepts 3 V to 15 V.',
    },
    pinout: [
      { pin:  1, name: 'A',   type: 'input',  description: 'Inverter 1 input' },
      { pin:  2, name: 'YA',  type: 'output', description: 'Inverter 1 output (inverted)' },
      { pin:  3, name: 'B',   type: 'input',  description: 'Inverter 2 input' },
      { pin:  4, name: 'YB',  type: 'output', description: 'Inverter 2 output' },
      { pin:  5, name: 'C',   type: 'input',  description: 'Inverter 3 input' },
      { pin:  6, name: 'YC',  type: 'output', description: 'Inverter 3 output' },
      { pin:  7, name: 'GND', type: 'power',  description: 'Ground (0 V)' },
      { pin:  8, name: 'YD',  type: 'output', description: 'Inverter 4 output' },
      { pin:  9, name: 'D',   type: 'input',  description: 'Inverter 4 input' },
      { pin: 10, name: 'YE',  type: 'output', description: 'Inverter 5 output' },
      { pin: 11, name: 'E',   type: 'input',  description: 'Inverter 5 input' },
      { pin: 12, name: 'YF',  type: 'output', description: 'Inverter 6 output' },
      { pin: 13, name: 'F',   type: 'input',  description: 'Inverter 6 input' },
      { pin: 14, name: 'VDD', type: 'power',  description: 'Positive supply (3 15 V)' },
    ],
    gates: [
      { type: 'NOT', inputs: ['A'], output: 'YA' },
      { type: 'NOT', inputs: ['B'], output: 'YB' },
      { type: 'NOT', inputs: ['C'], output: 'YC' },
      { type: 'NOT', inputs: ['D'], output: 'YD' },
      { type: 'NOT', inputs: ['E'], output: 'YE' },
      { type: 'NOT', inputs: ['F'], output: 'YF' },
    ],
    guideSections: [
      {
        title: 'Inverter Basics',
        paragraphs: [
          'Each gate inverts its input: a HIGH becomes LOW and a LOW becomes HIGH. Six separate gates on one package allow independent signal inversion on six channels.',
          'The CD4069UB is unbuffered, providing a more analog-like voltage transfer curve than the buffered CD40106. This makes it suitable for biasing into the linear region as a simple CMOS amplifier or crystal oscillator driver.',
          'For digital-only use where hysteresis and noise immunity are important, prefer the CD40106 (Schmitt-trigger version) instead.',
        ],
        list: [
          'Signal inversion: complement any logic signal.',
          'Ring oscillator: chain an odd number of gates in a loop for a raw oscillation (frequency depends on gate propagation delay).',
          'Linear amplifier/oscillator: bias input near the switching threshold using a feedback resistor.',
        ],
        note: '74Sim models each gate as a digital inverter. Analog biasing and linear amplifier behavior are not simulated.',
      },
    ],
  },

  // ── CD4082: Dual 4 input AND (14-pin) ──────────────────────────────────
  /* Primary source: Texas Instruments, CD4082 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/cd4082b.pdf */
  'CD4082': {
    name: 'CD4082',
    simpleName: 'Dual 4 Input AND',
    description: 'Dual 4 input AND gate CMOS 4000 series. (14-pin)',
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/cd4082b.pdf',
    tags: ['cmos', '4000 series', 'logic gate', 'AND', 'dual', '4 input'],
    guideOverview: 'The CD4082 contains two independent 4 input AND gates. Output is HIGH only when all four inputs are simultaneously HIGH; any single LOW input forces the output LOW. Pins 6 and 8 are no-connect. It is the 4 input AND counterpart to the CD4012 NAND. Supply voltage 3 15 V.',
    guidePinDescriptions: {
      '1Y':  'Output of gate 1. HIGH only when 1A, 1B, 1C, and 1D are all HIGH.',
      '1A':  'Input A of gate 1.',
      '1B':  'Input B of gate 1.',
      '1C':  'Input C of gate 1.',
      '1D':  'Input D of gate 1.',
      'NC':  'No internal connection. Leave unconnected.',
      'GND': 'Ground reference (VSS). Connect to 0 V.',
      'NC2': 'No internal connection. Leave unconnected.',
      '2D':  'Input D of gate 2.',
      '2C':  'Input C of gate 2.',
      '2B':  'Input B of gate 2.',
      '2A':  'Input A of gate 2.',
      '2Y':  'Output of gate 2. HIGH only when 2A, 2B, 2C, and 2D are all HIGH.',
      'VDD': 'Positive supply. Accepts 3 V to 15 V.',
    },
    pinout: [
      { pin:  1, name: '1Y',  type: 'output', description: 'Gate 1 AND output: HIGH when all inputs HIGH' },
      { pin:  2, name: '1A',  type: 'input',  description: 'Gate 1 input A' },
      { pin:  3, name: '1B',  type: 'input',  description: 'Gate 1 input B' },
      { pin:  4, name: '1C',  type: 'input',  description: 'Gate 1 input C' },
      { pin:  5, name: '1D',  type: 'input',  description: 'Gate 1 input D' },
      { pin:  6, name: 'NC',  type: 'nc',     description: 'No connection' },
      { pin:  7, name: 'GND', type: 'power',  description: 'Ground (0 V)' },
      { pin:  8, name: 'NC2', type: 'nc',     description: 'No connection' },
      { pin:  9, name: '2D',  type: 'input',  description: 'Gate 2 input D' },
      { pin: 10, name: '2C',  type: 'input',  description: 'Gate 2 input C' },
      { pin: 11, name: '2B',  type: 'input',  description: 'Gate 2 input B' },
      { pin: 12, name: '2A',  type: 'input',  description: 'Gate 2 input A' },
      { pin: 13, name: '2Y',  type: 'output', description: 'Gate 2 AND output: HIGH when all inputs HIGH' },
      { pin: 14, name: 'VDD', type: 'power',  description: 'Positive supply (3 15 V)' },
    ],
    gates: [
      { type: 'AND', inputs: ['1A','1B','1C','1D'], output: '1Y' },
      { type: 'AND', inputs: ['2A','2B','2C','2D'], output: '2Y' },
    ],
    guideSections: [
      {
        title: 'Logic Function',
        paragraphs: [
          'AND logic: output is HIGH only when every input is simultaneously HIGH. One LOW input immediately forces the output LOW.',
          'The 4 input version lets you gate a signal with three enable conditions simultaneously, or combine four parallel sensor inputs into a single all-conditions-met flag.',
        ],
        formulas: [
          'Y = A · B · C · D',
        ],
      },
      {
        title: 'Typical Uses',
        list: [
          'All-or-nothing enable: output is HIGH only when all four enabling conditions are met.',
          'Multi-input coincidence detector: output goes HIGH only when all four inputs agree.',
          'Reduce chip count versus cascading two 2-input AND gates for a 4-input function.',
        ],
        note: 'Pins 6 and 8 are no-connect; do not route signals through them.',
      },
    ],
  },

  // ── CD4543: BCD to 7-segment latch/decoder/driver (16-pin) ─────────────
  /* Primary source: Texas Instruments, CD4543 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/cd4543b.pdf
     https://en.wikipedia.org/wiki/Flip-flop_(electronics) */
  'CD4543': {
    name: 'CD4543',
    simpleName: 'BCD to 7-Segment Decoder/Driver (CA/CC)',
    description: 'BCD to 7-segment latch/decoder/driver for common-anode or common-cathode displays CMOS 4000 series. (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    sequential: true,
    datasheet: 'https://www.ti.com/lit/ds/symlink/cd4543b.pdf',
    tags: ['cmos', '4000 series', 'decoder', '7-segment', 'BCD decoder', 'display driver', 'latch', 'LCD', 'common anode', 'common cathode'],
    guideOverview: 'The CD4543 converts a 4 bit BCD input (A D) into seven segment drive signals (a g) for either common-cathode or common-anode 7-segment LED/LCD displays. The Ph (Phase) pin selects output polarity: Ph=LOW gives active HIGH outputs for common-cathode displays; Ph=HIGH inverts all outputs for common-anode displays. A transparent latch (LE) holds the displayed digit when HIGH. BL (active HIGH) blanks all segments. BCD values 10 15 produce a blank output. Unlike the CD4511, there is no lamp-test pin, and blanking is active HIGH.',
    guidePinDescriptions: {
      Ph:  'Phase / polarity select. LOW = active HIGH outputs (common cathode). HIGH = active LOW outputs (common anode).',
      D:   'BCD input bit 3 (weight 8, MSB).',
      A:   'BCD input bit 0 (weight 1, LSB).',
      B:   'BCD input bit 1 (weight 2).',
      C:   'BCD input bit 2 (weight 4).',
      BL:  'Blanking input. Active HIGH: all segments OFF when HIGH. Set LOW for normal operation.',
      LE:  'Latch Enable. Transparent when LOW: segment outputs follow BCD inputs in real time. When HIGH: latches the current BCD value so the display holds even if inputs change.',
      GND: 'Ground (0 V). Connect to negative supply rail.',
      f:   'Segment f output (upper left vertical bar).',
      g:   'Segment g output (middle horizontal bar).',
      a:   'Segment a output (top horizontal bar).',
      b:   'Segment b output (upper right vertical bar).',
      c:   'Segment c output (lower right vertical bar).',
      d:   'Segment d output (bottom horizontal bar).',
      e:   'Segment e output (lower left vertical bar).',
      VDD: 'Positive supply. Accepts 3 V to 15 V.',
    },
    pinout: [
      { pin:  1, name: 'Ph',  type: 'input',  description: 'Phase select: LOW=active HIGH (CC), HIGH=active LOW (CA)' },
      { pin:  2, name: 'D',   type: 'input',  description: 'BCD input bit 3 (weight 8)' },
      { pin:  3, name: 'A',   type: 'input',  description: 'BCD input bit 0 (weight 1)' },
      { pin:  4, name: 'B',   type: 'input',  description: 'BCD input bit 1 (weight 2)' },
      { pin:  5, name: 'C',   type: 'input',  description: 'BCD input bit 2 (weight 4)' },
      { pin:  6, name: 'BL',  type: 'input',  description: 'Blanking (active HIGH)' },
      { pin:  7, name: 'LE',  type: 'input',  description: 'Latch Enable (HIGH=latch)' },
      { pin:  8, name: 'GND', type: 'power',  description: 'Ground (0 V)' },
      { pin:  9, name: 'f',   type: 'output', description: 'Segment f (upper left vertical)' },
      { pin: 10, name: 'g',   type: 'output', description: 'Segment g (middle horizontal)' },
      { pin: 11, name: 'a',   type: 'output', description: 'Segment a (top horizontal)' },
      { pin: 12, name: 'b',   type: 'output', description: 'Segment b (upper right vertical)' },
      { pin: 13, name: 'c',   type: 'output', description: 'Segment c (lower right vertical)' },
      { pin: 14, name: 'd',   type: 'output', description: 'Segment d (bottom horizontal)' },
      { pin: 15, name: 'e',   type: 'output', description: 'Segment e (lower left vertical)' },
      { pin: 16, name: 'VDD', type: 'power',  description: 'Positive supply (3 15 V)' },
    ],
    gates: [
      { type: 'BCD_7SEG_4543', inputs: ['A','B','C','D','LE','BL','Ph'], outputs: ['a','b','c','d','e','f','g'] },
    ],
    guideSections: [
      {
        title: 'BCD to 7-Segment Decoding',
        paragraphs: [
          'In transparent mode (LE=LOW), segment outputs track the BCD input in real time. When LE goes HIGH the current digit is latched and held, even if A D change. This is useful for freezing a displayed value during a calculation or input update cycle.',
          'BL=HIGH blanks all segments regardless of BCD input. BCD values 10 15 (invalid) also produce a blank display.',
          'The Ph pin makes this chip work with either display type without external inverters: Ph=LOW drives common-cathode displays (active HIGH segment outputs), Ph=HIGH drives common-anode displays (active LOW outputs).',
        ],
        list: [
          'Common-cathode display: connect Ph to GND. Segment outputs drive LED anodes directly through current-limiting resistors.',
          'Common-anode display: connect Ph to VDD. Segment outputs drive LED cathodes (active LOW).',
          'Latch mode: toggle LE HIGH to hold the displayed digit while BCD input changes, then return LE LOW to update.',
          'Blanking: drive BL HIGH to turn off the display (e.g., suppress leading zeros).',
        ],
        note: 'Unlike the CD4511, the CD4543 has no lamp-test pin. Blanking is active HIGH (HIGH=blank), the opposite polarity from the CD4511 BL/BIn pin.',
      },
    ],
  },

};
