// Chip definitions block 57
// Chips: 74x3893, 74x4002, 74x4015, 74x4016, 74x4017, 74x4020, 74x4022,
//        74x4024, 74x4028, 74x4040, 74x4046, 74x4049, 74x4050, 74x4051,
//        74x4052, 74x4053

export const CHIPS_BLOCK_57 = {

  // 74x3893: Quad Futurebus backplane transceiver, TS+OC (20-pin)
  // MC74F3893A complex transceiver with both TS drivers and OC outputs; treat as GENERIC_STUB
  '74x3893': {
    name: '74x3893',
    simpleName: 'Quad Futurebus Backplane Transceiver',
    description: 'Quad Futurebus backplane transceiver with three-state and open-collector outputs (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: '',
    tags: ['transceiver', 'futurebus', 'backplane', 'quad', 'stub'],
    pinout: [
      { pin:  1, name: 'DIR',  type: 'input'  },
      { pin:  2, name: 'OEn',  type: 'input'  },
      { pin:  3, name: 'A1',   type: 'bidir'  },
      { pin:  4, name: 'B1',   type: 'bidir'  },
      { pin:  5, name: 'A2',   type: 'bidir'  },
      { pin:  6, name: 'B2',   type: 'bidir'  },
      { pin:  7, name: 'A3',   type: 'bidir'  },
      { pin:  8, name: 'B3',   type: 'bidir'  },
      { pin:  9, name: 'A4',   type: 'bidir'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'B4',   type: 'bidir'  },
      { pin: 12, name: 'LE',   type: 'input'  },
      { pin: 13, name: 'CEn',  type: 'input'  },
      { pin: 14, name: 'NC',   type: 'nc'     },
      { pin: 15, name: 'NC2',  type: 'nc'     },
      { pin: 16, name: 'NC3',  type: 'nc'     },
      { pin: 17, name: 'NC4',  type: 'nc'     },
      { pin: 18, name: 'NC5',  type: 'nc'     },
      { pin: 19, name: 'NC6',  type: 'nc'     },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['DIR','OEn','LE','CEn'], outputs: [] },
    ],
  },

  // 74x4002: Dual 4 input NOR gate (14-pin)
  // CD74x4002 two independent 4 input NOR gates
  '74x4002': {
    name: '74x4002',
    simpleName: 'Dual 4 Input NOR Gate',
    description: 'Dual 4 input NOR gate (14-pin)',
    pins: 14, vcc: 14, gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/cd74hc4002.pdf',
    tags: ['NOR', 'dual', '4 input', 'gate'],
    guideOverview: 'The 74x4002 contains two independent 4 input NOR gates. A NOR gate outputs HIGH only when all of its inputs are LOW, so it is effectively an OR gate followed by inversion. Four-input NOR gates are handy when several conditions must all be false before an output can turn on, or when you need to combine many signals without building a tree of smaller gates.',
    guidePinDescriptions: {
      '1Y': 'Output of gate 1. It goes HIGH only when 1A, 1B, 1C, and 1D are all LOW.',
      '1A': 'Input A of gate 1.',
      '1B': 'Input B of gate 1.',
      '1C': 'Input C of gate 1.',
      '1D': 'Input D of gate 1.',
      'NC': 'No internal connection. Leave unconnected.',
      'GND': 'Ground reference for the package.',
      'NC2': 'No internal connection. Leave unconnected.',
      '2D': 'Input D of gate 2.',
      '2C': 'Input C of gate 2.',
      '2B': 'Input B of gate 2.',
      '2A': 'Input A of gate 2.',
      '2Y': 'Output of gate 2. It goes HIGH only when all four inputs of gate 2 are LOW.',
      'VCC': 'Positive supply for the logic gates.',
    },
    guideSections: [
      {
        title: 'Logic Function',
        paragraphs: [
          'A NOR gate is the inverse of OR. If any input is HIGH, the output goes LOW. Only the all-LOW input condition produces a HIGH output.',
        ],
        formulas: [
          'Y = not (A + B + C + D)',
        ],
      },
      {
        title: 'Common Uses',
        list: [
          'Combining several active HIGH conditions into one active LOW result.',
          'Building simple state-detect or inhibit logic.',
          'Implementing other logic functions through De Morgan transformations.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: '1Y',  type: 'output' },
      { pin:  2, name: '1A',  type: 'input'  },
      { pin:  3, name: '1B',  type: 'input'  },
      { pin:  4, name: '1C',  type: 'input'  },
      { pin:  5, name: '1D',  type: 'input'  },
      { pin:  6, name: 'NC',  type: 'nc'     },
      { pin:  7, name: 'GND', type: 'power'  },
      { pin:  8, name: 'NC2', type: 'nc'     },
      { pin:  9, name: '2D',  type: 'input'  },
      { pin: 10, name: '2C',  type: 'input'  },
      { pin: 11, name: '2B',  type: 'input'  },
      { pin: 12, name: '2A',  type: 'input'  },
      { pin: 13, name: '2Y',  type: 'output' },
      { pin: 14, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'NOR', inputs: ['1A','1B','1C','1D'], output: '1Y' },
      { type: 'NOR', inputs: ['2A','2B','2C','2D'], output: '2Y' },
    ],
  },

  // 74x4015: Dual 4 bit serial-in/parallel-out shift register (16-pin)
  // CD74x4015 two independent 4-stage shift registers; no common clock/reset
  '74x4015': {
    name: '74x4015',
    simpleName: 'Dual 4 bit Serial-In/Parallel-Out Shift Register',
    description: 'Dual 4 bit serial-in / parallel-out shift register (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/cd74hc4015.pdf',
    tags: ['shift-register', 'dual', '4 bit', 'serial-in', 'parallel-out', 'stub'],
    guideOverview: 'The 74x4015 contains two separate 4 bit serial-in, parallel-out shift registers. Each section accepts one data bit at a time on its serial input and shifts the stored bits along one stage for each clock pulse. It is useful for serial-to-parallel conversion, simple delay lines, and stepping patterns through a small set of outputs.',
    guidePinDescriptions: {
      'CLK2': 'Clock for shift-register section 2. Each active clock edge shifts a new bit in on D2.',
      'D2': 'Serial data input for section 2.',
      'Q20': 'Stage 0 output of section 2.',
      'Q21': 'Stage 1 output of section 2.',
      'Q22': 'Stage 2 output of section 2.',
      'Q23': 'Stage 3 output of section 2.',
      'NC': 'No internal connection. Leave unconnected.',
      'GND': 'Ground reference for the device.',
      'Q13': 'Stage 3 output of section 1.',
      'Q12': 'Stage 2 output of section 1.',
      'Q11': 'Stage 1 output of section 1.',
      'Q10': 'Stage 0 output of section 1.',
      'D1': 'Serial data input for section 1.',
      'CLK1': 'Clock for shift-register section 1.',
      'NC2': 'No internal connection. Leave unconnected.',
      'VCC': 'Positive supply for the shift registers.',
    },
    guideSections: [
      {
        title: 'How Shifting Works',
        paragraphs: [
          'On each clock pulse, the new serial input bit enters the first stage and the old contents move one stage farther down the register. After several clocks, the sequence of bits becomes available on the parallel Q outputs.',
        ],
      },
      {
        title: 'Two Independent Registers',
        paragraphs: [
          'The two 4 bit sections do not have to run together. Each has its own clock and data input, so they can be used for unrelated tasks or cascaded into a longer shift path.',
        ],
        note: 'This entry remains a documented stub in the simulator rather than a full serial state machine implementation.',
      },
    ],
    pinout: [
      { pin:  1, name: 'CLK2', type: 'input'  },
      { pin:  2, name: 'D2',   type: 'input'  },
      { pin:  3, name: 'Q20',  type: 'output' },
      { pin:  4, name: 'Q21',  type: 'output' },
      { pin:  5, name: 'Q22',  type: 'output' },
      { pin:  6, name: 'Q23',  type: 'output' },
      { pin:  7, name: 'NC',   type: 'nc'     },
      { pin:  8, name: 'GND',  type: 'power'  },
      { pin:  9, name: 'Q13',  type: 'output' },
      { pin: 10, name: 'Q12',  type: 'output' },
      { pin: 11, name: 'Q11',  type: 'output' },
      { pin: 12, name: 'Q10',  type: 'output' },
      { pin: 13, name: 'D1',   type: 'input'  },
      { pin: 14, name: 'CLK1', type: 'input'  },
      { pin: 15, name: 'NC2',  type: 'nc'     },
      { pin: 16, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['CLK1','D1','CLK2','D2'], outputs: [] },
    ],
  },

  // 74x4016: Quad bilateral switch, analog (14-pin)
  // CD74x4016 four independent SPST analog switches; each has two I/O pins and a control input
  '74x4016': {
    name: '74x4016',
    simpleName: 'Quad Bilateral Analog Switch',
    description: 'Quad bilateral switch with analog signal capability (14-pin)',
    pins: 14, vcc: 14, gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/cd74hc4016.pdf',
    tags: ['analog', 'switch', 'bilateral', 'quad', 'bidir', 'stub'],
    guideOverview: 'The 74x4016 contains four independent bilateral analog switches. Each channel behaves like an electronically controlled SPST switch, so it can pass signals in either direction when enabled and isolate them when disabled. This makes it useful for routing analog signals, gating digital lines, or building simple multiplexing functions without directional buffers.',
    guidePinDescriptions: {
      'A1': 'One side of switch channel 1.',
      'B1': 'Other side of switch channel 1.',
      'E1': 'Control input for channel 1. In the 4016 family, a HIGH control level usually closes the switch.',
      'E2': 'Control input for channel 2.',
      'B2': 'Other side of switch channel 2.',
      'A2': 'One side of switch channel 2.',
      'GND': 'Ground reference for the package.',
      'A3': 'One side of switch channel 3.',
      'B3': 'Other side of switch channel 3.',
      'E3': 'Control input for channel 3.',
      'E4': 'Control input for channel 4.',
      'B4': 'Other side of switch channel 4.',
      'A4': 'One side of switch channel 4.',
      'VCC': 'Positive supply for the control circuitry.',
    },
    guideSections: [
      {
        title: 'Bilateral Analog Switching',
        paragraphs: [
          'Because each switch channel is bilateral, the chip does not care which side is the source and which side is the destination. That is different from a buffer, which has a fixed input side and output side.',
        ],
      },
      {
        title: 'Where It Is Useful',
        list: [
          'Selecting among analog sensor signals.',
          'Connecting or disconnecting audio or control lines.',
          'Making simple digitally controlled routing networks.',
        ],
        note: 'This simulator entry documents the switch concept, but it does not model detailed analog resistance or distortion.',
      },
    ],
    pinout: [
      { pin:  1, name: 'A1',  type: 'bidir'  },
      { pin:  2, name: 'B1',  type: 'bidir'  },
      { pin:  3, name: 'E1',  type: 'input'  },
      { pin:  4, name: 'E2',  type: 'input'  },
      { pin:  5, name: 'B2',  type: 'bidir'  },
      { pin:  6, name: 'A2',  type: 'bidir'  },
      { pin:  7, name: 'GND', type: 'power'  },
      { pin:  8, name: 'A3',  type: 'bidir'  },
      { pin:  9, name: 'B3',  type: 'bidir'  },
      { pin: 10, name: 'E3',  type: 'input'  },
      { pin: 11, name: 'E4',  type: 'input'  },
      { pin: 12, name: 'B4',  type: 'bidir'  },
      { pin: 13, name: 'A4',  type: 'bidir'  },
      { pin: 14, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['E1','E2','E3','E4'], outputs: [] },
    ],
  },

  // 74x4017: 5-stage ÷10 Johnson decade counter (16-pin)
  // CD74x4017 10 decoded outputs (Q0-Q9), ripple-carry out, clock, clock-enable, controller reset
  '74x4017': {
    name: '74x4017',
    simpleName: '5-Stage Divide-by-10 Johnson Counter',
    description: '5-stage divide-by-10 Johnson decade counter with 10 decoded outputs (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/cd74hc4017.pdf',
    tags: ['counter', 'johnson', 'decade', 'divide-by-10', 'stub'],
    guideOverview: 'The 74x4017 is a Johnson decade counter with ten decoded outputs. Instead of presenting a binary count, it turns on one output at a time in sequence, making it very popular for LED chasers, step sequencing, and divide-by-10 timing. It is easy to use on a breadboard because the decoded outputs eliminate the need for a separate binary-to-decimal decoder.',
    guidePinDescriptions: {
      'Q5': 'Decoded output 5. Goes HIGH during count state 5.',
      'Q1': 'Decoded output 1. Goes HIGH during count state 1.',
      'Q0': 'Decoded output 0. This is the first active output after reset.',
      'Q2': 'Decoded output 2. Goes HIGH during count state 2.',
      'Q6': 'Decoded output 6. Goes HIGH during count state 6.',
      'Q7': 'Decoded output 7. Goes HIGH during count state 7.',
      'Q3': 'Decoded output 3. Goes HIGH during count state 3.',
      'GND': 'Ground reference for the counter.',
      'Q8': 'Decoded output 8. Goes HIGH during count state 8.',
      'Q4': 'Decoded output 4. Goes HIGH during count state 4.',
      'Q9': 'Decoded output 9. Goes HIGH during count state 9.',
      'COUT': 'Carry output used for cascading multiple counters or divide-by logic.',
      'CLKEn': 'Clock enable (active LOW). Pull LOW to allow clock pulses; hold HIGH to freeze the sequence.',
      'CLK': 'Clock input. Each valid clock edge advances the active output to the next decoded state.',
      'MR': 'Master reset. Assert HIGH to reset the counter to state 0.',
      'VCC': 'Positive supply for the device.',
    },
    guideSections: [
      {
        title: 'Decoded Counting',
        paragraphs: [
          'Only one Q output is active at a time. Each clock pulse moves that active state to the next output, so the chip directly produces a one-of-ten sequence.',
        ],
      },
      {
        title: 'Why Johnson Counters Are Handy',
        paragraphs: [
          'A Johnson counter saves logic because the decoding is built in. That makes it a convenient building block for step sequencers, scanners, and simple time-base division.',
        ],
        note: 'This entry is documented as a stub rather than a full sequential simulation model.',
      },
    ],
    pinout: [
      { pin:  1, name: 'Q5',    type: 'output' },
      { pin:  2, name: 'Q1',    type: 'output' },
      { pin:  3, name: 'Q0',    type: 'output' },
      { pin:  4, name: 'Q2',    type: 'output' },
      { pin:  5, name: 'Q6',    type: 'output' },
      { pin:  6, name: 'Q7',    type: 'output' },
      { pin:  7, name: 'Q3',    type: 'output' },
      { pin:  8, name: 'GND',   type: 'power'  },
      { pin:  9, name: 'Q8',    type: 'output' },
      { pin: 10, name: 'Q4',    type: 'output' },
      { pin: 11, name: 'Q9',    type: 'output' },
      { pin: 12, name: 'COUT',  type: 'output' },
      { pin: 13, name: 'CLKEn', type: 'input'  },
      { pin: 14, name: 'CLK',   type: 'input'  },
      { pin: 15, name: 'MR',    type: 'input'  },
      { pin: 16, name: 'VCC',   type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['CLK','CLKEn','MR'], outputs: [] },
    ],
  },

  // 74x4020: 14-stage binary ripple counter (16-pin)
  // SN74x4020 14 flip-flop chain; not all Q outputs brought out; Q2/Q3 not accessible
  '74x4020': {
    name: '74x4020',
    simpleName: '14-Stage Binary Ripple Counter',
    description: '14-stage binary ripple counter (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74hc4020.pdf',
    tags: ['counter', 'binary', '14-stage', 'ripple', 'stub'],
    guideOverview: 'The 74x4020 is a long binary ripple counter that divides an incoming clock by powers of two. Each successive output toggles at half the rate of the previous stage, so one chip can generate many slower timing signals from one faster source. It is useful for frequency division, long delays, and simple timing chains.',
    guidePinDescriptions: {
      'Q12': 'Higher-order counter output. It toggles at a much lower frequency than the input clock.',
      'Q6': 'Counter output stage 6.',
      'Q5': 'Counter output stage 5.',
      'Q7': 'Counter output stage 7.',
      'Q4': 'Counter output stage 4.',
      'Q3': 'Counter output stage 3.',
      'Q2': 'Counter output stage 2.',
      'GND': 'Ground reference for the counter.',
      'Q1': 'Counter output stage 1, one of the faster divided outputs.',
      'MR': 'Master reset. Assert it to clear the counter back to zero.',
      'CLK': 'Clock input for the ripple counter chain.',
      'Q11': 'Counter output stage 11.',
      'Q10': 'Counter output stage 10.',
      'Q9': 'Counter output stage 9.',
      'Q8': 'Counter output stage 8.',
      'VCC': 'Positive supply for the chip.',
    },
    guideSections: [
      {
        title: 'Ripple Counting and Division',
        paragraphs: [
          'A ripple counter is built from cascaded flip-flops. Each stage divides the frequency of the previous stage by 2, so the outputs naturally provide many divided clock rates.',
        ],
        formulas: [
          'Qn frequency = clock frequency / 2^n',
        ],
      },
      {
        title: 'Common Uses',
        list: [
          'Generating slower timing pulses from a crystal or oscillator source.',
          'Creating long delays with simple logic.',
          'Providing binary count states to other logic.',
        ],
        note: 'This part is documented in the simulator but kept as a stub rather than a full counter implementation.',
      },
    ],
    pinout: [
      { pin:  1, name: 'Q12', type: 'output' },
      { pin:  2, name: 'Q6',  type: 'output' },
      { pin:  3, name: 'Q5',  type: 'output' },
      { pin:  4, name: 'Q7',  type: 'output' },
      { pin:  5, name: 'Q4',  type: 'output' },
      { pin:  6, name: 'Q3',  type: 'output' },
      { pin:  7, name: 'Q2',  type: 'output' },
      { pin:  8, name: 'GND', type: 'power'  },
      { pin:  9, name: 'Q1',  type: 'output' },
      { pin: 10, name: 'MR',  type: 'input'  },
      { pin: 11, name: 'CLK', type: 'input'  },
      { pin: 12, name: 'Q11', type: 'output' },
      { pin: 13, name: 'Q10', type: 'output' },
      { pin: 14, name: 'Q9',  type: 'output' },
      { pin: 15, name: 'Q8',  type: 'output' },
      { pin: 16, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['CLK','MR'], outputs: [] },
    ],
  },

  // 74x4022: 4-stage ÷8 Johnson divide-by-8 counter (14-pin)
  // SN74x4022 8 decoded outputs (Q0-Q7), ripple-carry out, clock, clock-enable, controller reset
  '74x4022': {
    name: '74x4022',
    simpleName: '4-Stage Divide-by-8 Johnson Counter',
    description: '4-stage divide-by-8 Johnson counter with 8 decoded outputs (14-pin)',
    pins: 14, vcc: 14, gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/cd4022b.pdf',
    tags: ['counter', 'johnson', 'divide-by-8', 'stub'],
    guideOverview: 'The 74x4022 is the 8-output relative of the 4017 Johnson counter. It advances one active output through eight decoded positions, which makes it useful for sequencing, scanning, and divide-by-8 timing. Because the outputs are already decoded, it is easy to wire directly to visible indicators or control stages.',
    guidePinDescriptions: {
      'Q1': 'Decoded output 1. Goes HIGH during count state 1.',
      'Q0': 'Decoded output 0. First active output after reset.',
      'Q2': 'Decoded output 2. Goes HIGH during count state 2.',
      'Q5': 'Decoded output 5. Goes HIGH during count state 5.',
      'Q6': 'Decoded output 6. Goes HIGH during count state 6.',
      'Q3': 'Decoded output 3. Goes HIGH during count state 3.',
      'GND': 'Ground reference for the counter.',
      'COUT': 'Carry output used for cascading counters.',
      'Q4': 'Decoded output 4. Goes HIGH during count state 4.',
      'Q7': 'Decoded output 7. Goes HIGH during count state 7.',
      'CLKEn': 'Clock enable (active LOW). Pull LOW to count; hold HIGH to pause.',
      'CLK': 'Clock input. Each valid clock pulse advances the counter to the next decoded state.',
      'MR': 'Master reset. Assert it to return the output sequence to its starting state.',
      'VCC': 'Positive supply for the device.',
    },
    guideSections: [
      {
        title: 'One-of-Eight Sequence',
        paragraphs: [
          'The chip cycles a single active state through eight decoded outputs instead of producing a binary number. That makes its outputs directly useful without a separate decoder.',
        ],
      },
      {
        title: 'Sequencing Applications',
        list: [
          'LED or lamp chasers.',
          'Step-by-step control logic.',
          'Simple divide-by-8 timing.',
        ],
        note: 'This entry remains a documented stub in the simulator.',
      },
    ],
    pinout: [
      { pin:  1, name: 'Q1',    type: 'output' },
      { pin:  2, name: 'Q0',    type: 'output' },
      { pin:  3, name: 'Q2',    type: 'output' },
      { pin:  4, name: 'Q5',    type: 'output' },
      { pin:  5, name: 'Q6',    type: 'output' },
      { pin:  6, name: 'Q3',    type: 'output' },
      { pin:  7, name: 'GND',   type: 'power'  },
      { pin:  8, name: 'COUT',  type: 'output' },
      { pin:  9, name: 'Q4',    type: 'output' },
      { pin: 10, name: 'Q7',    type: 'output' },
      { pin: 11, name: 'CLKEn', type: 'input'  },
      { pin: 12, name: 'CLK',   type: 'input'  },
      { pin: 13, name: 'MR',    type: 'input'  },
      { pin: 14, name: 'VCC',   type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['CLK','CLKEn','MR'], outputs: [] },
    ],
  },

  // 74x4024: 7-stage binary ripple counter (14-pin)
  // CD74x4024 7 flip-flop chain; Q1-Q7 brought out; CLK and MR
  '74x4024': {
    name: '74x4024',
    simpleName: '7-Stage Binary Ripple Counter',
    description: '7-stage binary ripple carry counter (14-pin)',
    pins: 14, vcc: 14, gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/cd74hc4024.pdf',
    tags: ['counter', 'binary', '7-stage', 'ripple', 'stub'],
    guideOverview: 'The 74x4024 is a compact binary ripple counter that provides seven divided outputs. Each stage divides the clock rate by 2, so the device is useful whenever one oscillator must be slowed down into several lower-frequency timing signals. It is a classic choice for simple counters, blinkers, and timing chains.',
    guidePinDescriptions: {
      'CLK': 'Clock input for the ripple counter.',
      'Q7': 'Counter output stage 7, one of the slowest available outputs.',
      'Q6': 'Counter output stage 6.',
      'Q5': 'Counter output stage 5.',
      'Q4': 'Counter output stage 4.',
      'Q3': 'Counter output stage 3.',
      'GND': 'Ground reference for the chip.',
      'Q2': 'Counter output stage 2.',
      'Q1': 'Counter output stage 1, one of the faster divided outputs.',
      'NC': 'No internal connection. Leave unconnected.',
      'NC2': 'No internal connection. Leave unconnected.',
      'NC3': 'No internal connection. Leave unconnected.',
      'MR': 'Master reset. Assert it to clear the count back to zero.',
      'VCC': 'Positive supply for the device.',
    },
    guideSections: [
      {
        title: 'Binary Division',
        paragraphs: [
          'Each output is a divided version of the clock. The farther down the chain the output comes from, the slower it toggles.',
        ],
      },
      {
        title: 'Why Use a Ripple Counter',
        paragraphs: [
          'Ripple counters are simple and efficient when exact synchronous edge alignment between all outputs is not required. They are especially convenient for frequency division and timing on hobby breadboards.',
        ],
        note: 'This counter is documented in the simulator as a stub rather than a full sequential model.',
      },
    ],
    pinout: [
      { pin:  1, name: 'CLK', type: 'input'  },
      { pin:  2, name: 'Q7',  type: 'output' },
      { pin:  3, name: 'Q6',  type: 'output' },
      { pin:  4, name: 'Q5',  type: 'output' },
      { pin:  5, name: 'Q4',  type: 'output' },
      { pin:  6, name: 'Q3',  type: 'output' },
      { pin:  7, name: 'GND', type: 'power'  },
      { pin:  8, name: 'Q2',  type: 'output' },
      { pin:  9, name: 'Q1',  type: 'output' },
      { pin: 10, name: 'NC',  type: 'nc'     },
      { pin: 11, name: 'NC2', type: 'nc'     },
      { pin: 12, name: 'NC3', type: 'nc'     },
      { pin: 13, name: 'MR',  type: 'input'  },
      { pin: 14, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['CLK','MR'], outputs: [] },
    ],
  },

  // 74x4028: BCD-to-decimal decoder (16-pin)
  // TC74x4028P 4 bit BCD input A-D, 10 decoded active high outputs Q0-Q9
  '74x4028': {
    name: '74x4028',
    simpleName: 'BCD to Decimal Decoder',
    description: 'BCD to decimal decoder with 4 bit BCD input and 10 decoded outputs (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/cd4028b.pdf',
    tags: ['decoder', 'BCD', 'decimal', '4-to-10', 'stub'],
    guideOverview: 'The 74x4028 converts a 4 bit input code into one active decimal output. In its BCD use, valid input codes 0 through 9 each select one matching output line, which is useful for numeric displays, step selection, and address decoding. It is the opposite of an encoder: one binary-coded input becomes one-of-many decoded outputs.',
    guidePinDescriptions: {
      'Q7': 'Decoded output 7.',
      'Q6': 'Decoded output 6.',
      'Q5': 'Decoded output 5.',
      'Q4': 'Decoded output 4.',
      'Q3': 'Decoded output 3.',
      'Q2': 'Decoded output 2.',
      'Q1': 'Decoded output 1.',
      'GND': 'Ground reference for the decoder.',
      'Q0': 'Decoded output 0.',
      'D': 'Most significant input bit in the 4 bit input code.',
      'C': 'Input bit C.',
      'B': 'Input bit B.',
      'A': 'Least significant input bit in the 4 bit input code.',
      'Q9': 'Decoded output 9.',
      'Q8': 'Decoded output 8.',
      'VCC': 'Positive supply for the logic.',
    },
    guideSections: [
      {
        title: 'Decoding BCD',
        paragraphs: [
          'A decoder turns a binary code into a one-of-many output. For BCD inputs, the values 0000 through 1001 activate Q0 through Q9 respectively.',
        ],
      },
      {
        title: 'Where It Helps',
        list: [
          'Selecting one of ten lines from a 4 bit control value.',
          'Driving digit-selection or indicator logic.',
          'Turning a binary-coded state into simple one-hot control signals.',
        ],
        note: 'This entry is documented as a stub in the simulator rather than a full decoder implementation.',
      },
    ],
    pinout: [
      { pin:  1, name: 'Q7',  type: 'output' },
      { pin:  2, name: 'Q6',  type: 'output' },
      { pin:  3, name: 'Q5',  type: 'output' },
      { pin:  4, name: 'Q4',  type: 'output' },
      { pin:  5, name: 'Q3',  type: 'output' },
      { pin:  6, name: 'Q2',  type: 'output' },
      { pin:  7, name: 'Q1',  type: 'output' },
      { pin:  8, name: 'GND', type: 'power'  },
      { pin:  9, name: 'Q0',  type: 'output' },
      { pin: 10, name: 'D',   type: 'input'  },
      { pin: 11, name: 'C',   type: 'input'  },
      { pin: 12, name: 'B',   type: 'input'  },
      { pin: 13, name: 'A',   type: 'input'  },
      { pin: 14, name: 'Q9',  type: 'output' },
      { pin: 15, name: 'Q8',  type: 'output' },
      { pin: 16, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['A','B','C','D'], outputs: [] },
    ],
  },

  // 74x4040: 12-stage binary ripple counter (16-pin)
  // SN74x4040 12 flip-flop chain; Q1-Q12 all brought out; CLK and MR
  '74x4040': {
    name: '74x4040',
    simpleName: '12-Stage Binary Ripple Counter',
    description: '12-stage binary ripple counter (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74hc4040.pdf',
    tags: ['counter', 'binary', '12-stage', 'ripple', 'stub'],
    guideOverview: 'The 74x4040 is a 12-stage binary ripple counter that divides a clock by successive powers of two. Each output represents a later stage in the chain, so one input clock can produce many slower timing signals at once. It is a practical building block for time delays, clock division, and simple event counting.',
    guidePinDescriptions: {
      'Q12': 'Counter output stage 12, one of the slowest divided outputs.',
      'Q6': 'Counter output stage 6.',
      'Q5': 'Counter output stage 5.',
      'Q7': 'Counter output stage 7.',
      'Q4': 'Counter output stage 4.',
      'Q3': 'Counter output stage 3.',
      'Q2': 'Counter output stage 2.',
      'GND': 'Ground reference for the counter.',
      'Q1': 'Counter output stage 1, one of the fastest divided outputs.',
      'MR': 'Master reset. Assert it to clear the entire counter to zero.',
      'CLK': 'Clock input that drives the ripple counter chain.',
      'Q11': 'Counter output stage 11.',
      'Q10': 'Counter output stage 10.',
      'Q9': 'Counter output stage 9.',
      'Q8': 'Counter output stage 8.',
      'VCC': 'Positive supply for the chip.',
    },
    guideSections: [
      {
        title: 'Frequency Division',
        paragraphs: [
          'Each counter stage toggles at half the frequency of the stage before it. That means the outputs naturally provide a family of divided clocks derived from one input source.',
        ],
        formulas: [
          'Qn frequency = clock frequency / 2^n',
        ],
      },
      {
        title: 'When Ripple Counters Fit Best',
        paragraphs: [
          'Ripple counters are simple and compact, which makes them attractive for timing and division work. They are best used where small propagation differences between stages are acceptable.',
        ],
        note: 'This entry remains a documented stub rather than a full sequential simulator model.',
      },
    ],
    pinout: [
      { pin:  1, name: 'Q12', type: 'output' },
      { pin:  2, name: 'Q6',  type: 'output' },
      { pin:  3, name: 'Q5',  type: 'output' },
      { pin:  4, name: 'Q7',  type: 'output' },
      { pin:  5, name: 'Q4',  type: 'output' },
      { pin:  6, name: 'Q3',  type: 'output' },
      { pin:  7, name: 'Q2',  type: 'output' },
      { pin:  8, name: 'GND', type: 'power'  },
      { pin:  9, name: 'Q1',  type: 'output' },
      { pin: 10, name: 'MR',  type: 'input'  },
      { pin: 11, name: 'CLK', type: 'input'  },
      { pin: 12, name: 'Q11', type: 'output' },
      { pin: 13, name: 'Q10', type: 'output' },
      { pin: 14, name: 'Q9',  type: 'output' },
      { pin: 15, name: 'Q8',  type: 'output' },
      { pin: 16, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['CLK','MR'], outputs: [] },
    ],
  },

  // 74x4046: Phase-locked loop and VCO (16-pin)
  // CD74x4046A PLL with two phase comparators (PC1, PC2), VCO with ext R/C, signal out, inhibit
  '74x4046': {
    name: '74x4046',
    simpleName: 'Phase-Locked Loop and VCO',
    description: 'Phase-locked loop (PLL) and voltage-controlled oscillator (VCO) (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/cd74hc4046a.pdf',
    tags: ['PLL', 'VCO', 'phase-locked', 'oscillator', 'stub'],
    guideOverview: 'The 74x4046 is a phase-locked loop building block that combines a voltage-controlled oscillator with phase-comparison circuitry. A PLL can lock an internal oscillator to the phase and frequency of an external signal, which makes this chip useful for tone decoding, clock recovery, frequency synthesis experiments, and other timing tasks. It is more of a mixed-signal timing IC than a simple logic gate.',
    guidePinDescriptions: {
      'PC1': 'Phase comparator 1 output. It provides one style of phase-difference signal for external loop filtering.',
      'SIN': 'Signal input associated with the comparator section.',
      'CIN': 'Comparator input used by the PLL section.',
      'VCOout': 'Output of the internal voltage-controlled oscillator.',
      'INH': 'Inhibit control for the VCO. Use it to stop or disable oscillator action when required.',
      'C1A': 'External timing-capacitor connection for the VCO network.',
      'C1B': 'Second timing-capacitor connection for the VCO network.',
      'GND': 'Ground reference for the IC.',
      'VCOin': 'Control-voltage input for the VCO. The voltage here changes the oscillator frequency.',
      'DEMout': 'Demodulator or loop-related output as defined in the datasheet.',
      'R1A': 'External timing-resistor connection used to set the VCO operating range.',
      'R2A': 'Second external timing-resistor connection for the VCO network.',
      'PC2': 'Phase comparator 2 output. This provides a second comparison characteristic for loop design.',
      'SIG': 'Signal input for the phase detector path.',
      'ZIN': 'Additional comparator or control input used by the PLL section.',
      'VCC': 'Positive supply for the PLL and VCO circuitry.',
    },
    guideSections: [
      {
        title: 'What a PLL Does',
        paragraphs: [
          'A phase-locked loop compares an incoming signal to an internal oscillator and generates an error signal based on the phase difference. After filtering, that error signal nudges the oscillator until it locks to the input.',
        ],
      },
      {
        title: 'External Timing Network',
        paragraphs: [
          'The 4046 relies on external resistors and capacitors to set the VCO frequency range and the behavior of the control loop. That flexibility is powerful, but it also means the part is more analog-sensitive than ordinary logic chips.',
        ],
        note: 'This simulator entry is intentionally a documented stub. The analog dynamics of a real PLL are not modeled here.',
      },
    ],
    pinout: [
      { pin:  1, name: 'PC1',   type: 'output' },
      { pin:  2, name: 'SIN',   type: 'input'  },
      { pin:  3, name: 'CIN',   type: 'input'  },
      { pin:  4, name: 'VCOout',type: 'output' },
      { pin:  5, name: 'INH',   type: 'input'  },
      { pin:  6, name: 'C1A',   type: 'input'  },
      { pin:  7, name: 'C1B',   type: 'input'  },
      { pin:  8, name: 'GND',   type: 'power'  },
      { pin:  9, name: 'VCOin', type: 'input'  },
      { pin: 10, name: 'DEMout',type: 'output' },
      { pin: 11, name: 'R1A',   type: 'input'  },
      { pin: 12, name: 'R2A',   type: 'input'  },
      { pin: 13, name: 'PC2',   type: 'output' },
      { pin: 14, name: 'SIG',   type: 'input'  },
      { pin: 15, name: 'ZIN',   type: 'input'  },
      { pin: 16, name: 'VCC',   type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['SIN','CIN','INH','C1A','C1B','VCOin','R1A','R2A','SIG','ZIN'], outputs: [] },
    ],
  },

  // 74x4049: Hex inverting buffer/converter (16-pin, NON-STANDARD power pins)
  // CD74x4049 VCC at pin 1 (not 16!), GND at pin 8; 6 independent NOT gates
  // Note: pins 14 and 16 are NC in the standard DIP package
  '74x4049': {
    name: '74x4049',
    simpleName: 'Hex Inverting Buffer',
    description: 'Hex inverting buffer / converter (non-standard: VCC=pin1, GND=pin8) (16-pin)',
    pins: 16, vcc: 1, gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/cd74hc4049.pdf',
    tags: ['NOT', 'hex', 'inverter', 'buffer'],
    guideOverview: 'The 74x4049 contains six independent inverting buffers. Each section outputs the opposite logic level of its input, and the family is often used both for inversion and for buffering weak signals. This part is also notable because its DIP power pins are not in the usual 14-or-16 pin logic locations, so the pinout deserves extra care when breadboarding.',
    guidePinDescriptions: {
      'VCC': 'Positive supply. This device uses the unusual 4049/4050 power arrangement with VCC on pin 1.',
      'A1': 'Input of inverter 1.',
      'Y1': 'Output of inverter 1. It is the logical inverse of A1.',
      'A2': 'Input of inverter 2.',
      'Y2': 'Output of inverter 2.',
      'A3': 'Input of inverter 3.',
      'Y3': 'Output of inverter 3.',
      'GND': 'Ground reference on pin 8, also part of the unusual 4049/4050 pinout.',
      'Y4': 'Output of inverter 4.',
      'A4': 'Input of inverter 4.',
      'Y5': 'Output of inverter 5.',
      'A5': 'Input of inverter 5.',
      'Y6': 'Output of inverter 6.',
      'NC': 'No internal connection. Leave unconnected.',
      'A6': 'Input of inverter 6.',
      'NC2': 'No internal connection. Leave unconnected.',
    },
    guideSections: [
      {
        title: 'Inversion and Buffering',
        paragraphs: [
          'Each section acts like a NOT gate with some buffering ability. That makes the chip useful for logic inversion, waveform cleanup, or creating complementary control signals.',
        ],
      },
      {
        title: 'Non-Standard Power Pins',
        paragraphs: [
          'Unlike many 16-pin logic chips, this family puts VCC on pin 1 and GND on pin 8. That is an easy source of wiring mistakes if you assume the usual VCC-at-the-end convention.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'VCC', type: 'power'  },
      { pin:  2, name: 'A1',  type: 'input'  },
      { pin:  3, name: 'Y1',  type: 'output' },
      { pin:  4, name: 'A2',  type: 'input'  },
      { pin:  5, name: 'Y2',  type: 'output' },
      { pin:  6, name: 'A3',  type: 'input'  },
      { pin:  7, name: 'Y3',  type: 'output' },
      { pin:  8, name: 'GND', type: 'power'  },
      { pin:  9, name: 'Y4',  type: 'output' },
      { pin: 10, name: 'A4',  type: 'input'  },
      { pin: 11, name: 'Y5',  type: 'output' },
      { pin: 12, name: 'A5',  type: 'input'  },
      { pin: 13, name: 'Y6',  type: 'output' },
      { pin: 14, name: 'NC',  type: 'nc'     },
      { pin: 15, name: 'A6',  type: 'input'  },
      { pin: 16, name: 'NC2', type: 'nc'     },
    ],
    gates: [
      { type: 'NOT', inputs: ['A1'], output: 'Y1' },
      { type: 'NOT', inputs: ['A2'], output: 'Y2' },
      { type: 'NOT', inputs: ['A3'], output: 'Y3' },
      { type: 'NOT', inputs: ['A4'], output: 'Y4' },
      { type: 'NOT', inputs: ['A5'], output: 'Y5' },
      { type: 'NOT', inputs: ['A6'], output: 'Y6' },
    ],
  },

  // 74x4050: Hex non-inverting buffer/converter (16-pin, NON-STANDARD power pins)
  // CD74x4050 VCC at pin 1 (not 16!), GND at pin 8; 6 independent BUFFER gates
  // Same pinout as 74x4049 but non-inverting
  '74x4050': {
    name: '74x4050',
    simpleName: 'Hex Non-Inverting Buffer',
    description: 'Hex buffer / converter, non-inverting (non-standard: VCC=pin1, GND=pin8) (16-pin)',
    pins: 16, vcc: 1, gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/cd74hc4050.pdf',
    tags: ['BUFFER', 'hex', 'non-inverting', 'buffer'],
    guideOverview: 'The 74x4050 provides six independent non-inverting buffer stages. Each output follows its input, but with the buffering benefits of a dedicated driver stage. It is often used to isolate one logic stage from another, improve fan-out, or adapt signals in systems that need the unusual 4049/4050 pinout family.',
    guidePinDescriptions: {
      'VCC': 'Positive supply on pin 1. This is the non-standard 4049/4050 family power arrangement.',
      'A1': 'Input of buffer 1.',
      'Y1': 'Output of buffer 1. It follows A1 without inversion.',
      'A2': 'Input of buffer 2.',
      'Y2': 'Output of buffer 2.',
      'A3': 'Input of buffer 3.',
      'Y3': 'Output of buffer 3.',
      'GND': 'Ground reference on pin 8.',
      'Y4': 'Output of buffer 4.',
      'A4': 'Input of buffer 4.',
      'Y5': 'Output of buffer 5.',
      'A5': 'Input of buffer 5.',
      'Y6': 'Output of buffer 6.',
      'NC': 'No internal connection. Leave unconnected.',
      'A6': 'Input of buffer 6.',
      'NC2': 'No internal connection. Leave unconnected.',
    },
    guideSections: [
      {
        title: 'Why Use a Buffer',
        paragraphs: [
          'A buffer reproduces the same logic state at its output, but it can isolate loading and provide cleaner drive to the next stage. This is helpful when one source must feed several destinations.',
        ],
      },
      {
        title: 'Pinout Reminder',
        paragraphs: [
          'Like the 4049, the 4050 does not use the common VCC-at-the-last-pin layout. Double-check power wiring before inserting the chip into a breadboard design.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'VCC', type: 'power'  },
      { pin:  2, name: 'A1',  type: 'input'  },
      { pin:  3, name: 'Y1',  type: 'output' },
      { pin:  4, name: 'A2',  type: 'input'  },
      { pin:  5, name: 'Y2',  type: 'output' },
      { pin:  6, name: 'A3',  type: 'input'  },
      { pin:  7, name: 'Y3',  type: 'output' },
      { pin:  8, name: 'GND', type: 'power'  },
      { pin:  9, name: 'Y4',  type: 'output' },
      { pin: 10, name: 'A4',  type: 'input'  },
      { pin: 11, name: 'Y5',  type: 'output' },
      { pin: 12, name: 'A5',  type: 'input'  },
      { pin: 13, name: 'Y6',  type: 'output' },
      { pin: 14, name: 'NC',  type: 'nc'     },
      { pin: 15, name: 'A6',  type: 'input'  },
      { pin: 16, name: 'NC2', type: 'nc'     },
    ],
    gates: [
      { type: 'BUFFER', inputs: ['A1'], output: 'Y1' },
      { type: 'BUFFER', inputs: ['A2'], output: 'Y2' },
      { type: 'BUFFER', inputs: ['A3'], output: 'Y3' },
      { type: 'BUFFER', inputs: ['A4'], output: 'Y4' },
      { type: 'BUFFER', inputs: ['A5'], output: 'Y5' },
      { type: 'BUFFER', inputs: ['A6'], output: 'Y6' },
    ],
  },

  // 74x4051: Single 8-channel analog multiplexer/demultiplexer (16-pin)
  // CD74x4051 analog mux; VEE (neg supply) at pin 7; Y0-Y7 are bidirectional analog I/O pins
  '74x4051': {
    name: '74x4051',
    simpleName: '8-Channel Analog Multiplexer/Demultiplexer',
    description: 'High-speed 8-channel analog multiplexer / demultiplexer (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/cd74hc4051.pdf',
    tags: ['analog', 'mux', 'demux', '8-channel', 'bidir', 'stub'],
    guideOverview: 'The 74x4051 is an 8-channel analog multiplexer/demultiplexer. It connects one common node to one of eight channel pins based on a 3 bit select code, and because the switch path is bilateral it can route analog or digital signals in either direction. This makes it useful for sensor selection, audio switching, and simple data acquisition experiments.',
    guidePinDescriptions: {
      'Z': 'Common analog switch node. It connects to one selected Y channel when the part is enabled.',
      'Y1': 'Channel 1 analog I/O node.',
      'Y6': 'Channel 6 analog I/O node.',
      'Y2': 'Channel 2 analog I/O node.',
      'Y5': 'Channel 5 analog I/O node.',
      'Y3': 'Channel 3 analog I/O node.',
      'VEE': 'Negative analog supply or analog lower-rail reference. This allows the part to handle signals below ground in suitable configurations.',
      'GND': 'Ground reference for the logic and analog supply scheme.',
      'Y4': 'Channel 4 analog I/O node.',
      'Y7': 'Channel 7 analog I/O node.',
      'Y0': 'Channel 0 analog I/O node.',
      'C': 'Most significant select input bit.',
      'B': 'Middle select input bit.',
      'A': 'Least significant select input bit.',
      'INH': 'Inhibit control. Use it to disconnect all channels from Z when the mux should be off.',
      'VCC': 'Positive supply for the switch-control circuitry.',
    },
    guideSections: [
      {
        title: 'Select Logic',
        paragraphs: [
          'The A, B, and C inputs form a 3 bit address that chooses which one of the eight channels connects to Z. Only one channel is selected at a time.',
        ],
      },
      {
        title: 'Analog Routing',
        paragraphs: [
          'Unlike ordinary digital multiplexers, the 4051 is designed to pass analog voltages as well as digital logic. The VEE pin extends the allowed signal range in circuits that need a negative analog rail.',
        ],
        note: 'This simulator entry describes the switching concept and control pins, but it does not model analog resistance or distortion in detail.',
      },
    ],
    pinout: [
      { pin:  1, name: 'Z',   type: 'bidir'  },
      { pin:  2, name: 'Y1',  type: 'bidir'  },
      { pin:  3, name: 'Y6',  type: 'bidir'  },
      { pin:  4, name: 'Y2',  type: 'bidir'  },
      { pin:  5, name: 'Y5',  type: 'bidir'  },
      { pin:  6, name: 'Y3',  type: 'bidir'  },
      { pin:  7, name: 'VEE', type: 'power'  },
      { pin:  8, name: 'GND', type: 'power'  },
      { pin:  9, name: 'Y4',  type: 'bidir'  },
      { pin: 10, name: 'Y7',  type: 'bidir'  },
      { pin: 11, name: 'Y0',  type: 'bidir'  },
      { pin: 12, name: 'C',   type: 'input'  },
      { pin: 13, name: 'B',   type: 'input'  },
      { pin: 14, name: 'A',   type: 'input'  },
      { pin: 15, name: 'INH', type: 'input'  },
      { pin: 16, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['A','B','C','INH'], outputs: [] },
    ],
  },

  // 74x4052: Dual 4-channel analog multiplexer/demultiplexer (16-pin)
  // CD74x4052 dual analog mux; VEE at pin 7; each mux has 4 I/O channels + common Z
  '74x4052': {
    name: '74x4052',
    simpleName: 'Dual 4-Channel Analog Multiplexer/Demultiplexer',
    description: 'Dual 4-channel analog multiplexer / demultiplexer (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/cd74hc4052.pdf',
    tags: ['analog', 'mux', 'demux', 'dual', '4-channel', 'bidir', 'stub'],
    guideOverview: 'The 74x4052 is a dual 4-channel analog multiplexer/demultiplexer. It contains two separate 4-channel switch sections that share the same 2 bit select code and inhibit input, so two related signals can be routed together. That makes it useful for stereo audio switching, paired sensor channels, or two-bit data paths.',
    guidePinDescriptions: {
      'XZ': 'Common node for the X-channel multiplexer section.',
      'X3': 'Channel 3 of the X section.',
      'X1': 'Channel 1 of the X section.',
      'X0': 'Channel 0 of the X section.',
      'X2': 'Channel 2 of the X section.',
      'YZ': 'Common node for the Y-channel multiplexer section.',
      'VEE': 'Negative analog supply or analog lower-rail reference.',
      'GND': 'Ground reference for the chip.',
      'Y2': 'Channel 2 of the Y section.',
      'Y0': 'Channel 0 of the Y section.',
      'Y1': 'Channel 1 of the Y section.',
      'Y3': 'Channel 3 of the Y section.',
      'B': 'Most significant select input bit shared by both sections.',
      'A': 'Least significant select input bit shared by both sections.',
      'INH': 'Inhibit control that disconnects both sections when asserted.',
      'VCC': 'Positive supply for the control circuitry.',
    },
    guideSections: [
      {
        title: 'Two Sections, One Address',
        paragraphs: [
          'Both the X and Y sections use the same select inputs, so they switch corresponding channels together. That is useful when two related signals should always be routed in parallel.',
        ],
      },
      {
        title: 'Analog Multiplexing',
        paragraphs: [
          'Because the paths are bilateral analog switches, the part can be used with analog or digital signals within the allowed voltage rails. The VEE pin allows more flexible analog signal ranges than a single-supply logic mux.',
        ],
        note: 'This simulator entry is a documented stub and does not model detailed analog characteristics.',
      },
    ],
    pinout: [
      { pin:  1, name: 'XZ',  type: 'bidir'  },
      { pin:  2, name: 'X3',  type: 'bidir'  },
      { pin:  3, name: 'X1',  type: 'bidir'  },
      { pin:  4, name: 'X0',  type: 'bidir'  },
      { pin:  5, name: 'X2',  type: 'bidir'  },
      { pin:  6, name: 'YZ',  type: 'bidir'  },
      { pin:  7, name: 'VEE', type: 'power'  },
      { pin:  8, name: 'GND', type: 'power'  },
      { pin:  9, name: 'Y2',  type: 'bidir'  },
      { pin: 10, name: 'Y0',  type: 'bidir'  },
      { pin: 11, name: 'Y1',  type: 'bidir'  },
      { pin: 12, name: 'Y3',  type: 'bidir'  },
      { pin: 13, name: 'B',   type: 'input'  },
      { pin: 14, name: 'A',   type: 'input'  },
      { pin: 15, name: 'INH', type: 'input'  },
      { pin: 16, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['A','B','INH'], outputs: [] },
    ],
  },

  // 74x4053: Triple 2-channel analog multiplexer/demultiplexer (16-pin)
  // CD74x4053 three independent SPDT analog switches; VEE at pin 7
  '74x4053': {
    name: '74x4053',
    simpleName: 'Triple 2-Channel Analog Multiplexer/Demultiplexer',
    description: 'Triple 2-channel analog multiplexer / demultiplexer (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/cd74hc4053.pdf',
    tags: ['analog', 'mux', 'demux', 'triple', '2-channel', 'bidir', 'stub'],
    guideOverview: 'The 74x4053 contains three independent 2-channel analog switch sections. Each section behaves like a digitally controlled SPDT switch, and the three select lines let each section choose between its 0 and 1 path independently. It is a versatile part for audio routing, sensor selection, and control circuits that need multiple analog channels switched at once.',
    guidePinDescriptions: {
      'ZB': 'Common node for section B.',
      'ZA': 'Common node for section A.',
      'ZC': 'Common node for section C.',
      'Y0A': 'Channel 0 node for section A.',
      'Y0B': 'Channel 0 node for section B.',
      'Y0C': 'Channel 0 node for section C.',
      'VEE': 'Negative analog supply or analog lower-rail reference.',
      'GND': 'Ground reference for the device.',
      'Y1C': 'Channel 1 node for section C.',
      'Y1B': 'Channel 1 node for section B.',
      'Y1A': 'Channel 1 node for section A.',
      'C': 'Select control for section C.',
      'B': 'Select control for section B.',
      'A': 'Select control for section A.',
      'INH': 'Global inhibit control that disconnects all three sections when asserted.',
      'VCC': 'Positive supply for the control circuitry.',
    },
    guideSections: [
      {
        title: 'Three SPDT Switches',
        paragraphs: [
          'Each section connects its common Z node to either the 0 channel or the 1 channel. Unlike the 4051 or 4052, the three sections do not share one address; each has its own select input.',
        ],
      },
      {
        title: 'Flexible Analog Routing',
        paragraphs: [
          'This device is useful when several analog or low-frequency digital paths need independent switching under one global enable. It can replace small relay arrangements in many low power designs.',
        ],
        note: 'The simulator documents the intended routing role of this part but does not model analog pass-switch resistance or signal distortion.',
      },
    ],
    pinout: [
      { pin:  1, name: 'ZB',  type: 'bidir'  },
      { pin:  2, name: 'ZA',  type: 'bidir'  },
      { pin:  3, name: 'ZC',  type: 'bidir'  },
      { pin:  4, name: 'Y0A', type: 'bidir'  },
      { pin:  5, name: 'Y0B', type: 'bidir'  },
      { pin:  6, name: 'Y0C', type: 'bidir'  },
      { pin:  7, name: 'VEE', type: 'power'  },
      { pin:  8, name: 'GND', type: 'power'  },
      { pin:  9, name: 'Y1C', type: 'bidir'  },
      { pin: 10, name: 'Y1B', type: 'bidir'  },
      { pin: 11, name: 'Y1A', type: 'bidir'  },
      { pin: 12, name: 'C',   type: 'input'  },
      { pin: 13, name: 'B',   type: 'input'  },
      { pin: 14, name: 'A',   type: 'input'  },
      { pin: 15, name: 'INH', type: 'input'  },
      { pin: 16, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['A','B','C','INH'], outputs: [] },
    ],
  },

};
