// Chip definitions block 50
// Chips: 74x1808, 74x1811, 74x1821, 74x1823, 74x1832, 74x1841, 74x1843,
//        74x2003, 74x2010, 74x2014, 74x2125, 74x2150,
//        74x2151, 74x2153, 74x2157, 74x2161

export const CHIPS_BLOCK_50 = {

  // 74x1808: Hex 2 input AND driver (20-pin)
  '74x1808': {
    name: '74x1808',
    simpleName: 'Hex 2 Input AND Driver',
    description: 'Hex 2 input AND gate with high-drive outputs (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: '',
    tags: ['and', 'hex', 'driver', 'stub'],
    pinout: [
      { pin:  1, name: '1A',   type: 'input'  },
      { pin:  2, name: '1B',   type: 'input'  },
      { pin:  3, name: '1Y',   type: 'output' },
      { pin:  4, name: '2A',   type: 'input'  },
      { pin:  5, name: '2B',   type: 'input'  },
      { pin:  6, name: '2Y',   type: 'output' },
      { pin:  7, name: '3A',   type: 'input'  },
      { pin:  8, name: '3B',   type: 'input'  },
      { pin:  9, name: '3Y',   type: 'output' },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: '4Y',   type: 'output' },
      { pin: 12, name: '4A',   type: 'input'  },
      { pin: 13, name: '4B',   type: 'input'  },
      { pin: 14, name: '5Y',   type: 'output' },
      { pin: 15, name: '5A',   type: 'input'  },
      { pin: 16, name: '5B',   type: 'input'  },
      { pin: 17, name: '6Y',   type: 'output' },
      { pin: 18, name: '6A',   type: 'input'  },
      { pin: 19, name: '6B',   type: 'input'  },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['1A','1B','2A','2B','3A','3B','4A','4B','5A','5B','6A','6B'], outputs: [] },
    ],
  },

  // 74x1811: FM/MFM/DM encoder/decoder, data rates up to 20 MHz (24-pin)
  '74x1811': {
    name: '74x1811',
    simpleName: 'FM/MFM/DM Encoder/Decoder (20 MHz)',
    description: 'FM, MFM, and DM encoder / decoder, data rates up to 20 MHz (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['encoder', 'decoder', 'FM', 'MFM', 'data', 'stub'],
    pinout: [
      { pin:  1, name: 'RD',   type: 'input'  },
      { pin:  2, name: 'CD',   type: 'input'  },
      { pin:  3, name: 'LD',   type: 'input'  },
      { pin:  4, name: 'WD',   type: 'input'  },
      { pin:  5, name: 'RC',   type: 'input'  },
      { pin:  6, name: 'WC',   type: 'input'  },
      { pin:  7, name: 'S0',   type: 'input'  },
      { pin:  8, name: 'S1',   type: 'input'  },
      { pin:  9, name: 'RST',  type: 'input'  },
      { pin: 10, name: 'NC',   type: 'nc'     },
      { pin: 11, name: 'NC2',  type: 'nc'     },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'NC3',  type: 'nc'     },
      { pin: 14, name: 'NC4',  type: 'nc'     },
      { pin: 15, name: 'DD',   type: 'output' },
      { pin: 16, name: 'SC',   type: 'output' },
      { pin: 17, name: 'WG',   type: 'output' },
      { pin: 18, name: 'LBn',  type: 'output' },
      { pin: 19, name: 'NC5',  type: 'nc'     },
      { pin: 20, name: 'NC6',  type: 'nc'     },
      { pin: 21, name: 'NC7',  type: 'nc'     },
      { pin: 22, name: 'NC8',  type: 'nc'     },
      { pin: 23, name: 'NC9',  type: 'nc'     },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['RD','CD','LD','WD','RC','WC','S0','S1','RST'], outputs: [] },
    ],
  },

  // 74x1821: 10 bit bus interface flip-flops, TRI-STATE (24-pin)
  '74x1821': {
    name: '74x1821',
    simpleName: '10 bit Bus Interface Flip-Flops',
    description: '10 bit bus interface flip-flops, TRI-STATE (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['flip-flop', '10 bit', 'bus', 'tri-state', 'stub'],
    pinout: [
      { pin:  1, name: 'OEn',  type: 'input'  },
      { pin:  2, name: 'CLK',  type: 'input'  },
      { pin:  3, name: 'D0',   type: 'input'  },
      { pin:  4, name: 'D1',   type: 'input'  },
      { pin:  5, name: 'D2',   type: 'input'  },
      { pin:  6, name: 'D3',   type: 'input'  },
      { pin:  7, name: 'D4',   type: 'input'  },
      { pin:  8, name: 'D5',   type: 'input'  },
      { pin:  9, name: 'D6',   type: 'input'  },
      { pin: 10, name: 'D7',   type: 'input'  },
      { pin: 11, name: 'D8',   type: 'input'  },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'D9',   type: 'input'  },
      { pin: 14, name: 'Q9',   type: 'output' },
      { pin: 15, name: 'Q8',   type: 'output' },
      { pin: 16, name: 'Q7',   type: 'output' },
      { pin: 17, name: 'Q6',   type: 'output' },
      { pin: 18, name: 'Q5',   type: 'output' },
      { pin: 19, name: 'Q4',   type: 'output' },
      { pin: 20, name: 'Q3',   type: 'output' },
      { pin: 21, name: 'Q2',   type: 'output' },
      { pin: 22, name: 'Q1',   type: 'output' },
      { pin: 23, name: 'Q0',   type: 'output' },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','CLK','D0','D1','D2','D3','D4','D5','D6','D7','D8','D9'], outputs: [] },
    ],
  },

  // 74x1823: 9 bit bus interface flip-flops with clear, TRI-STATE (24-pin)
  '74x1823': {
    name: '74x1823',
    simpleName: '9 bit Bus Interface Flip-Flops with Clear',
    description: '9 bit bus interface flip-flops with clear, TRI-STATE (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['flip-flop', '9 bit', 'bus', 'tri-state', 'clear', 'stub'],
    pinout: [
      { pin:  1, name: 'OEn',  type: 'input'  },
      { pin:  2, name: 'CLK',  type: 'input'  },
      { pin:  3, name: 'CLRn', type: 'input'  },
      { pin:  4, name: 'D0',   type: 'input'  },
      { pin:  5, name: 'D1',   type: 'input'  },
      { pin:  6, name: 'D2',   type: 'input'  },
      { pin:  7, name: 'D3',   type: 'input'  },
      { pin:  8, name: 'D4',   type: 'input'  },
      { pin:  9, name: 'D5',   type: 'input'  },
      { pin: 10, name: 'D6',   type: 'input'  },
      { pin: 11, name: 'D7',   type: 'input'  },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'D8',   type: 'input'  },
      { pin: 14, name: 'Q8',   type: 'output' },
      { pin: 15, name: 'Q7',   type: 'output' },
      { pin: 16, name: 'Q6',   type: 'output' },
      { pin: 17, name: 'Q5',   type: 'output' },
      { pin: 18, name: 'Q4',   type: 'output' },
      { pin: 19, name: 'Q3',   type: 'output' },
      { pin: 20, name: 'Q2',   type: 'output' },
      { pin: 21, name: 'Q1',   type: 'output' },
      { pin: 22, name: 'Q0',   type: 'output' },
      { pin: 23, name: 'NC',   type: 'nc'     },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','CLK','CLRn','D0','D1','D2','D3','D4','D5','D6','D7','D8'], outputs: [] },
    ],
  },

  // 74x1832: Hex 2 input OR driver (20-pin)
  '74x1832': {
    name: '74x1832',
    simpleName: 'Hex 2 Input OR Driver',
    description: 'Hex 2 input OR gate with high-drive outputs (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: '',
    tags: ['or', 'hex', 'driver', 'stub'],
    pinout: [
      { pin:  1, name: '1A',   type: 'input'  },
      { pin:  2, name: '1B',   type: 'input'  },
      { pin:  3, name: '1Y',   type: 'output' },
      { pin:  4, name: '2A',   type: 'input'  },
      { pin:  5, name: '2B',   type: 'input'  },
      { pin:  6, name: '2Y',   type: 'output' },
      { pin:  7, name: '3A',   type: 'input'  },
      { pin:  8, name: '3B',   type: 'input'  },
      { pin:  9, name: '3Y',   type: 'output' },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: '4Y',   type: 'output' },
      { pin: 12, name: '4A',   type: 'input'  },
      { pin: 13, name: '4B',   type: 'input'  },
      { pin: 14, name: '5Y',   type: 'output' },
      { pin: 15, name: '5A',   type: 'input'  },
      { pin: 16, name: '5B',   type: 'input'  },
      { pin: 17, name: '6Y',   type: 'output' },
      { pin: 18, name: '6A',   type: 'input'  },
      { pin: 19, name: '6B',   type: 'input'  },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['1A','1B','2A','2B','3A','3B','4A','4B','5A','5B','6A','6B'], outputs: [] },
    ],
  },

  // 74x1841: 10 bit bus interface transparent latches, TRI-STATE (24-pin)
  '74x1841': {
    name: '74x1841',
    simpleName: '10 bit Bus Interface Transparent Latches',
    description: '10 bit bus interface transparent latches, TRI-STATE (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['latch', '10 bit', 'bus', 'tri-state', 'stub'],
    pinout: [
      { pin:  1, name: 'OEn',  type: 'input'  },
      { pin:  2, name: 'LE',   type: 'input'  },
      { pin:  3, name: 'D0',   type: 'input'  },
      { pin:  4, name: 'D1',   type: 'input'  },
      { pin:  5, name: 'D2',   type: 'input'  },
      { pin:  6, name: 'D3',   type: 'input'  },
      { pin:  7, name: 'D4',   type: 'input'  },
      { pin:  8, name: 'D5',   type: 'input'  },
      { pin:  9, name: 'D6',   type: 'input'  },
      { pin: 10, name: 'D7',   type: 'input'  },
      { pin: 11, name: 'D8',   type: 'input'  },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'D9',   type: 'input'  },
      { pin: 14, name: 'Q9',   type: 'output' },
      { pin: 15, name: 'Q8',   type: 'output' },
      { pin: 16, name: 'Q7',   type: 'output' },
      { pin: 17, name: 'Q6',   type: 'output' },
      { pin: 18, name: 'Q5',   type: 'output' },
      { pin: 19, name: 'Q4',   type: 'output' },
      { pin: 20, name: 'Q3',   type: 'output' },
      { pin: 21, name: 'Q2',   type: 'output' },
      { pin: 22, name: 'Q1',   type: 'output' },
      { pin: 23, name: 'Q0',   type: 'output' },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','LE','D0','D1','D2','D3','D4','D5','D6','D7','D8','D9'], outputs: [] },
    ],
  },

  // 74x1843: 9 bit bus interface transparent latches with clear, TRI-STATE (24-pin)
  '74x1843': {
    name: '74x1843',
    simpleName: '9 bit Bus Interface Transparent Latches with Clear',
    description: '9 bit bus interface transparent latches with clear, TRI-STATE (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['latch', '9 bit', 'bus', 'tri-state', 'clear', 'stub'],
    pinout: [
      { pin:  1, name: 'OEn',  type: 'input'  },
      { pin:  2, name: 'LE',   type: 'input'  },
      { pin:  3, name: 'CLRn', type: 'input'  },
      { pin:  4, name: 'D0',   type: 'input'  },
      { pin:  5, name: 'D1',   type: 'input'  },
      { pin:  6, name: 'D2',   type: 'input'  },
      { pin:  7, name: 'D3',   type: 'input'  },
      { pin:  8, name: 'D4',   type: 'input'  },
      { pin:  9, name: 'D5',   type: 'input'  },
      { pin: 10, name: 'D6',   type: 'input'  },
      { pin: 11, name: 'D7',   type: 'input'  },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'D8',   type: 'input'  },
      { pin: 14, name: 'Q8',   type: 'output' },
      { pin: 15, name: 'Q7',   type: 'output' },
      { pin: 16, name: 'Q6',   type: 'output' },
      { pin: 17, name: 'Q5',   type: 'output' },
      { pin: 18, name: 'Q4',   type: 'output' },
      { pin: 19, name: 'Q3',   type: 'output' },
      { pin: 20, name: 'Q2',   type: 'output' },
      { pin: 21, name: 'Q1',   type: 'output' },
      { pin: 22, name: 'Q0',   type: 'output' },
      { pin: 23, name: 'NC',   type: 'nc'     },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','LE','CLRn','D0','D1','D2','D3','D4','D5','D6','D7','D8'], outputs: [] },
    ],
  },

  // 74x2003: 8 bit level translator (GTL to TTL) (20-pin)
  '74x2003': {
    name: '74x2003',
    simpleName: '8 bit Level Translator',
    description: '8 bit level translator (GTL to TTL) (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74gtl2003.pdf',
    tags: ['level translator', '8 bit', 'GTL', 'stub'],
    guideOverview: 'The 74x2003 is an eight-bit interface device that translates between a low-voltage GTL-style bus and ordinary TTL-compatible logic levels. GTL signaling uses reduced swing and a reference threshold so a heavily loaded bus can switch quickly without the full noise of standard TTL swings. A part like this sits at the edge of that bus and converts the signaling into levels that conventional logic can understand more easily.',
    guidePinDescriptions: {
      'A0': 'Signal channel A0. Connect one side of the translator path here.',
      'A1': 'Signal channel A1. This is another translated bus line.',
      'A2': 'Signal channel A2. Use it for a third signal path through the translator.',
      'A3': 'Signal channel A3. Another A-side channel in the 8 bit group.',
      'A4': 'Signal channel A4. It participates in the same translation network as the other channels.',
      'A5': 'Signal channel A5. Use it for another translated line.',
      'A6': 'Signal channel A6. This is the seventh A-side channel.',
      'A7': 'Signal channel A7. This is the final A-side signal line.',
      'VREF': 'Reference-voltage input for the GTL receiver thresholds. Tie it to the level recommended by the datasheet so the translator recognizes GTL HIGH and LOW correctly.',
      'GND': 'Ground reference for the device.',
      'B7': 'Signal channel B7. This is the B-side partner for A7.',
      'B6': 'Signal channel B6. Another B-side translated line.',
      'B5': 'Signal channel B5. It pairs with A5 through the translation circuitry.',
      'B4': 'Signal channel B4. Use it as another B-side interface node.',
      'B3': 'Signal channel B3. This is one of the lower-numbered B-side channels.',
      'B2': 'Signal channel B2. Another translated connection on the B side.',
      'B1': 'Signal channel B1. It pairs with A1 through the device.',
      'B0': 'Signal channel B0. This is the B-side partner for A0.',
      'NC': 'No internal connection. Leave this pin unconnected.',
      'VCC': 'Positive supply for the translator logic.',
    },
    guideSections: [
      {
        title: 'Why GTL Needs Translation',
        paragraphs: [
          'GTL uses a smaller signal swing than ordinary TTL, which helps heavily loaded buses switch faster and with less noise. The tradeoff is that ordinary TTL inputs are not always the right place to terminate or interpret those signals directly.',
          'A translator like the 74x2003 sits between the two worlds. It uses a reference threshold to interpret the GTL side and presents a cleaner, more TTL-friendly interface on the local logic side.',
        ],
      },
      {
        title: 'Role of VREF',
        paragraphs: [
          'Because GTL is a low-swing signaling scheme, the receiver cannot simply compare the input against a generic TTL threshold. VREF supplies the comparison level that tells the device where the switching boundary should be.',
        ],
        note: 'This simulator entry is a documentation-oriented stub. It records the part role and pins, but it does not emulate analog GTL threshold behavior.',
      },
    ],
    pinout: [
      { pin:  1, name: 'A0',   type: 'bidir'  },
      { pin:  2, name: 'A1',   type: 'bidir'  },
      { pin:  3, name: 'A2',   type: 'bidir'  },
      { pin:  4, name: 'A3',   type: 'bidir'  },
      { pin:  5, name: 'A4',   type: 'bidir'  },
      { pin:  6, name: 'A5',   type: 'bidir'  },
      { pin:  7, name: 'A6',   type: 'bidir'  },
      { pin:  8, name: 'A7',   type: 'bidir'  },
      { pin:  9, name: 'VREF', type: 'input'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'B7',   type: 'bidir'  },
      { pin: 12, name: 'B6',   type: 'bidir'  },
      { pin: 13, name: 'B5',   type: 'bidir'  },
      { pin: 14, name: 'B4',   type: 'bidir'  },
      { pin: 15, name: 'B3',   type: 'bidir'  },
      { pin: 16, name: 'B2',   type: 'bidir'  },
      { pin: 17, name: 'B1',   type: 'bidir'  },
      { pin: 18, name: 'B0',   type: 'bidir'  },
      { pin: 19, name: 'NC',   type: 'nc'     },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['VREF'], outputs: [] },
    ],
  },

  // 74x2010: 10 bit level translator (GTL to TTL) (24-pin)
  '74x2010': {
    name: '74x2010',
    simpleName: '10 bit Level Translator',
    description: '10 bit level translator (GTL to TTL) (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74gtl2010.pdf',
    tags: ['level translator', '10 bit', 'GTL', 'stub'],
    guideOverview: 'The 74x2010 is the 10 bit version of the GTL-to-TTL translation idea. It is intended for wider control or data groups where ten low-swing GTL lines must be interfaced to standard logic in one package. For designers working with backplanes or processor buses, this kind of part keeps the signaling scheme on the shared bus separate from the logic family used locally on the card.',
    guidePinDescriptions: {
      'A0': 'Signal channel A0. Connect one side of the first translated line here.',
      'A1': 'Signal channel A1. Another A-side bus connection.',
      'A2': 'Signal channel A2. Use it for the third translated signal.',
      'A3': 'Signal channel A3. Another A-side channel in the package.',
      'A4': 'Signal channel A4. It participates in the 10 bit translation group.',
      'A5': 'Signal channel A5. Use it for another line through the translator.',
      'A6': 'Signal channel A6. Another translated A-side signal.',
      'A7': 'Signal channel A7. This is the eighth A-side line.',
      'A8': 'Signal channel A8. This is the ninth A-side line.',
      'A9': 'Signal channel A9. This is the tenth and final A-side line.',
      'VREF': 'Reference-voltage input for the GTL receiver threshold. Use the datasheet-recommended bias level here.',
      'GND': 'Ground reference for the translator.',
      'B9': 'Signal channel B9. This is the B-side partner for A9.',
      'B8': 'Signal channel B8. Another B-side translated node.',
      'B7': 'Signal channel B7. Use it as the B-side mate for A7.',
      'B6': 'Signal channel B6. Another B-side interface line.',
      'B5': 'Signal channel B5. It belongs to the same translation bank as the rest.',
      'B4': 'Signal channel B4. Another B-side channel.',
      'B3': 'Signal channel B3. This is one of the lower-numbered B-side lines.',
      'B2': 'Signal channel B2. It pairs with A2 through the translator.',
      'B1': 'Signal channel B1. Another translated B-side line.',
      'B0': 'Signal channel B0. This is the B-side partner for A0.',
      'NC': 'No internal connection. Leave this pin unconnected.',
      'VCC': 'Positive supply for the device.',
    },
    guideSections: [
      {
        title: 'Wide-Bus Translation',
        paragraphs: [
          'A 10 bit translator is useful when a bus is wider than a simple byte but still needs uniform threshold handling across every line. One package gives the whole bus the same biasing and translation behavior.',
        ],
      },
      {
        title: 'Signal-Integrity Context',
        paragraphs: [
          'Parts like this existed because high-speed multi-drop buses place different demands on interconnects than point-to-point TTL links do. GTL was optimized for the shared bus; the translator makes that bus practical to interface with ordinary digital logic around it.',
        ],
        note: 'The simulator keeps this device as a stub/documentation model rather than a full analog GTL interface simulation.',
      },
    ],
    pinout: [
      { pin:  1, name: 'A0',   type: 'bidir'  },
      { pin:  2, name: 'A1',   type: 'bidir'  },
      { pin:  3, name: 'A2',   type: 'bidir'  },
      { pin:  4, name: 'A3',   type: 'bidir'  },
      { pin:  5, name: 'A4',   type: 'bidir'  },
      { pin:  6, name: 'A5',   type: 'bidir'  },
      { pin:  7, name: 'A6',   type: 'bidir'  },
      { pin:  8, name: 'A7',   type: 'bidir'  },
      { pin:  9, name: 'A8',   type: 'bidir'  },
      { pin: 10, name: 'A9',   type: 'bidir'  },
      { pin: 11, name: 'VREF', type: 'input'  },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'B9',   type: 'bidir'  },
      { pin: 14, name: 'B8',   type: 'bidir'  },
      { pin: 15, name: 'B7',   type: 'bidir'  },
      { pin: 16, name: 'B6',   type: 'bidir'  },
      { pin: 17, name: 'B5',   type: 'bidir'  },
      { pin: 18, name: 'B4',   type: 'bidir'  },
      { pin: 19, name: 'B3',   type: 'bidir'  },
      { pin: 20, name: 'B2',   type: 'bidir'  },
      { pin: 21, name: 'B1',   type: 'bidir'  },
      { pin: 22, name: 'B0',   type: 'bidir'  },
      { pin: 23, name: 'NC',   type: 'nc'     },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['VREF'], outputs: [] },
    ],
  },

  // 74x2014: 4 bit GTL to TTL transceiver, TRI-STATE and OC (14-pin)
  '74x2014': {
    name: '74x2014',
    simpleName: '4 bit GTL to TTL Transceiver',
    description: '4 bit GTL to TTL transceiver, TRI-STATE and open-collector (14-pin)',
    pins: 14, vcc: 14, gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74gtl2014.pdf',
    tags: ['transceiver', 'GTL', 'TTL', '4 bit', 'bidir', 'stub'],
    guideOverview: 'The 74x2014 is a four-bit GTL-to-TTL interface/transceiver with control over when the translated outputs are active. It is meant for smaller groups of lines where a full 8 bit or 10 bit translator would waste channels. The part combines GTL threshold handling, a reference input, and controlled bus connection so a local TTL circuit can safely interact with a lower-swing shared bus.',
    guidePinDescriptions: {
      'OEn': 'Output enable (active LOW). Pull LOW to activate the translated interface; drive HIGH to disconnect the controlled outputs.',
      'VREF': 'Reference-voltage input for the GTL thresholds. This bias level determines how the device interprets the low-swing bus signals.',
      'A0': 'Channel-0 A-side input. Use it as the local logic-side signal for the first translated path.',
      'B0': 'Channel-0 B-side bus node. This pin interfaces with the GTL/translated side of channel 0.',
      'A1': 'Channel-1 A-side input. Another local logic-side signal into the translator.',
      'B1': 'Channel-1 B-side bus node. It pairs with A1 through the device.',
      'GND': 'Ground reference for the package.',
      'B2': 'Channel-2 B-side bus node. This is the translated/bus-facing side of the third channel.',
      'A2': 'Channel-2 A-side input. Use it as the local-side source for channel 2.',
      'B3': 'Channel-3 B-side bus node. This is the final translated bus-facing line.',
      'A3': 'Channel-3 A-side input. It controls the fourth translation channel.',
      'NC': 'No internal connection. Leave this pin unconnected.',
      'NC2': 'No internal connection. Leave this pin unconnected.',
      'VCC': 'Positive supply for the interface logic.',
    },
    guideSections: [
      {
        title: 'Small-Bus Translation',
        paragraphs: [
          'Not every bus needs a full byte-wide interface. A 4 bit translator is a better fit for status groups, nibbles, or narrow control bundles that still use GTL-style signaling on the shared side.',
        ],
      },
      {
        title: 'Enable and Threshold Control',
        paragraphs: [
          'OEn controls when the translated outputs are allowed to participate, while VREF sets the comparison point for the GTL receivers. Together they let the designer manage both the bus loading and the logic threshold behavior.',
        ],
        note: 'As with the other GTL parts in this file, the simulator documents the package and controls but does not emulate the full analog bus physics.',
      },
    ],
    pinout: [
      { pin:  1, name: 'OEn',  type: 'input'  },
      { pin:  2, name: 'VREF', type: 'input'  },
      { pin:  3, name: 'A0',   type: 'input'  },
      { pin:  4, name: 'B0',   type: 'bidir'  },
      { pin:  5, name: 'A1',   type: 'input'  },
      { pin:  6, name: 'B1',   type: 'bidir'  },
      { pin:  7, name: 'GND',  type: 'power'  },
      { pin:  8, name: 'B2',   type: 'bidir'  },
      { pin:  9, name: 'A2',   type: 'input'  },
      { pin: 10, name: 'B3',   type: 'bidir'  },
      { pin: 11, name: 'A3',   type: 'input'  },
      { pin: 12, name: 'NC',   type: 'nc'     },
      { pin: 13, name: 'NC2',  type: 'nc'     },
      { pin: 14, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','VREF','A0','A1','A2','A3'], outputs: [] },
    ],
  },

  // 74x2125: Quad bus buffer, TRI-STATE, 25Ω series resistor (14-pin)
  '74x2125': {
    name: '74x2125',
    simpleName: 'Quad Bus Buffer (25Ω Series)',
    description: 'Quad bus buffer, TRI-STATE with 25 Ω series resistors (14-pin)',
    pins: 14, vcc: 14, gnd: 7,
    datasheet: '',
    tags: ['buffer', 'quad', 'tri-state', 'stub'],
    pinout: [
      { pin:  1, name: '1OEn', type: 'input'  },
      { pin:  2, name: '1A',   type: 'input'  },
      { pin:  3, name: '1Y',   type: 'output' },
      { pin:  4, name: '2OEn', type: 'input'  },
      { pin:  5, name: '2A',   type: 'input'  },
      { pin:  6, name: '2Y',   type: 'output' },
      { pin:  7, name: 'GND',  type: 'power'  },
      { pin:  8, name: '3Y',   type: 'output' },
      { pin:  9, name: '3A',   type: 'input'  },
      { pin: 10, name: '3OEn', type: 'input'  },
      { pin: 11, name: '4Y',   type: 'output' },
      { pin: 12, name: '4A',   type: 'input'  },
      { pin: 13, name: '4OEn', type: 'input'  },
      { pin: 14, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['1OEn','1A','2OEn','2A','3OEn','3A','4OEn','4A'], outputs: [] },
    ],
  },

  // 74x2150: 512 x 8 cache address comparator (24-pin)
  '74x2150': {
    name: '74x2150',
    simpleName: '512 x 8 Cache Address Comparator',
    description: '512 x 8 cache address comparator (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['comparator', 'cache', 'address', 'stub'],
    pinout: [
      { pin:  1, name: 'A0',   type: 'input'  },
      { pin:  2, name: 'A1',   type: 'input'  },
      { pin:  3, name: 'A2',   type: 'input'  },
      { pin:  4, name: 'A3',   type: 'input'  },
      { pin:  5, name: 'A4',   type: 'input'  },
      { pin:  6, name: 'A5',   type: 'input'  },
      { pin:  7, name: 'A6',   type: 'input'  },
      { pin:  8, name: 'A7',   type: 'input'  },
      { pin:  9, name: 'WEn',  type: 'input'  },
      { pin: 10, name: 'RESn', type: 'input'  },
      { pin: 11, name: 'HIT',  type: 'output' },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'HITn', type: 'output' },
      { pin: 14, name: 'D0',   type: 'input'  },
      { pin: 15, name: 'D1',   type: 'input'  },
      { pin: 16, name: 'D2',   type: 'input'  },
      { pin: 17, name: 'D3',   type: 'input'  },
      { pin: 18, name: 'D4',   type: 'input'  },
      { pin: 19, name: 'D5',   type: 'input'  },
      { pin: 20, name: 'D6',   type: 'input'  },
      { pin: 21, name: 'D7',   type: 'input'  },
      { pin: 22, name: 'CLK',  type: 'input'  },
      { pin: 23, name: 'RA78', type: 'input'  },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['A0','A1','A2','A3','A4','A5','A6','A7','WEn','RESn','D0','D1','D2','D3','D4','D5','D6','D7','CLK','RA78'], outputs: [] },
    ],
  },

  // 74x2151: 8-line to 1-line multiplexer, 25Ω series resistor (16-pin)
  '74x2151': {
    name: '74x2151',
    simpleName: '8-Line to 1-Line Multiplexer (25Ω Series)',
    description: '8-line to 1-line multiplexer with 25 Ω series resistor (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    datasheet: '',
    tags: ['multiplexer', '8:1', 'mux', 'stub'],
    pinout: [
      { pin:  1, name: 'D3',   type: 'input'  },
      { pin:  2, name: 'D2',   type: 'input'  },
      { pin:  3, name: 'D1',   type: 'input'  },
      { pin:  4, name: 'D0',   type: 'input'  },
      { pin:  5, name: 'Y',    type: 'output' },
      { pin:  6, name: 'Wn',   type: 'output' },
      { pin:  7, name: 'STRn', type: 'input'  },
      { pin:  8, name: 'GND',  type: 'power'  },
      { pin:  9, name: 'C',    type: 'input'  },
      { pin: 10, name: 'B',    type: 'input'  },
      { pin: 11, name: 'A',    type: 'input'  },
      { pin: 12, name: 'D7',   type: 'input'  },
      { pin: 13, name: 'D6',   type: 'input'  },
      { pin: 14, name: 'D5',   type: 'input'  },
      { pin: 15, name: 'D4',   type: 'input'  },
      { pin: 16, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['D0','D1','D2','D3','D4','D5','D6','D7','A','B','C','STRn'], outputs: [] },
    ],
  },

  // 74x2153: Dual 4-line to 1-line multiplexer, 25Ω series resistor (16-pin)
  '74x2153': {
    name: '74x2153',
    simpleName: 'Dual 4-Line to 1-Line Multiplexer (25Ω Series)',
    description: 'Dual 4-line to 1-line multiplexer with 25 Ω series resistor (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    datasheet: '',
    tags: ['multiplexer', '4:1', 'dual', 'mux', 'stub'],
    pinout: [
      { pin:  1, name: '1STRn', type: 'input'  },
      { pin:  2, name: 'B',     type: 'input'  },
      { pin:  3, name: 'A',     type: 'input'  },
      { pin:  4, name: '1D0',   type: 'input'  },
      { pin:  5, name: '1D1',   type: 'input'  },
      { pin:  6, name: '1D2',   type: 'input'  },
      { pin:  7, name: '1D3',   type: 'input'  },
      { pin:  8, name: 'GND',   type: 'power'  },
      { pin:  9, name: '2D3',   type: 'input'  },
      { pin: 10, name: '2D2',   type: 'input'  },
      { pin: 11, name: '2D1',   type: 'input'  },
      { pin: 12, name: '2D0',   type: 'input'  },
      { pin: 13, name: '2Y',    type: 'output' },
      { pin: 14, name: '1Y',    type: 'output' },
      { pin: 15, name: '2STRn', type: 'input'  },
      { pin: 16, name: 'VCC',   type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['1STRn','B','A','1D0','1D1','1D2','1D3','2D0','2D1','2D2','2D3','2STRn'], outputs: [] },
    ],
  },

  // 74x2157: Quad 2-line to 1-line multiplexer, 25Ω series resistor (16-pin)
  '74x2157': {
    name: '74x2157',
    simpleName: 'Quad 2-Line to 1-Line Multiplexer (25Ω Series)',
    description: 'Quad 2-line to 1-line multiplexer with 25 Ω series resistor (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    datasheet: '',
    tags: ['multiplexer', '2:1', 'quad', 'mux', 'stub'],
    pinout: [
      { pin:  1, name: 'SEL',  type: 'input'  },
      { pin:  2, name: '1A',   type: 'input'  },
      { pin:  3, name: '1B',   type: 'input'  },
      { pin:  4, name: '1Y',   type: 'output' },
      { pin:  5, name: '2A',   type: 'input'  },
      { pin:  6, name: '2B',   type: 'input'  },
      { pin:  7, name: '2Y',   type: 'output' },
      { pin:  8, name: 'GND',  type: 'power'  },
      { pin:  9, name: '3Y',   type: 'output' },
      { pin: 10, name: '3A',   type: 'input'  },
      { pin: 11, name: '3B',   type: 'input'  },
      { pin: 12, name: '4Y',   type: 'output' },
      { pin: 13, name: '4A',   type: 'input'  },
      { pin: 14, name: '4B',   type: 'input'  },
      { pin: 15, name: 'STRn', type: 'input'  },
      { pin: 16, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['SEL','1A','1B','2A','2B','3A','3B','4A','4B','STRn'], outputs: [] },
    ],
  },

  // 74x2161: Synchronous presettable 4 bit binary counter, async clear, 25Ω (16-pin)
  '74x2161': {
    name: '74x2161',
    simpleName: 'Sync Presettable 4 bit Binary Counter (25Ω)',
    description: 'Synchronous presettable 4 bit binary counter with asynchronous clear and 25 Ω series resistor (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    datasheet: '',
    tags: ['counter', '4 bit', 'synchronous', 'preset', 'clear', 'stub'],
    pinout: [
      { pin:  1, name: 'CLRn', type: 'input'  },
      { pin:  2, name: 'CLK',  type: 'input'  },
      { pin:  3, name: 'A',    type: 'input'  },
      { pin:  4, name: 'B',    type: 'input'  },
      { pin:  5, name: 'C',    type: 'input'  },
      { pin:  6, name: 'D',    type: 'input'  },
      { pin:  7, name: 'ENP',  type: 'input'  },
      { pin:  8, name: 'GND',  type: 'power'  },
      { pin:  9, name: 'LDn',  type: 'input'  },
      { pin: 10, name: 'ENT',  type: 'input'  },
      { pin: 11, name: 'QD',   type: 'output' },
      { pin: 12, name: 'QC',   type: 'output' },
      { pin: 13, name: 'QB',   type: 'output' },
      { pin: 14, name: 'QA',   type: 'output' },
      { pin: 15, name: 'RCO',  type: 'output' },
      { pin: 16, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['CLRn','CLK','A','B','C','D','ENP','LDn','ENT'], outputs: [] },
    ],
  },
};