// chips26.js Chips Block 26: 74446, 74447, 74448, 74449, 74S450, 74x450,
//                              74S451, 74x451, 74452, 74x453, 74454,
//                              74x455, 74x456, 74458, 74x460, 74461
export const CHIPS_BLOCK_26 = {

  // ── 74446: Quad bus transceivers, direction controls, inverting outputs ──
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Three-state_logic
     Wikipedia: https://en.wikipedia.org/wiki/Bus_transceiver */
  '74x446': {
    name: '74x446',
    simpleName: 'Quad Inv Bus Xcvr (3-state)',
    description: 'Quad bus transceiver, DIR control, inverting 3-state outputs (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    tags: ['transceiver', 'quad', 'inverting', 'tri state'],
    guideOverview: 'The 74x446 is a quad inverting bidirectional bus transceiver with tri state outputs. Two enable inputs (OE1n, OE2n active LOW) plus DIR control data direction. Data is inverted as it passes through a HIGH on the A side becomes a LOW on the B side. A compact 16-pin alternative to the 20-pin 74x443.',
    guidePinDescriptions: {
      'OE1n': 'Output Enable 1 (active LOW). Both OE1n and OE2n must be LOW to enable.',
      'OE2n': 'Output Enable 2 (active LOW).',
      'DIR':  'Direction. HIGH = A to B (inverted); LOW = B to A (inverted).',
      'A1':   'Side A pin 1.',
      'B1':   'Side B pin 1 (inverted).',
      'A2':   'Side A pin 2.',
      'B2':   'Side B pin 2.',
      'GND':  'Ground reference (pin 8).',
      'B3':   'Side B pin 3.',
      'A3':   'Side A pin 3.',
      'B4':   'Side B pin 4.',
      'A4':   'Side A pin 4.',
      'NC1':  'No connect.',
      'NC2':  'No connect.',
      'NC3':  'No connect.',
      'VCC':  'Positive supply (+5 V, pin 16).',
    },
    guideSections: [
      {
        title: 'Inverting Transceiver',
        paragraphs: [
          'The inversion is useful when interfacing TTL buses of opposite active polarity. The 74x446 is the 16-pin counterpart to the 20-pin 74x443 (same function, fewer NC pins).',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'OE1n', type: 'input' },
      { pin:  2, name: 'OE2n', type: 'input' },
      { pin:  3, name: 'DIR',  type: 'input' },
      { pin:  4, name: 'A1',   type: 'input' },
      { pin:  5, name: 'B1',   type: 'output' },
      { pin:  6, name: 'A2',   type: 'input' },
      { pin:  7, name: 'B2',   type: 'output' },
      { pin:  8, name: 'GND',  type: 'power' },
      { pin:  9, name: 'B3',   type: 'output' },
      { pin: 10, name: 'A3',   type: 'input' },
      { pin: 11, name: 'B4',   type: 'output' },
      { pin: 12, name: 'A4',   type: 'input' },
      { pin: 13, name: 'NC1',  type: 'nc' },
      { pin: 14, name: 'NC2',  type: 'nc' },
      { pin: 15, name: 'NC3',  type: 'nc' },
      { pin: 16, name: 'VCC',  type: 'power' },
    ],
    gates: [
      { type: 'BUS_XCVR_QUAD_INV_TRI',
        inputs:  ['OE1n','OE2n','DIR','A1','A2','A3','A4'],
        outputs: ['B1','B2','B3','B4'] },
    ],
  },

  // ── 74447: BCD to 7 segment decoders/drivers (low voltage version of 74247)
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Multiplexer
     Wikipedia: https://en.wikipedia.org/wiki/Open_collector */
  '74x447': {
    name: '74x447',
    simpleName: 'BCD to 7-Seg (OC, low V)',
    description: 'BCD to 7-seg decoder/driver, open-collector, low-voltage 74247 (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    openCollector: true,
    tags: ['7 segment', '7 seg', 'decoder', 'bcd', 'display', 'open collector'],
    guideOverview: 'The 74x447 is a BCD to 7 segment decoder/driver with open collector outputs and a low voltage output swing suited for direct LED or LCD interfacing. It is functionally identical to the 74x247 but specified for lower output voltage. LT (lamp test) forces all segments on; RBI blanks leading zeros; BI/RBO blanks and ripple chains multiple digits.',
    guidePinDescriptions: {
      'B':      'BCD input bit B (weight 2).',
      'C':      'BCD input bit C (weight 4).',
      'LT':     'Lamp Test (active LOW). Pull LOW to light all seven segments regardless of BCD input.',
      'BI/RBO': 'Blanking Input / Ripple Blanking Output. When pulled LOW externally, blanks all outputs. Goes LOW automatically when RBI suppresses a zero.',
      'RBI':    'Ripple Blanking Input (active LOW). Pull LOW to suppress a zero digit (output blanked when BCD = 0000 and RBI = LOW).',
      'D':      'BCD input bit D (weight 8, MSB).',
      'A':      'BCD input bit A (weight 1, LSB).',
      'GND':    'Ground reference (pin 8).',
      'e':      'Segment e output (active LOW, OC).',
      'd':      'Segment d output (active LOW, OC).',
      'c':      'Segment c output (active LOW, OC).',
      'b':      'Segment b output (active LOW, OC).',
      'a':      'Segment a output (active LOW, OC).',
      'g':      'Segment g output (active LOW, OC).',
      'f':      'Segment f output (active LOW, OC).',
      'VCC':    'Positive supply (+5 V, pin 16).',
    },
    guideSections: [
      {
        title: '7 Segment Display Layout',
        paragraphs: [
          'Segments a-g correspond to: a=top, b=upper right, c=lower right, d=bottom, e=lower left, f=upper left, g=middle bar. Each active LOW OC output needs a pull up resistor matched to the LED forward voltage and desired current.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'B',      type: 'input' },
      { pin:  2, name: 'C',      type: 'input' },
      { pin:  3, name: 'LT',     type: 'input' },
      { pin:  4, name: 'BI/RBO', type: 'input' },
      { pin:  5, name: 'RBI',    type: 'input' },
      { pin:  6, name: 'D',      type: 'input' },
      { pin:  7, name: 'A',      type: 'input' },
      { pin:  8, name: 'GND',    type: 'power' },
      { pin:  9, name: 'e',      type: 'output' },
      { pin: 10, name: 'd',      type: 'output' },
      { pin: 11, name: 'c',      type: 'output' },
      { pin: 12, name: 'b',      type: 'output' },
      { pin: 13, name: 'a',      type: 'output' },
      { pin: 14, name: 'g',      type: 'output' },
      { pin: 15, name: 'f',      type: 'output' },
      { pin: 16, name: 'VCC',    type: 'power' },
    ],
    gates: [
      { type: 'BCD_7SEG', inputs: ['A','B','C','D'], outputs: ['a','b','c','d','e','f','g'] },
    ],
  },

  // ── 74448: Quad tridirectional transceiver, inv+non inv, OC ─────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Open_collector
     Wikipedia: https://en.wikipedia.org/wiki/Bus_transceiver */
  '74x448': {
    name: '74x448',
    simpleName: 'Quad Inv+Non Inv Tridirnl Xcvr (OC)',
    description: 'Quad tridirectional transceiver, mixed polarity, open-collector (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    openCollector: true,
    tags: ['transceiver', 'quad', 'bidirectional', 'inverting', 'open collector'],
    guideOverview: 'The 74x448 is a quad mixed polarity tridirectional bus transceiver with open collector outputs. Some channels pass data non inverted and some are inverted, making it suitable for buses that mix active HIGH and active LOW lines. OC outputs require external pull ups.',
    guidePinDescriptions: {
      'OE1n': 'Output Enable 1 (active LOW).',
      'OE2n': 'Output Enable 2 (active LOW).',
      'DIR':  'Direction. HIGH = A to B; LOW = B to A.',
      'A1':   'Side A pin 1.',
      'B1':   'Side B pin 1.',
      'A2':   'Side A pin 2.',
      'B2':   'Side B pin 2.',
      'A3':   'Side A pin 3.',
      'B3':   'Side B pin 3.',
      'GND':  'Ground reference (pin 10).',
      'B4':   'Side B pin 4.',
      'A4':   'Side A pin 4.',
      'NC1':  'No connect.',
      'NC2':  'No connect.',
      'NC3':  'No connect.',
      'NC4':  'No connect.',
      'NC5':  'No connect.',
      'NC6':  'No connect.',
      'NC7':  'No connect.',
      'VCC':  'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'Mixed Polarity OC Transceiver',
        paragraphs: [
          'The combination of OC outputs and mixed polarity channels allows the 74x448 to be used on buses with wired AND logic across mixed active-level lines. Add 1 kΩ pull ups to VCC on all B outputs.',
        ],
      },
    ],
    // Pins 1-10 reconstructed: the def shipped with only the pin 11-20 tail.
    // Signal order follows the 74x446/74x449 family interleave; GND at pin 10
    // and VCC at pin 20 match this chip's own guidePinDescriptions.
    pinout: [
      { pin:  1, name: 'OE1n', type: 'input' },
      { pin:  2, name: 'OE2n', type: 'input' },
      { pin:  3, name: 'DIR',  type: 'input' },
      { pin:  4, name: 'A1',   type: 'input' },
      { pin:  5, name: 'B1',   type: 'output' },
      { pin:  6, name: 'A2',   type: 'input' },
      { pin:  7, name: 'B2',   type: 'output' },
      { pin:  8, name: 'A3',   type: 'input' },
      { pin:  9, name: 'B3',   type: 'output' },
      { pin: 10, name: 'GND',  type: 'power' },
      { pin: 11, name: 'B4',   type: 'output' },
      { pin: 12, name: 'A4',   type: 'input' },
      { pin: 13, name: 'NC1',  type: 'nc' },
      { pin: 14, name: 'NC2',  type: 'nc' },
      { pin: 15, name: 'NC3',  type: 'nc' },
      { pin: 16, name: 'NC4',  type: 'nc' },
      { pin: 17, name: 'NC5',  type: 'nc' },
      { pin: 18, name: 'NC6',  type: 'nc' },
      { pin: 19, name: 'NC7',  type: 'nc' },
      { pin: 20, name: 'VCC',  type: 'power' },
    ],
    gates: [
      { type: 'BUS_XCVR_QUAD_INV_OC',
        inputs:  ['OE1n','OE2n','DIR','A1','A2','A3','A4'],
        outputs: ['B1','B2','B3','B4'] },
    ],
  },

  // ── 74449: Quad bus transceivers, direction controls, non inverting ──────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Three-state_logic
     Wikipedia: https://en.wikipedia.org/wiki/Bus_transceiver */
  '74x449': {
    name: '74x449',
    simpleName: 'Quad Non Inv Bus Xcvr (3-state)',
    description: 'Quad bus transceiver, DIR control, non-inverting 3-state outputs (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    tags: ['transceiver', 'quad', 'tri state'],
    guideOverview: 'The 74x449 is a quad non inverting bidirectional bus transceiver with tri state outputs in a 16-pin package. DIR controls data direction; OE1n and OE2n (both active LOW) must be asserted together. It is the compact version of the 74x442 with fewer NC pins.',
    guidePinDescriptions: {
      'OE1n': 'Output Enable 1 (active LOW).',
      'OE2n': 'Output Enable 2 (active LOW).',
      'DIR':  'Direction. HIGH = A to B; LOW = B to A.',
      'A1':   'Side A pin 1.',
      'B1':   'Side B pin 1.',
      'A2':   'Side A pin 2.',
      'B2':   'Side B pin 2.',
      'GND':  'Ground reference (pin 8).',
      'B3':   'Side B pin 3.',
      'A3':   'Side A pin 3.',
      'B4':   'Side B pin 4.',
      'A4':   'Side A pin 4.',
      'NC1':  'No connect.',
      'NC2':  'No connect.',
      'NC3':  'No connect.',
      'VCC':  'Positive supply (+5 V, pin 16).',
    },
    guideSections: [
      {
        title: 'Compact Non Inverting Transceiver',
        paragraphs: [
          'The 74x449 provides the same function as 74x442 in a smaller 16-pin package by eliminating the NC pins. Functionally identical; choose based on board size and routing constraints.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'OE1n', type: 'input' },
      { pin:  2, name: 'OE2n', type: 'input' },
      { pin:  3, name: 'DIR',  type: 'input' },
      { pin:  4, name: 'A1',   type: 'input' },
      { pin:  5, name: 'B1',   type: 'output' },
      { pin:  6, name: 'A2',   type: 'input' },
      { pin:  7, name: 'B2',   type: 'output' },
      { pin:  8, name: 'GND',  type: 'power' },
      { pin:  9, name: 'B3',   type: 'output' },
      { pin: 10, name: 'A3',   type: 'input' },
      { pin: 11, name: 'B4',   type: 'output' },
      { pin: 12, name: 'A4',   type: 'input' },
      { pin: 13, name: 'NC1',  type: 'nc' },
      { pin: 14, name: 'NC2',  type: 'nc' },
      { pin: 15, name: 'NC3',  type: 'nc' },
      { pin: 16, name: 'VCC',  type: 'power' },
    ],
    gates: [
      { type: 'BUS_XCVR_QUAD_TRI',
        inputs:  ['OE1n','OE2n','DIR','A1','A2','A3','A4'],
        outputs: ['B1','B2','B3','B4'] },
    ],
  },

  // ── 74x450: 16-to-1 multiplexer, complementary outputs ─────────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits */
  '74x450': {
    name: '74x450',
    simpleName: '16-to-1 Mux (compl. out)',
    description: '16-to-1 multiplexer with complementary (true and inverted) outputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    tags: ['multiplexer', '16-to-1', 'complementary'],
    guideOverview: 'The 74x450 is a 16-to-1 multiplexer with a 4 bit select (A-D), 16 data inputs (E0-E15), an active LOW global enable (Gn), and a true output (W). With 4 select lines it can address any of 16 inputs (2^4 = 16). This is the largest single package MUX in the 74xx family.',
    guidePinDescriptions: {
      'E0':  'Data input 0.',
      'E1':  'Data input 1.',
      'E2':  'Data input 2.',
      'E3':  'Data input 3.',
      'E4':  'Data input 4.',
      'E5':  'Data input 5.',
      'E6':  'Data input 6.',
      'E7':  'Data input 7.',
      'E8':  'Data input 8.',
      'E9':  'Data input 9.',
      'E10': 'Data input 10.',
      'GND': 'Ground reference (pin 12).',
      'E11': 'Data input 11.',
      'E12': 'Data input 12.',
      'E13': 'Data input 13.',
      'E14': 'Data input 14.',
      'E15': 'Data input 15.',
      'A':   'Select bit A (LSB).',
      'B':   'Select bit B.',
      'C':   'Select bit C.',
      'D':   'Select bit D (MSB).',
      'Gn':  'Global Enable (active LOW). When HIGH, W is forced LOW.',
      'W':   'MUX output. Reflects the selected input.',
      'VCC': 'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: '16-to-1 Selection',
        paragraphs: [
          'The four select bits ABCD encode a binary number 0-15 that selects the corresponding E input. With Gn=LOW the selected E value passes to W.',
          'Practical use: connect 16 signal sources to E0-E15 and sweep ABCD with a binary counter to read each source in sequence serial scan of 16 parallel inputs.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'E0',  type: 'input' },
      { pin:  2, name: 'E1',  type: 'input' },
      { pin:  3, name: 'E2',  type: 'input' },
      { pin:  4, name: 'E3',  type: 'input' },
      { pin:  5, name: 'E4',  type: 'input' },
      { pin:  6, name: 'E5',  type: 'input' },
      { pin:  7, name: 'E6',  type: 'input' },
      { pin:  8, name: 'E7',  type: 'input' },
      { pin:  9, name: 'E8',  type: 'input' },
      { pin: 10, name: 'E9',  type: 'input' },
      { pin: 11, name: 'E10', type: 'input' },
      { pin: 12, name: 'GND', type: 'power' },
      { pin: 13, name: 'E11', type: 'input' },
      { pin: 14, name: 'E12', type: 'input' },
      { pin: 15, name: 'E13', type: 'input' },
      { pin: 16, name: 'E14', type: 'input' },
      { pin: 17, name: 'E15', type: 'input' },
      { pin: 18, name: 'A',   type: 'input' },
      { pin: 19, name: 'B',   type: 'input' },
      { pin: 20, name: 'C',   type: 'input' },
      { pin: 21, name: 'D',   type: 'input' },
      { pin: 22, name: 'Gn',  type: 'input' },
      { pin: 23, name: 'W',   type: 'output' },
      { pin: 24, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'MUX_16TO1_COMPL',
        inputs:  ['E0','E1','E2','E3','E4','E5','E6','E7','E8','E9','E10','E11','E12','E13','E14','E15','A','B','C','D','Gn'],
        outputs: ['W'] },
    ],
  },

  // ── 74x451: Dual 8-to-1 multiplexer ────────────────────────────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits */
  // 24-pin dual 8→1 mux; sections share select lines S0,S1,S2 and lower data
  // inputs D0-D3; each section has own D4-D7 inputs and enable (Gn).
  '74x451': {
    name: '74x451',
    simpleName: 'Dual 8-to-1 Mux',
    description: 'Dual 8-to-1 mux, complementary outputs, shared lower-4 inputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    tags: ['multiplexer', '8-to-1', 'dual'],
    guideOverview: 'The 74x451 contains two 8-to-1 multiplexers in a 24-pin package. Both sections share the lower 4 data inputs (D0-D3) and all three select lines (S0-S2), but each section has its own upper 4 data inputs (1D4-1D7, 2D4-2D7), enable (1Gn/2Gn), and complementary outputs (1W/1Wn, 2W/2Wn).',
    guidePinDescriptions: {
      'D0':  'Shared data input 0 (used by both sections).',
      'D1':  'Shared data input 1.',
      'D2':  'Shared data input 2.',
      'D3':  'Shared data input 3.',
      'S0':  'Select bit 0 (LSB). Shared by both sections.',
      'S1':  'Select bit 1. Shared.',
      'S2':  'Select bit 2 (MSB). Shared.',
      '1Gn': 'Enable for section 1 (active LOW). When HIGH, 1W is forced LOW.',
      '1W':  'MUX output of section 1 (selected input, true).',
      '1Wn': 'MUX output of section 1 (selected input, complemented).',
      '1D4': 'Private data input 4 of section 1.',
      'GND': 'Ground reference (pin 12).',
      '1D5': 'Private data input 5 of section 1.',
      '1D6': 'Private data input 6 of section 1.',
      '1D7': 'Private data input 7 of section 1.',
      '2D4': 'Private data input 4 of section 2.',
      '2D5': 'Private data input 5 of section 2.',
      '2D6': 'Private data input 6 of section 2.',
      '2D7': 'Private data input 7 of section 2.',
      '2Gn': 'Enable for section 2 (active LOW).',
      '2W':  'MUX output of section 2 (selected input, true).',
      '2Wn': 'MUX output of section 2 (selected input, complemented)',
      'NC':  'No connect.',
      'VCC': 'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: 'Shared vs Private Inputs',
        paragraphs: [
          'D0-D3 are common to both sections, reducing pin count for the lower half of the address space. D4-D7 are separate per section for the upper half. This architecture is useful for dual channel signal routing where both channels share a common input pool.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'D0',   type: 'input' },
      { pin:  2, name: 'D1',   type: 'input' },
      { pin:  3, name: 'D2',   type: 'input' },
      { pin:  4, name: 'D3',   type: 'input' },
      { pin:  5, name: 'S0',   type: 'input' },
      { pin:  6, name: 'S1',   type: 'input' },
      { pin:  7, name: 'S2',   type: 'input' },
      { pin:  8, name: '1Gn',  type: 'input' },
      { pin:  9, name: '1W',   type: 'output' },
      { pin: 10, name: '1Wn',  type: 'output' },
      { pin: 11, name: '1D4',  type: 'input' },
      { pin: 12, name: 'GND',  type: 'power' },
      { pin: 13, name: '1D5',  type: 'input' },
      { pin: 14, name: '1D6',  type: 'input' },
      { pin: 15, name: '1D7',  type: 'input' },
      { pin: 16, name: '2D4',  type: 'input' },
      { pin: 17, name: '2D5',  type: 'input' },
      { pin: 18, name: '2D6',  type: 'input' },
      { pin: 19, name: '2D7',  type: 'input' },
      { pin: 20, name: '2Gn',  type: 'input' },
      { pin: 21, name: '2W',   type: 'output' },
      { pin: 22, name: '2Wn',  type: 'output' },
      { pin: 23, name: 'NC',   type: 'nc' },
      { pin: 24, name: 'VCC',  type: 'power' },
    ],
    gates: [
      { type: 'MUX_8TO1_COMPL_TRI',
        inputs:  ['D0','D1','D2','D3','1D4','1D5','1D6','1D7','S0','S1','S2','1Gn'],
        outputs: ['1W','1Wn'] },
      { type: 'MUX_8TO1_COMPL_TRI',
        inputs:  ['D0','D1','D2','D3','2D4','2D5','2D6','2D7','S0','S1','S2','2Gn'],
        outputs: ['2W','2Wn'] },
    ],
  },

  // ── 74452: Dual decade counter, synchronous ──────────────────────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Counter_(digital)
     Wikipedia: https://en.wikipedia.org/wiki/Flip-flop_(electronics) */
  '74x452': {
    name: '74x452',
    simpleName: 'Dual Decade Counter (sync)',
    description: 'Dual synchronous decade counter with reset (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    sequential: true,
    tags: ['counter', 'decade', 'synchronous', 'dual'],
    guideOverview: 'The 74x452 contains two independent synchronous BCD decade counters (0-9), each with its own clock, active LOW clear, and terminal count (TC) output for cascading. Unlike the asynchronous 74x390, both flip flops in each counter are clocked simultaneously, eliminating ripple delay between bits.',
    guidePinDescriptions: {
      'CLK1':  'Clock for counter 1 (rising edge counts).',
      'CLRn1': 'Clear for counter 1 (active LOW). Synchronous or asynchronous depending on variant.',
      'QA1':   'Output A of counter 1 (bit 0).',
      'QB1':   'Output B of counter 1.',
      'QC1':   'Output C of counter 1.',
      'QD1':   'Output D of counter 1 (MSB).',
      'TC1':   'Terminal Count of counter 1. Goes HIGH when count reaches 9.',
      'GND':   'Ground reference (pin 8).',
      'TC2':   'Terminal Count of counter 2.',
      'QD2':   'Output D of counter 2.',
      'QC2':   'Output C of counter 2.',
      'QB2':   'Output B of counter 2.',
      'QA2':   'Output A of counter 2.',
      'CLRn2': 'Clear for counter 2 (active LOW).',
      'CLK2':  'Clock for counter 2.',
      'VCC':   'Positive supply (+5 V, pin 16).',
    },
    guideSections: [
      {
        title: 'Synchronous vs Asynchronous Decade Counter',
        paragraphs: [
          'In a synchronous counter all flip flops share the clock, so all outputs change simultaneously. In an asynchronous (ripple) counter each stage clocks from the previous output, causing small delays that can produce glitches on combinational decode logic.',
          'The TC output (HIGH at count 9) can clock the next counter for multi digit cascading.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'CLK1',  type: 'input' },
      { pin:  2, name: 'CLRn1', type: 'input' },
      { pin:  3, name: 'QA1',   type: 'output' },
      { pin:  4, name: 'QB1',   type: 'output' },
      { pin:  5, name: 'QC1',   type: 'output' },
      { pin:  6, name: 'QD1',   type: 'output' },
      { pin:  7, name: 'TC1',   type: 'output' },
      { pin:  8, name: 'GND',   type: 'power' },
      { pin:  9, name: 'TC2',   type: 'output' },
      { pin: 10, name: 'QD2',   type: 'output' },
      { pin: 11, name: 'QC2',   type: 'output' },
      { pin: 12, name: 'QB2',   type: 'output' },
      { pin: 13, name: 'QA2',   type: 'output' },
      { pin: 14, name: 'CLRn2', type: 'input' },
      { pin: 15, name: 'CLK2',  type: 'input' },
      { pin: 16, name: 'VCC',   type: 'power' },
    ],
    gates: [
      { type: 'COUNTER_DECADE_DUAL_SYNC',
        inputs:  ['CLK1','CLRn1','CLK2','CLRn2'],
        outputs: ['QA1','QB1','QC1','QD1','TC1','QA2','QB2','QC2','QD2','TC2'] },
    ],
  },

  // ── 74x453: Quad 4-to-1 multiplexer ─────────────────────────────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits */
  '74x453': {
    name: '74x453',
    simpleName: 'Quad 4-to-1 Mux',
    description: 'Quad 4-to-1 multiplexer with common select lines (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    tags: ['multiplexer', '4-to-1', 'quad'],
    guideOverview: 'The 74x453 contains four independent 4-to-1 multiplexers sharing a common 2 bit select (S0, S1). Each section has four data inputs (C_0 to C_3) and one output (Y). All four selectors are steered to the same address simultaneously, making this ideal for 4-wide bus selection or function generation.',
    guidePinDescriptions: {
      'S0':   'Select bit 0 (LSB). Shared by all four sections.',
      'S1':   'Select bit 1 (MSB). Shared by all four sections.',
      'Y1':   'MUX output of section 1 (selected input).',
      'C1_0': 'Section 1 data input 0.',
      'C1_1': 'Section 1 data input 1.',
      'C1_2': 'Section 1 data input 2.',
      'C1_3': 'Section 1 data input 3.',
      'Y2':   'MUX output of section 2 (selected input).',
      'C2_0': 'Section 2 data input 0.',
      'C2_1': 'Section 2 data input 1.',
      'C2_2': 'Section 2 data input 2.',
      'GND':  'Ground reference (pin 12).',
      'C2_3': 'Section 2 data input 3.',
      'Y3':   'MUX output of section 3 (selected input).',
      'C3_0': 'Section 3 data input 0.',
      'C3_1': 'Section 3 data input 1.',
      'C3_2': 'Section 3 data input 2.',
      'C3_3': 'Section 3 data input 3.',
      'Y4':   'MUX output of section 4 (selected input)',
      'C4_0': 'Section 4 data input 0.',
      'C4_1': 'Section 4 data input 1.',
      'C4_2': 'Section 4 data input 2.',
      'C4_3': 'Section 4 data input 3.',
      'VCC':  'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: '4-Wide Bus Selection',
        paragraphs: [
          'By treating the four sections as a nibble wide MUX, you can route one of four 4 bit buses to the output with a single 2 bit address. Connect S0/S1 to address bits; the four Y outputs give the selected nibble.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'S0',   type: 'input' },
      { pin:  2, name: 'S1',   type: 'input' },
      { pin:  3, name: 'Y1',   type: 'output' },
      { pin:  4, name: 'C1_0', type: 'input' },
      { pin:  5, name: 'C1_1', type: 'input' },
      { pin:  6, name: 'C1_2', type: 'input' },
      { pin:  7, name: 'C1_3', type: 'input' },
      { pin:  8, name: 'Y2',   type: 'output' },
      { pin:  9, name: 'C2_0', type: 'input' },
      { pin: 10, name: 'C2_1', type: 'input' },
      { pin: 11, name: 'C2_2', type: 'input' },
      { pin: 12, name: 'GND',  type: 'power' },
      { pin: 13, name: 'C2_3', type: 'input' },
      { pin: 14, name: 'Y3',   type: 'output' },
      { pin: 15, name: 'C3_0', type: 'input' },
      { pin: 16, name: 'C3_1', type: 'input' },
      { pin: 17, name: 'C3_2', type: 'input' },
      { pin: 18, name: 'C3_3', type: 'input' },
      { pin: 19, name: 'Y4',   type: 'output' },
      { pin: 20, name: 'C4_0', type: 'input' },
      { pin: 21, name: 'C4_1', type: 'input' },
      { pin: 22, name: 'C4_2', type: 'input' },
      { pin: 23, name: 'C4_3', type: 'input' },
      { pin: 24, name: 'VCC',  type: 'power' },
    ],
    gates: [
      { type: 'MUX_QUAD_4TO1',
        inputs:  ['C1_0','C1_1','C1_2','C1_3','C2_0','C2_1','C2_2','C2_3',
                  'C3_0','C3_1','C3_2','C3_3','C4_0','C4_1','C4_2','C4_3','S0','S1'],
        outputs: ['Y1','Y2','Y3','Y4'] },
    ],
  },

  // ── 74454: Dual decade up/down counter, synchronous, preset input ────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Counter_(digital) */
  '74x454': {
    name: '74x454',
    simpleName: 'Dual Decade Up/Down Counter (sync)',
    description: 'Dual synchronous decade up/down counter with preset inputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    sequential: true,
    tags: ['counter', 'decade', 'synchronous', 'up-down', 'dual', 'preset'],
    guideOverview: 'The 74x454 is a dual synchronous BCD up/down decade counter with parallel preset. A common clock, up/down select (U_Dn), enable inputs (ENP, ENT), parallel load (LOADn), and clear (CLRn) are provided per counter. TCU fires at count 9 going up; TCD fires at count 0 going down.',
    guidePinDescriptions: {
      'CLK':   'Clock for counter 1 (rising edge).',
      'U_Dn':  'Direction. HIGH = count up; LOW = count down.',
      'ENP':   'Count Enable Parallel (counter 1). Both ENP and ENT must be HIGH to count.',
      'ENT':   'Count Enable Trickle. Drives TCU/TCD outputs and cascades.',
      'LOADn': 'Parallel Load (active LOW). On rising CLK, loads P0-P3.',
      'CLRn':  'Clear (active LOW). Asynchronously resets counter 1 to 0.',
      'P0':    'Preset data bit 0 for counter 1.',
      'P1':    'Preset data bit 1.',
      'P2':    'Preset data bit 2.',
      'P3':    'Preset data bit 3.',
      'Q0':    'Output bit 0 of counter 1.',
      'GND':   'Ground reference (pin 12).',
      'Q1':    'Output bit 1.',
      'Q2':    'Output bit 2.',
      'Q3':    'Output bit 3.',
      'TCD':   'Terminal Count Down. HIGH when counter reaches 0 going down.',
      'TCU':   'Terminal Count Up. HIGH when counter reaches 9 going up.',
      'CLK2':  'Clock for counter 2.',
      'ENP2':  'Count Enable Parallel for counter 2.',
      'P4':    'Preset data bit 0 for counter 2.',
      'P5':    'Preset data bit 1 for counter 2.',
      'P6':    'Preset data bit 2 for counter 2.',
      'P7':    'Preset data bit 3 for counter 2.',
      'VCC':   'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: 'Up/Down Counter Cascading',
        paragraphs: [
          'Connect TCU of the lower counter to ENT of the next for up counting cascade; connect TCD similarly for down counting. ENP should be tied HIGH for cascaded sections since they should always count when the upstream counter reaches its terminal.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'CLK',   type: 'input' },
      { pin:  2, name: 'U_Dn',  type: 'input' },
      { pin:  3, name: 'ENP',   type: 'input' },
      { pin:  4, name: 'ENT',   type: 'input' },
      { pin:  5, name: 'LOADn', type: 'input' },
      { pin:  6, name: 'CLRn',  type: 'input' },
      { pin:  7, name: 'P0',    type: 'input' },
      { pin:  8, name: 'P1',    type: 'input' },
      { pin:  9, name: 'P2',    type: 'input' },
      { pin: 10, name: 'P3',    type: 'input' },
      { pin: 11, name: 'Q0',    type: 'output' },
      { pin: 12, name: 'GND',   type: 'power' },
      { pin: 13, name: 'Q1',    type: 'output' },
      { pin: 14, name: 'Q2',    type: 'output' },
      { pin: 15, name: 'Q3',    type: 'output' },
      { pin: 16, name: 'TCD',   type: 'output' },
      { pin: 17, name: 'TCU',   type: 'output' },
      { pin: 18, name: 'CLK2',  type: 'input' },
      { pin: 19, name: 'ENP2',  type: 'input' },
      { pin: 20, name: 'P4',    type: 'input' },
      { pin: 21, name: 'P5',    type: 'input' },
      { pin: 22, name: 'P6',    type: 'input' },
      { pin: 23, name: 'P7',    type: 'input' },
      { pin: 24, name: 'VCC',   type: 'power' },
    ],
    gates: [
      { type: 'COUNTER_DECADE_UPDOWN_DUAL',
        inputs:  ['CLK','CLK2','U_Dn','ENP','ENT','ENP2','LOADn','CLRn','P0','P1','P2','P3','P4','P5','P6','P7'],
        outputs: ['Q0','Q1','Q2','Q3','TCD','TCU'] },
    ],
  },

  // ── 74x455: Octal buffer/line driver with parity, inverting ─────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits */
  '74x455': {
    name: '74x455',
    simpleName: 'Octal Buffer w/ Parity (inv)',
    description: 'Octal buffer/line driver, parity gen, inverting, 3-state (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    tags: ['buffer', 'octal', 'parity', 'inverting', 'tri state'],
    guideOverview: 'The 74x455 is an octal inverting buffer/line driver with integrated even/odd parity generation. Each of the eight inputs passes through an inverter to the Y output; simultaneously the XOR tree accumulates a parity bit. EP (Even Parity) selects whether the PERR output flags even or odd parity. OEn tri states all Y outputs.',
    guidePinDescriptions: {
      'OEn':  'Output Enable (active LOW). When HIGH, Y0-Y7 are high impedance.',
      'A0':   'Data input 0.',
      'A1':   'Data input 1.',
      'A2':   'Data input 2.',
      'A3':   'Data input 3.',
      'A4':   'Data input 4.',
      'A5':   'Data input 5.',
      'A6':   'Data input 6.',
      'A7':   'Data input 7.',
      'EP':   'Even Parity select. HIGH = even parity mode.',
      'PERR': 'Parity Error output. Flags a parity violation.',
      'GND':  'Ground reference (pin 12).',
      'Y7':   'Inverted output 7.',
      'Y6':   'Inverted output 6.',
      'Y5':   'Inverted output 5.',
      'Y4':   'Inverted output 4.',
      'Y3':   'Inverted output 3.',
      'Y2':   'Inverted output 2.',
      'Y1':   'Inverted output 1.',
      'Y0':   'Inverted output 0.',
      'NC1':  'No connect.',
      'NC2':  'No connect.',
      'NC3':  'No connect.',
      'VCC':  'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: 'Parity Generation',
        paragraphs: [
          'Parity is a simple error detection scheme: an extra bit is added to a data word so the total number of 1 bits is always even (even parity) or always odd (odd parity). The receiver recounts and flags a PERR if the parity is wrong.',
          'The 74x455 generates parity on the fly as data is buffered, adding error detection without extra logic.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'OEn',  type: 'input' },
      { pin:  2, name: 'A0',   type: 'input' },
      { pin:  3, name: 'A1',   type: 'input' },
      { pin:  4, name: 'A2',   type: 'input' },
      { pin:  5, name: 'A3',   type: 'input' },
      { pin:  6, name: 'A4',   type: 'input' },
      { pin:  7, name: 'A5',   type: 'input' },
      { pin:  8, name: 'A6',   type: 'input' },
      { pin:  9, name: 'A7',   type: 'input' },
      { pin: 10, name: 'EP',   type: 'input' },
      { pin: 11, name: 'PERR', type: 'output' },
      { pin: 12, name: 'GND',  type: 'power' },
      { pin: 13, name: 'Y7',   type: 'output' },
      { pin: 14, name: 'Y6',   type: 'output' },
      { pin: 15, name: 'Y5',   type: 'output' },
      { pin: 16, name: 'Y4',   type: 'output' },
      { pin: 17, name: 'Y3',   type: 'output' },
      { pin: 18, name: 'Y2',   type: 'output' },
      { pin: 19, name: 'Y1',   type: 'output' },
      { pin: 20, name: 'Y0',   type: 'output' },
      { pin: 21, name: 'NC1',  type: 'nc' },
      { pin: 22, name: 'NC2',  type: 'nc' },
      { pin: 23, name: 'NC3',  type: 'nc' },
      { pin: 24, name: 'VCC',  type: 'power' },
    ],
    gates: [
      { type: 'BUFFER_OCTAL_PARITY_INV',
        inputs:  ['A0','A1','A2','A3','A4','A5','A6','A7','OEn','EP'],
        outputs: ['Y0','Y1','Y2','Y3','Y4','Y5','Y6','Y7','PERR'] },
    ],
  },

  // ── 74x456: Octal buffer/line driver with parity, non inverting ──────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits */
  '74x456': {
    name: '74x456',
    simpleName: 'Octal Buffer w/ Parity (non inv)',
    description: 'Octal buffer/line driver, parity gen, non-inverting, 3-state (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    tags: ['buffer', 'octal', 'parity', 'non inverting', 'tri state'],
    guideOverview: 'The 74x456 is identical to the 74x455 but with non inverting outputs. Eight inputs pass through buffers unchanged to Y0-Y7 while the parity tree checks or generates even/odd parity. OEn tri states all Y outputs.',
    guidePinDescriptions: {
      'OEn':  'Output Enable (active LOW).',
      'A0':   'Data input 0.',
      'A1':   'Data input 1.',
      'A2':   'Data input 2.',
      'A3':   'Data input 3.',
      'A4':   'Data input 4.',
      'A5':   'Data input 5.',
      'A6':   'Data input 6.',
      'A7':   'Data input 7.',
      'EP':   'Even Parity select.',
      'PERR': 'Parity Error output.',
      'GND':  'Ground reference (pin 12).',
      'Y7':   'Buffered output 7 (non inverted).',
      'Y6':   'Buffered output 6.',
      'Y5':   'Buffered output 5.',
      'Y4':   'Buffered output 4.',
      'Y3':   'Buffered output 3.',
      'Y2':   'Buffered output 2.',
      'Y1':   'Buffered output 1.',
      'Y0':   'Buffered output 0.',
      'NC1':  'No connect.',
      'NC2':  'No connect.',
      'NC3':  'No connect.',
      'VCC':  'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: '74x455 vs 74x456',
        paragraphs: [
          'The 74x455 inverts each data bit at the output; the 74x456 does not. Both calculate parity on the same input data. Use 74x456 when you need the original data on the bus with in line parity checking.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'OEn',  type: 'input' },
      { pin:  2, name: 'A0',   type: 'input' },
      { pin:  3, name: 'A1',   type: 'input' },
      { pin:  4, name: 'A2',   type: 'input' },
      { pin:  5, name: 'A3',   type: 'input' },
      { pin:  6, name: 'A4',   type: 'input' },
      { pin:  7, name: 'A5',   type: 'input' },
      { pin:  8, name: 'A6',   type: 'input' },
      { pin:  9, name: 'A7',   type: 'input' },
      { pin: 10, name: 'EP',   type: 'input' },
      { pin: 11, name: 'PERR', type: 'output' },
      { pin: 12, name: 'GND',  type: 'power' },
      { pin: 13, name: 'Y7',   type: 'output' },
      { pin: 14, name: 'Y6',   type: 'output' },
      { pin: 15, name: 'Y5',   type: 'output' },
      { pin: 16, name: 'Y4',   type: 'output' },
      { pin: 17, name: 'Y3',   type: 'output' },
      { pin: 18, name: 'Y2',   type: 'output' },
      { pin: 19, name: 'Y1',   type: 'output' },
      { pin: 20, name: 'Y0',   type: 'output' },
      { pin: 21, name: 'NC1',  type: 'nc' },
      { pin: 22, name: 'NC2',  type: 'nc' },
      { pin: 23, name: 'NC3',  type: 'nc' },
      { pin: 24, name: 'VCC',  type: 'power' },
    ],
    gates: [
      { type: 'BUFFER_OCTAL_PARITY',
        inputs:  ['A0','A1','A2','A3','A4','A5','A6','A7','OEn','EP'],
        outputs: ['Y0','Y1','Y2','Y3','Y4','Y5','Y6','Y7','PERR'] },
    ],
  },

  // ── 74458: Nines complement / zero element ────────────────────────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits */
  '74x458': {
    name: '74x458',
    simpleName: "Nines Complement / Zero Elem",
    description: "Nines complement and zero element logic (stub) (14-pin)",
    pins: 14, vcc: 14, gnd: 7,
    tags: ['arithmetic', 'bcd', 'complement'],
    guideOverview: 'The 74x458 computes the nines complement of a BCD digit. Given a BCD input A (0-9), it outputs 9-A. When the ZEn (Zero Element) input is asserted, the output is forced to zero. Used in BCD subtraction circuits where complement and add is used instead of direct subtraction.',
    guidePinDescriptions: {
      'A0':  'BCD input bit 0 (LSB).',
      'A1':  'BCD input bit 1.',
      'A2':  'BCD input bit 2.',
      'A3':  'BCD input bit 3 (MSB).',
      'ZEn': 'Zero Element enable. When asserted, forces output to 0.',
      'Y0':  'Nines complement output bit 0.',
      'GND': 'Ground reference (pin 7).',
      'Y1':  'Nines complement output bit 1.',
      'Y2':  'Nines complement output bit 2.',
      'Y3':  'Nines complement output bit 3.',
      'NC1': 'No connect.',
      'NC2': 'No connect.',
      'NC3': 'No connect.',
      'VCC': 'Positive supply (+5 V, pin 14).',
    },
    guideSections: [
      {
        title: 'Nines Complement and BCD Subtraction',
        paragraphs: [
          'To subtract two BCD digits: compute the nines complement of the subtrahend, add 1 (tens complement), then add to the minuend using a BCD adder. The 74x458 handles the first step automatically.',
          'Example: 7 − 3 = 7 + (9-3+1) = 7 + 7 = 14 → carry=1, result=4.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'A0',  type: 'input' },
      { pin:  2, name: 'A1',  type: 'input' },
      { pin:  3, name: 'A2',  type: 'input' },
      { pin:  4, name: 'A3',  type: 'input' },
      { pin:  5, name: 'ZEn', type: 'input' },
      { pin:  6, name: 'Y0',  type: 'output' },
      { pin:  7, name: 'GND', type: 'power' },
      { pin:  8, name: 'Y1',  type: 'output' },
      { pin:  9, name: 'Y2',  type: 'output' },
      { pin: 10, name: 'Y3',  type: 'output' },
      { pin: 11, name: 'NC1', type: 'nc' },
      { pin: 12, name: 'NC2', type: 'nc' },
      { pin: 13, name: 'NC3', type: 'nc' },
      { pin: 14, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'NINES_COMPLEMENT',
        inputs:  ['A0','A1','A2','A3','ZEn'],
        outputs: ['Y0','Y1','Y2','Y3'] },
    ],
  },

  // ── 74x460: 10 bit comparator ────────────────────────────────────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits */
  '74x460': {
    name: '74x460',
    simpleName: '10 bit Comparator',
    description: '10 bit identity comparator (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    tags: ['comparator', '10 bit', 'identity'],
    guideOverview: 'The 74x460 is a 10 bit identity comparator. It compares two 10 bit words (A0-A9 vs B0-B9) bit by bit and asserts the single AEQB output when all ten pairs match. An output enable (OEn) tri states the AEQB output. Wider than the 4 bit 74x85, it is useful for address match detection in 10 bit address spaces.',
    guidePinDescriptions: {
      'A0':   'Comparator A bit 0.',
      'A1':   'Comparator A bit 1.',
      'A2':   'Comparator A bit 2.',
      'A3':   'Comparator A bit 3.',
      'A4':   'Comparator A bit 4.',
      'A5':   'Comparator A bit 5.',
      'A6':   'Comparator A bit 6.',
      'A7':   'Comparator A bit 7.',
      'A8':   'Comparator A bit 8.',
      'A9':   'Comparator A bit 9 (MSB).',
      'OEn':  'Output Enable (active LOW). When HIGH, AEQB is tri stated.',
      'GND':  'Ground reference (pin 12).',
      'AEQB': 'A equals B output. HIGH when A[9:0] = B[9:0].',
      'B0':   'Comparator B bit 0.',
      'B1':   'Comparator B bit 1.',
      'B2':   'Comparator B bit 2.',
      'B3':   'Comparator B bit 3.',
      'B4':   'Comparator B bit 4.',
      'B5':   'Comparator B bit 5.',
      'B6':   'Comparator B bit 6.',
      'B7':   'Comparator B bit 7.',
      'B8':   'Comparator B bit 8.',
      'B9':   'Comparator B bit 9.',
      'VCC':  'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: '10 bit Address Match Detector',
        paragraphs: [
          'The AEQB output is a single flag this chip does not provide magnitude comparison (A>B, A<B). For magnitude comparison, use 74x85 or cascade multiple 74x85s.',
          'Typical use: connect A0-A9 to the CPU address bus and B0-B9 to switch selectable address constants. AEQB goes HIGH to select a memory region.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'A0',   type: 'input' },
      { pin:  2, name: 'A1',   type: 'input' },
      { pin:  3, name: 'A2',   type: 'input' },
      { pin:  4, name: 'A3',   type: 'input' },
      { pin:  5, name: 'A4',   type: 'input' },
      { pin:  6, name: 'A5',   type: 'input' },
      { pin:  7, name: 'A6',   type: 'input' },
      { pin:  8, name: 'A7',   type: 'input' },
      { pin:  9, name: 'A8',   type: 'input' },
      { pin: 10, name: 'A9',   type: 'input' },
      { pin: 11, name: 'OEn',  type: 'input' },
      { pin: 12, name: 'GND',  type: 'power' },
      { pin: 13, name: 'AEQB', type: 'output' },
      { pin: 14, name: 'B0',   type: 'input' },
      { pin: 15, name: 'B1',   type: 'input' },
      { pin: 16, name: 'B2',   type: 'input' },
      { pin: 17, name: 'B3',   type: 'input' },
      { pin: 18, name: 'B4',   type: 'input' },
      { pin: 19, name: 'B5',   type: 'input' },
      { pin: 20, name: 'B6',   type: 'input' },
      { pin: 21, name: 'B7',   type: 'input' },
      { pin: 22, name: 'B8',   type: 'input' },
      { pin: 23, name: 'B9',   type: 'input' },
      { pin: 24, name: 'VCC',  type: 'power' },
    ],
    gates: [
      { type: 'COMPARATOR_10BIT',
        inputs:  ['A0','A1','A2','A3','A4','A5','A6','A7','A8','A9',
                  'B0','B1','B2','B3','B4','B5','B6','B7','B8','B9','OEn'],
        outputs: ['AEQB'] },
    ],
  },

  // ── 74461: 8 bit presettable binary counter ──────────────────────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Counter_(digital)
     Wikipedia: https://en.wikipedia.org/wiki/Three-state_logic */
  '74x461': {
    name: '74x461',
    simpleName: '8 bit Presettable Binary Counter',
    description: '8 bit presettable cascadable binary counter with tri state outputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    sequential: true,
    tags: ['counter', '8 bit', 'presettable', 'binary', 'tri state'],
    guideOverview: 'The 74x461 is an 8 bit presettable synchronous binary counter with tri state outputs and ripple carry output (RCO). LOADn (active LOW) parallel loads P0-P7; CLRn resets asynchronously; ENP and ENT enable counting; RCO goes HIGH when the counter overflows from 255 to 0, allowing cascading.',
    guidePinDescriptions: {
      'OEn':   'Output Enable (active LOW). When HIGH, Q1-Q7 are tri stated.',
      'P0':    'Preset data bit 0.',
      'P1':    'Preset data bit 1.',
      'P2':    'Preset data bit 2.',
      'P3':    'Preset data bit 3.',
      'P4':    'Preset data bit 4.',
      'P5':    'Preset data bit 5.',
      'P6':    'Preset data bit 6.',
      'P7':    'Preset data bit 7.',
      'ENP':   'Count Enable Parallel. Must be HIGH with ENT to count.',
      'ENT':   'Count Enable Trickle. Must be HIGH with ENP to count. Also drives RCO.',
      'GND':   'Ground reference (pin 12).',
      'RCO':   'Ripple Carry Output. HIGH when count=255 and ENT is HIGH.',
      'LOADn': 'Parallel Load (active LOW). On rising CLK loads P0-P7.',
      'CLK':   'Clock (rising edge).',
      'CLRn':  'Asynchronous Clear (active LOW).',
      'Q7':    'Output bit 7 (MSB).',
      'Q6':    'Output bit 6.',
      'Q5':    'Output bit 5.',
      'Q4':    'Output bit 4.',
      'Q3':    'Output bit 3.',
      'Q2':    'Output bit 2.',
      'Q1':    'Output bit 1.',
      'VCC':   'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: '8 bit Counter Cascading',
        paragraphs: [
          'Connect RCO of one 74x461 to ENT of the next for 16 bit, 24 bit, or wider counters. The ENP of each downstream stage should be connected to the RCO of the upstream stage; ENT should be a separate cascaded carry chain.',
          'The parallel load allows arbitrary starting points useful for event timers that count down from a preset value to zero.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'OEn',  type: 'input' },
      { pin:  2, name: 'P0',   type: 'input' },
      { pin:  3, name: 'P1',   type: 'input' },
      { pin:  4, name: 'P2',   type: 'input' },
      { pin:  5, name: 'P3',   type: 'input' },
      { pin:  6, name: 'P4',   type: 'input' },
      { pin:  7, name: 'P5',   type: 'input' },
      { pin:  8, name: 'P6',   type: 'input' },
      { pin:  9, name: 'P7',   type: 'input' },
      { pin: 10, name: 'ENP',  type: 'input' },
      { pin: 11, name: 'ENT',  type: 'input' },
      { pin: 12, name: 'GND',  type: 'power' },
      { pin: 13, name: 'RCO',  type: 'output' },
      { pin: 14, name: 'LOADn',type: 'input' },
      { pin: 15, name: 'CLK',  type: 'input' },
      { pin: 16, name: 'CLRn', type: 'input' },
      { pin: 17, name: 'Q7',   type: 'output' },
      { pin: 18, name: 'Q6',   type: 'output' },
      { pin: 19, name: 'Q5',   type: 'output' },
      { pin: 20, name: 'Q4',   type: 'output' },
      { pin: 21, name: 'Q3',   type: 'output' },
      { pin: 22, name: 'Q2',   type: 'output' },
      { pin: 23, name: 'Q1',   type: 'output' },
      { pin: 24, name: 'VCC',  type: 'power' },
    ],
    gates: [
      { type: 'COUNTER_8BIT_PRESET',
        inputs:  ['CLK','CLRn','LOADn','ENP','ENT','OEn','P0','P1','P2','P3','P4','P5','P6','P7'],
        outputs: ['Q1','Q2','Q3','Q4','Q5','Q6','Q7','RCO'] },
    ],
  },

};
// end of CHIPS_BLOCK_26
