// Chip definitions block 40
// Chips: 74802 74803, 74804 74805, 74807 74808, 74810 74811,
//        74817 74819, 74821 74825

export const CHIPS_BLOCK_40 = {

  // ── 74802: Triple 4 input OR/NOR drivers (20-pin) ────────────────────────
  /* Primary source: Texas Instruments, 74802 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74as802.pdf */
  '74802': {
    name: '74x802',
    simpleName: 'Triple 4 Input OR/NOR Driver',
    description: 'Triple 4 input OR/NOR drivers (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74as802.pdf',
    tags: ['OR', 'NOR', 'gate', 'driver', 'quad-input', 'stub'],
    guideOverview: 'The 74x802 contains three 4 input logic sections, each providing both OR and NOR outputs. This dual-polarity output style is useful in control logic because you can route either active HIGH or active LOW forms without adding inverters.',
    guidePinDescriptions: {
      'A0':  'Input A for channel 0.',
      'B0':  'Input B for channel 0.',
      'C0':  'Input C for channel 0.',
      'D0':  'Input D for channel 0.',
      'Y0n': 'NOR output for channel 0 (inverted OR).',
      'Y0':  'OR output for channel 0.',
      'A1':  'Input A for channel 1.',
      'B1':  'Input B for channel 1.',
      'C1':  'Input C for channel 1.',
      'GND': 'Ground reference (pin 10).',
      'D1':  'Input D for channel 1.',
      'Y1n': 'NOR output for channel 1.',
      'Y1':  'OR output for channel 1.',
      'A2':  'Input A for channel 2.',
      'B2':  'Input B for channel 2.',
      'C2':  'Input C for channel 2.',
      'D2':  'Input D for channel 2.',
      'Y2n': 'NOR output for channel 2.',
      'Y2':  'OR output for channel 2.',
      'VCC': 'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'OR and NOR in One Package',
        formulas: [
          'Y = A + B + C + D',
          'Yn = ~(A + B + C + D)',
        ],
        paragraphs: [
          'Providing both polarities from the same internal logic saves package count in decode and arbitration networks.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'A0',  type: 'input'  },
      { pin:  2, name: 'B0',  type: 'input'  },
      { pin:  3, name: 'C0',  type: 'input'  },
      { pin:  4, name: 'D0',  type: 'input'  },
      { pin:  5, name: 'Y0n', type: 'output' },
      { pin:  6, name: 'Y0',  type: 'output' },
      { pin:  7, name: 'A1',  type: 'input'  },
      { pin:  8, name: 'B1',  type: 'input'  },
      { pin:  9, name: 'C1',  type: 'input'  },
      { pin: 10, name: 'GND', type: 'power'  },
      { pin: 11, name: 'D1',  type: 'input'  },
      { pin: 12, name: 'Y1n', type: 'output' },
      { pin: 13, name: 'Y1',  type: 'output' },
      { pin: 14, name: 'A2',  type: 'input'  },
      { pin: 15, name: 'B2',  type: 'input'  },
      { pin: 16, name: 'C2',  type: 'input'  },
      { pin: 17, name: 'D2',  type: 'input'  },
      { pin: 18, name: 'Y2n', type: 'output' },
      { pin: 19, name: 'Y2',  type: 'output' },
      { pin: 20, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['A0','B0','C0','D0','A1','B1','C1','D1','A2','B2','C2','D2'], outputs: ['Y0','Y0n','Y1','Y1n','Y2','Y2n'] },
    ],
  },


  // ── 74803: Quad D flip-flop (14-pin) ─────────────────────────────────────
  /* Primary source: 74803 datasheet   URL not yet verified.
     https://en.wikipedia.org/wiki/Flip-flop_(electronics) */
  '74803': {
    name: '74x803',
    simpleName: 'Quad D Flip-Flop',
    description: 'Quad D-type flip-flops with common clock and asynchronous clear (14-pin)',
    pins: 14, vcc: 14, gnd: 7,
    datasheet: null,
    tags: ['flip-flop', 'D-type', 'quad', 'stub'],
    sequential: true,
    guideOverview: 'The 74x803 contains four independent D-type flip-flops sharing a common clock (CLK) and asynchronous clear (CLRn). On each rising clock edge, each D input is sampled and its value transferred to the corresponding Q output. CLRn immediately resets all four Q outputs to LOW regardless of the clock state.',
    guidePinDescriptions: {
      'CLRn': 'Asynchronous clear (active LOW). Drives all Q outputs LOW immediately.',
      'D0':   'Data input for flip-flop 0.',
      'Q0':   'Output of flip-flop 0.',
      'D1':   'Data input for flip-flop 1.',
      'Q1':   'Output of flip-flop 1.',
      'D2':   'Data input for flip-flop 2.',
      'GND':  'Ground reference (pin 7).',
      'Q2':   'Output of flip-flop 2.',
      'CLK':  'Common clock input (rising edge triggered).',
      'Q3':   'Output of flip-flop 3.',
      'D3':   'Data input for flip-flop 3.',
      'NC1':  'No connect.',
      'NC2':  'No connect.',
      'VCC':  'Positive supply (+5 V, pin 14).',
    },
    guideSections: [
      {
        title: 'Common Clock Quad D FF',
        paragraphs: [
          'All four flip-flops share a single CLK and CLRn to minimize pin count. Common-clock operation ensures all four outputs update on the same edge, making this useful for capturing 4 bit nibble data or controlling four independent state outputs synchronously.',
        ],
        note: 'Functional behavior is represented as a generic stub in simulation.',
      },
    ],
    pinout: [
      { pin:  1, name: 'CLRn', type: 'input'  },
      { pin:  2, name: 'D0',   type: 'input'  },
      { pin:  3, name: 'Q0',   type: 'output' },
      { pin:  4, name: 'D1',   type: 'input'  },
      { pin:  5, name: 'Q1',   type: 'output' },
      { pin:  6, name: 'D2',   type: 'input'  },
      { pin:  7, name: 'GND',  type: 'power'  },
      { pin:  8, name: 'Q2',   type: 'output' },
      { pin:  9, name: 'CLK',  type: 'input'  },
      { pin: 10, name: 'Q3',   type: 'output' },
      { pin: 11, name: 'D3',   type: 'input'  },
      { pin: 12, name: 'NC1',  type: 'nc'     },
      { pin: 13, name: 'NC2',  type: 'nc'     },
      { pin: 14, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['CLRn','CLK','D0','D1','D2','D3'], outputs: ['Q0','Q1','Q2','Q3'] },
    ],
  },

  // ── 74804: Hex 2 input NAND drivers (20-pin) ─────────────────────────────
  /* Primary source: Texas Instruments, 74804 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74als804a.pdf */
  '74804': {
    name: '74x804',
    simpleName: 'Hex 2 Input NAND Driver',
    description: 'Hex 2 input NAND drivers (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74als804a.pdf',
    tags: ['NAND', 'gate', 'driver', 'hex', 'stub'],
    guideOverview: 'The 74x804 is a hex 2 input NAND driver. It packs six independent NAND gates optimized for higher drive capability than simple logic gate arrays. NAND is a universal gate and can implement nearly any combinational logic function.',
    guidePinDescriptions: {
      'A0':  'Input A for gate 0.',
      'B0':  'Input B for gate 0.',
      'Y0n': 'NAND output for gate 0.',
      'A1':  'Input A for gate 1.',
      'B1':  'Input B for gate 1.',
      'Y1n': 'NAND output for gate 1.',
      'A2':  'Input A for gate 2.',
      'B2':  'Input B for gate 2.',
      'Y2n': 'NAND output for gate 2.',
      'GND': 'Ground reference (pin 10).',
      'Y3n': 'NAND output for gate 3.',
      'B3':  'Input B for gate 3.',
      'A3':  'Input A for gate 3.',
      'Y4n': 'NAND output for gate 4.',
      'B4':  'Input B for gate 4.',
      'A4':  'Input A for gate 4.',
      'Y5n': 'NAND output for gate 5.',
      'B5':  'Input B for gate 5.',
      'A5':  'Input A for gate 5.',
      'VCC': 'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'Hex NAND Driver',
        paragraphs: [
          'With six channels, this part is often used as a general-purpose glue-logic workhorse for enables, chip-select conditioning, and state decoding.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'A0',  type: 'input'  },
      { pin:  2, name: 'B0',  type: 'input'  },
      { pin:  3, name: 'Y0n', type: 'output' },
      { pin:  4, name: 'A1',  type: 'input'  },
      { pin:  5, name: 'B1',  type: 'input'  },
      { pin:  6, name: 'Y1n', type: 'output' },
      { pin:  7, name: 'A2',  type: 'input'  },
      { pin:  8, name: 'B2',  type: 'input'  },
      { pin:  9, name: 'Y2n', type: 'output' },
      { pin: 10, name: 'GND', type: 'power'  },
      { pin: 11, name: 'Y3n', type: 'output' },
      { pin: 12, name: 'B3',  type: 'input'  },
      { pin: 13, name: 'A3',  type: 'input'  },
      { pin: 14, name: 'Y4n', type: 'output' },
      { pin: 15, name: 'B4',  type: 'input'  },
      { pin: 16, name: 'A4',  type: 'input'  },
      { pin: 17, name: 'Y5n', type: 'output' },
      { pin: 18, name: 'B5',  type: 'input'  },
      { pin: 19, name: 'A5',  type: 'input'  },
      { pin: 20, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['A0','B0','A1','B1','A2','B2','A3','B3','A4','B4','A5','B5'], outputs: ['Y0n','Y1n','Y2n','Y3n','Y4n','Y5n'] },
    ],
  },

  // ── 74805: Hex 2 input NOR drivers (20-pin) ──────────────────────────────
  /* Primary source: Texas Instruments, 74805 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74als805a.pdf */
  '74805': {
    name: '74x805',
    simpleName: 'Hex 2 Input NOR Driver',
    description: 'Hex 2 input NOR drivers (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74als805a.pdf',
    tags: ['NOR', 'gate', 'driver', 'hex', 'stub'],
    guideOverview: 'The 74x805 is the NOR-gate counterpart to the 74x804, providing six 2 input NOR drivers. NOR is also universal logic and is common in active LOW control networks where OR-then-invert behavior appears naturally.',
    guidePinDescriptions: {
      'A0':  'Input A for gate 0.',
      'B0':  'Input B for gate 0.',
      'Y0n': 'NOR output for gate 0.',
      'A1':  'Input A for gate 1.',
      'B1':  'Input B for gate 1.',
      'Y1n': 'NOR output for gate 1.',
      'A2':  'Input A for gate 2.',
      'B2':  'Input B for gate 2.',
      'Y2n': 'NOR output for gate 2.',
      'GND': 'Ground reference (pin 10).',
      'Y3n': 'NOR output for gate 3.',
      'B3':  'Input B for gate 3.',
      'A3':  'Input A for gate 3.',
      'Y4n': 'NOR output for gate 4.',
      'B4':  'Input B for gate 4.',
      'A4':  'Input A for gate 4.',
      'Y5n': 'NOR output for gate 5.',
      'B5':  'Input B for gate 5.',
      'A5':  'Input A for gate 5.',
      'VCC': 'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'Hex NOR Driver',
        paragraphs: [
          'NOR-heavy logic is common in asynchronous control and active LOW decode trees. A six-gate package can collapse many small logic equations into one IC.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'A0',  type: 'input'  },
      { pin:  2, name: 'B0',  type: 'input'  },
      { pin:  3, name: 'Y0n', type: 'output' },
      { pin:  4, name: 'A1',  type: 'input'  },
      { pin:  5, name: 'B1',  type: 'input'  },
      { pin:  6, name: 'Y1n', type: 'output' },
      { pin:  7, name: 'A2',  type: 'input'  },
      { pin:  8, name: 'B2',  type: 'input'  },
      { pin:  9, name: 'Y2n', type: 'output' },
      { pin: 10, name: 'GND', type: 'power'  },
      { pin: 11, name: 'Y3n', type: 'output' },
      { pin: 12, name: 'B3',  type: 'input'  },
      { pin: 13, name: 'A3',  type: 'input'  },
      { pin: 14, name: 'Y4n', type: 'output' },
      { pin: 15, name: 'B4',  type: 'input'  },
      { pin: 16, name: 'A4',  type: 'input'  },
      { pin: 17, name: 'Y5n', type: 'output' },
      { pin: 18, name: 'B5',  type: 'input'  },
      { pin: 19, name: 'A5',  type: 'input'  },
      { pin: 20, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['A0','B0','A1','B1','A2','B2','A3','B3','A4','B4','A5','B5'], outputs: ['Y0n','Y1n','Y2n','Y3n','Y4n','Y5n'] },
    ],
  },

  // ── 74807: 1-to-10 clock driver (20-pin) ─────────────────────────────────
  /* Primary source: Texas Instruments, 74807 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/idt74fct807.pdf */
  '74807': {
    name: '74x807',
    simpleName: '1-to-10 Clock Driver',
    description: '1-to-10 clock driver (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/idt74fct807.pdf',
    tags: ['clock', 'driver', 'fanout', 'stub'],
    guideOverview: 'The 74x807 is a 1-to-10 clock fanout driver. A single clock input is buffered and distributed to ten outputs with matched timing intent. This is used to distribute one timing source across many loads while minimizing skew and loading on the source oscillator.',
    guidePinDescriptions: {
      'OEn': 'Output-enable control. Disable all fanout outputs when inactive.',
      'CLK': 'Clock input source to be distributed.',
      'Y0':  'Clock output channel 0.',
      'Y1':  'Clock output channel 1.',
      'Y2':  'Clock output channel 2.',
      'Y3':  'Clock output channel 3.',
      'Y4':  'Clock output channel 4.',
      'Y5':  'Clock output channel 5.',
      'Y6':  'Clock output channel 6.',
      'GND': 'Ground reference (pin 10).',
      'Y7':  'Clock output channel 7.',
      'Y8':  'Clock output channel 8.',
      'Y9':  'Clock output channel 9.',
      'NC':  'No connect.',
      'VCC': 'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'Clock Distribution',
        paragraphs: [
          'Clock fanout buffers isolate the oscillator from heavy capacitive loading and deliver cleaner edges to each destination. This improves timing reliability in multi-device synchronous systems.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'OEn', type: 'input'  },
      { pin:  2, name: 'CLK', type: 'input'  },
      { pin:  3, name: 'Y0',  type: 'output' },
      { pin:  4, name: 'Y1',  type: 'output' },
      { pin:  5, name: 'Y2',  type: 'output' },
      { pin:  6, name: 'Y3',  type: 'output' },
      { pin:  7, name: 'Y4',  type: 'output' },
      { pin:  8, name: 'Y5',  type: 'output' },
      { pin:  9, name: 'Y6',  type: 'output' },
      { pin: 10, name: 'GND', type: 'power'  },
      { pin: 11, name: 'Y7',  type: 'output' },
      { pin: 12, name: 'Y8',  type: 'output' },
      { pin: 13, name: 'Y9',  type: 'output' },
      { pin: 14, name: 'NC',  type: 'nc'     },
      { pin: 15, name: 'NC',  type: 'nc'     },
      { pin: 16, name: 'NC',  type: 'nc'     },
      { pin: 17, name: 'NC',  type: 'nc'     },
      { pin: 18, name: 'NC',  type: 'nc'     },
      { pin: 19, name: 'NC',  type: 'nc'     },
      { pin: 20, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','CLK'], outputs: ['Y0','Y1','Y2','Y3','Y4','Y5','Y6','Y7','Y8','Y9'] },
    ],
  },

  // ── 74808: Hex 2 input AND drivers (20-pin) ──────────────────────────────
  /* Primary source: Texas Instruments, 74808 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74as808b.pdf */
  '74808': {
    name: '74x808',
    simpleName: 'Hex 2 Input AND Driver',
    description: 'Hex 2 input AND drivers (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74as808b.pdf',
    tags: ['AND', 'gate', 'driver', 'hex', 'stub'],
    guideOverview: 'The 74x808 provides six independent 2 input AND driver gates. It is used for enable qualification, control masking, and straightforward combinational logic where totem-pole drive is needed.',
    guidePinDescriptions: {
      'A0':  'Input A for gate 0.',
      'B0':  'Input B for gate 0.',
      'Y0':  'AND output for gate 0.',
      'A1':  'Input A for gate 1.',
      'B1':  'Input B for gate 1.',
      'Y1':  'AND output for gate 1.',
      'A2':  'Input A for gate 2.',
      'B2':  'Input B for gate 2.',
      'Y2':  'AND output for gate 2.',
      'GND': 'Ground reference (pin 10).',
      'Y3':  'AND output for gate 3.',
      'B3':  'Input B for gate 3.',
      'A3':  'Input A for gate 3.',
      'Y4':  'AND output for gate 4.',
      'B4':  'Input B for gate 4.',
      'A4':  'Input A for gate 4.',
      'Y5':  'AND output for gate 5.',
      'B5':  'Input B for gate 5.',
      'A5':  'Input A for gate 5.',
      'VCC': 'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'Hex AND Functions',
        formulas: [
          'Y = A * B',
        ],
        paragraphs: [
          'AND drivers are widely used to gate clocks, qualifies, and control strobes with one or more enable conditions.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'A0',  type: 'input'  },
      { pin:  2, name: 'B0',  type: 'input'  },
      { pin:  3, name: 'Y0',  type: 'output' },
      { pin:  4, name: 'A1',  type: 'input'  },
      { pin:  5, name: 'B1',  type: 'input'  },
      { pin:  6, name: 'Y1',  type: 'output' },
      { pin:  7, name: 'A2',  type: 'input'  },
      { pin:  8, name: 'B2',  type: 'input'  },
      { pin:  9, name: 'Y2',  type: 'output' },
      { pin: 10, name: 'GND', type: 'power'  },
      { pin: 11, name: 'Y3',  type: 'output' },
      { pin: 12, name: 'B3',  type: 'input'  },
      { pin: 13, name: 'A3',  type: 'input'  },
      { pin: 14, name: 'Y4',  type: 'output' },
      { pin: 15, name: 'B4',  type: 'input'  },
      { pin: 16, name: 'A4',  type: 'input'  },
      { pin: 17, name: 'Y5',  type: 'output' },
      { pin: 18, name: 'B5',  type: 'input'  },
      { pin: 19, name: 'A5',  type: 'input'  },
      { pin: 20, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['A0','B0','A1','B1','A2','B2','A3','B3','A4','B4','A5','B5'], outputs: ['Y0','Y1','Y2','Y3','Y4','Y5'] },
    ],
  },

  // ── 74810: Quad 2 input XNOR gates (14-pin) ──────────────────────────────
  /* Primary source: Texas Instruments, 74810 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74als810.pdf */
  '74810': {
    name: '74x810',
    simpleName: 'Quad 2 Input XNOR',
    description: 'Quad 2 input XNOR gates (14-pin)',
    pins: 14, vcc: 14, gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74als810.pdf',
    tags: ['XNOR', 'gate', 'quad', 'stub'],
    guideOverview: 'The 74x810 contains four 2 input XNOR gates. XNOR outputs HIGH when inputs are equal, making it ideal for equality detection, parity checking, and bit-by-bit comparators.',
    guidePinDescriptions: {
      'A0':  'Input A for gate 0.',
      'B0':  'Input B for gate 0.',
      'Y0':  'XNOR output for gate 0.',
      'A1':  'Input A for gate 1.',
      'B1':  'Input B for gate 1.',
      'Y1':  'XNOR output for gate 1.',
      'GND': 'Ground reference (pin 7).',
      'Y2':  'XNOR output for gate 2.',
      'B2':  'Input B for gate 2.',
      'A2':  'Input A for gate 2.',
      'Y3':  'XNOR output for gate 3.',
      'B3':  'Input B for gate 3.',
      'A3':  'Input A for gate 3.',
      'VCC': 'Positive supply (+5 V, pin 14).',
    },
    guideSections: [
      {
        title: 'Equality Logic',
        formulas: [
          'Y = A XNOR B = ~(A XOR B)',
        ],
        paragraphs: [
          'Cascading XNOR stages and ANDing their outputs forms an n-bit equality comparator.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'A0',  type: 'input'  },
      { pin:  2, name: 'B0',  type: 'input'  },
      { pin:  3, name: 'Y0',  type: 'output' },
      { pin:  4, name: 'A1',  type: 'input'  },
      { pin:  5, name: 'B1',  type: 'input'  },
      { pin:  6, name: 'Y1',  type: 'output' },
      { pin:  7, name: 'GND', type: 'power'  },
      { pin:  8, name: 'Y2',  type: 'output' },
      { pin:  9, name: 'B2',  type: 'input'  },
      { pin: 10, name: 'A2',  type: 'input'  },
      { pin: 11, name: 'Y3',  type: 'output' },
      { pin: 12, name: 'B3',  type: 'input'  },
      { pin: 13, name: 'A3',  type: 'input'  },
      { pin: 14, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['A0','B0','A1','B1','A2','B2','A3','B3'], outputs: ['Y0','Y1','Y2','Y3'] },
    ],
  },

  // ── 74811: Quad 2 input XNOR gates, OC (14-pin) ──────────────────────────
  /* Primary source: Texas Instruments, 74811 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/dm74als811.pdf */
  '74811': {
    name: '74x811',
    simpleName: 'Quad 2 Input XNOR (OC)',
    description: 'Quad 2 input XNOR gates with open-collector outputs (14-pin)',
    pins: 14, vcc: 14, gnd: 7,
    openCollector: true,
    datasheet: 'https://www.ti.com/lit/ds/symlink/dm74als811.pdf',
    tags: ['XNOR', 'gate', 'quad', 'open-collector', 'stub'],
    guideOverview: 'The 74x811 is an open-collector version of the quad XNOR function. It performs equality logic but outputs can be wire-ANDed across multiple chips, requiring external pull ups.',
    guidePinDescriptions: {
      'A0':  'Input A for gate 0.',
      'B0':  'Input B for gate 0.',
      'Y0':  'Open-collector XNOR output for gate 0.',
      'A1':  'Input A for gate 1.',
      'B1':  'Input B for gate 1.',
      'Y1':  'Open-collector XNOR output for gate 1.',
      'GND': 'Ground reference (pin 7).',
      'Y2':  'Open-collector XNOR output for gate 2.',
      'B2':  'Input B for gate 2.',
      'A2':  'Input A for gate 2.',
      'Y3':  'Open-collector XNOR output for gate 3.',
      'B3':  'Input B for gate 3.',
      'A3':  'Input A for gate 3.',
      'VCC': 'Positive supply (+5 V, pin 14).',
    },
    guideSections: [
      {
        title: 'OC Equality Networks',
        paragraphs: [
          'Open-collector XNOR outputs can be combined on shared lines to create multi-device compare conditions where all stages must agree before a line releases HIGH.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'A0',  type: 'input'  },
      { pin:  2, name: 'B0',  type: 'input'  },
      { pin:  3, name: 'Y0',  type: 'output' },
      { pin:  4, name: 'A1',  type: 'input'  },
      { pin:  5, name: 'B1',  type: 'input'  },
      { pin:  6, name: 'Y1',  type: 'output' },
      { pin:  7, name: 'GND', type: 'power'  },
      { pin:  8, name: 'Y2',  type: 'output' },
      { pin:  9, name: 'B2',  type: 'input'  },
      { pin: 10, name: 'A2',  type: 'input'  },
      { pin: 11, name: 'Y3',  type: 'output' },
      { pin: 12, name: 'B3',  type: 'input'  },
      { pin: 13, name: 'A3',  type: 'input'  },
      { pin: 14, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['A0','B0','A1','B1','A2','B2','A3','B3'], outputs: ['Y0','Y1','Y2','Y3'] },
    ],
  },

  // ── 74817: GTL+↔LV-TTL fanout driver, TRI+OC (24-pin) ───────────────────
  /* Primary source: Texas Instruments, 74817 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74gtlp817.pdf */
  '74817': {
    name: '74x817',
    simpleName: 'GTL+/LV-TTL Fanout Driver',
    description: 'GTL+ to LV-TTL 1-to-6 fanout / LV-TTL to GTL+ 1-to-2 fanout driver (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74gtlp817.pdf',
    tags: ['driver', 'fanout', 'GTL', 'LV-TTL', 'stub'],
    guideOverview: 'The 74x817 is a mixed-standard fanout driver for GTL+ and LV-TTL style buses. It supports one-to-many distribution in one direction and reduced fanout in the other, helping interface low-voltage terminated buses with TTL-like logic domains.',
    guidePinDescriptions: {
      'OEn': 'Output-enable control for driver stages.',
      'IN':  'Main input signal to be fanned out.',
      'Y0':  'Fanout output 0.',
      'Y1':  'Fanout output 1.',
      'Y2':  'Fanout output 2.',
      'Y3':  'Fanout output 3.',
      'Y4':  'Fanout output 4.',
      'Y5':  'Fanout output 5.',
      'NC':  'No connect.',
      'GND': 'Ground reference (pin 12).',
      'B0':  'Secondary fanout/bus output 0.',
      'B1':  'Secondary fanout/bus output 1.',
      'VCC': 'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: 'Bus-Level Translation and Fanout',
        paragraphs: [
          'GTL and TTL families have different threshold and termination assumptions. Dedicated fanout translators like this reduce signal integrity issues when one source must drive many loads across mixed standards.',
        ],
        note: 'Detailed analog bus behavior is abstracted by a stub model.',
      },
    ],
    pinout: [
      { pin:  1, name: 'OEn',  type: 'input'  },
      { pin:  2, name: 'IN',   type: 'input'  },
      { pin:  3, name: 'Y0',   type: 'output' },
      { pin:  4, name: 'Y1',   type: 'output' },
      { pin:  5, name: 'Y2',   type: 'output' },
      { pin:  6, name: 'Y3',   type: 'output' },
      { pin:  7, name: 'Y4',   type: 'output' },
      { pin:  8, name: 'Y5',   type: 'output' },
      { pin:  9, name: 'NC',   type: 'nc'     },
      { pin: 10, name: 'NC',   type: 'nc'     },
      { pin: 11, name: 'NC',   type: 'nc'     },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'NC',   type: 'nc'     },
      { pin: 14, name: 'B0',   type: 'output' },
      { pin: 15, name: 'B1',   type: 'output' },
      { pin: 16, name: 'NC',   type: 'nc'     },
      { pin: 17, name: 'NC',   type: 'nc'     },
      { pin: 18, name: 'NC',   type: 'nc'     },
      { pin: 19, name: 'NC',   type: 'nc'     },
      { pin: 20, name: 'NC',   type: 'nc'     },
      { pin: 21, name: 'NC',   type: 'nc'     },
      { pin: 22, name: 'NC',   type: 'nc'     },
      { pin: 23, name: 'NC',   type: 'nc'     },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','IN'], outputs: ['Y0','Y1','Y2','Y3','Y4','Y5','B0','B1'] },
    ],
  },

  // ── 74818: 8 bit diagnostic register, TRI (24-pin) ───────────────────────
  /* Primary source: Texas Instruments, 74818 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/74act818.pdf */
  '74818': {
    name: '74x818',
    simpleName: '8 bit Diagnostic Register (TRI)',
    description: '8 bit diagnostic register with three-state outputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: 'https://www.ti.com/lit/ds/symlink/74act818.pdf',
    tags: ['register', '8 bit', 'diagnostic', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x818 is an 8 bit diagnostic register with tri-state outputs. It captures and holds bus values for observation, testing, or pipeline checkpointing. Combined CLK and LE controls allow flexible capture timing in debug paths.',
    guidePinDescriptions: {
      'OEn': 'Output enable (active LOW).',
      'CLK': 'Clock input for edge-triggered capture stages.',
      'LE':  'Latch/enable control for capture behavior.',
      'D0':  'Diagnostic data input bit 0.',
      'D1':  'Diagnostic data input bit 1.',
      'D2':  'Diagnostic data input bit 2.',
      'D3':  'Diagnostic data input bit 3.',
      'D4':  'Diagnostic data input bit 4.',
      'D5':  'Diagnostic data input bit 5.',
      'D6':  'Diagnostic data input bit 6.',
      'D7':  'Diagnostic data input bit 7.',
      'GND': 'Ground reference (pin 12).',
      'Q7':  'Stored output bit 7.',
      'Q6':  'Stored output bit 6.',
      'Q5':  'Stored output bit 5.',
      'Q4':  'Stored output bit 4.',
      'Q3':  'Stored output bit 3.',
      'Q2':  'Stored output bit 2.',
      'Q1':  'Stored output bit 1.',
      'Q0':  'Stored output bit 0.',
      'NC':  'No connect.',
      'VCC': 'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: 'Diagnostic Register Purpose',
        paragraphs: [
          'Diagnostic registers let engineers capture internal bus states without permanently loading the datapath. During normal operation outputs can be tri-stated; during debug they can be read out for visibility.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'OEn', type: 'input'  },
      { pin:  2, name: 'CLK', type: 'input'  },
      { pin:  3, name: 'LE',  type: 'input'  },
      { pin:  4, name: 'D0',  type: 'input'  },
      { pin:  5, name: 'D1',  type: 'input'  },
      { pin:  6, name: 'D2',  type: 'input'  },
      { pin:  7, name: 'D3',  type: 'input'  },
      { pin:  8, name: 'D4',  type: 'input'  },
      { pin:  9, name: 'D5',  type: 'input'  },
      { pin: 10, name: 'D6',  type: 'input'  },
      { pin: 11, name: 'D7',  type: 'input'  },
      { pin: 12, name: 'GND', type: 'power'  },
      { pin: 13, name: 'Q7',  type: 'output' },
      { pin: 14, name: 'Q6',  type: 'output' },
      { pin: 15, name: 'Q5',  type: 'output' },
      { pin: 16, name: 'Q4',  type: 'output' },
      { pin: 17, name: 'Q3',  type: 'output' },
      { pin: 18, name: 'Q2',  type: 'output' },
      { pin: 19, name: 'Q1',  type: 'output' },
      { pin: 20, name: 'Q0',  type: 'output' },
      { pin: 21, name: 'NC',  type: 'nc'     },
      { pin: 22, name: 'NC',  type: 'nc'     },
      { pin: 23, name: 'NC',  type: 'nc'     },
      { pin: 24, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','CLK','LE','D0','D1','D2','D3','D4','D5','D6','D7'], outputs: ['Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7'] },
    ],
  },

  // ── 74819: 8 bit diagnostic/pipeline register, TRI (24-pin) ──────────────
  /* Primary source: Texas Instruments, 74819 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74als819.pdf */
  '74819': {
    name: '74x819',
    simpleName: '8 bit Diagnostic/Pipeline Reg (TRI)',
    description: '8 bit diagnostic / pipeline register with three-state outputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74als819.pdf',
    tags: ['register', '8 bit', 'diagnostic', 'pipeline', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x819 extends the diagnostic register concept with pipeline-oriented timing behavior. It can stage data between logic phases while still supporting debug/readout style tri-state outputs.',
    guidePinDescriptions: {
      'OEn': 'Output enable (active LOW).',
      'CLK': 'Clock input for registering data.',
      'LE':  'Latch/enable timing control.',
      'D0':  'Pipeline input bit 0.',
      'D1':  'Pipeline input bit 1.',
      'D2':  'Pipeline input bit 2.',
      'D3':  'Pipeline input bit 3.',
      'D4':  'Pipeline input bit 4.',
      'D5':  'Pipeline input bit 5.',
      'D6':  'Pipeline input bit 6.',
      'D7':  'Pipeline input bit 7.',
      'GND': 'Ground reference (pin 12).',
      'Q7':  'Registered output bit 7.',
      'Q6':  'Registered output bit 6.',
      'Q5':  'Registered output bit 5.',
      'Q4':  'Registered output bit 4.',
      'Q3':  'Registered output bit 3.',
      'Q2':  'Registered output bit 2.',
      'Q1':  'Registered output bit 1.',
      'Q0':  'Registered output bit 0.',
      'NC':  'No connect.',
      'VCC': 'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: 'Pipeline Registering',
        paragraphs: [
          'Pipeline registers break long combinational paths into shorter clocked stages, increasing maximum operating frequency and reducing timing closure complexity.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'OEn', type: 'input'  },
      { pin:  2, name: 'CLK', type: 'input'  },
      { pin:  3, name: 'LE',  type: 'input'  },
      { pin:  4, name: 'D0',  type: 'input'  },
      { pin:  5, name: 'D1',  type: 'input'  },
      { pin:  6, name: 'D2',  type: 'input'  },
      { pin:  7, name: 'D3',  type: 'input'  },
      { pin:  8, name: 'D4',  type: 'input'  },
      { pin:  9, name: 'D5',  type: 'input'  },
      { pin: 10, name: 'D6',  type: 'input'  },
      { pin: 11, name: 'D7',  type: 'input'  },
      { pin: 12, name: 'GND', type: 'power'  },
      { pin: 13, name: 'Q7',  type: 'output' },
      { pin: 14, name: 'Q6',  type: 'output' },
      { pin: 15, name: 'Q5',  type: 'output' },
      { pin: 16, name: 'Q4',  type: 'output' },
      { pin: 17, name: 'Q3',  type: 'output' },
      { pin: 18, name: 'Q2',  type: 'output' },
      { pin: 19, name: 'Q1',  type: 'output' },
      { pin: 20, name: 'Q0',  type: 'output' },
      { pin: 21, name: 'NC',  type: 'nc'     },
      { pin: 22, name: 'NC',  type: 'nc'     },
      { pin: 23, name: 'NC',  type: 'nc'     },
      { pin: 24, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','CLK','LE','D0','D1','D2','D3','D4','D5','D6','D7'], outputs: ['Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7'] },
    ],
  },

  // ── 74821: 10 bit bus interface flip-flop, TRI (24-pin) ──────────────────
  /* Primary source: Texas Instruments, 74821 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74as821a.pdf
     https://en.wikipedia.org/wiki/Flip-flop_(electronics) */
  '74821': {
    name: '74x821',
    simpleName: '10 bit Bus Interface FF (TRI)',
    description: '10 bit bus interface flip-flop with three-state outputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74as821a.pdf',
    tags: ['flip-flop', 'D-type', '10 bit', 'bus', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x821 is a 10 bit D-type bus-interface flip-flop with tri-state outputs. It captures D0-D9 on clock events and presents Q0-Q9 to the bus when enabled. This width is useful for address/control groupings wider than a byte.',
    guidePinDescriptions: {
      'OEn': 'Output enable (active LOW) for bus drive.',
      'D0':  'Data input bit 0.',
      'D1':  'Data input bit 1.',
      'D2':  'Data input bit 2.',
      'D3':  'Data input bit 3.',
      'D4':  'Data input bit 4.',
      'D5':  'Data input bit 5.',
      'D6':  'Data input bit 6.',
      'D7':  'Data input bit 7.',
      'D8':  'Data input bit 8.',
      'D9':  'Data input bit 9.',
      'GND': 'Ground reference (pin 12).',
      'CLK': 'Clock input for sampling D inputs.',
      'Q9':  'Registered output bit 9.',
      'Q8':  'Registered output bit 8.',
      'Q7':  'Registered output bit 7.',
      'Q6':  'Registered output bit 6.',
      'Q5':  'Registered output bit 5.',
      'Q4':  'Registered output bit 4.',
      'Q3':  'Registered output bit 3.',
      'Q2':  'Registered output bit 2.',
      'Q1':  'Registered output bit 1.',
      'Q0':  'Registered output bit 0.',
      'VCC': 'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: 'Wide Bus Interface Registers',
        paragraphs: [
          '10 bit registers are often used when a bus carries 8 data bits plus parity/status bits or split address/control fields. Tri-state outputs let many such devices share a common backplane.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'OEn', type: 'input'  },
      { pin:  2, name: 'D0',  type: 'input'  },
      { pin:  3, name: 'D1',  type: 'input'  },
      { pin:  4, name: 'D2',  type: 'input'  },
      { pin:  5, name: 'D3',  type: 'input'  },
      { pin:  6, name: 'D4',  type: 'input'  },
      { pin:  7, name: 'D5',  type: 'input'  },
      { pin:  8, name: 'D6',  type: 'input'  },
      { pin:  9, name: 'D7',  type: 'input'  },
      { pin: 10, name: 'D8',  type: 'input'  },
      { pin: 11, name: 'D9',  type: 'input'  },
      { pin: 12, name: 'GND', type: 'power'  },
      { pin: 13, name: 'CLK', type: 'input'  },
      { pin: 14, name: 'Q9',  type: 'output' },
      { pin: 15, name: 'Q8',  type: 'output' },
      { pin: 16, name: 'Q7',  type: 'output' },
      { pin: 17, name: 'Q6',  type: 'output' },
      { pin: 18, name: 'Q5',  type: 'output' },
      { pin: 19, name: 'Q4',  type: 'output' },
      { pin: 20, name: 'Q3',  type: 'output' },
      { pin: 21, name: 'Q2',  type: 'output' },
      { pin: 22, name: 'Q1',  type: 'output' },
      { pin: 23, name: 'Q0',  type: 'output' },
      { pin: 24, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','CLK','D0','D1','D2','D3','D4','D5','D6','D7','D8','D9'], outputs: ['Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7','Q8','Q9'] },
    ],
  },

  // ── 74822: 10 bit bus interface flip-flop, inverting inputs, TRI (24-pin) ─
  /* Primary source: Texas Instruments, 74822 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74as822.pdf
     https://en.wikipedia.org/wiki/Flip-flop_(electronics) */
  '74822': {
    name: '74x822',
    simpleName: '10 bit Bus Interface FF (Inv In, TRI)',
    description: '10 bit bus interface flip-flop with inverting inputs and three-state outputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74as822.pdf',
    tags: ['flip-flop', 'D-type', '10 bit', 'bus', 'inverting', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x822 is a 10 bit bus flip-flop variant with inverting input/logic convention compared to 74x821. It keeps the same width and tri-state bus function while matching active LOW or inverted data-path requirements.',
    guidePinDescriptions: {
      'OEn': 'Output enable (active LOW).',
      'D0':  'Data input bit 0.',
      'D1':  'Data input bit 1.',
      'D2':  'Data input bit 2.',
      'D3':  'Data input bit 3.',
      'D4':  'Data input bit 4.',
      'D5':  'Data input bit 5.',
      'D6':  'Data input bit 6.',
      'D7':  'Data input bit 7.',
      'D8':  'Data input bit 8.',
      'D9':  'Data input bit 9.',
      'GND': 'Ground reference (pin 12).',
      'CLK': 'Clock input.',
      'Q9':  'Registered output bit 9.',
      'Q8':  'Registered output bit 8.',
      'Q7':  'Registered output bit 7.',
      'Q6':  'Registered output bit 6.',
      'Q5':  'Registered output bit 5.',
      'Q4':  'Registered output bit 4.',
      'Q3':  'Registered output bit 3.',
      'Q2':  'Registered output bit 2.',
      'Q1':  'Registered output bit 1.',
      'Q0':  'Registered output bit 0.',
      'VCC': 'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: 'Inverting Bus FF Variant',
        paragraphs: [
          'Families often include inverted variants so designers can absorb polarity into one IC and avoid separate inverter stages, reducing skew and board area.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'OEn', type: 'input'  },
      { pin:  2, name: 'D0',  type: 'input'  },
      { pin:  3, name: 'D1',  type: 'input'  },
      { pin:  4, name: 'D2',  type: 'input'  },
      { pin:  5, name: 'D3',  type: 'input'  },
      { pin:  6, name: 'D4',  type: 'input'  },
      { pin:  7, name: 'D5',  type: 'input'  },
      { pin:  8, name: 'D6',  type: 'input'  },
      { pin:  9, name: 'D7',  type: 'input'  },
      { pin: 10, name: 'D8',  type: 'input'  },
      { pin: 11, name: 'D9',  type: 'input'  },
      { pin: 12, name: 'GND', type: 'power'  },
      { pin: 13, name: 'CLK', type: 'input'  },
      { pin: 14, name: 'Q9',  type: 'output' },
      { pin: 15, name: 'Q8',  type: 'output' },
      { pin: 16, name: 'Q7',  type: 'output' },
      { pin: 17, name: 'Q6',  type: 'output' },
      { pin: 18, name: 'Q5',  type: 'output' },
      { pin: 19, name: 'Q4',  type: 'output' },
      { pin: 20, name: 'Q3',  type: 'output' },
      { pin: 21, name: 'Q2',  type: 'output' },
      { pin: 22, name: 'Q1',  type: 'output' },
      { pin: 23, name: 'Q0',  type: 'output' },
      { pin: 24, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','CLK','D0','D1','D2','D3','D4','D5','D6','D7','D8','D9'], outputs: ['Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7','Q8','Q9'] },
    ],
  },

  // ── 74823: 9 bit D flip-flops, CLRn+CEN, TRI (24-pin) ───────────────────
  /* Primary source: Texas Instruments, 74823 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74as823a.pdf
     https://en.wikipedia.org/wiki/Flip-flop_(electronics) */
  '74823': {
    name: '74x823',
    simpleName: '9 bit D-FF w/ CLRn + CEN (TRI)',
    description: '9 bit D-type flip-flops with clear and clock enable inputs, three-state outputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74as823a.pdf',
    tags: ['flip-flop', 'D-type', '9 bit', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x823 is a 9 bit D-type register with asynchronous clear (CLRn), clock enable (CEN), and tri-state outputs. It is designed for bus-interface applications where one extra control/parity bit accompanies an 8 bit data field.',
    guidePinDescriptions: {
      'OEn':  'Output enable (active LOW).',
      'CLRn': 'Asynchronous clear, active LOW. Clears stored outputs regardless of clock.',
      'CEN':  'Clock enable control input.',
      'D0':   'Data input bit 0.',
      'D1':   'Data input bit 1.',
      'D2':   'Data input bit 2.',
      'D3':   'Data input bit 3.',
      'D4':   'Data input bit 4.',
      'D5':   'Data input bit 5.',
      'D6':   'Data input bit 6.',
      'D7':   'Data input bit 7.',
      'GND':  'Ground reference (pin 12).',
      'CLK':  'Clock input.',
      'D8':   'Data input bit 8.',
      'Q8':   'Registered output bit 8.',
      'Q7':   'Registered output bit 7.',
      'Q6':   'Registered output bit 6.',
      'Q5':   'Registered output bit 5.',
      'Q4':   'Registered output bit 4.',
      'Q3':   'Registered output bit 3.',
      'Q2':   'Registered output bit 2.',
      'Q1':   'Registered output bit 1.',
      'Q0':   'Registered output bit 0.',
      'VCC':  'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: 'Clear and Clock Enable Controls',
        paragraphs: [
          'CLRn provides fast global reset, while CEN allows selective state hold without stopping the system clock. Together these controls are common in pipelined bus interfaces.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'OEn', type: 'input'  },
      { pin:  2, name: 'CLRn',type: 'input'  },
      { pin:  3, name: 'CEN', type: 'input'  },
      { pin:  4, name: 'D0',  type: 'input'  },
      { pin:  5, name: 'D1',  type: 'input'  },
      { pin:  6, name: 'D2',  type: 'input'  },
      { pin:  7, name: 'D3',  type: 'input'  },
      { pin:  8, name: 'D4',  type: 'input'  },
      { pin:  9, name: 'D5',  type: 'input'  },
      { pin: 10, name: 'D6',  type: 'input'  },
      { pin: 11, name: 'D7',  type: 'input'  },
      { pin: 12, name: 'GND', type: 'power'  },
      { pin: 13, name: 'CLK', type: 'input'  },
      { pin: 14, name: 'D8',  type: 'input'  },
      { pin: 15, name: 'Q8',  type: 'output' },
      { pin: 16, name: 'Q7',  type: 'output' },
      { pin: 17, name: 'Q6',  type: 'output' },
      { pin: 18, name: 'Q5',  type: 'output' },
      { pin: 19, name: 'Q4',  type: 'output' },
      { pin: 20, name: 'Q3',  type: 'output' },
      { pin: 21, name: 'Q2',  type: 'output' },
      { pin: 22, name: 'Q1',  type: 'output' },
      { pin: 23, name: 'Q0',  type: 'output' },
      { pin: 24, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','CLRn','CEN','CLK','D0','D1','D2','D3','D4','D5','D6','D7','D8'], outputs: ['Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7','Q8'] },
    ],
  },

  // ── 74824: 9 bit D flip-flops, CLRn+CEN, inverting inputs, TRI (24-pin) ──
  /* Primary source: Texas Instruments, 74824 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74as824.pdf
     https://en.wikipedia.org/wiki/Flip-flop_(electronics) */
  '74824': {
    name: '74x824',
    simpleName: '9 bit D-FF w/ CLRn + CEN, Inv In (TRI)',
    description: '9 bit D-type flip-flops with clear and clock enable inputs, inverting inputs, three-state outputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74as824.pdf',
    tags: ['flip-flop', 'D-type', '9 bit', 'inverting', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x824 is the inverting/polarity-variant member of the 9 bit bus FF family. It retains CLRn, CEN, and tri-state behavior while matching active LOW data-path conventions.',
    guidePinDescriptions: {
      'OEn':  'Output enable (active LOW).',
      'CLRn': 'Asynchronous clear input, active LOW.',
      'CEN':  'Clock enable input.',
      'D0':   'Data input bit 0.',
      'D1':   'Data input bit 1.',
      'D2':   'Data input bit 2.',
      'D3':   'Data input bit 3.',
      'D4':   'Data input bit 4.',
      'D5':   'Data input bit 5.',
      'D6':   'Data input bit 6.',
      'D7':   'Data input bit 7.',
      'GND':  'Ground reference (pin 12).',
      'CLK':  'Clock input.',
      'D8':   'Data input bit 8.',
      'Q8':   'Registered output bit 8.',
      'Q7':   'Registered output bit 7.',
      'Q6':   'Registered output bit 6.',
      'Q5':   'Registered output bit 5.',
      'Q4':   'Registered output bit 4.',
      'Q3':   'Registered output bit 3.',
      'Q2':   'Registered output bit 2.',
      'Q1':   'Registered output bit 1.',
      'Q0':   'Registered output bit 0.',
      'VCC':  'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: '74x823 vs 74x824',
        paragraphs: [
          'These chips share the same control structure and width. The practical choice is polarity fit in the surrounding logic network.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'OEn', type: 'input'  },
      { pin:  2, name: 'CLRn',type: 'input'  },
      { pin:  3, name: 'CEN', type: 'input'  },
      { pin:  4, name: 'D0',  type: 'input'  },
      { pin:  5, name: 'D1',  type: 'input'  },
      { pin:  6, name: 'D2',  type: 'input'  },
      { pin:  7, name: 'D3',  type: 'input'  },
      { pin:  8, name: 'D4',  type: 'input'  },
      { pin:  9, name: 'D5',  type: 'input'  },
      { pin: 10, name: 'D6',  type: 'input'  },
      { pin: 11, name: 'D7',  type: 'input'  },
      { pin: 12, name: 'GND', type: 'power'  },
      { pin: 13, name: 'CLK', type: 'input'  },
      { pin: 14, name: 'D8',  type: 'input'  },
      { pin: 15, name: 'Q8',  type: 'output' },
      { pin: 16, name: 'Q7',  type: 'output' },
      { pin: 17, name: 'Q6',  type: 'output' },
      { pin: 18, name: 'Q5',  type: 'output' },
      { pin: 19, name: 'Q4',  type: 'output' },
      { pin: 20, name: 'Q3',  type: 'output' },
      { pin: 21, name: 'Q2',  type: 'output' },
      { pin: 22, name: 'Q1',  type: 'output' },
      { pin: 23, name: 'Q0',  type: 'output' },
      { pin: 24, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','CLRn','CEN','CLK','D0','D1','D2','D3','D4','D5','D6','D7','D8'], outputs: ['Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7','Q8'] },
    ],
  },

  // ── 74825: 8 bit D flip-flop, CLRn+CEN, TRI (24-pin) ────────────────────
  /* Primary source: Texas Instruments, 74825 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74as825a.pdf
     https://en.wikipedia.org/wiki/Flip-flop_(electronics) */
  '74825': {
    name: '74x825',
    simpleName: '8 bit D-FF w/ CLRn + CEN (TRI)',
    description: '8 bit D-type flip-flop with clear and clock enable inputs, three-state outputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74as825a.pdf',
    tags: ['flip-flop', 'D-type', '8 bit', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x825 is an 8 bit D-type bus flip-flop with CLRn, CEN, and tri-state outputs. It is one of the standard byte-wide building blocks for synchronous bus pipelines and register files.',
    guidePinDescriptions: {
      'OEn':  'Output enable (active LOW).',
      'CLRn': 'Asynchronous clear input, active LOW.',
      'CEN':  'Clock enable input.',
      'D0':   'Data input bit 0.',
      'D1':   'Data input bit 1.',
      'D2':   'Data input bit 2.',
      'D3':   'Data input bit 3.',
      'D4':   'Data input bit 4.',
      'D5':   'Data input bit 5.',
      'D6':   'Data input bit 6.',
      'D7':   'Data input bit 7.',
      'GND':  'Ground reference (pin 12).',
      'CLK':  'Clock input.',
      'NC':   'No connect.',
      'Q7':   'Registered output bit 7.',
      'Q6':   'Registered output bit 6.',
      'Q5':   'Registered output bit 5.',
      'Q4':   'Registered output bit 4.',
      'Q3':   'Registered output bit 3.',
      'Q2':   'Registered output bit 2.',
      'Q1':   'Registered output bit 1.',
      'Q0':   'Registered output bit 0.',
      'VCC':  'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: 'Byte-Wide Bus Register',
        paragraphs: [
          'This part captures one byte per clock edge and can be inserted between bus stages to improve timing closure. CLRn and CEN provide strong control over reset and update behavior.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'OEn', type: 'input'  },
      { pin:  2, name: 'CLRn',type: 'input'  },
      { pin:  3, name: 'CEN', type: 'input'  },
      { pin:  4, name: 'D0',  type: 'input'  },
      { pin:  5, name: 'D1',  type: 'input'  },
      { pin:  6, name: 'D2',  type: 'input'  },
      { pin:  7, name: 'D3',  type: 'input'  },
      { pin:  8, name: 'D4',  type: 'input'  },
      { pin:  9, name: 'D5',  type: 'input'  },
      { pin: 10, name: 'D6',  type: 'input'  },
      { pin: 11, name: 'D7',  type: 'input'  },
      { pin: 12, name: 'GND', type: 'power'  },
      { pin: 13, name: 'CLK', type: 'input'  },
      { pin: 14, name: 'NC',  type: 'nc'     },
      { pin: 15, name: 'Q7',  type: 'output' },
      { pin: 16, name: 'Q6',  type: 'output' },
      { pin: 17, name: 'Q5',  type: 'output' },
      { pin: 18, name: 'Q4',  type: 'output' },
      { pin: 19, name: 'Q3',  type: 'output' },
      { pin: 20, name: 'Q2',  type: 'output' },
      { pin: 21, name: 'Q1',  type: 'output' },
      { pin: 22, name: 'Q0',  type: 'output' },
      { pin: 23, name: 'NC',  type: 'nc'     },
      { pin: 24, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','CLRn','CEN','CLK','D0','D1','D2','D3','D4','D5','D6','D7'], outputs: ['Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7'] },
    ],
  },

};