// chips25.js Chips Block 25: 74414, 74416, 74417, 74424, 74425, 74426,
//                              74432, 74433, 74436, 74437, 74440, 74441,
//                              74442, 74443, 74444, 74445
export const CHIPS_BLOCK_25 = {

  // ── 74414: Interrupt priority controller (Intel 8214 equiv) ──────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits */
  '74x414': {
    name: '74x414',
    simpleName: 'Interrupt Priority Ctrl (8214)',
    description: 'Interrupt priority controller for 8080, equiv Intel 8214 (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    sequential: true,
    tags: ['interrupt', 'priority', 'intel-8214', 'complex'],
    guideOverview: 'The 74x414 is an interrupt priority controller functionally equivalent to the Intel 8214. It accepts eight interrupt request inputs (R0-R7, where R7 is highest priority) and resolves which one should be serviced. It outputs a 3 bit encoded interrupt level (B0-B2), an INT strobe, and status outputs (OINT, PINT, INTB) compatible with the Intel 8080 CPU interrupt handshake.',
    guidePinDescriptions: {
      'EI':   'Enable Interrupt. When LOW, no interrupts are passed through.',
      'R0':   'Interrupt Request 0 (lowest priority).',
      'R1':   'Interrupt Request 1.',
      'R2':   'Interrupt Request 2.',
      'R3':   'Interrupt Request 3.',
      'R4':   'Interrupt Request 4.',
      'R5':   'Interrupt Request 5.',
      'R6':   'Interrupt Request 6.',
      'R7':   'Interrupt Request 7 (highest priority).',
      'CLK':  'Clock. Synchronizes interrupt sampling.',
      'SGS':  'Status Gate Strobe. Latches the priority status.',
      'GND':  'Ground reference (pin 12).',
      'INT':  'Interrupt output. Goes HIGH when a valid interrupt is pending.',
      'ENLG': 'Enable Latch Gate. Controls internal latch.',
      'B0':   'Encoded interrupt level bit 0.',
      'B1':   'Encoded interrupt level bit 1.',
      'B2':   'Encoded interrupt level bit 2 (MSB).',
      'OINT': 'Output interrupt signal.',
      'PINT': 'Priority interrupt output.',
      'INTB': 'Interrupt bus output.',
      'S0':   'Current serving level bit 0.',
      'S1':   'Current serving level bit 1.',
      'S2':   'Current serving level bit 2.',
      'VCC':  'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: 'Intel 8214 Equivalent',
        paragraphs: [
          'The Intel 8214 was used in 8080 systems to manage up to eight interrupt sources. The highest asserted request wins and its 3 bit code is placed on B0-B2 for the CPU to read via INTA. S0-S2 communicate the currently servicing level to support priority masking.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'EI',   type: 'input' },
      { pin:  2, name: 'R0',   type: 'input' },
      { pin:  3, name: 'R1',   type: 'input' },
      { pin:  4, name: 'R2',   type: 'input' },
      { pin:  5, name: 'R3',   type: 'input' },
      { pin:  6, name: 'R4',   type: 'input' },
      { pin:  7, name: 'R5',   type: 'input' },
      { pin:  8, name: 'R6',   type: 'input' },
      { pin:  9, name: 'R7',   type: 'input' },
      { pin: 10, name: 'CLK',  type: 'input' },
      { pin: 11, name: 'SGS',  type: 'input' },
      { pin: 12, name: 'GND',  type: 'power' },
      { pin: 13, name: 'INT',  type: 'output' },
      { pin: 14, name: 'ENLG', type: 'input' },
      { pin: 15, name: 'B0',   type: 'output' },
      { pin: 16, name: 'B1',   type: 'output' },
      { pin: 17, name: 'B2',   type: 'output' },
      { pin: 18, name: 'OINT', type: 'output' },
      { pin: 19, name: 'PINT', type: 'output' },
      { pin: 20, name: 'INTB', type: 'output' },
      { pin: 21, name: 'S0',   type: 'input' },
      { pin: 22, name: 'S1',   type: 'input' },
      { pin: 23, name: 'S2',   type: 'input' },
      { pin: 24, name: 'VCC',  type: 'power' },
    ],
    gates: [
      { type: 'INTR_PRIORITY_CTRL',
        inputs:  ['R0','R1','R2','R3','R4','R5','R6','R7','EI','CLK','SGS','ENLG','S0','S1','S2'],
        outputs: ['B0','B1','B2','INT','OINT','PINT','INTB'] },
    ],
  },

  // ── 74416: 4 bit bidirectional bus transceiver (Intel 8216 equiv) ────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Three-state_logic
     Wikipedia: https://en.wikipedia.org/wiki/Bus_transceiver */
  '74x416': {
    name: '74x416',
    simpleName: '4 bit Bus Xcvr (8216)',
    description: '4 bit bidirectional bus transceiver (Intel 8216 equiv), tri state (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    tags: ['bus transceiver', '4 bit', 'tri state', 'bidirectional', 'intel-8216'],
    guideOverview: 'The 74x416 is a 4 bit bidirectional bus transceiver with tri state outputs, equivalent to the Intel 8216. DIR controls the data direction: DIR=HIGH drives A→B, DIR=LOW drives B→A. OEn (active LOW) enables the outputs; when HIGH, all outputs are high impedance. Used to interface the Intel 8080 data bus.',
    guidePinDescriptions: {
      'OEn': 'Output Enable (active LOW). When HIGH, all outputs are tri stated.',
      'DIR': 'Direction. HIGH = A to B; LOW = B to A.',
      'A1':  'Side A data pin 1.',
      'A2':  'Side A data pin 2.',
      'A3':  'Side A data pin 3.',
      'A4':  'Side A data pin 4.',
      'NC':  'No connect.',
      'GND': 'Ground reference (pin 8).',
      'B4':  'Side B data pin 4.',
      'B3':  'Side B data pin 3.',
      'B2':  'Side B data pin 2.',
      'B1':  'Side B data pin 1.',
      'NC2': 'No connect.',
      'NC3': 'No connect.',
      'NC4': 'No connect.',
      'VCC': 'Positive supply (+5 V, pin 16).',
    },
    guideSections: [
      {
        title: 'Intel 8080 Data Bus Interface',
        paragraphs: [
          'The Intel 8216 (and its 74x416 equivalent) was the standard data bus driver for 8080 systems. The CPU data bus side connects to A1-A4 and the memory/peripheral side to B1-B4. The DBIN and WR signals from the 8080 drive DIR to control data flow direction.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'OEn', type: 'input' },
      { pin:  2, name: 'DIR', type: 'input' },
      { pin:  3, name: 'A1',  type: 'input' },
      { pin:  4, name: 'A2',  type: 'input' },
      { pin:  5, name: 'A3',  type: 'input' },
      { pin:  6, name: 'A4',  type: 'input' },
      { pin:  7, name: 'NC',  type: 'nc' },
      { pin:  8, name: 'GND', type: 'power' },
      { pin:  9, name: 'B4',  type: 'output' },
      { pin: 10, name: 'B3',  type: 'output' },
      { pin: 11, name: 'B2',  type: 'output' },
      { pin: 12, name: 'B1',  type: 'output' },
      { pin: 13, name: 'NC2', type: 'nc' },
      { pin: 14, name: 'NC3', type: 'nc' },
      { pin: 15, name: 'NC4', type: 'nc' },
      { pin: 16, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'BUS_XCVR_4BIT_TRI',
        inputs:  ['OEn','DIR','A1','A2','A3','A4'],
        outputs: ['B1','B2','B3','B4'] },
    ],
  },

  // ── 74417: Modulo 2 and modulo 5 counters, shared preload/clear ──────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Counter_(digital) */
  '74x417': {
    name: '74x417',
    simpleName: 'Modulo 2 & 5 Counters',
    description: 'Modulo 2 and modulo 5 counters, shared preload/clear (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    sequential: true,
    tags: ['counter', 'modulo', 'divide by-2', 'divide by-5'],
    guideOverview: 'The 74x417 contains a modulo-2 (÷2) and a modulo-5 (÷5) counter stage driven by separate clocks (CLK2, CLK5) with shared parallel load (P0-P2, LD) and asynchronous clear (CLRn). Connecting CLK5 to the ÷2 output creates a ÷10 (decade) counter. The preload allows setting an arbitrary starting count.',
    guidePinDescriptions: {
      'CLK2':  'Clock for the ÷2 stage. Counts on falling edge.',
      'CLK5':  'Clock for the ÷5 stage.',
      'P0':    'Preload data bit 0.',
      'P1':    'Preload data bit 1.',
      'P2':    'Preload data bit 2.',
      'LD':    'Load. When HIGH, preloads P0-P2 into the counter on next clock.',
      'CLRn':  'Clear (active LOW). Asynchronously resets counter to 0.',
      'GND':   'Ground reference (pin 8).',
      'Q0':    'Output bit 0.',
      'Q1':    'Output bit 1.',
      'Q2':    'Output bit 2.',
      'NC1':   'No connect.',
      'NC2':   'No connect.',
      'NC3':   'No connect.',
      'NC4':   'No connect.',
      'VCC':   'Positive supply (+5 V, pin 16).',
    },
    guideSections: [
      {
        title: 'Decade Counter Configuration',
        paragraphs: [
          'Connect Q0 (÷2 output) to CLK5 to get a BCD decade counter (0-9). The preload feature allows offset counting for example, start at 3 to count only 3-9 before rollover.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'CLK2',  type: 'input' },
      { pin:  2, name: 'CLK5',  type: 'input' },
      { pin:  3, name: 'P0',    type: 'input' },
      { pin:  4, name: 'P1',    type: 'input' },
      { pin:  5, name: 'P2',    type: 'input' },
      { pin:  6, name: 'LD',    type: 'input' },
      { pin:  7, name: 'CLRn',  type: 'input' },
      { pin:  8, name: 'GND',   type: 'power' },
      { pin:  9, name: 'Q0',    type: 'output' },
      { pin: 10, name: 'Q1',    type: 'output' },
      { pin: 11, name: 'Q2',    type: 'output' },
      { pin: 12, name: 'NC1',   type: 'nc' },
      { pin: 13, name: 'NC2',   type: 'nc' },
      { pin: 14, name: 'NC3',   type: 'nc' },
      { pin: 15, name: 'NC4',   type: 'nc' },
      { pin: 16, name: 'VCC',   type: 'power' },
    ],
    gates: [
      { type: 'COUNTER_MOD2_MOD5',
        inputs:  ['CLK2','CLK5','P0','P1','P2','LD','CLRn'],
        outputs: ['Q0','Q1','Q2'] },
    ],
  },

  // ── 74424: Two phase clock generator (Intel 8224 equiv) ─────────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits */
  '74x424': {
    name: '74x424',
    simpleName: 'Two Phase Clock Gen (8224)',
    description: 'Two phase clock generator/driver for 8080, equiv Intel 8224 (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    sequential: true,
    tags: ['clock', 'two-phase', 'intel-8224', 'driver', 'complex'],
    guideOverview: 'The 74x424 is a two phase clock generator and driver equivalent to the Intel 8224. It takes a crystal oscillator (XTAL1/XTAL2) and generates the non overlapping two phase clocks (PHI1, PHI2) required by the Intel 8080 CPU. It also buffers the RESET and READY signals from the 8080 system.',
    guidePinDescriptions: {
      'XTAL1':  'Crystal input 1 (or external clock input).',
      'XTAL2':  'Crystal input 2.',
      'RESn':   'Reset input (active LOW). Drives the RESETn output after synchronization.',
      'RDYn':   'Ready input (active LOW). Drives RDYIN to the CPU.',
      'SYNCn':  'Sync from 8080 CPU (active LOW). Used for READY synchronization.',
      'TANK':   'Tank circuit input for crystal oscillator.',
      'OSCn':   'Oscillator output, inverted.',
      'GND':    'Ground reference (pin 8).',
      'PHI2':   'Phase-2 clock output to 8080.',
      'PHI1':   'Phase-1 clock output to 8080.',
      'RESETn': 'Synchronized reset output (active LOW) to 8080.',
      'RDYIN':  'Ready output to 8080 CPU READY pin.',
      'OSC':    'Oscillator output (non inverted).',
      'NC1':    'No connect.',
      'NC2':    'No connect.',
      'VCC':    'Positive supply (+5 V, pin 16).',
    },
    guideSections: [
      {
        title: 'Two Phase 8080 Clock',
        paragraphs: [
          'The Intel 8080 requires two non overlapping clocks (PHI1 and PHI2) to sequence its internal pipeline. The 8224 (74x424) generates these from a crystal and ensures they never overlap if both were HIGH simultaneously, bus contention would destroy data.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'XTAL1', type: 'input' },
      { pin:  2, name: 'XTAL2', type: 'input' },
      { pin:  3, name: 'RESn',  type: 'input' },
      { pin:  4, name: 'RDYn',  type: 'input' },
      { pin:  5, name: 'SYNCn', type: 'input' },
      { pin:  6, name: 'TANK',  type: 'input' },
      { pin:  7, name: 'OSCn',  type: 'output' },
      { pin:  8, name: 'GND',   type: 'power' },
      { pin:  9, name: 'PHI2',  type: 'output' },
      { pin: 10, name: 'PHI1',  type: 'output' },
      { pin: 11, name: 'RESETn',type: 'output' },
      { pin: 12, name: 'RDYIN', type: 'output' },
      { pin: 13, name: 'OSC',   type: 'output' },
      { pin: 14, name: 'NC1',   type: 'nc' },
      { pin: 15, name: 'NC2',   type: 'nc' },
      { pin: 16, name: 'VCC',   type: 'power' },
    ],
    gates: [
      { type: 'CLK_GEN_TWOPHASE',
        inputs:  ['XTAL1','XTAL2','RESn','RDYn','SYNCn','TANK'],
        outputs: ['PHI1','PHI2','OSC','OSCn','RESETn','RDYIN'] },
    ],
  },

  // ── 74425: Quad bus buffers, active LOW enables, tri state ───────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Three-state_logic */
  '74x425': {
    name: '74x425',
    simpleName: 'Quad Buffer (active LOW En)',
    description: 'Quad bus buffers with active low enables, tri state outputs (14-pin)',
    pins: 14, vcc: 14, gnd: 7,
    tags: ['buffer', 'quad', 'tri state', 'active low'],
    guideOverview: 'The 74x425 contains four non inverting tri state buffers. Each buffer has its own independent active LOW enable (E1n-E4n). When an enable is HIGH, that output is high impedance. Commonly used to selectively drive shared bus lines.',
    guidePinDescriptions: {
      'E1n': 'Enable for buffer 1 (active LOW). When HIGH, Y1 is tri stated.',
      'A1':  'Input for buffer 1.',
      'Y1':  'Tri state output 1.',
      'E2n': 'Enable for buffer 2 (active LOW).',
      'A2':  'Input for buffer 2.',
      'Y2':  'Tri state output 2.',
      'GND': 'Ground reference (pin 7).',
      'Y3':  'Tri state output 3.',
      'A3':  'Input for buffer 3.',
      'E3n': 'Enable for buffer 3 (active LOW).',
      'Y4':  'Tri state output 4.',
      'A4':  'Input for buffer 4.',
      'E4n': 'Enable for buffer 4 (active LOW).',
      'VCC': 'Positive supply (+5 V, pin 14).',
    },
    guideSections: [
      {
        title: 'Independent Enable Buffers',
        paragraphs: [
          'Each buffer can be independently enabled or tri stated. This is useful when four different bus lines need gating control from four separate signals rather than sharing a single OEn.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'E1n', type: 'input' },
      { pin:  2, name: 'A1',  type: 'input' },
      { pin:  3, name: 'Y1',  type: 'output' },
      { pin:  4, name: 'E2n', type: 'input' },
      { pin:  5, name: 'A2',  type: 'input' },
      { pin:  6, name: 'Y2',  type: 'output' },
      { pin:  7, name: 'GND', type: 'power' },
      { pin:  8, name: 'Y3',  type: 'output' },
      { pin:  9, name: 'A3',  type: 'input' },
      { pin: 10, name: 'E3n', type: 'input' },
      { pin: 11, name: 'Y4',  type: 'output' },
      { pin: 12, name: 'A4',  type: 'input' },
      { pin: 13, name: 'E4n', type: 'input' },
      { pin: 14, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'BUFFER_QUAD_TRI_NLOW',
        inputs:  ['A1','E1n','A2','E2n','A3','E3n','A4','E4n'],
        outputs: ['Y1','Y2','Y3','Y4'] },
    ],
  },

  // ── 74426: Quad bus buffers, active HIGH enables, tri state ─────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Three-state_logic */
  '74x426': {
    name: '74x426',
    simpleName: 'Quad Buffer (active HIGH En)',
    description: 'Quad bus buffers with active high enables, tri state outputs (14-pin)',
    pins: 14, vcc: 14, gnd: 7,
    tags: ['buffer', 'quad', 'tri state', 'active high'],
    guideOverview: 'The 74x426 is the active HIGH enable counterpart of the 74x425. Each of the four tri state non inverting buffers is independently enabled by an active HIGH enable input (E1-E4). When an enable is LOW, that output is high impedance.',
    guidePinDescriptions: {
      'E1':  'Enable for buffer 1 (active HIGH). When LOW, Y1 is tri stated.',
      'A1':  'Input for buffer 1.',
      'Y1':  'Tri state output 1.',
      'E2':  'Enable for buffer 2 (active HIGH).',
      'A2':  'Input for buffer 2.',
      'Y2':  'Tri state output 2.',
      'GND': 'Ground reference (pin 7).',
      'Y3':  'Tri state output 3.',
      'A3':  'Input for buffer 3.',
      'E3':  'Enable for buffer 3 (active HIGH).',
      'Y4':  'Tri state output 4.',
      'A4':  'Input for buffer 4.',
      'E4':  'Enable for buffer 4 (active HIGH).',
      'VCC': 'Positive supply (+5 V, pin 14).',
    },
    guideSections: [
      {
        title: '74x425 vs 74x426',
        paragraphs: [
          'The 74x425 and 74x426 are functionally identical except for enable polarity. Use 74x426 when the control signals are active HIGH (e.g., from TTL outputs that are already at logic-1 to enable).',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'E1', type: 'input' },
      { pin:  2, name: 'A1', type: 'input' },
      { pin:  3, name: 'Y1', type: 'output' },
      { pin:  4, name: 'E2', type: 'input' },
      { pin:  5, name: 'A2', type: 'input' },
      { pin:  6, name: 'Y2', type: 'output' },
      { pin:  7, name: 'GND',type: 'power' },
      { pin:  8, name: 'Y3', type: 'output' },
      { pin:  9, name: 'A3', type: 'input' },
      { pin: 10, name: 'E3', type: 'input' },
      { pin: 11, name: 'Y4', type: 'output' },
      { pin: 12, name: 'A4', type: 'input' },
      { pin: 13, name: 'E4', type: 'input' },
      { pin: 14, name: 'VCC',type: 'power' },
    ],
    gates: [
      { type: 'BUFFER_QUAD_TRI_NHIGH',
        inputs:  ['A1','E1','A2','E2','A3','E3','A4','E4'],
        outputs: ['Y1','Y2','Y3','Y4'] },
    ],
  },

  // ── 74432: 8 bit multi mode buffered latch, tri state ───────────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Flip-flop_(electronics)
     Wikipedia: https://en.wikipedia.org/wiki/Three-state_logic
     Wikipedia: https://en.wikipedia.org/wiki/Open_collector */
  '74x432': {
    name: '74x432',
    simpleName: '8 bit Multi Mode Latch (3-state)',
    description: '8 bit multi mode buffered latch, tri state (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    sequential: true,
    tags: ['latch', '8 bit', 'tri state', 'multi-mode'],
    guideOverview: 'The 74x432 is the tri state output version of the 74x412 multi mode 8 bit latch. Like the 74x412 it replicates Intel 8212 behavior (strobe loaded, mode selectable, interrupt generating), but instead of open collector outputs it provides full totem pole tri state outputs controlled by OEn.',
    guidePinDescriptions: {
      'DS1':  'Device Select 1 (active HIGH). Assert to enable the device.',
      'DI0':  'Data input bit 0.',
      'DI1':  'Data input bit 1.',
      'DI2':  'Data input bit 2.',
      'DI3':  'Data input bit 3.',
      'DI4':  'Data input bit 4.',
      'DI5':  'Data input bit 5.',
      'DI6':  'Data input bit 6.',
      'DI7':  'Data input bit 7.',
      'STB':  'Strobe. Rising edge captures DI0-DI7 and asserts INT.',
      'MD':   'Mode. LOW = output port mode, HIGH = input port mode.',
      'GND':  'Ground reference (pin 12).',
      'OEn':  'Output Enable (active LOW tri state). When HIGH, DO outputs are high impedance.',
      'INT':  'Interrupt. Pulses HIGH after STB to notify CPU of new data.',
      'DO7':  'Latched output bit 7.',
      'DO6':  'Latched output bit 6.',
      'DO5':  'Latched output bit 5.',
      'DO4':  'Latched output bit 4.',
      'DO3':  'Latched output bit 3.',
      'DO2':  'Latched output bit 2.',
      'DO1':  'Latched output bit 1.',
      'DO0':  'Latched output bit 0.',
      'DS2n': 'Device Select 2 (active LOW).',
      'VCC':  'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: '74x412 vs 74x432',
        paragraphs: [
          'Both chips implement the Intel 8212 function. The 74x432 uses tri state (totem pole) outputs instead of open collector, making it faster and not requiring external pull up resistors.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'DS1',  type: 'input' },
      { pin:  2, name: 'DI0',  type: 'input' },
      { pin:  3, name: 'DI1',  type: 'input' },
      { pin:  4, name: 'DI2',  type: 'input' },
      { pin:  5, name: 'DI3',  type: 'input' },
      { pin:  6, name: 'DI4',  type: 'input' },
      { pin:  7, name: 'DI5',  type: 'input' },
      { pin:  8, name: 'DI6',  type: 'input' },
      { pin:  9, name: 'DI7',  type: 'input' },
      { pin: 10, name: 'STB',  type: 'input' },
      { pin: 11, name: 'MD',   type: 'input' },
      { pin: 12, name: 'GND',  type: 'power' },
      { pin: 13, name: 'OEn',  type: 'input' },
      { pin: 14, name: 'INT',  type: 'output' },
      { pin: 15, name: 'DO7',  type: 'output' },
      { pin: 16, name: 'DO6',  type: 'output' },
      { pin: 17, name: 'DO5',  type: 'output' },
      { pin: 18, name: 'DO4',  type: 'output' },
      { pin: 19, name: 'DO3',  type: 'output' },
      { pin: 20, name: 'DO2',  type: 'output' },
      { pin: 21, name: 'DO1',  type: 'output' },
      { pin: 22, name: 'DO0',  type: 'output' },
      { pin: 23, name: 'DS2n', type: 'input' },
      { pin: 24, name: 'VCC',  type: 'power' },
    ],
    gates: [
      { type: 'MULTIMODE_LATCH_8BIT',
        inputs:  ['DS1','DI0','DI1','DI2','DI3','DI4','DI5','DI6','DI7','STB','MD','OEn','DS2n'],
        outputs: ['DO0','DO1','DO2','DO3','DO4','DO5','DO6','DO7','INT'] },
    ],
  },

  // ── 74433: 256 bit FIFO (64×4), tri state ───────────────────────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Three-state_logic
     Wikipedia: https://en.wikipedia.org/wiki/Random-access_memory */
  '74x433': {
    name: '74x433',
    simpleName: '64×4 FIFO (3-state)',
    description: '256 bit FIFO memory (64×4) with tri state outputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    sequential: true,
    tags: ['fifo', '64x4', 'memory', 'tri state'],
    guideOverview: 'The 74x433 is the tri state output version of the 74x413 (64 word × 4 bit FIFO). It adds an output enable pin (OEn) that tri states the data outputs, allowing multiple FIFOs to share a common output bus. Otherwise operation is identical: independent read and write clocks, EF and FF status flags.',
    guidePinDescriptions: {
      'DIN0':   'Data input bit 0.',
      'DIN1':   'Data input bit 1.',
      'DIN2':   'Data input bit 2.',
      'DIN3':   'Data input bit 3.',
      'WR_CLK': 'Write clock. Rising edge enqueues DIN when WR_EN is HIGH.',
      'WR_EN':  'Write Enable (active HIGH).',
      'RD_EN':  'Read Enable (active HIGH). Advances read pointer on RD_CLK.',
      'OEn':    'Output Enable (active LOW). When HIGH, DOUT outputs are tri stated.',
      'NC1':    'No connect.',
      'NC2':    'No connect.',
      'EF':     'Empty Flag. HIGH when FIFO is empty.',
      'GND':    'Ground reference (pin 12).',
      'FF':     'Full Flag. HIGH when all 64 locations are used.',
      'RD_CLK': 'Read clock.',
      'DOUT3':  'Data output bit 3.',
      'DOUT2':  'Data output bit 2.',
      'DOUT1':  'Data output bit 1.',
      'DOUT0':  'Data output bit 0.',
      'NC3':    'No connect.',
      'NC4':    'No connect.',
      'NC5':    'No connect.',
      'NC6':    'No connect.',
      'NC7':    'No connect.',
      'VCC':    'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: 'Tri State vs Always Active FIFO',
        paragraphs: [
          'Use the 74x433 when multiple FIFOs share a common read bus. Only one device asserts OEn LOW at a time. The 74x413 (no OEn) is simpler when the FIFO is the only driver on the output lines.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'DIN0',   type: 'input' },
      { pin:  2, name: 'DIN1',   type: 'input' },
      { pin:  3, name: 'DIN2',   type: 'input' },
      { pin:  4, name: 'DIN3',   type: 'input' },
      { pin:  5, name: 'WR_CLK', type: 'input' },
      { pin:  6, name: 'WR_EN',  type: 'input' },
      { pin:  7, name: 'RD_EN',  type: 'input' },
      { pin:  8, name: 'OEn',    type: 'input' },
      { pin:  9, name: 'NC1',    type: 'nc' },
      { pin: 10, name: 'NC2',    type: 'nc' },
      { pin: 11, name: 'EF',     type: 'output' },
      { pin: 12, name: 'GND',    type: 'power' },
      { pin: 13, name: 'FF',     type: 'output' },
      { pin: 14, name: 'RD_CLK', type: 'input' },
      { pin: 15, name: 'DOUT3',  type: 'output' },
      { pin: 16, name: 'DOUT2',  type: 'output' },
      { pin: 17, name: 'DOUT1',  type: 'output' },
      { pin: 18, name: 'DOUT0',  type: 'output' },
      { pin: 19, name: 'NC3',    type: 'nc' },
      { pin: 20, name: 'NC4',    type: 'nc' },
      { pin: 21, name: 'NC5',    type: 'nc' },
      { pin: 22, name: 'NC6',    type: 'nc' },
      { pin: 23, name: 'NC7',    type: 'nc' },
      { pin: 24, name: 'VCC',    type: 'power' },
    ],
    gates: [
      { type: 'FIFO_64X4_TRI',
        inputs:  ['DIN0','DIN1','DIN2','DIN3','WR_CLK','RD_CLK','WR_EN','RD_EN','OEn'],
        outputs: ['DOUT0','DOUT1','DOUT2','DOUT3','EF','FF'] },
    ],
  },

  // ── 74436: Line driver / MOS memory interface (with damping) ────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits */
  '74x436': {
    name: '74x436',
    simpleName: 'Line Driver (damped)',
    description: 'Line driver / MOS memory interface with damping output resistors (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    tags: ['driver', 'buffer', 'memory-interface', 'mos'],
    guideOverview: 'The 74x436 is a hex non inverting line driver designed to interface TTL logic with MOS memory buses. It features internal damping resistors on the outputs to suppress transmission line reflections on long PCB traces, reducing ringing that could cause false triggering of MOS inputs.',
    guidePinDescriptions: {
      'A1':  'Input 1.',
      'Y1':  'Buffered output 1 (damped).',
      'A2':  'Input 2.',
      'Y2':  'Buffered output 2 (damped).',
      'A3':  'Input 3.',
      'Y3':  'Buffered output 3 (damped).',
      'A4':  'Input 4.',
      'GND': 'Ground reference (pin 8).',
      'Y4':  'Buffered output 4 (damped).',
      'A5':  'Input 5.',
      'Y5':  'Buffered output 5 (damped).',
      'A6':  'Input 6.',
      'Y6':  'Buffered output 6 (damped).',
      'OEn': 'Output Enable (active LOW). When HIGH, all outputs are tri stated.',
      'EN':  'Additional enable input.',
      'VCC': 'Positive supply (+5 V, pin 16).',
    },
    guideSections: [
      {
        title: 'Damped Line Driver',
        paragraphs: [
          'The on chip damping resistors series terminate the output, absorbing signal reflections from capacitive or mismatched loads. This was important when driving long traces to DRAM chips in late-1970s minicomputer memory boards.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'A1',  type: 'input' },
      { pin:  2, name: 'Y1',  type: 'output' },
      { pin:  3, name: 'A2',  type: 'input' },
      { pin:  4, name: 'Y2',  type: 'output' },
      { pin:  5, name: 'A3',  type: 'input' },
      { pin:  6, name: 'Y3',  type: 'output' },
      { pin:  7, name: 'A4',  type: 'input' },
      { pin:  8, name: 'GND', type: 'power' },
      { pin:  9, name: 'Y4',  type: 'output' },
      { pin: 10, name: 'A5',  type: 'input' },
      { pin: 11, name: 'Y5',  type: 'output' },
      { pin: 12, name: 'A6',  type: 'input' },
      { pin: 13, name: 'Y6',  type: 'output' },
      { pin: 14, name: 'OEn', type: 'input' },
      { pin: 15, name: 'EN',  type: 'input' },
      { pin: 16, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'LINE_DRIVER_6X',
        inputs:  ['A1','A2','A3','A4','A5','A6','OEn','EN'],
        outputs: ['Y1','Y2','Y3','Y4','Y5','Y6'] },
    ],
  },

  // ── 74437: Line driver / MOS memory interface ────────────────────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits */
  '74x437': {
    name: '74x437',
    simpleName: 'Line Driver',
    description: 'Line driver / MOS memory interface (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    tags: ['driver', 'buffer', 'memory-interface', 'mos'],
    guideOverview: 'The 74x437 is a hex non inverting line driver for MOS memory interfaces, identical to the 74x436 but without the internal damping resistors. Use when external series resistors are preferred, or when the output load is close enough that reflection damping is not required.',
    guidePinDescriptions: {
      'A1':  'Input 1.',
      'Y1':  'Buffered output 1.',
      'A2':  'Input 2.',
      'Y2':  'Buffered output 2.',
      'A3':  'Input 3.',
      'Y3':  'Buffered output 3.',
      'A4':  'Input 4.',
      'GND': 'Ground reference (pin 8).',
      'Y4':  'Buffered output 4.',
      'A5':  'Input 5.',
      'Y5':  'Buffered output 5.',
      'A6':  'Input 6.',
      'Y6':  'Buffered output 6.',
      'OEn': 'Output Enable (active LOW).',
      'EN':  'Additional enable input.',
      'VCC': 'Positive supply (+5 V, pin 16).',
    },
    guideSections: [
      {
        title: '74x436 vs 74x437',
        paragraphs: [
          'The 74x437 is pin compatible with 74x436. Choose 74x436 when on chip damping is required for long line signals; use 74x437 when adding your own series resistors or when the trace length is short.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'A1',  type: 'input' },
      { pin:  2, name: 'Y1',  type: 'output' },
      { pin:  3, name: 'A2',  type: 'input' },
      { pin:  4, name: 'Y2',  type: 'output' },
      { pin:  5, name: 'A3',  type: 'input' },
      { pin:  6, name: 'Y3',  type: 'output' },
      { pin:  7, name: 'A4',  type: 'input' },
      { pin:  8, name: 'GND', type: 'power' },
      { pin:  9, name: 'Y4',  type: 'output' },
      { pin: 10, name: 'A5',  type: 'input' },
      { pin: 11, name: 'Y5',  type: 'output' },
      { pin: 12, name: 'A6',  type: 'input' },
      { pin: 13, name: 'Y6',  type: 'output' },
      { pin: 14, name: 'OEn', type: 'input' },
      { pin: 15, name: 'EN',  type: 'input' },
      { pin: 16, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'LINE_DRIVER_6X',
        inputs:  ['A1','A2','A3','A4','A5','A6','OEn','EN'],
        outputs: ['Y1','Y2','Y3','Y4','Y5','Y6'] },
    ],
  },

  // ── 74440: Quad tridirectional transceiver, non inverting, OC ───────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Open_collector
     Wikipedia: https://en.wikipedia.org/wiki/Bus_transceiver */
  '74x440': {
    name: '74x440',
    simpleName: 'Quad Tridirnl Xcvr (OC)',
    description: 'Quad tridirectional bus transceiver, non inverting, open collector (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    openCollector: true,
    tags: ['transceiver', 'quad', 'bidirectional', 'open collector'],
    guideOverview: 'The 74x440 is a quad non inverting tridirectional bus transceiver with open collector outputs. Two enable inputs (OE1n, OE2n) and a direction control (DIR) allow four A/B channels to pass data in either direction. Open collector outputs support wired OR bus configurations.',
    guidePinDescriptions: {
      'OE1n': 'Output Enable 1 (active LOW). Both OE1n and OE2n must be LOW to enable.',
      'OE2n': 'Output Enable 2 (active LOW).',
      'DIR':  'Direction. HIGH = A to B; LOW = B to A.',
      'A1':   'Side A pin 1.',
      'B1':   'Side B pin 1 (OC output when DIR=HIGH).',
      'A2':   'Side A pin 2.',
      'B2':   'Side B pin 2.',
      'A3':   'Side A pin 3.',
      'B3':   'Side B pin 3.',
      'GND':  'Ground reference (pin 10).',
      'B4':   'Side B pin 4.',
      'A4':   'Side A pin 4.',
      'NC1':  'No connect.',
      'NC2':  'No connect.',
      'NC3':  'No connect.',
      'NC4':  'No connect.',
      'NC5':  'No connect.',
      'NC6':  'No connect.',
      'NC7':  'No connect.',
      'VCC':  'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'Tridirectional Transceiver',
        paragraphs: [
          'Tridirectional means the device supports not just two directions but also a high impedance (off) state, making three possible modes. With two OEn pins both must be LOW to enable data flow; either HIGH disables all outputs.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'OE1n', type: 'input' },
      { pin:  2, name: 'OE2n', type: 'input' },
      { pin:  3, name: 'DIR',  type: 'input' },
      { pin:  4, name: 'A1',   type: 'input' },
      { pin:  5, name: 'B1',   type: 'output' },
      { pin:  6, name: 'A2',   type: 'input' },
      { pin:  7, name: 'B2',   type: 'output' },
      { pin:  8, name: 'A3',   type: 'input' },
      { pin:  9, name: 'B3',   type: 'output' },
      { pin: 10, name: 'GND',  type: 'power' },
      { pin: 11, name: 'B4',   type: 'output' },
      { pin: 12, name: 'A4',   type: 'input' },
      { pin: 13, name: 'NC1',  type: 'nc' },
      { pin: 14, name: 'NC2',  type: 'nc' },
      { pin: 15, name: 'NC3',  type: 'nc' },
      { pin: 16, name: 'NC4',  type: 'nc' },
      { pin: 17, name: 'NC5',  type: 'nc' },
      { pin: 18, name: 'NC6',  type: 'nc' },
      { pin: 19, name: 'NC7',  type: 'nc' },
      { pin: 20, name: 'VCC',  type: 'power' },
    ],
    gates: [
      { type: 'BUS_XCVR_QUAD_TRI_OC',
        inputs:  ['OE1n','OE2n','DIR','A1','A2','A3','A4'],
        outputs: ['B1','B2','B3','B4'] },
    ],
  },

  // ── 74441: Quad tridirectional transceiver, inverting, OC ───────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Open_collector
     Wikipedia: https://en.wikipedia.org/wiki/Bus_transceiver */
  '74x441': {
    name: '74x441',
    simpleName: 'Quad Tridirnl Xcvr (Inv, OC)',
    description: 'Quad tridirectional bus transceiver, inverting, open collector (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    openCollector: true,
    tags: ['transceiver', 'quad', 'bidirectional', 'inverting', 'open collector'],
    guideOverview: 'The 74x441 is an inverting quad tridirectional bus transceiver with open collector outputs. It is identical in control to the 74x440 but inverts the data on the output side. Useful when bus polarity needs to be reversed between two circuit domains.',
    guidePinDescriptions: {
      'OE1n': 'Output Enable 1 (active LOW).',
      'OE2n': 'Output Enable 2 (active LOW).',
      'DIR':  'Direction. HIGH = A to B (inverted); LOW = B to A (inverted).',
      'A1':   'Side A pin 1.',
      'B1':   'Side B pin 1 (OC, inverted from A1).',
      'A2':   'Side A pin 2.',
      'B2':   'Side B pin 2.',
      'A3':   'Side A pin 3.',
      'B3':   'Side B pin 3.',
      'GND':  'Ground reference (pin 10).',
      'B4':   'Side B pin 4.',
      'A4':   'Side A pin 4.',
      'NC1':  'No connect.',
      'NC2':  'No connect.',
      'NC3':  'No connect.',
      'NC4':  'No connect.',
      'NC5':  'No connect.',
      'NC6':  'No connect.',
      'NC7':  'No connect.',
      'VCC':  'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'Inverting Transceiver',
        paragraphs: [
          'By inverting the data in transit, the 74x441 allows a system that uses positive logic on one bus and negative logic on another to communicate without external inverters.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'OE1n', type: 'input' },
      { pin:  2, name: 'OE2n', type: 'input' },
      { pin:  3, name: 'DIR',  type: 'input' },
      { pin:  4, name: 'A1',   type: 'input' },
      { pin:  5, name: 'B1',   type: 'output' },
      { pin:  6, name: 'A2',   type: 'input' },
      { pin:  7, name: 'B2',   type: 'output' },
      { pin:  8, name: 'A3',   type: 'input' },
      { pin:  9, name: 'B3',   type: 'output' },
      { pin: 10, name: 'GND',  type: 'power' },
      { pin: 11, name: 'B4',   type: 'output' },
      { pin: 12, name: 'A4',   type: 'input' },
      { pin: 13, name: 'NC1',  type: 'nc' },
      { pin: 14, name: 'NC2',  type: 'nc' },
      { pin: 15, name: 'NC3',  type: 'nc' },
      { pin: 16, name: 'NC4',  type: 'nc' },
      { pin: 17, name: 'NC5',  type: 'nc' },
      { pin: 18, name: 'NC6',  type: 'nc' },
      { pin: 19, name: 'NC7',  type: 'nc' },
      { pin: 20, name: 'VCC',  type: 'power' },
    ],
    gates: [
      { type: 'BUS_XCVR_QUAD_INV_OC',
        inputs:  ['OE1n','OE2n','DIR','A1','A2','A3','A4'],
        outputs: ['B1','B2','B3','B4'] },
    ],
  },

  // ── 74442: Quad tridirectional transceiver, non inverting, tri state ─────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Three-state_logic
     Wikipedia: https://en.wikipedia.org/wiki/Open_collector
     Wikipedia: https://en.wikipedia.org/wiki/Bus_transceiver */
  '74x442': {
    name: '74x442',
    simpleName: 'Quad Tridirnl Xcvr (3-state)',
    description: 'Quad tridirectional bus transceiver, non inverting, tri state (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    tags: ['transceiver', 'quad', 'bidirectional', 'tri state'],
    guideOverview: 'The 74x442 is a quad non inverting tridirectional bus transceiver with tri state outputs. It is the tri state counterpart of the 74x440 (which is open collector). DIR controls data direction; OE1n and OE2n (both active LOW) must both be asserted to enable data flow.',
    guidePinDescriptions: {
      'OE1n': 'Output Enable 1 (active LOW).',
      'OE2n': 'Output Enable 2 (active LOW).',
      'DIR':  'Direction. HIGH = A to B; LOW = B to A.',
      'A1':   'Side A pin 1.',
      'B1':   'Side B pin 1.',
      'A2':   'Side A pin 2.',
      'B2':   'Side B pin 2.',
      'A3':   'Side A pin 3.',
      'B3':   'Side B pin 3.',
      'GND':  'Ground reference (pin 10).',
      'B4':   'Side B pin 4.',
      'A4':   'Side A pin 4.',
      'NC1':  'No connect.',
      'NC2':  'No connect.',
      'NC3':  'No connect.',
      'NC4':  'No connect.',
      'NC5':  'No connect.',
      'NC6':  'No connect.',
      'NC7':  'No connect.',
      'VCC':  'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: '74x440/441/442/443/444 Family',
        paragraphs: [
          'These five chips form a matrix of inverting/non inverting and OC/tri state options. The 74x442 is the non inverting, tri state version. Choose based on whether your bus uses wired OR (OC) or totem pole (tri state) signaling, and whether data polarity needs inversion.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'OE1n', type: 'input' },
      { pin:  2, name: 'OE2n', type: 'input' },
      { pin:  3, name: 'DIR',  type: 'input' },
      { pin:  4, name: 'A1',   type: 'input' },
      { pin:  5, name: 'B1',   type: 'output' },
      { pin:  6, name: 'A2',   type: 'input' },
      { pin:  7, name: 'B2',   type: 'output' },
      { pin:  8, name: 'A3',   type: 'input' },
      { pin:  9, name: 'B3',   type: 'output' },
      { pin: 10, name: 'GND',  type: 'power' },
      { pin: 11, name: 'B4',   type: 'output' },
      { pin: 12, name: 'A4',   type: 'input' },
      { pin: 13, name: 'NC1',  type: 'nc' },
      { pin: 14, name: 'NC2',  type: 'nc' },
      { pin: 15, name: 'NC3',  type: 'nc' },
      { pin: 16, name: 'NC4',  type: 'nc' },
      { pin: 17, name: 'NC5',  type: 'nc' },
      { pin: 18, name: 'NC6',  type: 'nc' },
      { pin: 19, name: 'NC7',  type: 'nc' },
      { pin: 20, name: 'VCC',  type: 'power' },
    ],
    gates: [
      { type: 'BUS_XCVR_QUAD_TRI',
        inputs:  ['OE1n','OE2n','DIR','A1','A2','A3','A4'],
        outputs: ['B1','B2','B3','B4'] },
    ],
  },

  // ── 74443: Quad tridirectional transceiver, inverting, tri state ─────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Three-state_logic
     Wikipedia: https://en.wikipedia.org/wiki/Bus_transceiver */
  '74x443': {
    name: '74x443',
    simpleName: 'Quad Tridirnl Xcvr (Inv, 3-state)',
    description: 'Quad tridirectional bus transceiver, inverting, tri state (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    tags: ['transceiver', 'quad', 'bidirectional', 'inverting', 'tri state'],
    guideOverview: 'The 74x443 is an inverting quad tridirectional bus transceiver with tri state outputs. It is identical to 74x442 except data is inverted in transit. Useful for interfacing two buses where one uses inverted polarity (e.g., active HIGH to active LOW bus conversion).',
    guidePinDescriptions: {
      'OE1n': 'Output Enable 1 (active LOW).',
      'OE2n': 'Output Enable 2 (active LOW).',
      'DIR':  'Direction. HIGH = A to B (inverted); LOW = B to A (inverted).',
      'A1':   'Side A pin 1.',
      'B1':   'Side B pin 1 (inverted from A1).',
      'A2':   'Side A pin 2.',
      'B2':   'Side B pin 2.',
      'A3':   'Side A pin 3.',
      'B3':   'Side B pin 3.',
      'GND':  'Ground reference (pin 10).',
      'B4':   'Side B pin 4.',
      'A4':   'Side A pin 4.',
      'NC1':  'No connect.',
      'NC2':  'No connect.',
      'NC3':  'No connect.',
      'NC4':  'No connect.',
      'NC5':  'No connect.',
      'NC6':  'No connect.',
      'NC7':  'No connect.',
      'VCC':  'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'Inverting Tri State Transceiver',
        paragraphs: [
          'The combination of inversion and tri state outputs makes the 74x443 useful for bus isolation with polarity translation. Unlike OC versions, no pull up resistors are needed, giving faster edges on long lines.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'OE1n', type: 'input' },
      { pin:  2, name: 'OE2n', type: 'input' },
      { pin:  3, name: 'DIR',  type: 'input' },
      { pin:  4, name: 'A1',   type: 'input' },
      { pin:  5, name: 'B1',   type: 'output' },
      { pin:  6, name: 'A2',   type: 'input' },
      { pin:  7, name: 'B2',   type: 'output' },
      { pin:  8, name: 'A3',   type: 'input' },
      { pin:  9, name: 'B3',   type: 'output' },
      { pin: 10, name: 'GND',  type: 'power' },
      { pin: 11, name: 'B4',   type: 'output' },
      { pin: 12, name: 'A4',   type: 'input' },
      { pin: 13, name: 'NC1',  type: 'nc' },
      { pin: 14, name: 'NC2',  type: 'nc' },
      { pin: 15, name: 'NC3',  type: 'nc' },
      { pin: 16, name: 'NC4',  type: 'nc' },
      { pin: 17, name: 'NC5',  type: 'nc' },
      { pin: 18, name: 'NC6',  type: 'nc' },
      { pin: 19, name: 'NC7',  type: 'nc' },
      { pin: 20, name: 'VCC',  type: 'power' },
    ],
    gates: [
      { type: 'BUS_XCVR_QUAD_INV_TRI',
        inputs:  ['OE1n','OE2n','DIR','A1','A2','A3','A4'],
        outputs: ['B1','B2','B3','B4'] },
    ],
  },

  // ── 74444: Quad tridirectional transceiver, inv & non inv, tri state ─────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Three-state_logic
     Wikipedia: https://en.wikipedia.org/wiki/Bus_transceiver */
  '74x444': {
    name: '74x444',
    simpleName: 'Quad Tridirnl Xcvr (Mix, 3-state)',
    description: 'Quad tridirectional bus transceiver, inv and non-inv, 3-state (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    tags: ['transceiver', 'quad', 'bidirectional', 'tri state'],
    guideOverview: 'The 74x444 is a mixed polarity quad tridirectional bus transceiver with tri state outputs. Two channels are non inverting and two are inverting, allowing address/data bus translations where only some lines need polarity inversion. DIR and OE1n/OE2n work the same as the rest of the 744xx transceiver family.',
    guidePinDescriptions: {
      'OE1n': 'Output Enable 1 (active LOW).',
      'OE2n': 'Output Enable 2 (active LOW).',
      'DIR':  'Direction. HIGH = A to B; LOW = B to A.',
      'A1':   'Side A pin 1.',
      'B1':   'Side B pin 1.',
      'A2':   'Side A pin 2.',
      'B2':   'Side B pin 2.',
      'A3':   'Side A pin 3.',
      'B3':   'Side B pin 3.',
      'GND':  'Ground reference (pin 10).',
      'B4':   'Side B pin 4.',
      'A4':   'Side A pin 4.',
      'NC1':  'No connect.',
      'NC2':  'No connect.',
      'NC3':  'No connect.',
      'NC4':  'No connect.',
      'NC5':  'No connect.',
      'NC6':  'No connect.',
      'NC7':  'No connect.',
      'VCC':  'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'Mixed Polarity Transceiver',
        paragraphs: [
          'The mixed polarity configuration is useful when a bus has both inverted and non inverted lines. For example, some early CPU address buses used active LOW lower bits and active HIGH upper bits. The 74x444 handles the mix in one package.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'OE1n', type: 'input' },
      { pin:  2, name: 'OE2n', type: 'input' },
      { pin:  3, name: 'DIR',  type: 'input' },
      { pin:  4, name: 'A1',   type: 'input' },
      { pin:  5, name: 'B1',   type: 'output' },
      { pin:  6, name: 'A2',   type: 'input' },
      { pin:  7, name: 'B2',   type: 'output' },
      { pin:  8, name: 'A3',   type: 'input' },
      { pin:  9, name: 'B3',   type: 'output' },
      { pin: 10, name: 'GND',  type: 'power' },
      { pin: 11, name: 'B4',   type: 'output' },
      { pin: 12, name: 'A4',   type: 'input' },
      { pin: 13, name: 'NC1',  type: 'nc' },
      { pin: 14, name: 'NC2',  type: 'nc' },
      { pin: 15, name: 'NC3',  type: 'nc' },
      { pin: 16, name: 'NC4',  type: 'nc' },
      { pin: 17, name: 'NC5',  type: 'nc' },
      { pin: 18, name: 'NC6',  type: 'nc' },
      { pin: 19, name: 'NC7',  type: 'nc' },
      { pin: 20, name: 'VCC',  type: 'power' },
    ],
    gates: [
      { type: 'BUS_XCVR_QUAD_MIX_TRI',
        inputs:  ['OE1n','OE2n','DIR','A1','A2','A3','A4'],
        outputs: ['B1','B2','B3','B4'] },
    ],
  },

  // ── 74445: BCD to decimal decoder/driver ─────────────────────────────────
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Multiplexer */
  '74x445': {
    name: '74x445',
    simpleName: 'BCD→Decimal Decoder',
    description: 'BCD to decimal decoders/drivers (80 mA outputs) (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    tags: ['decoder', 'bcd', 'decimal', 'driver'],
    guideOverview: 'The 74x445 decodes a 4 bit BCD input (A-D) to one of ten active LOW outputs (Y0-Y9) with high output drive capability (80 mA sink per output). Used to directly drive incandescent displays, relays, or TTL bus lines without additional driver transistors. Invalid BCD codes (10-15) leave all outputs HIGH.',
    guidePinDescriptions: {
      'A':   'BCD input bit A (weight 1, LSB).',
      'B':   'BCD input bit B (weight 2).',
      'C':   'BCD input bit C (weight 4).',
      'D':   'BCD input bit D (weight 8, MSB).',
      'Y0':  'Output 0 (active LOW when BCD = 0000).',
      'Y1':  'Output 1 (active LOW when BCD = 0001).',
      'Y2':  'Output 2 (active LOW when BCD = 0010).',
      'GND': 'Ground reference (pin 8).',
      'Y3':  'Output 3 (active LOW when BCD = 0011).',
      'Y4':  'Output 4 (active LOW when BCD = 0100).',
      'Y5':  'Output 5 (active LOW when BCD = 0101).',
      'Y6':  'Output 6 (active LOW when BCD = 0110).',
      'Y7':  'Output 7 (active LOW when BCD = 0111).',
      'Y8':  'Output 8 (active LOW when BCD = 1000).',
      'Y9':  'Output 9 (active LOW when BCD = 1001).',
      'VCC': 'Positive supply (+5 V, pin 16).',
    },
    guideSections: [
      {
        title: 'BCD to Decimal-Decoding',
        paragraphs: [
          'BCD (Binary Coded Decimal) represents digits 0-9 as 4 bit binary patterns. The 74x445 converts each BCD code to a single asserted output only one of the ten outputs is LOW at a time.',
          'The high sink current (80 mA) means you can connect indicator lamps or relays directly to the outputs with appropriate current limiting.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'A',   type: 'input' },
      { pin:  2, name: 'B',   type: 'input' },
      { pin:  3, name: 'C',   type: 'input' },
      { pin:  4, name: 'D',   type: 'input' },
      { pin:  5, name: 'Y0',  type: 'output' },
      { pin:  6, name: 'Y1',  type: 'output' },
      { pin:  7, name: 'Y2',  type: 'output' },
      { pin:  8, name: 'GND', type: 'power' },
      { pin:  9, name: 'Y3',  type: 'output' },
      { pin: 10, name: 'Y4',  type: 'output' },
      { pin: 11, name: 'Y5',  type: 'output' },
      { pin: 12, name: 'Y6',  type: 'output' },
      { pin: 13, name: 'Y7',  type: 'output' },
      { pin: 14, name: 'Y8',  type: 'output' },
      { pin: 15, name: 'Y9',  type: 'output' },
      { pin: 16, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'BCD_DECIMAL', inputs: ['A','B','C','D'], outputs: ['Y0','Y1','Y2','Y3','Y4','Y5','Y6','Y7','Y8','Y9'] },
    ],
  },

};
// end of CHIPS_BLOCK_25
