// chips65.js Block 65: 74x9135 .. 74120 (15 chips)
// Implementable: 74x9135 (nine-wide buffer OC), 74x9240 (9 bit inv tri-state),
//   74x9244 (9 bit non-inv tri-state), 74x9541 (8 bit dual-OE buffer)
// Stubs: 74x9164, 74x9245, 74x9323, 74x9595, 74x40102, 74x40103,
//   74x40104, 74x40105, 74116, 74119, 74120
// NOTE: 7453 omitted already implemented in chips8.js

export const CHIPS_BLOCK_65 = {

  // ═══════════════════════════════════════════════════════════════════════
  // IMPLEMENTABLE
  // ═══════════════════════════════════════════════════════════════════════

  // ── 74x9135: Nine-wide buffer, non-inverting, open-collector (20-pin) ─
  /* Primary source: 74x9135 datasheet   URL not yet verified.
     https://en.wikipedia.org/wiki/Open_collector */
  '74x9135': {
    name: '74x9135',
    simpleName: 'Nine-Wide Buffer OC',
    description: 'Nine-wide non-inverting buffer with open-collector outputs (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    openCollector: true,
    datasheet: '',
    tags: ['buffer', 'nine-wide', 'open-collector'],
    guideOverview: 'The 74x9135 is a nine-wide non-inverting buffer with open-collector outputs, useful when you need to buffer a wide control word while retaining the ability to share pull up lines or create wired AND logic. Each of the nine inputs passes through to its corresponding open-collector output, which can only pull LOW actively; an external pull up resistor is required to produce a HIGH level. The nine-bit width conveniently handles a data byte plus a parity or control bit in one package.',
    pinout: [
      { pin:  1, name: 'A1', type: 'input'  },
      { pin:  2, name: 'A2', type: 'input'  },
      { pin:  3, name: 'A3', type: 'input'  },
      { pin:  4, name: 'A4', type: 'input'  },
      { pin:  5, name: 'A5', type: 'input'  },
      { pin:  6, name: 'A6', type: 'input'  },
      { pin:  7, name: 'A7', type: 'input'  },
      { pin:  8, name: 'A8', type: 'input'  },
      { pin:  9, name: 'A9', type: 'input'  },
      { pin: 10, name: 'GND', type: 'power' },
      { pin: 11, name: 'Y9', type: 'output' },
      { pin: 12, name: 'Y8', type: 'output' },
      { pin: 13, name: 'Y7', type: 'output' },
      { pin: 14, name: 'Y6', type: 'output' },
      { pin: 15, name: 'Y5', type: 'output' },
      { pin: 16, name: 'Y4', type: 'output' },
      { pin: 17, name: 'Y3', type: 'output' },
      { pin: 18, name: 'Y2', type: 'output' },
      { pin: 19, name: 'Y1', type: 'output' },
      { pin: 20, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'BUFFER', inputs: ['A1'], output: 'Y1' },
      { type: 'BUFFER', inputs: ['A2'], output: 'Y2' },
      { type: 'BUFFER', inputs: ['A3'], output: 'Y3' },
      { type: 'BUFFER', inputs: ['A4'], output: 'Y4' },
      { type: 'BUFFER', inputs: ['A5'], output: 'Y5' },
      { type: 'BUFFER', inputs: ['A6'], output: 'Y6' },
      { type: 'BUFFER', inputs: ['A7'], output: 'Y7' },
      { type: 'BUFFER', inputs: ['A8'], output: 'Y8' },
      { type: 'BUFFER', inputs: ['A9'], output: 'Y9' },
    ],
  },

  // ── 74x9240: 9 bit inverting buffer / line driver, tri-state (24-pin) ─
  /* Primary source: 74x9240 datasheet   URL not yet verified.
     https://en.wikipedia.org/wiki/Three-state_logic */
  '74x9240': {
    name: '74x9240',
    simpleName: '9 bit Inv Buffer (TRI)',
    description: '9 bit inverting buffer / line driver with three-state outputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['buffer', 'driver', '9 bit', 'inverting', 'tri-state'],
    guideOverview: 'The 74x9240 is a 9 bit inverting buffer and line driver with 3-state outputs. Each input is logically inverted on its way to the corresponding output. Output enable (active LOW) places all nine outputs in high-Z simultaneously. The nine-bit width covers a full byte plus a parity bit in one package, which is convenient for backplane bus drivers where stronger drive current and defined propagation delay matter.',
    pinout: [
      { pin:  1, name: 'OEn', type: 'input'  },
      { pin:  2, name: 'A1',  type: 'input'  },
      { pin:  3, name: 'A2',  type: 'input'  },
      { pin:  4, name: 'A3',  type: 'input'  },
      { pin:  5, name: 'A4',  type: 'input'  },
      { pin:  6, name: 'A5',  type: 'input'  },
      { pin:  7, name: 'A6',  type: 'input'  },
      { pin:  8, name: 'A7',  type: 'input'  },
      { pin:  9, name: 'A8',  type: 'input'  },
      { pin: 10, name: 'A9',  type: 'input'  },
      { pin: 11, name: 'NC1', type: 'nc'     },
      { pin: 12, name: 'GND', type: 'power'  },
      { pin: 13, name: 'Y9',  type: 'output' },
      { pin: 14, name: 'Y8',  type: 'output' },
      { pin: 15, name: 'Y7',  type: 'output' },
      { pin: 16, name: 'Y6',  type: 'output' },
      { pin: 17, name: 'Y5',  type: 'output' },
      { pin: 18, name: 'Y4',  type: 'output' },
      { pin: 19, name: 'Y3',  type: 'output' },
      { pin: 20, name: 'Y2',  type: 'output' },
      { pin: 21, name: 'Y1',  type: 'output' },
      { pin: 22, name: 'NC2', type: 'nc'     },
      { pin: 23, name: 'NC3', type: 'nc'     },
      { pin: 24, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'TRI_NOT_LO', inputs: ['A1', 'OEn'], output: 'Y1' },
      { type: 'TRI_NOT_LO', inputs: ['A2', 'OEn'], output: 'Y2' },
      { type: 'TRI_NOT_LO', inputs: ['A3', 'OEn'], output: 'Y3' },
      { type: 'TRI_NOT_LO', inputs: ['A4', 'OEn'], output: 'Y4' },
      { type: 'TRI_NOT_LO', inputs: ['A5', 'OEn'], output: 'Y5' },
      { type: 'TRI_NOT_LO', inputs: ['A6', 'OEn'], output: 'Y6' },
      { type: 'TRI_NOT_LO', inputs: ['A7', 'OEn'], output: 'Y7' },
      { type: 'TRI_NOT_LO', inputs: ['A8', 'OEn'], output: 'Y8' },
      { type: 'TRI_NOT_LO', inputs: ['A9', 'OEn'], output: 'Y9' },
    ],
  },

  // ── 74x9244: 9 bit non-inverting buffer / line driver, tri-state (24-pin)
  /* Primary source: 74x9244 datasheet   URL not yet verified.
     https://en.wikipedia.org/wiki/Three-state_logic */
  '74x9244': {
    name: '74x9244',
    simpleName: '9 bit Buffer (TRI)',
    description: '9 bit non-inverting buffer / line driver with three-state outputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['buffer', 'driver', '9 bit', 'non-inverting', 'tri-state'],
    guideOverview: 'The 74x9244 is a 9 bit non-inverting buffer and line driver with 3-state outputs. Each input passes through to the corresponding output without inversion. Output enable (active LOW) places all nine outputs in high-Z simultaneously. The nine-bit width carries a byte plus an extra parity or status bit in one package, making it a natural fit for byte-wide bus buffers that also need to pass parity information on a shared backplane.',
    pinout: [
      { pin:  1, name: 'OEn', type: 'input'  },
      { pin:  2, name: 'A1',  type: 'input'  },
      { pin:  3, name: 'A2',  type: 'input'  },
      { pin:  4, name: 'A3',  type: 'input'  },
      { pin:  5, name: 'A4',  type: 'input'  },
      { pin:  6, name: 'A5',  type: 'input'  },
      { pin:  7, name: 'A6',  type: 'input'  },
      { pin:  8, name: 'A7',  type: 'input'  },
      { pin:  9, name: 'A8',  type: 'input'  },
      { pin: 10, name: 'A9',  type: 'input'  },
      { pin: 11, name: 'NC1', type: 'nc'     },
      { pin: 12, name: 'GND', type: 'power'  },
      { pin: 13, name: 'Y9',  type: 'output' },
      { pin: 14, name: 'Y8',  type: 'output' },
      { pin: 15, name: 'Y7',  type: 'output' },
      { pin: 16, name: 'Y6',  type: 'output' },
      { pin: 17, name: 'Y5',  type: 'output' },
      { pin: 18, name: 'Y4',  type: 'output' },
      { pin: 19, name: 'Y3',  type: 'output' },
      { pin: 20, name: 'Y2',  type: 'output' },
      { pin: 21, name: 'Y1',  type: 'output' },
      { pin: 22, name: 'NC2', type: 'nc'     },
      { pin: 23, name: 'NC3', type: 'nc'     },
      { pin: 24, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'TRI_BUFFER_LO', inputs: ['A1', 'OEn'], output: 'Y1' },
      { type: 'TRI_BUFFER_LO', inputs: ['A2', 'OEn'], output: 'Y2' },
      { type: 'TRI_BUFFER_LO', inputs: ['A3', 'OEn'], output: 'Y3' },
      { type: 'TRI_BUFFER_LO', inputs: ['A4', 'OEn'], output: 'Y4' },
      { type: 'TRI_BUFFER_LO', inputs: ['A5', 'OEn'], output: 'Y5' },
      { type: 'TRI_BUFFER_LO', inputs: ['A6', 'OEn'], output: 'Y6' },
      { type: 'TRI_BUFFER_LO', inputs: ['A7', 'OEn'], output: 'Y7' },
      { type: 'TRI_BUFFER_LO', inputs: ['A8', 'OEn'], output: 'Y8' },
      { type: 'TRI_BUFFER_LO', inputs: ['A9', 'OEn'], output: 'Y9' },
    ],
  },

  // ── 74x9541: 8 bit buffer / line driver, selectable inv/non-inv, Schmitt, dual OE (20-pin)
  /* Primary source: Texas Instruments, 74x9541 datasheet. [Online]. Available: https://www.ti.com/product/SN74AHC541
     https://en.wikipedia.org/wiki/Three-state_logic */
  '74x9541': {
    name: '74x9541',
    simpleName: '8 bit Dual-OE Buffer (ST)',
    description: '8 bit non-inverting buffer / line driver with Schmitt-trigger inputs and dual active LOW output enable (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.ti.com/product/SN74AHC541',
    tags: ['buffer', 'driver', 'octal', 'tri-state', 'Schmitt-trigger', 'dual-OE'],
    guideOverview: 'The 74x9541 is an 8 bit non-inverting buffer and line driver with Schmitt-trigger inputs and two independent active LOW output-enable pins (OE1 and OE2). Outputs are driven when both OE1 and OE2 are LOW; if either is HIGH the outputs go to high-impedance. The closest live manufacturer reference is TI\'s SN74AHC541, which implements the same dual active LOW enable, non-inverting, 20-pin topology.',
    guidePinDescriptions: {
      'OE1': 'Active LOW output enable 1 (pin 1). Outputs are driven only when both OE1 and OE2 are LOW.',
      'A1': 'Input channel 1.',
      'A2': 'Input channel 2.',
      'A3': 'Input channel 3.',
      'A4': 'Input channel 4.',
      'A5': 'Input channel 5.',
      'A6': 'Input channel 6.',
      'A7': 'Input channel 7.',
      'A8': 'Input channel 8.',
      'GND': 'Ground reference for the device.',
      'Y8': 'Output channel 8.',
      'Y7': 'Output channel 7.',
      'Y6': 'Output channel 6.',
      'Y5': 'Output channel 5.',
      'Y4': 'Output channel 4.',
      'Y3': 'Output channel 3.',
      'Y2': 'Output channel 2.',
      'Y1': 'Output channel 1.',
      'OE2': 'Active LOW output enable 2 (pin 19). Outputs are driven only when both OE1 and OE2 are LOW.',
      'VCC': 'Positive supply for the device.',
    },
    guideSections: [
      {
        title: 'Output Enable Logic',
        paragraphs: [
          'Both OE1 (pin 1) and OE2 (pin 19) must be LOW for outputs to be active. If either enable is HIGH, all eight outputs enter high-impedance state. This allows two independent control sources to gate the bus driver.',
        ],
      },
      {
        title: 'Live Family Reference',
        paragraphs: [
          'The TI SN74AHC541 (https://www.ti.com/product/SN74AHC541) implements the same dual active LOW OE, non-inverting, 20-pin octal buffer topology and serves as the authoritative datasheet reference for this entry.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'OE1', type: 'input'  },
      { pin:  2, name: 'A1',  type: 'input'  },
      { pin:  3, name: 'A2',  type: 'input'  },
      { pin:  4, name: 'A3',  type: 'input'  },
      { pin:  5, name: 'A4',  type: 'input'  },
      { pin:  6, name: 'A5',  type: 'input'  },
      { pin:  7, name: 'A6',  type: 'input'  },
      { pin:  8, name: 'A7',  type: 'input'  },
      { pin:  9, name: 'A8',  type: 'input'  },
      { pin: 10, name: 'GND', type: 'power'  },
      { pin: 11, name: 'Y8',  type: 'output' },
      { pin: 12, name: 'Y7',  type: 'output' },
      { pin: 13, name: 'Y6',  type: 'output' },
      { pin: 14, name: 'Y5',  type: 'output' },
      { pin: 15, name: 'Y4',  type: 'output' },
      { pin: 16, name: 'Y3',  type: 'output' },
      { pin: 17, name: 'Y2',  type: 'output' },
      { pin: 18, name: 'Y1',  type: 'output' },
      { pin: 19, name: 'OE2', type: 'input'  },
      { pin: 20, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'TRI_BUFFER_DUAL_OE', inputs: ['A1', 'OE1', 'OE2'], output: 'Y1' },
      { type: 'TRI_BUFFER_DUAL_OE', inputs: ['A2', 'OE1', 'OE2'], output: 'Y2' },
      { type: 'TRI_BUFFER_DUAL_OE', inputs: ['A3', 'OE1', 'OE2'], output: 'Y3' },
      { type: 'TRI_BUFFER_DUAL_OE', inputs: ['A4', 'OE1', 'OE2'], output: 'Y4' },
      { type: 'TRI_BUFFER_DUAL_OE', inputs: ['A5', 'OE1', 'OE2'], output: 'Y5' },
      { type: 'TRI_BUFFER_DUAL_OE', inputs: ['A6', 'OE1', 'OE2'], output: 'Y6' },
      { type: 'TRI_BUFFER_DUAL_OE', inputs: ['A7', 'OE1', 'OE2'], output: 'Y7' },
      { type: 'TRI_BUFFER_DUAL_OE', inputs: ['A8', 'OE1', 'OE2'], output: 'Y8' },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // STUBS
  // ═══════════════════════════════════════════════════════════════════════

  // ── 74x9164: 8 bit shift register, serial/parallel I/O, ST, TRI (16-pin)
  /* Primary source: 74x9164 datasheet   URL not yet verified.
     https://en.wikipedia.org/wiki/Shift_register */
  '74x9164': {
    name: '74x9164',
    simpleName: '8 bit Shift Reg (S/P I/O)',
    description: '8 bit shift register with serial in/out and parallel in/out, Schmitt-trigger inputs, three-state outputs (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    datasheet: '',
    tags: ['shift-register', '8 bit', 'serial', 'parallel', 'Schmitt-trigger', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x9164 is an 8 bit shift register with serial and parallel data paths, Schmitt-trigger inputs, and 3-state parallel outputs. A MODE pin selects between serial shift and parallel load operations on each rising clock edge. The serial output (QSER) follows the last stage for cascading. Output enable (active LOW) places the parallel outputs in high-Z without affecting the shift register contents. Schmitt-trigger inputs give the part better noise immunity than standard TTL, useful when clock or data lines have slow edges or noise. The simulator currently represents this as a generic stub.',
    pinout: [
      { pin:  1, name: 'SER',  type: 'input'  },
      { pin:  2, name: 'D0',   type: 'input'  },
      { pin:  3, name: 'D1',   type: 'input'  },
      { pin:  4, name: 'D2',   type: 'input'  },
      { pin:  5, name: 'D3',   type: 'input'  },
      { pin:  6, name: 'CLK',  type: 'input'  },
      { pin:  7, name: 'MODE', type: 'input'  },
      { pin:  8, name: 'GND',  type: 'power'  },
      { pin:  9, name: 'OEn',  type: 'input'  },
      { pin: 10, name: 'Q0',   type: 'output' },
      { pin: 11, name: 'Q1',   type: 'output' },
      { pin: 12, name: 'Q2',   type: 'output' },
      { pin: 13, name: 'Q3',   type: 'output' },
      { pin: 14, name: 'Q4',   type: 'output' },
      { pin: 15, name: 'QSER', type: 'output' },
      { pin: 16, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['SER','D0','D1','D2','D3','CLK','MODE','OEn'], outputs: ['Q0','Q1','Q2','Q3','Q4','QSER'] },
    ],
  },

  // ── 74x9245: 9 bit bidirectional transceiver, non-inverting, TRI (24-pin)
  /* Primary source: 74x9245 datasheet   URL not yet verified.
     https://en.wikipedia.org/wiki/Bus_transceiver */
  '74x9245': {
    name: '74x9245',
    simpleName: '9 bit Transceiver',
    description: '9 bit bidirectional bus transceiver with three-state outputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['transceiver', 'bus', '9 bit', 'tri-state', 'bidirectional', 'stub'],
    guideOverview: 'The 74x9245 is a 9 bit bidirectional bus transceiver with 3-state outputs. A direction (DIR) pin selects whether data flows from the A port to the B port or vice versa, and output enable (active LOW) disconnects all nine lines simultaneously. The ninth bit is typically used for bus parity. On a breadboard it is the nine-bit equivalent of the popular 74245 and allows two buses to be loosely coupled with parity included. The simulator currently represents this as a generic stub.',
    pinout: [
      { pin:  1, name: 'DIR', type: 'input'  },
      { pin:  2, name: 'A1',  type: 'input'  },
      { pin:  3, name: 'A2',  type: 'input'  },
      { pin:  4, name: 'A3',  type: 'input'  },
      { pin:  5, name: 'A4',  type: 'input'  },
      { pin:  6, name: 'A5',  type: 'input'  },
      { pin:  7, name: 'A6',  type: 'input'  },
      { pin:  8, name: 'A7',  type: 'input'  },
      { pin:  9, name: 'A8',  type: 'input'  },
      { pin: 10, name: 'A9',  type: 'input'  },
      { pin: 11, name: 'NC1', type: 'nc'     },
      { pin: 12, name: 'GND', type: 'power'  },
      { pin: 13, name: 'OEn', type: 'input'  },
      { pin: 14, name: 'B9',  type: 'input'  },
      { pin: 15, name: 'B8',  type: 'input'  },
      { pin: 16, name: 'B7',  type: 'input'  },
      { pin: 17, name: 'B6',  type: 'input'  },
      { pin: 18, name: 'B5',  type: 'input'  },
      { pin: 19, name: 'B4',  type: 'input'  },
      { pin: 20, name: 'B3',  type: 'input'  },
      { pin: 21, name: 'B2',  type: 'input'  },
      { pin: 22, name: 'B1',  type: 'input'  },
      { pin: 23, name: 'NC2', type: 'nc'     },
      { pin: 24, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['DIR','OEn','A1','A2','A3','A4','A5','A6','A7','A8','A9','B1','B2','B3','B4','B5','B6','B7','B8','B9'], outputs: ['A1','A2','A3','A4','A5','A6','A7','A8','A9','B1','B2','B3','B4','B5','B6','B7','B8','B9'] },
    ],
  },

  // ── 74x9323: Programmable ripple counter with oscillator, TRI (8-pin) ──
  /* Primary source: 74x9323 datasheet   URL not yet verified.
     https://en.wikipedia.org/wiki/Counter_(digital) */
  '74x9323': {
    name: '74x9323',
    simpleName: 'Prog Ripple Counter',
    description: 'Programmable ripple counter with oscillator, three-state output (8-pin)',
    pins: 8, vcc: 8, gnd: 4,
    datasheet: '',
    tags: ['counter', 'oscillator', 'programmable', 'ripple', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x9323 is a programmable ripple counter with a built in oscillator in an 8-pin package. Two select inputs (S0 and S1) choose the divide ratio, allowing the oscillator output to be divided down before appearing at Qout. Output enable (active LOW) disconnects Qout from its downstream load. The tiny package and self-contained oscillator make this a convenient frequency reference or timeout generator on a breadboard when you need a slower periodic signal without a separate clock chip. The simulator currently represents this as a generic stub.',
    pinout: [
      { pin: 1, name: 'OSCin', type: 'input'  },
      { pin: 2, name: 'S0',    type: 'input'  },
      { pin: 3, name: 'S1',    type: 'input'  },
      { pin: 4, name: 'GND',   type: 'power'  },
      { pin: 5, name: 'OEn',   type: 'input'  },
      { pin: 6, name: 'Qout',  type: 'output' },
      { pin: 7, name: 'OSCout',type: 'output' },
      { pin: 8, name: 'VCC',   type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OSCin','S0','S1','OEn'], outputs: ['Qout','OSCout'] },
    ],
  },

  // ── 74x9595: 8 bit shift register with latch, serial in / parallel out, ST (16-pin)
  /* Primary source: Nexperia, 74HC595 datasheet. [Online]. Available: https://www.nexperia.com/products/analog-logic-ics/logic/flip-flops-latches-registers-counters-dividers/shift-registers/series/74HC595-74HCT595.html
     https://en.wikipedia.org/wiki/Shift_register */
  '74x9595': {
    name: '74x9595',
    simpleName: '8 bit Shift Reg/Latch',
    description: '8 bit shift register with latch (serial in, parallel out), Schmitt-trigger inputs (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    datasheet: 'https://www.nexperia.com/products/analog-logic-ics/logic/flip-flops-latches-registers-counters-dividers/shift-registers/series/74HC595-74HCT595.html',
    tags: ['shift-register', 'latch', '8 bit', 'serial-in', 'parallel-out', 'Schmitt-trigger'],
    sequential: true,
    guideOverview: 'The 74x9595 is a serial-in, parallel-out shift register with a separate output latch and Schmitt-trigger inputs, functionally equivalent to the 74HC595 family. Bits enter one at a time on SER, shift forward on each rising SRCLK edge, and are copied to the visible outputs on a rising RCLK edge. Shift-register clear (active LOW) asynchronously clears the shift register without disturbing the output latch. Output enable (active LOW) tri-states QA QH without affecting stored data. QHs always reflects the last shift-register stage for cascading.',
    guidePinDescriptions: {
      'QB': 'Parallel output B from the storage register.',
      'QC': 'Parallel output C from the storage register.',
      'QD': 'Parallel output D from the storage register.',
      'QE': 'Parallel output E from the storage register.',
      'QF': 'Parallel output F from the storage register.',
      'QG': 'Parallel output G from the storage register.',
      'QH': 'Parallel output H from the storage register.',
      'GND': 'Ground reference for the device.',
      'QHs': 'Serial output from the last shift-register stage. Connect to SER of the next chip to cascade.',
      'SRCLRn': 'Shift-register clear (active LOW). Drive LOW to reset all shift register bits to 0. Does not affect the output latch.',
      'SRCLK': 'Shift-register clock. Rising edge shifts data: SER enters first stage, each bit moves to the next.',
      'RCLK': 'Storage register (latch) clock. Rising edge copies current shift register contents to QA QH outputs.',
      'OEn': 'Output enable (active LOW). HIGH tri-states QA QH without affecting stored data. QHs remains active.',
      'SER': 'Serial data input. Sampled on each rising SRCLK edge and shifted into the first stage.',
      'QA': 'Parallel output A (LSB) from the storage register.',
      'VCC': 'Positive supply for the device.',
    },
    guideSections: [
      {
        title: 'Shift Then Latch',
        paragraphs: [
          'SRCLK and RCLK perform different jobs. SRCLK moves bits through the internal shift register one step per rising edge while RCLK publishes the current 8 bit word to QA QH all at once.',
          'The Schmitt-trigger inputs improve noise immunity compared to standard 74HC595, making this variant suitable for noisier environments.',
        ],
        list: [
          'Keep the output enable pin (active LOW) LOW for active parallel outputs, or drive HIGH to disconnect QA QH from the bus without losing data.',
          'Connect QHs to SER of the next chip to daisy-chain registers the SRCLK and RCLK lines are shared.',
        ],
        note: 'The shift-register clear pin (active LOW) clears the shift register only. To clear the visible outputs you must also pulse RCLK after clearing.',
      },
    ],
    pinout: [
      { pin:  1, name: 'QB',    type: 'output' },
      { pin:  2, name: 'QC',    type: 'output' },
      { pin:  3, name: 'QD',    type: 'output' },
      { pin:  4, name: 'QE',    type: 'output' },
      { pin:  5, name: 'QF',    type: 'output' },
      { pin:  6, name: 'QG',    type: 'output' },
      { pin:  7, name: 'QH',    type: 'output' },
      { pin:  8, name: 'GND',   type: 'power'  },
      { pin:  9, name: 'QHs',   type: 'output' },
      { pin: 10, name: 'SRCLRn',type: 'input'  },
      { pin: 11, name: 'SRCLK', type: 'input'  },
      { pin: 12, name: 'RCLK',  type: 'input'  },
      { pin: 13, name: 'OEn',   type: 'input'  },
      { pin: 14, name: 'SER',   type: 'input'  },
      { pin: 15, name: 'QA',    type: 'output' },
      { pin: 16, name: 'VCC',   type: 'power'  },
    ],
    gates: [
      { type: 'SHIFT_REG_LATCH', inputs: ['SER','SRCLK','RCLK','SRCLRn','OEn'], outputs: ['QA','QB','QC','QD','QE','QF','QG','QH','QHs'] },
    ],
  },

  // ── 74x40102: Presettable synchronous 2-decade BCD down counter (16-pin)
  /* Primary source: Texas Instruments, 74x40102 datasheet. [Online]. Available: https://www.ti.com/product/CD40102B
     https://en.wikipedia.org/wiki/Counter_(digital) */
  '74x40102': {
    name: '74x40102',
    simpleName: '2-Decade BCD Down Counter',
    description: 'Presettable synchronous 2-decade BCD down counter (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    datasheet: 'https://www.ti.com/product/CD40102B',
    tags: ['counter', 'BCD', 'decade', 'down', 'presettable', 'synchronous'],
    sequential: true,
    guideOverview: 'The 74x40102 is a presettable synchronous 2-decade BCD down counter (CD40102B). Both BCD digits count downward together on each rising CLK edge when count enable (active LOW) and single-phase enable (active LOW) are LOW. Drive preset enable (active LOW) LOW on a rising CLK edge to synchronously load the preset values (P0 P3 for units, P4 P7 for tens). TCdec goes LOW when the units decade reaches zero; TC goes LOW when both decades reach zero, making cascading straightforward.',
    guidePinDescriptions: {
      'CLK': 'Clock input. Rising edge advances the counter or loads preset.',
      'PEn': 'Synchronous preset enable (active LOW). Hold LOW on a rising CLK edge to load P0 P7.',
      'P0': 'Preset data bit 0 (units decade LSB).',
      'P1': 'Preset data bit 1 (units decade).',
      'P2': 'Preset data bit 2 (units decade).',
      'P3': 'Preset data bit 3 (units decade MSB).',
      'CEn': 'Count enable (active LOW). Both CEn and SPE must be LOW to count.',
      'GND': 'Ground reference for the counter.',
      'TC': 'Terminal count (active LOW). Goes LOW when both BCD decades reach 0.',
      'P4': 'Preset data bit 4 (tens decade LSB).',
      'P5': 'Preset data bit 5 (tens decade).',
      'P6': 'Preset data bit 6 (tens decade).',
      'P7': 'Preset data bit 7 (tens decade MSB).',
      'SPE': 'Single-phase enable (active LOW). Both CEn and SPE must be LOW to count.',
      'TCdec': 'Decoded terminal count (active LOW). Goes LOW when units decade reaches 0.',
      'VCC': 'Positive supply for the device.',
    },
    guideSections: [
      {
        title: 'BCD Down Counting',
        paragraphs: [
          'A BCD down counter works with decimal digits encoded in binary form. Instead of rolling through all 256 binary values it follows decade boundaries units counts 9→8→...→0 and then borrows into the tens digit which is useful for clocks, timers, and numeric displays.',
          'Both count enable (active LOW) and single-phase enable (active LOW) must be LOW for the counter to advance. Pull preset enable (active LOW) LOW on a rising CLK edge to synchronously reload the preset value at any time.',
        ],
        list: [
          'TCdec (pin 15) goes LOW when the units decade reaches 0 use this to enable a cascaded counter.',
          'TC (pin 9) goes LOW only when both decades reach 0 this is the overall borrow output.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'CLK',  type: 'input'  },
      { pin:  2, name: 'PEn',  type: 'input'  },
      { pin:  3, name: 'P0',   type: 'input'  },
      { pin:  4, name: 'P1',   type: 'input'  },
      { pin:  5, name: 'P2',   type: 'input'  },
      { pin:  6, name: 'P3',   type: 'input'  },
      { pin:  7, name: 'CEn',  type: 'input'  },
      { pin:  8, name: 'GND',  type: 'power'  },
      { pin:  9, name: 'TC',   type: 'output' },
      { pin: 10, name: 'P4',   type: 'input'  },
      { pin: 11, name: 'P5',   type: 'input'  },
      { pin: 12, name: 'P6',   type: 'input'  },
      { pin: 13, name: 'P7',   type: 'input'  },
      { pin: 14, name: 'SPE',  type: 'input'  },
      { pin: 15, name: 'TCdec',type: 'output' },
      { pin: 16, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'BCD_DOWN_2DEC', inputs: ['CLK','PEn','P0','P1','P2','P3','P4','P5','P6','P7','CEn','SPE'], outputs: ['TC','TCdec'] },
    ],
  },

  // ── 74x40103: Presettable 8 bit synchronous down counter (16-pin) ─────
  /* Primary source: Texas Instruments, 74x40103 datasheet. [Online]. Available: https://www.ti.com/product/CD74HC40103
     https://en.wikipedia.org/wiki/Counter_(digital) */
  '74x40103': {
    name: '74x40103',
    simpleName: '8 bit Down Counter',
    description: 'Presettable 8 bit synchronous down counter (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    datasheet: 'https://www.ti.com/product/CD74HC40103',
    tags: ['counter', 'binary', '8 bit', 'down', 'presettable', 'synchronous'],
    sequential: true,
    guideOverview: 'The 74x40103 is a presettable synchronous 8 bit binary down counter (CD74HC40103). Load a starting value by holding preset enable (active LOW) LOW on a rising CLK edge; the counter then decrements by 1 on each rising CLK edge when both count enable (active LOW) and single-phase enable (active LOW) are LOW. TC goes active LOW when the counter reaches zero, making it easy to cascade multiple stages for longer delays or divide-by-N functions.',
    guidePinDescriptions: {
      'PEn': 'Synchronous preset enable (active LOW). Hold LOW on a rising CLK edge to load P0 P7.',
      'P5': 'Preset data bit 5.',
      'P4': 'Preset data bit 4.',
      'P3': 'Preset data bit 3.',
      'P6': 'Preset data bit 6.',
      'P7': 'Preset data bit 7 (MSB).',
      'CEn': 'Count enable (active LOW). Both CEn and SPE must be LOW to count.',
      'GND': 'Ground reference for the counter.',
      'TC': 'Terminal count (active LOW). Goes LOW when counter reaches 0.',
      'P0': 'Preset data bit 0 (LSB).',
      'P1': 'Preset data bit 1.',
      'P2': 'Preset data bit 2.',
      'SPE': 'Single-phase enable (active LOW). Both CEn and SPE must be LOW to count.',
      'CLK': 'Clock input. Rising edge decrements the counter or loads preset.',
      'NC': 'No internal connection. Leave unconnected.',
      'VCC': 'Positive supply for the device.',
    },
    guideSections: [
      {
        title: 'Presettable Binary Down Counter',
        paragraphs: [
          'A presettable down counter lets you choose the starting number rather than always beginning at 255. Set preset enable (active LOW) LOW on a rising CLK edge to load any 8 bit value, then the counter steps toward zero one per clock.',
          'Both count enable (active LOW) and single-phase enable (active LOW) must be LOW to enable counting. TC goes LOW when the count reaches 0, at which point the next clock edge wraps the counter back to 255.',
        ],
        list: [
          'To cascade two counters for a 16 bit delay, connect TC of the lower byte to SPE of the upper byte.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'PEn', type: 'input'  },
      { pin:  2, name: 'P5',  type: 'input'  },
      { pin:  3, name: 'P4',  type: 'input'  },
      { pin:  4, name: 'P3',  type: 'input'  },
      { pin:  5, name: 'P6',  type: 'input'  },
      { pin:  6, name: 'P7',  type: 'input'  },
      { pin:  7, name: 'CEn', type: 'input'  },
      { pin:  8, name: 'GND', type: 'power'  },
      { pin:  9, name: 'TC',  type: 'output' },
      { pin: 10, name: 'P0',  type: 'input'  },
      { pin: 11, name: 'P1',  type: 'input'  },
      { pin: 12, name: 'P2',  type: 'input'  },
      { pin: 13, name: 'SPE', type: 'input'  },
      { pin: 14, name: 'CLK', type: 'input'  },
      { pin: 15, name: 'NC',  type: 'nc'     },
      { pin: 16, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'BIN_DOWN_8BIT', inputs: ['CLK','PEn','P0','P1','P2','P3','P4','P5','P6','P7','CEn','SPE'], outputs: ['TC'] },
    ],
  },

  // ── 74x40104: 4 bit bidirectional universal shift register, TRI (16-pin)
  /* Primary source: 74x40104 datasheet   URL not yet verified.
     https://en.wikipedia.org/wiki/Shift_register */
  '74x40104': {
    name: '74x40104',
    simpleName: '4 bit Bidir Shift Reg',
    description: '4 bit bidirectional universal shift register with three-state outputs (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    datasheet: '',
    tags: ['shift-register', '4 bit', 'bidirectional', 'universal', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x40104 is a 4 bit bidirectional universal shift register with 3-state outputs. Mode select pins S0 and S1 choose between hold, shift right, shift left, and parallel load operations on each rising clock edge. Output enable (active LOW) allows the outputs to be disconnected from a shared bus. On a breadboard this single package replaces the usual combination of a shift register plus direction-select logic wherever 4 bit wide data needs to move in either direction. The simulator currently represents this as a generic stub.',
    pinout: [
      { pin:  1, name: 'SR',   type: 'input'  },
      { pin:  2, name: 'P0',   type: 'input'  },
      { pin:  3, name: 'P1',   type: 'input'  },
      { pin:  4, name: 'P2',   type: 'input'  },
      { pin:  5, name: 'P3',   type: 'input'  },
      { pin:  6, name: 'SL',   type: 'input'  },
      { pin:  7, name: 'S0',   type: 'input'  },
      { pin:  8, name: 'GND',  type: 'power'  },
      { pin:  9, name: 'S1',   type: 'input'  },
      { pin: 10, name: 'CLK',  type: 'input'  },
      { pin: 11, name: 'OEn',  type: 'input'  },
      { pin: 12, name: 'Q3',   type: 'output' },
      { pin: 13, name: 'Q2',   type: 'output' },
      { pin: 14, name: 'Q1',   type: 'output' },
      { pin: 15, name: 'Q0',   type: 'output' },
      { pin: 16, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['SR','SL','P0','P1','P2','P3','S0','S1','CLK','OEn'], outputs: ['Q0','Q1','Q2','Q3'] },
    ],
  },

  // ── 74x40105: 64 bit FIFO memory (16x4), TRI (16-pin) ─────────────────
  /* Primary source: Texas Instruments, 74x40105 datasheet. [Online]. Available: https://www.ti.com/product/CD74HC40105
     https://en.wikipedia.org/wiki/Queue_(abstract_data_type) */
  '74x40105': {
    name: '74x40105',
    simpleName: '64 bit FIFO (16x4)',
    description: '64 bit FIFO memory (16 words × 4 bits) with three-state outputs (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    datasheet: 'https://www.ti.com/product/CD74HC40105',
    tags: ['FIFO', 'memory', '16x4', 'tri-state'],
    sequential: true,
    guideOverview: 'The 74x40105 is a 16-word by 4 bit first-in, first-out memory (CD74HC40105). Unlike a shift register, a FIFO stores words in arrival order and delivers them in that same order, making it ideal for buffering between circuits that run at different rates. A rising edge on WR pushes the current D0 D3 word into the queue (if not full); a rising edge on RD pops the front word to Q0 Q3. Reset (active LOW) clears the queue asynchronously when pulled LOW. The FF and EF status flags are active LOW: FF goes LOW when the 16-word queue is full, EF goes LOW when it is empty. Output enable (active LOW) disables the data outputs when HIGH.',
    guidePinDescriptions: {
      'D0': 'Data input bit 0 for the word being written into the FIFO.',
      'D1': 'Data input bit 1.',
      'D2': 'Data input bit 2.',
      'D3': 'Data input bit 3.',
      'WR': 'Write control. Pulse it to push a new word into the FIFO when space is available.',
      'RD': 'Read control. Pulse it to pop the next stored word from the FIFO.',
      'RSTn': 'Active LOW reset. Pull LOW to clear the FIFO state.',
      'GND': 'Ground reference for the device.',
      'FF': 'Full flag output. It indicates that no more words can be written until data is read out.',
      'EF': 'Empty flag output. It indicates that no stored words are currently available to read.',
      'OEn': 'Active LOW output enable. Pull LOW to drive Q0 through Q3; pull HIGH to disable the outputs.',
      'Q3': 'Data output bit 3 for the next word available at the FIFO output.',
      'Q2': 'Data output bit 2.',
      'Q1': 'Data output bit 1.',
      'Q0': 'Data output bit 0.',
      'VCC': 'Positive supply for the device.',
    },
    guideSections: [
      {
        title: 'How A FIFO Differs From A Shift Register',
        paragraphs: [
          'A FIFO stores complete words and preserves their arrival order. That makes it useful for buffering bursts of data or crossing between circuits that do not read and write at exactly the same rate.',
        ],
      },
      {
        title: 'Operation Summary',
        paragraphs: [
          'Pulse WR HIGH to push D0 D3 into the queue (ignored when full). Pulse RD HIGH to pop the front word to Q0 Q3. Pull RSTn LOW at any time to clear the queue asynchronously. FF goes LOW when all 16 slots are occupied; EF goes LOW when the queue is empty. Pull OEn LOW to drive the data outputs; pull it HIGH to place Q0 Q3 in high-Z.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'D0',  type: 'input'  },
      { pin:  2, name: 'D1',  type: 'input'  },
      { pin:  3, name: 'D2',  type: 'input'  },
      { pin:  4, name: 'D3',  type: 'input'  },
      { pin:  5, name: 'WR',  type: 'input'  },
      { pin:  6, name: 'RD',  type: 'input'  },
      { pin:  7, name: 'RSTn',type: 'input'  },
      { pin:  8, name: 'GND', type: 'power'  },
      { pin:  9, name: 'FF',  type: 'output' },
      { pin: 10, name: 'EF',  type: 'output' },
      { pin: 11, name: 'OEn', type: 'input'  },
      { pin: 12, name: 'Q3',  type: 'output' },
      { pin: 13, name: 'Q2',  type: 'output' },
      { pin: 14, name: 'Q1',  type: 'output' },
      { pin: 15, name: 'Q0',  type: 'output' },
      { pin: 16, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'FIFO_16X4_RST_TRI', inputs: ['D0','D1','D2','D3','WR','RD','RSTn','OEn'], outputs: ['Q0','Q1','Q2','Q3','FF','EF'] },
    ],
  },

  // ── 74116: Dual 4 bit latch with clear (24-pin) ───────────────────────
  /* Primary source: 74116 datasheet   URL not yet verified.
     https://en.wikipedia.org/wiki/Flip-flop_(electronics) */
  '74116': {
    name: '74x116',
    simpleName: 'Dual 4 bit Latch w/ CLR',
    description: 'Dual 4 bit latch with asynchronous clear (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['latch', '4 bit', 'dual', 'clear', 'stub'],
    sequential: true,
    guideOverview: 'The 74116 is a dual 4 bit D-type transparent latch with an asynchronous active LOW clear input for each half. Each group of four data inputs can be latched independently using a separate latch enable and gate pin. Pulling the clear input LOW forces all four outputs in that half to LOW immediately regardless of the latch enable state. On a breadboard the 74116 is useful wherever two independent 4 bit words need to be individually latched and cleared, such as a two-nibble register or a pair of BCD digit latches. The simulator currently represents this as a generic stub.',
    pinout: [
      { pin:  1, name: '1CLRn', type: 'input'  },
      { pin:  2, name: '1D1',   type: 'input'  },
      { pin:  3, name: '1Q1',   type: 'output' },
      { pin:  4, name: '1D2',   type: 'input'  },
      { pin:  5, name: '1Q2',   type: 'output' },
      { pin:  6, name: '1D3',   type: 'input'  },
      { pin:  7, name: '1Q3',   type: 'output' },
      { pin:  8, name: '1D4',   type: 'input'  },
      { pin:  9, name: '1Q4',   type: 'output' },
      { pin: 10, name: '1LE',   type: 'input'  },
      { pin: 11, name: '1GATE', type: 'input'  },
      { pin: 12, name: 'GND',   type: 'power'  },
      { pin: 13, name: '2GATE', type: 'input'  },
      { pin: 14, name: '2LE',   type: 'input'  },
      { pin: 15, name: '2Q4',   type: 'output' },
      { pin: 16, name: '2D4',   type: 'input'  },
      { pin: 17, name: '2Q3',   type: 'output' },
      { pin: 18, name: '2D3',   type: 'input'  },
      { pin: 19, name: '2Q2',   type: 'output' },
      { pin: 20, name: '2D2',   type: 'input'  },
      { pin: 21, name: '2Q1',   type: 'output' },
      { pin: 22, name: '2D1',   type: 'input'  },
      { pin: 23, name: '2CLRn', type: 'input'  },
      { pin: 24, name: 'VCC',   type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['1CLRn','1LE','1GATE','1D1','1D2','1D3','1D4','2CLRn','2LE','2GATE','2D1','2D2','2D3','2D4'], outputs: ['1Q1','1Q2','1Q3','1Q4','2Q1','2Q2','2Q3','2Q4'] },
    ],
  },

  // ── 74119: Hex set/reset latch (24-pin) ────────────────────────────────
  /* Primary source: 74119 datasheet   URL not yet verified.
     https://en.wikipedia.org/wiki/Flip-flop_(electronics) */
  '74119': {
    name: '74x119',
    simpleName: 'Hex SR Latch',
    description: 'Hex set/reset latch (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['latch', 'set-reset', 'hex', 'stub'],
    sequential: true,
    guideOverview: 'The 74119 is a hex set/reset latch, providing six independent SR latch cells in a single 24-pin package. Each cell has a separate SET (S) input and a RESET (R) input. Driving S HIGH sets the corresponding Q output HIGH, while driving R HIGH resets it to LOW. On a breadboard it is a convenient building block for six independent status flags or handshake bits that need to be individually set and cleared by different parts of the circuit. The simulator currently represents this as a generic stub.',
    pinout: [
      { pin:  1, name: 'S1',  type: 'input'  },
      { pin:  2, name: 'R1',  type: 'input'  },
      { pin:  3, name: 'Q1',  type: 'output' },
      { pin:  4, name: 'S2',  type: 'input'  },
      { pin:  5, name: 'R2',  type: 'input'  },
      { pin:  6, name: 'Q2',  type: 'output' },
      { pin:  7, name: 'S3',  type: 'input'  },
      { pin:  8, name: 'R3',  type: 'input'  },
      { pin:  9, name: 'Q3',  type: 'output' },
      { pin: 10, name: 'S4',  type: 'input'  },
      { pin: 11, name: 'R4',  type: 'input'  },
      { pin: 12, name: 'GND', type: 'power'  },
      { pin: 13, name: 'Q4',  type: 'output' },
      { pin: 14, name: 'S5',  type: 'input'  },
      { pin: 15, name: 'R5',  type: 'input'  },
      { pin: 16, name: 'Q5',  type: 'output' },
      { pin: 17, name: 'S6',  type: 'input'  },
      { pin: 18, name: 'R6',  type: 'input'  },
      { pin: 19, name: 'Q6',  type: 'output' },
      { pin: 20, name: 'NC1', type: 'nc'     },
      { pin: 21, name: 'NC2', type: 'nc'     },
      { pin: 22, name: 'NC3', type: 'nc'     },
      { pin: 23, name: 'NC4', type: 'nc'     },
      { pin: 24, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['S1','R1','S2','R2','S3','R3','S4','R4','S5','R5','S6','R6'], outputs: ['Q1','Q2','Q3','Q4','Q5','Q6'] },
    ],
  },

  // ── 74120: Dual pulse synchronizer/drivers (16-pin) ────────────────────
  /* Primary source: 74120 datasheet   URL not yet verified. */
  '74120': {
    name: '74x120',
    simpleName: 'Dual Pulse Sync/Driver',
    description: 'Dual pulse synchronizer/drivers with 15 kΩ pull up inputs (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    datasheet: '',
    tags: ['synchronizer', 'driver', 'pulse', 'dual', 'stub'],
    sequential: true,
    guideOverview: 'The 74120 is a dual pulse synchronizer and driver with built in 15 kΩ pull up resistors on the inputs. Each half accepts two inputs and provides complementary Q and Qn outputs. On a breadboard the 74120 is useful for cleaning up asynchronous pulse signals before passing them into synchronous logic, because the internal pull up and synchronizer circuitry stabilizes slow or noisy edges. The simulator currently represents this as a generic stub.',
    pinout: [
      { pin:  1, name: '1IN1', type: 'input'  },
      { pin:  2, name: '1IN2', type: 'input'  },
      { pin:  3, name: '1Q',   type: 'output' },
      { pin:  4, name: '1Qn',  type: 'output' },
      { pin:  5, name: '1CLR', type: 'input'  },
      { pin:  6, name: '2CLR', type: 'input'  },
      { pin:  7, name: '2Q',   type: 'output' },
      { pin:  8, name: 'GND',  type: 'power'  },
      { pin:  9, name: '2Qn',  type: 'output' },
      { pin: 10, name: '2IN1', type: 'input'  },
      { pin: 11, name: '2IN2', type: 'input'  },
      { pin: 12, name: 'NC1',  type: 'nc'     },
      { pin: 13, name: 'NC2',  type: 'nc'     },
      { pin: 14, name: 'NC3',  type: 'nc'     },
      { pin: 15, name: 'NC4',  type: 'nc'     },
      { pin: 16, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['1IN1','1IN2','1CLR','2IN1','2IN2','2CLR'], outputs: ['1Q','1Qn','2Q','2Qn'] },
    ],
  },
};