// chips72.js Block 72: CMOS 4000 series logic ICs (coverage expansion, Batch 1)
// Pure combinational gates. Pinouts verified against primary datasheets
// (TI/Harris SCHS-series reprints, Intersil/Renesas CD4000BMS, onsemi MC145xx)
// — read from the actual PDF pages, never copied from sibling parts.
// See CMOS-4000-Coverage-Plan.md for the full roadmap.
// Chips: CD4000, CD4002, CD4009, CD4010, CD4041, CD4068, CD4072, CD4078,
//        CD4572, CD4584
export const CHIPS_BLOCK_72 = {

  // ── CD4002: Dual 4 input NOR (14-pin) ──────────────────────────────────
  /* Primary source: Texas Instruments, CD4001B/CD4002B datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/cd4002b.pdf */
  'CD4002': {
    name: 'CD4002',
    simpleName: 'Dual 4 Input NOR',
    description: 'Dual 4 input NOR gate CMOS 4000 series. (14-pin)',
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/cd4002b.pdf',
    tags: ['cmos', '4000 series', 'logic gate', 'NOR', 'dual', '4 input'],
    guideOverview: 'The CD4002 contains two independent 4 input NOR gates. Output is HIGH only when all four inputs are simultaneously LOW; any single HIGH input forces the output LOW. Pins 6 and 8 are no connect. It is the 4 input NOR counterpart to the CD4012 NAND and shares the same pinout. Supply voltage 3-15 V (some versions to 18 V).',
    guidePinDescriptions: {
      '1Y':  'Output of gate 1. HIGH only when 1A, 1B, 1C, and 1D are all LOW.',
      '1A':  'Input A of gate 1.',
      '1B':  'Input B of gate 1.',
      '1C':  'Input C of gate 1.',
      '1D':  'Input D of gate 1.',
      'NC':  'No internal connection. Leave unconnected.',
      'GND': 'Ground reference (VSS). Connect to 0 V.',
      'NC2': 'No internal connection. Leave unconnected.',
      '2D':  'Input D of gate 2.',
      '2C':  'Input C of gate 2.',
      '2B':  'Input B of gate 2.',
      '2A':  'Input A of gate 2.',
      '2Y':  'Output of gate 2. HIGH only when 2A, 2B, 2C, and 2D are all LOW.',
      'VDD': 'Positive supply. Accepts 3 V to 15 V.',
    },
    pinout: [
      { pin:  1, name: '1Y',  type: 'output', description: 'Gate 1 NOR output: HIGH only when all inputs LOW' },
      { pin:  2, name: '1A',  type: 'input',  description: 'Gate 1 input A' },
      { pin:  3, name: '1B',  type: 'input',  description: 'Gate 1 input B' },
      { pin:  4, name: '1C',  type: 'input',  description: 'Gate 1 input C' },
      { pin:  5, name: '1D',  type: 'input',  description: 'Gate 1 input D' },
      { pin:  6, name: 'NC',  type: 'nc',     description: 'No connection' },
      { pin:  7, name: 'GND', type: 'power',  description: 'Ground (0 V)' },
      { pin:  8, name: 'NC2', type: 'nc',     description: 'No connection' },
      { pin:  9, name: '2D',  type: 'input',  description: 'Gate 2 input D' },
      { pin: 10, name: '2C',  type: 'input',  description: 'Gate 2 input C' },
      { pin: 11, name: '2B',  type: 'input',  description: 'Gate 2 input B' },
      { pin: 12, name: '2A',  type: 'input',  description: 'Gate 2 input A' },
      { pin: 13, name: '2Y',  type: 'output', description: 'Gate 2 NOR output: HIGH only when all inputs LOW' },
      { pin: 14, name: 'VDD', type: 'power',  description: 'Positive supply (3-15 V)' },
    ],
    gates: [
      { type: 'NOR', inputs: ['1A','1B','1C','1D'], output: '1Y' },
      { type: 'NOR', inputs: ['2A','2B','2C','2D'], output: '2Y' },
    ],
    guideSections: [
      {
        title: 'Logic Function',
        paragraphs: [
          'NOR logic: the output is HIGH only when every input is simultaneously LOW. A single HIGH input is enough to pull the output LOW.',
          'The 4 input version lets you OR four conditions and invert the result in one gate. Tie inputs together to make a 3-, 2-, or 1-input NOR (an unused input must be tied to a known level, never left floating).',
        ],
        formulas: [
          'Y = NOT(A + B + C + D)',
        ],
      },
      {
        title: 'Typical Uses',
        list: [
          'All inputs LOW detector: output goes HIGH only when every monitored line is at 0.',
          'Wide NOR for address/state decoding where any active line should disable the output.',
          'Pin compatible with the CD4012 (NAND) and CD4082 layout family for the inputs, but verify outputs (NOR/NAND outputs sit on pins 1 and 13).',
        ],
      },
    ],
  },

  // ── CD4009: Hex inverting buffer/converter (16-pin, dual supply) ────────
  /* Primary source: Texas Instruments, CD4009UB/CD4010B datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/cd4009ub.pdf */
  'CD4009': {
    name: 'CD4009',
    simpleName: 'Hex Inverting Buffer (Level Shifter)',
    description: 'Hex inverting buffer, dual supply, CMOS-to-TTL shifter (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/cd4009ub.pdf',
    tags: ['cmos', '4000 series', 'logic gate', 'NOT', 'inverter', 'buffer', 'level shifter', 'hex inverter'],
    guideOverview: 'The CD4009 is a hex inverting buffer/converter with six independent NOT gates. It has TWO supply pins: VDD (pin 16) sets the CMOS input/logic level, while VCC (pin 1) sets the output high level — this lets the chip translate higher voltage CMOS logic down to a lower 5 V TTL level (or vice versa). It can sink more current than ordinary CMOS gates, driving one or two TTL/DTL loads. The newer CD4049 is the preferred replacement except where the separate VCC level-shift pin is needed.',
    guidePinDescriptions: {
      VCC: 'Output-stage supply. Sets the output HIGH voltage (e.g. tie to 5 V to produce TTL-level outputs). Usually ≤ VDD.',
      A:   'Input of inverter 1.',
      B:   'Input of inverter 2.',
      C:   'Input of inverter 3.',
      D:   'Input of inverter 4.',
      E:   'Input of inverter 5.',
      F:   'Input of inverter 6.',
      QA:  'Output of inverter 1. LOW when A is HIGH.',
      QB:  'Output of inverter 2.',
      QC:  'Output of inverter 3.',
      QD:  'Output of inverter 4.',
      QE:  'Output of inverter 5.',
      QF:  'Output of inverter 6.',
      NC:  'No internal connection. Leave unconnected.',
      GND: 'Ground reference (VSS). Connect to 0 V.',
      VDD: 'Input/logic supply. Sets the CMOS input switching level (3 V to 15 V).',
    },
    pinout: [
      { pin:  1, name: 'VCC', type: 'power',  description: 'Output-stage supply (sets output HIGH level, e.g. 5 V for TTL)' },
      { pin:  2, name: 'QA',  type: 'output', description: 'Inverter 1 output (inverted)' },
      { pin:  3, name: 'A',   type: 'input',  description: 'Inverter 1 input' },
      { pin:  4, name: 'QB',  type: 'output', description: 'Inverter 2 output' },
      { pin:  5, name: 'B',   type: 'input',  description: 'Inverter 2 input' },
      { pin:  6, name: 'C',   type: 'input',  description: 'Inverter 3 input' },
      { pin:  7, name: 'QC',  type: 'output', description: 'Inverter 3 output' },
      { pin:  8, name: 'GND', type: 'power',  description: 'Ground (VSS, 0 V)' },
      { pin:  9, name: 'D',   type: 'input',  description: 'Inverter 4 input' },
      { pin: 10, name: 'QD',  type: 'output', description: 'Inverter 4 output' },
      { pin: 11, name: 'E',   type: 'input',  description: 'Inverter 5 input' },
      { pin: 12, name: 'QE',  type: 'output', description: 'Inverter 5 output' },
      { pin: 13, name: 'NC',  type: 'nc',     description: 'No connection' },
      { pin: 14, name: 'F',   type: 'input',  description: 'Inverter 6 input' },
      { pin: 15, name: 'QF',  type: 'output', description: 'Inverter 6 output' },
      { pin: 16, name: 'VDD', type: 'power',  description: 'Input/logic supply (3-15 V)' },
    ],
    gates: [
      { type: 'NOT', inputs: ['A'], output: 'QA' },
      { type: 'NOT', inputs: ['B'], output: 'QB' },
      { type: 'NOT', inputs: ['C'], output: 'QC' },
      { type: 'NOT', inputs: ['D'], output: 'QD' },
      { type: 'NOT', inputs: ['E'], output: 'QE' },
      { type: 'NOT', inputs: ['F'], output: 'QF' },
    ],
    guideSections: [
      {
        title: 'Inverter Plus Level Translation',
        paragraphs: [
          'Each of the six gates simply inverts its input. The distinctive feature is the separate VCC pin (pin 1): the output stage swings between VSS and VCC, while the input threshold is referenced to VDD. By running VDD at a higher CMOS rail and VCC at 5 V, the CD4009 converts high voltage CMOS logic into clean TTL level signals.',
          'It also has a stronger output than a normal CMOS gate, so it can directly drive one or two TTL/DTL inputs.',
        ],
        list: [
          'CMOS to TTL converter: VDD at the CMOS rail, VCC at 5 V.',
          'High-to-low logic level shifter.',
          'Higher current inverting buffer / line driver.',
        ],
        note: '74Sim models the six gates as digital inverters. The analog level-translation behavior of the VCC pin is informational; logic is evaluated from VDD/VSS.',
      },
    ],
  },

  // ── CD4010: Hex non-inverting buffer/converter (16-pin, dual supply) ────
  /* Primary source: Texas Instruments, CD4009UB/CD4010B datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/cd4010b.pdf */
  'CD4010': {
    name: 'CD4010',
    simpleName: 'Hex Buffer (Level Shifter)',
    description: 'Hex non-inverting buffer, dual supply, CMOS-to-TTL shifter (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/cd4010b.pdf',
    tags: ['cmos', '4000 series', 'logic gate', 'BUFFER', 'buffer', 'level shifter', 'hex buffer'],
    guideOverview: 'The CD4010 is a hex non-inverting buffer/converter with six independent buffers. Like the CD4009 it has two supply pins: VDD (pin 16) sets the input/logic level and VCC (pin 1) sets the output HIGH level, allowing high-to-low logic level translation. Each output simply follows its input. It can drive one or two TTL/DTL loads. The newer CD4050 is the preferred replacement except where the separate VCC level-shift pin is needed.',
    guidePinDescriptions: {
      VCC: 'Output-stage supply. Sets the output HIGH voltage (e.g. tie to 5 V to produce TTL-level outputs). Usually ≤ VDD.',
      A:   'Input of buffer 1.',
      B:   'Input of buffer 2.',
      C:   'Input of buffer 3.',
      D:   'Input of buffer 4.',
      E:   'Input of buffer 5.',
      F:   'Input of buffer 6.',
      QA:  'Output of buffer 1. Follows A.',
      QB:  'Output of buffer 2.',
      QC:  'Output of buffer 3.',
      QD:  'Output of buffer 4.',
      QE:  'Output of buffer 5.',
      QF:  'Output of buffer 6.',
      NC:  'No internal connection. Leave unconnected.',
      GND: 'Ground reference (VSS). Connect to 0 V.',
      VDD: 'Input/logic supply. Sets the CMOS input switching level (3 V to 15 V).',
    },
    pinout: [
      { pin:  1, name: 'VCC', type: 'power',  description: 'Output-stage supply (sets output HIGH level, e.g. 5 V for TTL)' },
      { pin:  2, name: 'QA',  type: 'output', description: 'Buffer 1 output (follows A)' },
      { pin:  3, name: 'A',   type: 'input',  description: 'Buffer 1 input' },
      { pin:  4, name: 'QB',  type: 'output', description: 'Buffer 2 output' },
      { pin:  5, name: 'B',   type: 'input',  description: 'Buffer 2 input' },
      { pin:  6, name: 'C',   type: 'input',  description: 'Buffer 3 input' },
      { pin:  7, name: 'QC',  type: 'output', description: 'Buffer 3 output' },
      { pin:  8, name: 'GND', type: 'power',  description: 'Ground (VSS, 0 V)' },
      { pin:  9, name: 'D',   type: 'input',  description: 'Buffer 4 input' },
      { pin: 10, name: 'QD',  type: 'output', description: 'Buffer 4 output' },
      { pin: 11, name: 'E',   type: 'input',  description: 'Buffer 5 input' },
      { pin: 12, name: 'QE',  type: 'output', description: 'Buffer 5 output' },
      { pin: 13, name: 'NC',  type: 'nc',     description: 'No connection' },
      { pin: 14, name: 'F',   type: 'input',  description: 'Buffer 6 input' },
      { pin: 15, name: 'QF',  type: 'output', description: 'Buffer 6 output' },
      { pin: 16, name: 'VDD', type: 'power',  description: 'Input/logic supply (3-15 V)' },
    ],
    gates: [
      { type: 'BUFFER', inputs: ['A'], output: 'QA' },
      { type: 'BUFFER', inputs: ['B'], output: 'QB' },
      { type: 'BUFFER', inputs: ['C'], output: 'QC' },
      { type: 'BUFFER', inputs: ['D'], output: 'QD' },
      { type: 'BUFFER', inputs: ['E'], output: 'QE' },
      { type: 'BUFFER', inputs: ['F'], output: 'QF' },
    ],
    guideSections: [
      {
        title: 'Buffer Plus Level Translation',
        paragraphs: [
          'Each of the six gates passes its input straight through (no inversion). The separate VCC pin lets the output stage swing to a different rail than the input threshold, so the CD4010 converts higher voltage CMOS logic down to a clean 5 V TTL level while preserving polarity.',
          'Its output is stronger than an ordinary CMOS gate, able to drive one or two TTL/DTL inputs directly.',
        ],
        list: [
          'CMOS to TTL converter (non-inverting): VDD at the CMOS rail, VCC at 5 V.',
          'High-to-low logic level shifter without polarity flip.',
          'Higher current non-inverting buffer / line driver.',
        ],
        note: '74Sim models the six gates as digital buffers. The analog level-translation behavior of the VCC pin is informational; logic is evaluated from VDD/VSS.',
      },
    ],
  },

  // ── CD4041: Quad true/complement buffer (14-pin) ───────────────────────
  /* Primary source: Texas Instruments, CD4041UB datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/cd4041ub.pdf */
  'CD4041': {
    name: 'CD4041',
    simpleName: 'Quad True/Complement Buffer',
    description: 'Quad true/complement buffer, CMOS 4000 series (14-pin)',
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/cd4041ub.pdf',
    tags: ['cmos', '4000 series', 'logic gate', 'BUFFER', 'NOT', 'buffer', 'inverter', 'quad'],
    guideOverview: 'The CD4041 contains four buffers, each providing BOTH a true (non-inverted) output and a complement (inverted) output from a single input. The true and complement delays are matched so both polarities arrive together. With roughly four times standard "B" drive it works well as a line driver, resistor-ladder (DAC) driver, or CMOS-to-TTL converter where both phases of a signal are needed.',
    guidePinDescriptions: {
      QA:  'Buffer A true output (follows A).',
      QAN: 'Buffer A complement output (inverted A).',
      A:   'Buffer A input.',
      QB:  'Buffer B true output (follows B).',
      QBN: 'Buffer B complement output (inverted B).',
      B:   'Buffer B input.',
      GND: 'Ground reference (VSS). Connect to 0 V.',
      QCN: 'Buffer C complement output (inverted C).',
      QC:  'Buffer C true output (follows C).',
      C:   'Buffer C input.',
      QD:  'Buffer D true output (follows D).',
      QDN: 'Buffer D complement output (inverted D).',
      D:   'Buffer D input.',
      VDD: 'Positive supply. Accepts 3 V to 18 V.',
    },
    pinout: [
      { pin:  1, name: 'QA',  type: 'output', description: 'Buffer A true output (= A)' },
      { pin:  2, name: 'QAN', type: 'output', description: 'Buffer A complement output (= NOT A)' },
      { pin:  3, name: 'A',   type: 'input',  description: 'Buffer A input' },
      { pin:  4, name: 'QB',  type: 'output', description: 'Buffer B true output (= B)' },
      { pin:  5, name: 'QBN', type: 'output', description: 'Buffer B complement output (= NOT B)' },
      { pin:  6, name: 'B',   type: 'input',  description: 'Buffer B input' },
      { pin:  7, name: 'GND', type: 'power',  description: 'Ground (0 V)' },
      { pin:  8, name: 'QCN', type: 'output', description: 'Buffer C complement output (= NOT C)' },
      { pin:  9, name: 'QC',  type: 'output', description: 'Buffer C true output (= C)' },
      { pin: 10, name: 'C',   type: 'input',  description: 'Buffer C input' },
      { pin: 11, name: 'QD',  type: 'output', description: 'Buffer D true output (= D)' },
      { pin: 12, name: 'QDN', type: 'output', description: 'Buffer D complement output (= NOT D)' },
      { pin: 13, name: 'D',   type: 'input',  description: 'Buffer D input' },
      { pin: 14, name: 'VDD', type: 'power',  description: 'Positive supply (3-18 V)' },
    ],
    gates: [
      { type: 'BUFFER', inputs: ['A'], output: 'QA' },
      { type: 'NOT',    inputs: ['A'], output: 'QAN' },
      { type: 'BUFFER', inputs: ['B'], output: 'QB' },
      { type: 'NOT',    inputs: ['B'], output: 'QBN' },
      { type: 'BUFFER', inputs: ['C'], output: 'QC' },
      { type: 'NOT',    inputs: ['C'], output: 'QCN' },
      { type: 'BUFFER', inputs: ['D'], output: 'QD' },
      { type: 'NOT',    inputs: ['D'], output: 'QDN' },
    ],
    guideSections: [
      {
        title: 'True and Complement Outputs',
        paragraphs: [
          'Each buffer takes one input and produces two outputs at once: a true output that copies the input and a complement output that inverts it. Because both stages are designed with equal delay, the two phases stay aligned in time — useful when a circuit needs a signal and its inverse simultaneously.',
          'The strong output drive (≈ 4× standard "B" series) makes the part suitable as a line driver or for driving resistor-ladder DAC networks.',
        ],
        list: [
          'Generate a signal and its inverse for differential or push-pull drive.',
          'Resistor-ladder (R-2R) DAC driver needing matched true/complement levels.',
          'CMOS-to-TTL converter / line driver where both phases are required.',
        ],
      },
    ],
  },

  // ── CD4068: 8 input NAND/AND gate (14-pin) ─────────────────────────────
  /* Primary source: Texas Instruments, CD4068B datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/cd4068b.pdf */
  'CD4068': {
    name: 'CD4068',
    simpleName: '8 Input NAND/AND',
    description: 'Single 8-input gate, both NAND and AND outputs, CMOS (14-pin)',
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/cd4068b.pdf',
    tags: ['cmos', '4000 series', 'logic gate', 'NAND', 'AND', '8 input'],
    guideOverview: 'The CD4068 is a single 8 input gate that provides both functions at once: the AND output (K, pin 1) is HIGH only when all eight inputs are HIGH, and the NAND output (J, pin 13) is its complement. Pins 6 and 8 are no connect. It is handy for detecting an exact all-ones condition across eight lines, or as an 8-bit "all true" flag. Supply voltage 3-15 V (some versions to 18 V).',
    guidePinDescriptions: {
      K:   'AND output. HIGH only when all eight inputs A-H are HIGH.',
      A:   'Input A.',
      B:   'Input B.',
      C:   'Input C.',
      D:   'Input D.',
      NC:  'No internal connection. Leave unconnected.',
      GND: 'Ground reference (VSS). Connect to 0 V.',
      NC2: 'No internal connection. Leave unconnected.',
      E:   'Input E.',
      F:   'Input F.',
      G:   'Input G.',
      H:   'Input H.',
      J:   'NAND output. LOW only when all eight inputs A-H are HIGH (complement of K).',
      VDD: 'Positive supply. Accepts 3 V to 15 V.',
    },
    pinout: [
      { pin:  1, name: 'K',   type: 'output', description: 'AND output: HIGH only when all 8 inputs HIGH' },
      { pin:  2, name: 'A',   type: 'input',  description: 'Input A' },
      { pin:  3, name: 'B',   type: 'input',  description: 'Input B' },
      { pin:  4, name: 'C',   type: 'input',  description: 'Input C' },
      { pin:  5, name: 'D',   type: 'input',  description: 'Input D' },
      { pin:  6, name: 'NC',  type: 'nc',     description: 'No connection' },
      { pin:  7, name: 'GND', type: 'power',  description: 'Ground (0 V)' },
      { pin:  8, name: 'NC2', type: 'nc',     description: 'No connection' },
      { pin:  9, name: 'E',   type: 'input',  description: 'Input E' },
      { pin: 10, name: 'F',   type: 'input',  description: 'Input F' },
      { pin: 11, name: 'G',   type: 'input',  description: 'Input G' },
      { pin: 12, name: 'H',   type: 'input',  description: 'Input H' },
      { pin: 13, name: 'J',   type: 'output', description: 'NAND output: LOW only when all 8 inputs HIGH' },
      { pin: 14, name: 'VDD', type: 'power',  description: 'Positive supply (3-15 V)' },
    ],
    gates: [
      { type: 'AND',  inputs: ['A','B','C','D','E','F','G','H'], output: 'K' },
      { type: 'NAND', inputs: ['A','B','C','D','E','F','G','H'], output: 'J' },
    ],
    guideSections: [
      {
        title: '8-Input Coincidence Gate',
        paragraphs: [
          'A single gate combines all eight inputs. The AND output (K) goes HIGH only when every input is HIGH; the NAND output (J) is the inverse. Having both polarities on one chip saves an external inverter.',
          'Any unused input must be tied HIGH (so it does not block the AND) — never left floating on a CMOS part.',
        ],
        formulas: [
          'K = A · B · C · D · E · F · G · H',
          'J = NOT(A · B · C · D · E · F · G · H)',
        ],
        list: [
          'Detect an exact 8-bit all-ones pattern (e.g. address/bus decode).',
          'Combine eight enable conditions into a single "all ready" flag.',
        ],
      },
    ],
  },

  // ── CD4072: Dual 4 input OR (14-pin) ───────────────────────────────────
  /* Primary source: Texas Instruments, CD4071B/CD4072B/CD4075B datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/cd4072b.pdf */
  'CD4072': {
    name: 'CD4072',
    simpleName: 'Dual 4 Input OR',
    description: 'Dual 4 input OR gate CMOS 4000 series. (14-pin)',
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/cd4072b.pdf',
    tags: ['cmos', '4000 series', 'logic gate', 'OR', 'dual', '4 input'],
    guideOverview: 'The CD4072 contains two independent 4 input OR gates. Output is HIGH when at least one of the four inputs is HIGH, and LOW only when all four are LOW. Note the pinout: the two outputs sit on pins 8 and 9, inputs on pins 3-6 and 10-13, and pins 1 and 2 are no connect — this differs from the NAND/NOR (4012/4002) family. It is the 4 input OR counterpart to the CD4082 AND. Supply voltage 3-15 V (some versions to 18 V).',
    guidePinDescriptions: {
      NC:  'No internal connection. Leave unconnected.',
      NC2: 'No internal connection. Leave unconnected.',
      '1A':  'Input A of gate 1.',
      '1B':  'Input B of gate 1.',
      '1C':  'Input C of gate 1.',
      '1D':  'Input D of gate 1.',
      GND: 'Ground reference (VSS). Connect to 0 V.',
      '1Y':  'Output of gate 1. HIGH when any of 1A-1D is HIGH.',
      '2Y':  'Output of gate 2. HIGH when any of 2A-2D is HIGH.',
      '2A':  'Input A of gate 2.',
      '2B':  'Input B of gate 2.',
      '2C':  'Input C of gate 2.',
      '2D':  'Input D of gate 2.',
      VDD: 'Positive supply. Accepts 3 V to 15 V.',
    },
    pinout: [
      { pin:  1, name: 'NC',  type: 'nc',     description: 'No connection' },
      { pin:  2, name: 'NC2', type: 'nc',     description: 'No connection' },
      { pin:  3, name: '1A',  type: 'input',  description: 'Gate 1 input A' },
      { pin:  4, name: '1B',  type: 'input',  description: 'Gate 1 input B' },
      { pin:  5, name: '1C',  type: 'input',  description: 'Gate 1 input C' },
      { pin:  6, name: '1D',  type: 'input',  description: 'Gate 1 input D' },
      { pin:  7, name: 'GND', type: 'power',  description: 'Ground (0 V)' },
      { pin:  8, name: '1Y',  type: 'output', description: 'Gate 1 OR output: HIGH when any input HIGH' },
      { pin:  9, name: '2Y',  type: 'output', description: 'Gate 2 OR output: HIGH when any input HIGH' },
      { pin: 10, name: '2A',  type: 'input',  description: 'Gate 2 input A' },
      { pin: 11, name: '2B',  type: 'input',  description: 'Gate 2 input B' },
      { pin: 12, name: '2C',  type: 'input',  description: 'Gate 2 input C' },
      { pin: 13, name: '2D',  type: 'input',  description: 'Gate 2 input D' },
      { pin: 14, name: 'VDD', type: 'power',  description: 'Positive supply (3-15 V)' },
    ],
    gates: [
      { type: 'OR', inputs: ['1A','1B','1C','1D'], output: '1Y' },
      { type: 'OR', inputs: ['2A','2B','2C','2D'], output: '2Y' },
    ],
    guideSections: [
      {
        title: 'Logic Function',
        paragraphs: [
          'OR logic: the output is HIGH whenever any input is HIGH, and only LOW when all four inputs are LOW. The 4 input gate combines four signals so any one of them can assert the output.',
          'Watch the pin map: unlike the dual-4-input NAND/NOR parts, the CD4072 (and CD4082 AND) place their outputs on pins 8 and 9 with the inputs on 3-6 and 10-13.',
        ],
        formulas: [
          'Y = A + B + C + D',
        ],
        list: [
          'Combine four trigger/alarm lines so any active one raises the output.',
          'Wide OR for run/enable logic where multiple sources can request an action.',
        ],
      },
    ],
  },

  // ── CD4078: 8 input NOR/OR gate (14-pin) ───────────────────────────────
  /* Primary source: Texas Instruments, CD4078B datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/cd4078b.pdf */
  'CD4078': {
    name: 'CD4078',
    simpleName: '8 Input NOR/OR',
    description: 'Single 8 input gate with both NOR and OR outputs CMOS 4000 series. (14-pin)',
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/cd4078b.pdf',
    tags: ['cmos', '4000 series', 'logic gate', 'NOR', 'OR', '8 input'],
    guideOverview: 'The CD4078 is a single 8 input gate providing both functions: the OR output (K, pin 1) is HIGH when any of the eight inputs is HIGH, and the NOR output (J, pin 13) is its complement (HIGH only when all eight inputs are LOW). Pins 6 and 8 are no connect. It shares the CD4068 pinout. Useful as an 8-line "any active" detector. Supply voltage 3-15 V (some versions to 18 V).',
    guidePinDescriptions: {
      K:   'OR output. HIGH when any of the eight inputs A-H is HIGH.',
      A:   'Input A.',
      B:   'Input B.',
      C:   'Input C.',
      D:   'Input D.',
      NC:  'No internal connection. Leave unconnected.',
      GND: 'Ground reference (VSS). Connect to 0 V.',
      NC2: 'No internal connection. Leave unconnected.',
      E:   'Input E.',
      F:   'Input F.',
      G:   'Input G.',
      H:   'Input H.',
      J:   'NOR output. HIGH only when all eight inputs A-H are LOW (complement of K).',
      VDD: 'Positive supply. Accepts 3 V to 15 V.',
    },
    pinout: [
      { pin:  1, name: 'K',   type: 'output', description: 'OR output: HIGH when any of the 8 inputs HIGH' },
      { pin:  2, name: 'A',   type: 'input',  description: 'Input A' },
      { pin:  3, name: 'B',   type: 'input',  description: 'Input B' },
      { pin:  4, name: 'C',   type: 'input',  description: 'Input C' },
      { pin:  5, name: 'D',   type: 'input',  description: 'Input D' },
      { pin:  6, name: 'NC',  type: 'nc',     description: 'No connection' },
      { pin:  7, name: 'GND', type: 'power',  description: 'Ground (0 V)' },
      { pin:  8, name: 'NC2', type: 'nc',     description: 'No connection' },
      { pin:  9, name: 'E',   type: 'input',  description: 'Input E' },
      { pin: 10, name: 'F',   type: 'input',  description: 'Input F' },
      { pin: 11, name: 'G',   type: 'input',  description: 'Input G' },
      { pin: 12, name: 'H',   type: 'input',  description: 'Input H' },
      { pin: 13, name: 'J',   type: 'output', description: 'NOR output: HIGH only when all 8 inputs LOW' },
      { pin: 14, name: 'VDD', type: 'power',  description: 'Positive supply (3-15 V)' },
    ],
    gates: [
      { type: 'OR',  inputs: ['A','B','C','D','E','F','G','H'], output: 'K' },
      { type: 'NOR', inputs: ['A','B','C','D','E','F','G','H'], output: 'J' },
    ],
    guideSections: [
      {
        title: '8-Input Any/None Detector',
        paragraphs: [
          'A single gate spans all eight inputs. The OR output (K) is HIGH if any input is HIGH; the NOR output (J) is HIGH only when every input is LOW. Both polarities are available without an external inverter.',
          'Any unused input must be tied LOW (so it does not assert the OR) — never left floating on a CMOS part.',
        ],
        formulas: [
          'K = A + B + C + D + E + F + G + H',
          'J = NOT(A + B + C + D + E + F + G + H)',
        ],
        list: [
          'All-quiet detector: the NOR output (J) flags when all eight lines are idle.',
          'Any-active flag: the OR output (K) flags when any of eight events occurs.',
        ],
      },
    ],
  },

  // ── CD4584: Hex Schmitt trigger inverter (14-pin) ──────────────────────
  /* Primary source: ON Semiconductor / Motorola, MC14584B (CD4584) datasheet. [Online]. Available: https://www.onsemi.com/pdf/datasheet/mc14584b-d.pdf */
  'CD4584': {
    name: 'CD4584',
    simpleName: 'Hex Schmitt Trigger Inverter',
    description: 'Six Schmitt-trigger inverters, CMOS 4000 series (14-pin)',
    schmittInputs: true,
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.onsemi.com/pdf/datasheet/mc14584b-d.pdf',
    tags: ['cmos', '4000 series', 'logic gate', 'NOT', 'inverter', 'Schmitt trigger', 'hex inverter'],
    guideOverview: 'The CD4584 (also sold as MC14584/HEF4584) contains six independent Schmitt trigger inverters. Each gate inverts its input, and the Schmitt trigger input gives hysteresis: the threshold for a rising edge is higher than for a falling edge, preventing output chatter on slow or noisy signals. It is functionally and pin-for-pin identical to the CD40106 and equivalent to the 74x14. A single gate with an RC feedback network makes a simple relaxation oscillator. Supply voltage 3-15 V.',
    guidePinDescriptions: {
      A:   'Input of inverter 1.',
      YA:  'Output of inverter 1 (inverted, Schmitt trigger input). HIGH when A is LOW.',
      B:   'Input of inverter 2.',
      YB:  'Output of inverter 2.',
      C:   'Input of inverter 3.',
      YC:  'Output of inverter 3.',
      GND: 'Ground reference (VSS). Connect to 0 V.',
      YD:  'Output of inverter 4.',
      D:   'Input of inverter 4.',
      YE:  'Output of inverter 5.',
      E:   'Input of inverter 5.',
      YF:  'Output of inverter 6.',
      F:   'Input of inverter 6.',
      VDD: 'Positive supply. Accepts 3 V to 15 V.',
    },
    pinout: [
      { pin:  1, name: 'A',   type: 'input',  description: 'Inverter 1 input' },
      { pin:  2, name: 'YA',  type: 'output', description: 'Inverter 1 output (inverted, Schmitt trigger)' },
      { pin:  3, name: 'B',   type: 'input',  description: 'Inverter 2 input' },
      { pin:  4, name: 'YB',  type: 'output', description: 'Inverter 2 output' },
      { pin:  5, name: 'C',   type: 'input',  description: 'Inverter 3 input' },
      { pin:  6, name: 'YC',  type: 'output', description: 'Inverter 3 output' },
      { pin:  7, name: 'GND', type: 'power',  description: 'Ground (0 V)' },
      { pin:  8, name: 'YD',  type: 'output', description: 'Inverter 4 output' },
      { pin:  9, name: 'D',   type: 'input',  description: 'Inverter 4 input' },
      { pin: 10, name: 'YE',  type: 'output', description: 'Inverter 5 output' },
      { pin: 11, name: 'E',   type: 'input',  description: 'Inverter 5 input' },
      { pin: 12, name: 'YF',  type: 'output', description: 'Inverter 6 output' },
      { pin: 13, name: 'F',   type: 'input',  description: 'Inverter 6 input' },
      { pin: 14, name: 'VDD', type: 'power',  description: 'Positive supply (3-15 V)' },
    ],
    gates: [
      { type: 'NOT', inputs: ['A'], output: 'YA' },
      { type: 'NOT', inputs: ['B'], output: 'YB' },
      { type: 'NOT', inputs: ['C'], output: 'YC' },
      { type: 'NOT', inputs: ['D'], output: 'YD' },
      { type: 'NOT', inputs: ['E'], output: 'YE' },
      { type: 'NOT', inputs: ['F'], output: 'YF' },
    ],
    guideSections: [
      {
        title: 'Schmitt Trigger Inverter',
        paragraphs: [
          'Each gate inverts its input but with a hysteretic switching threshold: the output flips LOW at a higher input voltage than it flips HIGH. This hysteresis cleans up slow or noisy edges and prevents output chatter.',
          'Pin-for-pin identical to the CD40106, so either part drops into the same socket. The classic application is a relaxation oscillator: feed the output back to the input through a resistor with a capacitor from input to ground.',
        ],
        list: [
          'RC relaxation oscillator: output → R → input, C from input to GND (f ≈ 1/(1.2·R·C)).',
          'Debounce / clean up slow or noisy digital inputs before downstream logic.',
          'Drop-in CMOS alternative to the 74x14 and the CD40106.',
        ],
        note: '74Sim models the Schmitt-trigger inputs with real hysteresis. The classic RC relaxation oscillator behaves as expected.',
      },
    ],
  },

  // ── CD4000: Dual 3 input NOR + single inverter (14-pin) ────────────────
  /* Primary source: Intersil/Renesas, CD4000BMS/CD4001BMS/CD4002BMS/CD4025BMS datasheet (Nov 1994). [Online]. Available: https://www.renesas.com/us/en/document/dst/cd4000bms-cd4001bms-cd4002bms-cd4025bms-datasheet */
  'CD4000': {
    name: 'CD4000',
    simpleName: 'Dual 3 Input NOR + Inverter',
    description: 'Dual 3-input NOR gate plus inverter, CMOS 4000 series (14-pin)',
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.renesas.com/us/en/document/dst/cd4000bms-cd4001bms-cd4002bms-cd4025bms-datasheet',
    tags: ['cmos', '4000 series', 'logic gate', 'NOR', 'inverter', 'NOT', 'dual', '3 input'],
    guideOverview: 'The CD4000 packs two independent 3 input NOR gates plus one spare inverter into a single 14-pin device — the part that gives the whole 4000 family its number. Each NOR output is HIGH only when all three of its inputs are LOW; any HIGH input forces it LOW. The extra inverter (input G on pin 8, output L on pin 9) is a standalone NOT gate handy for mopping up a leftover signal. Pins 1 and 2 are no connect. Supply voltage 3-15 V (high-voltage "BMS" versions to 20 V).',
    guidePinDescriptions: {
      NC:  'No internal connection. Leave unconnected.',
      NC2: 'No internal connection. Leave unconnected.',
      A:   'Gate 1 input A.',
      B:   'Gate 1 input B.',
      C:   'Gate 1 input C.',
      H:   'Gate 1 NOR output. HIGH only when A, B, and C are all LOW.',
      GND: 'Ground reference (VSS). Connect to 0 V.',
      G:   'Inverter input.',
      L:   'Inverter output. HIGH when G is LOW (L = NOT G).',
      K:   'Gate 2 NOR output. HIGH only when D, E, and F are all LOW.',
      D:   'Gate 2 input D.',
      E:   'Gate 2 input E.',
      F:   'Gate 2 input F.',
      VDD: 'Positive supply. Accepts 3 V to 15 V.',
    },
    pinout: [
      { pin:  1, name: 'NC',  type: 'nc',     description: 'No connection' },
      { pin:  2, name: 'NC2', type: 'nc',     description: 'No connection' },
      { pin:  3, name: 'A',   type: 'input',  description: 'Gate 1 input A' },
      { pin:  4, name: 'B',   type: 'input',  description: 'Gate 1 input B' },
      { pin:  5, name: 'C',   type: 'input',  description: 'Gate 1 input C' },
      { pin:  6, name: 'H',   type: 'output', description: 'Gate 1 NOR output: HIGH only when A, B, C all LOW' },
      { pin:  7, name: 'GND', type: 'power',  description: 'Ground (0 V)' },
      { pin:  8, name: 'G',   type: 'input',  description: 'Inverter input' },
      { pin:  9, name: 'L',   type: 'output', description: 'Inverter output (L = NOT G)' },
      { pin: 10, name: 'K',   type: 'output', description: 'Gate 2 NOR output: HIGH only when D, E, F all LOW' },
      { pin: 11, name: 'D',   type: 'input',  description: 'Gate 2 input D' },
      { pin: 12, name: 'E',   type: 'input',  description: 'Gate 2 input E' },
      { pin: 13, name: 'F',   type: 'input',  description: 'Gate 2 input F' },
      { pin: 14, name: 'VDD', type: 'power',  description: 'Positive supply (3-15 V)' },
    ],
    gates: [
      { type: 'NOR', inputs: ['A','B','C'], output: 'H' },
      { type: 'NOR', inputs: ['D','E','F'], output: 'K' },
      { type: 'NOT', inputs: ['G'], output: 'L' },
    ],
    guideSections: [
      {
        title: 'Two NORs Plus a Spare Inverter',
        paragraphs: [
          'The two NOR gates are fully independent 3 input gates: each output goes HIGH only when every one of its three inputs is LOW. The third element is a plain inverter that has nothing to do with the NOR gates — it is there to use up an otherwise-idle gate, for example to invert a control line or build a cross-coupled latch with one of the NORs.',
          'Tie any unused NOR input to a known level (LOW so it does not block the gate); never leave a CMOS input floating.',
        ],
        formulas: [
          'H = NOT(A + B + C)',
          'K = NOT(D + E + F)',
          'L = NOT(G)',
        ],
        list: [
          'Three-condition "all clear" detector: output HIGH only when all three lines are LOW.',
          'Cross-couple a NOR with the spare inverter to make a simple set/reset latch.',
          'Use the inverter alone when a design just needs one more NOT gate.',
        ],
      },
    ],
  },

  // ── CD4572: Hex gate — 4 inverters + 1 NOR + 1 NAND (16-pin) ───────────
  /* Primary source: Texas Instruments (Harris Semiconductor), CD4572UB datasheet, SCHS090C (rev. Oct 2003). [Online]. Available: https://www.ti.com/lit/ds/symlink/cd4572ub.pdf */
  'CD4572': {
    name: 'CD4572',
    simpleName: 'Hex Gate (4 Inverters + NOR + NAND)',
    description: 'Hex gate: 4 inverters, 2-input NOR + NAND, CMOS 4000 series (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/cd4572ub.pdf',
    tags: ['cmos', '4000 series', 'logic gate', 'NOT', 'inverter', 'NOR', 'NAND', 'hex', 'mixed gate'],
    guideOverview: 'The CD4572 is a "hex" mixed-function gate that bundles the leftovers you often need to finish a design: four independent inverters, one 2 input NOR gate, and one 2 input NAND gate, all in one 16-pin package. The pinout is arranged so one NOR input (pin 7) sits next to VSS and one NAND input (pin 15) next to VDD, making it easy to tie a spare input off and use either gate as an extra inverter. It is the unbuffered "UB" type. Supply voltage 3-15 V.',
    guidePinDescriptions: {
      J:   'Inverter 1 output (J = NOT A).',
      A:   'Inverter 1 input.',
      K:   'Inverter 2 output (K = NOT B).',
      B:   'Inverter 2 input.',
      L:   'NOR output (L = NOT(C + D)).',
      C:   'NOR input C.',
      D:   'NOR input D (sits next to VSS so the NOR can be used as an inverter).',
      GND: 'Ground reference (VSS). Connect to 0 V.',
      M:   'Inverter 3 output (M = NOT E).',
      E:   'Inverter 3 input.',
      N:   'Inverter 4 output (N = NOT F).',
      F:   'Inverter 4 input.',
      P:   'NAND output (P = NOT(G · H)).',
      G:   'NAND input G.',
      H:   'NAND input H (sits next to VDD so the NAND can be used as an inverter).',
      VDD: 'Positive supply. Accepts 3 V to 15 V.',
    },
    pinout: [
      { pin:  1, name: 'J',   type: 'output', description: 'Inverter 1 output (J = NOT A)' },
      { pin:  2, name: 'A',   type: 'input',  description: 'Inverter 1 input' },
      { pin:  3, name: 'K',   type: 'output', description: 'Inverter 2 output (K = NOT B)' },
      { pin:  4, name: 'B',   type: 'input',  description: 'Inverter 2 input' },
      { pin:  5, name: 'L',   type: 'output', description: 'NOR output (L = NOT(C + D))' },
      { pin:  6, name: 'C',   type: 'input',  description: 'NOR input C' },
      { pin:  7, name: 'D',   type: 'input',  description: 'NOR input D' },
      { pin:  8, name: 'GND', type: 'power',  description: 'Ground (VSS, 0 V)' },
      { pin:  9, name: 'M',   type: 'output', description: 'Inverter 3 output (M = NOT E)' },
      { pin: 10, name: 'E',   type: 'input',  description: 'Inverter 3 input' },
      { pin: 11, name: 'N',   type: 'output', description: 'Inverter 4 output (N = NOT F)' },
      { pin: 12, name: 'F',   type: 'input',  description: 'Inverter 4 input' },
      { pin: 13, name: 'P',   type: 'output', description: 'NAND output (P = NOT(G · H))' },
      { pin: 14, name: 'G',   type: 'input',  description: 'NAND input G' },
      { pin: 15, name: 'H',   type: 'input',  description: 'NAND input H' },
      { pin: 16, name: 'VDD', type: 'power',  description: 'Positive supply (3-15 V)' },
    ],
    gates: [
      { type: 'NOT',  inputs: ['A'], output: 'J' },
      { type: 'NOT',  inputs: ['B'], output: 'K' },
      { type: 'NOT',  inputs: ['E'], output: 'M' },
      { type: 'NOT',  inputs: ['F'], output: 'N' },
      { type: 'NOR',  inputs: ['C','D'], output: 'L' },
      { type: 'NAND', inputs: ['G','H'], output: 'P' },
    ],
    guideSections: [
      {
        title: 'Six Gates, Three Functions',
        paragraphs: [
          'The CD4572 is a "junk box in a chip": four inverters, a 2 input NOR, and a 2 input NAND, each fully independent. It is meant to absorb the odd leftover gates a logic design needs — an inverter here, a NAND there — without adding three separate packages.',
          'Because one NOR input (D, pin 7) is next to ground and one NAND input (H, pin 15) is next to the positive rail, you can tie that input to the adjacent supply and use the NOR or NAND as a sixth/seventh inverter.',
        ],
        formulas: [
          'J = NOT(A),  K = NOT(B),  M = NOT(E),  N = NOT(F)',
          'L = NOT(C + D)',
          'P = NOT(G · H)',
        ],
        list: [
          'Clean up a logic design by collecting scattered inverter/NAND/NOR needs into one chip.',
          'Tie a NOR/NAND input to its adjacent rail to borrow an extra inverter.',
          'Build a small set/reset latch from the NOR and NAND plus the inverters.',
        ],
        note: '74Sim models each element as a hard digital gate. The CD4572 is the unbuffered "UB" type, so on real silicon an inverter biased near its threshold can act as a small linear amplifier — that analog behavior is not simulated (logic only).',
      },
    ],
  },

};
