// Chip definitions block 49
// Chips: 74x1622-1623, 74x1631, 74x1638-1645,
//        74x1779, 74x1801, 74x1803-1805

export const CHIPS_BLOCK_49 = {

  // 74x1622: Octal bus transceiver, inverting, open-collector (20-pin)
  '74x1622': {
    name: '74x1622',
    simpleName: 'Octal Bus Transceiver Inverting (OC)',
    description: 'Octal bus transceiver, inverting, open-collector (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: '',
    tags: ['transceiver', 'octal', 'inverting', 'open collector', 'bidir', 'stub'],
    pinout: [
      { pin:  1, name: 'GABn', type: 'input'  },
      { pin:  2, name: 'GBAn', type: 'input'  },
      { pin:  3, name: 'A0',   type: 'bidir'  },
      { pin:  4, name: 'B0',   type: 'bidir'  },
      { pin:  5, name: 'A1',   type: 'bidir'  },
      { pin:  6, name: 'B1',   type: 'bidir'  },
      { pin:  7, name: 'A2',   type: 'bidir'  },
      { pin:  8, name: 'B2',   type: 'bidir'  },
      { pin:  9, name: 'A3',   type: 'bidir'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'B3',   type: 'bidir'  },
      { pin: 12, name: 'A4',   type: 'bidir'  },
      { pin: 13, name: 'B4',   type: 'bidir'  },
      { pin: 14, name: 'A5',   type: 'bidir'  },
      { pin: 15, name: 'B5',   type: 'bidir'  },
      { pin: 16, name: 'A6',   type: 'bidir'  },
      { pin: 17, name: 'B6',   type: 'bidir'  },
      { pin: 18, name: 'A7',   type: 'bidir'  },
      { pin: 19, name: 'B7',   type: 'bidir'  },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['GABn','GBAn'], outputs: [] },
    ],
  },

  // 74x1623: Octal bus transceiver, non-inverting, TRI-STATE (20-pin)
  '74x1623': {
    name: '74x1623',
    simpleName: 'Octal Bus Transceiver Non-Inverting',
    description: 'Octal bus transceiver, non-inverting, TRI-STATE (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: '',
    tags: ['transceiver', 'octal', 'non-inverting', 'tri-state', 'bidir', 'stub'],
    pinout: [
      { pin:  1, name: 'GABn', type: 'input'  },
      { pin:  2, name: 'GBAn', type: 'input'  },
      { pin:  3, name: 'A0',   type: 'bidir'  },
      { pin:  4, name: 'B0',   type: 'bidir'  },
      { pin:  5, name: 'A1',   type: 'bidir'  },
      { pin:  6, name: 'B1',   type: 'bidir'  },
      { pin:  7, name: 'A2',   type: 'bidir'  },
      { pin:  8, name: 'B2',   type: 'bidir'  },
      { pin:  9, name: 'A3',   type: 'bidir'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'B3',   type: 'bidir'  },
      { pin: 12, name: 'A4',   type: 'bidir'  },
      { pin: 13, name: 'B4',   type: 'bidir'  },
      { pin: 14, name: 'A5',   type: 'bidir'  },
      { pin: 15, name: 'B5',   type: 'bidir'  },
      { pin: 16, name: 'A6',   type: 'bidir'  },
      { pin: 17, name: 'B6',   type: 'bidir'  },
      { pin: 18, name: 'A7',   type: 'bidir'  },
      { pin: 19, name: 'B7',   type: 'bidir'  },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['GABn','GBAn'], outputs: [] },
    ],
  },

  // 74x1631: Quad bus driver with complementary outputs, TRI-STATE (16-pin)
  '74x1631': {
    name: '74x1631',
    simpleName: 'Quad Bus Driver with Complementary Outputs',
    description: 'Quad bus driver with complementary outputs, TRI-STATE (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    datasheet: '',
    tags: ['driver', 'quad', 'complementary', 'tri-state', 'stub'],
    pinout: [
      { pin:  1, name: 'OEn',  type: 'input'  },
      { pin:  2, name: 'A0',   type: 'input'  },
      { pin:  3, name: 'Y0',   type: 'output' },
      { pin:  4, name: 'Y0n',  type: 'output' },
      { pin:  5, name: 'A1',   type: 'input'  },
      { pin:  6, name: 'Y1',   type: 'output' },
      { pin:  7, name: 'Y1n',  type: 'output' },
      { pin:  8, name: 'GND',  type: 'power'  },
      { pin:  9, name: 'Y2n',  type: 'output' },
      { pin: 10, name: 'Y2',   type: 'output' },
      { pin: 11, name: 'A2',   type: 'input'  },
      { pin: 12, name: 'Y3n',  type: 'output' },
      { pin: 13, name: 'Y3',   type: 'output' },
      { pin: 14, name: 'A3',   type: 'input'  },
      { pin: 15, name: 'NC',   type: 'nc'     },
      { pin: 16, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','A0','A1','A2','A3'], outputs: [] },
    ],
  },

  // 74x1638: Octal bus transceiver, inverting, TRI-STATE+OC (20-pin)
  '74x1638': {
    name: '74x1638',
    simpleName: 'Octal Bus Transceiver Inverting (low power, TRI-STATE/OC)',
    description: 'Octal bus transceiver, inverting, TRI-STATE and open-collector (lower-power version of 74x638) (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: '',
    tags: ['transceiver', 'octal', 'inverting', 'tri-state', 'open collector', 'bidir', 'stub'],
    pinout: [
      { pin:  1, name: 'GABn', type: 'input'  },
      { pin:  2, name: 'GBAn', type: 'input'  },
      { pin:  3, name: 'A0',   type: 'bidir'  },
      { pin:  4, name: 'B0',   type: 'bidir'  },
      { pin:  5, name: 'A1',   type: 'bidir'  },
      { pin:  6, name: 'B1',   type: 'bidir'  },
      { pin:  7, name: 'A2',   type: 'bidir'  },
      { pin:  8, name: 'B2',   type: 'bidir'  },
      { pin:  9, name: 'A3',   type: 'bidir'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'B3',   type: 'bidir'  },
      { pin: 12, name: 'A4',   type: 'bidir'  },
      { pin: 13, name: 'B4',   type: 'bidir'  },
      { pin: 14, name: 'A5',   type: 'bidir'  },
      { pin: 15, name: 'B5',   type: 'bidir'  },
      { pin: 16, name: 'A6',   type: 'bidir'  },
      { pin: 17, name: 'B6',   type: 'bidir'  },
      { pin: 18, name: 'A7',   type: 'bidir'  },
      { pin: 19, name: 'B7',   type: 'bidir'  },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['GABn','GBAn'], outputs: [] },
    ],
  },

  // 74x1639: Octal bus transceiver, non-inverting, TRI-STATE+OC (20-pin)
  '74x1639': {
    name: '74x1639',
    simpleName: 'Octal Bus Transceiver Non-Inverting (low power, TRI-STATE/OC)',
    description: 'Octal bus transceiver, non-inverting, TRI-STATE and open-collector (lower-power version of 74x639) (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: '',
    tags: ['transceiver', 'octal', 'non-inverting', 'tri-state', 'open collector', 'bidir', 'stub'],
    pinout: [
      { pin:  1, name: 'GABn', type: 'input'  },
      { pin:  2, name: 'GBAn', type: 'input'  },
      { pin:  3, name: 'A0',   type: 'bidir'  },
      { pin:  4, name: 'B0',   type: 'bidir'  },
      { pin:  5, name: 'A1',   type: 'bidir'  },
      { pin:  6, name: 'B1',   type: 'bidir'  },
      { pin:  7, name: 'A2',   type: 'bidir'  },
      { pin:  8, name: 'B2',   type: 'bidir'  },
      { pin:  9, name: 'A3',   type: 'bidir'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'B3',   type: 'bidir'  },
      { pin: 12, name: 'A4',   type: 'bidir'  },
      { pin: 13, name: 'B4',   type: 'bidir'  },
      { pin: 14, name: 'A5',   type: 'bidir'  },
      { pin: 15, name: 'B5',   type: 'bidir'  },
      { pin: 16, name: 'A6',   type: 'bidir'  },
      { pin: 17, name: 'B6',   type: 'bidir'  },
      { pin: 18, name: 'A7',   type: 'bidir'  },
      { pin: 19, name: 'B7',   type: 'bidir'  },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['GABn','GBAn'], outputs: [] },
    ],
  },

  // 74x1640: Octal bus transceiver, inverting, TRI-STATE (20-pin)
  '74x1640': {
    name: '74x1640',
    simpleName: 'Octal Bus Transceiver Inverting (low power)',
    description: 'Octal bus transceiver, inverting, TRI-STATE (lower-power version of 74x640) (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: '',
    tags: ['transceiver', 'octal', 'inverting', 'tri-state', 'bidir', 'stub'],
    pinout: [
      { pin:  1, name: 'GABn', type: 'input'  },
      { pin:  2, name: 'GBAn', type: 'input'  },
      { pin:  3, name: 'A0',   type: 'bidir'  },
      { pin:  4, name: 'B0',   type: 'bidir'  },
      { pin:  5, name: 'A1',   type: 'bidir'  },
      { pin:  6, name: 'B1',   type: 'bidir'  },
      { pin:  7, name: 'A2',   type: 'bidir'  },
      { pin:  8, name: 'B2',   type: 'bidir'  },
      { pin:  9, name: 'A3',   type: 'bidir'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'B3',   type: 'bidir'  },
      { pin: 12, name: 'A4',   type: 'bidir'  },
      { pin: 13, name: 'B4',   type: 'bidir'  },
      { pin: 14, name: 'A5',   type: 'bidir'  },
      { pin: 15, name: 'B5',   type: 'bidir'  },
      { pin: 16, name: 'A6',   type: 'bidir'  },
      { pin: 17, name: 'B6',   type: 'bidir'  },
      { pin: 18, name: 'A7',   type: 'bidir'  },
      { pin: 19, name: 'B7',   type: 'bidir'  },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['GABn','GBAn'], outputs: [] },
    ],
  },

  // 74x1641: Octal bus transceiver, non-inverting, OC (20-pin)
  '74x1641': {
    name: '74x1641',
    simpleName: 'Octal Bus Transceiver Non-Inverting (low power, OC)',
    description: 'Octal bus transceiver, non-inverting, open-collector (lower-power version of 74x641) (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: '',
    tags: ['transceiver', 'octal', 'non-inverting', 'open collector', 'bidir', 'stub'],
    pinout: [
      { pin:  1, name: 'GABn', type: 'input'  },
      { pin:  2, name: 'GBAn', type: 'input'  },
      { pin:  3, name: 'A0',   type: 'bidir'  },
      { pin:  4, name: 'B0',   type: 'bidir'  },
      { pin:  5, name: 'A1',   type: 'bidir'  },
      { pin:  6, name: 'B1',   type: 'bidir'  },
      { pin:  7, name: 'A2',   type: 'bidir'  },
      { pin:  8, name: 'B2',   type: 'bidir'  },
      { pin:  9, name: 'A3',   type: 'bidir'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'B3',   type: 'bidir'  },
      { pin: 12, name: 'A4',   type: 'bidir'  },
      { pin: 13, name: 'B4',   type: 'bidir'  },
      { pin: 14, name: 'A5',   type: 'bidir'  },
      { pin: 15, name: 'B5',   type: 'bidir'  },
      { pin: 16, name: 'A6',   type: 'bidir'  },
      { pin: 17, name: 'B6',   type: 'bidir'  },
      { pin: 18, name: 'A7',   type: 'bidir'  },
      { pin: 19, name: 'B7',   type: 'bidir'  },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['GABn','GBAn'], outputs: [] },
    ],
  },

  // 74x1642: Octal bus transceiver, inverting, OC (20-pin)
  '74x1642': {
    name: '74x1642',
    simpleName: 'Octal Bus Transceiver Inverting (low power, OC)',
    description: 'Octal bus transceiver, inverting, open-collector (lower-power version of 74x642) (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: '',
    tags: ['transceiver', 'octal', 'inverting', 'open collector', 'bidir', 'stub'],
    pinout: [
      { pin:  1, name: 'GABn', type: 'input'  },
      { pin:  2, name: 'GBAn', type: 'input'  },
      { pin:  3, name: 'A0',   type: 'bidir'  },
      { pin:  4, name: 'B0',   type: 'bidir'  },
      { pin:  5, name: 'A1',   type: 'bidir'  },
      { pin:  6, name: 'B1',   type: 'bidir'  },
      { pin:  7, name: 'A2',   type: 'bidir'  },
      { pin:  8, name: 'B2',   type: 'bidir'  },
      { pin:  9, name: 'A3',   type: 'bidir'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'B3',   type: 'bidir'  },
      { pin: 12, name: 'A4',   type: 'bidir'  },
      { pin: 13, name: 'B4',   type: 'bidir'  },
      { pin: 14, name: 'A5',   type: 'bidir'  },
      { pin: 15, name: 'B5',   type: 'bidir'  },
      { pin: 16, name: 'A6',   type: 'bidir'  },
      { pin: 17, name: 'B6',   type: 'bidir'  },
      { pin: 18, name: 'A7',   type: 'bidir'  },
      { pin: 19, name: 'B7',   type: 'bidir'  },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['GABn','GBAn'], outputs: [] },
    ],
  },

  // 74x1643: Octal bus transceiver, inverting and non-inverting, TRI-STATE (20-pin)
  '74x1643': {
    name: '74x1643',
    simpleName: 'Octal Bus Transceiver Inv/Non-Inv (low power)',
    description: 'Octal bus transceiver, inverting and non-inverting, TRI-STATE (lower-power version of 74x643) (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: '',
    tags: ['transceiver', 'octal', 'tri-state', 'bidir', 'stub'],
    pinout: [
      { pin:  1, name: 'T',    type: 'input'  },
      { pin:  2, name: 'GABn', type: 'input'  },
      { pin:  3, name: 'GBAn', type: 'input'  },
      { pin:  4, name: 'A0',   type: 'bidir'  },
      { pin:  5, name: 'B0',   type: 'bidir'  },
      { pin:  6, name: 'A1',   type: 'bidir'  },
      { pin:  7, name: 'B1',   type: 'bidir'  },
      { pin:  8, name: 'A2',   type: 'bidir'  },
      { pin:  9, name: 'B2',   type: 'bidir'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'B3',   type: 'bidir'  },
      { pin: 12, name: 'A3',   type: 'bidir'  },
      { pin: 13, name: 'B4',   type: 'bidir'  },
      { pin: 14, name: 'A4',   type: 'bidir'  },
      { pin: 15, name: 'B5',   type: 'bidir'  },
      { pin: 16, name: 'A5',   type: 'bidir'  },
      { pin: 17, name: 'B6',   type: 'bidir'  },
      { pin: 18, name: 'A6',   type: 'bidir'  },
      { pin: 19, name: 'B7',   type: 'bidir'  },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['T','GABn','GBAn'], outputs: [] },
    ],
  },

  // 74x1644: Octal bus transceiver, inverting and non-inverting, OC (20-pin)
  '74x1644': {
    name: '74x1644',
    simpleName: 'Octal Bus Transceiver Inv/Non-Inv (low power, OC)',
    description: 'Octal bus transceiver, inverting and non-inverting, open-collector (lower-power version of 74x644) (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: '',
    tags: ['transceiver', 'octal', 'open collector', 'bidir', 'stub'],
    pinout: [
      { pin:  1, name: 'T',    type: 'input'  },
      { pin:  2, name: 'GABn', type: 'input'  },
      { pin:  3, name: 'GBAn', type: 'input'  },
      { pin:  4, name: 'A0',   type: 'bidir'  },
      { pin:  5, name: 'B0',   type: 'bidir'  },
      { pin:  6, name: 'A1',   type: 'bidir'  },
      { pin:  7, name: 'B1',   type: 'bidir'  },
      { pin:  8, name: 'A2',   type: 'bidir'  },
      { pin:  9, name: 'B2',   type: 'bidir'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'B3',   type: 'bidir'  },
      { pin: 12, name: 'A3',   type: 'bidir'  },
      { pin: 13, name: 'B4',   type: 'bidir'  },
      { pin: 14, name: 'A4',   type: 'bidir'  },
      { pin: 15, name: 'B5',   type: 'bidir'  },
      { pin: 16, name: 'A5',   type: 'bidir'  },
      { pin: 17, name: 'B6',   type: 'bidir'  },
      { pin: 18, name: 'A6',   type: 'bidir'  },
      { pin: 19, name: 'B7',   type: 'bidir'  },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['T','GABn','GBAn'], outputs: [] },
    ],
  },

  // 74x1645: Octal bus transceiver, non-inverting, TRI-STATE (20-pin)
  '74x1645': {
    name: '74x1645',
    simpleName: 'Octal Bus Transceiver Non-Inverting (low power)',
    description: 'Octal bus transceiver, non-inverting, TRI-STATE (lower-power version of 74x645) (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74als1645a.pdf',
    tags: ['transceiver', 'octal', 'non-inverting', 'tri-state', 'bidir', 'stub'],
    guideOverview: 'The 74ALS1645 is a low power octal bus transceiver in the same family as the classic 74x645. It bridges two 8 bit buses, lets system logic choose the direction of data flow, and can disconnect itself completely through an active LOW enable pin so shared buses do not fight. This is the kind of part you reach for when two digital subsystems need to exchange bytes over a common backplane or data bus with controlled loading.',
    guidePinDescriptions: {
      'DIR': 'Direction control input. Set this pin according to the datasheet truth table to choose A-to-B or B-to-A transfer.',
      'A0': 'Bus line A0. It becomes an input or output depending on DIR and OEn.',
      'A1': 'Bus line A1. Use it as the second bit of the A-side bus.',
      'A2': 'Bus line A2. This is another A-side transceiver channel.',
      'A3': 'Bus line A3. It participates in the controlled byte transfer path.',
      'A4': 'Bus line A4. Another A-side data bit.',
      'A5': 'Bus line A5. It switches direction with the rest of the channels.',
      'A6': 'Bus line A6. Use it for another A-side bus bit.',
      'A7': 'Bus line A7. This is the highest-numbered A-side channel.',
      'GND': 'Ground reference for the transceiver.',
      'B7': 'Bus line B7. This is the highest-numbered B-side data bit.',
      'B6': 'Bus line B6. It pairs with A6 through the transceiver.',
      'B5': 'Bus line B5. Another B-side channel.',
      'B4': 'Bus line B4. It is part of the controlled bus bridge.',
      'B3': 'Bus line B3. Use it as the B-side mate for A3.',
      'B2': 'Bus line B2. Another B-side data line.',
      'B1': 'Bus line B1. This line changes direction with the rest of the bus.',
      'B0': 'Bus line B0. This is the lowest-numbered B-side channel.',
      'OEn': 'Output enable, active LOW. Pull LOW to enable the transceiver; drive HIGH to place the bus interface in high-impedance.',
      'VCC': 'Positive supply for the device, typically +5 V.',
    },
    guideSections: [
      {
        title: 'Bus Direction Control',
        paragraphs: [
          'A bidirectional transceiver acts like a gated bridge between two buses. DIR chooses which side currently drives and which side currently listens, so one package can support both read and write traffic on the same group of wires.',
          'That is especially useful around CPUs, latches, and peripheral chips where the same 8 bit path is used in both directions at different times in the bus cycle.',
        ],
      },
      {
        title: 'Why There Is an Enable Pin',
        paragraphs: [
          'The output enable (OE, active LOW) controls whether both bus sides are connected. This high-impedance state when inactive prevents contention and lets multiple transceivers share a common backplane safely.',
        ],
        note: 'This simulator entry is kept as a documentation-oriented stub. The guide explains the bus role and controls, but the simulator does not model full directional data transfer for this placeholder.',
      },
      {
        title: 'Common Uses',
        list: [
          'Buffering an 8 bit processor or microcontroller data bus.',
          'Isolating one board section from another to reduce loading.',
          'Building shared-bus systems where several devices take turns driving the same lines.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'DIR',  type: 'input'  },
      { pin:  2, name: 'A0',   type: 'bidir'  },
      { pin:  3, name: 'A1',   type: 'bidir'  },
      { pin:  4, name: 'A2',   type: 'bidir'  },
      { pin:  5, name: 'A3',   type: 'bidir'  },
      { pin:  6, name: 'A4',   type: 'bidir'  },
      { pin:  7, name: 'A5',   type: 'bidir'  },
      { pin:  8, name: 'A6',   type: 'bidir'  },
      { pin:  9, name: 'A7',   type: 'bidir'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'B7',   type: 'bidir'  },
      { pin: 12, name: 'B6',   type: 'bidir'  },
      { pin: 13, name: 'B5',   type: 'bidir'  },
      { pin: 14, name: 'B4',   type: 'bidir'  },
      { pin: 15, name: 'B3',   type: 'bidir'  },
      { pin: 16, name: 'B2',   type: 'bidir'  },
      { pin: 17, name: 'B1',   type: 'bidir'  },
      { pin: 18, name: 'B0',   type: 'bidir'  },
      { pin: 19, name: 'OEn',  type: 'input'  },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['DIR','OEn'], outputs: [] },
    ],
  },

  // 74x1779: 8 bit bidirectional binary counter, TRI-STATE (16-pin)
  '74x1779': {
    name: '74x1779',
    simpleName: '8 bit Bidirectional Binary Counter',
    description: '8 bit bidirectional binary counter, TRI-STATE (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    datasheet: '',
    tags: ['counter', '8 bit', 'bidirectional', 'tri-state', 'stub'],
    pinout: [
      { pin:  1, name: 'U_Dn', type: 'input'  },
      { pin:  2, name: 'ENn',  type: 'input'  },
      { pin:  3, name: 'CLK',  type: 'input'  },
      { pin:  4, name: 'OEn',  type: 'input'  },
      { pin:  5, name: 'D0',   type: 'bidir'  },
      { pin:  6, name: 'D1',   type: 'bidir'  },
      { pin:  7, name: 'D2',   type: 'bidir'  },
      { pin:  8, name: 'GND',  type: 'power'  },
      { pin:  9, name: 'D3',   type: 'bidir'  },
      { pin: 10, name: 'D4',   type: 'bidir'  },
      { pin: 11, name: 'D5',   type: 'bidir'  },
      { pin: 12, name: 'D6',   type: 'bidir'  },
      { pin: 13, name: 'D7',   type: 'bidir'  },
      { pin: 14, name: 'RCon', type: 'output' },
      { pin: 15, name: 'TCon', type: 'output' },
      { pin: 16, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['U_Dn','ENn','CLK','OEn'], outputs: [] },
    ],
  },

  // 74x1801: FM/MFM/DM encoder/decoder, data rates up to 10 MHz (24-pin)
  '74x1801': {
    name: '74x1801',
    simpleName: 'FM/MFM/DM Encoder/Decoder',
    description: 'FM, MFM, and DM encoder / decoder, data rates up to 10 MHz (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['encoder', 'decoder', 'FM', 'MFM', 'data', 'stub'],
    pinout: [
      { pin:  1, name: 'RD',   type: 'input'  },
      { pin:  2, name: 'CD',   type: 'input'  },
      { pin:  3, name: 'LD',   type: 'input'  },
      { pin:  4, name: 'WD',   type: 'input'  },
      { pin:  5, name: 'RC',   type: 'input'  },
      { pin:  6, name: 'WC',   type: 'input'  },
      { pin:  7, name: 'S0',   type: 'input'  },
      { pin:  8, name: 'S1',   type: 'input'  },
      { pin:  9, name: 'RST',  type: 'input'  },
      { pin: 10, name: 'NC',   type: 'nc'     },
      { pin: 11, name: 'NC2',  type: 'nc'     },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'NC3',  type: 'nc'     },
      { pin: 14, name: 'NC4',  type: 'nc'     },
      { pin: 15, name: 'DD',   type: 'output' },
      { pin: 16, name: 'SC',   type: 'output' },
      { pin: 17, name: 'WG',   type: 'output' },
      { pin: 18, name: 'LBn',  type: 'output' },
      { pin: 19, name: 'NC5',  type: 'nc'     },
      { pin: 20, name: 'NC6',  type: 'nc'     },
      { pin: 21, name: 'NC7',  type: 'nc'     },
      { pin: 22, name: 'NC8',  type: 'nc'     },
      { pin: 23, name: 'NC9',  type: 'nc'     },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['RD','CD','LD','WD','RC','WC','S0','S1','RST'], outputs: [] },
    ],
  },

  // 74x1803: Quad clock driver (14-pin)
  '74x1803': {
    name: '74x1803',
    simpleName: 'Quad Clock Driver',
    description: 'Quad clock driver (14-pin)',
    pins: 14, vcc: 14, gnd: 7,
    datasheet: '',
    tags: ['clock', 'driver', 'quad', 'stub'],
    pinout: [
      { pin:  1, name: '1A',   type: 'input'  },
      { pin:  2, name: '1Y',   type: 'output' },
      { pin:  3, name: '2A',   type: 'input'  },
      { pin:  4, name: '2Y',   type: 'output' },
      { pin:  5, name: '3A',   type: 'input'  },
      { pin:  6, name: '3Y',   type: 'output' },
      { pin:  7, name: 'GND',  type: 'power'  },
      { pin:  8, name: '4Y',   type: 'output' },
      { pin:  9, name: '4A',   type: 'input'  },
      { pin: 10, name: 'NC',   type: 'nc'     },
      { pin: 11, name: 'NC2',  type: 'nc'     },
      { pin: 12, name: 'NC3',  type: 'nc'     },
      { pin: 13, name: 'NC4',  type: 'nc'     },
      { pin: 14, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['1A','2A','3A','4A'], outputs: [] },
    ],
  },

  // 74x1804: Hex 2 input NAND driver (20-pin)
  '74x1804': {
    name: '74x1804',
    simpleName: 'Hex 2 Input NAND Driver',
    description: 'Hex 2 input NAND gate with high-drive outputs (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: '',
    tags: ['nand', 'hex', 'driver', 'stub'],
    pinout: [
      { pin:  1, name: '1A',   type: 'input'  },
      { pin:  2, name: '1B',   type: 'input'  },
      { pin:  3, name: '1Y',   type: 'output' },
      { pin:  4, name: '2A',   type: 'input'  },
      { pin:  5, name: '2B',   type: 'input'  },
      { pin:  6, name: '2Y',   type: 'output' },
      { pin:  7, name: '3A',   type: 'input'  },
      { pin:  8, name: '3B',   type: 'input'  },
      { pin:  9, name: '3Y',   type: 'output' },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: '4Y',   type: 'output' },
      { pin: 12, name: '4A',   type: 'input'  },
      { pin: 13, name: '4B',   type: 'input'  },
      { pin: 14, name: '5Y',   type: 'output' },
      { pin: 15, name: '5A',   type: 'input'  },
      { pin: 16, name: '5B',   type: 'input'  },
      { pin: 17, name: '6Y',   type: 'output' },
      { pin: 18, name: '6A',   type: 'input'  },
      { pin: 19, name: '6B',   type: 'input'  },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['1A','1B','2A','2B','3A','3B','4A','4B','5A','5B','6A','6B'], outputs: [] },
    ],
  },

  // 74x1805: Hex 2 input NOR driver (20-pin)
  '74x1805': {
    name: '74x1805',
    simpleName: 'Hex 2 Input NOR Driver',
    description: 'Hex 2 input NOR gate with high-drive outputs (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: '',
    tags: ['nor', 'hex', 'driver', 'stub'],
    pinout: [
      { pin:  1, name: '1A',   type: 'input'  },
      { pin:  2, name: '1B',   type: 'input'  },
      { pin:  3, name: '1Y',   type: 'output' },
      { pin:  4, name: '2A',   type: 'input'  },
      { pin:  5, name: '2B',   type: 'input'  },
      { pin:  6, name: '2Y',   type: 'output' },
      { pin:  7, name: '3A',   type: 'input'  },
      { pin:  8, name: '3B',   type: 'input'  },
      { pin:  9, name: '3Y',   type: 'output' },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: '4Y',   type: 'output' },
      { pin: 12, name: '4A',   type: 'input'  },
      { pin: 13, name: '4B',   type: 'input'  },
      { pin: 14, name: '5Y',   type: 'output' },
      { pin: 15, name: '5A',   type: 'input'  },
      { pin: 16, name: '5B',   type: 'input'  },
      { pin: 17, name: '6Y',   type: 'output' },
      { pin: 18, name: '6A',   type: 'input'  },
      { pin: 19, name: '6B',   type: 'input'  },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['1A','1B','2A','2B','3A','3B','4A','4B','5A','5B','6A','6B'], outputs: [] },
    ],
  },
};