// chips62.js Block 62: 74x7074 through 74x7403
// 16 chip definitions

export const CHIPS_BLOCK_62 = {

  // ── 74x7074: Two inverters, one 2-in NAND, one 2-in NOR, two D flip flops ──
  /* Primary source: 74x7074 datasheet   URL not yet verified.
     https://en.wikipedia.org/wiki/Flip-flop_(electronics) */
  // 24-pin mixed-function chip (VCC=24, GND=12)
  // Pin assignment based on TI SN74x7074 convention:
  //   Pins 1-2: Inverter 1 (1A→1Y)
  //   Pins 3-5: 2 input NAND (2A,2B→2Y)
  //   Pins 6-8: 2 input NOR (3A,3B→3Y)
  //   Pins 9-11: D-FF 1 (4CLR,4D,4CLK)  pin 12=GND
  //   Pins 13-16: D-FF 1 outputs + D-FF 2 (4PRE,4Q,4Qn,5CLK)
  //   Pins 17-20: D-FF 2 (5D,5CLR,5PRE,5Q)
  //   Pins 21-22: 5Qn, Inverter 2 (6A)
  //   Pins 23-24: 6Y, VCC
  '74x7074': {
    name: '74x7074',
    simpleName: 'Mixed Gate+FF',
    description: '2 NOT, 2-in NAND, 2-in NOR, 2 D flip-flops (24-pin)',
    pins: 24,
    vcc: 24,
    gnd: 12,
    datasheet: '',
    tags: ['mixed', 'gate', 'logic', 'nand', 'nor', 'not', 'flip flop', 'd'],
    pinout: [
      { pin: 1,  name: '1A',    type: 'input'  },
      { pin: 2,  name: '1Y',    type: 'output' },
      { pin: 3,  name: '2A',    type: 'input'  },
      { pin: 4,  name: '2B',    type: 'input'  },
      { pin: 5,  name: '2Y',    type: 'output' },
      { pin: 6,  name: '3A',    type: 'input'  },
      { pin: 7,  name: '3B',    type: 'input'  },
      { pin: 8,  name: '3Y',    type: 'output' },
      { pin: 9,  name: '4CLR',  type: 'input'  },
      { pin: 10, name: '4D',    type: 'input'  },
      { pin: 11, name: '4CLK',  type: 'input'  },
      { pin: 12, name: 'GND',   type: 'power'  },
      { pin: 13, name: '4PRE',  type: 'input'  },
      { pin: 14, name: '4Q',    type: 'output' },
      { pin: 15, name: '4Qn',   type: 'output' },
      { pin: 16, name: '5CLK',  type: 'input'  },
      { pin: 17, name: '5D',    type: 'input'  },
      { pin: 18, name: '5CLR',  type: 'input'  },
      { pin: 19, name: '5PRE',  type: 'input'  },
      { pin: 20, name: '5Q',    type: 'output' },
      { pin: 21, name: '5Qn',   type: 'output' },
      { pin: 22, name: '6A',    type: 'input'  },
      { pin: 23, name: '6Y',    type: 'output' },
      { pin: 24, name: 'VCC',   type: 'power'  },
    ],
    gates: [
      { type: 'NOT',  inputs: ['1A'],       output: '1Y' },
      { type: 'NAND', inputs: ['2A', '2B'], output: '2Y' },
      { type: 'NOR',  inputs: ['3A', '3B'], output: '3Y' },
      { type: 'D_FF', inputs: ['4D', '4CLK', '4PRE', '4CLR'], outputs: ['4Q', '4Qn'] },
      { type: 'D_FF', inputs: ['5D', '5CLK', '5PRE', '5CLR'], outputs: ['5Q', '5Qn'] },
      { type: 'NOT',  inputs: ['6A'],       output: '6Y' },
    ],
    sequential: true,
  },

  // ── 74x7075: Two inverters, two 2-in NAND, two D flip flops ───────────────
  /* Primary source: 74x7075 datasheet   URL not yet verified.
     https://en.wikipedia.org/wiki/Flip-flop_(electronics) */
  '74x7075': {
    name: '74x7075',
    simpleName: 'Mixed Gate+FF',
    description: 'Two inverters, two 2 input NAND gates, two D type flip flops (24-pin)',
    pins: 24,
    vcc: 24,
    gnd: 12,
    datasheet: '',
    tags: ['mixed', 'gate', 'logic', 'nand', 'not', 'flip flop', 'd'],
    pinout: [
      { pin: 1,  name: '1A',    type: 'input'  },
      { pin: 2,  name: '1Y',    type: 'output' },
      { pin: 3,  name: '2A',    type: 'input'  },
      { pin: 4,  name: '2B',    type: 'input'  },
      { pin: 5,  name: '2Y',    type: 'output' },
      { pin: 6,  name: '3A',    type: 'input'  },
      { pin: 7,  name: '3B',    type: 'input'  },
      { pin: 8,  name: '3Y',    type: 'output' },
      { pin: 9,  name: '4CLR',  type: 'input'  },
      { pin: 10, name: '4D',    type: 'input'  },
      { pin: 11, name: '4CLK',  type: 'input'  },
      { pin: 12, name: 'GND',   type: 'power'  },
      { pin: 13, name: '4PRE',  type: 'input'  },
      { pin: 14, name: '4Q',    type: 'output' },
      { pin: 15, name: '4Qn',   type: 'output' },
      { pin: 16, name: '5CLK',  type: 'input'  },
      { pin: 17, name: '5D',    type: 'input'  },
      { pin: 18, name: '5CLR',  type: 'input'  },
      { pin: 19, name: '5PRE',  type: 'input'  },
      { pin: 20, name: '5Q',    type: 'output' },
      { pin: 21, name: '5Qn',   type: 'output' },
      { pin: 22, name: '6A',    type: 'input'  },
      { pin: 23, name: '6Y',    type: 'output' },
      { pin: 24, name: 'VCC',   type: 'power'  },
    ],
    gates: [
      { type: 'NOT',  inputs: ['1A'],       output: '1Y' },
      { type: 'NAND', inputs: ['2A', '2B'], output: '2Y' },
      { type: 'NAND', inputs: ['3A', '3B'], output: '3Y' },
      { type: 'D_FF', inputs: ['4D', '4CLK', '4PRE', '4CLR'], outputs: ['4Q', '4Qn'] },
      { type: 'D_FF', inputs: ['5D', '5CLK', '5PRE', '5CLR'], outputs: ['5Q', '5Qn'] },
      { type: 'NOT',  inputs: ['6A'],       output: '6Y' },
    ],
    sequential: true,
  },

  // ── 74x7076: Two inverters, two 2-in NOR, two D flip flops ────────────────
  /* Primary source: 74x7076 datasheet   URL not yet verified.
     https://en.wikipedia.org/wiki/Flip-flop_(electronics) */
  '74x7076': {
    name: '74x7076',
    simpleName: 'Mixed Gate+FF',
    description: 'Two inverters, two 2 input NOR gates, two D type flip flops (24-pin)',
    pins: 24,
    vcc: 24,
    gnd: 12,
    datasheet: '',
    tags: ['mixed', 'gate', 'logic', 'nor', 'not', 'flip flop', 'd'],
    pinout: [
      { pin: 1,  name: '1A',    type: 'input'  },
      { pin: 2,  name: '1Y',    type: 'output' },
      { pin: 3,  name: '2A',    type: 'input'  },
      { pin: 4,  name: '2B',    type: 'input'  },
      { pin: 5,  name: '2Y',    type: 'output' },
      { pin: 6,  name: '3A',    type: 'input'  },
      { pin: 7,  name: '3B',    type: 'input'  },
      { pin: 8,  name: '3Y',    type: 'output' },
      { pin: 9,  name: '4CLR',  type: 'input'  },
      { pin: 10, name: '4D',    type: 'input'  },
      { pin: 11, name: '4CLK',  type: 'input'  },
      { pin: 12, name: 'GND',   type: 'power'  },
      { pin: 13, name: '4PRE',  type: 'input'  },
      { pin: 14, name: '4Q',    type: 'output' },
      { pin: 15, name: '4Qn',   type: 'output' },
      { pin: 16, name: '5CLK',  type: 'input'  },
      { pin: 17, name: '5D',    type: 'input'  },
      { pin: 18, name: '5CLR',  type: 'input'  },
      { pin: 19, name: '5PRE',  type: 'input'  },
      { pin: 20, name: '5Q',    type: 'output' },
      { pin: 21, name: '5Qn',   type: 'output' },
      { pin: 22, name: '6A',    type: 'input'  },
      { pin: 23, name: '6Y',    type: 'output' },
      { pin: 24, name: 'VCC',   type: 'power'  },
    ],
    gates: [
      { type: 'NOT',  inputs: ['1A'],       output: '1Y' },
      { type: 'NOR',  inputs: ['2A', '2B'], output: '2Y' },
      { type: 'NOR',  inputs: ['3A', '3B'], output: '3Y' },
      { type: 'D_FF', inputs: ['4D', '4CLK', '4PRE', '4CLR'], outputs: ['4Q', '4Qn'] },
      { type: 'D_FF', inputs: ['5D', '5CLK', '5PRE', '5CLR'], outputs: ['5Q', '5Qn'] },
      { type: 'NOT',  inputs: ['6A'],       output: '6Y' },
    ],
    sequential: true,
  },

  // ── 74x7080: 16 bit parity generator/checker ──────────────────────────────
  /* Primary source: 74x7080 datasheet   URL not yet verified.
     https://en.wikipedia.org/wiki/Parity_bit */
  '74x7080': {
    name: '74x7080',
    simpleName: 'Parity Gen/Check',
    description: '16 bit parity generator / checker (20-pin)',
    pins: 20,
    vcc: 20,
    gnd: 10,
    datasheet: '',
    tags: ['parity', 'generator', 'checker'],
    pinout: [
      { pin: 1,  name: 'I0',    type: 'input'  },
      { pin: 2,  name: 'I1',    type: 'input'  },
      { pin: 3,  name: 'I2',    type: 'input'  },
      { pin: 4,  name: 'I3',    type: 'input'  },
      { pin: 5,  name: 'I4',    type: 'input'  },
      { pin: 6,  name: 'I5',    type: 'input'  },
      { pin: 7,  name: 'I6',    type: 'input'  },
      { pin: 8,  name: 'I7',    type: 'input'  },
      { pin: 9,  name: 'PE',    type: 'output' },
      { pin: 10, name: 'GND',   type: 'power'  },
      { pin: 11, name: 'PO',    type: 'output' },
      { pin: 12, name: 'I8',    type: 'input'  },
      { pin: 13, name: 'I9',    type: 'input'  },
      { pin: 14, name: 'I10',   type: 'input'  },
      { pin: 15, name: 'I11',   type: 'input'  },
      { pin: 16, name: 'I12',   type: 'input'  },
      { pin: 17, name: 'I13',   type: 'input'  },
      { pin: 18, name: 'I14',   type: 'input'  },
      { pin: 19, name: 'I15',   type: 'input'  },
      { pin: 20, name: 'VCC',   type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['I0'], outputs: ['PE'] },
    ],
  },

  // ── 74x7132: Quad adjustable comparator with output latches ────────────────
  /* Primary source: 74x7132 datasheet   URL not yet verified.
     https://en.wikipedia.org/wiki/Digital_comparator */
  '74x7132': {
    name: '74x7132',
    simpleName: 'Adj Comparator',
    description: 'Quad adjustable comparator, output latches, Schmitt, 3-state (14-pin)',
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: '',
    tags: ['comparator', 'latch', 'schmitt', 'tri state'],
    pinout: [
      { pin: 1,  name: 'A1',   type: 'input'  },
      { pin: 2,  name: 'Y1',   type: 'output' },
      { pin: 3,  name: 'A2',   type: 'input'  },
      { pin: 4,  name: 'Y2',   type: 'output' },
      { pin: 5,  name: 'A3',   type: 'input'  },
      { pin: 6,  name: 'Y3',   type: 'output' },
      { pin: 7,  name: 'GND',  type: 'power'  },
      { pin: 8,  name: 'Y4',   type: 'output' },
      { pin: 9,  name: 'A4',   type: 'input'  },
      { pin: 10, name: 'OE',   type: 'input'  },
      { pin: 11, name: 'LE',   type: 'input'  },
      { pin: 12, name: 'REF',  type: 'input'  },
      { pin: 13, name: 'NC',   type: 'nc'     },
      { pin: 14, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['A1'], outputs: ['Y1'] },
    ],
  },

  // ── 74x7204: Dual unbuffered inverters ──────────────────────────────────
  /* Primary source: Texas Instruments, 74x7204 datasheet. [Online]. Available: https://www.ti.com/lit/gpn/SN74HCU7204 */
  '74x7204': {
    name: '74x7204',
    simpleName: 'Dual Inverter',
    description: 'Dual unbuffered inverters (8-pin)',
    pins: 8,
    vcc: 8,
    gnd: 4,
    datasheet: 'https://www.ti.com/lit/gpn/SN74HCU7204',
    tags: ['inverter', 'not', 'gate', 'unbuffered'],
    guideOverview: 'The 74x7204 contains two unbuffered inverters in a small 8-pin package. An unbuffered inverter has less internal gain staging than a regular buffered logic inverter, which makes it useful not only for logic inversion but also for analog ish timing tricks such as crystal oscillators and RC oscillators. On a breadboard, it is a compact way to get two NOT gates with behavior closer to the underlying CMOS stage.',
    guidePinDescriptions: {
      '1A': 'Input to inverter 1.',
      '1Y': 'Inverted output of inverter 1.',
      '2A': 'Input to inverter 2.',
      'GND': 'Ground reference for the package.',
      '2Y': 'Inverted output of inverter 2.',
      'NC1': 'No internal connection. Leave unconnected.',
      'NC2': 'No internal connection. Leave unconnected.',
      'VCC': 'Positive supply for the device.',
    },
    guideSections: [
      {
        title: 'Unbuffered Inverter Concept',
        paragraphs: [
          'An unbuffered inverter uses a simpler signal path than a heavily buffered logic gate. That makes it better suited to oscillator and analog threshold applications, while still working as an ordinary logic inverter.',
        ],
      },
      {
        title: 'Common Uses',
        list: [
          'Plain logic inversion.',
          'RC and crystal oscillator stages.',
          'Simple wave shaping circuits where buffered gates are too aggressive.',
        ],
      },
    ],
    pinout: [
      { pin: 1, name: '1A',  type: 'input'  },
      { pin: 2, name: '1Y',  type: 'output' },
      { pin: 3, name: '2A',  type: 'input'  },
      { pin: 4, name: 'GND', type: 'power'  },
      { pin: 5, name: '2Y',  type: 'output' },
      { pin: 6, name: 'NC1', type: 'nc'     },
      { pin: 7, name: 'NC2', type: 'nc'     },
      { pin: 8, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'NOT', inputs: ['1A'], output: '1Y' },
      { type: 'NOT', inputs: ['2A'], output: '2Y' },
    ],
  },

  // ── 74x7240: Octal inverting buffer (Schmitt, tri state) ──────────────────
  /* Primary source: Toshiba, TC74HC7240 datasheet. [Online]. Available: https://toshiba.semicon-storage.com/info/docget.jsp?did=16661&prodName=TC74HC7240AP
     https://en.wikipedia.org/wiki/Three-state_logic */
  // Same pinout and logic as 74x240
  '74x7240': {
    name: '74x7240',
    simpleName: 'Octal Inv Buffer',
    description: 'Octal inverting buffer/line driver, Schmitt inputs, 3-state (20-pin)',
    pins: 20,
    vcc: 20,
    gnd: 10,
    datasheet: 'https://toshiba.semicon-storage.com/info/docget.jsp?did=16661&prodName=TC74HC7240AP',
    tags: ['buffer', 'driver', 'octal', 'tri state', 'inverting', 'schmitt'],
    guideOverview: 'The 74x7240 is an octal inverting buffer and line driver with Schmitt trigger inputs and three state outputs. It behaves like a 240-family driver, but the Schmitt front end gives better noise immunity and cleaner switching when inputs have slow or ragged edges. This makes it useful for bus isolation, cable driven signals, and digital lines that come from switches, RC networks, or noisy logic.',
    guidePinDescriptions: {
      '1OE': 'Active LOW enable for bank 1. Pull LOW to let outputs 1Y1 through 1Y4 drive.',
      '1A1': 'Input bit 1 of bank 1.',
      '2Y4': 'Inverting three state output bit 4 of bank 2.',
      '1A2': 'Input bit 2 of bank 1.',
      '2Y3': 'Inverting three state output bit 3 of bank 2.',
      '1A3': 'Input bit 3 of bank 1.',
      '2Y2': 'Inverting three state output bit 2 of bank 2.',
      '1A4': 'Input bit 4 of bank 1.',
      '2Y1': 'Inverting three state output bit 1 of bank 2.',
      'GND': 'Ground reference for the package.',
      '2A1': 'Input bit 1 of bank 2.',
      '1Y4': 'Inverting three state output bit 4 of bank 1.',
      '2A2': 'Input bit 2 of bank 2.',
      '1Y3': 'Inverting three state output bit 3 of bank 1.',
      '2A3': 'Input bit 3 of bank 2.',
      '1Y2': 'Inverting three state output bit 2 of bank 1.',
      '2A4': 'Input bit 4 of bank 2.',
      '1Y1': 'Inverting three state output bit 1 of bank 1.',
      '2OE': 'Active LOW enable for bank 2.',
      'VCC': 'Positive supply for the device.',
    },
    guideSections: [
      {
        title: 'Inverting Tri State Driver',
        paragraphs: [
          'Each channel outputs the opposite logic state of its input when enabled, and disconnects from the bus when disabled. That makes the chip suitable for shared buses and line-driving jobs where polarity inversion is acceptable or desired.',
        ],
      },
      {
        title: 'Why Schmitt Inputs Matter',
        paragraphs: [
          'Schmitt trigger inputs add hysteresis, so the input must move farther before the logic state flips back. That reduces chatter and false switching with slow edges or noisy signals.',
        ],
      },
    ],
    pinout: [
      { pin: 1,  name: '1OE',  type: 'input'  },
      { pin: 2,  name: '1A1',  type: 'input'  },
      { pin: 3,  name: '2Y4',  type: 'output' },
      { pin: 4,  name: '1A2',  type: 'input'  },
      { pin: 5,  name: '2Y3',  type: 'output' },
      { pin: 6,  name: '1A3',  type: 'input'  },
      { pin: 7,  name: '2Y2',  type: 'output' },
      { pin: 8,  name: '1A4',  type: 'input'  },
      { pin: 9,  name: '2Y1',  type: 'output' },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: '2A1',  type: 'input'  },
      { pin: 12, name: '1Y4',  type: 'output' },
      { pin: 13, name: '2A2',  type: 'input'  },
      { pin: 14, name: '1Y3',  type: 'output' },
      { pin: 15, name: '2A3',  type: 'input'  },
      { pin: 16, name: '1Y2',  type: 'output' },
      { pin: 17, name: '2A4',  type: 'input'  },
      { pin: 18, name: '1Y1',  type: 'output' },
      { pin: 19, name: '2OE',  type: 'input'  },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'TRI_NOT_LO', inputs: ['1A1', '1OE'], output: '1Y1' },
      { type: 'TRI_NOT_LO', inputs: ['1A2', '1OE'], output: '1Y2' },
      { type: 'TRI_NOT_LO', inputs: ['1A3', '1OE'], output: '1Y3' },
      { type: 'TRI_NOT_LO', inputs: ['1A4', '1OE'], output: '1Y4' },
      { type: 'TRI_NOT_LO', inputs: ['2A1', '2OE'], output: '2Y1' },
      { type: 'TRI_NOT_LO', inputs: ['2A2', '2OE'], output: '2Y2' },
      { type: 'TRI_NOT_LO', inputs: ['2A3', '2OE'], output: '2Y3' },
      { type: 'TRI_NOT_LO', inputs: ['2A4', '2OE'], output: '2Y4' },
    ],
  },

  // ── 74x7241: Octal non inverting buffer (Schmitt, tri state) ──────────────
  /* Primary source: Texas Instruments, 74x7241 datasheet. [Online]. Available: https://www.ti.com/lit/gpn/SN74LS241
     https://en.wikipedia.org/wiki/Three-state_logic */
  // Same pinout as 74x241: bank 1 uses active low OE, bank 2 uses active high OE
  '74x7241': {
    name: '74x7241',
    simpleName: 'Octal Buffer',
    description: 'Octal non inverting buffer/line driver, Schmitt inputs, 3-state (20-pin)',
    pins: 20,
    vcc: 20,
    gnd: 10,
    datasheet: 'https://www.ti.com/lit/gpn/SN74LS241',
    tags: ['buffer', 'driver', 'octal', 'tri state', 'non inverting', 'schmitt'],
    guideOverview: 'The 74x7241 is an octal non inverting buffer and line driver with tri state outputs, organized like a 241-family part. One bank uses an active LOW enable and the other uses an active HIGH enable, which is handy when two groups of lines need complementary control logic. In this simulator, the 241-family behavior is the right functional reference; the Schmitt trigger input detail is an electrical refinement rather than a different truth table.',
    guidePinDescriptions: {
      '1OE': 'Active LOW enable for bank 1. Pull LOW to let outputs 1Y1 through 1Y4 drive.',
      '1A1': 'Input bit 1 of bank 1.',
      '2Y4': 'Three state output bit 4 of bank 2.',
      '1A2': 'Input bit 2 of bank 1.',
      '2Y3': 'Three state output bit 3 of bank 2.',
      '1A3': 'Input bit 3 of bank 1.',
      '2Y2': 'Three state output bit 2 of bank 2.',
      '1A4': 'Input bit 4 of bank 1.',
      '2Y1': 'Three state output bit 1 of bank 2.',
      'GND': 'Ground reference for the package.',
      '2A1': 'Input bit 1 of bank 2.',
      '1Y4': 'Three state output bit 4 of bank 1.',
      '2A2': 'Input bit 2 of bank 2.',
      '1Y3': 'Three state output bit 3 of bank 1.',
      '2A3': 'Input bit 3 of bank 2.',
      '1Y2': 'Three state output bit 2 of bank 1.',
      '2A4': 'Input bit 4 of bank 2.',
      '1Y1': 'Three state output bit 1 of bank 1.',
      '2OE': 'Active HIGH enable for bank 2 in this 241-style family mapping.',
      'VCC': 'Positive supply for the device.',
    },
    guideSections: [
      {
        title: '241-Style Buffer Organization',
        paragraphs: [
          'The chip is split into two four bit banks, each with its own enable polarity. That makes it easier to interface with control logic that already has one active LOW and one active HIGH control signal available.',
        ],
      },
      {
        title: 'Three State Bus Use',
        paragraphs: [
          'When a bank is disabled, its outputs disconnect from the bus instead of driving HIGH or LOW. That is essential when multiple devices share the same data lines.',
        ],
      },
    ],
    pinout: [
      { pin: 1,  name: '1OE',  type: 'input'  },
      { pin: 2,  name: '1A1',  type: 'input'  },
      { pin: 3,  name: '2Y4',  type: 'output' },
      { pin: 4,  name: '1A2',  type: 'input'  },
      { pin: 5,  name: '2Y3',  type: 'output' },
      { pin: 6,  name: '1A3',  type: 'input'  },
      { pin: 7,  name: '2Y2',  type: 'output' },
      { pin: 8,  name: '1A4',  type: 'input'  },
      { pin: 9,  name: '2Y1',  type: 'output' },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: '2A1',  type: 'input'  },
      { pin: 12, name: '1Y4',  type: 'output' },
      { pin: 13, name: '2A2',  type: 'input'  },
      { pin: 14, name: '1Y3',  type: 'output' },
      { pin: 15, name: '2A3',  type: 'input'  },
      { pin: 16, name: '1Y2',  type: 'output' },
      { pin: 17, name: '2A4',  type: 'input'  },
      { pin: 18, name: '1Y1',  type: 'output' },
      { pin: 19, name: '2OE',  type: 'input'  },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'TRI_BUFFER_LO', inputs: ['1A1', '1OE'], output: '1Y1' },
      { type: 'TRI_BUFFER_LO', inputs: ['1A2', '1OE'], output: '1Y2' },
      { type: 'TRI_BUFFER_LO', inputs: ['1A3', '1OE'], output: '1Y3' },
      { type: 'TRI_BUFFER_LO', inputs: ['1A4', '1OE'], output: '1Y4' },
      { type: 'TRI_BUFFER_HI', inputs: ['2A1', '2OE'], output: '2Y1' },
      { type: 'TRI_BUFFER_HI', inputs: ['2A2', '2OE'], output: '2Y2' },
      { type: 'TRI_BUFFER_HI', inputs: ['2A3', '2OE'], output: '2Y3' },
      { type: 'TRI_BUFFER_HI', inputs: ['2A4', '2OE'], output: '2Y4' },
    ],
  },

  // ── 74x7244: Octal non inverting buffer (Schmitt, tri state) ──────────────
  /* Primary source: Toshiba, TC74HC7244 datasheet. [Online]. Available: https://toshiba.semicon-storage.com/info/docget.jsp?did=16661&prodName=TC74HC7244AP
     https://en.wikipedia.org/wiki/Three-state_logic */
  // Same pinout as 74x244: both banks use active low OE
  '74x7244': {
    name: '74x7244',
    simpleName: 'Octal Buffer',
    description: 'Octal non inverting buffer/line driver, Schmitt inputs, 3-state (20-pin)',
    pins: 20,
    vcc: 20,
    gnd: 10,
    datasheet: 'https://toshiba.semicon-storage.com/info/docget.jsp?did=16661&prodName=TC74HC7244AP',
    tags: ['buffer', 'driver', 'octal', 'tri state', 'non inverting', 'schmitt'],
    guideOverview: 'The 74x7244 is an octal non inverting buffer and line driver with Schmitt trigger inputs and three state outputs. It follows the familiar 244-family organization, with two independent active LOW enable pins controlling two banks of four outputs. This makes it useful for bus driving, fan out improvement, and isolating noisy or slow edge signals before they reach the rest of a logic system.',
    guidePinDescriptions: {
      '1OE': 'Active LOW enable for bank 1.',
      '1A1': 'Input bit 1 of bank 1.',
      '2Y4': 'Three state output bit 4 of bank 2.',
      '1A2': 'Input bit 2 of bank 1.',
      '2Y3': 'Three state output bit 3 of bank 2.',
      '1A3': 'Input bit 3 of bank 1.',
      '2Y2': 'Three state output bit 2 of bank 2.',
      '1A4': 'Input bit 4 of bank 1.',
      '2Y1': 'Three state output bit 1 of bank 2.',
      'GND': 'Ground reference for the package.',
      '2A1': 'Input bit 1 of bank 2.',
      '1Y4': 'Three state output bit 4 of bank 1.',
      '2A2': 'Input bit 2 of bank 2.',
      '1Y3': 'Three state output bit 3 of bank 1.',
      '2A3': 'Input bit 3 of bank 2.',
      '1Y2': 'Three state output bit 2 of bank 1.',
      '2A4': 'Input bit 4 of bank 2.',
      '1Y1': 'Three state output bit 1 of bank 1.',
      '2OE': 'Active LOW enable for bank 2.',
      'VCC': 'Positive supply for the device.',
    },
    guideSections: [
      {
        title: '244-Style Non Inverting Driver',
        paragraphs: [
          'Each output follows its input without inversion when enabled. The two bank enables let you control four bit groups independently, which is convenient in bus oriented designs.',
        ],
      },
      {
        title: 'Noise Tolerant Inputs',
        paragraphs: [
          'Schmitt trigger inputs are less likely to chatter when fed from slow or noisy sources. That makes the part a better line conditioner than a plain buffer when wiring is long or signals are ragged.',
        ],
      },
    ],
    pinout: [
      { pin: 1,  name: '1OE',  type: 'input'  },
      { pin: 2,  name: '1A1',  type: 'input'  },
      { pin: 3,  name: '2Y4',  type: 'output' },
      { pin: 4,  name: '1A2',  type: 'input'  },
      { pin: 5,  name: '2Y3',  type: 'output' },
      { pin: 6,  name: '1A3',  type: 'input'  },
      { pin: 7,  name: '2Y2',  type: 'output' },
      { pin: 8,  name: '1A4',  type: 'input'  },
      { pin: 9,  name: '2Y1',  type: 'output' },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: '2A1',  type: 'input'  },
      { pin: 12, name: '1Y4',  type: 'output' },
      { pin: 13, name: '2A2',  type: 'input'  },
      { pin: 14, name: '1Y3',  type: 'output' },
      { pin: 15, name: '2A3',  type: 'input'  },
      { pin: 16, name: '1Y2',  type: 'output' },
      { pin: 17, name: '2A4',  type: 'input'  },
      { pin: 18, name: '1Y1',  type: 'output' },
      { pin: 19, name: '2OE',  type: 'input'  },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'TRI_BUFFER_LO', inputs: ['1A1', '1OE'], output: '1Y1' },
      { type: 'TRI_BUFFER_LO', inputs: ['1A2', '1OE'], output: '1Y2' },
      { type: 'TRI_BUFFER_LO', inputs: ['1A3', '1OE'], output: '1Y3' },
      { type: 'TRI_BUFFER_LO', inputs: ['1A4', '1OE'], output: '1Y4' },
      { type: 'TRI_BUFFER_LO', inputs: ['2A1', '2OE'], output: '2Y1' },
      { type: 'TRI_BUFFER_LO', inputs: ['2A2', '2OE'], output: '2Y2' },
      { type: 'TRI_BUFFER_LO', inputs: ['2A3', '2OE'], output: '2Y3' },
      { type: 'TRI_BUFFER_LO', inputs: ['2A4', '2OE'], output: '2Y4' },
    ],
  },

  // ── 74x7245: Octal bus transceiver (Schmitt, tri state) ───────────────────
  /* Primary source: Texas Instruments, 74x7245 datasheet. [Online]. Available: https://www.ti.com/lit/gpn/SN74LS245
     https://en.wikipedia.org/wiki/Bus_transceiver */
  // Same pinout and logic as 74x245
  '74x7245': {
    name: '74x7245',
    simpleName: 'Octal Transceiver',
    description: 'Octal bus transceiver, Schmitt inputs, 3-state (20-pin)',
    pins: 20,
    vcc: 20,
    gnd: 10,
    datasheet: 'https://www.ti.com/lit/gpn/SN74LS245',
    tags: ['transceiver', 'bus', 'octal', 'tri state', 'bidirectional', 'schmitt'],
    guideOverview: 'The 74x7245 is an octal bidirectional bus transceiver in the 245 family. It can pass eight bits from bus A to bus B or the reverse, with the direction pin selecting the source side and the enable pin disconnecting the device when needed. In the simulator, standard 245-family digital behavior is the right reference; the Schmitt trigger feature is an electrical improvement on the inputs rather than a different logic function.',
    guidePinDescriptions: {
      'DIR': 'Direction control. It selects whether data flows from A to B or from B to A.',
      'A1': 'Bit 1 on the A-side bus.',
      'A2': 'Bit 2 on the A-side bus.',
      'A3': 'Bit 3 on the A-side bus.',
      'A4': 'Bit 4 on the A-side bus.',
      'A5': 'Bit 5 on the A-side bus.',
      'A6': 'Bit 6 on the A-side bus.',
      'A7': 'Bit 7 on the A-side bus.',
      'A8': 'Bit 8 on the A-side bus.',
      'GND': 'Ground reference for the package.',
      'B8': 'Bit 8 on the B-side bus.',
      'B7': 'Bit 7 on the B-side bus.',
      'B6': 'Bit 6 on the B-side bus.',
      'B5': 'Bit 5 on the B-side bus.',
      'B4': 'Bit 4 on the B-side bus.',
      'B3': 'Bit 3 on the B-side bus.',
      'B2': 'Bit 2 on the B-side bus.',
      'B1': 'Bit 1 on the B-side bus.',
      'OE': 'Output enable for the transceiver. Disable it to disconnect both bus sides.',
      'VCC': 'Positive supply for the device.',
    },
    guideSections: [
      {
        title: 'Bidirectional Bus Transfer',
        paragraphs: [
          'A transceiver lets one multi bit bus drive another in either direction. This is useful whenever two subsystems share a data path but should not always be directly tied together.',
        ],
      },
      {
        title: 'Why It Matters On A Breadboard',
        paragraphs: [
          'A 245-style part helps isolate loading, control which side is currently driving, and avoid bus contention. That makes it a standard building block in processor, peripheral, and bus expansion circuits.',
        ],
      },
    ],
    pinout: [
      { pin: 1,  name: 'DIR',  type: 'input'  },
      { pin: 2,  name: 'A1',   type: 'input'  },
      { pin: 3,  name: 'A2',   type: 'input'  },
      { pin: 4,  name: 'A3',   type: 'input'  },
      { pin: 5,  name: 'A4',   type: 'input'  },
      { pin: 6,  name: 'A5',   type: 'input'  },
      { pin: 7,  name: 'A6',   type: 'input'  },
      { pin: 8,  name: 'A7',   type: 'input'  },
      { pin: 9,  name: 'A8',   type: 'input'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'B8',   type: 'input'  },
      { pin: 12, name: 'B7',   type: 'input'  },
      { pin: 13, name: 'B6',   type: 'input'  },
      { pin: 14, name: 'B5',   type: 'input'  },
      { pin: 15, name: 'B4',   type: 'input'  },
      { pin: 16, name: 'B3',   type: 'input'  },
      { pin: 17, name: 'B2',   type: 'input'  },
      { pin: 18, name: 'B1',   type: 'input'  },
      { pin: 19, name: 'OE',   type: 'input'  },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      {
        type: 'TRANSCEIVER_8BIT',
        inputs: ['A1','A2','A3','A4','A5','A6','A7','A8','B1','B2','B3','B4','B5','B6','B7','B8','DIR','OE'],
        outputs: ['A1','A2','A3','A4','A5','A6','A7','A8','B1','B2','B3','B4','B5','B6','B7','B8'],
      },
    ],
  },

  // ── 74x7266: Quad 2 input XNOR gate ───────────────────────────────────────
  /* Primary source: 74x7266 datasheet   URL not yet verified. */
  // Pinout is mixed: gate 1 = A-B-Y (pins 1-3), gate 2 = Y-A-B (pins 4-6),
  // gate 3 = A-B-Y (pins 8-10), gate 4 = Y-A-B (pins 11-13).
  '74x7266': {
    name: '74x7266',
    simpleName: 'Quad XNOR',
    description: 'Four 2 input XNOR (Exclusive NOR) gates. (14-pin)',
    guideOverview: 'The 74x7266 provides four independent XNOR gates. A common use is edge detection: combine the XNOR with an RC delay to generate a pulse whenever the input changes state. Note the non uniform pin ordering check the pinout carefully before wiring.',
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: '',
    tags: ['xnor', 'gate', 'logic', 'quad', 'exclusive nor'],
    pinout: [
      { pin: 1,  name: '1A',  type: 'input'  },
      { pin: 2,  name: '1B',  type: 'input'  },
      { pin: 3,  name: '1Y',  type: 'output' },
      { pin: 4,  name: '2Y',  type: 'output' },
      { pin: 5,  name: '2A',  type: 'input'  },
      { pin: 6,  name: '2B',  type: 'input'  },
      { pin: 7,  name: 'GND', type: 'power'  },
      { pin: 8,  name: '3A',  type: 'input'  },
      { pin: 9,  name: '3B',  type: 'input'  },
      { pin: 10, name: '3Y',  type: 'output' },
      { pin: 11, name: '4Y',  type: 'output' },
      { pin: 12, name: '4A',  type: 'input'  },
      { pin: 13, name: '4B',  type: 'input'  },
      { pin: 14, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'XNOR', inputs: ['1A', '1B'], output: '1Y' },
      { type: 'XNOR', inputs: ['2A', '2B'], output: '2Y' },
      { type: 'XNOR', inputs: ['3A', '3B'], output: '3Y' },
      { type: 'XNOR', inputs: ['4A', '4B'], output: '4Y' },
    ],
  },

  // ── 74x7273: Octal D flip flop with reset ─────────────────────────────────
  /* Primary source: Texas Instruments, 74x7273 datasheet. [Online]. Available: https://www.ti.com/lit/gpn/SN74LS273
     https://en.wikipedia.org/wiki/Flip-flop_(electronics) */
  // Same pinout as 74x273 (D_FF_OCTAL)
  '74x7273': {
    name: '74x7273',
    simpleName: 'Octal D FF',
    description: 'Octal positive edge triggered D type flip flop with reset (20-pin)',
    pins: 20,
    vcc: 20,
    gnd: 10,
    datasheet: 'https://www.ti.com/lit/gpn/SN74LS273',
    tags: ['flip flop', 'flip flop', 'd', 'octal', 'sequential', 'register'],
    guideOverview: 'The 74x7273 is an octal edge triggered D type register with a shared clock and asynchronous clear, functionally aligned with the 273 family. It captures eight input bits at the clock edge and holds them until the next capture event. This makes it useful for latching data buses, building output registers, and creating synchronous storage stages in digital systems.',
    guidePinDescriptions: {
      'CLR': 'Asynchronous clear for the whole register. Assert it to reset all outputs without waiting for a clock.',
      '1Q': 'Stored output bit 1.',
      '1D': 'Data input bit 1.',
      '2D': 'Data input bit 2.',
      '2Q': 'Stored output bit 2.',
      '3D': 'Data input bit 3.',
      '3Q': 'Stored output bit 3.',
      '4D': 'Data input bit 4.',
      '4Q': 'Stored output bit 4.',
      'GND': 'Ground reference for the package.',
      'CLK': 'Shared clock input. All eight D inputs are captured together on the active edge.',
      '5Q': 'Stored output bit 5.',
      '5D': 'Data input bit 5.',
      '6D': 'Data input bit 6.',
      '6Q': 'Stored output bit 6.',
      '7D': 'Data input bit 7.',
      '7Q': 'Stored output bit 7.',
      '8D': 'Data input bit 8.',
      '8Q': 'Stored output bit 8.',
      'VCC': 'Positive supply for the device.',
    },
    guideSections: [
      {
        title: 'Octal Register Behavior',
        paragraphs: [
          'All eight data bits are sampled together on the active clock edge and then held until the next capture. That makes the part a compact way to store one byte of synchronous state.',
        ],
      },
      {
        title: 'Why Shared Clear Is Useful',
        paragraphs: [
          'The asynchronous clear input can force the register to a known reset state immediately. That is useful when power up or system reset must bring all stored outputs to a predictable value.',
        ],
      },
    ],
    pinout: [
      { pin: 1,  name: 'CLR',  type: 'input'  },
      { pin: 2,  name: '1Q',   type: 'output' },
      { pin: 3,  name: '1D',   type: 'input'  },
      { pin: 4,  name: '2D',   type: 'input'  },
      { pin: 5,  name: '2Q',   type: 'output' },
      { pin: 6,  name: '3D',   type: 'input'  },
      { pin: 7,  name: '3Q',   type: 'output' },
      { pin: 8,  name: '4D',   type: 'input'  },
      { pin: 9,  name: '4Q',   type: 'output' },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'CLK',  type: 'input'  },
      { pin: 12, name: '5Q',   type: 'output' },
      { pin: 13, name: '5D',   type: 'input'  },
      { pin: 14, name: '6D',   type: 'input'  },
      { pin: 15, name: '6Q',   type: 'output' },
      { pin: 16, name: '7D',   type: 'input'  },
      { pin: 17, name: '7Q',   type: 'output' },
      { pin: 18, name: '8D',   type: 'input'  },
      { pin: 19, name: '8Q',   type: 'output' },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      {
        type: 'D_FF_OCTAL',
        inputs: ['1D', '2D', '3D', '4D', '5D', '6D', '7D', '8D', 'CLK', 'CLR'],
        outputs: ['1Q', '2Q', '3Q', '4Q', '5Q', '6Q', '7Q', '8Q'],
      },
    ],
    sequential: true,
  },

  // ── 74x7292: Programmable divider/timer ────────────────────────────────────
  /* Primary source: Toshiba, TC74HC7292 datasheet. [Online]. Available: https://toshiba.semicon-storage.com/info/docget.jsp?did=16705&prodName=TC74HC7292AP */
  '74x7292': {
    name: '74x7292',
    simpleName: 'Prog. Freq Divider',
    description: 'Programmable frequency divider (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    sequential: true,
    datasheet: 'https://toshiba.semicon-storage.com/info/docget.jsp?did=16705&prodName=TC74HC7292AP',
    tags: ['timer', 'divider', 'counter'],
    guideOverview: 'The TC74HC7292AP is a 12 bit programmable frequency divider. Twelve program inputs D0-D11 set a binary divisor N (0 4095). The chip counts N+1 falling edges of CLK, toggles OUT, then reloads producing an output that divides the input clock by N+1 with approximately 50% duty cycle when the divisor is even. Maximum division ratio is 4096 (all program inputs HIGH). Minimum is 1 (all program inputs LOW).',
    guidePinDescriptions: {
      'CLK': 'Clock input. Division is triggered on falling edges.',
      'D0':  'Program bit 0 (LSB). Sets divisor N bit 0.',
      'D1':  'Program bit 1.',
      'D2':  'Program bit 2.',
      'D3':  'Program bit 3.',
      'D4':  'Program bit 4.',
      'D5':  'Program bit 5.',
      'GND': 'Ground reference (pin 8).',
      'D6':  'Program bit 6.',
      'D7':  'Program bit 7.',
      'D8':  'Program bit 8.',
      'D9':  'Program bit 9.',
      'D10': 'Program bit 10.',
      'D11': 'Program bit 11 (MSB). Sets divisor N bit 11.',
      'OUT': 'Divided clock output. Toggles every N+1 CLK cycles.',
      'VCC': 'Positive supply (+5 V, pin 16).',
    },
    guideSections: [
      {
        title: 'Programmable Division Ratio',
        paragraphs: [
          'Set D0-D11 to hard wire the division ratio. The 12 bits form a binary integer N. The output frequency is f_CLK / (N+1), giving ratios from 1 (N=0) to 4096 (N=4095).',
        ],
        formulas: [
          'N = D0 + D1×2 + D2×4 + ... + D11×2048',
          'f_OUT = f_CLK / (N + 1)',
        ],
      },
      {
        title: 'Output Waveform',
        paragraphs: [
          'OUT toggles every time the internal down counter reaches zero and reloads. When N+1 is even the duty cycle is exactly 50%. When N+1 is odd OUT is HIGH for ⌈(N+1)/2⌉ cycles and LOW for ⌊(N+1)/2⌋ cycles.',
        ],
      },
    ],
    pinout: [
      { pin: 1,  name: 'CLK',  type: 'input'  },
      { pin: 2,  name: 'D0',   type: 'input'  },
      { pin: 3,  name: 'D1',   type: 'input'  },
      { pin: 4,  name: 'D2',   type: 'input'  },
      { pin: 5,  name: 'D3',   type: 'input'  },
      { pin: 6,  name: 'D4',   type: 'input'  },
      { pin: 7,  name: 'D5',   type: 'input'  },
      { pin: 8,  name: 'GND',  type: 'power'  },
      { pin: 9,  name: 'D6',   type: 'input'  },
      { pin: 10, name: 'D7',   type: 'input'  },
      { pin: 11, name: 'D8',   type: 'input'  },
      { pin: 12, name: 'D9',   type: 'input'  },
      { pin: 13, name: 'D10',  type: 'input'  },
      { pin: 14, name: 'D11',  type: 'input'  },
      { pin: 15, name: 'OUT',  type: 'output' },
      { pin: 16, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'FREQ_DIV_PROG_12BIT', inputs: ['CLK','D0','D1','D2','D3','D4','D5','D6','D7','D8','D9','D10','D11'], outputs: ['OUT'] },
    ],
  },

  // ── 74x7294: Programmable divider/timer ────────────────────────────────────
  /* Primary source: 74x7294 datasheet   URL not yet verified. */
  '74x7294': {
    name: '74x7294',
    simpleName: 'Divider/Timer',
    description: 'Programmable divider/timer (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: '',
    tags: ['timer', 'divider', 'counter'],
    pinout: [
      { pin: 1,  name: 'CLK',  type: 'input'  },
      { pin: 2,  name: 'D0',   type: 'input'  },
      { pin: 3,  name: 'D1',   type: 'input'  },
      { pin: 4,  name: 'D2',   type: 'input'  },
      { pin: 5,  name: 'D3',   type: 'input'  },
      { pin: 6,  name: 'D4',   type: 'input'  },
      { pin: 7,  name: 'D5',   type: 'input'  },
      { pin: 8,  name: 'GND',  type: 'power'  },
      { pin: 9,  name: 'D6',   type: 'input'  },
      { pin: 10, name: 'D7',   type: 'input'  },
      { pin: 11, name: 'D8',   type: 'input'  },
      { pin: 12, name: 'D9',   type: 'input'  },
      { pin: 13, name: 'D10',  type: 'input'  },
      { pin: 14, name: 'D11',  type: 'input'  },
      { pin: 15, name: 'OUT',  type: 'output' },
      { pin: 16, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['CLK'], outputs: ['OUT'] },
    ],
  },

  // ── 74x7340: 8 bit bus driver with bidirectional registers ─────────────────
  /* Primary source: 74x7340 datasheet   URL not yet verified.
     https://en.wikipedia.org/wiki/Bus_transceiver */
  '74x7340': {
    name: '74x7340',
    simpleName: 'Bus Driver/Reg',
    description: '8 bit bus driver with bidirectional registers (tri state) (24-pin)',
    pins: 24,
    vcc: 24,
    gnd: 12,
    datasheet: '',
    tags: ['bus', 'driver', 'register', 'tri state', 'bidirectional'],
    pinout: [
      { pin: 1,  name: 'OE',    type: 'input'  },
      { pin: 2,  name: 'D1',    type: 'input'  },
      { pin: 3,  name: 'D2',    type: 'input'  },
      { pin: 4,  name: 'D3',    type: 'input'  },
      { pin: 5,  name: 'D4',    type: 'input'  },
      { pin: 6,  name: 'D5',    type: 'input'  },
      { pin: 7,  name: 'D6',    type: 'input'  },
      { pin: 8,  name: 'D7',    type: 'input'  },
      { pin: 9,  name: 'D8',    type: 'input'  },
      { pin: 10, name: 'CLK',   type: 'input'  },
      { pin: 11, name: 'DIR',   type: 'input'  },
      { pin: 12, name: 'GND',   type: 'power'  },
      { pin: 13, name: 'Y8',    type: 'output' },
      { pin: 14, name: 'Y7',    type: 'output' },
      { pin: 15, name: 'Y6',    type: 'output' },
      { pin: 16, name: 'Y5',    type: 'output' },
      { pin: 17, name: 'Y4',    type: 'output' },
      { pin: 18, name: 'Y3',    type: 'output' },
      { pin: 19, name: 'Y2',    type: 'output' },
      { pin: 20, name: 'Y1',    type: 'output' },
      { pin: 21, name: 'LE',    type: 'input'  },
      { pin: 22, name: 'CLR',   type: 'input'  },
      { pin: 23, name: 'NC',    type: 'nc'     },
      { pin: 24, name: 'VCC',   type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['D1'], outputs: ['Y1'] },
    ],
  },

  // ── 74x7403: 256 bit FIFO memory (64×4) ──────────────────────────────────
  /* Primary source: 74x7403 datasheet   URL not yet verified.
     https://en.wikipedia.org/wiki/Queue_(abstract_data_type) */
  '74x7403': {
    name: '74x7403',
    simpleName: 'FIFO 64x4',
    description: '256 bit FIFO memory (64x4) with tri state outputs (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: '',
    tags: ['fifo', 'memory', 'tri state'],
    pinout: [
      { pin: 1,  name: 'D0',    type: 'input'  },
      { pin: 2,  name: 'D1',    type: 'input'  },
      { pin: 3,  name: 'D2',    type: 'input'  },
      { pin: 4,  name: 'D3',    type: 'input'  },
      { pin: 5,  name: 'WR',    type: 'input'  },
      { pin: 6,  name: 'RD',    type: 'input'  },
      { pin: 7,  name: 'RST',   type: 'input'  },
      { pin: 8,  name: 'GND',   type: 'power'  },
      { pin: 9,  name: 'Q0',    type: 'output' },
      { pin: 10, name: 'Q1',    type: 'output' },
      { pin: 11, name: 'Q2',    type: 'output' },
      { pin: 12, name: 'Q3',    type: 'output' },
      { pin: 13, name: 'IRn',   type: 'output' },
      { pin: 14, name: 'ORn',   type: 'output' },
      { pin: 15, name: 'OEn',   type: 'input'  },
      { pin: 16, name: 'VCC',   type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['D0'], outputs: ['Q0'] },
    ],
  },

};