// Chip definitions block 55
// Chips: 74x2970, 74x3004, 74x3037, 74x3038, 74x3040, 74x3125, 74x3126,
//        74x3244, 74CBT3244, 74FST3244, 74x3245, 74CBT3245, 74FST3245,
//        74LVX3245, 74x3251, 74x3253

export const CHIPS_BLOCK_55 = {

  // 74x2970: Memory timing controller for use without EDAC (24-pin)
  '74x2970': {
    name: '74x2970',
    simpleName: 'Memory Timing Controller (without EDAC)',
    description: 'Memory timing controller for use without EDAC (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['memory', 'timing', 'controller', 'stub'],
    pinout: [
      { pin:  1, name: 'A0',   type: 'input'  },
      { pin:  2, name: 'A1',   type: 'input'  },
      { pin:  3, name: 'A2',   type: 'input'  },
      { pin:  4, name: 'A3',   type: 'input'  },
      { pin:  5, name: 'A4',   type: 'input'  },
      { pin:  6, name: 'A5',   type: 'input'  },
      { pin:  7, name: 'A6',   type: 'input'  },
      { pin:  8, name: 'A7',   type: 'input'  },
      { pin:  9, name: 'A8',   type: 'input'  },
      { pin: 10, name: 'A9',   type: 'input'  },
      { pin: 11, name: 'CEn',  type: 'input'  },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'OEn',  type: 'input'  },
      { pin: 14, name: 'WEn',  type: 'input'  },
      { pin: 15, name: 'Y0',   type: 'output' },
      { pin: 16, name: 'Y1',   type: 'output' },
      { pin: 17, name: 'Y2',   type: 'output' },
      { pin: 18, name: 'Y3',   type: 'output' },
      { pin: 19, name: 'Y4',   type: 'output' },
      { pin: 20, name: 'Y5',   type: 'output' },
      { pin: 21, name: 'Y6',   type: 'output' },
      { pin: 22, name: 'Y7',   type: 'output' },
      { pin: 23, name: 'NC',   type: 'nc'     },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['A0','A1','A2','A3','A4','A5','A6','A7','A8','A9','CEn','OEn','WEn'], outputs: [] },
    ],
  },

  // 74x3004: Selectable GTL voltage reference, analog output (6-pin)
  '74x3004': {
    name: '74x3004',
    simpleName: 'Selectable GTL Voltage Reference',
    description: 'Selectable GTL voltage reference, analog output (6-pin)',
    pins: 6, vcc: 6, gnd: 3,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74gtl3004.pdf',
    tags: ['reference', 'GTL', 'analog', 'stub'],
    guideOverview: 'The 74x3004 is not a logic gate at all; it is a small reference voltage generator for GTL-style buses. GTL receivers rely on a stable threshold voltage rather than a full TTL style swing, so a dedicated reference source helps multiple devices agree on where the logic switching point should be. A selectable reference part like this is useful when one board needs to support different GTL threshold requirements without building a custom analog bias circuit.',
    guidePinDescriptions: {
      'VREF1': 'Reference voltage output 1. This pin provides one of the generated threshold voltages used by GTL receivers.',
      'VREF0': 'Reference voltage output 0. Use it as another stable GTL reference output as described in the datasheet.',
      'GND': 'Ground reference for the internal analog circuitry.',
      'VCC': 'Positive supply for the reference generator.',
      'S1': 'Select input 1. Together with S0 it chooses the output-reference setting.',
      'S0': 'Select input 0. Together with S1 it determines which reference level the device generates.',
    },
    guideSections: [
      {
        title: 'Why GTL Needs a Reference',
        paragraphs: [
          'GTL signaling uses lower voltage swing than ordinary TTL. Because the logic high and logic low regions are closer together, the receiving circuitry depends on a well defined reference threshold to decide which state is present.',
          'A dedicated reference IC makes that threshold more stable and repeatable across a whole board than a simple resistor divider would be on its own.',
        ],
      },
      {
        title: 'Selectable Output Levels',
        paragraphs: [
          'The select inputs let the designer choose among preset reference options. That is useful when different GTL families or board conditions call for slightly different threshold voltages.',
        ],
        note: 'This simulator entry is a documented stub. It captures the purpose and pins of the analog reference source, but it does not simulate analog output voltages.',
      },
    ],
    pinout: [
      { pin: 1, name: 'VREF1', type: 'output' },
      { pin: 2, name: 'VREF0', type: 'output' },
      { pin: 3, name: 'GND',   type: 'power'  },
      { pin: 4, name: 'VCC',   type: 'power'  },
      { pin: 5, name: 'S1',    type: 'input'  },
      { pin: 6, name: 'S0',    type: 'input'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['S0','S1'], outputs: [] },
    ],
  },

  // 74x3037: Quad 2 input NAND gate, 30Ω driver (16-pin)
  '74x3037': {
    name: '74x3037',
    simpleName: 'Quad 2 Input NAND Gate (30Ω Driver)',
    description: 'Quad 2 input NAND gate with 30 Ω output driver (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    datasheet: '',
    tags: ['NAND', 'quad', '2 input', 'driver', 'stub'],
    pinout: [
      { pin:  1, name: 'A1',   type: 'input'  },
      { pin:  2, name: 'B1',   type: 'input'  },
      { pin:  3, name: 'Y1',   type: 'output' },
      { pin:  4, name: 'A2',   type: 'input'  },
      { pin:  5, name: 'B2',   type: 'input'  },
      { pin:  6, name: 'Y2',   type: 'output' },
      { pin:  7, name: 'A3',   type: 'input'  },
      { pin:  8, name: 'GND',  type: 'power'  },
      { pin:  9, name: 'B3',   type: 'input'  },
      { pin: 10, name: 'Y3',   type: 'output' },
      { pin: 11, name: 'A4',   type: 'input'  },
      { pin: 12, name: 'B4',   type: 'input'  },
      { pin: 13, name: 'Y4',   type: 'output' },
      { pin: 14, name: 'NC',   type: 'nc'     },
      { pin: 15, name: 'NC2',  type: 'nc'     },
      { pin: 16, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'NAND', inputs: ['A1','B1'], output: 'Y1' },
      { type: 'NAND', inputs: ['A2','B2'], output: 'Y2' },
      { type: 'NAND', inputs: ['A3','B3'], output: 'Y3' },
      { type: 'NAND', inputs: ['A4','B4'], output: 'Y4' },
    ],
  },

  // 74x3038: Quad 2 input NAND gate, open collector 30Ω driver (16-pin)
  '74x3038': {
    name: '74x3038',
    simpleName: 'Quad 2 Input NAND Gate Open Collector (30Ω Driver)',
    description: 'Quad 2 input NAND gate with open collector 30 Ω output driver (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    openCollector: true,
    datasheet: '',
    tags: ['NAND', 'quad', '2 input', 'open collector', 'driver', 'stub'],
    pinout: [
      { pin:  1, name: 'A1',   type: 'input'  },
      { pin:  2, name: 'B1',   type: 'input'  },
      { pin:  3, name: 'Y1',   type: 'output' },
      { pin:  4, name: 'A2',   type: 'input'  },
      { pin:  5, name: 'B2',   type: 'input'  },
      { pin:  6, name: 'Y2',   type: 'output' },
      { pin:  7, name: 'A3',   type: 'input'  },
      { pin:  8, name: 'GND',  type: 'power'  },
      { pin:  9, name: 'B3',   type: 'input'  },
      { pin: 10, name: 'Y3',   type: 'output' },
      { pin: 11, name: 'A4',   type: 'input'  },
      { pin: 12, name: 'B4',   type: 'input'  },
      { pin: 13, name: 'Y4',   type: 'output' },
      { pin: 14, name: 'NC',   type: 'nc'     },
      { pin: 15, name: 'NC2',  type: 'nc'     },
      { pin: 16, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'NAND', inputs: ['A1','B1'], output: 'Y1' },
      { type: 'NAND', inputs: ['A2','B2'], output: 'Y2' },
      { type: 'NAND', inputs: ['A3','B3'], output: 'Y3' },
      { type: 'NAND', inputs: ['A4','B4'], output: 'Y4' },
    ],
  },

  // 74x3040: Dual 4 input NAND gate, 30Ω driver (16-pin)
  '74x3040': {
    name: '74x3040',
    simpleName: 'Dual 4 Input NAND Gate (30Ω Driver)',
    description: 'Dual 4 input NAND gate with 30 Ω output driver (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    datasheet: '',
    tags: ['NAND', 'dual', '4 input', 'driver', 'stub'],
    pinout: [
      { pin:  1, name: 'A1',   type: 'input'  },
      { pin:  2, name: 'B1',   type: 'input'  },
      { pin:  3, name: 'C1',   type: 'input'  },
      { pin:  4, name: 'D1',   type: 'input'  },
      { pin:  5, name: 'Y1',   type: 'output' },
      { pin:  6, name: 'NC',   type: 'nc'     },
      { pin:  7, name: 'NC2',  type: 'nc'     },
      { pin:  8, name: 'GND',  type: 'power'  },
      { pin:  9, name: 'NC3',  type: 'nc'     },
      { pin: 10, name: 'NC4',  type: 'nc'     },
      { pin: 11, name: 'Y2',   type: 'output' },
      { pin: 12, name: 'D2',   type: 'input'  },
      { pin: 13, name: 'C2',   type: 'input'  },
      { pin: 14, name: 'B2',   type: 'input'  },
      { pin: 15, name: 'A2',   type: 'input'  },
      { pin: 16, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'NAND', inputs: ['A1','B1','C1','D1'], output: 'Y1' },
      { type: 'NAND', inputs: ['A2','B2','C2','D2'], output: 'Y2' },
    ],
  },

  // 74x3125: Quad FET bus switch, output enable active low (14-pin)
  '74x3125': {
    name: '74x3125',
    simpleName: 'Quad FET Bus Switch (Active Low OE)',
    description: 'Quad FET bus switch with output enable active low (14-pin)',
    pins: 14, vcc: 14, gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74cbt3125.pdf',
    tags: ['FET', 'bus-switch', 'quad', 'stub'],
    guideOverview: 'The 74x3125 contains four bilateral FET bus switches. Instead of buffering or regenerating logic like a gate does, each channel behaves more like an electronically controlled switch that directly connects two nodes when enabled and isolates them when disabled. That makes the part useful for bus isolation, hot plug style segmentation, or temporarily connecting analog or digital signals without adding a fixed logic direction.',
    guidePinDescriptions: {
      'OE1n': 'Enable control (active LOW) for switch 1. Pull LOW to connect A1 and B1; drive HIGH to open the switch.',
      'A1': 'One side of switch channel 1. It is directly connected to B1 when OE1n is LOW.',
      'B1': 'Other side of switch channel 1. It is isolated from A1 when the channel is disabled.',
      'OE2n': 'Enable control (active LOW) for switch 2.',
      'A2': 'One side of switch channel 2.',
      'B2': 'Other side of switch channel 2.',
      'GND': 'Ground reference for the device.',
      'B3': 'Other side of switch channel 3.',
      'A3': 'One side of switch channel 3.',
      'OE3n': 'Enable control (active LOW) for switch 3.',
      'B4': 'Other side of switch channel 4.',
      'A4': 'One side of switch channel 4.',
      'OE4n': 'Enable control (active LOW) for switch 4.',
      'VCC': 'Positive supply for the switch control circuitry.',
    },
    guideSections: [
      {
        title: 'What a Bus Switch Is',
        paragraphs: [
          'A bus switch is different from a logic buffer. It does not create a new logic level with gain; it simply opens or closes a low resistance path between two pins using FETs.',
          'Because the path is bilateral, signals can usually pass either direction through the same switch channel as long as the voltage levels are within the allowed range.',
        ],
      },
      {
        title: 'Why Use an Active Low Enable',
        paragraphs: [
          'Each OE pin controls one switch channel independently. Active LOW enables are common in bus hardware because a LOW level is often the asserted control state in memory and peripheral logic.',
        ],
        note: 'This simulator entry documents the switch role and pins but does not model the analog on resistance or voltage drop of the FET path.',
      },
    ],
    pinout: [
      { pin:  1, name: 'OE1n', type: 'input'  },
      { pin:  2, name: 'A1',   type: 'bidir'  },
      { pin:  3, name: 'B1',   type: 'bidir'  },
      { pin:  4, name: 'OE2n', type: 'input'  },
      { pin:  5, name: 'A2',   type: 'bidir'  },
      { pin:  6, name: 'B2',   type: 'bidir'  },
      { pin:  7, name: 'GND',  type: 'power'  },
      { pin:  8, name: 'B3',   type: 'bidir'  },
      { pin:  9, name: 'A3',   type: 'bidir'  },
      { pin: 10, name: 'OE3n', type: 'input'  },
      { pin: 11, name: 'B4',   type: 'bidir'  },
      { pin: 12, name: 'A4',   type: 'bidir'  },
      { pin: 13, name: 'OE4n', type: 'input'  },
      { pin: 14, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OE1n','OE2n','OE3n','OE4n'], outputs: [] },
    ],
  },

  // 74x3126: Quad FET bus switch, output enable active high (14-pin)
  '74x3126': {
    name: '74x3126',
    simpleName: 'Quad FET Bus Switch (Active High OE)',
    description: 'Quad FET bus switch with output enable active high (14-pin)',
    pins: 14, vcc: 14, gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74cbt3126.pdf',
    tags: ['FET', 'bus-switch', 'quad', 'stub'],
    guideOverview: 'The 74x3126 is the active HIGH control companion to the 74x3125. It provides four bilateral FET switch channels that can connect or isolate paired signal nodes with very little logic overhead. Designers use parts like this to partition buses, multiplex raw signal lines, or make temporary point to point connections without the direction assumptions built into a normal transceiver.',
    guidePinDescriptions: {
      'OE1': 'Enable control (active HIGH) for switch 1. Drive HIGH to connect A1 and B1; drive LOW to open the switch.',
      'A1': 'One side of switch channel 1.',
      'B1': 'Other side of switch channel 1.',
      'OE2': 'Enable control (active HIGH) for switch 2.',
      'A2': 'One side of switch channel 2.',
      'B2': 'Other side of switch channel 2.',
      'GND': 'Ground reference for the package.',
      'B3': 'Other side of switch channel 3.',
      'A3': 'One side of switch channel 3.',
      'OE3': 'Enable control (active HIGH) for switch 3.',
      'B4': 'Other side of switch channel 4.',
      'A4': 'One side of switch channel 4.',
      'OE4': 'Enable control (active HIGH) for switch 4.',
      'VCC': 'Positive supply for the control circuitry.',
    },
    guideSections: [
      {
        title: 'Bilateral Signal Path',
        paragraphs: [
          'Each enabled channel behaves like an electronically controlled connection rather than a conventional logic gate. That means the signal can pass in whichever direction the surrounding circuit naturally drives it.',
        ],
      },
      {
        title: 'Active High Control',
        paragraphs: [
          'The only major difference from the 74x3125 is the control polarity. This version turns on when the OE pin is HIGH, which can simplify interface logic in systems where the asserted control state is active HIGH.',
        ],
        note: 'As with the 74x3125, the simulator keeps this as a documented stub and does not model analog FET resistance in detail.',
      },
    ],
    pinout: [
      { pin:  1, name: 'OE1',  type: 'input'  },
      { pin:  2, name: 'A1',   type: 'bidir'  },
      { pin:  3, name: 'B1',   type: 'bidir'  },
      { pin:  4, name: 'OE2',  type: 'input'  },
      { pin:  5, name: 'A2',   type: 'bidir'  },
      { pin:  6, name: 'B2',   type: 'bidir'  },
      { pin:  7, name: 'GND',  type: 'power'  },
      { pin:  8, name: 'B3',   type: 'bidir'  },
      { pin:  9, name: 'A3',   type: 'bidir'  },
      { pin: 10, name: 'OE3',  type: 'input'  },
      { pin: 11, name: 'B4',   type: 'bidir'  },
      { pin: 12, name: 'A4',   type: 'bidir'  },
      { pin: 13, name: 'OE4',  type: 'input'  },
      { pin: 14, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OE1','OE2','OE3','OE4'], outputs: [] },
    ],
  },

  // 74x3244: Dual 4 bit buffer / line driver, TRI (20-pin)
  '74x3244': {
    name: '74x3244',
    simpleName: 'Dual 4 bit Buffer / Line Driver',
    description: 'Dual 4 bit buffer / line driver, TRI STATE (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: '',
    tags: ['buffer', 'dual', '4 bit', 'tri state', 'stub'],
    pinout: [
      { pin:  1, name: 'OE1n', type: 'input'  },
      { pin:  2, name: 'A11',  type: 'input'  },
      { pin:  3, name: 'A12',  type: 'input'  },
      { pin:  4, name: 'A13',  type: 'input'  },
      { pin:  5, name: 'A14',  type: 'input'  },
      { pin:  6, name: 'Y14',  type: 'output' },
      { pin:  7, name: 'Y13',  type: 'output' },
      { pin:  8, name: 'Y12',  type: 'output' },
      { pin:  9, name: 'Y11',  type: 'output' },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'Y21',  type: 'output' },
      { pin: 12, name: 'Y22',  type: 'output' },
      { pin: 13, name: 'Y23',  type: 'output' },
      { pin: 14, name: 'Y24',  type: 'output' },
      { pin: 15, name: 'A24',  type: 'input'  },
      { pin: 16, name: 'A23',  type: 'input'  },
      { pin: 17, name: 'A22',  type: 'input'  },
      { pin: 18, name: 'A21',  type: 'input'  },
      { pin: 19, name: 'OE2n', type: 'input'  },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OE1n','A11','A12','A13','A14','OE2n','A21','A22','A23','A24'], outputs: [] },
    ],
  },



  // 74x3245: Octal bidirectional transceiver, TRI (20-pin)
  '74x3245': {
    name: '74x3245',
    simpleName: 'Octal Bidirectional Transceiver',
    description: 'Octal bidirectional transceiver, TRI STATE (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: '',
    tags: ['transceiver', 'octal', 'bidir', 'tri state'],
    pinout: [
      { pin:  1, name: 'OEn',  type: 'input'  },
      { pin:  2, name: 'DIR',  type: 'input'  },
      { pin:  3, name: 'A1',   type: 'bidir'  },
      { pin:  4, name: 'A2',   type: 'bidir'  },
      { pin:  5, name: 'A3',   type: 'bidir'  },
      { pin:  6, name: 'A4',   type: 'bidir'  },
      { pin:  7, name: 'A5',   type: 'bidir'  },
      { pin:  8, name: 'A6',   type: 'bidir'  },
      { pin:  9, name: 'A7',   type: 'bidir'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'A8',   type: 'bidir'  },
      { pin: 12, name: 'B8',   type: 'bidir'  },
      { pin: 13, name: 'B7',   type: 'bidir'  },
      { pin: 14, name: 'B6',   type: 'bidir'  },
      { pin: 15, name: 'B5',   type: 'bidir'  },
      { pin: 16, name: 'B4',   type: 'bidir'  },
      { pin: 17, name: 'B3',   type: 'bidir'  },
      { pin: 18, name: 'B2',   type: 'bidir'  },
      { pin: 19, name: 'B1',   type: 'bidir'  },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'TRANSCEIVER_8BIT',
        inputs:  ['A1','A2','A3','A4','A5','A6','A7','A8',
                  'B1','B2','B3','B4','B5','B6','B7','B8','DIR','OEn'],
        outputs: ['A1','A2','A3','A4','A5','A6','A7','A8',
                  'B1','B2','B3','B4','B5','B6','B7','B8'] },
    ],
  },



  // 74LVX3245: Octal bidirectional voltage-translating transceiver, TRI (24-pin)
  '74LVX3245': {
    name: '74x3245',
    simpleName: 'Octal Bidirectional Voltage-Translating Transceiver',
    description: 'Octal bidirectional voltage-translating transceiver, TRI STATE (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['transceiver', 'octal', 'voltage-translator', 'bidir', 'tri state', 'stub'],
    pinout: [
      { pin:  1, name: 'OEn',  type: 'input'  },
      { pin:  2, name: 'DIR',  type: 'input'  },
      { pin:  3, name: 'A1',   type: 'bidir'  },
      { pin:  4, name: 'A2',   type: 'bidir'  },
      { pin:  5, name: 'A3',   type: 'bidir'  },
      { pin:  6, name: 'A4',   type: 'bidir'  },
      { pin:  7, name: 'A5',   type: 'bidir'  },
      { pin:  8, name: 'A6',   type: 'bidir'  },
      { pin:  9, name: 'A7',   type: 'bidir'  },
      { pin: 10, name: 'A8',   type: 'bidir'  },
      { pin: 11, name: 'VCCA', type: 'power'  },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'VCCB', type: 'power'  },
      { pin: 14, name: 'B8',   type: 'bidir'  },
      { pin: 15, name: 'B7',   type: 'bidir'  },
      { pin: 16, name: 'B6',   type: 'bidir'  },
      { pin: 17, name: 'B5',   type: 'bidir'  },
      { pin: 18, name: 'B4',   type: 'bidir'  },
      { pin: 19, name: 'B3',   type: 'bidir'  },
      { pin: 20, name: 'B2',   type: 'bidir'  },
      { pin: 21, name: 'B1',   type: 'bidir'  },
      { pin: 22, name: 'NC',   type: 'nc'     },
      { pin: 23, name: 'NC2',  type: 'nc'     },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','DIR'], outputs: [] },
    ],
  },

  // 74x3251: 8 line to 1 line FET multiplexer / demultiplexer (16-pin)
  '74x3251': {
    name: '74x3251',
    simpleName: '8-to-1 FET Multiplexer / Demultiplexer',
    description: '8 line to 1 line FET multiplexer / demultiplexer (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74cbt3251.pdf',
    tags: ['FET', 'mux', 'demux', '8:1', 'bidir', 'stub'],
    guideOverview: 'The 74x3251 is an 8-channel FET switch arranged as an 8-to-1 multiplexer or 1-to-8 demultiplexer. Because the switch path is bilateral, the same hardware can route one common node to any selected channel or let one selected channel reach the common node without imposing a fixed signal direction. Parts like this are useful when you need to steer digital or moderately analog signals through one of several paths with low added logic complexity.',
    guidePinDescriptions: {
      'S0': 'Select input bit 0. Together with S1 and S2 it chooses which channel is connected to Z.',
      'S1': 'Select input bit 1. It forms the middle bit of the channel address.',
      'S2': 'Select input bit 2. It is the most significant select bit for channel choice.',
      'I0': 'Channel 0 switch node. It connects to Z when the select inputs choose channel 0 and the part is enabled.',
      'I1': 'Channel 1 switch node.',
      'I2': 'Channel 2 switch node.',
      'I3': 'Channel 3 switch node.',
      'GND': 'Ground reference for the device.',
      'I4': 'Channel 4 switch node.',
      'I5': 'Channel 5 switch node.',
      'I6': 'Channel 6 switch node.',
      'I7': 'Channel 7 switch node.',
      'OEn': 'Output enable (active LOW). Pull LOW to enable the switch matrix; drive HIGH to isolate all channels from Z.',
      'Z': 'Common switch node. It is connected to exactly one selected I-channel when enabled.',
      'NC': 'No internal connection. Leave this pin unconnected.',
      'VCC': 'Positive supply for the control logic.',
    },
    guideSections: [
      {
        title: 'Multiplexer and Demultiplexer View',
        paragraphs: [
          'If you think of Z as the output, the part behaves like an 8-to-1 multiplexer that routes one of the I inputs to Z. If you think of Z as the input, the same hardware behaves like a 1-to-8 demultiplexer that connects Z to one selected channel.',
        ],
      },
      {
        title: 'Why Use FET Switching',
        paragraphs: [
          'A FET switch path is useful when you want a low resistance connection instead of a logic buffer with fixed direction and full regeneration. That makes devices like the 74x3251 flexible for signal steering, especially when the surrounding circuit may drive from either side.',
        ],
        note: 'This simulator entry documents the routing concept and pins, but it does not model detailed analog switch resistance or charge injection.',
      },
    ],
    pinout: [
      { pin:  1, name: 'S0',   type: 'input'  },
      { pin:  2, name: 'S1',   type: 'input'  },
      { pin:  3, name: 'S2',   type: 'input'  },
      { pin:  4, name: 'I0',   type: 'bidir'  },
      { pin:  5, name: 'I1',   type: 'bidir'  },
      { pin:  6, name: 'I2',   type: 'bidir'  },
      { pin:  7, name: 'I3',   type: 'bidir'  },
      { pin:  8, name: 'GND',  type: 'power'  },
      { pin:  9, name: 'I4',   type: 'bidir'  },
      { pin: 10, name: 'I5',   type: 'bidir'  },
      { pin: 11, name: 'I6',   type: 'bidir'  },
      { pin: 12, name: 'I7',   type: 'bidir'  },
      { pin: 13, name: 'OEn',  type: 'input'  },
      { pin: 14, name: 'Z',    type: 'bidir'  },
      { pin: 15, name: 'NC',   type: 'nc'     },
      { pin: 16, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['S0','S1','S2','OEn'], outputs: [] },
    ],
  },

  // 74x3253: Dual 4 line to 1 line FET multiplexer / demultiplexer (16-pin)
  '74x3253': {
    name: '74x3253',
    simpleName: 'Dual 4-to-1 FET Multiplexer / Demultiplexer',
    description: 'Dual 4 line to 1 line FET multiplexer / demultiplexer (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74cbt3253.pdf',
    tags: ['FET', 'mux', 'demux', '4:1', 'dual', 'bidir', 'stub'],
    guideOverview: 'The 74x3253 splits the FET switch multiplexer idea into two independent 4-channel sections. Both sections share the same two select inputs, but each has its own enable pin and common node, making the part useful for steering paired signals such as two bits of data, two audio/control paths, or two related bus lines together. Because the channels are bilateral FET switches, the part works as either a multiplexer or a demultiplexer depending on which side of the path is being driven.',
    guidePinDescriptions: {
      'S0': 'Select input bit 0. Together with S1 it chooses which channel in each section is connected.',
      'S1': 'Select input bit 1. It completes the 2 bit address for both switch sections.',
      'A10': 'Channel 0 of section 1. It connects to Z1 when selected and enabled.',
      'A11': 'Channel 1 of section 1.',
      'A12': 'Channel 2 of section 1.',
      'A13': 'Channel 3 of section 1.',
      'Z1': 'Common node for section 1. It is connected to one selected A1x channel when OE1n is active.',
      'GND': 'Ground reference for the device.',
      'Z2': 'Common node for section 2. It is connected to one selected A2x channel when OE2n is active.',
      'A23': 'Channel 3 of section 2.',
      'A22': 'Channel 2 of section 2.',
      'A21': 'Channel 1 of section 2.',
      'A20': 'Channel 0 of section 2.',
      'OE2n': 'Enable for section 2 (active LOW). Pull LOW to connect Z2 to the selected channel.',
      'OE1n': 'Enable for section 1 (active LOW). Pull LOW to connect Z1 to the selected channel.',
      'VCC': 'Positive supply for the switch control circuitry.',
    },
    guideSections: [
      {
        title: 'Two Switch Trees in One Package',
        paragraphs: [
          'The two sections share the same select inputs, so both common nodes choose corresponding channel numbers at the same time. That is useful when two related signals should be steered in parallel under one control word.',
        ],
      },
      {
        title: 'Bilateral Routing',
        paragraphs: [
          'As with other CBT style switch parts, each path is bilateral. The selected channel and common node are simply connected through a FET switch, so the effective direction depends on which side is actively driving.',
        ],
        note: 'This entry remains a documented stub in the simulator and does not model the analog resistance of the switch path in detail.',
      },
    ],
    pinout: [
      { pin:  1, name: 'S0',   type: 'input'  },
      { pin:  2, name: 'S1',   type: 'input'  },
      { pin:  3, name: 'A10',  type: 'bidir'  },
      { pin:  4, name: 'A11',  type: 'bidir'  },
      { pin:  5, name: 'A12',  type: 'bidir'  },
      { pin:  6, name: 'A13',  type: 'bidir'  },
      { pin:  7, name: 'Z1',   type: 'bidir'  },
      { pin:  8, name: 'GND',  type: 'power'  },
      { pin:  9, name: 'Z2',   type: 'bidir'  },
      { pin: 10, name: 'A23',  type: 'bidir'  },
      { pin: 11, name: 'A22',  type: 'bidir'  },
      { pin: 12, name: 'A21',  type: 'bidir'  },
      { pin: 13, name: 'A20',  type: 'bidir'  },
      { pin: 14, name: 'OE2n', type: 'input'  },
      { pin: 15, name: 'OE1n', type: 'input'  },
      { pin: 16, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['S0','S1','OE1n','OE2n'], outputs: [] },
    ],
  },
};
