// Chip definitions block 5
// Auto-generated from chips.js

export const CHIPS_BLOCK_5 = {
  // ── 74148: 8-to-3 Priority Encoder ─────────────────────────────────────
  /* Primary source: Texas Instruments, SN74LS148 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls148.pdf
     Priority encoder concept: https://en.wikipedia.org/wiki/Priority_encoder */
  '74148': {
    name: '74x148',
    simpleName: '8-to-3 Encoder',
    description: '8-to-3 priority encoder (16-pin)',
    guideOverview: 'The 74x148 is an 8-to-3 priority encoder. When multiple inputs are LOW simultaneously, it encodes the highest-numbered active input (I7 has highest priority). An active LOW Enable Input (EI#) enables or disables the device. Enable Output (EO#) and Group Select (GS#) outputs allow daisy-chaining of multiple 74x148s to create wider encoders. All inputs and outputs are active LOW.',
    guidePinDescriptions: {
      'I4':  'Data input 4, active LOW. Priority 4 (lower than I5 I7).',
      'I5':  'Data input 5, active LOW. Priority 5.',
      'I6':  'Data input 6, active LOW. Priority 6.',
      'I7':  'Data input 7, active LOW. Highest priority input.',
      'EI':  'Enable Input, active LOW. Pull LOW to enable the device. HIGH disables all outputs.',
      'A2':  'Address output bit 2 (MSB), active LOW. Together with A1 and A0, encodes the highest-priority active input.',
      'A1':  'Address output bit 1, active LOW.',
      'GND': 'Ground reference (pin 8).',
      'A0':  'Address output bit 0 (LSB), active LOW.',
      'I0':  'Data input 0, active LOW. Lowest priority.',
      'I1':  'Data input 1, active LOW.',
      'I2':  'Data input 2, active LOW.',
      'I3':  'Data input 3, active LOW.',
      'GS':  'Group Select output, active LOW. Goes LOW when any input is asserted (and EI#=LOW). Indicates a valid code is on A0 A2.',
      'EO':  'Enable Output, active LOW. Goes LOW when no inputs are asserted and EI#=LOW. Used to cascade to the next lower-priority 74x148.',
      'VCC': 'Positive supply (+5 V) at pin 16.',
    },
    guideSections: [
      {
        title: '8-to-3 Priority Encoding',
        paragraphs: [
          'An encoder converts one-of-N active input lines into a binary code. A priority encoder resolves conflicts when multiple inputs are active simultaneously by encoding the highest-priority (highest-numbered) input.',
          'Connect the 8 active LOW input lines to I0 I7. Pull EI# LOW to enable. Read the 3 bit active LOW result from A2, A1, A0. GS# going LOW confirms that at least one input is active.',
        ],
        list: [
          'EO# to EI# chain: connect EO# of a higher-priority 74x148 to EI# of the next for 16 input encoding.',
          'To read a HIGH-active result, invert the A0 A2 outputs.',
        ],
      },
    ],
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls148.pdf',
    tags: ['encoder', 'priority', '8-to-3', 'logic'],
    pinout: [
      { pin: 1,  name: 'I4',  displayName: 'I\u03054\u0305', type: 'input' },
      { pin: 2,  name: 'I5',  displayName: 'I\u03055\u0305', type: 'input' },
      { pin: 3,  name: 'I6',  displayName: 'I\u03056\u0305', type: 'input' },
      { pin: 4,  name: 'I7',  displayName: 'I\u03057\u0305', type: 'input' },
      { pin: 5,  name: 'EI',  displayName: 'E\u0305I\u0305', type: 'input' },
      { pin: 6,  name: 'A2',  type: 'output' },
      { pin: 7,  name: 'A1',  type: 'output' },
      { pin: 8,  name: 'GND', type: 'power' },
      { pin: 9,  name: 'A0',  type: 'output' },
      { pin: 10, name: 'I0',  displayName: 'I\u03050\u0305', type: 'input' },
      { pin: 11, name: 'I1',  displayName: 'I\u03051\u0305', type: 'input' },
      { pin: 12, name: 'I2',  displayName: 'I\u03052\u0305', type: 'input' },
      { pin: 13, name: 'I3',  displayName: 'I\u03053\u0305', type: 'input' },
      { pin: 14, name: 'GS',  type: 'output' },
      { pin: 15, name: 'EO',  type: 'output' },
      { pin: 16, name: 'VCC', type: 'power' },
    ],
    gates: [
      {
        type: 'PRIORITY_ENC_8TO3',
        inputs: ['I0', 'I1', 'I2', 'I3', 'I4', 'I5', 'I6', 'I7', 'EI'],
        outputs: ['A0', 'A1', 'A2', 'GS', 'EO'],
      },
    ],
  },

  // ── 74150: 16-to-1 Multiplexer ─────────────────────────────────────────
  /* Primary source: Texas Instruments, SN74150 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74150.pdf
     Multiplexer concept: https://en.wikipedia.org/wiki/Multiplexer */
  '74150': {
    name: '74x150',
    simpleName: '16-to-1 Mux',
    description: '16-to-1 data selector/multiplexer (24-pin)',
    guideOverview: 'The 74x150 is a 16-to-1 multiplexer. Four address inputs (A=LSB, B, C, D=MSB) select one of 16 data inputs (E0 E15). The output W is the complement (inverted) of the selected input. An active LOW enable input G# must be LOW for valid output; HIGH forces W HIGH regardless of input.',
    guidePinDescriptions: {
      'E7':  'Data input 7.',
      'E6':  'Data input 6.',
      'E5':  'Data input 5.',
      'E4':  'Data input 4.',
      'E3':  'Data input 3.',
      'E2':  'Data input 2.',
      'E1':  'Data input 1.',
      'E0':  'Data input 0.',
      'G':   'Enable input, active LOW. Pull LOW to enable output. HIGH forces W HIGH.',
      'W':   'Output (inverted): W = NOT(selected input) when enabled.',
      'D':   'Address bit 3 (MSB). Selects upper or lower half of 16 inputs.',
      'GND': 'Ground reference (pin 12).',
      'C':   'Address bit 2.',
      'B':   'Address bit 1.',
      'A':   'Address bit 0 (LSB).',
      'E15': 'Data input 15.',
      'E14': 'Data input 14.',
      'E13': 'Data input 13.',
      'E12': 'Data input 12.',
      'E11': 'Data input 11.',
      'E10': 'Data input 10.',
      'E9':  'Data input 9.',
      'E8':  'Data input 8.',
      'VCC': 'Positive supply (+5 V) at pin 24.',
    },
    guideSections: [
      {
        title: '16-to-1 Multiplexer',
        paragraphs: ['The 4 bit address DCBA (0 15) selects which of the 16 inputs E0 E15 reaches the output W. The output is inverted: W = NOT(E_selected). Pull G# LOW for normal operation.'],
        note: 'Output is inverted. If you need the true (non-inverted) signal, add an inverter after W.',
      },
    ],
    pins: 24,
    vcc: 24,
    gnd: 12,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74150.pdf',
    tags: ['multiplexer', 'mux', '16-to-1', 'data selector'],
    pinout: [
      { pin: 1, name: 'E7', type: 'input' },
      { pin: 2, name: 'E6', type: 'input' },
      { pin: 3, name: 'E5', type: 'input' },
      { pin: 4, name: 'E4', type: 'input' },
      { pin: 5, name: 'E3', type: 'input' },
      { pin: 6, name: 'E2', type: 'input' },
      { pin: 7, name: 'E1', type: 'input' },
      { pin: 8, name: 'E0', type: 'input' },
      { pin: 9, name: 'G', type: 'input' },
      { pin: 10, name: 'W', type: 'output' },
      { pin: 11, name: 'D', type: 'input' },
      { pin: 12, name: 'GND', type: 'power' },
      { pin: 13, name: 'C', type: 'input' },
      { pin: 14, name: 'B', type: 'input' },
      { pin: 15, name: 'A', type: 'input' },
      { pin: 16, name: 'E15', type: 'input' },
      { pin: 17, name: 'E14', type: 'input' },
      { pin: 18, name: 'E13', type: 'input' },
      { pin: 19, name: 'E12', type: 'input' },
      { pin: 20, name: 'E11', type: 'input' },
      { pin: 21, name: 'E10', type: 'input' },
      { pin: 22, name: 'E9', type: 'input' },
      { pin: 23, name: 'E8', type: 'input' },
      { pin: 24, name: 'VCC', type: 'power' },
    ],
    gates: [
      {
        type: 'MUX_16TO1',
        inputs: ['E0','E1','E2','E3','E4','E5','E6','E7','E8','E9','E10','E11','E12','E13','E14','E15','A','B','C','D','G'],
        outputs: ['W'],
      },
    ],
  },

  // ── 74151: 8-to-1 Multiplexer ──────────────────────────────────────────
  /* Primary source: Texas Instruments, SN74LS151 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls151.pdf
     Multiplexer concept: https://en.wikipedia.org/wiki/Multiplexer */
  '74151': {
    name: '74x151',
    simpleName: '8-to-1 Multiplexer',
    description: '8-to-1 data selector/multiplexer. (16-pin)',
    guideOverview: 'The 74x151 is an 8-to-1 multiplexer with complementary outputs. Three address bits (A=LSB, B, C=MSB) select one of eight data inputs (D0 D7). The Y output is the true (non-inverted) selected input; W is the complement. An active LOW enable G# forces Y=0 and W=1 when HIGH.',
    guidePinDescriptions: {
      'D3':  'Data input 3.',
      'D2':  'Data input 2.',
      'D1':  'Data input 1.',
      'D0':  'Data input 0.',
      'Y':   'True (non-inverted) output. Equals selected input when G#=LOW.',
      'W':   'Inverted output. W = NOT(Y).',
      'G':   'Enable, active LOW. HIGH forces Y=0, W=1.',
      'GND': 'Ground reference (pin 8).',
      'C':   'Address bit 2 (MSB).',
      'B':   'Address bit 1.',
      'A':   'Address bit 0 (LSB).',
      'D7':  'Data input 7.',
      'D6':  'Data input 6.',
      'D5':  'Data input 5.',
      'D4':  'Data input 4.',
      'VCC': 'Positive supply (+5 V) at pin 16.',
    },
    guideSections: [
      {
        title: '8-to-1 Multiplexing',
        paragraphs: ['The 3 bit address CBA selects which input D0 D7 passes to Y. Complementary outputs Y and W are always available simultaneously.'],
        list: ['Set G# LOW for normal operation.', 'Use this chip to implement any 3-variable Boolean function by treating address bits as the truth-table address.'],
      },
    ],
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls151.pdf',
    tags: ['multiplexer', 'mux', '8-to-1', 'data selector', 'complementary output'],
    pinout: [
      { pin: 1,  name: 'D3',  type: 'input',  description: 'Data input 3' },
      { pin: 2,  name: 'D2',  type: 'input',  description: 'Data input 2' },
      { pin: 3,  name: 'D1',  type: 'input',  description: 'Data input 1' },
      { pin: 4,  name: 'D0',  type: 'input',  description: 'Data input 0' },
      { pin: 5,  name: 'Y',   type: 'output', description: 'True output equals selected data input when enabled' },
      { pin: 6,  name: 'W',   type: 'output', description: 'Complementary output W = NOT(Y)' },
      { pin: 7,  name: 'G',   type: 'input',  description: 'Enable (active LOW); HIGH forces Y=0, W=1' },
      { pin: 8,  name: 'GND', type: 'power',  description: 'Ground (0V)' },
      { pin: 9,  name: 'C',   type: 'input',  description: 'Address select bit 2 (MSB)' },
      { pin: 10, name: 'B',   type: 'input',  description: 'Address select bit 1' },
      { pin: 11, name: 'A',   type: 'input',  description: 'Address select bit 0 (LSB)' },
      { pin: 12, name: 'D7',  type: 'input',  description: 'Data input 7' },
      { pin: 13, name: 'D6',  type: 'input',  description: 'Data input 6' },
      { pin: 14, name: 'D5',  type: 'input',  description: 'Data input 5' },
      { pin: 15, name: 'D4',  type: 'input',  description: 'Data input 4' },
      { pin: 16, name: 'VCC', type: 'power',  description: 'Positive supply (+5V)' },
    ],
    gates: [
      {
        type: 'MUX_8TO1',
        inputs: ['D0', 'D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'A', 'B', 'C', 'G'],
        outputs: ['Y', 'W'],
      },
    ],
  },

  // ── 74153: Dual 4-to-1 Multiplexer ─────────────────────────────────────
  /* Primary source: Texas Instruments, SN74LS153 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls153.pdf
     Multiplexer concept: https://en.wikipedia.org/wiki/Multiplexer */
  '74153': {
    name: '74x153',
    simpleName: 'Dual 4-to-1 Mux',
    description: 'Dual 4-to-1 data selector/multiplexer (16-pin)',
    guideOverview: 'The 74x153 is a dual 4-to-1 multiplexer. Both sections share the same two address inputs (A and B) but have independent data inputs and independent active LOW enables (1G# and 2G#). Each section routes one of four data inputs to its output based on the AB address. A key use is implementing any 2-variable Boolean function on each section.',
    guidePinDescriptions: {
      '1G':  'Enable for section 1, active LOW. HIGH forces 1Y=LOW regardless of inputs.',
      'B':   'Address bit 1 (MSB), shared by both sections.',
      '1C3': 'Data input 3 of section 1. Selected when A=1, B=1.',
      '1C2': 'Data input 2 of section 1. Selected when A=0, B=1.',
      '1C1': 'Data input 1 of section 1. Selected when A=1, B=0.',
      '1C0': 'Data input 0 of section 1. Selected when A=0, B=0.',
      '1Y':  'Output of section 1. Reflects selected input when 1G#=LOW.',
      'GND': 'Ground reference (pin 8).',
      '2Y':  'Output of section 2.',
      '2C0': 'Data input 0 of section 2.',
      '2C1': 'Data input 1 of section 2.',
      '2C2': 'Data input 2 of section 2.',
      '2C3': 'Data input 3 of section 2.',
      'A':   'Address bit 0 (LSB), shared by both sections.',
      '2G':  'Enable for section 2, active LOW.',
      'VCC': 'Positive supply (+5 V) at pin 16.',
    },
    guideSections: [
      {
        title: 'Dual 4-to-1 Multiplexer',
        paragraphs: [
          'Both sections of the 74x153 share address lines A and B. This means when you change the address, BOTH sections switch simultaneously to a new input. This is useful for selecting between two 2 bit data buses at once.',
          'Each section can also implement any 2 input Boolean function by connecting constants (0 or 1) or input variables to the data pins.',
        ],
        formulas: ['A=0,B=0 → C0', 'A=1,B=0 → C1', 'A=0,B=1 → C2', 'A=1,B=1 → C3'],
      },
    ],
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls153.pdf',
    tags: ['multiplexer', 'mux', '4-to-1', 'data selector', 'dual'],
    pinout: [
      { pin: 1, name: '1G', type: 'input' },
      { pin: 2, name: 'B', type: 'input' },
      { pin: 3, name: '1C3', type: 'input' },
      { pin: 4, name: '1C2', type: 'input' },
      { pin: 5, name: '1C1', type: 'input' },
      { pin: 6, name: '1C0', type: 'input' },
      { pin: 7, name: '1Y', type: 'output' },
      { pin: 8, name: 'GND', type: 'power' },
      { pin: 9, name: '2Y', type: 'output' },
      { pin: 10, name: '2C0', type: 'input' },
      { pin: 11, name: '2C1', type: 'input' },
      { pin: 12, name: '2C2', type: 'input' },
      { pin: 13, name: '2C3', type: 'input' },
      { pin: 14, name: 'A', type: 'input' },
      { pin: 15, name: '2G', type: 'input' },
      { pin: 16, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'MUX_4TO1', inputs: ['1C0', '1C1', '1C2', '1C3', 'A', 'B', '1G'], output: '1Y' },
      { type: 'MUX_4TO1', inputs: ['2C0', '2C1', '2C2', '2C3', 'A', 'B', '2G'], output: '2Y' },
    ],
  },

  // ── 74154: 4-to-16 Decoder / Demultiplexer ─────────────────────────────
  /* Primary source: Texas Instruments, SN74LS154 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls154.pdf
     Decoder/demultiplexer concept: https://en.wikipedia.org/wiki/Multiplexer */
  '74154': {
    name: '74x154',
    simpleName: '4-to-16 Decoder',
    description: '4-to-16 decoder / demultiplexer (24-pin)',
    guideOverview: 'The 74x154 is a 4-to-16 line decoder/demultiplexer. Four address inputs (A=LSB to D=MSB) select one of 16 active LOW outputs (Y0 Y15). Two active LOW enable inputs (G1# and G2#) must both be LOW for the selected output to activate. Used extensively for memory address decoding and 16-device bus selection.',
    guidePinDescriptions: {
      'Y0':  'Active LOW output for address 0000.',
      'Y1':  'Active LOW output for address 0001.',
      'Y2':  'Active LOW output for address 0010.',
      'Y3':  'Active LOW output for address 0011.',
      'Y4':  'Active LOW output for address 0100.',
      'Y5':  'Active LOW output for address 0101.',
      'Y6':  'Active LOW output for address 0110.',
      'Y7':  'Active LOW output for address 0111.',
      'Y8':  'Active LOW output for address 1000.',
      'Y9':  'Active LOW output for address 1001.',
      'Y10': 'Active LOW output for address 1010.',
      'GND': 'Ground reference (pin 12).',
      'Y11': 'Active LOW output for address 1011.',
      'Y12': 'Active LOW output for address 1100.',
      'Y13': 'Active LOW output for address 1101.',
      'Y14': 'Active LOW output for address 1110.',
      'Y15': 'Active LOW output for address 1111.',
      'G1':  'Enable 1, active LOW. Must be LOW (with G2#) for any output to be active.',
      'G2':  'Enable 2, active LOW. Must be LOW (with G1#) for any output to be active.',
      'D':   'Address bit 3 (MSB).',
      'C':   'Address bit 2.',
      'B':   'Address bit 1.',
      'A':   'Address bit 0 (LSB).',
      'VCC': 'Positive supply (+5 V) at pin 24.',
    },
    guideSections: [
      {
        title: '4-to-16 Decoding',
        paragraphs: ['The 4 bit address DCBA selects one output LOW. Both G1# and G2# must be LOW simultaneously. When disabled, all outputs are HIGH. Use G1# and G2# for chip-select or banked-decoding logic.'],
      },
    ],
    pins: 24,
    vcc: 24,
    gnd: 12,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls154.pdf',
    tags: ['decoder', 'demultiplexer', 'demux', '4-to-16'],
    pinout: [
      { pin: 1, name: 'Y0', type: 'output' },
      { pin: 2, name: 'Y1', type: 'output' },
      { pin: 3, name: 'Y2', type: 'output' },
      { pin: 4, name: 'Y3', type: 'output' },
      { pin: 5, name: 'Y4', type: 'output' },
      { pin: 6, name: 'Y5', type: 'output' },
      { pin: 7, name: 'Y6', type: 'output' },
      { pin: 8, name: 'Y7', type: 'output' },
      { pin: 9, name: 'Y8', type: 'output' },
      { pin: 10, name: 'Y9', type: 'output' },
      { pin: 11, name: 'Y10', type: 'output' },
      { pin: 12, name: 'GND', type: 'power' },
      { pin: 13, name: 'Y11', type: 'output' },
      { pin: 14, name: 'Y12', type: 'output' },
      { pin: 15, name: 'Y13', type: 'output' },
      { pin: 16, name: 'Y14', type: 'output' },
      { pin: 17, name: 'Y15', type: 'output' },
      { pin: 18, name: 'G1', type: 'input' },
      { pin: 19, name: 'G2', type: 'input' },
      { pin: 20, name: 'D', type: 'input' },
      { pin: 21, name: 'C', type: 'input' },
      { pin: 22, name: 'B', type: 'input' },
      { pin: 23, name: 'A', type: 'input' },
      { pin: 24, name: 'VCC', type: 'power' },
    ],
    gates: [
      {
        type: 'DECODER_4TO16',
        inputs: ['A', 'B', 'C', 'D', 'G1', 'G2'],
        outputs: ['Y0','Y1','Y2','Y3','Y4','Y5','Y6','Y7','Y8','Y9','Y10','Y11','Y12','Y13','Y14','Y15'],
      },
    ],
  },

  // ── 74157: Quad 2-to-1 Multiplexer ─────────────────────────────────────
  /* Primary source: Texas Instruments, SN74LS157 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls157.pdf
     Multiplexer concept: https://en.wikipedia.org/wiki/Multiplexer */
  '74157': {
    name: '74x157',
    simpleName: 'Quad 2-to-1 Multiplexer',
    description: 'Quad 2-to-1 non-inverting data selector/multiplexer. (16-pin)',
    guideOverview: 'The 74x157 contains four independent 2-to-1 non-inverting multiplexers that all share a common select input (S) and a common active LOW enable (En#). When S=0, all four outputs follow the A inputs. When S=1, all four outputs follow the B inputs. When En# is HIGH, all outputs go LOW. It is commonly used for source selection across a 4 bit data bus.',
    guidePinDescriptions: {
      'S':   'Select input, shared by all four sections. LOW = outputs follow A inputs; HIGH = outputs follow B inputs.',
      '1A':  'Data input A for section 1.',
      '1B':  'Data input B for section 1.',
      '1Y':  'Output of section 1. Equals 1A when S=0; equals 1B when S=1 (and En#=LOW).',
      '2A':  'Data input A for section 2.',
      '2B':  'Data input B for section 2.',
      '2Y':  'Output of section 2.',
      'GND': 'Ground reference (pin 8).',
      '3Y':  'Output of section 3.',
      '3B':  'Data input B for section 3.',
      '3A':  'Data input A for section 3.',
      '4Y':  'Output of section 4.',
      '4B':  'Data input B for section 4.',
      '4A':  'Data input A for section 4.',
      'En':  'Output enable, active LOW. HIGH forces all outputs LOW.',
      'VCC': 'Positive supply (+5 V) at pin 16.',
    },
    guideSections: [
      {
        title: 'Quad 2-to-1 Bus Selection',
        paragraphs: ['Use S=0 to pass bus A to all outputs, S=1 to pass bus B. All four sections switch simultaneously, making this ideal for selecting between two complete 4 bit buses.'],
        note: 'The 74x158 is the inverting version; it produces complemented outputs.',
      },
    ],
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls157.pdf',
    tags: ['multiplexer', 'mux', '2-to-1', 'data selector', 'quad', 'non-inverting'],
    pinout: [
      { pin: 1,  name: 'S',   type: 'input',  description: 'Select input: S=0 → Y=A; S=1 → Y=B' },
      { pin: 2,  name: '1A',  type: 'input',  description: 'Section 1 data input A' },
      { pin: 3,  name: '1B',  type: 'input',  description: 'Section 1 data input B' },
      { pin: 4,  name: '1Y',  type: 'output', description: 'Section 1 output' },
      { pin: 5,  name: '2A',  type: 'input',  description: 'Section 2 data input A' },
      { pin: 6,  name: '2B',  type: 'input',  description: 'Section 2 data input B' },
      { pin: 7,  name: '2Y',  type: 'output', description: 'Section 2 output' },
      { pin: 8,  name: 'GND', type: 'power',  description: 'Ground (0V)' },
      { pin: 9,  name: '3Y',  type: 'output', description: 'Section 3 output' },
      { pin: 10, name: '3B',  type: 'input',  description: 'Section 3 data input B' },
      { pin: 11, name: '3A',  type: 'input',  description: 'Section 3 data input A' },
      { pin: 12, name: '4Y',  type: 'output', description: 'Section 4 output' },
      { pin: 13, name: '4B',  type: 'input',  description: 'Section 4 data input B' },
      { pin: 14, name: '4A',  type: 'input',  description: 'Section 4 data input A' },
      { pin: 15, name: 'En',  type: 'input',  description: 'Output enable (active LOW); HIGH forces all outputs LOW' },
      { pin: 16, name: 'VCC', type: 'power',  description: 'Positive supply (+5V)' },
    ],
    gates: [
      { type: 'MUX_2TO1', inputs: ['1A', '1B', 'S', 'En'], output: '1Y' },
      { type: 'MUX_2TO1', inputs: ['2A', '2B', 'S', 'En'], output: '2Y' },
      { type: 'MUX_2TO1', inputs: ['3A', '3B', 'S', 'En'], output: '3Y' },
      { type: 'MUX_2TO1', inputs: ['4A', '4B', 'S', 'En'], output: '4Y' },
    ],
  },

  // ── 74160: Synchronous 4 bit Decade Counter (with clear) ──────────────
  /* Primary source: Texas Instruments, SN74LS160A datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls160a.pdf
     Counter (digital) concept: https://en.wikipedia.org/wiki/Counter_(digital) */
  '74160': {
    name: '74x160',
    simpleName: 'Sync Decade Counter',
    description: 'Synchronous 4 bit decade counter with asynchronous clear (16-pin)',
    guideOverview: 'The 74x160 is a synchronous 4 bit decade (BCD) counter. It counts 0 9 on each rising clock edge when both enable inputs (ENP and ENT) are HIGH. An active LOW asynchronous clear (CLR#) resets the count to 0 immediately. A synchronous parallel load (LOAD#) captures inputs A D on the next rising clock edge. Terminal Count Output (RCO) goes HIGH at count 9 for cascading.',
    guidePinDescriptions: {
      'CLR':  'Asynchronous clear, active LOW. Immediately resets all outputs to 0 (overrides clock).',
      'CLK':  'Clock input. Count increments on the rising edge when ENP=ENT=HIGH.',
      'A':    'Parallel data input bit 0 (LSB). Loaded into QA when LOAD#=LOW on clock edge.',
      'B':    'Parallel data input bit 1.',
      'C':    'Parallel data input bit 2.',
      'D':    'Parallel data input bit 3 (MSB).',
      'ENP':  'Count enable input P. Both ENP and ENT must be HIGH to allow counting.',
      'GND':  'Ground reference (pin 8).',
      'LOAD': 'Synchronous parallel load, active LOW. On the rising clock edge when LOW, loads A D into the counter.',
      'ENT':  'Count enable input T. Must be HIGH (with ENP) to count. Also gates the RCO output.',
      'QD':   'Count output bit 3 (MSB, weight 8).',
      'QC':   'Count output bit 2 (weight 4).',
      'QB':   'Count output bit 1 (weight 2).',
      'QA':   'Count output bit 0 (LSB, weight 1).',
      'RCO':  'Terminal Count Output (Ripple Carry Out). HIGH at count 9 when ENT=HIGH. Used to cascade counters.',
      'VCC':  'Positive supply (+5 V) at pin 16.',
    },
    guideSections: [
      {
        title: 'Synchronous Decade Counting',
        paragraphs: [
          'All flip-flops share the same clock this is a synchronous counter. All outputs change simultaneously on the active clock edge, eliminating the ripple glitches of asynchronous counters.',
          'CLR# is asynchronous (immediate). LOAD# is synchronous (waits for clock). Both ENP and ENT must be HIGH to count. To cascade: connect RCO of stage N to ENP and ENT of stage N+1.',
        ],
        note: 'The 74x161 is identical but counts 0 15 (binary) instead of 0 9 (decade).',
      },
    ],
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls160a.pdf',
    tags: ['counter', 'decade', 'synchronous', '4 bit', 'sequential'],
    pinout: [
      { pin: 1, name: 'CLR', type: 'input' },
      { pin: 2, name: 'CLK', type: 'input' },
      { pin: 3, name: 'A', type: 'input' },
      { pin: 4, name: 'B', type: 'input' },
      { pin: 5, name: 'C', type: 'input' },
      { pin: 6, name: 'D', type: 'input' },
      { pin: 7, name: 'ENP', type: 'input' },
      { pin: 8, name: 'GND', type: 'power' },
      { pin: 9, name: 'LOAD', type: 'input' },
      { pin: 10, name: 'ENT', type: 'input' },
      { pin: 11, name: 'QD', type: 'output' },
      { pin: 12, name: 'QC', type: 'output' },
      { pin: 13, name: 'QB', type: 'output' },
      { pin: 14, name: 'QA', type: 'output' },
      { pin: 15, name: 'RCO', type: 'output' },
      { pin: 16, name: 'VCC', type: 'power' },
    ],
    gates: [
      {
        type: 'COUNTER_SYNC_DECADE',
        inputs: ['CLK', 'CLR', 'LOAD', 'ENP', 'ENT', 'A', 'B', 'C', 'D'],
        outputs: ['QA', 'QB', 'QC', 'QD', 'RCO'],
      },
    ],
    sequential: true,
  },

  // ── 74161: Synchronous 4 bit Binary Counter (with clear) ──────────────
  /* Primary source: Texas Instruments, SN74LS161A datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls161a.pdf
     Counter (digital) concept: https://en.wikipedia.org/wiki/Counter_(digital) */
  '74161': {
    name: '74x161',
    simpleName: 'Sync Binary Counter',
    description: 'Synchronous 4 bit binary counter with asynchronous clear (16-pin)',
    guideOverview: 'The 74x161 is a synchronous 4 bit binary counter. It counts 0 15 on each rising clock edge when ENP and ENT are HIGH. Identical to the 74x160 in pinout and control signals, but counts in binary (0 15) rather than BCD (0 9). RCO goes HIGH at count 15 for cascading to wider counters.',
    guidePinDescriptions: {
      'CLR':  'Asynchronous clear, active LOW. Immediately resets all outputs to 0.',
      'CLK':  'Clock input. Count increments on the rising edge when ENP=ENT=HIGH.',
      'A':    'Parallel data input bit 0 (LSB). Loaded when LOAD#=LOW on clock edge.',
      'B':    'Parallel data input bit 1.',
      'C':    'Parallel data input bit 2.',
      'D':    'Parallel data input bit 3 (MSB).',
      'ENP':  'Count enable P. Both ENP and ENT must be HIGH to count.',
      'GND':  'Ground reference (pin 8).',
      'LOAD': 'Synchronous parallel load, active LOW. Loads A D on the next rising clock edge.',
      'ENT':  'Count enable T. Also gates the RCO output.',
      'QD':   'Count output bit 3 (MSB, weight 8).',
      'QC':   'Count output bit 2 (weight 4).',
      'QB':   'Count output bit 1 (weight 2).',
      'QA':   'Count output bit 0 (LSB, weight 1).',
      'RCO':  'Terminal Count Output. HIGH at count 15 when ENT=HIGH. Connect to ENP/ENT of next stage for cascading.',
      'VCC':  'Positive supply (+5 V) at pin 16.',
    },
    guideSections: [
      {
        title: 'Synchronous Binary Counting (0 15)',
        paragraphs: ['Same architecture as 74x160 but counts binary 0 15. Cascade multiple chips for wider counters: RCO of stage 0 → ENP and ENT of stage 1, and so on.'],
        note: 'For synchronous clear (clear waits for clock), use the 74x163 instead.',
      },
    ],
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls161a.pdf',
    tags: ['counter', 'binary', 'synchronous', '4 bit', 'sequential'],
    pinout: [
      { pin: 1, name: 'CLR', type: 'input' },
      { pin: 2, name: 'CLK', type: 'input' },
      { pin: 3, name: 'A', type: 'input' },
      { pin: 4, name: 'B', type: 'input' },
      { pin: 5, name: 'C', type: 'input' },
      { pin: 6, name: 'D', type: 'input' },
      { pin: 7, name: 'ENP', type: 'input' },
      { pin: 8, name: 'GND', type: 'power' },
      { pin: 9, name: 'LOAD', type: 'input' },
      { pin: 10, name: 'ENT', type: 'input' },
      { pin: 11, name: 'QD', type: 'output' },
      { pin: 12, name: 'QC', type: 'output' },
      { pin: 13, name: 'QB', type: 'output' },
      { pin: 14, name: 'QA', type: 'output' },
      { pin: 15, name: 'RCO', type: 'output' },
      { pin: 16, name: 'VCC', type: 'power' },
    ],
    gates: [
      {
        type: 'COUNTER_SYNC_BIN',
        inputs: ['CLK', 'CLR', 'LOAD', 'ENP', 'ENT', 'A', 'B', 'C', 'D'],
        outputs: ['QA', 'QB', 'QC', 'QD', 'RCO'],
      },
    ],
    sequential: true,
  },

  // ── 74163: Synchronous 4 bit Binary Counter (with synchronous clear) ──
  /* Primary source: Texas Instruments, SN74LS163A datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls163a.pdf
     Counter (digital) concept: https://en.wikipedia.org/wiki/Counter_(digital) */
  '74163': {
    name: '74x163',
    simpleName: 'Sync Counter (SC)',
    description: 'Synchronous 4 bit binary counter with synchronous clear (16-pin)',
    guideOverview: 'The 74x163 is a synchronous 4 bit binary counter with fully synchronous clear. It is identical to the 74x161 except that CLR# is synchronous: the counter waits until the next rising clock edge to reset to 0. This eliminates potential glitches that can occur with asynchronous clear in high-speed designs.',
    guidePinDescriptions: {
      'CLR':  'Synchronous clear, active LOW. Counter resets to 0 on the NEXT rising clock edge when LOW (unlike 74x161 which resets immediately).',
      'CLK':  'Clock input. All state changes occur on the rising edge.',
      'A':    'Parallel data input bit 0 (LSB).',
      'B':    'Parallel data input bit 1.',
      'C':    'Parallel data input bit 2.',
      'D':    'Parallel data input bit 3 (MSB).',
      'ENP':  'Count enable P. Must be HIGH (with ENT) to count.',
      'GND':  'Ground reference (pin 8).',
      'LOAD': 'Synchronous parallel load, active LOW. Loads A D on the next rising clock edge.',
      'ENT':  'Count enable T. Also gates the RCO output.',
      'QD':   'Count output bit 3 (weight 8).',
      'QC':   'Count output bit 2 (weight 4).',
      'QB':   'Count output bit 1 (weight 2).',
      'QA':   'Count output bit 0 (weight 1).',
      'RCO':  'Terminal Count Output. HIGH when count=15 and ENT=HIGH.',
      'VCC':  'Positive supply (+5 V) at pin 16.',
    },
    guideSections: [
      {
        title: 'Synchronous Clear vs Asynchronous',
        paragraphs: ['The 74x163 clear is synchronous: asserting CLR# does not reset the counter immediately but on the next rising clock edge. This is safer in clocked systems where glitch-free transitions are required.'],
        note: 'For an asynchronous (immediate) clear, use the 74x161. Functionally they count identically.',
      },
    ],
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls163a.pdf',
    tags: ['counter', 'binary', 'synchronous', '4 bit', 'sequential'],
    pinout: [
      { pin: 1, name: 'CLR', type: 'input' },
      { pin: 2, name: 'CLK', type: 'input' },
      { pin: 3, name: 'A', type: 'input' },
      { pin: 4, name: 'B', type: 'input' },
      { pin: 5, name: 'C', type: 'input' },
      { pin: 6, name: 'D', type: 'input' },
      { pin: 7, name: 'ENP', type: 'input' },
      { pin: 8, name: 'GND', type: 'power' },
      { pin: 9, name: 'LOAD', type: 'input' },
      { pin: 10, name: 'ENT', type: 'input' },
      { pin: 11, name: 'QD', type: 'output' },
      { pin: 12, name: 'QC', type: 'output' },
      { pin: 13, name: 'QB', type: 'output' },
      { pin: 14, name: 'QA', type: 'output' },
      { pin: 15, name: 'RCO', type: 'output' },
      { pin: 16, name: 'VCC', type: 'power' },
    ],
    gates: [
      {
        type: 'COUNTER_SYNC_BIN_SC',
        inputs: ['CLK', 'CLR', 'LOAD', 'ENP', 'ENT', 'A', 'B', 'C', 'D'],
        outputs: ['QA', 'QB', 'QC', 'QD', 'RCO'],
      },
    ],
    sequential: true,
  },

  // ── 74164: 8 bit Serial-in Parallel-out Shift Register ─────────────────
  /* Primary source: Texas Instruments, SN74LS164 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls164.pdf
     Shift register concept: https://en.wikipedia.org/wiki/Shift_register */
  '74164': {
    name: '74x164',
    simpleName: '8 bit SIPO Shift Register',
    description: '8 bit serial-in, parallel-out shift register. (14-pin)',
    guideOverview: 'The 74x164 is an 8 bit serial-in, parallel-out (SIPO) shift register. Data enters serially through AND-gated inputs A and B (both must be HIGH to shift in a 1). On each rising clock edge, data shifts one position toward QH. All 8 bits are always available simultaneously on the parallel outputs QA QH. An active LOW asynchronous clear (CLR#) resets all outputs to 0 instantly.',
    guidePinDescriptions: {
      'A':   'Serial data input A. Both A and B must be HIGH to shift in a logic 1. LOW on either forces a 0 into the shift register.',
      'B':   'Serial data input B. ANDed with A for serial input.',
      'QA':  'Parallel output of bit 0 (first-in stage). Reflects the bit most recently shifted in.',
      'QB':  'Parallel output of bit 1.',
      'QC':  'Parallel output of bit 2.',
      'QD':  'Parallel output of bit 3.',
      'GND': 'Ground reference (pin 7).',
      'CLK': 'Clock input. Data shifts right (A→QA→QB...→QH) on each rising edge.',
      'CLR': 'Asynchronous clear, active LOW. Immediately sets all outputs to 0.',
      'QE':  'Parallel output of bit 4.',
      'QF':  'Parallel output of bit 5.',
      'QG':  'Parallel output of bit 6.',
      'QH':  'Parallel output of bit 7 (last stage). This is the serial output when cascading.',
      'VCC': 'Positive supply (+5 V) at pin 14.',
    },
    guideSections: [
      {
        title: 'Serial-In Parallel-Out (SIPO) Operation',
        paragraphs: [
          'The 74x164 converts a serial bit stream into 8 parallel bits. Clock in 8 bits (MSB first) and then read QA QH simultaneously. After exactly 8 clocks, the register holds the last 8 bits received.',
          'Use case: expand a serial interface into 8 control lines. Clock the data in with a microcontroller’s SPI or bit-bang serial, then use the 8 outputs to control LEDs, relays, or other devices.',
        ],
        note: 'Tie both A and B HIGH to shift in a 1. To shift in a 0, hold either A or B LOW. Tie CLR# HIGH for normal operation.',
      },
    ],
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls164.pdf',
    tags: ['shift register', 'serial', 'parallel', '8 bit', 'sequential', 'sipo'],
    pinout: [
      { pin: 1,  name: 'A',   type: 'input',  description: 'Serial data input A (ANDed with B to form shift input)' },
      { pin: 2,  name: 'B',   type: 'input',  description: 'Serial data input B (ANDed with A to form shift input)' },
      { pin: 3,  name: 'QA',  type: 'output', description: 'Parallel output bit 0 (first stage, MSB of shift direction)' },
      { pin: 4,  name: 'QB',  type: 'output', description: 'Parallel output bit 1' },
      { pin: 5,  name: 'QC',  type: 'output', description: 'Parallel output bit 2' },
      { pin: 6,  name: 'QD',  type: 'output', description: 'Parallel output bit 3' },
      { pin: 7,  name: 'GND', type: 'power',  description: 'Ground (0V)' },
      { pin: 8,  name: 'CLK', type: 'input',  description: 'Clock input data shifts on rising edge' },
      { pin: 9,  name: 'CLR', type: 'input',  description: 'Asynchronous clear (active LOW) LOW resets all outputs to 0 immediately' },
      { pin: 10, name: 'QE',  type: 'output', description: 'Parallel output bit 4' },
      { pin: 11, name: 'QF',  type: 'output', description: 'Parallel output bit 5' },
      { pin: 12, name: 'QG',  type: 'output', description: 'Parallel output bit 6' },
      { pin: 13, name: 'QH',  type: 'output', description: 'Parallel output bit 7 (last stage)' },
      { pin: 14, name: 'VCC', type: 'power',  description: 'Positive supply (+5V)' },
    ],
    gates: [
      {
        type: 'SHIFT_REG_SIPO',
        inputs: ['A', 'B', 'CLK', 'CLR'],
        outputs: ['QA', 'QB', 'QC', 'QD', 'QE', 'QF', 'QG', 'QH'],
      },
    ],
    sequential: true,
  },

  // ── 74165: 8 bit Parallel-in Serial-out Shift Register ─────────────────
  /* Primary source: Texas Instruments, SN74LS165 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls165.pdf
     Shift register concept: https://en.wikipedia.org/wiki/Shift_register */
  '74165': {
    name: '74x165',
    simpleName: '8 bit PISO Shift Register',
    description: '8 bit parallel-in, serial-out (PISO) shift register. (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls165.pdf',
    tags: ['shift register', 'parallel', 'serial', '8 bit', 'sequential', 'piso'],
    guideOverview: 'The 74165 is an 8 bit parallel-in, serial-out shift register. Apply a LOW to SH/LD# (pin 1) to latch all 8 parallel inputs (A H) into the register simultaneously. Then drive SH/LD# HIGH and clock the register to stream the data out one bit at a time on QH. Pull CLKINH HIGH to freeze the clock without disturbing the stored data. SER allows additional serial bits to be shifted in during the shift phase, enabling daisy-chaining of multiple 74165 ICs.',
    guidePinDescriptions: {
      'SH/LD': 'Shift/Load control (active LOW load). LOW = parallel load A H into register; HIGH = shift mode enabled.',
      'CLK': 'Clock input. On each rising edge (when SH/LD#=HIGH and CLKINH=LOW), register shifts one position toward QH.',
      'CLKINH': 'Clock inhibit. HIGH prevents the clock from advancing the shift register without affecting stored data.',
      'SER': 'Serial data input. Bit shifted into the LSB position on each rising clock during shift mode. Used to daisy-chain devices.',
      'QH': 'Serial data output the true (non-inverted) output of the last stage (MSB). Connect to SER of the next chip to cascade.',
      'QHn': 'Complementary (inverted) serial output. HIGH when QH is LOW and vice versa.',
    },
    guideSections: [
      {
        title: 'Parallel-In Serial-Out (PISO) Operation',
        paragraphs: [
          'The 74x165 converts 8 parallel bits into a serial bit stream. Pulse SH/LD# LOW briefly to latch A H, then clock out the bits one at a time on QH.',
          'To cascade two chips for 16 bit PISO, connect QH of the first chip to SER of the second chip and share CLK.',
        ],
        note: 'Pull CLKINH LOW during normal clocking. Keep SER LOW if you do not need to inject serial data.',
      },
    ],
    pinout: [
      { pin: 1,  name: 'SH/LD',  type: 'input',  description: 'Shift/Load select (active LOW load). LOW latches parallel inputs A H; HIGH enables shifting on clock.' },
      { pin: 2,  name: 'CLK',    type: 'input',  description: 'Clock input. Rising edge advances the shift register when SH/LD#=HIGH and CLKINH=LOW.' },
      { pin: 3,  name: 'E',      type: 'input',  description: 'Parallel data input bit E (bit 4 of 8). Loaded when SH/LD# goes LOW.' },
      { pin: 4,  name: 'F',      type: 'input',  description: 'Parallel data input bit F (bit 5 of 8). Loaded when SH/LD# goes LOW.' },
      { pin: 5,  name: 'G',      type: 'input',  description: 'Parallel data input bit G (bit 6 of 8). Loaded when SH/LD# goes LOW.' },
      { pin: 6,  name: 'H',      type: 'input',  description: 'Parallel data input bit H (bit 7 of 8, MSB). Loaded when SH/LD# goes LOW.' },
      { pin: 7,  name: 'QHn',    type: 'output', description: 'Complementary (inverted) serial output of the last shift stage.' },
      { pin: 8,  name: 'GND',    type: 'power' },
      { pin: 9,  name: 'QH',     type: 'output', description: 'True serial output from the last shift stage. Connect to SER of next chip when cascading.' },
      { pin: 10, name: 'SER',    type: 'input',  description: 'Serial data input. Shifted into the register on each rising clock edge during shift mode.' },
      { pin: 11, name: 'A',      type: 'input',  description: 'Parallel data input bit A (bit 0 of 8, LSB). Loaded when SH/LD# goes LOW.' },
      { pin: 12, name: 'B',      type: 'input',  description: 'Parallel data input bit B (bit 1 of 8). Loaded when SH/LD# goes LOW.' },
      { pin: 13, name: 'C',      type: 'input',  description: 'Parallel data input bit C (bit 2 of 8). Loaded when SH/LD# goes LOW.' },
      { pin: 14, name: 'D',      type: 'input',  description: 'Parallel data input bit D (bit 3 of 8). Loaded when SH/LD# goes LOW.' },
      { pin: 15, name: 'CLKINH', type: 'input',  description: 'Clock inhibit. Drive HIGH to freeze the shift register without losing its contents.' },
      { pin: 16, name: 'VCC',    type: 'power' },
    ],
    gates: [
      {
        type: 'SHIFT_REG_PISO',
        inputs: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'SER', 'CLK', 'CLKINH', 'SH/LD'],
        outputs: ['QH', 'QHn'],
      },
    ],
    sequential: true,
  },

  // ── 74173: 4 bit D Register (tri-state) ────────────────────────────────
  /* Primary source: Texas Instruments, SN74LS173A datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls173a.pdf
     Three-state (tri-state) logic: https://en.wikipedia.org/wiki/Three-state_logic
     Flip-flop concept: https://en.wikipedia.org/wiki/Flip-flop_(electronics) */
  '74173': {
    name: '74x173',
    simpleName: '4 bit D Register',
    description: '4 bit D-type register with tri-state outputs (16-pin)',
    guideOverview: 'The 74x173 is a 4 bit D-type register with tri-state outputs. On each rising clock edge, when both input enables (IE1 and IE2) are LOW, the 4 data inputs (1D 4D) are stored. The outputs (1Q 4Q) are tri-state: both output enable pins (OE1 and OE2) must be LOW to drive the outputs; otherwise they float to high-impedance. CLR# resets all outputs asynchronously. Useful for driving shared buses.',
    guidePinDescriptions: {
      'OE1':  'Output enable 1, active LOW. Both OE1 and OE2 must be LOW for outputs to be driven. Otherwise outputs are high-Z.',
      'OE2':  'Output enable 2, active LOW. See OE1.',
      '1Q':   'Registered output for bit 1. Tri-state: active only when OE1 and OE2 are both LOW.',
      '2Q':   'Registered output for bit 2.',
      '3Q':   'Registered output for bit 3.',
      '4Q':   'Registered output for bit 4.',
      'CLK':  'Clock input. Latches data inputs into register on the rising edge when IE1=IE2=LOW.',
      'GND':  'Ground reference (pin 8).',
      'IE1':  'Input enable 1, active LOW. Both IE1 and IE2 must be LOW for the register to capture new data.',
      'IE2':  'Input enable 2, active LOW. See IE1.',
      '4D':   'Data input for bit 4 (MSB). Captured on rising clock edge when IE1=IE2=LOW.',
      '3D':   'Data input for bit 3.',
      '2D':   'Data input for bit 2.',
      '1D':   'Data input for bit 1 (LSB).',
      'CLR':  'Asynchronous clear, active LOW (actually active HIGH in most variants check datasheet). Resets all Q outputs to 0.',
      'VCC':  'Positive supply (+5 V) at pin 16.',
    },
    guideSections: [
      {
        title: 'Tri-State Output Register',
        paragraphs: [
          'Both OE1 and OE2 must be LOW to enable outputs. Drive either HIGH to float the outputs off a shared bus.',
          'Both IE1 and IE2 must be LOW on a rising clock edge for data to be latched. Pull CLR# HIGH for normal operation.',
        ],
      },
    ],
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls173a.pdf',
    tags: ['register', 'd', '4 bit', 'tri-state', 'sequential'],
    pinout: [
      { pin: 1, name: 'OE1', type: 'input' },
      { pin: 2, name: 'OE2', type: 'input' },
      { pin: 3, name: '1Q', type: 'output' },
      { pin: 4, name: '2Q', type: 'output' },
      { pin: 5, name: '3Q', type: 'output' },
      { pin: 6, name: '4Q', type: 'output' },
      { pin: 7, name: 'CLK', type: 'input' },
      { pin: 8, name: 'GND', type: 'power' },
      { pin: 9, name: 'IE1', type: 'input' },
      { pin: 10, name: 'IE2', type: 'input' },
      { pin: 11, name: '4D', type: 'input' },
      { pin: 12, name: '3D', type: 'input' },
      { pin: 13, name: '2D', type: 'input' },
      { pin: 14, name: '1D', type: 'input' },
      { pin: 15, name: 'CLR', type: 'input' },
      { pin: 16, name: 'VCC', type: 'power' },
    ],
    gates: [
      {
        type: 'REG_4BIT_TRI',
        inputs: ['1D', '2D', '3D', '4D', 'CLK', 'CLR', 'IE1', 'IE2', 'OE1', 'OE2'],
        outputs: ['1Q', '2Q', '3Q', '4Q'],
      },
    ],
    sequential: true,
  },

  // ── 74174: Hex D flip-flop with clear ──────────────────────────────────
  /* Primary source: Texas Instruments, SN74LS174 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls174.pdf
     Flip-flop concept: https://en.wikipedia.org/wiki/Flip-flop_(electronics) */
  '74174': {
    name: '74x174',
    simpleName: 'Hex D FF',
    description: 'Hex D-type flip-flop with clear (16-pin)',
    guideOverview: 'The 74x174 contains six positive-edge-triggered D flip-flops sharing a common clock and a common active LOW asynchronous clear. All six D inputs are captured simultaneously on every rising clock edge. There is no Q-bar output for any section. It is essentially a 6 bit parallel register ideal for latching a 6 bit value synchronously.',
    guidePinDescriptions: {
      'CLR':  'Asynchronous clear, active LOW. Immediately resets all six outputs to 0.',
      '1Q':   'Output of flip-flop 1.',
      '1D':   'Data input for flip-flop 1. Captured on rising clock edge.',
      '2D':   'Data input for flip-flop 2.',
      '2Q':   'Output of flip-flop 2.',
      '3D':   'Data input for flip-flop 3.',
      '3Q':   'Output of flip-flop 3.',
      'GND':  'Ground reference (pin 8).',
      'CLK':  'Clock input, shared by all six flip-flops.',
      '4Q':   'Output of flip-flop 4.',
      '4D':   'Data input for flip-flop 4.',
      '5Q':   'Output of flip-flop 5.',
      '5D':   'Data input for flip-flop 5.',
      '6D':   'Data input for flip-flop 6.',
      '6Q':   'Output of flip-flop 6.',
      'VCC':  'Positive supply (+5 V) at pin 16.',
    },
    guideSections: [
      {
        title: 'Hex Parallel Register',
        paragraphs: [
          'The 74x174 functions as a 6 bit parallel storage register. All six D inputs are captured simultaneously on the rising clock edge. CLR# resets all 6 bits asynchronously.',
          'No Q-bar outputs are provided. For 8 bit storage use two 74x174 chips with a shared clock and clear.',
        ],
      },
    ],
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls174.pdf',
    tags: ['flip-flop', 'flip flop', 'd', 'hex', 'sequential', 'register'],
    pinout: [
      { pin: 1, name: 'CLR', type: 'input' },
      { pin: 2, name: '1Q', type: 'output' },
      { pin: 3, name: '1D', type: 'input' },
      { pin: 4, name: '2D', type: 'input' },
      { pin: 5, name: '2Q', type: 'output' },
      { pin: 6, name: '3D', type: 'input' },
      { pin: 7, name: '3Q', type: 'output' },
      { pin: 8, name: 'GND', type: 'power' },
      { pin: 9, name: 'CLK', type: 'input' },
      { pin: 10, name: '4Q', type: 'output' },
      { pin: 11, name: '4D', type: 'input' },
      { pin: 12, name: '5Q', type: 'output' },
      { pin: 13, name: '5D', type: 'input' },
      { pin: 14, name: '6D', type: 'input' },
      { pin: 15, name: '6Q', type: 'output' },
      { pin: 16, name: 'VCC', type: 'power' },
    ],
    gates: [
      {
        type: 'D_FF_HEX',
        inputs: ['1D', '2D', '3D', '4D', '5D', '6D', 'CLK', 'CLR'],
        outputs: ['1Q', '2Q', '3Q', '4Q', '5Q', '6Q'],
      },
    ],
    sequential: true,
  },
};
