// chips27.js -- Chips Block 27: 74462-74478
export const CHIPS_BLOCK_27 = {



  // - 74465: Octal buffer, non-inverting, two enables -
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Three-state_logic */
  '74465': {
    name: '74x465',
    simpleName: 'Octal Buffer (non-inv, 2-en)',
    description: 'Octal buffer with two active LOW enables, non-inverting, tri-state (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    tags: ['buffer', 'octal', 'tri-state', 'non-inverting'],
    guideOverview: 'The 74x465 is an octal non-inverting tri-state buffer with two active LOW enables (G1n, G2n) that must both be LOW to enable the outputs. When either is HIGH all eight Y outputs are high-impedance. Having two enables allows the chip to be gated by two independent control signals without external NAND logic.',
    guidePinDescriptions: {
      'G1n': 'Enable 1 (active LOW). When HIGH, all outputs tri-stated.',
      'A1':  'Data input 1.',
      'A2':  'Data input 2.',
      'A3':  'Data input 3.',
      'A4':  'Data input 4.',
      'A5':  'Data input 5.',
      'A6':  'Data input 6.',
      'A7':  'Data input 7.',
      'A8':  'Data input 8.',
      'GND': 'Ground reference (pin 10).',
      'Y8':  'Tri-state output 8.',
      'Y7':  'Tri-state output 7.',
      'Y6':  'Tri-state output 6.',
      'Y5':  'Tri-state output 5.',
      'Y4':  'Tri-state output 4.',
      'Y3':  'Tri-state output 3.',
      'Y2':  'Tri-state output 2.',
      'Y1':  'Tri-state output 1.',
      'G2n': 'Enable 2 (active LOW). Both G1n and G2n must be LOW to enable.',
      'VCC': 'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'Dual-Enable Bus Gating',
        paragraphs: [
          'The two-enable structure implements a wired AND in the enable path. You can use G1n for chip select and G2n for read/write direction without needing an external AND gate.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'G1n', type: 'input' },
      { pin:  2, name: 'A1',  type: 'input' },
      { pin:  3, name: 'A2',  type: 'input' },
      { pin:  4, name: 'A3',  type: 'input' },
      { pin:  5, name: 'A4',  type: 'input' },
      { pin:  6, name: 'A5',  type: 'input' },
      { pin:  7, name: 'A6',  type: 'input' },
      { pin:  8, name: 'A7',  type: 'input' },
      { pin:  9, name: 'A8',  type: 'input' },
      { pin: 10, name: 'GND', type: 'power' },
      { pin: 11, name: 'Y8',  type: 'output' },
      { pin: 12, name: 'Y7',  type: 'output' },
      { pin: 13, name: 'Y6',  type: 'output' },
      { pin: 14, name: 'Y5',  type: 'output' },
      { pin: 15, name: 'Y4',  type: 'output' },
      { pin: 16, name: 'Y3',  type: 'output' },
      { pin: 17, name: 'Y2',  type: 'output' },
      { pin: 18, name: 'Y1',  type: 'output' },
      { pin: 19, name: 'G2n', type: 'input' },
      { pin: 20, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'BUFFER_OCTAL_TRI',
        inputs:  ['A1','A2','A3','A4','A5','A6','A7','A8','G1n','G2n'],
        outputs: ['Y1','Y2','Y3','Y4','Y5','Y6','Y7','Y8'] },
    ],
  },

  // - 74466: Octal buffer, inverting outputs, two enables -
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Three-state_logic */
  '74466': {
    name: '74x466',
    simpleName: 'Octal Buffer (inv, 2-en)',
    description: 'Octal buffer with two active LOW enables, inverting outputs, tri-state (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    tags: ['buffer', 'octal', 'tri-state', 'inverting'],
    guideOverview: 'The 74x466 is an octal inverting tri-state buffer with two active LOW enables (G1n, G2n). Both enables must be LOW to drive the Y outputs; each output is the complement of its input. Use when an inverting buffer with a dual-enable AND condition is needed.',
    guidePinDescriptions: {
      'G1n': 'Enable 1 (active LOW).',
      'A1':  'Data input 1.',
      'A2':  'Data input 2.',
      'A3':  'Data input 3.',
      'A4':  'Data input 4.',
      'A5':  'Data input 5.',
      'A6':  'Data input 6.',
      'A7':  'Data input 7.',
      'A8':  'Data input 8.',
      'GND': 'Ground reference (pin 10).',
      'Y8':  'Inverted tri-state output 8.',
      'Y7':  'Inverted tri-state output 7.',
      'Y6':  'Inverted tri-state output 6.',
      'Y5':  'Inverted tri-state output 5.',
      'Y4':  'Inverted tri-state output 4.',
      'Y3':  'Inverted tri-state output 3.',
      'Y2':  'Inverted tri-state output 2.',
      'Y1':  'Inverted tri-state output 1.',
      'G2n': 'Enable 2 (active LOW).',
      'VCC': 'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: '74x465 vs 74x466',
        paragraphs: [
          'Same pinout, same dual-enable structure. 74x465 passes data unchanged; 74x466 inverts it. Select based on the bus polarity you need on the output side.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'G1n', type: 'input' },
      { pin:  2, name: 'A1',  type: 'input' },
      { pin:  3, name: 'A2',  type: 'input' },
      { pin:  4, name: 'A3',  type: 'input' },
      { pin:  5, name: 'A4',  type: 'input' },
      { pin:  6, name: 'A5',  type: 'input' },
      { pin:  7, name: 'A6',  type: 'input' },
      { pin:  8, name: 'A7',  type: 'input' },
      { pin:  9, name: 'A8',  type: 'input' },
      { pin: 10, name: 'GND', type: 'power' },
      { pin: 11, name: 'Y8',  type: 'output' },
      { pin: 12, name: 'Y7',  type: 'output' },
      { pin: 13, name: 'Y6',  type: 'output' },
      { pin: 14, name: 'Y5',  type: 'output' },
      { pin: 15, name: 'Y4',  type: 'output' },
      { pin: 16, name: 'Y3',  type: 'output' },
      { pin: 17, name: 'Y2',  type: 'output' },
      { pin: 18, name: 'Y1',  type: 'output' },
      { pin: 19, name: 'G2n', type: 'input' },
      { pin: 20, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'BUFFER_OCTAL_INV_TRI',
        inputs:  ['A1','A2','A3','A4','A5','A6','A7','A8','G1n','G2n'],
        outputs: ['Y1','Y2','Y3','Y4','Y5','Y6','Y7','Y8'] },
    ],
  },

  // - 74467: Octal buffer, non-inverting, separate enable per group -
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Three-state_logic */
  '74467': {
    name: '74x467',
    simpleName: 'Octal Buffer (non-inv, split-en)',
    description: 'Octal buffer, non-inverting, separate active LOW enables per nibble, tri-state (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    tags: ['buffer', 'octal', 'tri-state', 'non-inverting'],
    guideOverview: 'The 74x467 is an octal non-inverting tri-state buffer with independent enables for each 4 bit nibble. G1n controls A1-A4/Y1-Y4 and G2n controls A5-A8/Y5-Y8. This split-enable design allows one byte to be driven as two independently-gated nibbles on the same bus.',
    guidePinDescriptions: {
      'G1n': 'Enable for lower nibble A1-A4 (active LOW).',
      'A1':  'Data input 1 (lower nibble).',
      'A2':  'Data input 2.',
      'A3':  'Data input 3.',
      'A4':  'Data input 4.',
      'A5':  'Data input 5 (upper nibble).',
      'A6':  'Data input 6.',
      'A7':  'Data input 7.',
      'A8':  'Data input 8.',
      'GND': 'Ground reference (pin 10).',
      'Y8':  'Tri-state output 8.',
      'Y7':  'Tri-state output 7.',
      'Y6':  'Tri-state output 6.',
      'Y5':  'Tri-state output 5.',
      'Y4':  'Tri-state output 4.',
      'Y3':  'Tri-state output 3.',
      'Y2':  'Tri-state output 2.',
      'Y1':  'Tri-state output 1.',
      'G2n': 'Enable for upper nibble A5-A8 (active LOW).',
      'VCC': 'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'Split-Nibble Enable',
        paragraphs: [
          'The 74x467 differs from the 74x465 in that G1n and G2n are independent per-nibble enables rather than a shared AND pair. Use it when you need to selectively pass only the lower or upper byte of an 8 bit bus.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'G1n', type: 'input' },
      { pin:  2, name: 'A1',  type: 'input' },
      { pin:  3, name: 'A2',  type: 'input' },
      { pin:  4, name: 'A3',  type: 'input' },
      { pin:  5, name: 'A4',  type: 'input' },
      { pin:  6, name: 'A5',  type: 'input' },
      { pin:  7, name: 'A6',  type: 'input' },
      { pin:  8, name: 'A7',  type: 'input' },
      { pin:  9, name: 'A8',  type: 'input' },
      { pin: 10, name: 'GND', type: 'power' },
      { pin: 11, name: 'Y8',  type: 'output' },
      { pin: 12, name: 'Y7',  type: 'output' },
      { pin: 13, name: 'Y6',  type: 'output' },
      { pin: 14, name: 'Y5',  type: 'output' },
      { pin: 15, name: 'Y4',  type: 'output' },
      { pin: 16, name: 'Y3',  type: 'output' },
      { pin: 17, name: 'Y2',  type: 'output' },
      { pin: 18, name: 'Y1',  type: 'output' },
      { pin: 19, name: 'G2n', type: 'input' },
      { pin: 20, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'BUFFER_OCTAL_TRI',
        inputs:  ['A1','A2','A3','A4','A5','A6','A7','A8','G1n','G2n'],
        outputs: ['Y1','Y2','Y3','Y4','Y5','Y6','Y7','Y8'] },
    ],
  },

  // - 74468: Octal buffer, inverting, separate enable per group -
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Three-state_logic */
  '74468': {
    name: '74x468',
    simpleName: 'Octal Buffer (inv, split-en)',
    description: 'Octal buffer, inverting, separate active LOW enables per nibble, tri-state (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    tags: ['buffer', 'octal', 'tri-state', 'inverting'],
    guideOverview: 'The 74x468 is an octal inverting tri-state buffer with split per-nibble enables (G1n for A1-A4, G2n for A5-A8). Each output is the complement of its input. Combines the inverting capability of 74x466 with the split-enable flexibility of 74x467.',
    guidePinDescriptions: {
      'G1n': 'Enable for lower nibble A1-A4 (active LOW).',
      'A1':  'Data input 1 (lower nibble).',
      'A2':  'Data input 2.',
      'A3':  'Data input 3.',
      'A4':  'Data input 4.',
      'A5':  'Data input 5 (upper nibble).',
      'A6':  'Data input 6.',
      'A7':  'Data input 7.',
      'A8':  'Data input 8.',
      'GND': 'Ground reference (pin 10).',
      'Y8':  'Inverted tri-state output 8.',
      'Y7':  'Inverted tri-state output 7.',
      'Y6':  'Inverted tri-state output 6.',
      'Y5':  'Inverted tri-state output 5.',
      'Y4':  'Inverted tri-state output 4.',
      'Y3':  'Inverted tri-state output 3.',
      'Y2':  'Inverted tri-state output 2.',
      'Y1':  'Inverted tri-state output 1.',
      'G2n': 'Enable for upper nibble A5-A8 (active LOW).',
      'VCC': 'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'Inverting Split-Enable Buffer',
        paragraphs: [
          'Use the 74x468 when you need to selectively invert either the lower or upper nibble of an 8 bit bus independently. Both nibbles or only one can be driven at a time.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'G1n', type: 'input' },
      { pin:  2, name: 'A1',  type: 'input' },
      { pin:  3, name: 'A2',  type: 'input' },
      { pin:  4, name: 'A3',  type: 'input' },
      { pin:  5, name: 'A4',  type: 'input' },
      { pin:  6, name: 'A5',  type: 'input' },
      { pin:  7, name: 'A6',  type: 'input' },
      { pin:  8, name: 'A7',  type: 'input' },
      { pin:  9, name: 'A8',  type: 'input' },
      { pin: 10, name: 'GND', type: 'power' },
      { pin: 11, name: 'Y8',  type: 'output' },
      { pin: 12, name: 'Y7',  type: 'output' },
      { pin: 13, name: 'Y6',  type: 'output' },
      { pin: 14, name: 'Y5',  type: 'output' },
      { pin: 15, name: 'Y4',  type: 'output' },
      { pin: 16, name: 'Y3',  type: 'output' },
      { pin: 17, name: 'Y2',  type: 'output' },
      { pin: 18, name: 'Y1',  type: 'output' },
      { pin: 19, name: 'G2n', type: 'input' },
      { pin: 20, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'BUFFER_OCTAL_INV_TRI',
        inputs:  ['A1','A2','A3','A4','A5','A6','A7','A8','G1n','G2n'],
        outputs: ['Y1','Y2','Y3','Y4','Y5','Y6','Y7','Y8'] },
    ],
  },

  // - 74469: 8 bit synchronous up/down counter, load, hold -
  /* Primary source: Wikipedia contributors, "7400-series integrated circuits." [Online]. Available: https://en.wikipedia.org/wiki/7400-series_integrated_circuits
     Wikipedia: https://en.wikipedia.org/wiki/Counter_(digital)
     Wikipedia: https://en.wikipedia.org/wiki/Three-state_logic */
  '74469': {
    name: '74x469',
    simpleName: '8 bit Sync Up/Down Counter',
    description: '8 bit synchronous up/down counter with parallel load and hold, tri-state (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    sequential: true,
    tags: ['counter', '8 bit', 'synchronous', 'up-down', 'load', 'tri-state'],
    guideOverview: 'The 74x469 is an 8 bit synchronous up/down counter with parallel load, hold enable (ENn), tri-state outputs (OEn), and ripple carry output (RCO). U_Dn selects counting direction. LOADn (active LOW) parallel-loads P0-P7 on the next clock. ENn inhibits counting without clearing the count. RCO signals overflow (up) or underflow (down).',
    guidePinDescriptions: {
      'OEn':   'Output Enable (active LOW). When HIGH, Q0-Q7 are tri-stated.',
      'CLK':   'Clock (rising edge).',
      'LOADn': 'Parallel Load (active LOW). Loads P0-P7 on rising CLK.',
      'U_Dn':  'Up/Down. HIGH = count up; LOW = count down.',
      'ENn':   'Enable (active LOW). When HIGH, counter holds current value.',
      'P0':    'Preset input bit 0.',
      'P1':    'Preset input bit 1.',
      'P2':    'Preset input bit 2.',
      'P3':    'Preset input bit 3.',
      'P4':    'Preset input bit 4.',
      'P5':    'Preset input bit 5.',
      'GND':   'Ground reference (pin 12).',
      'P6':    'Preset input bit 6.',
      'P7':    'Preset input bit 7.',
      'Q0':    'Counter output bit 0.',
      'Q1':    'Counter output bit 1.',
      'Q2':    'Counter output bit 2.',
      'Q3':    'Counter output bit 3.',
      'Q4':    'Counter output bit 4.',
      'Q5':    'Counter output bit 5.',
      'Q6':    'Counter output bit 6.',
      'Q7':    'Counter output bit 7 (MSB).',
      'RCO':   'Ripple Carry Out. HIGH on overflow (up) or underflow (down).',
      'VCC':   'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: 'Up/Down Counter with Preset',
        paragraphs: [
          'Load any start value via P0-P7 using LOADn, then count up or down. RCO provides the cascade signal for chaining multiple chips to build 16 bit or wider up/down counters.',
          'The hold mode (ENn=HIGH) is useful for pausing the count without losing the current value, for example during a bus read operation.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'OEn',   type: 'input' },
      { pin:  2, name: 'CLK',   type: 'input' },
      { pin:  3, name: 'LOADn', type: 'input' },
      { pin:  4, name: 'U_Dn',  type: 'input' },
      { pin:  5, name: 'ENn',   type: 'input' },
      { pin:  6, name: 'P0',    type: 'input' },
      { pin:  7, name: 'P1',    type: 'input' },
      { pin:  8, name: 'P2',    type: 'input' },
      { pin:  9, name: 'P3',    type: 'input' },
      { pin: 10, name: 'P4',    type: 'input' },
      { pin: 11, name: 'P5',    type: 'input' },
      { pin: 12, name: 'GND',   type: 'power' },
      { pin: 13, name: 'P6',    type: 'input' },
      { pin: 14, name: 'P7',    type: 'input' },
      { pin: 15, name: 'Q0',    type: 'output' },
      { pin: 16, name: 'Q1',    type: 'output' },
      { pin: 17, name: 'Q2',    type: 'output' },
      { pin: 18, name: 'Q3',    type: 'output' },
      { pin: 19, name: 'Q4',    type: 'output' },
      { pin: 20, name: 'Q5',    type: 'output' },
      { pin: 21, name: 'Q6',    type: 'output' },
      { pin: 22, name: 'Q7',    type: 'output' },
      { pin: 23, name: 'RCO',   type: 'output' },
      { pin: 24, name: 'VCC',   type: 'power' },
    ],
    gates: [
      { type: 'COUNTER_8BIT_UPDOWN_SYNC',
        inputs:  ['CLK','LOADn','U_Dn','ENn','OEn','P0','P1','P2','P3','P4','P5','P6','P7'],
        outputs: ['Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7','RCO'] },
    ],
  },

};
// end of CHIPS_BLOCK_27

