// chips63.js Block 63: 74x7404 .. 74x8240 (16 chips)
// Implementable: 74x7540, 74x7541, 74x7623, 74x7640, 74x7645, 74x7793, 74x8003
// Stubs:         74x7404, 74x7597, 74x7643, 74x7731, 74x8151, 74x8153, 74x8154, 74x8161, 74x8240

export const CHIPS_BLOCK_63 = {

  // ── 74x7404 320 bit FIFO (64×5), 18-pin ──────────────────────────────
  /* Primary source: 74x7404 datasheet   URL not yet verified.
     https://en.wikipedia.org/wiki/Queue_(abstract_data_type) */
  '74x7404': {
    name: '74x7404',
    simpleName: 'FIFO 64×5',
    description: '320 bit FIFO memory (64 words × 5 bits), tri state outputs (18-pin)',
    pins: 18,
    vcc: 18,
    gnd: 9,
    datasheet: '',
    tags: ['fifo', 'memory', '320 bit'],
    pinout: [
      { pin:  1, name: 'D0',  type: 'input'  },
      { pin:  2, name: 'D1',  type: 'input'  },
      { pin:  3, name: 'D2',  type: 'input'  },
      { pin:  4, name: 'D3',  type: 'input'  },
      { pin:  5, name: 'D4',  type: 'input'  },
      { pin:  6, name: 'SI',  type: 'input'  },
      { pin:  7, name: 'SO',  type: 'input'  },
      { pin:  8, name: 'MR',  type: 'input'  },
      { pin:  9, name: 'GND', type: 'power'  },
      { pin: 10, name: 'OE',  type: 'input'  },
      { pin: 11, name: 'FF',  type: 'output' },
      { pin: 12, name: 'HF',  type: 'output' },
      { pin: 13, name: 'Q4',  type: 'output' },
      { pin: 14, name: 'Q3',  type: 'output' },
      { pin: 15, name: 'Q2',  type: 'output' },
      { pin: 16, name: 'Q1',  type: 'output' },
      { pin: 17, name: 'Q0',  type: 'output' },
      { pin: 18, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['D0','D1','D2','D3','D4','SI','SO','MR','OE'],
        outputs: ['Q0','Q1','Q2','Q3','Q4','FF','HF'] },
    ],
  },

  // ── 74x7540 Octal Inv Buffer (Schmitt), 20-pin ───────────────────────
  /* Primary source: Texas Instruments, 74x7540 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls240.pdf */
  // Same as 74x240 but with Schmitt trigger inputs
  '74x7540': {
    name: '74x7540',
    simpleName: 'Octal Inv Buffer (ST)',
    description: 'Octal inverting buffer/line driver, Schmitt inputs, 3-state (20-pin)',
    pins: 20,
    vcc: 20,
    gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls240.pdf',
    tags: ['buffer', 'driver', 'octal', 'tri state', 'inverting', 'schmitt'],
    guideOverview: 'The 74x7540 is an octal inverting buffer and line driver with three state outputs, functionally aligned with the 240 family. The distinguishing feature of the 7540 family is Schmitt trigger input conditioning, which improves noise tolerance and makes the device better behaved with slow or imperfect input edges. In the simulator, the standard 240-style inverting tri state behavior is the right digital model.',
    guidePinDescriptions: {
      '1OE': 'Active LOW enable for bank 1.',
      '1A1': 'Input bit 1 of bank 1.',
      '2Y4': 'Inverting three state output bit 4 of bank 2.',
      '1A2': 'Input bit 2 of bank 1.',
      '2Y3': 'Inverting three state output bit 3 of bank 2.',
      '1A3': 'Input bit 3 of bank 1.',
      '2Y2': 'Inverting three state output bit 2 of bank 2.',
      '1A4': 'Input bit 4 of bank 1.',
      '2Y1': 'Inverting three state output bit 1 of bank 2.',
      'GND': 'Ground reference for the package.',
      '2A1': 'Input bit 1 of bank 2.',
      '1Y4': 'Inverting three state output bit 4 of bank 1.',
      '2A2': 'Input bit 2 of bank 2.',
      '1Y3': 'Inverting three state output bit 3 of bank 1.',
      '2A3': 'Input bit 3 of bank 2.',
      '1Y2': 'Inverting three state output bit 2 of bank 1.',
      '2A4': 'Input bit 4 of bank 2.',
      '1Y1': 'Inverting three state output bit 1 of bank 1.',
      '2OE': 'Active LOW enable for bank 2.',
      'VCC': 'Positive supply for the device.',
    },
    guideSections: [
      {
        title: '240-Style Inverting Driver',
        paragraphs: [
          'Each channel outputs the logical inverse of its input when enabled. The two bank enable pins let you control two groups of four outputs independently, which is useful in bus oriented designs.',
        ],
      },
      {
        title: 'Schmitt Input Advantage',
        paragraphs: [
          'Schmitt trigger inputs reduce chatter on slow, noisy, or bouncing signals. That does not change the truth table of the part, but it makes the hardware more tolerant of imperfect edges.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: '1OE', type: 'input'  },
      { pin:  2, name: '1A1', type: 'input'  },
      { pin:  3, name: '2Y4', type: 'output' },
      { pin:  4, name: '1A2', type: 'input'  },
      { pin:  5, name: '2Y3', type: 'output' },
      { pin:  6, name: '1A3', type: 'input'  },
      { pin:  7, name: '2Y2', type: 'output' },
      { pin:  8, name: '1A4', type: 'input'  },
      { pin:  9, name: '2Y1', type: 'output' },
      { pin: 10, name: 'GND', type: 'power'  },
      { pin: 11, name: '2A1', type: 'input'  },
      { pin: 12, name: '1Y4', type: 'output' },
      { pin: 13, name: '2A2', type: 'input'  },
      { pin: 14, name: '1Y3', type: 'output' },
      { pin: 15, name: '2A3', type: 'input'  },
      { pin: 16, name: '1Y2', type: 'output' },
      { pin: 17, name: '2A4', type: 'input'  },
      { pin: 18, name: '1Y1', type: 'output' },
      { pin: 19, name: '2OE', type: 'input'  },
      { pin: 20, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'TRI_NOT_LO', inputs: ['1A1', '1OE'], output: '1Y1' },
      { type: 'TRI_NOT_LO', inputs: ['1A2', '1OE'], output: '1Y2' },
      { type: 'TRI_NOT_LO', inputs: ['1A3', '1OE'], output: '1Y3' },
      { type: 'TRI_NOT_LO', inputs: ['1A4', '1OE'], output: '1Y4' },
      { type: 'TRI_NOT_LO', inputs: ['2A1', '2OE'], output: '2Y1' },
      { type: 'TRI_NOT_LO', inputs: ['2A2', '2OE'], output: '2Y2' },
      { type: 'TRI_NOT_LO', inputs: ['2A3', '2OE'], output: '2Y3' },
      { type: 'TRI_NOT_LO', inputs: ['2A4', '2OE'], output: '2Y4' },
    ],
  },

  // ── 74x7541 Octal Buffer (Schmitt), dual OE, 20-pin ──────────────────
  /* Primary source: Texas Instruments, 74x7541 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls541.pdf */
  // Same as 74x541 but with Schmitt trigger inputs
  '74x7541': {
    name: '74x7541',
    simpleName: 'Octal Buffer (ST)',
    description: 'Octal non inverting buffer/line driver, Schmitt inputs, 3-state (20-pin)',
    pins: 20,
    vcc: 20,
    gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls541.pdf',
    tags: ['buffer', 'driver', 'octal', 'tri state', 'schmitt'],
    guideOverview: 'The 74x7541 is an octal non inverting buffer and line driver organized like a 541-family device. It uses two enables to control all eight outputs and adds Schmitt trigger inputs for improved noise rejection. In the simulator, plain 541-style digital behavior is the correct reference because the Schmitt input detail affects input conditioning rather than logic function.',
    guidePinDescriptions: {
      'OE1': 'Enable input 1 for the output stage. In the 541 family both enables must be in their active states before outputs drive.',
      'A1': 'Input bit 1.',
      'A2': 'Input bit 2.',
      'A3': 'Input bit 3.',
      'A4': 'Input bit 4.',
      'A5': 'Input bit 5.',
      'A6': 'Input bit 6.',
      'A7': 'Input bit 7.',
      'A8': 'Input bit 8.',
      'GND': 'Ground reference for the package.',
      'Y8': 'Output bit 8.',
      'Y7': 'Output bit 7.',
      'Y6': 'Output bit 6.',
      'Y5': 'Output bit 5.',
      'Y4': 'Output bit 4.',
      'Y3': 'Output bit 3.',
      'Y2': 'Output bit 2.',
      'Y1': 'Output bit 1.',
      'OE2': 'Enable input 2 for the output stage.',
      'VCC': 'Positive supply for the device.',
    },
    guideSections: [
      {
        title: '541-Style Buffering',
        paragraphs: [
          'A non inverting line driver reproduces the input logic state at the output when enabled. This is useful for improving fan out, isolating a source from bus loading, and controlling when a byte wide signal may drive a shared bus.',
        ],
      },
      {
        title: 'Dual Enable Logic',
        paragraphs: [
          'The two enable arrangement is common in 541-family devices and lets system logic decide exactly when the outputs are allowed onto a bus. It is especially useful in microprocessor and peripheral interfaces.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'OE1', type: 'input'  },
      { pin:  2, name: 'A1',  type: 'input'  },
      { pin:  3, name: 'A2',  type: 'input'  },
      { pin:  4, name: 'A3',  type: 'input'  },
      { pin:  5, name: 'A4',  type: 'input'  },
      { pin:  6, name: 'A5',  type: 'input'  },
      { pin:  7, name: 'A6',  type: 'input'  },
      { pin:  8, name: 'A7',  type: 'input'  },
      { pin:  9, name: 'A8',  type: 'input'  },
      { pin: 10, name: 'GND', type: 'power'  },
      { pin: 11, name: 'Y8',  type: 'output' },
      { pin: 12, name: 'Y7',  type: 'output' },
      { pin: 13, name: 'Y6',  type: 'output' },
      { pin: 14, name: 'Y5',  type: 'output' },
      { pin: 15, name: 'Y4',  type: 'output' },
      { pin: 16, name: 'Y3',  type: 'output' },
      { pin: 17, name: 'Y2',  type: 'output' },
      { pin: 18, name: 'Y1',  type: 'output' },
      { pin: 19, name: 'OE2', type: 'input'  },
      { pin: 20, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'TRI_BUFFER_DUAL_OE', inputs: ['A1', 'OE1', 'OE2'], output: 'Y1' },
      { type: 'TRI_BUFFER_DUAL_OE', inputs: ['A2', 'OE1', 'OE2'], output: 'Y2' },
      { type: 'TRI_BUFFER_DUAL_OE', inputs: ['A3', 'OE1', 'OE2'], output: 'Y3' },
      { type: 'TRI_BUFFER_DUAL_OE', inputs: ['A4', 'OE1', 'OE2'], output: 'Y4' },
      { type: 'TRI_BUFFER_DUAL_OE', inputs: ['A5', 'OE1', 'OE2'], output: 'Y5' },
      { type: 'TRI_BUFFER_DUAL_OE', inputs: ['A6', 'OE1', 'OE2'], output: 'Y6' },
      { type: 'TRI_BUFFER_DUAL_OE', inputs: ['A7', 'OE1', 'OE2'], output: 'Y7' },
      { type: 'TRI_BUFFER_DUAL_OE', inputs: ['A8', 'OE1', 'OE2'], output: 'Y8' },
    ],
  },

  // ── 74x7597 8 bit Shift Register w/ Input Latches, 16-pin ────────────
  /* Primary source: 74x7597 datasheet   URL not yet verified.
     https://en.wikipedia.org/wiki/Shift_register */
  '74x7597': {
    name: '74x7597',
    simpleName: '8 bit Shift Reg',
    description: '8 bit shift register with input latches (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: '',
    tags: ['shift-register', 'latch', '8 bit'],
    pinout: [
      { pin:  1, name: 'B',    type: 'input'  },
      { pin:  2, name: 'C',    type: 'input'  },
      { pin:  3, name: 'D',    type: 'input'  },
      { pin:  4, name: 'E',    type: 'input'  },
      { pin:  5, name: 'STCK', type: 'input'  },
      { pin:  6, name: 'SHCK', type: 'input'  },
      { pin:  7, name: 'DS',   type: 'input'  },
      { pin:  8, name: 'GND',  type: 'power'  },
      { pin:  9, name: 'MR',   type: 'input'  },
      { pin: 10, name: 'Q7S',  type: 'output' },
      { pin: 11, name: 'F',    type: 'input'  },
      { pin: 12, name: 'G',    type: 'input'  },
      { pin: 13, name: 'H',    type: 'input'  },
      { pin: 14, name: 'A',    type: 'input'  },
      { pin: 15, name: 'PL',   type: 'input'  },
      { pin: 16, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['A','B','C','D','E','F','G','H','STCK','SHCK','DS','MR','PL'],
        outputs: ['Q7S'] },
    ],
  },

  // ── 74x7623 Octal Bus Transceiver (non inv, TS), 20-pin ──────────────
  /* Primary source: Texas Instruments, 74x7623 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls623.pdf
     https://en.wikipedia.org/wiki/Bus_transceiver */
  // Same as 74x245 transceiver
  '74x7623': {
    name: '74x7623',
    simpleName: 'Octal Xcvr (TS)',
    description: 'Octal bus transceiver, non inverting, tri state outputs (20-pin)',
    pins: 20,
    vcc: 20,
    gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls623.pdf',
    tags: ['transceiver', 'bus', 'octal', 'tri state', 'bidirectional'],
    guideOverview: 'The 74x7623 is an octal bidirectional bus transceiver in the same functional class as the 623 and 245 families. It lets one 8 bit bus drive another in either direction, while the enable input disconnects the buses when needed. For simulator purposes, ordinary non inverting octal transceiver behavior is the right abstraction for this family.',
    guidePinDescriptions: {
      'DIR': 'Direction control. It selects whether the A-side or the B-side is currently driving.',
      'A1': 'Bit 1 on the A-side bus.',
      'A2': 'Bit 2 on the A-side bus.',
      'A3': 'Bit 3 on the A-side bus.',
      'A4': 'Bit 4 on the A-side bus.',
      'A5': 'Bit 5 on the A-side bus.',
      'A6': 'Bit 6 on the A-side bus.',
      'A7': 'Bit 7 on the A-side bus.',
      'A8': 'Bit 8 on the A-side bus.',
      'GND': 'Ground reference for the package.',
      'B8': 'Bit 8 on the B-side bus.',
      'B7': 'Bit 7 on the B-side bus.',
      'B6': 'Bit 6 on the B-side bus.',
      'B5': 'Bit 5 on the B-side bus.',
      'B4': 'Bit 4 on the B-side bus.',
      'B3': 'Bit 3 on the B-side bus.',
      'B2': 'Bit 2 on the B-side bus.',
      'B1': 'Bit 1 on the B-side bus.',
      'OE': 'Output enable for the transceiver. Disable it to isolate both buses.',
      'VCC': 'Positive supply for the device.',
    },
    guideSections: [
      {
        title: 'Bidirectional Bus Control',
        paragraphs: [
          'A bus transceiver lets two byte wide signal groups share hardware without always being directly tied together. The direction control chooses which side is the source, and the enable control decides whether the connection is active at all.',
        ],
      },
      {
        title: 'Why It Is Useful',
        list: [
          'Connecting processors to peripherals.',
          'Isolating shared data buses.',
          'Preventing contention while still allowing reversible data flow.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'DIR', type: 'input' },
      { pin:  2, name: 'A1',  type: 'io'    },
      { pin:  3, name: 'A2',  type: 'io'    },
      { pin:  4, name: 'A3',  type: 'io'    },
      { pin:  5, name: 'A4',  type: 'io'    },
      { pin:  6, name: 'A5',  type: 'io'    },
      { pin:  7, name: 'A6',  type: 'io'    },
      { pin:  8, name: 'A7',  type: 'io'    },
      { pin:  9, name: 'A8',  type: 'io'    },
      { pin: 10, name: 'GND', type: 'power' },
      { pin: 11, name: 'B8',  type: 'io'    },
      { pin: 12, name: 'B7',  type: 'io'    },
      { pin: 13, name: 'B6',  type: 'io'    },
      { pin: 14, name: 'B5',  type: 'io'    },
      { pin: 15, name: 'B4',  type: 'io'    },
      { pin: 16, name: 'B3',  type: 'io'    },
      { pin: 17, name: 'B2',  type: 'io'    },
      { pin: 18, name: 'B1',  type: 'io'    },
      { pin: 19, name: 'OE',  type: 'input' },
      { pin: 20, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'TRANSCEIVER_8BIT',
        inputs:  ['A1','A2','A3','A4','A5','A6','A7','A8',
                  'B1','B2','B3','B4','B5','B6','B7','B8','DIR','OE'],
        outputs: ['A1','A2','A3','A4','A5','A6','A7','A8',
                  'B1','B2','B3','B4','B5','B6','B7','B8'] },
    ],
  },

  // ── 74x7640 Octal Bus Transceiver (inv, Schmitt, TS), 20-pin ─────────
  /* Primary source: Texas Instruments, 74x7640 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls640.pdf
     https://en.wikipedia.org/wiki/Bus_transceiver */
  // Same pinout as 74x620
  '74x7640': {
    name: '74x7640',
    simpleName: 'Octal Xcvr Inv (ST)',
    description: 'Octal inverting bus transceiver, Schmitt trigger inputs, tri state (20-pin)',
    pins: 20,
    vcc: 20,
    gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls640.pdf',
    tags: ['transceiver', 'bus', 'octal', 'tri state', 'inverting', 'schmitt'],
    guideOverview: 'The 74x7640 is an octal inverting bus transceiver functionally aligned with the 640 family. It transfers data between two 8 bit buses while inverting the logic state, and it adds Schmitt trigger inputs to improve hardware tolerance of slow or noisy signals. In the simulator, the correct model is an inverting octal transceiver with three state control.',
    guidePinDescriptions: {
      'DIR': 'Direction control. It selects which bus side is currently the source.',
      'A1': 'Bit 1 on the A-side bus.',
      'A2': 'Bit 2 on the A-side bus.',
      'A3': 'Bit 3 on the A-side bus.',
      'A4': 'Bit 4 on the A-side bus.',
      'A5': 'Bit 5 on the A-side bus.',
      'A6': 'Bit 6 on the A-side bus.',
      'A7': 'Bit 7 on the A-side bus.',
      'A8': 'Bit 8 on the A-side bus.',
      'GND': 'Ground reference for the package.',
      'B8': 'Bit 8 on the B-side bus.',
      'B7': 'Bit 7 on the B-side bus.',
      'B6': 'Bit 6 on the B-side bus.',
      'B5': 'Bit 5 on the B-side bus.',
      'B4': 'Bit 4 on the B-side bus.',
      'B3': 'Bit 3 on the B-side bus.',
      'B2': 'Bit 2 on the B-side bus.',
      'B1': 'Bit 1 on the B-side bus.',
      'OEn': 'Active LOW output enable. Pull LOW to let the transceiver drive.',
      'VCC': 'Positive supply for the device.',
    },
    guideSections: [
      {
        title: 'Inverting Transceiver Behavior',
        paragraphs: [
          'Unlike a non inverting transceiver, this family outputs the complement of the input data while transferring between the buses. That makes it useful in systems that already use active LOW signaling conventions or need inversion at the bus boundary.',
        ],
      },
      {
        title: 'Schmitt Inputs',
        paragraphs: [
          'Schmitt trigger inputs do not change the logical role of the part, but they do make it more tolerant of noisy or slowly changing source signals. The simulator therefore models the inversion and transceiver function, not the analog edge conditioning.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'DIR', type: 'input' },
      { pin:  2, name: 'A1',  type: 'io'    },
      { pin:  3, name: 'A2',  type: 'io'    },
      { pin:  4, name: 'A3',  type: 'io'    },
      { pin:  5, name: 'A4',  type: 'io'    },
      { pin:  6, name: 'A5',  type: 'io'    },
      { pin:  7, name: 'A6',  type: 'io'    },
      { pin:  8, name: 'A7',  type: 'io'    },
      { pin:  9, name: 'A8',  type: 'io'    },
      { pin: 10, name: 'GND', type: 'power' },
      { pin: 11, name: 'B8',  type: 'io'    },
      { pin: 12, name: 'B7',  type: 'io'    },
      { pin: 13, name: 'B6',  type: 'io'    },
      { pin: 14, name: 'B5',  type: 'io'    },
      { pin: 15, name: 'B4',  type: 'io'    },
      { pin: 16, name: 'B3',  type: 'io'    },
      { pin: 17, name: 'B2',  type: 'io'    },
      { pin: 18, name: 'B1',  type: 'io'    },
      { pin: 19, name: 'OEn', type: 'input' },
      { pin: 20, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'TRANSCEIVER_8BIT_INV',
        inputs:  ['A1','A2','A3','A4','A5','A6','A7','A8',
                  'B1','B2','B3','B4','B5','B6','B7','B8','DIR','OEn'],
        outputs: ['A1','A2','A3','A4','A5','A6','A7','A8',
                  'B1','B2','B3','B4','B5','B6','B7','B8'] },
    ],
  },

  // ── 74x7643 Octal Bus Transceiver (non inv/inv, Schmitt, TS), 20-pin ─
  /* Primary source: 74x7643 datasheet   URL not yet verified.
     https://en.wikipedia.org/wiki/Bus_transceiver */
  '74x7643': {
    name: '74x7643',
    simpleName: 'Octal Xcvr NI/Inv (ST)',
    description: 'Octal bus transceiver, non inverting/inverting, Schmitt, tri state (20-pin)',
    pins: 20,
    vcc: 20,
    gnd: 10,
    datasheet: '',
    tags: ['transceiver', 'bus', 'octal', 'tri state', 'mixed', 'schmitt'],
    pinout: [
      { pin:  1, name: 'DIR', type: 'input' },
      { pin:  2, name: 'A1',  type: 'io'    },
      { pin:  3, name: 'A2',  type: 'io'    },
      { pin:  4, name: 'A3',  type: 'io'    },
      { pin:  5, name: 'A4',  type: 'io'    },
      { pin:  6, name: 'A5',  type: 'io'    },
      { pin:  7, name: 'A6',  type: 'io'    },
      { pin:  8, name: 'A7',  type: 'io'    },
      { pin:  9, name: 'A8',  type: 'io'    },
      { pin: 10, name: 'GND', type: 'power' },
      { pin: 11, name: 'B8',  type: 'io'    },
      { pin: 12, name: 'B7',  type: 'io'    },
      { pin: 13, name: 'B6',  type: 'io'    },
      { pin: 14, name: 'B5',  type: 'io'    },
      { pin: 15, name: 'B4',  type: 'io'    },
      { pin: 16, name: 'B3',  type: 'io'    },
      { pin: 17, name: 'B2',  type: 'io'    },
      { pin: 18, name: 'B1',  type: 'io'    },
      { pin: 19, name: 'OEn', type: 'input' },
      { pin: 20, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'GENERIC_STUB',
        inputs:  ['A1','A2','A3','A4','A5','A6','A7','A8',
                  'B1','B2','B3','B4','B5','B6','B7','B8','DIR','OEn'],
        outputs: ['A1','A2','A3','A4','A5','A6','A7','A8',
                  'B1','B2','B3','B4','B5','B6','B7','B8'] },
    ],
  },

  // ── 74x7645 Octal Bus Transceiver (non inv, Schmitt, TS), 20-pin ─────
  /* Primary source: Texas Instruments, 74x7645 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls645.pdf
     https://en.wikipedia.org/wiki/Bus_transceiver */
  // Same as 74x245 but with Schmitt trigger inputs
  '74x7645': {
    name: '74x7645',
    simpleName: 'Octal Xcvr (ST)',
    description: 'Octal non inverting bus transceiver, Schmitt inputs, 3-state (20-pin)',
    pins: 20,
    vcc: 20,
    gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls645.pdf',
    tags: ['transceiver', 'bus', 'octal', 'tri state', 'schmitt'],
    guideOverview: 'The 74x7645 is an octal non inverting bus transceiver aligned with the 645 family. It connects two 8 bit buses and allows data to flow either direction under the control of the direction pin, with three state outputs preventing contention when the device is disabled. The Schmitt trigger detail improves hardware robustness, while the simulator models the standard non inverting transceiver behavior.',
    guidePinDescriptions: {
      'DIR': 'Direction control. It determines whether data flows from A to B or from B to A.',
      'A1': 'Bit 1 on the A-side bus.',
      'A2': 'Bit 2 on the A-side bus.',
      'A3': 'Bit 3 on the A-side bus.',
      'A4': 'Bit 4 on the A-side bus.',
      'A5': 'Bit 5 on the A-side bus.',
      'A6': 'Bit 6 on the A-side bus.',
      'A7': 'Bit 7 on the A-side bus.',
      'A8': 'Bit 8 on the A-side bus.',
      'GND': 'Ground reference for the package.',
      'B8': 'Bit 8 on the B-side bus.',
      'B7': 'Bit 7 on the B-side bus.',
      'B6': 'Bit 6 on the B-side bus.',
      'B5': 'Bit 5 on the B-side bus.',
      'B4': 'Bit 4 on the B-side bus.',
      'B3': 'Bit 3 on the B-side bus.',
      'B2': 'Bit 2 on the B-side bus.',
      'B1': 'Bit 1 on the B-side bus.',
      'OE': 'Output enable for the transceiver. Disable it to isolate the two buses.',
      'VCC': 'Positive supply for the device.',
    },
    guideSections: [
      {
        title: '645-Style Transceiver',
        paragraphs: [
          'This family is a straightforward reversible byte wide buffer. One side of the bus drives the other, and the direction input decides which side currently has control.',
        ],
      },
      {
        title: 'Breadboard Use',
        paragraphs: [
          'A part like this is useful when two subsystems must share data lines without directly fighting each other. It gives the designer explicit control over bus direction and bus ownership.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'DIR', type: 'input' },
      { pin:  2, name: 'A1',  type: 'io'    },
      { pin:  3, name: 'A2',  type: 'io'    },
      { pin:  4, name: 'A3',  type: 'io'    },
      { pin:  5, name: 'A4',  type: 'io'    },
      { pin:  6, name: 'A5',  type: 'io'    },
      { pin:  7, name: 'A6',  type: 'io'    },
      { pin:  8, name: 'A7',  type: 'io'    },
      { pin:  9, name: 'A8',  type: 'io'    },
      { pin: 10, name: 'GND', type: 'power' },
      { pin: 11, name: 'B8',  type: 'io'    },
      { pin: 12, name: 'B7',  type: 'io'    },
      { pin: 13, name: 'B6',  type: 'io'    },
      { pin: 14, name: 'B5',  type: 'io'    },
      { pin: 15, name: 'B4',  type: 'io'    },
      { pin: 16, name: 'B3',  type: 'io'    },
      { pin: 17, name: 'B2',  type: 'io'    },
      { pin: 18, name: 'B1',  type: 'io'    },
      { pin: 19, name: 'OE',  type: 'input' },
      { pin: 20, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'TRANSCEIVER_8BIT',
        inputs:  ['A1','A2','A3','A4','A5','A6','A7','A8',
                  'B1','B2','B3','B4','B5','B6','B7','B8','DIR','OE'],
        outputs: ['A1','A2','A3','A4','A5','A6','A7','A8',
                  'B1','B2','B3','B4','B5','B6','B7','B8'] },
    ],
  },

  // ── 74x7731 Quad 64 bit Static Shift Register, 16-pin ────────────────
  /* Primary source: 74x7731 datasheet   URL not yet verified.
     https://en.wikipedia.org/wiki/Shift_register */
  '74x7731': {
    name: '74x7731',
    simpleName: 'Quad 64b Shift Reg',
    description: 'Quad 64 bit static shift register (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: '',
    tags: ['shift-register', 'quad', '64 bit'],
    pinout: [
      { pin:  1, name: '1D',  type: 'input'  },
      { pin:  2, name: '1Q',  type: 'output' },
      { pin:  3, name: '2D',  type: 'input'  },
      { pin:  4, name: '2Q',  type: 'output' },
      { pin:  5, name: 'CP1', type: 'input'  },
      { pin:  6, name: 'CP2', type: 'input'  },
      { pin:  7, name: 'CP3', type: 'input'  },
      { pin:  8, name: 'GND', type: 'power'  },
      { pin:  9, name: 'CP4', type: 'input'  },
      { pin: 10, name: '3D',  type: 'input'  },
      { pin: 11, name: '3Q',  type: 'output' },
      { pin: 12, name: '4D',  type: 'input'  },
      { pin: 13, name: '4Q',  type: 'output' },
      { pin: 14, name: 'NC1', type: 'nc'     },
      { pin: 15, name: 'NC2', type: 'nc'     },
      { pin: 16, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['1D','2D','3D','4D','CP1','CP2','CP3','CP4'],
        outputs: ['1Q','2Q','3Q','4Q'] },
    ],
  },

  // ── 74x7793 8 bit Transparent Latch w/ Readback, 20-pin ──────────────
  /* Primary source: Texas Instruments, 74x7793 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls373.pdf
     https://en.wikipedia.org/wiki/Flip-flop_(electronics) */
  // Same as 74x373 D_LATCH_OCTAL_TRI
  '74x7793': {
    name: '74x7793',
    simpleName: 'Octal D Latch (RB)',
    description: '8 bit non inverting transparent latch with readback, tri state (20-pin)',
    pins: 20,
    vcc: 20,
    gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls373.pdf',
    tags: ['latch', 'd', 'octal', 'tri state', 'transparent', 'readback'],
    guideOverview: 'The 74x7793 is an octal transparent latch with three state outputs and readback oriented family behavior. In practical digital use it behaves like a 373-style byte wide latch: while latch enable is active the outputs follow the inputs, and when the latch closes the last state is held. This is useful for bus interfacing, temporary data storage, and output staging.',
    guidePinDescriptions: {
      'OE': 'Output enable for the three state outputs. Disable it to disconnect the latch from the bus.',
      '1Q': 'Latched output bit 1.',
      '1D': 'Data input bit 1.',
      '2D': 'Data input bit 2.',
      '2Q': 'Latched output bit 2.',
      '3D': 'Data input bit 3.',
      '3Q': 'Latched output bit 3.',
      '4D': 'Data input bit 4.',
      '4Q': 'Latched output bit 4.',
      'GND': 'Ground reference for the package.',
      'LE': 'Latch enable. When active, the latch is transparent; when inactive, the current byte is held.',
      '5Q': 'Latched output bit 5.',
      '5D': 'Data input bit 5.',
      '6D': 'Data input bit 6.',
      '6Q': 'Latched output bit 6.',
      '7D': 'Data input bit 7.',
      '7Q': 'Latched output bit 7.',
      '8D': 'Data input bit 8.',
      '8Q': 'Latched output bit 8.',
      'VCC': 'Positive supply for the device.',
    },
    guideSections: [
      {
        title: 'Transparent Latch Operation',
        paragraphs: [
          'When LE is active, each Q output follows its corresponding D input. When LE changes to the hold state, the current byte is stored and remains available until the latch is opened again.',
        ],
      },
      {
        title: 'Why Three State Helps',
        paragraphs: [
          'Three state outputs let the stored byte disconnect from a shared bus when another device needs to drive the same lines. That is why octal latches are common in bused digital designs.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'OE', type: 'input'  },
      { pin:  2, name: '1Q', type: 'output' },
      { pin:  3, name: '1D', type: 'input'  },
      { pin:  4, name: '2D', type: 'input'  },
      { pin:  5, name: '2Q', type: 'output' },
      { pin:  6, name: '3D', type: 'input'  },
      { pin:  7, name: '3Q', type: 'output' },
      { pin:  8, name: '4D', type: 'input'  },
      { pin:  9, name: '4Q', type: 'output' },
      { pin: 10, name: 'GND', type: 'power' },
      { pin: 11, name: 'LE', type: 'input'  },
      { pin: 12, name: '5Q', type: 'output' },
      { pin: 13, name: '5D', type: 'input'  },
      { pin: 14, name: '6D', type: 'input'  },
      { pin: 15, name: '6Q', type: 'output' },
      { pin: 16, name: '7D', type: 'input'  },
      { pin: 17, name: '7Q', type: 'output' },
      { pin: 18, name: '8D', type: 'input'  },
      { pin: 19, name: '8Q', type: 'output' },
      { pin: 20, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'D_LATCH_OCTAL_TRI',
        inputs: ['1D','2D','3D','4D','5D','6D','7D','8D','LE','OE'],
        outputs: ['1Q','2Q','3Q','4Q','5Q','6Q','7Q','8Q'] },
    ],
    sequential: true,
  },

  // ── 74x8003 Dual 2 input NAND, 8-pin ─────────────────────────────────
  /* Primary source: Texas Instruments, 74x8003 datasheet. [Online]. Available: https://www.ti.com/lit/gpn/sn74lvc2g00 */
  '74x8003': {
    name: '74x8003',
    simpleName: 'Dual NAND',
    description: 'Dual 2 input NAND gate (8-pin)',
    pins: 8,
    vcc: 8,
    gnd: 4,
    datasheet: 'https://www.ti.com/lit/gpn/sn74lvc2g00',
    tags: ['nand', 'gate', 'dual'],
    guideOverview: 'The 74x8003 is a simple dual 2 input NAND gate in an 8-pin package. A NAND gate outputs LOW only when both inputs are HIGH, which makes it one of the most flexible building blocks in digital logic. Small dual gate packages like this are useful when you only need one or two NAND functions and do not want a larger 14-pin logic package on the breadboard.',
    guidePinDescriptions: {
      '1A': 'Input A of NAND gate 1.',
      '1B': 'Input B of NAND gate 1.',
      '1Y': 'Output of gate 1. It is LOW only when both 1A and 1B are HIGH.',
      'GND': 'Ground reference for the package.',
      '2Y': 'Output of gate 2.',
      '2A': 'Input A of NAND gate 2.',
      '2B': 'Input B of NAND gate 2.',
      'VCC': 'Positive supply for the logic.',
    },
    guideSections: [
      {
        title: 'Why NAND Is So Common',
        paragraphs: [
          'A NAND gate is functionally complete, which means you can build any digital logic function from NAND gates alone. That is one reason small NAND packages appear everywhere in logic design.',
        ],
      },
      {
        title: 'Small Package Use',
        paragraphs: [
          'Dual gate packages are convenient when you only need a little glue logic. They save space and power compared with using a full four gate package for one small task.',
        ],
      },
    ],
    pinout: [
      { pin: 1, name: '1A',  type: 'input'  },
      { pin: 2, name: '1B',  type: 'input'  },
      { pin: 3, name: '1Y',  type: 'output' },
      { pin: 4, name: 'GND', type: 'power'  },
      { pin: 5, name: '2Y',  type: 'output' },
      { pin: 6, name: '2A',  type: 'input'  },
      { pin: 7, name: '2B',  type: 'input'  },
      { pin: 8, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'NAND', inputs: ['1A', '1B'], output: '1Y' },
      { type: 'NAND', inputs: ['2A', '2B'], output: '2Y' },
    ],
  },

  // ── 74x8151 10 bit Inv/NonInv Buffer (Schmitt, TS), 24-pin ───────────
  /* Primary source: Texas Instruments, 74x8151 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74lv8151.pdf */
  '74x8151': {
    name: '74x8151',
    simpleName: '10 bit Buffer (ST)',
    description: '10 bit inverting/non inverting buffer, Schmitt trigger, tri state (24-pin)',
    pins: 24,
    vcc: 24,
    gnd: 12,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74lv8151.pdf',
    tags: ['buffer', '10 bit', 'tri state', 'schmitt'],
    guideOverview: 'The 74x8151 is a 10 bit tri state buffer with mixed inverting and non inverting outputs controlled by a single active LOW output enable. Channels 1, 2, 8, 9, and 10 produce inverted outputs, while channels 3 through 7 produce non inverting outputs. When OE is LOW, all ten buffers drive their respective outputs; when OE is HIGH, all outputs go to high impedance. The Schmitt trigger inputs give the device noise immunity on slowly changing input signals.',
    guidePinDescriptions: {
      'OE': 'Output enable for the 10 bit buffer. Use it to connect or disconnect the outputs from the bus.',
      '1A': 'Input channel 1.',
      '1nY': 'Inverting output for channel 1.',
      '2A': 'Input channel 2.',
      '2nY': 'Inverting output for channel 2.',
      '3A': 'Input channel 3.',
      '3Y': 'Non inverting output for channel 3.',
      '4A': 'Input channel 4.',
      '4Y': 'Non inverting output for channel 4.',
      '5A': 'Input channel 5.',
      '5Y': 'Non inverting output for channel 5.',
      'GND': 'Ground reference for the device.',
      '6A': 'Input channel 6.',
      '6Y': 'Non inverting output for channel 6.',
      '7A': 'Input channel 7.',
      '7Y': 'Non inverting output for channel 7.',
      '8A': 'Input channel 8.',
      '8nY': 'Inverting output for channel 8.',
      '9A': 'Input channel 9.',
      '9nY': 'Inverting output for channel 9.',
      '10A': 'Input channel 10.',
      '10nY': 'Inverting output for channel 10.',
      'NC1': 'No internal connection. Leave unconnected.',
      'VCC': 'Positive supply for the device.',
    },
    guideSections: [
      {
        title: 'Mixed Polarity Buffering',
        paragraphs: [
          'This family combines inverting and non inverting outputs in one package, which can reduce part count when a bus needs both polarities available. That is especially useful in hardware with active LOW control lines mixed with active HIGH data paths.',
          'Channels 1 and 2 (1A→1nY, 2A→2nY) and channels 8 through 10 (8A→8nY, 9A→9nY, 10A→10nY) produce inverted outputs. Channels 3 through 7 (3A→3Y through 7A→7Y) produce non inverting outputs.',
        ],
      },
      {
        title: 'Output Enable',
        paragraphs: [
          'A single active LOW OE pin controls all ten outputs simultaneously. When OE is HIGH, all outputs float to high impedance, allowing the device to share a bus with other drivers.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'OE',   type: 'input'  },
      { pin:  2, name: '1A',   type: 'input'  },
      { pin:  3, name: '1nY',  type: 'output' },
      { pin:  4, name: '2A',   type: 'input'  },
      { pin:  5, name: '2nY',  type: 'output' },
      { pin:  6, name: '3A',   type: 'input'  },
      { pin:  7, name: '3Y',   type: 'output' },
      { pin:  8, name: '4A',   type: 'input'  },
      { pin:  9, name: '4Y',   type: 'output' },
      { pin: 10, name: '5A',   type: 'input'  },
      { pin: 11, name: '5Y',   type: 'output' },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: '6A',   type: 'input'  },
      { pin: 14, name: '6Y',   type: 'output' },
      { pin: 15, name: '7A',   type: 'input'  },
      { pin: 16, name: '7Y',   type: 'output' },
      { pin: 17, name: '8A',   type: 'input'  },
      { pin: 18, name: '8nY',  type: 'output' },
      { pin: 19, name: '9A',   type: 'input'  },
      { pin: 20, name: '9nY',  type: 'output' },
      { pin: 21, name: '10A',  type: 'input'  },
      { pin: 22, name: '10nY', type: 'output' },
      { pin: 23, name: 'NC1',  type: 'nc'     },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'TRI_NOT_LO',    inputs: ['1A',  'OE'], output: '1nY'  },
      { type: 'TRI_NOT_LO',    inputs: ['2A',  'OE'], output: '2nY'  },
      { type: 'TRI_BUFFER_LO', inputs: ['3A',  'OE'], output: '3Y'   },
      { type: 'TRI_BUFFER_LO', inputs: ['4A',  'OE'], output: '4Y'   },
      { type: 'TRI_BUFFER_LO', inputs: ['5A',  'OE'], output: '5Y'   },
      { type: 'TRI_BUFFER_LO', inputs: ['6A',  'OE'], output: '6Y'   },
      { type: 'TRI_BUFFER_LO', inputs: ['7A',  'OE'], output: '7Y'   },
      { type: 'TRI_NOT_LO',    inputs: ['8A',  'OE'], output: '8nY'  },
      { type: 'TRI_NOT_LO',    inputs: ['9A',  'OE'], output: '9nY'  },
      { type: 'TRI_NOT_LO',    inputs: ['10A', 'OE'], output: '10nY' },
    ],
  },

  // ── 74x8153 Serial-to-Parallel Interface, 20-pin ────────────────────
  // Source: Texas Instruments, "SN74LV8153 Serial-To-Parallel Interface",
  //   SCLS555 (June 2004). [Online]. Available:
  //   https://www.ti.com/lit/ds/symlink/sn74lv8153.pdf. Verified: Description +
  //   Features (p.1), N/PW package Terminal Assignment (top view, p.1), Function
  //   Table per buffer (p.1), Pin Description table (p.2), data-transmission
  //   protocol + Serial-Data Format / Timing Chart (p.3), and Logic Diagram
  //   (p.4), read as 300-dpi PDF page images (issues.md C4).
  //
  // PINOUT FIXED (issues.md C2 / CD4082 lesson): the previous hand-entered stub
  //   was wrong on essentially every pin. It invented a CLK/CSn/OEn/DIN clocked-
  //   shift-register interface with Qn7 + five NC pins and a single VCC/GND, and
  //   pointed `gates` at a NON-EXISTENT engine type (SHIFT_REG_8BIT_CS_OE) — the
  //   unregistered-gate-type bug that used to freeze the simulator when this part
  //   was placed (see js/debug/scenarios/all-chips-evaluate.mjs). The real
  //   SN74LV8153 has NO clock pin. Per SCLS555: 1=VCC1, 2-4=A0/A1/A2 (device
  //   address), 5=D (serial data in), 6=OUTSEL, 7=RESET, 8=OE (active LOW),
  //   9=SOUT, 10/11=GND (two ground pins), 12-19=Y7..Y0, 20=VCC2.
  //
  // LEFT AS A STUB ON PURPOSE (effort policy — not meaningfully simulatable here).
  //   The defining function is UART-format reception with AUTOMATIC DATA-RATE
  //   (baud) DETECTION and no external clock: the chip recovers its bit clock by
  //   measuring the analog time between the two start bits (frame = 2START-
  //   3ADDRESS-4DATA-1STOP, two frames per byte, LSB first; the three address
  //   bits must match the A0-A2 pins or the byte is dropped). This digital,
  //   settle-to-steady engine has no real-time axis and no clock pin to sample
  //   on, so that self-timed reception cannot be driven faithfully. Modeling only
  //   the output stage would leave the data register stuck at its reset value
  //   (Y0-Y7 could never respond to serial data), which would misrepresent the
  //   part; inventing a clock/load pin would falsify the real 20-pin device. So
  //   the gate stays GENERIC_STUB and the 'stub' tag is kept (hidden from the
  //   picker, browsable in docs). The pinout and docs are corrected to the real
  //   part regardless. See issues.md "74x8153".
  '74x8153': {
    name: '74x8153',
    simpleName: '8 bit Ser to Par',
    description: 'UART serial-to-parallel: 8 outputs, push-pull/open-collector (20-pin)',
    pins: 20,
    vcc: 20,
    gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74lv8153.pdf',
    tags: ['serial', 'parallel', 'interface', '8 bit', 'uart', 'stub'],
    guideOverview: 'The 74x8153 turns a single serial data wire into 8 parallel output lines, a common way to add outputs to a controller that is short on pins. A byte arrives on D as two UART-style frames: each frame carries two start bits, the chip address, four data bits and a stop bit. The chip reads its own address from the A0, A1 and A2 pins, so up to eight of these devices can share one D wire and each responds only to frames carrying its address. There is no clock pin   the chip works out the data rate on its own by timing the start bits. Once a full byte is received it appears on Y0 to Y7 and SOUT pulses to acknowledge. OUTSEL picks the output type (push-pull or open-collector for driving LEDs), OE forces the outputs to high impedance, and RESET clears them.',
    guidePinDescriptions: {
      'VCC1': 'Logic supply (3 to 5.5 V). Powers everything except the Y outputs.',
      'A0': 'Address pin 0. Sets one bit of this device address so several chips can share the D line.',
      'A1': 'Address pin 1.',
      'A2': 'Address pin 2.',
      'D': 'Serial data input. Receives the UART-format frames, least significant bit first.',
      'OUTSEL': 'Output type select. LOW = open-collector (outputs inverted, good for LEDs); HIGH = push-pull.',
      'RESET': 'Clears the output register, driving the outputs to their reset state.',
      'OE': 'Output enable (active LOW). HIGH forces Y0 to Y7 to high impedance.',
      'SOUT': 'Status output. Pulses when the latched output data changes. Powered from VCC1.',
      'GND': 'Ground (pin 10).',
      'GND2': 'Ground (pin 11). Both ground pins should be tied to ground.',
      'Y0': 'Parallel output bit 0 (LSB). Powered from VCC2.',
      'Y1': 'Parallel output bit 1.',
      'Y2': 'Parallel output bit 2.',
      'Y3': 'Parallel output bit 3.',
      'Y4': 'Parallel output bit 4.',
      'Y5': 'Parallel output bit 5.',
      'Y6': 'Parallel output bit 6.',
      'Y7': 'Parallel output bit 7 (MSB).',
      'VCC2': 'Output supply for Y0 to Y7. Can range from 3 to 12 V, set separately from VCC1.',
    },
    guideSections: [
      {
        title: 'One wire in, eight lines out',
        paragraphs: [
          'A serial to parallel interface takes data one bit at a time on a single input and rebuilds it into a full output byte. It trades speed for wires: a controller drives one line instead of eight, which matters when pins or board space are tight.',
          'A byte is sent as two frames on D, lower four bits then upper four. Each frame is two start bits, three address bits, four data bits and a stop bit, sent least significant bit first. The address bits in the frame must match this chip address (set on A0, A1, A2) or the byte is ignored, which is how one D wire can feed up to eight chips independently.',
        ],
      },
      {
        title: 'No clock pin',
        paragraphs: [
          'Most serial parts need a separate clock line to mark where each bit begins. This one does not. It measures the time between the two start bits at the front of every frame, uses that to work out the incoming data rate, then samples the rest of the frame at that rate. That is what the start-bit pattern, a 0 then a 1, is for.',
        ],
      },
      {
        title: 'Output type and enable',
        paragraphs: [
          'OUTSEL chooses how the outputs drive. In push-pull mode each output actively drives HIGH or LOW. In open-collector mode the output only pulls LOW, and inverts the data, which suits driving LEDs to ground from an external supply on VCC2 up to 12 V. Holding OE HIGH disconnects the outputs to high impedance so the chip can share a bus, and RESET clears the stored byte.',
        ],
        note: 'The UART-style reception here is self-timed with no clock pin, which this digital simulator cannot drive faithfully, so the 74x8153 is shown as a documentation reference rather than an interactive part.',
      },
    ],
    pinout: [
      { pin:  1, name: 'VCC1',   type: 'power'  },
      { pin:  2, name: 'A0',     type: 'input'  },
      { pin:  3, name: 'A1',     type: 'input'  },
      { pin:  4, name: 'A2',     type: 'input'  },
      { pin:  5, name: 'D',      type: 'input'  },
      { pin:  6, name: 'OUTSEL', type: 'input'  },
      { pin:  7, name: 'RESET',  type: 'input'  },
      { pin:  8, name: 'OE',     type: 'input'  },
      { pin:  9, name: 'SOUT',   type: 'output' },
      { pin: 10, name: 'GND',    type: 'power'  },
      { pin: 11, name: 'GND2',   type: 'power'  },
      { pin: 12, name: 'Y7',     type: 'output' },
      { pin: 13, name: 'Y6',     type: 'output' },
      { pin: 14, name: 'Y5',     type: 'output' },
      { pin: 15, name: 'Y4',     type: 'output' },
      { pin: 16, name: 'Y3',     type: 'output' },
      { pin: 17, name: 'Y2',     type: 'output' },
      { pin: 18, name: 'Y1',     type: 'output' },
      { pin: 19, name: 'Y0',     type: 'output' },
      { pin: 20, name: 'VCC2',   type: 'power'  },
    ],
    gates: [
      // Documentation stub: UART auto-baud reception has no clock pin and is not
      // faithfully drivable in this engine (see header comment + issues.md).
      { type: 'GENERIC_STUB',
        inputs:  ['A0', 'A1', 'A2', 'D', 'OUTSEL', 'RESET', 'OE'],
        outputs: ['Y0', 'Y1', 'Y2', 'Y3', 'Y4', 'Y5', 'Y6', 'Y7', 'SOUT'] },
    ],
    sequential: true,
  },

  // ── 74x8154 Dual 16 bit Counters w/ Output Registers, 20-pin ─────────
  // Source: Texas Instruments, "SN74LV8154 Dual 16-Bit Binary Counters With
  //   3-State Output Registers", SCLS589B (Aug. 2004, rev. May 2020).
  //   [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74lv8154.pdf.
  //   Verified: Pin Configuration + Pin Functions (Table 1, p.3), Function
  //   Table (Table 2, p.10), Functional Block Diagram (8.2, p.9) and Detailed
  //   Description (8.1/8.3, p.9), read as 200-dpi PDF page images (issues.md C4).
  // NOTE: the previous hand-entered stub pinout was wrong (it modeled the part
  //   as two 8-bit counters with RCO1/RCO2/CLR1/CLR2/OEn). The real device is
  //   dual 16-bit with four active-LOW byte gates GAL/GAU/GBL/GBU, one active-LOW
  //   clock enable CLKBEN, one async clear CCLR, and one carry RCOA. Rebuilt
  //   from the datasheet, not from a sibling (issues.md C2).
  '74x8154': {
    name: '74x8154',
    simpleName: 'Dual 16 bit Ctr',
    description: 'Dual 16 bit binary counters with a 3-state output register (20-pin)',
    pins: 20,
    vcc: 20,
    gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74lv8154.pdf',
    tags: ['counter', '16 bit', 'dual', 'register'],
    guideOverview: 'The 74x8154 holds two independent 16 bit binary counters, A and B, that share an 8 bit output bus. Counter A counts up on each rising edge of CLKA; counter B counts up on each rising edge of CLKB, but only while CLKBEN is LOW. A LOW on CCLR clears both counters to zero at once. A rising edge on RCLK copies both counters into a 32 bit storage register, so the outside world reads a frozen snapshot while the counters keep running. The bus only carries one byte at a time: four active LOW gates pick which byte appears on Y0 Y7   GAL for counter A low byte, GAU for A high byte, GBL for B low byte, GBU for B high byte. With all four gates HIGH the bus is high impedance. RCOA goes LOW when counter A is at full count (FFFF) and about to roll over; wire RCOA to CLKBEN to chain the two halves into one 32 bit counter.',
    guidePinDescriptions: {
      'CLKA': 'Clock for counter A. Counter A counts up on the rising edge.',
      'CLKB': 'Clock for counter B. Counter B counts up on the rising edge while CLKBEN is LOW.',
      'CLKBEN': 'Active LOW clock enable for counter B. LOW lets CLKB clock counter B; HIGH freezes it.',
      'CCLR': 'Active LOW clear. A LOW resets both counters to zero immediately, independent of any clock.',
      'RCLK': 'Register clock. A rising edge copies both counters into the storage register.',
      'GAL': 'Active LOW gate. A LOW puts the low byte of counter A onto Y0 Y7.',
      'GAU': 'Active LOW gate. A LOW puts the high byte of counter A onto Y0 Y7.',
      'GBL': 'Active LOW gate. A LOW puts the low byte of counter B onto Y0 Y7.',
      'GBU': 'Active LOW gate. A LOW puts the high byte of counter B onto Y0 Y7.',
      'RCOA': 'Active LOW carry. Goes LOW when counter A reaches full count (FFFF). Connect to CLKBEN to cascade.',
      'Y0': 'Output bus bit 0 (LSB of the selected byte), 3-state.',
      'Y1': 'Output bus bit 1, 3-state.',
      'Y2': 'Output bus bit 2, 3-state.',
      'Y3': 'Output bus bit 3, 3-state.',
      'Y4': 'Output bus bit 4, 3-state.',
      'Y5': 'Output bus bit 5, 3-state.',
      'Y6': 'Output bus bit 6, 3-state.',
      'Y7': 'Output bus bit 7 (MSB of the selected byte), 3-state.',
      'GND': 'Ground reference for the package.',
      'VCC': 'Positive supply for the device.',
    },
    guideSections: [
      {
        title: 'Counter plus storage register',
        paragraphs: [
          'Each counter has 32 bits of state to read but only 8 wires to read it on, so the chip splits the job. The counters never stop. RCLK takes a snapshot: on its rising edge both 16 bit counts are copied into a storage register and held there until the next RCLK edge. You read the snapshot at your leisure while the counters move on underneath.',
          'This is what makes the part useful as a frequency or event counter. A signal drives CLKA, you pulse RCLK once per measurement window, then read four bytes off the bus without ever racing a changing count.',
        ],
      },
      {
        title: 'Reading one byte at a time',
        paragraphs: [
          'The 32 bit snapshot is four bytes: A low, A high, B low, B high. Only one reaches the Y0 Y7 bus at a time, chosen by the four gates GAL, GAU, GBL, GBU. The gates are active LOW   pull exactly one LOW to read its byte. With all four HIGH the bus is high impedance, so several chips can share the same eight wires.',
        ],
      },
      {
        title: 'Cascading to 32 bits',
        paragraphs: [
          'RCOA goes LOW when counter A is full (FFFF) and would roll over on the next CLKA edge. CLKBEN is an active LOW enable on counter B. Tie RCOA to CLKBEN and drive both clocks together, and counter B advances exactly once each time counter A wraps   the two 16 bit halves act as one 32 bit counter.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'CLKA',   type: 'input'  },
      { pin:  2, name: 'CLKB',   type: 'input'  },
      { pin:  3, name: 'GAL',    type: 'input'  },
      { pin:  4, name: 'GAU',    type: 'input'  },
      { pin:  5, name: 'GBL',    type: 'input'  },
      { pin:  6, name: 'GBU',    type: 'input'  },
      { pin:  7, name: 'RCLK',   type: 'input'  },
      { pin:  8, name: 'RCOA',   type: 'output' },
      { pin:  9, name: 'CLKBEN', type: 'input'  },
      { pin: 10, name: 'GND',    type: 'power'  },
      { pin: 11, name: 'CCLR',   type: 'input'  },
      { pin: 12, name: 'Y7',     type: 'output' },
      { pin: 13, name: 'Y6',     type: 'output' },
      { pin: 14, name: 'Y5',     type: 'output' },
      { pin: 15, name: 'Y4',     type: 'output' },
      { pin: 16, name: 'Y3',     type: 'output' },
      { pin: 17, name: 'Y2',     type: 'output' },
      { pin: 18, name: 'Y1',     type: 'output' },
      { pin: 19, name: 'Y0',     type: 'output' },
      { pin: 20, name: 'VCC',    type: 'power'  },
    ],
    gates: [
      { type: 'DUAL_CTR16_REG_TRI',
        inputs:  ['CLKA', 'CLKB', 'CLKBEN', 'CCLR', 'RCLK', 'GAL', 'GAU', 'GBL', 'GBU'],
        outputs: ['Y0', 'Y1', 'Y2', 'Y3', 'Y4', 'Y5', 'Y6', 'Y7', 'RCOA'] },
    ],
    sequential: true,
  },

  // ── 74x8161 8 bit Synchronous Binary Counter, 24-pin ─────────────────
  /* Primary source: 74x8161 datasheet   URL not yet verified.
     https://en.wikipedia.org/wiki/Counter_(digital) */
  '74x8161': {
    name: '74x8161',
    simpleName: '8 bit Sync Counter',
    description: '8 bit synchronous binary counter (24-pin)',
    pins: 24,
    vcc: 24,
    gnd: 12,
    datasheet: '',
    tags: ['counter', '8 bit', 'synchronous', 'binary'],
    pinout: [
      { pin:  1, name: 'MR',   type: 'input'  },
      { pin:  2, name: 'CP',   type: 'input'  },
      { pin:  3, name: 'D0',   type: 'input'  },
      { pin:  4, name: 'D1',   type: 'input'  },
      { pin:  5, name: 'D2',   type: 'input'  },
      { pin:  6, name: 'D3',   type: 'input'  },
      { pin:  7, name: 'D4',   type: 'input'  },
      { pin:  8, name: 'D5',   type: 'input'  },
      { pin:  9, name: 'D6',   type: 'input'  },
      { pin: 10, name: 'D7',   type: 'input'  },
      { pin: 11, name: 'CEP',  type: 'input'  },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'CET',  type: 'input'  },
      { pin: 14, name: 'PE',   type: 'input'  },
      { pin: 15, name: 'Q0',   type: 'output' },
      { pin: 16, name: 'Q1',   type: 'output' },
      { pin: 17, name: 'Q2',   type: 'output' },
      { pin: 18, name: 'Q3',   type: 'output' },
      { pin: 19, name: 'Q4',   type: 'output' },
      { pin: 20, name: 'Q5',   type: 'output' },
      { pin: 21, name: 'Q6',   type: 'output' },
      { pin: 22, name: 'Q7',   type: 'output' },
      { pin: 23, name: 'TC',   type: 'output' },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB',
        inputs:  ['MR','CP','D0','D1','D2','D3','D4','D5','D6','D7','CEP','CET','PE'],
        outputs: ['Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7','TC'] },
    ],
  },

  // ── 74x8240 Octal Inv Buffer w/ JTAG, 24-pin ─────────────────────────
  /* Primary source: Texas Instruments, 74x8240 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74bct8240a.pdf */
  '74x8240': {
    name: '74x8240',
    simpleName: 'Octal Inv Buffer (JTAG)',
    description: 'Octal inverting buffer/line driver, JTAG boundary scan, 3-state (24-pin)',
    pins: 24,
    vcc: 24,
    gnd: 12,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74bct8240a.pdf',
    tags: ['buffer', 'driver', 'octal', 'tri state', 'inverting', 'jtag'],
    guideOverview: 'The 74x8240 is an octal inverting tri state buffer with boundary scan support. At the ordinary logic level it behaves exactly like a 74x240 inverting line driver: each 4 bit bank has its own active LOW output-enable, and every enabled output is the logical inverse of its input. The extra JTAG pins (TDI, TDO, TMS, TCK) support boundary scan test access in larger systems but do not affect normal logic operation. The simulator models the inverting buffer function; the JTAG TAP state machine is not simulated.',
    guidePinDescriptions: {
      'TDO': 'JTAG test data output.',
      '1OE': 'Enable control for bank 1 of the buffer outputs.',
      '1A1': 'Input bit 1 of bank 1.',
      '2Y4': 'Inverting tri state output bit 4 of bank 2.',
      '1A2': 'Input bit 2 of bank 1.',
      '2Y3': 'Inverting tri state output bit 3 of bank 2.',
      '1A3': 'Input bit 3 of bank 1.',
      '2Y2': 'Inverting tri state output bit 2 of bank 2.',
      '1A4': 'Input bit 4 of bank 1.',
      '2Y1': 'Inverting tri state output bit 1 of bank 2.',
      'TDI': 'JTAG test data input.',
      'GND': 'Ground reference for the device.',
      '2A1': 'Input bit 1 of bank 2.',
      '1Y4': 'Inverting tri state output bit 4 of bank 1.',
      '2A2': 'Input bit 2 of bank 2.',
      '1Y3': 'Inverting tri state output bit 3 of bank 1.',
      '2A3': 'Input bit 3 of bank 2.',
      '1Y2': 'Inverting tri state output bit 2 of bank 1.',
      '2A4': 'Input bit 4 of bank 2.',
      '1Y1': 'Inverting tri state output bit 1 of bank 1.',
      '2OE': 'Enable control for bank 2 of the buffer outputs.',
      'TMS': 'JTAG test mode select input.',
      'TCK': 'JTAG test clock input.',
      'VCC': 'Positive supply for the device.',
    },
    guideSections: [
      {
        title: '240-Style Driver With Boundary Scan',
        paragraphs: [
          'At its core, the device is an octal inverting tri state line driver. Pull 1OE LOW to enable the 1A→1Y inverting bank; pull 2OE LOW to enable the 2A→2Y bank. When an enable is HIGH the corresponding outputs float to high impedance.',
          'The JTAG pins (TDI, TDO, TMS, TCK) are present for manufacturing test and boundary scan chains. They do not affect normal logic operation. The simulator models the buffer function only; the JTAG TAP state machine is not simulated.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'TDO',  type: 'output' },
      { pin:  2, name: '1OE',  type: 'input'  },
      { pin:  3, name: '1A1',  type: 'input'  },
      { pin:  4, name: '2Y4',  type: 'output' },
      { pin:  5, name: '1A2',  type: 'input'  },
      { pin:  6, name: '2Y3',  type: 'output' },
      { pin:  7, name: '1A3',  type: 'input'  },
      { pin:  8, name: '2Y2',  type: 'output' },
      { pin:  9, name: '1A4',  type: 'input'  },
      { pin: 10, name: '2Y1',  type: 'output' },
      { pin: 11, name: 'TDI',  type: 'input'  },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: '2A1',  type: 'input'  },
      { pin: 14, name: '1Y4',  type: 'output' },
      { pin: 15, name: '2A2',  type: 'input'  },
      { pin: 16, name: '1Y3',  type: 'output' },
      { pin: 17, name: '2A3',  type: 'input'  },
      { pin: 18, name: '1Y2',  type: 'output' },
      { pin: 19, name: '2A4',  type: 'input'  },
      { pin: 20, name: '1Y1',  type: 'output' },
      { pin: 21, name: '2OE',  type: 'input'  },
      { pin: 22, name: 'TMS',  type: 'input'  },
      { pin: 23, name: 'TCK',  type: 'input'  },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'TRI_NOT_LO', inputs: ['1A1', '1OE'], output: '1Y1' },
      { type: 'TRI_NOT_LO', inputs: ['1A2', '1OE'], output: '1Y2' },
      { type: 'TRI_NOT_LO', inputs: ['1A3', '1OE'], output: '1Y3' },
      { type: 'TRI_NOT_LO', inputs: ['1A4', '1OE'], output: '1Y4' },
      { type: 'TRI_NOT_LO', inputs: ['2A1', '2OE'], output: '2Y1' },
      { type: 'TRI_NOT_LO', inputs: ['2A2', '2OE'], output: '2Y2' },
      { type: 'TRI_NOT_LO', inputs: ['2A3', '2OE'], output: '2Y3' },
      { type: 'TRI_NOT_LO', inputs: ['2A4', '2OE'], output: '2Y4' },
    ],
  },

};