// Chip definitions block 1
// Auto-generated from chips.js

export const CHIPS_BLOCK_1 = {
  // ── 7400: Quad 2 input NAND ──────────────────────────────────────────────
  /* Primary source: Texas Instruments, SN74LS00 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls00.pdf
     Universal gate claim: M. M. Mano and C. R. Kime, Logic and Computer Design Fundamentals, 3rd ed. Prentice Hall, 2004, p. 73.
     Also: Wikipedia contributors, "NAND gate," https://en.wikipedia.org/wiki/NAND_gate */
  '7400': {
    name: '74x00',
    simpleName: 'Quad NAND',
    description: 'Four 2 input NAND gates. (14-pin)',
    /* [1] Functional completeness of NAND: M. M. Mano and C. R. Kime, Logic and Computer Design Fundamentals, 3rd ed. Prentice Hall, 2004, p. 73. */
    guideOverview: 'The 74x00 is the quintessential 7400-series chip and one of the most widely used logic ICs ever made. It has four independent 2 input NAND gates. Because NAND is a universal gate you can implement AND, OR, NOT, and any other combinational function using only NAND gates this chip is a staple for prototyping and minimising part count.',/* [1] */
    guidePinDescriptions: {
      '1A': 'Input A of NAND gate 1.',
      '1B': 'Input B of NAND gate 1.',
      '1Y': 'Output of gate 1. LOW only when both 1A and 1B are HIGH.',
      '2A': 'Input A of NAND gate 2.',
      '2B': 'Input B of NAND gate 2.',
      '2Y': 'Output of gate 2. LOW only when both 2A and 2B are HIGH.',
      'GND': 'Ground reference (pin 7).',
      '3Y': 'Output of gate 3. LOW only when both 3A and 3B are HIGH.',
      '3A': 'Input A of NAND gate 3.',
      '3B': 'Input B of NAND gate 3.',
      '4Y': 'Output of gate 4. LOW only when both 4A and 4B are HIGH.',
      '4A': 'Input A of NAND gate 4.',
      '4B': 'Input B of NAND gate 4.',
      'VCC': 'Positive supply (+5 V) at pin 14.',
    },
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls00.pdf',
    tags: ['nand', 'gate', 'logic', 'quad'],
    guideSections: [
      {
        title: 'NAND Gate Logic',
        paragraphs: [
          'A NAND gate is an AND gate followed by an inverter. Its output is LOW only when all inputs are HIGH; it is HIGH for every other input combination.',
          /* [1] Functional completeness: Mano & Kime 2004, p. 73; Wikipedia, "NAND gate," https://en.wikipedia.org/wiki/NAND_gate */
          'Because NAND is functionally complete, any Boolean expression can be realised using only NAND gates. This makes the 74x00 one of the most versatile chips in the 7400 family.',/* [1] */
        ],
        formulas: [
          'Y = NOT(A AND B)',
          'A=0,B=0 → Y=1 | A=0,B=1 → Y=1 | A=1,B=0 → Y=1 | A=1,B=1 → Y=0',
        ],
      },
      {
        title: 'Common Uses',
        list: [
          'Building SR latches (two cross-coupled NAND gates).',
          'Inverting a signal: tie both inputs together.',
          'Constructing AND, OR, and NOT functions from a single package.',
          'Simple glue logic to combine control signals.',
        ],
      },
    ],
    pinout: [
      { pin: 1, name: '1A', type: 'input' },
      { pin: 2, name: '1B', type: 'input' },
      { pin: 3, name: '1Y', type: 'output' },
      { pin: 4, name: '2A', type: 'input' },
      { pin: 5, name: '2B', type: 'input' },
      { pin: 6, name: '2Y', type: 'output' },
      { pin: 7, name: 'GND', type: 'power' },
      { pin: 8, name: '3Y', type: 'output' },
      { pin: 9, name: '3A', type: 'input' },
      { pin: 10, name: '3B', type: 'input' },
      { pin: 11, name: '4Y', type: 'output' },
      { pin: 12, name: '4A', type: 'input' },
      { pin: 13, name: '4B', type: 'input' },
      { pin: 14, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'NAND', inputs: ['1A', '1B'], output: '1Y' },
      { type: 'NAND', inputs: ['2A', '2B'], output: '2Y' },
      { type: 'NAND', inputs: ['3A', '3B'], output: '3Y' },
      { type: 'NAND', inputs: ['4A', '4B'], output: '4Y' },
    ],
  },

  // ── 7402: Quad 2 input NOR ───────────────────────────────────────────────
  /* Primary source: Texas Instruments, SN74LS02 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls02.pdf
     Universal gate claim: M. M. Mano and C. R. Kime, Logic and Computer Design Fundamentals, 3rd ed. Prentice Hall, 2004, p. 73.
     Also: Wikipedia contributors, "NOR gate," https://en.wikipedia.org/wiki/NOR_gate */
  '7402': {
    name: '74x02',
    simpleName: 'Quad NOR',
    description: 'Four 2 input NOR gates. (14-pin)',
    /* [1] NOR functional completeness: Mano & Kime 2004, p. 73. SR latch from NOR gates: Wikipedia contributors, "Flip-flop (electronics)," https://en.wikipedia.org/wiki/Flip-flop_(electronics)#SR_NOR_latch */
    guideOverview: 'The 74x02 provides four independent 2 input NOR gates. Like NAND, NOR is a universal gate capable of implementing any logic function alone. Its output is HIGH only when all inputs are LOW. The unusual pinout outputs at pins 1, 4, 10, and 13 is worth double-checking before wiring. Two cross-coupled NOR gates form the classic SR latch.',/* [1] */
    guidePinDescriptions: {
      '1Y': 'Output of gate 1. HIGH only when both 1A and 1B are LOW.',
      '1A': 'Input A of NOR gate 1.',
      '1B': 'Input B of NOR gate 1.',
      '2Y': 'Output of gate 2. HIGH only when both 2A and 2B are LOW.',
      '2A': 'Input A of NOR gate 2.',
      '2B': 'Input B of NOR gate 2.',
      'GND': 'Ground reference (pin 7).',
      '3A': 'Input A of NOR gate 3.',
      '3B': 'Input B of NOR gate 3.',
      '3Y': 'Output of gate 3. HIGH only when both 3A and 3B are LOW.',
      '4A': 'Input A of NOR gate 4.',
      '4B': 'Input B of NOR gate 4.',
      '4Y': 'Output of gate 4. HIGH only when both 4A and 4B are LOW.',
      'VCC': 'Positive supply (+5 V) at pin 14.',
    },
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls02.pdf',
    tags: ['nor', 'gate', 'logic', 'quad'],
    guideSections: [
      {
        title: 'NOR Gate Logic',
        paragraphs: [
          'A NOR gate is an OR gate followed by an inverter. Its output is HIGH only when all inputs are LOW; it goes LOW the moment any input goes HIGH.',
          /* [1] NOR functional completeness: Mano & Kime 2004, p. 73; Wikipedia, "NOR gate," https://en.wikipedia.org/wiki/NOR_gate */
          'NOR is functionally complete: any logic function can be built from NOR gates alone, making it the NOR-gate analogue of the 74x00 NAND chip.',/* [1] */
        ],
        formulas: [
          'Y = NOT(A OR B)',
          'A=0,B=0 → Y=1 | A=0,B=1 → Y=0 | A=1,B=0 → Y=0 | A=1,B=1 → Y=0',
        ],
      },
      {
        title: 'SR Latch from NOR Gates',
        paragraphs: [
          'Connect the output of gate 1 to an input of gate 2 and the output of gate 2 to an input of gate 1. The free inputs become S (Set) and R (Reset). Pulling S HIGH forces Q HIGH; pulling R HIGH forces Q LOW. Both inputs LOW hold the last state.',
        ],
        note: 'S=1 and R=1 simultaneously is a forbidden state both outputs go LOW, producing undefined behavior when the inputs return to 0.',
      },
    ],
    pinout: [
      { pin: 1, name: '1Y', type: 'output' },
      { pin: 2, name: '1A', type: 'input' },
      { pin: 3, name: '1B', type: 'input' },
      { pin: 4, name: '2Y', type: 'output' },
      { pin: 5, name: '2A', type: 'input' },
      { pin: 6, name: '2B', type: 'input' },
      { pin: 7, name: 'GND', type: 'power' },
      { pin: 8, name: '3A', type: 'input' },
      { pin: 9, name: '3B', type: 'input' },
      { pin: 10, name: '3Y', type: 'output' },
      { pin: 11, name: '4A', type: 'input' },
      { pin: 12, name: '4B', type: 'input' },
      { pin: 13, name: '4Y', type: 'output' },
      { pin: 14, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'NOR', inputs: ['1A', '1B'], output: '1Y' },
      { type: 'NOR', inputs: ['2A', '2B'], output: '2Y' },
      { type: 'NOR', inputs: ['3A', '3B'], output: '3Y' },
      { type: 'NOR', inputs: ['4A', '4B'], output: '4Y' },
    ],
  },

  // ── 7404: Hex Inverter (NOT) ─────────────────────────────────────────────
  '7404': {
    name: '74x04',
    simpleName: 'Hex Inverter',
    description: 'Six independent inverters (NOT gates). (14-pin)',
    guideOverview: 'The 74x04 contains six independent single-input inverters (NOT gates). Each gate outputs the logical complement of its input: HIGH in gives LOW out and vice versa. Inverters are used everywhere from signal conditioning and level shifting to building oscillators and debounce circuits.',
    guidePinDescriptions: {
      '1A': 'Input of inverter 1.',
      '1Y': 'Output of inverter 1. Inverts 1A: HIGH when 1A is LOW.',
      '2A': 'Input of inverter 2.',
      '2Y': 'Output of inverter 2. Inverts 2A: HIGH when 2A is LOW.',
      '3A': 'Input of inverter 3.',
      '3Y': 'Output of inverter 3. Inverts 3A: HIGH when 3A is LOW.',
      'GND': 'Ground reference (pin 7).',
      '4Y': 'Output of inverter 4. Inverts 4A: HIGH when 4A is LOW.',
      '4A': 'Input of inverter 4.',
      '5Y': 'Output of inverter 5. Inverts 5A: HIGH when 5A is LOW.',
      '5A': 'Input of inverter 5.',
      '6Y': 'Output of inverter 6. Inverts 6A: HIGH when 6A is LOW.',
      '6A': 'Input of inverter 6.',
      'VCC': 'Positive supply (+5 V) at pin 14.',
    },
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls04.pdf',
    tags: ['not', 'inverter', 'gate', 'logic', 'hex', 'six', '1-input', 'buffer'],
    guideSections: [
      {
        title: 'Inverter (NOT Gate) Logic',
        paragraphs: [
          'A NOT gate simply inverts its input. If the input is HIGH (logic 1), the output is LOW (logic 0), and vice versa. This is the most fundamental logic operation.',
        ],
        formulas: ['Y = NOT A', 'A=0 → Y=1', 'A=1 → Y=0'],
      },
      {
        title: 'Common Uses',
        list: [
          'Inverting an active LOW enable signal to active HIGH (or vice versa).',
          'Building a simple RC oscillator: connect an inverter output through an RC network back to its input.',
          'Creating a non-inverting buffer by chaining two inverters.',
          'Signal path inversion in arithmetic and logic circuits.',
        ],
      },
    ],
    pinout: [
      { pin: 1, name: '1A', type: 'input' },
      { pin: 2, name: '1Y', type: 'output' },
      { pin: 3, name: '2A', type: 'input' },
      { pin: 4, name: '2Y', type: 'output' },
      { pin: 5, name: '3A', type: 'input' },
      { pin: 6, name: '3Y', type: 'output' },
      { pin: 7, name: 'GND', type: 'power' },
      { pin: 8, name: '4Y', type: 'output' },
      { pin: 9, name: '4A', type: 'input' },
      { pin: 10, name: '5Y', type: 'output' },
      { pin: 11, name: '5A', type: 'input' },
      { pin: 12, name: '6Y', type: 'output' },
      { pin: 13, name: '6A', type: 'input' },
      { pin: 14, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'NOT', inputs: ['1A'], output: '1Y' },
      { type: 'NOT', inputs: ['2A'], output: '2Y' },
      { type: 'NOT', inputs: ['3A'], output: '3Y' },
      { type: 'NOT', inputs: ['4A'], output: '4Y' },
      { type: 'NOT', inputs: ['5A'], output: '5Y' },
      { type: 'NOT', inputs: ['6A'], output: '6Y' },
    ],
  },

  // ── 7408: Quad 2 input AND ───────────────────────────────────────────────
  '7408': {
    name: '74x08',
    simpleName: 'Quad AND',
    description: 'Four independent 2 input AND gates. (14-pin)',
    guideOverview: 'The 74x08 packages four independent 2 input AND gates. An AND gate output is HIGH only when all inputs are HIGH useful for gating a signal, checking that multiple conditions are simultaneously true, or enabling an output only when two control signals agree.',
    guidePinDescriptions: {
      '1A': 'Input A of AND gate 1.',
      '1B': 'Input B of AND gate 1.',
      '1Y': 'Output of gate 1. HIGH only when both 1A and 1B are HIGH.',
      '2A': 'Input A of AND gate 2.',
      '2B': 'Input B of AND gate 2.',
      '2Y': 'Output of gate 2. HIGH only when both 2A and 2B are HIGH.',
      'GND': 'Ground reference (pin 7).',
      '3Y': 'Output of gate 3. HIGH only when both 3A and 3B are HIGH.',
      '3A': 'Input A of AND gate 3.',
      '3B': 'Input B of AND gate 3.',
      '4Y': 'Output of gate 4. HIGH only when both 4A and 4B are HIGH.',
      '4A': 'Input A of AND gate 4.',
      '4B': 'Input B of AND gate 4.',
      'VCC': 'Positive supply (+5 V) at pin 14.',
    },
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls08.pdf',
    tags: ['and', 'gate', 'logic', 'quad', 'four', '2 input'],
    guideSections: [
      {
        title: 'AND Gate Logic',
        paragraphs: [
          'An AND gate produces a HIGH output only when every input is HIGH. If any input is LOW the output is LOW. This makes it ideal for enabling or gating: hold one input HIGH to pass the other through; hold one input LOW to block the signal entirely.',
        ],
        formulas: [
          'Y = A AND B',
          'A=0,B=0 → Y=0 | A=0,B=1 → Y=0 | A=1,B=0 → Y=0 | A=1,B=1 → Y=1',
        ],
      },
      {
        title: 'Common Uses',
        list: [
          'Clock gating pass a clock signal only when an enable line is HIGH.',
          'Combining two active HIGH chip-select signals.',
          'Detecting a specific address bit pattern when combined with other logic.',
        ],
      },
    ],
    pinout: [
      { pin: 1, name: '1A', type: 'input' },
      { pin: 2, name: '1B', type: 'input' },
      { pin: 3, name: '1Y', type: 'output' },
      { pin: 4, name: '2A', type: 'input' },
      { pin: 5, name: '2B', type: 'input' },
      { pin: 6, name: '2Y', type: 'output' },
      { pin: 7, name: 'GND', type: 'power' },
      { pin: 8, name: '3Y', type: 'output' },
      { pin: 9, name: '3A', type: 'input' },
      { pin: 10, name: '3B', type: 'input' },
      { pin: 11, name: '4Y', type: 'output' },
      { pin: 12, name: '4A', type: 'input' },
      { pin: 13, name: '4B', type: 'input' },
      { pin: 14, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'AND', inputs: ['1A', '1B'], output: '1Y' },
      { type: 'AND', inputs: ['2A', '2B'], output: '2Y' },
      { type: 'AND', inputs: ['3A', '3B'], output: '3Y' },
      { type: 'AND', inputs: ['4A', '4B'], output: '4Y' },
    ],
  },

  // ── 7410: Triple 3 input NAND ───────────────────────────────────────────
  '7410': {
    name: '74x10',
    simpleName: 'Triple 3-in NAND',
    description: 'Three independent 3 input NAND gates. (14-pin)',
    guideOverview: 'The 74x10 provides three independent 3 input NAND gates. Adding a third input makes the NAND condition more selective: the output goes LOW only when all three inputs are simultaneously HIGH. This is handy for detecting a specific 3 bit combination or gating a signal based on two control conditions.',
    guidePinDescriptions: {
      '1A': 'Input A of NAND gate 1.',
      '1B': 'Input B of NAND gate 1.',
      '2A': 'Input A of NAND gate 2.',
      '2B': 'Input B of NAND gate 2.',
      '2C': 'Input C of NAND gate 2.',
      '2Y': 'Output of gate 2. LOW only when 2A, 2B, and 2C are all HIGH.',
      'GND': 'Ground reference (pin 7).',
      '3A': 'Input A of NAND gate 3.',
      '3B': 'Input B of NAND gate 3.',
      '3C': 'Input C of NAND gate 3.',
      '3Y': 'Output of gate 3. LOW only when 3A, 3B, and 3C are all HIGH.',
      '1Y': 'Output of gate 1. LOW only when 1A, 1B, and 1C are all HIGH.',
      '1C': 'Input C of NAND gate 1.',
      'VCC': 'Positive supply (+5 V) at pin 14.',
    },
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls10.pdf',
    tags: ['nand', 'gate', 'logic', 'triple', 'three', '3 input'],
    guideSections: [
      {
        title: '3-Input NAND Logic',
        paragraphs: [
          'A 3 input NAND gate extends the standard NAND concept: the output is LOW only when ALL three inputs are HIGH simultaneously. For all other input combinations the output remains HIGH.',
          'Unused inputs must not be left floating. Tie any unused input to VCC (keeps it HIGH, leaving the gate functional) or connect it to another used input.',
        ],
        formulas: ['Y = NOT(A AND B AND C)'],
      },
    ],
    pinout: [
      { pin: 1, name: '1A', type: 'input' },
      { pin: 2, name: '1B', type: 'input' },
      { pin: 3, name: '2A', type: 'input' },
      { pin: 4, name: '2B', type: 'input' },
      { pin: 5, name: '2C', type: 'input' },
      { pin: 6, name: '2Y', type: 'output' },
      { pin: 7, name: 'GND', type: 'power' },
      { pin: 8, name: '3A', type: 'input' },
      { pin: 9, name: '3B', type: 'input' },
      { pin: 10, name: '3C', type: 'input' },
      { pin: 11, name: '3Y', type: 'output' },
      { pin: 12, name: '1Y', type: 'output' },
      { pin: 13, name: '1C', type: 'input' },
      { pin: 14, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'NAND', inputs: ['1A', '1B', '1C'], output: '1Y' },
      { type: 'NAND', inputs: ['2A', '2B', '2C'], output: '2Y' },
      { type: 'NAND', inputs: ['3A', '3B', '3C'], output: '3Y' },
    ],
  },

  // ── 7420: Dual 4 input NAND ─────────────────────────────────────────────
  '7420': {
    name: '74x20',
    simpleName: 'Dual 4-in NAND',
    description: 'Two independent 4 input NAND gates. (14-pin)',
    guideOverview: 'The 74x20 contains two independent 4 input NAND gates. The output goes LOW only when all four inputs are simultaneously HIGH. With four inputs you can detect a specific 4 bit HIGH pattern in one gate, making this chip popular for address decoding and combinational hazard detection.',
    guidePinDescriptions: {
      '1A': 'Input A of NAND gate 1.',
      '1B': 'Input B of NAND gate 1.',
      'NC': 'Not connected leave unconnected.',
      '1C': 'Input C of NAND gate 1.',
      '1D': 'Input D of NAND gate 1.',
      '1Y': 'Output of gate 1. LOW only when 1A, 1B, 1C, and 1D are all HIGH.',
      'GND': 'Ground reference (pin 7).',
      '2Y': 'Output of gate 2. LOW only when 2A, 2B, 2C, and 2D are all HIGH.',
      '2A': 'Input A of NAND gate 2.',
      '2B': 'Input B of NAND gate 2.',
      '2C': 'Input C of NAND gate 2.',
      '2D': 'Input D of NAND gate 2.',
      'VCC': 'Positive supply (+5 V) at pin 14.',
    },
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls20.pdf',
    tags: ['nand', 'gate', 'logic', 'dual', '4 input'],
    guideSections: [
      {
        title: '4 Input NAND Logic',
        paragraphs: [
          'A 4 input NAND produces a LOW only when all four inputs are HIGH. This is useful for detecting a full 4 bit HIGH word or forming the active LOW output of a 4 input AND function.',
          'Unused inputs must be tied to VCC, not left floating, to prevent them from pulling the output LOW inadvertently.',
        ],
        formulas: ['Y = NOT(A AND B AND C AND D)'],
      },
    ],
    pinout: [
      { pin: 1, name: '1A', type: 'input', description: 'Gate 1 input A' },
      { pin: 2, name: '1B', type: 'input', description: 'Gate 1 input B' },
      { pin: 3, name: 'NC', type: 'nc', description: 'Not connected' },
      { pin: 4, name: '1C', type: 'input', description: 'Gate 1 input C' },
      { pin: 5, name: '1D', type: 'input', description: 'Gate 1 input D' },
      { pin: 6, name: '1Y', type: 'output', description: 'Gate 1 NAND output' },
      { pin: 7, name: 'GND', type: 'power', description: 'Ground (0V)' },
      { pin: 8, name: '2Y', type: 'output', description: 'Gate 2 NAND output' },
      { pin: 9, name: '2A', type: 'input', description: 'Gate 2 input A' },
      { pin: 10, name: '2B', type: 'input', description: 'Gate 2 input B' },
      { pin: 11, name: 'NC', type: 'nc', description: 'Not connected' },
      { pin: 12, name: '2C', type: 'input', description: 'Gate 2 input C' },
      { pin: 13, name: '2D', type: 'input', description: 'Gate 2 input D' },
      { pin: 14, name: 'VCC', type: 'power', description: 'Positive supply (+5V)' },
    ],
    gates: [
      { type: 'NAND', inputs: ['1A', '1B', '1C', '1D'], output: '1Y' },
      { type: 'NAND', inputs: ['2A', '2B', '2C', '2D'], output: '2Y' },
    ],
  },

  // ── 7432: Quad 2 input OR ────────────────────────────────────────────────
  '7432': {
    name: '74x32',
    simpleName: 'Quad 2 input OR',
    description: 'Four independent 2 input OR gates. (14-pin)',
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls32.pdf',
    tags: ['or', 'gate', 'logic', 'quad', '2 input'],
    guideOverview: 'The 74x32 packages four basic OR gates. An OR gate goes HIGH when at least one input is HIGH, making it useful for combining multiple trigger conditions where any one is enough to activate an output.',
    guidePinDescriptions: {
      '1A': 'Input A of OR gate 1.',
      '1B': 'Input B of OR gate 1.',
      '1Y': 'Output of gate 1. HIGH when 1A or 1B (or both) is HIGH.',
      '2A': 'Input A of OR gate 2.',
      '2B': 'Input B of OR gate 2.',
      '2Y': 'Output of gate 2. HIGH when 2A or 2B (or both) is HIGH.',
      'GND': 'Ground reference (pin 7).',
      '3Y': 'Output of gate 3. HIGH when 3A or 3B (or both) is HIGH.',
      '3A': 'Input A of OR gate 3.',
      '3B': 'Input B of OR gate 3.',
      '4Y': 'Output of gate 4. HIGH when 4A or 4B (or both) is HIGH.',
      '4A': 'Input A of OR gate 4.',
      '4B': 'Input B of OR gate 4.',
      'VCC': 'Positive supply (+5 V) at pin 14.',
    },
    guideSections: [
      {
        title: 'OR Gate Logic',
        paragraphs: [
          'An OR gate output is HIGH if any one or more of its inputs are HIGH. It is LOW only when all inputs are simultaneously LOW.',
        ],
        formulas: [
          'Y = A OR B',
          'A=0,B=0 → Y=0 | A=0,B=1 → Y=1 | A=1,B=0 → Y=1 | A=1,B=1 → Y=1',
        ],
      },
      {
        title: 'Common Uses',
        list: [
          'Combining two interrupt or alarm signals: fire the output if either source triggers.',
          'Generating an active HIGH chip enable from multiple sources.',
          'Merging reset conditions from different parts of a circuit.',
        ],
      },
    ],
    pinout: [
      { pin: 1, name: '1A', type: 'input', description: 'Gate 1 input A' },
      { pin: 2, name: '1B', type: 'input', description: 'Gate 1 input B' },
      { pin: 3, name: '1Y', type: 'output', description: 'Gate 1 output: HIGH when 1A or 1B (or both) is HIGH' },
      { pin: 4, name: '2A', type: 'input', description: 'Gate 2 input A' },
      { pin: 5, name: '2B', type: 'input', description: 'Gate 2 input B' },
      { pin: 6, name: '2Y', type: 'output', description: 'Gate 2 output: HIGH when 2A or 2B (or both) is HIGH' },
      { pin: 7, name: 'GND', type: 'power', description: 'Ground (0 V)' },
      { pin: 8, name: '3Y', type: 'output', description: 'Gate 3 output: HIGH when 3A or 3B (or both) is HIGH' },
      { pin: 9, name: '3A', type: 'input', description: 'Gate 3 input A' },
      { pin: 10, name: '3B', type: 'input', description: 'Gate 3 input B' },
      { pin: 11, name: '4Y', type: 'output', description: 'Gate 4 output: HIGH when 4A or 4B (or both) is HIGH' },
      { pin: 12, name: '4A', type: 'input', description: 'Gate 4 input A' },
      { pin: 13, name: '4B', type: 'input', description: 'Gate 4 input B' },
      { pin: 14, name: 'VCC', type: 'power', description: 'Positive supply (+5 V)' },
    ],
    gates: [
      { type: 'OR', inputs: ['1A', '1B'], output: '1Y' },
      { type: 'OR', inputs: ['2A', '2B'], output: '2Y' },
      { type: 'OR', inputs: ['3A', '3B'], output: '3Y' },
      { type: 'OR', inputs: ['4A', '4B'], output: '4Y' },
    ],
  },

  // ── 7486: Quad 2 input XOR ───────────────────────────────────────────────
  '7486': {
    name: '74x86',
    simpleName: 'Quad 2 input XOR Gate',
    description: 'Quad 2 input XOR gate output HIGH when inputs differ (14-pin)',
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls86a.pdf',
    tags: ['xor', 'gate', 'logic', 'quad', 'exclusive or', 'combinational'],
    guideOverview: 'The 74x86 gives you four independent 2 input XOR (exclusive-OR) gates. Each output is HIGH when its two inputs are different, and LOW when they are the same. XOR gates are useful for parity checking, binary addition, and controlled inversion.',
    guidePinDescriptions: {
      '1A': 'Input A of XOR gate 1.',
      '1B': 'Input B of XOR gate 1.',
      '1Y': 'Output of gate 1. HIGH when 1A ≠ 1B.',
      '2A': 'Input A of XOR gate 2.',
      '2B': 'Input B of XOR gate 2.',
      '2Y': 'Output of gate 2. HIGH when 2A ≠ 2B.',
      GND:  'Ground reference (pin 7).',
      '3Y': 'Output of gate 3. HIGH when 3A ≠ 3B.',
      '3A': 'Input A of XOR gate 3.',
      '3B': 'Input B of XOR gate 3.',
      '4Y': 'Output of gate 4. HIGH when 4A ≠ 4B.',
      '4A': 'Input A of XOR gate 4.',
      '4B': 'Input B of XOR gate 4.',
      VCC:  'Positive supply (5V) at pin 14.',
    },
    pinout: [
      { pin: 1, name: '1A', type: 'input' },
      { pin: 2, name: '1B', type: 'input' },
      { pin: 3, name: '1Y', type: 'output' },
      { pin: 4, name: '2A', type: 'input' },
      { pin: 5, name: '2B', type: 'input' },
      { pin: 6, name: '2Y', type: 'output' },
      { pin: 7, name: 'GND', type: 'power' },
      { pin: 8, name: '3Y', type: 'output' },
      { pin: 9, name: '3A', type: 'input' },
      { pin: 10, name: '3B', type: 'input' },
      { pin: 11, name: '4Y', type: 'output' },
      { pin: 12, name: '4A', type: 'input' },
      { pin: 13, name: '4B', type: 'input' },
      { pin: 14, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'XOR', inputs: ['1A', '1B'], output: '1Y' },
      { type: 'XOR', inputs: ['2A', '2B'], output: '2Y' },
      { type: 'XOR', inputs: ['3A', '3B'], output: '3Y' },
      { type: 'XOR', inputs: ['4A', '4B'], output: '4Y' },
    ],
    guideSections: [
      {
        title: 'XOR Gate Truth Table',
        paragraphs: [
          'A=0, B=0 → Y=0 | A=0, B=1 → Y=1 | A=1, B=0 → Y=1 | A=1, B=1 → Y=0',
          'A common use is as a controlled inverter: hold one input HIGH and the other input becomes inverted at the output. Hold one input LOW and the signal passes through unchanged.',
        ],
      },
    ],
  },

  // ── 74266: Quad 2 input XNOR ─────────────────────────────────────────────
  '74266': {
    name: '74x266',
    simpleName: '2 input XNOR',
    description: 'Quad 2 input XNOR gate (14-pin)',
    guideOverview: 'The 74x266 provides four independent 2 input XNOR (exclusive-NOR) gates with open-collector outputs. An XNOR gate is the complement of XOR: its output is HIGH when both inputs are the same (both LOW or both HIGH). This makes it ideal for equality comparison, parity checking, and controlled inversion. The open-collector outputs require external pull up resistors to VCC.',
    guidePinDescriptions: {
      '1A': 'Input A of XNOR gate 1.',
      '1B': 'Input B of XNOR gate 1.',
      '1Y': 'Open-collector output of gate 1. HIGH (via pull up) when 1A equals 1B.',
      '2A': 'Input A of XNOR gate 2.',
      '2B': 'Input B of XNOR gate 2.',
      '2Y': 'Open-collector output of gate 2. HIGH (via pull up) when 2A equals 2B.',
      'GND': 'Ground reference (pin 7).',
      '3Y': 'Open-collector output of gate 3. HIGH (via pull up) when 3A equals 3B.',
      '3A': 'Input A of XNOR gate 3.',
      '3B': 'Input B of XNOR gate 3.',
      '4Y': 'Open-collector output of gate 4. HIGH (via pull up) when 4A equals 4B.',
      '4A': 'Input A of XNOR gate 4.',
      '4B': 'Input B of XNOR gate 4.',
      'VCC': 'Positive supply (+5 V) at pin 14.',
    },
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls266.pdf',
    tags: ['xnor', 'gate', 'logic', 'quad', 'exclusive nor'],
    guideSections: [
      {
        title: 'XNOR Gate Logic',
        paragraphs: [
          'XNOR is the complement of XOR. The output is HIGH when both inputs are identical and LOW when they differ.',
          'Because the outputs are open-collector, you must add a pull up resistor (typically 1 10 kΩ) from each Y output to VCC. Open-collector outputs can also be wire-ANDed: connect several Y outputs together through a single pull up to implement a wired AND function.',
        ],
        formulas: [
          'Y = NOT(A XOR B)',
          'A=0,B=0 → Y=1 | A=0,B=1 → Y=0 | A=1,B=0 → Y=0 | A=1,B=1 → Y=1',
        ],
        note: 'Open-collector outputs require an external pull up resistor. Outputs left without a pull up will float HIGH and produce unreliable logic levels.',
      },
      {
        title: 'Common Uses',
        list: [
          '1 bit comparator: output HIGH when both bits are equal.',
          'Parity checking across multiple bits.',
          'Controlled inversion: input LOW passes signal; input HIGH inverts it same as XOR but with inverted sense.',
        ],
      },
    ],
    pinout: [
      { pin: 1, name: '1A', type: 'input' },
      { pin: 2, name: '1B', type: 'input' },
      { pin: 3, name: '1Y', type: 'output' },
      { pin: 4, name: '2A', type: 'input' },
      { pin: 5, name: '2B', type: 'input' },
      { pin: 6, name: '2Y', type: 'output' },
      { pin: 7, name: 'GND', type: 'power' },
      { pin: 8, name: '3Y', type: 'output' },
      { pin: 9, name: '3A', type: 'input' },
      { pin: 10, name: '3B', type: 'input' },
      { pin: 11, name: '4Y', type: 'output' },
      { pin: 12, name: '4A', type: 'input' },
      { pin: 13, name: '4B', type: 'input' },
      { pin: 14, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'XNOR', inputs: ['1A', '1B'], output: '1Y' },
      { type: 'XNOR', inputs: ['2A', '2B'], output: '2Y' },
      { type: 'XNOR', inputs: ['3A', '3B'], output: '3Y' },
      { type: 'XNOR', inputs: ['4A', '4B'], output: '4Y' },
    ],
  },

  // ── 7447: BCD to 7-segment decoder (common anode) ────────────────────────
  /* Primary source: Texas Instruments, SN74LS47 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls47.pdf
     BCD encoding: Wikipedia contributors, "Binary-coded decimal." Available: https://en.wikipedia.org/wiki/Binary-coded_decimal
     7-segment display: Wikipedia contributors, "Seven-segment display." Available: https://en.wikipedia.org/wiki/Seven-segment_display */
  '7447': {
    name: '74x47',
    simpleName: 'BCD to 7-Seg (CA)',
    description: 'BCD to 7-segment decoder/driver for common anode displays. (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls47.pdf',
    tags: ['7-segment', '7 seg', 'decoder', 'driver', 'bcd', 'display', 'seven segment', 'common anode', 'active low'],
    guideOverview: 'The 74x47 converts a 4 bit BCD value into the seven active LOW segment signals needed to drive a common anode 7-segment LED display. A LOW on any segment output turns that segment ON. Three control pins add flexibility: LT# (lamp test) forces all segments ON, BI#/RBO# blanks all segments, and RBI# enables leading zero suppression when the BCD input is 0000.',
    guidePinDescriptions: {
      'B': 'BCD input bit 1 (weight 2).',
      'C': 'BCD input bit 2 (weight 4).',
      'LT': 'Lamp Test, active LOW. Pull LOW to force all seven segments ON to test for burned-out LEDs. Tie HIGH for normal operation.',
      'BI/RBO': 'Blanking Input / Ripple Blank Output (active LOW, bidirectional). Drive LOW as an input to blank all segments. Acts as an output when RBI# zero suppression is active, going LOW to propagate blanking to adjacent digits.',
      'RBI': 'Ripple Blank Input, active LOW. When LOW and BCD input is 0000, all segments blank and RBO# goes LOW for leading zero suppression. Tie HIGH to disable zero suppression.',
      'D': 'BCD input bit 3 (MSB, weight 8).',
      'A': 'BCD input bit 0 (LSB, weight 1).',
      'GND': 'Ground reference (pin 8).',
      'e': 'Segment e driver, active LOW. Connect to segment e of the common anode display through a current limiting resistor.',
      'd': 'Segment d driver, active LOW.',
      'c': 'Segment c driver, active LOW.',
      'b': 'Segment b driver, active LOW.',
      'a': 'Segment a driver, active LOW.',
      'g': 'Segment g driver, active LOW.',
      'f': 'Segment f driver, active LOW.',
      'VCC': 'Positive supply (+5 V) at pin 16.',
    },
    guideSections: [
      {
        title: 'BCD to 7-Segment Decoding',
        paragraphs: [
          'BCD (Binary-Coded Decimal) encodes each decimal digit 0 9 as a 4 bit binary number. The 74x47 takes BCD inputs A (LSB), B, C, D (MSB) and drives each of the seven display segments LOW or HIGH to form the correct digit shape on a common anode display.',
          'Input values 10 15 (invalid BCD) produce non-standard display patterns and are generally avoided.',
        ],
      },
      {
        title: 'Zero Suppression',
        paragraphs: [
          'For multi-digit displays, leading zeros look odd (e.g., "007" instead of "7"). Connect RBO# of the most significant digit driver to RBI# of the next digit. When the MS digit is 0, it blanks itself and propagates the blank signal rightward until a non-zero digit is reached. Keep RBI# HIGH on the least significant digit to avoid blanking the units place when the number is zero.',
        ],
      },
    ],
    pinout: [
      { pin: 1,  name: 'B',      type: 'input',  description: 'BCD input bit 1' },
      { pin: 2,  name: 'C',      type: 'input',  description: 'BCD input bit 2' },
      { pin: 3,  name: 'LT',     type: 'input',  description: 'Lamp Test, active LOW: pull LOW to force all seven segments ON regardless of BCD input (tests that no segments are burned out)' },
      { pin: 4,  name: 'BI/RBO', type: 'input',  description: 'Blanking Input / Ripple Blank Output (bidirectional, active LOW): as input, pull LOW to blank (turn off) all segments; as output, goes LOW when RBI# blanking is applied to propagate zero suppression to adjacent digits' },
      { pin: 5,  name: 'RBI',    type: 'input',  description: 'Ripple Blank Input, active LOW: when LOW and BCD input is 0000, all segments are blanked and RBO# goes LOW (leading zero suppression)' },
      { pin: 6,  name: 'D',      type: 'input',  description: 'BCD input bit 3 (MSB)' },
      { pin: 7,  name: 'A',      type: 'input',  description: 'BCD input bit 0 (LSB)' },
      { pin: 8,  name: 'GND',    type: 'power',  description: 'Ground (0 V)' },
      { pin: 9,  name: 'e',      type: 'output', description: 'Segment e drive, active LOW (LOW = segment ON for common anode display)' },
      { pin: 10, name: 'd',      type: 'output', description: 'Segment d drive, active LOW' },
      { pin: 11, name: 'c',      type: 'output', description: 'Segment c drive, active LOW' },
      { pin: 12, name: 'b',      type: 'output', description: 'Segment b drive, active LOW' },
      { pin: 13, name: 'a',      type: 'output', description: 'Segment a drive, active LOW' },
      { pin: 14, name: 'g',      type: 'output', description: 'Segment g drive, active LOW' },
      { pin: 15, name: 'f',      type: 'output', description: 'Segment f drive, active LOW' },
      { pin: 16, name: 'VCC',    type: 'power',  description: 'Positive supply (+5 V)' },
    ],
    // BCD decoder logic is complex defined as a lookup table
    gates: [
      { type: 'BCD_7SEG', inputs: ['A', 'B', 'C', 'D'], outputs: ['a', 'b', 'c', 'd', 'e', 'f', 'g'] },
    ],
  },

  // ── 7448: BCD to 7-segment decoder (common cathode) ────────────────────
  /* Primary source: Texas Instruments, SN7448 datasheet. [Online]. Available: https://www.ti.com/lit/gpn/sn7448
     BCD encoding: Wikipedia contributors, "Binary-coded decimal." Available: https://en.wikipedia.org/wiki/Binary-coded_decimal */
  '7448': {
    name: '74x48',
    simpleName: 'BCD to 7-Seg (CC)',
    description: 'BCD to 7-segment decoder/driver for common cathode displays. (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/gpn/sn7448',
    tags: ['7-segment', '7 seg', 'decoder', 'driver', 'bcd', 'display', 'seven segment', 'common cathode', 'active high'],
    guideOverview: 'The 74x48 is the common cathode complement of the 74x47. It drives a 7-segment display with active HIGH outputs: a HIGH on any segment output turns that segment ON. Internal pull up resistors mean you can often connect display segments directly without external current limiting resistors, though resistors are still recommended for reliability. Shares the same pinout and control signals (LT#, BI#/RBO#, RBI#) as the 74x47.',
    guidePinDescriptions: {
      'B': 'BCD input bit 1 (weight 2).',
      'C': 'BCD input bit 2 (weight 4).',
      'LT': 'Lamp Test, active LOW. Pull LOW to force all seven segments ON. Tie HIGH for normal operation.',
      'BI/RBO': 'Blanking Input / Ripple Blank Output (active LOW, bidirectional). Drive LOW to blank all segments; acts as output for ripple-blank chaining.',
      'RBI': 'Ripple Blank Input, active LOW. Pull LOW to enable leading zero suppression when BCD input is 0000.',
      'D': 'BCD input bit 3 (MSB, weight 8).',
      'A': 'BCD input bit 0 (LSB, weight 1).',
      'GND': 'Ground reference (pin 8).',
      'e': 'Segment e driver, active HIGH. Connect to segment e of the common cathode display through a current limiting resistor.',
      'd': 'Segment d driver, active HIGH.',
      'c': 'Segment c driver, active HIGH.',
      'b': 'Segment b driver, active HIGH.',
      'a': 'Segment a driver, active HIGH.',
      'g': 'Segment g driver, active HIGH.',
      'f': 'Segment f driver, active HIGH.',
      'VCC': 'Positive supply (+5 V) at pin 16.',
    },
    guideSections: [
      {
        title: 'Common-Cathode vs Common-Anode',
        paragraphs: [
          'In a common cathode display, all LED cathodes share a single GND connection and individual segment anodes are driven HIGH to illuminate. The 74x48 provides active HIGH outputs to match this configuration directly.',
          'The 74x47 is the active LOW equivalent for common anode displays, where all anodes share VCC and segments are illuminated by pulling the cathode LOW. Use current limiting resistors (typically 150 470 Ω) on each segment line even though the 74x48 has internal pull ups.',
        ],
      },
    ],
    pinout: [
      { pin: 1,  name: 'B',      type: 'input',  description: 'BCD input bit 1' },
      { pin: 2,  name: 'C',      type: 'input',  description: 'BCD input bit 2' },
      { pin: 3,  name: 'LT',     type: 'input',  description: 'Lamp Test, active LOW: pull LOW to force all seven segments ON regardless of BCD input' },
      { pin: 4,  name: 'BI/RBO', type: 'input',  description: 'Blanking Input / Ripple Blank Output (bidirectional, active LOW): as input, pull LOW to blank all segments; as output, goes LOW when RBI# zero suppression is active' },
      { pin: 5,  name: 'RBI',    type: 'input',  description: 'Ripple Blank Input, active LOW: when LOW and BCD input is 0000, all segments are blanked (leading zero suppression)' },
      { pin: 6,  name: 'D',      type: 'input',  description: 'BCD input bit 3 (MSB)' },
      { pin: 7,  name: 'A',      type: 'input',  description: 'BCD input bit 0 (LSB)' },
      { pin: 8,  name: 'GND',    type: 'power',  description: 'Ground (0 V)' },
      { pin: 9,  name: 'e',      type: 'output', description: 'Segment e drive, active HIGH (HIGH = segment ON for common cathode display)' },
      { pin: 10, name: 'd',      type: 'output', description: 'Segment d drive, active HIGH' },
      { pin: 11, name: 'c',      type: 'output', description: 'Segment c drive, active HIGH' },
      { pin: 12, name: 'b',      type: 'output', description: 'Segment b drive, active HIGH' },
      { pin: 13, name: 'a',      type: 'output', description: 'Segment a drive, active HIGH' },
      { pin: 14, name: 'g',      type: 'output', description: 'Segment g drive, active HIGH' },
      { pin: 15, name: 'f',      type: 'output', description: 'Segment f drive, active HIGH' },
      { pin: 16, name: 'VCC',    type: 'power',  description: 'Positive supply (+5 V)' },
    ],
    gates: [
      { type: 'BCD_7SEG_CC', inputs: ['A', 'B', 'C', 'D'], outputs: ['a', 'b', 'c', 'd', 'e', 'f', 'g'] },
    ],
  },

  // ── 7474: Dual D flip-flop ───────────────────────────────────────────────
  /* Primary source: Texas Instruments, SN74LS74A datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls74a.pdf
     D flip-flop theory: Wikipedia contributors, "Flip-flop (electronics)." Available: https://en.wikipedia.org/wiki/Flip-flop_(electronics) */
  '7474': {
    name: '74x74',
    simpleName: 'Dual D Flip-Flop',
    description: 'Two independent positive-edge-triggered D flip-flops with active LOW asynchronous preset (PRE#) and clear (CLR#). (14-pin)',
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls74a.pdf',
    tags: ['flip-flop', 'flip flop', 'd', 'latch', 'sequential', 'register', 'memory', 'preset', 'clear'],
    guideOverview: 'The 74x74 packages two D flip-flops that capture their D input on the rising clock edge. Asynchronous active LOW preset and clear let you force the output HIGH or LOW at any time without waiting for a clock edge. Common uses include shift registers, counters, frequency dividers, and edge-triggered data storage.',
    guidePinDescriptions: {
      '1CLR': 'Flip-flop 1 asynchronous clear, active LOW. Pull LOW to force 1Q=0 at any time. Tie HIGH for normal clocked operation.',
      '1D': 'Flip-flop 1 data input. Captured by 1Q on the rising edge of 1CLK.',
      '1CLK': 'Flip-flop 1 clock. Q1 updates to D1 on the LOW→HIGH transition.',
      '1PRE': 'Flip-flop 1 asynchronous preset, active LOW. Pull LOW to force 1Q=1 at any time. Tie HIGH for normal clocked operation.',
      '1Q': 'Flip-flop 1 true output.',
      '1Qn': 'Flip-flop 1 complementary output (/Q1). Always the inverse of 1Q during normal operation.',
      'GND': 'Ground reference (pin 7).',
      '2Qn': 'Flip-flop 2 complementary output (/Q2).',
      '2Q': 'Flip-flop 2 true output.',
      '2PRE': 'Flip-flop 2 asynchronous preset, active LOW. Pull LOW to force 2Q=1.',
      '2CLK': 'Flip-flop 2 clock. Q2 updates to D2 on the LOW→HIGH transition.',
      '2D': 'Flip-flop 2 data input. Captured by 2Q on the rising edge of 2CLK.',
      '2CLR': 'Flip-flop 2 asynchronous clear, active LOW. Pull LOW to force 2Q=0.',
      'VCC': 'Positive supply (+5 V) at pin 14.',
    },
    guideSections: [
      {
        title: 'How the D Flip-Flop Works',
        paragraphs: [
          'A D (Data) flip-flop samples the D input at the moment a rising clock edge occurs (LOW→HIGH transition). Whatever logic level is on D at that instant is transferred to Q; Q holds that value until the next rising edge.',
          'The asynchronous PRE# and CLR# inputs override the clock. Pulling PRE# LOW forces Q=1 immediately; pulling CLR# LOW forces Q=0. Both must be HIGH for normal clocked operation.',
        ],
        note: 'Do not assert PRE# and CLR# simultaneously both Q and Q̄ would go HIGH, which is invalid for complementary outputs.',
      },
      {
        title: 'Common Uses',
        list: [
          'Frequency divider: connect Q̄ to D; the output toggles on every clock edge, dividing frequency by 2.',
          'Shift register: chain Q of one flip-flop to D of the next.',
          'Edge-detect and synchronisation: capture an asynchronous signal in a clocked domain.',
          'Simple 1 bit memory element.',
        ],
      },
    ],
    pinout: [
      { pin: 1,  name: '1CLR',  type: 'input',  description: 'Flip-flop 1 asynchronous clear, active LOW: forces Q1=0 regardless of clock' },
      { pin: 2,  name: '1D',    type: 'input',  description: 'Flip-flop 1 data input captured on rising clock edge' },
      { pin: 3,  name: '1CLK',  type: 'input',  description: 'Flip-flop 1 clock Q1 updates to D1 on rising edge (LOW→HIGH)' },
      { pin: 4,  name: '1PRE',  type: 'input',  description: 'Flip-flop 1 asynchronous preset, active LOW: forces Q1=1 regardless of clock' },
      { pin: 5,  name: '1Q',    type: 'output', description: 'Flip-flop 1 true output' },
      { pin: 6,  name: '1Qn',   type: 'output', description: 'Flip-flop 1 inverted output (/Q1)' },
      { pin: 7,  name: 'GND',   type: 'power',  description: 'Ground (0 V)' },
      { pin: 8,  name: '2Qn',   type: 'output', description: 'Flip-flop 2 inverted output (/Q2)' },
      { pin: 9,  name: '2Q',    type: 'output', description: 'Flip-flop 2 true output' },
      { pin: 10, name: '2PRE',  type: 'input',  description: 'Flip-flop 2 asynchronous preset, active LOW: forces Q2=1 regardless of clock' },
      { pin: 11, name: '2CLK',  type: 'input',  description: 'Flip-flop 2 clock Q2 updates to D2 on rising edge (LOW→HIGH)' },
      { pin: 12, name: '2D',    type: 'input',  description: 'Flip-flop 2 data input captured on rising clock edge' },
      { pin: 13, name: '2CLR',  type: 'input',  description: 'Flip-flop 2 asynchronous clear, active LOW: forces Q2=0 regardless of clock' },
      { pin: 14, name: 'VCC',   type: 'power',  description: 'Positive supply (+5 V)' },
    ],
    gates: [
      { type: 'D_FF', inputs: ['1D', '1CLK', '1PRE', '1CLR'], outputs: ['1Q', '1Qn'] },
      { type: 'D_FF', inputs: ['2D', '2CLK', '2PRE', '2CLR'], outputs: ['2Q', '2Qn'] },
    ],
    sequential: true,
  },

  // ── 7401: Quad 2 input NAND (open collector) ──────────────────────────────
  '7401': {
    name: '74x01',
    simpleName: 'Quad NAND (OC)',
    description: 'Quad 2 input NAND gate with open-collector outputs. (14-pin)',
    guideOverview: 'The 74x01 is a quad 2 input NAND gate identical in logic function to the 74x00 but with open-collector outputs. Open-collector means the output transistor can only pull the line LOW; an external pull up resistor is required to pull it HIGH. This allows outputs from multiple gates to be wire-ANDed on a single bus, and also allows the output to drive loads at voltages different from VCC.',
    guidePinDescriptions: {
      '1Y': 'Open-collector output of gate 1. LOW when both 1A and 1B are HIGH; otherwise high-impedance (floats HIGH via pull up).',
      '1A': 'Input A of NAND gate 1.',
      '1B': 'Input B of NAND gate 1.',
      '2Y': 'Open-collector output of gate 2.',
      '2A': 'Input A of NAND gate 2.',
      '2B': 'Input B of NAND gate 2.',
      'GND': 'Ground reference (pin 7).',
      '3A': 'Input A of NAND gate 3.',
      '3B': 'Input B of NAND gate 3.',
      '3Y': 'Open-collector output of gate 3.',
      '4A': 'Input A of NAND gate 4.',
      '4B': 'Input B of NAND gate 4.',
      '4Y': 'Open-collector output of gate 4.',
      'VCC': 'Positive supply (+5 V) at pin 14.',
    },
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn7401.pdf',
    tags: ['nand', 'gate', 'logic', 'quad', 'open collector', 'open-collector', '2 input', 'wired and'],
    guideSections: [
      {
        title: 'Open Collector Outputs',
        paragraphs: [
          'A standard totem-pole output can actively drive both HIGH and LOW. An open-collector output can only actively drive LOW; it relies on an external resistor to pull the line HIGH when the transistor is off.',
          'Wire-AND: if you connect several open-collector outputs to the same node with a single pull up, the node goes LOW whenever any one output pulls it LOW. This implements a wired AND function without additional logic gates.',
        ],
        note: 'Choose the pull up resistor value to limit current while meeting timing: 1 10 kΩ is typical for TTL-level signals at moderate speeds.',
      },
    ],
    pinout: [
      { pin: 1, name: '1Y', type: 'output' },
      { pin: 2, name: '1A', type: 'input' },
      { pin: 3, name: '1B', type: 'input' },
      { pin: 4, name: '2Y', type: 'output' },
      { pin: 5, name: '2A', type: 'input' },
      { pin: 6, name: '2B', type: 'input' },
      { pin: 7, name: 'GND', type: 'power' },
      { pin: 8, name: '3A', type: 'input' },
      { pin: 9, name: '3B', type: 'input' },
      { pin: 10, name: '3Y', type: 'output' },
      { pin: 11, name: '4A', type: 'input' },
      { pin: 12, name: '4B', type: 'input' },
      { pin: 13, name: '4Y', type: 'output' },
      { pin: 14, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'NAND', inputs: ['1A', '1B'], output: '1Y' },
      { type: 'NAND', inputs: ['2A', '2B'], output: '2Y' },
      { type: 'NAND', inputs: ['3A', '3B'], output: '3Y' },
      { type: 'NAND', inputs: ['4A', '4B'], output: '4Y' },
    ],
  },

  // ── 7403: Quad 2 input NAND (open collector) ────────────────────────────
  '7403': {
    name: '74x03',
    simpleName: 'Quad NAND (OC)',
    description: 'Quad 2 input NAND gate with open-collector outputs. (14-pin)',
    guideOverview: 'The 74x03 is the LS-family open-collector version of the quad 2 input NAND gate. Its pinout matches the standard 74x00 (inputs and outputs in the same positions) but with open-collector outputs, unlike the 74x01 which has a different pinout. Requires external pull up resistors; supports wire-ANDing and higher voltage output loads.',
    guidePinDescriptions: {
      '1A': 'Input A of NAND gate 1.',
      '1B': 'Input B of NAND gate 1.',
      '1Y': 'Open-collector output of gate 1. LOW when 1A and 1B are both HIGH.',
      '2A': 'Input A of NAND gate 2.',
      '2B': 'Input B of NAND gate 2.',
      '2Y': 'Open-collector output of gate 2.',
      'GND': 'Ground reference (pin 7).',
      '3Y': 'Open-collector output of gate 3.',
      '3A': 'Input A of NAND gate 3.',
      '3B': 'Input B of NAND gate 3.',
      '4Y': 'Open-collector output of gate 4.',
      '4A': 'Input A of NAND gate 4.',
      '4B': 'Input B of NAND gate 4.',
      'VCC': 'Positive supply (+5 V) at pin 14.',
    },
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls03.pdf',
    tags: ['nand', 'gate', 'logic', 'quad', 'open collector', 'open-collector', '2 input', 'wired and'],
    guideSections: [
      {
        title: 'Open Collector NAND',
        paragraphs: [
          'Logic function is identical to the 74x00: output LOW only when both inputs are HIGH. The open-collector output stage requires an external pull up resistor to produce a logic-HIGH level.',
          'The LS03 pinout is the same as the standard LS00, making it a pin-compatible drop-in for designs that need open-collector drive capability.',
        ],
      },
    ],
    pinout: [
      { pin: 1, name: '1A', type: 'input' },
      { pin: 2, name: '1B', type: 'input' },
      { pin: 3, name: '1Y', type: 'output' },
      { pin: 4, name: '2A', type: 'input' },
      { pin: 5, name: '2B', type: 'input' },
      { pin: 6, name: '2Y', type: 'output' },
      { pin: 7, name: 'GND', type: 'power' },
      { pin: 8, name: '3Y', type: 'output' },
      { pin: 9, name: '3A', type: 'input' },
      { pin: 10, name: '3B', type: 'input' },
      { pin: 11, name: '4Y', type: 'output' },
      { pin: 12, name: '4A', type: 'input' },
      { pin: 13, name: '4B', type: 'input' },
      { pin: 14, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'NAND', inputs: ['1A', '1B'], output: '1Y' },
      { type: 'NAND', inputs: ['2A', '2B'], output: '2Y' },
      { type: 'NAND', inputs: ['3A', '3B'], output: '3Y' },
      { type: 'NAND', inputs: ['4A', '4B'], output: '4Y' },
    ],
  },

  // ── 7405: Hex Inverter (open collector) ─────────────────────────────────
  '7405': {
    name: '74x05',
    simpleName: 'Hex Inverter (OC)',
    description: 'Six open-collector inverters (NOT gates). (14-pin)',
    guideOverview: 'The 74x05 provides six open-collector inverters. Logic function is identical to the 74x04 (NOT gate), but the outputs can only actively pull LOW. An external pull up resistor is required to produce a HIGH. This allows interfacing between different voltage levels and supports wire-ANDing of multiple inverter outputs.',
    guidePinDescriptions: {
      '1A': 'Input of inverter 1.',
      '1Y': 'Open-collector output of inverter 1. LOW when 1A is HIGH; high-impedance (floats HIGH via pull up) when 1A is LOW.',
      '2A': 'Input of inverter 2.',
      '2Y': 'Open-collector output of inverter 2.',
      '3A': 'Input of inverter 3.',
      '3Y': 'Open-collector output of inverter 3.',
      'GND': 'Ground reference (pin 7).',
      '4Y': 'Open-collector output of inverter 4.',
      '4A': 'Input of inverter 4.',
      '5Y': 'Open-collector output of inverter 5.',
      '5A': 'Input of inverter 5.',
      '6Y': 'Open-collector output of inverter 6.',
      '6A': 'Input of inverter 6.',
      'VCC': 'Positive supply (+5 V) at pin 14.',
    },
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls05.pdf',
    tags: ['not', 'inverter', 'gate', 'logic', 'hex', 'six', 'open collector', 'open-collector', '1-input'],
    guideSections: [
      {
        title: 'Open Collector Inverter',
        paragraphs: [
          'Each inverter drives its output LOW when the input is HIGH, and goes high-impedance (off) when the input is LOW. A pull up resistor (typically 1 10 kΩ) to VCC or another supply rail produces the HIGH level.',
          'The pull up can connect to a different voltage than VCC, making this chip useful for level-translation from 5V TTL to 3.3V or other voltages.',
        ],
      },
    ],
    pinout: [
      { pin: 1, name: '1A', type: 'input' },
      { pin: 2, name: '1Y', type: 'output' },
      { pin: 3, name: '2A', type: 'input' },
      { pin: 4, name: '2Y', type: 'output' },
      { pin: 5, name: '3A', type: 'input' },
      { pin: 6, name: '3Y', type: 'output' },
      { pin: 7, name: 'GND', type: 'power' },
      { pin: 8, name: '4Y', type: 'output' },
      { pin: 9, name: '4A', type: 'input' },
      { pin: 10, name: '5Y', type: 'output' },
      { pin: 11, name: '5A', type: 'input' },
      { pin: 12, name: '6Y', type: 'output' },
      { pin: 13, name: '6A', type: 'input' },
      { pin: 14, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'NOT', inputs: ['1A'], output: '1Y' },
      { type: 'NOT', inputs: ['2A'], output: '2Y' },
      { type: 'NOT', inputs: ['3A'], output: '3Y' },
      { type: 'NOT', inputs: ['4A'], output: '4Y' },
      { type: 'NOT', inputs: ['5A'], output: '5Y' },
      { type: 'NOT', inputs: ['6A'], output: '6Y' },
    ],
  },

  // ── 7406: Hex Inverter Buffer/Driver (open collector, high voltage) ───────────────────
  '7406': {
    name: '74x06',
    simpleName: 'Hex Inv Driver (OC)',
    description: 'Six open-collector inverting buffers/drivers rated for up to 30V and 40mA output sink current. (14-pin)',
    guideOverview: 'The 74x06 provides six open-collector inverting high-voltage drivers. Unlike standard TTL open-collector gates, each output can withstand up to 30 V and sink up to 40 mA. This makes the 74x06 the right choice for driving relays, indicator lamps, LEDs from a higher voltage supply, or interfacing a 5V TTL signal to a 12V or 24V system.',
    guidePinDescriptions: {
      '1A': 'Input of driver 1. TTL-level input (5V logic).',
      '1Y': 'Open-collector output of driver 1. Can sink up to 40 mA at up to 30 V when input is HIGH.',
      '2A': 'Input of driver 2.',
      '2Y': 'Open-collector output of driver 2.',
      '3A': 'Input of driver 3.',
      '3Y': 'Open-collector output of driver 3.',
      'GND': 'Ground reference (pin 7). Must be the common ground for both the TTL supply and the high-voltage load.',
      '4Y': 'Open-collector output of driver 4.',
      '4A': 'Input of driver 4.',
      '5Y': 'Open-collector output of driver 5.',
      '5A': 'Input of driver 5.',
      '6Y': 'Open-collector output of driver 6.',
      '6A': 'Input of driver 6.',
      'VCC': 'TTL supply (+5 V) at pin 14. The load supply can be different connect pull ups to the load voltage rail.',
    },
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn7406.pdf',
    tags: ['not', 'inverter', 'buffer', 'driver', 'gate', 'logic', 'hex', 'six', 'open collector', 'open-collector', 'high voltage', '30v', '40ma'],
    guideSections: [
      {
        title: 'High-Voltage Open Collector Driver',
        paragraphs: [
          'The output transistor is rated for 30 V collector-to-emitter and 40 mA continuous collector current. When the input is HIGH the transistor turns on and pulls the output low, sinking current from the load. When the input is LOW the transistor is off and the output floats.',
          'Connect the load between the higher supply (up to 30 V) and the output pin. Ensure the GND of the 74x06 is common with the load ground.',
        ],
        note: 'Do not exceed 30 V on any output pin or 40 mA per output. Exceeding these limits permanently damages the chip.',
      },
      {
        title: 'Common Uses',
        list: [
          'Driving indicator lamps or LEDs from a 12 V or 24 V supply.',
          'Controlling a relay coil (with a flyback diode) from a 12 V supply.',
          'Level-shifting a 5 V TTL signal to a higher-voltage logic family.',
        ],
      },
    ],
    pinout: [
      { pin: 1, name: '1A', type: 'input' },
      { pin: 2, name: '1Y', type: 'output' },
      { pin: 3, name: '2A', type: 'input' },
      { pin: 4, name: '2Y', type: 'output' },
      { pin: 5, name: '3A', type: 'input' },
      { pin: 6, name: '3Y', type: 'output' },
      { pin: 7, name: 'GND', type: 'power' },
      { pin: 8, name: '4Y', type: 'output' },
      { pin: 9, name: '4A', type: 'input' },
      { pin: 10, name: '5Y', type: 'output' },
      { pin: 11, name: '5A', type: 'input' },
      { pin: 12, name: '6Y', type: 'output' },
      { pin: 13, name: '6A', type: 'input' },
      { pin: 14, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'NOT', inputs: ['1A'], output: '1Y' },
      { type: 'NOT', inputs: ['2A'], output: '2Y' },
      { type: 'NOT', inputs: ['3A'], output: '3Y' },
      { type: 'NOT', inputs: ['4A'], output: '4Y' },
      { type: 'NOT', inputs: ['5A'], output: '5Y' },
      { type: 'NOT', inputs: ['6A'], output: '6Y' },
    ],
  },

  // ── 7407: Hex Buffer/Driver (open collector, non-inverting) ─────────────────────
  '7407': {
    name: '74x07',
    simpleName: 'Hex Buffer (OC)',
    description: 'Six non-inverting open-collector buffers/drivers. (14-pin)',
    guideOverview: 'The 74x07 is the non-inverting companion to the 74x06. It provides six open-collector buffer/driver outputs rated up to 30 V and 40 mA. The output follows the input logically: a HIGH input turns on the output transistor, sinking current from the load. Useful for driving active LOW peripherals while keeping 5V TTL control logic isolated from the load voltage.',
    guidePinDescriptions: {
      '1A': 'Input of buffer 1.',
      '1Y': 'Open-collector output of buffer 1. Conducts (pulls LOW) when 1A is HIGH.',
      '2A': 'Input of buffer 2.',
      '2Y': 'Open-collector output of buffer 2.',
      '3A': 'Input of buffer 3.',
      '3Y': 'Open-collector output of buffer 3.',
      'GND': 'Ground reference (pin 7). Common ground for TTL supply and load supply.',
      '4Y': 'Open-collector output of buffer 4.',
      '4A': 'Input of buffer 4.',
      '5Y': 'Open-collector output of buffer 5.',
      '5A': 'Input of buffer 5.',
      '6Y': 'Open-collector output of buffer 6.',
      '6A': 'Input of buffer 6.',
      'VCC': 'TTL supply (+5 V) at pin 14. Load pull up can be connected to a separate supply up to 30 V.',
    },
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn7407.pdf',
    tags: ['buffer', 'driver', 'gate', 'logic', 'hex', 'six', 'open collector', 'open-collector', 'non-inverting', 'high voltage', '30v'],
    guideSections: [
      {
        title: 'Non-Inverting Open Collector Buffer',
        paragraphs: [
          'Unlike the 74x06 which inverts the signal, the 74x07 passes the logic sense through: a HIGH input turns on the output transistor, sinking current. This makes it suited to driving active LOW peripherals (e.g., enable lines that activate on a LOW).',
          'The high-voltage rating (30 V, 40 mA) lets you sink current from loads powered by a separate supply while keeping control logic at 5 V.',
        ],
      },
    ],
    pinout: [
      { pin: 1, name: '1A', type: 'input' },
      { pin: 2, name: '1Y', type: 'output' },
      { pin: 3, name: '2A', type: 'input' },
      { pin: 4, name: '2Y', type: 'output' },
      { pin: 5, name: '3A', type: 'input' },
      { pin: 6, name: '3Y', type: 'output' },
      { pin: 7, name: 'GND', type: 'power' },
      { pin: 8, name: '4Y', type: 'output' },
      { pin: 9, name: '4A', type: 'input' },
      { pin: 10, name: '5Y', type: 'output' },
      { pin: 11, name: '5A', type: 'input' },
      { pin: 12, name: '6Y', type: 'output' },
      { pin: 13, name: '6A', type: 'input' },
      { pin: 14, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'BUFFER', inputs: ['1A'], output: '1Y' },
      { type: 'BUFFER', inputs: ['2A'], output: '2Y' },
      { type: 'BUFFER', inputs: ['3A'], output: '3Y' },
      { type: 'BUFFER', inputs: ['4A'], output: '4Y' },
      { type: 'BUFFER', inputs: ['5A'], output: '5Y' },
      { type: 'BUFFER', inputs: ['6A'], output: '6Y' },
    ],
  },

  // ── 7409: Quad 2 input AND (open collector) ─────────────────────────────
  '7409': {
    name: '74x09',
    simpleName: '2 input AND (OC)',
    description: 'Quad 2 input AND gate (open collector) (14-pin)',
    guideOverview: 'The 74x09 is a quad 2 input AND gate with open-collector outputs. The logic function is identical to the 74x08 (AND), but the open-collector outputs require external pull up resistors and allow wire-ANDing multiple outputs on a shared bus or driving loads at voltages above VCC.',
    guidePinDescriptions: {
      '1A': 'Input A of AND gate 1.',
      '1B': 'Input B of AND gate 1.',
      '1Y': 'Open-collector output of gate 1. Conducts (pulls LOW) when both 1A and 1B are HIGH.',
      '2A': 'Input A of AND gate 2.',
      '2B': 'Input B of AND gate 2.',
      '2Y': 'Open-collector output of gate 2.',
      'GND': 'Ground reference (pin 7).',
      '3Y': 'Open-collector output of gate 3.',
      '3A': 'Input A of AND gate 3.',
      '3B': 'Input B of AND gate 3.',
      '4Y': 'Open-collector output of gate 4.',
      '4A': 'Input A of AND gate 4.',
      '4B': 'Input B of AND gate 4.',
      'VCC': 'Positive supply (+5 V) at pin 14.',
    },
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls09.pdf',
    tags: ['and', 'gate', 'logic', 'quad', 'open collector'],
    guideSections: [
      {
        title: 'Open Collector AND Gate',
        paragraphs: [
          'The AND function (output HIGH only when all inputs HIGH) is implemented with an open-collector output stage. The output transistor is on (sinking) when the AND result is HIGH, and off when LOW. A pull up resistor to VCC (or a higher rail) is required to produce the HIGH level.',
          'Wire-ANDing multiple 74x09 outputs on one bus with a single pull up creates an AND of all the AND gate outputs.',
        ],
        note: 'Add pull up resistors on every output pin that will be used. Floating open-collector outputs produce undefined logic levels.',
      },
    ],
    pinout: [
      { pin: 1, name: '1A', type: 'input' },
      { pin: 2, name: '1B', type: 'input' },
      { pin: 3, name: '1Y', type: 'output' },
      { pin: 4, name: '2A', type: 'input' },
      { pin: 5, name: '2B', type: 'input' },
      { pin: 6, name: '2Y', type: 'output' },
      { pin: 7, name: 'GND', type: 'power' },
      { pin: 8, name: '3Y', type: 'output' },
      { pin: 9, name: '3A', type: 'input' },
      { pin: 10, name: '3B', type: 'input' },
      { pin: 11, name: '4Y', type: 'output' },
      { pin: 12, name: '4A', type: 'input' },
      { pin: 13, name: '4B', type: 'input' },
      { pin: 14, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'AND', inputs: ['1A', '1B'], output: '1Y' },
      { type: 'AND', inputs: ['2A', '2B'], output: '2Y' },
      { type: 'AND', inputs: ['3A', '3B'], output: '3Y' },
      { type: 'AND', inputs: ['4A', '4B'], output: '4Y' },
    ],
  },

  // ── 7411: Triple 3 input AND ────────────────────────────────────────────
  '7411': {
    name: '74x11',
    simpleName: 'Triple 3-in AND',
    description: 'Three independent 3 input AND gates. (14-pin)',
    guideOverview: 'The 74x11 provides three independent 3 input AND gates. The output is HIGH only when all three inputs are simultaneously HIGH. Useful for detecting a specific 3 bit HIGH condition or gating a signal based on two separate enable conditions simultaneously.',
    guidePinDescriptions: {
      '1A': 'Input A of AND gate 1.',
      '1B': 'Input B of AND gate 1.',
      '2A': 'Input A of AND gate 2.',
      '2B': 'Input B of AND gate 2.',
      '2C': 'Input C of AND gate 2.',
      '2Y': 'Output of gate 2. HIGH only when 2A, 2B, and 2C are all HIGH.',
      'GND': 'Ground reference (pin 7).',
      '3Y': 'Output of gate 3. HIGH only when 3A, 3B, and 3C are all HIGH.',
      '3A': 'Input A of AND gate 3.',
      '3B': 'Input B of AND gate 3.',
      '3C': 'Input C of AND gate 3.',
      '1Y': 'Output of gate 1. HIGH only when 1A, 1B, and 1C are all HIGH.',
      '1C': 'Input C of AND gate 1.',
      'VCC': 'Positive supply (+5 V) at pin 14.',
    },
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls11.pdf',
    tags: ['and', 'gate', 'logic', 'triple', 'three', '3 input'],
    guideSections: [
      {
        title: '3-Input AND Logic',
        paragraphs: [
          'Extends the AND concept to three inputs. All three must be HIGH for the output to be HIGH. Tie unused inputs to VCC to keep them from pulling the output LOW.',
        ],
        formulas: ['Y = A AND B AND C'],
      },
    ],
    pinout: [
      { pin: 1, name: '1A', type: 'input' },
      { pin: 2, name: '1B', type: 'input' },
      { pin: 3, name: '2A', type: 'input' },
      { pin: 4, name: '2B', type: 'input' },
      { pin: 5, name: '2C', type: 'input' },
      { pin: 6, name: '2Y', type: 'output' },
      { pin: 7, name: 'GND', type: 'power' },
      { pin: 8, name: '3Y', type: 'output' },
      { pin: 9, name: '3A', type: 'input' },
      { pin: 10, name: '3B', type: 'input' },
      { pin: 11, name: '3C', type: 'input' },
      { pin: 12, name: '1Y', type: 'output' },
      { pin: 13, name: '1C', type: 'input' },
      { pin: 14, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'AND', inputs: ['1A', '1B', '1C'], output: '1Y' },
      { type: 'AND', inputs: ['2A', '2B', '2C'], output: '2Y' },
      { type: 'AND', inputs: ['3A', '3B', '3C'], output: '3Y' },
    ],
  },

  // ── 7412: Triple 3 input NAND (open collector) ─────────────────────────
  '7412': {
    name: '74x12',
    simpleName: 'Triple 3-in NAND (OC)',
    description: 'Three 3 input NAND gates with open-collector outputs. (14-pin)',
    guideOverview: 'The 74x12 combines three 3 input NAND gates with open-collector outputs. The output is LOW only when all three inputs are HIGH; otherwise the open-collector output is high-impedance. Requires pull up resistors. Allows wire-ANDing and interfacing to higher-voltage loads.',
    guidePinDescriptions: {
      '1A': 'Input A of NAND gate 1.',
      '1B': 'Input B of NAND gate 1.',
      '2A': 'Input A of NAND gate 2.',
      '2B': 'Input B of NAND gate 2.',
      '2C': 'Input C of NAND gate 2.',
      '2Y': 'Open-collector output of gate 2. LOW when 2A, 2B, and 2C are all HIGH.',
      'GND': 'Ground reference (pin 7).',
      '3A': 'Input A of NAND gate 3.',
      '3B': 'Input B of NAND gate 3.',
      '3C': 'Input C of NAND gate 3.',
      '3Y': 'Open-collector output of gate 3.',
      '1Y': 'Open-collector output of gate 1.',
      '1C': 'Input C of NAND gate 1.',
      'VCC': 'Positive supply (+5 V) at pin 14.',
    },
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls12.pdf',
    tags: ['nand', 'gate', 'logic', 'triple', 'three', '3 input', 'open collector', 'open-collector', 'wired and'],
    guideSections: [
      {
        title: 'Open Collector 3-Input NAND',
        paragraphs: [
          'Logic function: Y = NOT(A AND B AND C). The output pulls LOW only when all three inputs are HIGH. An external pull up resistor is required for each output.',
          'Wire-ANDing: connect multiple open-collector NAND outputs to the same node with one pull up to AND all NAND results.',
        ],
      },
    ],
    pinout: [
      { pin: 1, name: '1A', type: 'input' },
      { pin: 2, name: '1B', type: 'input' },
      { pin: 3, name: '2A', type: 'input' },
      { pin: 4, name: '2B', type: 'input' },
      { pin: 5, name: '2C', type: 'input' },
      { pin: 6, name: '2Y', type: 'output' },
      { pin: 7, name: 'GND', type: 'power' },
      { pin: 8, name: '3Y', type: 'output' },
      { pin: 9, name: '3A', type: 'input' },
      { pin: 10, name: '3B', type: 'input' },
      { pin: 11, name: '3C', type: 'input' },
      { pin: 12, name: '1Y', type: 'output' },
      { pin: 13, name: '1C', type: 'input' },
      { pin: 14, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'NAND', inputs: ['1A', '1B', '1C'], output: '1Y' },
      { type: 'NAND', inputs: ['2A', '2B', '2C'], output: '2Y' },
      { type: 'NAND', inputs: ['3A', '3B', '3C'], output: '3Y' },
    ],
  },

  // ── 7413: Dual 4 input NAND (Schmitt trigger) ──────────────────────────
  /* Primary source: Texas Instruments, SN74LS13 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls13.pdf
     Schmitt trigger hysteresis: Wikipedia contributors, "Schmitt trigger." Available: https://en.wikipedia.org/wiki/Schmitt_trigger */
  '7413': {
    name: '74x13',
    simpleName: 'Dual 4-in NAND (Schmitt)',
    description: 'Dual 4 input NAND gate with Schmitt-trigger inputs. (14-pin)',
    guideOverview: 'The 74x13 provides two independent 4 input NAND gates where every input passes through a Schmitt trigger. A Schmitt trigger uses two different threshold voltages a higher one for switching HIGH→LOW and a lower one for switching LOW→HIGH creating hysteresis. This makes the inputs immune to slow transitions, noise, and ringing on input signals, especially useful for capacitive RC inputs or mechanical switch debouncing.',
    guidePinDescriptions: {
      '1A': 'Schmitt-trigger input A of NAND gate 1.',
      '1B': 'Schmitt-trigger input B of NAND gate 1.',
      'NC': 'Not connected leave unconnected.',
      '1C': 'Schmitt-trigger input C of NAND gate 1.',
      '1D': 'Schmitt-trigger input D of NAND gate 1.',
      '1Y': 'Output of gate 1. LOW only when all four inputs are HIGH.',
      'GND': 'Ground reference (pin 7).',
      '2Y': 'Output of gate 2. LOW only when all four inputs are HIGH.',
      '2A': 'Schmitt-trigger input A of NAND gate 2.',
      '2B': 'Schmitt-trigger input B of NAND gate 2.',
      '2C': 'Schmitt-trigger input C of NAND gate 2.',
      '2D': 'Schmitt-trigger input D of NAND gate 2.',
      'VCC': 'Positive supply (+5 V) at pin 14.',
    },
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls13.pdf',
    tags: ['nand', 'gate', 'logic', 'dual', '4 input', 'schmitt', 'schmitt trigger', 'hysteresis'],
    guideSections: [
      {
        title: 'Schmitt Trigger Inputs',
        paragraphs: [
          'Standard TTL inputs switch at a single threshold voltage (~1.4 V). A Schmitt trigger uses two thresholds: V_T+ (positive-going) and V_T- (negative-going), where V_T+ > V_T-. The output only switches once the input voltage crosses the appropriate threshold in the correct direction, ignoring noise below the hysteresis band.',
          'Slow or noisy rising/falling edges will not cause multiple output transitions the output switches cleanly once and stays there.',
        ],
        formulas: [
          'Hysteresis = V_T+ − V_T−  (typically ~0.8 V for the LS13)',
        ],
        note: 'Tie unused inputs to VCC to prevent them from pulling the output to an unknown state.',
      },
      {
        title: 'Common Uses',
        list: [
          'Debouncing mechanical switches connected through an RC filter.',
          'Receiving slow-rise-time signals from sensors or long cable runs.',
          'Building relaxation oscillators with an RC network.',
        ],
      },
    ],
    pinout: [
      { pin: 1, name: '1A', type: 'input', description: 'Gate 1 input A' },
      { pin: 2, name: '1B', type: 'input', description: 'Gate 1 input B' },
      { pin: 3, name: 'NC', type: 'nc', description: 'Not connected' },
      { pin: 4, name: '1C', type: 'input', description: 'Gate 1 input C' },
      { pin: 5, name: '1D', type: 'input', description: 'Gate 1 input D' },
      { pin: 6, name: '1Y', type: 'output', description: 'Gate 1 NAND output' },
      { pin: 7, name: 'GND', type: 'power', description: 'Ground (0V)' },
      { pin: 8, name: '2Y', type: 'output', description: 'Gate 2 NAND output' },
      { pin: 9, name: '2A', type: 'input', description: 'Gate 2 input A' },
      { pin: 10, name: '2B', type: 'input', description: 'Gate 2 input B' },
      { pin: 11, name: 'NC', type: 'nc', description: 'Not connected' },
      { pin: 12, name: '2C', type: 'input', description: 'Gate 2 input C' },
      { pin: 13, name: '2D', type: 'input', description: 'Gate 2 input D' },
      { pin: 14, name: 'VCC', type: 'power', description: 'Positive supply (+5V)' },
    ],
    gates: [
      { type: 'NAND', inputs: ['1A', '1B', '1C', '1D'], output: '1Y' },
      { type: 'NAND', inputs: ['2A', '2B', '2C', '2D'], output: '2Y' },
    ],
  },

  // ── 7414: Hex Schmitt-trigger Inverter ──────────────────────────────────
  /* Primary source: Texas Instruments, SN74LS14 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls14.pdf
     V_T+ ≈ 1.7 V, V_T- ≈ 0.9 V: TI SN74LS14 datasheet typical values.
     Wikipedia contributors, "Schmitt trigger." Available: https://en.wikipedia.org/wiki/Schmitt_trigger */
  '7414': {
    name: '74x14',
    simpleName: 'Hex NOT (Schmitt)',
    description: 'Six independent Schmitt-trigger inverters. (14-pin)',
    guideOverview: 'The 74x14 provides six Schmitt-trigger inverters the most popular chip in the family for taming noisy or slowly-changing signals. Each input has hysteresis to prevent multiple output transitions on a noisy edge, and the output is the logical complement of the input. The classic application is a square-wave RC oscillator: connect the output through a resistor back to the input with a capacitor to ground.',
    guidePinDescriptions: {
      '1A': 'Schmitt-trigger input of inverter 1.',
      '1Y': 'Output of inverter 1 the complement of 1A.',
      '2A': 'Schmitt-trigger input of inverter 2.',
      '2Y': 'Output of inverter 2.',
      '3A': 'Schmitt-trigger input of inverter 3.',
      '3Y': 'Output of inverter 3.',
      'GND': 'Ground reference (pin 7).',
      '4Y': 'Output of inverter 4.',
      '4A': 'Schmitt-trigger input of inverter 4.',
      '5Y': 'Output of inverter 5.',
      '5A': 'Schmitt-trigger input of inverter 5.',
      '6Y': 'Output of inverter 6.',
      '6A': 'Schmitt-trigger input of inverter 6.',
      'VCC': 'Positive supply (+5 V) at pin 14.',
    },
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls14.pdf',
    tags: ['not', 'inverter', 'gate', 'logic', 'hex', 'schmitt', 'schmitt trigger', 'hysteresis', 'oscillator'],
    guideSections: [
      {
        title: 'Schmitt-Trigger Inverter',
        paragraphs: [
          'The Schmitt trigger adds hysteresis to the inverter: the output switches LOW→HIGH only when the input falls below V_T- and switches HIGH→LOW only when the input rises above V_T+. The gap between the two thresholds is the hysteresis band and determines noise immunity.',
        ],
        formulas: [
          'Approx V_T+ ≈ 1.7 V, V_T− ≈ 0.9 V for the LS14 (see datasheet for guaranteed limits)',
        ],
      },
      {
        title: 'RC Oscillator',
        paragraphs: [
          'Connect the output of one inverter through a resistor R to its own input. Add a capacitor C from the input to GND. The capacitor charges and discharges through R, and the Schmitt trigger snaps the output cleanly at both thresholds, producing a square wave.',
        ],
        formulas: [
          'Approximate frequency f ≈ 1 / (1.2 × R × C)',
        ],
        note: 'This is an approximation actual frequency depends on the exact threshold voltages of the specific chip. Use a trimmer resistor for fine adjustment.',
      },
    ],
    pinout: [
      { pin: 1, name: '1A', type: 'input', description: 'Inverter 1 input' },
      { pin: 2, name: '1Y', type: 'output', description: 'Inverter 1 output (NOT 1A)' },
      { pin: 3, name: '2A', type: 'input', description: 'Inverter 2 input' },
      { pin: 4, name: '2Y', type: 'output', description: 'Inverter 2 output (NOT 2A)' },
      { pin: 5, name: '3A', type: 'input', description: 'Inverter 3 input' },
      { pin: 6, name: '3Y', type: 'output', description: 'Inverter 3 output (NOT 3A)' },
      { pin: 7, name: 'GND', type: 'power', description: 'Ground (0V)' },
      { pin: 8, name: '4Y', type: 'output', description: 'Inverter 4 output (NOT 4A)' },
      { pin: 9, name: '4A', type: 'input', description: 'Inverter 4 input' },
      { pin: 10, name: '5Y', type: 'output', description: 'Inverter 5 output (NOT 5A)' },
      { pin: 11, name: '5A', type: 'input', description: 'Inverter 5 input' },
      { pin: 12, name: '6Y', type: 'output', description: 'Inverter 6 output (NOT 6A)' },
      { pin: 13, name: '6A', type: 'input', description: 'Inverter 6 input' },
      { pin: 14, name: 'VCC', type: 'power', description: 'Positive supply (+5V)' },
    ],
    gates: [
      { type: 'NOT', inputs: ['1A'], output: '1Y' },
      { type: 'NOT', inputs: ['2A'], output: '2Y' },
      { type: 'NOT', inputs: ['3A'], output: '3Y' },
      { type: 'NOT', inputs: ['4A'], output: '4Y' },
      { type: 'NOT', inputs: ['5A'], output: '5Y' },
      { type: 'NOT', inputs: ['6A'], output: '6Y' },
    ],
  },
};
