// chips61.js Block 61: 74x6311 through 74x7060
// 15 chip definitions

export const CHIPS_BLOCK_61 = {

  // ── 74x6311: Static column/page mode access detector for dRAM ──────────
  /* Primary source: 74x6311 datasheet   URL not yet verified.
     https://en.wikipedia.org/wiki/Random-access_memory */
  '74x6311': {
    name: '74x6311',
    simpleName: 'DRAM Access Detector',
    description: 'Static column and page mode access detector for dRAM (20-pin)',
    pins: 20,
    vcc: 20,
    gnd: 10,
    datasheet: '',
    tags: ['dram', 'memory', 'detector'],
    pinout: [
      { pin: 1,  name: 'MA0',   type: 'input'  },
      { pin: 2,  name: 'MA1',   type: 'input'  },
      { pin: 3,  name: 'MA2',   type: 'input'  },
      { pin: 4,  name: 'MA3',   type: 'input'  },
      { pin: 5,  name: 'MA4',   type: 'input'  },
      { pin: 6,  name: 'MA5',   type: 'input'  },
      { pin: 7,  name: 'MA6',   type: 'input'  },
      { pin: 8,  name: 'MA7',   type: 'input'  },
      { pin: 9,  name: 'MA8',   type: 'input'  },
      { pin: 10, name: 'GND',   type: 'power'  },
      { pin: 11, name: 'RASn',  type: 'input'  },
      { pin: 12, name: 'CASn',  type: 'input'  },
      { pin: 13, name: 'WEn',   type: 'input'  },
      { pin: 14, name: 'MODE',  type: 'input'  },
      { pin: 15, name: 'SCPn',  type: 'output' },
      { pin: 16, name: 'PPn',   type: 'output' },
      { pin: 17, name: 'RDYn',  type: 'output' },
      { pin: 18, name: 'NC1',   type: 'nc'     },
      { pin: 19, name: 'NC2',   type: 'nc'     },
      { pin: 20, name: 'VCC',   type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['MA0','MA1','MA2','MA3','MA4','MA5','MA6','MA7','MA8','RASn','CASn','WEn','MODE','NC1','NC2'], outputs: ['SCPn','PPn','RDYn'] },
    ],
  },

  // ── 74x6323: Programmable ripple counter with oscillator ───────────────
  /* Primary source: 74x6323 datasheet   URL not yet verified.
     https://en.wikipedia.org/wiki/Counter_(digital) */
  '74x6323': {
    name: '74x6323',
    simpleName: 'Ripple Counter/Osc',
    description: 'Programmable ripple counter with oscillator (8-pin)',
    pins: 8,
    vcc: 8,
    gnd: 4,
    datasheet: '',
    tags: ['counter', 'oscillator', 'timer'],
    pinout: [
      { pin: 1, name: 'OSC1',  type: 'input'  },
      { pin: 2, name: 'OSC2',  type: 'input'  },
      { pin: 3, name: 'SEL',   type: 'input'  },
      { pin: 4, name: 'GND',   type: 'power'  },
      { pin: 5, name: 'OE',    type: 'input'  },
      { pin: 6, name: 'Q',     type: 'output' },
      { pin: 7, name: 'RST',   type: 'input'  },
      { pin: 8, name: 'VCC',   type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OSC1','OSC2','SEL','OE','RST'], outputs: ['Q'] },
    ],
  },

  // ── 74x6800: 10 bit FET bus switch with precharge ─────────────────────
  /* Primary source: Renesas, 74FST6800 datasheet. [Online]. Available: https://www.renesas.com/us/en/document/dst/74fst6800-datasheet */
  '74x6800': {
    name: '74x6800',
    simpleName: '10 bit Bus Switch',
    description: '10 bit FET bus switch with precharge (24-pin)',
    pins: 24,
    vcc: 24,
    gnd: 12,
    datasheet: 'https://www.renesas.com/us/en/document/dst/74fst6800-datasheet',
    tags: ['bus', 'switch', 'fet'],
    guideOverview: 'The 74x6800 is a 10 bit FET bus switch with output precharge. A bus switch is not a buffered transceiver; it is a bank of low resistance pass transistors that connect corresponding lines between two buses when enabled. Parts like this are used for hot plug backplanes, bus isolation, and low skew signal steering where buffering is not desired.',
    guidePinDescriptions: {
      'OEn': 'Active LOW switch enable. Pull LOW to connect the A and B sides through the FET switch array.',
      'A1': 'Bus side node A1.',
      'B1': 'Corresponding bus side node B1.',
      'A2': 'Bus side node A2.',
      'B2': 'Corresponding bus side node B2.',
      'A3': 'Bus side node A3.',
      'B3': 'Corresponding bus side node B3.',
      'A4': 'Bus side node A4.',
      'B4': 'Corresponding bus side node B4.',
      'A5': 'Bus side node A5.',
      'B5': 'Corresponding bus side node B5.',
      'GND': 'Ground reference for the device.',
      'B6': 'Corresponding bus side node B6.',
      'A6': 'Bus side node A6.',
      'B7': 'Corresponding bus side node B7.',
      'A7': 'Bus side node A7.',
      'B8': 'Corresponding bus side node B8.',
      'A8': 'Bus side node A8.',
      'B9': 'Corresponding bus side node B9.',
      'A9': 'Bus side node A9.',
      'B10': 'Corresponding bus side node B10.',
      'A10': 'Bus side node A10.',
      'PRE': 'Precharge control used to bias the bus switch outputs before connection.',
      'VCC': 'Positive supply for the switch control circuitry.',
    },
    guideSections: [
      {
        title: 'Passive Bus Switching',
        paragraphs: [
          'Unlike a transceiver, a FET bus switch does not actively drive logic HIGH or LOW. It simply connects corresponding lines through a low resistance path, which keeps delay and skew low.',
        ],
      },
      {
        title: 'Bidirectional Simulation Model',
        paragraphs: [
          'The simulator models each channel by driving the A side from the B side value and the B side from the A side value simultaneously. The iterative MNA solver converges to the correct logic state when one side is externally driven.',
        ],
      },
    ],
    pinout: [
      { pin: 1,  name: 'OEn',  type: 'input'  },
      { pin: 2,  name: 'A1',   type: 'input'  },
      { pin: 3,  name: 'B1',   type: 'input'  },
      { pin: 4,  name: 'A2',   type: 'input'  },
      { pin: 5,  name: 'B2',   type: 'input'  },
      { pin: 6,  name: 'A3',   type: 'input'  },
      { pin: 7,  name: 'B3',   type: 'input'  },
      { pin: 8,  name: 'A4',   type: 'input'  },
      { pin: 9,  name: 'B4',   type: 'input'  },
      { pin: 10, name: 'A5',   type: 'input'  },
      { pin: 11, name: 'B5',   type: 'input'  },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'B6',   type: 'input'  },
      { pin: 14, name: 'A6',   type: 'input'  },
      { pin: 15, name: 'B7',   type: 'input'  },
      { pin: 16, name: 'A7',   type: 'input'  },
      { pin: 17, name: 'B8',   type: 'input'  },
      { pin: 18, name: 'A8',   type: 'input'  },
      { pin: 19, name: 'B9',   type: 'input'  },
      { pin: 20, name: 'A9',   type: 'input'  },
      { pin: 21, name: 'B10',  type: 'input'  },
      { pin: 22, name: 'A10',  type: 'input'  },
      { pin: 23, name: 'PRE',  type: 'input'  },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'BUS_SWITCH_10BIT',
        inputs:  ['OEn','PRE','A1','A2','A3','A4','A5','A6','A7','A8','A9','A10','B1','B2','B3','B4','B5','B6','B7','B8','B9','B10'],
        outputs: ['A1','A2','A3','A4','A5','A6','A7','A8','A9','A10','B1','B2','B3','B4','B5','B6','B7','B8','B9','B10'],
      },
    ],
  },

  // ── 74x6845: 8 bit FET bus switch with precharge ──────────────────────
  /* Primary source: Texas Instruments, 74x6845 datasheet. [Online]. Available: https://www.ti.com/lit/gpn/sn74cbt6845c */
  '74x6845': {
    name: '74x6845',
    simpleName: '8 bit Bus Switch',
    description: '8 bit FET bus switch with precharge and extended voltage range (20-pin)',
    pins: 20,
    vcc: 20,
    gnd: 10,
    datasheet: 'https://www.ti.com/lit/gpn/sn74cbt6845c',
    tags: ['bus', 'switch', 'fet'],
    guideOverview: 'The 74x6845 is an 8 bit 1:1 FET bus switch with output precharge. It belongs to the CBT switch family, which is used to connect buses with very low added delay and without the drive behavior of a buffered transceiver. These parts are useful for bus isolation, hot insertion support, and signal path steering on wide digital buses.',
    guidePinDescriptions: {
      'OEn': 'Active LOW switch enable. Pull LOW to connect the A and B nodes through the switch array.',
      'A1': 'Bus side node A1.',
      'B1': 'Corresponding bus side node B1.',
      'A2': 'Bus side node A2.',
      'B2': 'Corresponding bus side node B2.',
      'A3': 'Bus side node A3.',
      'B3': 'Corresponding bus side node B3.',
      'A4': 'Bus side node A4.',
      'B4': 'Corresponding bus side node B4.',
      'GND': 'Ground reference for the device.',
      'B5': 'Corresponding bus side node B5.',
      'A5': 'Bus side node A5.',
      'B6': 'Corresponding bus side node B6.',
      'A6': 'Bus side node A6.',
      'B7': 'Corresponding bus side node B7.',
      'A7': 'Bus side node A7.',
      'B8': 'Corresponding bus side node B8.',
      'A8': 'Bus side node A8.',
      'PRE': 'Precharge control for the bus switch outputs.',
      'VCC': 'Positive supply for the control circuitry.',
    },
    guideSections: [
      {
        title: 'CBT Bus Switch Concept',
        paragraphs: [
          'CBT family parts use pass transistors rather than active logic drivers. That makes them useful when you want to connect two buses with minimal delay instead of regenerating the logic with buffers.',
        ],
      },
      {
        title: 'Bidirectional Simulation Model',
        paragraphs: [
          'The simulator models each channel by driving the A side from the B side value and the B side from the A side value simultaneously. The iterative MNA solver converges to the correct logic state when one side is externally driven.',
        ],
      },
    ],
    pinout: [
      { pin: 1,  name: 'OEn',  type: 'input'  },
      { pin: 2,  name: 'A1',   type: 'input'  },
      { pin: 3,  name: 'B1',   type: 'input'  },
      { pin: 4,  name: 'A2',   type: 'input'  },
      { pin: 5,  name: 'B2',   type: 'input'  },
      { pin: 6,  name: 'A3',   type: 'input'  },
      { pin: 7,  name: 'B3',   type: 'input'  },
      { pin: 8,  name: 'A4',   type: 'input'  },
      { pin: 9,  name: 'B4',   type: 'input'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'B5',   type: 'input'  },
      { pin: 12, name: 'A5',   type: 'input'  },
      { pin: 13, name: 'B6',   type: 'input'  },
      { pin: 14, name: 'A6',   type: 'input'  },
      { pin: 15, name: 'B7',   type: 'input'  },
      { pin: 16, name: 'A7',   type: 'input'  },
      { pin: 17, name: 'B8',   type: 'input'  },
      { pin: 18, name: 'A8',   type: 'input'  },
      { pin: 19, name: 'PRE',  type: 'input'  },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'BUS_SWITCH_8BIT',
        inputs:  ['OEn','PRE','A1','A2','A3','A4','A5','A6','A7','A8','B1','B2','B3','B4','B5','B6','B7','B8'],
        outputs: ['A1','A2','A3','A4','A5','A6','A7','A8','B1','B2','B3','B4','B5','B6','B7','B8'],
      },
    ],
  },

  // ── 74x7001: Quad 2 input AND (Schmitt trigger) ──────────────────────
  /* Primary source: Texas Instruments, 74x7001 datasheet. [Online]. Available: https://www.ti.com/lit/gpn/sn74hc7001 */
  '74x7001': {
    name: '74x7001',
    simpleName: 'Quad AND (Schmitt)',
    description: 'Four 2 input AND gates with Schmitt trigger inputs. (14-pin)',
    schmittInputs: true,
    guideOverview: 'The 74x7001 provides four independent AND gates with Schmitt trigger inputs. It is pin compatible with the 74x08 but offers better noise rejection. Use it anywhere a standard AND gate would work, especially in noisy environments or when building RC oscillators.',
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/gpn/sn74hc7001',
    tags: ['and', 'gate', 'logic', 'quad', 'schmitt'],
    guidePinDescriptions: {
      '1A': 'Input A of gate 1.',
      '1B': 'Input B of gate 1.',
      '1Y': 'Output of gate 1. It is HIGH only when both 1A and 1B are HIGH.',
      '2A': 'Input A of gate 2.',
      '2B': 'Input B of gate 2.',
      '2Y': 'Output of gate 2.',
      'GND': 'Ground reference for the package.',
      '3Y': 'Output of gate 3.',
      '3A': 'Input A of gate 3.',
      '3B': 'Input B of gate 3.',
      '4Y': 'Output of gate 4.',
      '4A': 'Input A of gate 4.',
      '4B': 'Input B of gate 4.',
      'VCC': 'Positive supply for the logic.',
    },
    guideSections: [
      {
        title: 'AND Logic With Schmitt Inputs',
        paragraphs: [
          'An AND gate outputs HIGH only when all of its inputs are HIGH. The Schmitt trigger input stage adds hysteresis, which helps reject slow or noisy input transitions.',
        ],
      },
      {
        title: 'Where It Helps',
        list: [
          'Cleaning up switch or RC shaped inputs before AND logic decisions.',
          'Combining multiple required conditions in noisy environments.',
          'Building gates around slowly changing sensor signals.',
        ],
      },
    ],
    pinout: [
      { pin: 1,  name: '1A',  type: 'input'  },
      { pin: 2,  name: '1B',  type: 'input'  },
      { pin: 3,  name: '1Y',  type: 'output' },
      { pin: 4,  name: '2A',  type: 'input'  },
      { pin: 5,  name: '2B',  type: 'input'  },
      { pin: 6,  name: '2Y',  type: 'output' },
      { pin: 7,  name: 'GND', type: 'power'  },
      { pin: 8,  name: '3Y',  type: 'output' },
      { pin: 9,  name: '3A',  type: 'input'  },
      { pin: 10, name: '3B',  type: 'input'  },
      { pin: 11, name: '4Y',  type: 'output' },
      { pin: 12, name: '4A',  type: 'input'  },
      { pin: 13, name: '4B',  type: 'input'  },
      { pin: 14, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'AND', inputs: ['1A', '1B'], output: '1Y' },
      { type: 'AND', inputs: ['2A', '2B'], output: '2Y' },
      { type: 'AND', inputs: ['3A', '3B'], output: '3Y' },
      { type: 'AND', inputs: ['4A', '4B'], output: '4Y' },
    ],
  },

  // ── 74x7002: Quad 2 input NOR (Schmitt trigger) ──────────────────────
  /* Primary source: Texas Instruments, 74x7002 datasheet. [Online]. Available: https://www.ti.com/lit/gpn/sn74hc7002 */
  // Pinout matches 74x00/74x08 layout (A-B-Y on top half, Y-A-B on bottom half)
  // NOT the same as 7402 the 74x7002 keeps inputs-first ordering.
  '74x7002': {
    name: '74x7002',
    simpleName: 'Quad NOR (Schmitt)',
    description: 'Four 2 input NOR gates with Schmitt trigger inputs. (14-pin)',
    schmittInputs: true,
    guideOverview: 'The 74x7002 provides four independent NOR gates with Schmitt trigger inputs. The pinout follows the AND gate pin ordering (inputs first, output last per gate) rather than the standard 74x02 NOR ordering. It works as a drop-in replacement for ordinary NOR gates with extra noise immunity.',
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/gpn/sn74hc7002',
    tags: ['nor', 'gate', 'logic', 'quad', 'schmitt'],
    guidePinDescriptions: {
      '1A': 'Input A of gate 1.',
      '1B': 'Input B of gate 1.',
      '1Y': 'Output of gate 1. It is HIGH only when both 1A and 1B are LOW.',
      '2A': 'Input A of gate 2.',
      '2B': 'Input B of gate 2.',
      '2Y': 'Output of gate 2.',
      'GND': 'Ground reference for the package.',
      '3Y': 'Output of gate 3.',
      '3A': 'Input A of gate 3.',
      '3B': 'Input B of gate 3.',
      '4Y': 'Output of gate 4.',
      '4A': 'Input A of gate 4.',
      '4B': 'Input B of gate 4.',
      'VCC': 'Positive supply for the logic.',
    },
    guideSections: [
      {
        title: 'NOR Logic And Hysteresis',
        paragraphs: [
          'A NOR gate outputs HIGH only when none of its inputs are HIGH. The Schmitt trigger front end makes the inputs less sensitive to noise and slow edge transitions.',
        ],
      },
      {
        title: 'Pinout Note',
        paragraphs: [
          'This family keeps the inputs first ordering rather than the classic 74x02 NOR package ordering. The local definition already captures that correctly.',
        ],
      },
    ],
    pinout: [
      { pin: 1,  name: '1A',  type: 'input'  },
      { pin: 2,  name: '1B',  type: 'input'  },
      { pin: 3,  name: '1Y',  type: 'output' },
      { pin: 4,  name: '2A',  type: 'input'  },
      { pin: 5,  name: '2B',  type: 'input'  },
      { pin: 6,  name: '2Y',  type: 'output' },
      { pin: 7,  name: 'GND', type: 'power'  },
      { pin: 8,  name: '3Y',  type: 'output' },
      { pin: 9,  name: '3A',  type: 'input'  },
      { pin: 10, name: '3B',  type: 'input'  },
      { pin: 11, name: '4Y',  type: 'output' },
      { pin: 12, name: '4A',  type: 'input'  },
      { pin: 13, name: '4B',  type: 'input'  },
      { pin: 14, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'NOR', inputs: ['1A', '1B'], output: '1Y' },
      { type: 'NOR', inputs: ['2A', '2B'], output: '2Y' },
      { type: 'NOR', inputs: ['3A', '3B'], output: '3Y' },
      { type: 'NOR', inputs: ['4A', '4B'], output: '4Y' },
    ],
  },

  // ── 74x7003: Quad 2 input NAND (Schmitt, open collector) ─────────────
  /* Primary source: 74x7003 datasheet   URL not yet verified.
     https://en.wikipedia.org/wiki/Open_collector */
  '74x7003': {
    name: '74x7003',
    simpleName: '2 input NAND (Schmitt OC)',
    description: 'Quad 2 input NAND gate (Schmitt trigger inputs, open collector) (14-pin)',
    schmittInputs: true,
    pins: 14,
    vcc: 14,
    gnd: 7,
    openCollector: true,
    datasheet: '',
    tags: ['nand', 'gate', 'logic', 'quad', 'schmitt', 'open collector'],
    pinout: [
      { pin: 1,  name: '1A',  type: 'input'  },
      { pin: 2,  name: '1B',  type: 'input'  },
      { pin: 3,  name: '1Y',  type: 'output' },
      { pin: 4,  name: '2A',  type: 'input'  },
      { pin: 5,  name: '2B',  type: 'input'  },
      { pin: 6,  name: '2Y',  type: 'output' },
      { pin: 7,  name: 'GND', type: 'power'  },
      { pin: 8,  name: '3Y',  type: 'output' },
      { pin: 9,  name: '3A',  type: 'input'  },
      { pin: 10, name: '3B',  type: 'input'  },
      { pin: 11, name: '4Y',  type: 'output' },
      { pin: 12, name: '4A',  type: 'input'  },
      { pin: 13, name: '4B',  type: 'input'  },
      { pin: 14, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'NAND', inputs: ['1A', '1B'], output: '1Y' },
      { type: 'NAND', inputs: ['2A', '2B'], output: '2Y' },
      { type: 'NAND', inputs: ['3A', '3B'], output: '3Y' },
      { type: 'NAND', inputs: ['4A', '4B'], output: '4Y' },
    ],
  },

  // ── 74x7006: Mixed gate (2 NOT, 3-NAND, 4-NAND, 3-NOR, 4-NOR) ───────
  /* Primary source: 74x7006 datasheet   URL not yet verified. */
  '74x7006': {
    name: '74x7006',
    simpleName: 'Mixed Gate',
    description: '2 NOT, 3-in + 4-in NAND, 3-in + 4-in NOR (24-pin)',
    pins: 24,
    vcc: 24,
    gnd: 12,
    datasheet: '',
    tags: ['mixed', 'gate', 'logic', 'nand', 'nor', 'not'],
    pinout: [
      { pin: 1,  name: '1A',   type: 'input'  },
      { pin: 2,  name: '1Y',   type: 'output' },
      { pin: 3,  name: '2A',   type: 'input'  },
      { pin: 4,  name: '2B',   type: 'input'  },
      { pin: 5,  name: '2C',   type: 'input'  },
      { pin: 6,  name: '2Y',   type: 'output' },
      { pin: 7,  name: '3A',   type: 'input'  },
      { pin: 8,  name: '3B',   type: 'input'  },
      { pin: 9,  name: '3C',   type: 'input'  },
      { pin: 10, name: '3D',   type: 'input'  },
      { pin: 11, name: '3Y',   type: 'output' },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: '4Y',   type: 'output' },
      { pin: 14, name: '4A',   type: 'input'  },
      { pin: 15, name: '4B',   type: 'input'  },
      { pin: 16, name: '4C',   type: 'input'  },
      { pin: 17, name: '5Y',   type: 'output' },
      { pin: 18, name: '5A',   type: 'input'  },
      { pin: 19, name: '5B',   type: 'input'  },
      { pin: 20, name: '5C',   type: 'input'  },
      { pin: 21, name: '5D',   type: 'input'  },
      { pin: 22, name: '6Y',   type: 'output' },
      { pin: 23, name: '6A',   type: 'input'  },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'NOT',  inputs: ['1A'],               output: '1Y' },
      { type: 'NAND', inputs: ['2A', '2B', '2C'],   output: '2Y' },
      { type: 'NAND', inputs: ['3A', '3B', '3C', '3D'], output: '3Y' },
      { type: 'NOR',  inputs: ['4A', '4B', '4C'],   output: '4Y' },
      { type: 'NOR',  inputs: ['5A', '5B', '5C', '5D'], output: '5Y' },
      { type: 'NOT',  inputs: ['6A'],               output: '6Y' },
    ],
  },

  // ── 74x7007: Hex buffer gate ──────────────────────────────────────────
  /* Primary source: 74x7007 datasheet   URL not yet verified. */
  '74x7007': {
    name: '74x7007',
    simpleName: 'Hex Buffer',
    description: 'Hex buffer gate (14-pin)',
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: '',
    tags: ['buffer', 'gate', 'logic', 'hex'],
    pinout: [
      { pin: 1,  name: '1A',  type: 'input'  },
      { pin: 2,  name: '1Y',  type: 'output' },
      { pin: 3,  name: '2A',  type: 'input'  },
      { pin: 4,  name: '2Y',  type: 'output' },
      { pin: 5,  name: '3A',  type: 'input'  },
      { pin: 6,  name: '3Y',  type: 'output' },
      { pin: 7,  name: 'GND', type: 'power'  },
      { pin: 8,  name: '4Y',  type: 'output' },
      { pin: 9,  name: '4A',  type: 'input'  },
      { pin: 10, name: '5Y',  type: 'output' },
      { pin: 11, name: '5A',  type: 'input'  },
      { pin: 12, name: '6Y',  type: 'output' },
      { pin: 13, name: '6A',  type: 'input'  },
      { pin: 14, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'BUFFER', inputs: ['1A'], output: '1Y' },
      { type: 'BUFFER', inputs: ['2A'], output: '2Y' },
      { type: 'BUFFER', inputs: ['3A'], output: '3Y' },
      { type: 'BUFFER', inputs: ['4A'], output: '4Y' },
      { type: 'BUFFER', inputs: ['5A'], output: '5Y' },
      { type: 'BUFFER', inputs: ['6A'], output: '6Y' },
    ],
  },

  // ── 74x7008: Mixed gate (2 NOT, 3×NAND, 3×NOR) ──────────────────────
  /* Primary source: 74x7008 datasheet   URL not yet verified. */
  '74x7008': {
    name: '74x7008',
    simpleName: 'Mixed Gate',
    description: 'Two inverters, three 2 input NAND, three 2 input NOR (24-pin)',
    pins: 24,
    vcc: 24,
    gnd: 12,
    datasheet: '',
    tags: ['mixed', 'gate', 'logic', 'nand', 'nor', 'not'],
    pinout: [
      { pin: 1,  name: '1A',   type: 'input'  },
      { pin: 2,  name: '1Y',   type: 'output' },
      { pin: 3,  name: '2A',   type: 'input'  },
      { pin: 4,  name: '2B',   type: 'input'  },
      { pin: 5,  name: '2Y',   type: 'output' },
      { pin: 6,  name: '3A',   type: 'input'  },
      { pin: 7,  name: '3B',   type: 'input'  },
      { pin: 8,  name: '3Y',   type: 'output' },
      { pin: 9,  name: '4A',   type: 'input'  },
      { pin: 10, name: '4B',   type: 'input'  },
      { pin: 11, name: '4Y',   type: 'output' },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: '5Y',   type: 'output' },
      { pin: 14, name: '5A',   type: 'input'  },
      { pin: 15, name: '5B',   type: 'input'  },
      { pin: 16, name: '6Y',   type: 'output' },
      { pin: 17, name: '6A',   type: 'input'  },
      { pin: 18, name: '6B',   type: 'input'  },
      { pin: 19, name: '7Y',   type: 'output' },
      { pin: 20, name: '7A',   type: 'input'  },
      { pin: 21, name: '7B',   type: 'input'  },
      { pin: 22, name: '8Y',   type: 'output' },
      { pin: 23, name: '8A',   type: 'input'  },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'NOT',  inputs: ['1A'],          output: '1Y' },
      { type: 'NAND', inputs: ['2A', '2B'],    output: '2Y' },
      { type: 'NAND', inputs: ['3A', '3B'],    output: '3Y' },
      { type: 'NAND', inputs: ['4A', '4B'],    output: '4Y' },
      { type: 'NOR',  inputs: ['5A', '5B'],    output: '5Y' },
      { type: 'NOR',  inputs: ['6A', '6B'],    output: '6Y' },
      { type: 'NOR',  inputs: ['7A', '7B'],    output: '7Y' },
      { type: 'NOT',  inputs: ['8A'],          output: '8Y' },
    ],
  },

  // ── 74x7014: Hex Schmitt trigger buffer ───────────────────────────────
  /* Primary source: 74x7014 datasheet   URL not yet verified. */
  '74x7014': {
    name: '74x7014',
    simpleName: 'Buffer (Schmitt)',
    description: 'Hex Schmitt trigger buffer (non inverting) (14-pin)',
    schmittInputs: true,
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: '',
    tags: ['buffer', 'gate', 'logic', 'hex', 'schmitt'],
    pinout: [
      { pin: 1,  name: '1A',  type: 'input'  },
      { pin: 2,  name: '1Y',  type: 'output' },
      { pin: 3,  name: '2A',  type: 'input'  },
      { pin: 4,  name: '2Y',  type: 'output' },
      { pin: 5,  name: '3A',  type: 'input'  },
      { pin: 6,  name: '3Y',  type: 'output' },
      { pin: 7,  name: 'GND', type: 'power'  },
      { pin: 8,  name: '4Y',  type: 'output' },
      { pin: 9,  name: '4A',  type: 'input'  },
      { pin: 10, name: '5Y',  type: 'output' },
      { pin: 11, name: '5A',  type: 'input'  },
      { pin: 12, name: '6Y',  type: 'output' },
      { pin: 13, name: '6A',  type: 'input'  },
      { pin: 14, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'BUFFER', inputs: ['1A'], output: '1Y' },
      { type: 'BUFFER', inputs: ['2A'], output: '2Y' },
      { type: 'BUFFER', inputs: ['3A'], output: '3Y' },
      { type: 'BUFFER', inputs: ['4A'], output: '4Y' },
      { type: 'BUFFER', inputs: ['5A'], output: '5Y' },
      { type: 'BUFFER', inputs: ['6A'], output: '6Y' },
    ],
  },

  // ── 74x7022: 4-stage ÷8 Johnson counter with power-up clear ──────────
  /* Primary source: 74x7022 datasheet   URL not yet verified.
     https://en.wikipedia.org/wiki/Counter_(digital) */
  '74x7022': {
    name: '74x7022',
    simpleName: '÷8 Johnson Counter',
    description: '4-stage ÷8 Johnson counter with power-up clear (14-pin)',
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: '',
    tags: ['counter', 'johnson', 'divider'],
    pinout: [
      { pin: 1,  name: 'Q0',   type: 'output' },
      { pin: 2,  name: 'Q1',   type: 'output' },
      { pin: 3,  name: 'Q2',   type: 'output' },
      { pin: 4,  name: 'Q3',   type: 'output' },
      { pin: 5,  name: 'CO',   type: 'output' },
      { pin: 6,  name: 'INH',  type: 'input'  },
      { pin: 7,  name: 'GND',  type: 'power'  },
      { pin: 8,  name: 'Q7',   type: 'output' },
      { pin: 9,  name: 'Q6',   type: 'output' },
      { pin: 10, name: 'Q5',   type: 'output' },
      { pin: 11, name: 'Q4',   type: 'output' },
      { pin: 12, name: 'RST',  type: 'input'  },
      { pin: 13, name: 'CLK',  type: 'input'  },
      { pin: 14, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['INH','RST','CLK'], outputs: ['Q0','Q1','Q2','Q3','Q4','Q5','Q6','Q7','CO'] },
    ],
  },

  // ── 74x7032: Quad 2 input OR (Schmitt trigger) ───────────────────────
  /* Primary source: Texas Instruments, 74x7032 datasheet. [Online]. Available: https://www.ti.com/lit/gpn/sn74hc7032 */
  '74x7032': {
    name: '74x7032',
    simpleName: 'Quad OR (Schmitt)',
    description: 'Four 2 input OR gates with Schmitt trigger inputs. (14-pin)',
    schmittInputs: true,
    guideOverview: 'The 74x7032 provides four independent OR gates with Schmitt trigger inputs. It is pin compatible with the 74x32 but handles noisy signals better. Useful for wired OR applications and building RC relaxation oscillators.',
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/gpn/sn74hc7032',
    tags: ['or', 'gate', 'logic', 'quad', 'schmitt'],
    guidePinDescriptions: {
      '1A': 'Input A of gate 1.',
      '1B': 'Input B of gate 1.',
      '1Y': 'Output of gate 1. It goes HIGH if either input is HIGH.',
      '2A': 'Input A of gate 2.',
      '2B': 'Input B of gate 2.',
      '2Y': 'Output of gate 2.',
      'GND': 'Ground reference for the package.',
      '3Y': 'Output of gate 3.',
      '3A': 'Input A of gate 3.',
      '3B': 'Input B of gate 3.',
      '4Y': 'Output of gate 4.',
      '4A': 'Input A of gate 4.',
      '4B': 'Input B of gate 4.',
      'VCC': 'Positive supply for the logic.',
    },
    guideSections: [
      {
        title: 'OR Logic With Schmitt Inputs',
        paragraphs: [
          'An OR gate outputs HIGH when any input is HIGH. Adding Schmitt trigger inputs makes the gate better at handling slow, noisy, or RC shaped signals without chatter.',
        ],
      },
      {
        title: 'Typical Uses',
        list: [
          'Combining multiple request or alarm signals.',
          'Cleaning up noisy control inputs before OR combination.',
          'Building simple Schmitt trigger RC timing tricks around OR logic.',
        ],
      },
    ],
    pinout: [
      { pin: 1,  name: '1A',  type: 'input'  },
      { pin: 2,  name: '1B',  type: 'input'  },
      { pin: 3,  name: '1Y',  type: 'output' },
      { pin: 4,  name: '2A',  type: 'input'  },
      { pin: 5,  name: '2B',  type: 'input'  },
      { pin: 6,  name: '2Y',  type: 'output' },
      { pin: 7,  name: 'GND', type: 'power'  },
      { pin: 8,  name: '3Y',  type: 'output' },
      { pin: 9,  name: '3A',  type: 'input'  },
      { pin: 10, name: '3B',  type: 'input'  },
      { pin: 11, name: '4Y',  type: 'output' },
      { pin: 12, name: '4A',  type: 'input'  },
      { pin: 13, name: '4B',  type: 'input'  },
      { pin: 14, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'OR', inputs: ['1A', '1B'], output: '1Y' },
      { type: 'OR', inputs: ['2A', '2B'], output: '2Y' },
      { type: 'OR', inputs: ['3A', '3B'], output: '3Y' },
      { type: 'OR', inputs: ['4A', '4B'], output: '4Y' },
    ],
  },

  // ── 74x7038: 9 bit bus transceiver with latch ────────────────────────
  /* Primary source: 74x7038 datasheet   URL not yet verified.
     https://en.wikipedia.org/wiki/Flip-flop_(electronics) */
  '74x7038': {
    name: '74x7038',
    simpleName: '9 bit Transceiver/Latch',
    description: '9 bit bus transceiver with latch (three-state) (24-pin)',
    pins: 24,
    vcc: 24,
    gnd: 12,
    datasheet: '',
    tags: ['transceiver', 'latch', 'bus'],
    pinout: [
      { pin: 1,  name: 'DIR',  type: 'input'  },
      { pin: 2,  name: 'A1',   type: 'input'  },
      { pin: 3,  name: 'B1',   type: 'output' },
      { pin: 4,  name: 'A2',   type: 'input'  },
      { pin: 5,  name: 'B2',   type: 'output' },
      { pin: 6,  name: 'A3',   type: 'input'  },
      { pin: 7,  name: 'B3',   type: 'output' },
      { pin: 8,  name: 'A4',   type: 'input'  },
      { pin: 9,  name: 'B4',   type: 'output' },
      { pin: 10, name: 'A5',   type: 'input'  },
      { pin: 11, name: 'B5',   type: 'output' },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'B6',   type: 'output' },
      { pin: 14, name: 'A6',   type: 'input'  },
      { pin: 15, name: 'B7',   type: 'output' },
      { pin: 16, name: 'A7',   type: 'input'  },
      { pin: 17, name: 'B8',   type: 'output' },
      { pin: 18, name: 'A8',   type: 'input'  },
      { pin: 19, name: 'B9',   type: 'output' },
      { pin: 20, name: 'A9',   type: 'input'  },
      { pin: 21, name: 'LE',   type: 'input'  },
      { pin: 22, name: 'OEn',  type: 'input'  },
      { pin: 23, name: 'NC',   type: 'nc'     },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['DIR','A1','A2','A3','A4','A5','A6','A7','A8','A9','LE','OEn','NC'], outputs: ['B1','B2','B3','B4','B5','B6','B7','B8','B9'] },
    ],
  },

  // ── 74x7060: 14-stage binary counter with oscillator (Schmitt) ───────
  /* Primary source: 74x7060 datasheet   URL not yet verified.
     https://en.wikipedia.org/wiki/Counter_(digital) */
  '74x7060': {
    name: '74x7060',
    simpleName: '14-stage Counter/Osc',
    description: '14-stage binary counter with oscillator (Schmitt trigger input) (20-pin)',
    pins: 20,
    vcc: 20,
    gnd: 10,
    datasheet: '',
    tags: ['counter', 'binary', 'oscillator', 'schmitt'],
    pinout: [
      { pin: 1,  name: 'Q12',  type: 'output' },
      { pin: 2,  name: 'Q13',  type: 'output' },
      { pin: 3,  name: 'Q14',  type: 'output' },
      { pin: 4,  name: 'Q6',   type: 'output' },
      { pin: 5,  name: 'Q5',   type: 'output' },
      { pin: 6,  name: 'Q7',   type: 'output' },
      { pin: 7,  name: 'Q4',   type: 'output' },
      { pin: 8,  name: 'OSCo', type: 'output' },
      { pin: 9,  name: 'OSCi', type: 'input'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'RST',  type: 'input'  },
      { pin: 12, name: 'Q10',  type: 'output' },
      { pin: 13, name: 'Q8',   type: 'output' },
      { pin: 14, name: 'Q9',   type: 'output' },
      { pin: 15, name: 'Q3',   type: 'output' },
      { pin: 16, name: 'Q2',   type: 'output' },
      { pin: 17, name: 'Q11',  type: 'output' },
      { pin: 18, name: 'Q1',   type: 'output' },
      { pin: 19, name: 'CLK',  type: 'input'  },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OSCi','RST','CLK'], outputs: ['Q1','Q2','Q3','Q4','Q5','Q6','Q7','Q8','Q9','Q10','Q11','Q12','Q13','Q14','OSCo'] },
    ],
  },

};