// Chip definitions block 4
// Auto-generated from chips.js

export const CHIPS_BLOCK_4 = {
  // ── 7490: Decade Counter ───────────────────────────────────────────────
  /* Primary source: Texas Instruments, SN74LS90 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls90.pdf
     Counter (digital) concept: https://en.wikipedia.org/wiki/Counter_(digital) */
  '7490': {
    name: '74x90',
    simpleName: 'BCD Decade Counter (0 to 9)',
    description: '4 bit BCD decade counter counts 0 to 9 with reset-to-0 and preset-to-9 inputs (14 pin)',
    pins: 14,
    vcc: 5,
    gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls90.pdf',
    tags: ['counter', 'decade', 'bcd', 'sequential', 'divider', 'ripple'],
    guideOverview: 'The 74x90 is a 4 bit BCD decade counter that counts from 0 to 9 and outputs the result on QA to QD. Internally it contains a ÷2 section (CKA → QA) and a ÷5 section (CKB → QB,QC,QD). Connect QA to CKB and use CKA as your clock to count 0 to 9 in BCD.',
    guidePinDescriptions: {
      CKB:  'Clock input for the divide-by-5 section (QB,QC,QD). Active on falling edge. Connect QA here for BCD counting.',
      R01:  'Reset input 1 (of 2). When both R01 and R02 are HIGH all outputs reset to 0000.',
      R02:  'Reset input 2 (of 2). When both R01 and R02 are HIGH all outputs reset to 0000.',
      NC1:  'Not connected.',
      VCC:  'Positive supply (5V). Note: VCC is at pin 5, non standard position.',
      R91:  'Preset-to-9 input 1 (of 2). Both R91 and R92 HIGH set outputs to 1001 (BCD 9).',
      R92:  'Preset-to-9 input 2 (of 2). Both R91 and R92 HIGH set outputs to 1001 (BCD 9).',
      QC:   'Bit 2 of the BCD count output (weight 4).',
      QB:   'Bit 1 of the BCD count output (weight 2).',
      GND:  'Ground reference at pin 10.',
      QD:   'Bit 3 of the BCD count output (weight 8).',
      QA:   'Bit 0 of the BCD count output (weight 1, LSB). Connect to CKB for decade counting.',
      NC2:  'Not connected.',
      CKA:  'Clock input for the divide-by-2 section (QA). Use this as the main clock input.',
    },
    pinout: [
      { pin: 1, name: 'CKB', type: 'input' },
      { pin: 2, name: 'R01', type: 'input' },
      { pin: 3, name: 'R02', type: 'input' },
      { pin: 4, name: 'NC1', type: 'nc' },
      { pin: 5, name: 'VCC', type: 'power' },
      { pin: 6, name: 'R91', type: 'input' },
      { pin: 7, name: 'R92', type: 'input' },
      { pin: 8, name: 'QC', type: 'output' },
      { pin: 9, name: 'QB', type: 'output' },
      { pin: 10, name: 'GND', type: 'power' },
      { pin: 11, name: 'QD', type: 'output' },
      { pin: 12, name: 'QA', type: 'output' },
      { pin: 13, name: 'NC2', type: 'nc' },
      { pin: 14, name: 'CKA', type: 'input' },
    ],
    gates: [
      {
        type: 'COUNTER_DECADE',
        inputs: ['CKA', 'CKB', 'R01', 'R02', 'R91', 'R92'],
        outputs: ['QA', 'QB', 'QC', 'QD'],
      },
    ],
    sequential: true,
    guideSections: [
      {
        title: 'Decade Counting (0 to 9)',
        paragraphs: [
          'For BCD decade counting, connect QA to CKB. Apply your clock signal to CKA. The counter will count 0 to 9 in BCD on outputs QA to QD, then reset to 0.',
          'To reset to 0: assert both R01 and R02 HIGH simultaneously. To preset to 9 (1001): assert both R91 and R92 HIGH. For normal operation keep R01, R02, R91, R92 all LOW.',
        ],
        note: 'VCC is at pin 5 and GND is at pin 10. These are non standard positions, double check power wiring.',
      },
    ],
  },

  // ── 7491: 8 bit Shift Register ─────────────────────────────────────────
  /* Primary source: Texas Instruments, SN74LS91 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls91.pdf
     Shift register concept: https://en.wikipedia.org/wiki/Shift_register */
  '7491': {
    name: '74x91',
    simpleName: '8 bit Serial-In Serial-Out Shift Register',
    description: '8 bit SISO shift register with AND gated serial inputs and complementary outputs (14 pin)',
    pins: 14,
    vcc: 5,
    gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls91.pdf',
    tags: ['shift register', 'serial', '8 bit', 'sequential', 'siso'],
    guideOverview: 'The 74x91 is an 8 bit serial in serial out (SISO) shift register. Data enters through AND gated inputs A and B, both must be HIGH to shift in a 1. After 8 clock pulses, data appears at output Q (and its complement Qn). Used for serial data delay, buffering, and storage.',
    guidePinDescriptions: {
      NC1:  'Not connected (pin 1).',
      NC2:  'Not connected (pin 2).',
      NC3:  'Not connected (pin 3).',
      NC4:  'Not connected (pin 4).',
      VCC:  'Positive supply (5V). Note: VCC is at pin 5, non standard position.',
      NC5:  'Not connected (pin 6).',
      NC6:  'Not connected (pin 7).',
      NC7:  'Not connected (pin 8).',
      CLK:  'Clock input. Data shifts on the rising edge.',
      GND:  'Ground reference at pin 10.',
      B:    'AND gate enable/data input. Both A and B must be HIGH to shift in a 1.',
      A:    'AND gate data input. Both A and B must be HIGH to shift in a 1.',
      Q:    'Serial output data appears here after 8 clock pulses.',
      Qn:   'Complement of Q output.',
    },
    pinout: [
      { pin:  1, name: 'NC1', type: 'nc'     },
      { pin:  2, name: 'NC2', type: 'nc'     },
      { pin:  3, name: 'NC3', type: 'nc'     },
      { pin:  4, name: 'NC4', type: 'nc'     },
      { pin:  5, name: 'VCC', type: 'power'  },
      { pin:  6, name: 'NC5', type: 'nc'     },
      { pin:  7, name: 'NC6', type: 'nc'     },
      { pin:  8, name: 'NC7', type: 'nc'     },
      { pin:  9, name: 'CLK', type: 'input'  },
      { pin: 10, name: 'GND', type: 'power'  },
      { pin: 11, name: 'B',   type: 'input'  },
      { pin: 12, name: 'A',   type: 'input'  },
      { pin: 13, name: 'Q',   type: 'output' },
      { pin: 14, name: 'Qn',  type: 'output' },
    ],
    gates: [
      { type: 'SHIFT_REG_SISO', inputs: ['A', 'B', 'CLK'], outputs: ['Q', 'Qn'] },
    ],
    sequential: true,
    guideSections: [
      {
        title: '8 bit Serial Operation',
        paragraphs: [
          'To shift in a logic 1: set both A and B HIGH before the rising edge of CLK. To shift in a logic 0: hold either A or B LOW. Data ripples through 8 internal stages and emerges at Q after 8 clock pulses.',
          'Q and Qn are always complementary. This chip provides only serial output, there are no parallel tap outputs between stages.',
        ],
      },
    ],
  },

  // ── 7492: Divide-by-12 Counter ─────────────────────────────────────────
  /* Primary source: Texas Instruments, SN74LS92 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls92.pdf
     Counter (digital) concept: https://en.wikipedia.org/wiki/Counter_(digital) */
  '7492': {
    name: '74x92',
    simpleName: 'Divide-by-12 Counter',
    description: 'Divide-by-twelve counter, two sections: ÷2 and ÷6, combine for ÷12 (14 pin)',
    pins: 14,
    vcc: 5,
    gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls92.pdf',
    tags: ['counter', 'divider', 'divide-by-12', 'sequential', 'ripple'],
    guideOverview: 'The 74x92 is a divide-by-12 counter useful for digital clocks and timing circuits. It contains a ÷2 section (CKA → QA) and a ÷6 section (CKB → QB,QC,QD). Connect QA to CKB and use CKA as the clock input to count 0 to 11 in binary, then reset to 0.',
    guidePinDescriptions: {
      CKB:  'Clock input for the divide-by-6 section. Connect QA here for divide-by-12 operation.',
      NC1:  'Not connected (pin 2).',
      NC2:  'Not connected (pin 3).',
      NC3:  'Not connected (pin 4).',
      VCC:  'Positive supply (5V) at pin 5, non standard position.',
      R01:  'Reset input 1 (of 2). When both R01 and R02 are HIGH all outputs clear to 0000.',
      R02:  'Reset input 2 (of 2). When both R01 and R02 are HIGH all outputs clear to 0000.',
      QC:   'Bit 2 of the count output (weight 4).',
      QB:   'Bit 1 of the count output (weight 2).',
      GND:  'Ground reference at pin 10.',
      QD:   'Bit 3 of the count output (weight 8).',
      QA:   'Bit 0 of the count output (weight 1, LSB). Connect to CKB for divide-by-12.',
      NC4:  'Not connected (pin 13).',
      CKA:  'Clock input for the divide-by-2 section (QA). Use as main clock input.',
    },
    pinout: [
      { pin: 1, name: 'CKB', type: 'input' },
      { pin: 2, name: 'NC1', type: 'nc' },
      { pin: 3, name: 'NC2', type: 'nc' },
      { pin: 4, name: 'NC3', type: 'nc' },
      { pin: 5, name: 'VCC', type: 'power' },
      { pin: 6, name: 'R01', type: 'input' },
      { pin: 7, name: 'R02', type: 'input' },
      { pin: 8, name: 'QC', type: 'output' },
      { pin: 9, name: 'QB', type: 'output' },
      { pin: 10, name: 'GND', type: 'power' },
      { pin: 11, name: 'QD', type: 'output' },
      { pin: 12, name: 'QA', type: 'output' },
      { pin: 13, name: 'NC4', type: 'nc' },
      { pin: 14, name: 'CKA', type: 'input' },
    ],
    gates: [
      {
        type: 'COUNTER_DIV12',
        inputs: ['CKA', 'CKB', 'R01', 'R02'],
        outputs: ['QA', 'QB', 'QC', 'QD'],
      },
    ],
    sequential: true,
    guideSections: [
      {
        title: 'Divide-by-12 Operation',
        paragraphs: [
          'For a full divide-by-12 counter, connect QA to CKB and apply your clock to CKA. The counter increments from 0 to 11 (binary 1011) then resets to 0.',
          'To reset to 0 at any time: pull both R01 and R02 HIGH simultaneously. For normal counting, keep both LOW.',
        ],
        note: 'VCC is at pin 5 and GND is at pin 10, non standard positions for a 14 pin DIP.',
      },
    ],
  },

  // ── 7493: 4 bit Binary Counter ─────────────────────────────────────────
  /* Primary source: Texas Instruments, SN74LS93 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls93.pdf
     Counter (digital) concept: https://en.wikipedia.org/wiki/Counter_(digital) */
  '7493': {
    name: '74x93',
    simpleName: '4 bit Binary Counter (0 to 15)',
    description: '4 bit binary ripple counter, two sections: ÷2 and ÷8, combine for ÷16 (0 to 15) (14 pin)',
    pins: 14,
    vcc: 5,
    gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls93.pdf',
    tags: ['counter', 'binary', '4 bit', 'sequential', 'divider', 'ripple'],
    guideOverview: 'The 74x93 is a 4 bit asynchronous binary ripple counter. It contains a ÷2 section (CKA → QA) and a ÷8 section (CKB → QB,QC,QD). Connect QA to CKB and use CKA as your clock to count 0 to 15 in binary. Both reset inputs (R01, R02) must be HIGH to clear all outputs to 0.',
    guidePinDescriptions: {
      CKB:  'Clock input for the divide-by-8 section (QB,QC,QD). Connect QA here for 4 bit counting.',
      R01:  'Reset input 1 (of 2). When both R01 and R02 are HIGH all outputs clear to 0000.',
      R02:  'Reset input 2 (of 2). When both R01 and R02 are HIGH all outputs clear to 0000.',
      NC1:  'Not connected (pin 4).',
      VCC:  'Positive supply (5V) at pin 5, non standard position.',
      NC2:  'Not connected (pin 6).',
      NC3:  'Not connected (pin 7).',
      QC:   'Bit 2 of the binary count (weight 4).',
      QB:   'Bit 1 of the binary count (weight 2).',
      GND:  'Ground reference at pin 10.',
      QD:   'Bit 3 of the binary count (weight 8, MSB).',
      QA:   'Bit 0 of the binary count (weight 1, LSB). Connect to CKB for 4 bit counting.',
      NC4:  'Not connected (pin 13).',
      CKA:  'Clock input for the divide-by-2 section (QA). Use as the main clock input.',
    },
    pinout: [
      { pin: 1, name: 'CKB', type: 'input' },
      { pin: 2, name: 'R01', type: 'input' },
      { pin: 3, name: 'R02', type: 'input' },
      { pin: 4, name: 'NC1', type: 'nc' },
      { pin: 5, name: 'VCC', type: 'power' },
      { pin: 6, name: 'NC2', type: 'nc' },
      { pin: 7, name: 'NC3', type: 'nc' },
      { pin: 8, name: 'QC', type: 'output' },
      { pin: 9, name: 'QB', type: 'output' },
      { pin: 10, name: 'GND', type: 'power' },
      { pin: 11, name: 'QD', type: 'output' },
      { pin: 12, name: 'QA', type: 'output' },
      { pin: 13, name: 'NC4', type: 'nc' },
      { pin: 14, name: 'CKA', type: 'input' },
    ],
    gates: [
      {
        type: 'COUNTER_4BIT',
        inputs: ['CKA', 'CKB', 'R01', 'R02'],
        outputs: ['QA', 'QB', 'QC', 'QD'],
      },
    ],
    sequential: true,
    guideSections: [
      {
        title: '4 bit Binary Counting (0 to 15)',
        paragraphs: [
          'For a full 4 bit counter, connect QA to CKB and apply your clock to CKA. Outputs QA to QD count 0 to 15 in binary, then wrap back to 0.',
          'To reset the counter: assert both R01 and R02 HIGH at the same time. For normal counting, keep R01 and R02 LOW.',
        ],
        note: 'VCC is at pin 5 and GND is at pin 10, both non standard for a 14 pin DIP.',
      },
    ],
  },

  // ── 7495: 4 bit Parallel-access Shift Register ─────────────────────────
  /* Primary source: Texas Instruments, SN74LS95B datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls95b.pdf
     Shift register concept: https://en.wikipedia.org/wiki/Shift_register */
  '7495': {
    name: '74x95',
    simpleName: '4 bit Parallel Access Shift Register',
    description: '4 bit universal shift register with parallel load and serial shift modes (14 pin)',
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls95b.pdf',
    tags: ['shift register', 'parallel', '4 bit', 'sequential', 'serial', 'universal'],
    guideOverview: 'The 74x95 is a 4 bit universal shift register with two operating modes. In shift mode (MODE LOW), data shifts serially through the register on CLK1. In parallel load mode (MODE HIGH), data from inputs A to D is loaded into the register on CLK2. Outputs QA to QD are always available.',
    guidePinDescriptions: {
      SER:  'Serial data input. Shifts into QA on each CLK1 pulse when in shift mode.',
      A:    'Parallel data input for bit 0 (QA). Loaded when MODE is HIGH on CLK2.',
      B:    'Parallel data input for bit 1 (QB). Loaded when MODE is HIGH on CLK2.',
      C:    'Parallel data input for bit 2 (QC). Loaded when MODE is HIGH on CLK2.',
      D:    'Parallel data input for bit 3 (QD). Loaded when MODE is HIGH on CLK2.',
      MODE: 'Mode select. LOW = shift mode (use CLK1). HIGH = parallel load mode (use CLK2).',
      GND:  'Ground reference (pin 7).',
      CLK2: 'Clock for parallel load mode. Loads A to D into register when MODE is HIGH.',
      CLK1: 'Clock for shift mode. Shifts data right (SER → QA → QB → QC → QD) when MODE is LOW.',
      QD:   'Output bit 3 (MSB) of the shift register.',
      QC:   'Output bit 2 of the shift register.',
      QB:   'Output bit 1 of the shift register.',
      QA:   'Output bit 0 (LSB) of the shift register.',
      VCC:  'Positive supply (5V) at pin 14.',
    },
    pinout: [
      { pin: 1, name: 'SER', type: 'input' },
      { pin: 2, name: 'A', type: 'input' },
      { pin: 3, name: 'B', type: 'input' },
      { pin: 4, name: 'C', type: 'input' },
      { pin: 5, name: 'D', type: 'input' },
      { pin: 6, name: 'MODE', type: 'input' },
      { pin: 7, name: 'GND', type: 'power' },
      { pin: 8, name: 'CLK2', type: 'input' },
      { pin: 9, name: 'CLK1', type: 'input' },
      { pin: 10, name: 'QD', type: 'output' },
      { pin: 11, name: 'QC', type: 'output' },
      { pin: 12, name: 'QB', type: 'output' },
      { pin: 13, name: 'QA', type: 'output' },
      { pin: 14, name: 'VCC', type: 'power' },
    ],
    gates: [
      {
        type: 'SHIFT_REG_4BIT',
        inputs: ['SER', 'A', 'B', 'C', 'D', 'MODE', 'CLK1', 'CLK2'],
        outputs: ['QA', 'QB', 'QC', 'QD'],
      },
    ],
    sequential: true,
    guideSections: [
      {
        title: 'Shift and Parallel Load Modes',
        paragraphs: [
          'Shift mode (MODE=LOW): Apply a clock to CLK1. On each rising edge, the contents shift right: SER → QA → QB → QC → QD. The previous QD value is lost.',
          'Parallel load mode (MODE=HIGH): Apply a clock to CLK2. On the rising edge, inputs A, B, C, D are loaded directly into QA, QB, QC, QD simultaneously.',
        ],
      },
    ],
  },

  // ── 74107: Dual J-K flip-flop with clear ───────────────────────────────
  /* Primary source: Texas Instruments, SN74LS107A datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls107a.pdf
     Flip-flop concept: https://en.wikipedia.org/wiki/Flip-flop_(electronics) */
  '74107': {
    name: '74x107',
    simpleName: 'Dual JK FF (Neg Edge, Active LOW CLR)',
    description: 'Dual negative edge triggered JK flip-flop with individual active LOW async clear (14 pin)',
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls107a.pdf',
    tags: ['flip-flop', 'flip flop', 'jk', 'sequential', 'dual', 'clear', 'negative-edge'],
    guideOverview: 'The 74x107 contains two independent negative edge triggered JK flip-flops. Each flip-flop has its own J, K, clock, and active LOW asynchronous clear. On the falling edge of the clock: J=0,K=0 → hold; J=1,K=0 → set; J=0,K=1 → reset; J=1,K=1 → toggle. CLR=LOW resets Q to 0 immediately.',
    guidePinDescriptions: {
      '1J':   'J input for flip-flop 1.',
      '1Qn':  'Inverting (complement) output of flip-flop 1.',
      '1Q':   'Non inverting output of flip-flop 1.',
      '1K':   'K input for flip-flop 1.',
      '2Q':   'Non inverting output of flip-flop 2.',
      '2Qn':  'Inverting (complement) output of flip-flop 2.',
      GND:    'Ground reference (pin 7).',
      '2J':   'J input for flip-flop 2.',
      '2CLK': 'Clock input for flip-flop 2. State updates on the falling (negative) edge.',
      '2CLR': 'Active LOW async clear for FF2. When LOW, forces 2Q=0 regardless of clock.',
      '2K':   'K input for flip-flop 2.',
      '1CLK': 'Clock input for flip-flop 1. State updates on the falling (negative) edge.',
      '1CLR': 'Active LOW async clear for FF1. When LOW, forces 1Q=0 regardless of clock.',
      VCC:    'Positive supply (5V) at pin 14.',
    },
    pinout: [
      { pin: 1, name: '1J', type: 'input' },
      { pin: 2, name: '1Qn', type: 'output' },
      { pin: 3, name: '1Q', type: 'output' },
      { pin: 4, name: '1K', type: 'input' },
      { pin: 5, name: '2Q', type: 'output' },
      { pin: 6, name: '2Qn', type: 'output' },
      { pin: 7, name: 'GND', type: 'power' },
      { pin: 8, name: '2J', type: 'input' },
      { pin: 9, name: '2CLK', type: 'input' },
      { pin: 10, name: '2CLR', type: 'input' },
      { pin: 11, name: '2K', type: 'input' },
      { pin: 12, name: '1CLK', type: 'input' },
      { pin: 13, name: '1CLR', type: 'input' },
      { pin: 14, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'JK_FF_SIMPLE', inputs: ['1J', '1K', '1CLK', '1CLR'], outputs: ['1Q', '1Qn'] },
      { type: 'JK_FF_SIMPLE', inputs: ['2J', '2K', '2CLK', '2CLR'], outputs: ['2Q', '2Qn'] },
    ],
    sequential: true,
    guideSections: [
      {
        title: 'JK Flip-Flop Operation',
        paragraphs: [
          'On the falling edge of each CLK: J=0,K=0 → output holds; J=1,K=0 → Q goes HIGH (set); J=0,K=1 → Q goes LOW (reset); J=1,K=1 → Q toggles.',
          'The active LOW CLR overrides the clock asynchronously. Pulling CLRn LOW forces Q=0 and Qn=1 immediately without waiting for a clock edge.',
        ],
        note: 'The two flip-flops are fully independent, each has its own clock and clear. Unlike the 7478, there is no shared clock or shared clear here.',
      },
    ],
  },

  // ── 74109: Dual J-K positive-edge-triggered flip-flop with preset and clear ─
  /* Primary source: Texas Instruments, SN74LS109A datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls109a.pdf
     Flip-flop concept: https://en.wikipedia.org/wiki/Flip-flop_(electronics) */
  '74109': {
    name: '74x109',
    simpleName: 'Dual JK# FF (pos-edge)',
    description: 'Dual J-K positive edge triggered flip-flop with active LOW preset and clear. (16 pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls109a.pdf',
    tags: ['flip-flop', 'flip flop', 'jk', 'sequential', 'dual', 'edge-triggered', 'positive-edge', 'preset', 'clear'],
    guideOverview: 'The 74x109 provides two independent positive edge triggered J-K flip-flops. Unlike most JK flip-flops that have active HIGH K, this device uses an active LOW K input (Kn). So to set the flip-flop: J=1, Kn=1 (K effectively LOW); to reset: J=0, Kn=0 (K effectively HIGH). Both active LOW preset (PRE#) and clear (CLR#) pins override the clock asynchronously.',
    guidePinDescriptions: {
      '1CLR': 'Asynchronous clear for FF1, active LOW. Forces 1Q=0 immediately.',
      '1J':   'J input for FF1.',
      '1Kn':  'K-bar (inverted K) input for FF1. Pull LOW to effectively set K=HIGH (reset on clock edge); pull HIGH to set K=LOW (set on clock edge).',
      '1CLK': 'Clock input for FF1. State changes on the rising edge.',
      '1PRE': 'Asynchronous preset for FF1, active LOW. Forces 1Q=1 immediately.',
      '1Q':   'True output of FF1.',
      '1Qn':  'Inverted output of FF1.',
      'GND':  'Ground reference (pin 8).',
      '2Qn':  'Inverted output of FF2.',
      '2Q':   'True output of FF2.',
      '2PRE': 'Asynchronous preset for FF2, active LOW.',
      '2CLK': 'Clock input for FF2. State changes on the rising edge.',
      '2Kn':  'K-bar input for FF2.',
      '2J':   'J input for FF2.',
      '2CLR': 'Asynchronous clear for FF2, active LOW.',
      'VCC':  'Positive supply (+5 V) at pin 16.',
    },
    guideSections: [
      {
        title: 'J-K# (Inverted K) Operation',
        paragraphs: [
          'The 74x109 uses J and Kn (K-bar) rather than J and K. Kn is the logical complement of K: when Kn=LOW, K is effectively HIGH.',
          'J=0, Kn=1 → hold (J=0, K=0); J=1, Kn=1 → set Q=1 (J=1, K=0); J=0, Kn=0 → reset Q=0 (J=0, K=1); J=1, Kn=0 → toggle (J=1, K=1).',
        ],
        note: 'Updates occur on the positive (rising) clock edge, unlike the 74x76 and 74x73 which trigger on the negative edge.',
      },
    ],
    pinout: [
      { pin: 1,  name: '1CLR', type: 'input',  description: 'Clear (reset) input for FF1 (active LOW, sets Q=0 immediately)' },
      { pin: 2,  name: '1J',   type: 'input',  description: 'J input for FF1' },
      { pin: 3,  name: '1Kn',  type: 'input',  description: 'K-bar (inverted K) input for FF1, LOW=set, HIGH=reset when clocked' },
      { pin: 4,  name: '1CLK', type: 'input',  description: 'Clock input for FF1 (triggers on rising edge)' },
      { pin: 5,  name: '1PRE', type: 'input',  description: 'Preset input for FF1 (active LOW, sets Q=1 immediately)' },
      { pin: 6,  name: '1Q',   type: 'output', description: 'Q output of FF1' },
      { pin: 7,  name: '1Qn',  type: 'output', description: 'Q-bar (inverted) output of FF1' },
      { pin: 8,  name: 'GND',  type: 'power' },
      { pin: 9,  name: '2Qn',  type: 'output', description: 'Q-bar (inverted) output of FF2' },
      { pin: 10, name: '2Q',   type: 'output', description: 'Q output of FF2' },
      { pin: 11, name: '2PRE', type: 'input',  description: 'Preset input for FF2 (active LOW, sets Q=1 immediately)' },
      { pin: 12, name: '2CLK', type: 'input',  description: 'Clock input for FF2 (triggers on rising edge)' },
      { pin: 13, name: '2Kn',  type: 'input',  description: 'K-bar (inverted K) input for FF2, LOW=set, HIGH=reset when clocked' },
      { pin: 14, name: '2J',   type: 'input',  description: 'J input for FF2' },
      { pin: 15, name: '2CLR', type: 'input',  description: 'Clear (reset) input for FF2 (active LOW, sets Q=0 immediately)' },
      { pin: 16, name: 'VCC',  type: 'power' },
    ],
    gates: [
      { type: 'JK_FF_FULL', inputs: ['1J', '1Kn', '1CLK', '1PRE', '1CLR'], outputs: ['1Q', '1Qn'] },
      { type: 'JK_FF_FULL', inputs: ['2J', '2Kn', '2CLK', '2PRE', '2CLR'], outputs: ['2Q', '2Qn'] },
    ],
    sequential: true,
  },

  // ── 74121: Monostable Multivibrator ────────────────────────────────────
  /* Primary source: Texas Instruments, SN74121 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74121.pdf */
  '74121': {
    name: '74x121',
    simpleName: 'One-Shot (non retrig)',
    description: 'Non retriggerable monostable multivibrator (one-shot pulse generator). (14 pin)',
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74121.pdf',
    tags: ['monostable', 'multivibrator', 'one-shot', 'timer', 'pulse', 'non-retriggerable'],
    guideOverview: 'The 74x121 is a non retriggerable monostable multivibrator (one-shot). When triggered, it generates a single fixed width output pulse. If additional triggers arrive during the pulse, they are ignored. The pulse width is set by an internal 2 kΩ resistor (when RINT is tied to VCC) or an external RC network on the REXT/CEXT pins.',
    guidePinDescriptions: {
      'Qn':   'Inverted output. HIGH when idle; LOW during the output pulse.',
      'NC1':  'Not connected (pin 2). Leave unconnected.',
      'A1':   'Trigger input 1, active LOW. A falling edge here (while B=HIGH) triggers the one-shot.',
      'A2':   'Trigger input 2, active LOW. A falling edge here (while B=HIGH) triggers the one-shot.',
      'B':    'Trigger input, active HIGH. A rising edge here (while A1 or A2 is LOW) triggers the one-shot.',
      'Q':    'True output. LOW when idle; HIGH during the output pulse.',
      'GND':  'Ground reference (pin 7).',
      'NC2':  'Not connected (pin 8).',
      'RINT': 'Internal resistor connection. Tie to VCC to use the internal ~2 kΩ timing resistor.',
      'CEXT': 'External timing capacitor. Connect one side here, other side to REXT.',
      'REXT': 'External timing resistor connection. RC network here sets pulse width.',
      'NC3':  'Not connected (pin 12).',
      'NC4':  'Not connected (pin 13).',
      'VCC':  'Positive supply (+5 V) at pin 14.',
    },
    guideSections: [
      {
        title: 'One-Shot Pulse Width',
        paragraphs: [
          'Connect a resistor R between VCC and REXT, and a capacitor C from REXT to GND. The output pulse width is approximately: tW ≈ 0.7 × R × C. Minimum pulse with internal resistor only (~2 kΩ) and no external capacitor is approximately 35 ns.',
          'To trigger: hold B=HIGH and pulse A1 or A2 LOW; or hold A1 and A2 LOW and pulse B HIGH. Once triggered, additional triggers are ignored until the pulse ends.',
        ],
        formulas: ['tW ≈ 0.7 × R × C'],
        note: 'For a retriggerable version that extends the pulse on each new trigger, use the 74x122 or 74x123.',
      },
    ],
    pinout: [
      { pin: 1,  name: 'Qn',   type: 'output', description: 'Inverted (Q-bar) output, HIGH when idle, LOW during pulse' },
      { pin: 2,  name: 'NC1',  type: 'nc',  description: 'No connection' },
      { pin: 3,  name: 'A1',   type: 'input',  description: 'Active LOW trigger input 1 (used with B to trigger pulse)' },
      { pin: 4,  name: 'A2',   type: 'input',  description: 'Active LOW trigger input 2 (used with B to trigger pulse)' },
      { pin: 5,  name: 'B',    type: 'input',  description: 'Active HIGH trigger input; pulse fires when B=HIGH and A1 or A2 is LOW' },
      { pin: 6,  name: 'Q',    type: 'output', description: 'Non inverted output, LOW when idle, HIGH during pulse' },
      { pin: 7,  name: 'GND',  type: 'power' },
      { pin: 8,  name: 'NC2',  type: 'nc',  description: 'No connection' },
      { pin: 9,  name: 'RINT', type: 'input',  description: 'Connect to VCC to use internal timing resistor (~2kΩ)' },
      { pin: 10, name: 'CEXT', type: 'input',  description: 'External timing capacitor connection' },
      { pin: 11, name: 'REXT', type: 'input',  description: 'External timing resistor/RC network connection' },
      { pin: 12, name: 'NC3',  type: 'nc',  description: 'No connection' },
      { pin: 13, name: 'NC4',  type: 'nc',  description: 'No connection' },
      { pin: 14, name: 'VCC',  type: 'power' },
    ],
    gates: [
      { type: 'MONOSTABLE', inputs: ['A1', 'A2', 'B'], outputs: ['Q', 'Qn'] },
    ],
    sequential: true,
  },

  // ── 74122: Retriggerable Monostable Multivibrator (with clear) ─────────
  /* Primary source: Texas Instruments, SN74LS122 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls122.pdf */
  '74122': {
    name: '74x122',
    simpleName: 'One-Shot (retriggerable)',
    description: 'Retriggerable monostable multivibrator (one-shot) with active LOW clear. (14 pin)',
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls122.pdf',
    tags: ['monostable', 'multivibrator', 'one-shot', 'timer', 'pulse', 'retriggerable', 'clear'],
    guideOverview: 'The 74x122 is a single retriggerable monostable multivibrator. Unlike the 74x121, each new valid trigger while the output pulse is active extends the pulse duration from that moment. This allows you to create a pulse that stays HIGH as long as triggers keep arriving within the pulse interval. An active LOW CLR input can terminate the pulse immediately.',
    guidePinDescriptions: {
      'A1':   'Trigger input 1, active LOW.',
      'A2':   'Trigger input 2, active LOW.',
      'B1':   'Trigger input 1, active HIGH.',
      'B2':   'Trigger input 2, active HIGH.',
      'CLR':  'Clear, active LOW. Pull LOW to immediately end any active pulse and return output to idle.',
      'Qn':   'Inverted output. HIGH when idle, LOW during pulse.',
      'GND':  'Ground reference (pin 7).',
      'Q':    'True output. LOW when idle, HIGH during pulse.',
      'RINT': 'Connect to VCC to use internal 10 kΩ timing resistor.',
      'NC1':  'Not connected (pin 10).',
      'CEXT': 'External timing capacitor connection.',
      'NC2':  'Not connected (pin 12).',
      'REXT': 'External timing resistor/RC network connection.',
      'VCC':  'Positive supply (+5 V) at pin 14.',
    },
    guideSections: [
      {
        title: 'Retriggerable One-Shot',
        paragraphs: [
          'On each valid trigger edge, the output goes HIGH for a duration of tW. If another valid trigger arrives before tW expires, the timer resets and the output remains HIGH for another full tW from that point.',
          'This is useful for watchdog timers and activity detectors: the output stays HIGH while signals keep arriving and drops LOW only when there is a gap larger than tW.',
        ],
        formulas: ['tW ≈ 0.7 × R × C'],
        note: 'For a non retriggerable one-shot, use the 74x121 or 74x221.',
      },
    ],
    pinout: [
      { pin: 1,  name: 'A1',   type: 'input',  description: 'Active LOW trigger input 1' },
      { pin: 2,  name: 'A2',   type: 'input',  description: 'Active LOW trigger input 2' },
      { pin: 3,  name: 'B1',   type: 'input',  description: 'Active HIGH trigger input 1' },
      { pin: 4,  name: 'B2',   type: 'input',  description: 'Active HIGH trigger input 2' },
      { pin: 5,  name: 'CLR',  type: 'input',  description: 'Clear input (active LOW), aborts pulse and forces Q=LOW' },
      { pin: 6,  name: 'Qn',   type: 'output', description: 'Inverted (Q-bar) output, HIGH when idle, LOW during pulse' },
      { pin: 7,  name: 'GND',  type: 'power' },
      { pin: 8,  name: 'Q',    type: 'output', description: 'Non inverted output, LOW when idle, HIGH during pulse' },
      { pin: 9,  name: 'RINT', type: 'input',  description: 'Connect to VCC to use internal 10kΩ timing resistor' },
      { pin: 10, name: 'NC1',  type: 'nc',  description: 'No connection' },
      { pin: 11, name: 'CEXT', type: 'input',  description: 'External timing capacitor connection' },
      { pin: 12, name: 'NC2',  type: 'nc',  description: 'No connection' },
      { pin: 13, name: 'REXT', type: 'input',  description: 'External timing resistor/RC network connection' },
      { pin: 14, name: 'VCC',  type: 'power' },
    ],
    gates: [
      { type: 'MONOSTABLE_122', inputs: ['A1', 'A2', 'B1', 'B2', 'CLR'], outputs: ['Q', 'Qn'] },
    ],
    sequential: true,
  },
  '74123': {
    name: '74x123',
    simpleName: 'Dual One-Shot (retriggerable)',
    description: 'Dual retriggerable monostable multivibrator with active LOW clear. (16 pin)',
    guideOverview: 'The 74x123 is the dual version of the 74x122: two independent retriggerable one-shot circuits in a 16 pin package. Each section has separate A# (active LOW) and B (active HIGH) trigger inputs, an active LOW clear, and individual external R/C timing pins. Both Q and Q-bar outputs are available per section.',
    guidePinDescriptions: {
      '1A':    'Active LOW trigger for section 1. Falling edge (while 1B=HIGH) triggers the pulse.',
      '1B':    'Active HIGH trigger for section 1. Rising edge (while 1A#=LOW) triggers the pulse.',
      '1CLR':  'Clear for section 1, active LOW. Pull LOW to immediately end pulse.',
      '1Qn':   'Inverted output of section 1. HIGH when idle, LOW during pulse.',
      '2Q':    'True output of section 2. LOW when idle, HIGH during pulse.',
      '2CEXT': 'External timing capacitor connection for section 2.',
      '2REXT': 'External timing resistor connection for section 2.',
      'GND':   'Ground reference (pin 8).',
      '2A':    'Active LOW trigger for section 2.',
      '2B':    'Active HIGH trigger for section 2.',
      '2CLR':  'Clear for section 2, active LOW.',
      '2Qn':   'Inverted output of section 2.',
      '1Q':    'True output of section 1. LOW when idle, HIGH during pulse.',
      '1CEXT': 'External timing capacitor connection for section 1.',
      '1REXT': 'External timing resistor connection for section 1.',
      'VCC':   'Positive supply (+5 V) at pin 16.',
    },
    guideSections: [
      {
        title: 'Dual Retriggerable One-Shot',
        paragraphs: [
          'Each section operates independently. Connect an external resistor (REXT to VCC) and capacitor (CEXT to GND) to set the pulse width: tW ≈ 0.7 × R × C.',
          'Retriggerable: each new trigger during an active pulse extends the timing from that moment. Use the 74x221 for non retriggerable dual one-shots.',
        ],
        formulas: ['tW ≈ 0.7 × R × C'],
      },
    ],
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls123.pdf',
    tags: ['monostable', 'multivibrator', 'one-shot', 'retriggerable', 'dual', 'timer', 'pulse', 'clear'],
    pinout: [
      { pin: 1,  name: '1A',    type: 'input',  description: 'Active LOW trigger input for section 1 (falling edge or LOW level triggers)' },
      { pin: 2,  name: '1B',    type: 'input',  description: 'Active HIGH trigger input for section 1 (rising edge or HIGH level triggers)' },
      { pin: 3,  name: '1CLR',  type: 'input',  description: 'Clear input for section 1 (active LOW, aborts pulse and forces Q=LOW)' },
      { pin: 4,  name: '1Qn',   type: 'output', description: 'Inverted output of section 1, HIGH when idle, LOW during pulse' },
      { pin: 5,  name: '2Q',    type: 'output', description: 'Non inverted output of section 2, LOW when idle, HIGH during pulse' },
      { pin: 6,  name: '2CEXT', type: 'input',  description: 'External timing capacitor connection for section 2' },
      { pin: 7,  name: '2REXT', type: 'input',  description: 'External timing resistor/RC connection for section 2' },
      { pin: 8,  name: 'GND',   type: 'power' },
      { pin: 9,  name: '2A',    type: 'input',  description: 'Active LOW trigger input for section 2' },
      { pin: 10, name: '2B',    type: 'input',  description: 'Active HIGH trigger input for section 2' },
      { pin: 11, name: '2CLR',  type: 'input',  description: 'Clear input for section 2 (active LOW, aborts pulse and forces Q=LOW)' },
      { pin: 12, name: '2Qn',   type: 'output', description: 'Inverted output of section 2, HIGH when idle, LOW during pulse' },
      { pin: 13, name: '1Q',    type: 'output', description: 'Non inverted output of section 1, LOW when idle, HIGH during pulse' },
      { pin: 14, name: '1CEXT', type: 'input',  description: 'External timing capacitor connection for section 1' },
      { pin: 15, name: '1REXT', type: 'input',  description: 'External timing resistor/RC connection for section 1' },
      { pin: 16, name: 'VCC',   type: 'power' },
    ],
    gates: [
      { type: 'MONOSTABLE_RETRIG', inputs: ['1A', '1B', '1CLR'], outputs: ['1Q', '1Qn'] },
      { type: 'MONOSTABLE_RETRIG', inputs: ['2A', '2B', '2CLR'], outputs: ['2Q', '2Qn'] },
    ],
    sequential: true,
  },

  // ── 74221: Dual Non-Retriggerable Monostable Multivibrator (with clear) ─
  /* Primary source: Texas Instruments, SN74LS221 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls221.pdf */
  // Like the 74121 but doubled. Each section fires a fixed-width pulse on a
  // valid trigger edge; unlike the 74123 it does NOT extend on re-trigger.
  // CLR immediately terminates the output pulse when pulled LOW.
  '74221': {
    name: '74x221',
    simpleName: 'Dual One-Shot (non retrig, CLR)',
    description: 'Dual non retriggerable monostable multivibrator with active LOW clear. (16 pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls221.pdf',
    tags: ['monostable', 'multivibrator', 'one-shot', 'timer', 'pulse', 'non-retriggerable', 'dual', 'clear'],
    guideOverview: 'The 74221 contains two independent non retriggerable one-shot circuits. Each section generates a single output pulse when triggered either by a falling edge on the A# (active LOW) input or a rising edge on the B (active HIGH) input. Once the pulse starts, additional triggers are ignored until the pulse ends. An active LOW CLR input can terminate the pulse early at any time. Pulse width is determined by external resistor and capacitor values: tW ≈ 0.7 × Rext × Cext.',
    guidePinDescriptions: {
      '1A':   'Active LOW trigger input for section 1. A falling edge here (while B is HIGH) starts the one-shot pulse.',
      '1B':   'Active HIGH trigger input for section 1. A rising edge here (while A# is LOW) starts the one-shot pulse.',
      '1CLR': 'Clear for section 1 (active LOW). Pulling LOW immediately resets the output to idle (Q=LOW, Q#=HIGH).',
      '1Q':   'True output of section 1, LOW when idle, HIGH during the timed pulse.',
      '1Qn':  'Inverted output of section 1, HIGH when idle, LOW during the timed pulse.',
      '2A':   'Active LOW trigger input for section 2.',
      '2B':   'Active HIGH trigger input for section 2.',
      '2CLR': 'Clear for section 2 (active LOW). Pulling LOW immediately resets section 2 output.',
      '2Q':   'True output of section 2, LOW when idle, HIGH during the timed pulse.',
      '2Qn':  'Inverted output of section 2, HIGH when idle, LOW during the timed pulse.',
    },
    pinout: [
      { pin: 1,  name: '1A',    type: 'input',  description: 'Active LOW trigger input for section 1. Falling edge triggers the one-shot (when 1B=HIGH).' },
      { pin: 2,  name: '1B',    type: 'input',  description: 'Active HIGH trigger input for section 1. Rising edge triggers the one-shot (when 1A#=LOW).' },
      { pin: 3,  name: '1CLR',  type: 'input',  description: 'Clear for section 1 (active LOW). Drive LOW to immediately end any active pulse.' },
      { pin: 4,  name: '1Qn',   type: 'output', description: 'Inverted output of section 1, HIGH when idle, LOW during pulse.' },
      { pin: 5,  name: '2Q',    type: 'output', description: 'True output of section 2, LOW when idle, HIGH during pulse.' },
      { pin: 6,  name: '2CEXT', type: 'input',  description: 'External timing capacitor connection for section 2.' },
      { pin: 7,  name: '2REXT', type: 'input',  description: 'External timing resistor/RC network connection for section 2.' },
      { pin: 8,  name: 'GND',   type: 'power' },
      { pin: 9,  name: '2A',    type: 'input',  description: 'Active LOW trigger input for section 2. Falling edge triggers the one-shot (when 2B=HIGH).' },
      { pin: 10, name: '2B',    type: 'input',  description: 'Active HIGH trigger input for section 2. Rising edge triggers the one-shot (when 2A#=LOW).' },
      { pin: 11, name: '2CLR',  type: 'input',  description: 'Clear for section 2 (active LOW). Drive LOW to immediately end any active pulse.' },
      { pin: 12, name: '2Qn',   type: 'output', description: 'Inverted output of section 2, HIGH when idle, LOW during pulse.' },
      { pin: 13, name: '1Q',    type: 'output', description: 'True output of section 1, LOW when idle, HIGH during pulse.' },
      { pin: 14, name: '1CEXT', type: 'input',  description: 'External timing capacitor connection for section 1.' },
      { pin: 15, name: '1REXT', type: 'input',  description: 'External timing resistor/RC network connection for section 1.' },
      { pin: 16, name: 'VCC',   type: 'power' },
    ],
    gates: [
      { type: 'MONOSTABLE', inputs: ['1A', '1B', '1CLR'], outputs: ['1Q', '1Qn'] },
      { type: 'MONOSTABLE', inputs: ['2A', '2B', '2CLR'], outputs: ['2Q', '2Qn'] },
    ],
    sequential: true,
    guideSections: [
      {
        title: 'Non Retriggerable Dual One-Shot',
        paragraphs: [
          'Each section produces a single fixed width output pulse when triggered. Additional triggers during the pulse are ignored, the timer runs to completion before the circuit can be triggered again.',
          'Pulse width: tW ≈ 0.7 × Rext × Cext. Connect external R from VCC to REXT and external C from REXT to GND.',
        ],
        formulas: ['tW ≈ 0.7 × R × C'],
        note: 'Use the 74x123 for a retriggerable version. CLR# can terminate the pulse early at any time.',
      },
    ],
  },

  // ── 74125: Quad Bus Buffer (tri-state, active low enable) ──────────────
  /* Primary source: Texas Instruments, SN74LS125A datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls125a.pdf
     Three-state (tri-state) logic: https://en.wikipedia.org/wiki/Three-state_logic */
  '74125': {
    name: '74x125',
    simpleName: 'Quad Tristate Buffer (active LOW OE)',
    description: 'Quad non inverting tristate buffer with active LOW output enable. (14 pin)',
    guideOverview: 'The 74x125 contains four independent non inverting tristate buffers. Each buffer has its own active LOW output enable (OE#). When OE# is LOW, the output follows the input. When OE# is HIGH, the output goes to a high impedance (Hi-Z) state, effectively disconnecting from the bus. All four buffers can independently control their own presence on a shared bus.',
    guidePinDescriptions: {
      '1OE': 'Output enable for buffer 1, active LOW. LOW = output active; HIGH = Hi-Z (disconnected).',
      '1A':  'Data input for buffer 1.',
      '1Y':  'Tristate output of buffer 1. Follows 1A when 1OE is LOW; Hi-Z when 1OE is HIGH.',
      '2OE': 'Output enable for buffer 2, active LOW.',
      '2A':  'Data input for buffer 2.',
      '2Y':  'Tristate output of buffer 2.',
      'GND': 'Ground reference (pin 7).',
      '3Y':  'Tristate output of buffer 3.',
      '3A':  'Data input for buffer 3.',
      '3OE': 'Output enable for buffer 3, active LOW.',
      '4Y':  'Tristate output of buffer 4.',
      '4A':  'Data input for buffer 4.',
      '4OE': 'Output enable for buffer 4, active LOW.',
      'VCC': 'Positive supply (+5 V) at pin 14.',
    },
    guideSections: [
      {
        title: 'Tristate Bus Buffer',
        paragraphs: [
          'A tristate buffer can output logic HIGH, logic LOW, or high impedance (Hi-Z). Hi-Z means the output is electrically disconnected from the line, it neither drives HIGH nor LOW.',
          'Multiple tristate buffers can share a single bus line as long as only one is enabled at a time. Enabling two outputs simultaneously on the same line causes a bus contention (short circuit).',
        ],
        note: 'Use the 74x126 (active HIGH OE) when your enable logic is the opposite polarity.',
      },
    ],
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls125a.pdf',
    tags: ['buffer', 'tri-state', 'bus', 'quad', '3-state', 'non-inverting'],
    pinout: [
      { pin: 1,  name: '1OE', type: 'input',  description: 'Output enable for buffer 1 (active LOW: LOW=enabled, HIGH=Hi-Z)' },
      { pin: 2,  name: '1A',  type: 'input',  description: 'Data input for buffer 1' },
      { pin: 3,  name: '1Y',  type: 'output', description: 'Data output for buffer 1 (follows 1A when enabled, Hi-Z when disabled)' },
      { pin: 4,  name: '2OE', type: 'input',  description: 'Output enable for buffer 2 (active LOW)' },
      { pin: 5,  name: '2A',  type: 'input',  description: 'Data input for buffer 2' },
      { pin: 6,  name: '2Y',  type: 'output', description: 'Data output for buffer 2' },
      { pin: 7,  name: 'GND', type: 'power' },
      { pin: 8,  name: '3Y',  type: 'output', description: 'Data output for buffer 3' },
      { pin: 9,  name: '3A',  type: 'input',  description: 'Data input for buffer 3' },
      { pin: 10, name: '3OE', type: 'input',  description: 'Output enable for buffer 3 (active LOW)' },
      { pin: 11, name: '4Y',  type: 'output', description: 'Data output for buffer 4' },
      { pin: 12, name: '4A',  type: 'input',  description: 'Data input for buffer 4' },
      { pin: 13, name: '4OE', type: 'input',  description: 'Output enable for buffer 4 (active LOW)' },
      { pin: 14, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'TRI_BUFFER_LO', inputs: ['1A', '1OE'], output: '1Y' },
      { type: 'TRI_BUFFER_LO', inputs: ['2A', '2OE'], output: '2Y' },
      { type: 'TRI_BUFFER_LO', inputs: ['3A', '3OE'], output: '3Y' },
      { type: 'TRI_BUFFER_LO', inputs: ['4A', '4OE'], output: '4Y' },
    ],
  },

  // ── 74126: Quad Bus Buffer (tri-state, active high enable) ─────────────
  /* Primary source: Texas Instruments, SN74LS126A datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls126a.pdf
     Three-state (tri-state) logic: https://en.wikipedia.org/wiki/Three-state_logic */
  '74126': {
    name: '74x126',
    simpleName: 'Quad Tristate Buffer (active HIGH OE)',
    description: 'Quad non inverting tristate buffer with active HIGH output enable. (14 pin)',
    guideOverview: 'The 74x126 is identical to the 74x125 except the output enables are active HIGH. When OE is HIGH, the output follows the input. When OE is LOW, the output goes to Hi-Z. Use this device when your bus control logic uses active HIGH enables.',
    guidePinDescriptions: {
      '1OE': 'Output enable for buffer 1, active HIGH. HIGH = output active; LOW = Hi-Z.',
      '1A':  'Data input for buffer 1.',
      '1Y':  'Tristate output of buffer 1. Follows 1A when 1OE is HIGH; Hi-Z when 1OE is LOW.',
      '2OE': 'Output enable for buffer 2, active HIGH.',
      '2A':  'Data input for buffer 2.',
      '2Y':  'Tristate output of buffer 2.',
      'GND': 'Ground reference (pin 7).',
      '3Y':  'Tristate output of buffer 3.',
      '3A':  'Data input for buffer 3.',
      '3OE': 'Output enable for buffer 3, active HIGH.',
      '4Y':  'Tristate output of buffer 4.',
      '4A':  'Data input for buffer 4.',
      '4OE': 'Output enable for buffer 4, active HIGH.',
      'VCC': 'Positive supply (+5 V) at pin 14.',
    },
    guideSections: [
      {
        title: 'Active HIGH Tristate Buffer',
        paragraphs: ['Same tristate bus buffer as the 74x125, but with active HIGH enables. Only one buffer should be enabled on a shared bus at a time.'],
        note: 'Use the 74x125 (active LOW OE) when your control logic is inverted.',
      },
    ],
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls126a.pdf',
    tags: ['buffer', 'tri-state', 'bus', 'quad', '3-state', 'non-inverting'],
    pinout: [
      { pin: 1,  name: '1OE', type: 'input',  description: 'Output enable for buffer 1 (active HIGH: HIGH=enabled, LOW=Hi-Z)' },
      { pin: 2,  name: '1A',  type: 'input',  description: 'Data input for buffer 1' },
      { pin: 3,  name: '1Y',  type: 'output', description: 'Data output for buffer 1 (follows 1A when enabled, Hi-Z when disabled)' },
      { pin: 4,  name: '2OE', type: 'input',  description: 'Output enable for buffer 2 (active HIGH)' },
      { pin: 5,  name: '2A',  type: 'input',  description: 'Data input for buffer 2' },
      { pin: 6,  name: '2Y',  type: 'output', description: 'Data output for buffer 2' },
      { pin: 7,  name: 'GND', type: 'power' },
      { pin: 8,  name: '3Y',  type: 'output', description: 'Data output for buffer 3' },
      { pin: 9,  name: '3A',  type: 'input',  description: 'Data input for buffer 3' },
      { pin: 10, name: '3OE', type: 'input',  description: 'Output enable for buffer 3 (active HIGH)' },
      { pin: 11, name: '4Y',  type: 'output', description: 'Data output for buffer 4' },
      { pin: 12, name: '4A',  type: 'input',  description: 'Data input for buffer 4' },
      { pin: 13, name: '4OE', type: 'input',  description: 'Output enable for buffer 4 (active HIGH)' },
      { pin: 14, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'TRI_BUFFER_HI', inputs: ['1A', '1OE'], output: '1Y' },
      { type: 'TRI_BUFFER_HI', inputs: ['2A', '2OE'], output: '2Y' },
      { type: 'TRI_BUFFER_HI', inputs: ['3A', '3OE'], output: '3Y' },
      { type: 'TRI_BUFFER_HI', inputs: ['4A', '4OE'], output: '4Y' },
    ],
  },

  // ── 74132: Quad 2 input NAND (Schmitt trigger) ─────────────────────────
  /* Primary source: Texas Instruments, SN74LS132 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls132.pdf */
  '74132': {
    name: '74x132',
    simpleName: 'Quad 2 input NAND (Schmitt)',
    description: 'Quad 2 input NAND gate with Schmitt trigger inputs. (14 pin)',
    guideOverview: 'The 74x132 contains four 2 input NAND gates with Schmitt trigger inputs. The Schmitt trigger adds hysteresis to the input threshold: the positive going threshold (VT+) is higher than the negative going threshold (VT-). This makes the gates immune to slow, noisy, or bouncing input signals. Use it to clean up messy digital signals before feeding other logic.',
    guidePinDescriptions: {
      '1A':  'Schmitt trigger input A of NAND gate 1.',
      '1B':  'Schmitt trigger input B of NAND gate 1.',
      '1Y':  'Output of NAND gate 1. LOW only when both inputs are above VT+.',
      '2A':  'Schmitt trigger input A of NAND gate 2.',
      '2B':  'Schmitt trigger input B of NAND gate 2.',
      '2Y':  'Output of NAND gate 2.',
      'GND': 'Ground reference (pin 7).',
      '3Y':  'Output of NAND gate 3.',
      '3A':  'Schmitt trigger input A of NAND gate 3.',
      '3B':  'Schmitt trigger input B of NAND gate 3.',
      '4Y':  'Output of NAND gate 4.',
      '4A':  'Schmitt trigger input A of NAND gate 4.',
      '4B':  'Schmitt trigger input B of NAND gate 4.',
      'VCC': 'Positive supply (+5 V) at pin 14.',
    },
    guideSections: [
      {
        title: 'Schmitt Trigger Hysteresis',
        paragraphs: [
          'Normal TTL gates switch at a single threshold voltage. A Schmitt trigger input uses two thresholds: VT+ (typically ~1.7 V) for the rising transition and VT- (typically ~0.9 V) for the falling transition. The gap between them (hysteresis) prevents rapid toggling on slow or noisy signals.',
          'Typical uses include debouncing mechanical switches, squaring up slowly changing waveforms, and receiving signals from long cable runs.',
        ],
        note: 'The 74x132 is logically identical to the 74x00 but with Schmitt inputs. Swap it in when signal integrity is a problem.',
      },
    ],
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls132.pdf',
    tags: ['nand', 'gate', 'logic', 'quad', 'schmitt', 'schmitt-trigger', 'hysteresis', '2 input'],
    pinout: [
      { pin: 1,  name: '1A',  type: 'input',  description: 'Input A of NAND gate 1 (Schmitt-trigger)' },
      { pin: 2,  name: '1B',  type: 'input',  description: 'Input B of NAND gate 1 (Schmitt-trigger)' },
      { pin: 3,  name: '1Y',  type: 'output', description: 'Output of NAND gate 1: LOW only when both 1A and 1B are HIGH' },
      { pin: 4,  name: '2A',  type: 'input',  description: 'Input A of NAND gate 2 (Schmitt-trigger)' },
      { pin: 5,  name: '2B',  type: 'input',  description: 'Input B of NAND gate 2 (Schmitt-trigger)' },
      { pin: 6,  name: '2Y',  type: 'output', description: 'Output of NAND gate 2' },
      { pin: 7,  name: 'GND', type: 'power' },
      { pin: 8,  name: '3Y',  type: 'output', description: 'Output of NAND gate 3' },
      { pin: 9,  name: '3A',  type: 'input',  description: 'Input A of NAND gate 3 (Schmitt-trigger)' },
      { pin: 10, name: '3B',  type: 'input',  description: 'Input B of NAND gate 3 (Schmitt-trigger)' },
      { pin: 11, name: '4Y',  type: 'output', description: 'Output of NAND gate 4' },
      { pin: 12, name: '4A',  type: 'input',  description: 'Input A of NAND gate 4 (Schmitt-trigger)' },
      { pin: 13, name: '4B',  type: 'input',  description: 'Input B of NAND gate 4 (Schmitt-trigger)' },
      { pin: 14, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'NAND', inputs: ['1A', '1B'], output: '1Y' },
      { type: 'NAND', inputs: ['2A', '2B'], output: '2Y' },
      { type: 'NAND', inputs: ['3A', '3B'], output: '3Y' },
      { type: 'NAND', inputs: ['4A', '4B'], output: '4Y' },
    ],
  },

  // ── 74138: 3-to-8 Line Decoder / Demultiplexer ──────────────────────────
  /* Primary source: Texas Instruments, SN74HC138 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74hc138.pdf
     Decoder/demultiplexer concept: https://en.wikipedia.org/wiki/Multiplexer */
  // Three address inputs (A=LSB, B, C=MSB) select one of 8 active LOW outputs.
  // Three enable inputs must all be satisfied: G1 HIGH, G2A LOW, G2B LOW.
  // When disabled, all outputs are HIGH (inactive).
  '74138': {
    name: '74x138',
    simpleName: '3 to 8 Line Decoder',
    description: '3 to 8 line decoder/demultiplexer. (16-pin)',
    guideOverview: 'The 74x138 is a 3 to 8 line decoder/demultiplexer. Three binary address inputs (A=LSB, B, C=MSB) select one of eight active LOW outputs (Y0 Y7). Three enable inputs must all be satisfied simultaneously (G1=HIGH, G2A=LOW, G2B=LOW) for the selected output to go LOW. When disabled, all outputs are HIGH. A classic use is memory address decoding: use A, B, C as address lines and the enables for chip select.',
    guidePinDescriptions: {
      A:    'Address input, least significant bit (LSB, weight 1).',
      B:    'Address input, middle bit (weight 2).',
      C:    'Address input, most significant bit (MSB, weight 4).',
      G2A:  'Enable input 2A, active LOW. Must be LOW for any output to be selected.',
      G2B:  'Enable input 2B, active LOW. Must be LOW for any output to be selected.',
      G1:   'Enable input 1, active HIGH. Must be HIGH for any output to be selected.',
      Y7:   'Active LOW output for address 111 (C=1, B=1, A=1).',
      GND:  'Ground reference (pin 8).',
      Y6:   'Active LOW output for address 110.',
      Y5:   'Active LOW output for address 101.',
      Y4:   'Active LOW output for address 100.',
      Y3:   'Active LOW output for address 011.',
      Y2:   'Active LOW output for address 010.',
      Y1:   'Active LOW output for address 001.',
      Y0:   'Active LOW output for address 000 (all address inputs LOW).',
      VCC:  'Positive supply (+5 V) at pin 16.',
    },
    guideSections: [
      {
        title: '3 to 8 Decoding',
        paragraphs: [
          'When all three enables are satisfied (G1=HIGH, G2A=LOW, G2B=LOW), exactly one output goes LOW based on the binary value of CBA. All others remain HIGH. When disabled, all outputs are HIGH.',
          'The three enable pins can be used to daisy-chain multiple decoders for larger address spaces: connect the select output of a higher-level decoder to enable the appropriate 74x138.',
        ],
        list: [
          'Tie G2B to G2A (both to GND) and G1 to VCC for a simple always-enabled decoder.',
          'Use G1 as a chip-select and G2A/G2B as address enable inputs for memory banking.',
        ],
      },
    ],
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74hc138.pdf',
    tags: ['decoder', 'demultiplexer', 'demux', '3-to-8', '1-of-8', 'active low', 'logic', '74138', '74hc138', '74ls138'],
    pinout: [
      { pin: 1,  name: 'A',   type: 'input',  description: 'Address input, least significant bit' },
      { pin: 2,  name: 'B',   type: 'input',  description: 'Address input, middle bit' },
      { pin: 3,  name: 'C',   type: 'input',  description: 'Address input, most significant bit' },
      { pin: 4,  name: 'G2A', type: 'input',  description: 'Enable input, active LOW' },
      { pin: 5,  name: 'G2B', type: 'input',  description: 'Enable input, active LOW' },
      { pin: 6,  name: 'G1',  type: 'input',  description: 'Enable input, active HIGH' },
      { pin: 7,  name: 'Y7',  type: 'output', description: 'Output for address 111, active LOW' },
      { pin: 8,  name: 'GND', type: 'power' },
      { pin: 9,  name: 'Y6',  type: 'output', description: 'Output for address 110, active LOW' },
      { pin: 10, name: 'Y5',  type: 'output', description: 'Output for address 101, active LOW' },
      { pin: 11, name: 'Y4',  type: 'output', description: 'Output for address 100, active LOW' },
      { pin: 12, name: 'Y3',  type: 'output', description: 'Output for address 011, active LOW' },
      { pin: 13, name: 'Y2',  type: 'output', description: 'Output for address 010, active LOW' },
      { pin: 14, name: 'Y1',  type: 'output', description: 'Output for address 001, active LOW' },
      { pin: 15, name: 'Y0',  type: 'output', description: 'Output for address 000, active LOW' },
      { pin: 16, name: 'VCC', type: 'power' },
    ],
    gates: [
      {
        // Inputs order must match _evaluateDecoder3to8: [A, B, C, G1, G2A, G2B]
        // Enabled when G1=1, G2A=0, G2B=0; selected output = LOW, all others HIGH.
        // Address: index = A | (B<<1) | (C<<2)
        type: 'DECODER_3TO8',
        inputs: ['A', 'B', 'C', 'G1', 'G2A', 'G2B'],
        outputs: ['Y0', 'Y1', 'Y2', 'Y3', 'Y4', 'Y5', 'Y6', 'Y7'],
      },
    ],
  },

  // ── 74139: Dual 2-to-4 Decoder / Demultiplexer ─────────────────────────
  /* Primary source: Texas Instruments, SN74LS139A datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls139a.pdf
     Decoder/demultiplexer concept: https://en.wikipedia.org/wiki/Multiplexer */
  '74139': {
    name: '74x139',
    simpleName: 'Dual 2 to 4 Decoder',
    description: 'Dual independent 2 to 4 line decoder/demultiplexer. (16-pin)',
    guideOverview: 'The 74x139 contains two independent 2 to 4 line decoders in one 16-pin package. Each section has 2 address inputs, an active LOW enable, and 4 active LOW outputs. When enabled, exactly one output goes LOW based on the 2 bit address. Both sections can be used simultaneously as independent decoders or as a 1 of 4 demultiplexer.',
    guidePinDescriptions: {
      '1G':  'Enable for section 1, active LOW. HIGH disables all outputs of section 1 (all go HIGH).',
      '1A':  'Address bit 0 (LSB) for section 1.',
      '1B':  'Address bit 1 (MSB) for section 1.',
      '1Y0': 'Output 0 of section 1, active LOW. LOW when G=0, A=0, B=0.',
      '1Y1': 'Output 1 of section 1, active LOW. LOW when G=0, A=1, B=0.',
      '1Y2': 'Output 2 of section 1, active LOW. LOW when G=0, A=0, B=1.',
      '1Y3': 'Output 3 of section 1, active LOW. LOW when G=0, A=1, B=1.',
      'GND': 'Ground reference (pin 8).',
      '2Y3': 'Output 3 of section 2, active LOW.',
      '2Y2': 'Output 2 of section 2, active LOW.',
      '2Y1': 'Output 1 of section 2, active LOW.',
      '2Y0': 'Output 0 of section 2, active LOW.',
      '2B':  'Address bit 1 (MSB) for section 2.',
      '2A':  'Address bit 0 (LSB) for section 2.',
      '2G':  'Enable for section 2, active LOW.',
      'VCC': 'Positive supply (+5 V) at pin 16.',
    },
    guideSections: [
      {
        title: '2 to 4 Decoding',
        paragraphs: [
          'With enable LOW, the selected output (chosen by A and B) goes LOW. All other outputs stay HIGH. With enable HIGH, all four outputs are HIGH regardless of address.',
          'Two 74x139 sections together decode 2 independent 2 bit addresses. Chain two ICs to build a 3 to 8 decoder by using one section to create the MSB enable for each 74x139.',
        ],
      },
    ],
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls139a.pdf',
    tags: ['decoder', 'demultiplexer', 'demux', '2-to-4', 'dual', 'inverting', 'active low'],
    pinout: [
      { pin: 1,  name: '1G',  type: 'input',  description: 'Enable for section 1 (active LOW); HIGH disables all outputs' },
      { pin: 2,  name: '1A',  type: 'input',  description: 'Address bit 0 for section 1' },
      { pin: 3,  name: '1B',  type: 'input',  description: 'Address bit 1 for section 1' },
      { pin: 4,  name: '1Y0', type: 'output', description: 'Section 1 output 0 (active LOW; LOW when A=0, B=0)' },
      { pin: 5,  name: '1Y1', type: 'output', description: 'Section 1 output 1 (active LOW; LOW when A=1, B=0)' },
      { pin: 6,  name: '1Y2', type: 'output', description: 'Section 1 output 2 (active LOW; LOW when A=0, B=1)' },
      { pin: 7,  name: '1Y3', type: 'output', description: 'Section 1 output 3 (active LOW; LOW when A=1, B=1)' },
      { pin: 8,  name: 'GND', type: 'power',  description: 'Ground (0V)' },
      { pin: 9,  name: '2Y3', type: 'output', description: 'Section 2 output 3 (active LOW; LOW when A=1, B=1)' },
      { pin: 10, name: '2Y2', type: 'output', description: 'Section 2 output 2 (active LOW; LOW when A=0, B=1)' },
      { pin: 11, name: '2Y1', type: 'output', description: 'Section 2 output 1 (active LOW; LOW when A=1, B=0)' },
      { pin: 12, name: '2Y0', type: 'output', description: 'Section 2 output 0 (active LOW; LOW when A=0, B=0)' },
      { pin: 13, name: '2B',  type: 'input',  description: 'Address bit 1 for section 2' },
      { pin: 14, name: '2A',  type: 'input',  description: 'Address bit 0 for section 2' },
      { pin: 15, name: '2G',  type: 'input',  description: 'Enable for section 2 (active LOW); HIGH disables all outputs' },
      { pin: 16, name: 'VCC', type: 'power',  description: 'Positive supply (+5V)' },
    ],
    gates: [
      { type: 'DECODER_2TO4', inputs: ['1A', '1B', '1G'], outputs: ['1Y0', '1Y1', '1Y2', '1Y3'] },
      { type: 'DECODER_2TO4', inputs: ['2A', '2B', '2G'], outputs: ['2Y0', '2Y1', '2Y2', '2Y3'] },
    ],
  },
};
