// Chip definitions block 59
// Chips: 74x4305, 74x4306, 74x4316, 74x4351, 74x4352, 74x4353,
//        74x4374, 74x4510, 74x4511, 74x4514, 74x4515, 74x4516,
//        74x4518, 74x4520, 74x4543, 74x4560

export const CHIPS_BLOCK_59 = {

  // 74x4305: Dual 4 bit inverting buffer, three-state (20-pin)
  '74x4305': {
    name: '74x4305',
    simpleName: 'Dual 4 bit Inverting Buffer (TS)',
    description: 'Dual 4 bit inverting buffer with three-state outputs (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.ti.com/lit/gpn/sn74hc540',
    tags: ['buffer', 'inverting', 'dual', '4 bit', 'tri-state'],
    guideOverview: 'The 74x4305 is an octal inverting three-state buffer arranged as two 4 bit groups with separate enables. Each channel outputs the inverse of its input when enabled, or disconnects from the bus when disabled. This is useful for bus driving, signal isolation, and active LOW bus systems where eight channels of inverted buffering are needed.',
    guidePinDescriptions: {
      '1OEn': 'Active LOW output enable for buffer group 1. Pull LOW to enable outputs 1Y1 through 1Y4.',
      '1A1': 'Input bit 1 of group 1.',
      '1Y1': 'Inverted output bit 1 of group 1 (three-state).',
      '1A2': 'Input bit 2 of group 1.',
      '1Y2': 'Inverted output bit 2 of group 1 (three-state).',
      '1A3': 'Input bit 3 of group 1.',
      '1Y3': 'Inverted output bit 3 of group 1 (three-state).',
      '1A4': 'Input bit 4 of group 1.',
      '1Y4': 'Inverted output bit 4 of group 1 (three-state).',
      'GND': 'Ground reference for the package.',
      '2OEn': 'Active LOW output enable for buffer group 2.',
      '2A1': 'Input bit 1 of group 2.',
      '2Y1': 'Inverted output bit 1 of group 2 (three-state).',
      '2A2': 'Input bit 2 of group 2.',
      '2Y2': 'Inverted output bit 2 of group 2 (three-state).',
      '2A3': 'Input bit 3 of group 2.',
      '2Y3': 'Inverted output bit 3 of group 2 (three-state).',
      '2A4': 'Input bit 4 of group 2.',
      '2Y4': 'Inverted output bit 4 of group 2 (three-state).',
      'VCC': 'Positive supply for the device.',
    },
    guideSections: [
      {
        title: 'Inverting Buffer Groups',
        paragraphs: [
          'Each output drives the opposite logic state of its input. The two separate enable pins let you control the lower and upper four-bit groups independently.',
        ],
      },
      {
        title: 'Three-State Bus Use',
        paragraphs: [
          'When a group is disabled, its outputs disconnect instead of forcing HIGH or LOW. That makes the chip suitable for shared buses where multiple devices may take turns driving the same lines.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: '1OEn', type: 'input'  },
      { pin:  2, name: '1A1',  type: 'input'  },
      { pin:  3, name: '1Y1',  type: 'output' },
      { pin:  4, name: '1A2',  type: 'input'  },
      { pin:  5, name: '1Y2',  type: 'output' },
      { pin:  6, name: '1A3',  type: 'input'  },
      { pin:  7, name: '1Y3',  type: 'output' },
      { pin:  8, name: '1A4',  type: 'input'  },
      { pin:  9, name: '1Y4',  type: 'output' },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: '2OEn', type: 'input'  },
      { pin: 12, name: '2A1',  type: 'input'  },
      { pin: 13, name: '2Y1',  type: 'output' },
      { pin: 14, name: '2A2',  type: 'input'  },
      { pin: 15, name: '2Y2',  type: 'output' },
      { pin: 16, name: '2A3',  type: 'input'  },
      { pin: 17, name: '2Y3',  type: 'output' },
      { pin: 18, name: '2A4',  type: 'input'  },
      { pin: 19, name: '2Y4',  type: 'output' },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'TRI_NOT_LO', inputs: ['1A1', '1OEn'], output: '1Y1' },
      { type: 'TRI_NOT_LO', inputs: ['1A2', '1OEn'], output: '1Y2' },
      { type: 'TRI_NOT_LO', inputs: ['1A3', '1OEn'], output: '1Y3' },
      { type: 'TRI_NOT_LO', inputs: ['1A4', '1OEn'], output: '1Y4' },
      { type: 'TRI_NOT_LO', inputs: ['2A1', '2OEn'], output: '2Y1' },
      { type: 'TRI_NOT_LO', inputs: ['2A2', '2OEn'], output: '2Y2' },
      { type: 'TRI_NOT_LO', inputs: ['2A3', '2OEn'], output: '2Y3' },
      { type: 'TRI_NOT_LO', inputs: ['2A4', '2OEn'], output: '2Y4' },
    ],
  },

  // 74x4306: Dual 4 bit non-inverting buffer, three-state (20-pin)
  '74x4306': {
    name: '74x4306',
    simpleName: 'Dual 4 bit Non-Inverting Buffer (TS)',
    description: 'Dual 4 bit non-inverting buffer with three-state outputs (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.ti.com/lit/gpn/sn74hc541',
    tags: ['buffer', 'non-inverting', 'dual', '4 bit', 'tri-state'],
    guideOverview: 'The 74x4306 is an octal non-inverting three-state buffer split into two 4 bit groups with separate enables. Each enabled output follows its input directly, while disabled outputs disconnect from the bus. It is useful for isolating logic stages, improving fan-out, and steering bus traffic cleanly.',
    guidePinDescriptions: {
      '1OEn': 'Active LOW output enable for buffer group 1. Pull LOW to enable outputs 1Y1 through 1Y4.',
      '1A1': 'Input bit 1 of group 1.',
      '1Y1': 'Output bit 1 of group 1 (three-state, non-inverting).',
      '1A2': 'Input bit 2 of group 1.',
      '1Y2': 'Output bit 2 of group 1 (three-state, non-inverting).',
      '1A3': 'Input bit 3 of group 1.',
      '1Y3': 'Output bit 3 of group 1 (three-state, non-inverting).',
      '1A4': 'Input bit 4 of group 1.',
      '1Y4': 'Output bit 4 of group 1 (three-state, non-inverting).',
      'GND': 'Ground reference for the package.',
      '2OEn': 'Active LOW output enable for buffer group 2.',
      '2A1': 'Input bit 1 of group 2.',
      '2Y1': 'Output bit 1 of group 2 (three-state, non-inverting).',
      '2A2': 'Input bit 2 of group 2.',
      '2Y2': 'Output bit 2 of group 2 (three-state, non-inverting).',
      '2A3': 'Input bit 3 of group 2.',
      '2Y3': 'Output bit 3 of group 2 (three-state, non-inverting).',
      '2A4': 'Input bit 4 of group 2.',
      '2Y4': 'Output bit 4 of group 2 (three-state, non-inverting).',
      'VCC': 'Positive supply for the device.',
    },
    guideSections: [
      {
        title: 'Non-Inverting Bus Buffering',
        paragraphs: [
          'Each output reproduces the same logic state seen at its input. This makes the chip useful when you need more drive strength or need to isolate a source from bus loading without changing polarity.',
        ],
      },
      {
        title: 'Independent Enables',
        paragraphs: [
          'The separate 4 bit enable controls make it easy to treat the package like two nibble-wide bus sections. That can simplify microprocessor or peripheral bus designs.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: '1OEn', type: 'input'  },
      { pin:  2, name: '1A1',  type: 'input'  },
      { pin:  3, name: '1Y1',  type: 'output' },
      { pin:  4, name: '1A2',  type: 'input'  },
      { pin:  5, name: '1Y2',  type: 'output' },
      { pin:  6, name: '1A3',  type: 'input'  },
      { pin:  7, name: '1Y3',  type: 'output' },
      { pin:  8, name: '1A4',  type: 'input'  },
      { pin:  9, name: '1Y4',  type: 'output' },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: '2OEn', type: 'input'  },
      { pin: 12, name: '2A1',  type: 'input'  },
      { pin: 13, name: '2Y1',  type: 'output' },
      { pin: 14, name: '2A2',  type: 'input'  },
      { pin: 15, name: '2Y2',  type: 'output' },
      { pin: 16, name: '2A3',  type: 'input'  },
      { pin: 17, name: '2Y3',  type: 'output' },
      { pin: 18, name: '2A4',  type: 'input'  },
      { pin: 19, name: '2Y4',  type: 'output' },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'TRI_BUFFER_LO', inputs: ['1A1', '1OEn'], output: '1Y1' },
      { type: 'TRI_BUFFER_LO', inputs: ['1A2', '1OEn'], output: '1Y2' },
      { type: 'TRI_BUFFER_LO', inputs: ['1A3', '1OEn'], output: '1Y3' },
      { type: 'TRI_BUFFER_LO', inputs: ['1A4', '1OEn'], output: '1Y4' },
      { type: 'TRI_BUFFER_LO', inputs: ['2A1', '2OEn'], output: '2Y1' },
      { type: 'TRI_BUFFER_LO', inputs: ['2A2', '2OEn'], output: '2Y2' },
      { type: 'TRI_BUFFER_LO', inputs: ['2A3', '2OEn'], output: '2Y3' },
      { type: 'TRI_BUFFER_LO', inputs: ['2A4', '2OEn'], output: '2Y4' },
    ],
  },

  // 74x4316: Quad bilateral analog switch with level translation (16-pin)
  // CD74HC4316 four independent SPST switches; VEE at pin 7 for dual-supply analog swing; active HIGH enables
  '74x4316': {
    name: '74x4316',
    simpleName: 'Quad Bilateral Analog Switch (Level Translation)',
    description: 'Quad bilateral analog switch with level translation (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/cd74hc4316.pdf',
    tags: ['analog', 'switch', 'quad', 'bilateral', 'bidir', 'stub'],
    guideOverview: 'The 74x4316 contains four independent bilateral analog switches with level-translation capability. Each channel passes signals in either direction when its active HIGH enable is asserted. The separate VEE supply pin allows the analog signal range to extend below ground, making the device suitable for mixed-supply systems where TTL/CMOS logic controls analog paths that swing on a dual rail.',
    guidePinDescriptions: {
      '1Y':  'One bilateral terminal of switch channel 1.',
      '1A':  'Other bilateral terminal of switch channel 1.',
      '1E':  'Active HIGH enable for channel 1. HIGH closes the switch; LOW opens it.',
      '2A':  'One bilateral terminal of switch channel 2.',
      '2Y':  'Other bilateral terminal of switch channel 2.',
      '2E':  'Active HIGH enable for channel 2.',
      'VEE': 'Negative analog supply. Allows analog signals to swing below GND when using a dual supply.',
      'GND': 'Ground reference for the device.',
      '3E':  'Active HIGH enable for channel 3.',
      '3Y':  'One bilateral terminal of switch channel 3.',
      '3A':  'Other bilateral terminal of switch channel 3.',
      '4E':  'Active HIGH enable for channel 4.',
      '4Y':  'One bilateral terminal of switch channel 4.',
      '4A':  'Other bilateral terminal of switch channel 4.',
      'NC':  'No internal connection. Leave unconnected.',
      'VCC': 'Positive supply for the switch-control logic.',
    },
    guideSections: [
      {
        title: 'Level Translation',
        paragraphs: [
          'The key difference between the 4316 and the plain 4066 is the addition of a VEE pin. The digital enable inputs are referenced to VCC and GND (TTL/CMOS levels), while the analog switch terminals can swing between VCC and VEE. This lets one supply power the control logic and a separate dual supply govern the analog signal range.',
        ],
      },
      {
        title: 'Bilateral Switching',
        paragraphs: [
          'Each of the four channels acts as a digitally controlled SPST switch. Signals can travel in either direction through the closed switch. All four channels are independent and each has its own enable pin.',
        ],
      },
      {
        title: 'Common Uses',
        list: [
          'Routing analog sensor or audio signals under digital control.',
          'Mixed-supply systems where logic runs at 5 V but analog swings ±5 V.',
          'Pin-compatible upgrade path from the 4066 when a dual analog rail is needed.',
        ],
        note: '74Sim models the switching role of this part. Analog on-resistance and dual-supply signal swing are not simulated in detail.',
      },
    ],
    pinout: [
      { pin:  1, name: '1Y',  type: 'bidir'  },
      { pin:  2, name: '1A',  type: 'bidir'  },
      { pin:  3, name: '1E',  type: 'input'  },
      { pin:  4, name: '2A',  type: 'bidir'  },
      { pin:  5, name: '2Y',  type: 'bidir'  },
      { pin:  6, name: '2E',  type: 'input'  },
      { pin:  7, name: 'VEE', type: 'power'  },
      { pin:  8, name: 'GND', type: 'power'  },
      { pin:  9, name: '3E',  type: 'input'  },
      { pin: 10, name: '3Y',  type: 'bidir'  },
      { pin: 11, name: '3A',  type: 'bidir'  },
      { pin: 12, name: '4E',  type: 'input'  },
      { pin: 13, name: '4Y',  type: 'bidir'  },
      { pin: 14, name: '4A',  type: 'bidir'  },
      { pin: 15, name: 'NC',  type: 'nc'     },
      { pin: 16, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['1E','2E','3E','4E'], outputs: [] },
    ],
  },

  // 74x4351: 8-channel analog mux/demux with latch (20-pin) analog, stubbed
  '74x4351': {
    name: '74x4351',
    simpleName: '8-Ch Analog Mux with Latch',
    description: '8-channel analog multiplexer/demultiplexer with latch (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/cd74hc4351.pdf',
    tags: ['analog', 'mux', '8-channel', 'latch', 'stub'],
    guideOverview: 'The 74x4351 is an 8-channel analog multiplexer/demultiplexer with address latching. Like a 4051, it selects one of eight channels onto a common path, but the latch lets the address be captured and held so the select lines can change without immediately changing the analog path. This is useful when analog routing must be synchronized or when noisy digital address lines should not directly disturb the switch selection.',
    guidePinDescriptions: {
      'Y0': 'Analog channel 0.',
      'Y1': 'Analog channel 1.',
      'Y2': 'Analog channel 2.',
      'Y3': 'Analog channel 3.',
      'Z': 'Common analog node connected to the selected Y channel.',
      'Zn': 'Complementary or associated output node as named in this latched-switch family.',
      'INH': 'Inhibit control. Use it to disconnect the signal path when switching should be disabled.',
      'LE': 'Latch-enable control for the address inputs.',
      'C': 'Most significant select input bit.',
      'GND': 'Ground reference for the chip.',
      'B': 'Middle select input bit.',
      'A': 'Least significant select input bit.',
      'Y4': 'Analog channel 4.',
      'Y5': 'Analog channel 5.',
      'Y6': 'Analog channel 6.',
      'Y7': 'Analog channel 7.',
      'NC': 'No internal connection. Leave unconnected.',
      'NC2': 'No internal connection. Leave unconnected.',
      'VEE': 'Negative analog supply or lower analog rail reference.',
      'VCC': 'Positive supply for the analog-switch control logic.',
    },
    guideSections: [
      {
        title: 'Latched Address Selection',
        paragraphs: [
          'The address bits A, B, and C select one of eight channels, but LE lets that selection be stored internally. That means the chosen channel can remain fixed even if the controlling logic changes afterward.',
        ],
      },
      {
        title: 'Why A Latch Helps',
        paragraphs: [
          'In mixed-signal systems, keeping digital address changes away from the analog selection node can reduce switching disturbances. The latch makes that easier than with a plain 4051-style part.',
        ],
        note: 'This entry is documented as a stub rather than a detailed analog simulator model.',
      },
    ],
    pinout: [
      { pin:  1, name: 'Y0',   type: 'bidir'  },
      { pin:  2, name: 'Y1',   type: 'bidir'  },
      { pin:  3, name: 'Y2',   type: 'bidir'  },
      { pin:  4, name: 'Y3',   type: 'bidir'  },
      { pin:  5, name: 'Z',    type: 'bidir'  },
      { pin:  6, name: 'Zn',   type: 'output' },
      { pin:  7, name: 'INH',  type: 'input'  },
      { pin:  8, name: 'LE',   type: 'input'  },
      { pin:  9, name: 'C',    type: 'input'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'B',    type: 'input'  },
      { pin: 12, name: 'A',    type: 'input'  },
      { pin: 13, name: 'Y4',   type: 'bidir'  },
      { pin: 14, name: 'Y5',   type: 'bidir'  },
      { pin: 15, name: 'Y6',   type: 'bidir'  },
      { pin: 16, name: 'Y7',   type: 'bidir'  },
      { pin: 17, name: 'NC',   type: 'nc'     },
      { pin: 18, name: 'NC2',  type: 'nc'     },
      { pin: 19, name: 'VEE',  type: 'power'  },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['A','B','C','INH','LE'], outputs: [] },
    ],
  },

  // 74x4352: Dual 4-channel analog mux/demux with latch (20-pin) analog, stubbed
  '74x4352': {
    name: '74x4352',
    simpleName: 'Dual 4-Ch Analog Mux with Latch',
    description: 'Dual 4-channel analog multiplexer/demultiplexer with latch (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/cd74hc4352.pdf',
    tags: ['analog', 'mux', '4-channel', 'dual', 'latch', 'stub'],
    guideOverview: 'The 74x4352 is a dual 4-channel analog multiplexer/demultiplexer with latched address control. It behaves like a pair of 4052-style analog mux sections, but the address inputs can be captured and held internally. That is useful when two related analog paths must switch together while the digital controller is free to move on.',
    guidePinDescriptions: {
      '1Y0': 'Channel 0 of section 1.',
      '1Y1': 'Channel 1 of section 1.',
      '1Z': 'Common analog node for section 1.',
      '1Zn': 'Complementary or associated node for section 1 as named in this family.',
      'INH': 'Inhibit control shared by the device. Use it to disable switching.',
      'LE': 'Latch-enable control for the shared address inputs.',
      'B': 'Most significant shared select input bit.',
      'A': 'Least significant shared select input bit.',
      'VEE': 'Negative analog supply or lower analog rail reference.',
      'GND': 'Ground reference for the package.',
      '1Y2': 'Channel 2 of section 1.',
      '1Y3': 'Channel 3 of section 1.',
      '2Y0': 'Channel 0 of section 2.',
      '2Y1': 'Channel 1 of section 2.',
      '2Z': 'Common analog node for section 2.',
      '2Zn': 'Complementary or associated node for section 2 as named in this family.',
      '2Y2': 'Channel 2 of section 2.',
      '2Y3': 'Channel 3 of section 2.',
      'NC': 'No internal connection. Leave unconnected.',
      'VCC': 'Positive supply for the control circuitry.',
    },
    guideSections: [
      {
        title: 'Two Mux Sections, One Latched Address',
        paragraphs: [
          'Both sections share the same A and B address bits, so they switch corresponding channels together. LE lets that address be stored, which is useful when the switch state should stay stable while control logic changes elsewhere.',
        ],
      },
      {
        title: 'Analog Pair Routing',
        paragraphs: [
          'A part like this is handy for stereo audio, paired sensor lines, or other two-channel analog paths. The latch feature helps keep digital switching activity separate from the settled analog route.',
        ],
        note: 'This device is documented in the simulator as a stub rather than a detailed analog path model.',
      },
    ],
    pinout: [
      { pin:  1, name: '1Y0',  type: 'bidir'  },
      { pin:  2, name: '1Y1',  type: 'bidir'  },
      { pin:  3, name: '1Z',   type: 'bidir'  },
      { pin:  4, name: '1Zn',  type: 'output' },
      { pin:  5, name: 'INH',  type: 'input'  },
      { pin:  6, name: 'LE',   type: 'input'  },
      { pin:  7, name: 'B',    type: 'input'  },
      { pin:  8, name: 'A',    type: 'input'  },
      { pin:  9, name: 'VEE',  type: 'power'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: '1Y2',  type: 'bidir'  },
      { pin: 12, name: '1Y3',  type: 'bidir'  },
      { pin: 13, name: '2Y0',  type: 'bidir'  },
      { pin: 14, name: '2Y1',  type: 'bidir'  },
      { pin: 15, name: '2Z',   type: 'bidir'  },
      { pin: 16, name: '2Zn',  type: 'output' },
      { pin: 17, name: '2Y2',  type: 'bidir'  },
      { pin: 18, name: '2Y3',  type: 'bidir'  },
      { pin: 19, name: 'NC',   type: 'nc'     },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['A','B','INH','LE'], outputs: [] },
    ],
  },

  // 74x4353: Triple 2-channel analog mux/demux with latch (20-pin) analog, stubbed
  '74x4353': {
    name: '74x4353',
    simpleName: 'Triple 2-Ch Analog Mux with Latch',
    description: 'Triple 2-channel analog multiplexer/demultiplexer with latch (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: '',
    tags: ['analog', 'mux', '2-channel', 'triple', 'latch', 'stub'],
    pinout: [
      { pin:  1, name: '1Y0',  type: 'bidir'  },
      { pin:  2, name: '1Z',   type: 'bidir'  },
      { pin:  3, name: '1Zn',  type: 'output' },
      { pin:  4, name: '1Y1',  type: 'bidir'  },
      { pin:  5, name: '2Y0',  type: 'bidir'  },
      { pin:  6, name: '2Z',   type: 'bidir'  },
      { pin:  7, name: 'INH',  type: 'input'  },
      { pin:  8, name: 'LE',   type: 'input'  },
      { pin:  9, name: 'A',    type: 'input'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'VEE',  type: 'power'  },
      { pin: 12, name: '2Zn',  type: 'output' },
      { pin: 13, name: '2Y1',  type: 'bidir'  },
      { pin: 14, name: '3Y0',  type: 'bidir'  },
      { pin: 15, name: '3Z',   type: 'bidir'  },
      { pin: 16, name: '3Zn',  type: 'output' },
      { pin: 17, name: '3Y1',  type: 'bidir'  },
      { pin: 18, name: 'NC',   type: 'nc'     },
      { pin: 19, name: 'NC2',  type: 'nc'     },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['A','INH','LE'], outputs: [] },
    ],
  },

  // 74x4374: 8 bit dual-rank synchronizer (20-pin) complex, stubbed
  '74x4374': {
    name: '74x4374',
    simpleName: '8 bit Dual-Rank Synchronizer',
    description: '8 bit dual-rank synchronizer with three-state outputs (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: '',
    tags: ['synchronizer', '8 bit', 'dual-rank', 'tri-state', 'stub'],
    pinout: [
      { pin:  1, name: 'OEn',  type: 'input'  },
      { pin:  2, name: 'D1',   type: 'input'  },
      { pin:  3, name: 'D2',   type: 'input'  },
      { pin:  4, name: 'D3',   type: 'input'  },
      { pin:  5, name: 'D4',   type: 'input'  },
      { pin:  6, name: 'D5',   type: 'input'  },
      { pin:  7, name: 'D6',   type: 'input'  },
      { pin:  8, name: 'D7',   type: 'input'  },
      { pin:  9, name: 'D8',   type: 'input'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'CLK',  type: 'input'  },
      { pin: 12, name: 'Q8',   type: 'output' },
      { pin: 13, name: 'Q7',   type: 'output' },
      { pin: 14, name: 'Q6',   type: 'output' },
      { pin: 15, name: 'Q5',   type: 'output' },
      { pin: 16, name: 'Q4',   type: 'output' },
      { pin: 17, name: 'Q3',   type: 'output' },
      { pin: 18, name: 'Q2',   type: 'output' },
      { pin: 19, name: 'Q1',   type: 'output' },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn','CLK','D1','D2','D3','D4','D5','D6','D7','D8'], outputs: [] },
    ],
  },

  // 74x4510: BCD decade up/down counter (16-pin)
  '74x4510': {
    name: '74x4510',
    simpleName: 'BCD Decade Up/Down Counter',
    description: 'Presettable synchronous BCD decade up/down counter (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    datasheet: 'https://www.ti.com/lit/gpn/cd4510b',
    tags: ['counter', 'BCD', 'decade', 'up-down', 'presettable'],
    guideOverview: 'The 74x4510 is a presettable synchronous BCD up/down counter. It can count upward or downward through decimal states, load a starting value, and cascade with other counters through its carry connections. This makes it useful for decimal timers, score counters, frequency division, and any project that needs a real decimal sequence rather than a straight binary count.',
    guidePinDescriptions: {
      'PE': 'Preset or parallel-load enable control used to load P0 through P3 into the counter.',
      'Q1': 'Counter output bit 1.',
      'Q0': 'Counter output bit 0, the least significant BCD bit.',
      'CI': 'Carry-in or cascade input used when chaining counters.',
      'UD': 'Up/down direction control.',
      'Q2': 'Counter output bit 2.',
      'Q3': 'Counter output bit 3, the most significant BCD bit.',
      'GND': 'Ground reference for the package.',
      'P3': 'Preset input bit 3.',
      'P2': 'Preset input bit 2.',
      'MR': 'Master reset. Assert it to return the counter to zero.',
      'CP': 'Clock input for synchronous counting.',
      'COn': 'Active LOW carry output for cascading to the next stage.',
      'P1': 'Preset input bit 1.',
      'P0': 'Preset input bit 0.',
      'VCC': 'Positive supply for the counter.',
    },
    guideSections: [
      {
        title: 'Decimal Up/Down Counting',
        paragraphs: [
          'Unlike a pure binary counter, a BCD decade counter cycles only through decimal states 0 to 9. The UD input chooses whether the sequence moves upward or downward.',
        ],
      },
      {
        title: 'Preset and Cascade',
        paragraphs: [
          'Preset inputs let the count start from a chosen value instead of zero. Carry-in and carry-out connections let multiple counters be chained into multi-digit decimal systems.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'PE',   type: 'input'  },
      { pin:  2, name: 'Q1',   type: 'output' },
      { pin:  3, name: 'Q0',   type: 'output' },
      { pin:  4, name: 'CI',   type: 'input'  },
      { pin:  5, name: 'UD',   type: 'input'  },
      { pin:  6, name: 'Q2',   type: 'output' },
      { pin:  7, name: 'Q3',   type: 'output' },
      { pin:  8, name: 'GND',  type: 'power'  },
      { pin:  9, name: 'P3',   type: 'input'  },
      { pin: 10, name: 'P2',   type: 'input'  },
      { pin: 11, name: 'MR',   type: 'input'  },
      { pin: 12, name: 'CP',   type: 'input'  },
      { pin: 13, name: 'COn',  type: 'output' },
      { pin: 14, name: 'P1',   type: 'input'  },
      { pin: 15, name: 'P0',   type: 'input'  },
      { pin: 16, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'COUNTER_BCD_UPDOWN_CD', inputs: ['CP','UD','PE','CI','MR','P0','P1','P2','P3'], outputs: ['Q0','Q1','Q2','Q3','COn'] },
    ],
  },

  // 74x4511: BCD to 7-segment latch/decoder/driver (16-pin)
  '74x4511': {
    name: '74x4511',
    simpleName: 'BCD to 7-Segment Decoder',
    description: 'BCD to 7-segment latch/decoder/driver (common cathode) (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/cd74hc4511.pdf',
    tags: ['decoder', 'BCD', '7-segment', 'latch', 'driver'],
    guideOverview: 'The 74x4511 converts a 4 bit BCD input into the seven segment-drive signals needed for a common-cathode numeric display. It also includes latch and display-control functions, so a displayed digit can be held steady even if the input code changes. This is one of the simplest ways to drive a single decimal digit from logic or a microcontroller.',
    guidePinDescriptions: {
      'B': 'BCD input bit B.',
      'C': 'BCD input bit C.',
      'LTn': 'Active LOW lamp-test input. Pull LOW to force the display segments on for test purposes.',
      'BIn': 'Blanking input control used to suppress the display output when required.',
      'LE': 'Latch enable. Use it to hold the displayed digit even if the input code changes.',
      'D': 'Most significant BCD input bit.',
      'A': 'Least significant BCD input bit.',
      'GND': 'Ground reference for the decoder/driver.',
      'e': 'Segment e output.',
      'd': 'Segment d output.',
      'c': 'Segment c output.',
      'b': 'Segment b output.',
      'a': 'Segment a output.',
      'g': 'Segment g output.',
      'f': 'Segment f output.',
      'VCC': 'Positive supply for the chip.',
    },
    guideSections: [
      {
        title: 'BCD To 7-Segment Decoding',
        paragraphs: [
          'A BCD-to-7-segment decoder turns the binary-coded decimal values 0 through 9 into the correct pattern of segments a through g. That saves a lot of manual logic when driving numeric displays.',
        ],
      },
      {
        title: 'Latch and Display Controls',
        paragraphs: [
          'The latch lets you freeze one digit on the display, while blanking and lamp test make it easier to control and debug the display output. Those extras are why the 4511 is more convenient than a plain decoder.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'B',    type: 'input'  },
      { pin:  2, name: 'C',    type: 'input'  },
      { pin:  3, name: 'LTn',  type: 'input'  },
      { pin:  4, name: 'BIn',  type: 'input'  },
      { pin:  5, name: 'LE',   type: 'input'  },
      { pin:  6, name: 'D',    type: 'input'  },
      { pin:  7, name: 'A',    type: 'input'  },
      { pin:  8, name: 'GND',  type: 'power'  },
      { pin:  9, name: 'e',    type: 'output' },
      { pin: 10, name: 'd',    type: 'output' },
      { pin: 11, name: 'c',    type: 'output' },
      { pin: 12, name: 'b',    type: 'output' },
      { pin: 13, name: 'a',    type: 'output' },
      { pin: 14, name: 'g',    type: 'output' },
      { pin: 15, name: 'f',    type: 'output' },
      { pin: 16, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'BCD_7SEG_4511', inputs: ['A','B','C','D','LE','BIn','LTn'], outputs: ['a','b','c','d','e','f','g'] },
    ],
  },

  // 74x4514: 4-to-16 decoder with input latches, active HIGH outputs (24-pin)
  '74x4514': {
    name: '74x4514',
    simpleName: '4-to-16 Decoder (Active HIGH, Latched)',
    description: '4-to-16 line decoder/demultiplexer with input latches, active HIGH outputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: 'https://www.ti.com/lit/ds/symlink/cd74hc4514.pdf',
    tags: ['decoder', '4-to-16', 'latch', 'active high'],
    guideOverview: 'The 74x4514 is a 4-to-16 decoder with latched inputs and active HIGH outputs. A 4 bit input selects exactly one of sixteen outputs, and the latch can hold that selection even after the input lines change. It is useful for one-hot control, address decoding, and selecting one of many destinations from a small binary code.',
    guidePinDescriptions: {
      'LE': 'Latch enable for the 4 bit address input.',
      'D': 'Most significant address input bit.',
      'C': 'Address input bit C.',
      'B': 'Address input bit B.',
      'A': 'Least significant address input bit.',
      'Y7': 'Decoded output 7, active HIGH when address 7 is selected.',
      'Y6': 'Decoded output 6.',
      'Y5': 'Decoded output 5.',
      'Y4': 'Decoded output 4.',
      'Y3': 'Decoded output 3.',
      'Y2': 'Decoded output 2.',
      'GND': 'Ground reference for the package.',
      'Y1': 'Decoded output 1.',
      'Y0': 'Decoded output 0.',
      'Y15': 'Decoded output 15.',
      'Y14': 'Decoded output 14.',
      'Y13': 'Decoded output 13.',
      'Y12': 'Decoded output 12.',
      'Y11': 'Decoded output 11.',
      'Y10': 'Decoded output 10.',
      'Y9': 'Decoded output 9.',
      'Y8': 'Decoded output 8.',
      'ENn': 'Active LOW enable. Pull LOW to allow decoding.',
      'VCC': 'Positive supply for the decoder.',
    },
    guideSections: [
      {
        title: 'One-Of-Sixteen Decoding',
        paragraphs: [
          'The 4 bit input code is expanded into a one-hot output pattern. Only one of the sixteen outputs is asserted at a time when the device is enabled.',
        ],
      },
      {
        title: 'Latched Addressing',
        paragraphs: [
          'The latch lets the selected output remain stable even if the input address bus changes afterward. That can be useful in systems where the address bus is shared or only valid briefly.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'LE',   type: 'input'  },
      { pin:  2, name: 'D',    type: 'input'  },
      { pin:  3, name: 'C',    type: 'input'  },
      { pin:  4, name: 'B',    type: 'input'  },
      { pin:  5, name: 'A',    type: 'input'  },
      { pin:  6, name: 'Y7',   type: 'output' },
      { pin:  7, name: 'Y6',   type: 'output' },
      { pin:  8, name: 'Y5',   type: 'output' },
      { pin:  9, name: 'Y4',   type: 'output' },
      { pin: 10, name: 'Y3',   type: 'output' },
      { pin: 11, name: 'Y2',   type: 'output' },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'Y1',   type: 'output' },
      { pin: 14, name: 'Y0',   type: 'output' },
      { pin: 15, name: 'Y15',  type: 'output' },
      { pin: 16, name: 'Y14',  type: 'output' },
      { pin: 17, name: 'Y13',  type: 'output' },
      { pin: 18, name: 'Y12',  type: 'output' },
      { pin: 19, name: 'Y11',  type: 'output' },
      { pin: 20, name: 'Y10',  type: 'output' },
      { pin: 21, name: 'Y9',   type: 'output' },
      { pin: 22, name: 'Y8',   type: 'output' },
      { pin: 23, name: 'ENn',  type: 'input'  },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'DEC_4TO16_LATCH_HI', inputs: ['A','B','C','D','LE','ENn'], outputs: ['Y0','Y1','Y2','Y3','Y4','Y5','Y6','Y7','Y8','Y9','Y10','Y11','Y12','Y13','Y14','Y15'] },
    ],
  },

  // 74x4515: 4-to-16 decoder with input latches, active LOW outputs (24-pin)
  '74x4515': {
    name: '74x4515',
    simpleName: '4-to-16 Decoder (Active LOW, Latched)',
    description: '4-to-16 line decoder/demultiplexer with input latches, active LOW outputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: 'https://www.ti.com/lit/ds/symlink/cd74hc4515.pdf',
    tags: ['decoder', '4-to-16', 'latch', 'active low'],
    guideOverview: 'The 74x4515 is the active LOW companion to the 4514. It decodes a 4 bit input into one of sixteen outputs, but the selected output goes LOW instead of HIGH. This is useful in systems that use active LOW enables, chip-selects, or bus-control signals.',
    guidePinDescriptions: {
      'LE': 'Latch enable for the address inputs.',
      'D': 'Most significant address input bit.',
      'C': 'Address input bit C.',
      'B': 'Address input bit B.',
      'A': 'Least significant address input bit.',
      'Y7n': 'Decoded output 7, active LOW when address 7 is selected.',
      'Y6n': 'Decoded output 6, active LOW.',
      'Y5n': 'Decoded output 5, active LOW.',
      'Y4n': 'Decoded output 4, active LOW.',
      'Y3n': 'Decoded output 3, active LOW.',
      'Y2n': 'Decoded output 2, active LOW.',
      'GND': 'Ground reference for the chip.',
      'Y1n': 'Decoded output 1, active LOW.',
      'Y0n': 'Decoded output 0, active LOW.',
      'Y15n': 'Decoded output 15, active LOW.',
      'Y14n': 'Decoded output 14, active LOW.',
      'Y13n': 'Decoded output 13, active LOW.',
      'Y12n': 'Decoded output 12, active LOW.',
      'Y11n': 'Decoded output 11, active LOW.',
      'Y10n': 'Decoded output 10, active LOW.',
      'Y9n': 'Decoded output 9, active LOW.',
      'Y8n': 'Decoded output 8, active LOW.',
      'ENn': 'Active LOW enable input.',
      'VCC': 'Positive supply for the decoder.',
    },
    guideSections: [
      {
        title: 'Active LOW Decoding',
        paragraphs: [
          'The 4515 produces the same one-of-sixteen selection pattern as the 4514, but with active LOW outputs. That is often more convenient for chip-select and bus-enable signals that are already LOW-true.',
        ],
      },
      {
        title: 'Latched Selection',
        paragraphs: [
          'As with the 4514, the address can be latched internally so the selected output remains stable after the input bus changes. This is useful in multiplexed and shared-bus designs.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'LE',    type: 'input'  },
      { pin:  2, name: 'D',     type: 'input'  },
      { pin:  3, name: 'C',     type: 'input'  },
      { pin:  4, name: 'B',     type: 'input'  },
      { pin:  5, name: 'A',     type: 'input'  },
      { pin:  6, name: 'Y7n',   type: 'output' },
      { pin:  7, name: 'Y6n',   type: 'output' },
      { pin:  8, name: 'Y5n',   type: 'output' },
      { pin:  9, name: 'Y4n',   type: 'output' },
      { pin: 10, name: 'Y3n',   type: 'output' },
      { pin: 11, name: 'Y2n',   type: 'output' },
      { pin: 12, name: 'GND',   type: 'power'  },
      { pin: 13, name: 'Y1n',   type: 'output' },
      { pin: 14, name: 'Y0n',   type: 'output' },
      { pin: 15, name: 'Y15n',  type: 'output' },
      { pin: 16, name: 'Y14n',  type: 'output' },
      { pin: 17, name: 'Y13n',  type: 'output' },
      { pin: 18, name: 'Y12n',  type: 'output' },
      { pin: 19, name: 'Y11n',  type: 'output' },
      { pin: 20, name: 'Y10n',  type: 'output' },
      { pin: 21, name: 'Y9n',   type: 'output' },
      { pin: 22, name: 'Y8n',   type: 'output' },
      { pin: 23, name: 'ENn',   type: 'input'  },
      { pin: 24, name: 'VCC',   type: 'power'  },
    ],
    gates: [
      { type: 'DEC_4TO16_LATCH_LO', inputs: ['A','B','C','D','LE','ENn'], outputs: ['Y0n','Y1n','Y2n','Y3n','Y4n','Y5n','Y6n','Y7n','Y8n','Y9n','Y10n','Y11n','Y12n','Y13n','Y14n','Y15n'] },
    ],
  },

  // 74x4516: 4 bit binary up/down counter (16-pin)
  '74x4516': {
    name: '74x4516',
    simpleName: '4 bit Binary Up/Down Counter',
    description: 'Presettable synchronous 4 bit binary up/down counter (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    datasheet: 'https://www.ti.com/lit/gpn/cd4516b',
    tags: ['counter', 'binary', '4 bit', 'up-down', 'presettable'],
    guideOverview: 'The 74x4516 is a presettable synchronous 4 bit binary up/down counter. It can count upward or downward, load a starting value, and cascade into larger counters through its carry connections. This is a versatile part for programmable timing, binary state sequencing, and divide-by-N designs.',
    guidePinDescriptions: {
      'PE': 'Preset or parallel-load enable control used to load P0 through P3 into the counter.',
      'Q1': 'Counter output bit 1.',
      'Q0': 'Counter output bit 0, the least significant bit.',
      'CI': 'Carry-in or cascade input used when chaining counters.',
      'UD': 'Up/down direction control.',
      'Q2': 'Counter output bit 2.',
      'Q3': 'Counter output bit 3, the most significant output bit.',
      'GND': 'Ground reference for the device.',
      'P3': 'Preset input bit 3.',
      'P2': 'Preset input bit 2.',
      'MR': 'Master reset. Assert it to clear the count.',
      'CP': 'Clock input for synchronous counting.',
      'COn': 'Active LOW carry output for cascade operation.',
      'P1': 'Preset input bit 1.',
      'P0': 'Preset input bit 0.',
      'VCC': 'Positive supply for the counter.',
    },
    guideSections: [
      {
        title: 'Binary Up/Down Counting',
        paragraphs: [
          'Unlike the 4510, this part counts through all 16 binary states from 0000 to 1111. The UD input selects whether the count moves upward or downward.',
        ],
      },
      {
        title: 'Preset and Cascading',
        paragraphs: [
          'Preset inputs allow the counter to start from an arbitrary binary value, and the carry pins support chaining to build wider counters. That makes the 4516 a flexible general-purpose synchronous counter.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'PE',   type: 'input'  },
      { pin:  2, name: 'Q1',   type: 'output' },
      { pin:  3, name: 'Q0',   type: 'output' },
      { pin:  4, name: 'CI',   type: 'input'  },
      { pin:  5, name: 'UD',   type: 'input'  },
      { pin:  6, name: 'Q2',   type: 'output' },
      { pin:  7, name: 'Q3',   type: 'output' },
      { pin:  8, name: 'GND',  type: 'power'  },
      { pin:  9, name: 'P3',   type: 'input'  },
      { pin: 10, name: 'P2',   type: 'input'  },
      { pin: 11, name: 'MR',   type: 'input'  },
      { pin: 12, name: 'CP',   type: 'input'  },
      { pin: 13, name: 'COn',  type: 'output' },
      { pin: 14, name: 'P1',   type: 'input'  },
      { pin: 15, name: 'P0',   type: 'input'  },
      { pin: 16, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'COUNTER_BIN_UPDOWN_CD', inputs: ['CP','UD','PE','CI','MR','P0','P1','P2','P3'], outputs: ['Q0','Q1','Q2','Q3','COn'] },
    ],
  },

  // 74x4518: Dual synchronous BCD decade counter (16-pin)
  '74x4518': {
    name: '74x4518',
    simpleName: 'Dual Synchronous BCD Counter',
    description: 'Dual synchronous 4 bit BCD decade counter (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/cd74hc4518.pdf',
    tags: ['counter', 'BCD', 'decade', 'dual', 'synchronous'],
    guideOverview: 'The 74x4518 contains two independent synchronous BCD decade counters in one package. Each section counts from 0 to 9 and then wraps, which makes the chip useful for decimal event counting, timers, and multi-digit counters. Having two sections in one IC is convenient when building simple clocks or score displays.',
    guidePinDescriptions: {
      '1CP': 'Clock input for counter section 1.',
      '1EN': 'Enable control for counter section 1.',
      '1Q0': 'Least significant BCD output bit of section 1.',
      '1Q1': 'BCD output bit 1 of section 1.',
      '1Q2': 'BCD output bit 2 of section 1.',
      '1Q3': 'Most significant BCD output bit of section 1.',
      '1MR': 'Master reset for counter section 1.',
      'GND': 'Ground reference for the package.',
      '2MR': 'Master reset for counter section 2.',
      '2Q3': 'Most significant BCD output bit of section 2.',
      '2Q2': 'BCD output bit 2 of section 2.',
      '2Q1': 'BCD output bit 1 of section 2.',
      '2Q0': 'Least significant BCD output bit of section 2.',
      '2EN': 'Enable control for counter section 2.',
      '2CP': 'Clock input for counter section 2.',
      'VCC': 'Positive supply for the device.',
    },
    guideSections: [
      {
        title: 'Two Decade Counters',
        paragraphs: [
          'Each section counts only the decimal values 0 through 9. Because the two counters are independent, one package can handle two digits or two unrelated BCD counting jobs.',
        ],
      },
      {
        title: 'Synchronous Operation',
        paragraphs: [
          'Because the counters are synchronous, the output bits change together in a more controlled way than in a ripple design. That is helpful when the outputs feed other logic directly.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: '1CP',  type: 'input'  },
      { pin:  2, name: '1EN',  type: 'input'  },
      { pin:  3, name: '1Q0',  type: 'output' },
      { pin:  4, name: '1Q1',  type: 'output' },
      { pin:  5, name: '1Q2',  type: 'output' },
      { pin:  6, name: '1Q3',  type: 'output' },
      { pin:  7, name: '1MR',  type: 'input'  },
      { pin:  8, name: 'GND',  type: 'power'  },
      { pin:  9, name: '2MR',  type: 'input'  },
      { pin: 10, name: '2Q3',  type: 'output' },
      { pin: 11, name: '2Q2',  type: 'output' },
      { pin: 12, name: '2Q1',  type: 'output' },
      { pin: 13, name: '2Q0',  type: 'output' },
      { pin: 14, name: '2EN',  type: 'input'  },
      { pin: 15, name: '2CP',  type: 'input'  },
      { pin: 16, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'COUNTER_GATED_DECADE', inputs: ['1CP','1EN','1MR'], outputs: ['1Q0','1Q1','1Q2','1Q3'] },
      { type: 'COUNTER_GATED_DECADE', inputs: ['2CP','2EN','2MR'], outputs: ['2Q0','2Q1','2Q2','2Q3'] },
    ],
  },

  // 74x4520: Dual synchronous binary counter (16-pin)
  '74x4520': {
    name: '74x4520',
    simpleName: 'Dual Synchronous Binary Counter',
    description: 'Dual synchronous 4 bit binary counter (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/cd74hc4520.pdf',
    tags: ['counter', 'binary', '4 bit', 'dual', 'synchronous'],
    guideOverview: 'The 74x4520 contains two independent synchronous 4 bit binary counters. Each section counts from 0 to 15 and then wraps, making it useful for compact digital timing and state generation. It is the binary counterpart to the 4518, trading decimal counting for a full 4 bit range.',
    guidePinDescriptions: {
      '1CP': 'Clock input for counter section 1.',
      '1EN': 'Enable control for counter section 1.',
      '1Q0': 'Least significant binary output bit of section 1.',
      '1Q1': 'Binary output bit 1 of section 1.',
      '1Q2': 'Binary output bit 2 of section 1.',
      '1Q3': 'Most significant binary output bit of section 1.',
      '1MR': 'Master reset for counter section 1.',
      'GND': 'Ground reference for the device.',
      '2MR': 'Master reset for counter section 2.',
      '2Q3': 'Most significant binary output bit of section 2.',
      '2Q2': 'Binary output bit 2 of section 2.',
      '2Q1': 'Binary output bit 1 of section 2.',
      '2Q0': 'Least significant binary output bit of section 2.',
      '2EN': 'Enable control for counter section 2.',
      '2CP': 'Clock input for counter section 2.',
      'VCC': 'Positive supply for the package.',
    },
    guideSections: [
      {
        title: 'Dual Binary Counting',
        paragraphs: [
          'Each counter section advances through the sixteen 4 bit binary states. That makes the part useful for binary timing, state generation, and dividing a clock by programmable binary stages.',
        ],
      },
      {
        title: 'Why Synchronous Matters',
        paragraphs: [
          'In a synchronous counter, all bits are updated under one clocked action rather than rippling stage-to-stage. This reduces transient decode glitches when the outputs are fed into other logic.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: '1CP',  type: 'input'  },
      { pin:  2, name: '1EN',  type: 'input'  },
      { pin:  3, name: '1Q0',  type: 'output' },
      { pin:  4, name: '1Q1',  type: 'output' },
      { pin:  5, name: '1Q2',  type: 'output' },
      { pin:  6, name: '1Q3',  type: 'output' },
      { pin:  7, name: '1MR',  type: 'input'  },
      { pin:  8, name: 'GND',  type: 'power'  },
      { pin:  9, name: '2MR',  type: 'input'  },
      { pin: 10, name: '2Q3',  type: 'output' },
      { pin: 11, name: '2Q2',  type: 'output' },
      { pin: 12, name: '2Q1',  type: 'output' },
      { pin: 13, name: '2Q0',  type: 'output' },
      { pin: 14, name: '2EN',  type: 'input'  },
      { pin: 15, name: '2CP',  type: 'input'  },
      { pin: 16, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'COUNTER_GATED_BIN', inputs: ['1CP','1EN','1MR'], outputs: ['1Q0','1Q1','1Q2','1Q3'] },
      { type: 'COUNTER_GATED_BIN', inputs: ['2CP','2EN','2MR'], outputs: ['2Q0','2Q1','2Q2','2Q3'] },
    ],
  },

  // 74x4543: BCD to 7-segment LCD driver (16-pin) complex, stubbed
  '74x4543': {
    name: '74x4543',
    simpleName: 'BCD to 7-Segment LCD Driver',
    description: 'BCD to 7-segment latch/decoder/driver for LCDs (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/cd74hc4543.pdf',
    tags: ['decoder', 'BCD', '7-segment', 'LCD', 'latch', 'driver', 'stub'],
    guideOverview: 'The 74x4543 is a BCD-to-7-segment decoder/driver intended for LCD-style displays. It converts a decimal code into segment outputs, but it also includes latch and phase-related features needed for LCD drive schemes rather than simple LED drive. That makes it useful when you want logic-level numeric display control without designing the segment decode table yourself.',
    guidePinDescriptions: {
      'LD': 'Latch/data control input used by the decoder section.',
      'BIn': 'Blanking input used to suppress the display when required.',
      'PH': 'Phase input associated with LCD-style drive operation.',
      'D': 'Most significant BCD input bit.',
      'A': 'Least significant BCD input bit.',
      'B': 'BCD input bit B.',
      'C': 'BCD input bit C.',
      'GND': 'Ground reference for the chip.',
      'f': 'Segment f output.',
      'g': 'Segment g output.',
      'a': 'Segment a output.',
      'b': 'Segment b output.',
      'c': 'Segment c output.',
      'd': 'Segment d output.',
      'e': 'Segment e output.',
      'VCC': 'Positive supply for the device.',
    },
    guideSections: [
      {
        title: 'LCD-Oriented 7-Segment Driving',
        paragraphs: [
          'The 4543 belongs to the same general family as LED-oriented BCD decoders, but its control scheme is adapted for LCD drive requirements. That is why it includes phase-related behavior not found on simpler LED drivers.',
        ],
      },
      {
        title: 'Decoder Plus Control Logic',
        paragraphs: [
          'By combining the numeric decode logic with latch and display-control features, the part reduces the amount of supporting logic needed around an LCD digit. It is documented here as a stub rather than a full LCD waveform simulator.',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'LD',   type: 'input'  },
      { pin:  2, name: 'BIn',  type: 'input'  },
      { pin:  3, name: 'PH',   type: 'input'  },
      { pin:  4, name: 'D',    type: 'input'  },
      { pin:  5, name: 'A',    type: 'input'  },
      { pin:  6, name: 'B',    type: 'input'  },
      { pin:  7, name: 'C',    type: 'input'  },
      { pin:  8, name: 'GND',  type: 'power'  },
      { pin:  9, name: 'f',    type: 'output' },
      { pin: 10, name: 'g',    type: 'output' },
      { pin: 11, name: 'a',    type: 'output' },
      { pin: 12, name: 'b',    type: 'output' },
      { pin: 13, name: 'c',    type: 'output' },
      { pin: 14, name: 'd',    type: 'output' },
      { pin: 15, name: 'e',    type: 'output' },
      { pin: 16, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['LD','BIn','PH','A','B','C','D'], outputs: [] },
    ],
  },

  // 74x4560: 4 bit BCD adder (16-pin) complex, stubbed
  '74x4560': {
    name: '74x4560',
    simpleName: '4 bit BCD Adder',
    description: '4 bit BCD adder (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    datasheet: '',
    tags: ['adder', 'BCD', '4 bit', 'stub'],
    pinout: [
      { pin:  1, name: 'B2',   type: 'input'  },
      { pin:  2, name: 'A2',   type: 'input'  },
      { pin:  3, name: 'A1',   type: 'input'  },
      { pin:  4, name: 'B1',   type: 'input'  },
      { pin:  5, name: 'A0',   type: 'input'  },
      { pin:  6, name: 'B0',   type: 'input'  },
      { pin:  7, name: 'CIN',  type: 'input'  },
      { pin:  8, name: 'GND',  type: 'power'  },
      { pin:  9, name: 'S0',   type: 'output' },
      { pin: 10, name: 'S1',   type: 'output' },
      { pin: 11, name: 'S2',   type: 'output' },
      { pin: 12, name: 'S3',   type: 'output' },
      { pin: 13, name: 'COUT', type: 'output' },
      { pin: 14, name: 'B3',   type: 'input'  },
      { pin: 15, name: 'A3',   type: 'input'  },
      { pin: 16, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['A0','A1','A2','A3','B0','B1','B2','B3','CIN'], outputs: [] },
    ],
  },

};