// Chip definitions block 56
// Chips: 74x3257, 74x3305, 74x3306, 74x3345, 74x3374, 74x3383, 74x3384,
//        74x3386, 74x3573, 74x3574, 74x3584, 74x3807, 74x3827,
//        74x3861, 74x3862

export const CHIPS_BLOCK_56 = {

  // 74x3257: Quad 2 line to 1 line FET multiplexer / demultiplexer (16-pin)
  // Shared S (select) and OEn (active low); 4 channels each with A/B (bidir) and Z (common bidir)
  // Pinout follows 74x157/257 family convention -- mirrors 74x3253 (dual 4:1) structure
  '74x3257': {
    name: '74x3257',
    simpleName: 'Quad 2-to-1 FET Multiplexer / Demultiplexer',
    description: 'Quad 2 line to 1 line FET multiplexer / demultiplexer (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74cbt3257.pdf',
    tags: ['FET', 'mux', 'demux', '2:1', 'quad', 'bidir', 'stub'],
    guideOverview: 'The 74x3257 is a quad 2-to-1 FET switch that can be viewed as either a multiplexer or a demultiplexer. Each channel connects a common Z node to either its A input or its B input, and because the path is a bilateral FET switch, signals can pass in whichever direction the surrounding circuit drives them. This kind of part is useful when you need to steer raw signal lines without adding the fixed direction or logic regeneration of a buffer.',
    guidePinDescriptions: {
      'S': 'Shared select input for all four channels. In the usual truth table, one select state connects each Z pin to its A input and the other state connects each Z pin to its B input.',
      'A1': 'A-side node for channel 1. It is connected to Z1 when the select input chooses the A path and the part is enabled.',
      'B1': 'B-side node for channel 1. It is connected to Z1 when the select input chooses the B path and the part is enabled.',
      'Z1': 'Common node for channel 1. It connects to either A1 or B1 depending on S.',
      'A2': 'A-side node for channel 2.',
      'B2': 'B-side node for channel 2.',
      'Z2': 'Common node for channel 2.',
      'GND': 'Ground reference for the switch control circuitry.',
      'Z3': 'Common node for channel 3.',
      'B3': 'B-side node for channel 3.',
      'A3': 'A-side node for channel 3.',
      'Z4': 'Common node for channel 4.',
      'B4': 'B-side node for channel 4.',
      'A4': 'A-side node for channel 4.',
      'OEn': 'Active LOW global enable. Pull LOW to enable all four switch channels; drive HIGH to isolate every Z pin from its A and B nodes.',
      'VCC': 'Positive supply for the control logic.',
    },
    guideSections: [
      {
        title: 'How the Switch Selects a Path',
        paragraphs: [
          'Each channel is a 2-to-1 signal selector built from FET switches. The shared select input decides whether the common Z node is connected to the A side or the B side for all four channels at once.',
          'Because the connections are bilateral, the same hardware can be used as a multiplexer or a demultiplexer depending on which side of the channel is being driven.',
        ],
        formulas: [
          'OEn = 1 -> all channels open',
          'OEn = 0 and S selects A -> Zx connected to Ax',
          'OEn = 0 and S selects B -> Zx connected to Bx',
        ],
      },
      {
        title: 'Why Use a FET Multiplexer',
        paragraphs: [
          'A FET switch adds very little logic behavior of its own. That makes it useful when you want routing flexibility more than signal restoration, such as steering buses, selecting among data sources, or making temporary links between two parts of a board.',
        ],
        note: 'This simulator entry is a documented stub. It describes the intended switching behavior, but it does not model analog switch resistance or detailed pass transistor effects.',
      },
    ],
    pinout: [
      { pin:  1, name: 'S',    type: 'input'  },
      { pin:  2, name: 'A1',   type: 'bidir'  },
      { pin:  3, name: 'B1',   type: 'bidir'  },
      { pin:  4, name: 'Z1',   type: 'bidir'  },
      { pin:  5, name: 'A2',   type: 'bidir'  },
      { pin:  6, name: 'B2',   type: 'bidir'  },
      { pin:  7, name: 'Z2',   type: 'bidir'  },
      { pin:  8, name: 'GND',  type: 'power'  },
      { pin:  9, name: 'Z3',   type: 'bidir'  },
      { pin: 10, name: 'B3',   type: 'bidir'  },
      { pin: 11, name: 'A3',   type: 'bidir'  },
      { pin: 12, name: 'Z4',   type: 'bidir'  },
      { pin: 13, name: 'B4',   type: 'bidir'  },
      { pin: 14, name: 'A4',   type: 'bidir'  },
      { pin: 15, name: 'OEn',  type: 'input'  },
      { pin: 16, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['S', 'OEn'], outputs: [] },
    ],
  },

  // 74x3305: Dual FET bus switch with extended voltage range, active HIGH per switch OE (8-pin)
  // SN74CBT3305C -- two independent switches each with its own active high OE
  '74x3305': {
    name: '74x3305',
    simpleName: 'Dual FET Bus Switch (Active High OE, Extended Voltage)',
    description: 'Dual FET bus switch, wide voltage range, per-switch active-HIGH OE (8-pin)',
    pins: 8, vcc: 8, gnd: 4,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74cbt3305c.pdf',
    tags: ['FET', 'bus-switch', 'dual', 'bidir', 'stub'],
    guideOverview: 'The 74x3305 contains two independent bilateral FET bus switches. Each channel has its own active HIGH enable, so you can turn the two connections on and off separately. Designers use parts like this when they need very simple, low delay routing between two nodes without forcing a fixed signal direction.',
    guidePinDescriptions: {
      'OE1': 'Enable control (active HIGH) for switch channel 1. Drive HIGH to connect A1 and B1; drive LOW to open the path.',
      'A1': 'One side of switch channel 1.',
      'B1': 'Other side of switch channel 1.',
      'GND': 'Ground reference for the device.',
      'B2': 'Other side of switch channel 2.',
      'A2': 'One side of switch channel 2.',
      'OE2': 'Enable control (active HIGH) for switch channel 2.',
      'VCC': 'Positive supply for the control circuitry.',
    },
    guideSections: [
      {
        title: 'Independent Switching Channels',
        paragraphs: [
          'The two channels are controlled separately, so one path can be connected while the other remains open. That is useful when only some lines of an interface need to be connected at a given time.',
        ],
      },
      {
        title: 'Bilateral Bus Switching',
        paragraphs: [
          'Each channel behaves like an electronically controlled connection, not a logic buffer. Signals can pass either direction through the closed switch as long as they stay within the device limits.',
        ],
        note: 'The simulator documents the control and routing role of this part but does not model analog on resistance in detail.',
      },
    ],
    pinout: [
      { pin: 1, name: 'OE1',  type: 'input'  },
      { pin: 2, name: 'A1',   type: 'bidir'  },
      { pin: 3, name: 'B1',   type: 'bidir'  },
      { pin: 4, name: 'GND',  type: 'power'  },
      { pin: 5, name: 'B2',   type: 'bidir'  },
      { pin: 6, name: 'A2',   type: 'bidir'  },
      { pin: 7, name: 'OE2',  type: 'input'  },
      { pin: 8, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OE1', 'OE2'], outputs: [] },
    ],
  },

  // 74x3306: Dual FET bus switch, single shared active LOW OEn (8-pin)
  // SN74CBT3306 -- both switches share one active low enable; pin 7 unused (NC)
  '74x3306': {
    name: '74x3306',
    simpleName: 'Dual FET Bus Switch (Active Low OE)',
    description: 'Dual FET bus switch with shared active low output enable (8-pin)',
    pins: 8, vcc: 8, gnd: 4,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74cbt3306.pdf',
    tags: ['FET', 'bus-switch', 'dual', 'bidir', 'stub'],
    guideOverview: 'The 74x3306 is a dual bilateral FET bus switch with one shared active LOW enable control. When enabled, both channels behave like low resistance links between their A and B pins; when disabled, both paths open at once. It is a simple way to isolate or reconnect a pair of lines with very little added propagation delay.',
    guidePinDescriptions: {
      'OEn': 'Shared enable control for both switch channels (active LOW). Pull LOW to close both switches; drive HIGH to open both paths.',
      'A1': 'One side of switch channel 1.',
      'B1': 'Other side of switch channel 1.',
      'GND': 'Ground reference for the package.',
      'B2': 'Other side of switch channel 2.',
      'A2': 'One side of switch channel 2.',
      'NC': 'No internal connection. Leave this pin unconnected.',
      'VCC': 'Positive supply for the control circuitry.',
    },
    guideSections: [
      {
        title: 'One Enable for Both Channels',
        paragraphs: [
          'Unlike the 74x3305, this part enables or disables both switch channels together. That makes it useful when two related lines should always connect and disconnect as a pair.',
        ],
      },
      {
        title: 'Why Bus Switches Are Different',
        paragraphs: [
          'A bus switch does not regenerate a logic level the way a gate buffer does. It simply connects two nodes together through a controlled FET path.',
        ],
        note: 'This is represented as a documented stub in the simulator rather than a detailed analog switch model.',
      },
    ],
    pinout: [
      { pin: 1, name: 'OEn',  type: 'input'  },
      { pin: 2, name: 'A1',   type: 'bidir'  },
      { pin: 3, name: 'B1',   type: 'bidir'  },
      { pin: 4, name: 'GND',  type: 'power'  },
      { pin: 5, name: 'B2',   type: 'bidir'  },
      { pin: 6, name: 'A2',   type: 'bidir'  },
      { pin: 7, name: 'NC',   type: 'nc'     },
      { pin: 8, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn'], outputs: [] },
    ],
  },

  // 74x3345: Octal FET bus switch with dual output enable (20-pin)
  // SN74CBT3345 -- both OE1n and OE2n must be low to close all 8 switches
  '74x3345': {
    name: '74x3345',
    simpleName: 'Octal FET Bus Switch (Dual Output Enable)',
    description: 'Octal FET bus switch with dual output enable (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74cbt3345.pdf',
    tags: ['FET', 'bus-switch', 'octal', 'bidir', 'stub'],
    guideOverview: 'The 74x3345 extends the bilateral FET switch idea to eight signal paths. It is not a transceiver with a chosen direction; instead it is eight electronically controlled pass switches that can connect one 8 bit group to another with minimal added delay. Dual enable inputs make it easier to fit the part into shared bus control logic where more than one condition must be true before the bus can connect.',
    guidePinDescriptions: {
      'OE1n': 'One of the active LOW enable controls. In the local definition both enables must be asserted to allow all eight switch paths to conduct.',
      'A1': 'Bit 1 on the A-side bus.',
      'A2': 'Bit 2 on the A-side bus.',
      'A3': 'Bit 3 on the A-side bus.',
      'A4': 'Bit 4 on the A-side bus.',
      'A5': 'Bit 5 on the A-side bus.',
      'A6': 'Bit 6 on the A-side bus.',
      'A7': 'Bit 7 on the A-side bus.',
      'A8': 'Bit 8 on the A-side bus.',
      'GND': 'Ground reference for the device.',
      'B8': 'Bit 8 on the B-side bus.',
      'B7': 'Bit 7 on the B-side bus.',
      'B6': 'Bit 6 on the B-side bus.',
      'B5': 'Bit 5 on the B-side bus.',
      'B4': 'Bit 4 on the B-side bus.',
      'B3': 'Bit 3 on the B-side bus.',
      'B2': 'Bit 2 on the B-side bus.',
      'B1': 'Bit 1 on the B-side bus.',
      'OE2n': 'Second active LOW enable control for the switch array.',
      'VCC': 'Positive supply for the control logic.',
    },
    guideSections: [
      {
        title: 'Eight Bilateral Switches',
        paragraphs: [
          'Each A pin is paired with a corresponding B pin through a controlled FET path. When enabled, the device acts like an 8 bit connection between the two buses rather than a directional logic buffer.',
        ],
      },
      {
        title: 'Why Use Two Enable Inputs',
        paragraphs: [
          'Dual enables let the switch bank participate in more complex control schemes. For example, one enable might come from address decoding while the other comes from a bus ownership signal.',
        ],
        note: 'This simulator entry remains a documented stub and does not model analog resistance or contention effects through the pass switches.',
      },
    ],
    pinout: [
      { pin:  1, name: 'OE1n', type: 'input'  },
      { pin:  2, name: 'A1',   type: 'bidir'  },
      { pin:  3, name: 'A2',   type: 'bidir'  },
      { pin:  4, name: 'A3',   type: 'bidir'  },
      { pin:  5, name: 'A4',   type: 'bidir'  },
      { pin:  6, name: 'A5',   type: 'bidir'  },
      { pin:  7, name: 'A6',   type: 'bidir'  },
      { pin:  8, name: 'A7',   type: 'bidir'  },
      { pin:  9, name: 'A8',   type: 'bidir'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'B8',   type: 'bidir'  },
      { pin: 12, name: 'B7',   type: 'bidir'  },
      { pin: 13, name: 'B6',   type: 'bidir'  },
      { pin: 14, name: 'B5',   type: 'bidir'  },
      { pin: 15, name: 'B4',   type: 'bidir'  },
      { pin: 16, name: 'B3',   type: 'bidir'  },
      { pin: 17, name: 'B2',   type: 'bidir'  },
      { pin: 18, name: 'B1',   type: 'bidir'  },
      { pin: 19, name: 'OE2n', type: 'input'  },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OE1n', 'OE2n'], outputs: [] },
    ],
  },

  // 74x3374: 8 bit metastable resistant D type flip flop, three state (20-pin)
  // SN74AS3374 -- follows standard 74374-pin convention (D/Q interleaved per bit, not bus style)
  '74x3374': {
    name: '74x3374',
    simpleName: '8 bit Metastable Resistant D Flip Flop (TS)',
    description: '8-bit metastable-resistant D-type flip-flop, 3-state outputs (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: '',
    tags: ['flip flop', '8 bit', 'D type', 'metastable', 'tri state', 'stub'],
    pinout: [
      { pin:  1, name: 'OE',   type: 'input'  },
      { pin:  2, name: '1Q',   type: 'output' },
      { pin:  3, name: '1D',   type: 'input'  },
      { pin:  4, name: '2D',   type: 'input'  },
      { pin:  5, name: '2Q',   type: 'output' },
      { pin:  6, name: '3D',   type: 'input'  },
      { pin:  7, name: '3Q',   type: 'output' },
      { pin:  8, name: '4D',   type: 'input'  },
      { pin:  9, name: '4Q',   type: 'output' },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'CLK',  type: 'input'  },
      { pin: 12, name: '5Q',   type: 'output' },
      { pin: 13, name: '5D',   type: 'input'  },
      { pin: 14, name: '6D',   type: 'input'  },
      { pin: 15, name: '6Q',   type: 'output' },
      { pin: 16, name: '7D',   type: 'input'  },
      { pin: 17, name: '7Q',   type: 'output' },
      { pin: 18, name: '8D',   type: 'input'  },
      { pin: 19, name: '8Q',   type: 'output' },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['1D','2D','3D','4D','5D','6D','7D','8D','CLK','OE'], outputs: [] },
    ],
  },

  // 74x3383: 5 bit 4-port FET bus exchange switch (24-pin)
  // IDT74FST3383 -- 4 ports (A,B,C,D) each 5 bit wide; OE1n enables A<->B, OE2n enables C<->D
  '74x3383': {
    name: '74x3383',
    simpleName: '5 bit 4-Port FET Bus Exchange Switch',
    description: '5 bit 4-port FET bus exchange switch (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: 'https://www.renesas.com/en/products/74fst3383',
    tags: ['FET', 'bus-switch', '5 bit', '4-port', 'exchange', 'bidir', 'stub'],
    guideOverview: 'The 74x3383 is a multiport FET bus switch device that groups its channels into two independently enabled 5 bit connections. Instead of buffering data, it creates low delay bilateral links between paired ports, which is useful when a board needs to rearrange or isolate bus segments without committing to one signal direction. Devices in this class are commonly used in routing fabrics, bus sharing, and connection management between logic blocks.',
    guidePinDescriptions: {
      'OE1n': 'Active LOW enable for the A-to B switch group. Pull LOW to allow the A and B channels to connect.',
      'A1': 'Bit 1 of port A.',
      'A2': 'Bit 2 of port A.',
      'A3': 'Bit 3 of port A.',
      'A4': 'Bit 4 of port A.',
      'A5': 'Bit 5 of port A.',
      'B5': 'Bit 5 of port B.',
      'B4': 'Bit 4 of port B.',
      'B3': 'Bit 3 of port B.',
      'B2': 'Bit 2 of port B.',
      'B1': 'Bit 1 of port B.',
      'GND': 'Ground reference for the switch control circuitry.',
      'C1': 'Bit 1 of port C.',
      'C2': 'Bit 2 of port C.',
      'C3': 'Bit 3 of port C.',
      'C4': 'Bit 4 of port C.',
      'C5': 'Bit 5 of port C.',
      'D5': 'Bit 5 of port D.',
      'D4': 'Bit 4 of port D.',
      'D3': 'Bit 3 of port D.',
      'D2': 'Bit 2 of port D.',
      'D1': 'Bit 1 of port D.',
      'OE2n': 'Active LOW enable for the C-to D switch group.',
      'VCC': 'Positive supply for the device.',
    },
    guideSections: [
      {
        title: 'Two Independently Enabled Groups',
        paragraphs: [
          'The local definition organizes the device as two 5 bit switch groups. One enable controls the A/B connection set and the other controls the C/D set, so the two groups can be used separately.',
        ],
      },
      {
        title: 'Exchange and Routing Use',
        paragraphs: [
          'Multiport bus switches are useful when signals need to be rerouted or conditionally connected without adding logic inversion or clocked storage. They behave more like electronically controlled wiring than like ordinary gates.',
        ],
        note: 'The simulator keeps this as a documented stub. It captures the control intent and pin roles, but not detailed analog pass switch behavior.',
      },
    ],
    pinout: [
      { pin:  1, name: 'OE1n', type: 'input'  },
      { pin:  2, name: 'A1',   type: 'bidir'  },
      { pin:  3, name: 'A2',   type: 'bidir'  },
      { pin:  4, name: 'A3',   type: 'bidir'  },
      { pin:  5, name: 'A4',   type: 'bidir'  },
      { pin:  6, name: 'A5',   type: 'bidir'  },
      { pin:  7, name: 'B5',   type: 'bidir'  },
      { pin:  8, name: 'B4',   type: 'bidir'  },
      { pin:  9, name: 'B3',   type: 'bidir'  },
      { pin: 10, name: 'B2',   type: 'bidir'  },
      { pin: 11, name: 'B1',   type: 'bidir'  },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'C1',   type: 'bidir'  },
      { pin: 14, name: 'C2',   type: 'bidir'  },
      { pin: 15, name: 'C3',   type: 'bidir'  },
      { pin: 16, name: 'C4',   type: 'bidir'  },
      { pin: 17, name: 'C5',   type: 'bidir'  },
      { pin: 18, name: 'D5',   type: 'bidir'  },
      { pin: 19, name: 'D4',   type: 'bidir'  },
      { pin: 20, name: 'D3',   type: 'bidir'  },
      { pin: 21, name: 'D2',   type: 'bidir'  },
      { pin: 22, name: 'D1',   type: 'bidir'  },
      { pin: 23, name: 'OE2n', type: 'input'  },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OE1n', 'OE2n'], outputs: [] },
    ],
  },

  // 74x3384: Dual 5 bit FET bus switch (24-pin)
  // IDT74FST3384 -- two independent 5 bit switches; OE1n controls 1A<->1B, OE2n controls 2A<->2B
  '74x3384': {
    name: '74x3384',
    simpleName: 'Dual 5 bit FET Bus Switch',
    description: 'Dual 5 bit FET bus switch (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: 'https://www.renesas.com/en/products/74fst3384',
    tags: ['FET', 'bus-switch', 'dual', '5 bit', 'bidir', 'stub'],
    guideOverview: 'The 74x3384 provides two separately controlled 5 bit bilateral bus switch banks. Each bank can connect one 5 bit group of pins to another with little delay and without imposing a fixed data direction. This is useful when several bus groups need to be connected only under certain operating modes or board configurations.',
    guidePinDescriptions: {
      'OE1n': 'Active LOW enable for bank 1. Pull LOW to connect the 1A and 1B signals.',
      '1A1': 'Bit 1 on bank 1, side A.',
      '1A2': 'Bit 2 on bank 1, side A.',
      '1A3': 'Bit 3 on bank 1, side A.',
      '1A4': 'Bit 4 on bank 1, side A.',
      '1A5': 'Bit 5 on bank 1, side A.',
      '1B5': 'Bit 5 on bank 1, side B.',
      '1B4': 'Bit 4 on bank 1, side B.',
      '1B3': 'Bit 3 on bank 1, side B.',
      '1B2': 'Bit 2 on bank 1, side B.',
      '1B1': 'Bit 1 on bank 1, side B.',
      'GND': 'Ground reference for the package.',
      '2B1': 'Bit 1 on bank 2, side B.',
      '2B2': 'Bit 2 on bank 2, side B.',
      '2B3': 'Bit 3 on bank 2, side B.',
      '2B4': 'Bit 4 on bank 2, side B.',
      '2B5': 'Bit 5 on bank 2, side B.',
      '2A5': 'Bit 5 on bank 2, side A.',
      '2A4': 'Bit 4 on bank 2, side A.',
      '2A3': 'Bit 3 on bank 2, side A.',
      '2A2': 'Bit 2 on bank 2, side A.',
      '2A1': 'Bit 1 on bank 2, side A.',
      'OE2n': 'Active LOW enable for bank 2.',
      'VCC': 'Positive supply for the control circuitry.',
    },
    guideSections: [
      {
        title: 'Two 5 bit Banks',
        paragraphs: [
          'The device is divided into two independent banks, each with its own enable. That lets one 5 bit path be active while the other is isolated, or both be active together when needed.',
        ],
      },
      {
        title: 'Switch Instead of Buffer',
        paragraphs: [
          'Because the paths are bilateral FET switches, the part behaves like controllable wiring rather than like a directional bus driver. That can be an advantage when the source side of the signal changes with operating mode.',
        ],
        note: 'This entry remains a documented stub rather than a full analog switch simulation.',
      },
    ],
    pinout: [
      { pin:  1, name: 'OE1n', type: 'input'  },
      { pin:  2, name: '1A1',  type: 'bidir'  },
      { pin:  3, name: '1A2',  type: 'bidir'  },
      { pin:  4, name: '1A3',  type: 'bidir'  },
      { pin:  5, name: '1A4',  type: 'bidir'  },
      { pin:  6, name: '1A5',  type: 'bidir'  },
      { pin:  7, name: '1B5',  type: 'bidir'  },
      { pin:  8, name: '1B4',  type: 'bidir'  },
      { pin:  9, name: '1B3',  type: 'bidir'  },
      { pin: 10, name: '1B2',  type: 'bidir'  },
      { pin: 11, name: '1B1',  type: 'bidir'  },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: '2B1',  type: 'bidir'  },
      { pin: 14, name: '2B2',  type: 'bidir'  },
      { pin: 15, name: '2B3',  type: 'bidir'  },
      { pin: 16, name: '2B4',  type: 'bidir'  },
      { pin: 17, name: '2B5',  type: 'bidir'  },
      { pin: 18, name: '2A5',  type: 'bidir'  },
      { pin: 19, name: '2A4',  type: 'bidir'  },
      { pin: 20, name: '2A3',  type: 'bidir'  },
      { pin: 21, name: '2A2',  type: 'bidir'  },
      { pin: 22, name: '2A1',  type: 'bidir'  },
      { pin: 23, name: 'OE2n', type: 'input'  },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OE1n', 'OE2n'], outputs: [] },
    ],
  },

  // 74x3386: 5 bit 4-port FET bus exchange switch, extended voltage range (24-pin)
  // SN74CBT3386 -- identical function and pinout to 74x3383; TI CBT technology with wider voltage range
  '74x3386': {
    name: '74x3386',
    simpleName: '5 bit 4-Port FET Bus Exchange Switch (Extended Voltage)',
    description: '5 bit 4-port FET bus exchange switch with extended voltage range (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['FET', 'bus-switch', '5 bit', '4-port', 'exchange', 'bidir', 'stub'],
    pinout: [
      { pin:  1, name: 'OE1n', type: 'input'  },
      { pin:  2, name: 'A1',   type: 'bidir'  },
      { pin:  3, name: 'A2',   type: 'bidir'  },
      { pin:  4, name: 'A3',   type: 'bidir'  },
      { pin:  5, name: 'A4',   type: 'bidir'  },
      { pin:  6, name: 'A5',   type: 'bidir'  },
      { pin:  7, name: 'B5',   type: 'bidir'  },
      { pin:  8, name: 'B4',   type: 'bidir'  },
      { pin:  9, name: 'B3',   type: 'bidir'  },
      { pin: 10, name: 'B2',   type: 'bidir'  },
      { pin: 11, name: 'B1',   type: 'bidir'  },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'C1',   type: 'bidir'  },
      { pin: 14, name: 'C2',   type: 'bidir'  },
      { pin: 15, name: 'C3',   type: 'bidir'  },
      { pin: 16, name: 'C4',   type: 'bidir'  },
      { pin: 17, name: 'C5',   type: 'bidir'  },
      { pin: 18, name: 'D5',   type: 'bidir'  },
      { pin: 19, name: 'D4',   type: 'bidir'  },
      { pin: 20, name: 'D3',   type: 'bidir'  },
      { pin: 21, name: 'D2',   type: 'bidir'  },
      { pin: 22, name: 'D1',   type: 'bidir'  },
      { pin: 23, name: 'OE2n', type: 'input'  },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OE1n', 'OE2n'], outputs: [] },
    ],
  },

  // 74x3573: Octal transparent D type latch, three state (20-pin)
  // IDT74FCT3573 -- FCT version of 74573; identical pinout to standard 74x573
  '74x3573': {
    name: '74x3573',
    simpleName: 'Octal Transparent Latch (TS)',
    description: 'Octal transparent D type latch with three state outputs (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.renesas.com/en/products/74fct3573',
    tags: ['latch', 'octal', '8 bit', 'transparent', 'tri state', 'stub'],
    guideOverview: 'The 74x3573 is an octal transparent latch with three state outputs. A transparent latch lets data flow directly from D to Q while the latch enable input is active, then holds the last value when the enable is removed. This makes the part useful for temporarily capturing bus values, holding addresses, or isolating one logic stage from timing changes in another.',
    guidePinDescriptions: {
      'OE': 'Output-enable control. On 573-style latches this control is typically active LOW and is used to place the outputs in high impedance when the stored data should not drive a bus.',
      '1D': 'Data input for bit 1.',
      '2D': 'Data input for bit 2.',
      '3D': 'Data input for bit 3.',
      '4D': 'Data input for bit 4.',
      '5D': 'Data input for bit 5.',
      '6D': 'Data input for bit 6.',
      '7D': 'Data input for bit 7.',
      '8D': 'Data input for bit 8.',
      'GND': 'Ground reference for the device.',
      'LE': 'Latch enable input. While LE is asserted, the outputs follow the inputs; when LE is released, the last state is held.',
      '8Q': 'Stored output for bit 8.',
      '7Q': 'Stored output for bit 7.',
      '6Q': 'Stored output for bit 6.',
      '5Q': 'Stored output for bit 5.',
      '4Q': 'Stored output for bit 4.',
      '3Q': 'Stored output for bit 3.',
      '2Q': 'Stored output for bit 2.',
      '1Q': 'Stored output for bit 1.',
      'VCC': 'Positive supply for the latch.',
    },
    guideSections: [
      {
        title: 'Transparent Latch Behavior',
        paragraphs: [
          'A transparent latch is level sensitive. When LE is active, each Q output follows its matching D input in real time. When LE becomes inactive, the most recent state is stored and held.',
        ],
      },
      {
        title: 'Why Three State Outputs Matter',
        paragraphs: [
          'Three state outputs let the latch hold data internally without necessarily driving the shared bus. That makes latches like the 74x3573 useful in bused systems where several devices share the same lines.',
        ],
        note: 'The simulator documents the role of this latch, but the entry remains a stub rather than a full stateful implementation.',
      },
    ],
    pinout: [
      { pin:  1, name: 'OE',   type: 'input'  },
      { pin:  2, name: '1D',   type: 'input'  },
      { pin:  3, name: '2D',   type: 'input'  },
      { pin:  4, name: '3D',   type: 'input'  },
      { pin:  5, name: '4D',   type: 'input'  },
      { pin:  6, name: '5D',   type: 'input'  },
      { pin:  7, name: '6D',   type: 'input'  },
      { pin:  8, name: '7D',   type: 'input'  },
      { pin:  9, name: '8D',   type: 'input'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'LE',   type: 'input'  },
      { pin: 12, name: '8Q',   type: 'output' },
      { pin: 13, name: '7Q',   type: 'output' },
      { pin: 14, name: '6Q',   type: 'output' },
      { pin: 15, name: '5Q',   type: 'output' },
      { pin: 16, name: '4Q',   type: 'output' },
      { pin: 17, name: '3Q',   type: 'output' },
      { pin: 18, name: '2Q',   type: 'output' },
      { pin: 19, name: '1Q',   type: 'output' },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OE','LE','1D','2D','3D','4D','5D','6D','7D','8D'], outputs: [] },
    ],
  },

  // 74x3574: Octal D type edge triggered flip flop, three state (20-pin)
  // IDT74FCT3574 -- FCT version of 74574; identical pinout to standard 74x574
  '74x3574': {
    name: '74x3574',
    simpleName: 'Octal D Flip Flop (TS)',
    description: 'Octal D type edge triggered flip flop with three state outputs (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.renesas.com/en/products/74fct3574',
    tags: ['flip flop', 'octal', '8 bit', 'D type', 'tri state', 'stub'],
    guideOverview: 'The 74x3574 is an octal edge triggered D flip flop with three state outputs. Unlike a transparent latch, a flip flop captures data only on a clock edge, which makes it better suited for synchronous digital designs. Breadboard builders reach for parts like this when they need to register bus data cleanly on a clock and hold it stable between clock events.',
    guidePinDescriptions: {
      'OE': 'Output-enable control. On 574-style devices this control is typically active LOW and disconnects the outputs from the bus when not asserted.',
      '1D': 'Data input for bit 1.',
      '2D': 'Data input for bit 2.',
      '3D': 'Data input for bit 3.',
      '4D': 'Data input for bit 4.',
      '5D': 'Data input for bit 5.',
      '6D': 'Data input for bit 6.',
      '7D': 'Data input for bit 7.',
      '8D': 'Data input for bit 8.',
      'GND': 'Ground reference for the package.',
      'CLK': 'Clock input. Data on the D inputs is captured on the active clock edge and then held until the next capture.',
      '8Q': 'Registered output for bit 8.',
      '7Q': 'Registered output for bit 7.',
      '6Q': 'Registered output for bit 6.',
      '5Q': 'Registered output for bit 5.',
      '4Q': 'Registered output for bit 4.',
      '3Q': 'Registered output for bit 3.',
      '2Q': 'Registered output for bit 2.',
      '1Q': 'Registered output for bit 1.',
      'VCC': 'Positive supply for the flip flop.',
    },
    guideSections: [
      {
        title: 'Edge Triggered Storage',
        paragraphs: [
          'A D flip flop samples data only at a clock transition. That makes the outputs less sensitive to input chatter between clock edges and gives the system a clear synchronous timing point.',
        ],
      },
      {
        title: 'Registered Bus Operation',
        paragraphs: [
          'Three state registered outputs let the device hold a byte internally and then present it onto a shared bus only when allowed. That is a common pattern in CPUs, peripheral interfaces, and pipeline stages.',
        ],
        note: 'This chip remains a documented stub in the simulator rather than a full clocked implementation.',
      },
    ],
    pinout: [
      { pin:  1, name: 'OE',   type: 'input'  },
      { pin:  2, name: '1D',   type: 'input'  },
      { pin:  3, name: '2D',   type: 'input'  },
      { pin:  4, name: '3D',   type: 'input'  },
      { pin:  5, name: '4D',   type: 'input'  },
      { pin:  6, name: '5D',   type: 'input'  },
      { pin:  7, name: '6D',   type: 'input'  },
      { pin:  8, name: '7D',   type: 'input'  },
      { pin:  9, name: '8D',   type: 'input'  },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'CLK',  type: 'input'  },
      { pin: 12, name: '8Q',   type: 'output' },
      { pin: 13, name: '7Q',   type: 'output' },
      { pin: 14, name: '6Q',   type: 'output' },
      { pin: 15, name: '5Q',   type: 'output' },
      { pin: 16, name: '4Q',   type: 'output' },
      { pin: 17, name: '3Q',   type: 'output' },
      { pin: 18, name: '2Q',   type: 'output' },
      { pin: 19, name: '1Q',   type: 'output' },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OE','CLK','1D','2D','3D','4D','5D','6D','7D','8D'], outputs: [] },
    ],
  },

  // 74x3584: Dual 5 bit FET bus switch with 25 Ohm series resistors (24-pin)
  // QS74QST3584 -- same function and pinout as 74x3384; 25 Ohm series resistors reduce EMI/reflections
  '74x3584': {
    name: '74x3584',
    simpleName: 'Dual 5 bit FET Bus Switch (25 Ohm Series Resistor)',
    description: 'Dual 5 bit FET bus switch with 25 Ohm series resistor (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['FET', 'bus-switch', 'dual', '5 bit', 'bidir', 'stub'],
    pinout: [
      { pin:  1, name: 'OE1n', type: 'input'  },
      { pin:  2, name: '1A1',  type: 'bidir'  },
      { pin:  3, name: '1A2',  type: 'bidir'  },
      { pin:  4, name: '1A3',  type: 'bidir'  },
      { pin:  5, name: '1A4',  type: 'bidir'  },
      { pin:  6, name: '1A5',  type: 'bidir'  },
      { pin:  7, name: '1B5',  type: 'bidir'  },
      { pin:  8, name: '1B4',  type: 'bidir'  },
      { pin:  9, name: '1B3',  type: 'bidir'  },
      { pin: 10, name: '1B2',  type: 'bidir'  },
      { pin: 11, name: '1B1',  type: 'bidir'  },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: '2B1',  type: 'bidir'  },
      { pin: 14, name: '2B2',  type: 'bidir'  },
      { pin: 15, name: '2B3',  type: 'bidir'  },
      { pin: 16, name: '2B4',  type: 'bidir'  },
      { pin: 17, name: '2B5',  type: 'bidir'  },
      { pin: 18, name: '2A5',  type: 'bidir'  },
      { pin: 19, name: '2A4',  type: 'bidir'  },
      { pin: 20, name: '2A3',  type: 'bidir'  },
      { pin: 21, name: '2A2',  type: 'bidir'  },
      { pin: 22, name: '2A1',  type: 'bidir'  },
      { pin: 23, name: 'OE2n', type: 'input'  },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OE1n', 'OE2n'], outputs: [] },
    ],
  },

  // 74x3807: 3.3V CMOS 1-to-10 low skew clock driver (20-pin)
  // IDT74FCT3807 -- OEn at pin 1, A (clock input) at pin 2, Y0-Y4 top half, Y5-Y9 bottom half
  // Multiple internal power/ground bonds for low noise; NCs on unused package pins
  '74x3807': {
    name: '74x3807',
    simpleName: '1-to-10 Clock Driver',
    description: '3.3V CMOS 1-to-10 low skew clock driver (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: 'https://www.renesas.com/en/products/74fct3807',
    tags: ['clock', 'driver', 'buffer', '1:10', 'fanout', 'stub'],
    guideOverview: 'The 74x3807 is a clock fanout buffer that copies one input clock onto ten outputs while keeping the skew between outputs low. Low skew matters because clocked logic behaves best when each destination sees nearly the same clock edge time. This part is useful whenever one oscillator or system clock must feed many chips without building a discrete buffer tree.',
    guidePinDescriptions: {
      'OEn': 'Active LOW enable for the clock outputs. Pull LOW to let the input clock drive the outputs; drive HIGH to disable them.',
      'A': 'Clock input. This single input is copied to all enabled Y outputs.',
      'Y0': 'Clock output 0.',
      'Y1': 'Clock output 1.',
      'Y2': 'Clock output 2.',
      'Y3': 'Clock output 3.',
      'Y4': 'Clock output 4.',
      'NC': 'No internal connection. Leave unconnected.',
      'NC2': 'No internal connection. Leave unconnected.',
      'GND': 'Ground reference for the driver.',
      'NC3': 'No internal connection. Leave unconnected.',
      'NC4': 'No internal connection. Leave unconnected.',
      'Y5': 'Clock output 5.',
      'Y6': 'Clock output 6.',
      'Y7': 'Clock output 7.',
      'Y8': 'Clock output 8.',
      'Y9': 'Clock output 9.',
      'NC5': 'No internal connection. Leave unconnected.',
      'NC6': 'No internal connection. Leave unconnected.',
      'VCC': 'Positive supply for the clock driver circuitry.',
    },
    guideSections: [
      {
        title: 'Clock Fanout and Skew',
        paragraphs: [
          'A plain logic buffer can duplicate a clock, but when many destinations need the same edge, the timing difference between outputs becomes important. A low skew clock driver is designed so those output to output differences stay small.',
        ],
      },
      {
        title: 'Why a Dedicated Clock Driver Helps',
        paragraphs: [
          'Using one part to fan a clock out to many loads is often cleaner than cascading ordinary gates. It reduces uncertainty, keeps loading more predictable, and simplifies clock distribution wiring.',
        ],
        note: 'This entry is documented as a stub in the simulator. It describes the chip role and pins, but it does not model fine grained timing skew.',
      },
    ],
    pinout: [
      { pin:  1, name: 'OEn',  type: 'input'  },
      { pin:  2, name: 'A',    type: 'input'  },
      { pin:  3, name: 'Y0',   type: 'output' },
      { pin:  4, name: 'Y1',   type: 'output' },
      { pin:  5, name: 'Y2',   type: 'output' },
      { pin:  6, name: 'Y3',   type: 'output' },
      { pin:  7, name: 'Y4',   type: 'output' },
      { pin:  8, name: 'NC',   type: 'nc'     },
      { pin:  9, name: 'NC2',  type: 'nc'     },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'NC3',  type: 'nc'     },
      { pin: 12, name: 'NC4',  type: 'nc'     },
      { pin: 13, name: 'Y5',   type: 'output' },
      { pin: 14, name: 'Y6',   type: 'output' },
      { pin: 15, name: 'Y7',   type: 'output' },
      { pin: 16, name: 'Y8',   type: 'output' },
      { pin: 17, name: 'Y9',   type: 'output' },
      { pin: 18, name: 'NC5',  type: 'nc'     },
      { pin: 19, name: 'NC6',  type: 'nc'     },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn', 'A'], outputs: [] },
    ],
  },

  // 74x3827: 10 bit non inverting buffer, three state (24-pin)
  // IDT74FCT3827 -- same pinout structure as 74x2827 (SN74BCT2827), without 25 Ohm series resistor
  '74x3827': {
    name: '74x3827',
    simpleName: '10 bit Non Inverting Buffer (TS)',
    description: '10 bit non inverting buffer with three state outputs (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: 'https://www.renesas.com/en/products/74fct3827',
    tags: ['buffer', '10 bit', 'non inverting', 'tri state', 'stub'],
    guideOverview: 'The 74x3827 is a 10 bit non inverting buffer with three state outputs. It is meant to strengthen and isolate a wide parallel signal group without changing the bit values. Devices like this are common in bus interfaces, where one source needs enough drive strength to feed several loads or where a bus should be disconnectable under control.',
    guidePinDescriptions: {
      'OE1n': 'Active LOW output-enable control for one side of the output bank. Assert it to let the related outputs drive.',
      'A0': 'Input bit 0.',
      'A1': 'Input bit 1.',
      'A2': 'Input bit 2.',
      'A3': 'Input bit 3.',
      'A4': 'Input bit 4.',
      'A5': 'Input bit 5.',
      'A6': 'Input bit 6.',
      'A7': 'Input bit 7.',
      'A8': 'Input bit 8.',
      'A9': 'Input bit 9.',
      'GND': 'Ground reference for the package.',
      'OE2n': 'Second active LOW enable control for the remaining output bank.',
      'Y9': 'Buffered output bit 9.',
      'Y8': 'Buffered output bit 8.',
      'Y7': 'Buffered output bit 7.',
      'Y6': 'Buffered output bit 6.',
      'Y5': 'Buffered output bit 5.',
      'Y4': 'Buffered output bit 4.',
      'Y3': 'Buffered output bit 3.',
      'Y2': 'Buffered output bit 2.',
      'Y1': 'Buffered output bit 1.',
      'Y0': 'Buffered output bit 0.',
      'VCC': 'Positive supply for the buffer.',
    },
    guideSections: [
      {
        title: 'Why Buffer a Wide Bus',
        paragraphs: [
          'Wide buffers isolate the source from heavy bus loading and help preserve clean logic levels across a board. A non inverting buffer reproduces the same bit values at the outputs, just with more drive capability and controlled enable behavior.',
        ],
      },
      {
        title: 'Three State Control',
        paragraphs: [
          'The output-enable inputs let the device disconnect from the bus when another device should be driving. That is essential in shared bus systems where multiple sources take turns using the same traces.',
        ],
        note: 'The simulator keeps this device as a documented stub rather than a detailed bus driver model.',
      },
    ],
    pinout: [
      { pin:  1, name: 'OE1n', type: 'input'  },
      { pin:  2, name: 'A0',   type: 'input'  },
      { pin:  3, name: 'A1',   type: 'input'  },
      { pin:  4, name: 'A2',   type: 'input'  },
      { pin:  5, name: 'A3',   type: 'input'  },
      { pin:  6, name: 'A4',   type: 'input'  },
      { pin:  7, name: 'A5',   type: 'input'  },
      { pin:  8, name: 'A6',   type: 'input'  },
      { pin:  9, name: 'A7',   type: 'input'  },
      { pin: 10, name: 'A8',   type: 'input'  },
      { pin: 11, name: 'A9',   type: 'input'  },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'OE2n', type: 'input'  },
      { pin: 14, name: 'Y9',   type: 'output' },
      { pin: 15, name: 'Y8',   type: 'output' },
      { pin: 16, name: 'Y7',   type: 'output' },
      { pin: 17, name: 'Y6',   type: 'output' },
      { pin: 18, name: 'Y5',   type: 'output' },
      { pin: 19, name: 'Y4',   type: 'output' },
      { pin: 20, name: 'Y3',   type: 'output' },
      { pin: 21, name: 'Y2',   type: 'output' },
      { pin: 22, name: 'Y1',   type: 'output' },
      { pin: 23, name: 'Y0',   type: 'output' },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OE1n','OE2n','A0','A1','A2','A3','A4','A5','A6','A7','A8','A9'], outputs: [] },
    ],
  },

  // 74x3861: 10 bit FET bus switch (24-pin)
  // SN74CBT3861 -- single OEn controls all 10 switches; A1-A10 and B1-B10 bidir; pin 13 is NC
  '74x3861': {
    name: '74x3861',
    simpleName: '10 bit FET Bus Switch',
    description: '10 bit FET bus switch (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74cbt3861.pdf',
    tags: ['FET', 'bus-switch', '10 bit', 'bidir', 'stub'],
    guideOverview: 'The 74x3861 is a 10 bit bilateral bus switch. One active LOW enable controls ten separate pass switch channels, making it a compact way to connect or isolate an entire 10 bit group in one action. This is useful for wide buses, shared backplanes, or board sections that should only be linked in certain modes.',
    guidePinDescriptions: {
      'OEn': 'Active LOW global enable for all ten switch channels. Pull LOW to connect the A and B buses; drive HIGH to isolate them.',
      'A1': 'Bit 1 on the A-side bus.',
      'A2': 'Bit 2 on the A-side bus.',
      'A3': 'Bit 3 on the A-side bus.',
      'A4': 'Bit 4 on the A-side bus.',
      'A5': 'Bit 5 on the A-side bus.',
      'A6': 'Bit 6 on the A-side bus.',
      'A7': 'Bit 7 on the A-side bus.',
      'A8': 'Bit 8 on the A-side bus.',
      'A9': 'Bit 9 on the A-side bus.',
      'A10': 'Bit 10 on the A-side bus.',
      'GND': 'Ground reference for the device.',
      'NC': 'No internal connection. Leave unconnected.',
      'B10': 'Bit 10 on the B-side bus.',
      'B9': 'Bit 9 on the B-side bus.',
      'B8': 'Bit 8 on the B-side bus.',
      'B7': 'Bit 7 on the B-side bus.',
      'B6': 'Bit 6 on the B-side bus.',
      'B5': 'Bit 5 on the B-side bus.',
      'B4': 'Bit 4 on the B-side bus.',
      'B3': 'Bit 3 on the B-side bus.',
      'B2': 'Bit 2 on the B-side bus.',
      'B1': 'Bit 1 on the B-side bus.',
      'VCC': 'Positive supply for the control circuitry.',
    },
    guideSections: [
      {
        title: 'One Control for Ten Channels',
        paragraphs: [
          'The single enable pin makes the device act like a wide electronically controlled connector. When enabled, all ten A/B pairs are linked; when disabled, all ten are opened at once.',
        ],
      },
      {
        title: 'Where Wide Bus Switches Help',
        paragraphs: [
          'Wide pass switch parts are useful where many parallel lines must be joined or separated together, such as memory interfaces, plug in options, and segmented buses.',
        ],
        note: 'The simulator documents the intended control behavior but does not model analog pass transistor details.',
      },
    ],
    pinout: [
      { pin:  1, name: 'OEn',  type: 'input'  },
      { pin:  2, name: 'A1',   type: 'bidir'  },
      { pin:  3, name: 'A2',   type: 'bidir'  },
      { pin:  4, name: 'A3',   type: 'bidir'  },
      { pin:  5, name: 'A4',   type: 'bidir'  },
      { pin:  6, name: 'A5',   type: 'bidir'  },
      { pin:  7, name: 'A6',   type: 'bidir'  },
      { pin:  8, name: 'A7',   type: 'bidir'  },
      { pin:  9, name: 'A8',   type: 'bidir'  },
      { pin: 10, name: 'A9',   type: 'bidir'  },
      { pin: 11, name: 'A10',  type: 'bidir'  },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'NC',   type: 'nc'     },
      { pin: 14, name: 'B10',  type: 'bidir'  },
      { pin: 15, name: 'B9',   type: 'bidir'  },
      { pin: 16, name: 'B8',   type: 'bidir'  },
      { pin: 17, name: 'B7',   type: 'bidir'  },
      { pin: 18, name: 'B6',   type: 'bidir'  },
      { pin: 19, name: 'B5',   type: 'bidir'  },
      { pin: 20, name: 'B4',   type: 'bidir'  },
      { pin: 21, name: 'B3',   type: 'bidir'  },
      { pin: 22, name: 'B2',   type: 'bidir'  },
      { pin: 23, name: 'B1',   type: 'bidir'  },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OEn'], outputs: [] },
    ],
  },

  // 74x3862: 10 bit FET bus switch with dual output enable (24-pin)
  // IDT74CBTLV3862 -- CBTLV (low voltage) technology; OE1 (active HIGH, pin 1) and OE2n (active LOW, pin 23) for wired OR control
  '74x3862': {
    name: '74x3862',
    simpleName: '10 bit FET Bus Switch (Dual Output Enable)',
    description: '10 bit FET bus switch with dual output enable (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: 'https://www.renesas.com/en/products/74cbtlv3862',
    tags: ['FET', 'bus-switch', '10 bit', 'bidir'],
    guideOverview: 'The 74x3862 is a 10 bit bilateral bus switch in the CBTLV family. It links two wide signal groups with low delay instead of buffering them through a fixed logic direction. The device uses mixed polarity enables: OE1 is active HIGH (pin 1) and OE2n is active LOW (pin 23). Both must be asserted simultaneously for the switch to conduct.',
    guidePinDescriptions: {
      'OE1': 'Active HIGH output enable. Drive HIGH to enable the switch channels. Must be HIGH and OE2n must be LOW for the switch to conduct.',
      'A1': 'Bit 1 on the A-side bus.',
      'A2': 'Bit 2 on the A-side bus.',
      'A3': 'Bit 3 on the A-side bus.',
      'A4': 'Bit 4 on the A-side bus.',
      'A5': 'Bit 5 on the A-side bus.',
      'A6': 'Bit 6 on the A-side bus.',
      'A7': 'Bit 7 on the A-side bus.',
      'A8': 'Bit 8 on the A-side bus.',
      'A9': 'Bit 9 on the A-side bus.',
      'A10': 'Bit 10 on the A-side bus.',
      'GND': 'Ground reference for the device.',
      'B10': 'Bit 10 on the B-side bus.',
      'B9': 'Bit 9 on the B-side bus.',
      'B8': 'Bit 8 on the B-side bus.',
      'B7': 'Bit 7 on the B-side bus.',
      'B6': 'Bit 6 on the B-side bus.',
      'B5': 'Bit 5 on the B-side bus.',
      'B4': 'Bit 4 on the B-side bus.',
      'B3': 'Bit 3 on the B-side bus.',
      'B2': 'Bit 2 on the B-side bus.',
      'B1': 'Bit 1 on the B-side bus.',
      'OE2n': 'Active LOW output enable. Drive LOW to enable the switch channels. Must be LOW and OE1 must be HIGH for the switch to conduct.',
      'VCC': 'Positive supply for the control circuitry.',
    },
    guideSections: [
      {
        title: 'Wide Bilateral Switching',
        paragraphs: [
          'The core job of the device is still straightforward: it conditionally links ten A/B signal pairs through pass switches. That makes it suitable for bus isolation and wide path routing with little added propagation delay.',
        ],
      },
      {
        title: 'Mixed Polarity Dual Enable',
        paragraphs: [
          'The two enable pins use opposite polarities: OE1 is active HIGH and OE2n is active LOW. The switch conducts only when both enables are asserted (OE1=1 and OE2n=0). This wired OR arrangement allows flexible enable control from different logic sources.',
        ],
        formulas: [
          'Switch ON: OE1 = 1 AND OE2n = 0',
          'Switch OFF: OE1 = 0 OR OE2n = 1',
        ],
      },
    ],
    pinout: [
      { pin:  1, name: 'OE1',  type: 'input'  },
      { pin:  2, name: 'A1',   type: 'bidir'  },
      { pin:  3, name: 'A2',   type: 'bidir'  },
      { pin:  4, name: 'A3',   type: 'bidir'  },
      { pin:  5, name: 'A4',   type: 'bidir'  },
      { pin:  6, name: 'A5',   type: 'bidir'  },
      { pin:  7, name: 'A6',   type: 'bidir'  },
      { pin:  8, name: 'A7',   type: 'bidir'  },
      { pin:  9, name: 'A8',   type: 'bidir'  },
      { pin: 10, name: 'A9',   type: 'bidir'  },
      { pin: 11, name: 'A10',  type: 'bidir'  },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'B10',  type: 'bidir'  },
      { pin: 14, name: 'B9',   type: 'bidir'  },
      { pin: 15, name: 'B8',   type: 'bidir'  },
      { pin: 16, name: 'B7',   type: 'bidir'  },
      { pin: 17, name: 'B6',   type: 'bidir'  },
      { pin: 18, name: 'B5',   type: 'bidir'  },
      { pin: 19, name: 'B4',   type: 'bidir'  },
      { pin: 20, name: 'B3',   type: 'bidir'  },
      { pin: 21, name: 'B2',   type: 'bidir'  },
      { pin: 22, name: 'B1',   type: 'bidir'  },
      { pin: 23, name: 'OE2n', type: 'input'  },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['OE1', 'OE2n'], outputs: [] },
    ],
  },
};
