// Chip definitions block 44
// Chips: 74907-74910, 74913-74915, 74918, 74920-74923, 74925-74928

export const CHIPS_BLOCK_44 = {

  // 74907: Hex open drain p-channel buffers (14-pin)
  '74907': {
    name: '74x907',
    simpleName: 'Hex Open Drain P-Channel Buffer',
    description: 'Hex open drain p-channel buffers (14-pin)',
    pins: 14, vcc: 14, gnd: 7,
    openCollector: true,
    datasheet: '',
    tags: ['buffer', 'hex', 'open drain', 'pmos'],
    guideOverview: 'The 74x907 is a hex open-drain p-channel buffer. Six BUFFER channels pass their input without inversion, but each output is an open-drain p-channel transistor that can only pull the output HIGH (toward VCC), not drive it LOW. An external pull down resistor is required. Multiple 74x907 outputs can share a wired AND bus line where the line is pulled LOW only when all drivers allow it.',
    pinout: [
      { pin:  1, name: '1A',  type: 'input'  },
      { pin:  2, name: '1Y',  type: 'output' },
      { pin:  3, name: '2A',  type: 'input'  },
      { pin:  4, name: '2Y',  type: 'output' },
      { pin:  5, name: '3A',  type: 'input'  },
      { pin:  6, name: '3Y',  type: 'output' },
      { pin:  7, name: 'GND', type: 'power'  },
      { pin:  8, name: '4Y',  type: 'output' },
      { pin:  9, name: '4A',  type: 'input'  },
      { pin: 10, name: '5Y',  type: 'output' },
      { pin: 11, name: '5A',  type: 'input'  },
      { pin: 12, name: '6Y',  type: 'output' },
      { pin: 13, name: '6A',  type: 'input'  },
      { pin: 14, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'BUFFER', inputs: ['1A'], output: '1Y' },
      { type: 'BUFFER', inputs: ['2A'], output: '2Y' },
      { type: 'BUFFER', inputs: ['3A'], output: '3Y' },
      { type: 'BUFFER', inputs: ['4A'], output: '4Y' },
      { type: 'BUFFER', inputs: ['5A'], output: '5Y' },
      { type: 'BUFFER', inputs: ['6A'], output: '6Y' },
    ],
  },

  // 74908: Dual 2 input NAND 30V/250mA relay driver (8-pin)
  '74908': {
    name: '74x908',
    simpleName: 'Dual 2 Input NAND Relay Driver',
    description: 'Dual 2 input NAND 30V/250mA relay driver (8-pin)',
    pins: 8, vcc: 8, gnd: 4,
    datasheet: '',
    tags: ['nand', 'gate', 'relay', 'driver'],
    guideOverview: 'The 74x908 is a dual 2-input NAND gate with high-voltage (30V) high-current (250mA) output drivers designed to switch relays, solenoids, or other inductive loads directly. Each gate produces a LOW only when both inputs are HIGH. The heavy-duty open-collector outputs replace the need for separate transistor driver stages when controlling electromechanical loads.',
    pinout: [
      { pin: 1, name: '1A',  type: 'input'  },
      { pin: 2, name: '1B',  type: 'input'  },
      { pin: 3, name: '1Y',  type: 'output' },
      { pin: 4, name: 'GND', type: 'power'  },
      { pin: 5, name: '2Y',  type: 'output' },
      { pin: 6, name: '2A',  type: 'input'  },
      { pin: 7, name: '2B',  type: 'input'  },
      { pin: 8, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'NAND', inputs: ['1A','1B'], output: '1Y' },
      { type: 'NAND', inputs: ['2A','2B'], output: '2Y' },
    ],
  },

  // 74909: Quad voltage comparator, analog input, OC output (14-pin)
  '74909': {
    name: '74x909',
    simpleName: 'Quad Voltage Comparator (OC)',
    description: 'Quad voltage comparator with analog inputs and open-collector outputs (14-pin)',
    pins: 14, vcc: 14, gnd: 7,
    openCollector: true,
    datasheet: '',
    tags: ['comparator', 'analog', 'quad', 'open collector', 'stub'],
    guideOverview: 'The 74x909 is a quad voltage comparator with open-collector outputs. Each of the four channels drives its output LOW when the non-inverting input (IN+) is below the inverting input (IN-); otherwise the output is high-impedance. An external pull up resistor is required to pull the output HIGH. Use for threshold detection, window detectors, zero-crossing detection, and interfacing analog signals to digital logic.',
    pinout: [
      { pin:  1, name: '1IN+',type: 'input'  },
      { pin:  2, name: '1IN-',type: 'input'  },
      { pin:  3, name: '1OUT',type: 'output' },
      { pin:  4, name: '2IN+',type: 'input'  },
      { pin:  5, name: '2IN-',type: 'input'  },
      { pin:  6, name: '2OUT',type: 'output' },
      { pin:  7, name: 'GND', type: 'power'  },
      { pin:  8, name: '3OUT',type: 'output' },
      { pin:  9, name: '3IN-',type: 'input'  },
      { pin: 10, name: '3IN+',type: 'input'  },
      { pin: 11, name: '4OUT',type: 'output' },
      { pin: 12, name: '4IN-',type: 'input'  },
      { pin: 13, name: '4IN+',type: 'input'  },
      { pin: 14, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['1IN+','1IN-','2IN+','2IN-','3IN+','3IN-','4IN+','4IN-'], outputs: ['1OUT','2OUT','3OUT','4OUT'] },
    ],
  },

  // 74910: 256 bit RAM (64x4), three-state (18-pin)
  '74910': {
    name: '74x910',
    simpleName: '256 bit RAM 64x4 (TRI)',
    description: '256 bit RAM organized as 64 words x 4 bits with three-state outputs (18-pin)',
    pins: 18, vcc: 18, gnd: 9,
    datasheet: '',
    tags: ['ram', 'memory', '256 bit', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x910 is a 256 bit static RAM organized as 64 words by 4 bits with 3-state outputs. Address inputs A0–A5 select one of 64 word locations. WEn (active LOW) writes the four data bits D0–D3 into the selected location; OEn (active LOW) drives the stored data onto the shared D0–D3 bidirectional pins. When both WEn and OEn are HIGH, outputs are in high impedance for bus sharing.',
    pinout: [
      { pin:  1, name: 'A0',  type: 'input'  },
      { pin:  2, name: 'A1',  type: 'input'  },
      { pin:  3, name: 'A2',  type: 'input'  },
      { pin:  4, name: 'A3',  type: 'input'  },
      { pin:  5, name: 'A4',  type: 'input'  },
      { pin:  6, name: 'A5',  type: 'input'  },
      { pin:  7, name: 'WEn', type: 'input'  },
      { pin:  8, name: 'OEn', type: 'input'  },
      { pin:  9, name: 'GND', type: 'power'  },
      { pin: 10, name: 'D0',  type: 'bidir'  },
      { pin: 11, name: 'D1',  type: 'bidir'  },
      { pin: 12, name: 'D2',  type: 'bidir'  },
      { pin: 13, name: 'D3',  type: 'bidir'  },
      { pin: 14, name: 'NC',  type: 'nc'     },
      { pin: 15, name: 'NC2', type: 'nc'     },
      { pin: 16, name: 'NC3', type: 'nc'     },
      { pin: 17, name: 'NC4', type: 'nc'     },
      { pin: 18, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['A0','A1','A2','A3','A4','A5','WEn','OEn'], outputs: [] },
    ],
  },

  // 74913: 6-digit BCD display controller and driver (24-pin)
  '74913': {
    name: '74x913',
    simpleName: '6-Digit BCD Display Controller',
    description: '6-digit BCD display controller and driver, no decimal point (24-pin)',
    pins: 24, vcc: 24, gnd: 12,
    datasheet: '',
    tags: ['display', 'bcd', '7-segment', 'driver', 'stub'],
    sequential: true,
    guideOverview: 'The 74x913 is a 6-digit BCD display controller and driver. Four-bit BCD digits are loaded serially via D0–D3 and CLK into internal storage registers, latched on LD, and reset on RST. The chip multiplexes 7-segment outputs a–g across the six display positions: DIS sequences through digit-select signals, and COL drives a colon indicator. MSB controls most-significant-digit blanking. Use with a time-multiplexed 7-segment LED display for numeric readouts.',
    pinout: [
      { pin:  1, name: 'D0',   type: 'input'  },
      { pin:  2, name: 'D1',   type: 'input'  },
      { pin:  3, name: 'D2',   type: 'input'  },
      { pin:  4, name: 'D3',   type: 'input'  },
      { pin:  5, name: 'CLK',  type: 'input'  },
      { pin:  6, name: 'LD',   type: 'input'  },
      { pin:  7, name: 'RST',  type: 'input'  },
      { pin:  8, name: 'DIS',  type: 'output' },
      { pin:  9, name: 'a',    type: 'output' },
      { pin: 10, name: 'b',    type: 'output' },
      { pin: 11, name: 'c',    type: 'output' },
      { pin: 12, name: 'GND',  type: 'power'  },
      { pin: 13, name: 'd',    type: 'output' },
      { pin: 14, name: 'e',    type: 'output' },
      { pin: 15, name: 'f',    type: 'output' },
      { pin: 16, name: 'g',    type: 'output' },
      { pin: 17, name: 'MSB',  type: 'input'  },
      { pin: 18, name: 'COL',  type: 'output' },
      { pin: 19, name: 'NC',   type: 'nc'     },
      { pin: 20, name: 'NC2',  type: 'nc'     },
      { pin: 21, name: 'NC3',  type: 'nc'     },
      { pin: 22, name: 'NC4',  type: 'nc'     },
      { pin: 23, name: 'NC5',  type: 'nc'     },
      { pin: 24, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['D0','D1','D2','D3','CLK','LD','RST','MSB'], outputs: ['DIS','a','b','c','d','e','f','g','COL'] },
    ],
  },

  // 74914: Hex inverter gate, Schmitt trigger inputs (14-pin)
  '74914': {
    name: '74x914',
    simpleName: 'Hex Schmitt Trigger Inverter',
    description: 'Hex inverter gate with Schmitt trigger inputs (14-pin)',
    pins: 14, vcc: 14, gnd: 7,
    datasheet: '',
    tags: ['inverter', 'schmitt-trigger', 'hex'],
    guideOverview: 'The 74x914 is a hex Schmitt trigger inverter. Six NOT gates each produce a logic-inverted output, but the inputs use a hysteresis threshold: the output switches HIGH-to-LOW at an upper trigger level and switches back LOW-to-HIGH at a lower level. This prevents chattering and false transitions on slow-slewing, noisy, or bouncing inputs. Drop-in replacement for a standard hex inverter (74x04) when input signal quality is poor.',
    pinout: [
      { pin:  1, name: '1A',  type: 'input'  },
      { pin:  2, name: '1Y',  type: 'output' },
      { pin:  3, name: '2A',  type: 'input'  },
      { pin:  4, name: '2Y',  type: 'output' },
      { pin:  5, name: '3A',  type: 'input'  },
      { pin:  6, name: '3Y',  type: 'output' },
      { pin:  7, name: 'GND', type: 'power'  },
      { pin:  8, name: '4Y',  type: 'output' },
      { pin:  9, name: '4A',  type: 'input'  },
      { pin: 10, name: '5Y',  type: 'output' },
      { pin: 11, name: '5A',  type: 'input'  },
      { pin: 12, name: '6Y',  type: 'output' },
      { pin: 13, name: '6A',  type: 'input'  },
      { pin: 14, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'NOT', inputs: ['1A'], output: '1Y' },
      { type: 'NOT', inputs: ['2A'], output: '2Y' },
      { type: 'NOT', inputs: ['3A'], output: '3Y' },
      { type: 'NOT', inputs: ['4A'], output: '4Y' },
      { type: 'NOT', inputs: ['5A'], output: '5Y' },
      { type: 'NOT', inputs: ['6A'], output: '6Y' },
    ],
  },

  // 74915: 7-segment to BCD converter, TRI (18-pin)
  '74915': {
    name: '74x915',
    simpleName: '7-Segment to BCD Converter (TRI)',
    description: '7-segment to BCD converter with three-state outputs (18-pin)',
    pins: 18, vcc: 18, gnd: 9,
    datasheet: '',
    tags: ['decoder', '7-segment', 'bcd', 'tri-state', 'stub'],
    guideOverview: 'The 74x915 is a 7-segment to BCD converter with 3-state outputs. It decodes the seven segment inputs a–g of an active 7-segment display back into a 4 bit BCD code (Q0–Q3). An INV (invalid) output goes HIGH when the segment pattern does not match any valid BCD digit (0–9). OEn (active LOW) enables the 3-state output drivers. Use to read back the state of a 7-segment display from its segment lines, for example in a system that monitors display content without separate digit registers.',
    pinout: [
      { pin:  1, name: 'a',    type: 'input'  },
      { pin:  2, name: 'b',    type: 'input'  },
      { pin:  3, name: 'c',    type: 'input'  },
      { pin:  4, name: 'd',    type: 'input'  },
      { pin:  5, name: 'e',    type: 'input'  },
      { pin:  6, name: 'f',    type: 'input'  },
      { pin:  7, name: 'g',    type: 'input'  },
      { pin:  8, name: 'OEn',  type: 'input'  },
      { pin:  9, name: 'GND',  type: 'power'  },
      { pin: 10, name: 'Q0',   type: 'output' },
      { pin: 11, name: 'Q1',   type: 'output' },
      { pin: 12, name: 'Q2',   type: 'output' },
      { pin: 13, name: 'Q3',   type: 'output' },
      { pin: 14, name: 'INV',  type: 'output' },
      { pin: 15, name: 'NC',   type: 'nc'     },
      { pin: 16, name: 'NC2',  type: 'nc'     },
      { pin: 17, name: 'NC3',  type: 'nc'     },
      { pin: 18, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['a','b','c','d','e','f','g','OEn'], outputs: ['Q0','Q1','Q2','Q3','INV'] },
    ],
  },

  // 74918: Dual 2 input NAND 30V/250mA relay driver (14-pin)
  '74918': {
    name: '74x918',
    simpleName: 'Dual 2 Input NAND Relay Driver (14-pin)',
    description: 'Dual 2 input NAND 30V/250mA relay driver (14-pin)',
    pins: 14, vcc: 14, gnd: 7,
    datasheet: '',
    tags: ['nand', 'gate', 'relay', 'driver'],
    guideOverview: 'The 74x918 is the 14-pin version of the 74x908 — a dual 2-input NAND gate with 30V/250mA high-current output drivers for relay and solenoid switching. Each gate produces LOW only when both inputs are HIGH. The extra pins are NC (no connection), providing standard 14-pin DIP form factor for more convenient board layout. Electrically identical to the 74x908.',
    pinout: [
      { pin:  5, name: 'NC2', type: 'nc'     },
      { pin:  6, name: '2A',  type: 'input'  },
      { pin:  7, name: 'GND', type: 'power'  },
      { pin:  8, name: '2B',  type: 'input'  },
      { pin:  9, name: 'NC3', type: 'nc'     },
      { pin: 10, name: 'NC4', type: 'nc'     },
      { pin: 11, name: '2Y',  type: 'output' },
      { pin: 12, name: 'NC5', type: 'nc'     },
      { pin: 13, name: 'NC6', type: 'nc'     },
      { pin: 14, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'NAND', inputs: ['1A','1B'], output: '1Y' },
      { type: 'NAND', inputs: ['2A','2B'], output: '2Y' },
    ],
  },

  // 74920: 1024 bit RAM (256x4), TRI, separate I/O (22-pin)
  '74920': {
    name: '74x920',
    simpleName: '1024 bit RAM 256x4 (TRI, Sep I/O)',
    description: '1024 bit RAM organized as 256 words x 4 bits with three-state outputs and separate data inputs and outputs (22-pin)',
    pins: 22, vcc: 22, gnd: 12,
    datasheet: '',
    tags: ['ram', 'memory', '1024 bit', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x920 is a 1024 bit static RAM organized as 256 words by 4 bits with 3-state outputs and separate data input (DI0–DI3) and output (DO0–DO3) pins. Address inputs A0–A7 select one of 256 locations. WEn (active LOW) writes the DI inputs into the addressed location; OEn (active LOW) enables the DO outputs; CSn (chip select, active LOW) enables the device. Separate I/O pins prevent bus contention and allow simultaneous data setup and readback.',
    pinout: [
      { pin:  1, name: 'A0',  type: 'input'  },
      { pin:  2, name: 'A1',  type: 'input'  },
      { pin:  3, name: 'A2',  type: 'input'  },
      { pin:  4, name: 'A3',  type: 'input'  },
      { pin:  5, name: 'A4',  type: 'input'  },
      { pin:  6, name: 'A5',  type: 'input'  },
      { pin:  7, name: 'A6',  type: 'input'  },
      { pin:  8, name: 'A7',  type: 'input'  },
      { pin:  9, name: 'WEn', type: 'input'  },
      { pin: 10, name: 'OEn', type: 'input'  },
      { pin: 11, name: 'CSn', type: 'input'  },
      { pin: 12, name: 'GND', type: 'power'  },
      { pin: 13, name: 'DI0', type: 'input'  },
      { pin: 14, name: 'DI1', type: 'input'  },
      { pin: 15, name: 'DI2', type: 'input'  },
      { pin: 16, name: 'DI3', type: 'input'  },
      { pin: 17, name: 'DO0', type: 'output' },
      { pin: 18, name: 'DO1', type: 'output' },
      { pin: 19, name: 'DO2', type: 'output' },
      { pin: 20, name: 'DO3', type: 'output' },
      { pin: 21, name: 'NC',  type: 'nc'     },
      { pin: 22, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['A0','A1','A2','A3','A4','A5','A6','A7','WEn','OEn','CSn','DI0','DI1','DI2','DI3'], outputs: ['DO0','DO1','DO2','DO3'] },
    ],
  },

  // 74921: 1024 bit RAM (256x4), TRI (18-pin)
  '74921': {
    name: '74x921',
    simpleName: '1024 bit RAM 256x4 (TRI)',
    description: '1024 bit RAM organized as 256 words x 4 bits with three-state outputs (18-pin)',
    pins: 18, vcc: 18, gnd: 9,
    datasheet: '',
    tags: ['ram', 'memory', '1024 bit', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x921 is a 1024 bit static RAM organized as 256 words by 4 bits with 3-state outputs and common bidirectional data pins D0–D3. Address inputs A0–A7 select one of 256 memory locations. WEn (active LOW) writes the data present on D0–D3 into the addressed word; OEn (active LOW) drives the stored data onto the D0–D3 pins. Compared to the 74x920, the shared I/O pins reduce pin count but require careful bus management to avoid write/read contention.',
    pinout: [
      { pin:  1, name: 'A0',  type: 'input'  },
      { pin:  2, name: 'A1',  type: 'input'  },
      { pin:  3, name: 'A2',  type: 'input'  },
      { pin:  4, name: 'A3',  type: 'input'  },
      { pin:  5, name: 'A4',  type: 'input'  },
      { pin:  6, name: 'A5',  type: 'input'  },
      { pin:  7, name: 'A6',  type: 'input'  },
      { pin:  8, name: 'A7',  type: 'input'  },
      { pin:  9, name: 'GND', type: 'power'  },
      { pin: 10, name: 'WEn', type: 'input'  },
      { pin: 11, name: 'OEn', type: 'input'  },
      { pin: 12, name: 'D0',  type: 'bidir'  },
      { pin: 13, name: 'D1',  type: 'bidir'  },
      { pin: 14, name: 'D2',  type: 'bidir'  },
      { pin: 15, name: 'D3',  type: 'bidir'  },
      { pin: 16, name: 'NC',  type: 'nc'     },
      { pin: 17, name: 'NC2', type: 'nc'     },
      { pin: 18, name: 'VCC', type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['A0','A1','A2','A3','A4','A5','A6','A7','WEn','OEn'], outputs: [] },
    ],
  },

  // 74922: 16-key encoder, TRI (18-pin)
  '74922': {
    name: '74x922',
    simpleName: '16-Key Encoder (TRI)',
    description: '16-key encoder with three-state outputs (18-pin)',
    pins: 18, vcc: 18, gnd: 9,
    datasheet: '',
    tags: ['encoder', 'keyboard', '16-key', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x922 is a 16-key keyboard encoder with 3-state outputs. It scans a 4×4 key matrix by cycling column drive outputs C1–C4 and reading row inputs R1–R4. When a key is pressed it debounces, encodes the position as a 4 bit code on outputs A–D, and asserts DA (data available) HIGH. OEn (active LOW) enables the 3-state code outputs. KBM selects keyboard-matrix mode; OSC accepts an external clock to set the debounce timing period.',
    pinout: [
      { pin:  1, name: 'R1',   type: 'input'  },
      { pin:  2, name: 'R2',   type: 'input'  },
      { pin:  3, name: 'R3',   type: 'input'  },
      { pin:  4, name: 'R4',   type: 'input'  },
      { pin:  5, name: 'C1',   type: 'output' },
      { pin:  6, name: 'C2',   type: 'output' },
      { pin:  7, name: 'C3',   type: 'output' },
      { pin:  8, name: 'C4',   type: 'output' },
      { pin:  9, name: 'GND',  type: 'power'  },
      { pin: 10, name: 'OEn',  type: 'input'  },
      { pin: 11, name: 'DA',   type: 'output' },
      { pin: 12, name: 'A',    type: 'output' },
      { pin: 13, name: 'B',    type: 'output' },
      { pin: 14, name: 'C',    type: 'output' },
      { pin: 15, name: 'D',    type: 'output' },
      { pin: 16, name: 'KBM',  type: 'input'  },
      { pin: 17, name: 'OSC',  type: 'input'  },
      { pin: 18, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['R1','R2','R3','R4','OEn','KBM','OSC'], outputs: ['C1','C2','C3','C4','DA','A','B','C','D'] },
    ],
  },

  // 74923: 20-key encoder, TRI (20-pin)
  '74923': {
    name: '74x923',
    simpleName: '20-Key Encoder (TRI)',
    description: '20-key encoder with three-state outputs (20-pin)',
    pins: 20, vcc: 20, gnd: 10,
    datasheet: '',
    tags: ['encoder', 'keyboard', '20-key', 'tri-state', 'stub'],
    sequential: true,
    guideOverview: 'The 74x923 is a 20-key keyboard encoder with 3-state outputs. It scans a 4×5 key matrix: four column drives C1–C4 and five row inputs R1–R5. A key press produces a 5 bit code on outputs A–E, with DA (data available) indicating a valid keypress. OEn (active LOW) enables the 3-state outputs. KBM and OSC control debounce mode and timing. Handles larger keypad matrices than the 16-key 74x922.',
    pinout: [
      { pin:  1, name: 'R1',   type: 'input'  },
      { pin:  2, name: 'R2',   type: 'input'  },
      { pin:  3, name: 'R3',   type: 'input'  },
      { pin:  4, name: 'R4',   type: 'input'  },
      { pin:  5, name: 'R5',   type: 'input'  },
      { pin:  6, name: 'C1',   type: 'output' },
      { pin:  7, name: 'C2',   type: 'output' },
      { pin:  8, name: 'C3',   type: 'output' },
      { pin:  9, name: 'C4',   type: 'output' },
      { pin: 10, name: 'GND',  type: 'power'  },
      { pin: 11, name: 'OEn',  type: 'input'  },
      { pin: 12, name: 'DA',   type: 'output' },
      { pin: 13, name: 'A',    type: 'output' },
      { pin: 14, name: 'B',    type: 'output' },
      { pin: 15, name: 'C',    type: 'output' },
      { pin: 16, name: 'D',    type: 'output' },
      { pin: 17, name: 'E',    type: 'output' },
      { pin: 18, name: 'KBM',  type: 'input'  },
      { pin: 19, name: 'OSC',  type: 'input'  },
      { pin: 20, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['R1','R2','R3','R4','R5','OEn','KBM','OSC'], outputs: ['C1','C2','C3','C4','DA','A','B','C','D','E'] },
    ],
  },

  // 74925: 4-digit decade counter/display driver (16-pin)
  '74925': {
    name: '74x925',
    simpleName: '4-Digit Counter/Display Driver',
    description: '4-digit counter/display driver (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    datasheet: '',
    tags: ['counter', 'display', 'driver', '4-digit', 'stub'],
    sequential: true,
    guideOverview: 'The 74x925 is a 4-digit counter and display driver. CLK increments an internal BCD counter; RST resets it to zero; LE (latch enable) captures the current count into an output register for stable display. The chip multiplexes 7-segment outputs a–g across the four digit positions using digit select signals D1–D4. Connect to a multiplexed 4-digit 7-segment LED display to show counts from 0000 to 9999.',
    pinout: [
      { pin:  1, name: 'CLK',  type: 'input'  },
      { pin:  2, name: 'RST',  type: 'input'  },
      { pin:  3, name: 'LE',   type: 'input'  },
      { pin:  4, name: 'a',    type: 'output' },
      { pin:  5, name: 'b',    type: 'output' },
      { pin:  6, name: 'c',    type: 'output' },
      { pin:  7, name: 'd',    type: 'output' },
      { pin:  8, name: 'GND',  type: 'power'  },
      { pin:  9, name: 'e',    type: 'output' },
      { pin: 10, name: 'f',    type: 'output' },
      { pin: 11, name: 'g',    type: 'output' },
      { pin: 12, name: 'D1',   type: 'output' },
      { pin: 13, name: 'D2',   type: 'output' },
      { pin: 14, name: 'D3',   type: 'output' },
      { pin: 15, name: 'D4',   type: 'output' },
      { pin: 16, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['CLK','RST','LE'], outputs: ['a','b','c','d','e','f','g','D1','D2','D3','D4'] },
    ],
  },

  // 74926: 4-digit decade counter/display driver with carry out and latch (16-pin)
  '74926': {
    name: '74x926',
    simpleName: '4-Digit Decade Counter/Display Driver',
    description: '4-digit decade counter/display driver with carry out and latch (up to 9999) (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    datasheet: '',
    tags: ['counter', 'display', 'driver', '4-digit', 'decade', 'stub'],
    sequential: true,
    guideOverview: 'The 74x926 is a 4-digit decade counter and display driver with carry-out, counting up to 9999. CLK increments the BCD decade counter; RST resets; LE latches the count for stable 7-segment display output. The chip drives 7-segment outputs a–g and digit select lines D1–D4 for a multiplexed display. The carry output allows chaining multiple chips for wider count ranges. This is essentially a 74x925 with an added carry flag for cascading.',
    pinout: [
      { pin:  1, name: 'CLK',  type: 'input'  },
      { pin:  2, name: 'RST',  type: 'input'  },
      { pin:  3, name: 'LE',   type: 'input'  },
      { pin:  4, name: 'a',    type: 'output' },
      { pin:  5, name: 'b',    type: 'output' },
      { pin:  6, name: 'c',    type: 'output' },
      { pin:  7, name: 'd',    type: 'output' },
      { pin:  8, name: 'GND',  type: 'power'  },
      { pin:  9, name: 'e',    type: 'output' },
      { pin: 10, name: 'f',    type: 'output' },
      { pin: 11, name: 'g',    type: 'output' },
      { pin: 12, name: 'D1',   type: 'output' },
      { pin: 13, name: 'D2',   type: 'output' },
      { pin: 14, name: 'D3',   type: 'output' },
      { pin: 15, name: 'D4',   type: 'output' },
      { pin: 16, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['CLK','RST','LE'], outputs: ['a','b','c','d','e','f','g','D1','D2','D3','D4'] },
    ],
  },

  // 74927: 4-digit timer counter/display driver (16-pin)
  '74927': {
    name: '74x927',
    simpleName: '4-Digit Timer Counter/Display Driver',
    description: '4-digit timer counter/display driver (up to 9:59.9 min) (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    datasheet: '',
    tags: ['counter', 'display', 'driver', '4-digit', 'timer', 'stub'],
    sequential: true,
    guideOverview: 'The 74x927 is a 4-digit timer counter and display driver formatted for minute:second.tenth-of-second timing (up to 9:59.9). With a 100ms external clock on CLK, the chip counts tenths of seconds and handles rollover at 10 tenths per second, 60 seconds per minute, and the minutes digit. RST resets; LE latches for a stable display. Outputs a–g drive 7-segment segments and D1–D4 select the active digit for a multiplexed 4-digit display.',
    pinout: [
      { pin:  1, name: 'CLK',  type: 'input'  },
      { pin:  2, name: 'RST',  type: 'input'  },
      { pin:  3, name: 'LE',   type: 'input'  },
      { pin:  4, name: 'a',    type: 'output' },
      { pin:  5, name: 'b',    type: 'output' },
      { pin:  6, name: 'c',    type: 'output' },
      { pin:  7, name: 'd',    type: 'output' },
      { pin:  8, name: 'GND',  type: 'power'  },
      { pin:  9, name: 'e',    type: 'output' },
      { pin: 10, name: 'f',    type: 'output' },
      { pin: 11, name: 'g',    type: 'output' },
      { pin: 12, name: 'D1',   type: 'output' },
      { pin: 13, name: 'D2',   type: 'output' },
      { pin: 14, name: 'D3',   type: 'output' },
      { pin: 15, name: 'D4',   type: 'output' },
      { pin: 16, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['CLK','RST','LE'], outputs: ['a','b','c','d','e','f','g','D1','D2','D3','D4'] },
    ],
  },

  // 74928: 4-digit counter/display driver (up to 1999) (16-pin)
  '74928': {
    name: '74x928',
    simpleName: '4-Digit Counter/Display Driver (1999)',
    description: '4-digit counter/display driver (up to 1999) (16-pin)',
    pins: 16, vcc: 16, gnd: 8,
    datasheet: '',
    tags: ['counter', 'display', 'driver', '4-digit', 'stub'],
    sequential: true,
    guideOverview: 'The 74x928 is a 4-digit counter and display driver for count ranges up to 1999, where the most significant digit is limited to "0" or "1". CLK increments the BCD counter; RST resets; LE latches the count for stable display. Outputs a\u2013g drive 7-segment segments and D1\u2013D4 select the active digit for a multiplexed 4-digit display. Use in measurement applications where the maximum reading is 1999, such as millivolt meters or pulse counters.',
    pinout: [
      { pin:  1, name: 'CLK',  type: 'input'  },
      { pin:  2, name: 'RST',  type: 'input'  },
      { pin:  3, name: 'LE',   type: 'input'  },
      { pin:  4, name: 'a',    type: 'output' },
      { pin:  5, name: 'b',    type: 'output' },
      { pin:  6, name: 'c',    type: 'output' },
      { pin:  7, name: 'd',    type: 'output' },
      { pin:  8, name: 'GND',  type: 'power'  },
      { pin:  9, name: 'e',    type: 'output' },
      { pin: 10, name: 'f',    type: 'output' },
      { pin: 11, name: 'g',    type: 'output' },
      { pin: 12, name: 'D1',   type: 'output' },
      { pin: 13, name: 'D2',   type: 'output' },
      { pin: 14, name: 'D3',   type: 'output' },
      { pin: 15, name: 'D4',   type: 'output' },
      { pin: 16, name: 'VCC',  type: 'power'  },
    ],
    gates: [
      { type: 'GENERIC_STUB', inputs: ['CLK','RST','LE'], outputs: ['a','b','c','d','e','f','g','D1','D2','D3','D4'] },
    ],
  },
};