// chips33.js Chip Block 33
// 74615, 74620-623, 74624-629, 74636-637, 74638-640
//
// Transceivers (non-registered):
//   74620   octal transceiver, inverting, TRI         → new TRANSCEIVER_8BIT_INV
//   74621   octal transceiver, non-inverting, OC      → reuse TRANSCEIVER_8BIT
//   74622   octal transceiver, inverting, OC          → reuse TRANSCEIVER_8BIT_INV
//   74623   octal transceiver, non-inverting, TRI     → reuse TRANSCEIVER_8BIT
//   74638   octal transceiver, inverting, TRI+OC      → reuse TRANSCEIVER_8BIT_INV
//   74639   octal transceiver, non-inverting, TRI+OC  → reuse TRANSCEIVER_8BIT
//   74640   octal transceiver, inverting, TRI         → reuse TRANSCEIVER_8BIT_INV
//
// Registered transceiver:
//   74615   octal transceiver + register, non-inverting, OC → reuse TRANSCEIVER_OCTAL_REG
//
// VCO stubs (analog not simulatable): 74624-629
// ECC stubs:  74636-637

export const CHIPS_BLOCK_33 = {

  // ── 74615: Octal registered bus transceiver, non-inverting, OC ──────────
  /* Primary source: Texas Instruments, 74615 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74als615.pdf
     https://en.wikipedia.org/wiki/Bus_transceiver */
  // Like 74543 (TRANSCEIVER_OCTAL_REG). OC vs TRI not distinguished in sim.
  '74615': {
    name: '74x615',
    simpleName: 'Octal Reg Xcvr (OC)',
    description: 'Octal bus transceiver and register with non-inverting outputs (open-collector) (24-pin)',
    pins: 24,
    vcc: 24,
    gnd: 12,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74als615.pdf',
    tags: ['transceiver', 'registered', 'bidirectional', 'octal', 'open-collector'],
    guideOverview: 'The 74x615 is an octal registered bidirectional transceiver with non-inverting open-collector outputs. It is the OC version of the 74x543. LEAB/LEBA are latch enables, CLK registers the output, and DIR/OEABn/OEBAn control direction and drive. Open-collector outputs require external pull ups.',
    guidePinDescriptions: {
      'OEABn': 'A-to-B Output Enable (active LOW).',
      'OEBAn': 'B-to-A Output Enable (active LOW).',
      'LEAB':  'Latch Enable A-to-B.',
      'LEBA':  'Latch Enable B-to-A.',
      'CLK':   'Register clock.',
      'DIR':   'Direction select.',
      'A0':    'Port A bit 0.',
      'A1':    'Port A bit 1.',
      'A2':    'Port A bit 2.',
      'A3':    'Port A bit 3.',
      'A4':    'Port A bit 4.',
      'GND':   'Ground reference (pin 12).',
      'A5':    'Port A bit 5.',
      'A6':    'Port A bit 6.',
      'A7':    'Port A bit 7.',
      'B0':    'Port B bit 0.',
      'B1':    'Port B bit 1.',
      'B2':    'Port B bit 2.',
      'B3':    'Port B bit 3.',
      'B4':    'Port B bit 4.',
      'B5':    'Port B bit 5.',
      'B6':    'Port B bit 6.',
      'B7':    'Port B bit 7.',
      'VCC':   'Positive supply (+5 V, pin 24).',
    },
    guideSections: [
      {
        title: '74x543 vs 74x615',
        paragraphs: [
          '74x543 has tri-state outputs; 74x615 has open-collector. Both are non-inverting registered transceivers with the same control structure.',
        ],
        note: 'External pull up resistors required on all A/B port pins.',
      },
    ],
    pinout: [
      { pin: 1,  name: 'OEABn', type: 'input' },
      { pin: 2,  name: 'OEBAn', type: 'input' },
      { pin: 3,  name: 'LEAB',  type: 'input' },
      { pin: 4,  name: 'LEBA',  type: 'input' },
      { pin: 5,  name: 'CLK',   type: 'input' },
      { pin: 6,  name: 'DIR',   type: 'input' },
      { pin: 7,  name: 'A0',    type: 'io' },
      { pin: 8,  name: 'A1',    type: 'io' },
      { pin: 9,  name: 'A2',    type: 'io' },
      { pin: 10, name: 'A3',    type: 'io' },
      { pin: 11, name: 'A4',    type: 'io' },
      { pin: 12, name: 'GND',   type: 'power' },
      { pin: 13, name: 'A5',    type: 'io' },
      { pin: 14, name: 'A6',    type: 'io' },
      { pin: 15, name: 'A7',    type: 'io' },
      { pin: 16, name: 'B0',    type: 'io' },
      { pin: 17, name: 'B1',    type: 'io' },
      { pin: 18, name: 'B2',    type: 'io' },
      { pin: 19, name: 'B3',    type: 'io' },
      { pin: 20, name: 'B4',    type: 'io' },
      { pin: 21, name: 'B5',    type: 'io' },
      { pin: 22, name: 'B6',    type: 'io' },
      { pin: 23, name: 'B7',    type: 'io' },
      { pin: 24, name: 'VCC',   type: 'power' },
    ],
    gates: [
      { type: 'TRANSCEIVER_OCTAL_REG',
        inputs:  ['OEABn', 'OEBAn', 'LEAB', 'LEBA', 'CLK', 'DIR',
                  'A0', 'A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7',
                  'B0', 'B1', 'B2', 'B3', 'B4', 'B5', 'B6', 'B7'],
        outputs: ['A0', 'A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7',
                  'B0', 'B1', 'B2', 'B3', 'B4', 'B5', 'B6', 'B7'] },
    ],
    sequential: true,
  },

  // ── 74620: Octal bus transceiver, inverting, TRI ──────────────────────────
  /* Primary source: Texas Instruments, 74620 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls620.pdf
     https://en.wikipedia.org/wiki/Bus_transceiver */
  // Like 74245 but all data is inverted on output.
  // OEn=0: enabled. DIR=1: A→/B. DIR=0: B→/A.
  '74620': {
    name: '74x620',
    simpleName: 'Octal Xcvr Inv (TS)',
    description: 'Octal bus transceiver with inverting tri-state outputs (20-pin)',
    pins: 20,
    vcc: 20,
    gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls620.pdf',
    tags: ['transceiver', 'bus', 'octal', 'tri-state', 'bidirectional', 'inverting'],
    guideOverview: 'The 74x620 is an 8 bit bidirectional inverting bus transceiver with tri-state outputs. DIR HIGH routes A to inverted B; DIR LOW routes B to inverted A. OE (active LOW) enables the drive. It is the inverting-output complement of the 74x245.',
    guidePinDescriptions: {
      'DIR': 'Direction. HIGH = A drives inverted B; LOW = B drives inverted A.',
      'A1':  'Port A bit 1.',
      'A2':  'Port A bit 2.',
      'A3':  'Port A bit 3.',
      'A4':  'Port A bit 4.',
      'A5':  'Port A bit 5.',
      'A6':  'Port A bit 6.',
      'A7':  'Port A bit 7.',
      'A8':  'Port A bit 8.',
      'GND': 'Ground reference (pin 10).',
      'B8':  'Port B bit 8.',
      'B7':  'Port B bit 7.',
      'B6':  'Port B bit 6.',
      'B5':  'Port B bit 5.',
      'B4':  'Port B bit 4.',
      'B3':  'Port B bit 3.',
      'B2':  'Port B bit 2.',
      'B1':  'Port B bit 1.',
      'OEn': 'Output Enable (active LOW).',
      'VCC': 'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'Inverting Bidirectional Transceiver',
        paragraphs: [
          'Use the 74x620 when the receiving bus uses complemented active LOW logic, saving an inverter layer after the transceiver.',
        ],
      },
    ],
    pinout: [
      { pin: 1,  name: 'DIR', type: 'input' },
      { pin: 2,  name: 'A1',  type: 'io' },
      { pin: 3,  name: 'A2',  type: 'io' },
      { pin: 4,  name: 'A3',  type: 'io' },
      { pin: 5,  name: 'A4',  type: 'io' },
      { pin: 6,  name: 'A5',  type: 'io' },
      { pin: 7,  name: 'A6',  type: 'io' },
      { pin: 8,  name: 'A7',  type: 'io' },
      { pin: 9,  name: 'A8',  type: 'io' },
      { pin: 10, name: 'GND', type: 'power' },
      { pin: 11, name: 'B8',  type: 'io' },
      { pin: 12, name: 'B7',  type: 'io' },
      { pin: 13, name: 'B6',  type: 'io' },
      { pin: 14, name: 'B5',  type: 'io' },
      { pin: 15, name: 'B4',  type: 'io' },
      { pin: 16, name: 'B3',  type: 'io' },
      { pin: 17, name: 'B2',  type: 'io' },
      { pin: 18, name: 'B1',  type: 'io' },
      { pin: 19, name: 'OEn', type: 'input' },
      { pin: 20, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'TRANSCEIVER_8BIT_INV',
        inputs:  ['A1','A2','A3','A4','A5','A6','A7','A8',
                  'B1','B2','B3','B4','B5','B6','B7','B8','DIR','OEn'],
        outputs: ['A1','A2','A3','A4','A5','A6','A7','A8',
                  'B1','B2','B3','B4','B5','B6','B7','B8'] },
    ],
  },

  // ── 74621: Octal bus transceiver, non-inverting, OC ──────────────────────
  /* Primary source: Texas Instruments, 74621 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls621.pdf
     https://en.wikipedia.org/wiki/Bus_transceiver */
  // Same function as 74245 (non-inverting, same pinout), but OC outputs.
  '74621': {
    name: '74x621',
    simpleName: 'Octal Xcvr (OC)',
    description: 'Octal bus transceiver with non-inverting outputs (open-collector) (20-pin)',
    pins: 20,
    vcc: 20,
    gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls621.pdf',
    tags: ['transceiver', 'bus', 'octal', 'open-collector', 'bidirectional'],
    guideOverview: 'The 74x621 is an 8 bit bidirectional non-inverting bus transceiver with open-collector outputs. Same DIR/OE (active LOW) interface as the 74x245 but with OC outputs requiring external pull ups. Useful for wire-OR bus sharing or driving optocouplers.',
    guidePinDescriptions: {
      'DIR': 'Direction. HIGH = A drives B; LOW = B drives A.',
      'A1':  'Port A bit 1.',
      'A2':  'Port A bit 2.',
      'A3':  'Port A bit 3.',
      'A4':  'Port A bit 4.',
      'A5':  'Port A bit 5.',
      'A6':  'Port A bit 6.',
      'A7':  'Port A bit 7.',
      'A8':  'Port A bit 8.',
      'GND': 'Ground reference (pin 10).',
      'B8':  'Port B bit 8.',
      'B7':  'Port B bit 7.',
      'B6':  'Port B bit 6.',
      'B5':  'Port B bit 5.',
      'B4':  'Port B bit 4.',
      'B3':  'Port B bit 3.',
      'B2':  'Port B bit 2.',
      'B1':  'Port B bit 1.',
      'OEn': 'Output Enable (active LOW).',
      'VCC': 'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'OC Bidirectional Transceiver',
        paragraphs: [
          'Open-collector enables multiple 74x621s to share the same bus lines via wired AND. External pull up resistors (1-4.7 kΩ) are required.',
        ],
      },
    ],
    pinout: [
      { pin: 1,  name: 'DIR', type: 'input' },
      { pin: 2,  name: 'A1',  type: 'io' },
      { pin: 3,  name: 'A2',  type: 'io' },
      { pin: 4,  name: 'A3',  type: 'io' },
      { pin: 5,  name: 'A4',  type: 'io' },
      { pin: 6,  name: 'A5',  type: 'io' },
      { pin: 7,  name: 'A6',  type: 'io' },
      { pin: 8,  name: 'A7',  type: 'io' },
      { pin: 9,  name: 'A8',  type: 'io' },
      { pin: 10, name: 'GND', type: 'power' },
      { pin: 11, name: 'B8',  type: 'io' },
      { pin: 12, name: 'B7',  type: 'io' },
      { pin: 13, name: 'B6',  type: 'io' },
      { pin: 14, name: 'B5',  type: 'io' },
      { pin: 15, name: 'B4',  type: 'io' },
      { pin: 16, name: 'B3',  type: 'io' },
      { pin: 17, name: 'B2',  type: 'io' },
      { pin: 18, name: 'B1',  type: 'io' },
      { pin: 19, name: 'OEn', type: 'input' },
      { pin: 20, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'TRANSCEIVER_8BIT',
        inputs:  ['A1','A2','A3','A4','A5','A6','A7','A8',
                  'B1','B2','B3','B4','B5','B6','B7','B8','DIR','OEn'],
        outputs: ['A1','A2','A3','A4','A5','A6','A7','A8',
                  'B1','B2','B3','B4','B5','B6','B7','B8'] },
    ],
  },

  // ── 74622: Octal bus transceiver, inverting, OC ──────────────────────────
  /* Primary source: Texas Instruments, 74622 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls622.pdf
     https://en.wikipedia.org/wiki/Bus_transceiver */
  '74622': {
    name: '74x622',
    simpleName: 'Octal Xcvr Inv (OC)',
    description: 'Octal bus transceiver with inverting outputs (open-collector) (20-pin)',
    pins: 20,
    vcc: 20,
    gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls622.pdf',
    tags: ['transceiver', 'bus', 'octal', 'open-collector', 'bidirectional', 'inverting'],
    guideOverview: 'The 74x622 is an 8 bit bidirectional inverting bus transceiver with open-collector outputs. It is the OC version of the 74x620. All data is inverted through the transceiver; external pull ups required.',
    guidePinDescriptions: {
      'DIR': 'Direction. HIGH = A drives inverted B; LOW = B drives inverted A.',
      'A1':  'Port A bit 1.',
      'A2':  'Port A bit 2.',
      'A3':  'Port A bit 3.',
      'A4':  'Port A bit 4.',
      'A5':  'Port A bit 5.',
      'A6':  'Port A bit 6.',
      'A7':  'Port A bit 7.',
      'A8':  'Port A bit 8.',
      'GND': 'Ground reference (pin 10).',
      'B8':  'Port B bit 8.',
      'B7':  'Port B bit 7.',
      'B6':  'Port B bit 6.',
      'B5':  'Port B bit 5.',
      'B4':  'Port B bit 4.',
      'B3':  'Port B bit 3.',
      'B2':  'Port B bit 2.',
      'B1':  'Port B bit 1.',
      'OEn': 'Output Enable (active LOW).',
      'VCC': 'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: '74x620/621/622/623 Family',
        list: [
          '74x620: TRI outputs, inverting',
          '74x621: OC outputs, non-inverting',
          '74x622: OC outputs, inverting',
          '74x623: TRI outputs, non-inverting',
        ],
      },
    ],
    pinout: [
      { pin: 1,  name: 'DIR', type: 'input' },
      { pin: 2,  name: 'A1',  type: 'io' },
      { pin: 3,  name: 'A2',  type: 'io' },
      { pin: 4,  name: 'A3',  type: 'io' },
      { pin: 5,  name: 'A4',  type: 'io' },
      { pin: 6,  name: 'A5',  type: 'io' },
      { pin: 7,  name: 'A6',  type: 'io' },
      { pin: 8,  name: 'A7',  type: 'io' },
      { pin: 9,  name: 'A8',  type: 'io' },
      { pin: 10, name: 'GND', type: 'power' },
      { pin: 11, name: 'B8',  type: 'io' },
      { pin: 12, name: 'B7',  type: 'io' },
      { pin: 13, name: 'B6',  type: 'io' },
      { pin: 14, name: 'B5',  type: 'io' },
      { pin: 15, name: 'B4',  type: 'io' },
      { pin: 16, name: 'B3',  type: 'io' },
      { pin: 17, name: 'B2',  type: 'io' },
      { pin: 18, name: 'B1',  type: 'io' },
      { pin: 19, name: 'OEn', type: 'input' },
      { pin: 20, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'TRANSCEIVER_8BIT_INV',
        inputs:  ['A1','A2','A3','A4','A5','A6','A7','A8',
                  'B1','B2','B3','B4','B5','B6','B7','B8','DIR','OEn'],
        outputs: ['A1','A2','A3','A4','A5','A6','A7','A8',
                  'B1','B2','B3','B4','B5','B6','B7','B8'] },
    ],
  },

  // ── 74623: Octal bus transceiver, non-inverting, TRI ─────────────────────
  /* Primary source: Texas Instruments, 74623 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls623.pdf
     https://en.wikipedia.org/wiki/Bus_transceiver */
  // Same as 74245. Reuse TRANSCEIVER_8BIT.
  '74623': {
    name: '74x623',
    simpleName: 'Octal Xcvr (TS)',
    description: 'Octal bus transceiver with non-inverting tri-state outputs (20-pin)',
    pins: 20,
    vcc: 20,
    gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls623.pdf',
    tags: ['transceiver', 'bus', 'octal', 'tri-state', 'bidirectional'],
    guideOverview: 'The 74x623 is an 8 bit bidirectional non-inverting bus transceiver with tri-state outputs, functionally equivalent to the 74x245. DIR controls direction; OE (active LOW) enables the outputs. A pin-for-pin compatible replacement for 74x245 in many designs.',
    guidePinDescriptions: {
      'DIR': 'Direction. HIGH = A drives B; LOW = B drives A.',
      'A1':  'Port A bit 1.',
      'A2':  'Port A bit 2.',
      'A3':  'Port A bit 3.',
      'A4':  'Port A bit 4.',
      'A5':  'Port A bit 5.',
      'A6':  'Port A bit 6.',
      'A7':  'Port A bit 7.',
      'A8':  'Port A bit 8.',
      'GND': 'Ground reference (pin 10).',
      'B8':  'Port B bit 8.',
      'B7':  'Port B bit 7.',
      'B6':  'Port B bit 6.',
      'B5':  'Port B bit 5.',
      'B4':  'Port B bit 4.',
      'B3':  'Port B bit 3.',
      'B2':  'Port B bit 2.',
      'B1':  'Port B bit 1.',
      'OEn': 'Output Enable (active LOW).',
      'VCC': 'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'Non-Inverting Transceiver',
        paragraphs: [
          'Functionally the same as the 74x245 the standard bidirectional bus transceiver. Select 74x623 vs 74x245 based on logic family speed or availability.',
        ],
      },
    ],
    pinout: [
      { pin: 1,  name: 'DIR', type: 'input' },
      { pin: 2,  name: 'A1',  type: 'io' },
      { pin: 3,  name: 'A2',  type: 'io' },
      { pin: 4,  name: 'A3',  type: 'io' },
      { pin: 5,  name: 'A4',  type: 'io' },
      { pin: 6,  name: 'A5',  type: 'io' },
      { pin: 7,  name: 'A6',  type: 'io' },
      { pin: 8,  name: 'A7',  type: 'io' },
      { pin: 9,  name: 'A8',  type: 'io' },
      { pin: 10, name: 'GND', type: 'power' },
      { pin: 11, name: 'B8',  type: 'io' },
      { pin: 12, name: 'B7',  type: 'io' },
      { pin: 13, name: 'B6',  type: 'io' },
      { pin: 14, name: 'B5',  type: 'io' },
      { pin: 15, name: 'B4',  type: 'io' },
      { pin: 16, name: 'B3',  type: 'io' },
      { pin: 17, name: 'B2',  type: 'io' },
      { pin: 18, name: 'B1',  type: 'io' },
      { pin: 19, name: 'OEn', type: 'input' },
      { pin: 20, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'TRANSCEIVER_8BIT',
        inputs:  ['A1','A2','A3','A4','A5','A6','A7','A8',
                  'B1','B2','B3','B4','B5','B6','B7','B8','DIR','OEn'],
        outputs: ['A1','A2','A3','A4','A5','A6','A7','A8',
                  'B1','B2','B3','B4','B5','B6','B7','B8'] },
    ],
  },

  // ── 74624: Voltage-Controlled Oscillator (analog stub) ────────────────────
  /* Primary source: Texas Instruments, 74624 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls624.pdf
     https://en.wikipedia.org/wiki/Electronic_oscillator */
  '74624': {
    name: '74x624',
    simpleName: 'VCO Single',
    description: 'Voltage-controlled oscillator with enable, range, and two-phase outputs (14-pin)',
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls624.pdf',
    tags: ['vco', 'oscillator', 'analog', 'stub'],
    guideOverview: 'The 74x624 is a voltage-controlled oscillator (VCO). An analog voltage on FREQ1/FREQ2 controls the output frequency; RNG selects a coarse frequency range; OE (active LOW) enables the two complementary outputs (OUT and OUTn). This is an analog device the simulator outputs a fixed logic level stub.',
    guidePinDescriptions: {
      'FREQ1': 'Frequency control input 1 (analog voltage).',
      'FREQ2': 'Frequency control input 2 (analog voltage).',
      'RNG':   'Range select. Selects one of several frequency bands.',
      'OEn':   'Output Enable (active LOW).',
      'OUT':   'Oscillator output.',
      'OUTn':  'Complementary oscillator output.',
      'GND':   'Ground reference (pin 7).',
      'FSEL':  'Frequency select.',
      'AIN1':  'Analog input 1.',
      'AIN2':  'Analog input 2.',
      'AIN3':  'Analog input 3.',
      'AIN4':  'Analog input 4.',
      'SYNC':  'Sync input for phase locking.',
      'VCC':   'Positive supply (+5 V, pin 14).',
    },
    guideSections: [
      {
        title: 'Voltage-Controlled Oscillator',
        paragraphs: [
          'A VCO produces a digital clock whose frequency is proportional to an analog control voltage. Typical applications include phase-locked loops (PLLs), frequency synthesizers, and clock generators.',
        ],
        note: 'Not simulatable as a digital component. The simulator outputs a stub.',
      },
    ],
    pinout: [
      { pin: 1,  name: 'FREQ1', type: 'input' },
      { pin: 2,  name: 'FREQ2', type: 'input' },
      { pin: 3,  name: 'RNG',   type: 'input' },
      { pin: 4,  name: 'OEn',   type: 'input' },
      { pin: 5,  name: 'OUT',   type: 'output' },
      { pin: 6,  name: 'OUTn',  type: 'output' },
      { pin: 7,  name: 'GND',   type: 'power' },
      { pin: 8,  name: 'FSEL',  type: 'input' },
      { pin: 9,  name: 'AIN1',  type: 'input' },
      { pin: 10, name: 'AIN2',  type: 'input' },
      { pin: 11, name: 'AIN3',  type: 'input' },
      { pin: 12, name: 'AIN4',  type: 'input' },
      { pin: 13, name: 'SYNC',  type: 'input' },
      { pin: 14, name: 'VCC',   type: 'power' },
    ],
    gates: [
      { type: 'VCO_STUB',
        inputs:  ['OEn'],
        outputs: ['OUT', 'OUTn'] },
    ],
  },

  // ── 74625: Dual VCO ────────────────────────────────────────────────────────
  /* Primary source: Texas Instruments, 74625 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls625.pdf
     https://en.wikipedia.org/wiki/Electronic_oscillator */
  '74625': {
    name: '74x625',
    simpleName: 'Dual VCO',
    description: 'Dual voltage-controlled oscillator with two-phase outputs (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls625.pdf',
    tags: ['vco', 'oscillator', 'analog', 'dual', 'stub'],
    guideOverview: 'The 74x625 contains two independent voltage-controlled oscillators in a single 16-pin package. Each VCO has separate FREQ1/FREQ2 and RNG control inputs and complementary outputs. Useful when two independent clock sources are needed on the same board.',
    guidePinDescriptions: {
      'FREQ1A': 'Frequency control 1 for VCO A.',
      'FREQ2A': 'Frequency control 2 for VCO A.',
      'RNGA':   'Range select for VCO A.',
      'OUTA':   'Output of VCO A.',
      'OUTnA':  'Complementary output of VCO A.',
      'OUTB':   'Output of VCO B.',
      'OUTnB':  'Complementary output of VCO B.',
      'GND':    'Ground reference (pin 8).',
      'FREQ1B': 'Frequency control 1 for VCO B.',
      'FREQ2B': 'Frequency control 2 for VCO B.',
      'RNGB':   'Range select for VCO B.',
      'AIN1':   'Analog input 1.',
      'AIN2':   'Analog input 2.',
      'AIN3':   'Analog input 3.',
      'AIN4':   'Analog input 4.',
      'VCC':    'Positive supply (+5 V, pin 16).',
    },
    guideSections: [
      {
        title: 'Dual VCO',
        paragraphs: [
          'The 74x625 integrates two VCOs, reducing board space compared to two 74x624 chips. Both VCOs are analog and not simulatable.',
        ],
        note: 'Analog device simulator outputs a stub only.',
      },
    ],
    pinout: [
      { pin: 1,  name: 'FREQ1A', type: 'input' },
      { pin: 2,  name: 'FREQ2A', type: 'input' },
      { pin: 3,  name: 'RNGA',   type: 'input' },
      { pin: 4,  name: 'OUTA',   type: 'output' },
      { pin: 5,  name: 'OUTnA',  type: 'output' },
      { pin: 6,  name: 'OUTB',   type: 'output' },
      { pin: 7,  name: 'OUTnB',  type: 'output' },
      { pin: 8,  name: 'GND',    type: 'power' },
      { pin: 9,  name: 'FREQ1B', type: 'input' },
      { pin: 10, name: 'FREQ2B', type: 'input' },
      { pin: 11, name: 'RNGB',   type: 'input' },
      { pin: 12, name: 'AIN1',   type: 'input' },
      { pin: 13, name: 'AIN2',   type: 'input' },
      { pin: 14, name: 'AIN3',   type: 'input' },
      { pin: 15, name: 'AIN4',   type: 'input' },
      { pin: 16, name: 'VCC',    type: 'power' },
    ],
    gates: [
      { type: 'VCO_STUB', inputs: [], outputs: ['OUTA', 'OUTnA'] },
      { type: 'VCO_STUB', inputs: [], outputs: ['OUTB', 'OUTnB'] },
    ],
  },

  // ── 74626: Dual VCO with enable ───────────────────────────────────────────
  /* Primary source: Texas Instruments, 74626 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls626.pdf
     https://en.wikipedia.org/wiki/Electronic_oscillator */
  '74626': {
    name: '74x626',
    simpleName: 'Dual VCO (EN)',
    description: 'Dual voltage-controlled oscillator with enable control and two-phase outputs (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls626.pdf',
    tags: ['vco', 'oscillator', 'analog', 'dual', 'enable', 'stub'],
    guideOverview: 'The 74x626 is a dual VCO with per-section enable pins (OEnA, OEnB). Each VCO has independent FREQ1/FREQ2 controls. The enable pins allow the outputs to be disabled without removing power, useful in frequency-switching applications.',
    guidePinDescriptions: {
      'FREQ1A': 'Frequency control 1 for VCO A.',
      'FREQ2A': 'Frequency control 2 for VCO A.',
      'OEnA':   'Output Enable for VCO A (active LOW).',
      'OUTA':   'Output of VCO A.',
      'OUTnA':  'Complementary output of VCO A.',
      'OUTB':   'Output of VCO B.',
      'OUTnB':  'Complementary output of VCO B.',
      'GND':    'Ground reference (pin 8).',
      'OEnB':   'Output Enable for VCO B (active LOW).',
      'FREQ1B': 'Frequency control 1 for VCO B.',
      'FREQ2B': 'Frequency control 2 for VCO B.',
      'AIN1':   'Analog input 1.',
      'AIN2':   'Analog input 2.',
      'AIN3':   'Analog input 3.',
      'AIN4':   'Analog input 4.',
      'VCC':    'Positive supply (+5 V, pin 16).',
    },
    guideSections: [
      {
        title: 'Dual VCO with Enable',
        paragraphs: [
          'Adding OEn to each VCO section allows dynamic selection of which oscillator drives the output bus, useful in PLLs that switch between reference and feedback paths.',
        ],
        note: 'Analog device simulator outputs a stub only.',
      },
    ],
    pinout: [
      { pin: 1,  name: 'FREQ1A', type: 'input' },
      { pin: 2,  name: 'FREQ2A', type: 'input' },
      { pin: 3,  name: 'OEnA',   type: 'input' },
      { pin: 4,  name: 'OUTA',   type: 'output' },
      { pin: 5,  name: 'OUTnA',  type: 'output' },
      { pin: 6,  name: 'OUTB',   type: 'output' },
      { pin: 7,  name: 'OUTnB',  type: 'output' },
      { pin: 8,  name: 'GND',    type: 'power' },
      { pin: 9,  name: 'OEnB',   type: 'input' },
      { pin: 10, name: 'FREQ1B', type: 'input' },
      { pin: 11, name: 'FREQ2B', type: 'input' },
      { pin: 12, name: 'AIN1',   type: 'input' },
      { pin: 13, name: 'AIN2',   type: 'input' },
      { pin: 14, name: 'AIN3',   type: 'input' },
      { pin: 15, name: 'AIN4',   type: 'input' },
      { pin: 16, name: 'VCC',    type: 'power' },
    ],
    gates: [
      { type: 'VCO_STUB', inputs: ['OEnA'], outputs: ['OUTA', 'OUTnA'] },
      { type: 'VCO_STUB', inputs: ['OEnB'], outputs: ['OUTB', 'OUTnB'] },
    ],
  },

  // ── 74627: Dual VCO (no enable) ───────────────────────────────────────────
  /* Primary source: Texas Instruments, 74627 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls627.pdf
     https://en.wikipedia.org/wiki/Electronic_oscillator */
  '74627': {
    name: '74x627',
    simpleName: 'Dual VCO',
    description: 'Dual voltage-controlled oscillator with two-phase outputs (14-pin)',
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls627.pdf',
    tags: ['vco', 'oscillator', 'analog', 'dual', 'stub'],
    guideOverview: 'The 74x627 is a dual VCO in a 14-pin package (vs the 74x625 in 16-pin). It has two independent VCO sections with FREQ1/FREQ2 frequency control inputs and complementary outputs. No enable pin is provided. Analog device not simulatable.',
    guidePinDescriptions: {
      'FREQ1A': 'Frequency control 1 for VCO A.',
      'FREQ2A': 'Frequency control 2 for VCO A.',
      'OUTA':   'Output of VCO A.',
      'OUTnA':  'Complementary output of VCO A.',
      'OUTB':   'Output of VCO B.',
      'OUTnB':  'Complementary output of VCO B.',
      'GND':    'Ground reference (pin 7).',
      'FREQ1B': 'Frequency control 1 for VCO B.',
      'FREQ2B': 'Frequency control 2 for VCO B.',
      'AIN1':   'Analog input 1.',
      'AIN2':   'Analog input 2.',
      'AIN3':   'Analog input 3.',
      'AIN4':   'Analog input 4.',
      'VCC':    'Positive supply (+5 V, pin 14).',
    },
    guideSections: [
      {
        title: '74x625 vs 74x627',
        paragraphs: [
          '74x625 is 16-pin; 74x627 is 14-pin. The 74x625 adds a RNG (range) pin per section. Choose 74x627 when RNG is not needed and package size is critical.',
        ],
        note: 'Analog device simulator outputs a stub only.',
      },
    ],
    pinout: [
      { pin: 1,  name: 'FREQ1A', type: 'input' },
      { pin: 2,  name: 'FREQ2A', type: 'input' },
      { pin: 3,  name: 'OUTA',   type: 'output' },
      { pin: 4,  name: 'OUTnA',  type: 'output' },
      { pin: 5,  name: 'OUTB',   type: 'output' },
      { pin: 6,  name: 'OUTnB',  type: 'output' },
      { pin: 7,  name: 'GND',    type: 'power' },
      { pin: 8,  name: 'FREQ1B', type: 'input' },
      { pin: 9,  name: 'FREQ2B', type: 'input' },
      { pin: 10, name: 'AIN1',   type: 'input' },
      { pin: 11, name: 'AIN2',   type: 'input' },
      { pin: 12, name: 'AIN3',   type: 'input' },
      { pin: 13, name: 'AIN4',   type: 'input' },
      { pin: 14, name: 'VCC',    type: 'power' },
    ],
    gates: [
      { type: 'VCO_STUB', inputs: [], outputs: ['OUTA', 'OUTnA'] },
      { type: 'VCO_STUB', inputs: [], outputs: ['OUTB', 'OUTnB'] },
    ],
  },

  // ── 74628: VCO with enable, range, external temp compensation ─────────────
  /* Primary source: Texas Instruments, 74628 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls628.pdf
     https://en.wikipedia.org/wiki/Electronic_oscillator */
  '74628': {
    name: '74x628',
    simpleName: 'VCO Single (Ext)',
    description: 'Voltage-controlled oscillator with enable, range, external temp compensation (14-pin)',
    pins: 14,
    vcc: 14,
    gnd: 7,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls628.pdf',
    tags: ['vco', 'oscillator', 'analog', 'stub'],
    guideOverview: 'The 74x628 is a single VCO with external temperature compensation (TC pin). It adds a TC pin for connecting an external NTC/PTC thermistor network to compensate for frequency drift with temperature. Otherwise functionally similar to the 74x624 with OEn enable and complementary outputs.',
    guidePinDescriptions: {
      'FREQ1': 'Frequency control input 1.',
      'FREQ2': 'Frequency control input 2.',
      'RNG':   'Range select.',
      'OEn':   'Output Enable (active LOW).',
      'OUT':   'Oscillator output.',
      'OUTn':  'Complementary output.',
      'GND':   'Ground reference (pin 7).',
      'TC':    'Temperature compensation input.',
      'AIN1':  'Analog input 1.',
      'AIN2':  'Analog input 2.',
      'AIN3':  'Analog input 3.',
      'AIN4':  'Analog input 4.',
      'SYNC':  'Sync input.',
      'VCC':   'Positive supply (+5 V, pin 14).',
    },
    guideSections: [
      {
        title: '74x624 vs 74x628',
        paragraphs: [
          '74x628 adds a TC (temperature compensation) pin to the 74x624 for improved frequency stability over temperature using an external component network.',
        ],
        note: 'Analog device simulator outputs a stub only.',
      },
    ],
    pinout: [
      { pin: 1,  name: 'FREQ1', type: 'input' },
      { pin: 2,  name: 'FREQ2', type: 'input' },
      { pin: 3,  name: 'RNG',   type: 'input' },
      { pin: 4,  name: 'OEn',   type: 'input' },
      { pin: 5,  name: 'OUT',   type: 'output' },
      { pin: 6,  name: 'OUTn',  type: 'output' },
      { pin: 7,  name: 'GND',   type: 'power' },
      { pin: 8,  name: 'TC',    type: 'input' },
      { pin: 9,  name: 'AIN1',  type: 'input' },
      { pin: 10, name: 'AIN2',  type: 'input' },
      { pin: 11, name: 'AIN3',  type: 'input' },
      { pin: 12, name: 'AIN4',  type: 'input' },
      { pin: 13, name: 'SYNC',  type: 'input' },
      { pin: 14, name: 'VCC',   type: 'power' },
    ],
    gates: [
      { type: 'VCO_STUB', inputs: ['OEn'], outputs: ['OUT', 'OUTn'] },
    ],
  },

  // ── 74629: Dual VCO with enable and range control ────────────────────────
  /* Primary source: Texas Instruments, 74629 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls629.pdf
     https://en.wikipedia.org/wiki/Electronic_oscillator */
  '74629': {
    name: '74x629',
    simpleName: 'Dual VCO (EN+RNG)',
    description: 'Dual voltage-controlled oscillator with enable and range control (16-pin)',
    pins: 16,
    vcc: 16,
    gnd: 8,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls629.pdf',
    tags: ['vco', 'oscillator', 'analog', 'dual', 'enable', 'stub'],
    guideOverview: 'The 74x629 is a dual VCO with both enable (OEn) and range (RNG) control per section. It is the most feature-complete of the VCO family combining the enable of 74x626 with the range select of 74x625. Analog device, not simulatable.',
    guidePinDescriptions: {
      'FREQ1A': 'Frequency control 1 for VCO A.',
      'FREQ2A': 'Frequency control 2 for VCO A.',
      'RNGA':   'Range select for VCO A.',
      'OEnA':   'Output Enable for VCO A (active LOW).',
      'OUTA':   'Output of VCO A.',
      'OUTnA':  'Complementary output of VCO A.',
      'OUTB':   'Output of VCO B.',
      'GND':    'Ground reference (pin 8).',
      'OUTnB':  'Complementary output of VCO B.',
      'OEnB':   'Output Enable for VCO B (active LOW).',
      'RNGB':   'Range select for VCO B.',
      'FREQ1B': 'Frequency control 1 for VCO B.',
      'FREQ2B': 'Frequency control 2 for VCO B.',
      'AIN1':   'Analog input 1.',
      'AIN2':   'Analog input 2.',
      'VCC':    'Positive supply (+5 V, pin 16).',
    },
    guideSections: [
      {
        title: 'VCO Family Comparison',
        list: [
          '74x624/628: single VCO, enable + range (628 adds temp comp)',
          '74x625/627: dual VCO, range only (627 is smaller package)',
          '74x626: dual VCO, enable only',
          '74x629: dual VCO, enable + range (most complete)',
        ],
        note: 'Analog device simulator outputs a stub only.',
      },
    ],
    pinout: [
      { pin: 1,  name: 'FREQ1A', type: 'input' },
      { pin: 2,  name: 'FREQ2A', type: 'input' },
      { pin: 3,  name: 'RNGA',   type: 'input' },
      { pin: 4,  name: 'OEnA',   type: 'input' },
      { pin: 5,  name: 'OUTA',   type: 'output' },
      { pin: 6,  name: 'OUTnA',  type: 'output' },
      { pin: 7,  name: 'OUTB',   type: 'output' },
      { pin: 8,  name: 'GND',    type: 'power' },
      { pin: 9,  name: 'OUTnB',  type: 'output' },
      { pin: 10, name: 'OEnB',   type: 'input' },
      { pin: 11, name: 'RNGB',   type: 'input' },
      { pin: 12, name: 'FREQ1B', type: 'input' },
      { pin: 13, name: 'FREQ2B', type: 'input' },
      { pin: 14, name: 'AIN1',   type: 'input' },
      { pin: 15, name: 'AIN2',   type: 'input' },
      { pin: 16, name: 'VCC',    type: 'power' },
    ],
    gates: [
      { type: 'VCO_STUB', inputs: ['OEnA'], outputs: ['OUTA', 'OUTnA'] },
      { type: 'VCO_STUB', inputs: ['OEnB'], outputs: ['OUTB', 'OUTnB'] },
    ],
  },

  // ── 74636: 8 bit ECC (TRI) ────────────────────────────────────────────────
  /* Primary source: Texas Instruments, 74636 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls636.pdf */
  // Error detection and correction not simulatable. Stub: drives all HiZ.
  '74636': {
    name: '74x636',
    simpleName: '8 bit ECC (TS)',
    description: '8 bit parallel error detection and correction with tri-state outputs (20-pin)',
    pins: 20,
    vcc: 20,
    gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls636.pdf',
    tags: ['ecc', 'error-correction', 'parity', 'stub'],
    guideOverview: 'The 74x636 is an 8 bit parallel error detection and correction (SECDED) circuit with tri-state outputs. It generates and checks 7 check bits (CB0-CB6) for 8 data bits, detecting and correcting single-bit errors. fE indicates an uncorrectable double-bit error. OEn and SEn control output enables. This is too complex to simulate digitally stub only.',
    guidePinDescriptions: {
      'D0':  'Data bit 0.',
      'D1':  'Data bit 1.',
      'D2':  'Data bit 2.',
      'D3':  'Data bit 3.',
      'D4':  'Data bit 4.',
      'D5':  'Data bit 5.',
      'D6':  'Data bit 6.',
      'D7':  'Data bit 7.',
      'CB0': 'Check bit 0.',
      'GND': 'Ground reference (pin 10).',
      'CB1': 'Check bit 1.',
      'CB2': 'Check bit 2.',
      'CB3': 'Check bit 3.',
      'CB4': 'Check bit 4.',
      'CB5': 'Check bit 5.',
      'CB6': 'Check bit 6.',
      'fE':  'Fatal Error output. HIGH = uncorrectable error detected.',
      'OEn': 'Output Enable (active LOW).',
      'SEn': 'Syndrome Enable (active LOW). Enables syndrome logic.',
      'VCC': 'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'SECDED Error Correction',
        paragraphs: [
          'SECDED (Single Error Correct, Double Error Detect) uses Hamming code extended with a parity bit. The 74x636 implements this for 8 bit memory bytes, generating and checking 7 check bits per byte.',
        ],
        note: 'Digital simulator stub only actual ECC logic is not simulated.',
      },
    ],
    pinout: [
      { pin: 1,  name: 'D0',  type: 'io' },
      { pin: 2,  name: 'D1',  type: 'io' },
      { pin: 3,  name: 'D2',  type: 'io' },
      { pin: 4,  name: 'D3',  type: 'io' },
      { pin: 5,  name: 'D4',  type: 'io' },
      { pin: 6,  name: 'D5',  type: 'io' },
      { pin: 7,  name: 'D6',  type: 'io' },
      { pin: 8,  name: 'D7',  type: 'io' },
      { pin: 9,  name: 'CB0', type: 'io' },
      { pin: 10, name: 'GND', type: 'power' },
      { pin: 11, name: 'CB1', type: 'io' },
      { pin: 12, name: 'CB2', type: 'io' },
      { pin: 13, name: 'CB3', type: 'io' },
      { pin: 14, name: 'CB4', type: 'io' },
      { pin: 15, name: 'CB5', type: 'io' },
      { pin: 16, name: 'CB6', type: 'io' },
      { pin: 17, name: 'fE',  type: 'output' },
      { pin: 18, name: 'OEn', type: 'input' },
      { pin: 19, name: 'SEn', type: 'input' },
      { pin: 20, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'ECC_STUB',
        inputs:  ['OEn', 'SEn', 'D0','D1','D2','D3','D4','D5','D6','D7',
                  'CB0','CB1','CB2','CB3','CB4','CB5','CB6'],
        outputs: ['D0','D1','D2','D3','D4','D5','D6','D7',
                  'CB0','CB1','CB2','CB3','CB4','CB5','CB6', 'fE'] },
    ],
  },

  // ── 74637: 8 bit ECC (OC) ────────────────────────────────────────────────
  /* Primary source: Texas Instruments, 74637 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls637.pdf */
  '74637': {
    name: '74x637',
    simpleName: '8 bit ECC (OC)',
    description: '8 bit parallel error detection and correction with open-collector outputs (20-pin)',
    pins: 20,
    vcc: 20,
    gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls637.pdf',
    tags: ['ecc', 'error-correction', 'parity', 'open-collector', 'stub'],
    guideOverview: 'The 74x637 is the open-collector version of the 74x636 SECDED ECC chip. Identical function (8 bit data + 7 check bits, single-error correct, double-error detect) but with OC outputs that require pull up resistors. OC allows wire-OR of the error-flag lines in multi-bank ECC memory designs.',
    guidePinDescriptions: {
      'D0':  'Data bit 0.',
      'D1':  'Data bit 1.',
      'D2':  'Data bit 2.',
      'D3':  'Data bit 3.',
      'D4':  'Data bit 4.',
      'D5':  'Data bit 5.',
      'D6':  'Data bit 6.',
      'D7':  'Data bit 7.',
      'CB0': 'Check bit 0.',
      'GND': 'Ground reference (pin 10).',
      'CB1': 'Check bit 1.',
      'CB2': 'Check bit 2.',
      'CB3': 'Check bit 3.',
      'CB4': 'Check bit 4.',
      'CB5': 'Check bit 5.',
      'CB6': 'Check bit 6.',
      'fE':  'Fatal Error output (OC).',
      'OEn': 'Output Enable (active LOW).',
      'SEn': 'Syndrome Enable (active LOW).',
      'VCC': 'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: '74x636 vs 74x637',
        paragraphs: [
          '74x636 has tri-state outputs; 74x637 has open-collector. Use 74x637 when the fE flag needs to be wire-OR’d across multiple ECC chips in a memory system.',
        ],
        note: 'Digital simulator stub only.',
      },
    ],
    pinout: [
      { pin: 1,  name: 'D0',  type: 'io' },
      { pin: 2,  name: 'D1',  type: 'io' },
      { pin: 3,  name: 'D2',  type: 'io' },
      { pin: 4,  name: 'D3',  type: 'io' },
      { pin: 5,  name: 'D4',  type: 'io' },
      { pin: 6,  name: 'D5',  type: 'io' },
      { pin: 7,  name: 'D6',  type: 'io' },
      { pin: 8,  name: 'D7',  type: 'io' },
      { pin: 9,  name: 'CB0', type: 'io' },
      { pin: 10, name: 'GND', type: 'power' },
      { pin: 11, name: 'CB1', type: 'io' },
      { pin: 12, name: 'CB2', type: 'io' },
      { pin: 13, name: 'CB3', type: 'io' },
      { pin: 14, name: 'CB4', type: 'io' },
      { pin: 15, name: 'CB5', type: 'io' },
      { pin: 16, name: 'CB6', type: 'io' },
      { pin: 17, name: 'fE',  type: 'output' },
      { pin: 18, name: 'OEn', type: 'input' },
      { pin: 19, name: 'SEn', type: 'input' },
      { pin: 20, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'ECC_STUB',
        inputs:  ['OEn', 'SEn', 'D0','D1','D2','D3','D4','D5','D6','D7',
                  'CB0','CB1','CB2','CB3','CB4','CB5','CB6'],
        outputs: ['D0','D1','D2','D3','D4','D5','D6','D7',
                  'CB0','CB1','CB2','CB3','CB4','CB5','CB6', 'fE'] },
    ],
  },

  // ── 74638: Octal bus transceiver, inverting, TRI+OC mixed ────────────────
  /* Primary source: Texas Instruments, 74638 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls638.pdf
     https://en.wikipedia.org/wiki/Bus_transceiver */
  // A-side: TRI outputs. B-side: OC outputs. Inverting.
  // Model as 74620 (TRANSCEIVER_8BIT_INV).
  '74638': {
    name: '74x638',
    simpleName: 'Octal Xcvr Inv (TS/OC)',
    description: 'Octal bus transceiver with inverting outputs (tri-state A-side, OC B-side) (20-pin)',
    pins: 20,
    vcc: 20,
    gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls638.pdf',
    tags: ['transceiver', 'bus', 'octal', 'tri-state', 'open-collector', 'bidirectional', 'inverting'],
    guideOverview: 'The 74x638 is an 8 bit inverting bidirectional transceiver where the A-side outputs are tri-state and the B-side outputs are open-collector. This mixed output structure was designed for interfacing between a tri-state bus (e.g., CPU bus) and an open-collector bus (e.g., legacy TTL bus).',
    guidePinDescriptions: {
      'DIR': 'Direction. HIGH = A (TRI) drives inverted B (OC); LOW = B drives inverted A.',
      'A1':  'Port A bit 1 (tri-state).',
      'A2':  'Port A bit 2.',
      'A3':  'Port A bit 3.',
      'A4':  'Port A bit 4.',
      'A5':  'Port A bit 5.',
      'A6':  'Port A bit 6.',
      'A7':  'Port A bit 7.',
      'A8':  'Port A bit 8.',
      'GND': 'Ground reference (pin 10).',
      'B8':  'Port B bit 8 (open-collector).',
      'B7':  'Port B bit 7.',
      'B6':  'Port B bit 6.',
      'B5':  'Port B bit 5.',
      'B4':  'Port B bit 4.',
      'B3':  'Port B bit 3.',
      'B2':  'Port B bit 2.',
      'B1':  'Port B bit 1.',
      'OEn': 'Output Enable (active LOW).',
      'VCC': 'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: 'Mixed TRI/OC Output Transceiver',
        paragraphs: [
          'The A-side tri-state interface suits modern buses; the B-side OC interface suits wire-OR legacy buses. The inverting output handles active LOW bus conventions.',
        ],
        note: 'B-side outputs require external pull up resistors.',
      },
    ],
    pinout: [
      { pin: 1,  name: 'DIR', type: 'input' },
      { pin: 2,  name: 'A1',  type: 'io' },
      { pin: 3,  name: 'A2',  type: 'io' },
      { pin: 4,  name: 'A3',  type: 'io' },
      { pin: 5,  name: 'A4',  type: 'io' },
      { pin: 6,  name: 'A5',  type: 'io' },
      { pin: 7,  name: 'A6',  type: 'io' },
      { pin: 8,  name: 'A7',  type: 'io' },
      { pin: 9,  name: 'A8',  type: 'io' },
      { pin: 10, name: 'GND', type: 'power' },
      { pin: 11, name: 'B8',  type: 'io' },
      { pin: 12, name: 'B7',  type: 'io' },
      { pin: 13, name: 'B6',  type: 'io' },
      { pin: 14, name: 'B5',  type: 'io' },
      { pin: 15, name: 'B4',  type: 'io' },
      { pin: 16, name: 'B3',  type: 'io' },
      { pin: 17, name: 'B2',  type: 'io' },
      { pin: 18, name: 'B1',  type: 'io' },
      { pin: 19, name: 'OEn', type: 'input' },
      { pin: 20, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'TRANSCEIVER_8BIT_INV',
        inputs:  ['A1','A2','A3','A4','A5','A6','A7','A8',
                  'B1','B2','B3','B4','B5','B6','B7','B8','DIR','OEn'],
        outputs: ['A1','A2','A3','A4','A5','A6','A7','A8',
                  'B1','B2','B3','B4','B5','B6','B7','B8'] },
    ],
  },

  // ── 74639: Octal bus transceiver, non-inverting, TRI+OC mixed ────────────
  /* Primary source: Texas Instruments, 74639 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls639.pdf
     https://en.wikipedia.org/wiki/Bus_transceiver */
  '74639': {
    name: '74x639',
    simpleName: 'Octal Xcvr (TS/OC)',
    description: 'Octal bus transceiver with non-inverting outputs (tri-state A-side, OC B-side) (20-pin)',
    pins: 20,
    vcc: 20,
    gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls639.pdf',
    tags: ['transceiver', 'bus', 'octal', 'tri-state', 'open-collector', 'bidirectional'],
    guideOverview: 'The 74x639 is an 8 bit non-inverting bidirectional transceiver with mixed outputs: A-side is tri-state, B-side is open-collector. Same DIR/OEn interface as the 74x638 but without output inversion. For non-inverting mixed-output bus bridging.',
    guidePinDescriptions: {
      'DIR': 'Direction. HIGH = A (TRI) drives B (OC); LOW = B drives A.',
      'A1':  'Port A bit 1.',
      'A2':  'Port A bit 2.',
      'A3':  'Port A bit 3.',
      'A4':  'Port A bit 4.',
      'A5':  'Port A bit 5.',
      'A6':  'Port A bit 6.',
      'A7':  'Port A bit 7.',
      'A8':  'Port A bit 8.',
      'GND': 'Ground reference (pin 10).',
      'B8':  'Port B bit 8 (open-collector).',
      'B7':  'Port B bit 7.',
      'B6':  'Port B bit 6.',
      'B5':  'Port B bit 5.',
      'B4':  'Port B bit 4.',
      'B3':  'Port B bit 3.',
      'B2':  'Port B bit 2.',
      'B1':  'Port B bit 1.',
      'OEn': 'Output Enable (active LOW).',
      'VCC': 'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: '74x638 vs 74x639',
        paragraphs: [
          '74x638 inverts data through the transceiver; 74x639 passes data non-inverted. Both have TRI A-side and OC B-side.',
        ],
      },
    ],
    pinout: [
      { pin: 1,  name: 'DIR', type: 'input' },
      { pin: 2,  name: 'A1',  type: 'io' },
      { pin: 3,  name: 'A2',  type: 'io' },
      { pin: 4,  name: 'A3',  type: 'io' },
      { pin: 5,  name: 'A4',  type: 'io' },
      { pin: 6,  name: 'A5',  type: 'io' },
      { pin: 7,  name: 'A6',  type: 'io' },
      { pin: 8,  name: 'A7',  type: 'io' },
      { pin: 9,  name: 'A8',  type: 'io' },
      { pin: 10, name: 'GND', type: 'power' },
      { pin: 11, name: 'B8',  type: 'io' },
      { pin: 12, name: 'B7',  type: 'io' },
      { pin: 13, name: 'B6',  type: 'io' },
      { pin: 14, name: 'B5',  type: 'io' },
      { pin: 15, name: 'B4',  type: 'io' },
      { pin: 16, name: 'B3',  type: 'io' },
      { pin: 17, name: 'B2',  type: 'io' },
      { pin: 18, name: 'B1',  type: 'io' },
      { pin: 19, name: 'OEn', type: 'input' },
      { pin: 20, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'TRANSCEIVER_8BIT',
        inputs:  ['A1','A2','A3','A4','A5','A6','A7','A8',
                  'B1','B2','B3','B4','B5','B6','B7','B8','DIR','OEn'],
        outputs: ['A1','A2','A3','A4','A5','A6','A7','A8',
                  'B1','B2','B3','B4','B5','B6','B7','B8'] },
    ],
  },

  // ── 74640: Octal bus transceiver, inverting, TRI ──────────────────────────
  /* Primary source: Texas Instruments, 74640 datasheet. [Online]. Available: https://www.ti.com/lit/ds/symlink/sn74ls640.pdf
     https://en.wikipedia.org/wiki/Bus_transceiver */
  // Like 74620. Reuse TRANSCEIVER_8BIT_INV.
  '74640': {
    name: '74x640',
    simpleName: 'Octal Xcvr Inv (TS)',
    description: 'Octal bus transceiver with inverting tri-state outputs (20-pin)',
    pins: 20,
    vcc: 20,
    gnd: 10,
    datasheet: 'https://www.ti.com/lit/ds/symlink/sn74ls640.pdf',
    tags: ['transceiver', 'bus', 'octal', 'tri-state', 'bidirectional', 'inverting'],
    guideOverview: 'The 74x640 is an 8 bit bidirectional inverting bus transceiver with tri-state outputs, functionally equivalent to the 74x620. DIR controls direction and OEn enables the outputs. Data is inverted as it passes through in either direction.',
    guidePinDescriptions: {
      'DIR': 'Direction. HIGH = A drives inverted B; LOW = B drives inverted A.',
      'A1':  'Port A bit 1.',
      'A2':  'Port A bit 2.',
      'A3':  'Port A bit 3.',
      'A4':  'Port A bit 4.',
      'A5':  'Port A bit 5.',
      'A6':  'Port A bit 6.',
      'A7':  'Port A bit 7.',
      'A8':  'Port A bit 8.',
      'GND': 'Ground reference (pin 10).',
      'B8':  'Port B bit 8.',
      'B7':  'Port B bit 7.',
      'B6':  'Port B bit 6.',
      'B5':  'Port B bit 5.',
      'B4':  'Port B bit 4.',
      'B3':  'Port B bit 3.',
      'B2':  'Port B bit 2.',
      'B1':  'Port B bit 1.',
      'OEn': 'Output Enable (active LOW).',
      'VCC': 'Positive supply (+5 V, pin 20).',
    },
    guideSections: [
      {
        title: '74x620 vs 74x640',
        paragraphs: [
          'Both 74x620 and 74x640 are inverting tri-state bidirectional transceivers. They are functionally identical; the part number difference reflects the logic family or manufacturer variant.',
        ],
      },
    ],
    pinout: [
      { pin: 1,  name: 'DIR', type: 'input' },
      { pin: 2,  name: 'A1',  type: 'io' },
      { pin: 3,  name: 'A2',  type: 'io' },
      { pin: 4,  name: 'A3',  type: 'io' },
      { pin: 5,  name: 'A4',  type: 'io' },
      { pin: 6,  name: 'A5',  type: 'io' },
      { pin: 7,  name: 'A6',  type: 'io' },
      { pin: 8,  name: 'A7',  type: 'io' },
      { pin: 9,  name: 'A8',  type: 'io' },
      { pin: 10, name: 'GND', type: 'power' },
      { pin: 11, name: 'B8',  type: 'io' },
      { pin: 12, name: 'B7',  type: 'io' },
      { pin: 13, name: 'B6',  type: 'io' },
      { pin: 14, name: 'B5',  type: 'io' },
      { pin: 15, name: 'B4',  type: 'io' },
      { pin: 16, name: 'B3',  type: 'io' },
      { pin: 17, name: 'B2',  type: 'io' },
      { pin: 18, name: 'B1',  type: 'io' },
      { pin: 19, name: 'OEn', type: 'input' },
      { pin: 20, name: 'VCC', type: 'power' },
    ],
    gates: [
      { type: 'TRANSCEIVER_8BIT_INV',
        inputs:  ['A1','A2','A3','A4','A5','A6','A7','A8',
                  'B1','B2','B3','B4','B5','B6','B7','B8','DIR','OEn'],
        outputs: ['A1','A2','A3','A4','A5','A6','A7','A8',
                  'B1','B2','B3','B4','B5','B6','B7','B8'] },
    ],
  },

};
